### ISSUE TITLE
GStreamer plugin for Opus files don’t work

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#1000]
Lollypop-Flatpack cannot play/see(?)/access(?) Opus files. According to gnumdk/lollypop#1209, this issue is caused by org.gnome.Platform.

**Comment by alexlarsson** [comment]
Yes, opus is not in the current runtime. Individual apps can add it if they want.
It will be in the gnome 3.26 runtime though.

**Comment by fbruetting** [comment]
Thanks! So with 3.26 it will work without further ado? Or does the Lollypop maintainer have to add it manually then?

**Comment by gnumdk** [comment]
3.26 is coming soon so you will have to wait ;)

**Comment by alexlarsson** [comment]
The maintainer will need to switch to the new runtime when its available.

**Comment by nedrichards** [comment]
Lollypop on flathub [now uses the GNOME 3.26](https://github.com/flathub/org.gnome.Lollypop/blob/master/org.gnome.Lollypop.json) runtime.
