### ISSUE TITLE
SRU Flatpak releases in Ubuntu

### ISSUE THREAD

**Issue by Ads20000** [flatpak/flatpak#1001]
[As Joe Sneddon of OMG! Ubuntu! says](https://disqus.com/home/discussion/omgubuntu/ahoy_flathub_website_now_lets_you_install_apps/#comment-3505492180), it's annoying that at the moment one has to add a PPA to use a universal packaging format which should do away with PPAs and the like... Would it be possible (even though it is a rather involved process - though the snappy developers manage it) to get Flatpak releases [SRU'd](https://wiki.ubuntu.com/StableReleaseUpdates) into supported Ubuntu releases (14.04, 16.04, and 17.04)?

**Comment by Ads20000** [comment]
I notice that `snapd` [has a process ](https://wiki.ubuntu.com/SnapdUpdates)which it goes through for SRU's and I imagine Flatpak would need to undergo a similar process. I'm guessing someone here has contacts with the Ubuntu developers so they can ask how to go about doing this?

[Here's an example](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1703798) of the most recent `snapd` release being SRU'd into all supported Ubuntu releases (so that the new release is available without a PPA being necessary).

**Comment by smcv** [comment]
This is something you would have to request in Ubuntu. The Flatpak upstream developers do not have control over what downstream distributions do with Flatpak.

**Comment by mhall119** [comment]
It would require collaboration between Ubuntu and Flatpak developers, and I believe the Flatpak developers would have to be the ones to initiate it

**Comment by Ads20000** [comment]
It would not be hard to get started, I think Flatpak should file an SRU as a bug in Launchpad, then the Ubuntu developers would have to respond :)

**Comment by mhall119** [comment]
https://wiki.ubuntu.com/StableReleaseUpdates describes the process. The fact that there is already a PPA with updated Ubuntu packages should help. It will likely require somebody filing a new bug in Launchpad for each SRU request

**Comment by Ads20000** [comment]
Admittedly with snappy and Fedora I think it was Neal Gompa, someone involved with Fedora, [who got in contact with Fedora about snappy first](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/IMI5TP2K6A6R7PSIOUBLOE62ENIZDXOA/), but then Zyga, a snappy developer, [introduced himself](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/VAMB2VQVG2L7SXHHGARRR6DBU6UQRVXC/).

I think with Flatpak and Ubuntu though, an SRU bug in Launchpad would be a good first step :)

**Comment by Ads20000** [comment]
I could also try emailing the Ubuntu Technical Board because they seemed to be in charge of allowing the special SRU method for `snapd`? What do people think of that? Thing is that I'd need to know that someone from Flatpak were willing to put in some work to satisfy demands by the Technical Board (as in a link I gave above, there's a fairly thorough process `snapd` has to go through to get SRU'd), so that my email wouldn't be in vain. Perhaps the Flatpak devs would like to email them direct?

**Comment by alexlarsson** [comment]
I don't really have much experience in ubuntu packaging, but if someone wants to do the work to do of doing a SRU that would be nice. However, given that we don't really have stable release out other than the old 0.8.x series i think it would be a bit early to look into this. Once we have a stable 0.10 release, and it is in debian unstable, then we may want to look at an SRU.

**Comment by Ads20000** [comment]
I don't either tbh, it's just something I'd like to see happen, I was hoping a Flatpak contributor would have more experience. Whoever packages for Debian Unstable may have an idea of how to get this sort of thing going? :)

**Comment by smcv** [comment]
> Whoever ends up packaging for Debian Unstable

That would be me. Sorry, I don't use Ubuntu and don't have the bandwidth to maintain Flatpak there: someone who primarily uses Ubuntu will have to lead this.

**Comment by Ads20000** [comment]
@smcv Right, could you put a message here when you've packaged for Unstable and I'll try sending a message to the Ubuntu Technical Board and filing an SRU bug? :)

**Comment by jbicha** [comment]
Flatpak cannot be packaged for Ubuntu 14.04 LTS because it requires systemd which wasn't in that version of Ubuntu.

Ubuntu 17.04 intentionally does not have the "latest" version of Flatpak because we stuck with the LTS 0.8 series because it was unclear when the next version would be considered LTS.

My understanding is that the next major release of Flatpak is expected soon so Ubuntu 18.04 LTS will include Flatpak 0.10. It really won't make sense to backport Flatpak 0.10 from 18.04 LTS to 17.10.

I did try to get flatpak into Ubuntu 16.04 LTS but it got stuck because it's more complicated to get brand new packages in as SRUs. (Also Ubuntu 16.04 LTS won't have the best experience since the version of the GNOME Software app in Ubuntu 16.04 LTS doesn't have Flatpak integration.)

I have done some SRUs for Flatpak on Ubuntu but

1. I honestly don't really use Flatpak or Snap yet
1. Some of the Flatpak LTS updates were rather larger than I expected for an LTS branch.
1. So basically the SRUs are a lot of work. Help would be appreciated.

Anyway, this is an Ubuntu issue, not a Flatpak one so maybe we can close this issue?

**Comment by Ads20000** [comment]
> Flatpak cannot be packaged for Ubuntu 14.04 LTS because it requires systemd which wasn't in that version of Ubuntu.

[Apparently it doesn't require systemd](http://flatpak.org/faq.html#Is_Flatpak_tied_to_systemd_)?

> It really won't make sense to backport Flatpak 0.10 from 18.04 LTS to 17.10.

Except people expect latest Flatpak to run Flatpak'd apps with (since newer Flatpak'd apps often expect newer Flatpak).

Also `snapd` is SRU'd with every `snapd` release so presumably this _should_ be possible with Flatpak? Different tech, I know, I guess there's also a manpower issue, hopefully someone with more experience than me will be able to help out...

> I did try to get flatpak into Ubuntu 16.04 LTS but it got stuck because it's more complicated to get brand new packages in as SRUs.

More complicated, but doable, again see `snapd`'s insertion into older Ubuntu releases, even 14.04!

I guess we can continue the discussion on an ubuntu-devel mailing list thread (or I'll try emailing you direct) when we need to have it :) I didn't fully realize that it's more of an Ubuntu issue, thanks for your help.

**Comment by jbicha** [comment]
You're welcome to work on packaging ostree, flatpak, etc. on 14.04 LTS if you want. Personally, it's too old for me now.

You can't backport from 18.04 LTS until 18.04 is released. Once it's released, 17.10 is only supported for ~3 months. It doesn't really make much sense to push something new there when people should really be using 18.04 LTS which should be more stable and have more bugs fixed than 17.10.

Yes, it might be possible to backport major releases as SRUs. There are a few packages like that in Ubuntu. But it needs people to work on the packaging and thorough testing.

**Comment by Ads20000** [comment]
> But it needs people to work on the packaging and thorough testing.

Well yes, that is the requirement...

**Comment by alexlarsson** [comment]
Some details:

Flatpak doesn't require systemd anymore (although it does use it if its there).

Newer versions of flatpak are generally required to build stuff as the build story progresses, and the overall CLI experience and features of regular flatpak gets better. However, I try to ensure that older versions of flatpak still *run* new flatpaks, by backporting any changes needed for that to the 0.8.x stable series. There are few outstanding features that i will add to a 0.8.x release when 0.10 is releases, but most things should already work fine.

**Comment by alexlarsson** [comment]
For the record, rhel 7.4 also has flatpak 0.8.x.

**Comment by smcv** [comment]
> could you put a message here when you've got a package in Unstable

For avoidance of doubt: I do not intend to announce new Debian packages here, or anywhere else that is not Debian - I update them as promptly as I am able to, and anything extra that I need to remember to do will just slow down the actual packaging. However, Debian's developer-facing web pages like https://tracker.debian.org/pkg/flatpak and https://tracker.debian.org/pkg/flatpak-builder provide lots of information about the packages, and keep track of the latest available flatpak and flatpak-builder in every supported suite (currently 0.8.x in stretch and jessie-backports, and 0.9.x in unstable, testing and stretch-backports). Anyone can create a Debian "guest" SSO account and subscribe to those tracker pages if they want to be kept up to date with those versions and their bug reports. The corresponding tracker pages for bubblewrap and ostree are also very relevant to this stack.

The git version control repository used for each source package is also public, and is linked from the package tracker. All Debian Developers and many other Debian contributors have commit access. If it would be useful for the developers of Ubuntu or other derivatives, they are welcome to maintain branches with [DEP 14](http://dep.debian.net/deps/dep14/) names like `ubuntu/artful` in that git repository, or a clone of it elsewhere.

**Comment by Ads20000** [comment]
Apologies for my ignorance about the Debian update process and thanks for your patience :)
