### ISSUE TITLE
flatpak run --devel is broken

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#1002]
```
$ flatpak run --command=strace --devel org.kde.discover 

(flatpak run:17810): GLib-CRITICAL **: g_key_file_get_string: assertion 'key_file != NULL' failed

(flatpak run:17810): GLib-CRITICAL **: g_strsplit: assertion 'string != NULL' failed

(flatpak run:17810): GLib-CRITICAL **: g_strv_length: assertion 'str_array != NULL' failed
error: Wrong number of components in runtime (null)
```

**Comment by alexlarsson** [comment]
Yeah, this was an embarrasing regression, but should be fixed in 0.9.9. I also pushed a fix patch to the 0.9.8 PPAs before that. What version are you on?

**Comment by aleixpol** [comment]
0.9.8

That settles it then, will need a new version in ArchLinux.

**Comment by Barthalion** [comment]
Poked Arch maintainer to move 0.9.10 from `[testing]` to `[extra]`. It should be available in your mirror already.
