### ISSUE TITLE
flatpak hangs with "pivot_root: Invalid argument"

### ISSUE THREAD

**Issue by juanitotc** [flatpak/flatpak#1007]
Using flatpack-0.9.10 with tinycorelinux:

$ flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install --user flathub org.libretro.RetroArch
Required runtime for org.libretro.RetroArch/x86_64/stable (org.freedesktop.Platform/x86_64/1.6) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.freedesktop.Platform/x86_64/1.6 from flathub
...
[####################] 4 delta parts, 33 loose fetched; 114054 KiB transferred in 163 seconds
pivot_root: Invalid argument

$ flatpak run org.libretro.RetroArch
pivot_root: Invalid argument

Is this because the tinycore initrd is loaded into ramdisk which is an actual file system and initramfs is not a file system. For initrd pivot_root is used and for initramfs switch_root is used. You cannot use pivot_root on an initramfs rootfs, you can only pivot real file systems?

Is there a way around this?

**Comment by alexlarsson** [comment]
From the manpage for pivot_root:
```
       EINVAL put_old is not underneath new_root.
```
Here is what we do:
```
mkdir /tmp/.bubblewrap
chdir /tmp/.bubblewrap
mkdir newroot
mkdir oldroot
pivot_root /tmp/.bubblewrap oldroot
```
I don't understand how oldroot could not be under /tmp/.bubblewrap

**Comment by juanitotc** [comment]
I'm not too sure what you mean by that, but I have:

$ ls -a /tmp/.bubblewrap-1001/
./  ../

In case it's useful, --verbose gives the following:

$ flatpak run --verbose org.libretro.RetroArch
XA: No installations directory in /usr/local/etc/flatpak/installations.d. Skipping
XA: Allowing homedir access
XA: Allowing x11 access
XA: Allowing wayland access
XA: Allowing pulseaudio access
XA: Failed to run in transient scope: No systemd user session available, cgroups not available
XA: bwrap args '--bind /var /var --bind /tmp /tmp --ro-bind /sys /sys --bind /run /run --ro-bind /proc /proc --ro-bind /opt /opt --ro-bind /mnt /mnt --ro-bind /home /home --ro-bind /etc /etc --symlink bin/busybox /linuxrc --ro-bind /lib /lib --ro-bind /bin /bin --ro-bind /sbin /sbin --ro-bind /usr /usr --ro-bind /root /root --ro-bind /dev /dev --bind /home/tc/.cache/.dbus-proxy/ /home/tc/.cache/.dbus-proxy/ --file 15 /.flatpak-info'
XA: Running '/usr/local/lib/flatpak/flatpak-bwrap --args 17 /usr/local/lib/flatpak/flatpak-dbus-proxy --fd=14 'unix:abstract=/tmp/dbus-QyiC1z6SSK,guid=8a2e17792684d8e760b11f1859b841e3' /home/tc/.cache/.dbus-proxy/session-bus-proxy-QVPI6Y --filter --own=org.libretro.RetroArch '--own=org.libretro.RetroArch.*' '--talk=org.freedesktop.portal.*' 'unix:abstract=/tmp/dbus-E1owUaqBD1,guid=69ec2899a72a619c5b9225ff59b841e4' /home/tc/.cache/.dbus-proxy/a11y-bus-proxy-0FSI6Y --filter --sloppy-names '--filter=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Embed@/org/a11y/atspi/accessible/root' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Unembed@/org/a11y/atspi/accessible/root' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.Registry.GetRegisteredEvents@/org/a11y/atspi/registry' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetKeystrokeListeners@/org/a11y/atspi/registry/deviceeventcontroller' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetDeviceEventListeners@/org/a11y/atspi/registry/deviceeventcontroller' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersSync@/org/a11y/atspi/registry/deviceeventcontroller' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersAsync@/org/a11y/atspi/registry/deviceeventcontroller''
pivot_root: Invalid argument

**Comment by alexlarsson** [comment]
I'm just trying to figure out why pivot_root gives you an EINVAL error, and it doesn't seem to match what the manpage says.

(/tmp/.bubblewrap vs /tmp/.bubblewrap-1001 was just a simplification on my side).

**Comment by alexlarsson** [comment]
This is actually a bubblewrap issue, and you should be able to reproduce with:
`bwrap --bind / / true`.
Can you file it in https://github.com/projectatomic/bubblewrap ?

**Comment by juanitotc** [comment]
see: https://github.com/projectatomic/bubblewrap/issues/214

**Comment by juanitotc** [comment]
BTW, it might be a good idea to list flatpak runtime deps in the readme

bubblewrap, gsettings-desktop-scemas, gnome-keyring

**Comment by alexlarsson** [comment]
Bubblewrap is optional, it will use the built-in copy if not there. There should be no dependencies on gsettings-desktop-scemas or gnome-keyring though.

**Comment by juanitotc** [comment]
There's no reply from bubblewrap though :(
