### ISSUE TITLE
Possible GPL violation

### ISSUE THREAD

**Issue by lkundrak** [flatpak/flatpak#1016]
You seem to offer binaries of various GPL licensed software in apps [1] and as part of the runtimes [2].

[1] http://flatpak.org/apps.html
[2] http://flatpak.org/runtimes.html

I assume that you're distributing the binaries under the 6.d.) of the GPL [3], since they're not distributed as part of a physical product or via peer-to-peer transmission. The license requires you to redistribute the sources "in the same way through the same place" as the object code. For Flatpak apps you seem to provide two ways to install the software: run a command [4] or clicking on a link [5]. Neither of these approaches two can be used to obtain the corresponding source code. This seems to be in violation of the license of the GPL-licensed components you distribute.

[3] https://www.gnu.org/licenses/gpl-3.0.en.html
[4] http://flatpak.org/apps.html#cli
[5] http://flatpak.org/apps.html#graphical

The bundles don't seem to include any information about the licensing. The license text is often missing and "flatpak info" doesn't seem to be helpful either. Worse even, there doesn't seem to be any way for the user to learn about the licensing condition prior to installing the software.

---

This worries me great deal. The freedom to modify the software is a rather essential right granted by the GPL. Currenty Flatpak makes it very easy to get binaries and does nothing to help me make modifications and recreate equivalent binaries with my changes. As I explained above I believe it does even less than the license mandates. I wish, on the contrary, that it would make the task easy and comfortable (think getting and rebuilding a src.rpm corresponding to a .rpm).

Today I failed locating the flatpak manifest for GEdit build I installed via flatpak. If the flatpak manifest itself is sufficient to locate the source files and the right buildroot to recreate a flatpak bundle, then perhaps fixing this issue just involves the links to it in the right places, a command to fetch it and some licensing metadata here and there.

**Comment by Alexander-Wilms** [comment]
The AppData contains the license of the packaged application and I assume flatpak-builder throws an error when it's missing.

You can get the sources via flatpak install flathub org.gnome.gedit.Sources.

**Comment by matthiasclasen** [comment]
We are working hard to make it _easier_ for you to modify the software. Have you seen the builder videos where the application window is flipped over to reveal the source code in an ide, ready for you to patch away ? That is built on flatpak technology.

**Comment by TingPing** [comment]
`flatpak` does not currently expose license but the information is there as @Alexander-Wilms and `flatpak` will surely use it at some point. `gnome-software` is how most users will install software and it does expose the license and mark proprietary software in bright red and allow hiding them all.

**Comment by lkundrak** [comment]
> We are working hard to make it easier for you to modify the software. Have you seen the builder videos where the application window is flipped over to reveal the source code in an ide, ready for you to patch away ? That is built on flatpak technology.

I haven't seen that video. I've given Builder a few tries, but I'm sure it can do a lot more than I know. But I'm not sure that's quite to the point here. I'm absolutely not saying that you are not aiming to make it easier to modify the source.

What I'm saying is that I made a honest attempt at getting the relevant sources for modification, following the resources on flatpak web site and I failed.

This is my first experience with flatpak so I'm probably quite naive and uninformed. Nevertheless, if I should have used Builder or Software to get the sources then flatpak.org has mislead me and that should be fixed.

> You can get the sources via flatpak install flathub org.gnome.gedit.Sources

How am I supposed to know this?

**Comment by hbons** [comment]
Getting the license for the app is usually easy enough, but what about bundled dependencies? Would be great if flatpak could standardise these too somehow.

**Comment by alexlarsson** [comment]
@hbons All the sources are in the org.my.App.Sources extension.

Its true that this is not necessarily well documented or easy to use atm though.

**Comment by alexlarsson** [comment]
Additionally each flatpak itself contains a version of the resolved manifest in /app/manifest.json, so even without downloading the sources you can easily see what went into building the app.

We do need better CLI integration to show the appdata though, which includes the licence, but also a lot of other useful information.

**Comment by alexlarsson** [comment]
We don't currently have a sources bundle for the runtime though. And that would be pretty large, so we should probably have some other way to handle those.

**Comment by matthiasclasen** [comment]
flatpak 1.2 will show license information.

**Comment by artemmolotov** [comment]
> flatpak 1.2 will show license information.

Hello, @matthiasclasen. Could you write a command for showing license information of a _not installed_ package? I didn't find it in the documentation.

 I tried these commands, but they don't contain licenses.
`flatpak search --columns=all firefox`
`flatpak install -vv flathub org.mozilla.firefox`

Flatpak `1.10.7`.

Thank you.

**Comment by nmstoker** [comment]
Is there any chance this could be considered for re-opening.  I know you're making efforts with flatpak but the legal issue is that the licenses often say that **the distribution must include the source**.

This is very distinctly different from "there's an accompanying way you can get the source".  In that scenario the source is not part of the distribution (ie the downloading of the flatpak) and thus a user is in contravention of the license in cases where the source distribution applies.

I'm not a lawyer but I'm reasonably confident this is the correct interpretation (ie that it _is_ a problem) but if there are lawyers on your team who can weigh in then that'd be ideal.

If you prefer this opened as a new issue, that's fine by me, just say and I'll post as a new issue.

Thanks!  Not trying to create problems, flatpak is great, just seems important to find a scenario where apps based on GPL licensed code can be distributed properly in line with the license. 👍🏻

**Comment by TingPing** [comment]
@nmstoker Which license says that? I've never encountered one.

The GPL for example says you can get the source on request. This is the backbone of all FOSS Linux distrubutions. They provide separate source repositories, just like Flathub, where you can get the sources.

**Comment by TingPing** [comment]
@artemmolotov `flatpak info` shows the license. `flatpak search` does not. Feel free to open a feature request for that.

**Comment by nmstoker** [comment]
Hi @TingPing actually maybe I'm wrong, as it appearsthe GPL does allow a separate distribution of source as you say, it's simply that it has to be clearly documented

Mentioned here:
https://www.gnu.org/licenses/gpl-faq.en.html#SourceAndBinaryOnDifferentSites

My confusion stems from reading comments in code I thought was GPL'd but seems not to be after all. Apologies for the misunderstanding!

**Comment by smcv** [comment]
Flatpak (the program that downloads and installs Flatpak apps) can't really be violating the GPL unless it contains a license-violating combination of things in its own source code. If you believe Flathub (a popular repository for Flatpak apps) is violating the GPL in the way it makes those apps available, please see https://flathub.org/about instead. Flathub is maintained by different people (with some overlap) and this is not its issue tracker.

The difference between Flatpak and Flathub is a bit like the difference between apt and Debian, or between RPM and Fedora.

**Comment by nmstoker** [comment]
@smcv - it's okay, with my response above i withdrew my original concern which proved to be a misunderstanding on my part

Thanks for clarifying the flathub point though.
