### ISSUE TITLE
Is there a way for an app to use two runtimes at the same time?

### ISSUE THREAD

**Issue by whenov** [flatpak/flatpak#1017]
If not, what's the proper solution? Thanks!

(I want to build an app which depends on both gnome and qt.)

**Comment by alexlarsson** [comment]
No, runtimes are not the same as package dependencies, they are more like a distro (supplies all of /usr). The proper solution is to pick one runtime and bundle whatever is not in that.

**Comment by alexlarsson** [comment]
Note that gtk3 is in the kde runtime, so you might not need as much bundling as you expect.

**Comment by whenov** [comment]
Thanks for your answer!
