### ISSUE TITLE
Install runtimes in user $HOME

### ISSUE THREAD

**Issue by ispmarin** [flatpak/flatpak#1018]
I'm trying flatpak to install Telegram, for example, and when I run 

`flatpak install --from https://jgrulich.fedorapeople.org/telegram/telegram.flatpakref`

I get asked to insert my root password, to add the runtime. Is there a way to install everything that flatkpak needs, including runtime, in my $HOME folder?

**Comment by phw** [comment]
Using the `--user` switch should work.

**Comment by ispmarin** [comment]
It worked. This is a very nice feature of flatpak, maybe it should be better explained on the docs? Thanks.
