### ISSUE TITLE
Can't reproduce build on second run.

### ISSUE THREAD

**Issue by hbons** [flatpak/flatpak#1019]
Flatpak 0.9.10 on Fedora 26.

flatpak-builder file: https://github.com/hbons/org.sparkleshare.SparkleShare/blob/e00279c2d43dd14ce049e0f92636d85d04434cdb/org.sparkleshare.SparkleShare.json

I'm building using `flatpak-builder --force-clean --repo=repo app org.sparkleshare.SparkleShare.json`.
On the first run (no .flatpak-builder/ exists) everything builds fine and I can install and run the app. On second run I get this error:

```
...
New Type: WebKit2.SubmitFormArgs
Member Added: public SubmitFormArgs ();
Member Added: public WebKit2.FormSubmissionRequest Request { get; }
New Type: WebKit2.SnapshotError
Member Added: Create
Members Added: 845, Members Deleted: 0
make[1]: Leaving directory '/run/build/webkit2-sharp/doc'
make: *** [Makefile:479: all-recursive] Error 1
Error: module webkit2-sharp: Child process exited with code 2
```

Update: when I remove the repo (here: ./repo) it also builds fine.

**Comment by alexlarsson** [comment]
I see this:
```
New Namespace File: WebKit2
New Type: WebKit2.CacheModel
mdoc: Could not create file "/tmp/tmp564b8a5a.tmp". File already exists.
See `mdoc help' for more information or use --debug to diagnose.
```

Which might be the error

**Comment by alexlarsson** [comment]
In fact, its like its running two instances of monodocer:
```
make[1]: Entering directory '/run/build/webkit2-sharp/doc'
mkdir -p ./en
mkdir -p ./en
/app/bin/monodocer -assembly:../out/*/webkit2-sharp.dll -path:en
/app/bin/monodocer -assembly:../out/*/webkit2-sharp.dll -path:en
Generating webkit2-sharp-docs.source
New Type: WebKit2.AuthenticationScheme
New Type: WebKit2.AuthenticationScheme
Member Added: Default
...
```

**Comment by alexlarsson** [comment]
Probably these are running in parallel, which does't work:
```
update:
        mkdir -p $(srcdir)/en
        $(MONODOCER) $(UPDATE_ASSEMBLIES) -path:en

$(srcdir)/en/*/*.xml $(srcdir)/en/*.xml:
        mkdir -p $(srcdir)/en
        $(MONODOCER) $(UPDATE_ASSEMBLIES) -path:en
```

Adding  `"no-parallel-make": true` to the webkit2-sharp moduie fixes it for me.

I'm not sure why it works on the first install though...

**Comment by alexlarsson** [comment]
Also, this:
```
                    "branch": "master",
                    "commit": "9ef7d3f394b9d485674c59e92db24ac66fd9f16b"
```

Is not really great. It will just make the app fail to build once master branch gets a new commit. Either use a tag (not branch) + commit, or if you don't have one, just the commit.

**Comment by hbons** [comment]
That fixed it! Weird that it always worked before. It must have been racing. Thanks!

Regarding the branch + commit. I added this to make it more readable. As Flathub suggests adding the tag name + commit for this reason, I thought this would work for branch names too. It would be nice if the same could be done for branches too as it's useful info to know. using "branch" for both branches and tags in the json can be confusing too. Maybe flatpak-builder could only use "tag:" specifically for tags and prefer branches over tags when "branch:" is used. I guess it will break a lot of spec files when changing this now though.
