### ISSUE TITLE
Runtimes should be able to remove files from the runtimes they're based on

### ISSUE THREAD

**Issue by ptomato** [flatpak/flatpak#1024]
I suspect that the commit https://git.gnome.org/browse/gnome-sdk-images/commit/?h=gnome-3-26&id=2b1dc1b1ad84bddc932da2395a96d5a7e4c4fad0 isn't actually doing anything. (I updated to the latest org.gnome.Sdk//3.26 and the gstreamer plugin scanner is still crashing, causing plugins to be blacklisted.)

Here's a minimal runtime manifest that builds fine for me (flatpak 0.9.8, ostree 2017.10) but you can verify in a shell in the sandbox that `/usr/lib/gstreamer-1.0` is still there and full of plugins:
```json
{
    "build-runtime": true,
    "id": "name.ptomato.Sdk",
    "id-platform": "name.ptomato.Platform",
    "branch": "master",
    "runtime": "org.freedesktop.Platform",
    "sdk": "org.freedesktop.Sdk",
    "runtime-version": "1.6",
    "modules": [
        {
            "name": "clean-out-old-gstreamer",
            "buildsystem": "simple",
            "ensure-writable": ["/usr/lib/gstreamer-1.0/*"],
            "build-commands": ["rm -rf /usr/lib/gstreamer-1.0"]
        }
    ]
}
```

**Comment by alexlarsson** [comment]
I have not yet imported the latest build to stable, but i just tried the build in http://sdkbuilder1.gnome.org/repo/ and it did indeed fix the warnings from gst-inspect-1.0

**Comment by alexlarsson** [comment]
I tried your example here with:

flatpak-0.9.10-1.fc26.x86_64
flatpak-builder-0.9.9-1.fc26.x86_64
ostree-libs-2017.10-2.fc26.x86_64
and it worked fine...

**Comment by birros** [comment]
I got some troubles running a webkit2gtk based app inside the gnome platform 3.26, WebKitWebProcess printing many warnings about gstreamer.

I'm posting this here cause this seems to be related to blacklisted gstreamer plugins as this output proves.

```
$ flatpak run --command=gst-inspect-1.0 org.gnome.Platform//3.26 -b 2> /dev/null
Blacklisted files:
  libgstkmssink.so
  libgstcamerabin.so
  libgstencoding.so
  libgstoss4.so
  libgstpulseaudio.so
  libgstcoreelements.so
  libgstgtk.so
```

I don't know how works gstreamer in details but those problems doesn't appears when running this command on the sdk runtime.

Maybe some files required by gstreamer are removed during the cleanup-platform process.

My skills stop there. Good luck.

```
$ flatpak info org.gnome.Platform//3.26
Ref: runtime/org.gnome.Platform/x86_64/3.26
ID: org.gnome.Platform
Arch: x86_64
Branch: 3.26
Origin: gnome
Commit: 1b78d7195d9cb3af0fa207ff964651d662070f58a5e93d62a88b23e9a610d12e
Location: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.26/1b78d7195d9cb3af0fa207ff964651d662070f58a5e93d62a88b23e9a610d12e
Installed size: 938,1 MB
```

**Comment by alexlarsson** [comment]
Yeah, it seems we're removing the base gstreamer plugins from the sdk only, not the platform, this needs some flatpak-builder support i believe.
