### ISSUE TITLE
Crash or hang while updating org.mozilla.FirefoxNightly/x86_64/master from org.mozilla.FirefoxRepo

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#1028]
Hi,

here is the problem:

```
# flatpak update
Looking for updates...
Updating: org.mozilla.FirefoxDevEdition/x86_64/master from org.mozilla.FirefoxRepo
[                    ] Downloading metadata: 6/(estimating) 25,9 kB
Error: Failed to update org.mozilla.FirefoxDevEdition/x86_64/master: While pulling app/org.mozilla.FirefoxDevEdition/x86_64/master from remote org.mozilla.FirefoxRepo: Server returned status 404: Not Found
Updating: org.mozilla.FirefoxDevEdition.Locale/x86_64/master from org.mozilla.FirefoxRepo
**
OSTree:ERROR:src/libostree/ostree-repo-pull.c:1291:meta_fetch_on_complete: assertion failed: (pull_data->n_outstanding_metadata_fetches > 0)
Aborted (core dumped)
```

I tried several times and sometimes got a crash and other times got a hang.

**Comment by LaurentBonnaud** [comment]
Here is version info: 
```
Ubuntu 17.04

Package: flatpak
Version: 0.9.12-0alexlarsson1~zesty

Package: libostree-1-1
Version: 2017.10-0alexalarsson1~zesty
```

**Comment by alexlarsson** [comment]
So, it was pulling one ref from the server, which returned 404:

```
While pulling app/org.mozilla.FirefoxDevEdition/x86_64/master from remote org.mozilla.FirefoxRepo: Server returned status 404: Not Found
```
And then it started pulling another and gets an internal ostree assertion:
```
OSTree:ERROR:src/libostree/ostree-repo-pull.c:1291:meta_fetch_on_complete: assertion failed: (pull_data->n_outstanding_metadata_fetches > 0)
```

I wonder if its the initial pull still happening in the background on a tthread, or if its the new pull.

@cgwalters Ever seen this?

**Comment by cgwalters** [comment]
Oh indeed this could be another symptom of https://github.com/ostreedev/ostree/pull/1185

An unfortunate downside of ostree's commandline-based tests is we don't have good coverage right now for what flatpak is doing.  Further this was a race that only happens in error conditions.

I think if we add some tests to flatpak for this, we would get coverage for free once we update ostree's tests to the updated flatpak, since https://github.com/ostreedev/ostree/pull/818

**Comment by LaurentBonnaud** [comment]
I am closing this bug that I never saw again since then.
