### ISSUE TITLE
API to remove refs from the local repository

### ISSUE THREAD

**Issue by smspillaz** [flatpak/flatpak#1031]
As alluded to in #1011 it'd be nice if we had an API to clean up refs in the local repository. In our usecase, this would ensure that refs we pulled but didn't install for some reason could be cleaned up and didn't take up disk space.

The drawback to this is that it exposes something that could be considered to be an implementation detail through the API. Thoughts?

**Comment by alexlarsson** [comment]
Its really already exposed with the PULL_ONLY API though

**Comment by smspillaz** [comment]
Thats true, I suppose. It just irked me a little. Nonetheless I'm preparing a patch and should have it ready shortly
