### ISSUE TITLE
flatpak run does not work when ~/.local/share/flatpak is symlink

### ISSUE THREAD

**Issue by lapseofreason** [flatpak/flatpak#1032]
`flatpak run` gives the following error when `~/.local/share/flatpak` is a symlink:

~~~~
Can't mount tmpfs on /newroot/home/luser/.local/share/flatpak: No such file or directory
~~~~

Replacing the symlink with the actual directory fixes the issue and the application runs normally. It does not make a difference whether the symlink is absolute or relative. 

The use case for the symlink is in my opinion a valid one as `~/.local/share/flatpak` can become very large and there is no need to include it in hourly/daily backups.

System is Fedora 26, flatpak v0.9.12.

**Comment by alexlarsson** [comment]
We're trying to mount a tmpfs on ~/.local/share/flatpak to hide what is there. However, if the app has access to $HOME, then there is already a symlink there, and we can't mount a directory on a symlink.
I guess we need to follow the symlink and mount something there...

**Comment by lapseofreason** [comment]
Thanks a lot, I really appreciate the quick fix. Now that the updated version is in Fedora I tested it and it works like a charm ;)
