### ISSUE TITLE
flatpak update command crash or something 

### ISSUE THREAD

**Issue by Lvaskz** [flatpak/flatpak#1033]
Hi, I recently tried to update all the applications I have installed in flatpak with the command: "flatpak update", but we found this:

$ flatpak update
Looking for updates...
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: Error resolving 'dl.tingping.se': Fallo temporal en la resolución del nombre
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
error: GPG signatures found, but none are in trusted keyring

OS: Linuxmint 18.2

**Comment by TingPing** [comment]
Yea repo should be fine but it only contains development builds now. So as a user you probably do want to use flathub.

**Comment by Lvaskz** [comment]
Looking for updates...
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: Error resolving 'dl.tingping.se': Temporary failure in name resolution
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
error: GPG signatures found, but none are in trusted keyring
I traduced the spanish line to english, thanks

**Comment by Lvaskz** [comment]
it seems now i can update apps. thanks
