### ISSUE TITLE
define a roadmap towards 1.0

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#104]
We should have some sort of roadmap on the website that outlines milestones towards the big one dot oh.

Some ideas of what we need for that:
- a stable runtime
- fleshed out portals
- a registry ?

**Comment by dmedri** [comment]
- extend runtimes architectures, not only X86_64 (X86_32, ...). A good tip to add on the wiki page, is add example for "flatpak remote-ls gnome -v -d" to check what is available.
- not sure what you mean for a "registry", but a web interface to check what is available, accept user requests for apps, download stats, should be useful.

**Comment by mwleeds** [comment]
I think this can be closed now that we're about to release 1.0. The roadmap was basically the 1.0 Milestone.
