### ISSUE TITLE
Flatpak 0.9.98-0alexlarsson1~zesty on Ubuntu 17.04 states permissioned denied when trying to install system level flatpaks

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#1040]
What happened:
1) Install the latest flatpak package from the PPA [0]
2) Try to install a system level flatpak package
  $ flatpak install repo app
3) Notice that you get "error: Permission denied"

What I expected to happen:
At step 3 for the package to be installed

Note that before (0.9.12-0alexlarsson1~zesty) did not have this issue.

$ lsb_release -rd
Description:	Ubuntu 17.04
Release:	17.04
$ apt-cache policy flatpak
flatpak:
  Installed: 0.9.98-0alexlarsson1~zesty
  Candidate: 0.9.98-0alexlarsson1~zesty
  Version table:
 *** 0.9.98-0alexlarsson1~zesty 500
        500 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.8.5-1 500
        500 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages

0 - https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

**Comment by alexlarsson** [comment]
Should be fixed in 0.9.98.2
