### ISSUE TITLE
Flatpak crashes when updating org.mozilla.FirefoxNightlyWayland (double free or corruption (!prev))

### ISSUE THREAD

**Issue by jurf** [flatpak/flatpak#1042]
This has been going on for some time. I think it also happens with the other variants too, except normal Nightly, but I am not sure about that.

Running 0.9.12

Stack trace attached. Also sent to the ABRT server or what’s it called.

[flatpak-crash-2.txt](https://github.com/flatpak/flatpak/files/1334099/flatpak-crash-2.txt)

**Comment by alexlarsson** [comment]
I wonder if this is related to https://github.com/flatpak/flatpak/issues/605. Same server.

**Comment by alexlarsson** [comment]
@cgwalters This seems to be a crash in the curl ostree backend.

@jurf Do you know what the id of this is on the ABRT server?

**Comment by cgwalters** [comment]
I'd retest with https://github.com/ostreedev/ostree/pull/1185 - anything could go wrong without that.

**Comment by jurf** [comment]
@alexlarsson https://retrace.fedoraproject.org/faf/reports/1861143/ I think. I tried reporting it, I think it went fine but it complained that backtrace was unusable, so now I’m trying the second download-heavy option.

**Comment by jurf** [comment]
@cgwalters how can I do that? I’m running Fedora 26.

**Comment by jurf** [comment]
Happened again today, makes it almost impossible to update (I haven’t been able to completely update for like two weeks due to misc. issues with Firefox nightlies, sometimes flatpak crashes, othertimes there’s a stream error or flatpak downright freezes).

**Comment by cgwalters** [comment]
The [PR mentioned above](https://github.com/flatpak/flatpak/issues/1042#issuecomment-332279363) is in [the libostree v2017.12 release(https://github.com/ostreedev/ostree/releases/tag/v2017.12).  Want to give that a try?

**Comment by cgwalters** [comment]
The PR mentioned above is in [the libostree v2017.12 release](https://github.com/ostreedev/ostree/releases/tag/v2017.12). Want to give that a try?

**Comment by alexlarsson** [comment]
Did anyone see this with 2017.12 or later?

**Comment by jurf** [comment]
I havem’t experienced this for a long time, I think it’s safe to close.
