### ISSUE TITLE
flathub.org command line instructions to install apps should specify it needs root permissions or have --user

### ISSUE THREAD

**Issue by HoboPrimate** [flatpak/flatpak#1049]
As it is right now gives an error:
flatpak install --from https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
Installing: com.spotify.Client/x86_64/stable
Installing: com.spotify.Client/x86_64/stable from flathub
error: Permission denied

**Comment by HoboPrimate** [comment]
Apparently, it should have asked for a password, which it didn't, so it's an issue with either flatpak or more probably fedora 27.

**Comment by alexlarsson** [comment]
This is a bug in 0.9.98, fixed in 0.9.98.2
