### ISSUE TITLE
re-apply locale subpaths on an upgrade

### ISSUE THREAD

**Issue by ramcq** [flatpak/flatpak#1051]
When the value of xa.languages or the list of system locales returned by AccountsService changes (or indeed, if the user changes their locale), we should notice that the list of desired locale subpaths is different to the locales currently deployed, and re-deploy the extension with an updated list of subpaths.

**Comment by ramcq** [comment]
Perhaps as a pre-requisite to this, the upgrade operation should also allow --subpath to be specified.

**Comment by alexlarsson** [comment]
Eh, did you test this?

```
$ flatpak info org.gnome.frogr.Locale 
Ref: runtime/org.gnome.frogr.Locale/x86_64/stable
ID: org.gnome.frogr.Locale
Arch: x86_64
Branch: stable
Origin: flathub
Commit: 58a26c23b221e35eca8027045001c9376a9f8ec0792425757ab6204cd64aea33
Location: /home/alex/.local/share/flatpak/runtime/org.gnome.frogr.Locale/x86_64/stable/58a26c23b221e35eca8027045001c9376a9f8ec0792425757ab6204cd64aea33-en
Installed size: 512 bytes
Installed subdirectories: /en
$ flatpak --user update --subpath= org.gnome.frogr.Locale
Looking for updates...
Updating: org.gnome.frogr.Locale/x86_64/stable from flathub
[####################] 1 delta parts, 1 loose fetched; 82 KiB transferred in 0 seconds
Now at 58a26c23b221.
$ flatpak info org.gnome.frogr.Locale 
Ref: runtime/org.gnome.frogr.Locale/x86_64/stable
ID: org.gnome.frogr.Locale
Arch: x86_64
Branch: stable
Origin: flathub
Commit: 58a26c23b221e35eca8027045001c9376a9f8ec0792425757ab6204cd64aea33
Location: /home/alex/.local/share/flatpak/runtime/org.gnome.frogr.Locale/x86_64/stable/58a26c23b221e35eca8027045001c9376a9f8ec0792425757ab6204cd64aea33
Installed size: 397,3 kB
```

**Comment by ramcq** [comment]
Haha errr awkward. No I just read the manpage for flatpak update. :) Is there some way to upgrade the subpath state for a particular deploy so that it is changed next time an upgrade is downloaded?

**Comment by alexlarsson** [comment]
No, thats not currently possible.

**Comment by ramcq** [comment]
So if you ignore my 2nd comment, I think the 1st issue still stands - flatpak_dir_get_locale_subpaths is not (re)used when something is being upgraded, so when languages are changed/added on the system, the deploys you have won't ever be changed. I guess the problem is, we don't know whether a deploy had it's subpaths set explicitly (either on the command line or xa.languages from the install time) or whether they are just defaults of some sort. What do you think a reasonable tie-break/heuristic would be? Eg - merge the current output of flatpak_dir_get_locale_subpaths with the current locale subpaths (unless it returns * but the deployed Locale has a subpath, in which case leave it)?

**Comment by alexlarsson** [comment]
Yeah, merging the current locates with the old, unless everything is already installed sound like the right thing to do to me.
