### ISSUE TITLE
Why does flatpak ask root password multiple times?

### ISSUE THREAD

**Issue by alexandrevicenzi** [flatpak/flatpak#1055]
Every time that I need to install a package flatpak asks for root password multiple times. I think it ask for every dependency.

It should only ask once if needed.

Just in case, I'm using openSuse Leap 42.

**Comment by marcosps** [comment]
It still happens, is there a way to disable it? Or it is done by polkit or other trick in suse Leap 15?

**Comment by marcosps** [comment]
@TingPing indeed, running ```flatpak update``` with sudo solves the problem.

@kirbyfan64 I will check how to change these permissions in polkit, since I found where this is set...

thanks!

**Comment by matthiasclasen** [comment]
should be better with flatpak 1.2

**Comment by bms** [comment]
I have just been afflicted by this on Ubuntu 24.04 under my own user account.
The tool does not even understand my backspaces when I know I have mis-typed characters and am correcting my own typing.

Please stop making software this bad.
