### ISSUE TITLE
No Runtime for Nvidia-384-90

### ISSUE THREAD

**Issue by Hasbreak** [flatpak/flatpak#1056]
The NVIDIA drivers received an update to 384-90 on Arch Linux 6 days ago. Flatpak doesn't seem to have a Runtime for the following version yet. Hence Steam and presumably other apps that depend on it are broken, and they won't run.

```
❯ cat /sys/module/nvidia/version
384.90
```

**Comment by TingPing** [comment]
They were added 5 days ago: https://github.com/flatpak/freedesktop-sdk-images/commit/ea5417b75e88e10ea017111dd1e5d4cb36c87d38

But seems they didn't get built on the server or something. Will probably have to wait until Monday.

**Comment by Hasbreak** [comment]
New version of the NVIDIA driver has been released.
```
❯ cat /sys/module/nvidia/version
387.12
```

**Comment by TingPing** [comment]
They have been uploaded.
