### ISSUE TITLE
flatpak won't allow passing parameter in `--command=vlc --no-qt-privacy-ask` 

### ISSUE THREAD

**Issue by kensully** [flatpak/flatpak#1058]
I installed  `vlc`  with `flatpak install --user flathub org.videolan.VLC` command. 
When I tried to run it like `flatpak run  org.videolan.VLC` it exits after a gui flashes a title with `Privacy and Network Access Policy` then disappears an exit immediately. I looked for it, it's a bug related to `vlc` when you launch it first time. But launching it with `vlc --no-qt-privacy-ask` overcomes the issue but **flatpak** won't allow me to add `--no-qt-privacy-ask` switch with `vlc` like

        flatpak run --command="vlc --no-qt-privacy-ask" --runtime=org.gnome.Sdk/i386/3.24 org.videolan.VLC

It prints 

       execvp vlc --no-qt-privacy-ask: No such file or directory

How can I pass parameter to a command in **flatpak**?

**Comment by TingPing** [comment]
`flatpak run org.videolan.VLC --no-qt-privacy-ask`

**Comment by kensully** [comment]
@TingPing  thank you responding. your suggestion suppressed the dialog, however `vlc` keeps exiting. So I have a different issue. VLC exits immediately after launching.

**Comment by nedrichards** [comment]
Hi there, that sounds like an issue with the VLC flatpak. You'd probably get a better response if you file it over there: https://github.com/flathub/org.videolan.VLC

**Comment by kensully** [comment]
@nedrichards thank you for your guidance. I close the issue. 
Thank you all.
