### ISSUE TITLE
Confusing behaviour with flatpak install --user and system remotes

### ISSUE THREAD

**Issue by sbird** [flatpak/flatpak#1065]
Steps to reproduce:
1. Follow instructions on flathub:
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
(this adds a system remote)
2. Try to install a user package:
> flatpak install --user flathub com.skype.Client
error: Remote "flathub" not found
> flatpak remotes                                  
Name   Options
flathub  system

This was (at least to me) rather confusing. My preferred  behaviour would be for "flatpak install --user" to first search user remotes for the package to install, then to search system remotes. 
Failing that, an improved error message would be: "error: Remote "flathub" is for system packages only".

**Comment by alexlarsson** [comment]
I don't agree. The system and per-user configurations are separate, both implementation wise, and because they have different people controlling them. For instance, you could remove/change a remote in the system install which would break the user-installed thing (it would be installed from a non-existing remote).

**Comment by xasx** [comment]
This is currently confusing me as well. Not sure how the separation of the implementation should affect end-users.

**Comment by sbird** [comment]
If you don't want to change the behaviour (which is fair enough) then please do improve the error message.

**Comment by mwleeds** [comment]
After https://github.com/flatpak/flatpak/pull/2073 is merged Flatpak will check both user and system installations for the specified remote, unless the user specifies `--user`, `--system`, or `--installation`. But a remote from one installation will not be used when installing to another, so it is different behavior than what this issue originally asked for.
