### ISSUE TITLE
Manage module dependencies through nesting not list order

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1071]
Hi!

As you know, I have a lot of problems with modules being rebuilt for every little change. Just today, I rebuilt (uselessly) nearly all modules at least 3 times (while disabling temporarily the long-build dependency, otherwise it would be impossible) because I am trying to use BaseApps and some errors in some module at the start of my manifest forced useless rebuild of everything.

What I'll be asking is maybe a big change but I'll hope you'll consider it.
Basically right now, if you have:

```
"modules": [
  {
    "name": "libfoo"
  },
  {
    "name": "libbar"
  }]
```
A change to libfoo will have libbar being rebuilt. This is very annoying when libfoo is not a dependency of libbar. Now if you look for instance at GIMP flatpak manifest: https://git.gnome.org/browse/gimp/tree/build/flatpak/org.gimp.GIMP-dev.json
It has many modules and if a change to — say — the first dep occurs, everything is rebuilt!

On the other hand, modules can be nested under modules. I actually use this in our manifest, for instance "exiv2" under "gexiv2", and even adding all Python related deps under some "virtual" (i.e. not actually building something) "python" module. Though currently it seems to be only useful for my own organization and also so that I can deactivate ("disabled": true) a bunch of modules at once when needed.
But it would make a lot of sense to use nesting to imply a dependency.

```
"modules": [
  {
    "name": "libfoo"
  },
  {
    "name": "libbar",
    "modules": [
      {
        "name": "libplop"
      }]
  }]
```
In the above example, a change in libfoo would not trigger a rebuild of libbar but a change of libplop would.

Of course, you could have the case where a module is dependency to 2 modules, but then you could just add a syntax to reference by its name a module previously built:

```
"modules": [
  {
    "name": "libfoo",
    "modules": [
      {
        "name": "libplop"
      }]
  },
  {
    "name": "libbar",
    "modules": [
      "libplop",
      {
        "name": "libotherdep"
      }]
  },
  {
    "name": "gimp",
    "modules": [ "libfoo", "libbar" ]
  }]
```

I understand that this change may be a problem since it changes semantic to the order of modules in the flatpak manifest (to be accurate, it removes semantic to order and add it to nesting instead) and there are a bunch of manifests in the wild already. But I think it would be really worth it for big projects with a lot of dependencies.
If really you don't want to change the dependency behavior, at least a CLI option to flatpak-builder to switch to this behavior would be acceptable (though it would really make a lot of sense if that were a default behavior IMO).

**Comment by matthiasclasen** [comment]
You are asking for some pretty fundamental changes here. These are some of the basic ideas of how flatpak-builder operates:

- a simple, linear recipe instead of complex dependency graphs
- complete builds to avoid issues stemming from partial rebuilds

**Comment by matthiasclasen** [comment]
Also, flatpak-builder has its own github module now and this issue probably belongs over there...

**Comment by Jehan** [comment]
> You are asking for some pretty fundamental changes here. These are some of the basic ideas of how flatpak-builder operates:

Indeed. But really testing and building flatpak packages is a real pain in the ass because of the many rebuild issues I encountered. Really most things are nice otherwise. But this part often feels like a waste of time and we have no control over it even when we know that the rebuild is useless (but no way to tell it to flatpak). ;-(
If really the change is not possible, I would really welcome an optional CLI option for instance.

> Also, flatpak-builder has its own github module now and this issue probably belongs over there...

Oh is there? Sorry didn't know. I assume github still doesn't have a feature to move report accross projects?

**Comment by chergert** [comment]
If your SDK contains `ccache`, you can also run `flatpak-builder --ccache ...` which should help quite a bit. If the module at hand really didn't include files that were changed by previous modules, it should be fairly quick to spit out `.o`s for C and C++ sources.

A major difficulty, as I understand it, to moving away from the serialized build ordering is that it would move the burden on the maintainer of the json manifest to ensure reproducibility. Given that the big wins from OSTree come when bits are reproducible, that might be counter productive.

**Comment by alexlarsson** [comment]
Yeah, this is a fundamental change in how flatpak-builder works, which is a fully reproducible linear direct install into $PREFIX. To support dependencies in the way you're suggesting means completely changing this, installing each module into $DESTDIR, collecting the various builds and combining them, running post install snippets after compination, etc. This is not what flatpak-builder was designed for.

It does however sound a lot like buildstream, which is another (wip) build format that can target flatpaks.

**Comment by Jehan** [comment]
I see. I thought it would not be accepted but I had to try. :P
At least I discovered flatpak can make use of ccache which indeed should help a lot (I use ccache on all my local builds as well). Now I'll prefix all my flatpak-builder build commands with ccache. It still won't be perfect, but at least a lot better.
