### ISSUE TITLE
Spotify .deb 404 not found

### ISSUE THREAD

**Issue by SabeBarker** [flatpak/flatpak#1074]
`flatpak install --from https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref`

Receive this error when trying to install spotify (using instructions from website):

`error: While downloading http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.59.395.ge6ca9946-18_amd64.deb: Server returned status 404: Not Found`

The link should be:
`http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.64.407.g9bd02c2d-26_amd64.deb`

This is the .flatpakref from the link above:
```
[Flatpak Ref]
Title=Spotify
Name=com.spotify.Client
Branch=master
Url=http://alexlarsson.s3-website-us-east-1.amazonaws.com/spotify-repo
IsRuntime=False
GPGKey=[removed for cleanliness]
RuntimeRepo=https://sdk.gnome.org/gnome.flatpakrepo
Comment=Spotify
Description=Linux version of the spotify client
Icon=https://developer.spotify.com/wp-content/uploads/2016/07/icon1@2x.png
```

Am I doing something wrong?

**Comment by TingPing** [comment]
The download link is wrong: See flathub/com.spotify.Client#7
