### ISSUE TITLE
Introduce a new file format to be able to install N apps with one command (my-app-picks.flatpakrefcol)

### ISSUE THREAD

**Issue by jgarciao** [flatpak/flatpak#1085]
I think a killer feature for flathub.org could be:

1. A user visits http://flathub.org and looks for multimedia related applications
2. Once he finds an interesting app, instead of just clicking on the instal button he logs-in and adds the app into an app collection that he calls "multimedia essentials"
3. The user keeps looking for other multimedia apps and adds them to the collection
4. Once he is finished he goes to his collection and clicks on a "Install all" button
5. A multimedia-essentials.flatpakrefcol file is downloaded
6. GNOME Software opens the file and asks for confirmation to install all apps in the collection
 
On the command line, the app collection could be installed with this command:
`flatpak install --from https://flathub.org/users/jgarciao/collections/multimedia-essentials.flatpakrefcol`
In my opinion the users shouldn't have to answer Yes N times to confirm the installation. Once should be enough. Same for root password if required

On flathub, collections could be public or secret, like [ Github's GISTS,](https://help.github.com/articles/about-gists/) so other users could "star" them and even make comments. This kind of interactions could help make a bigger community of users around flathub.  It can be also useful for companies to quickly install a set of tools required in workstations

The flatpakrefcol file coud be just a collection of links to flatpakref files:

```
[Flatpak Ref Col]
https://flathub.org/repo/appstream/org.gnome.Geary.flatpakref
https://flathub.org/repo/appstream/com.slack.Slack.flatpakref
https://flathub.org/repo/appstream/org.videolan.VLC.flatpakref
```

What do you think?

**Comment by alexlarsson** [comment]
I'm not sure i would say this is a killer feature, but it seems like an useful thing. It does complicate all the flatpak appstore implementations though, so needs careful consideration.

**Comment by jgarciao** [comment]
Maybe we should not invent a new file format and just use an appstream file to store the user's app picks collection.  The field *origin*  ([AppStream - Collection MetaData](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#sect-AppStream-XML)) could the the repo name

Maybe @hughsie @ximion or @aleixpol will be interested in this discussion

**Comment by hughsie** [comment]
Please not more file formats. We already have flatpakref, flatpak bundles, and flatpakrepo... I'm struggling as it is.

**Comment by matthiasclasen** [comment]
I don't think we want to make things any more complicated than they already are. Let users install one app at a time. It works for every other app store out there.

**Comment by jgarciao** [comment]
ok. Thanks for your feedback
