### ISSUE TITLE
Add "manual" extension special case

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1086]
The other day on IRC, I was discussing using extensions to install manuals. In GIMP, manuals are basically html pages which can be shown on F1. A user can install manuals in a specific language (doesn't have to install all languages).

I was told by @alexlarsson that probably it would be a better idea to make a special case for these, same as there is already a special case for locales, so that software installer (such as GNOME Software) can also special-case these. That sounds like a good idea.
So here I make a feature request to remember this and track the advancement of the request. :-)

**Comment by alexlarsson** [comment]
The locale-subset property of extensions should allow this now.
