### ISSUE TITLE
Add a portal to access the list of applications on the host

### ISSUE THREAD

**Issue by meghprkh** [flatpak/flatpak#1087]
In firefox when you download any file, there is an option to associate an application to open the file with directly instead of downloading it. This does not work in this [flatpak build](https://firefox-flatpak.mojefedora.cz/). Is this a non-resolvable bug due to the sandbox system? If so can the source code/build be modified so as to have this functionality since this is a important feature imo? (I am only a user so I dont know much)

![screenshot from 2017-10-07 19-26-43](https://user-images.githubusercontent.com/5979605/31308541-d9fddd44-ab67-11e7-961c-a4d3b7d973ce.png)

**Comment by TingPing** [comment]
It cannot be exposed currently because of the sandbox. There are security concerns with being able to launch any installed application with random data.

**Comment by alexlarsson** [comment]
I think firefox should use the open file portal to open the downloaded file, then the open would happen outside the sandbox, and we should be able to pick up e.g. installed pdf readers.

**Comment by chergert** [comment]
There is a cross-over here with a feature I need in Builder too. You can right-click a file in the project browser and "Open With" a given application populated in the menu. Those applications are loaded from GAppInfo. (This is mostly useful for opening things like images with `eog` or `gimp`).

Exposing the `GAppInfo` to the sandbox is certainly an information leak, but it could be a specific option that would mostly be used by creativity apps. There is probably a better solution though.
