### ISSUE TITLE
"iso-codes" package is not complete

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1096]
Your yocto build lists "iso-codes" package as available (cf. /usr/manifest.base) and the pkg-config file is indeed present (/usr/share/pkgconfig/iso-codes.pc) which means that a configure script would assume it is present.
In reality, I could only find 2 files from the packages:

> /usr/share/locale/en/LC_MESSAGES/iso_3166-2.mo
> /usr/share/locale/en/LC_MESSAGES/iso_3166_2.mo

A lot more are missing and that's a problem since if we base features on it, well these features get broken localizations.
Thanks!

**Comment by alexlarsson** [comment]
I'm not sure how this is supposed to work, but the english translation doesn't seem to have that file as you say, but e.g. the swedish one has:

```
ls /usr/share/locale/sv/LC_MESSAGES/iso_*
/usr/share/locale/sv/LC_MESSAGES/iso_15924.mo
/usr/share/locale/sv/LC_MESSAGES/iso_3166-2.mo
/usr/share/locale/sv/LC_MESSAGES/iso_4217.mo
/usr/share/locale/sv/LC_MESSAGES/iso_639-3.mo
/usr/share/locale/sv/LC_MESSAGES/iso_3166-1.mo
/usr/share/locale/sv/LC_MESSAGES/iso_3166-3.mo
/usr/share/locale/sv/LC_MESSAGES/iso_639-2.mo
 /usr/share/locale/sv/LC_MESSAGES/iso_639.mo
/usr/share/locale/sv/LC_MESSAGES/iso_3166_2.mo
/usr/share/locale/sv/LC_MESSAGES/iso_3166.mo
/usr/share/locale/sv/LC_MESSAGES/iso_639_3.mo
```

**Comment by matthiasclasen** [comment]
The way gettext generally works is that you get untranslated strings if there is no .no file. Which seems ok for English  ?

**Comment by Jehan** [comment]
Argh right of course!

Actually in GIMP, we use these to translate every language in itself (i.e. "français" instead of "French"), so we need all the `.mo` files for all languages (only at startup of course, since setlocale() is not thread-safe). That's why I was confused when I saw very few .mo. But you are right that when you break up the package per language, then for English only, it makes sense to only have a few files.
That's quite annoying but it goes with the logics you install only part of locales.

I guess you can close then. :-/
