### ISSUE TITLE
Kindly create an Ubuntu PPA for the 17.10 release (artful)

### ISSUE THREAD

**Issue by j1mc** [flatpak/flatpak#1104]
Someone made a comment on (now closed) Issue #773 requesting a PPA for the 17.10 release, but I thought I'd create a separate, stand-alone issue.

Please create a 17.10 PPA at your earliest convenience. Thanks!

**Comment by hadig** [comment]
...still not done. This is why the year of linux will never happen

**Comment by caravena** [comment]
Hello j1mc,

-> https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak?field.series_filter=artful

Regards,
--
Cristian

**Comment by j1mc** [comment]
Issue closed.  Thanks very much for updating the PPA
