### ISSUE TITLE
--nofilesystem issue

### ISSUE THREAD

**Issue by 2dsf** [flatpak/flatpak#1105]
Hi,

I'm trying to remove access to a folder partially un-sandboxed folder in Flatpak.  The folder is included in the flatpak repo by the developer [github discord.manifest](https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json)

After reading the [command references](http://docs.flatpak.org/en/latest/command-reference.html), i have been able to add and remove folders, but not the ones put in by default.

`flatpak --user override --nofilesystem=~/Videos com.discordapp.Discord`
or  
`flatpak --user override --nofilesystem=xdg-videos:ro com.discordapp.Discord`

It's been suggested to me that I try --remove-policy, but i have not been successful with it.

Thx

**Comment by amtlib-dot-dll** [comment]
It won't work +1

```shell
$ flatpak run --command=ls --nofilesystem=host --nofilesystem=home org.gnome.Builder
$ flatpak run --command=ls org.gnome.Builder
Desktop  Documents  Downloads  Music  Pictures	Public	Templates  Videos
$ flatpak override --user --nofilesystem=host --nofilesystem=home org.gnome.Builder
$ cat .local/share/flatpak/overrides/org.gnome.Builder 
[Context]
filesystems=
$ flatpak run --command=ls org.gnome.Builder
Desktop  Documents  Downloads  Music  Pictures	Public	Templates  Videos
```

I think the `override` feature is somehow crippled. ☹️

**Comment by alexlarsson** [comment]
This is https://github.com/flatpak/flatpak/issues/1232
