### ISSUE TITLE
firefox developer edition not install

### ISSUE THREAD

**Issue by Lvaskz** [flatpak/flatpak#1111]
hi, i tried to install firefox developer edition from terminal:
flatpak install --from https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxDevEdition.flatpakref
Installing: org.mozilla.FirefoxDevEdition/x86_64/master
Installing: org.mozilla.FirefoxDevEdition/x86_64/master from org.mozilla.FirefoxDevEdition-8-origin
[####################] Downloading files: 165/166 46,9 MB (199,4 kB/s)          
error: While charging app/org.mozilla.FirefoxDevEdition/x86_64/master from the remote repository org.mozilla.FirefoxDevEdition-8-origin: More input is needed

**Comment by TingPing** [comment]
That error has been happening since they set up that server (don't know whos at fault) but if you add the repo first then install it manually it tends to work.

**Comment by Lvaskz** [comment]
hi, can you tell me how ?

2017-10-17 14:47 GMT-06:00 TingPing <notifications@github.com>:

**Comment by mwleeds** [comment]
@Lvaskz Looks like there are instructions on https://firefox-flatpak.mojefedora.cz/

**Comment by Lvaskz** [comment]
ok thanks
