### ISSUE TITLE
.flatpak bundle does not recognize language system

### ISSUE THREAD

**Issue by Lvaskz** [flatpak/flatpak#1116]
Hi, I've been wondering if, .flatpak files could somehow become executable in .EXE style, without the need for gnome software or typing commands from the terminal?
I wonder why libreoffice, Inscape have this form of packaging and also firefox develop edition. is there some way in which after downloading the app.flatpak with double click, it is installed in the system and also recognizes the language of the OS? since the app.flatpak does not recognize the language of the system, they are only installed in English language.

OSlinuxmint 18.2
64 bits

**Comment by Lvaskz** [comment]
linuxmint 18.2
64 bits

**Comment by alexlarsson** [comment]
Yeah, the bundles don't currently include locale data, as per https://github.com/flatpak/flatpak/issues/165
Closing this as duplicate
