### ISSUE TITLE
Installing large bundles uses up a lot of memory

### ISSUE THREAD

**Issue by cpba** [flatpak/flatpak#1128]
Installing a 3GiB package can use around 6GiB of ram, this gets progressively worse the bigger the bundle is.

This makes flatpak difficult to use for packaging and distributing videogames, which can routinely be in the 10~50GiB range, which is a shame because they are otherwise ideal targets for flatpak.

**Comment by mwleeds** [comment]
I noticed this too the other day when I was making a 6 GB flatpak. The high memory usage seems to happen in both the `build-bundle` and `install` operations.

However this doesn't seem to happen when pulling the flatpak from a remote repo, so you still have that option.

**Comment by TingPing** [comment]
See also: #483

**Comment by alexlarsson** [comment]
Yeah, this is because of the way we use ostree to apply the bundles. Not great, but its some work to fix it...

**Comment by alexlarsson** [comment]
Closing this in favour of https://github.com/flatpak/flatpak/issues/483
