### ISSUE TITLE
Support multiple developer-supported runtimes

### ISSUE THREAD

**Issue by gjsman** [flatpak/flatpak#1129]
Developers should be able to support multiple runtimes, if they so choose, to avoid duplicate downloads.

For example, imagine there are 3 runtimes:
- org.gnome.Platform//3.26
- org.kde.Platform//5.11.0
- org.budgie.Platform//3.0.0

Lets say that, as a developer, I have tested my Flatpak, and it works on all three. However, currently I can only support one, and because org.gnome.Platform is most common right now, I probably will choose that. See what I mean?

**Comment by alexlarsson** [comment]
This is contrary to the point of flatpak, which is that you run exactly what the developers tested against. You can as a user run in some non-default runtime (run --runtime=XXX), but this is for development/testing only.

**Comment by gjsman** [comment]
@alexlarsson That is not what I meant. I actually raised this issue before, and I rephrased it to emphasize my real point. My point was that a developer may have tested it against 3 runtimes, but can only support one. Like, the developer _wants_ to support multiple runtimes to offer the least downloading times for his app.

**Comment by gjsman** [comment]
"which is that you run exactly what the developers tested against." - Yes, I mean, I might decide I want to support 3 runtimes, but can't do that. Not the user, the developer.

**Comment by matthiasclasen** [comment]
Why would you do that ? I think this is a far-fetched scenario.

**Comment by gjsman** [comment]
Mainly space savings. Why download a new runtime, if one you already have would have been marked by the developer as compatible?
