### ISSUE TITLE
rpm %post incompatible with ostree-for-system

### ISSUE THREAD

**Issue by cgwalters** [flatpak/flatpak#113]
Ironically,

```
%post
# Create an (empty) system-wide repo.
flatpak remote-list --system
```

won't work in an OSTree-for-system model.  I think the privileged helper needs to create-if-not-exists?

**Comment by alexlarsson** [comment]
We discussed this a bit, and I think the proper fix is for flatpak to handle a non-existing system repo in a non-fatal way, at least for the reading operations (list apps, list remotes, etc) this is simple, just return the empty lists. Then we need to make "add system remote" work for that case too.

I looked into this, and there are some complexities wrt libflatpak threadsafety that makes this somewhat hard, but it should be doable with some care.

**Comment by cgwalters** [comment]
Or we could install a systemd unit file which does create-if-not-exists ?

**Comment by cgwalters** [comment]
A workaround for this issue is to simply `sudo flatpak remote-list --system`.

**Comment by cgwalters** [comment]
This is still biting people trying out https://fedoraproject.org/wiki/Workstation/AtomicWorkstation .

WDYT about the systemd unit approach?

**Comment by cgwalters** [comment]
(I can write that patch easily enough...reworking flatpak like https://github.com/flatpak/flatpak/issues/113#issuecomment-229924407 would require me to learn a lot more of flatpak than I know right now)

**Comment by matthiasclasen** [comment]
I just ran into this again when trying atomic workstation. This pretty much breaks the out-of-the-box experience of gnome-software. We should really fix this

**Comment by matthiasclasen** [comment]
I think it would be great to have a systemd unit in the atomic workstation as a workaround until flatpak learns how to deal with nonexistent repos gracefully.

**Comment by cgwalters** [comment]
OK, I'll write one.

**Comment by cgwalters** [comment]
https://src.fedoraproject.org/rpms/flatpak/pull-request/1
