### ISSUE TITLE
Cannot use submodule commit whose commitid resolves to HEAD on a Github Pull Request on Flatpak 0.10 & Git <2.14

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#1133]
I'm not positive about which commit in git resolves the issue (that's a huge pain in the ass to bisect), but there's a combination of factors which leads to pain. For an easy example, try building https://github.com/directhex/pony-flatpak. The "good" behaviour is the build fails. The "bad" behaviour is the checkout fails.

On Flatpak 0.10, one new feature is to speed up builds, shallow clones are used. Part of this is submodule commitids are resolved to branches. For whatever reason, if a submodule points to a commit which is available as the tip of a pull request branch, then the fetch resolves to the pull request branch instead of the master branch (or any other branch containing that commit):

```
directhex@bubblegum:~/Projects/pony-flatpak$ flatpak-builder --force-clean pony com.pretty.ponies.json 
Emptying app dir 'pony'
Downloading sources
Fetching git repo git://github.com/directhex/pony-repo.git, ref refs/heads/master
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Fetching git repo git@github.com:directhex/wrench-aggregator.git, ref refs/pull/3/head
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
```

On git 2.14.1, this works fine:

```
Cloning into '/home/directhex/Projects/pony-flatpak/.flatpak-builder/build/pony-repo-4/arbitrary-submodule-with-PR-merge-as-latest'...
Submodule path 'arbitrary-submodule-with-PR-merge-as-latest': checked out '9633efeffd1d1453951af0464fdf1a7e2e5628a2'
```

On git 2.7.4, it fails the build:

```
fatal: reference is not a tree: 9633efeffd1d1453951af0464fdf1a7e2e5628a2
Unable to checkout '9633efeffd1d1453951af0464fdf1a7e2e5628a2' in submodule path 'arbitrary-submodule-with-PR-merge-as-latest'
```

Since PR refs are special-cased in the Github back-end, maybe Flatpak should be taught to avoid them? Or include a git version check on shallow cloning?

**Comment by directhex** [comment]
For a real, pony-free example, try https://github.com/mono/monodevelop tag monodevelop-7.2.0.636: https://jenkins.mono-project.com/view/Releases/job/release-flatpak-monodevelop/198/console

**Comment by alexlarsson** [comment]
For the record, we pull the tip of a pull request branch because there is no other way to pull a specific commit. If you pull a commit id directly you get a denied error from the server. If we can't find it at the tip of some ref, then we fall back to a deep clone.
