### ISSUE TITLE
Unable to perform Flatpak update

### ISSUE THREAD

**Issue by Veske** [flatpak/flatpak#1134]
I am unable to perform Flatpak update. I suspect that the problem arised when I tasked a removal of a flatpak package from Gnome software tool and started an flatpak update in terminal at the same time.

The errors look like this:

```
➜  ~ flatpak update
Looking for updates...
Updating: org.freedesktop.Platform/x86_64/1.6 from flathub
[####################] 8 delta parts, 1 loose fetched              
Warning: Failed to update org.freedesktop.Platform/x86_64/1.6: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to checkout ac14db14d7d89233c49e993469b6e1403bf2d193001aa4ee7c38ffe475ed6ffb into /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/.ac14db14d7d89233c49e993469b6e1403bf2d193001aa4ee7c38ffe475ed6ffb-SFR28Y: fgetxattr: No data available
Updating: org.gnome.Platform/x86_64/3.24 from gnome
[####################] Downloading: 2.1 MB/2.1 MB (513.9 kB/s)                 
Warning: Failed to update org.gnome.Platform/x86_64/3.24: While pulling runtime/org.gnome.Platform/x86_64/3.24 from remote gnome: opcode set-read-source: fgetxattr: No data available
Updating: org.gnome.Platform.Locale/x86_64/3.24 from gnome
[####################] 1 metadata, 0 content objects fetched; 313 B transferred in 2 seconds
Warning: Failed to update org.gnome.Platform.Locale/x86_64/3.24: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to checkout bab984606ce4e54fdb15cffd060a5fde1bbdd3eb59fafcaf8a407843ac7e7668 into /var/lib/flatpak/runtime/org.gnome.Platform.Locale/x86_64/3.24/.bab984606ce4e54fdb15cffd060a5fde1bbdd3eb59fafcaf8a407843ac7e7668-YOQX8Y: fgetxattr: No data available
Updating: org.freedesktop.Platform.Locale/x86_64/1.4 from gnome
^C
➜  ~ 

```

Probably what I did was not correct, but the tool should be smart enough to forbid an user doing something like that.

**Comment by mwleeds** [comment]
@Veske you should post what flatpak version you're using. There was a locking mechanism implemented in 0.9.98.

**Comment by alexlarsson** [comment]
Its trying to read xattrs for some reason, but failing. I believe there was a fix for a regression something like this in ostree recently, but i forgot the reasons. What ostree version are you on?

**Comment by Veske** [comment]
@mwleeds @alexlarsson 

```
flatpak --version
Flatpak 0.10.0

pacman -Q ostree 
ostree 2017.12-1
```
So I imagine I have the fixes that should prevent this? Any more info I can help you guys with?

**Comment by Veske** [comment]
Or maybe a way to just solve this? Reinstall did not seem to cut it.

**Comment by Gwend4l** [comment]
It seems I encounter the same problem:
```
$ flatpak --user update org.libretro.RetroArch                                                                                                                                                    Looking for updates...
Updating for user: org.freedesktop.Platform/x86_64/1.6 from flathub
[####################] Downloading: 1.7 MB/1.7 MB (82.1 kB/s)                  
Warning: Failed to update org.freedesktop.Platform/x86_64/1.6: While pulling runtime/org.freedesktop.Platform/x86_64/1.6 from remote flathub: opcode set-read-source: fgetxattr: No data available
Updating for user: org.freedesktop.Platform.Locale/x86_64/1.6 from flathub
[####################] 2 metadata, 0 content objects fetched; 794 B transferred in 1 seconds
Warning: Failed to update org.freedesktop.Platform.Locale/x86_64/1.6: While trying to checkout metadata subpath: fgetxattr: No data available
Updating for user: org.libretro.RetroArch/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred in 0 seconds
Error: Failed to update org.libretro.RetroArch/x86_64/stable: While trying to checkout bab84e41ca227b50749c694a384e37026ab6cbf1b3d84e2c7ba565540994636a into /home/funbox/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/stable/.bab84e41ca227b50749c694a384e37026ab6cbf1b3d84e2c7ba565540994636a-EQUWEZ: fgetxattr: No data available
error: One or more operations failed
```

**Comment by Veske** [comment]
Yeah... I got it once again also. Appeared out of nowhere again. Now I can atleast update my stuff, this error comes last always.

```
flatpak update
Looking for updates...
Updating appstream data for remote flathub
Error updating: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying appstream: fgetxattr: No data available
```

**Comment by arianvp** [comment]
Same problem here on

```
❯ flatpak --version
Flatpak 0.11.3
                                                                                
~   

```

**Comment by TheRoarkster** [comment]
I also have this problem, and it affects every application. 
`Flatpak 0.10.4`

```
libostree:
 Version: 2018.3
 Git: 0a81d897c917c9b7259b59a768e238e26640dd57
 Features:
  - libcurl
  - no-http2
  - libsoup
  - gpgme
  - libarchive
  - selinux
  - openssl
  - libmount
  - release

```

**Comment by nmusatti** [comment]
On CentOS 7.6 with `flatpak 1.0.2` I solved this problem by running

    flatpak repair [--user / --system]

As suggested in this [Red Hat Bugzilla issue](https://bugzilla.redhat.com/show_bug.cgi?id=1655953)

**Comment by Derpford** [comment]
```
> flatpak --version
Flatpak 0.10.4
> flatpak repair
...
error: Unknown command 'repair'
```

Annoyingly, this is the latest version of flatpak available for OpenSUSE Leap 15. Nuking the flatpak folder fixes it, though.

**Comment by slaffcheff** [comment]
I encounter issue when trying to run flatpak update on openSUSE Leap 15.

```
flatpak update
Looking for updates...
error: runtime/org.freedesktop.Platform.openh264/x86_64/19.08 needs a later flatpak version (1.4.2;1.2.5;1.0.9;)
```

> Information for package flatpak:
> --------------------------------
> Repository     : openSUSE-Leap-15.0-Update                  
> Name           : flatpak                                    
> Version        : 0.10.4-lp150.8.1                           
> Arch           : x86_64                                     
> Vendor         : openSUSE                                   
> Installed Size : 2.4 MiB                                    
> Installed      : Yes                                        
> Status         : up-to-date                                 
> Source package : flatpak-0.10.4-lp150.8.1.src               
> Summary        : OSTree based application bundles management

0.10.4 is the **LATEST** version -.-

**Comment by mwleeds** [comment]
@slaffcheff sounds like an issue to file with openSUSE

**Comment by slaffcheff** [comment]
@mwleeds i would say nope because i regularly update flatpak packages. And I suppose the old openSUSE release cannot handle new packages from flatpak. Current release is 1.5.0 and openSUSE latest release is 0.10.4 :) They need to fix this for sure.

**Comment by alittlebitofit** [comment]
I am using `Solus Mate 4.0`.

Current Flatpak version that released on 13 June, 2019 is `1.4.1`.

But when I `flatpak --version` it shows `Flatpak 1.0.9`.

I installed Flatpak just today and even tried to update using `flatpak update` and all it says is `Listing for updates...`.

Can anyone help me update it, please?

Thanks.

**Comment by mwleeds** [comment]
@alittlebitofit `flatpak update` only updates your installed flatpaks, not Flatpak itself. File an issue with your Linux distribution if you want them to update their version of Flatpak.

**Comment by Darcidride** [comment]
> On CentOS 7.6 with `flatpak 1.0.2` I solved this problem by running
> 
> ```
> flatpak repair [--user / --system]
> ```
> 
> As suggested in this [Red Hat Bugzilla issue](https://bugzilla.redhat.com/show_bug.cgi?id=1655953)

Just to let know everyone which is getting to this issue from there prefered search engine :

Debian unsatable / sid - Linux LUNE 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux

`flatpak --version`
Flatpak 1.6.3"

I executed a `flatpak repair --user && flatpak reair --system` and it fixed the issue `fgetxattr: No data available`
A shame flatpak itself doesn't let us know with a little message it can be the solution to our specific issue :(

**Comment by hexmode** [comment]
> I executed a `flatpak repair --user && flatpak reair --system` and it fixed the issue `fgetxattr: No data available`
> A shame flatpak itself doesn't let us know with a little message it can be the solution to our specific issue :(

I'm checking to see if there is an issue for this already and creating one if not.
