### ISSUE TITLE
Please add support for non-shallow clones in 0.10+

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#1137]
Flatpak 0.10 uses shallow clones, to save speed/bandwidth. Hooray! It would, however, be nice to be able to force a full clone - e.g. MonoDevelop uses `git log` to generate its own changelog and version number. On a shallow clone, all builds get a `.0.0` version suffix.

**Comment by alexlarsson** [comment]
To late, 0.10.2 already has it!
