### ISSUE TITLE
installed app ref not installed

### ISSUE THREAD

**Issue by Cyborgscode** [flatpak/flatpak#1139]
Bugzillalink: https://bugzilla.redhat.com/show_bug.cgi?id=1508400

Description of problem:

flatpak lists installed apps correctly, but denies knowlage of them, when you try to update them.

"flatpak update" was also not helping.

Version-Release number of selected component (if applicable):

0.9.7-1

Actual results:

[marius ~]$ /usr/bin/flatpak update app/com.belledonnecommunications.linphone/x86_64/4.1.1 Looking for updates... Fehler: app/com.belledonnecommunications.linphone/x86_64/4.1.1 not installed

Expected results: (if it's just the wrong error message )

[marius ~]$ /usr/bin/flatpak update app/com.belledonnecommunications.linphone/x86_64/4.1.1 Looking for updates... Fehler: app/com.belledonnecommunications.linphone/x86_64/4.1.1 no updates available

Additional info:

Ref                                                  Options     
com.belledonnecommunications.linphone/x86_64/4.1.1   user,current
org.freedesktop.Platform.GL.nvidia-375-66/i386/1.4   user,runtime
org.freedesktop.Platform.GL.nvidia-375-66/x86_64/1.4 user,runtime
org.freedesktop.Platform/x86_64/1.6                  user,runtime

[marius ~]$ /usr/bin/flatpak info "com.belledonnecommunications.linphone/x86_64/4.1.1" Ref: app/com.belledonnecommunications.linphone/x86_64/4.1.1 ID: com.belledonnecommunications.linphone Arch: x86_64 Branch: 4.1.1 Origin: com.belledonnecommunications.linphone-1-origin Commit: bae79f29ce390b6b28254cba0ae63f1bbb8d9a30f50acce422ce5ef1f1839441 Location: /home/marius/.local/share/flatpak/app/com.belledonnecommunications.linphone/x86_64/4.1.1/bae79f29ce390b6b28254cba0ae63f1bbb8d9a30f50acce422ce5ef1f1839441 Installed size: 315,4 MB Runtime: org.freedesktop.Platform/x86_64/1.6

**Comment by ihmels** [comment]
You have installed the Flatpak application _per-user_. If you want to update the application, you have to use the `--user` switch:

    flatpak --user update com.belledonnecommunications.linphone

**Comment by alexlarsson** [comment]
Yeah, need the --user flag.
