### ISSUE TITLE
Remotes with additional apps raises a confusing question

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#1141]
I was installing GNOME Recipes from Flathub today. When I did so I was asked the following.

> The remote 'flathub', at location https://flathub.org/repo/ contains additional applications.
> Do you want to install other applications from here? [y/n]

I was a bit confused here because I wasn't sure what flatpak would do if I said yes or no. It also gave me the impression that saying "yes" would install the additional  applications.

Maybe the question could be rephrased to something along the lines of "Should the remote be kept for future installations?".

**Comment by alexlarsson** [comment]
Yeah, that seems like a better phrasing.

**Comment by mwleeds** [comment]
Looks like this has been fixed
