### ISSUE TITLE
Allow svgz as an icon format for applications

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#1142]
Currently only svg is (and png and others). It's fairly common to use svgz and it has few obvious advantages (svg is a text format that compresses drastically). It would be okay to allow svgz along with svg.

**Comment by TingPing** [comment]
That is probably a request to extend the Icon Theme Spec?

> An icon file is an image that can be loaded and used as an icon. The supported image file formats are PNG, XPM and SVG. PNG is the recommended bitmap format, and SVG is for vectorized icons. XPM is supported due to backwards compability reasons, and it is not recommended that new themes use XPM files. Support for SVGs is optional.

https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

I don't know if in practice a launcher exists that supports svg but not svgz.

**Comment by alexlarsson** [comment]
I agree that supporting .svgz makes sense, but we can't just add it to flatpak. Once the upstream icon theme and desktop file specs support this we can add it.

**Comment by eszlari** [comment]
Flatpak could at least automatically gunzip svgz files. This way, not every project using them would have to be changed.

**Comment by TingPing** [comment]
It has been brought up twice in 3 years, I don't think its actually widely used.
