### ISSUE TITLE
Add a drag and drop portal

### ISSUE THREAD

**Issue by Kekun** [flatpak/flatpak#1143]
I tried to drag and drop a file into Geary to attach it to a mail, but it didn't work.

Dragging and dropping is an explicit request from the user to let the application open the file, having a portal to handle that would be great.

**Comment by matthiasclasen** [comment]
dnd is typically handled as part of the display protocol - for wayland, it is part of the wayland protocol, for X11, it is done via selections and client messages (xdnd). Thus the dnd transfer itself works fine. Whats missing here is a bit of special handling for the case where the data that is transferred consists of file system paths - the application inside the sandbox generally does not have the same view of the filesystem as the outside world, so somebody (most likely, the compositor), needs to translate the paths on the way into the sandbox, and possible export the files in the document portal to make them visible in the sandbox.

**Comment by TingPing** [comment]
See also: flatpak/xdg-desktop-portal#99

**Comment by mwleeds** [comment]
I don't think we need this issue open both here and in xdg-desktop-portal
