### ISSUE TITLE
make flatpak uninstall output smarter and/or more helpful

### ISSUE THREAD

**Issue by baedert** [flatpak/flatpak#1144]
When using `flatpak uninstall` from the command line, I basically always have to run `flatpak list` first. I usually either want to remove an app just by its name (e.g. peek or corebird) but that doesn't work of course since flatpak uses app ids, whch is good. Then I try to remember what the app id was exactly but they are long and so I have to resort to a `flatpak list`.

For example, when I want to uninstall Corebird, I can't just use `flatpak uninstall corebird` even though there's only one app installed with "corebird" in its app id (in this scenario; if there are multiple a fallback would have to be used of course). It would be cool if flatpak would try to figure out what I mean (e.g. starting from the end of the app id), then either uninstall the only hit or present me with a list of possible hits that I might have meant.

But when I use an invalid app id as in `flatpak uninstall foo.bar.baz` or just `flatpak uninstall` without any app id, the output could be more helpful, i.e. at least list the installed apps, especially in the case of an invalid app id. For a missing app id, the current output is helpful (even though I'd always pass `--help` to it anyway if I wanted to see that output).

**Comment by dennisotugo** [comment]
bump

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/flatpak/pull/2330 will make flatpak uninstall corebird work

**Comment by mwleeds** [comment]
Closing this since #2330 was merged. Personally I'm not convinced that uninstall should list every installed app if there aren't any matches.
