### ISSUE TITLE
Not nekohayo-proof (should handle interrupted operations gracefully)

### ISSUE THREAD

**Issue by nekohayo** [flatpak/flatpak#115]
I tried grabbing Pitivi's flatpak as per http://wiki.pitivi.org/wiki/Install_with_flatpak

This is what I got when executing https://git.gnome.org/browse/pitivi/plain/bin/pitivi.installer.desktop :
```
==========
Installing pitivi
==========
 
-> Installing org.gnome.Platform 3.20
 
Receiving delta parts: 9/9 9,6 ko/s 162,4 Mo/171,4 Mo 
^C
```

I cancelled it because after 2-3 hours it was clear the download was stalled for some reason unknown to me, so I re-ran the command and then I got:

```
==========
Installing pitivi
==========
 
-> Installing org.gnome.Platform 3.20
 
9 delta parts, 7 loose fetched; 8763 KiB transferred in 3 seconds
-> Installing org.gnome.Platform.Locale
 
4 delta parts, 55 loose fetched; 29184 KiB transferred in 11 seconds
-> Updating org.gnome.Platform 3.20
 
1 metadata, 0 content objects fetched; 313 B transferred in 1 seconds
-> Updating org.gnome.Platform.Locale
 
1 metadata, 0 content objects fetched; 313 B transferred in 1 seconds
Installing org.pitivi.Pitivi master...
 
6 delta parts, 31 loose fetched; 107678 KiB transferred in 58 seconds
 
(flatpak install:6871): flatpak-WARNING **: Error running trigger desktop-database.trigger: Executing child process "/usr/lib64/flatpak/bwrap" failed (No such file or directory)
 
(flatpak install:6871): flatpak-WARNING **: Error running trigger gtk-icon-cache.trigger: Executing child process "/usr/lib64/flatpak/bwrap" failed (No such file or directory)
 
(flatpak install:6871): flatpak-WARNING **: Error running trigger mime-database.trigger: Executing child process "/usr/lib64/flatpak/bwrap" failed (No such file or directory)
-> Updating org.pitivi.Pitivi master...
 
error: Unable to start app
```

And then, trying
```flatpak run org.pitivi.Pitivi```
will return the same error: Unable to start app.

Flatpak should be more nekohayo-proof, especially once GUIs start depending on it being cancellable and resumable during any operation.

**Comment by alexlarsson** [comment]
Are you using the fedora packages? If so, there was a packaging error and you need to install flatpak-libs (or wait for the new ones),

**Comment by alexlarsson** [comment]
(Ostree is very resumable, but its very design. Your error is something completely unrelated to that)

**Comment by nekohayo** [comment]
Hmm even with flatpak-libs installed the error persists, weird...

**Comment by alexlarsson** [comment]
Do you have a /usr/lib64/flatpak/bwrap ?

**Comment by nekohayo** [comment]
Turns out what was missing on my system was flatpak-builder, not flatpak-libs... but that was quite unclear from the terminal's output. It's also unclear why Pitivi's flatpak package needed that, but anyway, ideally the system should detect this sort of situation and propose to install flatpak-builder or any missing pieces...

**Comment by alexlarsson** [comment]
Seems this was due to the fedora 0.6.2 packaging issue
