### ISSUE TITLE
Deprecate and remove overly-powerful permissions

### ISSUE THREAD

**Issue by DemiMarie** [flatpak/flatpak#1152]
Currently, apps can request access to (for instance) a user’s entire home directory, to a shared `/tmp`, or to X11, the system message bus, or the session message bus.  **All of those can be used to run code with full privileges of the invoking user.**

**This is bad!**  Flatpak should not allow such powerful permissions.  Instead, requests for any file that doesn’t belong to the app should be forced to go through a proxy, which allows the user to select a file (and which can deny the request).  There is no reasonable way for a user to accept or deny requests for X11 or the system or user message busses, so these should never be allowed – **Flatpak must have a hard dependency on Wayland, or launch a subsidiary X server for each instance of each app.**

This will require that applications be modified to access user files via the provided Flatpak APIs rather than standard OS APIs, but I believe the tremendous security win (essentially, **being able to download any arbitrary Flatpak program and run it without worrying that it will compromise your system** – a guarantee that iOS and Android have offered since the very beginning) to be more than worth it.  Application developers *will* need to get used to a Web-style model however (where the user, not the program, controls which files are opened).

**Comment by cgwalters** [comment]
The problem of course is access to X11; that'd impact everything.  Though I could see it being useful to have the child X server be a builtin feature...there's lots of precedent for this.

I'd love to have a global switch which forces off access to `~`, or perhaps better, supported redirecting requests for `~` to e.g. `~/ContainerHome` or whatever I choose.

**Comment by TingPing** [comment]
It just has to be a slow transition, and perhaps less marketing calling it "secure" in the short term. Too many applications have to have holes to be usable, and "secure" also depends upon your definition. For example direct video card access is potentially very scary but we are a ways off from having a secure alternative to that (which will be much slower).

**Comment by alexlarsson** [comment]
We want to ask for permissions before install and on update, tracked here: https://github.com/flatpak/flatpak/issues/275

However, completely dissallowing this is not a goal. We want to allow packaging existing apps, and most existing apps will not work without these permissions. In the future as we make the portals framework work and convert apps to use it things will get better, but right now if we didn't have this flatpak would be useless for anything but games.

We do support overriding app permissions, and we should perhaps have a global override feature that affects all apps.

**Comment by DemiMarie** [comment]
@TingPing What would the secure alternative be?

@cgwalters I very much believe that we need to use a child X server and/or require Wayland as a mandatory dependency.

**Comment by TingPing** [comment]
> @TingPing What would the secure alternative be?

Few options like just relying on software rendering or something like [virgl](https://virgil3d.github.io/).
I vaguely remember another low level GPU virtualization research project but I can't find it.

**Comment by DemiMarie** [comment]
What does Chromium do?

**Comment by TingPing** [comment]
@DemiMarie It doesn't expose normal OpenGL to websites it only exposes WebGL which has a few behaviors designed for better security such as zeroing out any memory before its handed to you.

**Comment by DemiMarie** [comment]
I mean, “What does Chromium’s sandbox do regarding OpenGL?”

**Comment by TingPing** [comment]
@DemiMarie Nothing, because websites don't use OpenGL directly nor do they have kernel access directly like Flatpaks.

**Comment by DemiMarie** [comment]
I thought the Chromium sandbox proxied all OpenGL access.

**Comment by amtlib-dot-dll** [comment]
From https://fedoraproject.org/wiki/Changes/WorkstationOstree:

* Wayland-related tasks
  * __Make per-app xwayland possible for X apps__
  * Kill abstract sockets that are problematic for sandboxing: X, dbus, ...

I am staying tuned 😶

**Comment by DemiMarie** [comment]
@TingPing Chrome content processes cannot access OpenGL directly.  All OpenGL calls are proxied through a GPU process.  Flatpak should take a similar approach.

**Comment by alexlarsson** [comment]
@DemiMarie Chrome only runs javascript using an OpenGL subset (webgl). Running arbitrary code and proxying its GPU access is not possible.

**Comment by amtlib-dot-dll** [comment]
@mat8913 

> Any updates on this?

I'm afraid not, though I'm not concerned on this since long ago

**Comment by DemiMarie** [comment]
May I ask why?

**Comment by amtlib-dot-dll** [comment]
@DemiMarie There isn't any more information about this apart from that website :man_shrugging:

**Comment by Mikenux** [comment]
@DemiMarie: I think you can close this one as there are specific issues open.

**Comment by DemiMarie** [comment]
@Mikenux I think you’re correct.  Also the OpenGL remoting idea turned out to be terrible.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flatpak/flatpak/issues/1152#issuecomment-2323041400

@DemiMarie, in which case, is this issue really moreso completed or not planned?

**Comment by DemiMarie** [comment]
> > [#1152 (comment)](https://github.com/flatpak/flatpak/issues/1152#issuecomment-2323041400)
> 
> @DemiMarie, in which case, is this issue really completed, or more-so not planned / invalid?

 Not plan I think.

**Comment by RokeJulianLockhart** [comment]
@DemiMarie, in which case, you might be interested in https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue
