### ISSUE TITLE
flatpak --user install seems to write to root partition

### ISSUE THREAD

**Issue by kozec** [flatpak/flatpak#1154]
While trying to install large package, I'm constantly getting "No space left on device" error despite my home partition having plenty of free space. As clearly related problem, free space on my _root_ partition drops to zero whenever I run `flatpak --user install` command.

What could be causing this behavior?

**Comment by mwleeds** [comment]
You could look in `/tmp/` and `/var/tmp/` to see if flatpak is writing in one of those, or use `strace -y` to find out.

**Comment by alexlarsson** [comment]
I wouldn't be surprised if we write some to /var/tmp, but it shouldn't be all that much.
Can you try to `strace -y -f -o flatpak.log flatpak --user install ...` it to see where it is getting the ENOSPACE error.
