### ISSUE TITLE
Considering exposing flatpak_dir_get_default_locale_languages as public API

### ISSUE THREAD

**Issue by smspillaz** [flatpak/flatpak#1156]
It'd be useful to use this in our system updater to figure out which apps should be automatically installed on system updates, considering that we have different app ID's per language. This issue is here to track whether we should make this public API.

**Comment by alexlarsson** [comment]
Do you need the "default" setting? Could you not call flatpak_installation_get_config("languages")  and get the current value? It will be the default unless you have overridden it, and maybe in that case the overridden value is what you want?

**Comment by wjt** [comment]
#3058 actually has made this public API, I think?

**Comment by pwithnall** [comment]
Yup, `flatpak_installation_get_default_languages()` is present since 1.5.0 now. It returns the value of `xa.languages` (if set), otherwise the value of `flatpak_dir_get_default_locale_languages()`.
