### ISSUE TITLE
libflatpak: Provide API to list apps in USB remotes

### ISSUE THREAD

**Issue by joaquimrocha** [flatpak/flatpak#1159]
Ostree has p2p capabilities which allow to pull from repos in removable mounts and through LAN peers. However, there's no API in Flatpak that we can use to e.g. list apps that are in those "special" repos, so we cannot do things like showing a USB category in GNOME Software with all the apps that are in a USB drive that the user's just plugged in.

Because of the way that the appstream branches are configured, simply pointing a new remote to the repo URI in a USB drive is not enough, so we may need some changes to make this work.

Specifically we need a way to list refs coming from p2p locations, as well as get the appstream files from those locations (or seamlessly update the appstream files of each remote from those locations).
I am still going through the implications that the current design gives us before I can propose a more specific suggestion for the new API.

**Comment by pwithnall** [comment]
I’d propose something like this for the new API:
```
GPtrArray/*<FlatpakRemote*>*/ *
flatpak_installation_list_remotes_by_type_sync (FlatpakInstallation *installation, FlatpakRemoteType *remote_types, gsize n_remote_types, GCancellable *cancellable, GError **error);
```

It would list available remotes which have a type in the set `remote_types`. For LAN or USB remotes, it would create a new (temporary) `FlatpakRemote` which points to the right URI, and has the right GPG keys associated with it. You could then pass the `FlatpakRemote`s to other existing libflatpak APIs to list refs from them, etc.

Internally, this would be implemented by:
 * Grabbing all the collection IDs from the OSTree configuration in the `FlatpakInstallation`’s repository
 * Calling `ostree_repo_find_remotes()` with a set of ($collection_id, appstream/$arch) refs for the set of collection IDs, and passing it a set of `OstreeRepoFinder` instances corresponding to the set of `remote_types` passed in
 * Converting the resulting `OstreeRepoFinderResult`s into `FlatpakRemote`s

**Comment by mwleeds** [comment]
AFAIK we don't need this API any more. Currently GNOME Software is able to show a category listing the apps on a USB drive using the appstream data.
