### ISSUE TITLE
Flatpak Ubuntu repo deleted?

### ISSUE THREAD

**Issue by Alkaris** [flatpak/flatpak#1166]
I added the repo for Ubuntu 16.04, 16.10, and 17.04 but once I've added the repo and updated the repo list it just gives me

`E: Unable to locate package flatpak`

I did the following;

```
$ sudo add-apt-repository ppa:alexlarsson/flatpak
$ sudo apt update
$ sudo apt install flatpak
```
Result;

`E: Unable to locate package flatpak`

I go to a browser to browse the repo, but there are no Deb files or deb-src files anywhere, so did they get deleted or what?

**Comment by alexlarsson** [comment]
Weird, it seems to be there to me, and its still at https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak/+packages

**Comment by Ads20000** [comment]
The files are [definitely there](https://launchpad.net/%7Ealexlarsson/+archive/ubuntu/flatpak/+packages) when you browse for them
![screenshot from 2017-11-28 23-10-52](https://user-images.githubusercontent.com/3178485/33349304-6a5695d2-d491-11e7-921b-1c1181589af8.png)

**Comment by Alkaris** [comment]
files seem to be there, but trying to download them says they don't exist.

**Comment by Ads20000** [comment]
I can download the [amd64 Xenial Deb](https://launchpadlibrarian.net/346963773/flatpak_0.10.1-0alexlarsson1~xenial_amd64.deb) fine :) You might want to [ask a question about Launchpad](https://answers.launchpad.net/launchpad/+addquestion) (or [file a bug](https://bugs.launchpad.net/launchpad/+filebug)) describing your issue.

**Comment by mwleeds** [comment]
Sounds like perhaps an issue to be filed against Ubuntu
