### ISSUE TITLE
problem with telegram flatpak

### ISSUE THREAD

**Issue by MakuSensei** [flatpak/flatpak#1168]
• [7:54:16] ~ » flatpak run org.telegram.desktop         
This application failed to start because it could not find or load the Qt platform plugin "flatpak"
in "".

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Reinstalling the application may fix this problem.

**Comment by alexlarsson** [comment]
Please file application bugs with the individual packages. 
In this case: https://github.com/flathub/org.telegram.desktop

**Comment by TingPing** [comment]
I would suspect this would be a regression in the KDE runtime itself though.
