### ISSUE TITLE
Small error in license headers

### ISSUE THREAD

**Issue by KAMiKAZOW** [flatpak/flatpak#117]
The license headers refer to a GNU Lesser General Public License version 2.
No such license exists.  It appears that the author just took the standard GPL header and put a "Lesser" in front of the license name. The Lesser GPL numbering starts at version 2.1.

**Comment by matthiasclasen** [comment]
its a pretty common and harmless misstatement that you'll find all over the place. When somebody refers to "version 2 of the LGPL", it is generally understood to mean 2.1

**Comment by alexlarsson** [comment]
Yeah, this was inherited by copying the header boilerplate from Gtk I think, which has a similar issue.
There is a "LGPL 2", but that one is called "Library GPL", not "Lesser GPL".

Still, would be nice to change this to 2.1.

**Comment by alexlarsson** [comment]
(Especially since the COPYING file is 2.1)

**Comment by KAMiKAZOW** [comment]
It's not the end of the world (esp. since "or any later version" is in place anyway) but technically it still wrong. 😉

**Comment by matthiasclasen** [comment]
A patch would be welcome, I guess.

**Comment by matthiasclasen** [comment]
fixed now
