### ISSUE TITLE
Autostart support

### ISSUE THREAD

**Issue by pulb** [flatpak/flatpak#118]
Some daemon-like applications like [Mailnag](https://github.com/pulb/mailnag) store .desktop files in ~/.config/autostart so they’re executed on session start. Does flatpak has support for this?

**Comment by alexlarsson** [comment]
We can't expose random files into autostart, because these will be run on the host side and would completely escape the sandbox. Might be nice to have some built-in support that starts the sandboxed version though.

**Comment by TingPing** [comment]
There also needs to be some clear way to toggle it, either by a portal so the app can expose a UI, a command, or relying on desktops adding this.

**Comment by mjog** [comment]
Geary could use something like this for its "Always watch for new mail" feature - enabling/disabling that pref installs/deletes a desktop file in `~/.config/autostart`that launches Geary using `--hidden` at startup, so it starts running in the background when the user logs in.

I can work around this using `--filesystem=xdg-config/autostart:create` for now though.

**Comment by hadess** [comment]
You need to have 2 moving parts here, whether the application is allowed to run in the background, and whether the app requested to be run in the background. The first one needs to be provided by a Flatpak portal, and be designed such that it allows the creation of a configuration panel to control the toggle, and a store for the application to ask to be run in the background. Again, this cannot be solely under the application's control as you'd likely want to be able to enable the functionality by default, but still control whether the app gets its wish in the configuration dialogue.

**Comment by TingPing** [comment]
This was discussed a bit at GUADEC, some random thoughts:

- Portal sounds reasonable
- Should be a UI to allow background apps in g-c-c
  - Eventually track what is foreground/background
- Want a way to set custom exec args
  - Maybe put it in the `.desktop` file at export time, handles escaping/flatpak details

**Comment by matthiasclasen** [comment]
I've started to work on this.
Rough plan is:
- add a --background option to flatpak run that makes it fail unless the app has a 'run in background' permissiob
- export autostart file, rewrite Exec to use 'flatpak run --background'
- Add a portal method to let apps request 'run in background' privileges
- Maybe let that portal create an autostart file if one does not exist
- Have something monitor apps that are running in the background and kill them if they are not allowed to

**Comment by mjog** [comment]
This sounds great! Would the autostart file be removed when the 'run in background' permission is revoked? Also, would be it possible to expose some API in GLib for enabling/disabling autostart for an app that works with the portal when running under Flatpak?

In Geary, the "start in the background" pref actually does double work: It creates an autostart file, but does so with an extra "--hidden" command line arg to the Exec line. This means while the app is launched on login, the GUI only shows up when the icon is first clicked. Does what you have in mind handle that sort of use case?

Cheers!

**Comment by matthiasclasen** [comment]
The way this will look from the application side is:
- you install an autostart file with an Exec line that does what you want (can add --hidden there)
- flatpak will rewrite the Exec line to prepend "flatpak run --background"
- flatpak run --background will only launch the app if the 'run in background' permission is set

I envision that the control center will show a 'run in background' switch in the applications panel.

No library api for this at the moment. Will see about this later.

**Comment by hadess** [comment]
> * Add a portal method to let apps request 'run in background' privileges

You will also need a way for the application to query whether running in the background is allowed, so the app's interface can be adjusted after the initial request has been made and rejected, for example.

**Comment by matthiasclasen** [comment]
This was handled on the portal side

**Comment by Skycoder42** [comment]
@matthiasclasen Could you post a link to the documentation regarding this feature?

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.Background.xml

**Comment by leinardi** [comment]
I'm sorry if I'm asking something stupid but I can't really find any documentation on how to use this new portal feature. I opened all the link of this issue and went through all the issues linked here but I haven't found a single Pull Request or explanation on how to use it.

I understand the general idea:
> * add a --background option to flatpak run that makes it fail unless the app has a 'run in background' permission
> * export autostart file, rewrite Exec to use 'flatpak run --background'
> * Add a portal method to let apps request 'run in background' privileges
> * Maybe let that portal create an autostart file if one does not exist
> * Have something monitor apps that are running in the background and kill them if they are not allowed to

1. But what is the exact permission that I need to add? 
2. Where is documented? 
3. Is the rewrite of the Exec done in a completely transparent way?
4. Is there already an application that is taking advantage of it so that I can check how a working implementation looks?

**Comment by matthiasclasen** [comment]
We ended up not adding the --background option to flatpak

I'll try to write up some docs for this

**Comment by leinardi** [comment]
Any news about the missing documentation? Can we re-open this issue until there is a documented way to allow a flatpak application to autostart itself on login?

**Comment by TingPing** [comment]
The docs were linked: https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.Background.xml#L82

This doesn't seem to be in a release yet though.

**Comment by davidstrauss** [comment]
> This doesn't seem to be in a release yet though. (EDIT: It should be but I didn't see it locally)

I definitely have the relevant XML files locally on my Fedora 30 system.

**Comment by leinardi** [comment]
I'm sorry but I still don't understand how to use this xml to autostart a flatpak application on login. Can someone provide a working example of some app already using it or some more "for dummies" documentation?

**Comment by TingPing** [comment]
@leinardi Here is a WIP for an easy api to use this: https://github.com/matthiasclasen/libportal/pull/1

**Comment by leinardi** [comment]
Thanks, I've subscribed the PR.

**Comment by shinjiku01** [comment]
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/gwe --file-forwarding  @@u %U @@

**Comment by leinardi** [comment]
> /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/gwe --file-forwarding @@U %U @@

Could you explain what is this and how to use it?

**Comment by TingPing** [comment]
Its the content of a desktop file, I have no idea what point they are making.

**Comment by davidrhoderick** [comment]
> > /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/gwe --file-forwarding @@U %U @@
> 
> Could you explain what is this and how to use it?

I have no idea what the goal of @shinjiku01's response was but I looked at my desktop file for GreenWithEnvy and the only difference was a capital "U" in "@@U" instead of "@@u".  So I tried that and it did nothing so I'm not sure there is any use in their contribution without added clarification.

**Comment by pavangayakwad** [comment]
> /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/gwe --file-forwarding @@U %U @@

yep! I added this in "startup applications" and it worked!

**Comment by DenKov07** [comment]
Hi! I fave PopOS 22.04 and it's work for me:
```
nano ~/.config/autostart/gwe-autostart.desktop
```

```
[Desktop Entry]
Type=Application
Name=GWE
Comment=GPU Fan and Power management
Exec=/usr/bin/flatpak run com.leinardi.gwe --hide-window
Terminal=false
Hidden=false
NoDisplay=false
X-GNOME-Autostart-Enabled=true
StartupWMClass=gwe
```

`com.leinardi.gwe` - you can check it like this:
```
flatpak list | grep gwe
```

and don't forget to install it if you don't have this library installed yet:
```
sudo apt install libappindicator3-1
```


P.S. 
I have it working with `GreenWithEnvy   com.leinardi.gwe        0.15.9  stable`
