### ISSUE TITLE
Required runtime was not found in a configured remote

### ISSUE THREAD

**Issue by pipiscrew** [flatpak/flatpak#1182]
On archlinux : 

flatpak install --user --from https://download.mono-project.com/repo/monodevelop.flatpakref

Installing: com.xamarin.MonoDevelop/x86_64/stable
Required runtime for com.xamarin.MonoDevelop/x86_64/stable (org.freedesktop.Sdk/x86_64/1.4) is not installed, searching...
The required runtime org.freedesktop.Sdk/x86_64/1.4 was not found in a configured remote.

please advice!

**Comment by Lonsfor** [comment]
did you add the flathub repo? https://flathub.org/#using

**Comment by pipiscrew** [comment]
I uninstall it but I will try, this should be the solution^

thanks

**Comment by TingPing** [comment]
The `.flatpakref` already specifies the RuntimeRepo so perhaps you have a really old version of `flatpak?

**Comment by pipiscrew** [comment]
I follow the steps by 
http://www.monodevelop.com/download/linux/

now checking again, on **ubuntu** this time, Im getting 

> 
> flatpak install --user --from https://download.mono-project.com/repo/monodevelop.flatpakref
> This application depends on runtimes from:
>   https://sdk.gnome.org/repo/
> Configure this as new remote 'gnome' [y/n]: n
> Installing: com.xamarin.MonoDevelop/i386/stable
> Warning: Can't find dependencies: No entry for app/com.xamarin.MonoDevelop/i386/stable in remote summary flatpak cache 
> Installing: com.xamarin.MonoDevelop/i386/stable from com.xamarin.MonoDevelop-origin
> error: No such ref 'app/com.xamarin.MonoDevelop/i386/stable' in remote com.xamarin.MonoDevelop-origin

running @Lonsfor solution aka :  

> flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

end up with : 

> flatpak install --user --from https://download.mono-project.com/repo/monodevelop.flatpakref
> This application depends on runtimes from:
>   https://sdk.gnome.org/repo/
> Configure this as new remote 'gnome' [y/n]: n
> Installing: com.xamarin.MonoDevelop/i386/stable
> Warning: Can't find dependencies: No entry for app/com.xamarin.MonoDevelop/i386/stable in remote summary flatpak cache 
> Installing: com.xamarin.MonoDevelop/i386/stable from com.xamarin.MonoDevelop-1-origin
> error: No such ref 'app/com.xamarin.MonoDevelop/i386/stable' in remote com.xamarin.MonoDevelop-1-origin

1st time **com.xamarin.MonoDevelop-origin**  2nd ** com.xamarin.MonoDevelop-1-origin**

**Comment by pipiscrew** [comment]
doh, 
https://bugzilla.xamarin.com/show_bug.cgi?id=51534
