### ISSUE TITLE
 GPG signatures found, but none are in trusted keyring

### ISSUE THREAD

**Issue by afranke** [flatpak/flatpak#1187]
I got the following error for a while. Update via GNOME Software works without an issue. This is on an up to date Fedora 26.

```
$ flatpak update
Looking for updates...
Error updating remote metadata for 'gnome': GPG signatures found, but none are in trusted keyring
$ flatpak remote-list --show-details 
Name                            Title   URL                                      Priority Options            
flathub                         Flathub https://flathub.org/repo/                1        system             
gnome                           -       http://sdk.gnome.org/repo/               1        system             
org.perezdecastro.Revolt-origin Vector  https://flatpak.perezdecastro.org/revolt 0        system,no-enumerate
```

Let me know if you need more details.

**Comment by mwleeds** [comment]
Check if `/var/lib/flatpak/repo/gnome.trustedkeys.gpg` exists

**Comment by afranke** [comment]
It doesn’t! How do I fix it?

**Comment by mwleeds** [comment]
`flatpak remote-delete --force gnome; flatpak remote-add gnome https://sdk.gnome.org/gnome.flatpakrepo`

I wonder how the remote was added without the GPG keys

**Comment by afranke** [comment]
That indeed fixed it. I have no idea how it got in that state, but I started using flatpak quite early. Is it possible that I added the repo before there was GPG support?

**Comment by mwleeds** [comment]
It's possible you did something like `flatpak remote-add gnome https://sdk.gnome.org/repo/` without `--gpg-import`. For me that gives the `GPG signatures found, but none are in trusted keyring` error but adds the remote anyway. Or maybe you passed `--no-gpg-verify` for some reason.

**Comment by afranke** [comment]
I remember following instructions from a website but not the specifics, so maybe these instructions told me to do that. Probably no bug then, closing this.
