### ISSUE TITLE
Add "check-export" function

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#120]
To export a build to a repo, you'd run `flatpak build-export` after all your builds are done, and manifest files created. Adding a `check-export` function to flatpak before that would allow to:
 - warn about binaries that aren't supported by the target architecture
 - warn about files in the export/ sub-directory that won't be used by anything (eg. anything other than .desktop and icons)
 - check that the binaries are self-sufficient (eg. all the libraries are either in the bundle or in the platform they depend upon)
 - check the desktop file, manifest file, etc. for syntax and style errors (default executable not existing, unknown context options, etc.)

This would make it harder to create broken flatpak bundles, and make it easier to debug problems while creating them, especially when built from binary releases.

(I ended up creating a broken flatpak for a game because the original installer ships plenty of libraries, even some replacing platform ones, but not libcaca.so.0 because that's such a common lib...)

**Comment by alexlarsson** [comment]
We do some checks in build-export and print warnings about them. Is it good enough to expand these, or do we really want a different command to do it?

**Comment by hadess** [comment]
> We do some checks in build-export and print warnings about them.

It didn't warn about desktop file and icons before in the wrong directory in my tests.

>  Is it good enough to expand these, or do we really want a different command to do it?

I'd prefer a separate one, as it would allow either ignoring the warnings, or making them fatal. In my case, I'd probably want to make them fatal.

**Comment by matthiasclasen** [comment]
How about build-export --dry-run ?

**Comment by hadess** [comment]
A dry-run option would be fine as well.

**Comment by matthiasclasen** [comment]
I've added more validation for exported files.
