### ISSUE TITLE
errors on site flatpak.org

### ISSUE THREAD

**Issue by isinelobov** [flatpak/flatpak#1200]
Links from main page get 404.
http://flatpak.org/getting
http://flatpak.org/apps
http://flatpak.org/hello-world
http://flatpak.org/faq
404 Not Found
nginx/1.10.2

**Comment by ramcq** [comment]
Thanks for your report! Fixed. We're moving the site to be hosted on flathub.org so that we can enable HTTPS. https://github.com/flatpak/flatpak.github.io/issues/74
