### ISSUE TITLE
RFE: Support for drop-in remote reference files for flatpak configuration

### ISSUE THREAD

**Issue by Conan-Kudo** [flatpak/flatpak#1209]
For configuring flatpak to be preloaded with certain remotes, it'd be great if flatpak supported drop-in configuration files for identifying remotes and configuring them.

For example, vendor/distributor supplied remotes installed in `/usr/share/flatpak/remotes.d` would be remotes that the vendor/distributor supplies in the same vein that Yum/DNF repos are supplied in `/etc/yum.repos.d`.

User-added global remotes could be installed to `/etc/flatpak/remotes.d` (to differentiate from vendor/distributor provided ones), as well as configuration overrides in a similar manner (maybe `/etc/flatpak/remotes.d/<remote>.override.d/` like systemd? or something else).

This would make it tremendously saner for shipping default flatpak remotes (as I am considering for Mageia 7).

**Comment by alexlarsson** [comment]
Flatpak supports this [the same way ostree does](https://www.mankier.com/5/ostree.repo-config#/Etc/Ostree/Remotes.D), although the path used `/etc/flatpak/remotes.d`.
