### ISSUE TITLE
cjk input method is forbidden

### ISSUE THREAD

**Issue by ellicefix** [flatpak/flatpak#1211]
I think you are a group of retarded people. Do you know that there is a place called "CJK" on the planet? When people use the operation system, they need to use the unique input method software. At present, the packaging format you make doesn't open the interface to input method, so that people here can't use their input method. You yourself say, are you a bunch of idiots?

**Comment by alexlarsson** [comment]
There is support for input methods, but i'm no replying to garbage like this.
