### ISSUE TITLE
nvidia driver for nvidia-387-34?

### ISSUE THREAD

**Issue by dspmathguru** [flatpak/flatpak#1212]
Hi,

How hard is it to get a driver for nvidia-387-34

Thanx,
Richard

**Comment by TingPing** [comment]
They were added yesterday: https://github.com/flatpak/freedesktop-sdk-images/commit/366d19a2aba01f9b59eeecc8c217e805a63aa33b

(Maybe didn't make it to the server yet?)

**Comment by alexlarsson** [comment]
Yeah, not sync:ed yet, will be there soon.
