### ISSUE TITLE
Where do the configuration, profiles, or settings of Flatpak packages live?

### ISSUE THREAD

**Issue by emeydoubletee** [flatpak/flatpak#1214]
**Distro:**

Linux Mint 18.3

**Flatpak Version**:

0.10.0

****

This is a question **not** an issue. 

I would like to know I can go about making a backup of the _config files_, _profiles_ or _settings_ and be able to restore or use them on a different machine or after a clean install.
 
Typical packages store their profiles and settings in `~/.PackageName`, others in `~/.config/PackageName`, or both.

For example, Atom stores packages in `~/.atom` and configuration files in `~/.config/Atom`.

I would then run a script that performs a backup:

```
~ $ rsync -aq --delete ~/.atom/ /Path-To-Backup-Drive/home-dir/atom
~ $ rsync -aq --delete ~/.config/Atom/ /Path-To-Backup-Drive/config-dir/atom
```

In this manner, I'm able to restore and load the exact same settings on a different computer or on a clean install.

For Flatpak, I was able to follow the general path for both user and system installs, but I didn't see a directory that contains something similar to what the example above contain.

- `user` path output:

    ```
    ~ $ ls ~/.local/share/flatpak/app/App-Name/x86_64/stable/Really-Long-Number/
    ~ $ deploy export/ files/ metadata*
    ```

- `system` path output:

    ```
    # ls /var/lib/flatpak/app/App-Name/x86_64/stable/Really-Long-Number/
    # deploy export/ files/ metadata
    ```

How would I go about performing a backup and restoration of _config files_, _profiles_ or _settings_ on Flatpak applications? 

I'm trying to wean myself from using PPAs. I'm thinking of using _mostly_ Flatpak hopefully more in the future as more applications become available.

**Comment by chergert** [comment]
To ensure that applications have private storage space (and cannot snoop on each other), the various XDG dirs are changed from the user defaults. You can find them in `~/.var/app/$app_id/$xdg_dir`. So the `.config` that the `org.gnome.Builder` Flatpak'd application would use is `~/.var/app/org.gnome.Builder/config/`.

You can verify this with something like:

```sh
$ flatpak run --command=bash org.gnome.Builder
$ echo $XDG_CONFIG_HOME
/home/christian/.var/app/org.gnome.Builder/config
```

Keep in mind that applications still might use an additional subdirectory such as `gnome-builder` in the above case. So `.config/gnome-builder/` is instead `~/.var/app/org.gnome.Builder/config/gnome-builder` in it's application private space.

**Comment by emeydoubletee** [comment]
Thank you! :relieved: Whew! This was the only thing stopping me from switching my other apps to Flatpak. I didn't know about the existence of `~/.var`.

**Comment by RoyiAvital** [comment]
What about the Desktop Shortcuts?
Where do they go?

For instance in Linux Mint I can see launchers for Flatpak applications in Start Menu but I can't find their `.desktop` files.

**Comment by TingPing** [comment]
> What about the Desktop Shortcuts?

`/var/lib/flatpak/exports/share/applications` and `~/.local/share/flatpak/exports/share/applications`

**Comment by beedell-roke** [comment]
> [`#issuecomment-347752940`](https://github.com/flatpak/flatpak/issues/1214#issuecomment-347752940)

@chergert, I've run `perf record --debuginfod --call-graph dwarf io.github.alainm23.planify` inside `flatpak run --command=sh --devel io.github.alainm23.planify`, and see:

<blockquote>

~~~sh
[📦 io.github.alainm23.planify ~]$ ls /home/RokeJulianLockhart
perf.data  perf.data.old
~~~

</blockquote>

However, neither of the undermentioned contain it:

1.	<blockquote>

	~~~sh
	RokeJulianLockhart@Beedell:~$ flatpak info --show-location io.github.alainm23.planify
	/var/lib/flatpak/app/io.github.alainm23.planify/x86_64/stable/aec47960e9efb99d0efaf8b6b1799733f4a573babaf68d6795f5fdceaf5459d9
	~~~

	</blockquote>

1.	<blockquote>

	~~~sh
	[📦 io.github.alainm23.planify ~]$ echo $XDG_CONFIG_HOME
	/home/RokeJulianLockhart/.var/app/io.github.alainm23.planify/config
	~~~

	</blockquote>

...and it's not in `$HOME` outside of the sandbox (`tree -L1 . | grep perf` returns `$Null`).
