### ISSUE TITLE
Permissions ignored?

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak#1215]
I'm trying to follow the tutortial at https://flatpak.org/hello-world , but instead of

>#!/bin/sh
>echo "Hello world, from a sandbox"

I want test the permissions:

>#!/bin/sh
>ls /etc

When run this with

>flatpak-builder --run app-dir org.flatpak.Hello.json hello.sh

I would expect no output, because there is no "--filesystem" in the manifest, but I can see my host file system indeed.

**Comment by mwleeds** [comment]
@eszlari it's not actually your host `/etc`, just a minimal one to make sandboxed apps work. If you use `--filesystem=host`, `/etc` will be mounted as `/run/host/etc` in the sandbox.

**Comment by alexlarsson** [comment]
Yeah, in general flatpak doesn't use access control to control "permissions", instead you just can't see the files you don't have access to. `/etc` and `/usr` are special as they are always available, but from the runtime.

**Comment by eszlari** [comment]
Okay, maybe I should have provided the output or picked another directory, because there seems to be a misunderstanding: I can actually see my host filesystem! For example the output of 

> ls /

is this:

> app  bin  boot  cdrom  dev  etc  home  initrd.img  initrd.img.old  lib  lib64  lost+found  media  mnt  opt  proc  run  sbin  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old

**Comment by TingPing** [comment]
When you run a normal install rather than `flatpak-builder --run` it will behave as expected.

**Comment by eszlari** [comment]
> When you run a normal install rather than flatpak-builder --run it will behave as expected.

This worked, but shoudn't it be mentioned in the tutorial under point "7.Test the build"? Or shoud flatpak-builder honor these permssions?

I did another test with zenity:
```
#!/bin/sh
zenity --file-selection --title="Select a File"
```
Even after installing and using only "--socket=x11", I can browse the host.

**Comment by TingPing** [comment]
> I did another test with zenity:

That is because Zenity uses the portal support for choosing files.

**Comment by eszlari** [comment]
>That is because Zenity uses the portal support for choosing files.

Yeah, sorry, my mistake, I forgot that. (btw: is there way to disable portals on the command-line?)

That leaves the question about flatpak-builder: should I file a bug against it or should I add a note  to the tutorial about `--filesystem`?
