### ISSUE TITLE
[Feature Request] Install Flatpak apps on custom locations (eg external disk drive)

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#1224]
i have an 120GB SSD disk, and the problem is that i have run out of disk space, specially because of Flatpak games. I would run of disk space even if i had an 250GB disk, and depending the future Flatpaks a game can be 30GB

Windows 10 allows you to set installation locations on an external disk. can we have the same for Flatpak apps?

**Comment by mwleeds** [comment]
This is already possible. Here's how:
1. Put a file in `/etc/flatpak/installations.d/` called `extra.conf` like this:
```
[Installation "extra"]
Path=/run/media/mwleeds/ext4_4tb/flatpak/
DisplayName=Extra Installation
StorageType=harddisk
```
See `man flatpak-installation` for the format.
2. Add a remote with e.g. `flatpak --installation=extra remote-add flathub https://flathub.org/repo/flathub.flatpakrepo`
3. Install to it with e.g. `flatpak --installation=extra install flathub org.inkscape.Inkscape`
4. Run from it with e.g. `flatpak run org.inkscape.Inkscape`

**Comment by alex285** [comment]
@mwleeds i missed that! thank you! because i cant try that right now, do you if GNOME Software takes these configurations into account?

**Comment by mwleeds** [comment]
@alex285 I took a glance at the source for gnome-software and I think the answer is no. It would probably require some UI work as well to support.

**Comment by aiamuzz** [comment]
@mwleeds ...

forgive my posting a closed thread ... 

about the procedure you've marked on top suggesting the way to choose a installation location other than the default ... 

I have created a flatpak symbolic link at the location /var/lib/ pointing to the flatpak folder on my home which is on a separate partition ... i rsyncd the default flatpak directory to my home partition and all flatpak aaps previously installed as well as the ones newly installed are working just fine, they are getting installed at my home partition and working great.

I was wondering ... if the procedure you've marked above is the right way then, i reckon the procedure i've attempted is wrong ?

Ideally, It would be great to have the option to choose a location of preference when one installs flatpak(would make things a lot more simpler for us superusers) ... until then ... would it be possible for you to start a new thread here in the issues section on the correct procedure to change location of the flatpak applications ?

thanks.

**Comment by hughsie** [comment]
gnome-software should support it,  but you're right we don't allow the user to choose which installation to use.

**Comment by aiamuzz** [comment]
@hughsie ... 

thanks for looking ... any possibility of supporting the option to choose the installation location to one other than the default.

Of whatever little i have understood about your project 'flatpak' ... which strongly supports the developers with having to develop only one version of software for use across all linux distro's ... shouldn't the 'end-user' too be extended the courtesy of having to install our preferred apps only-once ???

It should be more so because unlike Windows and Mac OS's linux users are spoilt for choice ... the only reason people like me hold back from testing/hopping around distro's is because of the baggage of having to re-install my app environment from scratch !!!

I can understand it may be easier said then done as the flatpak team know the nuts & bolts of this project ... but i would certainly like to see the day when i can try/test new flavors of linux with my app environment up and ready to boot out of a fresh linux install.

**PS : could one of the team members post a step-by-step guide here on how to install a custom location for our apps and how to activate this location on first boot of a freshly installed linux distor.**

**Comment by aiamuzz** [comment]
thanks for reopening @mwleeds ... 

I am sure An "Install only once" incentive for the users ... will be as appealing to the users as it is currently for the Devs !!!

**Comment by aiamuzz** [comment]
Hi,

I am using flatpak pre-installed on my Deepin OS ... i have moved my flatpak folder to my home folder and placed a symbolic link in its place. All my flatpak apps(about 19 of them) are installed and running out of the above setup.

Now i want to move all the apps to a separate partition dedicated only for flatpak apps by adding a remote to this partion.

I would like to know the following ...

1. should the flatpak partition be of the ext4 format ?
2. I want to avoid re-installing all my 19 apps, instead i would like to move it to the new location. What will be an ideal way of moving the apps from my home folder ? Would it be as simple as moving folders from the /home to the new partition location ?

I am running Deepin OS ... as a result flatpak support is part of this OS by default as they have developed flatpak versions of their apps which are a part of their app store.

**Comment by alexlarsson** [comment]
flatpak partition has no specific needs, although for older versions of flatpak it has to support xattrs.
I think a regular cp -ar should be fine for the copy, as long as you copy the entire thing.

**Comment by aiamuzz** [comment]
@alexlarsson 

Hi,

I am using Deepin OS, these folks support flatpak out of the box, as a result they have hosted flatpak apps in their app store. These apps install to the default flatpak location. I have a separate partition for flatpak apps as i have created a remote at that location.

Is there a way(command) to move installed flatpak apps from the default location to my remote location ?

Would it be a good idea to have such a feature if its isn't already there ?

thanks.

**Comment by intika** [comment]
did not work for me using flatpak v0.11.3
the location /etc/flatpak was empty for me... i had to create the directory /etc/flatpak/installations.d/ and the needed file but i had an error when  running flatpak --installation=extra .... `error: Could not find installation extra`
so i ended up simlinking /usr/local/var/lib/flatpak to my external location... it works so i don't really need to debug etc...

**Comment by harishb94** [comment]
still not working using flatpak v1.0.6 on ubuntu 18.04
i created /etc/flatpak/installations.d/ location with file extra.conf containing
`[Installation "extra"]`
`Path=/data/Flatpak/`
`DisplayName=Extra Installation`
`StorageType=harddisk`
/data is my mounted 2nd hard drive

`Error: could not find installation extra`

**Comment by aiamuzz** [comment]
seems like the path could be incorrect in the 'extra.conf' file ...

@intika ...

Can you please paste the contents of your file 'extra.conf' ???

@harishb94  ...

Have you created the folder 'flatpak' in the root of the `/data` ... not sure if that could be the problem ... please rename `/data/Flatpak` to `/data/flatpak` ... lower case 'f' in 'flatpak' ...

**Comment by harishb94** [comment]
Applying changes suggested @aiamuzz 

i did changed name to lowercase
`❯ ls -al /data
total 32
drwxr-xr-x  5 root   root    4096 Nov 18 17:02  .
drwxr-xr-x 26 root   root    4096 Nov 14 09:48  ..
drwxrwxr-x  4 harish harish  4096 Nov 18 16:55  flatpak
drwxrwxr-x 16 harish harish  4096 Nov 18 15:31 'Linked Folders'
drwx------  2 root   root   16384 Apr 27  2018  lost+found`

Trying to install flatpak app...
Will take some time

**Comment by harishb94** [comment]
`❯ ls -al /data`
`total 32`
`drwxr-xr-x  5 root   root    4096 Nov 18 17:02  .`
`drwxr-xr-x 26 root   root    4096 Nov 14 09:48  ..`
`drwxrwxr-x  4 harish harish  4096 Nov 18 16:55  flatpak`
`drwxrwxr-x 16 harish harish  4096 Nov 18 15:31 'Linked Folders'`
`drwx------  2 root   root   16384 Apr 27  2018  lost+found`

**Comment by aiamuzz** [comment]
ok ...

correct the path in your extra.conf file from ...

`/data/Flatpak` ... to ... `/data/flatpak` ...

**Comment by harishb94** [comment]
i did that too...

didn't get
`Error: could not find installation extra`

**Comment by aiamuzz** [comment]
do you have any name for your external hard disk ? ... have you named it 'data'

**Comment by harishb94** [comment]
yes i did sir... didn't know any better way to name it

BTW its not external i have dual drive setup just mounted it as `/data` during installation

**Comment by aiamuzz** [comment]
@harishb94  ...

Have you manually mounted the external hard disk at `/data`  ?
Its best to mount the external hard disk at its default locations ... as it will be easier that way ...

my default location is `/media/muz/` ... some OS's mount it at `/mnt` ... whats your default mount folder ?

**Comment by harishb94** [comment]
Also i soft linked my `~/.local/share/flatpak/repo/objects` directory by moving original directory to `/data/flatpak/objects` location
I have preserved permissions and all
is it better way will it affect performance of flatpak apps ?

I did that because my `/home` partition was so low on storage and i panicked...
Thanks for your help

**Comment by aiamuzz** [comment]
is your 2nd hard drive ... internal or external ?

**Comment by harishb94** [comment]
Yes i manually mounted it that way its internal though..
As i was installing Ubuntu using shell (terminal) for LVM LUKS setup..

Switched from Arch at the time....

**Comment by aiamuzz** [comment]
> Yes i manually mounted it that way its internal though..

If its internal hard disk its best to let it mount automatically at its default location where all other partition's are mounted ... Have you configured your system to auto mount all partition on boot or it gets mounted when you click it in the file manager ?

**Comment by harishb94** [comment]
No it automounts added it to fstab during install..
Just didn't know where it mounts..

**Comment by aiamuzz** [comment]
@harishb94  ... @intika ...

I have started a separate thread explaining the procedure clearly here ... 

https://github.com/flatpak/flatpak/issues/2337

**Comment by intika** [comment]
@aiamuzz yeah just sym-linking is the easy quick best way to go...

**Comment by matthiasclasen** [comment]
I don't think there is a flatpak issue here

**Comment by jefrydco** [comment]
If you get error like this

`Error: could not find installation extra`

Don't forget to run flatpak with `sudo`, for instance:
`sudo flatpak --installation=extra install flathub org.application.name`

**Comment by mwleeds** [comment]
@jefrydco you should not need to use `sudo`. Perhaps you have unusual permissions on `/etc/flatpak/installations.d/extra.conf` or one of the intermediary directories.

**Comment by evnb** [comment]
With a considerable user base from steam deck having only 64GB, might it be worth adding GUI support for this?

**Comment by smcv** [comment]
This project does not provide a GUI, but some GUIs like GNOME Software and KDE Discover can install Flatpak apps (which they do by using code from this project). If you want features in a GUI, please send them to that GUI's issue tracker rather than here.

**Comment by smcv** [comment]
In the case of the Steam Deck, the relevant GUI is either Discover or Steam, depending how you're using it.

**Comment by dbzix** [comment]
> 3. Install to it with e.g. `flatpak --installation=extra install flathub org.inkscape.Inkscape`

Can I configure flatpak to use an extra location by default?
It would be great to have such a possibility because in this case, I don't need to remember to add this '--installation=extra' every time and I don't miss anything accidentally.
