### ISSUE TITLE
Unable to open gnome builder ver:3.26 installed using flatpak ver :0.10.1

### ISSUE THREAD

**Issue by Abhishek-Gawande** [flatpak/flatpak#1230]
i am using  ubuntu 16.04.as stated in title,i am unable to open gnome builder application,by clicking on icon.i did  reboot my computer after installing flatpak.
Although i am able to do the same by typing command
gnome-builder -vvvvv

here are some commands that i tried
flatpak list
Output :
Ref                                                                          Options       
org.gnome.Builder/x86_64/stable                           system,current
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6   system,runtime
org.gnome.Sdk/x86_64/3.26                                   system,runtime
org.gtk.Gtk3theme.Ambiance/x86_64/3.22             system,runtime

flatpak run org.gnome.Builder/x86_64/stable
Output :
Gtk-Message: Failed to load module "unity-gtk-module"
and application window opens after that

**Comment by alexlarsson** [comment]
You need to log out and then log in again if this was the first time you installed the  flatpak deb.

**Comment by alexlarsson** [comment]
The desktop integration only affects things during login.

**Comment by deikatsuo** [comment]
@alexlarsson Can I hid these message? ~Failed to load module "unity-gtk-module"

**Comment by TingPing** [comment]
@deikatsuo No but they are harmless.
