### ISSUE TITLE
Need a way to delete application data when removing apps

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#1231]
One of the nice things about Flatpak is that each app has its storage in a single location, which makes managing app data a lot easier. When you uninstall a Flatpak, it would be good if users could have the option whether to clear its data, in order to save themselves some space.

See https://bugzilla.gnome.org/show_bug.cgi?id=789770 for the GNOME Software side of this. The mockup implies we need to know the *size* of the app data too, ahead of the removal.

**Comment by mwleeds** [comment]
Yeah, `flatpak uninstall --purge ...` would be nice. I wonder if we would want it to be the default.

**Comment by user5145** [comment]
flatpak 1.1.0 has "--delete-data" :)
