### ISSUE TITLE
Export flatpak-transaction.c via libflatpak API

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#1234]
The CLI has some helper code for dependency handling in flatpak-transaction.c. It might make sense to export this in some form in libflatpak, so that apps like gnome-software can use it.

@hughsie does this make sense to you? And if so, how would the API look to work well for gnome-software?

**Comment by hughsie** [comment]
At the moment the gnome-software flatpak code is a complicated mess. It's trying to handle per-user and per-system (with extensions and runtimes supported in either) -- so I'm 100% up for looking at this all again. Ive not looked at flatpak-transaction yet, but it might be better to do interactively on IRC. Maybe grab me tmw?

**Comment by alexlarsson** [comment]
I want to get 0.10.2 out soonish, and this seems to be somewhat too complicated, with callbacks needed and whatnot. So, punting this for 1.0

**Comment by matthiasclasen** [comment]
This is now tested here: https://github.com/alexlarsson/flatpak/tree/transactions
