### ISSUE TITLE
Safer way to expose homedir

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#1235]
Many apps want access to the homedirectory for "regular files". However, there are many files in the homedir that are extra sensitive. For example .ssh, .gnupg and even things like .bashrc.

I wonder if we should introduce a --filesytem=dotfiles, and if this is not set, hide all these files (except perhaps some special case ones).

This wouldn't really make things completely safe, but it does mean granting homedir or filesystem access is a *bit* less like a complete open door.

**Comment by TingPing** [comment]
:-1: I think it gives a false sense of security. Even without dotfiles you can make a fake desktop launcher in `~/Desktop` and then boom you are running on the host. If we assume read-only people still store sensitive things in `~/Documents`. I think the `.` is an arbitrary distinction for security purposes.

**Comment by alexlarsson** [comment]
I wonder if we can basically use the override mechanism for this
Say we have a global override, which affects all apps. Then we could just have some default overrides, like `--nofilesystem=~/.ssh`. I agree that this is somewhat fake security, but not having things like that completely open might make some sense.
