### ISSUE TITLE
How to bundle 32-bit x86 binary to target x86-64?

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#124]
A number of older proprietary applications which are still of interest might be available as 32-bit (skype, games, etc.). How does one depend on the 32-bit runtime while targetting the 64-bit runtime?

**Comment by alexlarsson** [comment]
Its unclear what you mean by "targeting the 64bit runtime here". If your app is 32bit you need the libc etc from a 32bit runtime, so you should just make a 32bit app with a 32bit runtime. Running that works fine on 64bit arches.

**Comment by hadess** [comment]
Right, there's nothing special to do in the app's metadata file, simply depend on a platform of the correct architecture. Thanks.
