### ISSUE TITLE
Add a way to display an EULA

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#125]
I expect that showing EULAs to be as important, and problematic, for flatpaks as it once was for RPMs and Debs. Should it be flatpak metadata? Should it be appstream metadata? Should gnome-software show it prior to installing or updating an application?

**Comment by alexlarsson** [comment]
I think this makes better sense in the appstream data, because it can be translated, easily read before install, etc. However, @ximion might have different opinions.

**Comment by ximion** [comment]
I agree with Alex on this. With more and more long texts being added to AppStream, I need to think about whether allowing people to link them from other sources into the metadata for metainfo files makes sense...
@hadess care to file a bug against AppStream? (https://github.com/ximion/appstream/issues)

When the data is available in AppStream, Flatpak might still need to display it somehow though when installing local packages from the command-line.
