### ISSUE TITLE
Can't trash files in ~ from within sandbox, even with --filesystem=home

### ISSUE THREAD

**Issue by wjt** [flatpak/flatpak#1253]
Attempting to `g_file_trash()` a file in the user's homedir from a Flatpak'd application will fail with:

```
GLib.Error: g-io-error-quark: Unable to trash file /home/wjt/trash-test.1qkdgzrk across filesystem boundaries (15)
```

This is because `$XDG_DATA_HOME` is set to `$HOME/.var/app/$APP_ID/data` and `$HOME/.var/app` is a bind-mount. `g_local_file_trash()` checks whether the file to be trashed is on the same device as the user's homedir, and if so constructs the trash dir as `g_build_filename (g_get_user_data_dir (), "Trash", NULL)`, which is inside the bind-mount so is on a different filesystem ([source](https://git.gnome.org/browse/glib/tree/gio/glocalfile.c#n1941)). Since trashing involves `rename(2)` which doesn't work across filesystem boundaries (even when the two filesystems are bind-mounts of the same physical filesystem), this fails with EXDEV.

This is true even with `--filesystem=home` or `--filesystem=host` because the `~/.var/app/$APP_ID` bind-mount and `$XDG_DATA_HOME` are both done regardless.

`rename(2)` not working across bind mounts is [considered a feature, not a bug](http://yarchive.net/comp/linux/bind_mounts.html).

If you use `--filesystem=host` and then try to trash a file on another filesystem (such as a USB stick), this works, because the trash dir is constructed at the root of that filesystem so is on the same device.

From IRC discussion, one option might be that when `~` is the real `~`, the trashdir could be a symlink to the normal `~/.local/share/Trash` path. Another option would be a hypothetical Trash Portal.

[Here's a test app exhibiting the problem](https://github.com/wjt/trash-test):

```
% flatpak run --filesystem=host uk.me.wjt.TrashTest /run/media/wjt/eoslive/
Trashing /run/media/wjt/eoslive/trash-test.da22lom0
Trashed /run/media/wjt/eoslive/trash-test.da22lom0
  tensionsheet ~/src/flatpak/trash-test
% flatpak run --filesystem=host uk.me.wjt.TrashTest 
Trashing /home/wjt/trash-test.wk8g9q_3
[...]
GLib.Error: g-io-error-quark: Unable to trash file /home/wjt/trash-test.wk8g9q_3 across filesystem boundaries (15)
```

**Comment by TingPing** [comment]
This is discussed in flatpak/xdg-desktop-portal#114 but granting access to gvfs should be enough.

**Comment by wjt** [comment]
This is in GLocalFile so gvfs is not involved. Sure enough:

```console
$ flatpak run \
  --filesystem=host \
  --talk-name=org.gtk.vfs \
  --talk-name=org.gtk.vfs.'*' \
  uk.me.wjt.TrashTest
Trashing /home/wjt/trash-test.0hviuqme
Traceback (most recent call last):
  File "/app/trash-test", line 23, in <module>
    main()
  File "/app/trash-test", line 19, in main
    f.trash(None)
GLib.Error: g-io-error-quark: Unable to trash file /home/wjt/trash-test.0hviuqme across filesystem boundaries (15)
```

For a practical example of this problem, when you delete a torrent in Transmission (which uses `--filesystem=host`), it offers to delete the files on disk as well. This actually succeeds, but only because Transmission falls back to `g_file_delete()` (with a warning) if `g_file_trash()` fails.

**Comment by matthiasclasen** [comment]
see https://github.com/flatpak/xdg-desktop-portal/commit/93f4ec5c6dcea216e2f1da6944aa6894232fe6aa

**Comment by Mailaender** [comment]
How do I enable this portal? Does it also work for Qt/KDE applications?

**Comment by TingPing** [comment]
You don't enable the portal, libraries just must make use of it. I'm not sure about Qt/KDE personally but you can grep around their codebases for `org.freedesktop.portal.Trash`, probably in the KIO tools specifically.

**Comment by Mailaender** [comment]
https://github.com/search?q=org%3Aflathub+org.freedesktop.portal.Trash&type=code 0 hits

**Comment by nouspiro** [comment]
I got hit by this bug in my Qt application. `QFile::moveToTrash()` fail on rename error when trying to move file in ~ to trash. Looking into Qt implementation of that method it first get Trash location which end up as `$HOME/.var/app/$APP_ID/data/Trash` and then fail to move file there.
I tested `g_file_trash()` and that works.

**Comment by TingPing** [comment]
@nouspiro Qt needs to use the Trash portal.

**Comment by nouspiro** [comment]
So wait until Qt gets patched or use that `g_trash_file()` ?
Should I report this to https://github.com/flatpak/xdg-desktop-portal or somewhere else?

**Comment by TingPing** [comment]
You either report it to Qt or a KDE library that would implement it.

In the short term you can use DBus and call the portal by hand.
