### ISSUE TITLE
Need to restart after installing flatpak is awkward

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#1256]
My understanding is that you need to restart your session after installing flatpak, if you want flatpak apps to show up in your desktop. This causes a number of issues for the initial user experience:

 * It's unwelcome and may be enough to put some potential users off - nobody likes to restart, and if someone is just curious their commitment level will probably be quite low.
 * It breaks the flow when setting up for the first time - setup guides and tutorials have to assume that the process will be interrupted before someone can properly start using flatpak apps.
 * The need to restart isn't obvious - someone could easily install flatpak and think that everything should work, and then not understand why the apps they've installed haven't shown up. In this situation, users will often assume that there's a bug that's causing the issue.

**Comment by matthiasclasen** [comment]
the following answers to this were raised in the irc discussion:

1) the ideal scenario is that flatpak is pre-installed, so the paths with already be set up

2) in the case that flatpak is not installed, we need to get two programs to update their search paths:
- gnome-shell
- dbus-daemon

There's possible ways to do this for d-bus daemon, using config file fragments that we can drop in place, plus the ReloadConfig api.

gnome-shell would need a new api to add things to its search path without a restart.

The bigger issue is that installing flatpak on the host is a system-level action, whereas the dbus-daemon and gnome-shell are running in user session(s).

**Comment by hadess** [comment]
1. is definitely the better out-of-the-box option. If a distribution is particularly avert to having flatpak installed by default, it would be trivial to have a "filesystem" package which just creates the necessary filepaths so they're already there by the time flatpak gets installed.

**Comment by vadyalex** [comment]
> The need to restart isn't obvious - someone could easily install flatpak and think that everything should work, and then not understand why the apps they've installed haven't shown up. In this situation, users will often assume that there's a bug that's causing the issue.

I can confirm I had precisely that issue after installing _flatpak_ and _Telegram_ and trying to run it via _rofi_ launcher.. _rofi_ didn't see any app and I did re-install twice until I decided to give reboot a try. :thinking:

**Comment by matthiasclasen** [comment]
Random idea: We can make flatpak check if the environment looks ok, and if it doesn't, emit a warning.

**Comment by hadess** [comment]
> Random idea: We can make flatpak check if the environment looks ok, and if it doesn't, emit a warning.

That sounds good. Could we also have a little bit of documentation on the necessary filesystem setup for distributions?

**Comment by matthiasclasen** [comment]
Yes. Good idea

**Comment by davidhedlund** [comment]
@matthiasclasen "To complete setup, restart your system."
* https://flatpak.org/setup/Ubuntu -- **I didn't have to restart it**
* https://flatpak.org/setup/Manjaro
* https://flatpak.org/setup/Chrome%20OS
* https://flatpak.org/setup/Red%20Hat%20Enterprise%20Linux
* https://flatpak.org/setup/openSUSE
* https://flatpak.org/setup/Arch
* https://flatpak.org/setup/Debian
* https://flatpak.org/setup/Rocky%20Linux
* https://flatpak.org/setup/Gentoo
* https://flatpak.org/setup/Kubuntu
* https://flatpak.org/setup/Solus
* https://flatpak.org/setup/Alpine
* https://flatpak.org/setup/Mageia
* https://flatpak.org/setup/Pop!_OS
* https://flatpak.org/setup/Raspberry%20Pi%20OS
* https://flatpak.org/setup/Void%20Linux
* https://flatpak.org/setup/SulinOS
* https://flatpak.org/setup/Ataraxia%20Linux
* https://flatpak.org/setup/Deepin
* https://flatpak.org/setup/Pardus
* https://flatpak.org/setup/MX%20Linux
* https://flatpak.org/setup/Pisi%20GNU%20Linux
* https://flatpak.org/setup/EndeavourOS
* https://flatpak.org/setup/GNU%20Guix
