### ISSUE TITLE
CLI progress feedback is hard to read, at times confusing

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#1257]
When installing or uninstalling an app, the feedback provided by the CLI can be difficult to read and at times confusing. Some example output, from what will often be a user's first encounter with flatpak.

```
$ flatpak install --from https://flathub.org/repo/appstream/org.baedert.corebird.flatpakref
The remote 'flathub', at location https://flathub.org/repo/ contains additional applications.
Should the remote be kept for future installations? [y/n]: y
Installing: org.baedert.corebird/x86_64/stable
Required runtime for org.baedert.corebird/x86_64/stable (org.gnome.Platform/x86_64/3.26) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/3.26 from flathub
[####################] 10 delta parts, 74 loose fetched; 207705 KiB transferred in 27 seconds
Installing: org.gtk.Gtk3theme.Ambiance/x86_64/3.22 from flathub
[####################] 1 delta parts, 1 loose fetched; 292 KiB transferred in 1 seconds
Installing: org.gnome.Platform.Locale/x86_64/3.26 from flathub
[####################] 4 metadata, 1 content objects fetched; 14 KiB transferred in 0 seconds
Installing: org.baedert.corebird/x86_64/stable from flathub
[####################] 1 delta parts, 3 loose fetched; 6934 KiB transferred in 1 seconds
Installing: org.baedert.corebird.Locale/x86_64/stable from flathub
[####################] 3 metadata, 1 content objects fetched; 3 KiB transferred in 0 seconds
```

Issues with this:

 * Feedback is provided as a single block of text, which isn't broken up or structured. This makes it hard to read.
 * The install and uninstall commands don't state if the operation was successful - they exit silently. This will leave a lot of users wondering whether it was successful or not.
 * The progress strings include a lot of technical terms, such as `delta parts`, `loose fetched`, `metadata` and `content objects`. These add unnecessary complexity and won't mean a lot to users, including application developers.
 * The use of hashes in the progress bars creates visual noise. The progress bars also stay visible after each step has completed, rather than disappearing, further contributing to the noise issue.
 * If a new remote is specified, the CLI asks whether to permanently add it, but it does so before installation has taken place. This makes it unclear whether answering "no" will cancel the installation.
 * The phrasing of the question about adding a remote could be better - `Should the remote be kept for future installations? `

I've had a go at [sketching out a CLI that avoids these issues](https://github.com/flatpak/flatpak/wiki/CLI-experimental-design). According to this approach, the output for the operation that I pasted above would look like:

```
$  flatpak install --from https://flathub.org/repo/appstream/org.baedert.corebird.flatpakref

ID                               Architecture   Version   Repository
[+] org.gnome.Platform           x86_64         3.26      flathub              
[+] org.gtk.Gtk3theme.Ambiance   x86_64         3.22      flathub              
[+] org.gnome.Platform.Locale    x86_64         3.22      flathub              
[+] org.baedert.corebird.Locale  x86_64         stable    flathub
[+] org.baedert.corebird         x86_64         stable    flathub

org.baedert.corebird installed

Remote 'flathub' permanently added
```

It might not be the best and I'd be interested to hear ideas and suggestions. There's also [a small amount of research on the wiki](https://github.com/flatpak/flatpak/wiki/CLI-user-experience) that could be added to.

**Comment by TingPing** [comment]
Btw you don't need to use `--from` anymore, you can just do `flatpak install <url>`

**Comment by allanday** [comment]
> Btw you don't need to use --from anymore, you can just do flatpak install <url>

Oh that's great! For the website I'm thinking that we shouldn't use the .flatpakref for the CLI option. There's [an issue](https://github.com/flatpak/flatpak.github.io/issues/213) for the design changes, if you want to chip in.

**Comment by matthiasclasen** [comment]
the progress display will be addressed in the new ux branch.
