### ISSUE TITLE
How to mount/extract a flatpak bundle?

### ISSUE THREAD

**Issue by pcx862** [flatpak/flatpak#126]
Hi,
Is there a way to manually mount or extract a .flatpack file?
Something like: `flatpak --extract LibreOffice.flatpak`
Is there any utility to do this?

Thanks in advance.

**Comment by matthiasclasen** [comment]
Use flatpak install --bundle to install a bundle file.

**Comment by pcx862** [comment]
Thanks, but I was looking specifically for an extraction tool... or some way to just unpack/extract/mount a .flatpak file

I guess we can just install the .flatpak on a chroot and check the contents... but a dedicated extraction tool would be useful... (Malware analysis, unpacking to convert into [Portable Apps](https://www.orbital-apps.com), etc.)

On a related note, is there any documentation about the file format? A technical specification or something?

Thanks

**Comment by pcx862** [comment]
Great! Thats what I was looking for.

Just one more thing... `ostree checkout` requires a commit/SHA256
Any way to tell ostree to "just extract the latest commit"?

**Comment by alexlarsson** [comment]
The "latest commit" is stored by branch (just like in git), and the branch name is the app+arch+version. You can use ostree refs to list them.

**Comment by pcx862** [comment]
Strange... I had tried that, but I can't get it to work with the extracted repo:

`ostree init --repo=repo`
`sudo ostree static-delta apply-offline --repo=repo LibreOffice.flatpak`
`ostree refs --repo=repo`
(the command is executed but no output is produced)

However, if I do:
`sudo flatpak install --bundle LibreOffice.flatpak`
`ostree refs --repo=/var/lib/flatpak/repo`
I get:

> org.libreoffice.LibreOffice-origin:app/org.libreoffice.LibreOffice/x86_64/fresh

Further investigation reveals the repos have some differences:
`cat $HOME/repo/config`
> [core]
> repo_version=1
> mode=bare

cat /var/lib/flatpak/repo/config

> [core]
> repo_version=1
> mode=bare-user
> 
> [remote "org.libreoffice.LibreOffice-origin"]
> url=http://download.documentfoundation.org/libreoffice/flatpak/repository
> xa.title=LibreOffice.flatpak
> xa.noenumerate=true
> xa.prio=0

What am I missing?
(ostree version 2016.5 / Fedora 23 / 64bits)

**Comment by alexlarsson** [comment]
Just had a look at this, and yeah, there is in issue here. ostree apply-offline doesn't actually create a ref, so you can't easily reference the newly created commit object from apply-offiline. @cgwalters: Maybe ostree should accept an optional branchname here?

Anyway, for now you can do something like:
```
ostree init --repo=repo --mode=bare-user
ostree static-delta apply-offline --repo=repo LibreOffice.flatpak
ostree checkout --repo=repo -U $(basename $(echo repo/objects/*/*.commit | cut -d/ -f3- --output-delimiter= ) .commit) outdir
```

**Comment by pcx862** [comment]
Excellent. I confirm this works.

This will be very useful. Thank you.

**Comment by alexlarsson** [comment]
May I ask what you're using it for?

**Comment by pcx862** [comment]
Sure: I'm the lead developer of [ORB (Open Runnable Bundle)](https://www.orbital-apps.com), which is a project to create "next-gen Linux executables"

ORB executables (.orb files) work out-of-the-box on most modern linux distros: they behave exactly like ELF binaries ([just mark the file as executable and run](https://www.orbital-apps.com/documentation/running-an-orb-app-directly))
They also have a "next-gen mode" (enabled after installing [ORB Launcher](https://www.orbital-apps.com/launcher)) where the .orb executables become clickable, with icons and with [several security features](https://www.orbital-apps.com/security), like automatic cryptographic signature checking.


Now to answer your question: We are very excited about Flatpak and are planning to add support for it in our [ORB Creator](https://www.orbital-apps.com/creator). In short, it will take a .flatpak as input, download the runtimes, and output a cross-distro .orb executable (a [Portable App](https://www.orbital-apps.com/portable))

In addition, it might also be interesting to take the flatpak+runtimes and create a
cross-distro/offline-friendly/clickable installer (using flatpak at the "back-end").

Feel free to let me know if you have any questions or suggestions (either regarding Flatpak integration or anything else)

**Comment by matthiasclasen** [comment]
I think the question here was answered.

**Comment by probonopd** [comment]
Doesn't work on Ubuntu Live ISOs because `Unable to set xattr: Operation not supported`.

**Comment by skierpage** [comment]
@probonopd alexlarsson's command line above also fails with the same error if you unpack in a tmpfs like /tmp. I retried on a regular ext file system and it worked.

FWIW my scenario is trying to figure if the latest LibreOffice flatpak bundle for download matched the version that `flatpak --user update` installed. So I unpacked then ran `diff
~/.local/share/flatpak/app/org.libreoffice.LibreOffice/x86_64/fresh/783b14e2f564bbc37f3beb0c7ec26f71755674968917afdd01c7e683d4e4d1cf/files/libreoffice/program ~/temp/ostree_LibreOffice/outdir/files/libreoffice/program`.

**Comment by probonopd** [comment]
One and a half years later, there still seems no exist no way to extract the contents of a flatpak file using a system running on a Xubuntu 16.04 Live ISO:

```
me@host:~$ sudo add-apt-repository ppa:alexlarsson/flatpak -y
me@host:~$ sudo apt update
me@host:~$ sudo apt install flatpak ostree -y

me@host:~$ ostree init --repo=repo --mode=bare-user
error: fsetxattr(user.ostreemeta): Operation not supported
```

**Comment by ryanabx** [comment]
I went ahead and automated the process of running a .flatpak file: https://github.com/ryanabx/portapak

**Comment by faveoled** [comment]
I built a small tool for .flatpak extraction:
https://snapcraft.io/flatpak-extract
