### ISSUE TITLE
Can't remove installed Flatpak: "Only last name segment can contain -"

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#1262]
This was an attempt (a long time ago) at creating an extension for GNOME Games. I managed to remove `org.gnome.Games.Core.genesis-plus-gx` itself, but not its debug package.

```
$ rpm -q flatpak
flatpak-0.10.1-1.fc27.x86_64
$ flatpak list
org.gnome.Games.Core.genesis-plus-gx.Debug/x86_64/master user,runtime
$ flatpak uninstall  --user org.gnome.Games.Core.genesis-plus-gx.Debug/x86_64/master
error: Invalid id org.gnome.Games.Core.genesis-plus-gx.Debug: Only last name segment can contain -
```

**Comment by alexlarsson** [comment]
This was fixed in https://github.com/flatpak/flatpak-builder/commit/1b097

You should be able to just remove the `repo/refs/remotes/*/runtime/org.gnome.Games.Core.genesis-plus-gx.Debug` and `runtime/org.gnome.Games.Core.genesis-plus-gx.Debug` directories in `~/.local/share/flatpak` to fix this

**Comment by hadess** [comment]
I removed those files/directories manually, and that seems to have emptied my `flatpak list`, thanks.
