### ISSUE TITLE
Centos 7.4 | Flatpak 0.8.7 (built in official version) |  flathub = GPG errors

### ISSUE THREAD

**Issue by David-Else** [flatpak/flatpak#1264]
Hello,

Not sure if this is the place for github error reporting, but I can't find anywhere else.

I type as instructed on the flatpak site:

`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

`flatpak install --from https://flathub.org/repo/appstream/org.blender.Blender.flatpakref
`

or:

`flatpak install --from https://flathub.org/repo/appstream/org.DolphinEmu.dolphin-emu.flatpakref
`

and am greeted with:

`
error: While pulling runtime/org.freedesktop.Platform/x86_64/1.6 from remote flathub: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
`

**Comment by alexlarsson** [comment]
This sounds like a temporary issue. Do you still get this?

**Comment by David-Else** [comment]
I deleted Centos 7.4 after weeks of trying to make it work as well as Fedora, so I am afraid I can't give you any more details.
