### ISSUE TITLE
CLI - limited availability of app descriptions

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#1265]
`flatpak search` shows the app description, which can be really useful. However, other commands don't. This includes:

 * `flatpak remote-ls`
 * `flatpak remote-ls -d`
 * `flatpak remote-info`

This feels inconsistent. It also makes these commands less useful.

**Comment by TingPing** [comment]
Was planning on having commands to show that information. It doesn't necessarily make sense for them to be under `remote-info` and `remote-ls` though as I view those as lower level commands rather than user facing. (`search` largely replaces `remote-ls` for example)

**Comment by allanday** [comment]
> It doesn't necessarily make sense for them to be under remote-info and remote-ls

Having worked on this some more, I think you're right about `remote-ls`. I do think that it would be good to include the description in `remote-info` though, since:

 1. It's more applicable to end-user cases, where someone might be exploring
 2. It shows a lot of information already, and an extra line isn't going to make a huge difference

[This is what it looks like](https://github.com/flatpak/flatpak/wiki/CLI-experimental-design#info) in the sketches I've been playing around with recently.

I think I probably created this issue prematurely and it probably makes more sense as part of a wider set of changes, if we were to make them, so feel free to close it.

**Comment by matthiasclasen** [comment]
this will be addressed to some extent by the new ux branches, which add app descriptions to the info and remote-info output.
