### ISSUE TITLE
Can't remove Flathub from Flatpak.

### ISSUE THREAD

**Issue by Atlanelan** [flatpak/flatpak#1274]
When I run the command "$ sudo flatpak remote-delete flathub",the following info shows:
error: Can't remove remote 'flathub' with installed ref runtime/org.gnome.Platform.Locale/i386/3.26 (at least)

**Comment by TingPing** [comment]
Currently you have to remove the packages from the repo before removing the repo.

**Comment by mwleeds** [comment]
You can use the `--force` option, but you'll be left with apps/runtimes that won't be able to update.
