### ISSUE TITLE
How to export library  for an application

### ISSUE THREAD

**Issue by kensully** [flatpak/flatpak#1277]
I want to add   [this library](https://github.com/PCMan/gtk3-nocsd) into flatpak environment and call it like 
`flatpak run --env="/lib/libgtk3-nocsd.so.0" org.some.app` to disable client-side decoration.
But I don't know how I build it in flatpak.
Flatpak filesystem illustrated [here](https://github.com/flatpak/flatpak/wiki/Filesystem)
Is it possible?
Regards.
Kenn

**Comment by kensully** [comment]
@TingPing thank you for responding. 
> You cannot "just add a library" to a runtime.
But we can run an app in a runtime like:       
      flatpak run --runtime=org.gnome.Sdk/i386/3.24 org.some.app

If I create a local runtime and build and install it, does it work the way above?

**Comment by TingPing** [comment]
That would work yes, or it could simply be the same name and be used anyway.

**Comment by kensully** [comment]
I did the following steps:

      git clone https://github.com/PCMan/gtk3-nocsd.git
      flatpak build-init --arch=x86_64 gtk3-nocsd org.gnome.gtk3-nocsd org.gnome.Sdk/x86_64/3.24 org.gnome.Platform/x86_64/3.24
      cd gtk3-nocsd
      flatpak build ../gtk3-nocsd make --prefix=/app
      flatpak build ../gtk3-nocsd make
      flatpak build ../gtk3-nocsd make install
      cd ..
      flatpak build-finish gtk3-nocsd --socket=x11 --share=network --command=gtk3-nocsd
      flatpak build-export repo gtk3-nocsd
      flatpak --user install --arch=x86_64 tutorial-repo org.gnome.gtk3-nocsd/x86_64/master

I just followed the steps here [flatpak builder](http://docs.flatpak.org/en/latest/building-simple-apps.html)
     
So, how do I load the library to run the following app

       flatpak run   de.haeckerfelix.gradio
?

**Comment by alexlarsson** [comment]
This seems like overkill if you just want to hack the app. Can't you just put the  file in `~/.var/app/de.haeckerfelix.gradio` and then do something like `flatpak --user override --env=LD_PRELOAD=/home/user/.var/app/de.haeckerfelix.gradio/file.so de.haeckerfelix.gradio`

**Comment by kensully** [comment]
@alexlarsson thank you for your guidence. I tried what you advised now, but it fails to disable client side decoration. I think it is uneffective on  apps created by QT.
Thank you for your help.

**Comment by kensully** [comment]
@alexlarsson  I managed to disable `CSD` on `Nautilus by issuing `export GTK_CSD=0; flatpak run org.gnome.Nautilus` after applying your hack.
Since I managed to do what I want I close the issue. I hope somebody add this method to `Flatpak` documentation.
Thank you.

**Comment by LiohMoeller** [comment]
@trappedinspacetime does this still work for you?

I have tried with current GTK applications like Evince without success.
