### ISSUE TITLE
"bwrap: Can't make symlink at /home: File exists" when running flatpak steam on fedora atomic workstation

### ISSUE THREAD

**Issue by mczimmermann** [flatpak/flatpak#1278]
On Fedora Atomic Workstation, when I run

`flatpak run com.valvesoftware.Steam`

I get the following error message

`bwrap: Can't make symlink at /home: File exists`

The flatpak version is 0.10.2. I cleanly installed Atomic Workstation and `rpm-ostree status` gives:

Version: 27.26 (2017-12-22 14:44:29)
BaseCommit: d0da7129dd883735b91c3c1d2e041974d13689ae53b5da5bb1dc4d3fe07cfd66

I'd like to add that so far with atomic workstation everything else worked like a charm and that all the other flatpaks I've installed run without issues.

**Comment by mwleeds** [comment]
Sounds similar to #959

**Comment by mczimmermann** [comment]
Retested with

fedora-workstation:fedora/27/x86_64/workstation
Version: 27.57 (2018-01-25 06:57:44)
BaseCommit: d39f7bd0496a874d93b4df12b566ef7476d4abc5b3d92b6fca633f87a09514e7

flatpak version 0.10.2.1

Error still persists.

**Comment by cgwalters** [comment]
I haven't fully tried to debug this but offhand I suspect flatpak (or possibly bwrap) needs to chase symlinks when setting up bind mounts.

**Comment by mczimmermann** [comment]
Issue solved! Retested with

ostree://fedora-workstation:fedora/28/x86_64/workstation
                Version: 28.20180402.n.0 (2018-04-02 12:17:17)
                BaseCommit: 2be6a2da62810d97d4af7fe00bbdc20102fe49796c101ef951cd49659356d333

flatpak --version
Flatpak 0.11.3

**Comment by noark9** [comment]
On Fedora Workstation 28, when I run

flatpak run com.valvesoftware.Steam

I get the following error message

bwrap: Can't make symlink at /home/username/.local: File exists

flatpak --version
Flatpak 0.11.3

Error still here.

I make a symlink for ~/.local to another driver before. Seems like my symlink cause this error.

**Comment by Firstyear** [comment]
Hi. I think this need to be reopened because the updates do not correct issues such as https://github.com/flathub/org.darktable.Darktable/issues/6 . I believe that there are further issues, and this should be examined better. Thanks,

**Comment by omichalek** [comment]
I have the same problem:

> $ flatpak run org.darktable.Darktable 
> bwrap: Can't make symlink at /var/run: File exists

Flatpak 0.11.8.3 (Tumbleweed version)

**Comment by PorcelainMouse** [comment]
I don't have Atomic, but I still get this error.  Why is steam screwing with this, anyway??

**Comment by drschwabe** [comment]
Workaround for Steam, just delete or move the ~/Pictures folder (mine was a symlink) and then restore it after your done playing/using it.

**Comment by RossComputerGuy** [comment]
I'm having the same problem on nixOS, it says it wants to symlink `~/.nix-profile` which if I remove it, could screw up my user.

**Comment by beh-10257** [comment]
@RossComputerGuy any workarounds
I just symlinked my ./local/share/icons to .icons
and now its broken

**Comment by beh-10257** [comment]
so supposedly in this image 
![image](https://github.com/flatpak/flatpak/assets/77834479/88d069a4-d365-44b9-a13d-c58550f42b76)

there is no filesystem access in the first place and yet it still wants to access my .icons directory
