### ISSUE TITLE
build-init ignores SDK extensions unless writable-sdk is specified

### ISSUE THREAD

**Issue by gcampax** [flatpak/flatpak#1281]
At the moment (flatpak 0.10.2.1, but the code in master matches), the following command:

flatpak build-init --sdk-extension=org.freedesktop.Sdk.Extension.gfortran-62 --tag=nightly --arch=x86_64 appdir com.myapp org.gnome.Sdk org.gnome.Platform master

will ignore the --sdk-extension argument completely, unless --writable-sdk is also specified.
The result is that flatpak build subsequently complains for the lack of fortran.

I'm not sure if this is by design, but given that writable-sdk is an expensive option, because it requires a full copy of the SDK in every app dir, it would be nice to support extensions as overlays, like the runtime does.

**Comment by gcampax** [comment]
Actually, I just found out that without --writable-sdk the SDK extension is in fact loaded automagically by flatpak build, even though there is no argument or metadata that specifies it, and my builds were failing because gfortran is in a weird location.

This still seems a bad design to me, because now builds succeed or fail based on whether some unrelated software has caused the installation of the SDK extension.

**Comment by alexlarsson** [comment]
The extension is available, but unless you're doing something very weird it will not be used, its just an inert directory. You have to enable its use, such as e.g. adding it to the path on ld-library-path.

If you use flatpak-builder you can list the required extensions in `sdk-extensions` and it will fail the build early if its not installed (and can be auto-installed with --install-deps-from=REMOTE)
