### ISSUE TITLE
Unable to add a variable in the command line

### ISSUE THREAD

**Issue by andreamoro** [flatpak/flatpak#1283]
Unable to successfully specify a variable in the Exec path into a .desktop file.

I've the the Viber package that relies on a QT_SCALE_FACTOR=XX variable so to not load at magnified dimension. However, I can't see any FAQ or example on how to make this possible in a .desktop file, neither to make this inline into an Exec instruction like the following:
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=viber com.viber.Viber 

Any himt?

**Comment by TingPing** [comment]
You can add `--env=QT_SCALE_FACTOR=XX` to that line.

**Comment by andreamoro** [comment]
Thanks but in that way the command seems ignored.

**Comment by TingPing** [comment]
You need that before the end of the command. So: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=viber --env=FOO=bar com.viber.Viber`

**Comment by andreamoro** [comment]
Fantastic. Thanks
