### ISSUE TITLE
Where are all the installed flatpak apps .desktop files located 

### ISSUE THREAD

**Issue by andreamoro** [flatpak/flatpak#1286]
Have been trying to change the default behavior of the Viber app installed via FlatPack.
So long I create a desktop file, everything is ok, but when clicking on the icon in the system menu, flatpack keep loading the app with the default settings.

I initially thought that creating a .desktop file in the /usr/share/applications would have replaced the one shown, but that's not the case.
Do you know where these settings are located?

Thanks

**Comment by bochecha** [comment]
The `.desktop` file for each app is installed inside its checked out tree.

So if you install `org.gnome.Builder` system-wide, the desktop file is at:

```
/var/lib/flatpak/app/org.gnome.Builder/current/active/files/share/applications/org.gnome.Builder.desktop
```

However Flatpak knows a few things about desktop apps in general. One thing it knows is that an app will always have a `.desktop` file in its tree under `share/applications/${APPID}.desktop`, so it actively searches for these and "exports" them.

That means you can find the `.desktop` file in the `exports/` directory for the app, which in the previous example is:

```
/var/lib/flatpak/app/org.gnome.Builder/current/active/export/share/applications/org.gnome.Builder.desktop
```

But then that's not very useful, Flatpak can't tell your desktop to go and search for apps in all the possible `exports/` directories, one for each installed app.

So in addition, Flatpak takes everything for the per-app `exports/` directories and puts it in a global `exports/` directory. That means for our example you can find it at:

```
/var/lib/flatpak/exports/share/applications/org.gnome.Builder.desktop
```

Of course, all the above applies to per-user applications as well, just replace `/var/lib/flatpak/` by `~/.local/share/flatpak/` 😉 

Now, how does your desktop find those desktop files? Easy, it looks under each of the directories mentioned in the `$XDG_DATA_DIRS` variable. On my system:

```
$ echo $XDG_DATA_DIRS
/home/mathieu/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
```

And it looks into them **in order**, and stops at the first it finds. So when your desktop finds `/var/lib/flatpak/exports/share/applications/org.gnome.Builder.desktop`, it won't go and read the `/usr/share/applications/org.gnome.Builder.desktop` file you created, because that has a lower priority. (it comes later in `$XDG_DATA_DIRS`)

One path that isn't present in `$XDG_DATA_DIRS` but should always have precedence over the others is `~/.local/share/applications/`. Try adding your custom `desktop` file there, and make sure it's named exactly like the one from the app you're trying to override. 🙂

**Comment by alexlarsson** [comment]
Also, depending on what you're tweaking, look at `flatpak override` which lets you tweak flatpak options for a particular app.

**Comment by RoyiAvital** [comment]
@bochecha , I'm on Linux Mint 18.3 which integrated FlatHub into its Software Manager.

I can see in `~/.var/app/` the list of applications I installed through FlatHub (Seems like only the configuration files).
Yet I can't find where are the binary files of those applications. 
I looked at `~/.local/share/flatpak` yet all in there is `db` and `repo`.

Where can I find the binary files (Software Manager didn't ask for password -> User installation)?

**Comment by RoyiAvital** [comment]
@bochecha ,
I use Linux Mint 18.3 which integrated FlatPak.
Strange thing, it installs the applications system wide (`var/lib/flatpak`) without requesting any password.
Yet, if I try, as a user, to create a new folder in `var/lib/flatpak` I require to enter password.

Any idea?

**Comment by bochecha** [comment]
As I said, PolicyKit is configured to let you install flatpak apps system-wide without entering a password. That's either a configuration you did yourself, or the default configuration from your distribution.

Creating a folder has nothing to do with it, and requires entirely different permissions. There is no reason to conflate the two.

At this point, we're moving into general support on how a Linux system works, which is completely off-topic for this place. Please ask for help in the appropriate support forum from your distribution.

**Comment by joh-ku** [comment]
If I understood correctly, the `*.desktop` file in `/var/lib/flatpak/exports/share/applications` remains unchanged when updating the related flatpak application?

In my specific case I pass the `Exec` command a scale factor to properly size [Spotify on a HiDPI display](https://community.spotify.com/t5/Desktop-Linux/Linux-client-barely-usable-on-HiDPI-displays/td-p/1067272), which is overriden ervery time Spotify gets updated.

**Comment by TingPing** [comment]
@joh-ku If you want to override a desktop file you put a copy in `~/.local/share/applications`.

**Comment by joh-ku** [comment]
@TingPing this setup seems to slow down the initial application startup, but it works. Thank you very much for clarification!

**Comment by raffaem** [comment]
Notice that, in order for the desktop file to be copied in `/var/lib/flatpak/exports/share/applications` (which is the path in $XDG_DATA_DIRS, and thus the one that will be used by the shell to populate the application overview), the .desktop file *must* be named

`<appid>.desktop`

Where `<app-id>` is the "app-id" variable of the manifest file

@bochecha: correct me if I am wrong

**Comment by motoryzen** [comment]
People .ya don't have to do any super advanced bashscripts or exec tom foolery to get Flatpak ( aka Flathub version found in Software Manager of Linux Mint 21 or 21.1 that is for one example) to let you finally create your individual games shortcuts to put in any folder you want

It took me a while today, but I figured it out. 

`flatpak run com.valvesoftware.Steam :steam steam://rungameid/35700`

You'll notice that is a single spacebare press between com.valvesoftware.Steam     ...   and  :steam steam://runegameid/35700

That is an example of the precise command for me to launch Trine 1 via flatpak steam

<<<   My steam info when clicking Help, and then " About Steam"  :  >>>

Steam API: v020

Steam package versions: 1671501303

I ensure nothing about any versions of steam existed on my machine...installed the flatpak version from Mint's Software manager, restored my games using the Backup and Restore deal ( had to manually copy and paste the "Disk 1" folder that I chose to create it using the previous Steam's settings....toward the default showing folder/directory.....not sure why it refused to let me doing it directly from my spare 4TB ssd - shrugs...)

And ..now I'm a runway steam train  ;P

**Comment by martin-braun** [comment]
Installed AnyDesk on Debian LXDE, no desktop export which links 

```
/var/lib/flatpak/app/com.anydesk.Anydesk/current/active/files/share/applications/com.anydesk.Anydesk.desktop
```

from either:

- `/usr/share/applications/com.anydesk.Anydesk.desktop`
- `~/.local/share/applications/com.anydesk.Anydesk.desktop`

I thought flatpak is established enough to support all common DEs?

I tried to symlink to `/usr/share/applications`, but even a restart would not show AnyDesk in the start menu.

**Comment by TingPing** [comment]
@martin-braun Flatpak already creates a link to them, in `/var/lib/flatpak/exports/share/applications`.

This path will already be part of `XDG_DATA_DIRS` and every desktop should support that.

If you don't see them I'd assume `XDG_DATA_DIRS` is your issue.

**Comment by martin-braun** [comment]
@TingPing Thanks, that's definitely the issue.

I have set this in my `.xsessionrc`:

```sh
export FOO="foo"
export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
```

`$FOO` gets set, but `$XDG_DATA_DIRS` probably gets overwritten at a later stage:

<img width="696" alt="image" src="https://github.com/flatpak/flatpak/assets/24259245/b440ad8e-4f41-46d2-a6b6-626e976b9f9c">

AnyDesk is still not available in the start menu. What a trash DE. I'm not willing to modify system files, this needs to be configurable from within the user home directory.

**Comment by coder-cookie** [comment]
What if the .desktop files specifies the full path of the application to launch? Does it need to seach through `$XDG_DATA_DIRS` ? 
I see in  /var/lib/flatpak/exports/share/applications/org.gnome.Builder.desktop contents that a full path is specified yet the path doesn't exist in my system and I presume the path is relative to the sandbox even though it starts from root `/` .What is the relative path does the sandbox resolve paths from?

**Comment by reharish** [comment]
Ohhh, Got it. We should reboot on fresh install.
