### ISSUE TITLE
Why Flatpak? Isn't Snap enough?

### ISSUE THREAD

**Issue by kq01526** [flatpak/flatpak#1288]
This is meant as a follow-up to:

https://forum.snapcraft.io/t/assorted-questions-about-snapd-use/1738

So, reading through that forum thread mentioned above (incl. all the articles it links to) makes you wonder:

Wouldn't it be more sane to stop developing Flatpak and concentrate and combine all developer efforts onto Snap?

Why develop Flatpak and Snap? Why not collaborate on Snap only?

The forum thread and articles also seem to indicate that Snap is "better" than Flatpak.

This is not meant to offend anyone. But why do we need to have fragmentation on universal packaging formats? Universal packaging should reduce fragmentation, not support/increase it.

Sorry, but this makes @BryanLunduke 's "Linux Sucks" videos come back to mind.

Do we really want more of those videos?

**Comment by TingPing** [comment]
Honestly nothing productive can from from this sort of discussion on a *bug tracker*. I'll just say nothing is as simple as just *"Lets all work together"* and there are many different political and technical differences between effectively all software projects that have ever existed since the dawn of time.

**Comment by kq01526** [comment]
> @TingPing wrote:
> Honestly nothing productive can from from this sort of discussion on a _bug tracker_.

And where is the Flatpak forum? What place is there to discuss this?

**Comment by TingPing** [comment]
There is a mailing list: https://lists.freedesktop.org/mailman/listinfo/flatpak

**Comment by matthiasclasen** [comment]
There is also #flatpak on freenode
