### ISSUE TITLE
Keep Portals seperate modular so flatpack can be extended

### ISSUE THREAD

**Issue by fabianthoma** [flatpak/flatpak#129]
I think it would be a good idea to make flatpack modular in a way so additional portals can be available depending on the platform it's running on. Because of this a kind of plugin system would make sense. 
Keep in mind I don't currently have any idea of he internal workings of flatpack, so for all I know this could be already possible, but is undocumented.

**Comment by alexlarsson** [comment]
Portals are in general dbus services, so they are not super-tightly bound to flatpak. However, some are less separable than others (such as the document portal). I think it makes sense to separate out some of them.

**Comment by matthiasclasen** [comment]
There's https://github.com/flatpak/xdg-desktop-portal now. I think that's a sufficient answer for now ?
