### ISSUE TITLE
New user. Can't install org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6 as user

### ISSUE THREAD

**Issue by thelfer** [flatpak/flatpak#1298]
Dear flatpak developers,

I am interested in testing flatpak, so I tried to follow the documentation to get things started.

I thus tried to install the runtime and skd  corresponding to freedesktop as follows:

```
 $ flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak  install  flathub org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6
error: Remote "flathub" not found
th202608@pleiades098:~/.gnupg$ flatpak  install --user flathub org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6
Installing: org.freedesktop.Platform/x86_64/1.6 from flathub


error: While pulling runtime/org.freedesktop.Platform/x86_64/1.6 from remote flathub: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
```

After some googling, I found some answers; some people changed the dns in /etc/resolv.conf. This solution seems strange to me. Whatever, as I don't have administrative privileges, I can't try this.

Have I missed something ?

Best regards,

Thomas

**Comment by alexlarsson** [comment]
Do you still get this? It works fine here, and its possible this was a temporary issue on the server.
Basically, this means that it didn't find https://flathub.org/repo/summary.sig which is a signature for https://flathub.org/repo/summary

**Comment by thelfer** [comment]
Indeed, it works now.
I found several threads complaining about such problems. Would it be worth adding a note in the tutorial introduction ?
Whatever, thank you for taking the time to investigate the issue. I close the ticket.
Best regards,
Thomas
