### ISSUE TITLE
Support specifying url to gpg key

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#13]
_From @hbons on April 19, 2016 3:4_

This would save a setup step. :)

_Copied from original issue: alexlarsson/xdg-app#135_

**Comment by alexlarsson** [comment]
Yeah, but automatically downloading the gpg seems iffy from a security
perspective. I know its hardly more secure to just wget it, but a security
consious person would know that and properly verify the https source
details for a gpg key.

**Comment by mwleeds** [comment]
I think now that we have `.flatpakrepo` files this can be closed.
