### ISSUE TITLE
flatpak only works with sudo on fedora 27

### ISSUE THREAD

**Issue by maldun** [flatpak/flatpak#1300]
Hi!

Kudos to you guys for making this great project.
Nevertheless I still have a problem:
When I tried out the [Hello World example](https://flatpak.org/hello-world) 
line for line I always encountered the same problem:
When starting flatpak run the application hangs indefinitely (even when testing) and creates an
empty app/name.of.app/ folder and only Ctrl+C was possible
Everything works fine using sudo though, but this isn't good.

Today I tried to install Monodevelop and the same behaviour.

I don't know if there is some miss-configuration on my end, but I didn't do more than 
`sudo dnf install flatpak flatpak-builder`

Edit: Version is
`Flatpak 0.10.2.1`

Help is aprreciated!

**Comment by mwleeds** [comment]
@maldun please post what version of flatpak you're using (`flatpak --version`)

**Comment by maldun** [comment]
@mwleeds Sorry I forgot ...
`Flatpak 0.10.2.1`

**Comment by maldun** [comment]
No Inputs on this issue?

**Comment by mwleeds** [comment]
@maldun you should post exactly what commands you ran. It's hard to tell from the description

**Comment by maldun** [comment]
@mwleeds Here my commands

    sudo dnf install flatpak-builder
    flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    flatpak install --user flathub org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6
    flatpak-builder app-dir org.flatpak.Hello.json
    flatpak-builder --run -v app-dir org.flatpak.Hello.json hello.sh

Then I get:
    FB: starting: rofiles-fuse /home/maldun/prog/flatpak/hello2/app-dir /home/maldun/prog/flatpak/hello2    /.flatpak-builder/rofiles/rofiles-aqhKKE
    FB: Running 'flatpak build --with-appdir --bind-mount=/run/build=/home/maldun/prog/flatpak/hello2    /.flatpak-builder/build --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib     --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --talk-name=org.freedesktop.DBus /home/maldun/prog/flatpak/hello2/.flatpak-builder/rofiles/rofiles-aqhKKE hello.sh'
    
And then nothing it hangs. Only if I repeat those steps as root it works/ 
Strangely enough I did a fresh install on VirtualBox on Fedora XFCE and it works fine.

I'm using Fedora 27, KDE and NVidia card. Shell is zsh if this is needed.
Current versions are:
    Flatpak 0.10.3
    flatpak-builder 0.10.6

Hope this gives better information.

My personal guess is that something is messed up with user privileges, but I don't know where to start ...

When I first installed I installed the sdk systemwide via sudo btw.

**Comment by matthiasclasen** [comment]
Closing this, since it was reported against an old version of flatpak. Please reopen, if the issue still exists with flatpak 1.0.x

**Comment by salmanfs815** [comment]
I'm having the same issue: can't run `flatpak` commands without `sudo`
I'm on Fedora 29 (Linux kernel 4.20.16-200) with `Flatpak 1.2.3`.
```bash
[sasiddiq@localhost flatpak]$ flatpak update
Looking for updates…
error: Error opening directory '/var/lib/flatpak/app': Permission denied
[sasiddiq@localhost flatpak]$ sudo flatpak update
Looking for updates…
Nothing to do.
[sasiddiq@localhost flatpak]$ flatpak install flathub org.freedesktop.Platform//18.08
Looking for matches…


        ID                                               Arch              Branch            Remote             Download
 1. [✗] org.freedesktop.Platform                         x86_64            18.08             flathub            < 355.8 MB
 2. [ ] org.freedesktop.Platform.Locale                  x86_64            18.08             flathub            < 218.7 MB (partial)
 3. [ ] org.freedesktop.Platform.VAAPI.Intel             x86_64            18.08             flathub              < 1.8 MB
 4. [ ] org.freedesktop.Platform.html5-codecs            x86_64            18.08             flathub              < 4.9 MB

Error: openat(refs/remotes/flathub/runtime/org.freedesktop.Platform/x86_64/18.08): Permission denied
error: Failed to install org.freedesktop.Platform: openat(refs/remotes/flathub/runtime/org.freedesktop.Platform/x86_64/18.08): Permission denied
[sasiddiq@localhost flatpak]$ sudo flatpak install flathub org.freedesktop.Platform//18.08
Looking for matches…
Skipping: org.freedesktop.Platform/x86_64/18.08 is already installed
```
