### ISSUE TITLE
gdb can't disable address space randomization in sandbox

### ISSUE THREAD

**Issue by marbub** [flatpak/flatpak#1301]
If I start the debugger I get the message:

Error disabling address space randomization: Operation not permitted

The "devel" option is already set.

**Comment by mwleeds** [comment]
@marbub you should post exactly what command you ran

**Comment by mwleeds** [comment]
and you should post what OS you're on, and what version of the OS

**Comment by marbub** [comment]
Flatpak 0.10.2.1
Ubuntu 17.10

I was starting the gdb debugger in QtCreator. It's not easy to describe that QtCreator is setting gdb.

**Comment by Mikenux** [comment]
@marbub: Does your issue persist with newer versions?

**Comment by marbub** [comment]
I am now using the debugger. So it seems fixed.
