### ISSUE TITLE
Should the flatpak ID and the upstream ID be absolutely the same?

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1302]
Hello!

Sorry, this one is a bit of a question. I was not sure if that was more for the AppStream project or flatpak. Let's ask here first. :-)
So we have a bug report in GIMP of someone asking us to update our appdata ID to be the same as the one for our flatpak. Indeed in our Flatpak manifest, we use `org.gimp.GIMP` whereas our local appdata file uses `gimp.desktop` historically (which flatpak actually overrides).

A part of the complaints is also that they show as different applications, when listed in an application software (GNOME Software, etc.).
Personally I took this more as a feature (for myself at least), and that allows me to be able to launch both installed version in the overview or right click menus, etc. I find it an anti-feature that having several versions of the same applications, one is always hidden by others.

Is there any good reason why we should sync the ID upstream to the flatpak ID? Is it the path to follow and if so, why? Or are we just fine by having a separate ID in the upstream appdata/desktop files?

**Comment by TingPing** [comment]
The benefit of appdata and desktop matching is as you say to avoid duplication. This ID is also used for reviews but you can add a `<provides>` line for the alternate ID and it should fix the reviews.

There is a benefit of the icon names matching which is themes only need to provide a single name.

Your Application ID should be a valid DBus name anyway since GtkApplication uses that and any service you expose should use that (if you ever use that with the Gtk3 move).

**Comment by Jehan** [comment]
When I do so, I have to rename the desktop file as well as `org.gimp.GIMP.desktop`, right?

I see I can do a:

> <provides>
>     <id>gimp.desktop</id>
>   <provides>

Would that do without renaming? Or should we rename everything?

**Comment by TingPing** [comment]
> When I do so, I have to rename the desktop file as well as org.gimp.GIMP.desktop, right?

It is possible, outside of flatpak, to only rename the appstream id and keep the desktop file by using `<launchable desktop-id="gimp.desktop"/>`

I believe `<provides><id>...` is mainly for the review system. @hughsie can perhaps verify that.

**Comment by Jehan** [comment]
Thanks.
@hughsie Yes, we would appreciate your input on this. Is this right: GIMP now installs a `org.gimp.GIMP.appdata.xml` and a `gimp.desktop`. The appdata contains:

```
<id>org.gimp.GIMP</id>
<launchable type="desktop-id">gimp.desktop</launchable>
<provides>
    <id>gimp.desktop</id>
</provides>
```

Cf. files in: https://git.gnome.org/browse/gimp/tree/desktop
Is this a good setup?

Will a software such as GNOME software unify older `gimp.desktop` and newer `org.gimp.GIMP` application IDs? Seriously I did the change but even now, I am still wondering if this is really ideal. If I get it right, we will have a single entry for GIMP for both the flathub build and the one from the distribution repository. Is it really for the best? Clicking "install", which version will it install?
What if someone wants to install both? (some features are still lost in flatpak due to current limitation of the technology)
I understand the unification need, but in the same time, I am a bit reluctant and wonder if that is the best move.

Also will all the previous reviews for the software be salvaged thanks to this `<provides><id>`?

Are we missing something?

**Comment by hughsie** [comment]
> Also will all the previous reviews for the software be salvaged thanks to this <provides><id>?

Yes, we'll match all the IDs when getting reviews. I'm not sure I have much to add on the reverse DNS thing.

**Comment by Jehan** [comment]
Ok let's just close the question then.
I guess we'll do like this for now.
Thanks everyone!
