### ISSUE TITLE
CLI install completion could be more useful

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#1304]
Today I wanted to install Peek from Flathub, so I typed:

```
$ flatpak install flathub 
```

At this point I realized I didn't know the whole app id for Peek. I could have searched for it with a quick `remote-ls | grep` but I didn't want to lose my already typed command.

So I hit the <tab> key, and was presented with:

```
$ flatpak install flathub 
Display all 771 possibilities? (y or n)
```

The list I got when typing "y" was not the most helpful thing, and I ended up having to `remote-ls | grep` anyway.

For each app, Flathub builds up to 4 things:

* the app
* the `.Locale` extension
* the `.Debug` extension
* the `.Sources` bundle

If the `flatpak install` completion were to only list the actual apps (not their extensions) then that would cut the list to 272 items as of this writing, which is much more useful.

Of course, the nature of Flathub makes it a bit of an extreme no matter what: it is meant to host lots of apps, and with too many apps, the list gets too long and there's not much to do about that.

However, what I'm suggesting here would make things "less bad" for Flathub, and it would certainly be a net improvement for other, more reasonably-sized repositories.

What could be done is the following:

* when the completion resolves to multiple apps, then it should only list the apps, not their extensions
* when the completion resolves to a single app, then it should list the extensions

That is, if I type:

```
$ flatpak install flathub <tab>
```

The I get the list of apps, but not their extensions.

But if I type the following then I get:

```
$ flatpak install flathub com.uploadedlobster.peek<tab>
com.uploadedlobster.peek          com.uploadedlobster.peek.Debug
com.uploadedlobster.peek.Locale   com.uploadedlobster.peek.Sources
```

Does that seem reasonable?

**Comment by allanday** [comment]
Another way to handle this would be to provide suggestions if there's only a partial match on an app id. For example:

```
$ flatpak install flathub peek
Remote 'flathub' does not contain 'peek'. Did you mean:
      com.uploadedlobster.peek
```

This is in line with what's been discussed in issue #1290 and it's what I've been sketching [on the wiki](https://github.com/flatpak/flatpak/wiki/CLI-experimental-design#errors).

**Comment by bochecha** [comment]
@allanday That also seems like a great UX improvement, but I don't think both are mutually exclusive. 🙂

**Comment by alexlarsson** [comment]
The completion does not include the .Locale/.Source/etc stuff anymore in recent versions.
