### ISSUE TITLE
CLI: non-functional abort option when selecting an installation

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#1305]
If I run `$ flatpak remote-ls flathub`, the CLI asks the following:

```
Remote ‘flathub’ found in multiple installations:
1) user
2) system
Which do you want to use (0 to abort)? [1-2]:
```

If I enter `0` and press return, it repeats the question `Which do you want to use (0 to abort)? [1-2]:`.

It looks like it doesn't respond to option `0`.

(The question itself seems a bit clumsy - I don't really think of user and system as installations and the presentation of the options could be nicer, but maybe that's an issue for another day.)

**Comment by mwleeds** [comment]
Thanks for catching that. I really thought I tested it but I guess not
