### ISSUE TITLE
flatpak search command does not work (v 0.10.2.1)

### ISSUE THREAD

**Issue by Fak3** [flatpak/flatpak#1306]
Hi. I installed flatpak 0.10.2.1 on openSUSE Tumbleweed. Added flathub repo:
```
> flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> flatpak remotes -dv
F: Opening user flatpak installation at path /home/u1/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
Name                             Title                                  URL                          Priority Options            
flathub                          Flathub                                https://dl.flathub.org/repo/ 1        system        
```
Now when i try to search for any app name, it does not find anything:
```
> flatpak search Audacity
No matches found
```

Also flatpak search does not work in KDE Discover app, it only shows results from configured openSUSE repositories.

### Additional notes
When i go to https://flathub.org/apps.html in firefox browser and click Audacity, the KDE Disover opens up and suggests me to install Audacity (as expected). I was able to successfully install it this way. After that I noticed that new duplicated repository was added to the list of flatpak remotes (that's another issue, not sure if KDE Discover or flatpak is the culprit):
```
> flatpak remotes -d
Name                             Title                                  URL                          Priority Options            
flathub                          Flathub                                https://dl.flathub.org/repo/ 1        system             
org.audacityteam.Audacity-origin org.audacityteam.Audacity from flathub https://dl.flathub.org/repo/ 0        system,no-enumerate
```

**Comment by TingPing** [comment]
You do have to run `flatpak update --appstream` at least once.

**Comment by mwleeds** [comment]
Closing this in favor of #1339 which has a better description

**Comment by illettante** [comment]
> 

should that be in the quick setup guide
