### ISSUE TITLE
How to add Gnome starter for flatpak apps

### ISSUE THREAD

**Issue by stehgold** [flatpak/flatpak#1308]
Hi,

maybe I'm to numb to google but I couldn't find an answer.

I've installed MonoDevelop using flatpak (Debian comes with 5.10) and can start this from CLI.

flatpak run org.desktop.monodevelop

Using Alacarte I've created this MonoDevelop.Desktop file:

[Desktop Entry]
Comment=
Terminal=false
Name=MonoDevelop
Exec=flatpak run org.desktop.MonoDevelop
Type=Application
Icon=/home/oppa/.local/share/flatpak/app/com.xamarin.MonoDevelop/current/active/files/share/icons/hicolor/48x48/apps/com.xamarin.MonoDevelop.png
Name[en_GB]=MonoDevelop

I can find the Icon in Gnomes "Application Menu" but a click on this does not launch MonoDevelop.

So - How Do I ?

Regards,
Stephan

**Comment by mwleeds** [comment]
The flatpak should install a desktop file for you. You shouldn't have to do that. You may have to log out and back in if you installed flatpak in the same session.

Does `~/.local/share/flatpak/exports/share/applications/com.xamarin.MonoDevelop.desktop` exist?

**Comment by alexlarsson** [comment]
We have some docs here: http://docs.flatpak.org/en/latest/getting-started.html
