### ISSUE TITLE
Architecture-conditional stanzas in flatpak-builder manifest

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#1315]
On rare occasion, it might be necessary to modify the content of a builder manifest, depending on the target CPU architecture - for example, passing different configure flags modifying FPU parameters on an ARM build, or entirely different patches, archives, etc.

It should be possible to do this, without the maintenance nightmare of multiple builder manifests (especially in the absence of any `#include`-like behaviour to keep common components in one place)

**Comment by Barthalion** [comment]
This is already possible if you have relatively new flatpak-builder. You can pass different [build-options](https://github.com/flathub/org.freedesktop.Sdk.Extension.gcc7/blob/master/org.freedesktop.Sdk.Extension.gcc7.json#L48) and [limit a source to given architecture](https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L83).

Is there anything else you have in mind?

**Comment by Barthalion** [comment]
Also `only-arches` and `skip-arches` can be specified on the module level, not only for sources.

**Comment by directhex** [comment]
Perfect. Thanks @Barthalion
