### ISSUE TITLE
Proposal to default Gtk2 apps to Adwaita theme

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#1322]
(I know this is not for flatpak but the gnome runtime, but i cannot report issues there)

Currently if the user has a theme other than Adwaita installed, eg Arc, when they launch Gtk2 apps they appear without any theme and look like an app from the 1990s ! This happens for many popular apps (eg Atom, GIMP, Inkscape, HexChat to name a few) which are potentially a users first flatpak they install and frankly these apps look terrible and out of place (see the screenshot)

![screenshot from 2018-01-18 20-25-56](https://user-images.githubusercontent.com/3669750/35119747-d1bdcafa-fc8d-11e7-8ad7-f095a8c25603.png)

This can be resolved for powerusers by using the environment override for each app `GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc`, however most GUI users are unlikely to do this.

My proposal is to default all Gtk2 apps to using Adwaita as then the apps at least looks modern and not massively out of place (Adwaita themed GIMP on an Arc host doesn't really look terrible).

The main disadvantage I see to this is that users may think that this is a bug (that the apps are using Adwaita instead of their host theme) as there is no discoverable way to find out that these apps are Gtk2 and therefore not themed. But maybe, as there are discussions about allowing apps for force a theme (eg Builder to Adwaita or elementary apps), there should be a "themeable" field in appstream or something so that software stores (such as gnome-software) could show if the app has the ability to be themeable.

**Comment by alexlarsson** [comment]
I agree, lets change the default to adwaita, and disable getting the users theme configuration from the xsettings. This will let apps that hardcode things do whatever they want, but should use adwaita in most cases. So, something like this:

```
diff --git a/gdk/x11/gdkevents-x11.c b/gdk/x11/gdkevents-x11.c
index 186a8f5cb2..15f5c0f386 100644
--- a/gdk/x11/gdkevents-x11.c
+++ b/gdk/x11/gdkevents-x11.c
@@ -3033,6 +3033,12 @@ gdk_screen_get_setting (GdkScreen   *screen,
   
   g_return_val_if_fail (GDK_IS_SCREEN (screen), FALSE);
   
+  /* Neuter xsettings in gtk-theme-name in flatpaks, as we don't have
+     gtk2 theme support, so we rely on the default (Awaita, which we
+     ship) or whatever the app told us to use. */
+  if (strcmp ("gtk-theme-name", name) == 0)
+    return FALSE;
+
   screen_x11 = GDK_SCREEN_X11 (screen);
 
   for (i = 0; i < GDK_SETTINGS_N_ELEMENTS(); i++)
diff --git a/gtk/gtksettings.c b/gtk/gtksettings.c
index 3fbbf00548..bad04dad78 100644
--- a/gtk/gtksettings.c
+++ b/gtk/gtksettings.c
@@ -312,7 +312,7 @@ gtk_settings_class_init (GtkSettingsClass *class)
 #ifdef G_OS_WIN32
 								  "MS-Windows",
 #else
-								  "Raleigh",
+								  "Adwaita".
 #endif
 								  GTK_PARAM_READWRITE),
                                              NULL);
```

**Comment by TingPing** [comment]
We do have both `Adwaita` and `Adwaita-dark` so there is slight customization that is supported.

I also personally think Gtk2 themes should happen at some point, the only blocker there is it being annoying on package maintainers.

**Comment by alexlarsson** [comment]
I think the problem with Gtk2 is that if the users xsettings theme name does not exist, it doesn't fall back to the next theme name, it just relies on the default values of everything, which reproduces raleigh.

**Comment by alexlarsson** [comment]
So, we ignore xsettings for the theme name if we can't find a directory + rc file matching that name?

**Comment by alexlarsson** [comment]
No, the default values are whatever is compiled into gtk, not the default value of the theme name.
Basically, it will always look like Raleight (but it might not load the empty raleigh rc file).

**Comment by TingPing** [comment]
Ofc but we are talking about patching gtk here...

**Comment by alexlarsson** [comment]
I'm not sure what you mean then. Basically the current gtk2 has no way to specify a fallbact theme by name, it will try to load the theme the user configured, and if that fails, load no theme at all.

The easiest way to work around that seems to me to set the default theme name to something we know works (Adwaita), and filter the users xsetting, such that we ignore any data from it that we know will not work.

**Comment by alexlarsson** [comment]
Merging this atm.
