### ISSUE TITLE
Tagging support

### ISSUE THREAD

**Issue by MatMaul** [flatpak/flatpak#1323]
Is it possible to allow tagging of a versionned app ?
My use case would be I build an app with some app extension. I specify 1.0 as a branch since my extension would not work with 2.0.
However on top of that I would like to handle gracefully updates of the app even to a new major version, so at the end people using stable tag get a 2.0 update, with the 1.0 installed extension then ignored.
If I just use stable and no versioning and forget to update the plugin at th same time it could break some stuffs.

**Comment by alexlarsson** [comment]
That is not currently possible. However, you could make it work by having a "1.0" subdirectory in your extension, and bumping what you look for in the app.
