### ISSUE TITLE
Build app extension fails

### ISSUE THREAD

**Issue by MatMaul** [flatpak/flatpak#1324]
```json
{
  "id": "org.myorg.MyApp.Plugin.toto",
  "build-extension": true,
  "branch": "1.0",
  "runtime": "org.myorg.MyApp",
  "runtime-version": "1.0",
  "sdk": "org.myorg.MyApp.Debug",
  "modules": [
    {
      "name": "toto",
      "sources": [
        {
          "type": "archive",
          "url": "toto.tar.gz",
          "sha256": "ff53d1d01cacc29c071e23192dfefa93bdbeaf775fc5d296259b4859d0306b79"
        },
        {
          "type": "script",
          "commands": [
            "autoreconf -fiv"
          ],
          "dest-filename": "autogen.sh"
        }
      ]
    }
  ]
}
```
It fails with `bwrap: execvp ./autogen.sh: No such file or directory`.
Doing the same stuff but with a runtime extension works fine.

I am not putting that in flatpak-builder tracker since the build-init and build issued commands seem to be the same between runtime extension and app extension, so my guess is a bug in flatpak itself.

**Comment by MatMaul** [comment]
Ok so I managed to build my app extension without using flatpak-builder and with a hack, and it works :)

The problem is that after build-init currently metadata file contains:
```
[Runtime]
name=org.myorg.MyApp.Plugin.toto
sdk=org.myorg.MyApp.Debug/x86_64/master
[ExtensionOf]
ref=app/org.myorg.MyApp/x86_64/master
```
While it should contain:
```
[Runtime]
name=org.myorg.MyApp.Plugin.toto
sdk=org.freedesktop.Sdk/x86_64/1.6
[ExtensionOf]
ref=app/org.myorg.MyApp/x86_64/master
```
Overriding the metadata file with that after build-init and before the first build "fixes" the problem.

**Comment by alexlarsson** [comment]
I'm not sure why you are surprised that the sdk is org.myorg.MyApp.Debug? That is what you list in the json:
```
  "sdk": "org.myorg.MyApp.Debug",
```
In app extensions i've made before i put instead org.freedesktop.Sdk there.

**Comment by MatMaul** [comment]
Cf my comment on the related PR 😉
