### ISSUE TITLE
Building flatpaks in containers

### ISSUE THREAD

**Issue by johnramsden** [flatpak/flatpak#1326]
I'm trying to build a flatpak with `flatpak-builder` in a Docker container and keep ending up getting `bwrap` errors. I have tried running Docker with `-cap-add ALL`, as well as setting `bwrap`, `flatpak`, and `flatpak-builder` setuid. No matter what I've tried I'm getting errors.

I'm running flatpak-builder with:

```
flatpak-builder --disable-rofiles-fuse --disable-cache --force-clean \
                        --repo=${LOCAL_REPO} \
                        "${FLATPAK_NAME}" "${FLATPAK_DNS_PREFIX}.${FLATPAK_NAME}.json"
```

What I get when I do not set `--cap-add ALL` is:

```
bwrap: Creating new namespace failed: Operation not permitted
```

And if I do, I get a `pivot_root` error.

```
pivot_root: Operation not permitted
```

Is it possible to run `flatpak` in a container?

**Comment by johnramsden** [comment]
I believe I've gotten it to work by running docker with `---privileged`.

**Comment by MihaiTabara** [comment]
Follow-up on this, has anyone found a way to overcome this problem without enabling the container access to all devices on the host?
