### ISSUE TITLE
Add distutils support to builder

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak#134]
Quite a lot of Python projects use distutils/setuptools and would be nice to support that. Something like:

``` json
"modules": [
  {
    "name": "...",
    "no-autogen": true,
    "distutils": true
  }
]
```

That seems consistent with `cmake`. It would check for `setup.py`, run `./setup.py build --prefix=...` and `./setup.py install --prefix=... --optimize=1 --skip-build`. Though some projects don't have an exectuable setup.py so there would have to be another variable for python2 vs python3 in that case...

**Comment by alexlarsson** [comment]
See also https://github.com/flatpak/flatpak/issues/39

**Comment by bochecha** [comment]
> Though some projects don't have an exectuable setup.py so there would have to be another variable for python2 vs python3 in that case...

How about running `$PYTHON setup.py ...` instead?

The `PYTHON` env var could be set to `/usr/bin/python2` by default, and each JSON manifest could set it to something else instead? It would even help with finding a different Python version in `/app` as well.

**Comment by TingPing** [comment]
Possible. @alexlarsson also mentioned the idea of a "simple" buildsystem type where you just directly give it the configure and make commands which would be sufficient for this.

**Comment by alexlarsson** [comment]
Yes, having a buildsystem type that basically does nothing, but lets you list some commandlines to run, similar to post-install, or maybe even actually use post-install.

**Comment by TheBiggerGuy** [comment]
For reference I have found this the most effect pattern for Python packages.
```json
{
  "name": "cheetah",
  "no-autogen": true,
  "sources": [
    {
      "type": "archive",
      "url": "https://pypi.python.org/packages/cd/b0/c2d700252fc251e91c08639ff41a8a5203b627f4e0a2ae18a6b662ab32ea/Cheetah-2.4.4.tar.gz",
      "sha256": "be308229f0c1e5e5af4f27d7ee06d90bb19e6af3059794e5fd536a6f29a9b550"
    }, {
      "type": "shell",
      "commands": [ "echo 'all:\n\ninstall:\n\tpython ./setup.py install --prefix=/app' > makefile" ]
    }
  ]
}
```

Naturally full support for Python as a first class build system would be preferably. This would be ideal.
```json
{
  "name": "cheetah",
  "buildsystem": "setup.py",
  "sources": [
    {
      "type": "archive",
      "url": "https://pypi.python.org/packages/cd/b0/c2d700252fc251e91c08639ff41a8a5203b627f4e0a2ae18a6b662ab32ea/Cheetah-2.4.4.tar.gz",
      "sha256": "be308229f0c1e5e5af4f27d7ee06d90bb19e6af3059794e5fd536a6f29a9b550"
    }
  ]
}
```

**Comment by alexlarsson** [comment]
Alternatively we could have a buildsystem: "simple", which just lets you type in an array of commands to run.

**Comment by TingPing** [comment]
Python modules are fairly common to the point where a built-in option for it would be nice though.

**Comment by bochecha** [comment]
> Python modules are fairly common to the point where a built-in option for it would be nice though.

Except some work with `python setup.py build -j X`, but others fail as they don't know this option (because distutils vs setuptools).

And some work fine when you split `python setup.py build` and `python setup.py install --skip-build`, but others don't. (e.g numpy)

Etc...

And in the future, Python modules will have a `pyproject.toml` file and the Python packaging will probably change a lot (started with PEP 518, but there's still lots to do), to the point where `setup.py` files might disappear entirely.

So maybe for now the `"buildsystem": "simple"` approach is still the simplest for flatpak.

Plus, it's needed for other things than Python anyway. (I'm looking at you Boost and your `b2` tool)

**Comment by alexlarsson** [comment]
So, who wants to do "buildsystem": "simple"? :)

**Comment by bochecha** [comment]
Should we close this now that we have the `simple` buildsystem?

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#5
