### ISSUE TITLE
bwrap: Can't mkdir /app/lib/jvm: Read-only file system

### ISSUE THREAD

**Issue by trialism** [flatpak/flatpak#1341]
I used this finish-args:

```
    "finish-args": [
        "--device=dri",
        "--filesystem=xdg-run/dconf", "--filesystem=~/.config/dconf:ro",
        "--share=ipc",
        "--share=network",
        "--socket=pulseaudio",
        "--socket=wayland",
        "--socket=x11",
	"--persist=.",
        "--talk-name=ca.desrt.dconf", "--env=DCONF_USER_CONFIG_DIR=.config/dconf",
	"--extension=org.freedesktop.Sdk.Extension.openjdk9=version=1.6",
	"--extension=org.freedesktop.Sdk.Extension.openjdk9=directory=lib/jvm",
	"--extension=org.freedesktop.Sdk.Extension.openjdk9=subdirectories=true"
    ],
```

and after starting the app it returned with:

```
bwrap: Can't mkdir /app/lib/jvm: Read-only file system
error: ldconfig failed, exit status 256
```

I thought `lib/jvm` means `/usr/lib/jvm`. Why I am getting this error?

flatpak version: Flatpak 0.10.2.1
flatpak-builder version: flatpak-builder 0.10.5

**Comment by trialism** [comment]
It seems like it won't create /app/lib/jvm.

**Comment by trialism** [comment]
So, how could we change the content under /usr at build?

**Comment by trialism** [comment]
Bonus question: how can I access the internet when running make?

**Comment by smcv** [comment]
> I thought `lib/jvm` means `/usr/lib/jvm`. Why I am getting this error?

`lib/jvm` means `/usr/lib/jvm` if you are building a runtime, but `/app/lib/jvm` if you are building an app.

> It seems like it won't create /app/lib/jvm.

It can't: `/app` is mounted read-only from the Flatpak deployment. Your app needs to contain an empty `lib/jvm` onto which the extension can be mounted.

**Comment by ptomato** [comment]
It would be _really_ nice if this were somehow discoverable in the flatpak-builder documentation.

**Comment by michelinux8** [comment]
same error on different dir:
`bwrap: Can't mkdir parents for /usr/share/runtime/lib/plugins: Read-only file system`

**Comment by smcv** [comment]
> It would be *really* nice if this were somehow discoverable in the flatpak-builder documentation.

Can you suggest a patch that would add this information somewhere you would have looked for it?

> same error on different dir

Same answer: if you want to mount an extension on a directory under `/usr`, then the directory (probably empty) needs to exist in the runtime; if you want to mount an extension on a directory under `/app`, then the directory needs to exist in the app.

**Comment by ptomato** [comment]
OK, see https://github.com/flatpak/flatpak/pull/1927 and https://github.com/flatpak/flatpak-builder/pull/187

**Comment by DonaldKellett** [comment]
> > It would be _really_ nice if this were somehow discoverable in the flatpak-builder documentation.
> 
> Can you suggest a patch that would add this information somewhere you would have looked for it?
> 
> > same error on different dir
> 
> Same answer: if you want to mount an extension on a directory under `/usr`, then the directory (probably empty) needs to exist in the runtime; if you want to mount an extension on a directory under `/app`, then the directory needs to exist in the app.

May I suggest the Flatpak development team to add a Flatpak developer FAQ which addresses various build issues commonly encountered by first-time Flatpak developers/packagers? For example, the read-only filesystem issue seems quite commonly encountered in various different places, but there doesn't seem to be a general guideline how to troubleshoot and fix it.

No offense, but I've recently tried packaging for both Snap and Flatpak (similar ??? technologies that often get compared to each other) and the Snap packaging experience is just so much more straightforward and well-documented. I've now understood to sympathize with ISVs who only create Snaps for their software products (ignoring traditional package management) and refuse to provide Flatpaks.
