### ISSUE TITLE
Interaction between OCI and P2P support

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1350]
I noticed [here](https://github.com/flatpak/flatpak/blob/46db046b55060446290a1dc915dda8685b869334/app/flatpak-builtins-add-remote.c#L386) that enabling OCI support disables GPG, but using collection IDs forces GPG to be used. So it seems those two features are incompatible at the moment.

**Comment by alexlarsson** [comment]
Well, collection IDs imply ostree, no? I mean OCI completely replaces the pull code, so this should not really affect anything?

**Comment by mwleeds** [comment]
okay, I just didn't understand anything about the OCI support
