### ISSUE TITLE
Please create runtime for nvidia-340-106 drivers

### ISSUE THREAD

**Issue by dkayser** [flatpak/flatpak#1358]
I upgraded to the latest nvidia drivers of the 340 branch on Debian Buster. Now there's a version mismatch, causing flatpaks to break. 

My kernel:
```
Linux 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14)
```

My Nvidia driver:
```
$ cat /sys/module/nvidia/version  
340.106
```

On Flatpak:

```
flatpak remote-ls gnome | grep nvidia-340
org.freedesktop.Platform.GL.nvidia-340-101  
org.freedesktop.Platform.GL.nvidia-340-102  
org.freedesktop.Platform.GL.nvidia-340-104  
org.freedesktop.Platform.GL32.nvidia-340-101
org.freedesktop.Platform.GL32.nvidia-340-102
org.freedesktop.Platform.GL32.nvidia-340-104
```
Would be great if you could update the platform drivers.

On a sidenote, I had cgroup errors like
```
systemd[1645]: flatpak-com...: Failed to add PIDs to scope's control group: Permission denied
systemd[1645]: flatpak-com...: Failed with result 'resources'.
systemd[1645]: Failed to start flatpak-com....-63945.scope.
```

Which I could only solve by manually running:

```
chown -R $user:$user /sys/fs/cgroup/systemd/
chown -R $user:$user /sys/fs/cgroup/unified/
```
I don't know if that's a good solution. I understand it's a deeper issue with systemd cgroups, but I was wondering if meta information on these issues could somehow be included in the flatpak files and shown to the user on installation, to make these errors easier to debug.

**Comment by dkayser** [comment]
Many thanks, will this be merged or would it be better if I changed over to your fork?

**Comment by TingPing** [comment]
@dkayser @alexlarsson Should merge it soon.

**Comment by alexlarsson** [comment]
In flathub now
