### ISSUE TITLE
No docs in GnuCash on Mint18

### ISSUE THREAD

**Issue by cleanman2** [flatpak/flatpak#1364]
I installed the GnuCash flatpak from the Mint Software Manager. The program loaded and ran, but when I clicked on a help topic I got an error message. It seems there is a separate docs package that apparently is not in the flatpak.

Just letting you know.

Regards,  Jim

**Comment by julianrichen** [comment]
I believe the Mint Software Manager uses flathub as the source of the flatpaks. You would be better posting the issue in the respective repo on flathub since it's a packaging issue with GnuCash not flatpak itself.

https://github.com/flathub/org.gnucash.GnuCash

**Comment by cleanman2** [comment]
Thank you, I didn't know the correct procedure.

Regards,  Jim
