### ISSUE TITLE
Installed Flatpak Gtk theme isn't applied in MATE

### ISSUE THREAD

**Issue by lmintmate** [flatpak/flatpak#1371]
I installed Arc as a flatpak theme, and it didn't apply, as in e.g. LibreOffice it still used Adwaita, and then tried Greybird and still the same (and LibreOffice in its Flatpak page says it uses 3.24). The system theme I use is not the same as the Flatpak theme installed, as I use Zukitwo otherwise (I used to use Arc but since going to MATE 1.18 via the update from Mint 18.1 to 18.2 it messes my tasklbar). Here's some system info:
My system:
Linux Mint 18.3
Flatpak 0.10.0
Desktop: MATE 1.18 (Gtk3)
Kernel 4.4.0-109-generic
Currently installed flatpak packages:
```
flatpak list                                      
Ref                                            Options               
com.github.robertsanseries.ciano/x86_64/stable system,current        
com.skype.Client/x86_64/stable                 system,current        
org.audacityteam.Audacity/x86_64/stable        system,current        
org.gnome.clocks/x86_64/stable                 system,current        
org.gnome.gitg/x86_64/stable                   system,current        
org.libreoffice.LibreOffice/x86_64/stable      system,current        
io.elementary.code.Locale/x86_64/stable        system,runtime,partial
org.freedesktop.Platform.ffmpeg/x86_64/1.6     system,runtime        
org.freedesktop.Platform/x86_64/1.6            system,runtime        
org.freedesktop.Sdk/x86_64/1.6                 system,runtime        
org.gnome.Platform/x86_64/3.24                 system,runtime        
org.gnome.Platform/x86_64/3.26                 system,runtime        
org.gnome.gedit.Locale/x86_64/stable           system,runtime,partial
org.gtk.Gtk3theme.Greybird/x86_64/3.22         system,runtime
```
I also don't seem to have the .config/gtk-3.0/settings.ini file (only a bookmarks file is in there).
Hopefully this can be resolved somehow. Thanks in advance for understanding.

**Comment by TingPing** [comment]
Just to avoid variables try a normal Gtk3 application like `org.gnome.Calculator` also in your pasted list you do not have `org.gtk.Gtk3theme.Arc` installed.

**Comment by TingPing** [comment]
> The system theme I use is not the same as the Flatpak theme installed,

Oh well that is problematic itself, there isn't really a sane way to set a theme just for one app. `GTK_THEME=Arc` is more of a development feature.

**Comment by lmintmate** [comment]
About your comment on the Arc theme not being there, I removed the Arc theme in the meanwhile, because I thought that having 2 themes installed at the same time would confuse the system.
Here are side by side, on the left the calculator installed by default on Linux Mint (an older version of gnome-calculator) and on the right the gnome-calculator flatpak. The calculator on the left integrates relatively well with the system - the minimize and close buttons aren't of the theme (because it _is_ gnome-calculator) but everything else is, and the dropdown radio buttons under the basic function label (my system's in Greek) are of the theme on the left calculator and Adwaita's on the right.
![calculators](https://user-images.githubusercontent.com/26282842/35690359-53b43b8e-077e-11e8-91c1-46c8b76f93f9.png)
I wonder whether gnome-calculator was supposed to look more like the system one or not, given that gitg and gnome-clocks also look gnome-y, and I'm also not sure whether the elementary os apps (like ciano) are also supposed to look elementaryos-ey. 
In regards to LibreOffice (where the problem annoyed me the most as it's the one I use more often), after searching some more, I saw [this issue](https://github.com/flathub/org.libreoffice.LibreOffice/issues/4), which might have something to do with it not respecting my theme, and the last comment seems to suggest that I should update my Flatpak version.
Then there's also Audacity, which I recently installed as flatpak, which also doesn't respect my theme in regards to the controls, but uses Adwaita instead (which is also annoying, as I can't scroll down at least for the helpful tips and about menu for some reason).
![audacity](https://user-images.githubusercontent.com/26282842/35691073-35f6cf24-0780-11e8-99d3-5cd37cb388a0.png)
Admittedly, when I saw the LibreOffice issue, I worried whether I had opened this issue without good reason, but Audacity at least sets it straight, because the system version integrates with the theme. Here it is, for comparison:
![audacity2](https://user-images.githubusercontent.com/26282842/35691330-de4fec32-0780-11e8-9e68-a5e8e8d9c10e.png)
Hope this info helps. Please let me know in case I need to update my flatpak version (via [this PPA](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak), for example) - I'm not going to do it for the moment, to keep all the possible variables in play as they are.

**Comment by TingPing** [comment]
So this is just a misunderstanding of how themes work in Flatpak. Installing a Flatpak of a theme does nothing but add the theme files. It does not configure anything as that is configured by the host. So you need the host to be configured to use the same theme for anything to work.

**Comment by lmintmate** [comment]
So, if I understand correctly, I'd need Arc installed both system-wide and as Flatpak for the Arc theme to apply, Greybird installed both system-wide and as Flatpak to apply e.t.c. I guess I might have to put up with Adwaita then, because most of the currently available as Flatpak themes (as seen by the command `flatpak remote-ls flathub | grep org.gtk.Gtk3theme` -mentioned in [your blog post](https://tingping.github.io/2017/05/11/flatpak-theming.html) look awful on my system for whatever reason. I already mentioned the problem with Arc, and I also didn't like/  had bugs with the way Adapta, Ambiance, Greybird and Numix look on my system. I haven't tried yet Breeze (don't know whether there's even a Gtk version of that one - doubtful), Pop (which isn't afaik available for Xenial which Mint is based on) and Elementary (again no idea whether there's even an accessible to Mint version of that). So it looks like I'll either have to change my current system theme to one of those supported by Flatpak, put up with having Adwaita on Flatpaks (with all ensuing annoyances) or waiting to see whether Zukitwo/Zukitre will be released as Flatpak themes (again doubtful, though I could try to ask the developer - but then I'm not completely thrilled about that theme either -it's just something that looked nice when others didn't- so it's not like I have a burning desire to see it as Flatpak).
In the meanwhile, to make certain that the "problem" was indeed my bad understanding of the current theming system, I'll temporarily change my theme to Greybird (since I already have the Flatpak version installed), which also looks the least worse on my system iirc (it only looks cramped I guess), and let you know if the problem was solved.
Update: You'll be glad to know that LibreOffice and Audacity now fully integrate to the Greybird theme, while gnome-calculator, gitg, gnome-clocks and ciano partially integrate (only certain buttons), but most probably because they didn't integrate before -when they were systemwide- either. 
So, I guess the problem was me not understanding that I absolutely have to have the same theme both systemwide and Flatpak in order for it to apply - a documentation problem that is. This fact should probably be made clearer/put in a more promiment position then, at least until (if) a solution allowing for having different themes systemwide and Flatpak (because, at least I, would want to have anything but Adwaita in regards to Flatpak, but I might not want to limit my system theme choices to the themes available as Flatpak).
Sorry for taking up your time like that - I guess that technically my problem is now solved since Flatpak now look the same as the system, even if the system now doesn't look the way I'd want it to.

**Comment by TingPing** [comment]
Anybody can package the Zukitwo theme; It is mostly copy pasting an existing theme flatpak.

**Comment by lmintmate** [comment]
Oh, I didn't know that. Then I might take a stab at packaging it myself in the near future, I do wonder how I'll publish it though, since it'll somewhow have to be known to Flathub. Since you're here, do you perhaps have any pointers as to where I can look fo info on that?

**Comment by TingPing** [comment]
https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

Here is a theme to start as a base: https://github.com/flathub/org.gtk.Gtk3theme.Numix

**Comment by lmintmate** [comment]
Thanks a lot!
I guess you can close the issue whenever you want btw, because either adding more details on how theming works on the documentation or me creating the Zukitwo Flatpak theme are different issues from the one I was having, which is technically resolved. (I generally prefer not to close issues myself).

**Comment by TingPing** [comment]
Feel free to poke me if you have any more questions (Ideally on IRC ircs://chat.freenode.net/flatpak)

**Comment by AnwarShah** [comment]
@TingPing  Sorry to bother you. I'm new to flatpak things and am wondering is it possible to use a flatpak theme system-wise without having it in host? For example, if I have Arc flatpak theme installed, can I use it in system apps?

**Comment by TingPing** [comment]
@AnwarShah 	no.

**Comment by AnwarShah** [comment]
That's bad. Snap have this support I guess

**Comment by TingPing** [comment]
Flatpak doesn't exist to install system components.
