### ISSUE TITLE
remote-ls --update does not seem to take remote from flatpak into account

### ISSUE THREAD

**Issue by janvlug** [flatpak/flatpak#1372]
I have org.gnome.Platform/x86_64/3.26 from gnome, but when I do flatpak remote-ls -d --updates, I see:
runtime/org.gnome.Platform/x86_64/3.26 flathub c4d67937b041 782.3 MB       296.7 MB
as if the flatpak from gnome is tested against flathub.
Also flatpak update runtime/org.gnome.Platform/x86_64/3.26 does not perform the update.
I'm using Flatpak 0.10.2.1

**Comment by mwleeds** [comment]
The `flatpak update` failure sounds like a separate issue you could open a bug report for but the `remote-ls --updates` issue was fixed in a088c2b33dd0f04c7a35423969fa2c243b39a2b1.
