### ISSUE TITLE
g_app_info_get_default_for_uri_scheme does not work

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flatpak/flatpak#1375]
According to the call chain

https://github.com/zotero/zotero/blob/5.0.34.4/chrome/content/zotero/xpcom/zotero.js#L1102

https://github.com/zotero/zotero/blob/5.0.34.4/chrome/content/zotero/xpcom/file.js#L46

https://github.com/mozilla/gecko-dev/blob/6e98dc2b7bfd2ba9a6b7a62b14dd8f151f040d53/toolkit/modules/FileUtils.jsm#L175

https://github.com/mozilla/gecko-dev/blob/6e98dc2b7bfd2ba9a6b7a62b14dd8f151f040d53/xpcom/io/nsLocalFileUnix.cpp#L1996

https://github.com/mozilla/gecko-dev/blob/6e98dc2b7bfd2ba9a6b7a62b14dd8f151f040d53/toolkit/system/gnome/nsGIOService.cpp#L352

Eventually `g_app_info_launch_default_for_uri` is called when the user tries to open an PDF file in `flatpak`ed Zotero, but nothing happens. Probably attaching a debugger to a developer build would be better, but I don't have enough resource to do it.

Thanks!

**Comment by TingPing** [comment]
Yes your app doesn't know applications on the host (nor could it do much with that information). You can really only use `g_app_info_launch_default_for_uri()` which should work via the portal.

**Comment by amtlib-dot-dll** [comment]
Sorry for my typo, the actually called API is `g_app_info_launch_default_for_uri` but it doesn't work either

**Comment by TingPing** [comment]
Well it calls the Flatpak portal: https://github.com/GNOME/glib/blob/master/gio/gappinfo.c#L740-L765

**Comment by amtlib-dot-dll** [comment]
Yeah, I wonder whether [`launch_default_for_uri` above](https://github.com/GNOME/glib/blob/master/gio/gappinfo.c#L746) returns without calling the portal 🤔

**Comment by matthiasclasen** [comment]
Did you fix your problem here ?

**Comment by matthiasclasen** [comment]
please reopen if the issue persists
