### ISSUE TITLE
Suggest installing as a user if installing as system fails

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#1376]
I keep all my flatpak applications installed using the --user flag, but I often forget to type --user. 

Fx when I do "flatpak update com.skype.Client" I get it fails with "The command fails due to "GPG verification enabled, but no summary signatures found".

Or when I do "flatpak uninstall com.skype.Client" I would get ""error: com.skype.Client master not installed".

Maybe instead of just failing, we could suggest something like "did you mean --user?" or perhaps even be clever about it (unless there are security concerns there), search for the app in --user and only then ask "com.skype.Client found installed in --user flatpak tree, did you forget to type --user?"

(Note: Didnt put much effort into the formulation, but hope the idea got across!).

**Comment by alexlarsson** [comment]
Current flatpak automatically picks the right location now, or asks you, so this should be ok.
