### ISSUE TITLE
Can't add/set flatpak remotes in Linux Mint 18.3

### ISSUE THREAD

**Issue by farzado** [flatpak/flatpak#1378]
I have Flatpak version 0.10.2.1 installed, but `flatpack remotes` returns empty and when I try to add a repository via `flatpak remote-add --if-not-exists flathub http://dl.flathub.org/repo/flathub.flatpakrepo`, it gives the following error message: 

> Can't load uri http://dl.flathub.org/repo/flathub.flatpakrepo: TLS support is not available

I have also checked and the glib-networking is installed on my machine.

**Comment by mwleeds** [comment]
Is there a reason you're using an HTTP link to flathub rather than HTTPS?

**Comment by mwleeds** [comment]
Looks like flatpak automatically rewrites `http://` to `https://`. Check if you have the `gnutls` package installed?

**Comment by farzado** [comment]
As you mentioned, flatpak automatically defaults to https for its repository and I changed it to http to see if I can avoid using SSL. 
Installed `gnutls` as you suggested, but still getting the same error message.

**Comment by alexlarsson** [comment]
I think you need to install glib-networking

**Comment by alexlarsson** [comment]
Oh, i see that you already have that. Thats very weird. What http backend does mint build ostree with? Does ostree --version include `libcurl`?

**Comment by mwleeds** [comment]
@farzado what Linux distribution and version are you on? Weird that `glib-networking` wouldn't have a TLS implementation.

**Comment by farzado** [comment]
Couldn't find and run `ostree` seperately, but it is definately installed on my machine as you can see below:  `sudo apt show libostree-1.1`
Package: libostree-1-1
Version: 2017.14-0alexlarsson1~xenial
Priority: optional
Section: libs
Source: ostree
Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Installed-Size: 627 kB
Depends: libarchive13, libc6 (>= 2.14), libglib2.0-0 (>= 2.43.91), libgpg-error0 (>= 1.14), libgpgme11 (>= 1.2.0), liblzma5 (>= 5.1.1alpha+20120614), libmount1 (>= 2.24.2), libselinux1 (>= 2.2), libsoup2.4-1 (>= 2.41.90), libsystemd0, zlib1g (>= 1:1.1.4)

**Comment by mwleeds** [comment]
@farzado the ostree command line tools are probably packaged separately. Anyway I'll assume this isn't reproducible any more since it's been so long
