### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by fgeek** [flatpak/flatpak#1380]
```
Read documentation for the flatpak commandline tools and for the libflatpak library API.
```

http://flatpak.github.io/flatpak/flatpak-docs.html
http://flatpak.github.io/flatpak/reference/html/index.html

**Comment by bronikowski** [comment]
+1, I just came here to learn some details about flatpak and kissed the 404 both times.

**Comment by mwleeds** [comment]
Thanks for pointing this out. I fixed the command line reference link, but the libflatpak docs aren't currently hosted on docs.flatpak.org so it's harder to fix that one. In the mean time if you build flatpak with `./autogen.sh --enable-gtk-doc && make -j4` you'll find the libflatpak docs in `doc/reference/html/`.

**Comment by mwleeds** [comment]
I updated the gh-pages branch so those links lead to updated documentation. It would still be better to have it all on docs.flatpak.org rather than spread out, so I'll close this issue but leave https://github.com/flatpak/flatpak-docs/issues/106 still open.
