### ISSUE TITLE
flatpak-builder: build-args aren't propagated to shell sources

### ISSUE THREAD

**Issue by borring** [flatpak/flatpak#139]
Some sources (neovim) require other dependencies to be pulled in before the configuration and building of the actual app. This requires network connectivity for shell sources.

Here's an example manifest I've been playing with (trying to get working):

```json
{
  "app-id": "io.neovim.Neovim",
  "runtime": "org.freedesktop.Platform",
  "runtime-version": "1.4",
  "sdk": "org.freedesktop.Sdk",
  "command": "nvim",
  "build-options": {
	  "build-args": [
		  "--share=network"
	  ]
  },
  "finish-args": [ 
     "--filesystem=host" 
  ],
  "modules": [
    {
      "name": "neovim",
	  "cmake": true,
      "sources": [
        {
          "type": "git",
          "url": "https://github.com/neovim/neovim.git"
        },
		{
			"type": "shell",
			"commands": [
				"make deps"
			]
		}
      ]
    }
  ]
}
```

**Comment by hadess** [comment]
What's the actual problem? That network is disabled during the build? Or that you can't make it run `make deps` before `make`?

**Comment by borring** [comment]
@hadess with this particular build, `make deps` needs to run before the configure step, otherwise the configure step fails.

**make deps**
* Needs to be the first thing run
* Needs internet access

**Configure (cmake)**
* Requires deps

In order to run a command _before_ the Configure step, we need to use a `shell source` to run shell commands before proceeding with building the module. So naturally, `make deps` would be added as a command to a shell source.

The problem is that enabling network access through `build-args` isn't giving access to the shell command.

**Comment by hadess** [comment]
I think that you shouldn't use the "deps" target of neovim then, and build the dependencies yourself, as needed.

**Comment by matthiasclasen** [comment]
Yes, that is the right advice. We want the build manifest to list everything that goes in the builder, an flatpak-builder should be in control of downloading them.
