### ISSUE TITLE
Can't install Flatpaks in Ubuntu Software

### ISSUE THREAD

**Issue by Ads20000** [flatpak/flatpak#1390]
I know this is an Ubuntu downstream bug and needs to be fixed in Ubuntu, but you can't graphically install Flatpaks from .flatpakref's on Ubuntu 17.10 because of [this bug](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1716409), was wondering if someone from Flatpak wanted to take a look at this and push a fix? This would probably help with Flatpak adoption and I know that developers of other packaging formats are similarly proactive in fixing issues interacting with their formats on various distributions. But I recognize that Flatpak may not have the time to fix this bug and the onus is not really on them, still, I'm filing this in the hope that the bug gets fixed.

I'm afraid I'm not a dev so I can't work out how to fix this bug myself.

**Comment by TingPing** [comment]
I remember @hughsie mentioning perhaps wanting to auto-install missing g-s plugins. Don't know if anything came of that.

**Comment by mwleeds** [comment]
I wonder why Ubuntu can't just inherit the upstream support in g-s for flatpakrefs

**Comment by Ads20000** [comment]
Something broke it. A regular commentator on OMG! Ubuntu! (Sid) has something of a vendetta against Canonical and said he would see if there was a commit that intentionally broke it but I haven't heard anything from him yet!

**Comment by mwleeds** [comment]
Looks like this was resolved
