### ISSUE TITLE
`flatpak install` should automatically install drivers

### ISSUE THREAD

**Issue by jay-15** [flatpak/flatpak#1396]
The other day, I installed `com.valvesoftware.Steam` via `gnome-software` and noticed that some runtimes were installed as well, including some nvidia drivers.
The Steam client worked well, but I could not start any games, so I filed a [bug report](https://github.com/flathub/com.valvesoftware.Steam/issues/61).

As it turned out, gnome-software did not install the required 64bit nvidia drivers, but only the 32bit drivers. After issuing `flatpak update`, the games worked fine. It took some time to figure this out, since the app was "halfway working" and I was quite surprised by this behavior. I guess other newcomers to flatpak are equally confused.

So as @TingPing suggested in the above mentioned bug report, I would like to start the discussion whether flatpak should auto install drivers when installing an app. I think it should.

**Comment by AsciiWolf** [comment]
This was an issue with the runtime extensions not correctly installed. Should be fixed in GNOME Software 3.28.

**Comment by AsciiWolf** [comment]
It looks like that the runtime extensions are unfortunately still [not fully fixed](https://gitlab.gnome.org/GNOME/gnome-software/issues/324). The issue with Nvidia drivers was fixed, but other runtime extensions are still not automatically installed.
