### ISSUE TITLE
Flatpak periodical update notification?

### ISSUE THREAD

**Issue by orschiro** [flatpak/flatpak#1399]
Hi all, 

I am currently running `flatpak update` manually from time to time to check for new updates. 

What I would like to see is Flatpak notifying me about new updates that I can then either install running this terminal command or via a graphical interface. 

ARe there any plans for this for the future?

Currently testing Flatpak on Fedora 27.

Thanks for your time reading this!

**Comment by AsciiWolf** [comment]
I think that the GNOME Software supports this.

**Comment by orschiro** [comment]
> I think that the GNOME Software supports this.

Ah, good to know! Going to check that since I am on Fedora 27 which has GNOME Software.

**Comment by alexlarsson** [comment]
Yeah, the plan for this is that 3rd party graphical tools like gnome-software and kde discover does the auto-update in an integrated way.

**Comment by pgera** [comment]
Tangentially related request: I don't use gnome software, but use standard cli package managers (apt/yum/dnf). Is it possible to integrate flatpak updates with system updates so that something like 'yum update' would show flatpak updates ?

**Comment by orschiro** [comment]
@pgera I am running this script on startup:

```
#/bin/bash

read -p "Press enter to check for updates"
echo "Looking for updates..."
sudo dnf upgrade --assumeyes --refresh --best --allowerasing && flatpak update
notify-send "Updates finished"
$SHELL
```

**Comment by marcelpaulo** [comment]
An alternative for systems that use systemd:

1. Create _~/.config/systemd/user/flatpak-update.timer_:
    ```
    [Unit]
    Description=Flatpak update

    [Timer]
    OnCalendar=7:00
    Persistent=true

    [Install]
    WantedBy=timers.target
    ```

2. Create _~/.config/systemd/user/flatpak-update.service_:
    ```
    [Unit]
    Description=Flatpak update

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/flatpak update -y
    ```

3. Enable and start the timer:
    ```
    systemctl --user enable flatpak-update.timer
    systemctl --user start flatpak-update.timer
    ```

`OnCalendar` can be changed to whatever day/time is most convenient. [systemd-time(7)](http://man7.org/linux/man-pages/man7/systemd.time.7.html) explains the date/time formats.

**Comment by orschiro** [comment]
If I understand correctly, this performs Flatpak updates automatically in
the background?

**Comment by marcelpaulo** [comment]
> this performs Flatpak updates automatically in the background?

Exactly. And all output is logged in the systemd user journal. You can check it running:

`journalctl --user-unit flatpak-update.service`

**Comment by orschiro** [comment]
Wow, impressive. Thanks for sharing this service file! :-)

**Comment by candrapersada** [comment]
how to disable update automatically from mintUpdate?

**Comment by TingPing** [comment]
@candrapersada You are probably better off asking the mint folks that.

**Comment by Francewhoa** [comment]
> I think that the GNOME Software supports this.

Correct

For those not familiar with this. The steps are:

1. If not already done, install GNOME
2. Install the package "[gnome-software-plugin-flatpak](https://packages.debian.org/search?keywords=gnome-software-plugin-flatpak&searchon=names&suite=stable&section=all)". On most Linux, this package is already installed by default.
3. If configured appropriately, GNOME Software will automatically notify you of available Flatpak
