### ISSUE TITLE
An Idea that could END system freezes caused be app ??? ... with hard reboot being the only way out !!!

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1405]
Hi,

Without going deep, isn't the general idea of a flatpak system to run apps out of separate container with their own individual runtime environments ?

Could this architecture/framework be used to literally END the dreadful Operating System Freeze's caused by installed apps we all have grown up to encountering them all our lives ?

What i mean is, as a flatpak app is basically running off an isolated/separate container(its own environment) in a way freeing itself from directly functioning out of a system OS environment in a way legacy / non-flatpak apps have been running, Would it be possible to make 'system OS freeze's needing a hard reboot' a thing of the past ?

Forgive my non-technical plane English language ... but its really annoying to have to hard reboot the whole system OS just because some app decided to turn rogue and sabotage the whole system rendering it useless with a hard reboot the only way out.

Just like how Java took the 'sting' out of jeopardizing the entire system by running out of a Virtual Machine, It would really be great to liberate the OS from the apps and their ability to freeze up the entire system.

Honestly I do not know if flatpak apps too inherit the possibility of freezing up/sabotaging the whole system requiring a hard reboot, like the normal apps do, but given the idea of 'containerizing' apps shouldn't system freeze's be made a thing of the past if the current implementation/architecture of flatpak's isn't doing it already ?

Just an idea i thought i'd put it out in the open ... thinking out loud ... that's all !!!

PS : I know flatpaks aren't really running totally free of a System OS. but the fact that they ARE indirectly running out of it could be 'that opportunity' to explore the possibility of ending apps triggered system freeze's requiring a hard reboot !!!

**Comment by trialism** [comment]
> Just like how Java took the 'sting' out of jeopardizing the entire system by running out of a Virtual Machine

Java apps can cause system freeze.

> Could this architecture/framework be used to literally END the dreadful Operating System Freeze's caused by installed apps we all have grown up to encountering them all our lives ?

No. And if you've such problems then check your 1) drivers 2) desktop environment 3) compositor. I don't remember when was the last time I needed a hard reboot with manjaro+xfce+nvidia.

**Comment by alexlarsson** [comment]
System hangs are generally hardware issues or lowlevel host bugs. Using flatpak or not does not really affect this in one way or another.
