### ISSUE TITLE
develop using flatpak

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#1412]
How is it possible if using flatpak instead of native packages to develop apps?
For example if I need gnome-devel / org.gnome.SDK or plasma-devel /org.kde.SDK headers how do i use them?

**Comment by trialism** [comment]
See [flatpak-builder](http://docs.flatpak.org/en/latest/flatpak-builder.html).

**Comment by damianatorrpm** [comment]
I don't understand how flatpak-builder relates to that.

Example:
I installed org.kde.SDK and I wan to develop using headers contained in that.
How does flatpak-builder help?

**Comment by julianrichen** [comment]
You either use `flatpak-builder` directly via the cli or create a manifest file with the same cli arguments to build the application from the existing build system. So create your `newprogram.cpp`, then create either a Makefile, Meson, Autotools, etc.. build script, and then use `flatpak-builder` to do the bundling like RPM, Deb, etc.. flatpak is normally smart enough to check the directory contents and pick the right plugin to build using meson, autotools, makefile, etc..

```bash
mkdir -p /home/username/Projects/newprogram
touch /home/username/Projects/newprogram/newprogram.cpp // Your program
touch /home/username/Projects/newprogram/makefile // Your makefile/meson/autotools/etc file
touch /home/username/Projects/newprogram/com.github.damianatorrpm.newprogram.json //flatpak manifest
```

Manifest (`com.github.damianatorrpm.newprogram.json`):
```json
{
    "app-id": "com.github.damianatorrpm.newprogram",
    
    "runtime": "org.kde.Platform",
    "runtime-version": "5.10",
    
    "sdk": "org.kde.Sdk",
    
    "command": "newprogram",
    
    "finish-args": [
        "--socket=x11",
        "--socket=wayland"
    ],
    
    "modules": [
        {
            "name": "newprogram",
            "sources": [
                {
                    "type": "git",
                    "url": "file:///home/username/Projects/newprogram"
                }
            ]
        }
    ]
}
```

Also above I assumed you are using git to manage the project, hence the `git` type. More rtypes: http://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#idm140696437865536

build
```bash
# Add flathub repo to get KDE platform & sdk (you could also use the kde repo like you mentioned above)
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install
flatpak install flathub org.kde.Platform//5.10
flatpak install flathub org.kde.Sdk//5.10

# Move to your projects dir
cd /home/username/newprogram

# Build using flatpak manifest file
flatpak-builder --force-clean --repo=newprogram-repo newprogram-app com.github.damianatorrpm.newprogram.json

# Add new repo which contains app as an install-able location
flatpak --user remote-add --no-gpg-verify --if-not-exists newprogram-app newprogram-repo

# Install your app from your new local repo
flatpak --user install newprogram-app com.github.damianatorrpm.newprogram

# Run
flatpak run com.github.damianatorrpm.newprogram

# Update when you make changes
## Rebuild the app based on changes
flatpak-builder --force-clean --repo=newprogram-repo newprogram-app com.github.damianatorrpm.newprogram.json
## Update locally
flatpak update com.github.damianatorrpm.newprogram
```

If you use an IDE like `gnome-builder` it can automate some of this.

flatpak resources: http://docs.flatpak.org/en/latest/command-reference.html

If someone could provide a better compressed version of what I wrote it might be more helpful.

**Comment by trialism** [comment]
@damianatorrpm everything is in that documentation. It explains how to create manifests to build stuff. Read it.

**Comment by damianatorrpm** [comment]
@trialism @julianrichen Thanks for your answers, I am not sure it is what I mean.

Yes above commands work because the flatpak binary support ostree format.
So developers who use qt-creator or different IDE, everytime they want to try out a change in the program they are developing (developers) you have to rerun?:
```
# Move to your projects dir

cd /home/username/newprogram

# Build using flatpak manifest file
flatpak-builder --force-clean --repo=newprogram-repo newprogram-app com.github.damianatorrpm.newprogram.json

# Add new repo which contains app as an install-able location
flatpak --user remote-add --no-gpg-verify --if-not-exists newprogram-app newprogram-repo

# Install your app from your new local repo
flatpak --user install newprogram-app com.github.damianatorrpm.newprogram

# Run
flatpak run com.github.damianatorrpm.newprogram

# Update when you make changes
## Rebuild the app based on changes
flatpak-builder --force-clean --repo=newprogram-repo newprogram-app com.github.damianatorrpm.newprogram.json
## Update locally
flatpak update com.github.damianatorrpm.newprogram


```

**Comment by julianrichen** [comment]
No, running
```
flatpak-builder --force-clean --repo=newprogram-repo newprogram-app com.github.damianatorrpm.newprogram.json
```

Will update the the app and push changes to `newprogram-repo` & `newprogram-app`.

Then you need to run:
```bash
flatpak update com.github.damianatorrpm.newprogram
```

To update it when you want to rerun it. All that stuff above those commands is setting-up the repo for the first time. The above basically create the equivalent of a flathub, gnome, or kde repo but locally on your machine. You then download updates from that local repo. If Qt has an IDE that can integrate flatpak-builder then I would recommend using it so you don't have to run all the commands manually.

**Comment by damianatorrpm** [comment]
https://lists.freedesktop.org/archives/flatpak/2016-April/000194.html

**Comment by alexlarsson** [comment]
It is possible to use flatpak as a development environment. For example, the pitivi developers do this: http://developer.pitivi.org/HACKING.html

That said, this is not really the focus of flatpak-builder. Its more for building releases.

**Comment by damianatorrpm** [comment]
Thanks @alexlarsson for the link. That is the directio I was looking for.
