### ISSUE TITLE
[FIXED] Cannot install monoDevelop (error 504)

### ISSUE THREAD

**Issue by AmeNoTsuke** [flatpak/flatpak#1419]
Hi,
I've just installed OpenSUSE on my laptop. And I need to develop with C#. So I tried to install monodevelop with the instructions on their site. But I always get this error : 

`error: While pulling app/com.xamarin.MonoDevelop/x86_64/stable from remote com.xamarin.MonoDevelop-4-origin: Server returned status 504: Gateway Timeout`

I really don't understand where is the problem.

Thanks for your help&time !

**Comment by monyarm** [comment]
"[FIXED]", well that's great, but how ? Cause i'm having the same issue

**Comment by TingPing** [comment]
It is probably just a flaky host.
