### ISSUE TITLE
GPG error on runtime/sdk installation

### ISSUE THREAD

**Issue by comzeradd** [flatpak/flatpak#142]
Following the instructions on the developers page I'm trying to install the runtime and SDK but I get a gpg-verification error on both.

```
$ flatpak install gnome org.gnome.Platform 3.20
error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
```

**Comment by alexlarsson** [comment]
Can you try again? I was doing some work on the repo.

**Comment by comzeradd** [comment]
That was quick :+1: Everything works great again. Thanks.
