### ISSUE TITLE
Qt Apps Do Not Use qgnomeplatform on GNOME

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#1420]
Qt apps installed through flatpak do not seem to be using the qgnomeplatform plugin on GNOME. The windows seem to be using the default QT5 theme and _some_ of the gnome icons. Here's a picture of a non-Flatpak Qt window and a flatpak Qt window side-by-side.
![captura de pantalla de 2018-02-14 21-47-16](https://user-images.githubusercontent.com/4712288/36224591-c4e6d0d0-11d0-11e8-93d8-ca233319c485.png)

**Comment by TingPing** [comment]
You have to install them, these will be documented soon but here is the instructions for them: https://github.com/flatpak/flatpak-docs/pull/61/files?short_path=506bc60#diff-506bc6031b03094198b35dd41fa1d8c2

**Comment by Saroufim** [comment]
Now that I've installed qgnomeplatform from kdeapps, the theming issue is solved. However, the default gnome icons for the downloads, documents, desktop, photos, and music folders are still there while the rest of the folders use KDE's breeze icon set.

**Comment by TingPing** [comment]
I would guess those icon names simply are not provided elsewhere?

**Comment by Saroufim** [comment]
Could this be a translation issue because my system is in Spanish?

**Comment by TingPing** [comment]
I doubt that.

**Comment by TingPing** [comment]
@RokeJulianLockhart It already does by default: https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/qt5.15lts-23.08/org.kde.Sdk.json.in?ref_type=heads#L54
