### ISSUE TITLE
Using flatpak version of Meld as an external git diff tool fails

### ISSUE THREAD

**Issue by digitalstreamio** [flatpak/flatpak#1423]
I have a setup where git external diff command is pointed to:

```
#!/bin/bash
flatpak run org.gnome.meld "$2" "$5" > /dev/null 2>&1
```

However, sandboxed Meld (org.gnome.meld from flathub)  fails to display diff as it cannot access temporary files created by git in /tmp/ directory.

Is there a way to map /tmp directory of host into the application sandbox?

**Comment by TingPing** [comment]
Passing files from the CLI is really ugly but ideally you do:

`flatpak run --file-forwarding org.gnome.meld @@ "$2" @@ @@ "$5" @@` or such

**Comment by digitalstreamio** [comment]
Nice, that worked great. I can see why the syntax is a bit out there but I'll take it. Is this in general how all files are handled when passed through CLI?

**Comment by alexlarsson** [comment]
You can also flatpak override --filesystem=/tmp org.gnome.meld

**Comment by digitalstreamio** [comment]
I see, thanks for the suggestion. I think I am starting to get a feel for it now. Cheers!

**Comment by fbruetting** [comment]
> Passing files from the CLI is really ugly but ideally you do:
> 
> `flatpak run --file-forwarding org.gnome.meld @@ "$2" @@ @@ "$5" @@` or such

I now ran into the same problem, I tried that code which helped getting Meld to start at all. But it always shows me the same folder contents (instead of different versions and instead of the specified file).

My `.gitconfig`:
```
[diff]
	tool = meld_flatpak

[difftool "meld_flatpak"]
	cmd	= flatpak run --file-forwarding org.gnome.meld @@ \"$2\" @@ @@ \"$5\" @@
```

Any ideas?

**Comment by dpward** [comment]
The `--file-forwarding` option does not work with `git difftool --dir-diff`. However the [other suggestion](#issuecomment-366247280) to use `--filesystem=/tmp` does.

These could be combined into an uglier approach...
```ini
[diff]
	tool = meld_flatpak

[difftool "meld_flatpak"]
        cmd = flatpak run \"--filesystem=$(realpath \"$LOCAL\")\" \"--filesystem=$(realpath \"$REMOTE\")\" org.gnome.meld \"$LOCAL\" \"$REMOTE\"
```

See also: flathub/org.gnome.meld#11
