### ISSUE TITLE
Improve error message for invalid architectures

### ISSUE THREAD

**Issue by joaquimrocha** [flatpak/flatpak#1424]
I think `flatpak build-init` use is not matching its docs because it can never find the installed runtimes unless used with the full name/arch/branch.

e.g.:
```
flatpak build-init testdir com.mytest.App org.freedesktop.Platform org.freedesktop.Sdk 1.6 --arch=x86_86
error: org.freedesktop.Platform 1.6 not installed
```

However, I have 
```
$ flatpak list -d --runtime|grep freedesktop|grep 1\.6
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 flathub                       5962b0bb8996  -               7.8 MB       system        
org.freedesktop.Platform.ffmpeg/x86_64/1.6      flathub                       1d3a797ec2c5  -               6.4 MB       system        
org.freedesktop.Platform/x86_64/1.6             gnome                         0c28fcbcb9f1  -             567.0 MB       system        
org.freedesktop.Sdk/x86_64/1.6                  flathub                       53b19d73d952  -               1.3 GB       system 
```
and this works:

`flatpak build-init testdir com.mytest.App org.freedesktop.Platform/x86_64/1.6 org.freedesktop.Sdk/x86_64/1.6 1.6 --arch=x86_86`

at least from the help output, I believe it should work with the first command and I have some scripts running it like that too:
```
Usage:
  flatpak build-init [OPTION…] DIRECTORY APPNAME SDK RUNTIME [BRANCH] - Initialize a directory for building
```

**Comment by joaquimrocha** [comment]
Update: this was tested with 0.10.2.1 on Fedora

**Comment by matthiasclasen** [comment]
What is the first command ? I only see one specified invokation of flatpak build-init

**Comment by mwleeds** [comment]
@joaquimrocha looks like there's a typo in your achitecture value

**Comment by joaquimrocha** [comment]
@mwleeds Oh! And apparently that's exactly the problem!

Still, it should return a better error message, like including the architecture and not only the runtime and branch. Or, even better, mention that the architecture doesn't match the ones it validates (I think there's a list of those internally).

**Comment by pwithnall** [comment]
Prospective fix in https://github.com/flatpak/flatpak/pull/1462.
