### ISSUE TITLE
[CLI] "remote-ls" fails when there are Flatpaks without configured remotes

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#1427]
i want to check for updates
```
flatpak remote-ls --updates
```
**Output:**
```
error: Can't fetch summary from disabled remote ‘org.gabmus.hydrapaper-origin’
```
that happens because i installed `org.gabmus.hydrapaper` from a Flatpak bundle, that had not remotes configured, and that issue happens for every such app i have

**Expected Behavior:**
Flatpak CLI should ignore those flatpakApps and continue with listing the updates. `flatpak update` works as expected

**Flatpak version:** 0.11.1

**Comment by GabMus** [comment]
Same thing here. Wow I'm causing a lot of problems :grin:
