### ISSUE TITLE
waf fails in `flatpak build` environment

### ISSUE THREAD

**Issue by borring** [flatpak/flatpak#143]
All you need is a project source that uses waf. No need for manifests because
the package fails to even configure.
- build-init a package  
  `flatpak build-init mpv-flatpak io.mpv.Mpv org.gnome.Sdk org.gnome.Platform 3.20`
- Clone a project (mpv)  
  `git clone https://github.com/mpv-player/mpv.git && cd mpv`
- Run `./bootstrap.py` to download the waf script
- Run ./waf configure through flatpak build  
  `flatpak build ../mpv-flatpak ./waf configure`
  
  The script fails, meanwhile, running `./waf configure` outside of flatpak works

**Comment by alexlarsson** [comment]
I tried this, and it first fails with:
```
Checking for SSA/ASS support                                              : no ('libass >= 0.12.1' not found) 
Unable to find development files for libass, or the version found is too old. Aborting. If you really mean to compile without libass support use --disable-libass.
```
Then with --disable-libass:
```
Checking for libav/ffmpeg                                                 : no ('libavutil >= 54.02.0 libavcodec >= 56.1.0 libavformat >= 56.01.0 libswscale >= 2.1.3' not found) 
Unable to find development files for some of the required FFmpeg/Libav libraries. You need at least FFmpeg 2.4 or Libav 11. Aborting.
```

This seems right (in that ffmpeg is not in the runtime). What different behaviour are you seeing?

**Comment by borring** [comment]
I see no output at all. The script crashes and my system attempts to do a coredump (but fails for some reason)

Using pdb, it shows the script failing at line 164  
```python
from waflib import Scripting
```

**Comment by alexlarsson** [comment]
That is weird. What distro are you on and what flatpak packages do you use?

**Comment by alexlarsson** [comment]
Can you try something like:
```
flatpak build ../mpv-flatpak strace -o log -f ./waf configure
```
and attach the log?

**Comment by borring** [comment]
Fedora 24 (also happened in F23)
```
❯ flatpak --version
Flatpak 0.6.4
```
[log.txt](https://github.com/flatpak/flatpak/files/328878/log.txt)

**Comment by borring** [comment]
Here's a strace of it running normally outside of flatpak-build

[log2.txt](https://github.com/flatpak/flatpak/files/328890/log2.txt)

It goes further, but eventually fails (because of the libass dependency)

**Comment by borring** [comment]
Found this in the journal

```
Jun 23 03:35:01 navi-laptop audit[5793]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=5793 comm="python" exe="/usr/bin/python2.7" sig=4
Jun 23 03:35:01 navi-laptop kernel: traps: python[5793] trap invalid opcode ip:7f6156e10b26 sp:7fff8256f4c0 error:0 in strop.so[7f6156e0f000+6000]
```

**Comment by alexlarsson** [comment]
Yeah, so python is tripping over an illegal instruction. Wth?
Can you try running waf under valgrind?

**Comment by borring** [comment]
huh... it ran successfully in valgrind.
`flatpak build ../mpv-flatpak valgrind python ./waf configure`
[valgrind-log.txt](https://github.com/flatpak/flatpak/files/330200/valgrind-log.txt)


I did `flatpak build ../mpv-flatpak python ./waf configure` just in case it was because the invocation was different. It didn't work.

**Comment by alexlarsson** [comment]
Something deep inside python makes a double free, and i guess after that all bets are off. Pretty strange.

**Comment by alexlarsson** [comment]
actually i can repoduce the valgrind warnings by just doing:
```
flatpak build ../mpv-flatpak valgrind python -c "print 42"
```

**Comment by alexlarsson** [comment]
Seems like this is valgrind being confused about python:
  http://svn.python.org/projects/python/branches/release24-maint/Misc/README.valgrind

However, we still have two people who get the illegal instruction when running some python2 code. I have no idea what is causing that.

**Comment by hadess** [comment]
FWIW, it works fine on my computer. Otherwise I wouldn't have been able to build that bundle...

**Comment by matthiasclasen** [comment]
Googling around finds some hits for "sigill python", e.g. https://bugzilla.redhat.com/show_bug.cgi?id=896723

**Comment by cfoch** [comment]
I was trying on a Pitivi sandbox. There is something related to
/usr/lib/python2.7/lib-dynload/strop.so
I get a "core dumped" error when I do "import parse", "import pip" or "import textwrap" on a Python2.7 console.
Result of executing "gdb python2.7 -v -m textwrap":
https://paste.fedoraproject.org/388643/46789904/

Result of executing "coredumpctl gdb":
https://paste.fedoraproject.org/388641/14678986/

I use Arch

**Comment by hadess** [comment]
> Result of executing "gdb python2.7 -v -m textwrap":
> https://paste.fedoraproject.org/388643/46789904/

That should be gdb *--args* python2.7 -v -m textwrap
Otherwise you run into the error you saw, gdb doesn't have a "-m" option

> Result of executing "coredumpctl gdb":
> https://paste.fedoraproject.org/388641/14678986/

You need to run bt

**Comment by cfoch** [comment]
gdb --args python2.7 -v -m textwrap
https://paste.fedoraproject.org/389338/09083414/

**Comment by hadess** [comment]
Now you just need to capture the same thing with `org.freedesktop.Sdk.Debug` installed :)

**Comment by borring** [comment]
It seems just python2 is broken. Waf works when I run it with `python3 ./waf configure`

Running it with python2 (2.7.11) also works if I install it as a module and run it with `python2 ./waf configure`

Can a fix be pushed into the runtimes?

**Comment by fenryxo** [comment]
In my case, python2 gets SIGILL when building WebKitGTK. It happens on my desktop but not on my laptop though.

`traps: python2.7[25103] trap invalid opcode ip:7f43ae03db26 sp:7ffd242ac660 error:0 in strop.so[7f43ae03c000+6000]`

My workaround is

```
"build-options" : {
   "env": {
      "PYTHONHOME": "/app"
    }
},
...
"sources": [
  {
    "type": "shell",
    "commands": [
        "mkdir -p /app/lib /app/bin",
        "cp -a /usr/lib/python2.7 /app/lib/python2.7",
        "cp -af /usr/bin/python /usr/bin/python2* /usr/bin/python-* /app/bin",
        "rm /app/lib/python2.7/lib-dynload/strop.so"
      ]
  },
...
```

**Comment by Jehan** [comment]
For anyone interested, my own workaround to build GIMP itself where `gdbus-codegen` was crashing with python2. Yet could not set PYTHON to python3 because it was interfering with python2 as a dependency.

So on the GIMP module only, I set

>  "build-options" : {
>                "env": {
>                    "PATH": "/run/build/gimp/tmp-bin:/app/bin:/usr/bin"
>                }
>            },

And added as a source, after the main source:

>  {
>    "type": "script",
>    "commands": [   
>      "#!/bin/sh",
>      "python3 /usr/bin/gdbus-codegen $@"
>    ],
>    "dest-filename": "gdbus-codegen",
>    "dest": "tmp-bin/"
>  }

This way I wrapped around the gdbus-codegen provided in the runtime to force it to use python3.

**Comment by Jehan** [comment]
Also here is a backtrace when running `python2 /usr/bin/gdbus-codegen` in gdb inside flatpak environment:

```
#0  0x00007fe3bd30ab26 in ?? () from /usr/lib/python2.7/lib-dynload/strop.so
#1  0x00007fe3beb78b1f in PyEval_EvalFrameEx () from /lib/libpython2.7.so.1.0
#2  0x00007fe3beb7994c in PyEval_EvalCodeEx () from /lib/libpython2.7.so.1.0
#3  0x00007fe3beb77e70 in PyEval_EvalFrameEx () from /lib/libpython2.7.so.1.0
#4  0x00007fe3beb7994c in PyEval_EvalCodeEx () from /lib/libpython2.7.so.1.0
#5  0x00007fe3beb79a99 in PyEval_EvalCode () from /lib/libpython2.7.so.1.0
#6  0x00007fe3beb898dc in PyImport_ExecCodeModuleEx () from /lib/libpython2.7.so.1.0
#7  0x00007fe3beb89b4a in ?? () from /lib/libpython2.7.so.1.0
#8  0x00007fe3beb8a758 in ?? () from /lib/libpython2.7.so.1.0
#9  0x00007fe3beb8a9ef in ?? () from /lib/libpython2.7.so.1.0
#10 0x00007fe3beb8b2fd in PyImport_ImportModuleLevel () from /lib/libpython2.7.so.1.0
#11 0x00007fe3beb715d8 in ?? () from /lib/libpython2.7.so.1.0
#12 0x00007fe3beaddbf3 in PyObject_Call () from /lib/libpython2.7.so.1.0
#13 0x00007fe3beb731b7 in PyEval_CallObjectWithKeywords () from /lib/libpython2.7.so.1.0
#14 0x00007fe3beb74bfb in PyEval_EvalFrameEx () from /lib/libpython2.7.so.1.0
#15 0x00007fe3beb7994c in PyEval_EvalCodeEx () from /lib/libpython2.7.so.1.0
#16 0x00007fe3beb79a99 in PyEval_EvalCode () from /lib/libpython2.7.so.1.0
#17 0x00007fe3beb898dc in PyImport_ExecCodeModuleEx () from /lib/libpython2.7.so.1.0
#18 0x00007fe3beb89b4a in ?? () from /lib/libpython2.7.so.1.0
#19 0x00007fe3beb8a758 in ?? () from /lib/libpython2.7.so.1.0
#20 0x00007fe3beb8aa86 in ?? () from /lib/libpython2.7.so.1.0
#21 0x00007fe3beb8b2fd in PyImport_ImportModuleLevel () from /lib/libpython2.7.so.1.0
#22 0x00007fe3beb715d8 in ?? () from /lib/libpython2.7.so.1.0
#23 0x00007fe3beaddbf3 in PyObject_Call () from /lib/libpython2.7.so.1.0
#24 0x00007fe3beb731b7 in PyEval_CallObjectWithKeywords () from /lib/libpython2.7.so.1.0
#25 0x00007fe3beb74bfb in PyEval_EvalFrameEx () from /lib/libpython2.7.so.1.0
#26 0x00007fe3beb7994c in PyEval_EvalCodeEx () from /lib/libpython2.7.so.1.0
#27 0x00007fe3beb79a99 in PyEval_EvalCode () from /lib/libpython2.7.so.1.0
#28 0x00007fe3beb898dc in PyImport_ExecCodeModuleEx () from /lib/libpython2.7.so.1.0
#29 0x00007fe3beb89b4a in ?? () from /lib/libpython2.7.so.1.0
#30 0x00007fe3beb8a758 in ?? () from /lib/libpython2.7.so.1.0
#31 0x00007fe3beb8ac89 in ?? () from /lib/libpython2.7.so.1.0
#32 0x00007fe3beb8b40a in PyImport_ImportModuleLevel () from /lib/libpython2.7.so.1.0
#33 0x00007fe3beb715d8 in ?? () from /lib/libpython2.7.so.1.0
#34 0x00007fe3beaddbf3 in PyObject_Call () from /lib/libpython2.7.so.1.0
#35 0x00007fe3beb731b7 in PyEval_CallObjectWithKeywords () from /lib/libpython2.7.so.1.0
#36 0x00007fe3beb74bfb in PyEval_EvalFrameEx () from /lib/libpython2.7.so.1.0
#37 0x00007fe3beb7994c in PyEval_EvalCodeEx () from /lib/libpython2.7.so.1.0
#38 0x00007fe3beb79a99 in PyEval_EvalCode () from /lib/libpython2.7.so.1.0
#39 0x00007fe3beb930ef in ?? () from /lib/libpython2.7.so.1.0
#40 0x00007fe3beb941f2 in PyRun_FileExFlags () from /lib/libpython2.7.so.1.0
#41 0x00007fe3beb952f7 in PyRun_SimpleFileExFlags () from /lib/libpython2.7.so.1.0
#42 0x00007fe3beba47fe in Py_Main () from /lib/libpython2.7.so.1.0
#43 0x00007fe3be70f690 in __libc_start_main (main=0x4006d0 <main>, argc=2, argv=0x7ffce2ba7138, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffce2ba7128) at libc-start.c:289
#44 0x0000000000400709 in _start ()
```

It is funny to notice that the workaround by @fenryxo is basically deleting the `strop.so` dynamic module (except that since /usr/ is read-only, you cp it all to /app). The crash indeed happens in this module. So does that mean that strop.so is actually totally useless but it makes python2 crash?
According to what I find, this is a low-level module (with C implementation) which is used by the `string` module so it is totally weird if by just deleting it, everything is OK. Also why does the exact same binary works well on some machines, not on others?

**Comment by hadess** [comment]
It's a SIGILL, which means that this Python code contains an instruction that can't be run on your CPU, say an SSE or MMX extension that's not available.

**Comment by Jehan** [comment]
Oh I see. Well then I guess the fix is quite easy: build all runtime dependencies as generically as possible!

**Comment by alexlarsson** [comment]
We're not adding any special arch flags for python though. It should be a regular i386 build.

It would be interesting to get some exact data on exactly what CPUs it crashes on, and which it doesn't.

**Comment by alexlarsson** [comment]
Oh, actually we might have an issue here, because this sounds related:
http://lists.openembedded.org/pipermail/openembedded-core/2014-January/088962.html

**Comment by alexlarsson** [comment]
So, it seems like the default x86-64 tuning in yocto is for core2, which gives:

  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse

I guess some old CPUs doesn't like that.

**Comment by Jehan** [comment]
Ok you seem to have pushed a fix, but just in case you still wanted CPU info, here is the one for the computer where it crashes, which is indeed a very old computer which I use as a server for building stuff. SSE3 flag for instance would likely be a problem indeed.

> $ less /proc/cpuinfo
> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 15
> model           : 4
> model name      : Intel(R) Pentium(R) 4 CPU 3.06GHz
> stepping        : 9
> microcode       : 0x3
> cpu MHz         : 3059.257
> cache size      : 1024 KB
> physical id     : 0
> siblings        : 2
> core id         : 0
> cpu cores       : 1
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 5
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc pebs bts nopl pni dtes64 monitor ds_cpl tm2 cid cx16 xtpr lahf_lm
> bugs            :
> bogomips        : 6118.51
> clflush size    : 64
> cache_alignment : 128
> address sizes   : 36 bits physical, 48 bits virtual
> power management:
> 
> processor       : 1
> […]

**Comment by cfoch** [comment]
I forgot to mention that deleting the strop.so file fixed my bug.

**Comment by alexlarsson** [comment]
When i have a working build of the new flags i'd like someone who can reproduce this to test the fix.

**Comment by alexlarsson** [comment]
Some discussion on adding more generic "per-arch" stuff in https://github.com/flatpak/flatpak/pull/468

**Comment by alexlarsson** [comment]
oh, wrong issue for the last comment

**Comment by alexlarsson** [comment]
Ok, I need someone to test the new build, something like:

```
flatpak remote-add gnome-buildbot http://sdkbuilder1.gnome.org/gnome-buildbot.flatpakrepo
flatpak uninstall org.gnome.Sdk//3.22
flatpak install gnome-buildbot org.gnome.Sdk//3.22
```

**Comment by Jehan** [comment]
I will test later tonight.

**Comment by Jehan** [comment]
It works!
I just ran gdbus-codegen with python2 and it worked (no illegal instruction). I did not try to run a full build, but since that was the script python2 was breaking on previously, it looks fixed!

**Comment by alexlarsson** [comment]
Thanks!

**Comment by fenryxo** [comment]
WebKitGTK build also works.

**Comment by alexlarsson** [comment]
Should work on sdk.gnome.org now
