### ISSUE TITLE
Build failure with P2P enabled

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#1431]
Master with FLATPAK_ENABLE_P2P fails to build with:

```
../common/flatpak-dir.c: In function ‘flatpak_dir_find_latest_rev’:
../common/flatpak-dir.c:2031:11: error: ‘checksum_or_latest’ undeclared (first use in this function)
       if (checksum_or_latest != NULL)
           ^
../common/flatpak-dir.c:2031:11: note: each undeclared identifier is reported only once for each function it appears in
```

I didn't follow this closely, whats the right thing here @pwithnall @mwleeds ?

**Comment by pwithnall** [comment]
This was PR #1314 and, looking back at the code, I’m not sure how it built and passed the pre-merge tests. `checksum_or_latest` is not defined in that scope, and it doesn’t look like it was defined at the time that PR was merged.

@mwleeds, what’s going on here? Does `flatpak_dir_find_latest_rev()` need to be passed a `checksum_or_latest` argument by its caller?

**Comment by alexlarsson** [comment]
I think the tests passed because they are not built with P2P

**Comment by ebassi** [comment]
JFYI I had to disable P2P support in Continuous, to avoid this issue blocking the build.

**Comment by mwleeds** [comment]
Oops. It looks like when I rebased it to master git quietly applied the patch in the wrong place. See the unrebased version here: https://github.com/mwleeds/flatpak/tree/mwleeds/downgrade-collection-ids-unrebased
