### ISSUE TITLE
How to uninstall a flatpak removing all its settings?

### ISSUE THREAD

**Issue by glaubersm** [flatpak/flatpak#1434]
Hi
I cant open VLC anymore after change a setting in its preferences.
Uninstall and reinstall VLC did not solve the problem.
Therefore I need uninstall VLC removing all its settings.

I use Arch Linux, flatpak 0.10.4.

**Comment by TingPing** [comment]
`rm -r ~/.var/app/org.videolan.VLC`

**Comment by glaubersm** [comment]
Thank you, TingPing. Solved.
So currently there is no method to uninstall flatpaks also removing its settings?

**Comment by TingPing** [comment]
There is not and atm there cannot reliably be since some apps store settings outside of that directory (via DConf for example)

**Comment by Mailaender** [comment]
It would help workaround https://github.com/flathub/org.eclipse.Java/issues/12#issuecomment-2708226012 if there was a way to purge the settings on each update.
