### ISSUE TITLE
Android Studio flatpak version not listing all root folders ...

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1437]
Hi,

I recently installed Android Studio from here

flatpak install --from https://flathub.org/repo/appstream/com.google.AndroidStudio.flatpakref

surprisingly when i have to point Android Studio to my Android SDK partition which by default mounts at '`/media`' ... i am unable to locate `/media`, the folder tree is different when accessed from the flatpak version of Android Studio.

![androidstudiosdk detection failure](https://user-images.githubusercontent.com/3283676/36441266-1d673c06-1698-11e8-8c55-e57d1dfd54fb.png)

only the following folders show up ...
```
/app
/bin
/dev
/etc
/home
/lib
/lib64
/proc
/run
/sbin
/sys
/tmp
/usr
/var

```

the non-flatpak Android Studio however shows all the folders (as below) ...
```
/bin
/boot
/dev
/etc
/home
/lastore
/lib
/lib64
/lost+found
/media
/mnt
/opt
/proc
/recovery
/root
/run
/sbin
/srv
/sys
/tmp
/usr
/var

```
I don't know if this is a Android Studio(flatpak version)  problem or a flatpak package problem.

**Comment by TingPing** [comment]
`flatpak override --user --filesystem=host com.google.AndroidStudio` will do it.

**Comment by aiamuzz** [comment]
@TingPing ...

thanks that did the trick ...
and i'll follow it up with the specific repo ...
