### ISSUE TITLE
ssh-agent socket

### ISSUE THREAD

**Issue by ptomato** [flatpak/flatpak#1438]
A `--socket=ssh-agent` permission would be nice. My use case is building docs inside a sandbox with flatpak-builder and deploying them by pushing to the `gh-pages` branch of my repository on GitHub.

With the following options to `flatpak run` I can get GitHub to recognize my SSH key, so I assume it would just be a question of passing the appropriate args to bwrap:
```
flatpak run --command=bash --share=network --filesystem=$SSH_AUTH_SOCK --env=SSH_AUTH_SOCK=$SSH_AUTH_SOCK org.gnome.Sdk//3.26
```

**Comment by Lctrs** [comment]
Now that https://github.com/flatpak/flatpak/pull/1764 has been merged, I think this can be closed.

**Comment by antenore** [comment]
@Lctrs how does it works? 

Should I simply add this?

```--socket=ssh-auth```

Thanks!

**Comment by Lctrs** [comment]
It hasn't been released yet so it won't work. But once it's the case, you'll just have to do what you said.
