### ISSUE TITLE
Packages without a version number should be rejected

### ISSUE THREAD

**Issue by realnc** [flatpak/flatpak#1441]
This is my experience with flatpak right now:

```
$ flatpak search libreoffice
Application ID              Version Branch Remotes Description                       
org.libreoffice.LibreOffice         stable flathub The LibreOffice productivity suite
$ flatpak search retroarch
Application ID         Version Branch Remotes Description                                            
org.libretro.RetroArch         stable flathub Frontend for emulators, game engines and media players.
```

No version numbers. I would like to know what the version of the package I'm installing is. Is it newer than the one from my distro? Older? Ancient?

I'd like to suggest that flatpak should not allow building packages that do not specify a version number.

**Comment by TingPing** [comment]
This is more of a comment for flathub and it has been added as a requirement: https://github.com/flathub/flathub/wiki/App-Requirements#appstream

A few applications simply pre-date that requirement. Feel free to open bugs on their repositories here: https://github.com/flathub/

**Comment by realnc** [comment]
I don't see how that helps, but OK. Having flatpak outright reject versionless packages is the no-brainer solution.

What you're suggesting is not a solution.

**Comment by TingPing** [comment]
The `flatpak` tool doesn't require appstream data. Flathub really is the correct place to solve this and making it error *there* is a reasonable request.
