### ISSUE TITLE
remote-ls fails with 'invalid refspec'

### ISSUE THREAD

**Issue by fooishbar** [flatpak/flatpak#1444]
Running Flatpak 0.10.3-1.fc27, from F27 latest updates as of Feb 22nd.

I tried to run `flatpak update`, which after a seemingly-interminable amount of time complained about two of my remotes. I tried to run `flatpak remote-ls` to see if I could disable those remotes to do what I originally wanted to do (update Builder), but that failed too:

```
strictly:~% flatpak update   
Looking for updates...
Warning: Can't find dependencies: [28] Timeout was reached
Warning: Problem looking for related refs: [28] Timeout was reached
Warning: Can't find dependencies: No entry for app/org.mozilla.FirefoxNightlyWayland/x86_64/master in remote summary flatpak cache 
Warning: Can't find dependencies: [28] Timeout was reached
Warning: Problem looking for related refs: [28] Timeout was reached
Warning: Can't find dependencies: No entry for runtime/org.mozilla.FirefoxNightlyWayland.Locale/x86_64/master in remote summary flatpak cache 
Error updating remote metadata for 'nightly-graphics': [28] Timeout was reached
Error: Failed to update org.inkscape.InkscapeDevel/x86_64/master: [28] Timeout was reached
Error: Failed to update org.mozilla.FirefoxNightlyWayland/x86_64/master: No such ref 'app/org.mozilla.FirefoxNightlyWayland/x86_64/master' in remote org.mozilla.FirefoxNightlyWayland-origin
Error: Failed to update org.inkscape.InkscapeDevel.Locale/x86_64/master: [28] Timeout was reached
Error: Failed to update org.mozilla.FirefoxNightlyWayland.Locale/x86_64/master: No such ref 'runtime/org.mozilla.FirefoxNightlyWayland.Locale/x86_64/master' in remote org.mozilla.FirefoxNightlyWayland-origin
error: One or more operations failed
zsh: exit 1     flatpak update
strictly:~% flatpak remote-ls
[NB: a lot of time elapsed here, so I gave up and killed it]
^C
zsh: interrupt  flatpak remote-ls
strictly:~% sudo flatpak remote-ls
error: Invalid refspec org.gnome.Builder-origin:.
zsh: exit 1     sudo flatpak remote-ls
```

It seems to me like `remote-ls` shouldn't fail, even if one of the remotes is invalid. This seems to be a change in behaviour as well: this certainly _used_ to work. I guess an update at some point made Flatpak more strict in what it accepted, and now my configuration is invalid?

I'm tempted to just obliterate all my system Flatpaks and start from scratch with user Flatpaks to reclaim some space on my rootfs (much smaller than home) anyway. But is there anything I can do to help track down this bug before I do?

**Comment by mwleeds** [comment]
@fooishbar you could post `/var/lib/flatpak/repo/config` if there's nothing sensitive in it

**Comment by fooishbar** [comment]
Thanks, nothing sensitive at all:
```
[core]
repo_version=1
mode=bare-user
min-free-space-percent=0

[remote "gnome"]
gpg-verify=true
gpg-verify-summary=true
url=https://sdk.gnome.org/repo/
xa.title=Gnome Stable Runtimes
xa.title-is-set=true

[remote "gnome-nightly"]
url=https://sdk.gnome.org/nightly/repo/
xa.title=GNOME Nightly Runtime
gpg-verify=true
gpg-verify-summary=true

[remote "org.gnome.Builder-origin"]
url=https://sdk.gnome.org/nightly/repo-apps/
xa.title=GNOME Builder
xa.noenumerate=true
xa.prio=0
gpg-verify-summary=true
gpg-verify=true
xa.main-ref=app/org.gnome.Builder/x86_64/master

[remote "flathub"]
url=https://dl.flathub.org/repo/
xa.title=Flathub
gpg-verify=true
gpg-verify-summary=true
xa.noenumerate=false
```

**Comment by mwleeds** [comment]
Interesting that this is pretty much the same behavior as #1427 but a different error message

**Comment by mwleeds** [comment]
Looks like this is an effect of https://github.com/ostreedev/ostree/pull/1286

**Comment by alexlarsson** [comment]
This is where we're using the "$(remote):." form:
https://github.com/flatpak/flatpak/blob/master/common/flatpak-dir.c#L9679

**Comment by mwleeds** [comment]
The support for `<remote>:` syntax landed in ostree v2018.3, so we can at least fix this when that version is available. Is this reason enough to bump the ostree requirement @alexlarsson?

**Comment by mwleeds** [comment]
Oh, now I see that the `<remote>:.` syntax is being supported as well. It's probably a moot point though since I'm about to make a PR that bumps the ostree req anyway.

**Comment by cho2** [comment]
had same issue on `gnome-builder-nightly`

```
galat: Invalid refspec org.gnome.Builder-origin:.
```

**Comment by mwleeds** [comment]
This was fixed by adding a special case in ostree to bring back support for `<remote>:.` syntax (https://github.com/ostreedev/ostree/pull/1500)
