### ISSUE TITLE
flatpak install *Sdk should also install its Platform.

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#1445]
Current state:
* flatpak-builder app
error there's no SDK
* flatpak install SDK
* flatpak-builder app
error there's no platform :sob: 
* flatpak install platform
* flatpak-builder app

**Comment by mwleeds** [comment]
It's conceivable that you genuinely just want the Sdk. Builder for example uses the Sdk as its runtime.

**Comment by alexlarsson** [comment]
Also, there is no real "link" between the two, just naming conventions.
I think the flatpak-builder --install-deps-from=flathub feature is a better solution here.

**Comment by aleixpol** [comment]
Maybe you are right.

**Comment by MihaiTabara** [comment]
This was particulary useful for me too, thanks!
