### ISSUE TITLE
Flatpaks installed into custom location not added to launcher

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1449]
Hi,

I am running Deepin OS 15.5 version ...

I have setup a remote install location to a separate partition named 'Flatpak', program's have been installing and running fine from this remote location (seems like they take a longer to launch) ... anyways ... the apps installed ... install fine except that the the app(.desktop) icons don't get added to the system launcher(icons).

as an alternative i copy the launcher icons(.desktop files) manually to this location ...
```
eg :
cp /media/muz/Flatpak/flatpak/app/org.telegram.desktop/x86_64/stable/68c77269cc033895a1d5c195bbacb87fc9ccec316eabf07b7da22445b3cc9500/export/share/applications/org.telegram.desktop.desktop /home/muz/.local/share/applications/org.telegram.desktop.desktop
```
you might want to look into this issue and rectify the same ...

thanks.

**Comment by aiamuzz** [comment]
ok ... look forward to this issue and #1448 resolved ... thanks for looking.

**Comment by alexlarsson** [comment]
This is tricky to fix.  The way integration works is that the flatpak package adds a script snippet or config file with extends the XDG_DATA_DIRS environment variable in the session, which is then looked at by various processes like dbus and the desktop.

This integration is both distro specific and limited in what it can do, so I don't really see how we could automatically support adding dynamic locations to this. However, you can probably add this manually in your distro by dropping a config file somewhere.

**Comment by alexlarsson** [comment]
I'm going to close this, because its just not solvable from flatpak itself. Its more of a desktop integration issue. We've discussed various ways to easily extend the XDG_DATA_DIRS environment variable in a global deskopt-independent way, and it may be added as a xdg spec some day, but until then there is not much that can be done in a generic way.
