### ISSUE TITLE
Can I use flatpak on Solus?

### ISSUE THREAD

**Issue by Benedeito** [flatpak/flatpak#145]
Since a short time I'm working under the wunderful Linux Distribution Solus. 
The only fly in the ointment is the deficiency of some apps for me. Therefore flatpak sounds good for me. 
Is it possible to test it on my system?

**Comment by alexlarsson** [comment]
I don't see how it wouldn't be possible, but you need to ask the solus developers to package it.

**Comment by Benedeito** [comment]
Ok, thanks a lot for your quick response.
