### ISSUE TITLE
Android Studio icon on dock ...

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1451]
Hi,

I use Deepin OS 15.5 ... which has a dock.
I have added Android Studio Icon to it, ideally when one clicks on the application icon on the dock the application opens and the icon on the dock will have a marker a shadow at the bottom to show that this particular application is open.

ever since i installed Android Studio flatpak version i can see that an additional icon besides the onc i have already added to the dock for quick access.

Again i am not sure if this is a flatpak issue or the Android Studio Flatpak version issue.

please find the screenshot ...

![androidstudiodockicon](https://user-images.githubusercontent.com/3283676/36596402-a1835576-18cb-11e8-8586-bf200fc0c51e.png)

referencing this issue just in case its related ...
 
https://github.com/flatpak/flatpak/issues/1449

**Comment by TingPing** [comment]
Please open this against that package: https://github.com/flathub/com.google.AndroidStudio

I believe it is something that can be fixed in the desktop file it installs.

**Comment by Alexander-Wilms** [comment]
This can be closed
