### ISSUE TITLE
Error when building 4.4 GB module

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak#1452]
When trying to build TeX Live, I get the following error

```
Committing stage build-texlive-texmf-without-scripts to cache
Error: Metadata object of type 'commit' is 11,7 MB; maximum metadata size is 10,5 MB
```
This is the folder structure of the module:

![qdirstat](https://user-images.githubusercontent.com/3226457/36606493-2d4738d2-18c4-11e8-99fc-b71309be5661.png)

How can I work around this?

**Comment by mwleeds** [comment]
Seems like an ostree issue: https://github.com/ostreedev/ostree/blob/779df11c9ed589989ffa0277434a0f059830e0e6/src/libostree/ostree-repo-commit.c#L1958

**Comment by mwleeds** [comment]
I've built flatpaks around 10 GB though, so I wonder what about yours increases the commit metadata so much.

**Comment by Alexander-Wilms** [comment]
One workaround is omitting the doc directory.

**Comment by Alexander-Wilms** [comment]
I get the same result when using TeX Live's binary distribution.

**Comment by alexlarsson** [comment]
Flatpak-builder stores information about all new files in the module in the build cache commit object. My guess is that there are a lot of new files which makes this larger than the limit. So, its not about the size, but the number of files in a module. Maybe we should compress this data...

**Comment by vbraun** [comment]
I hit the same issue when trying to flatpak http://sagemath.org:

    Error: Metadata object of type 'commit' is 12.0 MB; maximum metadata size is 10.5 MB

It seems like this should be fixed by https://github.com/ostreedev/ostree/pull/1744, but I haven't tried

**Comment by hfiguiere** [comment]
Considering fixed. If this still occurs, feel free to open a new issue with how to reproduce.
