### ISSUE TITLE
Persistent folder for config file before first run of flatpak application

### ISSUE THREAD

**Issue by xdibda** [flatpak/flatpak#1454]
Hey, I **do not report an issue**. I only have a question.

I have a configuration file (`.properties` file) for my Java application that has to be editable and all changes made to this config file has to be persistent. I've read, that flatpak currently creates a persistent folder in `~/.var/app/$app_id` which has three subdirectories `data`, `config` and `cache`.

The issue is, I already need to read this `.properties` file on app start, but this `~/.var/app/$app_id` folder is created AFTER the first run of your flatpak application. 

Is there any way to force the flatpak create the folder in given location on installation state so I can copy my config in there and it's accessible on the first run already? Or what's the common pattern to work with config files?

Thank you all!

**Comment by TingPing** [comment]
> Or what's the common pattern to work with config files?

Well, an application should always behave fine when no config is found but.. If you need a file to exist before start you generally just make a wrapper script that sets up whatever and then runs the application.

**Comment by xdibda** [comment]
Okay, thank you for such a quick answer.

I'm closing this.

**Comment by pyrotek45** [comment]
Anyone mind explaining how to create a "wrapper script"?

**Comment by pyrotek45** [comment]
> > Or what's the common pattern to work with config files?
> 
> Well, an application should always behave fine when no config is found but.. If you need a file to exist before start you generally just make a wrapper script that sets up whatever and then runs the application.
> 

How would you create a "wrapper script"?

**Comment by TingPing** [comment]
> How would you create a "wrapper script"?

Make `someapp-wrapper`:

```sh
#!/bin/sh

# This application is broken, do something first
mkdir -p $XDG_CONFIG_HOME/something

exec someapp
```

In your manifest add a source:

```yaml
buildsystem: simple
build-commands:
  - install -Dm755 someapp-wrapper /app/bin/someapp-wrapper
sources:
  - type: file
    path: someapp-wrapper
```

**Comment by pyrotek45** [comment]
> > How would you create a "wrapper script"?
> 
> Make `someapp-wrapper`:
> 
> ```bash
> #!/bin/bash
> 
> # This application is broken, do something first
> mkdir -p $XDG_CONFIG_HOME/something
> 
> exec someapp $@
> ```
> 
> In your manifest add a module to install it:
> 
> ```yaml
> name: someapp-wrapper
> buildsystem: simple
> build-commands:
>   - install -Dm755 someapp-wrapper /app/bin/someapp-wrapper
> sources:
>   - type: file
>     path: someapp-wrapper
> ```
> 
> Lastly set `command` to `someapp-wrapper` instead of `someapp`.

I think you misunderstand, I'm not trying to build a flatpak. I want to install a flatpak like vscode or whatever, and change its config files without running it. If this is how you do that I'm bot sure. I'm kinda a noob at this.

**Comment by TingPing** [comment]
Then just make a script in `~/.local/bin`? You run commands with `flatpak run ...`, config files are in `~/.var/app/...`, etc.

Nothing to specific to flatpak.

**Comment by pyrotek45** [comment]
> Then just make a script in `~/.local/bin`? You run commands with `flatpak run ...`, config files are in `~/.var/app/...`, etc.
> 
> Nothing to specific to flatpak.

Sorry, I'm not understanding.  For instance if you download vscode via flatpak, there is no .var/app/vscodefolders yet untill you run vscode. However I want to change the settings.json file for vscode before I run vscode the first time . How can I change the settings.json ifnthe files arent there?
