### ISSUE TITLE
Flatpak 0.8.9 has a flaky test (testlibrary)

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#1463]
I have been SRU'ing 0.8.9 into Ubuntu 17.10 (artful), when building the package in pbuilder (or in the "cloud") I have sometimes seen a test failure. I've caught one instance of the failure log, so thought I'd report it in-case it still affects the latest series.

The failure in this instance was `testlibrary`, the log from `make check` of pbuilder can be seen here https://pastebin.ubuntu.com/p/yqyNcr8YN2/   Lines 91 to 127 are the test result.

The summary of the test states
```
ERROR: testlibrary - missing test plan
ERROR: testlibrary - exited with status 134 (terminated by signal 6?)
```

Note that if i rerun the build, it is likely that it'll pass - so this is an intermittent failure (or flaky test).

If this has been fixed in a later series, please close this issue :-)

**Comment by matthiasclasen** [comment]
tests have not been flaky for me for a while
