### ISSUE TITLE
 file chooser dialog won't open in KDE applications

### ISSUE THREAD

**Issue by kensully** [flatpak/flatpak#1465]
First of all, thank you for the work.
I am on Ubuntu 16.04.4 platform. It's not KDE desktop. I added kdeapps repo to flatpak and installed KDE apps but they fails to open file chooser dialog browser. I installed xdg-desktop-portal, xdg-desktop-portal-kde, xdg-desktop-portal-gtk. Doesn't flatpak support KDE apps in non KDE desktop environment?

**Comment by kensully** [comment]
This `flathub` application also won't open file chooser dialog 

      flatpak run com.github.robertsanseries.ciano

I get the following error:

      (com.github.robertsanseries.ciano:2): GLib-GIO-WARNING **: Cannot create document portal proxy: Error calling StartServiceByName for org.freedesktop.portal.Desktop: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.Desktop exited with status 127

      ** (com.github.robertsanseries.ciano:2): CRITICAL **: FileUtil.vala:47: OpenURI portal is not available

**Comment by kensully** [comment]
This `flathub` application also won't open file chooser dialog 

      flatpak run com.github.robertsanseries.ciano

I get the following error:

      (com.github.robertsanseries.ciano:2): GLib-GIO-WARNING **: Cannot create document portal proxy: Error calling StartServiceByName for org.freedesktop.portal.Desktop: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.Desktop exited with status 127

      ** (com.github.robertsanseries.ciano:2): CRITICAL **: FileUtil.vala:47: OpenURI portal is not available

**Comment by kensully** [comment]
#https://github.com/flatpak/xdg-desktop-portal/issues/168

**Comment by eszlari** [comment]
Does this still happen with the latest flatpak version 0.11.6?

**Comment by kensully** [comment]
@eszlari  Thank you for informing me. I just tested `flatpak version 0.11.7` I can open file chooser in `KDE` apps, so it appears to be fixed. 
Thank you for the fix.
Regards.
