### ISSUE TITLE
Stupid flatpak question

### ISSUE THREAD

**Issue by dreaddymck** [flatpak/flatpak#1466]
First. The solution that worked was to uninstall flatpak.

The stupid question: 
Is it possible for a flatpak installation to be detected as a separate disc drive?

The reason: 
Kodi on this system would toggle a disc icon on the home page at random intervals. End result would be a crash. Never could figure that out.
Just recently uninstalled flatpak in an attempt to fix this issue: https://github.com/alexlarsson/xdg-document-portal/issues/29

Seems to have resolved both. Just wondering if and why kodi would try to mount flatpak as a disc.

**Comment by mwleeds** [comment]
A flatpak installation is just a directory so I don't see why it would be treated as a mount.

**Comment by dreaddymck** [comment]
I suppose you are right. Kodi problem came back.  Marking this as closed as "waste of time" isn't an option.
