### ISSUE TITLE
Filesystem xdg-dirs language problem

### ISSUE THREAD

**Issue by rexcze** [flatpak/flatpak#147]
Hello,

I specified "--filesystem=xdg-download:rw" in finish-args which points to ~/Downloads, but in czech localization dir has name Stažené. When I open built app (https://github.com/vrutkovs/firefox-flatpak) I can see "Sta~ené", but I can not write into it.

# flatpak run org.mozilla.firefox

(firefox:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
ATTENTION: default value of option force_s3tc_enable overridden by environment.

(/app/lib/firefox-50.0a1/plugin-container:71): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

Maybe this is Firefox issue, but I don't know.

**Comment by hadess** [comment]
You might need to install the locale packages, like: `org.freedesktop.Platform.Locale`
See `flatpak remote-ls <name of repo>` to see the full list.

If that doesn't fix it, run `flatpak run --command=/bin/sh org.mozilla.firefox` and capture the `locale` output.

**Comment by rexcze** [comment]
Hello hadess,

thank you for pointing me out.

My locale output is:

$ flatpak run --command=/bin/sh org.mozilla.firefox
sh-4.3$ locale
LANG=cs_CZ.UTF-8
LC_CTYPE="cs_CZ.UTF-8"
LC_NUMERIC="cs_CZ.UTF-8"
LC_TIME="cs_CZ.UTF-8"
LC_COLLATE="cs_CZ.UTF-8"
LC_MONETARY="cs_CZ.UTF-8"
LC_MESSAGES="cs_CZ.UTF-8"
LC_PAPER="cs_CZ.UTF-8"
LC_NAME="cs_CZ.UTF-8"
LC_ADDRESS="cs_CZ.UTF-8"
LC_TELEPHONE="cs_CZ.UTF-8"
LC_MEASUREMENT="cs_CZ.UTF-8"
LC_IDENTIFICATION="cs_CZ.UTF-8"
LC_ALL=

2016-06-24 1:47 GMT+02:00 hadess <notifications@github.com>:
