### ISSUE TITLE
flatpak run repository-id app-id as alias for flatpak run app-id

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#1470]
Hi,

I find it difficult to remember when I need to specify the repository and when I dont need to do so when using the flatpak CLI interface. So now I got accustomed to always try and write the repository ID before the app id - except when you have to do "flatpak run app-id" in which case flatpak simply fails with the error error:

[bastian@archxps ~]$ flatpak run gnome-nightly-apps org.gnome.Contacts
Invalid id gnome-nightly-apps: Only last name segment can contain -

maybe as fallback, we can try to start the app anyway using the second argument, should there be one? just for convenience sake.

**Comment by matthiasclasen** [comment]
I'm not convinced that we should add redundant arguments like that.
Just type "<Super> contacts <Enter>" and forget about the cli...

**Comment by TingPing** [comment]
It does install the wrapper scripts now so you could just type `org.gnome.Contacts` from the cli also.

**Comment by alexlarsson** [comment]
Yeah, i don't think this is a good idea.
