### ISSUE TITLE
P2P updates fail when an old ostree-metadata is offered

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1473]
When a computer tries to update (or install) from a peer source, either USB or LAN, and that peer offers an older `ostree-metadata` ref than the computer currently has, the update fails. But just because the peer has an old `ostree-metadata` doesn't mean it has nothing to offer; it may have an app that the updating computer doesn't have. So flatpak needs to either (a) pull the old `ostree-metadata` and use it for the update without actually updating the one it has (which I think is impossible for `--user` operations) or (b) treat the old `ostree-metadata` as non-fatal and continue with the update.

**Comment by pwithnall** [comment]
This should become less of a problem if we rely on `ostree-metadata` a bit less by (for example) moving metadata to signed commit metadata (see my comments on #1592). I suspect it would be better to ignore the old `ostree-metadata` and just proceed with our locally cached copy. Anything to do with the list of refs available in the repository should be coming from the `summary`.

**Comment by mwleeds** [comment]
Currently flatpak uses commit metadata for things like permissions, but the `xa.cache` in `ostree-metadata` is still also used for some things, like as a list of remote refs. So this remains an issue and will require care to be fixed without breaking anything else.
