### ISSUE TITLE
Naming scheme: Why does flatpak use long, non-intuitiv application names (Application ID)?

### ISSUE THREAD

**Issue by heis2201** [flatpak/flatpak#1480]
Hi,
I was wondering why flatpak is not using simplified package names or IDs as in distros' packages. If all flatpak apps are starting with an `org`, why not leave it out?  Why have duplicate words in one ID? (example: `org.nextcloud.Nextcloud`, `org.geany.Geany`, ...)? Why not use a short, unique name? (example: `nextcloud`, `geany`, `anydesk`, ...)

Thanks

**Comment by TingPing** [comment]
We need to get this into docs somewhere but basically this: https://github.com/flathub/org.filezillaproject.Filezilla/pull/1#issuecomment-354509330

**Comment by heis2201** [comment]
Thanks for your quick reply and the information provided. Sorry for misusing the issue tracker as an ask forum.
