### ISSUE TITLE
Is it possible to run command line tools from platforms/apps?

### ISSUE THREAD

**Issue by hubslave** [flatpak/flatpak#1483]
Hello friends,

I want to ask similar question as here:

https://github.com/flathub/org.darktable.Darktable/issues/9

> - Darktable application comes with a utility called darktable-cli - a command line batch utility for processing photos from terminal. Is it possible to use this utility when I have Darktable installed as flatpak? If yes how can I use it?

Also I'm wondering if it is possible to run command line utilities from flatpak runtimes such as gnome platform, freedesktop platform, since in the folders I see that there are utilities such as ffmpeg, zip, tar etc. Is it possible to use them somehow? When I try to run for example:

`/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/.../files/bin/zip`

I get this error:

`bash: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/.../files/bin/zip: /lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory`

Thank you very much and have a nice day :)

**Comment by TingPing** [comment]
> Darktable application comes with a utility called darktable-cli - a command line batch utility for processing photos from terminal. Is it possible to use this utility when I have Darktable installed as flatpak? If yes how can I use it?

`flatpak run --command=darktable-cli org.darktable.Darktable --arguments-go-here`

**Comment by BellaCoola** [comment]
Thank you very much @TingPing,

It seems that I can use ffmpeg the same way:

`flatpak run --command=ffmpeg org.gnome.Platform/x86_64/3.26`

Great to know, thank you very much :)

**Comment by hubslave** [comment]
Thank you very much @TingPing,

It seems that I can use ffmpeg the same way:

`flatpak run --command=ffmpeg org.gnome.Platform/x86_64/3.26`

Great to know, thank you very much :)
