### ISSUE TITLE
Can't get info for remotes

### ISSUE THREAD

**Issue by Ads20000** [flatpak/flatpak#1484]
I can't get more details for remotes, which I think is a problem? I have `flathub` and `flathub-1` in `flatpak remotes` but I can't find out more info about them easily from the CLI. `flatpak remote-ls` lists apps and runtimes in a remote, `remote-info` gives info for an app or runtime in a remote, `info` only gives info for a Flatpak app or runtime, but not a remote.

**Comment by ernestask** [comment]
`flatpak remotes -d` should provide more details.

**Comment by Ads20000** [comment]
Ah yes, sorry, I should have run `flatpak remotes --help` to find that, cheers.
