### ISSUE TITLE
error: GPG verification enabled, but no summary signatures found

### ISSUE THREAD

**Issue by hbons** [flatpak/flatpak#149]
Flatpak 0.6.5.

I get this error after trying to install the package from the repo, and after having added the remote successfully (no gpg errors there).

```
[10:14pm] hbons: hi, i’m getting this error trying to sign the repo after upgrading to latest flatpak:
“error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)”
[10:14pm] hbons: any ideas?
[10:24pm] thiblahute: hbons: I had the same issue and asked here without answer, I found that doing `ostree summary -u --gpg-sign=XXX` makes it all work.
[10:24pm] thiblahute: Not sure if there is another solution to get it working without needing to do direct calls to ostree.
[10:24pm] hbons: thiblahute: thanks, i’ll try that 
[10:33pm] hbons: thiblahute: hmm, same error for me unfortunately 
[10:34pm] thiblahute: hbons: Didn't that command create a summary.sig file?
[10:34pm] thiblahute: In the ostree repo
[10:34pm] thiblahute: (you need to run it from the repo folder)
[10:38pm] hbons: thiblahute: yea, did that. it creates the summary.sig but it doesn’t make a difference
[10:38pm] thiblahute: That is weird
[10:38pm] hbons: going to open an issue
```

**Comment by alexlarsson** [comment]
Its not clear exactly what you mean. What repo? Did you create it? How?

**Comment by hbons** [comment]
this is the builder file: https://github.com/hbons/org.sparkleshare.SparkleShare/blob/master/org.sparkleshare.SparkleShare.json

the steps run: https://github.com/hbons/org.sparkleshare.SparkleShare/blob/master/scripts/build.sh

the error happens on the install step. The repo built ok.

**Comment by alexlarsson** [comment]
What type is the repo? Is it an archive-z2?
I.e. how does sparkleshare.org/config look?

Do you have a "summary.sig" file next to the "summary" file in the  repo?

Also can you try something like:
```
 flatpak build-update-repo --gpg-sign=051F66BD sparkleshare.org 
```
And see if it makes any difference.

**Comment by dbnicholson** [comment]
We hit this at endless sometimes. I think what happens is actually a race in the summary file generation and signing. The summary.sig file is not deleted until after the new summary file is created. And then the new summary file isn't signed atomically. So, I think you can get the new summary file and the old summary signature file. The error message is wrong in this case (a bunch of the ostree GPG verification failures use this generic message). So, if someone is pulling apps while the signature is getting regenerated, they might get data that doesn't match.

Not 100% sure, but when I looked into ostree for it, that was the best I could think of.

**Comment by alexlarsson** [comment]
I agree that there is a race here, but its pretty tiny, and only happens on build-update-repo. Do you actually see this race in production?

If so we need to make the writing of the summary file happen to a tmpfile and do the signing on that, and then move everything to the final place with two renames() (still racy, but *tiiiny*).

**Comment by dbnicholson** [comment]
We see it when our image build server is pulling apps from our dev flatpak repo while it's being updated. Happens fairly often.

I had the same idea about the summary file for ostree and was going to open an issue there. The other idea I had to go full atomic would be a summaries directory with a current symlink that can be atomically swapped sure of like the bootloader directory in ostree.

**Comment by alexlarsson** [comment]
Yeah, actual atomicity would be even better. Of course, it really is not atomic to the clients anyway, because they fetch first the summary.sig, and then the summary, and they can change inbetween.

So, even better would be to have an atomically replaced summary.sig, which contained a metadata  field with the unique name of the summary file (we could keep the "summary" name a symlink to the latest summary for backwards compat). Then we could keep old summary files around for a while. This would fix clients racing with the summary being replaced.

**Comment by alexlarsson** [comment]
Closing this for the upstream issue.
