### ISSUE TITLE
org.freedesktop.Platform.GL.nvidia-390-42 runtime not yet available

### ISSUE THREAD

**Issue by hubslave** [flatpak/flatpak#1490]
Hello, I just noticed that Nvidia released new drivers (390.42), which are not yet available in flatpak repositories.

Have a nice day :)

**Comment by TingPing** [comment]
Will be uploaded soon: https://github.com/flatpak/freedesktop-sdk-images/commit/48a0f4f7ea4da52abaac5ec9522b0df383e49b74

**Comment by hubslave** [comment]
resolved, thank you very much :)
