### ISSUE TITLE
[Feature Request] Flatpak Should Be Allowed To Manage App Extensions 

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#1494]
Rhythmbox, Firefox, and Gedit among others have several extensions that the user can install at will. Software centers such as gnome-software already have a way to handle installing these extensions with the traditional package managers. However, with Flatpak, the extensions are singled out. It would be nice if Flatpak can allow packages to have extensions that the user can install at will.

**Comment by TingPing** [comment]
I imagine this would be handled in https://github.com/flatpak/xdg-desktop-portal

**Comment by TingPing** [comment]
Oh sorry I may have mis-interpreted the issue. Apps can already have plugins just fine. An example: https://github.com/flathub/io.github.Hexchat.Plugin.Perl

(I read it as allowing Flatpaks to install their own extensions)

**Comment by Saroufim** [comment]
Ah. It's not a very frequently used feature which made me believe it did not exist. Sorry for the inconvenience.

**Comment by TingPing** [comment]
I might make a blog post about it which will hopefully inspire some other packages to follow.
