### ISSUE TITLE
flatpak-builder: allow to shallow clone git repos

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#15]
_From @hbons on February 27, 2016 21:39_

Git repos can be huge, and when building you may not be interested in the full history.
Maybe a property in the json file (or even changing the default) to allow shallow cloning would save a lot of time and bandwidth.

_Copied from original issue: alexlarsson/xdg-app#112_

**Comment by alexlarsson** [comment]
Hmm, I can see how this could be useful. But its also somewhat tricky. For the initial pull things are fine, but on an update the depth is stored, so the new pull will drop all local history other than the new head of the branch you pulled.

If you're only pulling a repo once this is not really a problem. However, with xdg-app you can have a single download cache shared by multiple json files, or the same json file can refer to the same git repo (either directly or via submodules) which could be problematic if those refered to different branches (or direct commit ids).

I wish there was a way to do an initial shallow clone, but then allow further pulls to just get all changes between your current commit and the new HEAD.

**Comment by alexlarsson** [comment]
_From @hbons on February 29, 2016 13:21_

I think recent Git releases fixed this. You can do a shallow clone and then pull whatever else you need later.

**Comment by alexlarsson** [comment]
There was some kind of fix, but I don't think it does quite what we want here anyway.

**Comment by alexlarsson** [comment]
_From @hbons on February 29, 2016 15:35_

Shallow clones are the default setting in SparkleShare and it works great, so it might be worth looking into. :)

**Comment by jcelerier** [comment]
+1 for shallow clones

**Comment by albfan** [comment]
Any little test that can be configured to implement this? Like a flatpak project with a dependency with more than one commit. Doing a shallow copy from dep and commiting another change to it should be enough to test if this will work. 

I'm trying to install gnome-todo with flatpak and there's a huge repos gnome-online-accounts and evolution-data-server that has no sense to download entirely.

Moreover when I have them downloaded to use with jhbuild. is there too an option to reuse existing repo clones?

Another problem related is on a unsuccesful build (interrunped) flatpak cannot reuse clone_tmp dir and fails (maybe that can be solved too here or another issue is needed)

**Comment by albfan** [comment]
Humm, shallow copies fails

telepathy-account-widgets is a submodule of gnome-online-accounts and it seek for a specific commit so after  bare clone, depth 1 is not correct

Given that I have those repos cloned, is there a way to instruct flatpak to use existing clones (like ~/jhbuild/checkout)?

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#6
