### ISSUE TITLE
Poor performance of update operations

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#1500]
- Fedora 27
- Flatpak 0.10.3

When I update my applications, they often just require a download of not even one MB – still, it takes Flatpak two minutes, for downloading 3,1 MB in total and apply those six updates. Is there a way to speed that up to speeds we’re used to?

**Comment by mwleeds** [comment]
Do you mean using the flathub remote? What is the URL set to? (run `flatpak remotes -d` to check)

**Comment by fbruetting** [comment]
Ah yes.

```
$  flatpak remotes -d
Name               Title                      ADRESSE                                  Priority Options
flathub            Flathub                    https://dl.flathub.org/repo/             1        user   
gnome              Gnome Stable Runtimes      https://sdk.gnome.org/repo/              1        user   
gnome-nightly      GNOME Nightly Runtime      https://sdk.gnome.org/nightly/repo/      1        user   
flathub            Flathub                    https://dl.flathub.org/repo/             1        system 
gnome              -                          https://sdk.gnome.org/repo/              1        system 
gnome-apps         Gnome Stable Applications  http://sdk.gnome.org/repo-apps/          1        system 
gnome-apps-nightly GNOME Nightly Applications https://sdk.gnome.org/nightly/repo-apps/ 1        system 
gnome-nightly      GNOME Nightly Runtime      https://sdk.gnome.org/nightly/repo/      1        system
```

**Comment by mwleeds** [comment]
If it's the download speed and not the speed of the update operation, then this issue would make more sense on https://github.com/flathub/flathub, although I doubt you'll get a great answer since I think a CDN was already deployed for it.

**Comment by fbruetting** [comment]
It’s more the update operation. I made a screencast:
https://www.dropbox.com/s/fluap6vnm4jvk7x/Flatpak%20speed.webm?dl=0

**Comment by TingPing** [comment]
It does an `fsync` after ever operation, so on slow storage it can be painful.

**Comment by fbruetting** [comment]
I have a quite new 256 GB SSD which I can’t believe to be slow… ;)

**Comment by alexlarsson** [comment]
The latest version (0.99.3) is much better at batching certain operations and a `flatpak update` is now a lot faster.
