### ISSUE TITLE
Any commercial support for Flatpak or Flathub?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flatpak/flatpak#1503]
Copied from https://github.com/flathub/flathub/issues/308

Some news:
* [Firefox Quantum snap now available on Linux-based devices](https://insights.ubuntu.com/2018/03/19/firefox-quantum-snap-now-available-on-linux-based-devices)
* [Canonical Officially Announces Mozilla's Firefox as a Snap App for Ubuntu Linux](http://news.softpedia.com/news/canonical-officially-announces-mozilla-s-firefox-as-a-snap-app-for-ubuntu-linux-520302.shtml)

Well Canonical and Ubuntu are well known for their well-known 😂 However one of the key factors leading to a successful open source project is popularity. News, media, usually paid, _do_ come with popularity.

The difference in popularity makes people [Add support for building x64 snap package](https://github.com/Microsoft/vscode/commit/d2b2b4d7ea285561c7ab9b66d01d9d91e4daa8b9) and [Remove flatpak gulp task](https://github.com/Microsoft/vscode/issues/44578).

[The website of Snaps](https://snapcraft.io) is designed in the consistent Ubuntu style. Our website is split into [two](https://flatpak.org) [sites](https://flathub.org/). 🤦

If there is only one platform to package applications on Linux, our solution should be perfect, as disciplinary as RedHat products. But now there are more than one. The "Auto-build from GitHub without review" feature and the "Add package from Ubuntu .deb repo without compiling them every time" feature, _are_ not neat, but they _do_ reduce app developer's time and effort in supporting another platform.

Everyone knows that Snaps is supported by Canonical. Is our project supported by any investors?

Sister: https://github.com/flathub/flathub/issues/308

**Comment by mwleeds** [comment]
Both Red Hat and Endless are invested in Flatpak (using the word invest in a loose sense). Both companies are effectively paying people to maintain it and work in the surrounding ecosystem.

**Comment by matthieugras** [comment]
duplication of effort is great! Maybe we could develop another 2 or 3 solutions that fetch exactly the same apps that are available in the distro repos. But ideally they would have to be completely incompatible and run on a new desktop environment and maybe also be selinux confined (just to make sure you need a phd in comp sc to make the applications work) :+1:
