### ISSUE TITLE
Cannot install Nvidia 390-42 runtime.

### ISSUE THREAD

**Issue by isantop** [flatpak/flatpak#1510]
My system currently has nvidia-390 version `390.42-0ubuntu1` installed. Since the newest version of the nvidia runtime available in flatpak is 390-25 this means that any application requiring the Nvidia driver does not work.

**Comment by TingPing** [comment]
The driver has been there like a week. `flatpak update` should install it but you can explicitly do `flatpak install flathub org.freedesktop.Platform.GL.nvidia-390-42/x86_64/1.4`
