### ISSUE TITLE
Getting warning: Failed to find latest revision for ref appstream

### ISSUE THREAD

**Issue by johnramsden** [flatpak/flatpak#1518]
I've [created a repository](http://flatpakrepo.johnramsden.ca) and installed from it successfully.

```
$ flatpak --user remote-add --if-not-exists johnramsden http://flatpakrepo.johnramsden.ca/johnramsden.flatpakrepo 
$ flatpak --user install johnramsden ca.johnramsden.pathofexile
```

The problem is I keep getting this app stream related Warning. What should I do to get rid of the morning?

I thought it might be because there wasn't appstream  data in my package, but after adding the metadata the message continues to appear.

```
$ flatpak update
Looking for updates...
Failed to find latest revision for ref appstream/x86_64 from remote johnramsden: No such ref 'appstream/x86_64' in remote johnramsden

```

Does some sort of extra appstream data need to be added to the remote as well as the individual application repository?

**Comment by mwleeds** [comment]
I think the per-repo appstream data is generated if you use the `--update-appstream` option on `flatpak build-export`

**Comment by johnramsden** [comment]
@mwleeds I can't seem to find a way to do that with flatpak builder. Does that mean if I'm using builder to export there's no way of updating the appstream data?

**Comment by TingPing** [comment]
@johnramsden Run `flatpak build-update-repo` on the repo after `flatpak-builder` exports it.

**Comment by johnramsden** [comment]
@TingPing Thanks!
