### ISSUE TITLE
Move ~/.var

### ISSUE THREAD

**Issue by Crafter6432** [flatpak/flatpak#1519]
Hi,

I've just tried to move .var using symlinks which didn't really work for some apps, Spotify still worked Steam didn't.

`bwrap: Can't make symlink at /home/x/.var: File exists`

Sylinking .local/share/flatpak onto the other filesystem did't help either, after doing some research I discover that it is possible to move the installation(the app it self) but apparently not it's data(.var).
So just wondering if there is actually a way to move .var or even better just one app's data onto a different filesystem?

**Comment by mwleeds** [comment]
https://github.com/flatpak/flatpak/issues/1224 might be of interest

**Comment by user5145** [comment]
Try to bind it using fstab. Steam works with this configuration
/opt/flatpak		/var/lib/flatpak		none		rw,defaults,bind,noatime,nodiratime	0 2

**Comment by matthiasclasen** [comment]
I don't think there is anything fo ruse to do there
