### ISSUE TITLE
Question: deduplication before dowload / downloading deltas

### ISSUE THREAD

**Issue by rolfen** [flatpak/flatpak#1520]
Say I am downloading a new runtime which shares a few files with a runtime that is already installed.
Will Flatpak skip downloading these files?
If not, is it possible or planned?
Thank you.

**Comment by barthalion** [comment]
Only new files (technically objects) will be downloaded in that case.

**Comment by rolfen** [comment]
Thank you, that is good to know. I understand that this functionality is implemented by OsTree. Although I found the OsTree documentation to be somewhat confusing, it does seem like this is what is happening.

**Comment by rolfen** [comment]
Thank you, that is good to know. I understand that this functionality is implemented by OsTree. Although I found the OsTree documentation to be somewhat confusing, it does seem like this is what is happening.
