### ISSUE TITLE
KDE: Shared _NET_WM_PID results in incorrect audio indicator

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak#1523]
If you run e.g. Keepass and VLC installed from Flathub on KDE 12.2, the audio indicator showing the status of VLC (if it's playing a sound right now) is also shown in the task bar entry of Keepass. But e.g. Octave doesn't show this icon.

![grafik](https://user-images.githubusercontent.com/3226457/37952785-44617f5a-31a1-11e8-8a49-71a48eca0579.png)

xprop tells us that both windows have this property: _NET_WM_PID(CARDINAL) = 2

[keepass-xprop.txt](https://github.com/flatpak/flatpak/files/1850813/keepass-xprop.txt)
[vlc-xprop.txt](https://github.com/flatpak/flatpak/files/1850814/vlc-xprop.txt)
[org.keepassxc.KeePassXC.desktop.txt](https://github.com/flatpak/flatpak/files/1850818/org.keepassxc.KeePassXC.desktop.txt)
[org.videolan.VLC.desktop.txt](https://github.com/flatpak/flatpak/files/1850821/org.videolan.VLC.desktop.txt)

Cf. KDE bug report  https://bugs.kde.org/show_bug.cgi?id=392385

**Comment by kbroulik** [comment]
Note that also the `application.process.id` reported by PulseAudio is `2` so this needs to be adjusted in both places to match up.

**Comment by alexlarsson** [comment]
Its hard to fix this, because the pid that the app itself sees *is* 2, due to the pid namespaces, and it is the app itself that sets _NET_WM_PID. The pid of the process is different outside the sandbox though...

Basically, i think _NET_WM_PID is not really usable in the face of containerized apps...

**Comment by matthiasclasen** [comment]
I don't think this can be fixed in flatpak

**Comment by ratijas** [comment]
KDE System Monitor has a similar issue with associating window info (title, icon) to host processes PID namespace.

https://bugs.kde.org/show_bug.cgi?id=473780
