### ISSUE TITLE
Flatpak apps don't respect "Large Text" settings

### ISSUE THREAD

**Issue by kwill** [flatpak/flatpak#1525]
**Steps to reproduce:**

1. In GNOME Settings > Universal Access, turn on "Large Text"
2. Launch Flatpak app

**What should happen:**

* GUI and content appear larger than usual (like other applications)

**What happens instead:**

* GUI and content both remain the same size

**Notes:**

* See comments at https://gitlab.gnome.org/World/fractal/issues/160

**Comment by Exalm** [comment]
I cannot reproduce this.
Flatpak 0.11.3, Fedora 28 Atomic Workstation, Fractal 0.1.22 from Flathub.

**Comment by matthiasclasen** [comment]
it will work as long as the sandboxed app has access to dconf. under wayland, gtk directly reads the text scaling factor out of gsettings.

**Comment by matthiasclasen** [comment]
Seems confirmed in the fractal issue
