### ISSUE TITLE
can I remove `~/.local/share/flatpak/repo/objects` directory?

### ISSUE THREAD

**Issue by kensully** [flatpak/flatpak#1526]
I am running out of space in my OS, I noticed that `~/.local/share/flatpak/repo/objects` occupies around 17GB. Is it safe to remove that directory to regain space?

**Comment by alexlarsson** [comment]
That is where the flatpaks are installed, and removing it will break stuff. If you want to remove all your flatpaks, then remove the entire `~/.local/share/flatpak/` instead.
