### ISSUE TITLE
What am I doing wrong? Skype

### ISSUE THREAD

**Issue by kenny-w7** [flatpak/flatpak#1529]
Hello! I'm very new to the flatpak/appimage sort of things, I'm having trouble getting Skype installed.
I'm running Void Linux x86_64-MUSL.

flatpak --user install --from https://s3.amazonaws.com/alexlarsson/skype-repo/skype.flatpakref
sudo flatpak install --from https://s3.amazonaws.com/alexlarsson/skype-repo/skype.flatpakref
Just hangs. Won't budge.

I've tried running these:
wget https://sdk.gnome.org/keys/gnome-sdk.gpg
flatpak --user remote-add --gpg-import=gnome-sdk.gpg gnome http://sdk.gnome.org/repo/
flatpak --user install gnome org.freedesktop.Sdk 1.4
flatpak --user install gnome org.freedesktop.Platform 1.4

these worked & installed OK, but the next commands won't work at all, I've already cloned the github repo for skype flatpak but the make command also fails...

make
flatpak --user remote-add --no-gpg-verify local-skype repo
flatpak --user install local-skype com.skype.Client

flatpak-builder --force-clean --repo=repo --ccache --require-changes skype com.skype.Client.json
Downloading sources
Downloading http://ftp.kernel.org/pub/linux/utils/kernel/hotplug/udev-175.tar.bz2
Failed to download sources: module udev: Error resolving “ftp.kernel.org”: Name does not resolve
make: *** [Makefile:9: test] Error 1

I'm trying again with the snaggen/skype-app repo, I was using the gbraad one before which I assume may have been the problem.

**Comment by kenny-w7** [comment]
This is the error I end up with when trying to install it via the snaggen/skype-app repo:

https://pastebin.com/W0rzRXQP

**Comment by TingPing** [comment]
You are using the wrong repo: https://beta.flathub.org/apps/details/com.skype.Client

**Comment by kenny-w7** [comment]
Ohh ok, thank you TingPing. I am currently attempting to install it via your link. I'm really new to this whole FlatPak/AppImage stuff, sorry.

**Comment by kenny-w7** [comment]
Yay, it works now! How can I get it added to the desktop-environment menu?

**Comment by TingPing** [comment]
> Is this wrong? Should this be updated to the one you gave me?

Yes.

**Comment by kenny-w7** [comment]
Hey one last question, 

error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)

What do I do to make this work?

**Comment by TingPing** [comment]
For what repo?

**Comment by kenny-w7** [comment]
I'm trying to install Discord from flathub

**Comment by kenny-w7** [comment]
I don't understand what I'm doing wrong :( 
I thought I already added flathub why do I have to do it again??? I can't get this thing to install no matter what I do ugh...

**Comment by kenny-w7** [comment]
flatpak install flathub com.discordapp.Discord
error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)

please tell me what command I need to do to make this work....
????????????? :/

**Comment by mwleeds** [comment]
@kenny-w7 post exactly what command you're running and the output? It's probably a confusion between the user and system installations of flatpak

**Comment by kenny-w7** [comment]
I did post it, what am I doing wrong??? I don't understand... I did the commands it told me to do but it doesn't work...

flatpak install flathub com.discordapp.Discord
error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)

**Comment by mwleeds** [comment]
that is odd. You could post the output of `ls /var/lib/flatpak/repo/`, `cat /var/lib/flatpak/repo/config`, `ls ~/.local/share/flatpak/repo/` and `cat ~/.local/share/flatpak/repo/config`.

**Comment by mwleeds** [comment]
You could also try installing it in your user installation: `flatpak install --user flathub com.discordapp.Discord`

**Comment by kenny-w7** [comment]
flatpak install --user flathub com.discordapp.Discord
error: Remote "flathub" not found

ls /var/lib/flatpak/repo/
config	extensions  flathub-1.trustedkeys.gpg  gnome.trustedkeys.gpg  objects  refs  state  tmp

cat /var/lib/flatpak/repo/config
[core]
repo_version=1
mode=bare-user-only
min-free-space-percent=0

[remote "gnome"]
gpg-verify=true
gpg-verify-summary=true
url=https://sdk.gnome.org/repo/
xa.title=Gnome Stable Runtimes
xa.title-is-set=true

[remote "flathub"]
gpg-verify=true
gpg-verify-summary=true
url=https://dl.flathub.org/repo/flathub.repo

[remote "flathub-1"]
url=https://dl.flathub.org/repo/
xa.title=Flathub
gpg-verify=true
gpg-verify-summary=true

ls ~/.local/share/flatpak/repo/
config	extensions  gnome.trustedkeys.gpg  objects  refs  state  tmp

[core]
repo_version=1
mode=bare-user-only
min-free-space-percent=0

[remote "gnome"]
gpg-verify=true
gpg-verify-summary=true
url=http://sdk.gnome.org/repo/

[remote "local-skype"]
gpg-verify=false
gpg-verify-summary=false
url=file:///home/kzn/Documents/repo

[remote "local-discord"]
gpg-verify=false
gpg-verify-summary=false
url=file:///home/kzn/Compiles/repo

**Comment by kenny-w7** [comment]
I managed to install Discord from the local file, but why doesn't it work when I do the flathub non-local way?

**Comment by mwleeds** [comment]
Interesting, you have two flathub remotes and only one of them has a `.trustedkeys.gpg` file in the repo

**Comment by mwleeds** [comment]
I would delete the flathub remote, rename flathub-1 to flathub, and rename flathub-1.trustedkeys.gpg to flathub.trustedkeys.gpg

**Comment by mwleeds** [comment]
Although it would be nice to know how you got in that state in case there's a flatpak bug

**Comment by kenny-w7** [comment]
Now I get this:
sudo flatpak install flathub com.googleplaymusicdesktopplayer.GPMDP
error: GPG signatures found, but none are in trusted keyring

**Comment by mwleeds** [comment]
Check if `/var/lib/flatpak/repo/flathub.trustedkeys.gpg` exists

**Comment by kenny-w7** [comment]
Ah, its flathub-1 in there too, I'll rename it.

**Comment by mwleeds** [comment]
@kenny-w7 I think you did `flatpak remote-add https://dl.flathub.org/repo/flathub.repo` rather than `flatpak remote-add https://dl.flathub.org/repo/flathub.flatpakrepo` at some point. It might be good if flatpak didn't add the remote with the wrong URL (it already prints an error).

**Comment by bossjones** [comment]
Just confirming the behavior and solution for others to find this. While attempting to use a dated github project(2017 - https://github.com/takluyver/pygame-flatpak-test) to begin my journey into building applications using flatpak, I accidentally ran some commands that incorrectly configured both my gnome remote and my flathub remote. 

The old commands were:

```
	# Install the freedesktop 1.4 platform and SDK (runtime for building the app)
	flatpak remote-add --if-not-exists gnome http://sdk.gnome.org/repo/
	flatpak install gnome org.freedesktop.Sdk//1.4 || true
	flatpak install gnome org.freedesktop.Platform//1.4 || true
```

After doing that I started getting `error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)`. Following the conversation in this thread, I ran the commands suggested by @mwleeds in-order to debug my VM:

```
ls /var/lib/flatpak/repo/
cat /var/lib/flatpak/repo/config
ls ~/.local/share/flatpak/repo/
cat ~/.local/share/flatpak/repo/config
```

I noticed his comment in https://github.com/flatpak/flatpak/issues/1529#issuecomment-377040905 and looked at the urls I was trying to add an realized they were incorrect. In order to fix it, I needed to run the following from the `--user` and `--system` level (In my situation) 

```
# delete remotes at system level
sudo flatpak remote-delete --force flathub
sudo flatpak remote-delete --force gnome

# delete remotes at user level
flatpak --user remote-delete --force flathub
flatpak --user remote-delete --force gnome

```

Then finally re-add all remotes everything ( Notes I ran with --no-gpg-verify just for testing purposes ).

```
flatpak remote-add --no-gpg-verify --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
	flatpak remote-add --no-gpg-verify --if-not-exists gnome https://sdk.gnome.org/gnome.flatpakrepo
	flatpak --user remote-add --no-gpg-verify --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
	flatpak --user remote-add --no-gpg-verify --if-not-exists gnome https://sdk.gnome.org/gnome.flatpakrepo
```

Details on my setup.

```
[developer@gnometop pygame-flatpak-test]$ flatpak --version
Flatpak 0.10.4
```

Running on Fedora 25.

Thanks for listing out debugging steps in this git issue, it helped me out!

**Comment by bossjones** [comment]
@mwleeds agreed re: both points. Going to get rid of the —no-gpg-verify and try running everything at the system level! Thanks again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
