### ISSUE TITLE
Problem with 32 bit application? 'ldconfig: Exec format error'

### ISSUE THREAD

**Issue by johnramsden** [flatpak/flatpak#1539]
I've created [a flatpak](https://github.com/johnramsden/pathofexile-flatpak), and while it runs fine for me, someone trying to use is getting [an error](https://github.com/johnramsden/pathofexile-flatpak/issues/1):

```
> flatpak run ca.johnramsden.pathofexile
execvp ldconfig: Exec format error
error: ldconfig failed, exit status 256
```

I was wondering if this could be related to the fact that I used an i386 run time, and he is installing it on a 64bit OS. From what I understood flatpak should fine with this, and since I too am using a 64bit OS, I know it does works on 64-bit. Do you have any idea what might be causing this problem?

**Comment by TingPing** [comment]
I've certainly ran 32bit apps on 64bit host before, so it is more than that

**Comment by johnramsden** [comment]
I've ran it on a 64-bit host, I was just wondering if you thought it might be related. Any recommendations for debugging?
