### ISSUE TITLE
No support for new NVIDIA Long-Lived Branch Driver Release - v390.48

### ISSUE THREAD

**Issue by RogueScholar** [flatpak/flatpak#1543]
I'm attempting to get more comfortable with the flatpak ecosystem and decided to start with installing the app Tiliado on my system running Kubuntu Bionic Beaver Beta 1 (18.04), but I've reached an impasse since the NVIDIA driver update hit the repos a few days ago but doesn't appear to have a corresponding package available for flatpak. Tiliado's [documentation](https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers) has me looking for it in the gnome repo. Should I be looking elsewhere, or do I just need to be patient for an updated port of those drivers to be added?

Driver link: http://www.nvidia.com/Download/driverResults.aspx/132530/en-us

**Comment by TingPing** [comment]
Added https://flathub.org/builds/#/builders/2/builds/522 - Will take a bit before it hits the repo.
