### ISSUE TITLE
Compose key combinations from ~/.XCompose don't work

### ISSUE THREAD

**Issue by Exalm** [flatpak/flatpak#1545]
It's possible to define additional compose key combinations in `~/.XCompose` file, e.g. 
```
include "/usr/share/X11/locale/en_US.UTF-8/Compose"
<Multi_key> <Z> <minus>         : "Ƶ"
<Multi_key> <z> <minus>         : "ƶ"
```
Unless sandbox has access to home, it doesn't get loaded.

**Comment by matthiasclasen** [comment]
not a flatpak issue

**Comment by felix-hoc** [comment]
If anyone else is running across this problem: I had this issue with Slack and managed to fix it by installing [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) (makes managing Flatpak permissions easier) and allowing access to `~/.XCompose`.

**Comment by RalfJung** [comment]
> If anyone else is running across this problem: I had this issue with Slack and managed to fix it by installing [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) (makes managing Flatpak permissions easier) and allowing access to `~/.XCompose`.

I tried that, but it does not seem to work -- `flatpak run com.vscodium.codium  --filesystem=~/.XCompose:ro` still does not respect my compose settings.

> not a flatpak issue

Why not? This works fine in all regular applications, and is broken in all flatpak applications. Looks like a flatpak issue to me.

**Comment by develop7** [comment]
> `include "/usr/share/X11/locale/en_US.UTF-8/Compose"`

@Exalm consider using `include "%L"` along with sharing the `~/.XCompose` with the sandbox(es), might do the trick if the sandbox does have a `Compose` file but under a different path
