### ISSUE TITLE
Empty Menu List shown

### ISSUE THREAD

**Issue by olissongs** [flatpak/flatpak#1549]
## Linux distribution and version
16.04 LTS 64 BIT x86 / unity
## Flatpak version
0.11.3
## Description of the problem
no Apllikation menus in
## Steps to reproduce
flatpak install --from https://www.tabos.org/wp-content/uploads/2018/04/roger.flatpakref 
sudo flatpak run org.tabos.roger -d (i dont know why sudo, but it dont work else)
the Application starts, and the menu is an empty List shown, instead of the Appliction Menu Entries

**Comment by matthiasclasen** [comment]
Closing this, as it was reported against an old version of flatpak. Please reopen, if you still see this issue with flatpak 1.0.x
