### ISSUE TITLE
Ubuntu 17.10 unable to launch any flatpak app

### ISSUE THREAD

**Issue by fchaillou** [flatpak/flatpak#1553]
## Linux distribution and version
Ubuntu 17.10

## Flatpak version
Flatpak 0.11.3

## Description of the problem
When trying to run any app with flatpak it fails with :
```
kernel: traps: flatpak-bwrap[27624] general protection ip:7faeef2cf085 sp:7fff8dbadee0 error:0 in libc-2.26.so[7faeef296000+1d6000]
```
## Steps to reproduce
Just try to run a flatpak app on an up to date ubuntu 17.10 and in the journal you will see the previously mentionned error.

I tried to google for a solution but found nothing.
By the way my home folder is encrypted with ecryptfs `/home/.ecryptfs/fabien/.Private on /home/fabien type ecryptfs` 

`/usr/lib/flatpak/flatpak-bwrap --ro-bind / / --dev /dev --unshare-user /bin/true; echo $?` returns 134 for me !

**Comment by hfiguiere** [comment]
out of date.
