### ISSUE TITLE
Cannot install on elementary OS freya

### ISSUE THREAD

**Issue by SuicSoft** [flatpak/flatpak#156]
When I run

```
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak
```
I get **E: Unable to locate package flatpak**

**Comment by alexlarsson** [comment]
The ppa is for ubuntu xenial, and does not target elementary.

**Comment by SuicSoft** [comment]
@alexlarsson How can I get it installed then.Do I have to build it from source ?
