### ISSUE TITLE
Please add flatform GL driver for long-lived nvidia driver version 384.130

### ISSUE THREAD

**Issue by RisingPhorce** [flatpak/flatpak#1570]
## Linux distribution and version
Ubuntu 17.10

## Flatpak version
Flatpak 0.8.9

## Description of the problem
Please add flatform GL driver for long-lived nvidia driver version 384.130 (currently platform drivers only go up to 384-111)

https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

## Steps to reproduce
$ cat /sys/module/nvidia/version
384.130

$ flatpak remote-ls gnome | grep GL.nvidia | grep 384
org.freedesktop.Platform.GL.nvidia-384-111        
org.freedesktop.Platform.GL.nvidia-384-47         
org.freedesktop.Platform.GL.nvidia-384-59         
org.freedesktop.Platform.GL.nvidia-384-69         
org.freedesktop.Platform.GL.nvidia-384-90         
org.freedesktop.Platform.GL.nvidia-384-98

**Comment by TingPing** [comment]
Added https://flathub.org/builds/#/builders/2/builds/753
