### ISSUE TITLE
Exporting mime types

### ISSUE THREAD

**Issue by create3000** [flatpak/flatpak#1572]
## Description of the problem

My application ships with some custom mime types which are not exported from flatpak. Flatpak produces an error "Not exporting share/mime/packages/x3d+xml.xml, wrong prefix".  After reading https://developer.gnome.org/integration-guide/stable/mime.html.en I created a mime type file in share/mime/packages/x3d+xml.xml for the mime type "model/x3d+xml". What do I do wrong?

You wrote "We now export mime type files with the right name." What are the conditions for the right name?

The associated icon for the mime type is also not exported producing the error "Not exporting share/icons/hicolor/scalable/mimetypes/model-x3d+xml.svg, wrong prefix" What do I do wrong?

Holger Seelig

**Comment by mwleeds** [comment]
@create3000 the mime type and icon have to have the app ID as a prefix, so that you can't export data for some other application. See http://docs.flatpak.org/en/latest/conventions.html

**Comment by TingPing** [comment]
To clarify the file name of the mime type must match the ID, the types can be anything.

**Comment by create3000** [comment]
Thank you very much. This solves my problem. Everything works fine.
