### ISSUE TITLE
Support for rootless install

### ISSUE THREAD

**Issue by adamryczkowski** [flatpak/flatpak#1576]
Does flatpack support (and ever will) installation without the root privileges? I would like to use it on a HPC mainframe as a walkaround for the very slow pace with which the software is being updated by the admin.

**Comment by alexlarsson** [comment]
Flatpak can install applications as non-root by passing --user to the various commands. Additionally you can install flatpak yourself as a non-root user *if* your kernel supports non-privileged user namespaces. If it doesn't, then you need a setuid version of bubblewrap, which can only be installed by root.

**Comment by TangentFoxy** [comment]
For anyone as stupid as me stumbling across this in the future, it's not an *option* where you specify the user, it's a *flag* that is only used with the current user.

I spent a while trying to use `--user my_name` and wondering why it kept failing weirdly because I misread the answer.
