### ISSUE TITLE
Does flatpak support something like local cache server to reduce the bandwidth?

### ISSUE THREAD

**Issue by adamryczkowski** [flatpak/flatpak#1577]
Question in title. As I understand, unlike e.g. apt, flatpack does not store copies of the downloaded data, so simply sharing the directory will not be possible. 

There is an option to run a flatpack repository, but I understand it will not work as a proxy. It will only provide manually added data, and will not cache data that are being requested by one of the clients like apt-cacher does.

**Comment by alexlarsson** [comment]
There is work in progress to make flatpak handle something like this. This is the "peer-2-peer" feature that you currently have to explicitly enable in ostree and flatpak. This is work in progress though.

**Comment by adamryczkowski** [comment]
Thank you.
