### ISSUE TITLE
Can't pull org.gnome.Platform/x86_64/3.24

### ISSUE THREAD

**Issue by Zlopez** [flatpak/flatpak#1581]
## Linux distribution and version
Fedora 27
## Flatpak version
flatpak-0.10.4-1.fc27.x86_64
## Description of the problem
When I try to update org.gnome.Platform I'm getting: 
`Error: Failed to update org.gnome.Platform/x86_64/3.24: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: While pulling runtime/org.gnome.Platform/x86_64/3.24 from remote flathub: Couldn't find file object 'df01368d0415cda2d22e7b785d0aeb80938834225a011ead17835f6d22cb67f8'`
## Steps to reproduce
1. flatpak update

**Comment by Zlopez** [comment]
I resolved this issue by uninstalling the org.gnome.Platform/x86_64/3.24 and installing org.gnome.Platform.Locale/x86_64/3.28 instead

**Comment by Darcidride** [comment]
@Zlopez 
Thank you for this issue and the solution, you're part of the first answers on Duckduckgo.
I fixed my issues (same of yours) with this solution

**Comment by Zlopez** [comment]
@Darcidride 
I'm glad this was helpful to you.
