### ISSUE TITLE
SUGGESTION : Branding / Identifying Flatpak apps from native ones !!!

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1582]
## Linux distribution and version

Deepin 15.5

## Flatpak version

flatpak - 0.11.3.p1-4(amd64)

## Description (a Branding/Cataloguing  Suggestion)

Hi,

with the native apps and flatpaks showing up in my application drawer/launcher i wanted somehow to identify which app was a native linux app and which one was flatpak app. This necessity arose from the fact that Deepin OS has adopted flatpak out-of-the-box, as flatpak is a relatively new field the Deepin team have 2 versions of their apps 'Native' and 'Flatpak' versions. Due to their internal organizational constraints they delay pushing updates to their flatpak version of the apps. As a result i have installed native apps as well as flatpak versions side by side for the purposing of testing for them.

Out of this need i wanted to easily distinguish between the native and flatpak versions from the app launcher, i started modifying the .desktop file 'Name' attribute to 'AppName (Flatpak)'.

As i am a freelance brand/design consultant it was but a matter of time to have thought of this suggestion.

Please find mockups of the same below ...

## Branding/Identification Suggestion for Flatpak apps

![mylaunchericons 1](https://user-images.githubusercontent.com/3283676/38812729-bf8a0cec-41aa-11e8-9ea3-b239a23aacde.png)

![mylaunchericons 3](https://user-images.githubusercontent.com/3283676/38812735-c3e48394-41aa-11e8-94c6-6870fdd3325f.png)

![flatpakwebsite 5](https://user-images.githubusercontent.com/3283676/38812738-c6bb690c-41aa-11e8-8941-e87363337527.png)

## I don't know ... a possible implementation ?

this is a transparent image file with the suggested Brand identification(the flatpak logo at the bottom right of the app icon/image) for compositing(superimposing) over the default app icon images ... either through coding ... or as a mandatory guideline to publishers to composite it over their flatpak apps icon/images.

![flatpakcomposite_512px_300dpi_darkershadow3](https://user-images.githubusercontent.com/3283676/38812913-36a1d170-41ab-11e8-9cf7-8c9256282c80.png)

Is the idea any good ?

from a branding point of view it has tremendous scope for the users to adopt the flatpak version of the apps over native ones.

**PS : I just reinstalled my Deepin OS on another partition today and as i had a separate partition for flatpaks from my previous Deepin Installation, i can't begin to describe what a breeze it was for me to recreate the remote on this new installation and point it to the flatpak partion(my personal repository of flatpak applications)**

**Comment by alexlarsson** [comment]
Yeah, i don't really agree with the overall notion that you need to be told that there is something special about certain apps in your daily driver experience. The goal of flatpak is to be fully integrated so that it *doesn't* feel non-native.

I mean, there are cases where the flatpak *is* special, like if you're using a flatpak to run the developement or testing version of some app. But then it is up to the packager of that app to tweak the icon/name to differentiate with the regular one.

**Comment by aiamuzz** [comment]
ok ... i used the term 'native' here for the lack of better word when referring to a non-flatpak app ...
would a generic-linux-app be an ideal term to refer it as ? :) ... hope that takes care of the offence the term 'native' might have generated :)

> But then it is up to the packager of that app to tweak the icon/name to differentiate with the regular one

I feel the flatpak team is a better entity to add a small script which watermarks all app icons in the icon folders as part of the packaging process BUT if the flatpak team feels the packager is a better entity to handle it then a **flatpak-packaging-guideline SHOULD stipulate it as a MANDATORY requirement for all flatpak packaged apps so that every flatpak app that is packaged has this visually differentiating element,**

The reason i strongly lobby for it, is for the same purpose any brand would want to put the branding logo on their products ... to gain traction ... to become popular ... so that it catches on ... a little effort in this direction shouldn't hurt.

I would like to see flatpak get popular against the generic-linux-apps system for the simple reason that its a 'fantastic concept' and i am totally sold on it (there is no way i would like to go back to the typical linux packages, especially after my recent OS re-install ... where all i had to do was create a remote to my separate flatpak partition with all my favorite apps !!!)

i remember by college days, days when we used to fiddle with windows 95 ... believe me i have personally tried to achieve the idea of installing-only-once by trying to install all my softwares and games to D:\ ... but that remained a dream ... **for me flatpak is an actual dream come true !!!**

Someday I would love to see the flatpak team recommend by Default an installation to a seperate partition ... that way they would achieve "install-only-once-and-update-to-perpetuity" idea believe me it is an irresistible idea from a user perspective and i greatly hope it will help popularize the flatpak concept !!!

**Comment by mwleeds** [comment]
@aiamuzz note that Flatpak has some amount of branding already in that you see the Flatpak icon in GNOME Software when you're looking at a flatpak'd app.

**Comment by mwleeds** [comment]
@aiamuzz never mind I guess it just says "Sandboxed"
![screenshot from 2018-04-28 10-55-40](https://user-images.githubusercontent.com/7833263/39399491-6a5b5a0a-4ad3-11e8-92dc-9b6d89520295.png)

**Comment by aiamuzz** [comment]
Yeah that doesn't amount to branding ... flathub.org is the only pointer that points to flatpak.

i guess its possible to superimpose/watermark an icon in the launcher by way of coding after all !!!

Just discovered the following in my deepin app drawer when i tried to add apps to startup ... notice how the Chrome and qBittorrent app as a small icon at the bottom left corner ???

would love to see our flatpak apps carry a similar thing ... a little flatpak sandbox logo ... on the right corner as i have tried to show in the mockup in the first post ...

![dmovie20180429000538](https://user-images.githubusercontent.com/3283676/39399779-c4dc994e-4b41-11e8-9f07-22009e6b7364.jpg)

PS : if flatpak team did the scripting it it would be consistent (which is paramount when it comes to branding) across all linux distro app drawers/start menu's !!!

**Comment by aiamuzz** [comment]
ok ... i think i kind of figure how this has been pulled off ...

Deepin's implementation is one where one has to just right click an icon in the app drawer and select 'Add to startup' from the menu and this operation copies the relevant desktop configuration file to the 'autostart' folder at the path above ... 
...alternately ...
 i tried to just copy an app desktop configuration file manually into this 'autostart' folder ... guess what ... the startup icon watermark does show up on the copied app icon inside the drawer too.

so i guess its as simple as marking a particular folder and its contents to display the watermark !!!
and flathub already has such folders ...
... aka ... 
/var/lib/flatpak/exports/share/applications - the default flatpak folder for app icons.
&
/media/user/Flatpak/flatpak/exports/share/applications - the remote location (separate flatpak partition)

**Comment by matthiasclasen** [comment]
all of this is offtopic for the flatpak issue tracker
