### ISSUE TITLE
`flatpak remote-ls URI` broken

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1588]
You used to be able to do this:
```
↳ flatpak remote-ls file:///run/media/mwleeds/f6d04c7a-60f6-4ba3-bb96-0f40498675be/.ostree/repo
Ref             
org.kde.Khangman
```

But it looks like this behavior is broken on master:
```
↳ flatpak remote-ls file:///run/media/mwleeds/f6d04c7a-60f6-4ba3-bb96-0f40498675be/.ostree/repo
error: Remote "file:///run/media/mwleeds/f6d04c7a-60f6-4ba3-bb96-0f40498675be/.ostree/repo" not found
```

**Comment by alexlarsson** [comment]
This probably broke with the RemoteState stuff, we should add a test for this when we fix it to make sure it doesn't regress again.

**Comment by mwleeds** [comment]
I bisected and it turns out this was broken in b3828eea46ceaee61b58bbc38a637214632fa64e, so it was my fault. I'm looking at fixing it now.

**Comment by mwleeds** [comment]
It turns out fixing this on master requires both [this patch](https://github.com/flatpak/flatpak/pull/1587/commits/017034c9107b760804a51fea0365d6da11de98c9) already being proposed and another I'm about to propose.
