### ISSUE TITLE
Flatpak is too dependent on xa.cache

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1597]
Currently one of the tests, `test_list_refs_in_remotes`, is failing on master with P2P enabled. Here's an excerpt:
```
PASS: testlibrary 11 /library/list-refs
# Spawning /src/flatpak_0.10.1+dev303.d6e558e/_build/sub/flatpak-bwrap --unshare-ipc --unshare-net --unshare-pid --ro-bind / / /bin/true
ok 12 /library/install-launch-uninstall # SKIP bwrap not supported
SKIP: testlibrary 12 /library/install-launch-uninstall # SKIP bwrap not supported
# Spawning /src/flatpak_0.10.1+dev303.d6e558e/_build/sub/../../tests/make-multi-collection-id-repo.sh /var/tmp/flatpak-test-AH2SHZ/multi-refs-repo
# Spawning flatpak remote-add --user --no-gpg-verify multi-refs-repo file:///var/tmp/flatpak-test-AH2SHZ/multi-refs-repo
# flatpak-DEBUG: Fetching summary file for remote ?multi-refs-repo?
# flatpak-FATAL-WARNING: Ignoring ref app/org.test.Hello2/x86_64/master due to lack of metadata
ERROR: testlibrary - too few tests run (expected 14, got 12)
ERROR: testlibrary - exited with status 133 (terminated by signal 5?)
```
Here's what happened:
1. In `make-multi-collection-id-repo.sh` we run `ostree summary --update`, so the summary and `ostree-metadata` don't have `xa.cache`. According to [this comment](https://github.com/flatpak/flatpak/blob/9afca51507efa7f40fa438fb26d2e2fe2d2358d4/tests/test-unsigned-summaries.sh#L84), this should be a supported setup (although it raises questions about how we will be able to list remote refs on LAN peers in the offline case).
2. This call chain happens: `test_list_refs_in_remote` -> `flatpak_installation_list_remote_refs_sync` -> `flatpak_remote_ref_new` -> `flatpak_remote_state_lookup_cache`, then since it can't find `xa.cache` in the metadata it errors out.

**Comment by alexlarsson** [comment]
I'm not sure what the general p2p offline approach is to repo-wide operations like listing the remote refs? Are we supposed to fail that when offline, or do we return some partial list reconstructed from all nearby peers?

**Comment by alexlarsson** [comment]
It would be *nice* if we could rely on the xa.cache in some way. I guess we can return 0 for e.g. the download size and nothing would break, but if e.g. gnome-software is using the metadata to show sandbox status of the app, then we need to have access to the "metadata" file. And ideally in a single place, to avoid having to separately download the commit object for all apps in the remote.

**Comment by mwleeds** [comment]
> I'm not sure what the general p2p offline approach is to repo-wide operations like listing the remote refs? Are we supposed to fail that when offline, or do we return some partial list reconstructed from all nearby peers?

I guess that's open for discussion. I would kind of expect `remote-ls` to list the ref available on the Internet server. If we're offline and can't find `xa.cache`, I think the only way we could list remote refs is by using the `OstreeRemote` object in `OstreeRepoFinderResult` instances and fetching the summary from that, which is a bit messy.

> It would be nice if we could rely on the xa.cache in some way. I guess we can return 0 for e.g. the download size and nothing would break, but if e.g. gnome-software is using the metadata to show sandbox status of the app, then we need to have access to the "metadata" file. And ideally in a single place, to avoid having to separately download the commit object for all apps in the remote.

We could treat a failure to get the metadata in `flatpak_remote_state_lookup_cache` as non-fatal and have separate API that fetches it from the commit metadata. The API GNOME Software uses is `flatpak_installation_fetch_remote_metadata_sync`. So that might be a reasonable place to do the fetch. That way you have a specific ref to do it for, rather than all of them.

**Comment by mwleeds** [comment]
I suppose that would get pretty inefficient if you have a lot of remote refs and `flatpak_installation_fetch_remote_metadata_sync` gets called on each. We could have `flatpak_remote_state_lookup_cache` fetch the commit metadata for every ref at once when it can't find `xa.cache` but then it's named misleadingly.

**Comment by mwleeds** [comment]
I submitted https://github.com/flatpak/flatpak/pull/1600 but it's only a partial fix for this.

**Comment by alexlarsson** [comment]
@pwithnall So, that sounds good to me. What operations do we expect to work when offline? Install and update only?

**Comment by pwithnall** [comment]
Initially, yes. With some of the work Sam’s doing, I would expect that finding related refs should work when offline (since we don’t have to search for them — they’re listed in an app’s metadata). Listing apps using the `appstream` data is also expected to work offline, but listing apps by seeing what refs are available on your peers is not supported.

**Comment by mwleeds** [comment]
This is fixed now that we get `xa.cache` from `ostree-metadata` when possible.
