### ISSUE TITLE
Cache ostree summary for remotes to disk for later offline use (non-p2p)

### ISSUE THREAD

**Issue by smspillaz** [flatpak/flatpak#1604]
Right now, performing operations like `flatpak_installation_list_remote_related_refs_sync` and `flatpak_installation_list_remote_refs_sync` isn't possible when offline, since the ostree summary file for a repo is pulled from the remote by `flatpak_dir_remote_fetch_summary` whenever we use those operations. The summary file is cached in memory (`flatpak_dir_lookup_cached_summary` etc) but it goes stale after five minutes.

My usecase is for the Endless OS Updater's Flatpak Installer - I need to be able to pull a bunch of flatpak refs when online, then deploy them on rebooting into the new OSTree, where the user is not guaranteed to have a network connection. Recently I have been adding a sort of "dependency resolution" support to the flatpak installer that relies on `flatpak_installation_list_remote_related_refs_sync`, `flatpak_installation_list_remote_refs_sync` and `flatpak_installation_fetch_remote_metadata_sync`. This works great online, but doesn't work offline across process invocations.

The proposed solution I have here is to simply extend the summary caching to cache the summary to disk (to, eg, dir/cache/remotename.summary-cache) with appropriate locking and mtime checking to ensure that it does not become inconsistent if two processes are using the same repository). That should be enough to handle the summary side of things. I've heard that ostree does some summary caching, though I'm not sure if we can rely on that since I need to force the use of the cache when offline. I believe @mwleeds is working on getting support for caching metadata for offline use, see https://github.com/endlessm/flatpak/pull/79

Should I go ahead with this approach? Or do it another way?

(cc @pwithnall @cosimoc)

**Comment by alexlarsson** [comment]
We already deeply rely on the existing on-disk ostree summary cache, so I don't think a second cache is right. Especially since the summary if kinda large. 

I think a straightforward way to allow use of that while offline is a good start, but here is also a general question of how to handle these kinds of remote-ls cases when offline in the context of p2p: https://github.com/flatpak/flatpak/issues/1597#issuecomment-383146103

**Comment by alexlarsson** [comment]
Also, per https://github.com/flatpak/flatpak/issues/1592#issuecomment-382637466, there are very tricky interactions between the summary and the metadata when doing dependency resolution, which needs careful thinking.

**Comment by smspillaz** [comment]
Hm okay. So I suppose what we need to do is work out why `ostree_repo_remote_fetch_summary` fails in cases where the summary file should have been cached and then fix that.

I guess as long as we can force ostree to retain its cache for as long as we need it and to always rely on the cache then this makes sense.

**Comment by smspillaz** [comment]
> If it's just related refs what I think you need is API that could be called flatpak_installation_list_local_related_refs_sync which is similar to flatpak_installation_list_installed_related_refs_sync but uses commit metadata rather than deployed metadata (or change the semantics of that API).

That's a good idea. I suspect I could have two slightly different functions in the updater which share as much code as possible but one uses the local related refs and the other uses the remote related refs. The only thing I'll need to add a special case for is runtimes but as you mention we can use `xa.metadata` for that.

I'll close this ticket for now and work on this in the updater instead.
