### ISSUE TITLE
Spelling error: "None are" should be "None is"

### ISSUE THREAD

**Issue by J-J-Chiarella** [flatpak/flatpak#1620]
In some manuals and command line displays, I see "none are."

In English it should always be "none is".

"None" is a contraction of "not one."

"None is" equates to "not one is," which is right.

"None are" equates to "not one are," which is wrong.

**Comment by J-J-Chiarella** [comment]
Muphry's Law strikes again. That should first part should be > I see "none are."

**Comment by TingPing** [comment]
"None are ..." is fine.
