### ISSUE TITLE
consider using casync instead of OSTree

### ISSUE THREAD

**Issue by eyelash** [flatpak/flatpak#1625]
Have you guys considered using [casync](https://github.com/systemd/casync/) instead of OSTree?
Some interesting quotes from the [introductory blog post](http://0pointer.net/blog/casync-a-tool-for-distributing-file-system-images.html):
> OSTree's serving of individual files is unfriendly to CDNs (as many small files in file trees cause an explosion of HTTP GET requests). To counter that OSTree supports placing pre-calculated delta images between selected revisions on the delivery servers, which means a certain amount of revision management, that leaks into the clients.

> Why is this different from rsync or OSTree, or similar tools? Well, one major difference between casync and those tools is that we remove file boundaries before chunking things up. This means that small files are lumped together with their siblings and large files are chopped into pieces, which permits us to recognize similarities in files and directories beyond file boundaries, and makes sure our chunk sizes are pretty evenly distributed, without the file boundaries affecting them.

Might this be able to solve problems like #339 or #1500?

**Comment by alexlarsson** [comment]
I am well aware of casync, but it doesn't really fit with the flatpak design, which deeply depends on the format of the local ostree repository (for cross-app deduplication, updates, etc).
