### ISSUE TITLE
flatpak does not grab the right version

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1626]
## Linux distribution and version

Fedora 27 at least.

## Flatpak version

flatpak 0.10.4

## Description of the problem

GIMP 2.10.0 is installed but flatpak thinks it to be 2.10.0~rc2.
This most likely comes from the appdata file even though the last `<release>` tag (in term of topmost order in the file, date and version number) is for 2.10.0.

```
$ flatpak search gimp
Application ID Version    Branch Remotes Description                       
org.gimp.GIMP  2.10.0~rc2 stable flathub Create images and edit photographs
```
I recently opened a report to `appstream-utils` which considers `2.10.0~rc2` to be newer than `2.10.0`. This may be linked (either maybe if flatpak uses appstream-glib, or maybe you just use a similar algorithm.
On the other hand, `rpmdev-vercmp` is right and considers `2.10.0~rc2` as being older.
See: https://github.com/hughsie/appstream-glib/issues/234

Note that I don't mind changing the version string if I am told of a standardized naming of something. Right now, there is clearly inconsistencies between tools since different tools see different order.

**Comment by TingPing** [comment]
Flatpak does use `appstream-glib` so thats the right place.

**Comment by alexlarsson** [comment]
Should be fixed by https://github.com/hughsie/appstream-glib/commit/0f9a78d8dc53cb7b918c4543c957d243bcd67c85
