### ISSUE TITLE
[regression] Can't install Epiphany with flatpak 0.11.4

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#1627]
## Linux distribution and version

Ubuntu 18.04 and 17.10.

## Flatpak version

Flatpak 0.11.4 (from the PPA and a package I'm preparing for SRU)

## Description of the problem

As part of my test plan to SRU flatpak I need to install Epiphany, however I get an error while installing (after downloading), this appears to be a regression and mwleeds on IRC has suggested that Endless has seen other packages have similar issues. (I am assuming this therefore isn't an app issue).

When trying to install I get `error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: No such file or directory` and syslog shows `Non-prefixed filename org.gnome.Epiphany.SearchProvider.service in app org.gnome.Epiphany, removing.`

## Steps to reproduce

1) Add the flathub repo
2) Try to install org.gnome.Epiphany
3) Observe that the installation fails and see the message in the syslog

```
$ flatpak install flathub org.gnome.Epiphany
Installing: org.gnome.Epiphany/x86_64/stable from flathub
[####################] 1 delta parts, 1 loose fetched; 2848 KiB transferred in 1
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: No such file or directory
$ journalctl -f
Apr 28 23:41:03 andrew-XPS-13-9360 systemd[1]: Starting flatpak system helper...
Apr 28 23:41:03 andrew-XPS-13-9360 dbus[1989]: [system] Successfully activated service 'org.freedesktop.Flatpak.SystemHelper'
Apr 28 23:41:03 andrew-XPS-13-9360 systemd[1]: Started flatpak system helper.
Apr 28 23:41:16 andrew-XPS-13-9360 dbus-daemon[2219]: Reloaded configuration
Apr 28 23:41:16 andrew-XPS-13-9360 dbus-daemon[2814]: Reloaded configuration
Apr 28 23:41:23 andrew-XPS-13-9360 flatpak[9985]: libostree pull from 'flathub' for app/org.gnome.Epiphany/x86_64/stable complete
                                                  security: GPG: summary+commit http: TLS
                                                  non-delta: meta: 2 content: 0
                                                  transfer: secs: 0 size: 1.8 kB
Apr 28 23:41:24 andrew-XPS-13-9360 flatpak[9985]: libostree pull from 'flathub' for app/org.gnome.Epiphany/x86_64/stable complete
                                                  security: GPG: summary+commit http: TLS
                                                  delta: parts: 1 loose: 1
                                                  transfer: secs: 1 size: 2.9 MB
Apr 28 23:41:26 andrew-XPS-13-9360 flatpak-system-[9893]: Non-prefixed filename org.gnome.Epiphany.SearchProvider.service in app org.gnome.Epiphany, removing.
```

**Comment by ahayzen** [comment]
Reading the release notes for 0.11.4 I wonder if `We now export .service files for names that the app is allowed to own on the session bus.` is causing the issue, as there is a service file with the name `org.gnome.Epiphany.SearchProvider.service` in the Epiphany data sources https://github.com/GNOME/epiphany/tree/master/data

**Comment by smspillaz** [comment]
Ah, thanks for fixing that @alexlarsson  - I'm afraid I only saw this one just now.
