### ISSUE TITLE
Need test-suite for libflatpak

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#163]
We currently have essentially zero testing of this. We need to test the APIs, and in particular, the threadsafety/parallel support.

**Comment by matthiasclasen** [comment]
I've started one; not covering thread-safety yet, though.

**Comment by matthiasclasen** [comment]
Before writing tests, we should write some docs that explain what level of thread-safety libflatpak is supposed to guarantee.

**Comment by matthiasclasen** [comment]
test suite and coverage testing exists now
