### ISSUE TITLE
systemd automount on any folder in / will prevent apps from starting

### ISSUE THREAD

**Issue by slaveriq** [flatpak/flatpak#1633]
## Linux distribution and version

Archlinux x86_64
4.15.14-1-ARCH

## Flatpak version

Flatpak 0.11.5

## Description of the problem

Due to full disk encryption i have my `/boot` on a seperate usb drive. I have it mounted with systemd's autofs, so that it blocks read/write calls to it when the usb drive is not present. This prevents updates writing to the `/boot` folder instead of the `/boot` mount.

When i start any flatpak'd application (tested spotify and gimp) it will hang until the USB drive is inserted.
Running flatpak run with -vv gives me this output:
```
F: bwrap args '--ro-bind /boot /boot --ro-bind /home /home --ro-bind /etc /etc --ro-bind /opt /opt --ro-bind /root /root --bind /run /run --ro-bind /srv /srv --bind /tmp /tmp --ro-bind /usr /usr --bind /var /var --ro-bind /dev /dev --ro-bind /mnt /mnt --ro-bind /proc /proc --ro-bind /sys /sys --symlink usr/bin /bin --symlink usr/lib /lib --symlink usr/lib /lib64 --symlink usr/bin /sbin --bind /run/user/1000/.dbus-proxy/ /run/user/1000/.dbus-proxy/ --file 19 /.flatpak-info'
F: Running 'bwrap --args 14 /usr/lib/flatpak-dbus-proxy --fd=18 unix:path=/run/user/1000/bus /run/user/1000/.dbus-proxy/session-bus-proxy-IG47HZ --filter --own=org.gimp.GIMP '--own=org.gimp.GIMP.*' '--talk=org.gtk.vfs.*' '--talk=org.freedesktop.portal.*' --talk=org.gtk.vfs 'unix:abstract=/tmp/dbus-Wejw7RTYFA,guid=bdec02c9d0354e8e48f11fd55acca530' /run/user/1000/.dbus-proxy/a11y-bus-proxy-NV47HZ --filter --sloppy-names '--filter=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Embed@/org/a11y/atspi/accessible/root' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Unembed@/org/a11y/atspi/accessible/root' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.Registry.GetRegisteredEvents@/org/a11y/atspi/registry' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetKeystrokeListeners@/org/a11y/atspi/registry/deviceeventcontroller' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetDeviceEventListeners@/org/a11y/atspi/registry/deviceeventcontroller' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersSync@/org/a11y/atspi/registry/deviceeventcontroller' '--filter=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersAsync@/org/a11y/atspi/registry/deviceeventcontroller''
```

after that it will just hang.
If i'm not all wrong then this "container" is used for the dbus-proxy, however i'm unsure what it would need `/boot` for.

## Steps to reproduce

Mount a usb drive with `noauto,x-systemd.automount` 

Remove the drive and make sure the mount point is still mounted with the `autofs` fs-type.
Start a flatpak

**Comment by alexlarsson** [comment]
The issue is that all the sandboxes (including the dbus-proxy one which happens to be first in this case) that have filesystem access bind mount all the toplevel directories into the sandbox, which causes this to block. I'm not sure how we can avoid automounting this though... There is a AT_NO_AUTOMOUNT flag, maybe we can use this somewhere.

**Comment by alexlarsson** [comment]
So, it hangs doing this:
```
3456704 mount("/oldroot/automountpoint", "/newroot/automountpoint", NULL, MS_BIND|MS_REC, NULL
```

Where (/oldroot)/automountpoint is a type autofs mount. I wonder if there is any way make this do a "copy" of the autofs mount instead of trying to dereference it...

**Comment by alexlarsson** [comment]
Can you try if https://github.com/flatpak/flatpak/pull/1648 fixes this?

**Comment by slaveriq** [comment]
I'm sorry for the delay i completly missed your comments.
I can confirm that your PR is fixing the issue.
