### ISSUE TITLE
Do flatpak app respect custom system wide font rendering settings?

### ISSUE THREAD

**Issue by Corsseir** [flatpak/flatpak#1647]
## Linux distribution and version
Fedora 28
## Flatpak version
0.11.3
## Description of the problem
I have a question. I'm using Fedora 28 right now and I installed a lot of apps that are flatpaks - GIMP, Spotify, Geary, Lollypop, etc. I decided to enhance a little bit font rendering in Fedora, so I have used gsettings tool that allowed me to change font "antialiasing" to "rgba" and "hinting" to "slight". Also, I have created /etc/fonts/local.conf file and put there necessary rules like lcdfilter switched to lcddefault, hintstyle switched to hintslight, etc.

I would like to know if flatpak apps are using my custom font rendering settings or rather some runtime font rendering settings?

Thank you in advance for your answer.
## Steps to reproduce
Empty

**Comment by mwleeds** [comment]
@Corsseir you could use `flatpak run --command=bash org.gimp.GIMP` followed by `gsettings get ...` to check the values from the flatpak's view of the world. Then just `exit` to exit back to the host.

**Comment by Corsseir** [comment]
Thank you for your response :)

**Comment by matthiasclasen** [comment]
if you do what mwleeds recommends, you can also look at /etc/fonts.conf inside the sandbox to see if it contains your custom settings.

**Comment by alexlarsson** [comment]
We don't currently export the host fontconfig config options to the sandbox, because they are a rats nest of complex rules that are tied to the exact version of fontconfig :/

We have on the TODO list to look into if we can do this in some way, but its not easy...

**Comment by arielnmz** [comment]
Any news on this? Is copying around my `fonts.conf` really the only solution?

**Comment by AdsonCicilioti** [comment]
Any news with this?

Dez 2020 :
![image](https://user-images.githubusercontent.com/6278398/101216789-e3b44500-365e-11eb-89b7-8f4cd27bb5ca.png)

**Comment by notklaatu** [comment]
I'm seeing similar problems with certain Flatpaks, although not all.

What are the debug steps @mwleeds is hinting at here? `gsettings get` prompts me for a schema, which should contain a key. I assume I'm looking for something related to a font path?
