### ISSUE TITLE
amd64 0.11.5-flatpak1~xenial 404 Not Found

### ISSUE THREAD

**Issue by peteruithoven** [flatpak/flatpak#1650]
## Linux distribution and version
elementary OS 0.4.1 Loki (Built on Ubuntu 16.04.3 LTS)

## Flatpak version
Flatpak 0.11.4

## Description of the problem
It doesn't seem to find Ubuntu xenial release in ppa.

## Steps to reproduce
I've got flatpak installed for a while but now I'm running into the following error when trying to run `apt upgrade`:
```
Err:1 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu xenial/main amd64 flatpak amd64 0.11.5-flatpak1~xenial
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu/pool/main/f/flatpak/flatpak_0.11.5-flatpak1~xenial_amd64.deb  404  Not Found
```

This release does seem to be listed on this page:
https://launchpad.net/%7Ealexlarsson/+archive/ubuntu/flatpak/+packages

What could be going wrong here?

**Comment by ahayzen** [comment]
Maybe you local apt cache is out of date? (As 0.11.6 is in the PPA now)

Try running the following
```
sudo apt update
sudo apt upgrade
```

Also I tend to run `sudo apt dist-upgrade` instead of `upgrade`, but make sure you understand the difference before using it :-)

**Comment by peteruithoven** [comment]
I... Don't know what's happing, but I've re-added the ppa and now it works fine. 
It has been blocking my elementaryOS AppCenter updates for a while. 
Looking forward to not having to deal with ppa's again ;)

@ahayzen thanks for your help.
