### ISSUE TITLE
~/.var should be moved to ~/.local/var

### ISSUE THREAD

**Issue by Tids** [flatpak/flatpak#1651]
According to https://github.com/flatpak/flatpak/wiki/Filesystem ~/.var is for 

> In addition to /app and /usr, each application sandbox gets a per-app data directory mounted which persists over app upgrades. It is stored as a subdirectory of the $HOME/.var/app directory (e.g. $HOME/.var/app/org.gnome.GEdit/). The $XDG_DATA_HOME, $XDG_CONFIG_HOME and $XDG_CACHE_HOME environment variables are set to point at data/, config/ and cache/ subdirectories respectively in this location.

So it's a Data directory, wich means it itself belongs to: 

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

So `~/.var` really should be moved to `$XDG_DATA_HOME/var` | `~/.local/share/var` 

On top of that it also looks wrong to have this in there and I think in the long run, this is a bit of a hold-back for flatpak.

Edit: https://github.com/flatpak/flatpak/issues/1651#issuecomment-386896758

**Comment by bogdancovaciu** [comment]
Just came by to confirm/support what @Tids was mentioning, hopefully something will be done regarding this.
Cheers!

**Comment by TingPing** [comment]
It isn't really "a data directory". It contains configs, caches, and data for all apps. I'm not sure it fits anywhere into XDG nicely. You might argue that if it is supposed to be like `/var` that it belongs in `~/.local/var`, dunno.

**Comment by Tids** [comment]
`~/.local/var` looks indeed like a much better place.

**Comment by larchunix** [comment]
Seems similar to #46 which has been rejected, so I guess it is unlikely to happen.

**Comment by soc** [comment]
Also replace "var" with "flatpak", but see https://github.com/flatpak/flatpak.github.io/issues/191.

**Comment by Tids** [comment]
@soc it would be `~/.local/var/flatpak`.

**Comment by soc** [comment]
Maybe. Tbh, they should just implement the XDG spec properly instead of trying to hide that they are violating it. :-)
I always wondered what would happen if another application started dumping stuff into `.var`.

**Comment by matthiasclasen** [comment]
There is no actual problem here.

**Comment by Tids** [comment]
For "No" problem, there are really many reports for this kind of thing.
In our company network for example we don't allow a .var directory inside users home. Because it's not part of the xdg specification. So flatpakbis not an option here. You guys really should consider to implement a switch via env var. So we can use it the way we want/need

**Comment by soc** [comment]
@Tids Agree. If you search for "XDG support" on GitHub it returns 6k results (that's a massive number, even if one removes some percentage of false positives).

I have also made my `$HOME` read-only because I'm tired of applications dumping their private data into `$HOME`. I'ts sad that an application that started as "xdg-app" is grossly violating XDG rules.

**Comment by falkTX** [comment]
Writing here to voice my opinion on this.
Really hope you can reconsider and allow to move the ~/.var dir to a more fitting place.

**Comment by alexlarsson** [comment]
The ~/.var/app location for per-application data as reached after a long discussion, including with some of the developers of the xdg basedir spec. We never got to updating the spec for this, but that will happen eventually.
