### ISSUE TITLE
org.gnome.Sdk impossible to install at version 3.26

### ISSUE THREAD

**Issue by cefn** [flatpak/flatpak#1652]
## Linux distribution and version

Lubuntu 17.10 

## Flatpak version

0.11.6
## Description of the problem

Installing org.gnome.Sdk fails.

## Steps to reproduce

Was trying to install org.gnome.Sdk before attempting a flatpak-builder version of Flowblade based on the Flowblade github repo. The first attempt to install this application ended in...

`error: org.gnome.Sdk/x86_64/3.26 not installed`

So I tried the following, which failed.

```
flatpak $ flatpak install flathub org.gnome.Sdk//3.26
Installing: org.gnome.Sdk/x86_64/3.26 from flathub
[####################] 19 delta parts, 10 loose fetched; 149067 KiB transferred 
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: While pulling runtime/org.gnome.Sdk/x86_64/3.26 from remote flathub: Couldn't find file object 'd52e7d87bd87e30773026fd2f11cd9fe78617973c84254277a5b553ccb01bfdb'
flatpak $ flatpak remotes
Name    Options
flathub system 
```

**Comment by mwleeds** [comment]
Looks like the same error message as #1581

**Comment by alexlarsson** [comment]
This was a long time ago and i've not seen anyone else with this since then. I'm assuming it was some transient network issue. Reopen if this still happens.
