### ISSUE TITLE
Is it possible to do a clean re-install of Flatpak?

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [flatpak/flatpak#1656]
I had a problem with an ocatave flatpak I tried to install and after uninstalling it using the command line I could not reinstall the stable version from Gnome software  because it still thought that flatpak was installed. So I went and downloaded the master version using the command line, not realising at the time it was the test version until it downloaded some extra run times which I didn't need. 

After uninstalling the unstable version and managing to install the stable version again from Gnome Software, I noticed that the previous flatpaks left various files and directories in different places on my system.

Is there a way to completely remove flatpak so that these redundant files and folders are removed along with it, so that I can do a clean re-installation of flatpak?

In docker its quite easy to erase the docker container and all that it brought along with it but it seems to me like flatpak makes it very difficult to uninstall flatpak apps and the flatpak container completely.

Since I have Gnome, flatpak was already installed so all I needed to do was to install flathub. In order to do a clean re-install I'm not sure if I have to remove flathub only or flatpak as well. Any thoughts? 

I'm using fedora 27 with the latest flatpak for my system (0.10.3).

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks for responding TingPing. I know how to uninstall the run time using flatpak uninstall runtime. Its actually the config files and similar files that are my concern. Isn't there a way to wipe all traces of previous flatpacks so that I can install them again as if they were new? Would using Gnome Software to uninstall the flathub repo achieve this and do I have to uninstall any flatpak apps first before attempting this GUI uninstallation?

For example before reading about flatpak in fedora magazine, I installed snap, unfortunately, and subsequently ran into problems before uninstalling it but it left behind files in my ./sys/ directory which I can't delete and in other places too.

Also, Can you tell me where flatpak and flathub stores applications, run times and related files so that atleast I can hopefully delete them manually with rm -r.

Over time, as more apps are added and updated, a scenario like this could leave hundreds of redundant files on my system so its best to be dealt with now.

**Comment by TingPing** [comment]
> Isn't there a way to wipe all traces of previous flatpacks so that I can install them again as if they were new? 

In general delete `~/.var/app/$app-id`. Some applications have write access to home and will be messy though.

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks again for the timely response TingPing, I have some questions:
1) What is $app-id? I'm guessing its the application Id number of a flatpak app, is this correct? If so how do I find this?

2) If I do rm -r ~/.var/app/$app-id, will it erase all previous information about a flatpak app or is this for deleting the flatpak software itself?

3) What do you mean "will be messy though"? If it helps, I have just three applications installed via flathub; geogebra, octave and okular. Preferrably I want to completely purge octave rather than removing flatpak from Gnome altogether. Then I can re-install it later. Would it be better to also remove flathub too?

4) Also, the master runtimes I deleted in the terminal are: org.kde.KStyle.Adwaita/x86_64/5.9, org.freedesktop.Platform.ffmpeg/x86_64/1.6, org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6. These are from the test version. After uninstalling them, are they still in my system and if so can they mess up a stable version of octave installed from Gnome Software?

**Comment by ChukwuemezieChristopherAneke** [comment]
Hi TingPing,

I'm quite happy with your suggestions and feel that I can now move on but I wanted to know one more thing. Why do you think that I should keep these three runtimes that I deleted?
- org.kde.KStyle.Adwaita/x86_64/5.9,
- org.freedesktop.Platform.ffmpeg/x86_64/1.6, 
- org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6.

After all, these runtimes were not there when I originally installed octave directly from Gnome Software.
They only appeared after I re-installed the test version of octave from the command line. Therefore I assumed they might disrupt the stable version of octave which I want to get from Gnome Software, so I uninstalled them. 

Finally, am I right in thinking that a flatpak installed using the command line e.g."flatpak install org.octave.Octave" is the nightly build (aka test version) where as those obtained from the Gnome software GUI are the stable builds?
Thanks,

**Comment by TingPing** [comment]
> Why do you think that I should keep these three runtimes that I deleted?

- org.kde.KStyle.Adwaita/x86_64/5.9,

This is just a theme, it will be useful if you ever use a Qt application.

- org.freedesktop.Platform.ffmpeg/x86_64/1.6,

This just contains codecs, it will be useful for many media applications.

- org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6.

This is a driver for your gpu, also useful for most video players.


`flatpak` will automatically install all 3 every update because they are just generally useful and honestly pretty small.
