### ISSUE TITLE
Slow install under zfs

### ISSUE THREAD

**Issue by henglinli** [flatpak/flatpak#1662]
## Linux distribution and version
Exherbo
## Flatpak version
0.11.7
## Description of the problem
When under btrfs it(0.11.4) work well, but when under zfs it take long time to extract and heard hard drive noise after download completed.
When disable zfs compression, it still take much time to extract.

**Comment by lihenglin** [comment]
@mwleeds 
try get deploy time with --no-deploy i got coredump:
[flatpak.core.log](https://github.com/flatpak/flatpak/files/1996675/flatpak.core.log)
[flapak.core.gz](https://raw.githubusercontent.com/henglinli/linux.config/master/flatpak.core.gz) 
[flatpak config.log](https://github.com/flatpak/flatpak/files/1996714/config.log)

**Comment by henglinli** [comment]
switch back to btrfs
