### ISSUE TITLE
Ubuntu 18.04 nvidia-390-48 support?

### ISSUE THREAD

**Issue by dspmathguru** [flatpak/flatpak#1663]
## Linux distribution and version
Ubuntu 18.04

## Flatpak version
Flatpak 0.11.6

## Description of the problem
Graphics driver 'nvidia-390-48' for Flatpak has not been found on your system. Please consult the documentation on graphics drivers to get help with installation.

## Steps to reproduce
I'm running Nuvola Service

**Comment by TingPing** [comment]
It is packaged... `flatpak update` should pull it in. Otherwise you can manually `flatpak install flathub org.freedesktop.Platform.GL.nvidia-390-48`

**Comment by dspmathguru** [comment]
Thanx, I guess I didn't understand how to update properly.  

flatpak update

worked fine.  Sorry for the confusion.
