### ISSUE TITLE
Changing the environment variables for all apps

### ISSUE THREAD

**Issue by lallenfrancisl** [flatpak/flatpak#1664]
I am currently running **Solus 3**. Running **Flatpak 0.10.4.**

How can I change the environment variable paths for flatpak apps. For example, my python binaries are at /home/$usr/.local/bin . And I would like this to be added to the PATH variable for Atom.

**Comment by mwleeds** [comment]
@alfranc you can use the `--env` option of `flatpak run` to set an environment variable on that instance, or the `--env` option on `flatpak override` to set the variable for every instance of the app. Atom would also need access to that part of the host filesystem (which can also be changed via `flatpak-run` and `flatpak-override`) but even then I'm not sure if what you're describing will work. Inside the flatpak sandbox `/usr` is different than on the host, so binaries won't necessarily work from inside the sandbox. Another option you have is to run a command on the host by using `flatpak-spawn`.

**Comment by alfranc** [comment]
Ok thank you @mwleeds I tried the override by adding a file in the overrides folder. But then again other errors like permission denied comes up when trying to run `flake8` (which is in /home/$username/.local/bin). I think there need to be something more done. I read something about **portals** in Flatpak documentation which I think will solve my problem. Also flatpak Atom uses the python version provided in the runtime, which is older. 

I would like to make this work, I am planning to look at it again next month(I am currently having exams and I need a working editor now). 

So please don't close this issue.

Also @mwleeds  I didn't get what to do with `flatpak-spawn`, can you please explain?

PS
I actually opened this issue to solve this [https://discuss.atom.io/t/linter-flake8-error-make-sure-installed-on-path-failed-to-spawn-command/55055](url)

**Comment by TingPing** [comment]
@alfranc You can't expect host tools to work.

`flatpak run --command=pip3 io.atom.Atom install --user flake8`

**Comment by alexlarsson** [comment]
The whole point of flatpak is for the app to run a specific known version of its dependencies. The same as the developer tested on. You can't just tell every build of every app in the world to use a different python binary instead. What if its older than needed, or not build with the same unicode string ABI?

**Comment by alfranc** [comment]
Oh right. I understand now. This is the whole idea of flatpaks, Right? But isn't this sort of a downside, not being able to use the latest versions of developer tools?

**Comment by alexlarsson** [comment]
Its one disadvantage of bundling, yes. But fundamentally if you want to guarantee that an app runs you can't run it against binaries built against a (potentially) different ABI.

flatpak-spawn can be used to run apps on the host, which sometimes can let you do what you want. On the other hand, the app have zero control of what is available on the host, so it might work or might not.

**Comment by winehub** [comment]
@alexlarsson on flatpak update only changes are commited right?
As long the desktop file isn't changed I can change the run command with  environment.
