### ISSUE TITLE
Allows unprivileged users to make system-wide changes (e.g., installation and removal)

### ISSUE THREAD

**Issue by J-J-Chiarella** [flatpak/flatpak#1669]
## Linux distribution and version

Ubuntu 18.04

## Flatpak version

0.11.7 EDIT: 0.11.6 (alexlarsson ppa) and 0.11.3-3 (ubuntu repo)

## Description of the problem

Does not ask for root permissions by prompt or by requiring sudo or su when doing system-wide changes like install and uninstall.

## Steps to reproduce

Add a new remote (e.g., flathub). Notice the pop-up asking for root privileges.

EDIT: all on command line

Install or uninstall a flatpak. Notice that there are no requirements for root privileges.

This means that unprivileged users [can] uninstall system-wide installed applications without permission. Unprivileged users should only be able to influence commands for --user. Am I missing something? I understand letting unprivileged users do upgrades, but entire installations and uninstallations seem beyond what should be allowed of ordinary users.

**Comment by mwleeds** [comment]
I think what you're seeing is `sudo` caching the credentials. See the documentation for `sudo -K` and `sudo -k`.

**Comment by J-J-Chiarella** [comment]
Thanks, but that isn't the case. I know that sudo caches the credentials for X minutes and what I'm describing happens even after resetting the computer and destroying the old desktop session.

I am talking about not even typing sudo at all. The command line has no prompt. When I type sudo and try to add or remove remotes (such as flathub) at a system-wide level, the command line asks me to type the password. When I do not type sudo and try to add or remove remotes (such as flathub) on a system-wide level, then a graphical prompt (triggered by polkit, I imagine) asks for the requisite password.

I tested this by resetting the machine, logging into the desktop and immediately performing install and uninstall at the command line, to make changes at the system-wide level. At this point I am in a fresh session (I never activate session saving) and flatpak does not prompt me for any changes.

Maybe it's something about polkit or pam or systemd in ubuntu. I do not see such behavior with any other programs at all.

I know it seems like I am ignoring sudo's cache, but I am talking about deliberately resetting the computer and starting a new session -- i.e., with no sudo cache. I have been using linux and sudo and the command line and modifying sudoer files for nearly a decade and this is the first time I have encountered this. I have worked with synaptic and gparted (which ask to run guis as root), kde programs asking for root as need be for certain actions, pkexec, gksu, kdesu, and kdesudo.

In any case, when adding or removing remotes system-wide on flatpak without typing sudo, then the graphical prompt comes up. I have seen sudo cache credentials for command-line only scenarios in that specific terminal, but not with GUI password prompts, which are not directly handled by sudo.

**Comment by J-J-Chiarella** [comment]
This problem is also the case on Ubuntu 17.10, running the repo version of flatpak. Fresh session just fired up on old laptop. Same thing. I see no reason to finger sudo as the culprit unless there is some bizarre configuration at play that does not affect other programs.

I haven't tested on other distributions, but hopefully someone here can try.

**Comment by J-J-Chiarella** [comment]
Again I tried with a reset and same results. I tried with a user who is not on the sudoers list.

This time I was stopped.

Apparently, unlike other programs, flatpak is caching the log in password or merely just checking to see if I'm on the sudoers list.

If I am letting someone jump on my computer for a second while I'm nearby, I don't bother with locking and starting up another, guest-like account or what if someone is helping me fix some sort of issue in person? It is common to use the up arrow and review recent commands. If I install and uninstall a program to test it out, that will be in recent history. One accidental strike of the enter key and the install could be initiated (which is sometimes slow). No prompt for password or asking if the user is sure (y/n?). More of an inconvenience than insecurity.

But could this be a security problem? Any program can open bash and uninstall flatpaks* without having to recall the administrator user's password (or root?....does this issue exist on systems without sudo  but with root log-in enabled?).

* An action which is quite fast and that I like 99% of the time.

**Comment by phw** [comment]
Are your users in the wheel group? Because by default Flatpak installs a polkit rule that allows wheel group members to install and uninstall apps and runtimes. The rules should be in `/usr/share/polkit-1/rules.d/org.freedesktop.Flatpak.rules`. If that doesn't match your needs you can overwrite the polkit rules with custom configuration in `/etc/polkit-1/rules.d`

**Comment by alexlarsson** [comment]
The reason for the difference is that the first operation (add a remote) implies a trust in the remote (in particular, the gpg key used to sign releases from it), this is why its later considered ok for a wheel user to install and update from it. So, *adding* trust needs authentication, but using it does not.

**Comment by alexlarsson** [comment]
Of course, this is just the default, its possible for distros/sysadmins to change this behaviour in the policykit setup.

**Comment by dmelgar** [comment]
Default policy on Debian provides a security risk. By default allows user to bypass requirement to authenticate to escalate privilege. Much safer to not have that rule and simply require the user to use `sudo` when invoking flatpak or have it prompt. Causes confusion and therefore security exposure.
