### ISSUE TITLE
electron apps do not recognize ibus

### ISSUE THREAD

**Issue by J-J-Chiarella** [flatpak/flatpak#1671]
## Linux distribution and version

Ubuntu 18.04

## Flatpak version

0.11.3 to .6

## Description of the problem

Electron apps do not recognize ibus

## Steps to reproduce

use ibus in an electron-using flatpak like Signal or Skype. Not recognized. Just uses bog standard US English layout.

others experienced this, too: https://github.com/flathub/org.signal.Signal/issues/17 but this is due to how electron is used. Rather than fixing every packaging of a flatpak or every implementation of electron, is there some way for flatpak the platform to ease the issue for electron apps?

Just thought I'd bring it to everyone's attention. I don't see it on bug reports here. At these early stages the venn diagram of flatpak users, electron app users, and ibus users is probably small. I also don't expect Microsoft to fix it if it must be fixed on a per-flatpak basis.

**Comment by J-J-Chiarella** [comment]
https://github.com/flatpak/flatpak/issues/675

i saw this but it seems separate to the electron issue

**Comment by juhp** [comment]
Atom, Slack and Skype are using org.electronjs.Electron2.BaseApp

Discord, vscode, Signal are using io.atom.electron.BaseApp

I suggest it would be good to get this fixed first in https://github.com/flathub/org.electronjs.Electron2.BaseApp if possible, so an issue should be filed there.

**Comment by juhp** [comment]
ibus seems to work in Discord for me.

**Comment by jeffshee** [comment]
> ibus seems to work in Discord (io.atom.electron.BaseApp (gtk2)) for me.

Hi, got directed to this issue, from #675. Thanks.
iBus doesn't seem working on my Discord though, is there any log files that I can provide?

**Comment by juhp** [comment]
I have: 
```
$ flatpak list -d
Ref                                                Origin  Active commit Latest commit Installed size Options       
com.discordapp.Discord/x86_64/stable               flathub 3ac6f4539e8d  -              39.9 MB       system,current
org.freedesktop.Platform/x86_64/18.08              flathub 95881b6e72a7  -             757.1 MB       system,runtime
$ rpm -q ibus flatpak
ibus-1.5.19-7.fc29.x86_64
flatpak-1.0.4-1.fc29.x86_64
```
Which ibus engine (IME or input method) are you using?

**Comment by juhp** [comment]
As noted in some other related issues sometimes `flatpak run --env=GTK_IM_MODULE=xim ...` works.

**Comment by jeffshee** [comment]
Sorry for asking but what is the status of this bug? Still waiting for the fix to be ported into Flatpak?

**Comment by fujiwarat** [comment]
I'm not sure the right category but I filed a request to update ibus in freedesktop-sdk-images now.

**Comment by fujiwarat** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/681
