### ISSUE TITLE
Create a Runtime for nvidia-396-24

### ISSUE THREAD

**Issue by robertowm** [flatpak/flatpak#1687]
I recently upgraded my NVidia drivers to 396.24. Flatpak doesn't seem to have a Runtime for this particular version thus breaking apps that depend on it.

$ cat /sys/module/nvidia/version
396.24

$ flatpak remote-ls gnome | grep nvidia-396
<nothing>

I am running Fedora 27.

**Comment by TingPing** [comment]
They are in [flathub](https://flatpak.org/setup/):
```
> flatpak remote-ls flathub | grep 396
org.freedesktop.Platform.GL.nvidia-396-24
org.freedesktop.Platform.GL32.nvidia-396-24
```
