### ISSUE TITLE
Will flatpak apps be able to bind to ports to listen for incomming connections.

### ISSUE THREAD

**Issue by Qwertie-** [flatpak/flatpak#1688]
I took a look through the wiki pages and all the docs I could find and wasn't able to work out if flatpak applications would have the ability to bind to ports. This is something that would most likely want to be sandboxed most of the time but is needed for peer to peer applications. 

Is there any existing info about this or is it not decided yet?

**Comment by alexlarsson** [comment]
There are currently only two options, no network (localhost only) or full network access.
At some point in the future it would be nice to have some option in-between, but there are technical reasons why it is not possible at the moment for an unprivileged application like flatpak.

**Comment by q2dg** [comment]
What about a Firewalld portal?
