### ISSUE TITLE
New NVIDIA runtime needed to match new Long-Lived Linux Driver Release

### ISSUE THREAD

**Issue by RogueScholar** [flatpak/flatpak#1695]
## Linux distribution and version
Kubuntu Bionic Beaver 18.04 LTS
## Flatpak version
Flatpak 0.11.7
## Description of the problem
New NVIDIA driver release to mainstream repositories has no corresponding runtime for flatpaks

Driver Release Page: http://www.nvidia.com/download/driverResults.aspx/134262/en-us
Direct Download Link: http://us.download.nvidia.com/XFree86/Linux-x86_64/390.59/NVIDIA-Linux-x86_64-390.59.run

**Comment by TingPing** [comment]
Building now: https://flathub.org/builds/#/builders/2/builds/1715
