### ISSUE TITLE
No GIMP metadata on flathub/GNOME Software

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1696]
Hi!

We have many reports that GIMP metadata does not appear in various places, when installed from flatpak: flathub (still the old data: https://flathub.org/apps/details/org.gimp.GIMP), GNOME Software, etc.

As far as we know, the appdata and desktop are processed with no error.
Also I can find both the appdata and the desktop files inside the flatpak environment: cf. https://github.com/flathub/org.gimp.GIMP/issues/8#issuecomment-389505250

I am not sure at all if the problem lies in flatpak, in the flathub process or somewhere in our manifest or metadata files. In any cases, we would appreciate some help to figure out the problem, as we have had already 2 GIMP 2.10.x releases and our software doesn't appear anywhere as "Updated App", and the description still shows old outdated information and screenshots.
Thanks!

**Comment by brittyazel** [comment]
@hughsie Any idea why this may be the case?

**Comment by eszlari** [comment]
```
$ appstream-util validate-relax /var/lib/flatpak/app/org.gimp.GIMP/current/active/files/share/appdata/org.gimp.GIMP.appdata.xml 
/var/lib/flatpak/app/org.gimp.GIMP/current/active/files/share/appdata/org.gimp.GIMP.appdata.xml: FAILED:
? tag-invalid           : <release> versions are not in order [2.10.0 before 2.10.0~rc2]
Validation of files failed
```
```
$ appstream-util validate-relax /var/lib/flatpak/app/org.gimp.GIMP/current/active/files/share/app-info/xmls/org.gimp.GIMP.xml.gz
/var/lib/flatpak/app/org.gimp.GIMP/current/active/files/share/app-info/xmls/org.gimp.GIMP.xml.gz: FAILED:
? attribute-invalid     : org.gimp.GIMP: <screenshot> width too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/112x63/org.gimp-9a006ea8c92d7eef681324078fe8d9ad.png] minimum is 300px
? attribute-invalid     : org.gimp.GIMP: <screenshot> height too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/112x63/org.gimp-9a006ea8c92d7eef681324078fe8d9ad.png] minimum is 150px
? attribute-invalid     : org.gimp.GIMP: <screenshot> width too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/224x126/org.gimp-9a006ea8c92d7eef681324078fe8d9ad.png] minimum is 300px
? attribute-invalid     : org.gimp.GIMP: <screenshot> height too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/224x126/org.gimp-9a006ea8c92d7eef681324078fe8d9ad.png] minimum is 150px
? attribute-invalid     : org.gimp.GIMP: <screenshot> width too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/112x63/org.gimp-37da35c76c5fb2ac1c6544b65f71fc7f.png] minimum is 300px
? attribute-invalid     : org.gimp.GIMP: <screenshot> height too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/112x63/org.gimp-37da35c76c5fb2ac1c6544b65f71fc7f.png] minimum is 150px
? attribute-invalid     : org.gimp.GIMP: <screenshot> width too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/224x126/org.gimp-37da35c76c5fb2ac1c6544b65f71fc7f.png] minimum is 300px
? attribute-invalid     : org.gimp.GIMP: <screenshot> height too small [https://flathub.org/repo/screenshots/org.gimp.GIMP-stable/224x126/org.gimp-37da35c76c5fb2ac1c6544b65f71fc7f.png] minimum is 150px
Validation of files failed
```

**Comment by Jehan** [comment]
Thanks @eszlari.

The first issue is a known bug of appstream-util which has been fixed in the Freedesktop runtime.
Cf. https://github.com/flatpak/freedesktop-sdk-images/pull/103

@hughsie Now maybe appstream-util has to be fixed also on every end-desktop which runs the flatpak? Do desktop validate appdata and refuse to display them if it detects an "error" such a version order?

@eszlari As for the screenshot errors (but I don't see the paste on github, only in the email I received, maybe you edited them out?), I have no idea what they are. I can definitely tell you our screenshots are more than 300x150! Check out our appdata: https://gitlab.gnome.org/GNOME/gimp/blob/master/desktop/org.gimp.GIMP.appdata.xml.in.in

No idea what these tiny thumbnails on flathub are for, but that's just scaled-down copies of the original.

**Comment by eszlari** [comment]
@Jehan Forget what I wrote, it was nonsense (that's why i delete the second part).

@alexlarsson Maybe the problem is similar to the one I had: https://github.com/flathub/flathub/issues/373

**Comment by Alexander-Wilms** [comment]
Can this be closed, since there's now [this](https://github.com/flatpak/flatpak-builder/pull/164) PR?

**Comment by Jehan** [comment]
Indeed.
