### ISSUE TITLE
--user installs broken on tmpfs $HOME due to missing xattr support

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#17]
_From @probonopd on November 28, 2015 13:16_

Trying to follow the instructions from https://wiki.gnome.org/Projects/SandboxedApps/NightlyBuilds on Fedora 23, I get:

```
xdg-app install-runtime --user gnome org.gnome.Platform 3.18
...
error: While pulling runtime/org.gnome.Platform/x86_64/3.18 from remote gnome: Operation not supported
```

_Copied from original issue: alexlarsson/xdg-app#85_

**Comment by alexlarsson** [comment]
What distro are you on, and where did you get your build of xdg-app?

**Comment by alexlarsson** [comment]
Oh, f23. So are you using the xdg-app distro package? Do you use that standard F23 kernel?

**Comment by alexlarsson** [comment]
_From @probonopd on November 29, 2015 12:3_

I am using Fedora-Live-Workstation-x86_64-23-10.iso (slightly [changed](https://github.com/haraldh/dracut/issues/104#issuecomment-158761724) to use overlayfs rather than device-mapper) loop-mounted with GRUB2 with its stock kernel. I followed ste steps from https://wiki.gnome.org/Projects/SandboxedApps/NightlyBuilds for getting xdg-app.

**Comment by alexlarsson** [comment]
Can you do something like:
```
strace -o log -f xdg-app install-runtime --user gnome org.gnome.Platform 3.18
```
And attach "log" here?

**Comment by alexlarsson** [comment]
_From @probonopd on November 29, 2015 12:20_

Lots of `EBADF (Bad file descriptor)`, might be related?
[log.txt](https://github.com/alexlarsson/xdg-app/files/46582/log.txt)

**Comment by alexlarsson** [comment]
Here is the failure:
3248  fsetxattr(14, "user.ostreemeta", "\0\0\0\0\0\0\0\0\0\0\201\244", 12, 0) = -1 EOPNOTSUPP (Operation not supported)

I guess overlayfs does not support xattrs?

**Comment by alexlarsson** [comment]
(The EBADF are just from trying to close all possible fds before execing a child process).

**Comment by alexlarsson** [comment]
If you just want to test this, you can try to install without the --user. Then you need to run it as root and it will install stuff in /var/xdg-app/, but it will not use xattrs.

**Comment by alexlarsson** [comment]
_From @probonopd on November 29, 2015 12:36_

All I could find on https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt is "On a file opened with O_RDONLY fchmod(2), fchown(2), futimesat(2) and fsetxattr(2) will fail with EROFS.".

I do not know how to test setxattr, but
```
[root@host me]# touch test
[root@host me]# strace -f setfattr -n foo -v bar test 2>&1 | grep attrexecve("/bin/setfattr", ["setfattr", "-n", "foo", "-v", "bar", "test"], [/* 35 vars */]) = 0
open("/lib64/libattr.so.1", O_RDONLY|O_CLOEXEC) = 3
setxattr("test", "foo", "bar", 3, 0)    = -1 EOPNOTSUPP (Operation not supported)
write(2, "setfattr: test: Operation not su"..., 40setfattr: test: Operation not supported
```
These are my relevant mounts:
```
/dev/sdb1 /run/initramfs/isoscan vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro 0 0
/dev/loop0 /run/initramfs/live iso9660 ro,relatime 0 0
/dev/loop6 /run/initramfs/squashfs squashfs ro,relatime 0 0
/dev/loop7 /run/sysroot ext4 ro,relatime,data=ordered 0 0
overlay / overlay rw,noatime,lowerdir=/run/sysroot,upperdir=/run/upper,workdir=/run/work 0 0
```

**Comment by alexlarsson** [comment]
_From @probonopd on November 29, 2015 12:42_

Thanks, testing without `--user` nor now, no longer getting the error, but needing no root rights is key for me.

**Comment by alexlarsson** [comment]
What is /run/upper on?
Also, could you not mount (e.g. a bind mount) ~/.local/share/xdg-app (or even ~/) directly to a ext4 directory somewhere. I.e. there is no need for the user homedir to be overlayed, no?

**Comment by alexlarsson** [comment]
_From @probonopd on November 29, 2015 16:14_

`run` is a tmpfs.

Yes, that would be doable if I wanted a persistent system (which is not my use case though).

**Comment by alexlarsson** [comment]
Yeah, tmpfs has no xattrs support unfortunately

**Comment by alexlarsson** [comment]
_From @probonopd on November 29, 2015 16:15_

That probably means that this solution is not going to work for Fedora live systems out-of-the-box then.

**Comment by alexlarsson** [comment]
Yeah, i'll think some about it.

**Comment by alexlarsson** [comment]
_From @probonopd on March 25, 2016 14:25_

@alexlarsson do you still consider making this usable for Live systems?

**Comment by alexlarsson** [comment]
It would be nice to have, but i can't really think of a good solution. Maybe one could create an ostree repo mode similar to bare-user that doesn't use xattrs, or one could look at adding xattrs to tmpfs.

**Comment by alexlarsson** [comment]
_From @hamr on April 7, 2016 12:58_

Unfortunately, I have the same problem with nfs $HOME.  Do you recommend the bind mounting workaround for people in that situation as well?

**Comment by alexlarsson** [comment]
Symlink should work too. Or, install the apps in the system repo (/var/lib/xdg-app), althought that requires you to be root to install them. The later is the long-term plan for most xdg-app installs actually. I want to add a polkit enabled helper that lets users update/install signed apps from trusted remotes.

**Comment by alexlarsson** [comment]
_From @hamr on April 7, 2016 16:20_

Cool, thanks!  That sounds like a good plan.

**Comment by vamur** [comment]
`flatpak install gnome org.gnome.Platform 3.20`

Running as root gives the same error. This makes it broken for any Live or USB based installs.

**Comment by probonopd** [comment]
Flatpak still does not work on ubuntu-gnome-17.04-beta2-desktop-amd64.iso, it is broken out of the box:

me@host:~$ flatpak install --user --from https://download.mono-project.com/repo/monodevelop.flatpakref

error: While pulling runtime/org.freedesktop.Platform/x86_64/1.4 from remote gnome: Unable to set xattr: Operation not supported

**Comment by alexlarsson** [comment]
Yeah, this is not quite there yet. However, with git master flatpak and git master ostree if you set FLATPAK_OSTREE_REPO_MODE=user-only in the environment it will work.

Over time we will make this work by default.

**Comment by probonopd** [comment]
https://blogs.gnome.org/alexl/2018/04/27/flatpak-inception/

> One interesting usecase of flatpak is as a compliment to the ideas of Fedora Atomic Workstation and similar projects. In other words, a read-only core image for the base operating system, and then using various types of containers and sandboxes for the applications on top of that.

Now it gets interesting - a _a read-only core image for the base operating system_ as in "Live ISO"? Does this mean that it works with tmpfs now?

**Comment by TingPing** [comment]
@probonopd 18.04 has an *almost* up to date `flatpak` in the main repos. Worth a try I suppose.

**Comment by probonopd** [comment]
The issue persists in the latest nightly Fedora Rawhide Live ISO as of today. GNOME Software pops an error notification about xattr, with no apparent solution (at least not from the GUI). I think this should work out of the box rather than the user having to investigate.

**Comment by muelli** [comment]
FTR: I've just tried to use `flatpak --user install flathub org.gnome.Sdk//3.26` on my NFSv4:

```
error: While pulling runtime/org.gnome.Sdk/x86_64/3.26 from remote flathub: Writing content object: fsetxattr(user.ostreemeta): Operation not supported
```

**Comment by alexlarsson** [comment]
In git master, FLATPAK_OSTREE_REPO_MODE=user-only is not needed, but this is not in a release yet, and also if you ran flatpak before you will need to start with a fresh /var/lib/flatpak and/or ~/.local/share/flatpak to get the xattr-less mode.

**Comment by probonopd** [comment]
Awaiting the day where it "just works" out of the box on a Fedora Live ISO. Trying every year or so...

**Comment by probonopd** [comment]
On an Ubuntu 18.10 Live ISO I did not see those errors anymore (but ran into [plenty of others](https://www.youtube.com/watch?v=hw0P_1uj2-Q))

**Comment by TingPing** [comment]
> On an Ubuntu 18.10 Live ISO I did not see those errors anymore (but ran into plenty of others)

That video is just a very long rant so I'll summerize:

- GNOME-Software failed to install the runtime. That is a bug to report there.
- The docs recommended restarting so apps show up in the launcher. User can do that on a live image. In theory just logging out and back in would work.
- In the end this issue was the blocker: https://github.com/flatpak/flatpak/issues/2200

**Comment by probonopd** [comment]
Thanks for your analysis @TingPing I was not sure what to report where since it felt I was just stumbling around.

**Comment by TingPing** [comment]
@probonopd 	Also the `flatpak` verison in Ubuntu 18.10 should be generally new enough. The docs are just generic to all Ubuntu versions and there isn't harm in using the latest versions.

> Where? In GS or in the GS plugin for Flatpak/Flathub?

https://gitlab.gnome.org/GNOME/gnome-software/issues

Step one is to try the very latest stable release. Step two is to run: `pkill gnome-software; gnome-software --verbose` to get some useful output.

**Comment by matthiasclasen** [comment]
> GNOME-Software failed to install the runtime. That is a bug to report there.

This should be fixed in the latest 3.30.x releases of Software.

> The docs recommended restarting so apps show up in the launcher. User can't do that on a live image. In theory just logging out and back in would work.

Not just theory. That will work

**Comment by ahayzen** [comment]
Some other comments
- you can install the one from the ubuntu repo, the one in the PPA is just slightly newer 
- the version of gnome-software in Ubuntu 18.10 is old and has issues, if it is updated to 3.30.3+ it should be better. But as you didn't restart this also caused more issues. If you install the flathub remote as a user rather than system this should help.
- using Ubuntu as a live ISO is a bit strange, why not use a distro designed to do this?
- you seem to be suffering some network issues, which is also causing your livestream to drop out

**Comment by TingPing** [comment]
> Not just theory. That will work

I just hadn't tested it. Might be a good idea to update the docs to say this just to be slightly more convenient and more technically accurate.

**Comment by TingPing** [comment]
So I think this issue, about xattrs, can be closed at this point.

As mentioned we already have #2200, GNOME-Software may have already fixed its issue, and we can open a new one to improve the restart section of the docs: https://github.com/flatpak/flatpak.github.io/issues
