### ISSUE TITLE
Create a runtime for the new Nvidia driver.

### ISSUE THREAD

**Issue by CodrinE** [flatpak/flatpak#1702]
## Linux distribution and version
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
## Flatpak version
Flatpak 0.11.7
## Description of the problem
Graphics driver 'nvidia-390-59' for Flatpak has not been found on your system. 
## Steps to reproduce
 flatpak run eu.tiliado.NuvolaAppDeezer 
Runner: [WARNING Δ232376us Nuvola] StartupWindow.vala:205: opengl-driver-message: Graphics driver 'nvidia-390-59' for Flatpak has not been found on your system. Please consult <a href="https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers">documentation on graphics drivers</a> to get help with installation.

**Comment by TingPing** [comment]
It is already there:

```
> flatpak remote-ls flathub | grep 390-59
org.freedesktop.Platform.GL.nvidia-390-59
org.freedesktop.Platform.GL32.nvidia-390-59
```

Just `flatpak update` or install manually if that fails.

**Comment by CodrinE** [comment]
that is great, thank you
