### ISSUE TITLE
Fonts not visible in LibreOffice on Silverblue

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#1710]
## Linux distribution and version
F28 Silverblue 28.20180524.0 (2018-05-24 13:43:38)

## Flatpak version
0.11.7

## Description of the problem
LibreOffice-Flatpak cannot access system-installed fonts anymore on F28 Silverblue – but that worked with LibreOffice-Flatpak on proper F27. I tried that with the Linux Libertine font. As that standard gnome-fonts program (RPM) shows me that this font is installed, I assume the bug to be due to the Flatpak abstraction.

## Steps to reproduce
- Install LibreOffice-Flatpak.
- `rpm-ostree install linux-libertine-biolinum-fonts linux-libertine-fonts`.

**Comment by matthiasclasen** [comment]
This was a regression in fontconfig, and is now fixed in runtimes.
