### ISSUE TITLE
Devuan/Debian very old version in package manager

### ISSUE THREAD

**Issue by johnny-mac** [flatpak/flatpak#1711]
## Steps to reproduce

Hi, I know you don't control the package manager for Debian/Devuan but the flatpak version in Devuan/Debian is very old & prevents me from searching or installing anything... it says I need both a ref & a remote, I don't know how I'm supposed to find this "ref".... Is there not a way to update flatpak with flatpak itself?? :/

**Comment by TingPing** [comment]
I believe it is in the backports repo?

**Comment by alexlarsson** [comment]
Yeah, newer version is in stretch-backports.
