### ISSUE TITLE
Pruning repo failed

### ISSUE THREAD

**Issue by trappedinspacetime** [flatpak/flatpak#1714]
## Linux distribution and version
Ubuntu 16.04.4
## Flatpak version
Flatpak 0.11.7 (from source)
## Description of the problem
`Pruning repo failed: No such metadata object ad1b2e7f21c9b972288edb3dee6d12769dd34b30ea3a03004139198ebcdad726.dirtree` Error
## Steps to reproduce
I had to restart computer while installing `TeXstudio`

       flatpak --user install flathub org.texstudio.TeXstudio

After  I restarted computer I reran the above command but it complained about some missing metadata files.

        Installing for user: org.texstudio.TeXstudio/i386/stable from flathub
        [####################] 1 metadata, 0 content objects fetched; 569 B transferred 
        Pruning repo failed: No such metadata object ad1b2e7f21c9b972288edb3dee6d12769dd34b30ea3a03004139198ebcdad726.dirtreeerror: While trying to checkout 9d97024b1c1b48948e68fa3b34d2ac31cc83d47f1d34935a559ae42369f84592 into /home/****/.local/share/flatpak/app/org.texstudio.TeXstudio/i386/stable/.9d97024b1c1b48948e68fa3b34d2ac31cc83d47f1d34935a559ae42369f84592-7BDLJZ: Couldn't find file object '1fe226df6890668fe131efbe6713f5e2e7f3d9c78263bb8b4ce45cfadb5e2707'

It won't install `org.texstudio.TeXstudio`

**Comment by kensully** [comment]
I don't know if the below command fixed it, 
 
           ostree --repo=$HOME/.local/share/flatpak/repo      fsck
           Validating refs...
           Enumerating objects...
           Verifying content integrity of 176 commit objects...
           fsck objects (180896/347458) [======       ]  52%
           error: fsck content object      225423dda3d3e9554b494cc8e5dd7fa52e0d2264b7bf6e41fb2f3e319c84316b: Corrupted file object; checksum expected='225423dda3d3e9554b494cc8e5dd7fa52e0d2264b7bf6e41fb2f3e319c84316b' actual='ad98a6240df55d60c44344953c57417f67328ba9ba1e4a33ed6e126bb29acc81

then I successfully installed it with

          flatpak --user install flathub org.texstudio.TeXstudio

**Comment by kensully** [comment]
#https://github.com/ostreedev/ostree/issues/959

**Comment by alexlarsson** [comment]
Hmm, not sure what is best here. We can try to ignore the prune errors, but then we will never ever remove old used objects. That doesn't seem like a good idea.

Maybe fsck is the best we can do, and we should add a "flatpak repair" wrapper to make this fixable to users.

**Comment by kensully** [comment]
A clean-up command would be neat, otherwise many dangling left-over objects pile up and occupy space.

**Comment by mwleeds** [comment]
We have a `flatpak repair` command now. Are we leaving this issue open thinking that flatpak prune operations should fsck automatically?

**Comment by matthiasclasen** [comment]
I think we can close htis
