### ISSUE TITLE
Icon cache not updated on uninstall

### ISSUE THREAD

**Issue by gnumdk** [flatpak/flatpak#1718]
## flatpak 0.11.7

If you first install an application as system, then uninstall it and install it again as user, the application icon will be broken.

When doing a flatpak uninstall, icon cache file is not updated, that's why you get an empty icon when reinstalling as user.

**Comment by alexlarsson** [comment]
It seems to work here:
```
$ strings /var/lib/flatpak/exports/share/icons/hicolor/icon-theme.cache | grep org.gnome.eog
org.gnome.eog-symbolic
<org.gnome.eog
$ flatpak uninstall org.gnome.eog
Uninstalling: org.gnome.eog/x86_64/stable from system
Uninstalling: org.gnome.eog.Locale/x86_64/stable from system
$ strings /var/lib/flatpak/exports/share/icons/hicolor/icon-theme.cache | grep org.gnome.eog
```

**Comment by gnumdk** [comment]
Ok happened here but as I do not have my command history, can't give you more information.

Closing ;)
