### ISSUE TITLE
No top menu bar

### ISSUE THREAD

**Issue by ChrisOfBristol** [flatpak/flatpak#174]
I'm only trying Flatpak to compare it with Snappy, Appimage and OBS, so I don't know much about it.
The sample applications all ran except builder and Polari, but they all had this warning message (among several others):
'Gtk-Message: Failed to load module "topmenu-gtk-module"'
and there were no menu bars at the top of the window.

I'm running them on Ubuntu 16.04 MATE.

**Comment by matthiasclasen** [comment]
This shows that the sandboxing is working to isolate the applications from the OS: you can't just inject code willy-nilly with a module.

**Comment by alexlarsson** [comment]
Yeah, this is your environment variables telling gtk+ to insert an ubuntu-specific module. That won't ever work in a sandboxed environment like flatpak.

**Comment by ChrisOfBristol** [comment]
Perhaps slightly off-topic, but: Are all these tools (Flatpak, Snappy, Appimage, OBS) running in such a way (a virtual machine?) and likely to do the same then? if so they aren't as useful to me as I had hoped.

**Comment by alexlarsson** [comment]
Those are different tools that do things differently, but yes, in generall for all of them you need your app to be custom built or to be relocatable from the start.
