### ISSUE TITLE
only one appstream entry is exported per flatpak

### ISSUE THREAD

**Issue by ramcq** [flatpak/flatpak#1749]
It looks to me like only one appdata <component> is exported from the app-provided one, because of this break:
https://github.com/flatpak/flatpak/blob/d174a6d604bf85e3def71f2641af764127666e82/common/flatpak-utils.c#L3605-L3606

It seems inconsistent with https://github.com/flatpak/flatpak/blob/master/common/flatpak-utils.c#L3576-L3587 going to the effort of allowing prefix matches. It seems the intended/desirable behaviour is to export every exactly matching component or subcomponent. Should we just delete that break?

**Comment by alexlarsson** [comment]
Yeah, since we're doing prefix matches we should allow several matches.
