### ISSUE TITLE
apt-get is unable to locate package flatpak

### ISSUE THREAD

**Issue by sasadorian** [flatpak/flatpak#175]
OS: Linux Mint 17.2 Cinnamon 64bit

Method to reproduce:
1. add-apt-repository ppa:alexlarsson/flatpak
2. apt-get update
3. apt-get install flatpak

output:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**E: Unable to locate package flatpak**

**Comment by feskyde** [comment]
PPA is not available for Ubuntu 14.04

**Comment by sasadorian** [comment]
Any idea how I can get flatpak on 14.04?
Goal is to get Pitivi. Is Pitivi even supported on 14.04?

**Comment by TingPing** [comment]
There are 14.04 builds, don't know if they are supported: https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak?field.series_filter=trusty

**Comment by sasadorian** [comment]
thanks. looks like I need a major update.

**Comment by darkoverlordofdata** [comment]
I'm getting the exact same issue with Elementary - built on Ubuntu 16.04 LTS
I'm following the steps for Ubuntu here: [http://flatpak.org/getting.html](http://flatpak.org/getting.html)

**Comment by alexlarsson** [comment]
I believe it should be possible to use the PPA on something based on 16.04, but I don't really know ubuntu well enough to say with certainty, or to figure out why it doesn't work.

**Comment by gaurikholkar** [comment]
Hi any updates on flatpak for 14.04? Having the same issue.

**Comment by conceptrat** [comment]
It looks like the Trusty builds failed https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak/+packages so they are not available when you try installing.

**Comment by lurch** [comment]
Ubuntu 14.04 LTS is still officially [supported](https://www.ubuntu.com/info/release-end-of-life) until 2019, so IMHO it would be great to see flatpak support it too, if flatpak really wants to be a "universal" packaging format.

Should I open a new issue requesting this, or is it something that'll never happen?

**Comment by conceptrat** [comment]
Give it a go. It could be that something has changed in the requirements for flatpak that now means that Trusty can't be supported.

**Comment by JLuc** [comment]
Issue is closed. Does this mean Ubuntu 14.04 LTS will never get flatpak ?

**Comment by lurch** [comment]
This issue is closed, but I've just noticed that #956 is open...
