### ISSUE TITLE
Locally custom Flatpak package without OSTree?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flatpak/flatpak#1762]
Currently Flatpak is dependent on OSTree, a system to track files by their checksum. This is beneficial for deduplication.

However Flatpak can also be treated as an optimized tool for the desktop integration of sandboxed applications. Its user-friendliness is far more better than docker if one want to run his untrusted desktop application inside a confined environment.

Now someone may want to run a beast inside it, and the beast is, for example, MATLAB. A full installation of MATLAB consists of 0.6 million files, comparatively, there are only 0.1 million files inside my `/var/lib/flatpak/repo/objects` directory. If one package his MATLAB installation as a flatpak, the OSTree repo would be overwhelmed.

Additionally, there is no necessity to distribute MATLAB as it cannot be redistributed and it cannot even be downloaded from a public URL.

It would be better if we can specify `/usr` of the host as the `/usr` directory in the sandboxed application rather than some runtime, and specify another directory as the `/app` directory instead of some files collected from the OSTree repo. Thence we can utilize the generated and auto-managed `.desktop` files as well as the fine-tuned `bwrap` profile. Thank you very much!

**Comment by alexlarsson** [comment]
It should be possible to use just bwrap to do this, but we don't want to make flatpak itself support special cases like this, it will only cause maintenance burden and not really help in the long-term goals of flatpak.
