### ISSUE TITLE
Cannot launch apps with --own-name=...

### ISSUE THREAD

**Issue by dsboger** [flatpak/flatpak#1767]
## Linux distribution and version
Arch Linux
```
$ uname -a
Linux davi-xps 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
```

## Flatpak version
$ flatpak --version
Flatpak 0.11.8

## Description of the problem
It seems like apps with `--own-name=...` are not launching (i.e. no window opens but the process does not terminate). E.g.:

```
$ flatpak run org.libreoffice.LibreOffice 
Unknown argument --none=org.libreoffice.LibreOfficeIpc0
^C
```

```
$ flatpak run work.openpaper.Paperwork 
Unknown argument --none=work.openpaper.paperwork
^C
```

## Steps to reproduce
Run an app that has `--own-name=...`.

I think it started happening after updating from 0.11.7 -> 0.11.8, but I'm not sure.

**Comment by dsboger** [comment]
Just confirmed that 0.11.7 works.

**Comment by lazka** [comment]
Same on Debian:

```
> flatpak run io.github.quodlibet.QuodLibet
Unknown argument --none=org.gnome.UPnP.MediaServer2.QuodLibet
```

**Comment by dsboger** [comment]
Ops, just saw it got fixed on master! Closing. And thanks!
