### ISSUE TITLE
Problem with locales

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#1775]
## Linux distribution and version
Fedora 28

## Flatpak version
Flatpak 0.11.7

## Description of the problem
I installed a previous version of TeXStudio via flathub.org (the current master has already fixed the following issue) and tried to compile a tex document with the lualatex provided with the flatpak Texstudio.

The compilation however failed due to some issue with the locales as within the sandboxed terminal I got the following result

```bash
sh-4.3$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

My normal terminal however gave me the following result:
```bash
[ich@localhost ~]$ locale
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

As lualatex couldn't find the locales and set them, it failed to compile the document.

So do you have any idea why didn't it could set the locales in the first place?

## Steps to reproduce
Install texstudio ( till commit 55997e9fa9cdec97f3222765491ef83502de977f ) on Fedora 28 and check to locales in the terminal that is provided by texstudio.

**Comment by Alexander-Wilms** [comment]
This is the current workaround:

```
- --env=LC_ALL=C # works around LuaLaTex issue with locale
```

**Comment by chrisawi** [comment]
Closing as stale. This seems to have been an issue where the platform locale subset wasn't being installed, which definitely works now.
