### ISSUE TITLE
Generate a build manifest for flatpak-builder

### ISSUE THREAD

**Issue by ebassi** [flatpak/flatpak#178]
One thing that Continuous does as a step towards reproducible builds is to generate a JSON manifest of the current build complete with the commit id used when building from a Git repository. This allows taking the manifest, feeding it to Continuous again, and hopefully getting the exact same result. Currently, nothing benefits from this, but it would be trivial to add a form of verification for stable builds that ensures reproducibility.

Flatpak-builder would benefit from the same mechanism, as it would make the dependencies explicit, and would allow users to verify that building a Flatpak of an application with the same JSON manifest generates the same result, regardless of cryptographic signature.

**Comment by ebassi** [comment]
Example of `build.json` from Continuous: http://build.gnome.org/continuous/buildmaster/builds/2016/07/11/10/build.json 

```
      {
        "src": "git:git://git.gnome.org/gnome-contacts",
        "config-opts": [
          "--disable-man-pages"
        ],
        "patches": [
          "gnome-contacts-builddir.patch"
        ],
        "name": "gnome-contacts",
        "branch": "master",
        "revision": "3.20.0-6-g3840be98f6abe760acf1c887c0c33da11d062b31"
      },
```

**Comment by matthiasclasen** [comment]
flatpak-builder actually does that - it puts this 'resolved' manifest into the repository.

**Comment by ebassi** [comment]
Where does it live? Would it be possible to have it exported?

**Comment by matthiasclasen** [comment]
I have both /usr/manifest.json (for the runtime) and /app/manifest.json (for the app) in this flatpak sandbox I'm looking at. Additionally writing it to some place outside the repository sounds easy.

**Comment by matthiasclasen** [comment]
In fact, I also see it in the app subdirectory of my builddir after the build is done: app/files/manifest.json

**Comment by alexlarsson** [comment]
This is also better in master, as it keeps the base layer manifest in multi-layer runtimes.
