### ISSUE TITLE
android studio: cannot download device image (out of space)

### ISSUE THREAD

**Issue by fiws** [flatpak/flatpak#1783]
## Linux distribution and version
Arch Linux

## Flatpak version
0.11.8.2

## Description of the problem

The Download fails at extracting a zip file. I have plenty of space and resized my tmp to 16GB just to be sure.

## Steps to reproduce

1. Tools -> AVD Manager -> Create new device
2. any device, next, download any image

<details>
  <summary>Log</summary>
<pre>
  To install:
- Google APIs Intel x86 Atom System Image (system-images;android-28;google_apis;x86)
Preparing "Install Google APIs Intel x86 Atom System Image (revision: 3)".
Downloading https://dl.google.com/android/repository/sys-img/google_apis/x86-28_r03.zip
An error occurred while preparing SDK package Google APIs Intel x86 Atom System Image: No space left on device.
"Install Google APIs Intel x86 Atom System Image (revision: 3)" failed.
Failed packages:
- Google APIs Intel x86 Atom System Image (system-images;android-28;google_apis;x86)
</pre>
</details>

**Comment by Alexander-Wilms** [comment]
This has been reported here: https://github.com/flathub/com.google.AndroidStudio/issues/9
