### ISSUE TITLE
Create a Runtime for nvidia-387-26

### ISSUE THREAD

**Issue by JackDeSomeTrades** [flatpak/flatpak#1785]
Flatpak doesn't seem to have a runtime for driver version 387.26. I can't change the driver versions and I can't any of my apps. 

`$ cat /sys/module/nvidia/version` 
`387.26`

`$ flatpak remote-ls| grep 387`
`org.freedesktop.Platform.GL.nvidia-387-12	flathub`
`org.freedesktop.Platform.GL.nvidia-387-22	flathub`
`org.freedesktop.Platform.GL.nvidia-387-34	flathub`
`org.freedesktop.Platform.GL32.nvidia-387-12	flathub`
`org.freedesktop.Platform.GL32.nvidia-387-22	flathub`
`org.freedesktop.Platform.GL32.nvidia-387-34	flathub`

Thank you. 

Running Ubuntu 16.04

**Comment by TingPing** [comment]
Nvidia does not host any driver for 387.26 - https://www.nvidia.com/object/linux-amd64-display-archive.html

Maybe it was a beta release? It is just unsupported and if we can't download it well you are out of luck.
