### ISSUE TITLE
org.freedesktop.Platform.GL.nvidia-396-24 is not mounted because /sys/module/nvidia/version says 396.24.02

### ISSUE THREAD

**Issue by fenryxo** [flatpak/flatpak#1786]
## Flatpak version

Flatpak 0.11.7

## Description of the problem

`org.freedesktop.Platform.GL.nvidia-396-24` is not mounted as `/usr/lib/GL/nvidia-396-24` because `/sys/module/nvidia/version` says `396.24.02` and [flatpak expects](https://github.com/flatpak/flatpak/blob/ae58744b10105df4f6d080dfb60dd2ec989f0e97/common/flatpak-utils.c#L514) the extension to be named `org.freedesktop.Platform.GL.nvidia-396-24-02`.

## Steps to reproduce

1. Get driver version: `cat /sys/module/nvidia/version` → `396.24.02`
2. Install driver extension: `flatpak install flathub org.freedesktop.Platform.GL.nvidia-396-24`
3. It is not mounted: `flatpak run --command=ls tld.domain.Whatever /usr/lib/GL` → `glvnd  OpenCL  vulkan` (`nvidia-396-24` is missing).
4. Workaround: Force GL driver and it is mounted: `FLATPAK_GL_DRIVERS=nvidia-396-24 flatpak run --command=ls tld.domain.Whatever /usr/lib/GL` → `glvnd nvidia-396-24 vulkan`

**Comment by Shished** [comment]
I tried to use the provided workaround with Steam and it does not works.
Also, glxinfo shows X error

```
$ export FLATPAK_GL_DRIVERS=nvidia-396-24 
$ flatpak run org.freedesktop.GlxInfo 
name of display: :99.0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  79
  Current serial number in output stream:  80
```

**Comment by alexlarsson** [comment]
Interestingly, my driver says:
```
cat /sys/module/nvidia/version 
396.24
```
This is nvidia-driver-396.24-1.fc28.x86_64 on fedora. What exact version of the driver says 396.24.02?

**Comment by alexlarsson** [comment]
https://developer.nvidia.com/vulkan-driver lists Linux 396.24.02 as a beta driver while  396.24 is the release one. So, these are actually two different versions.
