### ISSUE TITLE
Can I modify files in sandbox to test?

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1789]
## Linux distribution and version
Fedora 28

## Flatpak version
Flatpak 0.11.7

## Description of the problem

When testing/debugging my flatpak, sometimes the solution may simply be to modify some configuration file. I would like to test this first and don't want to make a full build (which will take hours) just to check if changing some settings in a text file somewhere fix the issue.

## Steps to reproduce

```
$ flatpak run --devel --command=bash org.gimp.GIMP//stable
$ sed 's%conf.d%/etc/fonts/conf.d%' /etc/fonts/fonts.conf >/etc/fonts/fonts.conf
bash: /etc/fonts/fonts.conf: Permission denied
```

I understand that the sandbox system is read-only and would not expect to be able to change it so easily (not asking you to change this!). But is there some write-for-developers-only hidden mode somewhere to allow me to play with files however I like? Without this, debugging these kind of file issues is quite horrible (we had the case already with the appdata manifest bug which took nearly 2 months to fix, and now I have another bug with fontconfig, and I'd like to not have to experience the same debugging pattern!).
Thanks!

**Comment by TingPing** [comment]
`flatpak run` takes the same permissions as the built packages and you can modify any and all permissions at runtime. See `man flatpak-run`

**Comment by Jehan** [comment]
Hmmm… I am reading `man flatpak-run` right now and can't see any option which would allow me to get write access on any file from the sandbox.
To be clear, I am speaking of the sandbox files (either files from the app modules under `/app/`, or even from the runtime under `/usr/`, as is the case here with fontconfig config file), not access to the main system files from within the sandbox (which would be done with `--filesystem`).

But maybe I am missing something (some of the CLI option, I am clearly not sure what they are for).
If the feature is actually there, could you give me some more

**Comment by mwleeds** [comment]
Some files visible in the sandbox are part of the app or runtime; others come from the host[[1](https://github.com/flatpak/flatpak/wiki/Sandbox)]. If you're referring to the former, there was some relevant discussion on the mailing list [here](https://lists.freedesktop.org/archives/flatpak/2018-April/001030.html).

**Comment by Jehan** [comment]
Thanks @mwleeds. I am indeed referring to former, i.e. app or runtime files.
Basically as a developer, to debug issues, I may want to tinker with app or runtime files dozen of times until I understand an issue or find the right fix (which I can then apply to the manifest at the end, but I'd like to avoid triggering development builds just to test things, and worse even pushing to the stable repo with untested fixes!).

Anyway your link is interesting. I've tried to play with files under `~/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/3.28/active/files/` but none of my changes are actually applied to flatpaks using this runtime. But it actually didn't work. My changes were not reflected in the sandbox when running the flatpak. So I am a little stumped.

In any case, thinking more about it, flatpak really needs some developer tools, allowing us to play with flatpak and runtime in some kind of "development layer" which can be resetted. Typically even if I find how to edit files in a runtime, I will end up basically breaking more than just a single flatpak. I will break all flatpaks using this runtime. That would be like editing files directly as root in my system!
And even editing files of the app is not great. I don't usually want to work by editing package files! But a sandbox being what it is, when you get specific bugs, you end up editing the package. It would be nice if we could do it in a revertable way.

**Comment by mwleeds** [comment]
@Jehan `~/.local/share/flatpak/` is the user flatpak installation whereas `/var/lib/flatpak/` is the system one (by default). So maybe you edited a runtime in the user installation and then ran an app that used the system installation? Or maybe you had a flatpak running which kept the unmodified runtime in memory? Just guessing.

**Comment by mwleeds** [comment]
By the way I believe running `flatpak repair` would restore the unmodified files.

**Comment by Jehan** [comment]
> So maybe you edited a runtime in the user installation and then ran an app that used the system installation?

No I obviously checked first and made sure there is only a single [org.gnome.platform/x86_64/3.28](https://github.com/flathub/org.gimp.GIMP/blob/master/org.gimp.GIMP.json#L5) installed and also made sure it was installed as user (I would never work in root!).

> $ flatpak list -d |grep org.gnome.Platform/x86_64/3.28org.gnome.Platform/x86_64/3.28	gnome
> 919a927d133a	-	1,3 GB	user,runtime

> Or maybe you had a flatpak running which kept the unmodified runtime in memory?

Well no, I might not be a genius, but I know the basics of software development and did not expect fontconfig to catch up with a modified file while GIMP was running (especially when I personally worked on the piece of code and know that all initialization happens once). Anyway I was not even running GIMP. :P 

> $ pwd
> /home/jehan/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/3.28/active/files/etc/fonts
> $ grep conf.d fonts.conf
> 	<include ignore_missing="yes">/usr/etc/fonts/conf.d</include>
> $ flatpak run --devel --command=bash org.gimp.GIMP//stable
> $ grep conf.d /etc/fonts/fonts.conf 
> 	<include ignore_missing="yes">conf.d</include>
> $ grep conf.d /usr/etc/fonts/fonts.conf 
> 	<include ignore_missing="yes">conf.d</include>

So anyway, I modified this file in the runtime tree, but I just don't see the change in the flatpak.
Unless by "keeping the runtime in memory", you mean there is actually a process somewhere (other than the flatpak itself since none are running) keeping the whole runtime in memory and which needs to be restarted to take file changes into account? I hope this is not the case, because restarting the session or whatever is not like a very cool development workflow. :-/

> By the way I believe running flatpak repair would restore the unmodified files.

Which version of flatpak did this command appear in? In flatpak 0.11.7, I get a `error: Unknown command 'repair'`. :-/

**Comment by mwleeds** [comment]
Flatpak 0.11.8 added the `repair` command.

**Comment by alexlarsson** [comment]
Tweaking the  files in `~/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/3.28/active/files/` *should* work fine, as long as you're using that runtime.

In your example above for instance, you're modifying org.gnome.Platform, but then running with --devel, which actually switches the runtime to org.gnome.Sdk. So, modifying `~/.local/share/flatpak/runtime/org.gnome.Sdk/x86_64/3.28/active/files/` instead should work fine.

**Comment by Jehan** [comment]
Oooh. I did not realize that. I'll try!
