### ISSUE TITLE
Flatpak App and /usr/bin/

### ISSUE THREAD

**Issue by curious-jim** [flatpak/flatpak#1792]
## Linux distribution and version

Fedora release 28 (Twenty Eight)

## Flatpak version

Flatpak 0.11.7

## Description of the problem

trying to use Flatpak version of VS Code <https://www.flathub.org/apps/details/com.visualstudio.code.oss>, but I receive a warning:

```
Cannot validate since /usr/bin/php is not a valid php executable. Use the setting 'php.validate.executablePath' to configure the PHP executable.
```

but this is a valid path, so it looks like the path is different for flatpak app or maybe app doesn't have access to /usr/bin/

what path do I need to use or how to give access to `/usr/bin/php` for this app?

**Comment by TingPing** [comment]
You can't use files from the host. The extension needs to have configurable paths and the application has to have the ability to add php. These are concerns to discuss against that package: https://github.com/flathub/com.visualstudio.code.oss
