### ISSUE TITLE
updated manually app and runtimes.

### ISSUE THREAD

**Issue by candrapersada** [flatpak/flatpak#1795]
## Linux distribution and version
Linux Mint 18.3
## Flatpak version
Flatpak 0.10.0
## Description of the problem
how to disable updated automatically vlc and use updated manually vlc?

**Comment by mwleeds** [comment]
Flatpak does not do automatic updates. However some versions of GNOME Software do; I'm not sure about the one in Linux Mint 18.3. Are you asking how to disable automatic updates?

**Comment by candrapersada** [comment]
yes for vlc and runtimes

**Comment by alexlarsson** [comment]
This is not under the control of flatpak, you need to check with gnome-software how to disable its auto-updates.

**Comment by candrapersada** [comment]
how to disable updated automatically package from flatpak not from gnome-software or from linux mint, but package from flatpak
