### ISSUE TITLE
`flatpak repo` shouldn't use remote metadata

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1805]
```
0 ✓ mwleeds@endless ~ $ flatpak repo --info /var/lib/flatpak/repo
Title: Endless Runtime and SDK
Default branch: stable
108 branches
```
Here the `flatpak repo` command is taking repo metadata from the ref `refs/remotes/eos-sdk/ostree-metadata` and presenting it as if it applies to the local repository. Flatpak should be able to distinguish between the repo metadata of a configured remote and that of the local repository.

**Comment by matthiasclasen** [comment]
I agree that we really should have a way to distinguish those ostree-metadata branches.

That being said, flatpak repo is really only meant to be used on a server-side repo, not a local one where you have configured remotes.
