### ISSUE TITLE
flatpak should be able to put a partial locale onto a USB

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1807]
```
$ ostree create-usb /run/media/mwleeds/1a9b4cb2-a7ef-4d9b-91a5-6eaf8fdd2bf6 com.endlessm.Dev.Sdk runtime/com.endlessm.apps.Platform.Locale/x86_64/4

error: Importing ae2d1542c9c858adacc0d45bf25fdcbe837b172bb268cfc878ec29f7e57c633e.dirtree: fstatat(ae/2d1542c9c858adacc0d45bf25fdcbe837b172bb268cfc878ec29f7e57c633e.dirtree): No such file or directory
$ flatpak list -a | grep Platform.Locale
com.endlessm.apps.Platform.Locale/x86_64/4	system,runtime,partial
```
Because the locale extension is partial, ostree is not able to pull it onto the USB. When I uninstalled and reinstalled `com.endlessm.apps.Platform.Locale/x86_64/4` (and ran `ostree summary -u`) I was able to put it on the USB. I think this is only now coming up because of recent bug fixes around finding related refs for P2P operations.

I think the better behavior would be for flatpak to allow you to use the locale for whatever language you have.

I'm not sure if this should be fixed at the level of ostree or flatpak (possibly as part of https://github.com/flatpak/flatpak/issues/1672).

**Comment by alexlarsson** [comment]
I think you need to extract the deployed subpaths and just pull those with --subpath

**Comment by mwleeds** [comment]
This is fixed in the `flatpak create-usb` command. As far as I know it can't be fixed for `ostree create-usb` because ostree is unaware of what subpaths to pull.
