### ISSUE TITLE
Can't open files from terminal

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [flatpak/flatpak#1812]
## Linux distribution and version
*fedora* __27__
## Flatpak version
Flatpak 0.10.3
## Description of the problem
I can't open files from terminal using Okular flatpak app.
## Steps to reproduce
1. make alias for flatpak in your bashrc or bash_aliases like this `alias okular = "org.kde.okular"`
2. try to open any file from the terminal like this `okular sample.pdf`

**Comment by barthalion** [comment]
It doesn't look nice, but when application properly supports portals, you need to make use of `--file-forwarding` like this: `flatpak run --file-forwarding org.kde.okular @@ /home/username/downloads/ticket_55773793.pdf @@`

**Comment by ChukwuemezieChristopherAneke** [comment]
thanks @barthalion  for the suggestion, but isn't there a better way to get flatpak to behave like a native binary app? Can I add that code as an alias? I can't be typing in very long commands like that every time I open a pdf.

**Comment by dsboger** [comment]
Maybe use xdg-open? It seems to work fine with Flatpak apps. It won't work if Okular is not your default app or you need to pass extra arguments, though.

**Comment by ChukwuemezieChristopherAneke** [comment]
thanks @dsboger but it's not an ideal solution. I like to open multiple files in a directory at the same time and using `xdg-open` would not only open the pdfs I want but anything else like epubs, text files etc. In other words it would not just open a pdf with okular, it will open other file extensions and their default apps as well.

Surely this was anticipated when developing flatpak and there should be a solution that lets me use okular in the terminal to open files.

**Comment by dsboger** [comment]
Yes, you can open files from command line. @barthalion showed how. You said it was too much typing, I gave you another possible solution. Then you brought up yet another new requirement :). 

Could you, please, explain your use cases thoroughly so you might get more useful answers?

**Comment by ChukwuemezieChristopherAneke** [comment]
I want to set an alias for okular so that I can type `okular <pdf_document> in the terminal and it opens a file. I also want to be able to use fuzzy opening with okular. For example, I have a directory with many pdfs, epubs, text files. I just want to open the pdfs and epubs so I do `okular .` to open all pdfs and epubs in this directory. This is very easy with native apps in Gnome for example, such as evince. That's my use case. I work mostly in the terminal so this is very necessary and I appreciate a solution.

Can I get okular to work intuitively thesame way as evince does in the terminal?

**Comment by alexlarsson** [comment]
You can grant okular full access to all files with: `flatpak override --filesystem=host org.kde.okular`. This lets you do what you want (at a small cost in security). Otherwise the other options described above can be used.

**Comment by anishmittal2020** [comment]
@alexlarsson 

> You can grant okular full access to all files with: `flatpak override --filesystem=host org.kde.okular`. This lets you do what you want (at a small cost in security). Otherwise the other options described above can be used.

@alexlarsson  What's the security issue? How does it affects users?

**Comment by felixcra** [comment]
These solutions are not really satisfying. I came across this issue because I want to open a pdf using vimtex when writing LaTeX documents with vim. A Linux app which doesn't treat the terminal as a first class citizen? Seems very Windows-ish like to me. Just my 2c.

**Comment by WalnussPower** [comment]
> @alexlarsson What's the security issue? How does it affects users?

It gives Okular (and thus potentially its developers, if it was malicious) access to your filesystem.

**Comment by aplatypus** [comment]
I have removed the flatpak.  Command line use is essential for my needs.

**Comment by MarjaE2** [comment]
I can't use okular without an environment variable to block blinking cursors. And because of this bug I can't use it with any environment variables, either.
