### ISSUE TITLE
Create and spread a place with example json files

### ISSUE THREAD

**Issue by pulb** [flatpak/flatpak#182]
Canonical members have created [Snappy playpen](https://github.com/ubuntu/snappy-playpen), a github repo with example build files for projects in various languages. It's currently shared in social media and according to the pull requests it seems to be very popular. I guess flatpak should have something similar ;-)

**Comment by matthiasclasen** [comment]
We have things like https://git.gnome.org/browse/gnome-apps-nightly/ which contains a lot of examples for packaged apps.

**Comment by pulb** [comment]
Oh, then you just need to make people aware of it :grin:

**Comment by TingPing** [comment]
Also https://github.com/flatpak/flatpak/wiki/Examples

**Comment by pulb** [comment]
What I'm trying to say is that Canonical is much more active in social media, spreading news and progress about snappy. There's already a community around it, submitting new snap build files on snappy playpen frequently.

**Comment by mwleeds** [comment]
We now have lots of example manifests on https://github.com/flathub/ which is linked to on http://docs.flatpak.org/en/latest/manifests.html
