### ISSUE TITLE
Inkscape from Flathub is older version and old Gnome runtime

### ISSUE THREAD

**Issue by skierpage** [flatpak/flatpak#1822]
Fedora 28 (KDE spin)
Flatpak 0.11.8.3

I wanted to use Inkscape, so I ran `flatpak install flathub org.inkscape.Inkscape`.
`flatpak run org.inkscape.Inkscape --version` reports
: Inkscape 0.92.2 2405546, 2018-03-11
But the latest version according to https://inkscape.org/en/release/ is 0.92.**3**.

The Inkscape in the Fedora 28 distribution is this latest version, `/usr/bin/inkscape --version` reports
: Inkscape 0.92.3 (2405546, 2018-03-11)
it's suspicious that the number and date  are the same despite different versions.

Also, Flathub's Inkscape reported 
: Required runtime for org.inkscape.Inkscape/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.24)
and prompted me to download this runtime. But I already have org.gnome.Platform/x86_64/3.**28**. I would expect a recent build of Inkscape to use the latest Gnome platform

Expected results:
Flathub should offer the latest Inkscape version built with latest Gnome.

**Comment by alexlarsson** [comment]
This is for tracking bugs in flatpak, file inkscape packaging issues in https://github.com/flathub/org.inkscape.Inkscape/issues
