### ISSUE TITLE
Steam Flatpak Gaming Performance 

### ISSUE THREAD

**Issue by dasgeekchannel** [flatpak/flatpak#1825]
## Linux distribution and version
Fedora 28 Xorg session
## Description of the problem
When using Steam flatpak and installing titles like Tomb Raider (Feral) Witcher or other high graphical games the performance from Vega 64 is 9-10 FPS. Installing Steam via RPM performance 100+ FPS. Other games were not impacted like Ballistic Overkill or CSGO. Games must be calling to a package they’re blocked from perhaps based on where Flatpak is installed?
## Steps to reproduce
Install Steam via Flatpak. Impacts Vega 56 and 64. Likely impact any AMD GPU attempting to call to libraries of any highly graphical games. 

It took me a long time to figure this out. I reinstalled Fedora and tried many other things to fix the FPS issue. Installing Steam via RPM was the only fix.

**Comment by alexlarsson** [comment]
This is likely caused by the mesa version in the runtime being different/older than the one on the host.

**Comment by TingPing** [comment]
>  Something that I would not like to do but I probably could do is to upgrade Mesa on host system.

Host libs don't matter. Anyway I doubt the drivers in fdo 18.08 are older than Fedora 28.

**Comment by Tomin1** [comment]
Yes, I was wondering why a different version of host library would a problem. I think I misunderstood alexlarsson's message.

My host system has Mesa 18.0.5 and Steam uses 18.1.6 so yes the fdo platform has a newer version than Fedora. Maybe there is a regression in this newer version of Mesa.

**Comment by jjardon** [comment]
@Tomin1 Just found this issue by coincidence; I wonder if this is still an issue? We have been pushing optimizations on the freedesktop-sdk so I'd like to know if you still see performance penalties when running flatpaks

**Comment by TingPing** [comment]
This should probably be closed anyway. Any performance issues would be runtime specific (https://gitlab.com/freedesktop-sdk/freedesktop-sdk).
