### ISSUE TITLE
Enable min-free-space-size instead of min-free-space-percent

### ISSUE THREAD

**Issue by uajain** [flatpak/flatpak#1826]
With `min-free-space-size` provided  by ostree [1], it makes sense to use it inside flatpak and decide  upon a default value maybe? This also means to avoid re-writing of `min-free-space-percent` as per : https://github.com/flatpak/flatpak/blob/master/common/flatpak-dir.c#L1950-L1961

[1] https://github.com/ostreedev/ostree/commit/31809d32f2268208a4f3e9e27b6882d39e4a75e0

**Comment by uajain** [comment]
Also, this option was added just after  2018.6 release. Not sure if @alexlarsson want's this for 1.0 , (which requires another OSTree release)

**Comment by ramcq** [comment]
My entirely made-up / arbitrary suggestion is 500MB... :)

**Comment by alexlarsson** [comment]
done now
