### ISSUE TITLE
Builder: add platform-agnostic support for dependency packages

### ISSUE THREAD

**Issue by pulb** [flatpak/flatpak#183]
Currently Snappy has a tremendous advantage over Flatpak: it supports creating .snap bundles with included dependencies pulled from .deb packages. Look at the endless dependency list of the [VLC snappy build file ](https://github.com/ubuntu/snappy-playpen/blob/master/vlc/snapcraft.yaml) for example. A developer can create a .snap bundle with many dependencies like this in a..._snap_, whereas he has to collect all dependency source tarballs and automake build settings in order to build an equivalent Flatpak bundle. Honestly, if I were an unbiased developer, I'd rather setup an Ubuntu VM and quickly build a bundle for my project with Snappy (snapcraft) before going through the hell of finding dependency sources, propper build settings and fixing compilation errors.

So I'd propose to incorporate a generic package plugin interface which can be implemented distro specific  (i.e. with backends for apt, dnf, pacman and so on).

**Comment by matthiasclasen** [comment]
See #87 which I think is a similar request. I don't think building a PackageKit-like package system abstraction is a great idea, but some support for packages as modules is certainly in scope.

**Comment by pulb** [comment]
Ah, I didn't see that one, thanks. Yes, it's similar, but please don't make it rpm-only.

**Comment by pulb** [comment]
IMHO this should be on top of the priority list - convenient features like this look like a very convincing selling point for developers currently comparing new distrubution solutions.

**Comment by alexlarsson** [comment]
You can't just take pre-existing builds and put them in flatpak and expect them to work though. Flatpak apps and bundled libraries need to be built in a special prefix, and linked against the libraries in the runtime. You can't just pick the ubuntu packages as-is (and it only works in snap because snap enforces that you use the base libraries from ubuntu core).

I.e. its not really possible to make "platform-agnostic" package support.

**Comment by pulb** [comment]
Well, it does work with packages that don't make use of a hardcoded prefix. For libs and runtimes (like Mono) that's the case very often. So launching a distros package manager (e.g. pacman -S mylib --root ~/builder/myapp/libs ...), adding /app/libs to LD_LIBRARY_PATH and just building the app itself with the /app prefix should be sufficient in many cases.

**Comment by alexlarsson** [comment]
Yes, this is how the rpm support referenced to above is meant to work. I.e. its for specialized rpms, and will not just work with any random, non-relocatable package.

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#8
