### ISSUE TITLE
Allow applications to run in the background in a restricted manner

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#184]
A lot of operating systems allow apps to run in the background, almost as a service. Applications that have this ability are able to automatically launch on boot and run without a window being visible. They are also typically allowed to show notifications.

At the same time, apps running in the background typically have restrictions placed on them, including:
- The amount of system resources they can use.
- Their ability to draw on the screen or play audio.
- Their ability to open windows.

Apps that are running in this way need to be flagged as such and a mechanism for stopping them needs to be provided. It might also be desirable to require applications to ask for permission to run in the background.

This kind of functionality allows some highly desirable behaviours. It allows "always on" apps, such as messaging services that are always available to alert the user of new messages, or sync clients that constantly work in the background to keep content up to date.

**Comment by TingPing** [comment]
Just to update an old issue initial work has been done here: https://github.com/flatpak/flatpak/pull/2681
