### ISSUE TITLE
Accesing share data for other apps

### ISSUE THREAD

**Issue by albfan** [flatpak/flatpak#1846]
## Description of the problem:

I run glade inside flatpak and gitg inside flatpak too. 

glade has the ability to find graphic objects from other libraries from catalogs (gitg has one gitg-glade.xml to discover ui objects into libgitg-1.0.so) 

As both apps are sandboxed I cannot access that file nor its library, so glade do not allow me to hack on its files. 

Is there any mechanishm to allow one flatpak app to access other flatpak app files? or any way (maybe extension) to deploy those objects to be read by others? or.gnome.Gitg.Catalog or similar. It needs to publish library and catalog

## Steps to reproduce

Clone this repo (as gitg catalog is broken)

    git clone https://gitlab.gnome.org/albfan/gitg/tree/catalog
    GLADE_CATALOG_SEARCH_PATH=$PWD/data glade libgitg/resources/ui/gitg-diff-view-file.ui

You should see:

![captura de pantalla de 2018-06-30 15-04-22](https://user-images.githubusercontent.com/220968/42125418-e4df807e-7c76-11e8-8893-b1a6e7f8a8d7.png)

but with flatpak (see here I try to access to a file on host not on flatpak gitg

GLADE_CATALOG_SEARCH_PATH=$PWD/data flatpak run org.gnome.Glade libgitg/resources/ui/gitg-diff-view-file.ui 

![captura de pantalla de 2018-06-30 15-06-41](https://user-images.githubusercontent.com/220968/42125449-4dedf80c-7c77-11e8-8e5f-86556f0a92ab.png)

Really don't know if this breaks the hole idea of flatpak, but I can think in several other applications for this: expose Documentation for a flatpak app. dbus docs for an app so you read it and hack on its api. Use case: Developing Builder from Builder, learn how to call Boxes from Builder as emulator

**Comment by matthiasclasen** [comment]
this can't work.

**Comment by albfan** [comment]
I think so

**Comment by bam80** [comment]
Don't know if https://github.com/flatpak/flatpak/issues/2303 related
