### ISSUE TITLE
404 error when installing org.freedesktop.Platform.ffmpeg/x86_64/1.6

### ISSUE THREAD

**Issue by piotr-szegda** [flatpak/flatpak#1852]
## Linux distribution and version
Arch Linux
## Flatpak version
Flatpak 0.99.2
## Description of the problem
I am not sure is flatpak or flathub problem. In my opinion If it was a problem only with the flathub, it would affect a large number of people. When I trying to install flathub net.fsuae.FS-UAE for example I getting 404 error.
```
[pszegda@archlinux ~]$  flatpak install flathub net.fsuae.FS-UAE -v
F: Opening system flatpak installation at path /var/lib/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Fetching summary file for remote ?flathub?
F: Fetching summary file for remote ?flathub?
F: Transaction: install flathub:app/net.fsuae.FS-UAE/x86_64/stable[*]
F: Updating remote metadata for flathub
F: marking op install:app/net.fsuae.FS-UAE/x86_64/stable resolved to 5795ad52143a456bd5cf56b900896f95e387124737b4da4ed573fba3ed6dc3dd
F: Updating dependent runtime runtime/org.freedesktop.Platform/x86_64/1.6
F: Transaction: update gnome:runtime/org.freedesktop.Platform/x86_64/1.6[$old]
F: Fetching summary file for remote ?gnome?
F: marking op update:runtime/org.freedesktop.Platform/x86_64/1.6 resolved to ea1a12e21086ec56bba0c83a6e97511109cb300cc9deb2dbb1e1e3e68d91aa65
F: Transaction: install/update gnome:runtime/org.freedesktop.Platform.GL.default/x86_64/1.6[*]
F: Transaction: install/update gnome:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6[*]
F: Transaction: install/update gnome:runtime/org.freedesktop.Platform.Locale/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/net.fsuae.FS_UAE.Locale/x86_64/stable[*]
F: marking op install/update:runtime/net.fsuae.FS_UAE.Locale/x86_64/stable resolved to 9eb7db9aa2e8b49003d6818789d08e4ee2b63992c394f4d096421b344e623285
F: marking op install/update:runtime/org.freedesktop.Platform.Locale/x86_64/1.6 resolved to 5bc67811966ffa596f9a9ec4626399be099e947fcbb6eb39672c69657e8f6148
F: marking op install/update:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6 resolved to e01955d7feef8da4c84894043176f2963cbf7ebc50c39baa13bde10791276fe1
F: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/1.6 resolved to fefd42de91fd4d688febbb100895990a3dae272ec379adaf30dff10d8e08345f
Installing in system:
net.fsuae.FS-UAE/x86_64/stable        flathub 5795ad52143a
  permissions: ipc, pulseaudio, x11, devices
  file access: home
net.fsuae.FS_UAE.Locale/x86_64/stable flathub 9eb7db9aa2e8
Updating in system:
org.freedesktop.Platform.ffmpeg/x86_64/1.6 flathub e01955d7feef
Is this ok [y/n]: y
Updating: org.freedesktop.Platform.ffmpeg/x86_64/1.6 from flathub
error: Failed to update org.freedesktop.Platform.ffmpeg/x86_64/1.6: Server returned status 404: Not Found
```

## Steps to reproduce
flatpak install flathub net.fsuae.FS-UAE

**Comment by Mikaela** [comment]
I am also seeing this with other packages such as `org.audacityteam.Audacity`, `org.mozilla.Thunderbird`, `org.signal.Signal`

Also `com.github.rssguard` gives a different 404 not found, should I report it separately?

```
Updating: org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4 from gnome
error: Failed to update org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4: Server returned status 404: Not Found
```

Ubuntu 18.04 LTS, Flatpak 0.99.3

```
# flatpak remote-list
Name                    Options
bochecha                system 
flathub                 system 
gnome                   system 
org.mozilla.FirefoxRepo system 
```

I am guessing that this is caused by the remote gnome having older version of these depedencies than gnome which confuses it? I cannot figure out how to move these flatpaks from gnome to flathub on my system.

**Comment by Mikaela** [comment]
> I am guessing that this is caused by the remote gnome having older version of these depedencies than gnome which confuses it?

Something like this fixed the issues for me as I fixed it by running `flatpak remote-delete gnome` and `flatpak install --reinstall flathub <whatever-prevented-remote-gnome-being-removed>` (thanks #flathub :smile:) until the first command was successful and then I was able to install all flatpaks that I listed above.

**Comment by piotr-szegda** [comment]
@Mikaela: In my case it's solve problem but only for same time.

**Comment by alexlarsson** [comment]
Is this still happening?

Note: I recommend not using the gnome remote. All the non-nightly gnome remotes are deprecated and the apps/runtimes are available on flathub.

**Comment by bdaase** [comment]
@alexlarsson Yeah, this is still happening. I am unable to update QTCreator today (tried it 6 times), always looks like this

```
➜  ~ flatpak update
Looking for updates…


        ID                      Branch         Op         Remote          Download
 1. [✗] io.qt.QtCreator         stable         u          flathub         236,0 MB / 6,3 GB

Error: While pulling app/io.qt.QtCreator/x86_64/stable from remote flathub: Server returned HTTP 404
Updates complete.
error: There were one or more errors
```

This is with flatpak 1.12.5.

**Comment by smcv** [comment]
@bdaase: I would recommend opening a new issue with full details (using `flatpak -v` or `flatpak -vv` might help to get more information about exactly what is failing). You are getting the same symptom as the original reporter of this issue, but that doesn't mean you are getting it for the same reason.

A 404 error here could be either a problem with Flatpak (downloading the wrong thing), or with the Flathub server (not actually providing everything that it lists as available). It isn't possible to tell which this is without more information.

**Comment by bdaase** [comment]
@smcv I actually just asked on IRC. The solution is to run `flatpak update --no-static-deltas`. It is an infrastructure problem and also occurs with org.kde.Sdk.Debug.

**Comment by DeedleFake** [comment]
Just had this same problem with `org.flightgear.FlightGear`. I'm adding this comment so that it'll hopefully show up in the Google search results a bit easier for people in the future.
