### ISSUE TITLE
Need flatpak_transaction_add_install_ref()

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#1853]
## Description of the problem

I'm porting gnome-software to use FlatpakTransaction -- not having `flatpak_transaction_add_install_ref()` means that I'm still duplicating a ton of code for things like checking if a remote exists in either scope, installing that first, then installing the app -- which means two transactions and a whole lot of wiring -- and a lot that can go wrong.

I think flatpak_transaction_add_install_ref() would be fairly easy to export, although might need another TransactionOperation or something more clever. It would certainly reduce the complexity in the gnome-software plugin by a huge amount. Thanks!

**Comment by alexlarsson** [comment]
This should be in now (flatpak_transaction_add_install_flatpakref)
