### ISSUE TITLE
command-line flag to skip yes/no questions?

### ISSUE THREAD

**Issue by orschiro** [flatpak/flatpak#1857]
When running `flatpak update`, I am prompted with: 

```
Looking for updates...
Updating in system:
org.gimp.GIMP/x86_64/stable flathub c8ed359f555e
Is this ok [y/n]: 
```

Is it possible to add a command-line flag to assume a yes or a no by default without user intervention?

That would be great!

**Comment by mwleeds** [comment]
This already exists. It's `-y` or `--assumeyes`

**Comment by orschiro** [comment]
I can confirm that using "--assumeyes" doesn't make the upgrade process
autonomously performed. I still need to press return.

**Comment by xgdgsc** [comment]
Is it  possible to make it default to "Y" when I' m prompted with "Found in remote flathub, do you want to install it? [y/n]" , so that I can press enter to confirm, instead of typing y? It isn' t a dangerous or license operation after all.

**Comment by orschiro** [comment]
Can assumeyes be permanently stored in a config file?

**Comment by mwleeds** [comment]
> Can assumeyes be permanently stored in a config file?

Not currently. You could file a separate issue about that if you want.

**Comment by aaronfranke** [comment]
Why isn't `-y` documented anywhere? It's not in `flatpak --help` and it's not in `man flatpak`.
