### ISSUE TITLE
flatpak breaks the assumption that no two processes can have the same pid while running

### ISSUE THREAD

**Issue by cmollekopf** [flatpak/flatpak#1859]
## Linux distribution and version
All

## Flatpak version
All

## Description of the problem
flatpak breaks the assumption that no two processes can have the same pid while running,
Point in case: https://phabricator.kde.org/T8063
The problem is that the files are shared but the pid-space is not.

This is perhaps rather a documentation issue than something that can be solved.
Another approach would be to allow a flatpak to specify that only a single instance can ever run.
Or of course, don't break the assumption, but I doubt that's feasible.

Don't know if this is an issue that affects other applications, but it's something to be aware of.

**Comment by matthiasclasen** [comment]
ever since the appearance of pid namespaces in the kernel, that is not a valid assumption anymore
