### ISSUE TITLE
`flatpak info --show-metadata` doesn't show overrides

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#1861]
## Linux distribution and version
Fedora 28

## Flatpak version
flatpak-0.99.2-1.fc28.x86_64

## Description of the problem

When using `flatpak info --show-metadata`, we can see most there is to know about an application, in a few sections like "Application", "Context", "Extension …", etc…

This doesn't show the overrides though, which would be very useful.

For example:

```
$ sudo flatpak override --nodevice=all org.musicbrainz.Picard 
$ flatpak info --show-metadata org.musicbrainz.Picard 
[Application]
name=org.musicbrainz.Picard
runtime=org.freedesktop.Platform/x86_64/1.6
sdk=org.freedesktop.Sdk/x86_64/1.6
command=picard

[Context]
shared=network;ipc;
sockets=x11;
devices=all;
filesystems=home;xdg-music;

[Session Bus Policy]
org.gnome.GConf=talk

[Extension org.musicbrainz.Picard.Locale]
directory=share/runtime/locale
autodelete=true
locale-subset=true

[Extension org.musicbrainz.Picard.Debug]
directory=lib/debug
autodelete=true
no-autodownload=true

[Build]
built-extensions=org.musicbrainz.Picard.Locale;org.musicbrainz.Picard.Debug;org.musicbrainz.Picard.Sources;
```

The overrides are missing, which made me think they hadn't been added. I verified running the app that it didn't have access to all of `/dev` any more, so the override did work, which left me puzzled.

I later found `flatpak info --show-permissions` which shows the "resolved" permissions, that is the ones from the `finish-args` modified by the overrides.

But that's not the same thing as showing both the `finish-args` permissions as well as the overrides, separately.

Something like the following would be nice:

```

$ flatpak info --show-metadata org.musicbrainz.Picard 
[Application]
name=org.musicbrainz.Picard
runtime=org.freedesktop.Platform/x86_64/1.6
sdk=org.freedesktop.Sdk/x86_64/1.6
command=picard

[Context]
shared=network;ipc;
sockets=x11;
devices=all;
filesystems=home;xdg-music;

[Context Overrides]
devices=!all;

[Session Bus Policy]
org.gnome.GConf=talk

[Extension org.musicbrainz.Picard.Locale]
directory=share/runtime/locale
autodelete=true
locale-subset=true

[Extension org.musicbrainz.Picard.Debug]
directory=lib/debug
autodelete=true
no-autodownload=true

[Build]
built-extensions=org.musicbrainz.Picard.Locale;org.musicbrainz.Picard.Debug;org.musicbrainz.Picard.Sources;
```

**Comment by mwleeds** [comment]
The problem with doing this is that metadata in this case has a very specific meaning. It's the contents of e.g. `/var/lib/flatpak/app/APP_ID/current/active/metadata`. So it wouldn't make sense to add sections that aren't part of that app metadata that gets generated by the build.

**Comment by bochecha** [comment]
It's entirely unclear to a casual user that this is what it is supposed to do. It wasn't clear at all to me, even though I knew about the `metadata` file and its contents.

At the very least, the help message for `flatpak info` should be improved:

```
$ flatpak info --help
Usage:
  flatpak info [OPTION…] NAME [BRANCH] - Get info about an installed app or runtime

Help Options:
  -h, --help                 Show help options

Application Options:
  …
  -m, --show-metadata        Show metadata
  …
```

In addition, limiting the CLI output to the contents of that file generated really doesn't seem very useful. Users rarely want to know about the defaults, but instead they want to know about the current configuration, or even better, how their current configuration changes the defaults.

If you really feel that doesn't have its place in `--show-metadata`, could it go in another option?

**Comment by kbjoon79** [comment]
I agree with you.

I installed the app using the "install --system" option and overrides the app for individual users using the "overrides --user" option.
This is inconvenient because you need to check the individual configuration files under the directory "~ /.local/ share/ flatpak/overrides/" to check the overrides setting of ordinary users.
I would like to be able to check the settings of system, global, app_id using additional options.
-- Used Google Google Translate (Sorry, I did not speak English properly, so I used a translator.)

korean:
저도 의견에 동의 합니다.

저는 "install --system" 옵션을 사용하여 app을 설치하고 "overrides --user" 옵션을 사용해서 개별 사용자에 대해서 app의 overrides 설정을 했습니다.
이 경우 일반 사용자의 overrides 설정을 확인하기위해 "~/.local/share/flatpak/overrides/" 아래 디렉토리 아래에 있는 개별 설정 파일을 별도로 확인하여야 하기때문에 불편합니다.
추가적인 옵션을 사용해서 system, global, app_id 의 설정 내용을 확인할 수 있으면 좋을 것 같습니다.

**Comment by Erick555** [comment]
There are: `flatpak info -M` and `flatpak info --show-permissions` equivalent options now. This is fixed.

**Comment by bochecha** [comment]
@Erick555 that's not really the same though.

`--show-permissions` shows the current permissions for the app, with the overrides taken into account.

What I was asking for is something that shows both the default permissions and the overrides that are applied on top.
