### ISSUE TITLE
Add a way to disable checking LAN/USB sources

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1863]
For privacy and performance reasons, some people might want to disable checking for refs on the LAN. But we still want everyone to use collection IDs eventually, so we might want a new repo config option.

**Comment by mwleeds** [comment]
There's probably a security argument to be made for this too, with e.g. https://github.com/ostreedev/ostree/issues/1527

**Comment by pwithnall** [comment]
Sounds good to me. I’d like to see this enabled by default, but I can see why people might have privacy concerns about it*. I suggest the way to do this would be to add a ‘enabled repo finders’ option to the OSTree repo config, in libostree. Looks like the code in `common/flatpak-installation.c` which instantiates some `OstreeRepoFinder` instances would need to pay attention to this config option too.

* The way that P2P ref resolution works means that when you’re looking for a specific ref (say, `app/my-super-secret-app`), the `OstreeRepoFinderAvahi` will grab the latest bloom filter from every peer on the LAN, without actually mentioning which refs it’s looking for. It’s only in the case of a bloom filter match that `OstreeRepoFinderAvahi` will make a HTTP request to the matching peer to get the checksum for that ref by name. So the privacy issue is not immediate, but an attacker could fairly easily publish an all-ones bloom filter (which matches every ref name) to snoop for update requests. So there is definitely an issue.

**Comment by mwleeds** [comment]
>an attacker could fairly easily publish an all-ones bloom filter (which matches every ref name) to snoop for update requests

I think the attacker would have to also publish a summary with every ref the victim might have.

**Comment by pwithnall** [comment]
True, but also quite possible. If you’re doing a targeted attack to work out who has (say) a particular vulnerable application installed, for example.
