### ISSUE TITLE
Is a Flatpak Maven plugin planned?

### ISSUE THREAD

**Issue by Sami32** [flatpak/flatpak#1869]
Sorry if you consider this question as out of topic, but i was wondering if a such Flatpak plugin was planned because i just discovered the [Snap](https://github.com/buggtb/snappy-maven-plugin) one.
It will be great to be able to build it from Maven or Gradle IMO.

Congratulation for your good work and effort to make Flatpak a great package👍 

Regards

**Comment by barthalion** [comment]
Unlikely to be part of flatpak project/roadmap. We'll be happy to accept maven/gradle generator for [flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools) though.

**Comment by Sami32** [comment]
Thank you for having took the time to answer +1
