### ISSUE TITLE
Error installing 'don't take it personally, babe, it just ain't your story' in Linux Mint 19

### ISSUE THREAD

**Issue by Mister-Dolus** [flatpak/flatpak#1876]
## Simply try to install the game with the GUI package manager

The error is as follows 'Error finding runtimes for flatpak: No entry for app/com.scoutshonour.dtipbijays/x86_64/stable in remote summary flatpak cache"

Included a cropped screenshot: 
![screenshot at 2018-07-09 21-18-13](https://user-images.githubusercontent.com/22648132/42486223-9302583e-83c0-11e8-976c-1279c30fd307.jpg)

**Comment by Mister-Dolus** [comment]
Oddly, there is an entry for the app in the menu, but it doesn't work. Installing and launching from the CLI do though.

**Comment by alexlarsson** [comment]
Does this still happen? It sounds like a transient network issue to me.
