### ISSUE TITLE
How do you set up icons for flatpak?

### ISSUE THREAD

**Issue by Pshemas** [flatpak/flatpak#1889]
## Flatpak version: 0.10.4

it's not exactly bug, but I wonder how do I set up icons that would work with Flatpak?
It is not picking system icons so I wonder how can I tweak Flatpak app so it would match system theme.

Another icon related - how do I set tray icons. I'm using Steam Flatpak from Flathub. Apart from low res and not matching the theme regular icon it it missing the tray one (I'm using Xfce). Any suggestions how can I fix it? And how should I go about identifying which file I should copy (if it is as simple as copying correct file to correct place).

**Comment by TingPing** [comment]
Nothing is different from normal applications. You are probably just using the wrong icon name as some applications were renamed to fit into an app-id format. So `foo` might be `org.example.Foo` now.

**Comment by alexlarsson** [comment]
App icons have to match the app id to be properly exported and thus available to the desktop for showing. You can use the rename-icon feature of flatpak-builder to do this (although the recommended approach is to rename the icons upstream if possible).

**Comment by Pshemas** [comment]
it seems that one of the recent updates to Steam flatpak fixed the issue - THANK YOU to all involved.
