### ISSUE TITLE
flatpak 0.99.3 fails to build on rawhide

### ISSUE THREAD

**Issue by kalev** [flatpak/flatpak#1890]
```
In file included from ./libglnx/glnx-missing.h:95,
                 from ./libglnx/libglnx.h:28,
                 from common/flatpak-dir-private.h:26,
                 from common/flatpak-transaction-private.h:26,
                 from common/flatpak-transaction.c:27:
./libglnx/glnx-missing-syscall.h:66:19: error: static declaration of 'renameat2' follows non-static declaration
 static inline int renameat2(int oldfd, const char *oldname, int newfd, const char *newname, unsigned flags) {
                   ^~~~~~~~~
In file included from common/flatpak-transaction.c:23:
/usr/include/stdio.h:164:12: note: previous declaration of 'renameat2' was here
 extern int renameat2 (int __oldfd, const char *__old, int __newfd,
            ^~~~~~~~~
make[2]: *** [Makefile:2594: common/libflatpak_common_la-flatpak-transaction.lo] Error 1
```

Full build logs at https://koji.fedoraproject.org/koji/taskinfo?taskID=28112147

**Comment by kalev** [comment]
Same issue with flatpak-builder: https://github.com/flatpak/flatpak-builder/issues/182

**Comment by alexlarsson** [comment]
@cgwalters Have you seen this in ostree?

**Comment by cgwalters** [comment]
No, but it might be a variant of https://gitlab.gnome.org/GNOME/libglnx/commit/03e16afa7f2cf7ce517b604035683fa0409f730c - did glibc add renameat2?

**Comment by cgwalters** [comment]
A few seconds with `git log --grep renameat2` later... https://sourceware.org/git/?p=glibc.git;a=commit;h=d6da5cb6a8e0e8a9ce92b7d951a254cf325248d7

**Comment by cgwalters** [comment]
I'll look at a fix.

**Comment by alexlarsson** [comment]
libglnx.m4 has:
```
AC_CHECK_DECLS([
        renameat2,
        memfd_create,
        copy_file_range],
        [], [], [[
#include <sys/types.h>
#include <unistd.h>
#include <sys/mount.h>
#include <fcntl.h>
#include <sched.h>
#include <linux/loop.h>
#include <linux/random.h>
#include <sys/mman.h>
]])
```
But that does not include /usr/include/stdio.h which gcc says defines it. 
@kalev Can you try adding that to the list of headers in that macro?

**Comment by cgwalters** [comment]
https://gitlab.gnome.org/GNOME/libglnx/merge_requests/2

**Comment by cgwalters** [comment]
I tested :arrow_up: by updating my rawhide container btw, was trivial to do with my heavily containerized development flow...I recommend it :wink:

**Comment by kalev** [comment]
Great, thanks Colin!
