### ISSUE TITLE
flatpak_transaction_ensure_remote_state() leaks memory

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#1895]
The `flatpak_transaction_ensure_remote_state()` function leaks memory. In some places it's returning a `FlatpakRemoteState` which is "owned" by the `GHashTable` `priv->remote_states`, and in one place its returning a `FlatpakRemoteState` that needs to be freed (if `transaction_is_local_only()`) is true. This means we leak tons of memory; in the GNOME Software self tests we're leaking 6kb every time we use FlatpakTransaction, which certainly adds up when it's a process like `gnome-software` that stays alive for the duration of the session, which may be many hundreds of transactions per week.

I'm not immediately sure how to fix this. Perhaps a per-transaction `GHashTable *remote_states_local` that holds the ownership for all local `FlatpakRemoteState`s?

**Comment by alexlarsson** [comment]
This is fixed now.
