### ISSUE TITLE
Glib crashes when registering a `SIGWINCH` signal in Flatpak container, but is working outside.

### ISSUE THREAD

**Issue by goffi-contrib** [flatpak/flatpak#1899]
## Linux distribution and version
Arch Linux 4.17.4-1-ARCH

## Flatpak version
Flatpak 0.99.2

## Description of the problem
Hello,

I'm doing several manifests for Salut à Toi and its frontends (<https://salut-a-toi.org>), and one on the frontend is TUI and uses Urwid (<https://urwid.org>).
On startup, Urwid is crashing while trying to initiate Glib event loop, while registering the `SIGWINCH` signal (needed to detect terminal size change).

It's working normally outside of Flatpak, and if I patch Urwid to not register this signal, it's starting normally (but it obviously can't detect terminal size change anymore). The problem is only happening with `SIGWINCH` signal, there is no crash with `SIGHUP`, `SIGINT`, `SIGTERM`, `SIGUSR1` or `SIGUSR2`

## Steps to reproduce
I'm joining here 2 files and a manifest to reproduce the issue.
The test is passing when you see this line: `if this line is displayed, the test passed`

The archive is available here: [org.flatpak.SigwinchTest.tar.gz](https://github.com/flatpak/flatpak/files/2193524/org.flatpak.SigwinchTest.tar.gz).

To reproduce:

```sh
tar zxf org.flatpak.SigwinchTest.tar.gz
cd org.flatpak.SigwinchTest
flatpak-builder build-dir org.flatpak.SigwinchTest.json --force-clean
flatpak-builder --run build-dir org.flatpak.SigwinchTest.json sigwinch_test.py
```

here is the expected result (if it were working):

```
this line is printed before the test
if this line is displayed, the test passed
```

here is the actual result (crash when registering the signal):
```
this line is printed before the test
/app/bin/sigwinch_test.py:7: Warning: g_unix_signal_source_new: assertion 'signum == SIGHUP || signum == SIGINT || signum == SIGTERM || signum == SIGUSR1 || signum == SIGUSR2' failed
  GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, signal.SIGWINCH, lambda args: None, signal.SIGWINCH)
/app/bin/sigwinch_test.py:7: Warning: g_source_set_callback: assertion 'source != NULL' failed
  GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, signal.SIGWINCH, lambda args: None, signal.SIGWINCH)
```

Thanks!

**Comment by goffi-contrib** [comment]
It seems that this issue is due to a outdated Glib version, according to https://github.com/GNOME/glib/blob/master/glib/glib-unix.c  `SIGWINCH` has been added in GLib 2.54, while it seems that the `org.freedesktop.Platform` runtime has a 2.0 version.
I'm not sure where I should request an update then.

**Comment by alexlarsson** [comment]
org.freedesktop.Platform is ABI stable and will not update the glib in-release. However, a new major version of it is planned soon. Alternatively you can use a gnome runtime that has a later glib, or bundle the release of glib that you need.

**Comment by goffi-contrib** [comment]
@alexlarsson thanks for feedback. I've worked around the issue by patching my Urwid instance, it seems to work and should be good enough until new org.freedesktop.platform release is out.
Thanks, I'm closing this ticket.
