### ISSUE TITLE
flatpak-builder hangs if the folder does not exist

### ISSUE THREAD

**Issue by aleb** [flatpak/flatpak#190]
I can wget this URL in a few seconds but flatpak-builder just hangs:

```
+ flatpak-builder --ccache --build-only /home/aleb/dev/pitivi/prefix /home/aleb/dev/pitivi/pitivi/build/flatpak/pitivi-master.json
Downloading sources
Downloading http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
```

It works fine if I create `/home/aleb/dev/pitivi/prefix`. It should print an error if the folder does not exist, instead of hanging.

**Comment by matthiasclasen** [comment]
I can't reproduce this. I get quick error messages in all cases where some of the directory(s) don't exist

**Comment by alexlarsson** [comment]
I've changed the download code recently, and i was never able to repro this, so closing for now.
