### ISSUE TITLE
Apps don't kill all their processes on exit

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#1903]
Fedora Rawhide 29
Flatpak 0.99.2

Reproduce
1. Open Kdenlive
2. Start rendering
3. Exit Kdenlive either from [x] or Shell quit menu

Outcome: Melt process still works and you can only discover if you open the CPU Monitor. [See the corresponding bug on Kdenlive](https://bugs.kde.org/show_bug.cgi?id=396519)

I understand this is a desired behavior for apps that want to run on background even when we exit the window, like Polari or FeedReader https://github.com/flatpak/flatpak/issues/553 but in this case is a bug on Kdenlive that also becomes a bug inside Flatpak Sandbox

I'm not familiar how Flatpak Sandbox is handling background processes, but it is expected when you quit an app, to quit gracefully or not :)

**Comment by alexlarsson** [comment]
Generally flatpak does not have a notion of "the main process" or any intimate knowledge about the running app. The sandbox will keep existing until the last process in it exits. (However, the "flatpak run" launch command will exit when the initial process in the sandbox exits.)
