### ISSUE TITLE
No clean way to launch a D-Bus service when app is split in many packages

### ISSUE THREAD

**Issue by goffi-contrib** [flatpak/flatpak#1904]
Hello,

this issue is following https://github.com/flatpak/flatpak/issues/1902 which has been solved thanks to @TingPing . But there is not clean way to launch the D-Bus service in a separate package if it is not installed, and I think this is a usability issue and it affects user experience.

To sum up the issue, I have an application which rely on one backend (`org.salutatoi.SAT`) which launches a D-Bus service, and several frontends (`org.salutatoi.[FRONTEND_NAME]`) which use this service, so the service must be launched when they need it.
If `org.salutatoi.SAT` is installed, the D-Bus `.service` file is installed, and all is fine. But in expected situation, end-user will just click on the frontend he/she want to use (e.g. `org.salutatoi.Cagou`), and the backend will not be installed.

All manifests are available at https://repos.goffi.org/sat_docs/file/4549cf265131/flatpak (_note: the hack explained below has been reverted since, because this method is really not clean_).

All the frontends use the same runtime which contains the whole backend, so I've worked around the issue by:
- giving all frontends the same permissions as backend
- installing the same D-Bus `.service` file in each frontend manifest
- giving ownership of `org.salutatoi.SAT` D-Bus namespace to each frontend

This is working, as each newly installed frontend will override the service with it's own `.service` file, which is launching the backend. But this is clearly a hack and has the following drawbacks:

- giving unneeded permissions to frontends (they most of time only need to access backend and internet)
- having to copy paste permissions and the `.service` file everywhere, which is tedious to maintain
- if any frontend is removed, the link is suppressed, and the backend will not be launched automatically anymore even if other frontends are still present

This can only be a temporary solution, and some clean way of handling this use case should in my opinion be available in Flatpak.

This could be fixed by allowing a runtime to install a `.service` file. Indeed, if my `org.salutatoi.Platform` runtime was able to install the `org.salutatoi.SAT` D-Bus service, it would solve the issue (I've tried by copying the file to `/usr/share/dbus-1/services/org.salutatoi.SAT.service`, and even with `--own-name=org.salutatoi.SAT` it is not working).

An other option would be to allow a dependency to be installed: if I install `org.salutatoi.Libervia` I then should have `org.salutatoi.SAT` installed automatically (after user confirmation).

Thank you very much!

## Linux distribution and version
Arch Linux 4.17.4-1-ARCH
## Flatpak version
Flatpak 0.99.2

**Comment by alexlarsson** [comment]
Flatpak has no dependency system, and adding one is contrary to the goals of the project. If you don't want to ship the backend in all the frontends (which honestly is in-line with how flatpaks are expected to work, i.e. self-contained) I would recommend to do a runtime check for the backend and open a dialog asking the user to install it.
