### ISSUE TITLE
No way to tell what commit is running

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#1908]
GNOME Software is going to start auto-updating flatpaks in 3.30 -- and for this we're adding notifications for the user if they're actually running an old version of something that's recently been updated. We also need to know the runtime the running apps are using, in case we update that and need to restart several apps.

At the moment `flatpak_run_add_app_info_args()` builds a beautiful keyfile with all the information we require, then opens it r/o, deletes the backing file, then bind mounts the fd into the newly created instance. I assume this is done to avoid having stale files for apps that are not cleane-up (for instance, forced shutdown, out of battery). If there isn't any security issue with having the file around, can we not `unlink()` the keyfile so that gnome-software can read the file? Thanks.

**Comment by matthiasclasen** [comment]
Together with this, a 'flatpak ps' command could be a nice addition

**Comment by alexlarsson** [comment]
You can access the info file for a running instance via the pid as /proc/$PID/root/.flatpak-info

**Comment by alexlarsson** [comment]
Additionally, the apps themselves can detect when they are updated by monitoring the file /app/.updated which will be created when the app is updated outside the sandbox.

**Comment by matthiasclasen** [comment]
but how do I know what pids belong to running flatpak sandboxes ?

**Comment by matthiasclasen** [comment]
I guess one answer is this:

$ ls /sys/fs/cgroup/unified/user.slice/user-1000.slice/user@1000.service/ | grep flatpak-.*.scope
flatpak-org.gnome.dfeet-24785.scope
flatpak-org.gnome.Polari-19341.scope
flatpak-org.gnome.Todo-2742.scope
flatpak-org.telegram.desktop-743.scope

**Comment by alexlarsson** [comment]
We create slices for the sandboxes only if systemd --user is running, but that is one option.

**Comment by matthiasclasen** [comment]
I've written an example around updates and restarting, here: https://blogs.gnome.org/mclasen/2018/08/02/on-flatpak-updates/

**Comment by matthiasclasen** [comment]
See the just merged 'flatpak ps' command. The flatpak-info file is now kept in
/run/user/$UID/.flatpak/$INSTANCE/info
