### ISSUE TITLE
Unable to install the Software Flatpak plugin

### ISSUE THREAD

**Issue by pedlino** [flatpak/flatpak#1915]
## Linux distribution and version
Ubuntu 16.04.4 LTS (DE Gnome)
## Flatpak version
0.99.3-flatpak1~xenial
## Description of the problem
The official Flatpak PPA is in my repository list as
http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu xenial main
When I run 
sudo apt install gnome-software-plugin-flatpak
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gnome-software-plugin-flatpak
## Steps to reproduce
Just run sudo apt install gnome-software-plugin-flatpak

Help?

**Comment by fenryxo** [comment]
Hello @pedlino. There is no Flatpak plugin for GNOME Software 3.20.5 in Ubuntu 16.04. If I recall correctly, GNOME software supports Flatpak from version 3.22. If you wish to manage Flatpaks with GNOME Software, I recommend upgrading to Ubuntu 18.04 LTS.

**Comment by pedlino** [comment]
I'm fairly new to Linux so maybe this question doesn't make sense: this is a Gnome limitation? Will the problem be solved if I switch to XFCE? Upgrading to Ubuntu 18.04 is not an option (it is not compatible with previous R versions)

**Comment by TingPing** [comment]
It is a limitation of time, 16.04 just contains too old of software.

**Comment by pedlino** [comment]
Ok. Thank you both for the answers.

**Comment by mervick** [comment]
16.04 is LTS. Why are you not support it?
There are many users which can't update to the newest Ubuntu

**Comment by fenryxo** [comment]
> 16.04 is LTS. Why are you not support it?
There are many users who can't update to the newest Ubuntu

**Ubuntu 16.04 LTS is supported by Flatpak.** You can easily install Flatpak from [Flatpak PPA](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak?field.series_filter=xenial).

You cannot, however, install Flatpaks with GNOME Software in Ubuntu 16.04 LTS because it contains old GNOME Software 3.20.5. That version doesn't inlude Flatpak plugin (you need 3.22+) and it **cannot be easily updated** - it's an integral part of your distribution with complex dependencies (which would probably need to be updated as well, welcome to the dependency hell).

**Comment by franny23dmt** [comment]
flatpak version 1.4.0-1~xenial is available now from the above PPA^

**Comment by pooky2483** [comment]
> > 16.04 is LTS. Why are you not support it?
> > There are many users who can't update to the newest Ubuntu
> 
> **Ubuntu 16.04 LTS is supported by Flatpak.** You can easily install Flatpak from [Flatpak PPA](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak?field.series_filter=xenial).
> 
> You cannot, however, install Flatpaks with GNOME Software in Ubuntu 16.04 LTS because it contains old GNOME Software 3.20.5. That version doesn't inlude Flatpak plugin (you need 3.22+) and it **cannot be easily updated** - it's an integral part of your distribution with complex dependencies (which would probably need to be updated as well, welcome to the dependency hell).

Then, HOW can we install .flatpakref files if we have everything BUT the gnome-software-plugin-flatpak extra ?

**Comment by pooky2483** [comment]
To everyone who is having problems installing flatpak programs on 16.04, I have found the way to do it. I did a little digging and found a site which has instructions on how to do it.
[HERE](http://bit.ly/38dkGwX)
