### ISSUE TITLE
Generically renamed Gnome base apps can’t be searched for via their real names in Gnome desktop search

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#1916]
## Linux distribution and version
Fedora 28 SB

## Flatpak version
0.99.3

## Description of the problem
When you search for those generically renamed Gnome base apps (Nautilus⇒Files, Evince⇒Documents, etc.) in the Gnome desktop search, you will see that flatpaked applications don’t get listed when you search for their real names.

## Steps to reproduce
Install some Gnome base apps like Evince via Flatpak, and search for “evince” in the gnome desktop search – you won’t get them listed (or maybe just the RPM packaged ones).

**Comment by TingPing** [comment]
This is reported upstream: https://gitlab.gnome.org/GNOME/glib/issues/1417
