### ISSUE TITLE
 Inkscape installed with Flatpak not access Internet.

### ISSUE THREAD

**Issue by pedropaulomg** [flatpak/flatpak#1921]
## Inkscape installed with Flatpak not access Internet.

When I execute the menu: File / Import Clipart and press the "search" button, Inkscape return this message: Could not connect to the Open Clipart Libary

![screenshot from 2018-07-24 19 37 13](https://user-images.githubusercontent.com/22965630/43169875-13582a90-8f79-11e8-9732-5cbf6ffb767f.png)

**Comment by barthalion** [comment]
`flatpak override --share=network appid`

Not a flatpak issue. If you want it to be changed by default, report it on Inkscape repository on Flathub organization.

**Comment by mwleeds** [comment]
This has moved to https://github.com/flathub/org.inkscape.Inkscape/issues/16
