### ISSUE TITLE
Opening Steam on RHEL after last update

### ISSUE THREAD

**Issue by jatin-newacc** [flatpak/flatpak#1931]
## Flatpak error while opening steam after last update
After Last update yesterday i updated steam using flatpak. It was working before but now steam is not opening here is the log error which im getting. 
![screenshot from 2018-07-28 15-43-18](https://user-images.githubusercontent.com/40650341/43355618-fca41334-927c-11e8-9f52-5cd5765d44e8.png)

**Comment by jatin-newacc** [comment]
There was a steam update which i got yesterday and now flatpak is unable to open Steam please help .... It was working well until yesterday.

**Comment by TingPing** [comment]
One solution is updating your` flatpak` version: https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/

**Comment by AsciiWolf** [comment]
This issue was "fixed". The commit that added Bluetooth support was [reverted](https://github.com/flathub/com.valvesoftware.Steam/commit/ea4a312fd19090b9c3a7aae31beaa0707c2e763e).

**Comment by barthalion** [comment]
I wonder if it wouldn't be better to ignore "unknown" permissions in older releases (and print a warning) instead of failing.

**Comment by mwleeds** [comment]
> I wonder if it wouldn't be better to ignore "unknown" permissions in older releases (and print a warning) instead of failing.

This is already the case on the 0.10.x branch: https://github.com/flatpak/flatpak/commit/c8c0df3fba458844d99ddd773244467fa4a35408. RHEL just has an ancient version of flatpak.

**Comment by nanonyme** [comment]
@AsciiWolf yeah, there was no good way to support bluetooth support without excessive side-effects. See summary in https://github.com/flathub/com.valvesoftware.Steam/pull/116
Consider Flatpak 0.10.3 a requirement for Steam (and kick your local maintainers to update to at least that) although it's not technically yet a requirement. I don't feel comfortable combining a strict version requirement with the fact that the workaround for getting Steam cloud that is possibly going to be merged soon is quite invasive.

**Comment by alexlarsson** [comment]
Yeah, lets focus on getting 1.0 out and into all distros.
