### ISSUE TITLE
Missing Flatpak Instruction about "Lanch application"

### ISSUE THREAD

**Issue by a-da** [flatpak/flatpak#1934]
Step to reproduce
1. Install Thunderbird Flatpak
2. Install Firefox Flapak
3. Open an email from Thunderbird and click on some link
4. It will prompt and pop up windows asking to chose  other application
5. I can not find option to specify that I want another Flatpak application (In my case Firefox Flatpak)

See screenshot:

![ada_selection_052](https://user-images.githubusercontent.com/17334646/43393632-1a876e88-93f8-11e8-84d4-e14d7a383ec2.png)

1. We can have a checkbox/filter to choose from all available flatpak apps
2. Until (1) is not implemented what is workaround for that ?

**Comment by matthiasclasen** [comment]
This is thunderbirds own dialog. If it was using the platform apis (glib, gtk) for opening urls, it would just work.

**Comment by TingPing** [comment]
Reported here: https://github.com/flathub/org.mozilla.Thunderbird/issues/1
