### ISSUE TITLE
Wrapper script for editors can't be used as $EDITOR with sudoedit

### ISSUE THREAD

**Issue by wjt** [flatpak/flatpak#1947]
## Linux distribution and version

Endless OS 3.4.6 // Fedora Workstation 28

## Flatpak version

0.99.3

## Description of the problem

On https://github.com/flathub/org.vim.Vim/issues/2 @TingPing summarized an IRC conversation, advising the reporter not to use `sudo flatpak run org.vim.Vim`, and to use `sudoedit` instead. This is actually not easy to achieve without pretty deep knowledge of how Flatpak works. The `org.vim.Vim` wrapper script provided by Flatpak doesn't use `--file-forwarding`, and `sudoedit` uses a temporary file in `/var/tmp` which is not shared within the sandbox, so the "obvious" approach of `EDITOR=org.vim.Vim` does not work.

## Steps to reproduce

1. `flatpak install flathub org.vim.Vim`
2. `EDITOR=/var/lib/flatpak/exports/bin/org.vim.Vim sudoedit /etc/hosts`

Expected result:

* Vim opens at a temporary file containing the current contents of `/etc/hosts`
* Modifying the file, saving, and exiting causes the real `/etc/hosts` to be overwritten

Actual result:

* Vim opens with a blank file and `"/var/tmp/hosts.ABCDEF" [New File]` in the status line
* When you close Vim, you see `sudoedit: /etc/hosts` unchanged, regardless of any edits you make to the (blank) file

## Notes

`org.vim.Vim.desktop` has:

```ini
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=vim --file-forwarding org.vim.Vim @@ %F @@
```

But `org.vim.Vim` looks like this:

```sh
#!/bin/sh
exec /usr/bin/flatpak run --branch=stable --arch=x86_64 org.vim.Vim "$@"
```

The problem can be worked around by creating `/usr/local/bin/vim-file-forwarding` containing:

```sh
#!/bin/sh
exec /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=vim --file-forwarding org.vim.Vim @@ "$@" @@
```

and setting this as `$EDITOR`. However it would not be correct to make this change in the main `org.vim.Vim` wrapper script because command-line arguments are treated as files:

```console
wjt@tensionsheet-redux:~$ cd /etc
wjt@tensionsheet-redux:/etc$ vim-file-forwarding --version
error: Failed to open '/etc/--version'
```

This is because Flatpak treats `--version` as a relative path, which it resolves to `/etc/--version`, then determines that `/etc/--version` will not be directly visible within the sandbox so tries to export it to the document store. It "works" if run from `~` because the package has `--filesystem=host`:

```console
wjt@tensionsheet-redux:~$ vim-file-forwarding --version | head -n1
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 31 2018 14:22:53)
```

I don't really see how it's possible to solve this in general because the only way to know which command-line arguments are paths is to run the specific application's command-line parser – but by the time we've launched the application I think it's too late to get the files into the portal without prompting.

**Comment by wjt** [comment]
@TingPing points out on the Vim ticket that it has host filesystem access and one can just add `--filesystem=/var/tmp` to open one more hole in the extremely hole-y sandbox. Doesn't help if the app *is* sandboxed but maybe one just doesn't care about that case.

**Comment by alexlarsson** [comment]
You can also flatpak override to grant /var/tmp access. I don't think we can ever do this in a generic way via the wrapper script, because we have no idea what the various options mean. In the desktop file case we do know where the app is gonna inject the filenames though.
