### ISSUE TITLE
Installing software with no reviews mess the theme installed

### ISSUE THREAD

**Issue by Trudill** [flatpak/flatpak#1950]
## Description of the problem
Hi,
When you install a software (ie Inkscape), the first ones who appears (and sometime the only one if you don't wait enough) is the one without reviews (no stars) as you can see on this picture.

![3](https://user-images.githubusercontent.com/3287253/43896163-24dba434-9bd8-11e8-93ab-e5aafe339e9c.png)

If you choose this one, the icons in whisker menu or on the desktop are not the right ones (which is not the case on my example, but it's to show where is the thing I am talking about.

Thanks for the amazing job you do !

## Steps to reproduce
Install a software with no stars, the icons are the wrong ones.

**Comment by AsciiWolf** [comment]
Is this really a Flatpak issue?

**Comment by alexlarsson** [comment]
This is a bug in gnome-software, not flatpak.

**Comment by Trudill** [comment]
Thank you for leading me to gnome-software !
Have a nice day !
