### ISSUE TITLE
i18n for the update confirmation request

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#1953]
## Linux distribution and version
Fedora 28 SB

## Flatpak version
v0.99.3

## Description of the problem
Flatpak newly shows up a confirmation request for updating certain packages. Could that also be internationalized, like the rest of the application interface? Would be more convenient (dnf already does that) and unify the interface. :)

**Comment by alexlarsson** [comment]
Its not clear exactly what you mean by this. The prompts should be translated (although we may not have translations for them yet), but the actual permissions are english, because they are technical details. Long term we should replace those with a highlevel explanaiont that could be translated.

**Comment by fbruetting** [comment]
ok
