### ISSUE TITLE
Can you clarify whether xdg-directory permissions grant access to entire $HOME when an xdg-directory does not exist?

### ISSUE THREAD

**Issue by sourcejedi** [flatpak/flatpak#1956]
http://docs.flatpak.org/en/latest/sandbox-permissions-reference.html

> xdg-music | Access the XDG music directory

The problem is I don't know how you define this, given the configuration I have.

I deleted some directories like Music, Desktop etc because I do not use them.  And I ran `xdg-user-dirs-update` and `xdg-user-dirs-gtk-update`, and now my filemanager isn't cluttered with unused/non-existent directories.

But, if an unsandboxed app looks for music - 

    $ xdg-user-dir MUSIC
    /home/alan/

It looks in $HOME.

My request is, can flatpak or its documentation be improved, such that it is clear how to check exactly which directories can be accessed by an app with a given permissions (e.g. by `filesystems=xdg-videos;xdg-download;xdg-documents;xdg-pictures;xdg-music;`).

---

```
$ cat /home/alan/.config/user-dirs.dirs
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/Documents/"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/"
```

uh.  So, they still appear to be set?  But notice that in Gnome, the file manager and file picker hide all these XDG directories that were set to "$HOME/".  AIUI, flatpak aims to help users to run GUI apps with some confidence about their isolation.  Does flatpak follow the example set by the Gnome GUI here, or does it follow `xdg-user-dir`?  I am confused!

It looks like the special code for skipping `$HOME/` is in `xdg-user-dirs-gtk-update`.  `strace` shows that it maintains this file:

$ cat /home/alan/.config/gtk-3.0/bookmarks
file:///home/alan/Downloads/podcasts
file:///home/alan/Documents
file:///home/alan/Downloads

Looking at the flatpak code... flatpack-context.c uses g_get_user_special_dir() from glib.  And so it looks to me like it is not following what Gnome/GTK does.

I would prefer if flatpak would make sure not to expose the entire "$HOME/".  But if it must do that, then I prefer to have documentation clearly warning about it, and telling how to avoid it.

**Comment by alexlarsson** [comment]
Hmm, i agree. It should not expose anything if these are set to $HOME.

**Comment by alexlarsson** [comment]
Actually, the code should already do this:
```
          if (strcmp (path, g_get_home_dir ()) == 0)
            {
              /* xdg-user-dirs sets disabled dirs to $HOME, and its in general not a good
                 idea to set full access to $HOME other than explicitly, so we ignore
                 these */
              g_debug ("Xdg dir %s is $HOME (i.e. disabled), ignoring", filesystem);
              continue;
```

Did you see it exposing the whole homedir?

**Comment by sourcejedi** [comment]
I didn't test, I was mainly looking at the documentation for some assurance when running Telegram.  I have Telegram running now, but was not sure how to launch a file open dialog from it.

After looking up debugging, `flatpak run --command=sh org.telegram.desktop/x86_64/stable` shows that `/home/alan` only has `Documents` and `Downloads`.  So it looks good, thanks.

I guess the `$HOME/` path must be being normalized somewhere, to remove the trailing slash before `strcmp()`.
