### ISSUE TITLE
Grand Ages: Medieval won't start without any message

### ISSUE THREAD

**Issue by nintyfan** [flatpak/flatpak#1959]
## Linux distribution and version
OpenSuSE Tumbleweed.
## Flatpak version
Flatpak 0.11.8.3
## Description of the problem
Won't load without any error. It doesn't depend how I launch the game. When launching from Steam - no any important message, When run Steam with --command=/bin/bash, ran Steam-wrapper in background, move into directory with and start ./App file - same error here.
## Steps to reproduce
As above.

**Comment by TingPing** [comment]
Please report issues against specific packages: https://github.com/flathub/com.valvesoftware.Steam/issues
