### ISSUE TITLE
Installing extension using extra-data

### ISSUE THREAD

**Issue by ozoder** [flatpak/flatpak#1975]
## Linux distribution and version
Fedora 28
## Flatpak version
0.99.3
## Description of the problem
I'm trying to create an Adobe Flash Player extension for Firefox. You can find it in [this](https://github.com/ondrej-zoder/firefox-devedition-flatpak/) repo. I've created an extension point in FirefoxNightly. The Flash Player extension itself downloads the tarball, extracts the files and copies the plugin inside the mozilla plugins folder. When I use the "type": "file" source for the plugin and run all the necessary commands inside "build-commands", everything works just fine. The code is [here](https://github.com/ondrej-zoder/firefox-devedition-flatpak/blob/63339febfc59b6e7c552687d23bc6e5a1c0f73dd/org.mozilla.FirefoxNightly.flashplayer/org.mozilla.FirefoxNightly.flashplayer.json#L16). 

But when I use "type": "extra-data" to download the plugin during the installation and then run the commands using an apply_extra script, like [this](https://github.com/ondrej-zoder/firefox-devedition-flatpak/blob/master/com.adobe.FlashPlayer.NPAPI/com.adobe.FlashPlayer.NPAPI.json#L16), it behaves strangely. Either the installation runs successfully, but the script does not execute, or the installation doesn't finish and I have to kill it.

For example [this](https://github.com/flathub/us.zoom.Zoom/blob/master/us.zoom.Zoom.json) app uses the same approach and works just fine. I suspect there might be an issue with using the apply_extra script in an extension.

## Steps to reproduce
1. Clone this repo: 
[https://github.com/ondrej-zoder/firefox-devedition-flatpak](url)
2. Install FirefoxNightly using the following commands:
`./setup_runtime.sh`
`./build.sh org.mozilla.FirefoxNightly`
`./install.sh org.mozilla.FirefoxNightly`
3. Install the Flash Player extension using these commands:
`flatpak-builder --repo=flash-repo build com.adobe.FlashPlayer.NPAPI/com.adobe.FlashPlayer.NPAPI.json`
`flatpak --user remote-add --no-gpg-verify flash-repo flash-repo`
`flatpak --user install flash-repo com.adobe.FlashPlayer.NPAPI`
4. You can use the following command to see the result inside the sandbox (both the script and the plugin are there, but the script wasn't executed):
`flatpak run --devel --command=sh org.mozilla.FirefoxNightly`

**Comment by bam80** [comment]
@ozoder are you sure you can write to /app/lib from _apply_extra_?
https://github.com/ozoder/firefox-devedition-flatpak/blob/64d78835d3fcc512b701b06d301565b4e8de916f/com.adobe.FlashPlayer.NPAPI/com.adobe.FlashPlayer.NPAPI.json#L28

**Comment by refi64** [comment]
This has been supported for a while now.

**Comment by tinywrkb** [comment]
This issue can be closed. Here's [an extension making use of extra-data](https://github.com/tinywrkb/flatpaks/blob/master/com.intel.quartus_prime.quartus_lite/com.intel.quartus_prime.quartus_lite.devinfo.ArriaLite.yaml).

**Comment by Mikenux** [comment]
Request to close if it has been resolved or is obsolete. @ozoder @GeorgesStavracas
