### ISSUE TITLE
Network slowness while installing anything

### ISSUE THREAD

**Issue by marceloslacerda** [flatpak/flatpak#1977]
Debian stretch (9.5)
Flatpak 0.8.9
I'm experiencing some extreme slowness while installing or updating packages with flatpak.

Here's a example:

> $ flatpak install -v org.gnu.emacs.flatpakref 2>&1
> Installing: org.gnu.emacs/x86_64/stable
> Required runtime for org.gnu.emacs/x86_64/stable (org.freedesktop.Sdk/x86_64/1.6) is not installed, searching...
> XA: Using cached summary for remote flathub
> Found in remote flathub, do you want to install it? [y/n]: y
> XA: Transaction: install/update flathub:runtime/org.freedesktop.Sdk/x86_64/1.6[$old]
> XA: Using cached summary for remote flathub
> XA: Transaction: install/update flathub:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6[*]
> XA: Transaction: install/update flathub:runtime/org.freedesktop.Sdk.Locale/x86_64/1.6[/en]
> XA: Transaction: install flathub:app/org.gnu.emacs/x86_64/stable[*]
> XA: Using cached summary for remote flathub
> Installing: org.freedesktop.Sdk/x86_64/1.6 from flathub
> XA: Using cached summary for remote flathub
> XA: Using cached summary for remote flathub
> 
> Receiving delta parts: 17/17 90.8 kB/s 20.2 MB/207.0 MB 34 minutes 17 seconds remainingg[[3~[[C
> error: While pulling runtime/org.freedesktop.Sdk/x86_64/1.6 from remote flathub: Socket I/O timed out
>

**Comment by alexlarsson** [comment]
Can you try the flatpak from backports? There has been a lot of performance fixes in since 0.8.

**Comment by marceloslacerda** [comment]
Yep, using the version from backports works normally. Great job!
