### ISSUE TITLE
Please support site and distro supplied configured remotes

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#198]
At the moment flatpak is set up with no remotes by default, and this is probably a good thing. I want to be able to ship one package in Fedora 25 which adds a few trusted .flatpakrepo files for projects like pitivi, libreoffice and darktable. To do this we figured the best way would be to have:

 *  `/usr/share/flatpak-1.0/repos.d` - for system ones
 * `/etc/flatpak-1.0/repos.d` for site ones
 * `~/.local/share/flatpak-1.0/repos.d` for per user ones (is this needed? We could just double click a .flatpakrepo...)

Then we'd need some kind of api, perhaps `flatpak_installation_list_remotes_default()` that returns a list of FlatpakRemotes from those three locations. In gnome-software the policy would be "just install them all without asking" but the command line could have other defaults.

This would let us ship one package in Fedora and get people installing flatpaks with little-to-no-fuss. Comments?

**Comment by alexlarsson** [comment]
This is already supported, via ostree, as we set a custom system path on the ostree Repo. Förgör the exact pathnames and can't check right now though.

**Comment by matthiasclasen** [comment]
You mean this ?

static OstreeRepo *
system_ostree_repo_new (GFile *repodir)
{
  return g_object_new (OSTREE_TYPE_REPO, "path", repodir,
                       "remotes-config-dir", FLATPAK_CONFIGDIR "/remotes.d",
                       NULL);
}

I didn't find an equivalent for per-user installation

**Comment by matthiasclasen** [comment]
There is no per-user equivalent, but the system-wide location is documented now.
