### ISSUE TITLE
Missing dependencies: gpgme, gobject-introspection and libcap

### ISSUE THREAD

**Issue by PrzemoF** [flatpak/flatpak#1981]
## Linux distribution and version
Fedora28
## Flatpak version
Building from source (git clone)
## Description of the problem
./autogen.sh fails
## Steps to reproduce
run ./autogen.sh on a system without gpgme, gpgme-devel, gobject-introspection and gobject-introspection-devel, libcap-devel installed

**Comment by mwleeds** [comment]
Run `dnf builddep flatpak`?

**Comment by PrzemoF** [comment]
Thanks! I guess it's good to have the checks in configure.ac? Feel free to close the issue if running dnf builddep is acceptable policy for the flatpak project.
