### ISSUE TITLE
Installing in user/system string is not fully translated

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak#1984]
## Linux distribution and version
Fedora 28
## Flatpak version
0.99.3
## Description of the problem
The "user" and "system" part of the _Installing in user_ and _Installing in system_ strings is not translatable. This is how it looks on Flatpak localised into Czech language:

```
$ flatpak --user install flathub org.gnome.chess
Instaluji v user:
org.gnome.chess/x86_64/stable        flathub e81577ea1837
...
```

## Steps to reproduce
1. Use non-English system localisation.
2. Try to install some app using `flatpak install`.

**Comment by AsciiWolf** [comment]
Same problem with the _Uninstalling from user/system_ and Updating in user/system strings.

**Comment by AsciiWolf** [comment]
Same problem with the _Uninstalling from user/system_ and _Updating in user/system_ strings.

**Comment by matthiasclasen** [comment]
user / system are really fixed IDs here. They correspond to the --user / --system options, which are not translated either.

char *
flatpak_dir_get_name (FlatpakDir *self)
{
  const char *id = NULL;

  if (self->user)
    return g_strdup ("user");

  id = flatpak_dir_get_id (self);
  if (id != NULL && g_strcmp0 (id, "default") != 0)
    return g_strdup_printf ("system (%s)", id);

  return g_strdup ("system");
}

**Comment by fenryxo** [comment]
If they are special fixed IDs, they could be then used as IDs and not as words. E.g.,

* `Installing in the default user location "%s".` where `%s` is `user`
* `Installing in the default system location "%s".` where `%s` is `system`
* `Installing in a custom location "%s".` where `%s` is the custom id.
