### ISSUE TITLE
Put base directories of applications in the user's ones

### ISSUE THREAD

**Issue by MayeulC** [flatpak/flatpak#1991]
## Description of the problem
XDG base dirs are here among other reasons to make it easier to find applications' configuration files, backup them, etc.
`.cache` for example would be safe to delete to regain disk space. 

However, flatpak currently stores data in places that are hard to guess, or in any case not aligned with the rest of the world. I think that `XDG_DATA_HOME` is `$HOME/.var/app/package.name/data`, there are also `config`, `cache`, etc.

## Proposal
Why not put `XDG_DATA_HOME` in a subdirectory of the real user-set one? Something like `$XDG_DATA_HOME/flatpak/package.name`

On my system, for instance, Steam's data would be in
```
/home/me/.local/share/flatpak/com.valvesoftware.Steam/
instead of
/home/me/.var/app/com.valvesoftware.Steam/data/
```
(note that both are at the same depth)

Other solutions are possible, but I think this one is already quite nice. `.var` could still be a fallback if the xdg data dirs are not set, or alternatively, use the defaults from the spec.

### Advantages
* Config files can roam just like the others
* Data can be stored on different partitions depending on the type. Example: cache on a ramdisk.
* cache can be deleted at once for every app
* Easier to find for the user, as data is stored in a standard location. Think of a videogame save the user wants to manually backup, for instance
* Non-conforming apps could be made to conform to the XDG base dir spec trough flatpak

### Drawbacks
* It might require a tiny bit of code for the migration
* Completely removing applications isn't as simple as deleting their directory in `.var/app`
  * Though there could be a daemon watching the directory and ask user if it wants to delete orphaned data, or flatpak could check if there are some orphaned directories when ran.

## Important note
This isn't about flatpak conforming itself to the XDG base directory specification (#1651, #46, https://github.com/flatpak/flatpak.github.io/issues/191), although it could be discussed in another issue; but rather about making flatpaks follow the user configuration.

**Comment by matthiasclasen** [comment]
I think it is too late for that kind of change

**Comment by matthiasclasen** [comment]
I think it is too late for that kind of change, and as you point out yourself, it would break one of the main reasons for setting things up the way they are now: keeping all of an apps files in one place.

**Comment by matthiasclasen** [comment]
This has been discussed repeatedly, and the answer has always been that we don't want to change this.

**Comment by lhanson** [comment]
It's baffling that such an easy feature to implement as "respect the user's preference if they go out of their way to indicate one, otherwise continue cluttering their `$HOME` as always" is met with such obstinance. If there's a valid argument for flatpak not respecting the user's preference other than "we don't want to" (which is your prerogative, of course), I haven't seen one. If somebody submitted a PR to respect XDG environment variables, would it be accepted?

**Comment by matthiasclasen** [comment]
If the organization of your xdg dirs is more important to you than all the other features that flatpak offers, then you should absolutely choose a method of installation that works best for you

**Comment by lhanson** [comment]
It's not the organization of "my xdg dirs" that's the issue; those are well-established and interoperate predictably with the software I use.

What has convinced me to avoid flatpak entirely is the fact that, while all the thinking has already been done for you (a cross-platform standard for where to store different types of files already exists), volunteers are ready to step up to do the work, and it costs you nothing to honor a user's wishes if they go out of their way to specify how they want your app to behave, somehow *this* particular arbitrarily-determined directory structure is worth disrespecting users for.

I can't help but to note with irony that the purported benefits of flatpak as listed on flatpak.org are *precisely* why the XDG spec exists in the first place. Standards for thee, but not for me, apparently.

**Comment by mwleeds** [comment]
See https://github.com/flatpak/flatpak/issues/1651#issuecomment-412878960

**Comment by Jonta** [comment]
>2 years since the comment @mwleeds links to was posted now, topic locked as "resolved"

@alexlarsson said "We never got to updating the spec for this, but that will happen eventually"

I assume that's the XDG-spec. Status? ETA on "eventually"?

My searches aren't turning up anything promising on ".var" and "xdg". =)
