### ISSUE TITLE
Temporary files filled my disk.

### ISSUE THREAD

**Issue by alexb3d** [flatpak/flatpak#1993]
Linux Ubuntu 18.04
Flatpak version 1.0.0 (PPA)

Hi. The temporary files filled my root (/) hard drive.
[https://drive.google.com/open?id=15GZskImkcATAAaROBckoi4eRNDPUo3dk](url)

**Comment by mwleeds** [comment]
Could you use the GitHub attach file feature rather than a Google Drive link? Or just put in the info directly in the issue.

**Comment by mwleeds** [comment]
Apparently not

**Comment by alexb3d** [comment]
You do not know how to open the google link?
You already closed the damn post. This is the second you close without a solution.
I still have the hard drive full because of Flatpak.

There was a tremor of 7.3 in my country.
Because the people of Gnome are so idiotic.
Damn useless.

I do not write anymore in this shit. Damn useless.
