### ISSUE TITLE
Inconsistency in tilde for home directory substitution in flatpak-builder command

### ISSUE THREAD

**Issue by aral** [flatpak/flatpak#1994]
## Linux distribution and version
Pop!_OS 18.04
## Flatpak version
1.0.0
## Description of the problem

The `repo` option for flatpak-builder cannot handle tilde (`~`) substitution for the home directory in the supplied path. The build directory handles the substitution correctly. This is inconsistent and confusing.

## Steps to reproduce

The following fails:

```bash
flatpak-builder --force-clean --gpg-sign=3AF2869FBAD46F4A28B39B29E23D430094E4F866 --repo=~/sandbox/gnomit-test-repo ~/sandbox/gnomit-test-build ./ind.ie.Gnomit.json
```

With the error:

```bash
Exporting ind.ie.Gnomit to repo
error: Creating repo: mkdirat: No such file or directory
```

The following succeeds:

```bash
flatpak-builder --force-clean --gpg-sign=3AF2869FBAD46F4A28B39B29E23D430094E4F866 --repo=/home/aral/sandbox/gnomit-test-repo ~/sandbox/gnomit-test-build ./ind.ie.Gnomit.json
````

**Comment by matthiasclasen** [comment]
This has nothing to do with flatpak-builder.

Expanding ~ to home is a shell feature. But the shell only does it at the beginning of arguments.

**Comment by aral** [comment]
@matthiasclasen That may be the case. Regarding the above use case, is Flatpak happy to pass the blame for the inconsistency that that creates in its own interface to the shell (in which case, shall I open a documentation PR to point this out) or should Flatpak work around this issue so that regardless of the limitation/inconsistency in shells, its command will handle tilde substitution for home directory consistently?

**Comment by matthiasclasen** [comment]
Every script and unix command behaves in this way. Try ./configure --prefix=~/foo

**Comment by TotallyDIO** [comment]
soo is it fixed or nah
