### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by 2sn** [flatpak/flatpak#1997]
## Steps to reproduce

trying to install on Fedora 28

the web page `https://flatpak.org/setup/Fedora/` provides a  file `flathub.flatpakrepo` for "installation" but no instructions what to do with the file.  It seems resistant to being installed with `dnf` or `rpm`.  So, what do I do with that file?  Any hints provided on the web page would be useful.

**Comment by Mikerr1111** [comment]
Well, the Fedora 28 Workstation comes with flatpack pre-installed.

**Comment by 2sn** [comment]
OK, thanks for the clarification.

**Comment by alexlarsson** [comment]
Clicking on the flatpakrepo file *should* have opened it in gnome-software to add it. If this is not happening for some reason, then you can manually add it in the cli as `flatpak remote-add flathub flathub.flatpakrepo`-
