### ISSUE TITLE
I cannot run Steam, something with "libglnx/glnx-shutil.c:147:mkdir_p_at_internal: assertion failed: (!did_recurse)"

### ISSUE THREAD

**Issue by Hund** [flatpak/flatpak#1998]
## Linux distribution and version
Gentoo Linux

## Flatpak version
Version 1.0.0, installed via this[[1]] overlay with `seccomp` as the only enabled USE-flag.

[1]: https://github.com/fosero/flatpak-overlay

## Description of the problem
I does not start, it only gives me this message:
```
flatpak:ERROR:libglnx/glnx-shutil.c:147:mkdir_p_at_internal: assertion failed: (!did_recurse)
zsh: abort      flatpak run com.valvesoftware.Steam
```
## Steps to reproduce
Run command `flatpak run com.valvesoftware.Steam`.

**Comment by vorlock** [comment]
The same issue on Debian Buster for the same app.

**Comment by Hund** [comment]
Then it's probably not me who's the issue then. :)

**Comment by ananace** [comment]
You might've run afoul of an issue in the Steam cloud data migration, I'd suggest checking that the folder structure in your `~/.var/app/com.valvesoftware.Steam` folder isn't broken.

**Comment by Hund** [comment]
I had these two symlinks there:

```
cache -> .cache
config -> .config
```

They where both pointing to dead ends and after creating the folders it worked for me. :)

Thanks for the help!

**Comment by nanonyme** [comment]
Any chance seeing if this reproduces if you wipe .var/app/com.valvesoftware.Steam and run Steam again? You can just rename it and move back after test if you already installed something

**Comment by Maldela** [comment]
Renaming .var/app/com.valvesoftware.Steam and running Steam again fixed it for me, too.

**Comment by nanonyme** [comment]
Can you please run flatpak update and see if it shows anything?

**Comment by Cogitri** [comment]
This just happened to me as well, deleting the folder and running it again fixed it for me.

**Comment by satchnut** [comment]
For me it worked only to delete _cache_, _config_, and _data_ symlinks within com.valvesoftware.Steam.
