### ISSUE TITLE
Add printer support

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#20]
We need some kind of solution for printing. A portal or some special cups configuration.

**Comment by matthiasclasen** [comment]
this is being done in xdg-desktop-portal

**Comment by gcclinux** [comment]
How can I use the xdg-desktop-portal in my json file?

**Comment by matthiasclasen** [comment]
both gtk and qt will automatically use the print portal for printing

**Comment by gcclinux** [comment]
> both gtk and qt will automatically use the print portal for printing

I understand, my app is java and wondering what I need to do or how in the declare a portal for printer access in the flatpak json file.

Is that even possible?
