### ISSUE TITLE
Installing/updating from origin remotes fails

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2000]
Flatpak version: 1.0.0

When a bundle is created with the `--repo-url` option, its `-origin` remote that is created when it's installed will have a URL set. But Flatpak also sets `gpg-verify=false`, `gpg-verify-summary=false`, and `collection-id=` on it, so it's unusable for installing extensions or updating the app. I'm testing this with a collection ID set on the flathub remote; I'm not sure what the behavior is otherwise.

Here are the steps to reproduce:
1. Install calculator from flathub: `flatpak install -y flathub org.gnome.Calculator`
2. Make a bundle of it with a URL set: `flatpak build-bundle --repo-url=https://dl.flathub.org/repo/ /var/lib/flatpak/repo/ calculator.flatpak org.gnome.Calculator stable`
3. Uninstall it: `flatpak uninstall -y org.gnome.Calculator`
4. Install from the bundle: `flatpak install calculator.flatpak`

Here's the output from the last step; notice the error at the end:
```
Installing in system:
org.gnome.Calculator/x86_64/stable        org.gnome.Calculator-origin 3ef5e4586712
  permissions: ipc, network, wayland, x11
  file access: xdg-run/dconf, ~/.config/dconf:ro
  dbus access: ca.desrt.dconf
org.gnome.Calculator.Locale/x86_64/stable org.gnome.Calculator-origin e67b1cd109f1
Is this ok [y/n]: y
Installing: org.gnome.Calculator/x86_64/stable from bundle calculator.flatpak
Now at 3ef5e4586712.
Installing: org.gnome.Calculator.Locale/x86_64/stable from org.gnome.Calculator-origin
Warning: Failed to install org.gnome.Calculator.Locale/x86_64/stable: Can't pull from untrusted non-gpg verified remote
```

**Comment by alexlarsson** [comment]
Why not add the gpg key to the bundle, then it should work fine, no?

**Comment by mwleeds** [comment]
Yeah, using `--gpg-keys` with the `build-bundle` command, combined with https://github.com/flatpak/flatpak/pull/2081 fixes this.

**Comment by mwleeds** [comment]
Apparently you can also use the `--gpg-file` option for the install command, so that's another way to make it work.
