### ISSUE TITLE
I can not install packages through flatpak

### ISSUE THREAD

**Issue by jovsantos** [flatpak/flatpak#2009]
## Linux distribution and version
Debian 9 Stretch
## Flatpak version
Flatpak 0.8.9
## Description of the problem
Today I tried to install gimp 2.10 via flatpak, but the installation does not work because of a possible network problem. I believe the problem is in flatpak / flathub, because my network works perfectly.

`Error: Error resolving "dl.flathub.org": Temporary failure in name resolution`
## Steps to reproduce
I do not know how to solve it.

**Comment by alexlarsson** [comment]
This is just a transient network issue (it could't resolve the dns). It'll fix itself eventually.

**Comment by jovsantos** [comment]
Thanks!

Em seg, 27 de ago de 2018 às 08:42, Alexander Larsson <
notifications@github.com> escreveu:
