### ISSUE TITLE
flatpak installed vscode's integrated terminal not having desired behaviour

### ISSUE THREAD

**Issue by mundusnine** [flatpak/flatpak#2011]
## Linux distribution and version
Debian 9
## Flatpak version
Flatpak 0.8.9
## Description of the problem
https://github.com/Microsoft/vscode-cpptools/issues/1550
The fact that the app is virtualized makes it so that you can't run : `flatpak run org.godotengine.Godot `
or any flatpak command in the integrated terminal of vscode. You can't also use gnome-terminal as your integrated terminal in vscode because of this. This makes it also troublesome when trying to use external apps that are used by the extensions.(i.e. My haxe extensions in vscode can't find haxe in my path even though it is installed). 
## Steps to reproduce
- Install vscode with flatpak
- use the integrated terminal of vscode(try with sh/bash) and call flatpak list
## Potential solution:
Having something like the snapd --classic directive ?

**Comment by mundusnine** [comment]
Will add it to the vscode repo has I think it is more fitting there.

**Comment by alexlarsson** [comment]
I think the proper approach here is for the vscode app to spawn the shell via the HostCommand portal, so the terminal itself is in the sandbox, but the shell in it is on the host. This is what e.g. gnome-builder does with its terminals. A quick fix for this would be to use `flatpak-spawn --host bash` as the shell, or you can make it directly do the dbus calls.

**Comment by zdog234** [comment]
@mundusnine, could you link to this issue from the issue you created on the vscode repo? (or vice-versa, I suppose)
