### ISSUE TITLE
test-oci-registry and test-oci-registry-system fail on i386 machines

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#2015]
## Linux distribution and version

Debian Testing i386 or Ubuntu Cosmic Daily i386 (potentially other 32bit systems).

## Flatpak version

1.0.0-1

## Description of the problem

When autopkgtests of flatpak ran while importing from Debian -> Ubuntu on i386 there is a failure of the following tests
```
Flatpak/test-oci-registry.sh
Flatpak/test-oci-registry-system.sh
```

## Steps to reproduce

1) Download and install Debian Testing i386 or Ubuntu Cosmic i386
2) Install the packages `sudo apt install flatpak flatpak-tests gnome-desktop-testing` (for Ubuntu Cosmic download the debs from here https://launchpad.net/ubuntu/+source/flatpak/1.0.0-1/+build/15288949 )
3) Run the tests
```
gnome-desktop-testing-runner Flatpak/test-oci-registry.sh
gnome-desktop-testing-runner Flatpak/test-oci-registry-system.sh
```
4) Observe that the tests fail and mention a GLib-ERROR (eg `(flatpak remote-ls:2177): GLib-ERROR **: 17:22:24.477: g_variant_new: expected GVariant of type 'ay' but received value has type 'a{sv}'`)

test-oci-registry.sh failure - https://pastebin.ubuntu.com/p/QcZ4hqQKd9/
test-oci-registry-system.sh failure - https://pastebin.ubuntu.com/p/C77wVQJNJm/

**Comment by alexlarsson** [comment]
As per https://github.com/flatpak/flatpak/pull/2010#issuecomment-416527139 this seems to still happen.

**Comment by alexlarsson** [comment]
Eh, this was the wrong bug for that.
