### ISSUE TITLE
hard to find collection id for create-usb

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2020]
I tried the create-usb command, and it told me that my flathub remote needs a collection ID for this to work. So far so good. But it is not easy at all to find out the right collection ID to use.

I happened to know that it is somewhere in the summary file, so I manually downloaded https://dl.flathub.org/repo/summary, and dug through the binary gibberish to find org.flathub.Stable.

This should be easier.

**Comment by mwleeds** [comment]
It's hard to see which command could provide that information. We have `flatpak remote-info` but it provides information about specific apps/runtimes. Maybe we could either add another form of `remote-info` that allows specifying a remote but not a ref, or we could add the collection ID to the error message emitted by `create-usb` (or both).

**Comment by mwleeds** [comment]
On the other hand, in the medium term future, the collection ID will be deployed to everyone and no one will have to worry about this.

**Comment by matthiasclasen** [comment]
Might be nice to add the collection id as a comment or inactive key to the flatpakrepo file ?

X-CollectionID=org.flathub.Stable

**Comment by mwleeds** [comment]
We can also solve this as part of #1983
