### ISSUE TITLE
Steam can't be executed: "mkdir_p_at_internal: assertion failed: (!did_recurse)"

### ISSUE THREAD

**Issue by Bohne13** [flatpak/flatpak#2025]
## Linux distribution and version
Ubuntu 18.10 daily build

## Flatpak version
Flatpak 1.0.0
with the "old" flatpak repository of bionic beaver

## Description of the problem
**
flatpak:ERROR:libglnx/glnx-shutil.c:147:mkdir_p_at_internal: assertion failed: (!did_recurse)
Abgebrochen (Speicherabzug geschrieben)

## Steps to reproduce
execute "flatpak run com.valvesoftware.Steam"

**Comment by nanonyme** [comment]
This is probably duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/161 and should be fixed. Does this still reproduce?
