### ISSUE TITLE
Need a os-release file in the runtime

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#203]
Various things require a /etc/os-release or /usr/lib/os-release file to work correctly, one of which being gnome-software to set the data for the review server. What about shipping something like this in the runtime:

    NAME=Flatpak
    VERSION=Upstream
    ID=flatpak
    VERSION_ID=

I appreciate it's basically dummy data, but support for os-release is assumed by quite a few things. The other alternative is to bind-mount the system version in, although I'm not sure that's any more accurate than the dummy data here.

**Comment by matthiasclasen** [comment]
Are these the only fields that are relevant for you ?
Maybe something more like

NAME=GNOME
VERSION=3.20 (Flatpak runtime)
VERSION_ID=3.20
ID=org.gnome.Platform

**Comment by hughsie** [comment]
I actually only care about the NAME in gnome-software, but other this seemed like the bare minimum we should provide. Your idea is much better, matching the data to the runtime.

**Comment by matthiasclasen** [comment]
[0001-Add-usr-lib-os-release.patch.txt](https://github.com/flatpak/flatpak/files/378423/0001-Add-usr-lib-os-release.patch.txt)

**Comment by hughsie** [comment]
LGTM

**Comment by matthiasclasen** [comment]
pushed this now
