### ISSUE TITLE
An anomaly or by design ? ... Flatpak folder size !!!

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2037]
Hi,

I have been meaning to share with you a rather strange data ...

I have a separate and exclusive partition called 'Flatpaks' ... designated as a custom flatpak location. This partition is a little more than 32 GB as you can see in the screenshot below ... with 9GB of space still available ... 

**The anomaly however is that when i poll the size of the 'Flatpak folder' in this partition it polls up to a size of 59.1 GB !!!**

![deepinscreenshot_select-area_20180828200659](https://user-images.githubusercontent.com/3283676/44731323-93a1bc00-ab00-11e8-8160-62e5702bebc2.png)

**Is this even possible ?
a folder polling a size far greater than the partition size itself ?**

**Comment by TingPing** [comment]
I'm guessing your file manager just doesn't know how to handle hardlinks so the number is duplicated multiple times over the real value.

**Comment by aiamuzz** [comment]
thanks @TingPing  ... i suspected something like that too ...

**Comment by matthiasclasen** [comment]
One way to look at it is that this the amount of space you'd need if we didn't have ostree doing deduplication via hardlinks.
