### ISSUE TITLE
Please let me use flatpak ps from the libflatpak library

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#2047]
GNOME Software wants to find out what application are running so that it can use the correct notification text for automatic updates. `flatpak ps` seems to provide what I need, but it's somewhat inelegant having to screen scrape for the information. Could this be part of libflatpak please, even if it's under an `#ifdef EXPERIMENAL_API` type thing.

**Comment by matthiasclasen** [comment]
You could also read the files yourself...

**Comment by matthiasclasen** [comment]
Quick sketch of an api:

https://github.com/matthiasclasen/flatpak/tree/instance-api

If this looks ok, we can port flatpak ps to use it.

**Comment by alexlarsson** [comment]
I think that API looks good to me. Although get_all() needs to try to lock to avoid returning stale instances. (I mean, its still racy as all ps operations are, but we should not do worse than we can.)

However, i'm not sure we should add libflatpak API to the stable branch. Its a bit weird. Maybe we can add it as an internal thing for now and have gnome-software do a copy of it for now? Its not really depending on anything.

**Comment by matthiasclasen** [comment]
I've made it private for now, and ported flatpak ps to it. See 
https://github.com/flatpak/flatpak/pull/2060

I think copy-pasting this to g-s almost works.  Sadly, we need the gc_ids() private api.

**Comment by matthiasclasen** [comment]
I've now pushed a version that does not use gc_ids() (at the cost of using libglnx...)
