### ISSUE TITLE
Trading the Prepackaged Distro version with the latest from here ... Possible ???

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2049]
## Linux distribution and version
Deepin OS 15.7

## Flatpak version
Flatpak 0.11.7-1deepin

## Description of the problem
I would like to update to the latest releases from here rather than the one provided by my distro ... u see ... the version i am running is way behind !!!

Is it possible to update the distro version to the latest release from here ... I don't mind uninstalling the prepackaged distro version and freshly install the latest one from here ...

If so please list out the commands that will help me install it fresh and clean to the version found here !!!

PS : will i run into any dependency problems that my distro might not have ? Let me know how i can check if all dependencies are installed on my system for a clean install from here.

**Comment by mwleeds** [comment]
Do you mean flatpak itself, not a flatpak app? If so, maybe [the Ubuntu PPA](https://flatpak.org/setup/Ubuntu/) works on Deepin; I'm not sure. Another option would be for you to compile flatpak yourself if you want to do that.

**Comment by aiamuzz** [comment]
> Do you mean flatpak itself, not a flatpak app? If so, maybe the Ubuntu PPA works on Deepin; I'm not sure. Another option would be for you to compile flatpak yourself if you want to do that.

yes ... exactly !!!
Any dependencies i need to check first ?

**Comment by aiamuzz** [comment]
as you can see the version currently installed on my system has the word `deepin` attached to the version number ... so uninstalling the default version and installing / building the flatpak as you suggest is the better way to go or ... just install/build over the default version ?

If i uninstall the default version ... 

What will happen to the flatpak apps/runtimes/platforms installed on my system already ?

I have a custom location on a separate partition dedicated for flatpaks only ... what will happen to the apps installed here ... will they get deleted too ?

would deleting the config file pointing to this custom location help in saving the already installed apps ? I could always create the config file pointing back to my custom location after installing the latest version ?

so lots of ... if's and but's ... just don't want to loose my apps at my custom location ... that is all ... :)

**Comment by aiamuzz** [comment]
Surprisingly i was able to dig out the following packages as deb installers ...

https://packages.debian.org/sid/libostree-1-1
https://packages.debian.org/sid/flatpak

installation went without any dependency issues ... and ...

viola ... `flatpak --version` throws up as `Flatpak 1.0.1` ... seems with a straight forward solution i was going round and round for nothing ...

**Comment by aiamuzz** [comment]
i managed to free myself of the distro version of flatpak ... however i am still not able to build from source ...  closing this thread !!!
