### ISSUE TITLE
GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2058]
## Linux distribution and version
Deepin OS

## Flatpak version
0.11.7-1deepin

## Description of the problem

Came across this issue when trying to get a newly added flatpak from here ... [INSTALLATION ISSUE](https://github.com/flathub/io.designer.GravitDesigner/issues/2)

[As i started facing an issue trying to run a flatpak app as i reported here](https://github.com/flatpak/flatpak/issues/2050)

I am running an update for all my flatpak apps ... and i am encounter this issue with more than one flatpak ...

```
Updating: com.google.AndroidStudio/x86_64/stable from flathub
[####################] Downloading: 897.7 MB/897.7 MB (1.0 MB/s)               
Error: Failed to update com.google.AndroidStudio/x86_64/stable: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

```

```
Updating: com.axosoft.GitKraken/x86_64/stable from flathub
[####################] Downloading: 268.2 MB/268.2 MB (779.7 kB/s)             
Error: Failed to update com.axosoft.GitKraken/x86_64/stable: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```

```
Updating: com.visualstudio.code/x86_64/stable from flathub
[####################] Downloading: 87.4 MB/87.4 MB (865.2 kB/s)               
Error: Failed to update com.visualstudio.code/x86_64/stable: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

```

**Comment by aiamuzz** [comment]
another one to the list ...

```
Updating: org.geogebra.GeoGebra/x86_64/stable from flathub
[####################] Downloading: 136.6 MB/136.6 MB (848.7 kB/s)             
Error: Failed to update org.geogebra.GeoGebra/x86_64/stable: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

```

while many other apps seem to updating fine ... none of them are running though !!!

**Comment by monperrus** [comment]
Just hit "While trying to apply extra data: apply_extra script failed" for installing `org.gnome.Platform`. 

```
        ID                                              Branch            Op           Remote            Download
 1. [✓] org.freedesktop.Platform.GL.default             19.08             i            flathub            92.1 MB / 92.6 MB
 2. [✓] org.freedesktop.Platform.VAAPI.Intel            19.08             i            flathub             8.6 MB / 8.7 MB
 3. [✗] org.freedesktop.Platform.openh264               2.0               i            flathub             1.2 MB / 916.8 kB
 4. [✓] org.gnome.Platform.Locale                       3.36              i            flathub            17.7 kB / 322.9 MB
 5. [✓] org.gnome.Platform                              3.36              i            flathub           348.7 MB / 322.9 MB

Warning: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 40704
```

Is there a known workaround?

**Comment by refi64** [comment]
`org.gnome.Platform`'s install succeeded, but installing openh264 mysteriously failed. Does it work if you try again now? Maybe it was just a temporary error?

**Comment by B00bleaTea** [comment]
i'm having a similar problem on `Manjaro Linux x86_64 5.9.16-1-MANJARO`
 ```
 
        ID                       Branch    Op   Remote    Download
 1. [|] com.visualstudio.code    stable    i    flathub   69.4 MB / 70.2 MB
        ID                       Branch    Op   Remote    Download
 1. [✗] com.visualstudio.code    stable    i    flathub   69.4 MB / 70.2 MB

Error: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.visualstudio.code: While trying to apply extra data: apply_extra script failed, exit status 256
```

and i tried `flathub repair` in sudo, user, user verbose and sudo verbose modes and the problem looks like it's either `flathub:runtime/org.kde.Platform/x86_64/5.14…`, `F: No installations directory in /etc/flatpak/installations.d. Skipping` or `org.freedesktop.Platform.openh264`

i opned an issue [Here](https://github.com/flatpak/flatpak/issues/4107) - if anyone find the solution, please leave a comment  [Here](https://github.com/flatpak/flatpak/issues/4107), thank you in advance

**Comment by AleMunin** [comment]
I don't know why this or https://github.com/flatpak/flatpak/issues/4107 was closed. This is still happening.

Also, for whatever reason, distrobox' own ubuntu flatpak didn't work.

```
flatpak uninstall --unused
flatpak update
flatpak repair
```

Didn't work.

I followed [this advice](https://askubuntu.com/a/1521206) but it didn't work (to be fair app armor wasn't on, but turning it on after adding the bwrap file didn't work) 

Quoting the post if anyone has this problem and more luck than me:


> Per this comment on the [bug report](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/2061728) for this issue:
> 
> Basically create the file /etc/apparmor.d/bwrap with the following contents :
> 
```
abi <abi/4.0>,
include <tunables/global>

profile bwrap /usr/bin/bwrap flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/bwrap>
}
```
> 
> and execute:
> 
```
sudo systemctl reload apparmor
```

PS: if you have it disabled for whatever reason you need to run `systemctl start apparmor` and `systemctl enable apparmor`

My workaround for now is installing vscode through yay on distrobox.

**Comment by ar1ja** [comment]
> I don't know why this or [#4107](https://github.com/flatpak/flatpak/issues/4107) was closed. This is still happening.
> 
> Also, for whatever reason, distrobox' own ubuntu flatpak didn't work.
> 
> ```
> flatpak uninstall --unused
> flatpak update
> flatpak repair
> ```
> 
> Didn't work.
> 
> I followed [this advice](https://askubuntu.com/a/1521206) but it didn't work (to be fair app armor wasn't on, but turning it on after adding the bwrap file didn't work)
> 
> Quoting the post if anyone has this problem and more luck than me:
> 
> > Per this comment on the [bug report](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/2061728) for this issue:
> > Basically create the file /etc/apparmor.d/bwrap with the following contents :
> 
> ```
> abi <abi/4.0>,
> include <tunables/global>
> 
> profile bwrap /usr/bin/bwrap flags=(unconfined) {
>   userns,
> 
>   # Site-specific additions and overrides. See local/README for details.
>   include if exists <local/bwrap>
> }
> ```
> 
> > and execute:
> 
> ```
> sudo systemctl reload apparmor
> ```
> 
> PS: if you have it disabled for whatever reason you need to run `systemctl start apparmor` and `systemctl enable apparmor`
> 
> My workaround for now is installing vscode through yay on distrobox.

Seems like the flatpak bot auto-closed it due to inactivity? I don't use flatpak and seems like people weren't interacting so maybe it's just automatic cleanup... Although a workaround was proposed in https://github.com/flatpak/flatpak/issues/4107#issuecomment-2424099343 which worked for a couple of people, so maybe try that :)
