### ISSUE TITLE
Racy assertion when updating an app/runtime

### ISSUE THREAD

**Issue by thiblahute** [flatpak/flatpak#206]
Sometimes doing:

```
flatpak update org.gnome.Platform 3.20
```

I get the following assertion:

```
OSTree:ERROR:libglnx/glnx-shutil.c:215:mkdir_p_at_internal: assertion failed: (lastslash != NULL)
```

I am also getting it on our build server:

https://ci.gstreamer.net/job/pitivi-flatpak/309/console

I am running `Flatpak 0.6.7` and `ostree 2016.6` on arch.

**Comment by matthiasclasen** [comment]
Looks like something you should report against libglnx or ostree.

**Comment by thiblahute** [comment]
This issue was moved to ostreedev/ostree#413
