### ISSUE TITLE
Can't find mount /oldroot/pkg on /newroot/pkg: No such file or directory RHEL7.1 FP 0.8.8

### ISSUE THREAD

**Issue by frankieliu** [flatpak/flatpak#2062]
## Linux distribution and version
Red Hat Enterprise Linux Server release 7.1 (Maipo)

## Flatpak version
Flatpak 0.8.8

## Description of the problem
Note my home is nfs4 mounted, the package was installed via --user from flathub
tmpfs in /run/user/<userid>

## Steps to reproduce
$  flatpak -vv run org.gnu.emacs -nw                               
XA: Allowing host-fs access                              
XA: Allowing x11 access                                                                                                                
XA: Allowing pulseaudio access                                          
XA: Failed to run in transient scope: No systemd user session available, cgroups not available

Can't bind mount /oldroot/pkg on /newroot/pkg: No such file or directory

**Comment by alexlarsson** [comment]
Is /pkg (on the host os) a symlink or something?

**Comment by frankieliu** [comment]
Hi Alex,

/pkg package seems to be an ldap automount, how is /pkg being used/referenced?
Thanks

**Comment by frankieliu** [comment]
I unmounted /pkg, and re-ran, it goes through.  Thanks for the hint.

**Comment by alexlarsson** [comment]
Yeah, i think there are some issues with automounts in 0.8, should work with more recent versions though
