### ISSUE TITLE
self-contained flatpak executable for old machine?

### ISSUE THREAD

**Issue by bdantas** [flatpak/flatpak#2067]
I have an Arch Linux machine that, for various reasons, uses a local repo--a snapshot from Arch's repository taken back in September 2015. Neither flatpak nor its dependencies were in Arch's repository back then, so my local repo doesn't have them either. The machine has linux kernel 4.1.6-1 and glibc version 2.22-1. 

I would very much like to use flatpak on this old machine. Is there a self-contained executable that contains flatpak, all required dependencies (bubblewrap, etc), and all required libraries? Something like a flatpak (gasp) AppImage?

**Comment by TingPing** [comment]
No. Honestly it sounds like you made your own mess so you should know how to compile software in it. Considering Flatpak builds fine on Ubuntu 16.04 I imagine it is doable on 2015 packages.

**Comment by bdantas** [comment]
Before rolling up my sleeves and compiling the whole suite, just thought I'd ask. Thanks for the quick reply.

**Comment by bdantas** [comment]
This is all that was required:
```
$ curl https://nixos.org/nix/install | sh
$ . $HOME/.nix-profile/etc/profile.d/nix.sh
$ nix-env --install flatpak
```

**Comment by TingPing** [comment]
Flatpak requires a `suid` binary, its not something one should install into `$HOME`...

**Comment by bdantas** [comment]
You are right:

```
$ flatpak run org.foo.Bar
bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems.
error: ldconfig failed, exit status 256
$ sudo flatpak run org.foo.Bar # this works
```
What is the best solution? I figure anything would be better than running every application with elevated privileges.

**Comment by TingPing** [comment]
Thats exactly what I was talking about, the only safe way is if `bwrap` is owned by root and you add suid.

**Comment by bdantas** [comment]
Yes, that did the trick:

```
$ sudo chown root:root /nix/store/q67sv4bhq6snp4r6cbh79s9zknvqg78h-bubblewrap-0.3.0/bin/bwrap
$ sudo chmod u+s /nix/store/q67sv4bhq6snp4r6cbh79s9zknvqg78h-bubblewrap-0.3.0/bin/bwrap
$ flatpak run org.foo.Bar # works!
```

Thank you, TingPing.
