### ISSUE TITLE
CentOS?

### ISSUE THREAD

**Issue by antmak** [flatpak/flatpak#208]
Do you plan to release flatpak for CentOS 7 ? Maybe you have information about such works in other teams?

**Comment by antmak** [comment]
Ok. I have built. Runnig with kernel-lt-4.4 (from elrepo) and --no-desktop option. I had to rebuild some packages from Fedora25 src-rpms.

**Comment by matthiasclasen** [comment]
Yes, we plan to release flatpak for RHEL7. Before we can do so, we need to add some compat code to deal with the lack of systemd --user (you've discovered --no-desktop as workaround).
