### ISSUE TITLE
Deployed commits are pruned by ostree

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2085]
Currently if you do an update without deploying it (such as via `flatpak update --no-deploy`), the deployed commit will be pruned in the next prune operation. This is not a problem for any running apps using the files because they're still in `/var/lib/flatpak/app/...` or `/var/lib/flatpak/runtime/...`, but it is a problem for at least the `create-usb` command, which reads the commit hash from the `deploy` file, and then fails to pull the commit with e.g. `error: Importing fa2eab670fb99da2c8e95460eb57304d52ddb136c9f81657f35cdfa2c0bc800e.commit: fstatat(fa/2eab670fb99da2c8e95460eb57304d52ddb136c9f81657f35cdfa2c0bc800e.commit): No such file or directory` if a prune happened.

So after discussion with @alexlarsson it seems one solution would be to have flatpak inform libostree of what commits are deployed, and preventing pruning of them. We can also have the `create-usb` command use the latest commit rather than the active one, but that could be counterintuitive.

We should also think about the interaction with `eos-updater-prepare-volume`, because we don't want to put the in-use version of the OS along with the not-yet-deployed versions of flatpaks on a USB, or the not-yet-deployed version of the OS along with the in-use versions of flatpaks (Endless OS updates have dependencies on flatpaks).

```
0 ✓ mwleeds@localhost /var/lib/flatpak (2 keys)
↳ cat runtime/org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0/active/deploy 
eos-sdkfa2eab670fb99da2c8e95460eb57304d52ddb136c9f81657f35cdfa2c0bc800e0I0 ✓ mwleeds@localhost /var/lib/flatpak (2 keys)
↳ cat repo/refs/remotes/eos-sdk/runtime/org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0 
91cf63a7be808ad1c885554381a0f76b3588a3c697357c12822fb99478c3da95
0 ✓ mwleeds@localhost /var/lib/flatpak (2 keys)
↳ ls runtime/org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0/
active  fa2eab670fb99da2c8e95460eb57304d52ddb136c9f81657f35cdfa2c0bc800e
0 ✓ mwleeds@localhost /var/lib/flatpak (2 keys)
↳ flatpak info runtime/org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0/active/deploy
Ref: runtime/org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0
ID: org.freedesktop.Platform.Icontheme.EndlessOS
Arch: x86_64
Branch: 1.0
Origin: eos-sdk
Active commit: fa2eab670fb99da2c8e95460eb57304d52ddb136c9f81657f35cdfa2c0bc800e
Latest commit: 91cf63a7be808ad1c885554381a0f76b3588a3c697357c12822fb99478c3da95
Parent: -
Location: /var/lib/flatpak/runtime/org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0/fa2eab670fb99da2c8e95460eb57304d52ddb136c9f81657f35cdfa2c0bc800e
Installed size: 143.4 kB
0 ✓ mwleeds@localhost /var/lib/flatpak (2 keys)
↳ ls repo/objects/fa/2e*
repo/objects/fa/2e18569a531de4599f90b41a47c9a21dc961621c8342ef8116bd59421b2383.file
repo/objects/fa/2e2045fe2c941a2e115447d9ebd211051ec12388ee174a7c7d8b49dca93364.file
repo/objects/fa/2e2a6c2d42855825fdb0c453997555cec6f122f1bf759d77ea3b22cb3d25c5.file
repo/objects/fa/2e4fb7df98add64cc85c15891b969b5ba5835e7c9568802c505043a746a72a.file
repo/objects/fa/2ee84dfa5e6a95083cd2f603dbbfbaa92939bd4299108dc52da3516db0d9ad.file
```

**Comment by cgwalters** [comment]
Similar to https://github.com/ostreedev/ostree/pull/1566/commits/47655d730727970c3bd04107d103fc5f9581d641

Maybe flatpak should also add "deployment refs" just like `OstreeSysroot` does?
The other option is to do what that new libostree API does, pass the deployed commits down as strong roots before pruning - but the problem with that is it doesn't play nicely with multiple processes pruning the repo.

**Comment by pwithnall** [comment]
> Maybe flatpak should also add "deployment refs" just like `OstreeSysroot` does?

That came up in my head too. Then there’s a single, OSTree-based, serialisation point for the version of each deployed app.
