### ISSUE TITLE
Install causes loss of apps using Snap from GNOME desktop, destructive to user experience

### ISSUE THREAD

**Issue by SwitchedToGitlab** [flatpak/flatpak#2087]
## Linux distribution and version
Ubuntu 18.04.1
## Flatpak version
1.0.1 installed via ```apt install flatpak``` using this [PPA](http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu)
## Description of the problem
Flatpak installation overwrites XDG_DATA_DIRS in GNOME, which is destructive to systems using snapd, as the desktop files are located based on paths included in the XDG_DATA_DIRS environment variable.

I actually couldn't figure out all the places that this was set on install, however I know I found at least 3 different places. After removing these references in 3 different places and I was still unsuccessful in getting XDG_DATA_DIRS to be set properly I uninstalled flatpak from my system completely and functionality was restored.

## Steps to reproduce
1. Install Firefox on Ubuntu 18.04.1 using snapd:
```snap install firefox```

2. Install Flatpak on Ubuntu 18.04.1
```sudo add-apt-repository ppa:alexlarsson/flatpak
 sudo apt update
 sudo apt install flatpak
```

3. Reboot

4. Note that the XDG_DATA_DIRS environment variable is different now, and doesn't list snap, and Firefox is not available in the GNOME Shell Applications menu or Search results. 

## Fix
```apt remove flatpak```

**Comment by smcv** [comment]
This is basically another way to say #25. Flatpak and Snap do similar path manipulations, and on your system, Flatpak "won".

**Comment by matthiasclasen** [comment]
I believe this is fixed in master
