### ISSUE TITLE
Need portal for launching other applications

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#21]
For example, inkscape can optionally open a file with the GIMP (by default) or another custom-specified editor in preferences → "Bitmaps" → "Bitmap editor".

We can't safely launch host-side apps in general, but a portal could gate this via some kind of user interaction.

**Comment by alexlarsson** [comment]
This is somewhat related at least in the design to https://github.com/flatpak/flatpak/issues/76 because you often want to open a (local) file uri in a different app.

**Comment by matthiasclasen** [comment]
this is being done in xdg-desktop-portal

**Comment by amtlib-dot-dll** [comment]
I have not tested it yet, but is it a security leak when malicious app inside the sandbox uses this portal to execute arbitrary code? Thanks

**Comment by TingPing** [comment]
> I have not tested it yet, but is it a security leak when malicious app inside the sandbox uses this portal to execute arbitrary code? Thanks

It would be technically possible yes but the user should be prompted (like they are for opening default handlers already) which makes it an explicit user decision at least.
