### ISSUE TITLE
ld: BFD (GNU Binutils) 2.27.0.20160806 internal error, aborting at ../../bfd/merge.c:905 in _bfd_merged_section_offset

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#2100]
## Linux distribution and version

Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-134-generic x86_64)

## Flatpak version
Flatpak 0.99.3
## Description of the problem
When building our GIMP nightly, it fails repeatedly when building i386 during the linking of our file-csource plug-in, with the following error:

```
/usr/lib/gcc/i586-unknown-linux/6.2.0/../../../../i586-unknown-linux/bin/ld: BFD (GNU Binutils) 2.27.0.20160806 internal error, aborting at ../../bfd/merge.c:905 in _bfd_merged_section_offset
```

I could find various occurrences of this error on the web, but usually people said it happened intermittently (in my case, I reproduced it every time I tried today and yesterday, which means 4 out of 4 times.

Also in all the reports I saw about this, I couldn't find any clear reason and solution.

Note: the build in x86_64 is fine, this only happens with the i586 linker (ARM and AARCH64 not tried with this manifest).

## Steps to reproduce

- I build this manifest: https://gitlab.gnome.org/GNOME/gimp/blob/master/build/flatpak/org.gimp.GIMP-nightly.json
- The command is:

```
flatpak-builder --ccache --force-clean --keep-build-dirs --jobs=1 --arch="i386" \
                       --state-dir="${STATEDIR}" "${INSTALLDIR}" org.gimp.GIMP-nightly.json
```

Note that I use `--jobs=1` (important precision as some people say they had this error when running make with several jobs; this is not my case).

The logs of the build: [gimp-flatpak-build-i386-nightly.log](https://github.com/flatpak/flatpak/files/2384239/gimp-flatpak-build-i386-nightly.log)

I am thinking that maybe the x86 ld bundled in the flatpak environment (is it in a runtime?) is buggy? Do you have any other idea?

**Comment by alexlarsson** [comment]
This is really an issue with the tools (ld) in the runtime. What runtime/sdk version are you using?

**Comment by alexlarsson** [comment]
Oh, i see it is gnome 3.28. Can you try again? We recently updated the tooling in the base sdk, maybe its fixed now?
