### ISSUE TITLE
Flatpak upgrade ... updating to latest upstream releases directly ?

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2106]
## Linux distribution and version
Deepin 15.7

## Flatpak version
1.0.1 from [Debian](https://packages.debian.org/sid/flatpak) ... a deb file manually installed.

## Question
Finally i was able to get rid of the old version that was distributed by my OS repo's and install a more recent version from the Debian repo's.

My question is will i have to keep upgrading to the more recent version of Flatpak by keeping a watch on the above debian package page and will have to download and install the latest, each time a new update is made available in the debian repo's ... 

... or ...

**Will it upgrade itself the moment a newer version is available at the above debian package / repo page ???**

... or ...

**Is there any way or a command that i can run and upgrade directly from the flatpak repo here on github (now that i am already on 1.0.1 thanks to debian repo)? ... It would be fantastic to have such an option as it takes out the need of being at the mercy of individual OS repo's**

**Comment by aiamuzz** [comment]
An option such as ...

`flatpak upgrade` ... **would be a fantastic option to upgrade directly from upstream release ... cutting out middle men OS repo's ... don't you think ?**

**Comment by TingPing** [comment]
Flatpak cannot update itself, it isn't your distros package manager and doesn't want to be.

**Comment by aiamuzz** [comment]
> My question is will i have to keep upgrading to the more recent version of Flatpak by keeping a watch on the above debian package page and will have to download and install the latest, each time a new update is made available in the debian repo's ...
> 
> ... or ...
> 
> Will it upgrade itself the moment a newer version is available at the above debian package / repo page ???

what about my first question ... will i have to download deb file each time from the debian site and install ?

> Flatpak cannot update itself, it isn't your distros package manager and doesn't want to be.

meaning no package in linux can update by itself ?
or 
its just flatpak doesn't want to for some reason ?

**Comment by TingPing** [comment]
> what about my first question ... will i have to download deb file each time from the debian site and install ?

Well that is a hack in the first place, but yes.

> meaning no package in linux can update by itself ?

That isn't how Linux systems are designed.
