### ISSUE TITLE
No access to /usr/share

### ISSUE THREAD

**Issue by create3000** [flatpak/flatpak#2107]
## Linux distribution and version
holger@mars:~/Projekte/Titania-flatpak$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

## Flatpak version
holger@mars:~/Projekte/Titania-flatpak$ flatpak --version
Flatpak 0.11.7

## Description of the problem
Although --filesystem=host is specified in the .json configuration file, /usr is different from the real /usr, especially /usr/share is not accessible. This means for instance that installed python modules are not accessible from within the flatpak.

**Comment by TingPing** [comment]
You can't just mount the host `/usr` on top of the runtime `/usr` as they would conflict. The `host` option mounts it in `/var/run/host` but don't expect being able to run binaries from there as that isn't its intention and will generally be broken.

There are many workarounds to your problem, an easy one is call `pip3 install --user` inside the sandbox (ideally setting a custom python home to not conflict with the host).

**Comment by Alexander-Wilms** [comment]
This is by design. Some directories of the host are blacklisted, since the /usr is provided by the runtime.
