### ISSUE TITLE
[RFE] Caching  software - On the same host

### ISSUE THREAD

**Issue by dmedri** [flatpak/flatpak#2111]
## Linux distribution and version

misc, flatpak on 27/28 with last updates

## Flatpak version
see above. (on fed27, ver. 1.0.0)

Browsing online on project website, I didn't find any useful reference or future plan. So, this is a RFE, a request for enhancement, or an open discussion about the implementation of a general idea.

Caching software packages, on the same host
-----------------------------------------------------------
With flatpak we could have on the same host, multi versions of runtimes, one for the system and one for every user that install on his home directory. So, the caching area should be used to store the same software package from the same repository. Since this option need extra disk space for a special need, it should be optionally enabled.

**Comment by mwleeds** [comment]
User-installed apps can already use system-installed runtimes, so I'm not sure it makes sense to add another caching mechanism

**Comment by matthiasclasen** [comment]
Yes. If space is a concern, and the system has multiple users, just install apps and runtimes systemwide.
