### ISSUE TITLE
flatpak broken on centos 7

### ISSUE THREAD

**Issue by TonyBostonTB** [flatpak/flatpak#2115]
## Linux distribution and version
CentOS Linux release 7.5.1804 (Core)
## Flatpak version
Flatpak 0.8.8
## Description of the problem
AFAIK there was an update some days ago which broke flatpak apps
The error is: error: Unknown socket type ssh-auth, valid types are: x11, wayland, pulseaudio, session-bus, system-bus
## Steps to reproduce
start any installed flatpak app

**Comment by TingPing** [comment]
Only one or two packages use `ssh-auth`, so everything else will work. If you want that application simply update using this repo: https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/
