### ISSUE TITLE
document how to create *.flatpakrepo files

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#212]
on http://flatpak.org/developer.html it would be nice if we had a section describing how to make *.flatpakrepo files inside the "Distributing Applications" section with details on the format, some ideas:

- that the GPGKey= field requires the GPGKey itself which you can get by doing ""base64 --wrap=0 < foo.gpg"

- that it should link to the application repo and not the runtime repo. 

- what command to use to install the *.flatpakrepo files.

**Comment by matthiasclasen** [comment]
Added a section for that

**Comment by bastianilso** [comment]
where can i find it?

**Comment by matthiasclasen** [comment]
Developer page,  distributing applications. Theres a new section called Referring to repositories

**Comment by bastianilso** [comment]
ah, very useful, thanks!
