### ISSUE TITLE
Should refuse to install flatpakrefs lacking RuntimeRepo=

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#2120]
The problem: developers writing flatpakref files frequently forget to include the RuntimeRepo= line. This means that the flatpakref works only for users who already have the remote installed, likely including the developer who wrote it, but will fail for everyone else.

flatpak could surface this problem by simply refusing to install from a flatpakref that lacks this line, so developers notice the issue. In the short term, it would break many existing flatpakrefs, but in the long term they will get fixed as developers notice the problem.

**Comment by matthiasclasen** [comment]
Refusing to install when we can seems a bit drastic, unless this is some opt-in test-my-flatpakref mode

**Comment by mcatanzaro** [comment]
There's no point in an opt-in test-my-flatpakref mode, because developers won't use it if it's opt-in.

**Comment by mcatanzaro** [comment]
I mean, anybody who knows about that would also know about RuntimeRemote, probably?

**Comment by mwleeds** [comment]
We could print a warning?
