### ISSUE TITLE
Whitelist go for Atom

### ISSUE THREAD

**Issue by Znert** [flatpak/flatpak#2126]
## Linux distribution and version
Fedora 28
## Flatpak version
1.0.2
## Description of the problem

I know that this is not a bug, but more a consequence of sandboxing. However, I don't know where else to post this, so sorry in advance if I'm wrong here.

My issue is with  too strict sandboxing:

I have installed Atom and want to write golang code with it. Now the `go-plus` package requires `go` and some go-binaries to be installed. However, `go-plus` cannot find `go` in `/usr/local/go/bin` as it's not visible in the sandbox. `go` also installs libraries/binaries to `~/go/bin` which must also be accessible by Atom.

Things I have tried so far:

* Giving Atom access to the host file system. Although as I learned later, io.atom.Atom's metadata already has `filesystems` set to `host`, so not much I can improve there.
* Manually setting the sandbox's `$PATH` variable to the same as I have set outside the sandbox (btw, isn't there an easier way to append to the `$PATH`? Had to investigate with `flatpak enter` to see what it was set to and then append my stuff...),  but as I learned, even though Atom has access to the host filesystem, it cannot read `/usr/local/go/bin` due to sandboxing.

## Steps to reproduce

1. Install `golang` (via your systems software manager or following https://golang.org/doc/install)
2. Install Atom from flathub
3. From `Edit -> Preferences -> Install` search and install the `go-plus` package (https://atom.io/packages/go-plus)
4. `go-plus` will ask you to install required go libraries, accept the request (if the popup is not showing, restart Atom)
5. Because `go-plus` cannot find `go` or any of the installed libraries it will fail silently. Most notably, even after restarting Atom `go-plus` will still ask you to install all `go` libraries. This also mean, that any `go-plus` related tools will not work.

You can also try to manually install all libraries following the steps at https://github.com/joefitzgerald/go-plus#installing-missing-tools but it won't fix or change anything.

**Comment by TingPing** [comment]
Flatpak doesn't whitelist any binaries and it never will that is entirely counter to what it is.

Since `go` is an example of a statically linked blob you can probably already call `/var/run/host/usr/bin/go` from the sandbox now and it will work. (Do not expect that to work for most things).

The real solution is for extensions to be made for tools.

**Comment by Znert** [comment]
Thanks for your quick answer :)

I didn't know that the host filesystem is linked to `/var/run/host`, so thanks alot for this information.

I also managed to hack it together by setting the `PATH` variable in io.atom.Atom's metadata as I mentioned before to include `var/run/host/usr/local/go/bin` and `~/go/bin` (not really happy with the solution, but well, at least it works...).

Do you see any better alternative to my "fix"? Or even more important: an generic approach to such problems? I don't think that it's that uncommon for this kind of situations to appear (especially when apps like Atom allow third party extensions).

For now I will definitly report this behaviour to `go-plus` as they currently do not provide any means to allow setting where the `go` binary is, which is probably a bad idea anyways.

**Comment by TingPing** [comment]
> For now I will definitly report this behaviour to go-plus as they currently do not provide any means to allow setting where the go binary is, which is probably a bad idea anyways.

Indeed that should be improved.

> Do you see any better alternative to my "fix"? Or even more important: an generic approach to such problems?

Yes we plan on making Flatpak extensions for such tools.

**Comment by haraldh** [comment]
I also see this problem.

Additionally on Fedora `/run/host/usr/bin/go` is an **absolut** symlink to `/etc/alternatives/go`, which points to `/usr/lib/golang/bin/go`.

Workaround for the reference:
```
[Environment]
PATH=/run/host/usr/lib/golang/bin:/bin:/sbin:/usr/bin:/usr/sbin:/run/host/usr/bin:/app/share/atom
```

**Comment by kirbyfan64** [comment]
FWIW instead of editing the raw file, you can use `sudo flatpak override your.app.id.here --env=PATH=YOUR:PATH:VALUE:HERE`.
