### ISSUE TITLE
Have to run the `remote-add` for every custom install locations !!!

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2127]
## Linux distribution and version
Deepin 15.7

## Flatpak version
1.0.1

## Description of the problem

`flatpak --installation=myFlatpaks remote-add flathub https://flathub.org/repo/flathub.flatpakrepo`

`flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo`

Seems currently I have to run the `remote-add` for every custom install locations ... else the `install flathub` does not work depending on where the installation is pointed to.

Even `flatpak update` needs to be run multiple times depending on the number of custom installation locations ... [Issue already opened here](https://github.com/flatpak/flatpak/issues/2006)

## Solution

**Shouldn't this be a one time affair running `remote-add` and `update`commands ???**

**Comment by matthiasclasen** [comment]
No. Flatpak installations are more or less independent (with some exceptions). But if you want to install something from a remote into an installation, that remote must be configured for that installation.

Out of curiousity, how many custom installations do you have? The expected case is that people just have the default (system and user) ones, and really only use one or the other...

**Comment by aiamuzz** [comment]
@matthiasclasen  ... hmmmmm ...

besides the default ... i have one other location ... a dedicated partition for only flatpak applications ... 

i have found that with this kind of setup ... i save the trouble of re-installing each and every app all over again ... between a corrupt OS re-installations(which is unavoidable at times) ... the bigger goal however being to be able to run the same set of applications from a multiboot linux installation setup ... somewhat like how the /home partition could be used across multi linux installations.

**Comment by aiamuzz** [comment]
@matthiasclasen  ... i use both the default and custom installation locations ...

you could say ... i install an app that i am new to on the default system location and those which i like and want to keep ... i use the custom installation location (my flatpak partition) ... as the whole idea of the custom installation location is to have my favorite apps available immediately after OS reinstallations or to other linux distros on my system.

**Comment by mwleeds** [comment]
Seems like this is desired behavior
