### ISSUE TITLE
flatpak permission-list & show crash: g_dir_close: assertion 'dir != NULL' failed

### ISSUE THREAD

**Issue by mvuets** [flatpak/flatpak#2130]
## Linux distribution and version
Fedora release 28

## Flatpak version
1.0.2

## Description of the problem
Flatpak CLI commands **permission-list** and **permission-show** do not work and the error message does not help to figure out why.

## Steps to reproduce
```
$ flatpak permission-list

(flatpak permission-list:27242): GLib-CRITICAL **: 17:09:43.685: g_dir_close: assertion 'dir != NULL' failed

$ flatpak permission-show net.ankiweb.Anki

(flatpak permission-show:27251): GLib-CRITICAL **: 17:09:44.411: g_dir_close: assertion 'dir != NULL' failed
```

**Comment by gun1x** [comment]
I have the same issue on fedora.
