### ISSUE TITLE
Suggestion: rename command permission-list to permissions

### ISSUE THREAD

**Issue by mvuets** [flatpak/flatpak#2131]
## Linux distribution and version
Fedora release 28

## Flatpak version
1.0.2

## Description of the ~~problem~~ suggestion
I've figured that there is a hidden command **remote-list** and **remotes** is its alias. Perhaps would be nice to have **permissions** as an alias to **permission-list** for brevity and consistency reasons too.

**Comment by matthiasclasen** [comment]
If we were to do this for consistency, we'd also have to add "documents" as an alias for "document-list".
I could go with that, lets see what others think.
