### ISSUE TITLE
GPG signatures found, but none are in trusted keyring winepak

### ISSUE THREAD

**Issue by bibiyanki** [flatpak/flatpak#2138]
## Flatpak version= i don't know maybe last
hello
i follow step for add reposetory of winepak, i think it's work because it don't tell nothing and return to the line
and when i try install app or just see list, it tell me
flatpak remote-ls winepak
error: GPG signatures found, but none are in trusted keyring

what's wrong
thank u

**Comment by mwleeds** [comment]
Duplicate of https://github.com/flatpak/flatpak/issues/1450
