### ISSUE TITLE
Relax min-free-space-* parameter for metadata refs

### ISSUE THREAD

**Issue by uajain** [flatpak/flatpak#2139]
## Flatpak version
1.0.2
## Description of the problem
From internal Endless ticket (T23758) : 
>I think it might be worth coming up with a way to skip or relax the space check for the operations where flatpak is pulling metadata refs (such as appstream2/x86_64 or ostree-metadata), so that updating/refreshing housekeeping data is more likely to work. It should always be significantly smaller than this 500MB.

## Steps to reproduce
Get free space below 500MB (or increase min-free-space-size parameter manually to greater than current free space). You should be able to hit something similar below:
```
uajain@endless:~/gnome-software$ flatpak remote-info  flathub org.kde.Platform//5.9
error: min-free-space-size 500MB would be exceeded
```

**Comment by uajain** [comment]
I added a OSTree flag[1] in OSTree to disable the check during the pull but later I realized that flatpak also sets `inherit-transaction` which doesn't allow OSTree to use it's own transaction. In fact, flatpak explicitly starts and commits OSTree transactions (using `prepare_transaction()` and `commit_transaction()` OSTree APIs).

Setting `inherit-transaction` makes the use of this flag impossible. OSTree flags get into action only during `ostree_repo_pull_with_options` but flatpak has prepared the transaction much earlier than that. As there is initial check for free space inside prepare_transaction(), the operation will just error out there, because it didn't get a chance to reach  `ostree_repo_pull_with_options` (and read the disabled min-free-space flag).

Can we set the `inherit-transaction` flag selectively (like `disable-static-deltas` in `get_common_pull_options`) ? I don't know what repercussions it may have on the pull code.

[1] https://github.com/endlessm/ostree/pull/140

**Comment by ramcq** [comment]
@cgwalters @alexlarsson Any idea on ostree API to handle this?

**Comment by uajain** [comment]
I believe the rework this needs is:
* Lift off disk space check from prepare_transaction()
* Enforce disk space check **only** for writing content objects (`OSTREE_OBJECT_TYPE_FILE`)

There are many metadata object types(`.dirmeta`, `.dirtree`, `.commit`, `.commit-tombstone`, `.commitmeta`, `.payload-link`) and if they are relatively small in size (as what we believe !), the above rework makes sense to me. Thoughts?

**Comment by mwleeds** [comment]
Another possible implementation would be to have another hard-coded min-free-space value for metadata, such as 1 MB

**Comment by uajain** [comment]
> Another possible implementation would be to have another hard-coded min-free-space value for metadata, such as 1 MB

hmm, it would be better if we can have some real values of metadata object sizes. So as to decide 1MB or x MB etc. Even having that, we need to lift off disk space check from prepare_transaction.

**Comment by mwleeds** [comment]
Flathub `ostree-metadata` seems to be 2 MB stored in the commit object
```
0 ✓ mwleeds@endless /var/lib/flatpak/repo (2 keys)
↳ cat refs/remotes/flathub/ostree-metadata 
6df99753b361ff2703ba10560bc002f834754bb29bbd6e2ec8fa2bef25bfd43a
0 ✓ mwleeds@endless /var/lib/flatpak/repo (2 keys)
↳ ls -lh objects/6d/f99753b361ff2703ba10560bc002f834754bb29bbd6e2ec8fa2bef25bfd43a.commit*
-rw-r--r-- 1 root root 1.8M Dec  4 13:09 objects/6d/f99753b361ff2703ba10560bc002f834754bb29bbd6e2ec8fa2bef25bfd43a.commit
-rw-r--r-- 1 root root  569 Dec  4 13:09 objects/6d/f99753b361ff2703ba10560bc002f834754bb29bbd6e2ec8fa2bef25bfd43a.commitmeta
```

**Comment by uajain** [comment]
This is now addressed by the OSTree PR : https://github.com/ostreedev/ostree/pull/1779

Closing.
