### ISSUE TITLE
Discourage or prohibit vendor-prefixed desktop file export

### ISSUE THREAD

**Issue by ramcq** [flatpak/flatpak#2142]
A little-known historical corner of the desktop ID spec is that stuff installed in share/applications/vendor/bla.desktop should be handled (eg by shell) as if it was named vendor-bla.desktop. Flatpak allows such exports provided bla matches the app ID, however in practice, anywhere else the vendor- prefix is added on, the invariant of the app ID matching the desktop name (appearing in GDesktopInfo APIs etc) is broken, which is pretty irritating for anything handling app renaming (such as pinning icons on the taskbar, Endless's icon grid, etc). It's something we have to support now given it was used in our own built-from-our-old-debs Flatpaks, however in the interests of safety/sanity, I suggest that we move towards some kind of deprecation strategy - perhaps have flatpak-builder or flatpak build-export give a noisy warning if these are used, and then later drop them?

**Comment by matthiasclasen** [comment]
I agree 100%. We should just not support the vendor prefix thing in flatpak

**Comment by matthiasclasen** [comment]
Do we have any apps on flathub or elsewhere that reply on the vendor prefix convention ?

**Comment by ramcq** [comment]
Endless had some from our first run of deb -> Flatpak, but we are killing almost all of those this month. ostree ls on Flathub shows 0 vendor prefix apps.
