### ISSUE TITLE
lex: command not found

### ISSUE THREAD

**Issue by linuxhw** [flatpak/flatpak#2144]
## Linux distribution and version
Ubuntu 16.04

## Flatpak version
1.0.2

## Description of the problem
Can't build source code of the `hwinfo` program. `make`, `gcc` and other basic tools are available, but not `lex`. How to tell the `flatpak-builder` to use `lex` from host `/usr/bin`?

## Steps to reproduce
* Build `hwinfo` source code by `flatpak-builder`.

Thank you.

**Comment by mwleeds** [comment]
You could probably give more specific steps to reproduce

**Comment by mwleeds** [comment]
But I think the answer is, if something is not in the Sdk you're using (e.g. `org.gnome.Sdk`) you should build it as a module. Otherwise the build isn't reproducible by others who might not have `lex` on their host OS.

**Comment by TingPing** [comment]
`flex` is in the Sdk which is what I believe it should be using.

**Comment by linuxhw** [comment]
I've added `flex` as a module because `hwinfo` requires `lex` (alias to `flex`). Probably you need to add this alias to Sdk to build projects like https://github.com/openSUSE/hwinfo without problems. Modern `flex` packages provide `lex` alias.

Thank you.

**Comment by TingPing** [comment]
> I've added flex as a module 

Just symlink `/app/bin/lex` to `/usr/bin/flex` or patch `hwinfo` to support both.
