### ISSUE TITLE
Flatpak should export other flatpak apps icons

### ISSUE THREAD

**Issue by loupianche** [flatpak/flatpak#2145]
Passbook is a new password manager for GNOME:
https://wiki.gnome.org/Apps/Passbook

BTW, when running on Flatpak, it can't detect others flatpaks applications icon, example:
https://adishatz.org/Passbook.jpg

Fractal is a flatpak app. Passbook is running as ArchLinux package and able to read Fractal icon.
But if I run Passbook as a flatpak, it can't access Fractal icon because XDG_DATA_DIRS does not contain this icon.

So when running as Flatpak, /home/loupianche/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/ should be exported.

**Comment by matthiasclasen** [comment]
That is intentional. Flatpak sandboxing isolates apps from the rest of the system - and from each other.

**Comment by loupianche** [comment]
Intentional? Flatpak sandboxing allow apps to access icons from the system, no valid reason for me to not give access (read only) to flatpak icons.

**Comment by matthiasclasen** [comment]
I don't think we want to leak information like what other apps are installed into every sandbox.

I'm not sure a password manager like this is very compatible with the idea of sandboxing, tbh.

**Comment by loupianche** [comment]
I guess you are right ;) Closing this one.
