### ISSUE TITLE
flatpak programs install to an unexpected name.

### ISSUE THREAD

**Issue by james-lawrence** [flatpak/flatpak#2148]
this is likely more a packaging issue than a flatpak issue but not sure where to file the issue
so starting here.

## Linux distribution and version
4.18.10-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 26 09:48:22 UTC 2018 x86_64 GNU/Linux

## Flatpak version
Flatpak 1.0.2

## Description of the problem
atom installed as io.atom.Atom instead of atom. this is unexpected and means most documentation for the application on the web will be incorrect when using the installation from flatpak.

## Steps to reproduce
installed atom from gnome software and dl.flathub.org

try to run `atom .` in a directory

**Comment by aiamuzz** [comment]
> atom installed as io.atom.Atom instead of atom

@james-lawrence ... there is nothing wrong with `io.atom.Atom` flatpak app install that way ... flatpak packages install with the reverse domain name ...

just run this command from the terminal ...
`flatpak run io.atom.Atom`

If atom applicatin opens ... then there is nothing wrong with the way the Atom Flatpak has got installed !

**Comment by james-lawrence** [comment]
@aiamuzz yes there is something wrong with that name.

its not used anywhere except by flatpak. its unexpected behaviour, and flatpak should attempt to integrate well with current systems. having its own binary naming conventions is a terrible idea.

**Comment by james-lawrence** [comment]
even worse this magic name isn't exposed anywhere to the user. so any CLI programs installed by flatpak will take extra effort to determine how to run them by users....

**Comment by matthiasclasen** [comment]
Flatpak works hard to integrated with the desktop. It installs desktop files and whatnot, precisely so you don't have to run the app from the commandline, but can use your favorite desktop launcher, be it kwin or gnome-shell.

To make your life easier as a commandline user, flatpak also installs a shell wrapper in ~/.local/share/flatpak/exports/bin, matching the app ID, ie io.atom.Atom. If you want, you can easily add a shell alias to get your commandline back:

export PATH=$PATH:$HOME/.local/share/flatpak/exports/bin
alias atom=io.atom.Atom

**Comment by james-lawrence** [comment]
@matthiasclasen you're both missing my point. I'm not asking for help on finding a workaround, I've already done this on my own.

integrating with the desktop includes the terminal. its not enough to make a desktop file.
if I want to open atom in a particular directory for example I'm going to use the command line.

_**I'm pointing out flatpak has a basic usability issue. Now the question is how are we going to fix the issue.**_

**Comment by james-lawrence** [comment]
> You are somewhat aggressive at making your case.

sorry for making sure my viewpoint is being clearly communicated. given the responses so far it did not seem that I was being clear enough.

>There are a number of commandline applications on flathub

if they are following this convention(?) that the atom package has, then my assessment is only reinforced.

>But it is there for a good reason

which is? I doubt its technical in nature as only reason I can think of is to prevent conflicts in naming (and thus security risks), which there are far better ways of handling that which do not include foisting it onto the user to deal with immediately.

to be clear I ran into this within 5 minutes of installing my first flatpak application. its not like it was a rare edge case that only came up months after using the system.

**Comment by matthiasclasen** [comment]
The reason is that we cannot allow conflicts between files installed by different apps. You may consider this 'just a technicality', but it is pretty fundamental to providing an experience that both user and app developers can trust. Citing an example from another issue discussing this: we can't let a fart app to pretend that it is firefox.

Therefore, we  only allow applications to export files with names that are starting with the app ID
(in the example here, io.atom.Atom). We provide an easy way to get their familiar commandline
back, as I described above.

**Comment by james-lawrence** [comment]
side note: what is to prevent me from make a .desktop file that looks identical to a well known application? that is just as much a security risk.

**Comment by matthiasclasen** [comment]
Well, we can just agree to disagree, I think, and you can find a system that suits your preferences ?

**Comment by matthiasclasen** [comment]
to answer your question: what you do on your own system is not much of a concern, and flatpak is not involved in it.

**Comment by aiamuzz** [comment]
@james-lawrence  ...  a heated aggressive posture is out of place in an open source environment ... for the simple fact that nobody owe's anybody anything !!! ... and that's that ... respect to the contributors of an open source effort can never be over done !!!

If only your tone and attitude were right ... @matthiasclasen ... would have certainly pointed you to this [WIP](https://github.com/flatpak/flatpak/pull/2091) ... he himself has stated what the best way could possibly be(pretty much addressing your concern) ... there are multiple threads here which have deliberated over it or at least around !!!

**Comment by james-lawrence** [comment]
@aiamuzz to be honest, nothing I've said has been rude or insulting towards either of you beyond pointing out the technical inaccuracies in statements and why this behavior by flatpak is problematic from a user experience point of view.

Everything I've done has been to try to get us to focus on the actual issue I've posted here.

From my viewpoint here is what I've been subjected to:
1) provide me with workarounds - which while generally may be helpful, not to me personally but hopefully to others, do not in fact address the issue I'm trying to bring to attention.
2) insults by claiming i'm `aggressive` and that my `tone` is wrong.
3) dismiss the issue with claims that do not hold up under technical scrutiny.
4) closing the issue with a passive aggressive statement when technical claims fall over.

so basically i'm pretty annoyed with the behavior demonstrated here by both of you. But that is counter productive. I'd rather just actually have a discussion about the issue. And despite your edited claims, I do not expect anything beyond an actual discussion about the issue on actual technical merits. Hell I'm even willing to help implement the improvements but that first requires an actual discussion.

so far we've established:
1. flatpak has a naming convention for the binaries executed by the desktop entry in order to prevent naming conflicts between applications installed by ensuring they are unique. 
2. flatpak currently makes no effort to integrate with the base environment only the XGD desktop environment.
3. the above two facts make for a poor user experience in other parts of the system (such as the command line) which can be problematic from an end user experience as standard behavior of applications differs between flatpak and native package management tools.
4. the stated reason is to prevent security risks by preventing naming collisions within the environment.
5. a similar security risk exists with the standard desktop entries because they can be made to look identical visually to another application. which may lead to a user improperly starting a malicious program after being installed by flatpak. but this problem was only used to demonstrate that user's are ultimately responsible for their systems and flatpak while it should attempt to help users make the right choice can only do so much.

I'm asserting flatpak can do better than current behavior by properly integrating with the entire environment without compromising security. using methods such as checking for name collisions within the flatpak environment during installation, global indexes, etc.

why its important:
current behavior results in loss of functionality for applications when installed by flatpak. as noted originally I was caught off guard when I tried installing atom via flatpak and basic commandline functionality that cannot be replicated by the desktop environment failed to work. said functionality is advertised within [standard atom documentation](https://flight-manual.atom.io/getting-started/sections/atom-basics/). implying the atom flatpak is not fully functional if not fundamentally broken.

current behavior also means that CLI applications will not properly integrate when installed via flatpak. despite claims by some here that there are plenty of CLI application flatpaks, said assertion doesn't hold up. a cursory glance at flathub's applications shows few (if any, I certainly didn't see any when I looked at all 408ish applications) actually exist.

**Comment by james-lawrence** [comment]
and again to be clear the discussion you linked to @aiamuzz doesn't have anything to do with this issue. it has to do with naming conflicts between remotes when installing a flatpak. which is an example of flatpak's naming convention failing in even its stated goal but again not relevant to the issue being discussed beyond yet another example of naming collisions that already exist within flatpak.
