### ISSUE TITLE
Listing available updates

### ISSUE THREAD

**Issue by MayeulC** [flatpak/flatpak#2168]
## Linux distribution and version
Arch Linux

## Flatpak version
1.0.2

## Description of the problem
I would like to list available updates without actually downloading them, to help with reporting a bug in KDE discover. I didn't find such a functionality. It could be a missing feature, or insufficient documentation (I tried looking in the man, the `--help` output and, on the Internet).

Maybe this could be provided as a `flatpak list --updatable`, or something like `flatpak update --dry-run`.

I just want to list updates without actually updating anything. Bonus points if the update size could be shown.

**Comment by TingPing** [comment]
Well `flatpak update` already doesn't actually update until you confirm.

**Comment by MayeulC** [comment]
I just saw that, indeed, but I still think it would be a good idea to mention it or add it as a switch, as I did not remember it that way.

**Comment by matthiasclasen** [comment]
There's also flatpak remote-ls --updates

**Comment by matthiasclasen** [comment]
I think remote-ls --updates is exactly what you want
