### ISSUE TITLE
runtime/org.freedesktop.Platform/x86_64/18.08 not installed

### ISSUE THREAD

**Issue by LanceHaverkamp** [flatpak/flatpak#2174]
runtime/org.freedesktop.Platform/x86_64/18.08 is, but is apparently not installing correctly in Fedora 27 (which is still current as of this writing).  

## Linux distribution and version
Fedora 27 (KDE Plasma desktop)
## Flatpak version
Flatpak 1.0.2
## Description of the problem
I'm trying to run Signal (the messaging app) the flatpak seems to install correctly, but fails to run
It returns: runtime/org.freedesktop.Platform/x86_64/18.08 not installed
## Steps to reproduce
sudo flatpak install flathub org.signal.Signal
flatpak run org.signal.Signal

Should it be looking for a freedesktop version when a KDE specific version seems to exist according to http://docs.flatpak.org/en/latest/available-runtimes.html

**Comment by mwleeds** [comment]
The runtime an app uses is independent of the desktop environment you have installed. Signal does indeed use the freedesktop one according to https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.json#L5

Maybe you could uninstall Signal and get verbose output from the next install?
```
$ flatpak uninstall org.signal.Signal
$ flatpak --verbose install flathub org.signal.Signal
$ flatpak run org.signal.Signal
```

**Comment by LanceHaverkamp** [comment]
That was different than what happened earlier, apparently something wasn't updating until I uninstalled so **Thanks for the suggestion!**   It asked if I wanted flathub or flathub-4, not knowing the difference I guessed flathub.:

[lance@localhost ~]$ flatpak --verbose install flathub org.signal.Signal
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/lance/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Fetching summary file for remote ‘flathub’
F: Fetching summary file for remote ‘flathub’
F: Transaction: install flathub:app/org.signal.Signal/x86_64/stable[*]
F: Updating remote metadata for flathub
F: Calling system helper: UpdateRemote
F: marking op install:app/org.signal.Signal/x86_64/stable resolved to 6c35096c21e505a3cec30ad28d52965b67d73a0a84fbc710a4d07a96a0ec75d9
F: Fetching summary file for remote ‘flathub-4’
Required runtime for org.signal.Signal/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/18.08) found in remotes: flathub
1) flathub
2) flathub-4
Which do you want to install (0 to abort)? [0-2]: 1
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform/x86_64/18.08[$old]
F: marking op install/update:runtime/org.freedesktop.Platform/x86_64/18.08 resolved to 73e812f33b03b170bda57c577a2ff9f15f6fe88f6b16d43415311c72751d7693
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/18.08[/en]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08[$old]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08[$old]
F: marking op install/update:runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08 resolved to cb314686f1e0c4c3c32a23b8b7e96113802083b2fbac0593cd57ff3245729fbb
F: marking op install/update:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08 resolved to 11d9fc7d7bbd8624282aaa6d8afadd61c7f5419dad0dca9a09af7548bca5010f
F: marking op install/update:runtime/org.freedesktop.Platform.Locale/x86_64/18.08 resolved to 5b871bcc2094fb5d65138fc78eb03bc91fbd5dcf1d59e76812c4b429f16324d0
Installing in system:
org.freedesktop.Platform/x86_64/18.08              flathub 73e812f33b03
org.freedesktop.Platform.Locale/x86_64/18.08       flathub 5b871bcc2094
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08  flathub 11d9fc7d7bbd
org.freedesktop.Platform.html5-codecs/x86_64/18.08 flathub cb314686f1e0
org.signal.Signal/x86_64/stable                    flathub 6c35096c21e5
  permissions: ipc, network, pulseaudio, x11, dri
  file access: home
  dbus access: org.freedesktop.Notifications
Is this ok [y/n]: y
Installing: org.freedesktop.Platform/x86_64/18.08 from flathub
[####################] 8 delta parts, 72 loose fetched; 168250 KiB transferred in 45 secondsF: Calling system helper: Deploy

Now at 73e812f33b03.
Installing: org.freedesktop.Platform.Locale/x86_64/18.08 from flathub
[####################] 4 metadata, 1 content objects fetched; 16 KiB transferred in 0 secondsF: Calling system helper: Deploy

Now at 5b871bcc2094.
Installing: org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08 from flathub
[####################] 1 delta parts, 2 loose fetched; 1762 KiB transferred in 1 secondsF: Calling system helper: Deploy

Now at 11d9fc7d7bbd.
Installing: org.freedesktop.Platform.html5-codecs/x86_64/18.08 from flathub
[####################] 1 delta parts, 2 loose fetched; 2459 KiB transferred in 1 secondsF: Calling system helper: Deploy

Now at cb314686f1e0.
Installing: org.signal.Signal/x86_64/stable from flathub
[####################] 2 delta parts, 10 loose fetched; 104673 KiB transferred in 40 secondsF: Calling system helper: Deploy

Now at 6c35096c21e5.
F: Calling system helper: RunTriggers
