### ISSUE TITLE
Allow creation of CAN sockets (AF_CAN address family)

### ISSUE THREAD

**Issue by wstering** [flatpak/flatpak#2176]
## Linux distribution and version
Fedora 28 x86_64
## Flatpak version
1.0.2, installed via `dnf` from Fedora's distro package `flatpak-1.0.2-1.fc28.x86_64  (Fedora Project)`
## Description of the problem
An application trying to create a CAN socket via e.g. `socket(PF_CAN, SOCK_RAW, CAN_RAW)` will get the error EAFNOSUPPORT (Address family not supported by protocol). Specifically, see [flatpak-run.c:2263](https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L2263) and the socket family whitelist in [flatpak-run.c:2143](https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L2143).

Note: when using `flatpak-builder --run <builddir> <manifest>` (as opposed to `flatpak run <appid>` once the app is installed), this seems to work.
## Steps to reproduce
Given a CAN-Bus accessible via *socketcan* is available as network interface `can0` on the host. If no real CAN-Adapter is available, Linux offers virtual CAN adapters that can be created dynamically with (sudo might be required unless running as root)
```bash
$ ip link add can0 type vcan
$ ip link set up can0
```
Then try to use `cansend can0 123#00` or `candump can0` of  the can-utils (https://github.com/linux-can/can-utils) inside a Flatpak sandbox.

A solution could provide an option similar to what was done for Bluetooth support (in 0.11.8, according to NEWS, as --allow=bluetooth for AF_BLUETOOTH sockets), e.g. --allow=socketcan.
Besides, other types of sockets are potentially of interest, e.g. AF_NFC sockets, as used by neard (see https://01.org/linux-nfc), for example.

Thanks @alexlarsson and @ramcq for the discussion on IRC #flatpak.

**Comment by alexlarsson** [comment]
AF_NFC seems to be used by neard, which is not suited to being in a sandbox, so nfc filtering is probably better done by gating access to the neard dbus service.
