### ISSUE TITLE
Gio File Copy: g-io-error-quark, Software caused connection abort

### ISSUE THREAD

**Issue by FalkAlexander** [flatpak/flatpak#2177]
## Linux distribution and version
Fedora 28/29, Ubuntu 18.04, Arch Linux
## Flatpak version
1.0.2
## Description of the problem
Using the copy function on a Gio File object for copying into another directory throws
`g-io-error-quark: Error opening file “/run/user/1000/doc/291bd18e/Safe.kdbx”: Software caused connection abort (0)`
https://lazka.github.io/pgi-docs/#Gio-2.0/classes/File.html#Gio.File.copy

Independent of the filesystem permission, tried without, with home and host.
## Steps to reproduce
1. Optionally get my app at https://gitlab.gnome.org/World/PasswordSafe
2. Start Password Safe
3. Click on "New..." for creating a new database
4. Select a directory for the database with GtkFileChooserNative
5. Click Save
6. Close the app
7. Look into the directory, there is a database file which size is > 0kb
8. Delete the database file
9. Reopen the app and recreate the database with the same filename
10. Gio throws g-io-error-quark and the database file size is 0 kb

Does not necessarily have to be the identical folder, sometimes this happens without previous deletion of the database file. Couldn't find an exact schema.

This does only happen with the Flatpak package.

I've discussed already with @bilelmoussaoui about this, maybe he has some information he can add here also.
@bertob experienced this behaviour also while using Password Safe.

**Comment by matthiasclasen** [comment]
To ask the obvious first: why are you creating the database outside the sandbox in the first place?
Would it not be more appropriate to just use $XDG_DATA_HOME, which points at the apps writable filesystem area in ~/.var/app ?

**Comment by FalkAlexander** [comment]
The databases are using the KeePass standard which is intended as portable file format, its use case is to e.g. storing it in a folder on the hard disk, a USB stick or in the cloud (e.g. via gvfs-goa).
A limitation to a certain directory would be too restrictive.

**Comment by matthiasclasen** [comment]
This is veering into design discussion, but if this is about sharing the data between machines, an explicit share or export feature might be nicer.

As for the problem in this issue, it is related to the documents portal. You can probably find an existing issue already filed against xdg-desktop-portal.

**Comment by FalkAlexander** [comment]
Thanks, good to know that this is related to xdg-desktop-portal. So I guess this issue can get moved?

**Comment by matthiasclasen** [comment]
I'm afraid github has no way to that. That I know of, at least.

**Comment by FalkAlexander** [comment]
Ok, then I'll recreate this one on xdg-desktop-portal and close this one.
