### ISSUE TITLE
flatpak-builder could tell where it couldn't find a file

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak#218]
I'm playing around with flatpak-builder and I wish it would be more discoverable in the sense that it tells what I'm doing wrong.

Just right now it complains about

    Error: icon data/icon.svg not found

but that does exist from where I call flatpak-builder, so I'm a bit confused.

Similarly, the .desktop file fails, too:

    Renaming data/myapp.desktop to org.gnome.myapp.desktop
    Error: Error moving file: No such file or directory

I'm probably doing something stupid, but I guess it'd help me if it said smth like "Couldn't find >>data/icon.svg<< in /path/to/directory".  It's probably more complicated like that, but the current error description is not very helpful (for me).

FWIW: I've tried to strace -f -eopen flatpak-builder but I couldn't see it trying to open the .desktop file. It seems to be using lstat. There, I could see it trying to lstat in /tmp/fpbuilder/files/share/applications/.  I guess I missed to tell flatpak-builder to copy my data/ directory somewhere useful inside the container. So maybe the error message could include a hint that it's looking for the file *in* the container rather than from where it's being called.

**Comment by matthiasclasen** [comment]
Added some more context to those error messages
