### ISSUE TITLE
check for python

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2186]
I just did a flatpak build on a fresh fedora 29 install, and found that after I install enough to make ./configure and make succeed, make check still runs into a large number of failures, which turn out to be due to python not being available.

Might be nice to check for python in configure

**Comment by matthiasclasen** [comment]
It turns out only python3 is available here.

**Comment by matthiasclasen** [comment]
Oh, and there's the whole python vs python3 issue. Fedora 29 only has python3 out of the box.
Here's a Debian patch: https://salsa.debian.org/debian/flatpak/blob/debian/master/debian/patches/debian/Use-Python-3-for-test-web-server.patch

**Comment by kirbyfan64** [comment]
SimpleHTTPServer was renamed to http.server. The patch linked has the name change, unless they missed some uses.

**Comment by matthiasclasen** [comment]
you're right
