### ISSUE TITLE
/etc/timezone does not match host system

### ISSUE THREAD

**Issue by danvratil** [flatpak/flatpak#2190]
## Linux distribution and version
KDE neon Developer Edition 18.04 (Ubuntu Bionic)

## Flatpak version
Flatpak 1.0.1

## Description of the problem
`/etc/timezone` inside the flatpak is always set to "Universal", so if the host system is configured to any other timezone, applications that depend on the timezone information will show wrong time.

As suggested in https://github.com/flathub/org.kde.kontact/issues/9, host `/etc/timezone` should be probably exposed to `/run/host/monitor`.

## Steps to reproduce
Change your system timezone to anything other than UTC, run Kontact, observe wrong time (see
https://github.com/flathub/org.kde.kontact/issues/9 for details)

**Comment by alexlarsson** [comment]
What is /etc/timezone. I've never heard about that before, and I don't have it on my fedora system. Is it a debian thing? Is there some kind of standard defining how this works?

**Comment by danvratil** [comment]
Debian, but also apparently Arch (and possibly other distros) use it as well. It contains the name of the timezone in Olson format (e.g. "Europe/Prague")

The problem is that Qt looks first for `/etc/timezone` and falls back to `/etc/localtime`, so even if `/etc/localtime` is correct inside of the Flatpak, Qt applications will honor the (wrong) `/etc/timezone`.

I could find only this: https://wiki.debian.org/TimeZoneChanges

**Comment by alexlarsson** [comment]
Another alternative is to remove /etc/timezone from the runtime. It seems to be in the 1.6 freedesktop runtime, but not in the new (18.08) version. If that is not there, what does Qt use for timezone then?

**Comment by Erick555** [comment]
@alexlarsson It was already said that it falls back to` /etc/localtime`.

**Comment by alexlarsson** [comment]
Its better to have all runtimes behave in the same way wrt something as core as timezone config i think

**Comment by alexlarsson** [comment]
Alternatively, we could implement /etc/timezone in the monitor, and then patch the glib in the runtime to support that. Then we could support the timezone changing at runtime.

Actually, glib already reads `/var/db/zoneinfo` with similar sematics to /etc/filesystem, so we could make both be symlinks...

**Comment by Erick555** [comment]
As `/etc/timezone` is redundant to `/etc/localtime` and doesn't exist in some systems (Fedora, Arch) then getting rid of it seems the easiest way. 18.08 doesn't have it so when KDE runtime will upgrade the problem will be gone.

**Comment by alexlarsson** [comment]
@Erick555 it is redundant on the host, but we can't really implement it in the sandbox because it relies on pointing into /usr, which is in the runtime that flatpak has no guarantees about (i.e. it might not have the same timezone data as the host). Also, it has to be a direct symlink, which means we can only specify it at sandbox creation and never update it.  That makes it not ideal for flatpak.

**Comment by alexlarsson** [comment]
@danvratil Whats your opinion on the approach in https://github.com/flatpak/flatpak/pull/2214

**Comment by danvratil** [comment]
@alexlarsson Looks good. I tested it with the Kontact flatpak and the timezone was set correctly, so it definitely fixes the timezone issue for Qt/KDE apps. Thanks for fixing this so quickly.
