### ISSUE TITLE
Flatpak-VLC: open a video, close it immediately and open another video broke VLC.

### ISSUE THREAD

**Issue by valeriodean** [flatpak/flatpak#2208]
## Linux distribution and version
Fedora 28
## Flatpak version
1.0.3
## Description of the problem
I use VLC through flatpak.
The problem I noticed appear when I open a video, recognise it is the wrong one and close it immediately, then click on another video and... nothing happen.
VLC seems dead.
When I check the system activity there are vlc related program in execution, but clicking on a video file doesn't trigger the player (see attached screenshot) or the player doesn't work any more.
To solve the problem I need to kill those process.
![vlc_flatpack_problem](https://user-images.githubusercontent.com/9042830/46584893-4e5e9b80-ca69-11e8-9764-50c94020bd94.png)
Note: if you do not change the video file and try to open again the same file you closed one second ago, it works. If you pick another video, it doesn't work.

## Steps to reproduce
1) open video A and close VLC immediately after (1 seconds later)
2) open video B... nothing happens
3) kill the vlc related process
4) open video B and vlc starts without problem.

## Request
VLC in flatpak format should manage the workflow above without problems as well as the "legacy" installation.

**Comment by alexlarsson** [comment]
Does it work if you wait more than 1 second btw?

**Comment by valeriodean** [comment]
> My guess is that the second copy of VLC tries to re-connect to the first instance, but that somehow fails due to the sandbox.
> 
> Is this the vlc from flathub? If so, can you file a bug against https://github.com/flathub/org.videolan.VLC/issues so that the right people can see this?

Ok, I will do it. Thank you.
[https://github.com/flathub/org.videolan.VLC/issues/47#issue-367875318](url)


> Does it work if you wait more than 1 second btw?

Waiting some seconds (up to 7) doesn't change the result.
