### ISSUE TITLE
Appstream should have separate branches

### ISSUE THREAD

**Issue by cosimoc** [flatpak/flatpak#222]
Currently when `flatpak build-update-repo` runs it will create a single appstream branch per each architecture, which will contain appstream information for all the bundles in all the branches of the repositories. It would be more convenient if there was an appstream branch for each repository branch, so that clients like gnome-software don't need to implement filtering logic to deduplicate the entries. (Related to #221)

**Comment by alexlarsson** [comment]
I don't think having appstreams per branch makes any sense, since branch-name have no "repo-global" scope. However, we discussed this at guadec and the point is that we want to be able to somehow tag which branches are the "default" and not show the others in the UI.

**Comment by alexlarsson** [comment]
Closing in favour of https://github.com/flatpak/flatpak/issues/221
