### ISSUE TITLE
need help to install Zotero

### ISSUE THREAD

**Issue by olioliv1** [flatpak/flatpak#2222]
Hi,

I've downloaded the file : org.zotero.Zotero.flatpakref and it is located here : /home/oli/Downloads

but when i run commands on terminal i got this :
```
(xenial)oli@localhost:~$ flatpak override --user --filesystem=/PATH/TO/ZOTEROFOLDER org.zotero.Zotero
(xenial)oli@localhost:~$ sudo flatpak install flathub org.zotero.Zotero
[sudo] password for oli:
error: Error searching remote flathub: Can't find ref org.zotero.Zotero
(xenial)oli@localhost:~$
```
I have an acer chromebook r 13 ( mediatek M8173C Core pilot 4 coeurs ARM Cortex-A72/A53 ) with ubuntu installed with crouton :
```
(xenial)oli@localhost:~$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:    16.04
Codename:    xenial
```
with the xfce desktop (version 4.12, xubuntu)

I've right now installed libre office properly so the flatpak repo is up to date.

Thanks for any help,

Oli

Best regards

**Comment by mwleeds** [comment]
`flatpak install flathub org.zotero.Zotero` works on my machine. Could you try running it without `sudo`? And could you say how you added the flathub remote? Did you run `flatpak remote-add ...` and if so could you paste the exact command?

**Comment by olioliv1** [comment]
I tried without sudo, but i got the same error, i ran this for the flathub remote :       

 flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo (by the setup guide)
-----------------------------------
(xenial)oli@localhost:~$  sudo apt install flatpak
Reading package lists... Done
Building dependency tree       
Reading state information... Done
flatpak is already the newest version (1.0.3-flatpak1~xenial).
The following package was automatically installed and is no longer required:
  libreoffice-style-galaxy
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(xenial)oli@localhost:~$  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
(xenial)oli@localhost:~$ flatpak install flathub org.zotero.Zotero
error: Error searching remote flathub: Can't find ref org.zotero.Zotero
---------------------------------------

**Comment by mwleeds** [comment]
Strange. You could post the output of `flatpak -vv install flathub org.zotero.Zotero`

**Comment by olioliv1** [comment]
flatpak -vv install flathub org.zotero.Zotero
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/oli/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Fetching summary file for remote ?flathub?
error: Error searching remote flathub: Can't find ref org.zotero.Zotero

**Comment by mwleeds** [comment]
Not much to go on there. This doesn't happen for other apps you try to install?

**Comment by olioliv1** [comment]
No, i could install libre office and Jamovi without any problem

**Comment by olioliv1** [comment]
Hello,

does anyone have any idea to help to fix ?

**Comment by Alexander-Wilms** [comment]
Zotero is not available on ARM: https://github.com/flathub/org.zotero.Zotero/blob/master/flathub.json
