### ISSUE TITLE
MIT-MAGIC-COOKIE issues cause Flatpaks not to launch, despite other apps launching fine

### ISSUE THREAD

**Issue by fusion809** [flatpak/flatpak#2228]
## Linux distribution and version
openSUSE Tumbleweed 20181004.

## Flatpak version
1.0.3.

## Description of the problem
Flatpaks for RuneScape (com.jagex.RuneScape) and Spotify (com.spotify.Client) both fail to launch, with RS giving the error: 
```
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
/app/extra/runescape: /lib/libcurl.so.4: no version information available (required by /app/extra/runescape)
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: (null)
Failed creating new xdo instance
```
and Spotify giving: 
```
Invalid MIT-MAGIC-COOKIE-1 key/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: 07:52:44.604: Failed to load module "canberra-gtk-module"
Invalid MIT-MAGIC-COOKIE-1 key
(spotify:6): Gtk-WARNING **: 07:52:44.604: cannot open display: :99.0
```
Other apps give the MIT-MAGIC-COOKIE part of the warning (which fvogt in the #suse Freenode IRC channel tells me is likely due to dhcp setting my hostname), but they launch fine. 

## Steps to reproduce
Install openSUSE Tumblewleed 20181004, then set up YaST with these network settings:

![screenshot_20181010_080146](https://user-images.githubusercontent.com/4717341/46701338-c2b05f00-cc62-11e8-92bb-243979822d46.png)
![screenshot_20181010_080148](https://user-images.githubusercontent.com/4717341/46701340-c348f580-cc62-11e8-9a8e-e17846ae087b.png)
![screenshot_20181010_080149](https://user-images.githubusercontent.com/4717341/46701341-c348f580-cc62-11e8-85d7-32ac971b9835.png)
![screenshot_20181010_080150](https://user-images.githubusercontent.com/4717341/46701342-c3e18c00-cc62-11e8-8aaa-5784a5c381cb.png)

Then install the RuneScape Flatpak by building (with flatpak-builder, of course) https://github.com/flathub/com.jagex.RuneScape/pull/44/commits/90156f4166edea43f9286525aa555b6cfa21924b, or the Spotify Flatpak with: `flatpak install --user flathub com.spotify.Client` (assuming the flathub remote has been added). Then try to launch the Flatpak you installed with `flatpak run APP`

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Aha, well unsetting domain name in YaST fixed this for me, so should this be closed or is making this not an issue in that circumstance still worthwhile?

**Comment by Artox** [comment]
I personally do see this as an issue - I set a hostname on purpose

**Comment by fusion809** [comment]
I think this issue was some weird X.Org bug, as other apps had similar problems.
