### ISSUE TITLE
Installing Platforms inside a docker container can fail with coredump

### ISSUE THREAD

**Issue by gbraad** [flatpak/flatpak#223]
For automated development purpose, I use Docker containers, and so also for Flatpak. But when installing the Platform or Sdk, it often fails:

`flatpak install gnome org.gnome.Platform 3.20` =>

```
Installing related: org.gnome.Platform.Locale
(flatpak install:100): GLib-GObject-CRITICAL **: g_object_new_valist: invalid object type 'GMemoryInputStream' for value type 'GInputStream'
(flatpak install:100): GLib-GIO-CRITICAL **: g_input_stream_read: assertion 'G_IS_INPUT_STREAM (stream)' failed
(flatpak install:100): GLib-GIO-CRITICAL **: g_input_stream_close: assertion 'G_IS_INPUT_STREAM (stream)' failed
(flatpak install:100): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(flatpak install:100): GLib-GIO-CRITICAL **: g_simple_async_result_take_error: assertion 'error != NULL' failed
/bin/sh: line 1:   100 Segmentation fault      (core dumped) flatpak install gnome org.gnome.Platform 3.20
Installing related: org.gnome.Sdk.Locale
(flatpak install:177): GLib-GObject-CRITICAL **: g_object_new_valist: invalid object type 'GMemoryInputStream' for value type 'GInputStream'
(flatpak install:177): GLib-GIO-CRITICAL **: g_input_stream_read: assertion 'G_IS_INPUT_STREAM (stream)' failed
(flatpak install:177): GLib-GIO-CRITICAL **: g_input_stream_close: assertion 'G_IS_INPUT_STREAM (stream)' failed
(flatpak install:177): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(flatpak install:177): GLib-GIO-CRITICAL **: g_simple_async_result_take_error: assertion 'error != NULL' failed
/bin/sh: line 1:   177 Segmentation fault      (core dumped) flatpak install gnome org.gnome.Sdk 3.20
```

Retriggering the build will result in a success or same problem. The used `Dockerfile` is:

```
FROM fedora:24
MAINTAINER Gerard Braad <me@gbraad.nl>

RUN mkdir -p /workspace; \
    dnf install -y git wget flatpak flatpak-builder; \
    wget https://sdk.gnome.org/keys/gnome-sdk.gpg; \
    flatpak remote-add --gpg-import=gnome-sdk.gpg gnome https://sdk.gnome.org/repo/; \
    flatpak install gnome org.gnome.Platform 3.20; \
    flatpak install gnome org.gnome.Sdk 3.20

VOLUME /workspace
CMD bash
```

Note: this happens for Automated builds on either Docker hub or GitLab CI Runners. Example: https://gitlab.com/gbraad/flatpak-builder-gnome/builds.

**Comment by matthiasclasen** [comment]
I've reproduced this here

**Comment by matthiasclasen** [comment]
well. It happened once on my system; haven't been able to reproduce it since. It would be very helpful if you could capture a stacktrace

**Comment by gbraad** [comment]
I'll try to get one... but locally it does not seem to happen until now. I'll try to get some information about the CI runners...

Curious about your storage driver... devicemapper, overlay?

**Comment by matthiasclasen** [comment]
docker info says:

Storage Driver: devicemapper

**Comment by sramkrishna** [comment]
You need to do all your flatpak command as one layer :
RUN flatpak remote-add --from gnome-nightly https://sdk.gnome.org/gnome-nightly.flatpakrepo && flatpak install gnome-nightly org.gnome.Sdk && flatpak install gnome-nightly org.gnome.Platform

**Comment by gbraad** [comment]
This was performed as one layer when the bug was reported. And this is not true as a resolution to this problem.

The issue has since been resolved; issue does not occur with later versions

**Comment by sramkrishna** [comment]
That's great to hear.. I got the solution actually from the mailing list.  BTW we are working on something similar for gitlab in order to do patch testing from bugzilla.  We are using gnome-todo and gnome-builder.  Would love to hear your thoughts on this.
