### ISSUE TITLE
Missing platform package for nvidia 340-107

### ISSUE THREAD

**Issue by tux-rampage** [flatpak/flatpak#2231]
## Linux distribution and version

Ubuntu 18.04

## Flatpak version

Flatpak 1.0.3

## Description of the problem

There was a new update for the nvidia-340 drivers to version to 340-107. This caused the Platform to fail for all applications using GL (like linphone - for what reason ever).

## Steps to reproduce

1. Install Ubuntu 18.04 with an older nvidia card
2. Enable proprietary nvidia drivers from nvidia-340.
3. Install flatpak
4. `flatpak install gnome org.gnome.Platform` (or any matching platform) -> This will install `org.freedesktop.Platform.GL.default` instead of `org.freedesktop.Platform.GL.nvidia-*`
5. Install a flatpak app that uses GL, for example Linphone
6. Attempt to run the flatpack app -> libGL errors

**Comment by tux-rampage** [comment]
The only workaround for end users at the moment is to use nouveau drivers.

**Comment by TingPing** [comment]
They have been in Flathub since release. Try:

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak update
```

**Comment by tux-rampage** [comment]
@TingPing thanks for pointing me in the right direction. The problem was, that i installed from the `gnome` repo (with `flatpak install gnome org.gnome.Platform`) instead of `flathub`.

So I first removed the installed gnome packages:

```bash
flatpak list
flatpak remove org.freedesktop.Platform.GL.default/x86_64/1.6 org.gnome.Platform/x86_64/3.28
```

After that I re-installed the platform from the flathub repo, which pulled the correct dependencies:

```bash
flatpak install flathub org.gnome.Platform
```
