### ISSUE TITLE
remote-delete ... behaviour ... 

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2234]
Hi,

i just happen to try deleting a remote to test a concept ... i encountered the following error ...

```
flatpak remote-delete flathub
error: Can't remove remote 'flathub' with installed ref app/com.github.hluk.copyq/x86_64/stable (at least)
```
I removed this hluk app and tried to delete the remote ... encountered the following error ...

```
flatpak remote-delete flathub
error: Can't remove remote 'flathub' with installed ref runtime/org.kde.palapeli.Locale/x86_64/stable (at least)
```

i uninstalled even this palapeli app ... and tried deleting the remote ... and i was able to successfully delete the flathub remote.

Is this expected behavior ... or is something off ?

FYI ... the above 2 apps are the only apps i have installed from flathub on my default install location ... i have quite a few apps installed at my custom install location from flathub ... 

**Why is it not letting me delete a remote without having to remove apps from the default install location ... and why is it letting me keep apps from flathub at my custom install location. ?**

**Comment by matthiasclasen** [comment]
we don't want to leave apps 'stranded' on your system without a way to receive updates.
you probably have the flathub remote installed in your custom installation as well.

**Comment by aiamuzz** [comment]
ok ... so its an intended behavior ...
yes you are right i do have the remote installed at my custom installation as well ... that explains ...

another observation ... suppose i haven't added the flathub remote to my installation paths ... i download the flatpakref file and install apps from flathub ... in such an event where the flathub remote is absent ... 

1. Do apps installed in such a way(flatpakref without the remote added) not receive updates ?
2. Is adding a remote a necessity a requirement for `flatpak update` command to work for all apps installed ?
