### ISSUE TITLE
vlc (and mpv) hangs and doesn't play videos

### ISSUE THREAD

**Issue by beaverbusy** [flatpak/flatpak#2240]
## Linux distribution and version
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
VERSION_ID=25500
## Flatpak version
Flatpak 1.0.3
## Description of the problem
Both vlc and mpv can be started. But once one chooses a file to open the program hangs and nothing is played. error message in vlc (mpv has same error message)
> flatpak run: Can't get document portal: GDBus.Error:org.freedesktop.portal.Error.Failed: Can't mount fuse fs
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)

## Steps to reproduce
get a full install of latest clear linux. Install vlc or mpv via flatpak. try to open a video file (avi, mkv, etc).

**Comment by mwleeds** [comment]
My guess is this is a problem with the way Clear Linux OS has packaged flatpak or xdg-desktop-portal. You could report the bug to them?

**Comment by Mikenux** [comment]
The last comment and looking at the issues mentioned (the fuse is now built into the kernel) suggests that this issue can be closed. @beaverbusy @GeorgesStavracas
