### ISSUE TITLE
Switch to Meson

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2241]
Just wanted to open the discussion on switching to Meson. Any reason to stay on Autotools other than the work involved in switching?

**Comment by matthiasclasen** [comment]
Continuing to support rhel7 ? Although we have worked around the lack of python3 for the last gnome rebase, so meson is not an absolute no-go anymore

**Comment by kirbyfan64** [comment]
Are there any other distros that Flatpak runs on where it would be an issue? IIRC that's what I was told when I asked on IRC.

**Comment by Ruedii** [comment]
Is there really any advantage to switching?

**Comment by mwleeds** [comment]
It seems a lot more user friendly and modern than Autotools based on my experience. I think many GNOME projects have been switching over for those reasons.

**Comment by TingPing** [comment]
The goal of flatpak is to build on as old of hosts as possible and it doesn't really care about the performance or portability wins Meson provides. So it is probably not the best case for a port.

**Comment by alexlarsson** [comment]
I don't want to switch to meson only, because the entire point of flatpak is to be maximally compatible with old distros (so you can then run newer apps on them). And doing both meson + automake seems to just be more work.

**Comment by nanonyme** [comment]
@alexlarsson now one and a half years in the future, is this still the case? Flatpak has grown a lot of dependencies to hosts (through eg portals) which many apps rely upon and which either do not exist on old distros or are not fully functional. Meson is quite common-place these days although it admittedly still changes quite fast which may in theory result in difficulties supporting wide ranges of Meson versions.

**Comment by refi64** [comment]
I don't think RHEL 7 has Meson outside of EPEL, so the autotools build
would still have to be maintained for backports.

**Comment by nanonyme** [comment]
Does someone actively test apps keep working on RHEL7 or is this just a theoretical goal?

**Comment by mwleeds** [comment]
I think RHEL 7 is on Flatpak 1.0 though, so it's a pretty different codebase than Flatpak 1.9.x in any case.

**Comment by alexlarsson** [comment]
I'm not entierly against moving to meson at some point, as older distros can potentially use older versions of flatpak. However, its not like the flatpak autoconf stuff is *that* complex, so its not super-clear to me that this is a priority.

Maybe we can start with a parallel port to meson to try it out, and then drop the auto* one after a cycle.

**Comment by smcv** [comment]
I have been trying to work towards this for a while: that's why the submodules are now in a Meson-style `subprojects/` directory.

The subprojects written in C should gain Meson build systems first:

* libglnx: done
* bubblewrap: https://github.com/containers/bubblewrap/pull/432
* xdg-dbus-proxy: I'm working on it, not ready yet though

**Comment by smcv** [comment]
Relatedly, libglnx could benefit from a review pass from @cgwalters or some other maintainer there. I have 4 merge requests waiting in https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests, two of which are Meson-related and would be beneficial if we are moving to Meson in Flatpak.

**Comment by smcv** [comment]
I think something we will need to do here is to make a decision on how far back into the past we still want to support.

In my PRs for bubblewrap and xdg-dbus-proxy, my cutoff was Meson 0.49.0, available in Debian >= 10. This would mean that a Meson-based version of Flatpak can easily be backported to:

* Debian >= 10 (and 9 with backports, but Debian 9 is EOL)
* Ubuntu 20.04 LTS (but not 18.04 LTS)
* openSUSE Leap 15.2 (but not 15.1)
* CentOS/RHEL 8

I personally think it would be reasonable to say that Flatpak 1.13.x/1.14.x are only available for those distributions, and backports to older distributions will be stuck at 1.12.x.

If Ubuntu 18.04 LTS and contemporary distros are important to us (bearing in mind that 22.04 LTS is due in 2 months, superseding 20.04), then someone could test on Meson 0.45.0 and see how much would need to change, but I'm not intending to do that myself.

**Comment by eli-schwartz** [comment]
@smcv Not considering straight up bugs present in old versions, you should as a rule be able to determine the minimum version of Meson you can support simply by setting `meson_version: '>=0.37.0'` and checking what Feature warnings it generates.

At least, that's the general design goal. If we are missing FeatureNew checks for any added functionality, that's a bug which must be reported and fixed. If behavior has changed, that's probably a bug too (we don't generally do that, though there are cases in which we have lengthy deprecation warnings for broken behavior).

So, checking what needs to change should be trivial.

**Comment by smcv** [comment]
I tried briefly with Ubuntu 18.04's Meson and it doesn't support `type: 'feature'` in `meson_options.txt`. I think that's further back into retrocomputing than I want to go, because `feature` is widely-used and very useful.

**Comment by eli-schwartz** [comment]
Ah yeah, that one is a pretty good reason. :D

**Comment by smcv** [comment]
I've started converting the build system to Meson (no PR just yet, but I'm working on it). See #4842 for a first step.

**Comment by smcv** [comment]
If other people want this, reviewing my pending PRs in xdg-dbus-proxy would be a good start: using Meson in Flatpak is going to require using Meson in its xdg-dbus-proxy subproject.
