### ISSUE TITLE
Nvidia new long-term 410.66 drivers need GL flatpak support

### ISSUE THREAD

**Issue by jadbox** [flatpak/flatpak#2248]
New stable Nvidia drivers released:
https://www.reddit.com/r/linux_gaming/comments/9oowh9/stable_nvidia_driver_v41066_is_released/

However, the latest Platform.GL.nvidia driver is Platform.GL.nvidia-410-57.
```
flatpak remote-ls| grep nvidia | grep 410
org.freedesktop.Platform.GL.nvidia-410-57	flathub
org.freedesktop.Platform.GL32.nvidia-410-57	flathub
org.freedesktop.Platform.GL.nvidia-410-57	flathub
org.freedesktop.Platform.GL32.nvidia-410-57	flathub
```

**Comment by TingPing** [comment]
Building will be released soon - https://flathub.org/builds/#/builders/2/builds/5382
