### ISSUE TITLE
Flatpak is not honouring mtimes

### ISSUE THREAD

**Issue by mbooth101** [flatpak/flatpak#2251]
## Linux distribution and version
Fedora 28 Workstation

## Flatpak version

```
$ rpm -q flatpak bubblewrap ostree
flatpak-1.0.3-1.fc28.x86_64
bubblewrap-0.3.0-2.fc28.x86_64
ostree-2018.8-1.fc28.x86_64
```

## Description of the problem

I'm packaging an app that is doing some comparison of file mtimes to determine whether it has been updated or not. But in the Flatpak sandbox, all installed files have a mtime of zero:

```
$ flatpak run --command=bash org.eclipse.Sdk
bash-4.4$ stat /app/eclipse/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info                                                                                     
  File: /app/eclipse/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info
  Size: 33028           Blocks: 72         IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 2423203     Links: 2
Access: (0644/-rw-r--r--)  Uid: (65534/nfsnobody)   Gid: (65534/nfsnobody)
Access: 2018-10-17 06:26:32.935605206 +0100
Modify: 1970-01-01 01:00:00.000000000 +0100
Change: 2018-10-17 10:11:09.422982354 +0100
```

However, when I check the source tarball from which this flatpak is generated, I can see the modified time is set correctly:

```
[root@eclipse products]# tar xf org.eclipse.sdk.ide-linux.gtk.x86_64.tar.gz 
[root@eclipse products]# stat eclipse/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info
  File: eclipse/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info
  Size: 33028           Blocks: 72         IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 43829343    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:var_lib_t:s0
Access: 2018-10-17 16:55:06.235863132 +0100
Modify: 2018-10-17 01:39:35.000000000 +0100
Change: 2018-10-17 16:55:06.235863132 +0100
```

So is flatpak or flatpak-builder not honouring mtimes? And if not, is this intentional?

It has caused me a great deal of debugging because I expected that the mtime be set to the same as ctime for files created in the sandbox, just as it is on the host. 

FWIW, I searched the issues before filing this, and a solution to this issue may also fix #9.

**Comment by matthiasclasen** [comment]
This is intentional, and imposed by ostree. We don't want to lose deduplication of files just because the mtime is different.

Flatpak offers a different way to check whether an app has been updated while it is running. I blogged about it a while ago

**Comment by mbooth101** [comment]
I see, thanks for the information
