### ISSUE TITLE
Stale wayland socket (or any file named like a wayland socket) causes --socket=fallback-x11 to break

### ISSUE THREAD

**Issue by phako** [flatpak/flatpak#2258]
## Linux distribution and version
Ubuntu 16.04 LTS and 18.04 LTS
## Flatpak version
Flatpak 1.0.4 on 16.04 and 1.0.1 on 18.04
## Description of the problem
If there is a stale wayland socket in $XDG_RUNTIME_DIR, an app with --socket=fallback-x11 will not run:
Unable to init server: Could not connect: Connection refused

(org.gnome.Photos:3): Gtk-WARNING **: 17:19:40.444: cannot open display: 

## Steps to reproduce
Run in a session with X11
touch $XDG_RUNTIME_DIR/wayland-0
flatpak run org.gnome.Photos

**Comment by matthiasclasen** [comment]
Isn't this basically the dedined behavior of fallback-x11: if wayland-0 exists, don't offer x11 ?
We could perhaps do a better job at checking that it is actually a socket
