### ISSUE TITLE
libflatpak doesn't offer the download speed

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#2261]
It's been requested here, we have it for other back-ends too.
https://bugs.kde.org/show_bug.cgi?id=396349

Ideally it would come through the FlatpakTransaction class.

**Comment by fafa2017** [comment]
Use flatpak is the command-line  to make sure the download speed appears.

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/flatpak/pull/2371 adds enough transaction api to compute download speed.
