### ISSUE TITLE
Cannot run executable in flatpak sandbox

### ISSUE THREAD

**Issue by plata** [flatpak/flatpak#2265]
## Linux distribution and version
Linux Mint 19

## Flatpak version
1.0.4

## Description of the problem
I'm trying to provide flatpak support for Phoenicis (see https://github.com/PhoenicisOrg/phoenicis/pull/1406). It is not possible to run `wine` (located in `~/.var/app/...` inside the flatpak), gives "file not found".

## Steps to reproduce
Try to install any application via Phoenicis.
```
flatpak run --command=bash org.phoenicis.javafx
```
Try to run:
```
~/.var/app/org.phoenicis.javafx/data/.Phoenicis/engines/wine/upstream-linux-x86/3.0.3/bin/wine
```

**Comment by TingPing** [comment]
If you run `ldd` on it (`flatpak run --devel ...`) you will probably see it is missing some library. Thats what happens when you just download random binaries built against other distros.

**Comment by plata** [comment]
I would understand that. Actually, I've copied a random executable to that directory to see how it would behave which gave linking errors. However, in the case of wine, I get "file not found". `ldd` gives " program is not dynamically linked".

**Comment by TingPing** [comment]
"file not found" is a vague error that often bubbles up from libraries not being found. `strace ~/.var/app/org.phoenicis.javafx/data/.Phoenicis/engines/wine/upstream-linux-x86/3.0.3/bin/wine` may give more helpful results.

**Comment by plata** [comment]
That gives me:
```
strace: exec: file or directory not found
```

**Comment by TingPing** [comment]
Uhm, well dumb question but maybe that path is incorrect and it doesn't actually exist?

**Comment by plata** [comment]
I've checked that several times (also I can `cd` into the directory and call the commands from there).

**Comment by plata** [comment]
Maybe it is related to https://github.com/flatpak/freedesktop-sdk-images/issues/101 and https://github.com/flatpak/flatpak-builder/issues/138? Not sure if that would cause this error message.

**Comment by plata** [comment]
If just tried to use the `Compat32` runtime. Now I cannot even run the flatpak (except with `--devel` for whatever reason). With `--devel` I get the same error message (I guess it's just not using the correct build).
I've also tried a 64bit Wine build and that seems to work. This leaves me with some questions:
- Why does `Compat32` not work?
- Is there anything flatpak can do about the strange error message (I guess not)?
- How can I make it run?

**Comment by plata** [comment]
I've found the issue. Fixed it in https://github.com/PhoenicisOrg/phoenicis/pull/1406/commits/34a398f5809a416b0c46476ccf3688695c0eda61. Not sure if this is the 100% correct/idiomatic way to do this. I've copied it from the [Steam manifest](https://github.com/flathub/com.valvesoftware.Steam/blob/master/com.valvesoftware.Steam.json). Maybe it would make sense to extend the [multiarch docs](https://github.com/flatpak/flatpak/wiki/Multiarch) with an example like that?

**Comment by TingPing** [comment]
We should probably get it documented here somewhere: https://github.com/flatpak/flatpak-docs

**Comment by plata** [comment]
Regarding the error message: can this be influenced by flatpak somehow?

Otherwise I'm fine closing the issue now.

**Comment by TingPing** [comment]
No, honestly `ld` or whatever generates that error should probably be improved upstream.
