### ISSUE TITLE
OpenCL on Nvidia requires /dev/nvidia-uvm

### ISSUE THREAD

**Issue by gasinvein** [flatpak/flatpak#2266]
## Linux distribution and version
Fedora 28
## Flatpak version
1.0.4
## Description of the problem
Subj. With Nvidia GPU, OpenCL requires device node `/dev/nvidia-uvm` (and probably `/dev/nvidia-uvm-tools`). I think those should be made available inside sandbox with `--device=dri`.
## Steps to reproduce
1. Run anything using OpenCL (e.g. `clinfo`) inside flatpak without `--device=all`.
2. Note that OpenCL is unavailable.

**Comment by TingPing** [comment]
On Nvidia 410.57 here `/dev/nvidia-uvm` does not exist. Do you know what versions have this?

**Comment by gasinvein** [comment]
`nvidia-uvm` module is not loaded by default, at least on Fedora.

**Comment by TingPing** [comment]
So does OpenCL work on the host in that case even?

**Comment by gasinvein** [comment]
I guess not, you have to load the kernel module first.

**Comment by TingPing** [comment]
Just as an update I have confirmed this is necessary and needed for CUDA also. On Fedora this requires installing `xorg-x11-drv-nvidia-cuda` and rebooting.

So we should probably just pass it through if it exists but it will still be up to the user to configure their system properly sadly.
