### ISSUE TITLE
Cannot build bundle

### ISSUE THREAD

**Issue by advius** [flatpak/flatpak#2268]
I can't build-bundle from installed gimp from flathub,
I tried 
flatpak build-bundle /var/lib/flatpak/app gimp.flatpak org.gimp.GIMP
but flatpak replied 
opendir(objects): No such file or directory

Fedora 28 Workstation
Flatpak 1.0.4  

Thank you for answer.

**Comment by kirbyfan64** [comment]
> /var/lib/flatpak/app

Pretty sure that isn't correct, though I'm not sure what exactly it should be...maybe try /var/lib/flatpak/repo?

**Comment by advius** [comment]
Thank you,

but I can't see org.gimp.GIMP
![snimek obrazovky porizeny 2018-10-21 15-50-14](https://user-images.githubusercontent.com/40942201/47267828-11a2a200-d549-11e8-923b-64fa832540fe.png)

**Comment by kirbyfan64** [comment]
That's not how build-bundle works. IIRC the first argument is the path to the OSTree repo, meaning that there's not going to be an org.gimp.GIMP folder. The command should still work, however.

**Comment by advius** [comment]
Terminal replied
Refspec 'app/org.gimp.GIMP/x86_64/master' not found.

**Comment by advius** [comment]
Thank you very much,
Please can you show me an example?

**Comment by TingPing** [comment]
`flatpak build-bundle /var/lib/flatpak/repo gimp.flatpak org.gimp.GIMP stable`

**Comment by advius** [comment]
Thank you very much for your help.

**Comment by advius** [comment]
I have same problem with build bundle with gnome.platform.

command:
flatpak build-bundle /var/lib/flatpak/repo gnome.flatpak org.gnome.Platform 3.28

terminal replied:
Refspec 'app/org.gnome.Platform/x86_64/3.28' not found

Thank you for answer.
