### ISSUE TITLE
Non-negligible startup overhead

### ISSUE THREAD

**Issue by wjt** [flatpak/flatpak#2275]
Distro | Flatpak | bwrap | fontconfig | Turing machine
--|--|--|--|--
Fedora 28 | 1.0.3 | 0.3.0 | fontconfig-2.13.0-5.fc28.i686 | Dell XPS 13 (2015), i7-5500U CPU @ 2.40GHz, SSD
Endless 3.4.8 | 1.0.0 | 0.3.0 | 2.12.92-0endless11bem1 | Lenovo Yoga 900 (2016), i5-6200U CPU @ 2.30GHz, SSD

## Description of the problem

Launching applications is several orders of magnitude slower inside Flatpak than outside. For long-lived applications this is not such a big deal, but if (for example) you used Flatpak:d Vim as your `$EDITOR` then the startup time being more than 1 second (as opposed to microseconds outside Flatpak) really hurts whenever you run `git commit`.

I looked into this because I noticed that https://github.com/indie-mirror/gnomit#slow-start-up-time – a Git commit editor app, which has the same requirement to launch quickly as Vim does for me – says:

> Compared to directly running the GJS script, the Flatpak version has a noticable delay before the Gnomit dialogue pops up.
> 
> Reportedly, the issue with slow start-up times [has been fixed](https://blogs.gnome.org/alexl/2018/01/16/fixing-flatpak-startup-times/) but we won’t be seeing the improvements until Linux distributions start pushing out version 2.13.0 of the fontconfig package.

If they're hoping that startup times will be identical inside and outside Flatpak with a newer Fontconfig, I think they will be disappointed. `ind.ie.Gnomit --version` on the XPS 13 takes 0.070+/-0.0012 outside and 0.203+/-0.0040 inside. (Not tested on the Yoga since GLib is too old on the Endless host system for Gnomit.)

## Steps to reproduce

* Clone and build https://github.com/ltratt/multitime (a `time`-like tool which runs commands many times and gives you statistics on their runtime)
* Install some apps both as Flatpaks and from distro packages. I used `/bin/true` (no installation required) and Vim (`vim-enhanced` on Fedora, `vim-gtk3` on Endless OS; I think these configurations are comparable to the Flathub one)
* Create a `BATCHFILE` like the following:

```
/bin/true
flatpak run --command=/bin/true org.freedesktop.Platform//18.08
flatpak run --command=/bin/true org.freedesktop.Platform//1.6
/bin/vim --cmd :q
org.vim.Vim --cmd :q
/bin/vim -c :q
org.vim.Vim -c :q
```

(`vim --cmd :q` runs the given command (Quit) immediately, before reading config files; `vim -c :q` runs the command once the Vim session is fully up and running.)

* Run `multitime-b BATCHFILE -n 100 -s 0` to run each command in `BATCHFILE` 100 times, with 0 seconds pause between them, and display statistics

Results below. The gist is that on the XPS 13, `/bin/true` takes negligible time to start outside Flatpak, and ~140ms/~150ms depending on which version of the fd.o platform one uses. Vim takes 4ms (negligible) vs 1151ms (very noticable) without reading config files; reading my not-insubstantial config files adds 50-60ms regardless of whether it's inside or outside Flatpak. (The results on the Yoga 900 are similar but a little worse across the board, which is what I'd expect.)

XPS 13 results:

```
$ ~/src/ltratt/multitime/multitime -b ~/true.batch -n 100 -s 0
===> multitime results
1: /bin/true
            Mean                Std.Dev.    Min         Median      Max
real        0.001+/-0.0001      0.000       0.000       0.001       0.003       
user        0.000+/-0.0001      0.000       0.000       0.000       0.001       
sys         0.000+/-0.0001      0.000       0.000       0.000       0.001       

2: flatpak run --command=/bin/true org.freedesktop.Platform//18.08
            Mean                Std.Dev.    Min         Median      Max
real        0.141+/-0.0044      0.017       0.118       0.140       0.243       
user        0.021+/-0.0008      0.003       0.015       0.021       0.033       
sys         0.014+/-0.0008      0.003       0.008       0.014       0.026       

3: flatpak run --command=/bin/true org.freedesktop.Platform//1.6
            Mean                Std.Dev.    Min         Median      Max
real        0.151+/-0.0027      0.011       0.133       0.150       0.196       
user        0.021+/-0.0008      0.003       0.014       0.021       0.033       
sys         0.014+/-0.0008      0.003       0.007       0.014       0.023       

4: /bin/vim --cmd :q
            Mean                Std.Dev.    Min         Median      Max
real        0.004+/-0.0003      0.001       0.002       0.004       0.007       
user        0.002+/-0.0003      0.001       0.000       0.002       0.004       
sys         0.002+/-0.0003      0.001       0.000       0.002       0.005       

5: org.vim.Vim --cmd :q
            Mean                Std.Dev.    Min         Median      Max
real        1.152+/-0.0024      0.009       1.133       1.151       1.181       
user        0.021+/-0.0008      0.003       0.013       0.020       0.029       
sys         0.013+/-0.0007      0.003       0.007       0.013       0.022       

6: /bin/vim -c :q
            Mean                Std.Dev.    Min         Median      Max
real        0.060+/-0.0023      0.009       0.049       0.058       0.111       
user        0.044+/-0.0014      0.006       0.036       0.043       0.069       
sys         0.008+/-0.0007      0.003       0.002       0.008       0.016       

7: org.vim.Vim -c :q
            Mean                Std.Dev.    Min         Median      Max
real        1.206+/-0.0059      0.023       1.179       1.200       1.331       
user        0.022+/-0.0010      0.004       0.013       0.021       0.034       
sys         0.013+/-0.0007      0.003       0.006       0.013       0.022       
```

Yoga 900 results:

```
$ ~/src/ltratt/multitime/multitime -b ~/true.batch -n 100 -s 0
===> multitime results
1: /bin/true
            Mean                Std.Dev.    Min         Median      Max
real        0.001+/-0.0001      0.000       0.000       0.001       0.002       
user        0.000+/-0.0001      0.000       0.000       0.000       0.002       
sys         0.000+/-0.0001      0.000       0.000       0.000       0.001       

2: flatpak run --command=/bin/true org.freedesktop.Platform//18.08
            Mean                Std.Dev.    Min         Median      Max
real        0.253+/-0.0080      0.031       0.185       0.250       0.327       
user        0.020+/-0.0014      0.005       0.010       0.020       0.034       
sys         0.011+/-0.0013      0.005       0.001       0.010       0.025       

3: flatpak run --command=/bin/true org.freedesktop.Platform//1.6
            Mean                Std.Dev.    Min         Median      Max
real        0.265+/-0.0076      0.030       0.212       0.260       0.355       
user        0.021+/-0.0016      0.006       0.008       0.021       0.040       
sys         0.010+/-0.0015      0.006       0.000       0.010       0.027       

4: /bin/vim --cmd :q
            Mean                Std.Dev.    Min         Median      Max
real        0.017+/-0.0012      0.005       0.014       0.015       0.037       
user        0.013+/-0.0012      0.005       0.005       0.014       0.034       
sys         0.004+/-0.0010      0.004       0.000       0.004       0.016       

5: org.vim.Vim --cmd :q
            Mean                Std.Dev.    Min         Median      Max
real        1.183+/-0.0045      0.017       1.152       1.182       1.240       
user        0.020+/-0.0017      0.006       0.006       0.020       0.041       
sys         0.010+/-0.0014      0.005       0.000       0.009       0.023       

6: /bin/vim -c :q
            Mean                Std.Dev.    Min         Median      Max
real        0.177+/-0.0034      0.013       0.096       0.175       0.200       
user        0.066+/-0.0020      0.008       0.050       0.065       0.086       
sys         0.011+/-0.0015      0.006       0.000       0.012       0.027       

7: org.vim.Vim -c :q
            Mean                Std.Dev.    Min         Median      Max
real        1.231+/-0.0051      0.020       1.203       1.228       1.323       
user        0.019+/-0.0015      0.006       0.008       0.019       0.042       
sys         0.009+/-0.0013      0.005       0.000       0.008       0.027
```

**Comment by matthiasclasen** [comment]
are you just measuring the sandbox setup overhead here?

**Comment by fenryxo** [comment]
@wjt, just for curiosity, is there any negligible difference between `org.vim.Vim --cmd :q` and `flatpak run org.vim.Vim  --cmd :q`. The former involves a shell wrapper.

**Comment by wjt** [comment]
> are you just measuring the sandbox setup overhead here?

Yep, guess so. I filed this because I made an offhand remark about the "slow start-up times are fixed" idea and @nedrichards encouraged me to open a ticket to track the fact that, while the fontconfig problem may be behind us, start-up times are still slow. (Bastien also mentioned the Vim case on IRC a while back.) I thought I may as well quantify what “slow” means. I didn't dig into where the time is going.

> @wjt, just for curiosity, is there any non-negligible difference between org.vim.Vim --cmd :q and flatpak run org.vim.Vim --cmd :q. The former involves a shell wrapper.

Great question. It has no measurable impact.

```
1: org.vim.Vim --cmd :q
            Mean                Std.Dev.    Min         Median      Max
real        1.150+/-0.0036      0.014       1.123       1.149       1.213       
user        0.025+/-0.0009      0.003       0.016       0.025       0.036       
sys         0.013+/-0.0007      0.003       0.005       0.012       0.018       

2: flatpak run org.vim.Vim --cmd :q
            Mean                Std.Dev.    Min         Median      Max
real        1.151+/-0.0040      0.015       1.130       1.146       1.224       
user        0.025+/-0.0010      0.004       0.017       0.024       0.039       
sys         0.013+/-0.0008      0.003       0.007       0.012       0.023       

3: /bin/vim --cmd :q
            Mean                Std.Dev.    Min         Median      Max
real        0.004+/-0.0009      0.003       0.002       0.003       0.037       
user        0.002+/-0.0002      0.001       0.000       0.001       0.004       
sys         0.002+/-0.0003      0.001       0.000       0.002       0.007       
```

**Comment by wjt** [comment]
“Interestingly”, Vim is actually calling `sleep(1)` during startup.

```
10:33:41 nanosleep({tv_sec=1, tv_nsec=0}, 0x7ffe8a183580) = 0 <1.000077>
```

```
(gdb) bt
#0  0x0000003bf82b80d0 in nanosleep () at /lib/libc.so.6
#1  0x0000003bf82b804a in sleep () at /lib/libc.so.6
#2  0x00007ffff5d18e81 in IceOpenConnection () at /lib/libICE.so.6
#3  0x00007ffff5f30d1f in SmcOpenConnection () at /lib/libSM.so.6
#4  0x000000000051ac3a in  ()
#5  0x0000000000416885 in  ()
#6  0x0000003bf8220291 in __libc_start_main () at /lib/libc.so.6
#7  0x000000000041806a in  ()
```

So maybe that one's a red herring. Nothing so dramatic in `/bin/true` though.

**Comment by wjt** [comment]
As above, the 1-second pause was an issue in the Vim Flatpak. It's still true that setting up the sandbox has a measurable cost but I'll close this ticket which is full of misinformation about Vim :)
