### ISSUE TITLE
Suggestion : Upstream involved apps ... being marked with a sort of seal/mentioning their involvement !

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2281]
Hi,

I know flatpak/flathub team prefers upstream themselves maintain their flatpak apps ... and i have seen some application 'adding' efforts have been discouraged because of lack of upstream participation.

While it is great if an applications upstream maintains the flatpak versions of their apps ... and its certainly NOT all bad if a third party is doing so or wants to do it ... simply because the flatpak app collection is growing on as a result of third party individuals ... and i as a community using them duely thank them for their efforts.

Almost all apps are opensource ... so whether upstream participates in maintaining it or a third party is dedicated his/her time and efforts to do the same, Flatpak/Flathub's should welcome nevertheless ... because in an open source model every body is participating/contributing ... the third party individuals included ... hell even i am contributing, at least i like to believe so :).

**i remember one of the flatpak/flathub team members giving the reason behind discouraging third party maintainers and preferring direct upstream involvement as saying that a 'third party' could drop out or go missing at any moment and their maintained app would get orphaned !!!**

But don't you think 'dropping out' or 'going missing' is a risk that exists with every open source project / initiative ??? Even upstream members could get busy and drop out or their participation diminish over time due to developments in their personal lives ... but that shouldn't really be anybody's worry ... least of all of an initiative such as our's ... flatpak is a new and budding concept and for that having an all welcoming atmosphere is only conducive to its growth and a positive outcome !!!

If a third party maintainer drops out ... for all we know you'd have others volunteering to take over/adopt the orphaned app ... we have seen people volunteering here haven't we ?

Here is what i was thinking ... Flatpak/Flathub should go all out and encourage anybody and everybody to maintain apps for us(flatpak/flathub) ... let the fear of dropping out not worry us anymore ... at the same time we could continue to encourage upstream involvement ... like asking the third party maintainers as a first order of business, to ping the upstream of the app they want to maintain, this could serve as an unofficial message from flatpak/flathub, an unofficial invite of sorts ... after that the thirt party could be extended all support in getting the app added to flathub.

The challenges any apps upstream often face are best known to this team too ... @alexlarsson ... @matthiasclasen  ... @mwleeds ... are some of the most active members who are seen actively developing our project. ... others may contribute as per their availability ... but it isn't stopping the project from moving ahead is it ?

**I have seen some nice suggestions here ...

1. Like having a separate section on flathub website where we as users can vote for apps that we like to see packaged as a flatpak. This could encourage upstream to take note of things to consider participating, seeing the demand their apps are recording.

2. I would like to see every app on flathub to be marked ... with some 'seal' which conveys the fact that  'upstream is involved/active' in maintaining this particular app ... and all those non marked apps could be construed as being maintained by third party contributors. ... with a button to record a vote for upstream participation ... another unofficial nudge to upstream 

3. Application Usage/install count shown besides every app ... this again could potentially encourage upstream to take note of things and participate or adopt their apps officially ... if they find it used more it will be easier to sell / buy into our 'upstream participation objective' !

As you can understand all the above suggestions(many more if the community has any to offer) would be a much more organic approach to get upstream on board to maintain their respective apps ... A positive approach of developing the community and ecosystem around our project and increase its use.**

PS : I would appreciate if the team kept this thread open(consider this effort as a means of managing PR) for productive discussion and suggestions from  the user community as well ... We may not be technically involved with developing things for you, but we sure are part of this community testing and reporting things to this project ...

I would really appreciate if one of the members  didn't just post a few lines of reply and close it ... just because its against their current resolve or they see things a little different than our views/feedback.

thanks.

**Comment by TingPing** [comment]
Wrong repo: https://github.com/flathub/linux-store-frontend/issues/146

**Comment by TingPing** [comment]
I realize I closed this before reading the entire post which makes me look like an ass but even with all of this discussion this is the wrong place for it. That more general Flathub discussion (not Flatpak) could go in flathub/flathub. I'm not sure there is much purpose to that though as it still allows third party maintainers it just discourages it over upstream maintainers. I agree clear labeling is a good change to make things clearer also.
