### ISSUE TITLE
libnotify notify-send notifications are not forwarded to desktop

### ISSUE THREAD

**Issue by mildred** [flatpak/flatpak#2282]
## Linux distribution and version
Fedora Silverblue 29.1.2 (Workstation Edition)

## Flatpak version
flatpak-1.0.3-1.fc29.x86_64

## Description of the problem
notify-send invocations inside a flatpak are not forwarded to the desktop (running GNOME with pretty standard setup, installed few days ago). Documentation is telling that libnotify should be forwarded: http://docs.flatpak.org/en/latest/desktop-integration.html#notifications

> A number of toolkits and frameworks provide transparent support for Linux desktop notificatoions. This includes Electron, GTK, KDE and QML. **Applications not using one of these can either use the libnotify library** or portals. Of these, portals has the benefit that it can easily be used from within an application sandbox.

notify-send is using libnotify, it's built out of it...

## Steps to reproduce

With the manifest file `fr.mildred.libnotify.json` containing

```json
{
    "app-id": "fr.mildred.libnotify",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "18.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "notify-send",
    "modules": [
        {
            "name": "libnotify",
            "buildsystem": "autotools",
            "sources": [
                {
                    "type": "archive",
                    "url": "http://ftp.gnome.org/pub/gnome/sources/libnotify/0.7/libnotify-0.7.7.tar.xz",
                    "sha256": "9cb4ce315b2655860c524d46b56010874214ec27e854086c1a1d0260137efc04"
                }
            ]
        }
    ]
}
```

And running `flatpak-builder build fr.mildred.libnotify.json` to build the flatpak, running it like this:

    flatpak-builder --run build fr.mildred.libnotify.json notify-send Hello World

I should have received a notification in my desktop, but didn't receive anything.

After installing the generated flatpak and trying it out, it doesn't work any more.

**Comment by matthiasclasen** [comment]
the documentation is incorrect

**Comment by mildred** [comment]
Is there some command-line utility that can make use of the notification portal that could replace `notify-send` ?

**Comment by mildred** [comment]
Is it possible to implement the libnotify dBus API within the portal server? What would make it complicated?

**Comment by TingPing** [comment]
> Is it possible to implement the libnotify dBus API within the portal server? What would make it complicated?

It is impossible for all of `libnotify`'s API to keep working. You can make a subset of it working.

Honestly we just need to push applications away from libnotify and let it die, its a very bad API.

**Comment by TingPing** [comment]
Anyway if you need libnotify you can add the `--talk-name=org.freedesktop.Notifications` permission. I have edited the docs to simply not mention libnotify for now.

**Comment by TingPing** [comment]
You can make a small CLI tool using `GNotification` but I don't know of one that exists offhand. It is an odd-match in that it is really designed for applications not one-off scripts.

**Comment by mildred** [comment]
Thanks. My problem at hand is to package weechat, a terminal IRC client, and it uses various scripts to hook up to the notification system.

If you want people to stop using libnotify, is there a dBus API or a library that can be used both inside flatpak and outside of it? So application authors can safely migrate to a better API. Perhaps desktop environments should implement the portal API, I don't know.

**Comment by TingPing** [comment]
> Thanks. My problem at hand is to package weechat, a terminal IRC client, and it uses various scripts to hook up to the notification system.

You can just allow the permission I mentioned, its not a real security threat.

> f you want people to stop using libnotify, is there a dBus API or a library that can be used both inside flatpak and outside of it? So application authors can safely migrate to a better API. Perhaps desktop environments should implement the portal API, I don't know.

Sure as the docs you linked said Qt and GLib have notification APIs that work. WeeChat I believe is glib-phobic though so no there isn't a drop-in solution for them.

They would have to have their own abstraction that uses the portal when available otherwise the old api.
