### ISSUE TITLE
No documentation on how to share homedir in flatpaks

### ISSUE THREAD

**Issue by mildred** [flatpak/flatpak#2283]
I'm trying to build a flatpak and I want to share the homedir so the app can write its dotfile and keep its configuration across executions.

The man page for `flatpak run` states:

>  --filesystem=FS
> Allow the application access to a subset of the filesystem. This overrides to the Context section from the application metadata.

So I have to modify the metadata file, which is described on the `flatpak-metadata` manual page or on https://github.com/flatpak/flatpak/wiki/Metadata

But nowhere it is told where I should put this file whan building the flatpak with flatpak-builder. is is somewhere like `/app/share/metainfo/reverse.dns.name.metadata`? Where is this explained?

**Comment by TingPing** [comment]
`man flatpak-override`

aka:

`flatpak override --user --filesystem=home reverse.dns.name`

**Comment by mildred** [comment]
Yes, that's where it's explained. Sorry for the noise.
