### ISSUE TITLE
Integrate flatpak terminal applications in desktop GUI

### ISSUE THREAD

**Issue by mildred** [flatpak/flatpak#2285]
This is a feature request.

In order to get terminal application well integrated within the desktop environment, I'd like to have terminal applications like emacs, vim, irssi, mutt or other integrated with my desktop environment. I want them to be separated in alt-tab app switcher, and be separated in the application dock.

Outside of flatpak, this can be implemented with running a specific instance of gnome-terminal with a specific WMClass. in recent gnome-terminal, a specific gnome-terminal-server process that can advertise the specific WMClass.

Here is described what's needed, inclding the gnome-terminal dbus service: https://chrisirwin.ca/posts/multiple-instances-of-gnome-terminal/

A shorter desktop entry can be defined like this (example using irssi):

```
[Desktop Entry]
Comment=
Terminal=false
Name=irssi
Exec=/bin/sh -c '$(env PATH="/usr/libexec:/usr/lib/gnome-terminal:$PATH" which gnome-terminal-server) --app-id=fr.mildred.irssi --class=fr.mildred.irssi --name=fr.mildred.irssi & sleep 0.25; gnome-terminal --app-id=fr.mildred.irssi --hide-menubar -e "flatpak run fr.mildred.irssi" '
Categories=Network
Keywords=irssi,irc
StartupWMClass=fr.mildred.irssi
Type=Application
Icon=fr.mildred.irssi
Version=1.0
```

edit: see related gnome-terminal bug: https://gitlab.gnome.org/GNOME/gnome-terminal/issues/46

**Comment by TingPing** [comment]
Terminal apps should have `Terminal=true` and how that behaves is up to your shell and that is probably where this should be handled.

**Comment by TingPing** [comment]
> I filed an issue here, because in the case of applications that want to handle this themselves in their desktop entry file, and not using Terminal=true (which doesn't work at the moment), it's not currently possible.

It can't be possible, its a sandbox escape to choose a random application to run.
