### ISSUE TITLE
How to know the contents of runtime/flatpak?

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#2286]
## Linux distribution and version

Fedora 28

## Flatpak version

Flatpak 1.0.2

## Description of the problem

A long time ago, I asked how to get the contents of a runtime. I was told that I could look in several places, in particular `/usr/manifest.json` for the manifest of the current runtime (was it specific to GNOME SDK or a generic thing? No idea). And even to look further in the base manifest (i.e. Freedesktop), I could look at `/usr/manifest-base-1.json`, and even further for the yocto-built image, there was `/usr/manifest.base`.

Now I tested the new GNOME 3.30 SDK and realize these don't exist anymore. This was extremely useful to check the contents of a SDK very quickly. Why did these path disappear? Is it something generated by flatpak or should I make reports to these SDK?

And if not generated by flatpak, well could it? This was really necessary IMO for any app with a bit of dependencies (as GIMP). Note that it was interesting to not only see the contents, but also how it was built and from which source (i.e. indeed the actual full manifest used for building, not just a list of names).

## Steps to reproduce

```
$ flatpak run --devel --command=bash org.gnome.Sdk//3.28
bash-4.3$ ls /usr/manifest*
/usr/manifest.base  /usr/manifest-base-1.json  /usr/manifest.json
bash-4.3$ exit
exit
$ flatpak run --devel --command=bash org.gnome.Sdk//3.30
bash-4.4$ ls /usr/manifest*
ls: cannot access '/usr/manifest*': No such file or directory
bash-4.4$ exit
exit
```

**Comment by TingPing** [comment]
> Now I tested the new GNOME 3.30 SDK and realize these don't exist anymore. This was extremely useful to check the contents of a SDK very quickly. Why did these path disappear? Is it something generated by flatpak or should I make reports to these SDK?

The new SDK is built with BuildStream so it lost the manifest. It should return very soon though: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/376
