### ISSUE TITLE
flatpak lies about the downloaded amount

### ISSUE THREAD

**Issue by abderrahim** [flatpak/flatpak#2290]
## Linux distribution and version
Debian testing
## Flatpak version
Flatpak 1.0.4
## Description of the problem

When looking for updates, flatpak downloads a non-negligible amount of data, which can take anywhere from 15 sec (this is starting to take long) to 5 min (what the hell is this doing?). (btw, I'm using a mobile connection). At the end of this, it says it only downloaded about 1kb.

While progress report is important (see [this article](https://www.nngroup.com/articles/response-times-3-important-limits/)), I think it's more important to try to actually reduce this delay/downloaded amount, and actually report it correctly.

## Steps to reproduce
1. run e.g. `sudo nethogs -a -v 3`
1. run `flatpak update`

flatpak says
```
Looking for updates...
1 metadata, 0 content objects fetched; 569 B transferred in 0 seconds
1 metadata, 0 content objects fetched; 569 B transferred in 1 seconds
Installing in system:
[...]
Updating in system:
[...]
Is this ok [y/n]: 
```

while nethogs reports
```
PROGRAM                                             DEV        SENT      RECEIVED
flatpak                                             enp0s1      0.536      15.966 MB
```

**Comment by matthiasclasen** [comment]
this will be addressed by the new cli ux
