### ISSUE TITLE
mount /run/dconf/user/$UID into sandboxes

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2292]
this is used by dconf (in a fleet commander context), and mounting it should be harmless.

**Comment by alexlarsson** [comment]
This is really tied to how we generally expose dconf, so if we do this it should be done in combination with exposing /etc/dconf/db too. Maybe both could appear in /run/dconf in the sandbox.

**Comment by matthiasclasen** [comment]
See https://github.com/flatpak/flatpak/pull/2295 for what we came up with
