### ISSUE TITLE
GTK 2 apps don't fallback to Adwaita theme

### ISSUE THREAD

**Issue by hroncok** [flatpak/flatpak#2294]
## Linux distribution and version

Fedora 29 with Xfce.

## Flatpak version

Flatpak 1.0.4.

## Description of the problem

My GTK theme is not Adwita but Greybird.
When I install a GTK2 app (such as Inkscape) with Flatpak and launch it, it looks like Windows 95 (= no GTK2 theme). When I switch my theme to Adwita, the Flatpak app switches to Adwita.

Installing `org.gtk.Gtk3theme.Greybird` does not solve this, as Inkscape is an GTK 2 app.

**Could flatpak GTK2 apps default to Adwita instead of defaulting to "no theme"?**

This is related to https://github.com/flatpak/flatpak/issues/114 yet different: I don't (necessarily) want to get the GTK2 theme in Flatpak, I just want a more reasonable default.

## Steps to reproduce

```console
$ sudo dnf remove inkscape
$ sudo dnf install flatpak greybird-gtk*-theme
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install flathub org.inkscape.Inkscape
$ flatpak install org.gtk.Gtk3theme.Greybird  # optional, doesn't change the behavior
$ # ... set Greybird in Xfce Appearance Settings 
$ flatpak run org.inkscape.Inkscape
```

![screenshot](https://churchyard.fedorapeople.org/inkscape-theme.png)

Flatpak on the left, "native" on the right.

**Comment by TingPing** [comment]
This should go away once Inkscape updates to the 3.30 runtime.

**Comment by hroncok** [comment]
Is this supposed to be fixed? I've updated the inkscape flatpak from flathub and the problem is still there.

**Comment by TingPing** [comment]
Its a app/package specific bug then. GTK2 in the GNOME runtime falls back to Adwaita or Adwaita-dark automatically.

**Comment by Mailaender** [comment]
https://github.com/flathub/shared-modules/tree/master/gtk2 claims to have support for themes. Some are disabled though, including KDE Breeze so that is broken for me.

**Comment by TingPing** [comment]
@Mailaender I have no idea why you bumped this issue...

But I believe the Breeze theme depends on Qt and KDE libs? It has been a while but it was insane. Feel free to see if its easier these days.

**Comment by Mailaender** [comment]
I submitted https://github.com/flathub/shared-modules/pull/253 to fix that.
