### ISSUE TITLE
Decide whether to include generated docs in tarballs or not

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#230]
We currently include gtk-doc-generated docs, but not generated man pages, which is a bit inconsistent.

**Comment by smcv** [comment]
If we want to include the generated man pages, https://github.com/flatpak/flatpak/pull/226 has some notes on the steps to do it correctly.

**Comment by smcv** [comment]
What was the decision?

**Comment by matthiasclasen** [comment]
I figured the decision is: whatever we are doing in releases now.
