### ISSUE TITLE
gpg-agent socket

### ISSUE THREAD

**Issue by fiaxh** [flatpak/flatpak#2301]
Currently, the gpg-agent can't be properly used out of the sandbox. An `--socket=gpg-agent` option would be helpful.

**Comment by SISheogorath** [comment]
@brainBlasted any plans to bring your changes towards upstream?

**Comment by BrainBlasted** [comment]
@SISheogorath eventually. IIRC I didn't finish the work to get things working there, and time hasn't been very permitting.

**Comment by apapsch** [comment]
I took a look at the commit and it seems to be a matter of removing a prefix from grep output. If the socket bind is all that is required, getting things done should be quite in reach :-)

**Comment by rugk** [comment]
This is needed for https://github.com/dino/dino/pull/343, i.e. a release of the Dino XMPP client as a flatpak, because the Dino devs insist on having the feature of PGP-encrypting your chats.

**Comment by SISheogorath** [comment]
@rugk as a quick solution you might want to have a peek into evolution's build instructions. They get GnuPG support by mounting the keyring directory. (Of course not perfect, but at least workable and not less secure than running it outside of Flatpak on an average distro.)

**Comment by bochecha** [comment]
Hi, I'm the person who wrote the Flatpak manifest for Dino. :wave: 

> @rugk as a quick solution you might want to have a peek into evolution's build instructions. They get GnuPG support by mounting the keyring directory. (Of course not perfect, but at least workable and not less secure than running it outside of Flatpak on an average distro.)

We know, that's all explained behind the link provided by @rugk, including the decision not to do that.

@rugk https://github.com/dino/dino/pull/343 had already been linked to this issue previously by the OP, who in fact is the Dino maintainer. We know Dino needs this. :wink: 

(please do not respond here if you want to add something to the topic of Dino; this ticket is about the gpg-agent socket for Flatpak, let's not pollute it with side conversations)

**Comment by AsciiWolf** [comment]
Any update regarding this issue?

**Comment by RomanRiabenko** [comment]
Hello. I would like to attract more attention to this issue. Would it be appropriate to open a bounty for it at bountysource? I ask in case there is any objection or advice against it. If not, I will proceed with opening a bounty by the next week. I looked though the project and didn't find anything against this.
