### ISSUE TITLE
/app/share/applications subdirs are not exported

### ISSUE THREAD

**Issue by bam80** [flatpak/flatpak#2319]
Normally, .desktop files are installed in top of `/app/share/applications` directory itself and exported from there.
But, if the files are placed in any subdirectory of _/app/share/applications/_ - they are not exported with error at install time:
`flatpak install: Not exporting file org.flatpak.Hello.desktop of unsupported type.`

It seems incorrect, because on the host side, there can be any levels of subdirectories in `$XDG_DATA_DIRS/applications/` for .desktop files to be found.
Some apps install their .desktop files in the subdirs.

**Comment by TingPing** [comment]
This actually seems like correct behavior. To quote the [spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html):

> To determine the ID of a desktop file, make its full path relative to the $XDG_DATA_DIRS component in which the desktop file is installed, remove the "applications/" prefix, and turn '/' into '-'.
> For example /usr/share/applications/foo/bar.desktop has the desktop file ID foo-bar.desktop.

So `/app/share/applications/foo/org.flatpak.Hello.desktop` turns into `foo-org.flatpak.Hello.desktop` which indeed should not be exported.

Now one situation that *should* be exported is `/app/share/applications/org.flatpak.Hello/foo.desktop` which would be interesting to test.

**Comment by bam80** [comment]
No, that doesn't work either. Such in-consistence with desktop behavior lead to problems with the software installations.
Moreover, `unsupported type` error seems confused.

**Comment by matthiasclasen** [comment]
Installing desktop files in subdirectories of /usr/share/applications is an obsolescent feature of the desktop entry spec (grandfathered in for kde3), which has unpleasant consequences for the app-id, and thus support for it was intentionally removed from flatpak.

Just name your desktop file after your app id, and install it in /usr/share/applications.

**Comment by bam80** [comment]
@matthiasclasen
Didn't know it's an obsolescent feature. Do you mean it will be dropped on Desktops either?

**Comment by TingPing** [comment]
> I'm asking because one of my projects depends on it heavily..

Well considering the files need renamed even if this was supported it doesn't matter in practice to rename all of them anyway.

**Comment by matthiasclasen** [comment]
I'm not predicting if it will be dropped or not, but you are better off not relying on it.
