### ISSUE TITLE
Unable to build KDE apps after commit b42bc35

### ISSUE THREAD

**Issue by aelog** [flatpak/flatpak#232]
After commit b42bc35, I get the "Icon not matching app id" error when trying to build any KDE application from http://quickgit.kde.org/?p=flatpak-kde-applications.git

I was able to fix this issue by adding the `org.kde` prefix to the `Icon` field of the app .desktop file and to the name of the icon(s) installed by the app (e.g. `48-apps-foo.png` => `48-apps-org.kde.foo.png`).

Is there a reason (a freedesktop standard?) why the icon has to match the `org.kde.foo` "app id"? This would require patching every KDE application and renaming their icons, in order to build with flatpak...

Maybe you could consider to downgrade the error to a simple warning?

**Comment by matthiasclasen** [comment]
flatpak requires that all exported files (desktop file, dbus service file, icon,...) are prefixed with the app-id, in order to avoid conflicts If you are using flatpak-builder, you can instruct it to rename the icon on-the-fly (see the rename-icon option).

**Comment by aelog** [comment]
Thanks, rename-icon does the trick, it seems.

However, what about icons *not* installed by the app?
For example Dolphin has `Icon=system-file-manager` as per freedesktop icon spec, but using `"rename-icon": "system-file-manager"`
in the json manifest doesn't work, as flatpak doesn't find the icon in the dolphin files...

```
Error: icon system-file-manager not found below /home/elvis/dev/kde/src/flatpak-kde-applications/app/files/share/icons
```

**Comment by matthiasclasen** [comment]
I guess that is a case I hadn't really considered. Using theme-provided icons for applications is somewhat frowned upon nowadays. If it is something we need to allow, then that check is indeed wrong.

**Comment by matthiasclasen** [comment]
See #233 for a possible patch.

**Comment by matthiasclasen** [comment]
Merged

**Comment by aelog** [comment]
Thanks!
