### ISSUE TITLE
Yaru Icon Theme not properly passed through

### ISSUE THREAD

**Issue by Ads20000** [flatpak/flatpak#2320]
## Linux distribution and version
Ubuntu 18.10

## Flatpak version
1.0.4-1

## Description of the problem
The lines in the window buttons and hamburger menus are too thick in both snaps and Flatpaks for GNOME apps e.g. the FilesMaster Flatpak.
For more, see https://github.com/ubuntu/yaru/issues/913
@Feichtmeier reckons that this is a Flatpak issue not a Yaru issue

## Steps to reproduce
1-4 should reproduce the issue, 5-16 is to compare with other apps.
1. `sudo apt install flatpak`
2. `flatpak remote-add --from gnome-apps-nightly https://sdk.gnome.org/gnome-apps-nightly.flatpakrepo`
3. `flatpak install gnome-apps-nightly org.gnome.NautilusMaster`
4. `flatpak run org.gnome.NautilusMaster`
5. See that the lines are too thick.
6. `snap install gnome-clocks`
7. `snap run gnome-clocks`
8. See that the lines are too thick.
9. `snap install gnome-characters`
10. `snap run gnome-characters`
11.  See that the lines are too thick
12. `snap install mailspring`
13. `snap run mailspring`
14. See that the lines are not too thick
15. `/usr/bin/nautilus`
16. See that the lines are not too thick

**Comment by matthiasclasen** [comment]
I don't see any indication here that flatpak is to blame. This needs to be debugged on the systems where you observe it.

**Comment by clobrano** [comment]
@matthiasclasen, I am not too skilled in this, could you give us a hint on how to debug which icon are taken in headerbars? If possible, of course

**Comment by clobrano** [comment]
> flatpak makes host icon themes available in the sandbox.

@matthiasclasen, it seems that only headerbar icons are affected by this issue, since the rest of the gtk icons are correct. Any idea why this could happen in the sandbox?

**Comment by Feichtmeier** [comment]
I don't think that it's headerbar only, look closely, it's using adwaita icons in the sidebar too:

**Comment by clobrano** [comment]
You're right. So, maybe only symbolic icons?

**Comment by Feichtmeier** [comment]
I think all icons that are used within the app. I'll check how it looks in Pop OS + flatpaks

**Comment by TingPing** [comment]
Maybe the installed icons on the host use some problematic symlinks or something?

**Comment by clobrano** [comment]
@TingPing, are symlinks unsupported?

**Comment by TingPing** [comment]
@clobrano Well if a symlink points to `/usr/share` for example it is simply broken as that isn't the path in the sandbox. If it uses relative symlinks they should just work.

**Comment by Feichtmeier** [comment]
It looks like all .svg's are images and not symlinks
![image](https://user-images.githubusercontent.com/15329494/48564282-5f1af080-e8f6-11e8-996f-07ae0f7c5311.png)
![image](https://user-images.githubusercontent.com/15329494/48564576-f4b68000-e8f6-11e8-8ffb-9080a5fc92b4.png)


For example how symlinks look
![image](https://user-images.githubusercontent.com/15329494/48564488-ce90e000-e8f6-11e8-9289-ecc250076881.png)

**Comment by clobrano** [comment]
This is weird. I installed gnome-clocks from flathub, but it uses the right icons

![image](https://user-images.githubusercontent.com/2883614/48567340-161a6a80-e8fd-11e8-804e-7a5837a7dcfa.png)

I didn't installed NautilusMaster because of missing dependency (org.gnome.Platform/x86_64/master)

**Comment by clobrano** [comment]
It looks good in Bionic as well

![image](https://user-images.githubusercontent.com/2883614/48698837-64bf5180-ebe8-11e8-9859-01705279307e.png)

![image](https://user-images.githubusercontent.com/2883614/48698926-99330d80-ebe8-11e8-83b5-fb69b16eee3e.png)

**Comment by Feichtmeier** [comment]
So can we close the Yaru repo issue then? It looks like it was something temporary or with your setup @ads20000 ? Best regards

**Comment by Ads20000** [comment]
Yes do close it unless and until it comes up again.
