### ISSUE TITLE
Allow reaping spawned process via HostCommand when flatpak exists

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#2326]
Currently, the HostCommand interface allows for flags such as:

```c
typedef enum {
  FLATPAK_HOST_COMMAND_FLAGS_CLEAR_ENV = 1 << 0,
} FlatpakHostCommandFlags;
```

We might want to extend that to add something like:

```c
  FLATPAK_HOST_COMMAND_FLAGS_REAP_ON_EXIT = 1 << 1,
```

with the purpose to ensure that spawned processes are reaped when the Flatpak exits such as after a crash. Since the app is not in the parent process (or even in the same pgroup) we can't use `prctl()` to ensure the process exists.

I assume this will require a bit of coordination with the session helper.

**Comment by matthiasclasen** [comment]
Sounds useful

**Comment by matthiasclasen** [comment]
But this is not so much about reaping, but killing, I assume ?

**Comment by matthiasclasen** [comment]
We may want a similar flag for org.freedesktop.portal.Flatpak.Spawn

**Comment by alexlarsson** [comment]
Yeah, seems very useful. It won't be trivial to implement though, as there is no global thing that keeps track of all live sandboxes. You have to somehow get told that the pid1 in the sandbox died. The way the dbus proxy does this is to pass a pipe fd into pid1 and check for errors on that from the write side dying. However, that is possible at startup, but what about in the middle of everything?

One option would be to have a different behaviour: Reap if the calling unique dbus peer disconnects from the bus. That would be more like a process group (not a sandbox group), but might be what most people really want anyway. Then if they want a sandbox group they can fork a daemon process and call it from that.

**Comment by matthiasclasen** [comment]
@chergert want to come up with a patch that works for you ?

**Comment by chergert** [comment]
I'm knee deep in a month long refactoring of Builder, so chances that I can really focus on it are a bit out of the short-term. After that, I could take a look.

The main reason I filed this was for https://gitlab.gnome.org/GNOME/gnome-builder/issues/704

**Comment by chergert** [comment]
PID Namespaces

**Comment by fbruetting** [comment]
Sorry if this is a silly question, but why can’t a subprocess of e.g. a Builder terminal be started in the same PID namespace as Builder, for the terminal to gain control over that subprocess?

**Comment by matthiasclasen** [comment]
The process inside the sandbox doesn't have the necessary privileges to create another one

**Comment by matthiasclasen** [comment]
Pushed a quick implementation of this for HostCommand. Needs testing

**Comment by smcv** [comment]
Follow-up: #2417
