### ISSUE TITLE
Authentication is required to install ostree-metadata from flathub

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2328]
Do we want the user to authenticate just to download metadata? That seems to be the case currently:

![screenshot from 2018-11-15 17-02-20](https://user-images.githubusercontent.com/7833263/48591377-7e1a8200-e8f8-11e8-8ce8-0d2c19e9a5e2.png)

**Comment by matthiasclasen** [comment]
Ha! Putting the details in the ui reveals the nonsense

**Comment by kalev** [comment]
Is this popping up because gnome-software is downloading the metadata in the background?

Should gnome-software do something differently? Like, check that it has permissions to download metadata with g_permission_get_allowed() and if not, not do automatic updates?

**Comment by kalev** [comment]
Fair enough, but how about regular users who aren't in wheel/sudo? Should gnome-software do something differently there to not spam them with metadata updating polkit prompts?

**Comment by matthiasclasen** [comment]
@kalev if we want to support some sort of locked-down use case where the system installation is entirely readonly for users, then yes, g-s should not trigger those dialogs for background operations. Maybe this can be done by providing some 'allow-interactive' or 'background' flag to the system helper. I think we've done this sort of hint in other places before ?

**Comment by kalev** [comment]
I'm thinking that polkit prompts popping up out of nowhere is bad user experience regardless of whether it's a locked down account or a regular user.

Maybe gnome-software should just skip doing background updates if it can't do it without acquiring polkit permissions? I think it's already possible to check this with g_permission_get_allowed() without adding new API.

packagekit has a "background" concept, but there "background" means something else, that the background tasks get cancelled as soon as a non-background (user initiated) task comes in.

**Comment by matthiasclasen** [comment]
See https://github.com/flatpak/flatpak/pull/2367

**Comment by kalev** [comment]
Ooh, awesome!

**Comment by matthiasclasen** [comment]
some open questions:
- what name is better, BACKGROUND or no_interaction ? currently its a mix, for the worst of both worlds
- should we use the opportunity to add flags to all system helper methods ?

**Comment by matthiasclasen** [comment]
I answered the first question myself, by renaming it all to no_interaction, and I made a separate PR for adding flags

**Comment by matthiasclasen** [comment]
Looking at the code, the system-helper returns GIO_DBUS_ERROR_ACCESS_DENIED in this case (the same as if the user mistyped his password), which should bubble up all the way.

**Comment by kalev** [comment]
That should work. Right now gnome-software shows a helpful "Unable to download updates: you do not have permission to install software" when it gets that error, but I think we can improve on that and just ignore it :)

**Comment by matthiasclasen** [comment]
Quitly accepting defeat would be the right thing to do, in the no-interaction case. I can add getters for the no-interaction flag on the transaction and installation objects, if that makes it easier to differentiate.

**Comment by kalev** [comment]
Yeah, maybe that would be good if it's easy to do. I think gnome-software can handle keeping the no-interaction state on its own too, but it's possible it makes it easier in certain places, and it sounds like an easy thing to expose in libflatpak.

**Comment by matthiasclasen** [comment]
The PR now has flatpak_installation_[sg]et_no_interaction. I decided that we can do without a setter in the transaction, since you can just operate on the underlying installation.

**Comment by ramcq** [comment]
I don't get the reasoning here, if we just make these noninteractive but don't change the PolKit logic / make a different action / something, we're "downgrading" the upgrade privelege to be basically useless unless you have the install privelege, because any upgrade op will also need to install metadata, and potentially new runtimes. That's inconsistent with our current defaults (non-priveleged users can upgrade but not install) and renders the two verbs useless/indivisible. So these changes are good (the noninteractive stuff) but we have more underlying issues to tackle:
1. I think we need to have a different (more permissable) action that covers metadata updates - moving it to "modify-repo" makes it worse because it's easy to imagine a system where the admin wants to control the remotes but is happy to allow users to install or upgrade from those remotes. Defining/modifying repos is "more priveleged" than install, not less.
2. We need to be able to figure out how to apply the upgrade perms to an install op that takes place as a part of an upgrade transaction.

**Comment by matthiasclasen** [comment]
basically, the reasoning is:
- the desired experience for background operations is that they happen in the background, without interrupting the user
- if the polkit policy does not let us implement that (by insisting on interaction), we can't do background operations, so we don't

you're right that we should work on the policy to make them possible

**Comment by matthiasclasen** [comment]
> Defining/modifying repos is "more priveleged" than install, not less.

I agree with this. So here are some suggestions:

- Make all-update imply runtime-install and runtime-update, policy-wise
- Add a separate metadata-update action

**Comment by matthiasclasen** [comment]
See https://github.com/flatpak/flatpak/pull/2383 for these changes

**Comment by mwleeds** [comment]
> I think we need to have a different (more permissable) action that covers metadata updates - moving it to "modify-repo" makes it worse because it's easy to imagine a system where the admin wants to control the remotes but is happy to allow users to install or upgrade from those remotes. Defining/modifying repos is "more priveleged" than install, not less.

`modify-repo` is not the action used for adding new remotes or modifying existing ones. That happens under `configure-remote`.

**Comment by matthiasclasen** [comment]
And see https://github.com/flatpak/flatpak/pull/2384 for another batch of polkit changes that gets us to the ideal of '1 transaction, (at most) 1 dialog'

**Comment by kalev** [comment]
Awesome stuff :)
