### ISSUE TITLE
Regarding recent fuzzy matching added to 'Install' command ...

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2334]
@mwleeds  ...  I just upgraded to the latest flatpak ... eager to try the fuzzy matching feature you just implemented for the install command ... is this feature released in Version 1.0.5 ?

If so, could you please describe how it is to be used ?

**Comment by mwleeds** [comment]
No, it's in 1.1.0. Is https://github.com/flatpak/flatpak/issues/1258#issuecomment-436748896 not clear on how to use it?

**Comment by aiamuzz** [comment]
> No, it's in 1.1.0. Is #1258 (comment) not clear on how to use it?

so the usage is correct ... its just that my version does not have that feature yet ...

If 1.1.0 has it ... then i need to wait until Debian adds version 1.1.0 to the repos ... currently version 1.0.5 is as far as they've got ...

:( ... If only deb installers were released too ...

**Comment by aiamuzz** [comment]
If the usage is ...

`flatpak install music`

1. Is there no need to mention flathub as the remote ?
2. Will this fuzzy matching implementation work even for the command ... `flatpak --installation=customLocation install music` ... ?

**Comment by matthiasclasen** [comment]
yes

**Comment by matthiasclasen** [comment]
These kinds of questions are best asked on irc. They can also be answered by reading the man page, of course...

**Comment by aiamuzz** [comment]
> They can also be answered by reading the man page, of course...

FYI ... i tried that first and then posted it here ... turns out version 1.0.5 does not have this feature implemented as result i could not locate any info in the man pages ...
