### ISSUE TITLE
Flawfinder report

### ISSUE THREAD

**Issue by Maryse47** [flatpak/flatpak#2343]
## Flatpak version
git master
## Description of the problem
This is summary from [flawfinder](https://www.dwheeler.com/flawfinder/) report. You may find something useful for you. Full log attached below.

```
ANALYSIS SUMMARY:

Hits = 253
Lines analyzed = 76159 in approximately 1.47 seconds (51947 lines/second)
Physical Source Lines of Code (SLOC) = 57668
Hits@level = [0]   2 [1] 113 [2]  57 [3]  19 [4]  55 [5]   9
Hits@level+ = [0+] 255 [1+] 253 [2+] 140 [3+]  83 [4+]  64 [5+]   9
Hits/KSLOC@level+ = [0+] 4.42186 [1+] 4.38718 [2+] 2.42769 [3+] 1.43927 [4+] 1.1098 [5+] 0.156066
Dot directories skipped = 2 (--followdotdir overrides)
Minimum risk level = 1
Not every hit is necessarily a security vulnerability.
There may be other security vulnerabilities; review your code!
See 'Secure Programming HOWTO'
(https://dwheeler.com/secure-programs) for more information.
```
## Steps to reproduce
`flawfinder -cQ flatpak`

[flawfinder-flatpak.txt](https://github.com/flatpak/flatpak/files/2609163/flawfinder-flatpak.txt)

**Comment by matthiasclasen** [comment]
This is very repetitive, and not directly actionable.

**Comment by Maryse47** [comment]
I recommend for devs to check for potential issues themselves an maybe add those checks to CI infra.
