### ISSUE TITLE
Width of the longest line of console output influences all other output lines

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#2346]
## Linux distribution and version
F29SB

## Flatpak version
v1.0.6

## Description of the problem
Okay, pretty minor issue, but still not that nice when you have to resize your terminal. Seems like Flatpaks output prints the whole terminal width full with whitespace to match the width of the longest line. So that when you resize the terminal, this “active” whitespace leads to a lot of superfluous new lines, on lines which actually don’t need that.

I made a screencast, but GitHub (in contrast to GitLab) sadly doesn’t support that awesome WebM format, which is why you get an archive instead:

[Peek 2018-11-24 16-59.zip](https://github.com/flatpak/flatpak/files/2612393/Peek.2018-11-24.16-59.zip)

**Comment by matthiasclasen** [comment]
We're now ellipsizing and have a --columns option to choose which columns you want to see.
