### ISSUE TITLE
Summary updates for system OCI repositories

### ISSUE THREAD

**Issue by owtaylor** [flatpak/flatpak#2350]
The we designed OCI support is that when you call `flatpak_dir_get_remote_state()` on an OCI repository, it updates the cached version of the image index in `$dir/oci/$remote.index.gz` - it consults the saved Cached-Control, ETag, etc, headers and skips the download entirely or sends If-None-Match / If-Modified-Since headers as appropriate. Then if the image index changed, it regenerates `$dir/oci/$remote.summary` and returns the contents of that.

This *only* works if you have write-access to the flatpak-dir.

On the other hand when you call `flatpak_dir_get_remote_state()` on a non-OCI repository, it (as far as I can tell) just always downloads the entire summary from the remote - mediated only by an in-memory cache.

This doesn't need write-access to the flatpak-dir.

The problem here is when we have a system OCI repository - when you do `flatpak remote-ls` on it, the user-level flatpak process will try to update the system cache and fail. (Right now, it fails for a stupid reason - the index cache is 0600 - but fixing that wouldn't get us much further.)

Possible solutions:
 * Add a system-helper method to update the cached summary, call that and then use the cached summary.
 * Just always download image index in the same we we always download the summary - it's bigger than the summary, but not way bigger.

I generally think the first is better. If we want `flatpak remote-ls` to *always* return fresh data, it might make sense to pass through some flag to ignore the Expires header and do a HTTP request (made efficient by If-None-Match/If-Modified-Since)

**Comment by alexlarsson** [comment]
We don't always download the summary actually, flatpak calls ostree_repo_set_cache_dir() to set the cache dir to  ~/.cache/flatpak/system-cache/, and the summaries are cached under that.

I actually have a ~/.cache/flatpak/system-cache/oci-summaries directory, but its only got a really old file. I guess we regressed on supporting that at some point?

**Comment by owtaylor** [comment]
I think the user-level caching of OCI summaries got removed when I switched things over to having the system helper handle downloading the index and updating the appstream. I didn't know at that point that the summaries were sometimes used directly for query operations without going through the system helper.

Because we don't have GPG signatures on the index or generated summary, downloads by the user can never be used by the system-helper, so we either download twice, or have the system-helper do the download. Downloading twice makes me worry about things getting out of sync in more complicated cases, though it would be harmless for `remote-ls`.

**Comment by alexlarsson** [comment]
Well, remote-ls is one thing, but its also used for e.g. tab-completion and things like "pick an existing remote ref from a partial ref", so diverging would be bad for that.

**Comment by alexlarsson** [comment]
So, i agree with you on the new system-helper operation.

**Comment by alexlarsson** [comment]
@owtaylor I did a PR for this. Can you review that and test it a bit?
I only tested it superficially, but it seems to work.

It should apply cleanly to 1.0, so we can easily put it in the fedora packages. (I don't think it makes sense to backport in the official releases).
