### ISSUE TITLE
 Add GL flatpak support for Nvidia driver 415.18.02

### ISSUE THREAD

**Issue by tannisroot** [flatpak/flatpak#2352]
Now, I understand that usually you don't package GL runtime for these dev drivers, but this one contains Vulkan transform feedback extension that is required by DXVK (used in Valve's Proton) to make quite a lot of games function properly, and it is not yet present in mainstream drivers.
So now, users have to either stick to mainstream driver and not be able to play their games, or abandon using Flatpak.
So if it's possible, it would be awesome to make an exception here.

**Comment by TingPing** [comment]
We can just keep the discussion in one thread: https://github.com/flathub/flathub/issues/619
