### ISSUE TITLE
Trying to Build and Install popcorn-flatpak ... doesn't seem to install ...

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2359]
Hi,

I just followed the steps to build and install the app from here ... ... https://gitlab.com/Preisschild/popcorntime-flatpak ...  ... turns out the commands are completing but can't seem to find the app installation ...

enclosing log for the build command ...
`flatpak-builder --install --install-deps-from=flathub popcorntime sh.popcorntime.PopcornTime.yml --force-clean >> popcornFlatpakInstall.log
`
[popcornFlatpakInstall.log](https://github.com/flatpak/flatpak/files/2634827/popcornFlatpakInstall.log)

```
flatpak-builder --installation=myFlatpaks --install --install-deps-from=flathub popcorntime sh.popcorntime.PopcornTime.yml --force-clean >> popcornFlatpakInstallCustomLocation.log
popcornFlatpakInstallCustomLocation.log
```

[popcornFlatpakInstallCustomLocation.log](https://github.com/flatpak/flatpak/files/2634832/popcornFlatpakInstallCustomLocation.log)

Why is the application not getting installed in spite of the commands seemingly executing alright  ?

**Comment by TingPing** [comment]
Read the logs...

```
Installing in system:
sh.popcorntime.PopcornTime/x86_64/stable	sh.popcorntime.PopcornTime-origin	921f669070a0
  permissions: ipc, network, pulseaudio, x11
  file access: home:ro
  dbus access: org.freedesktop.Notifications
Is this ok [y/n]: n
```

Stop piping output to a file or pass `-y`.

**Comment by aiamuzz** [comment]
> Stop piping output to a file or pass -y

the output to file was only so i can post the log here ...

where to i pass -y argument to the command ...

`flatpak-builder --installation=myFlatpaks --install --install-deps-from=flathub popcorntime sh.popcorntime.PopcornTime.yml`

**Comment by mwleeds** [comment]
@aiamuzz just add the option along with the other options: `flatpak-builder -y --installation=myFlatpaks ...`

**Comment by aiamuzz** [comment]
well i tried putting the -y at various places in the command and had been getting this error ... hence i thought i'd ask ... but turns out even the place you recommend is getting the same error ... could it be a bug ?

```
flatpak-builder -y --installation=myFlatpaks --install --install-deps-from=flathub -y popcorntime sh.popcorntime.PopcornTime.yml
Dependency Sdk: org.freedesktop.Sdk 18.08
Skipping: org.freedesktop.Sdk/x86_64/18.08 is already installed
Segmentation fault

```

**Comment by TingPing** [comment]
What version of `flatpak-builder`

**Comment by aiamuzz** [comment]
> 0.10.10 is quite old so I would guess the installation option is probably fixed by now but you could test it.

Yeah i know ... seems my distro has gotten only so far ... I have downloaded & installed from debian packages and seems the error is already fixed ... And the app got installed alright !!!

thanks for looking !
