### ISSUE TITLE
Automatic gtk theme installation not working with GNOME 3.30 runtime

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#2368]
## Linux distribution and version
Debian Testing / Stable / Ubuntu 18.04
## Flatpak version
1.0.6 / 1.0.4 / 1.0.1
## Description of the problem
If one has a non-Adwaita theme selected this is automatically installed (org.gtk.Gtk3theme.themename) for the user. But this doesn't work when trying to install an app that uses the GNOME 3.30 runtime as the first app (if you try to install a different runtime then the theme is installed).
## Steps to reproduce
1) Install flatpak
2) Change your theme to Arc (or something other than Adwaita)
3) Install a flatpak app which uses the GNOME 3.30 runtime
4) Notice that `org.gtk.Gtk3theme.Arc` is not automatically installed
5) Now manually install `org.gnome.Platform//3.28` and notice that the theme is installed

Is this due to the move to freedesktop 18.08.

**Comment by ahayzen** [comment]
Reported these in the upstream runtimes

 - https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/105
 - https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/497

**Comment by TingPing** [comment]
I'll just close here and let it be handled there.
