### ISSUE TITLE
Issues with the new search-install

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2372]
I noticed two issues that I consider bugs:

- I get asked to confirm that I want to install org.gnome.meld from flathub even if it is the only choice and those are the exact arguments I specified. It should just go ahead in the case of an exact match
- I see org.gnome.Builder-origin offered as a remote to install org.gnome.meld from. I don't think that should happen

**Comment by mwleeds** [comment]
> I get asked to confirm that I want to install org.gnome.meld from flathub even if it is the only choice and those are the exact arguments I specified. It should just go ahead in the case of an exact match

That's not the behavior I'm seeing:
```
$ flatpak install flathub org.gnome.meld
Required runtime for org.gnome.meld/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.30) found in remote flathub
Do you want to install it? [Y/n]: 
Installing in system:
org.gnome.Platform/x86_64/3.30        flathub 229b78cd8725
org.gnome.Platform.Locale/x86_64/3.30 flathub df217e26af45
org.gnome.meld/x86_64/stable          flathub 8db2ba555703
  permissions: ipc, wayland, x11
  file access: host, xdg-run/dconf, ~/.config/dconf:ro
  dbus access: ca.desrt.dconf
org.gnome.meld.Locale/x86_64/stable   flathub 82f4f74f542e
Updating in system:
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08  flathub cbf3d3cf9782
org.freedesktop.Platform.html5-codecs/x86_64/18.08 flathub 1f2e4a4769ab
Is this ok [Y/n]: n
```

> I see org.gnome.Builder-origin offered as a remote to install org.gnome.meld from. I don't think that should happen

Agreed, see https://github.com/flatpak/flatpak/pull/2376

**Comment by matthiasclasen** [comment]
I think the first thing was operator error - I probably just overlooked that flathub was missing from my commandline
