### ISSUE TITLE
[Question] Desktop file not exported. What am I doing wrong?

### ISSUE THREAD

**Issue by Bleuzen** [flatpak/flatpak#2378]
## Linux distribution and version
Manjaro  (newest updates from stable branch)
## Flatpak version
1.1.0
## Description of the problem
I'm trying to package a Qt app. Build works now, but there is no desktop file when installed. I can't start it from system application menu.
## Steps to reproduce
This is what I got so far:
https://gist.github.com/Bleuzen/c4ebe303761167a1b6377272af70d981
Build it and try to launch it as all other applications from menu.

**Comment by TingPing** [comment]
Have you tried restarting your session?

You can see the exported files in `/var/lib/flatpak/exports` or `~/.local/share/flatpak/exports`.

**Comment by Bleuzen** [comment]
Seems it was a bug of KDE Plasma. I restarted it and it works. Thank you.
