### ISSUE TITLE
lgetxattr: Permission denied remote-ls fedora flatpaks

### ISSUE THREAD

**Issue by Zlopez** [flatpak/flatpak#2388]
## Linux distribution and version
Fedora 29 Silverblue x86_64 
Version: 29.20181119.0 (2018-11-19T00:52:11Z)
## Flatpak version
flatpak-1.0.6-1.fc29.x86_64
## Description of the problem
I added new fedora flatpak repository, but when I want to do remote-ls I get:
```
error: lgetxattr: Permission denied
```
Maybe this is caused by using OCI format.

## Steps to reproduce
1. flatpak remote-add fedora oci+https://registry.fedoraproject.org
2. flatpak remote-ls fedora

**Comment by matthiasclasen** [comment]
This is fixed in flatpak-1.0.6-3.f29, i believe
