### ISSUE TITLE
tests don't use the built system-helper

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2390]
After a very frustrating afternoon, I found that make check probably does not use the built system-helper, unless I add FLATPAK_SYSTEM_HELPER_ON_SESSION=1 to the test environment and remove the systemd service line from the dbus service file.

Is this intentional ?

In general, dealing with failures in our test suite is _extremely_ frustrating due to the amount of goo in the test harness and the amount of spew in test-suite.log.

**Comment by matthiasclasen** [comment]
Or the built session-helper, for that matter

**Comment by matthiasclasen** [comment]
I also notice that libtest.sh sets up the servicedir with a custom dbus config, but testlibrary.c does not get the benefit of that, and thus potentially uses different session- and system- helpers.

**Comment by alexlarsson** [comment]
Ah, I wondered what you meant by this, as libtest.sh definately sets this up, as i've found issues this way.- But yes, we're not doing that in the library test.

**Comment by alexlarsson** [comment]
@matthiasclasen It should use it. It starts a custom session bus which points to a custom service directory where the custom generated .service files have Exec= lines that point into $builddir. Does this not work for you?

**Comment by matthiasclasen** [comment]
but the service files also have systemd stuff in it, so my suspicion is that the dbus daemon just defers to systemd which launches the installed versions

**Comment by matthiasclasen** [comment]
also, for the system helper, we won't even look for it on that bus unless that env var is set. and it isn't

**Comment by alexlarsson** [comment]
@matthiasclasen it should be set:
```
$ git grep ON_SESSION
common/flatpak-dir.c:      const char *on_session = g_getenv ("FLATPAK_SYSTEM_HELPER_ON_SESSION");
tests/libtest.sh:export FLATPAK_SYSTEM_HELPER_ON_SESSION=1
```
Is this also broken?

**Comment by alexlarsson** [comment]
But yeah, the systemd stuff needs to go from the test .service files.

**Comment by matthiasclasen** [comment]
oh, libtest.sh sets it. I was looking for it in TESTS_ENVIRONMENT

**Comment by alexlarsson** [comment]
It needs to be set when running the installed tests too

**Comment by alexlarsson** [comment]
Actually, we don't pass --systemd-activation to out dbus-daemon, so the systemd thing shouldn't affect anything.

**Comment by alexlarsson** [comment]
I think we have to break out the dbus setup from libtest.sh and call that from testlibrary.c

**Comment by alexlarsson** [comment]
I definately get these during make check:
```
alex     2464038  6.0  0.0 444500 24052 ?        Sl   14:49   0:00 /vcs/gnome/flatpak/flatpak-system-helper --session --no-idle-exit
alex     2464459  1.0  0.0 370820 11112 ?        Sl   14:49   0:00 /vcs/gnome/flatpak/flatpak-session-helper
```
Not during testlibrary though...

**Comment by alexlarsson** [comment]
https://github.com/flatpak/flatpak/pull/2397
