### ISSUE TITLE
Security: Flatpaks can overwrite native apps – "phishing" problem

### ISSUE THREAD

**Issue by rugk** [flatpak/flatpak#2407]
## Problem

I first noticed this in https://bugzilla.redhat.com/show_bug.cgi?id=1657274.

So say I have a flatpak "new little game". This is sandboxed and has few permissions.

So I e.g. install "new little game" flatpak or so, and I then cannot find it, I maybe end up saying "okay, that failed".

### What really happened

The flatpak has the same ID as another native app and actually replaces that one. It may e.g. replace your file manager or your password manager. So if it is malicious, it can trojan-like replace another app than what you think it does.

This way, e.g. for password managers, it can get the password the user enters.

### Reasoning

You may say, the user installed it and it's their fault.
However:
1. The app could act really "phishing-like" and make the user believe it is an innocent game app or so (AFAIK it can arbitrarily set the app name, screenshots, icon or so).
2. At least in GNOME Software, I do not see the app ID or that it overrides existing software.
3. On the console, it looks like this (`master` is new):
  ```
$ flatpak install --from https://webkitgtk.org/epiphany-tech-preview                               
Installing in system:
org.gnome.Epiphany/x86_64/master        org.gnome.Epiphany-origin 2dc014a697f1
  permissions: ipc, network, pulseaudio, wayland, x11, dri
  file access: xdg-download, xdg-run/dconf, ~/.config/dconf:ro
  dbus access: ca.desrt.dconf, org.freedesktop.Notifications, org.freedesktop.secrets
  system dbus access: org.freedesktop.GeoClue2
  tags: nightly
org.gnome.Epiphany.Locale/x86_64/master org.gnome.Epiphany-origin 035dce727a3b
Updating in system:
org.gnome.Platform/x86_64/master        gnome-nightly 5ffb8d60415e
org.gnome.Platform.Locale/x86_64/master gnome-nightly f5dd3a16f350
Is this ok [y/n]: 
   ```
   As a user myself, I do not know what explains to me that anything is overwritten/updated here?
   Possibly the `org.gnome.Platform` update, but that is obviously only the runtime and may also not need an update if properly crafted.
4. The user thinks flatpaks are isolated. So it is a reasonable assumption, that they install software that they would not run as "native" apps or other dubious stuff. Especially if it has not so much permissions (as it supposedly has). As such, if that overwrites system apps, this is a big security issue.

## Potential solution

Warn the user if the software that is going to be installed is overwriting other software or flatpaks.
As updates should not made manually anyway, this case should never happen when you use flatpaks as they are supposed to be in your day-to-day usage.

**Comment by kirbyfan64** [comment]
It doesn't overwrite system apps, it's just that most DEs will only show one of them.

**Comment by TingPing** [comment]
Nothing can be done about this from Flatpak. If an application uses a specific ID for everything then it will be higher priority than the same ID higher up.

Some applications now have multiple IDs, one for a test version, one for a normal version. But that happens at the application level and will be fairly uncommon since it takes a bit of work.

There is certainly no security risk in any of this. You as a user choose to install an application. Obviously you expect the application to be there.

**Comment by matthiasclasen** [comment]
After 

> flatpak install flathub $appid

this command will run what you installed

> flatpak run $appid

So the 'i cannot find it' part is hard to swallow. I don't think there is anything for us to fix here. You have to pay attention when installing software.

**Comment by rugk** [comment]
So it's rather about desktop managers, mhh? Okay, so considering the command line case to be advanced stuff (users then probably start via `flatpak run $appid` as you said), this is unlikely when you install it from GNOME Software or so… :thinking:

**Comment by rugk** [comment]
So reported at https://gitlab.gnome.org/GNOME/gnome-software/issues/549 to account rather for the usability problems this has.
