### ISSUE TITLE
X Window System error 'BadAccess' running under XFCE

### ISSUE THREAD

**Issue by jhasse** [flatpak/flatpak#2420]
## Linux distribution and version
XFCE on Manjaro / Arch Linux, latest version

## Flatpak version
1.0.6

## Description of the problem
Running wxFormBuilder (which uses Gtk+ 3 from the Freedesktop 18.08 SDK) results in the following error message and immediate exit before any window shows up:

```
$ flatpak run org.wxformbuilder.wxFormBuilder/x86_64/master
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

(wxformbuilder:3): Gdk-ERROR **: The program 'wxformbuilder' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
(Details: serial 454 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the GDK_SYNCHRONIZE environment
variable to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
```

## Steps to reproduce
Install XFCE on Arch Linux, install [wxformbuilder.flatpak](https://github.com/wxFormBuilder/wxFormBuilder/releases), run it two times (first time works sometimes).

See https://github.com/wxFormBuilder/wxFormBuilder/issues/471

**Comment by alexlarsson** [comment]
Can you try flatpak run --share=ipc org.wxformbuilder.wxFormBuilder

**Comment by jhasse** [comment]
According to https://github.com/wxFormBuilder/wxFormBuilder/issues/471#issuecomment-451754418 it works with that option (I don't have XFCE set-up myself anymore).
