### ISSUE TITLE
/var/home is created instead of /home inside Flatpaks on Fedora Silverblue

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak#2421]
## Linux distribution and version
Fedora Silverblue 29

## Flatpak version
flatpak-1.0.6-3.fc29.x86_64

## Description of the problem
When running Flatpaks on Fedora Silverblue that has `$HOME` as a symlink to `/var/home`, home directory is also created as a symlink to `/var/home` inside the Flatpak. This causes issues for some applications, for example [Blue Jeans](https://github.com/flathub/com.bluejeans.BlueJeans/issues/2#issuecomment-446584934). Is there any reason why Flatpak behaves this way on Silverblue?

## Steps to reproduce
1. Use Fedora Silverblue.
1. $ `flatpak run --command=sh bar.foo.App`
2. $ `stat /home`
  File: /home -> var/home
  Size: 8         	Blocks: 0          IO Block: 4096   symbolic link

**Comment by alexlarsson** [comment]
I'm not sure what exactly is the problem with this. Flatpak mirrors the host setup of the filesystem, because otherwise things like symlinks can be confused, etc. And the silverblue setup is that /home is a symlink. There is not much flatpak can do about this.
