### ISSUE TITLE
expand xdg-data at run time

### ISSUE THREAD

**Issue by bam80** [flatpak/flatpak#2424]
When --filesystem=xdg-data option is used when building container, host's $XDG_DATA_HOME directory gets shared when the flatpak runs.
But, seems there is no possibility to "expand" that `xdg-data` path from within the sandbox - inside it, XDG_DATA_HOME variable gets flatpak-specific value not related with real `xdg-data` path.

That shared paths can be crucial for tuning programs environment (which flatpak overrides unconditionally), so it seems logical if Flatpak provides a way to get them at run time.

#2413

**Comment by bam80** [comment]
Sample solution: overridden variables gets saved by flatpak in the other variables with prefixed/postfixed names, e.g.: HOST_XDG_DATA_HOME

**Comment by matthiasclasen** [comment]
Seems like a reasonable plan: pass HOST_XDG_{DATA,CONFIG,CACHE}_HOME into the sandbox if the original variables are set on the host side.

**Comment by bam80** [comment]
@matthiasclasen Thank you very much

**Comment by bam80** [comment]
@matthiasclasen I see the problem here, sorry, didn't catch it beforehand:

- the app only needs these host's value of the variables if they are present in the shared paths
- in the other hand, the app must not use them if the paths are not shared

So, maybe change the condition for setting the HOST_* variables:
- only set it if corresponding to the variable "xdg-" value ("xdg-data", ect.) is present in any `--filesystem` options arguments (one of the shared paths)
- use expanded xdg-data value for the setting (that is, use $HOME/.local/share for default)

That way we could use following in apps wrapper scripts for overriding XDG variables only when it needed:
```
${XDG_DATA_HOME:+$HOST_XDG_DATA_HOME}

**Comment by bam80** [comment]
@matthiasclasen I understand the algorithm suggested above https://github.com/flatpak/flatpak/issues/2424#issuecomment-447811771 would require more code.
Meanwhile, could we keep this issue open so it doesn't lost?

**Comment by bam80** [comment]
Apparently, all the hassle about this issue was due lack of documentation:
[document xdg-data/... mount points](https://github.com/flatpak/flatpak-docs/issues/162)
