### ISSUE TITLE
flatpak-builder should handle symbolic icons in rename-icon

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#243]
flatpak-builder should handle symbolic icons in rename-icon. My json manifest includes the following:

`"rename-icon": "gnome-chess"`

When building the app, I see:

```
Exporting share/icons/hicolor/16x16/apps/org.gnome.chess.png
Not exporting share/icons/hicolor/scalable/apps/gnome-chess-symbolic.svg, wrong prefix
Exporting share/icons/hicolor/32x32/apps/org.gnome.chess.png
```

This causes the color icon to be improperly used for the app menu.

**Comment by alexlarsson** [comment]
Fixed in master
