### ISSUE TITLE
Multiple polkit prompts when removing a flatpak

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#244]
When running the command `flatpak uninstall org.gnome.Epiphany` I get two polkit prompts: one to uninstall org.gnome.Epiphany, and another to uninstall org.gnome.Epiphany.Locale. I should only be prompted once for each call to `flatpak uninstall`.

**Comment by alexlarsson** [comment]
Uninstall is auth_admin_keep though, so it should store the auth. I wonder why that happened.

**Comment by matthiasclasen** [comment]
I think this has been addressed by recent polkit changes
