### ISSUE TITLE
flatpak theming

### ISSUE THREAD

**Issue by dirkdavidis** [flatpak/flatpak#2457]
## Linux distribution and version
Fedora 29
## Flatpak version
1.0.6
## Description of the problem
it is not an real issue, i want to ask how to build an application gtk theme in flathub. is it like normal app building procedure?

**Comment by kirbyfan64** [comment]
You can look at how [some of the other themes do it](https://github.com/flathub/org.gtk.Gtk3theme.Adapta-Nokto).

**Comment by tad1073** [comment]
The end user shouldn't have to deal with themeing apps from flathub or snap store. You guys need to get your act together and figure out client side environment and themes and that is one of the reasons I do not use flathub or snap store the other is that I don't trust the developers and the questionable dependencies. I avoid pulling from AUR as well for those same reasons, well, not the themeing issue.
