### ISSUE TITLE
Issue with oci install

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2470]
I've installed eog and the fedora runtime in my user installation. Running flatpak repair right after installing gives a pretty rough picture for the runtime. Every single file appears invalid. flatpak will go ahead and remove them all, then reinstall, and get the same result :(

> $ ./flatpak repair --user --dry-run
> Working on the user installation at /home/mclasen/.local/share/flatpak
> Verifying fedora-testing:runtime/org.fedoraproject.Platform/x86_64/f29…
> Object invalid: 9880aff2821430f579e4696a6d029c8aa098856aa29c195cdb83ba38f6616ef8.file
> Object invalid: 9d3f386eae02cfa44ae8fe22f01b86ffe6b255b4857288dee48d502c1e7fd966.file
> Object invalid: 811a375c1d8e8742f5d02246af00136f2192905d06ae1dd7de662f16b1ddebea.file
> Object invalid: 9396116ed486f52943960a591fe9375fb6d79328540eafaf3ae2f14cb7cc962b.file
> Object invalid: a8089de4cb3f66937351a23e0037f85f15f1c0e2a0595949a22b7c8670ef0536.file
> Object invalid: d79a57e24c5f3f80266595073a716412c85f613f53f4ec2bdeb05bff2214a6cd.file
> Object invalid: dc9bec836fa7af5be2b3bdbfce31749146ac2308636d053391972aedbcd0c8f5.file
> Object invalid: 2099bfa5bf73d3e344c1d9042698b424c3e8a8804537fdfe9b3f6a975f619339.file
> Object invalid: 6a8570900fa50b8302b7132e5473d2d49995b837071df55002686d1f86392874.file
> Object invalid: 6c7548e6632003ed674a9a29a8cb4386dddd8a8abf3a5ae1412343f2338e993b.file
> Object invalid: 26dab41c907bddb797a026dffc1d48f356ba3a0a8caf5d3fe78dad72eecab98a.file
> Object invalid: 9f5fcd7ad1b95c7b33f63ee2c89bc69f40bd46cf254a80b6da18723a41c15b6f.file
> Object invalid: cab94991d5c9dc36eaf9f2ab590f0e7990ed8e5caed79ebd02dc2b66e474afab.file
> Object invalid: 6607b949ebd858393a9bf73cd663e99ff194dd45952f9b068afe4e98cbed5a10.file
> Object invalid: 60345a2124b52618fcf4167d87a1db12a8d02177f915a23412c013516c01466c.file
> Object invalid: 315aeb0184dc70c22318e9f4875fc64262a2fbd82d7bb15183db43543b63a5e4.file
> Object invalid: af68264187211922bf58d7a45e338b7925f7f491dcd95682559f6fcf821f9f98.file
> Object invalid: 88d11b6b30c3059d3c4236c25a7765f7dba95da0e84841240ec1f0aa506f08c1.file
> Object invalid: 9619480c63f51572ed659f4cd32da2d1211e9c79963bbfb2c9a9a09468e009ee.file
> Object invalid: 8b0af60947f14bf052f09be907a498d87e7491d5d73c52722a5487400fc8844f.file
> Object invalid: 4cf0a0eb1c6af74b6bd1196bf420f64d47eaf1563de319e151e6d4a4a15a0f16.file
> Object invalid: 325ce462d90728db3708d43a08c722e4109422dfedb9f1552e2e2aba16dc6dfe.file
> Object invalid: 16451e3acfbf46c0aff19caa9310837c8735f4839cc5944cfe12470a1f633f32.file
> Object invalid: 4841327cbeb397f21a28cb562cae5737e65bac160f6627d337069ccf7bd1ad16.file
> Object invalid: 366b2670042a4c093631b89ead3c5bb7d9b10da6c3879a19b3dbe8a81bfb912c.file
...

**Comment by matthiasclasen** [comment]
Still the case

**Comment by alexlarsson** [comment]
I wonder if this is caused by the app not having canonical (bare-user-only compatible) permissions. We should probably canonicalize these when generating the oci commits.

**Comment by alexlarsson** [comment]
Researched this and filed: https://pagure.io/flatpak-module-tools/issue/2
