### ISSUE TITLE
Why the shortcuts of installed applications from flatpak are removed from cairo dock?

### ISSUE THREAD

**Issue by azerphoenix** [flatpak/flatpak#2474]
## Linux distribution and version
Linux Mint 19.1 (also LMDE 3)

## Flatpak version
flatpak 1.0.1

## Description of the problem
Why the shortcuts of installed applications from flatpak are removed from cairo dock?  Instead of the each application icon, a question mark is displayed, and when you log out or restart, they are deleted from Cairo Dock (version 3.4.1)

## Steps to reproduce
1) install cairo dock
2) install flatpak & some applications.
3) drag flatpak apps into Cairo dock.
4) restart OS

**Comment by kirbyfan64** [comment]
Sounds like a bug in Cairo dock TBH.

**Comment by matthiasclasen** [comment]
Probably XDG_DATA_DIRS not getting set properly on restart.

**Comment by azerphoenix** [comment]
> Sounds like a bug in Cairo dock TBH.

Other installed applications are displayed correctly, except for the flatpak. May be this is the bug of Cairo...

**Comment by matthiasclasen** [comment]
what does `echo $XDG_DATA_DIRS` print in a terminal, in this situation ?

**Comment by azerphoenix** [comment]
> what does `echo $XDG_DATA_DIRS` print in a terminal, in this situation ?

/usr/share/cinnamon:/usr/share/gnome:/home/phoenix/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop

**Comment by matthiasclasen** [comment]
that looks correct.

**Comment by azerphoenix** [comment]
> that looks correct.

And what did you think about it? Is that Cairo bug? Do I need write to Cairo developers? 
Thanks in advance)

**Comment by matthiasclasen** [comment]
I don't know enough to diagnose that from here. But cairo has nothing to do with the cairo-dock application.

**Comment by azerphoenix** [comment]
> I don't know enough to diagnose that from here. But cairo has nothing to do with the cairo-dock application.
> You said you drag the apps onto the cairo dock - where do you drag them from ?

First I create shortcut on Desktop, then drag this shortcut to Cairo Dock area. Other shortcuts works, only flatpak apps not displaying after restart.
Also I tried another way - created shortcut from Cairo Dock and added command to open. The same result.

Here is gif:
https://drive.google.com/file/d/1Ri6Bv_GtD2x1O-pip6UmPaowoGzlanoP/view?usp=sharing

**Comment by matthiasclasen** [comment]
Other consumers like gnome-shell or nautilus have no problems with the desktop files that are exported by flatpak, so i would say this needs to be debugged in the cairo-dock side
