### ISSUE TITLE
Installing progress shows a duplicated table's header 

### ISSUE THREAD

**Issue by bilelmoussaoui** [flatpak/flatpak#2480]
## Linux distribution and version 
<pre>bilelmoussaoui@localhost <font color="#849900">~/Projects</font>&gt; <b>cat</b> <font color="#29A097">/etc/fedora-release</font> 
Fedora release 30 (Rawhide)
</pre>
## Flatpak version
<pre>bilelmoussaoui@localhost <font color="#849900">~/Projects</font>&gt; <b>dnf</b> <font color="#29A097">info</font> <font color="#29A097">flatpak</font>
Installed Packages
Name         : flatpak
Version      : 1.1.2
Release      : 1.fc30
Arch         : x86_64
Size         : 4.2 M
Source       : flatpak-1.1.2-1.fc30.src.rpm
Repo         : @System
From repo    : rawhide
Summary      : Application deployment framework for desktop apps
URL          : http://flatpak.org/
License      : LGPLv2+
Description  : flatpak is a system for building, distributing and running sandboxed desktop
             : applications on Linux. See https://wiki.gnome.org/Projects/SandboxedApps for
             : more information.

</pre>
## Description of the problem
Regression on with new cli progress bar. 
<pre>bilelmoussaoui@localhost <font color="#849900">~/Projects</font>&gt; <b>flatpak</b> <font color="#29A097">install</font> <font color="#29A097">org.freedesktop.Sdk//18.08</font>
Looking for matches…
Remotes found with refs similar to ‘org.freedesktop.Sdk//18.08’:

  1) ‘flathub’ (system)
  2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 1

<b>        ID                             Arch      Branch   Remote      Download</b>
<b>        ID                             Arch      Branch    Remote     Download</b>
 1. [✓] org.freedesktop.Sdk            x86_64    18.08     flathub    82.5 MB / 1.5 GB
 2. [✓] org.freedesktop.Sdk.Locale     x86_64    18.08     flathub    16.9 kB / 221.3 MB

Installation complete.
</pre>
As you can see, it shows twice the ID, Arch, Branch, Remote, Download.
## Steps to reproduce
I just tried to install something, it shows the thing twice if you need to install an app and it needs to install a runtime, or like in this case, a runtime needs to install the Locale/Debug.
Not sure if it's the exact way to reproduce it, it's the only time I have seen this. Will come back if I have a correct way of reproducing or a patch.

**Comment by matthiasclasen** [comment]
I think this is fixed by #2472
