### ISSUE TITLE
Should flatpak-spawn'ed processes inherit the caller's devel options?

### ISSUE THREAD

**Issue by kirbyfan64** [flatpak/flatpak#2493]
It'd be really nice if e.g. processes sandboxed via flatpak-spawn were debuggable *if the calling Flatpak were run with --devel*. This would make debugging sandboxed applications a lot easier, and I don't believe there are any major security issues (since the Flatpak itself was run with devel anyway). 

FWIW I looked briefly over the source, but I didn't really see a straightforward way of being able to access the calling context from within the spawn portal.

**Comment by matthiasclasen** [comment]
The instance info for the caller is readily available  in handle_spawn(), the app_info is the same keyfile that is available in the sandbox as /.flatpak-info. But it does not directly reflect the --devel flag. The closest you have is the fact that the sdk is  used as runtime.

**Comment by kirbyfan64** [comment]
@matthiasclasen Would it be approved if I added a key in the keyfile if devel mode is enabled? e.g. `Instance.devel` would be true.

**Comment by matthiasclasen** [comment]
Thats a question for @alexlarsson
