### ISSUE TITLE
Allow app to install additonal translations

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak#2494]
Some apps provide the option to change the language from the GUI. For apps that bundle all translations (like Shotcut) this works, but for apps with a separate .locale extension (e.g. KDE apps like Kdenlive or Krita) this does not work. There needs to be a mechanism for installing additional translations (including the runtime), triggered from the app itself.

**Comment by eszlari** [comment]
I know, one could use `separate-locales: false` for individual apps, but the runtime would need to built with it too, and at the end, it would mean, getting ride of .locale extensions entirely.

**Comment by matthiasclasen** [comment]
I don't think that is something we need to support. There's well-established mechanisms for switching locales session-wide. We support those, and applications should use them, not invent their own.

**Comment by matthiasclasen** [comment]
That being said, 

`flatpak config --set languages all`

will make flatpak install all languages.
