### ISSUE TITLE
Flatpak exports added to search path in ways that fail if duplicated

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#25]
A test I like to apply to designs for extensibility is: would this still work if multiple parties did it? At the moment, the way Flatpak adds its exports to the search path seems to fail that test.

For example, if you have something like

```
XDG_DATA_DIRS=/opt/data:/usr/local/share:/usr/share
```

on entry to `flatpak.sh`, then Flatpak won't alter the search path to add `$HOME/.local/share/flatpak/exports/share` and/or `/var/lib/flatpak/exports/share`. I think I would expect it to prepend them to `XDG_DATA_DIRS`, which in my example would result in something like:

```
/home/me/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/opt/data:/usr/local/share:/usr/share
```

Pseudo-patch for discussion: something like

``` diff
-XDG_DATA_DIRS="${XDG_DATA_DIRS:-$HOME/.local/share/flatpak/exports/share:/var/flatpak/exports/share/:/usr/local/share/:/usr/share/}"
+XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/flatpak/exports/share:${XDG_DATA_DIRS:-usr/local/share:/usr/share}"
```

Similarly, if I'm understanding it correctly, `/usr/share/gdm/env.d/flatpak.env` unconditionally overwrites `XDG_DATA_DIRS`, resulting in last-write-wins behaviour. This probably cannot be fixed without an upstream feature request in `gdm` to add a mechanism for "prepend this string to this colon-separated search path [if not already present]" (analogous to `set foo^=bar` in `vim`), or failing that, either setting XDG_DATA_DIRS=/usr/local/share:/usr/share in advance or supporting shell `${foo:-bar}` syntax.

---

Relatedly, both flatpak.sh and flatpak.env hard-code `$HOME/.local/share` rather than `${XDG_DATA_HOME:-"$HOME/.local/share"}`. I can see that fixing this is not necessarily 100% desirable though, because what happens if the user changes XDG_DATA_HOME at a point in the sequence that comes after Flatpak?

**Comment by alexlarsson** [comment]
I agree that these methods are less than ideal, and we should try to do this better.
One issue that lead to the gdm env.d thing is that we have to set up XDG_DATA_DIRS really early, to make sure that the session bus picks this up. Otherwise exporting dbus service files doesn't work.

I think your approach for the flatpak.sh entry is more correct than what we have now. It would be even better if it checked if flatpak was already in the list (from say gdm) and didn't add it then. However, since that solution doesn't *really* work I'm not sure its worth making it better.

At some point I was trying to use a systemd template for user@.service that overrides the Environment to make this setup happen early in a distro-independent way. However, this failed because systemd expanded things wrongly. See https://github.com/alexlarsson/xdg-app/issues/147#issuecomment-215654989 for details.

**Comment by smcv** [comment]
> One issue that lead to the gdm env.d thing is that we have to set up XDG_DATA_DIRS really early, to make sure that the session bus picks this up.

Yeah, this is quite awkward. I'll keep thinking about it and see whether I can come up with a better solution... if the better solution involves code in dbus-daemon, that can happen.

If it wasn't so hard to hook into PAM in a distro-independent way, I'd say that was the right place to do environmental setup, but in practice PAM is really awkward.

What's the requirement here? Are there a finite number of things that can be exported, e.g. desktop files and D-Bus services (so changing their consumers could be part of a solution), or do you intend it to grow over time?

**Comment by alexlarsson** [comment]
I can see it being able to grow over time. For instance, maybe you can install a gnome-shell plugin or some other kind of extensions. However, as long as we change XDG_DATA_DIRS we get all that for free, its not like we need to set multiple env vars. The only problem is that we have to do it early enough to affect the entire sessions, including the early stuff like dbus-daemon and systemd --user.

As for changing the consumers. I dunno, XDG_DATA_DIRS and desktop files is a pretty old, and widely used standard. Can we really realistically find all users in the distro and make them use something else? And what would that else even be, if its not an env var? Symlink farm?

**Comment by matthiasclasen** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=767933

**Comment by matthiasclasen** [comment]
I believe htis is fixed in master
