### ISSUE TITLE
Happily install an app without the relevant platform

### ISSUE THREAD

**Issue by ocrete** [flatpak/flatpak#250]
This is on F24

1. Clean system with no flatpak
2. flatpak remote-add --gpg-import=nightly.gpg gnome-nightly-apps https://sdk.gnome.org/nightly/repo-apps/
3. flatpak install gnome-nightly-apps   org.gnome.Documents
4. flatpak run org.gnome.Documents
Result: error: runtime/org.gnome.Platform/x86_64/master not installed

**Comment by matthiasclasen** [comment]
The necessary intelligence to automatically install runtimes and related runtimes lives in gnome-software. We could probably try to be a bit smarter in the commandline as well, optionally.

**Comment by ocrete** [comment]
The install command for an app could at least complain, because clearly it knows it's missing? Having it in the UI is a bit grr if one wanted to use flatpak for embedded, but I guess that's a later bridge to cross.

**Comment by fastrizwaan** [comment]
on fedora 24 workstation,

```
[rizvan@localhost ~]$ flatpak install gnome org.gnome.Platform 3.22

1 metadata, 0 content objects fetched; 313 B transferred in 3 seconds                                                                           
error: GDBus.Error:org.freedesktop.Flatpak.Error.AlreadyInstalled: runtime/org.gnome.Platform/x86_64/3.22 is already installed
[rizvan@localhost ~]$ flatpak run org.gnome.Games
error: runtime/org.gnome.Platform/x86_64/master not installed
[rizvan@localhost ~]$ flatpak run org.gnome.Nautilus 
error: runtime/org.gnome.Platform/x86_64/master not installed

```

but the same thing runs fine on fedora 25.

**Comment by matthiasclasen** [comment]
this is improved in 0.6.13. flatpak install will now ask if you want to install required runtimes.
