### ISSUE TITLE
consider mentioning libappstream <> libappstream-glib in release notes

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2549]
We recently saw a problem where discover would hang inside some libappstream-glib calls made by flatpak. It turns out that libappstream and libappstream-glib have plenty of symbol collisions, and discover is linking against libappstream. 

Kalev is trying to fix that with -Bsymbolic on the appstream side, but it might be good to mention the new dependency in the release notes anyway.

**Comment by matthiasclasen** [comment]
add_appdata_to_deploy_data also needs libappstream-glib apis. It could be moved out of process, but...

**Comment by smcv** [comment]
You're right, that's reachable from the public flatpak_installation_install().

**Comment by matthiasclasen** [comment]
cunning idea: shell out to `flatpak info ` to get the appstream data in add_appdata_to_deploy_data

**Comment by alexlarsson** [comment]
Maybe we could use GMarkup to parse the xml, we're really just using libappstream-glib in trivial ways

**Comment by matthiasclasen** [comment]
See #2580
