### ISSUE TITLE
The new view form flatpak or flatpakbuilder by update or install show not good in Makefiles

### ISSUE THREAD

**Issue by winehub** [flatpak/flatpak#2552]
flatpak version 1.1.2
## Description of the problem
The new view by installation  or update [X] package ....

Inside of a Makefile ends up with with uggly 
glyph ;1R;1R;17R;47R;56

## Steps to reproduce

Makefile

all: build-all

build-all:
     flatpak update/install or flatpak-builder
     flatpak-builder build xxxxxx --force-clean --user --install

**Comment by winehub** [comment]
or is there config file to get the old solution back?

**Comment by matthiasclasen** [comment]
You can set FLATPAK_FANCY_OUTPUT=0 to get a bit more plain output.

All list-producing commands have a --columns option, so you can choose what you want to see.

**Comment by matthiasclasen** [comment]
Also see #2475

**Comment by matthiasclasen** [comment]
1.2 will have a --noninteractive option.
