### ISSUE TITLE
Implement aria2c or the likes to resume partial downloads

### ISSUE THREAD

**Issue by lasers** [flatpak/flatpak#2557]
**Linux distribution and version**: Arch
**Flatpak version:** Flatpak 1.1.2
**Description of the problem:**
* Implement `aria2c` or the likes to resume partial downloads. Similar to #2325.

```
$ flatpak install flathub org.freedesktop.Platform//18.08 org.freedesktop.Sdk//18.08
Looking for matches…
Skipping: org.freedesktop.Platform/x86_64/18.08 is already installed

ID                          Arch    Branch  Change  Remote      Download
 1. [✗] org.freedesktop.Sdk x86_64  18.08   i       flathub     1.2 GB / 1.5 GB

Error: While pulling runtime/org.freedesktop.Sdk/x86_64/18.08 from remote flathub:
    Writing content object: min-free-space-size 500MB would be exceeded, at least
    374.9 MB requested
error: Failed to install org.freedesktop.Sdk: While pulling
    runtime/org.freedesktop.Sdk/x86_64/18.08 from remote flathub: Writing content
    object: min-free-space-size 500MB would be exceeded, at least 374.9 MB requested
```
```
$ flatpak install flathub org.freedesktop.Platform//18.08 org.freedesktop.Sdk//18.08
Looking for matches…
Skipping: org.freedesktop.Platform/x86_64/18.08 is already installed

ID                          Arch    Branch  Change  Remote      Download
 1. [—] org.freedesktop.Sdk x86_64  18.08   i       flathub     19.9 MB / 1.5 GB
```
I trimmed the output to keep it simple. With this added, I would have resume downloading the remaining 300 MB and move on to other pending applications/runtimes instead of having to download the full 1.5 GB SDK again.

It's just one SDK, but with several applications, SDKs, runtimes, packages, etc... Users may be able to reduce their download bandwidth some more. Also, it may be possible for `flatpak` to take advantage of other `aria2c` features like sharing.

**Comment by kirbyfan64** [comment]
FWIW I think this might be more related to how Flatpak uses OSTree?

**Comment by matthiasclasen** [comment]
I don't know what aria2c is, but flatpak is reusing partial downloads when they get interrupted.

**Comment by lasers** [comment]
@matthiasclasen Maybe you're right. I had 8.3 GB in `/var/cache/pacman/pkg`. After moving them to make room for SDK and many other things, I tried again and got this:
```
$ flatpak install flathub org.freedesktop.Platform//18.08 org.freedesktop.Sdk//18.08
Looking for matches…
Skipping: org.freedesktop.Platform/x86_64/18.08 is already installed

ID                                              Arch    Branch  Change  Remote      Download
 1. [✓] org.freedesktop.Sdk                     x86_64  18.08   i       flathub     304.4 MB / 1.5 GB
 2. [✓] org.freedesktop.Sdk.Locale              x86_64  18.08   i       flathub     16.9 kB / 221.4 MB
 3. [✓] org.freedesktop.Platform.html5-codecs   x86_64  18.08   u       flathub     2.5 MB / 2.8 MB

Changes complete.
```
`304.4 MB` is practically same as my 300 MB... Fixing #2325 will surely improve the process. Cheers.
