### ISSUE TITLE
flatpak update --commit can fail but claim to succeed

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2564]
In the case that the commit you want to deploy already has a deploy directory that's not the active one, a deploy can fail but claim to succeed:
```
0 ✓ mwleeds@pop-os ~/.local/share/flatpak/app/org.signal.Signal/current (2 keys)
↳ ls -l
total 12
drwxr-xr-x 4 mwleeds mwleeds 4096 Jan 11 07:36 52833ac7c1b713282f0d71b9013b1ec332cab59c97e294f8229f663e0d9604d8
drwxr-xr-x 4 root    root    4096 Jan 11 07:33 a3e15e2f73401aea949f176fe97693995b264cc91d346c693ed05b5b7b3d6e79
lrwxrwxrwx 1 mwleeds mwleeds   64 Jan 11 07:36 active -> 52833ac7c1b713282f0d71b9013b1ec332cab59c97e294f8229f663e0d9604d8
0 ✓ mwleeds@pop-os ~/.local/share/flatpak/app/org.signal.Signal/current (2 keys)
↳ sudo flatpak update --commit=a3e15e2f73401aea949f176fe97693995b264cc91d346c693ed05b5b7b3d6e79 org.signal.Signal
[sudo] password for mwleeds: 
Looking for updates…


        ID                         Arch            Branch         Remote          Download
 1. [✓] org.signal.Signal          x86_64          stable         flathub         1.0 kB / 112.7 MB

Updates complete.
0 ✓ mwleeds@pop-os ~/.local/share/flatpak/app/org.signal.Signal/current (2 keys)
↳ ls -l
total 12
drwxr-xr-x 4 mwleeds mwleeds 4096 Jan 11 07:36 52833ac7c1b713282f0d71b9013b1ec332cab59c97e294f8229f663e0d9604d8
drwxr-xr-x 4 root    root    4096 Jan 11 07:33 a3e15e2f73401aea949f176fe97693995b264cc91d346c693ed05b5b7b3d6e79
lrwxrwxrwx 1 mwleeds mwleeds   64 Jan 11 07:36 active -> 52833ac7c1b713282f0d71b9013b1ec332cab59c97e294f8229f663e0d9604d8
```

This is because `flatpak_dir_deploy` returns `FLATPAK_ERROR_ALREADY_INSTALLED` if the deploy directory for a commit exists, and `flatpak_transaction_real_run` interprets that error message as success. Perhaps it would make more sense for `flatpak_dir_deploy` to call `flatpak_dir_set_active` in the case that a deploy already exists.

**Comment by matthiasclasen** [comment]
Do we know that the contents of that directory are correct ?

**Comment by mwleeds** [comment]
I suppose you would want to check that somehow. In this case I believe they are because it got into that state via #2565

**Comment by mwleeds** [comment]
I suppose to some extent this is user error because you only need root for downgrades in the system installation, not the user one. But it still seems like buggy behavior.

**Comment by mwleeds** [comment]
Once #2575 is merged I don't know of a way we could get in this state (of trying to deploy a commit that already has a deploy directory which is not the active one). So perhaps we don't have to worry about this.
