### ISSUE TITLE
Running flatpak as root can leave files with wrong permissions

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2565]
In order for `flatpak update --commit` to succeed on the system installation it has to be run as root. If the user (erroneously) runs it as root when operating on the user installation, it leaves directories owned by root that are difficult for later non-root operations to clean up:
```
0 ✓ mwleeds@pop-os ~/.local/share/flatpak/repo (2 keys)
↳ sudo flatpak update --commit=a3e15e2f73401aea949f176fe97693995b264cc91d346c693ed05b5b7b3d6e79 org.signal.Signal
Looking for updates…


        ID                         Arch            Branch         Remote          Download
 1. [✓] org.signal.Signal          x86_64          stable         flathub         98.3 MB / 112.7 MB

Updates complete.
0 ✓ mwleeds@pop-os ~/.local/share/flatpak/repo (2 keys)
↳ ls -l ../app/org.signal.Signal/current/
total 8
drwxr-xr-x 4 root root 4096 Jan 11 08:24 a3e15e2f73401aea949f176fe97693995b264cc91d346c693ed05b5b7b3d6e79
lrwxrwxrwx 1 root root   64 Jan 11 08:24 active -> a3e15e2f73401aea949f176fe97693995b264cc91d346c693ed05b5b7b3d6e79
0 ✓ mwleeds@pop-os ~/.local/share/flatpak/repo (2 keys)
↳ flatpak update org.signal.Signal
Looking for updates…


        ID                         Arch            Branch         Remote          Download
 1. [✗] org.signal.Signal          x86_64          stable         flathub         93.9 MB / 112.7 MB

Error: Permission denied
Updates complete.
error: There were one or more errors
1 ✗ mwleeds@pop-os ~/.local/share/flatpak/repo (2 keys)
↳ ls -l ../app/org.signal.Signal/current/
total 12
drwxr-xr-x 4 mwleeds mwleeds 4096 Jan 11 08:25 52833ac7c1b713282f0d71b9013b1ec332cab59c97e294f8229f663e0d9604d8
drwxr-xr-x 4 root    root    4096 Jan 11 08:24 a3e15e2f73401aea949f176fe97693995b264cc91d346c693ed05b5b7b3d6e79
lrwxrwxrwx 1 mwleeds mwleeds   64 Jan 11 08:25 active -> 52833ac7c1b713282f0d71b9013b1ec332cab59c97e294f8229f663e0d9604d8
```

**Comment by matthiasclasen** [comment]
Why does `flatpak update --commit` need root  anyway ? Why not use the system helper ?

**Comment by mwleeds** [comment]
I suppose to some extent this is user error because you only need root for downgrades in the system installation, not the user one. But it still seems like buggy behavior.

**Comment by mwleeds** [comment]
> Why does `flatpak update --commit` need root anyway ? Why not use the system helper ?

Because downgrades are considered dangerous: https://github.com/flatpak/flatpak/blob/f39b5a2795e5b7fc0a0c9530aaf1b06670119ebd/common/flatpak-dir.c#L8377

**Comment by mwleeds** [comment]
I suppose that could be a good idea but you would surely only do that for the system installation, so the user could still (erroneously) use root on the user installation, so this issue would still exist.

**Comment by matthiasclasen** [comment]
It seems odd to me that we would require root for changing files that you have access to anyway

**Comment by mwleeds** [comment]
We don't. Root is not required to downgrade the user installation but it is for the system installation, where the files are all owned by root.

**Comment by matthiasclasen** [comment]
Maybe we should just have a warning for "It looks like  you're using flatpak under sudo" ?

**Comment by mwleeds** [comment]
Yeah, I'll see if I can come up with a patch
