### ISSUE TITLE
flatpak.sh uses a bashism

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2594]
The newly rewritten `flatpak.sh` uses a bashism (process substitution) which is causing gdm to fail to start, so I can't login without deleting `/etc/profile.d/flatpak.sh`. This is because on Endless (and Ubuntu) `/bin/sh` is dash not bash. Here's the relevant line from the journal:

`Jan 15 12:29:10 endless /etc/gdm3/Xsession[1608]: /etc/gdm3/Xsession: 12: /etc/profile.d/flatpak.sh: Syntax error: redirection unexpected`

Adding `#!/bin/bash` at the top does not seem to fix it and I'm not sure how to rewrite it in a shell-independent way

@matthiasclasen

**Comment by matthiasclasen** [comment]
yeah, I'm not sure either, which is why I didn't

**Comment by matthiasclasen** [comment]
Probably need to fix that for 1.2

**Comment by matthiasclasen** [comment]
https://unix.stackexchange.com/questions/310500/how-to-emulate-process-substitution-in-dash has some hints

**Comment by mwleeds** [comment]
> If we can detect dash, we can just exit early.

But then you wouldn't have $XDG_DATA_DIRS set on Ubuntu?

One solution would be to add a `flatpak --all-installations` option that includes the user installation location. Then the script could just use a pipe:
```
flatpak --all-installations |
while read -r install_path
```

**Comment by mwleeds** [comment]
> https://unix.stackexchange.com/questions/310500/how-to-emulate-process-substitution-in-dash has some hints

It'd be a shame if we had to create a temporary file just to do something this simple

**Comment by matthiasclasen** [comment]
I guess we can check for $BASH_VERSION or somesuch if we have to do shell-dependent code
