### ISSUE TITLE
flatpak-builder export complains too aggressively about Exec line in desktop file

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak#260]
The .desktop file for the application I want to package contains `Exec=python -m foo`.  This is to support python style installations with `--user`. After a `pip install --user foo`, a user can execute `python -m foo` to run the module. `~/.local/bin/foo` would be an option, but `~/.local/bin/` is, unfortunately, not necessarily in the PATH of the user.

Anyway, I found `python -m foo` to be working for `--user` as well as "regular" installs. Now flatpak is complaining about it, although the "python" binary does exist:

```
sh-4.3$ type -a python
python is /usr/bin/python
sh-4.3$ 
```

So I don't understand why it's (fatally) complaining.
I would appreciate if the checks in flatpak would be more relaxed and acknowledged the fact that the python binary exists.

**Comment by muelli** [comment]
FWIW: The relevant code seems to have been introduced with b42bc359f634ca6cbcd062362549c91b0ccbee65

**Comment by alexlarsson** [comment]
Fixed it to just warn in this case.

**Comment by muelli** [comment]
cool. I think the warning is slightly misleading, but it's probably better to nudge people into providing absolute paths rather than depending on the binary being in the PATH.
Thanks!

**Comment by alexlarsson** [comment]
Yeah, its not ideal, but its complex to find the binary in the full PATH, because the PATH includes the runtime, as well as ways to modify the PATH env var in various places.
