### ISSUE TITLE
Flatpak 1.1.3 causing GNOME on Xorg to crash on login

### ISSUE THREAD

**Issue by brittyazel** [flatpak/flatpak#2600]
## Linux distribution and version
Archlinux updated on Jan 15, 2019
## Flatpak version
Flatpak 1.1.3
## Description of the problem
Upon upgrading to Flatpak 1.1.3 on Archlinux my GNOME Xorg sessions no longer would work and would crash immediately upon login. After typing in my password into GDM, the screen would go black and then immediately kick me back to the login screen. GNOME on Wayland is unaffected it seems.

Downgrading my Flatpak package to 1.1.2 solves the issue, and the GNOME on Xorg session works just as expected.

**Comment by matthiasclasen** [comment]
A fix is in #2597 

Should be easy enough to patch locally into /etc/profile.d/flatpak.sh if you need a workaround

**Comment by brittyazel** [comment]
Awesome, thanks Matthias, I'll forward this over to the packagers for ArchLinux

**Comment by brittyazel** [comment]
Weirdly that issue seems to be in relation to Bash vs Dash, but my Archlinux install is using Bash and I'm still having the issue. Hopefully the fix works for us nevertheless

**Comment by matthiasclasen** [comment]
there was some reference to bash 5.0 not supporting this syntax

**Comment by brittyazel** [comment]
Gotcha, that would do it then

**Comment by matthiasclasen** [comment]
fix merged
