### ISSUE TITLE
In 'flatpak list' command, long Description affects Application visibility

### ISSUE THREAD

**Issue by Erick555** [flatpak/flatpak#2605]
## Linux distribution and version
Arch Linux
## Flatpak version
Flatpak 1.1.3
## Description of the problem
In output from `flatpak list` command, long `Description` may cause `Application` name being cut at the beginning. Assuming that Application name is most important info (used in `flatpak run xxx`) it creates bad user experience.

Among possible fixes, the Description could be moved to the last column or the one column should be prevented from affecting others.
## Steps to reproduce
```
$ flatpak list
Description                                                           Application             Version    Branch Arch   Origin              Installation
Platform                                                              …fedoraproject.Platform            f29    x86_64 fedora              system
Freedesktop.org Application Platform version 18.08 - Shared librarie… …g.freedesktop.Platform            18.08  x86_64 flathub             system
Intel                                                                 …p.Platform.VAAPI.Intel            18.08  x86_64 flathub             system
html5-codecs                                                          ….Platform.html5-codecs            18.08  x86_64 flathub             system
```

**Comment by matthiasclasen** [comment]
One thing to note in your example: the fd.org runtime should probably shorten its name, and move the version to the version field

**Comment by matthiasclasen** [comment]
one thing we added recently is tweakable ellipsization. You can now (in 1.2.0) do `--columns=description,app:full,branch,version,...` to prevent the app id from being ellipsized.

Still tweaking though

**Comment by nanonyme** [comment]
@matthiasclasen FWIW it looks like there's actually now two fields combined into one in Flatpak. That's not appstream name but "name - summary". Yes, this will be quite long.

**Comment by alexlarsson** [comment]
master split the name - summary into two columns and made the summary not be in the default list.
Also I asked the runtime developers to shorten the names in the appdata file, as these tended to be the long ones.
