### ISSUE TITLE
Controller rumble broken in PCSX2 Flatpak  

### ISSUE THREAD

**Issue by Shoegzer** [flatpak/flatpak#2608]
## Linux distribution and version
Linux Mint 19.1

## Flatpak version
1.0.6

## Description of the problem
In the [PCSX2 Flatpak](https://github.com/flathub/net.pcsx2.PCSX2), controller rumble works in the UI, however when you enter any game that supports rumble, it doesn't work.  Possibly related to udev libraries?

## Steps to reproduce
Connect any gamepad with rumble support (DS4 pad used here), launch PCSX2, click Config > Controllers > Plugin Settings > Gamepad Configuration > Enable rumble > Uncheck and recheck box.  Observe rumble working.  Launch any game that supports rumble and observe that it doesn't.

Note that these rumble problems were encountered at exactly the same time Issue #2558 started occurring, though while PCSX2's file picker is now working after that issue was resolved and closed, rumble support remains broken.

**Comment by Shoegzer** [comment]
Update: This ended up being a local issue on the test system which was since fixed.  Closing.

**Comment by matthiasclasen** [comment]
thanks for updating the issue!
