### ISSUE TITLE
Please add flatpak driver support for nvidia-415-27

### ISSUE THREAD

**Issue by puxplaying** [flatpak/flatpak#2613]
The latest available driver via Flatpak is nvidia-415-25, current driver is nvidia-415-27.

**Comment by TingPing** [comment]
Building: https://flathub.org/builds/#/builders/2/builds/7545

**Comment by tannisroot** [comment]
Why is it building for an hour already 🤔

**Comment by TingPing** [comment]
8 things queued ahead of it so no builders available yet.
