### ISSUE TITLE
Obtain themes from host

### ISSUE THREAD

**Issue by AdrianVovk** [flatpak/flatpak#2632]
Hello!

I'm developing a distro and I've run into the problem of GTK themes. I understand that flatpak allows you to install themes from flathub and should do so automatically, but why does it not allow the sysadmin to bind /usr/share/themes into /run/host/share/themes? I understand the risk of incompatibility, but AFAIK gtk3's CSS has been stable since 3.20 and is guaranteed to not change.

If my user wants to install some obscure theme, they should be able to do so at risk of breakage. My distro's tweak tool could include a "Use untested themes" option that switches on the theme import from the host.

Thank you

**Comment by kirbyfan64** [comment]
Maybe related to #2538?

**Comment by TingPing** [comment]
> I understand the risk of incompatibility, but AFAIK gtk3's CSS has been stable since 3.20 and is guaranteed to not change.

Ok so a user installs `flatpak` on Ubuntu 16.04 which is still supported, it pulls in an unversioned host theme, and everything is broken.

Its probably safe to pull in versioned theme dirs but nobody uses them so it wouldn't help.

**Comment by AdrianVovk** [comment]
> Ok so a user installs `flatpak` on Ubuntu 16.04 which is still supported, it pulls in an unversioned host theme, and everything is broken.

@TingPing You ignore that I say this:
> I'm developing a distro

So I don't really care how flatpak works on other distros. Flatpak should work exactly the same way as it does today everywhere else, unless those distros decide to enable support for this. This can be a compilation flag with the build system for all I care (though that removes the possibility of it being optional to the user).

> My distro's tweak tool could include a "Use untested themes" option

There is zero need to turn this on by default, I agree. Really all I need is for some way to have a way to add files into `/run/host` with some drop-in config directory. For example, `/etc/flatpak/imports/10-untested-themes.conf` could be:
```
[Import]
From=/usr/share/themes
To=/run/host/share/themes
```
and my distro's tweak tool can create/delete this file as necessary. There is probably a more elegant solution, though

**Comment by TingPing** [comment]
> How feasible is it to generate a flatpak locally without having an SDK installed?

If the GTK theme is pure data (no build step) it should be possible to only build with the platforms.

> Are there any examples of a flatpak build manifest that takes a local directory from the system and packages it up?

I don't think so but look at the `"dir"` source type in `man flatpak-manifest`. This shouldn't be too hard. As @matthiasclasen was saying though there are still details to get right. If you reference any icons in the theme you must guarantee that icon theme is packaged too. If you have any symlinks in the theme you must ensure they are still valid in the sandbox.

**Comment by AdrianVovk** [comment]
@TingPing What would I set for the SDK field in the manifest? The platform? Or just not include an SDK field?

I probably won't bother with the details. If the theme uses links that aren't relative and all that jazz, and doesn't work in the flatpak environment, then it's an upstream bug, or needs to be properly packaged into a Flatpak and put on Flathub. This is only used if the user enables "Untested themes" so breakage is expected

**Comment by TingPing** [comment]
@AdrianVovk 	`org.freedesktop.Platform`.

**Comment by AdrianVovk** [comment]
@TingPing Alright. I'll get flatpak-builder packaged on my distro and try to figure something out.

Once I get it working, I'll close the issue

**Comment by AdrianVovk** [comment]
@TingPing I'm failing to get this to work... Flatpak does not allow me to write to /usr/share/runtime/share without naming the package `org.gtk.Gtk3theme.SOMETHING`, but then I can only write to `/usr/share/runtime/share/SOMETHING`

How could I work around this?

**Comment by TingPing** [comment]
> naming the package org.gtk.Gtk3theme.SOMETHING, but then I can only write to /usr/share/runtime/share/SOMETHING

That is correct. For example: https://github.com/flathub/org.gtk.Gtk3theme.elementary/blob/master/org.gtk.Gtk3theme.elementary.json#L15-L18

**Comment by AdrianVovk** [comment]
@TingPing I've been able to package individual themes from the system, so that's good enough for me. I'll close this issue

What's the best way to group together all of the theme flatpaks I generate to allow all of them to be uninstalled as a group?

**Comment by TingPing** [comment]
> What's the best way to group together all of the theme flatpaks I generate to allow all of them to be uninstalled as a group?

I guess you could add a tag to them and then have a script iterate over all installed flatpaks with that tag.
