### ISSUE TITLE
Unable to override the TMPDIR environment variable

### ISSUE THREAD

**Issue by bertogg** [flatpak/flatpak#2641]
## Linux distribution and version

Debian r9.7 ("stretch") and Debian testing

## Flatpak version

1.0.6
(Debian 1.0.6-1~bpo9+1 for stretch and 1.0.6-2 for testing)

## Description of the problem

It's not possible to override the TMPDIR environment variable (neither with the `--env` command-line option nor with the `[Environment]` section on the metadata file).

## Steps to reproduce

```
$ flatpak run --env=TMPDIR=foobar --command=sh APP_NAME
sh-4.4$ echo $TMPDIR

sh-4.4$
```

## Additional information

This is working fine with Flatpak 1.0.3 from Fedora 29 Silverblue, and reportedly also with version 1.0.6 from the same distribution.

Here's an example of an actual bug where this is causing problems: https://github.com/flathub/org.telegram.desktop/issues/62

**Comment by bertogg** [comment]
Ok, I found the problem.

The bubblewrap binary has the setuid bit set in Debian, and glibc removes some environment variables from those programs, including TMPDIR:

https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/generic/unsecvars.h;hb=HEAD

**Comment by smcv** [comment]
Hmm, yes. In principle Flatpak could pass those variables through (if set) with `bwrap --setenv` instead?

**Comment by smcv** [comment]
`TMPDIR` might well be the only interesting one in that list in practice.

**Comment by bertogg** [comment]
That sounds like a good solution.

**Comment by philmmanjaro** [comment]
Happend here some progress or is `sysctl kernel.unprivileged_userns_clone=1` currently the preferred way, as I see a trend on desktop oriented distros to enable it by default via `CONFIG_USER_NS_UNPRIVILEGED=y`? Also why is `TMPDIR` unsecure var in **glibc**?

**Comment by refi64** [comment]
It's cleared out because being able to override setuid's tmpdir means you can try to manipulate files in ways it's not expecting.

**Comment by philmmanjaro** [comment]
Setting `--with-priv-mode=none` in **bubblewarp** instead of `--with-priv-mode=setuid` might only work when the kernel supports `unprivileged_userns_clone`. Is that really the way to go? Should **flatpaks** not rather use `bwrap --setenv` instead if they need `TMPDIR`?

**Comment by anthraxx** [comment]
It would really be awesome to see --setenv being used to get around the problem and fix runtimes that choose to not have unprivileged userns for whatever reason they decide.

There is no new trend, the kconfig switch is a patch on top of the sysctl switch by a single base distro. However the hard switch to non suid flatpak/bwrap is primarily to simply work around this TMPDIR issue. However, doing so breaks runtimes that choose to not want that (including Debian) plus systems that use hardened Linux (where it
is disabled by default).

Another possibility would be to have a configure option to enable a suid helper which is used whenever unprivileged userns is not available, but passing --setenv seems to be an overall good option?

Cheers

**Comment by wland32** [comment]
Anything new on this solution?
Arch just broke my setup due to the removal of suid to work around this issue and I would really like to see both bubblewrap and flatpak to work again on debian as well as archs linux-hardened kernel.

If there is anything I can do as a non developer please let me know. (Where is the tip jar?)
