### ISSUE TITLE
Enable proprietary codec support in QWebEngine?

### ISSUE THREAD

**Issue by coslyk** [flatpak/flatpak#2646]
## Linux distribution and version
LinuxMint 19.1 Mate
## Flatpak version
1.0.1
## Description of the problem
The QWebEngine in KDE runtime can't play H.264 videos on the Internet. Is it possible to enable it? See https://doc.qt.io/qt-5/qtwebengine-features.html
Or if there is a license problem, is it OK to make it as a runtime plugin or as a BaseApp?

**Comment by kirbyfan64** [comment]
This should probably be filed at https://gitlab.com/freedesktop-sdk/flatpak-kde-runtime instead.

**Comment by matthiasclasen** [comment]
yes, can you please file it there ?
