### ISSUE TITLE
Only system icon themes are mounted, not  user icon themes

### ISSUE THREAD

**Issue by refi64** [flatpak/flatpak#2649]
Icon themes can be placed in either ~/.icons or ~/. local/share/icons, but neither are available from the sandbox at all. Only `/usr/share/icons` bind-mounted as `/run/host/share/icons` is available.

**Comment by refi64** [comment]
Was there ever a fix / resolution for this to be closed? If it's just lack
of any movement / PRs I'd take a stab myself, but there was never any
feedback.

**Comment by TingPing** [comment]
Not implemented. I think font configs are handled in HOME so there is precedent.
