### ISSUE TITLE
Revoke permissions of app

### ISSUE THREAD

**Issue by piegamesde** [flatpak/flatpak#2651]
## Linux distribution and version
`4.20.4-arch1-1-ARCH`
## Flatpak version
`Flatpak 1.1.3`
## Description of the problem
I have installed `com.axosoft.GitKraken` and it has the following file system permissions: `filesystems=host`. I do not like this and would like to restrict file system access only to folders containing my git projects.

## Steps to reproduce
Run
- `flatpak --user install com.axosoft.GitKraken`
- `flatpak override --user --filesystem=xdg-documents/git com.axosoft.GitKraken`
- `flat info --show-permissions com.axosoft.GitKraken`
## Expected result
The shown permissions should be:
`filesystems=xdg-documents/git;`
## Actual result
`filesystems=host;xdg-download;xdg-documents/git;`

**Is there a way to revoke the `host` permission?**

**Comment by alexlarsson** [comment]
Yes, you need to override --nofilesytem=host
