### ISSUE TITLE
Keep getting 503 Service Unavailable when trying to install Gnome Builder

### ISSUE THREAD

**Issue by sprite-1** [flatpak/flatpak#2659]
## Linux distribution and version
elementary OS 5.0
## Flatpak version
Flatpak 1.2.0
## Description of the problem
I've been trying to install Gnome Builder but it keeps failing on me.
## Steps to reproduce
1. Go to https://wiki.gnome.org/Apps/Builder
2. Click on the "Get Builder 3.30" button.
3. Install via `flatpak install org.gnome.Builder.flatpakref`
4. It will ask to install other stuff.
5. After a while it will fail and show `error: Failed to install org.gnome.Sdk: While pulling runtime/org.gnome.Sdk/x86_64/3.30 from remote flathub: Server returned status 503: Service Unavailable`

**Comment by AsciiWolf** [comment]
This seems to be a Flathub issue, not a Flatpak one.

**Comment by dbarnett** [comment]
See flathub/flathub#845 (marked fixed prematurely, but clearly it isn't). You can follow up there.

**Comment by jonathon-love** [comment]
i have found this to be very useful when installing this from flathub, in fact it should probably go in the installation instructions.

```
until flatpak install org.blah.Blah; do echo "Trying again"; sleep 2; done
```

you'll notice that between 503's, progress is actually being made, so this isn't redownloading the same content over and over.

cheers

**Comment by hfiguiere** [comment]
not a flatpak issue.
