### ISSUE TITLE
Cannot validate icon / Unclear error description

### ISSUE THREAD

**Issue by haecker-felix** [flatpak/flatpak#2660]
## Linux distribution and version
GNOME GitLab CI (gcc150.osuosl.org)

## Description of the problem
Since yesterday/today the GitLab CI pipeline from Shortwave / Fragments is failing, because it cannot validate the icon. It just says '... is not a valid icon:', without further information. Can someone please give me more information here? I don't know what's the problem here / what I should fix. It worked before without any problem.

https://gitlab.gnome.org/World/Shortwave/-/jobs/200446
https://gitlab.gnome.org/World/Fragments/-/jobs/200427

## Steps to reproduce

`$ flatpak build-export repo app`
error: /builds/World/Shortwave/app/export/share/icons/hicolor/scalable/apps/de.haeckerfelix.ShortwaveDevel.svg is not a valid icon:

**Comment by BrainBlasted** [comment]
This seems to be happening with multiple projects in GNOME:

* https://gitlab.gnome.org/GNOME/gnome-chess/-/jobs/200541
* https://gitlab.gnome.org/BrainBlasted/fractal/-/jobs/200726
* https://gitlab.gnome.org/GNOME/gnome-games/-/jobs/200531

**Comment by Alexander-Wilms** [comment]
Flatpak now validates icons: https://github.com/flatpak/flatpak/commit/f52d00f3916199f92e8bf5f42274de97dd97ebf1

**Comment by mwleeds** [comment]
For what it's worth I saw the same error message in the unit tests on the Endless fork of Flatpak, until I added these patches from the Debian packaging:

- https://salsa.debian.org/debian/flatpak/commit/3b29d037bd3c369f42dd19a29418051611c0f291 (a code change)
- https://salsa.debian.org/debian/flatpak/commit/81729347c7063acc8189a2e614629c5abbf513a2 (a packaging change)
- https://salsa.debian.org/debian/flatpak/commit/557b9d6de300992d401a4542eac5bfa227ed3b6d (a packaging change)

I'm guessing just the two patches from the first commit are necessary, but I haven't verified that.

**Comment by mwleeds** [comment]
@smcv are those something you plan to upstream?

**Comment by smcv** [comment]
I thought I had, but apparently not.

**Comment by smcv** [comment]
#2661 fixes the unit tests. It does not necessarily fix the original bug report: I don't know why the icon validation is failing in the original bug report. Applying the patches from #2661 and passing the new `--disable-sandbox` option to `flatpak build-export` will help for some root causes, but not for others.

If you are packaging Flatpak in a Debian derivative and you don't want to spend time duplicating what I'll have to do in Debian anyway, you're welcome to merge from https://salsa.debian.org/debian/flatpak (or contribute your changes there, if you get there first).

**Comment by mwleeds** [comment]
Yes, the packaging branch for Endless flatpak is already based on your Debian branch (thanks for that!)

**Comment by matthiasclasen** [comment]
Could be missing the gdk-pixbuf svg loader

**Comment by matthiasclasen** [comment]
Can you add --verbose to that command ?

**Comment by haecker-felix** [comment]
I can confirm, it works now, everything is green again.
