### ISSUE TITLE
Mintinstall can't be run from app chooser from flatpak. 

### ISSUE THREAD

**Issue by pyroxar** [flatpak/flatpak#2662]
## Linux distribution and version
Linux Mint 19.1
## Flatpak version
flatpak 1.0.1
GNOME 3.28
## Description of the problem
![obraz](https://user-images.githubusercontent.com/23406555/52008557-2344ff80-24d1-11e9-9883-8d9fe9729650.png)

Error: Can't find sub process "gnome-software".
Linux Mint don't use GNOME Software, they have their software manager.
It shouldn't be "gnome-software" but "mintinstall".
## Steps to reproduce
Install GameHub from flatpak.
Run It and click option to integrate GamHub with Steam (Steam must be installed in system).
Click the "Software manager" green link.

Links:
https://github.com/linuxmint/mintinstall/issues/236
https://github.com/tkashkin/GameHub/issues/186

**Comment by matthiasclasen** [comment]
Not a flatpak issue. This is built into gtk
