### ISSUE TITLE
Flatpak can't deal with empty %U

### ISSUE THREAD

**Issue by AdrianVovk** [flatpak/flatpak#2663]
## Linux distribution and version
carbonOS 0.0.1 (my own, in development)

## Flatpak version
1.2.0
OSTree 2019.1

## Description of the problem
When launched through the .desktop file, most applications open up a file called %U if no file is provided

For example: gedit, Password Safe, Evince, and more. All of them try to open ~/%U. I suspect this has something to do with Flatpak's path translation

## Steps to reproduce
Install org.gnome.Evince, and open it from the application menu. You'll see an error saying `Unable to open document "file:///home/USER/%U".`

**Comment by TingPing** [comment]
Flatpak isn't involved in that process. It makes a desktop file and it is launched as normal.

**Comment by AdrianVovk** [comment]
I just did some more testing, and found a locally-installed app that uses %U. It turns out, an app that is pinned to my taskbar and is opened behaves differently to an app that is in my "All Apps" list an is opened. This is an issue with my shell.

I appologise for wrongly assuming this is a Flatpak issue.
