### ISSUE TITLE
make-test-runtime.sh requires non-standard C.UTF-8 locale

### ISSUE THREAD

**Issue by heftig** [flatpak/flatpak#267]
The `make-test-runtime.sh` script attempts to copy `/usr/lib/locale/C.*` into the runtime, however on Arch Linux systems (and AFAIK other systems using the standard glibc locales) only `locale-archive` exists.

flatpak 0.6.9

**Comment by alexlarsson** [comment]
Does any of the en_US locales exist instead, or are even they in the archive?

**Comment by heftig** [comment]
As I said, only `locale-archive` exists. `locale -a` returns:
```
C
de_DE.utf8
en_DK.utf8
en_US.utf8
POSIX
```

The only locales that exist without configuration are `C` and `POSIX`.

**Comment by heftig** [comment]
For the record, copying everything from `/usr/lib/locale/` into the runtime seems to work.

**Comment by alexlarsson** [comment]
Yeah, but that makes the runtime huge, and makes the tests take a long time.
Maybe we can do that if C.utf8 doesn't exist only. Can you do a patch for that?

**Comment by heftig** [comment]
The tests pass for me even if I don't copy anything at all.

I'm pretty ignorant about how C.UTF-8 works on Fedora et al.  Maybe we can just ignore a failure to copy?

**Comment by alexlarsson** [comment]
I guess that would work too.

**Comment by hadess** [comment]
FYI, see:
https://sourceware.org/glibc/wiki/Proposals/C.UTF-8
https://sourceware.org/ml/libc-alpha/2015-02/msg00247.html

**Comment by mwleeds** [comment]
For the record Arch still has a workaround for this:
https://github.com/archlinux/svntogit-packages/blob/packages/flatpak/trunk/PKGBUILD#L50 currently has:
`sed -i '/locale\/C\./d' tests/make-test-runtime.sh`

So I assume this is still an issue (unless Arch just hasn't cleaned that up).

**Comment by heftig** [comment]
It's not an issue anymore. Arch's `glibc` package now has the `/usr/lib/locale/C.UTF-8` directory but the `flatpak` package hasn't been updated since.
