### ISSUE TITLE
Summary file regeneration very slow

### ISSUE THREAD

**Issue by dbnicholson** [flatpak/flatpak#269]
Our repos at Endless are pretty big. In particular, the runtimes are housed with the OS, so there are a lot of objects in there. When running `flatpak build-update-repo`, the `Updating summary` step can take 20 minutes or more. I haven't looked at the details of what's going on, but I guess this is probably the generation of the `xa.cache` metadata?

Any ideas to speed this up?

**Comment by alexlarsson** [comment]
I've noticed it being somewhat slow too, especially with the static-delta generation being faster now that it is threaded. But I have not researched it.

Also, are you sure that is the slow step, and not the pruning of old refs? I.e. do you use --prune?
If so, try with this commit to see which part is actually slow: 
  https://github.com/flatpak/flatpak/commit/e18ab46977afbaf499029084d2c6b7e8fbf132f9

If collecting sizes and metadata is the slow part, then an obvious performance fix is to reuse any such data in the previous summary, in case you're doing a partial update.

**Comment by dbnicholson** [comment]
It's definitely in the summary updating path. Looking at `flatpak_repo_update`, I see some obvious improvements for our case.

1. Only operate on refs that are relevant to flatpak. We have our OS in the same repo as the runtimes. These are large commits, and collecting size information would take a long time. To that end, instead of calling `ostree_repo_list_refs` with a `NULL` prefix, only look at `app`, `runtime` and `appstream` prefixes.

2. If multiple refs point to the same commit, only read the size info once. We have compat refs to handle stable branching for reasons that are tied to our development process. So, clients are currently setup to install from the `eos3` branch, but this is actually pointing to the same commit as the corresponding `eos3.0` branch. Collecting size and metadata information for both of these is obviously wasteful.

3. As you say, reusing the size data from the previous summary would be a big win. Collecting sizes on big trees like runtimes is an expensive operation, so it would be nice to only do this when needed. Maybe `build-update-repo` could add a `--force` flag to ignore the data from the existing summary file, but I think you'd need to change the `flatpak_repo_update` API or something like that.

**Comment by alexlarsson** [comment]
Sounds good to me! For the API, the common/* directory is free to change API however we want, as it is internal. lib/*.h is ABI stable though.

Another optimization for the size calculation would be to store not only sizes for the previous commits, but also for directory objects. So, if two runtimes share a directory, but not the entire commit (common for e.g. sdk and platform) we can reuse the size calculations.

**Comment by dbnicholson** [comment]
Tackled the first 2 in https://github.com/flatpak/flatpak/issues/280.

As for the 3rd item, I thought about another option (that's a bit similar to https://bugzilla.gnome.org/show_bug.cgi?id=756266, which I really need to get upstreamed). When collecting the data, store it in the commit's detached metadata. Since the commit isn't going to change, try to read it out the next time before collecting the data. Then you're really only doing the collection one time per commit.
