### ISSUE TITLE
Icon validator rejects qTox SVG icon

### ISSUE THREAD

**Issue by sudden6** [flatpak/flatpak#2692]
## Linux distribution and version
Debian Stretch
## Flatpak version
https://packages.debian.org/stretch-backports/flatpak (Flatpak 1.2.0)
## Description of the problem
Since today (2019-02-09) flatpak rejects the SVG icon of our application (qTox) in our CI system. It worked 2 weeks before, no changes on our side.
## Steps to reproduce
We noticed this problem in the build log of our CI and I suppose it's because of the recent update to Flatpak 1.2.0 in Debian backports. The build log with the error can be found here: https://travis-ci.org/qTox/qTox/jobs/490921405#L5054

I first thought the issue happens because we use SVGZ for our icons and that's apparently not supported according to https://github.com/flatpak/flatpak/issues/1142, but the problem happens even with pure SVG in: https://github.com/qTox/qTox/pull/5549

The file in question is https://github.com/qTox/qTox/blob/master/img/icons/qtox.svg does it need anything special? Or is this a bug in the icon validator?

**Comment by sudden6** [comment]
Seems to be similar to https://github.com/flatpak/flatpak/issues/2660 investigating

**Comment by TingPing** [comment]
You might be missing librsvg.

**Comment by sudden6** [comment]
Yes, it was the missing dependency on `librsvg2-2` and `librsvg-common` in the debian `stretch-backports` repositor.
