### ISSUE TITLE
libflatpak crashes Gnome Builder

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#2717]
## Linux distribution and version
```
● ostree://fedora-workstation:fedora/29/x86_64/silverblue
                   Version: 29.20190222.0 (2019-02-22T01:15:00Z)
                BaseCommit: 30790b239252aa5ca9a0361a1381503572a13125e964588787f86eed18af7126
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
       RemovedBasePackages: gnome-terminal-nautilus-3.30.2-1.fc29.x86_64
                            gnome-classic-session-3.30.1-1.fc29.noarch
                            gnome-shell-extension-places-menu-3.30.1-1.fc29.noarch
                            gnome-terminal-3.30.2-1.fc29.x86_64
                            gnome-shell-extension-apps-menu-3.30.1-1.fc29.noarch
                            gnome-shell-extension-launch-new-instance-3.30.1-1.fc29.noarch
                            gnome-shell-extension-window-list-3.30.1-1.fc29.noarch
                            gnome-shell-extension-alternate-tab-3.30.1-1.fc29.noarch
           LayeredPackages: adapta-gtk-theme aeskulap android-tools baobab bat cheese
                            chromium dconf-editor dnf easytag exa fd-find fedora-toolbox
                            ffmpeg file-roller file-roller-nautilus fuse-exfat gcc git
                            gnome-encfs-manager gnome-logs gnome-tweaks gnome-usage gpick
                            hack-fonts htop iftop julia linux-libertine-biolinum-fonts
                            linux-libertine-fonts mosh neovim open-sans-fonts powerline-go
                            pv python3-matplotlib ripgrep sqlite sqlite-devel task tilix
                            tilix-nautilus tmux tokei xenlism-wildfire
                            xenlism-wildfire-midnight youtube-dl zsh
             LocalPackages: rpmfusion-nonfree-release-29-0.5.noarch
                            zfs-release-1-5.fc29.noarch protonmail-bridge-1.1.1-1.x86_64
                            rpmfusion-free-release-29-0.5.noarch
```

## Flatpak version
`v.1.2.3`

## Description of the problem
Since a few days, Gnome Builder gets pretty unstable as soon as I open more application windows. I filed a bug report again Builder [here](https://gitlab.gnome.org/GNOME/gnome-builder/issues/828#note_444149), but it seems that libflatpak caused this.

## Steps to reproduce
Open two projects in Builder, it then often crashes at the second window opening or at project loading in the second window (when the “open some project” window closes and the project window opens).

**Comment by mwleeds** [comment]
The stack trace in https://gitlab.gnome.org/GNOME/gnome-builder/issues/828#note_444149 seems to be missing a lot of debug symbols which makes it a bit difficult to investigate this without reproducing it

**Comment by fbruetting** [comment]
Ah I see. So I installed the debug package for Builder and reproduced, but the output is even smaller… O_o
[log_debug.txt](https://github.com/flatpak/flatpak/files/2902409/log_debug.txt)

**Comment by mwleeds** [comment]
Maybe you need the debug extension for the runtime? So `org.gnome.Sdk.Debug` I think

**Comment by fbruetting** [comment]
6,5 GB via 30 kB/s… see us next year! ✌

**Comment by fbruetting** [comment]
Is it normal that processing the stacktrace takes like forever when hitting that crash with debug symbols?

Is this complete now, or is still something missing?

[log_debug_2.txt](https://github.com/flatpak/flatpak/files/2912738/log_debug_2.txt)

**Comment by mwleeds** [comment]
Thanks for taking the time to get that info. I submitted a fix which I'm almost certain will fix the seg fault, but feel free to verify that. It would also be interesting to know why you have missing deploy files in your installation. What's the output of these commands:
`find /var/lib/flatpak/ -name active -exec echo {} \; -exec ls -l {}/ \;`
and
`find ~/.local/share/flatpak/ -name active -exec echo {} \; -exec ls -l {}/ \;`
(if you're comfortable with your list of apps being public)

**Comment by fbruetting** [comment]
No problem of course. Here it is:

[1.txt](https://github.com/flatpak/flatpak/files/2913012/1.txt)
[2.txt](https://github.com/flatpak/flatpak/files/2913013/2.txt)

**Comment by mwleeds** [comment]
`deploy` files record information like what remote you installed from, whether the app/runtime is EOL, some appstream data, etc. As far as I can tell you have deploy files for every app and runtime, so I'm not sure why you hit that error path.
