### ISSUE TITLE
Permissions denied on flatpak update

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak#272]
I never used sudo for flatpak or similar. However for updating Builder or any other app, no polkit dialog is shown and instead this warning is displayed:

(flatpak update:29536): flatpak-WARNING **: Unable to remove old checkout: Permission denied

This happens running on flatpak update org.gnome.Builder

**Comment by alexlarsson** [comment]
Does this happen only for builder?
Also, this is a warning only, right? Everything still works?

**Comment by alexlarsson** [comment]
Should be fixed by:
https://github.com/flatpak/flatpak/commit/874a67c721a5987eb803822fec9618621c4ff502
