### ISSUE TITLE
flatpaked app and native host experience

### ISSUE THREAD

**Issue by dwrobel** [flatpak/flatpak#2732]
## Linux distribution and version
Fedora 28
## Flatpak version
$ rpm -qv flatpak
flatpak-1.0.6-4.fc28.x86_64

## Description of the problem
The question is how to achieve native host experience using flatpaked application _(e.g. Atom)_.

## Steps to reproduce
Install atom and the following plugins:
 - https://atom.io/packages/build
 - https://atom.io/packages/build-make

- Create a `test-project` directory with the following `Makefile` file inside it:
```
all:
        gcc --version
```
- Use "Add Project Folder" to add `test-project` to the Atom editor
- Open `Makefile` file
- Press `F9` to run `make` tool

The output is:
```
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Instead of the following:
```$ gcc --version
gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

So the question is how to develop a software using native tools. The example with `gcc` is just a simplified version as in reality there are hundred of dependencies installed on the native host filesystem needed to compile and run the example `test-project`.

According to [sandbox-presmission](http://docs.flatpak.org/en/latest/sandbox-permissions.html)  documentation, `/usr` directory, amongst other, is blacklisted and as a result simple command like 'make' which will build the `test-project` on native host is useless when invoked from flatpak (sandboxed) application.

Is there any plan to make this kind of functionality working out of the box _(without requiring any changes in the application to be sandboxed + any plugin developed for such an application)_?

**Comment by matthiasclasen** [comment]
One of the main goals of flatpak is to isolate applications from the host system.

**Comment by kirbyfan64** [comment]
Override the application to allow `--talk-name=org.freedesktop.Flatpak` and run `flatpak-spawn --host whatever` to run the command on the host system.

**Comment by dwrobel** [comment]
> flatpak-spawn --host

Thank you for the hint. In case of [build-make](https://atom.io/packages/build-make) I found an option to override the `make` command as following:
```$ cat ~/.var/app/io.atom.Atom/data/python/bin/make 
#!/bin/sh

exec flatpak-spawn --host make "$@"
```

**Comment by dwrobel** [comment]
> One of the main goals of flatpak is to isolate applications from the host system.

I appreciate it, although `isolation` doesn't necessary mean that isolated parts can't communicate between each other - see [optoisolator](https://en.wikipedia.org/wiki/Opto-isolator).
`flatpak` also isolates filesystem access but there is an option to access the host filesystem and IMHO similar solution to map some binaries _(and then use the host equivalent)_ might be quite usable for applications like `Atom` or `VSCode` where you want to use flatpaked app but develop/debug host applications.

**Comment by TingPing** [comment]
You can just pull in host binaries, they are from an unknown ABI and there is no reason to assume they work. Thus `flatpak-spawn` is the only way host tools can sanely be used since it executes outside.

The solution agreed upon for this is just to make flatpak extensions for more tools but somebody has to do that work.

Anyway I think this can be closed since pulling host binaries into the sandbox will always be out of scope. Extensions for tools is already possible and running commands on the host is already possible.
