### ISSUE TITLE
flatpak does not see under ~/.var/app even with --filesystem=host

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#2735]
## Linux distribution and version

Fedora 29

## Flatpak version

Flatpak 1.2.3

## Description of the problem

Someone noticed on the GIMP flatpak that one had no access to anything under `~/.var/local/` but `org.gimp.GIMP`. At first I thought it may have been a security measure (like a flatpak package cannot have access to config files from other packages), but @TingPing has been saying that this is not the case. Especially since `--filesystem=host` is set.

See: https://github.com/flathub/org.gimp.GIMP/issues/30

## Steps to reproduce

Run the following command:
```
$ flatpak run --command=ls org.gimp.GIMP//stable ~/.var/app
org.gimp.GIMP
```
Expected result: a whole more bunch of folders, same as when you run:

```
$ flatpak run --filesystem=home --command=ls org.freedesktop.Platform//1.6 ~/.var/app
```

Note: this doesn't happen only with GIMP. I tried with a bunch of other applications, such as `net.scribus.Scribus//stable` or `org.blender.Blender//stable` (which also have set `--filesystem=host`) and they only see their own directory only.

So if really not on purpose (like an exception to the `host` permission just for these files), this is apparently a bug of flatpak.

**Comment by mwleeds** [comment]
The change to the behavior of hiding `~/.var/app` was made by this commit: 4a5445040014e135077c09e906dd7a6a2a323b63

And according to the release notes for 0.6.14:
```
 * By default all the directories in ~/.var/app (except the app), as
   well as ~/.local/share/flatpak are hidden in the sandbox.
```

So it seems fairly intentional, but I agree it's strange that `--filesystem=host` wouldn't overrule that. Maybe because apps shouldn't be messing with the data of other apps?

However `--filesystem=~/.var/app/` does make the whole directory visible.

**Comment by Erick555** [comment]
`--filesystem=host` is often ~~ab~~used for access for removable media so not allowing `~/.var/app` is better than nothing. Keep in mind that apps using ghostscript like gimp are vulnerable to https://www.openwall.com/lists/oss-security/2019/01/23/5

**Comment by Jehan** [comment]
@mwleeds Ok. I thought it would be intentional (seemed a bit specific to be a random bug, though who knows!), yet as @TingPing was unsure as well, I wanted to make sure.
Also if there is a workaround, as you note, that's ok, I guess. Though I don't think we will need it (we can just ask people to save their files somewhere else).

So if you consider this is normal, even with `--filesystem=host` set, then just feel free to close. Though I would suggest to document the behavior somewhere first. This is probably the main point here.

**Comment by matthiasclasen** [comment]
The main takeaway is to reduce the use of filesystem holes in your sandbox, not to find new ways to plug even more holes.
