### ISSUE TITLE
`flatpak kill` not working

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#2736]
## Linux distribution and version
FSB29

## Flatpak version
v1.2.3

## Description of the problem
I recognized that Spotify ate too much CPU on my system and its GUI crashed (window not existent anymore, but music still played). So I wanted to kill it via `flatpak kill` – however, this was not possible and I had to kill all its processes, see my screen shot.

## Steps to reproduce
I don’t know, but that now happened the second time.

![bildschirmfoto von 2019-03-01 16-41-23](https://user-images.githubusercontent.com/10520767/53651017-1c331d80-3c46-11e9-802f-ec2cf6e85ddd.png)

**Comment by kirbyfan64** [comment]
I believe you're supposed to pass an app ID or instance ID `flatpak kill`, not the PID.

**Comment by fbruetting** [comment]
Oh, you’re right, sorry! 🤦‍♂
