### ISSUE TITLE
Will it ever be possible to make flatpak apps respect system settings?

### ISSUE THREAD

**Issue by ripefig** [flatpak/flatpak#2738]
## Linux distribution and version
Kubuntu 18.10

## Flatpak version
1.0 

## Description of the problem

Flatpak applications don't follow system font, theme and other settings stored in your home folder.

![image](https://user-images.githubusercontent.com/45201036/53693542-f70fed80-3db2-11e9-901e-9864af4541d4.png)

I suppose they look OK on Gnome systems unless you change the font or override the default CSS, but on KDE this means they look atrocious. Here's a typical GTK3 app packaged as .deb, for contrast:

![image](https://user-images.githubusercontent.com/45201036/53693612-dbf1ad80-3db3-11e9-9c0f-b3a2839f7653.png)

With a few simple tweaks to $HOME/.config/gtk-3.0, the Gnome app basically looks native on KDE. This obviously isn't the case with Flatpak app.

I am not sure if this is bug or intended design, but it is a problem. When you change the font you expect all the usual apps to follow it. Same with the the theme and the window buttons in the CSD.

**Comment by kirbyfan64** [comment]
They *should*, to an extent at least: 

- If you current theme is available on Flathub, Flatpak should have installed it automatically to match up. If not, you can probably install it manually via `flatpak install flathub org.gtk.Gtk3theme.Breeze`. 
- I admittedly have no clue about CSD or how the SSD Wayland extension is picked up. 
- Also not sure what's going on with the font, that should also be automatic. 
- AFAIK changes to ~/.config/gtk-3.0 aren't going to be picked up outside the sandbox, if that's how you're setting your theme and fonts, try GNOME Tweaks or manually via dconf instead.

**Comment by ripefig** [comment]
I dunno, I can't figure it out:

![image](https://user-images.githubusercontent.com/45201036/53703672-bac9a500-3e25-11e9-9551-005e02809162.png)

Flatpak apps disregard this setting - if it. They also disregard the setting that controls window buttons in CSD.

Either way, even if there is a way to make it work - which I am not sure there is - it's clearly not suitable for KDE users. And I'd like to keep the CSS tweaks. All these gtk themes are designed to be used without SSD - whereas in a KDE environment you need to force SSD on the apps. Therefore I tweak the CSS to style headerbars to look like toolbars.

Normal GTK3 packages do require advanced tweaking, sadly, but it IS feasible to make them look native (as my screenshot demonstrates). I was actually hoping that Flatpak apps would integrate better given that they are supposed to use portals - meaning they should be able to use native KDE file pickers etc. But none of the packages I installed actually do this in practice.

**So the bottom line is that Flatpak apps just don't integrate at all on KDE.** I'd like to see much more attention given to making sure that they do.

**Comment by TingPing** [comment]
- System level fontconfig settings should be picked up by default.
- Throwing things in HOME (custom css, etc) in general does not and will never work indeed.
- Themes have to be packaged
- For GSettings to be picked up the application requires permissions to talk to DConf.

**Comment by matthiasclasen** [comment]
In 1.2 and newer, flatpak has a settings portal that should take care of most of the toolkit level settings you mention, such as fonts.

I don't think you should generalize in this way. It may not be suitable for _you_, but it is clearly suitable for great number of other people.

**Comment by eszlari** [comment]
Isn't this the same issue: https://github.com/flatpak/flatpak/issues/1147

https://bugs.kde.org/show_bug.cgi?id=387091

**Comment by TingPing** [comment]
@eszlari 	No because this isn't a Qt app.

**Comment by matthiasclasen** [comment]
I don't think this is actionable.

The settings portal addresses it, basically.
