### ISSUE TITLE
Core dumped while updating org.freedesktop.Sdk

### ISSUE THREAD

**Issue by necho14** [flatpak/flatpak#2739]
## Linux distribution and version
Fedora 29
## Flatpak version
1.2.3
## Description of the problem
hello, does anyone have similar problem? 

`1. [\] org.freedesktop.Sdk        x86_64 18.08  flathub    16.5 MB / 1.8 GB`   
`2. [ ] org.freedesktop.Sdk.Locale x86_64 18.08  flathub < 222.0 MB (partial)`

`Updating 1/2… █████▍                27%  8.2 MB/sBus error (core dumped)`

**Comment by kirbyfan64** [comment]
Does this occur consistently? 

Could you grab a stack trace by installing the flatpak debuginfo (`dnf debuginfo-install`) and then use `coredumpctl debug flatpak` to open a debugger and grab a stack trace?

**Comment by matthiasclasen** [comment]
not much we can do without a stacktrace
