### ISSUE TITLE
Flatpak not preserving Exec key causes Shell's search for evince/totem give zero result

### ISSUE THREAD

**Issue by nbenitez** [flatpak/flatpak#2749]
**Fedora 29 Flatpak 1.2.0**

Evince and Totem both come installed by default on Fedora 29, if you do a gnome-shell overview search for any of them, "evince" (or "totem") you get a positive result. Now if you do:

1. Install evince or totem as flatpak (from flathub)
2. Reboot the system or close the session (or just run `sudo update-desktop-database`)
3. Do an overview search for "evince" (or "totem")..

**Actual outcome:**
No match is found for any of "evince" or "totem" searches.

**Expected outcome:**
It should return at least one match for any of the two searches.

**Rationale:**
When a flatpak application is installed alongside the distro packaged version of that application, then the `.desktop` file of the flatpak version is preferred by GLib's `g_desktop_app_info_search()` over the distro one (code [here](https://gitlab.gnome.org/GNOME/glib/blob/cec5778cad6fffd829872062eff30b27f196b758/gio/gdesktopappinfo.c#L1074)) because the flatpak one has higher precedence (it's in a `~/.local` path so has more precedence than the one in `/usr/share/applications`). This is fine.

So, the shell overview's app search uses `g_desktop_app_info_search()` which searches over the keys provided in the `.desktop` file of the flatpak version. But flatpak, in its modified version of the original application's `.desktop` file, replaced the `Exec=` key by a custom one (`Exec=/usr/bin/flatpak run ...`) _**without preserving the original content of the modified key**_ in another place, that place could e.g. be a new key named `X-Flatpak-Old-Exec`.

The lack of Flatpak at preserving the content of the original `Exec=` key is what ultimately causes Shell's overview to not match results by that key.

**Proposed fix:**
Save the original content of the `Exec=` key under a new `X-Flatpak-Old-Exec` key. Then a small fix would be added to GLib's `g_desktop_app_info_search()` to look up this key instead when the exec key is of type `Exec=/usr/bin/flatpak ...` .

This proposed fix was suggested by a GLib's maintainer on the corresponding GLib issue, see https://gitlab.gnome.org/GNOME/glib/issues/1706 .

**Comment by matthiasclasen** [comment]
I think that is a weird approach to fix this. I don't think searching apps by their binary name is worth an extra key like this. Just add 'evince' as a keyword

**Comment by AdrianVovk** [comment]
@matthiasclasen Do you mean that flatpak itself would add the keyword? That'd be sufficient probably

**Comment by matthiasclasen** [comment]
No, I mean that the applications desktop file should come with suitable keywords

**Comment by nbenitez** [comment]
> No, I mean that the applications desktop file should come with suitable keywords. I don't think there's any need for automagic solutions here.

Ok, I'll propose adding the keyword to evince and totem then, thanks for promptly answering to this merge request.
