### ISSUE TITLE
Figure out how we should present metadata permissions on install/update

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#275]
Currenly we just always install/update, no matter what the permissions the app requests, although we do have APIs in the library to get the metadata of an uninstalled app.

Long term, once apps start being more useful when sandboxed we should start warning the user if the app requires certain permissions, or if the permissions change during update.

**Comment by alexlarsson** [comment]
My current thinking is that we define some quite tight subset of permissions and define those as "sandboxed", and then mark everything else as not sandboxed, with a details button that has a textual description of the actual permissions (which may contains some technical gobbledegook).

As for the list of "safe things", I think there are some categories:

Not necessarily 100% safe, but should be ok and the entire thing is mostly useless without them:
 * --share=network (most interesting app needs network, especially those you want to sandbox)
 * --device=dri (In theory this should be safe due to the kernel validation of gpu commands, although the interface is huge and its likely there are holes)

Safe interfaces:
 * --socket=wayland
 * --socket=fallback-x11 (when on wayland)
 * --pulseaudio (when using the sandbox policy patches, need to get update on status of this)

**Comment by TingPing** [comment]
What about dbus and filesystem access? Will any be considered "unsandboxed"?

**Comment by alexlarsson** [comment]
@TingPing Yeah, if you can e.g. write to ~/.bashrc, or can call the "execute some javascript" gnome-shell dbus method, etc etc, then you have full access anyway.

**Comment by alexlarsson** [comment]
We no do this in the transaction confirmation. It could possibly be nicer, but we have the basic infra at least.
