### ISSUE TITLE
'flatpak remote-delete' does not remove all refs it says it will

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#2757]
## Linux distribution and version

Fedora 30

## Flatpak version

flatpak-1.2.3-2.fc30

## Description of the problem

`flatpak remote-delete` says it will remove all refs installed from that remote, but it doesn't actually do so.

## Steps to reproduce

```
$ sudo flatpak remote-delete gnome-nightly
The following refs are installed from remote 'gnome-nightly':

   1) runtime/org.gnome.Platform/x86_64/master
   2) runtime/org.gnome.Platform.Locale/x86_64/master
   3) runtime/org.gnome.Sdk.Locale/x86_64/master
   4) runtime/org.gnome.Sdk.Docs/x86_64/master
   5) runtime/org.gnome.Sdk.Debug/x86_64/master
   6) runtime/org.gnome.Sdk/x86_64/master

Remove them? [y/n]: y
Uninstalling runtime/org.gnome.Platform/x86_64/master
```

It didn't even uninstall runtime/org.gnome.Platform/x86_64/master, though. I still have that installed when I check with `flatpak list`. I think it's just failed without printing any error message.

**Comment by mcatanzaro** [comment]
Note: uninstalling them all manually with `flatpak uninstall` works perfectly fine.

**Comment by alexlarsson** [comment]
Fixed.
