### ISSUE TITLE
Should flatpak repair not require sudo?

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2759]
Currently for most Flatpak commands `sudo` is not needed because privileges are escalated via polkit when necessary. However to run the `repair` command on the system installation you have to be root, and the man page for it currently recommends `sudo`. Should we use polkit there so that `sudo` is never necessary with Flatpak?

**Comment by mwleeds** [comment]
I guess there's one other command that requires `sudo` according to https://github.com/flatpak/flatpak/issues/1860

**Comment by matthiasclasen** [comment]
Both of those are commands that should not be required in regular operation. Thats my understanding of the rationale for not pk-ing them. Of course, we could change that and say: pk all the things!
