### ISSUE TITLE
"flatpak list" doesn't handle "--arch=" correctly

### ISSUE THREAD

**Issue by doraskayo** [flatpak/flatpak#2762]
## Linux distribution and version
Fedora 29

## Flatpak version
1.2.3-2

## Description of the problem
The "flatpak list" command doesn't handle the case of "--arch=" being specified correctly.

## Steps to reproduce
1. Try to list your installed apps and runtimes, and notice that nothing is listed:
    ``` bash
    $ flatpak list --arch=$(flatpak --default-arch)
    ```

**Comment by mwleeds** [comment]
Fixed in https://github.com/flatpak/flatpak/pull/2765
