### ISSUE TITLE
Progress percentage sometimes goes backwards

### ISSUE THREAD

**Issue by rugk** [flatpak/flatpak#2768]
## STR

In my case, I just installed the Atom flatpak from flathub… :smile: 

## What happens

![backwards](https://gitlab.gnome.org/GNOME/gnome-software/uploads/ccab3a8aa26a3f7992f0ffa6fea01b51/backwards.gif)

(I could only catch the end of that ridiculous thing, at the beginning it was even harder, jumping from 30% to 23% or so…)

## What should happen

Please, don't confuse me! :stuck\_out\_tongue\_winking\_eye: 

## System

Flatpak 1.2.3
Fedora 29

----

moved from https://gitlab.gnome.org/GNOME/gnome-software/issues/625

**Comment by kirbyfan64** [comment]
AFAIK this is normal-ish, as the progress total is just an estimate.

**Comment by rugk** [comment]
Wtf, no. This never happened in the past and even if it is an estimate, it should _never_ go backwards. This looks _really_ ugly!

**Comment by rugk** [comment]
So what, @mattdangerw? Is this really expected behaviour?

**Comment by kirbyfan64** [comment]
What's the alternative? If there's more data than expected coming, it'd be worse for the progress bar to just freeze until it matches up again.

Ugliness is subjective; IMO it looks a bit odd but overall fine.

**Comment by rugk** [comment]
Question is why can't you expect the size before?

And IMHO, it would be better to wait some seconds than jump back somewhere...

**Comment by matthiasclasen** [comment]
This is the way it is. We don't have complete information. It is not ideal, but it is unlikely to change
