### ISSUE TITLE
Flatpak gtk apps dependend on gsettings-daemon running for fonts, icons and themes.

### ISSUE THREAD

**Issue by ripefig** [flatpak/flatpak#2771]
If you want your system settings to be applied, you need to run this daemon on login if you're not using Gnome desktop (or some close derivative). I am on KDE and it took me while to figure out why none of my system settings transferred over, either those in KDE control center or gsettings. 
(with this kind of fragmentation, it's probably not even fair to call them system settings, but I digress). Normal packages are fine because they just get their configs from the home folder.

Turned out that I had to install and set to autostart the gsettings-daemon. Not a great experience for users outside Gnome. Not a great user experience - how should users know that this is what they need to do to get the proper system font?

Might it be possible to either do a hard dependency on gsettings-daemon or have some desktop-agnostic place to grab the settings for GTK (normally these would be dotfiles in the home folder, which I know flatpak can't use)?

The second alternative is clearly ideal, though a hard dependency would be better than nothing. This affects the majority of flatpak apps running outside Gnome, given that most of these apps are GTK.

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/xdg-desktop-portal/commit/96a447255033cd34b9c515ad6d8bbdd9d0542665

addresses this

**Comment by ripefig** [comment]
Awesome. Thank you.

**Comment by TingPing** [comment]
I don't think XSettings usage was ever replaced in GTK so the linked commit alone isn't enough.

You also don't technically need `gnome-settings-daemon` since there are like 3 or 4 XSetting implementations that exist (just not one by KDE).
