### ISSUE TITLE
Brackets: Live Preview fail

### ISSUE THREAD

**Issue by celsolom** [flatpak/flatpak#2772]
## Linux distribution and version
Linux Mint 19.1 Tessa
Fedora 29

## Flatpak version
Flatpak 1.0.7
Flatpak 1.2.3

## Description of the problem
Hello! I'm having problems with the [Brackets](https://github.com/adobe/brackets) Flatpak package. When i try to open the live preview, popup a error and from what I've noticed this error is caused when it tries to run Google Chrome and can not find it, which is understandable. Is it possible to call a local program from Flatpak? Is there any permission to solve this? I appreciate your help.

Some errors reported:
https://github.com/adobe/brackets/issues/14466
https://github.com/adobe/brackets/issues/7372

This code appear to be related to the bug:
https://github.com/adobe/brackets-shell/blob/master/appshell/appshell_extensions_gtk.cpp
https://github.com/adobe/brackets-shell/blob/651b74b932634167520cce7b1794ec06cc9b51a2/appshell/appshell_extensions_gtk.cpp#L102
https://github.com/adobe/brackets-shell/blob/651b74b932634167520cce7b1794ec06cc9b51a2/appshell/appshell_extensions_gtk.cpp#L123

## Steps to reproduce
$ flatpak install flathub io.brackets.Brackets
$ flatpak run io.brackets.Brackets
On the main app window, press **crtl+alt+p**

**Comment by TingPing** [comment]
Brackets would have to detect its inside a flatpak sandbox and adapt to use `flatpak-spawn --host` to launch host applications.

**Comment by Mikenux** [comment]
@TingPing: I think this can be closed since you said it's not directly an issue in flatpak. Also, Brackets is no longer available on Flathub, which is understandable since the Adobe Brackets repository (https://github.com/adobe/brackets) has been archived.
