### ISSUE TITLE
Add PCSC socket

### ISSUE THREAD

**Issue by valentindavid** [flatpak/flatpak#2777]
To allow multiple access to smart cards or security keys, there is a daemon called `pcscd` that has a socket available at `/run/pcscd/pcscd.comm` or the value of environment variable `PCSCLITE_CSOCK_NAME`.

Some application may need that, for example Yubico applications for their keys.

**Comment by valentindavid** [comment]
Here is an application I would like to submit that requires the feature: https://github.com/valentindavid/flathub/tree/com.yubico.YubiOath

**Comment by kirbyfan64** [comment]
Can you do `--filesystem=xdg-run/pcscd:create`?

**Comment by valentindavid** [comment]
@kirbyfan64 `xdg-run` is not the right directory. I could do `--filesystem=/run/pcscd:create` though. But that does not work correctly when `PCSCLITE_CSOCK_NAME` is defined.

**Comment by alexlarsson** [comment]
This is merged
