### ISSUE TITLE
Wrong example in flatpak-run manpage

### ISSUE THREAD

**Issue by cfergeau** [flatpak/flatpak#2780]
## Linux distribution and version
Fedora 30
## Flatpak version
Flatpak 1.2.3

## Description of the problem

`man flatpak-run` has the command below in its examples:
`flatpak run --command=bash org.gnome.Sdk`
which is not working as expected
(I do not have this specific runtime installed so I tested with the kde one)

```
flatpak run --command=bash org.kde.Sdk
error: app/org.kde.Sdk/x86_64/master not installed
```

However this works as expected and gives a prompt inside the runtime:
`flatpak run --command=bash org.kde.Sdk/x86_64/5.12`

It would be great if the command from the manpage could do the right thing, if that's not possible, the man page needs to be fixed.

**Comment by mwleeds** [comment]
Do you have more than one branch of `org.kde.Sdk` installed? You can tell from the output of `flatpak list --runtime --columns=ref`

**Comment by refi64** [comment]
This occurs for me even if there's one instance installed.

**Comment by cfergeau** [comment]
Only one branch of org.kde.Sdk. I tried with other ones (org.freedesktop.Platform) before filing the bug. I just checked that I have only one kde Sdk:
```
$ flatpak list --runtime --columns=ref
Ref
com.bluejeans.BlueJeans.Locale/x86_64/stable
org.freedesktop.Platform/x86_64/18.08
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08
org.freedesktop.Platform.html5-codecs/x86_64/18.08
org.gnome.Platform/x86_64/3.30
org.gnome.Platform/x86_64/3.32
org.kde.KStyle.Adwaita/x86_64/5.12
org.kde.Platform/x86_64/5.12
org.kde.PlatformTheme.QGnomePlatform/x86_64/5.12
org.kde.Sdk/x86_64/5.12
```
