### ISSUE TITLE
Feature Request: Ability to override runtime

### ISSUE THREAD

**Issue by mat8913** [flatpak/flatpak#2786]
## Linux distribution and version
NixOS 19.03
## Flatpak version
Flatpak 1.2.3
## Description of the problem
I can't set a permanent override of an app's runtime. 
## Steps to reproduce

    $ flatpak --user override --runtime=org.gnome.Platform//3.32 org.libreoffice.LibreOffice 
    error: Unknown option --runtime=org.gnome.Platform//3.32

**Comment by matthiasclasen** [comment]
why would you want to do that?

**Comment by mat8913** [comment]
In LibreOffice, it's to make the icons display properly.

**Comment by mat8913** [comment]
Actually nevermind, I just found out about `org.freedesktop.Platform.Icontheme.Adwaita` which solves all my problems. Sorry for the noise. I do wish it were automatically installed though.
