### ISSUE TITLE
Do not provide GIMP's gtk3-port branch (for now)

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#279]
Hi!

I am writing on behalf of the GIMP team. First thank you very much for the GIMP nightlies in Flatpak. That's awesome. Having many people testing our master and reporting bugs at this stage is exactly what we need!

We are only a little annoyed by the GTK+3 binary. As far as I am concerned, the "GTK+3" version of GIMP does not exist. This is a mirage. The origin/gtk3-port branch is very broken and basically just has enough changes to make it buildable with GTK+3. But this is far from a usable GIMP. We are not (at all) working actively on it, and probably won't before GIMP 2.10 release (check out the logs, we had 2 commits this year, 5 in 2015…). This cannot give a good image of GIMP at all. Even for testing, this is mostly useless since basically everything is broken at this stage, we know it.
Could this GTK+3 dev version of GIMP be removed from your nightlies please? At least for now. We will tell you when we will really start working actively on the GTK+3 version if you want.
Thanks!

**Comment by alexlarsson** [comment]
Ok. I'll remove it for now.

**Comment by alexlarsson** [comment]
This is removed now

**Comment by Jehan** [comment]
Thanks!

**Comment by ElectricPrism** [comment]
"We are not (at all) working actively on it, and probably won't before GIMP 2.10 release (check out the logs, we had 2 commits this year, 5 in 2015…)"

How is that? Do you mean unique patches or just patches? I see many commits here:
https://git.gnome.org/browse/gimp/log/?h=gtk3-port

Also, I exclusively use GTK3 git branch and consider it to be the single most important improvement in over a decade and the biggest new feature that will draw users. I hope developers see this the way I do.

**Comment by Jehan** [comment]
>> We are not (at all) working actively on it
> How is that? Do you mean unique patches or just patches? I see many commits here:

We regularly rebase the branch, and it has been done a few days ago. Thus you cannot take into account the "Age" field in this web UI, as this one gets broken by the rebase (it takes the date of the rebase for all commits which have been reorganized). There is only one new commit on the branch from Mitch on September 7, and the previous one was from me on February 25. Others with younger authorship dates, are simply commits from master.

So yes, a commit every few months (3 in the last 10 months!) is not active development, it is maintenance at best. We only maintain the branch enough so that when we have to work on it, it will at least build. And we sometimes do some fix when we think of it (i.e. we add a commit on master than we know will break with GTK+3, so we revert or fix it directly).

> Also, I exclusively use GTK3 git branch and consider it to be the single most important improvement in over a decade and the biggest new feature that will draw users. I hope developers see this the way I do.

We have nothing against people using it willingly and if you are aware of its supra-alpha status. If you happen to be a developer, we also welcome fixes and patches. In such a case, you can as well build it from source anyway (since we rebase it every few months, that's not huge amount of work for a dev). We are simply not comfortable with having it spread widely as though it is ready software. That will only bring us flames.

Now we are not the maintainers of this flatpak repository and that's free software. If the package went back up online, we would do nothing about it. But if so, we'd appreciate proper warning.

**Comment by thekyriarchy** [comment]
Has this changed at all? I'd love to be able to test the GTK3 port

**Comment by Jehan** [comment]
Nothing has changed. The GTK+3 port branch has barely been touched (if at all) since last year. You can still compile it yourself if you want (you always could), but I would not recommend it even as a development version for test… unless you are a developer and want to provide patches (but then, you'll want to compile anyway).

Note: GIMP 2.10 is getting close (cf. for instance the [news for dev version GIMP 2.9.8](https://www.gimp.org/news/2017/12/12/gimp-2-9-8-released/) yesterday!). When this will happen, we will switch to work on the GTK+3 port directly! So not that much to wait for anymore.

**Comment by bugaevc** [comment]
https://github.com/GNOME/gimp/commit/1d30426102d5559401b8f4eb3c39e254eaf99f02

**Comment by Jehan** [comment]
> GNOME/gimp@1d30426

Yes, well I am the author of this manifest, and 2 years have passed since then. And we actually started to work actively on GIMP 3 not even a month ago. So the GIMP 3 branch is still not advised for any kind of actual production work.

This manifest is for our internal use mostly for now and there are still no public GTK+3 flatpak. Please don't make this into any kind of news with more meaning that it has. :-)
