### ISSUE TITLE
Please add rating features for the application

### ISSUE THREAD

**Issue by saileshkush95** [flatpak/flatpak#2791]
I think it would be better if you add rating features.

**Comment by matthiasclasen** [comment]
Ratings and reviews are handled at a higher level, in frontends like gnome-software or discover.

**Comment by mwleeds** [comment]
@saileshkush95 if you meant that you want this in flathub (as opposed to flatpak) there's an issue for it here: https://github.com/flathub/linux-store-frontend/issues/18
