### ISSUE TITLE
Not showing the architecture column in the CLI output

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#2794]
## Linux distribution and version
FSB 30

## Flatpak version
v1.2.3

## Description of the problem
At `flatpak update` or at `flatpak list`, the CLI output needs a lot of horizontal space. As the architecture column doesn’t seem to have any relevance (because it’s the same for all flatpak packages I installed) and therefore seems to be superfluous, I’d like to ask if this could be left out?

I imagine that it could be relevant to packagers, which may package applications for different architectures, but I don’t think that this is a standard use case, and could be detected when there are more packages with different architectures existing.

**Comment by alexlarsson** [comment]
As per the comment in the PR, yes, it is important to show the arch when you have multiple arches installed. But yes, when not so, we should avoid showing it.

**Comment by rugk** [comment]
> when you have multiple arches installed

Is that even possible? I mean if I am on an x64 system, I hardly can have ARM installed. Okay, maybe x86_64, but this is dying anyway…
So maybe make that arch thing an opt-in, but hide it by default.

**Comment by fbruetting** [comment]
Rather `noarch`, but who cares?

**Comment by rugk** [comment]
> Rather noarch,

Never seen such a flatpak… :smile: 
But yes, anyway, indeed: Who cares.

**Comment by mwleeds** [comment]
Commit 277a44374448634d8244e4aaee7d95c4f2e95d70 fixed this for `flatpak list` but not `flatpak update`
