### ISSUE TITLE
security: https pinning

### ISSUE THREAD

**Issue by shawnl** [flatpak/flatpak#2795]
## Linux distribution and version
Ubuntu Disco
## Flatpak version
one in Ubuntu
## Description of the problem
When adding a repository flatpak should show some information about the https certificate the site uses, like Firefox does, its fingerprint, and pin that certificate to the repo. That way installing a flatpak does not put the whole system in the hands of a fragile x509 PKI system.

**Comment by TingPing** [comment]
On a somewhat related note: the next version of `libsoup` will support HSTS

**Comment by shawnl** [comment]
This pinning should be unconditional, and not depend on HSTS.

**Comment by TingPing** [comment]
You are right that HSTS is kind of unrelated.

Anyway all commits are GPG signed and the GPG key never changes automatically so that ensures the data is secure.

If you think certificate system is compromised you have much better problems.

**Comment by shawnl** [comment]
> If you think certificate system is compromised you have much bigger problems.

But it is https://blog.mozilla.org/security/2018/03/12/distrust-symantec-tls-certificates/

And I think we should trust it for the initial connection. Just not subsequent connections. Apt does not depend on the fragile CA system.

**Comment by TingPing** [comment]
>  Apt does not depend on the fragile CA system.

`flatpak` trusts the same thing `apt` does, gpg...

**Comment by shawnl** [comment]
> flatpak trusts the same thing apt does, gpg...

Oh ok. then it is fine. When you said "commit" I thought that was a source code commit, because the gnome infrastructure turns out a binary. I assume that it is doing things right, and checking it an additional way, even if you did not describe why.

**Comment by TingPing** [comment]
I think TOFU is the only thing that can be done. Flatpak is decentralized so its not going to bundle store specific keys or anything. Distros can include default repo configs though I suppose.

@shawnl 	Commit refers to how OSTree works which is how Flatpak stores and transfers data. So every transaction is signed and verified (again after first use).

**Comment by shawnl** [comment]
I am satisified that it is not totally relying on https
