### ISSUE TITLE
Add keyfile for installing a remote + install app from the remote

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#28]
We want to support a simple key-file format looking something like:
```
[Flatpak Repo]
Url=http://....
Title=Descriptive title
GpgKey=BASE64...
```
We also need this format registrered with a mimetype, so that clicking on one can automatically open a nice UI for installing the remote.

It would also be interesting to have a similar format (but different group name, so different icon/mimetype) which has the same data + an app id. Installing such an file would create a non-enumerable version of the remote, plus install the specified app from it. Then an app webpage could have a single-click file to "install the app" which doesn't need update for each new minor release (which a bundle would need).

**Comment by matthiasclasen** [comment]
Looks like this was added in https://github.com/flatpak/flatpak/commit/7e58da35af6a5c01aad62932a0097c6b81bed603

**Comment by alexlarsson** [comment]
Reopening and retitling, because we still don't have the second kind, i.e. a keyfile that acts similar to a bundle install (without the data).

**Comment by matthiasclasen** [comment]
This was added as .flatpakref files.
