### ISSUE TITLE
Question: How can I use flatpack-istalled Gimp to work on a screenshot?

### ISSUE THREAD

**Issue by melolontha-melolontha** [flatpak/flatpak#2801]

**Comment by matthiasclasen** [comment]
You are probably better off asking your question in another place, say https://discussion.fedoraproject.org/c/desktop/silverblue

**Comment by melolontha-melolontha** [comment]
Xubuntu 16.04.6 LTS x64
Flatpak version: 1.3.1
Description of the problem: With the help of [https://github.com/flatpak/flatpak/issues/2799](https://github.com/flatpak/flatpak/issues/2799) I learned how to invoke an application installed as flatpak.

In my case I want to start Gimp 2.10.8. - I used to define a delayed starter on my xfce4-panel in order to take a screenshot with mouse cursor and the like some seconds after invoking the starter. The starter was previously, i.e. with the standard version of Gimp, associated with a command

`xfce4-screenshooter -fmd 4 -o gimp`

I wanted to take advantage of the new version 2.10.8 of Gimp and first I installed it as a snap. However, this snap-installed version of Gimp could not access `/tmp`, where `xfce4-screenshooter` stores its result. Unfortunately, my xfce4-screenshooter 1.8.2 can not be configured to store its results in `~/tmp`, which is accessible to the snap-installed program. I was told, a flatpak-installed version of Gimp is able to access `/tmp`.  - Therefore I uninstalled the snap-installed version of Gimp and installed it as flatpak instead. 

With the help of issue 2799, I learned that I have to call Gimp not simply by typing `gimp` on a command line, but rather as 

`flatpak run org.gimp.GIMP`

which is the right command from the command line to run Gimp. Indeed, now I have found starter in the graphics section of the start menu and looked up the command associated with it. It is 

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gimp-2.10 --file-forwarding org.gimp.GIMP @@u %U @@`.

With the teaching of issue 2799 I changed the stater command for my delayed screenshot to
`xfce4-screenshooter -fmd 5 -o flatpak run org.gimp.GIMP`

but when I invoke it, it only generates a png screenshot file in `/tmp` but Gimp does not open. **What is my mistake?** (sorry, I am not an experienced Unix user).

**Comment by melolontha-melolontha** [comment]
I just found a solution of my question: I just have to include the whole command, which replaces the previous `gimp` command, in double quotation marks:

`xfce4-screenshooter -fmd 5 -o "flatpak run org.gimp.GIMP"`

Bingo!

**Comment by refi64** [comment]
> `xfce4-screenshooter -fmd 5 -o flatpak run org.gimp.GIMP` 

Off the top of my head there are two issues here: 
- xfce4-screenshooter `-o` expects a single application name, not a full command line. If /var/lib/flatpak/exports/bin is in your path, try `xfce4-screenshooter... -o org.gimp.GIMP`. 
- /tmp isn't shared between host and Flatpak, so you'd have to set TMPDIR= to something else first.

**Comment by melolontha-melolontha** [comment]
Refi, my solution 

`xfce4-screenshooter -fmd 5 -o "flatpak run org.gimp.GIMP"`

actually worked for me.
