### ISSUE TITLE
Issue with --filesystem=/ on Silverblue

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2804]
On rawhide silverblue, with flatpak 1.3.1, I see the following:

```
$ flatpak run --filesystem=/ org.gnome.ghex 
bwrap: Can't mkdir parents for /run/host/usr: Read-only file system
```

**Comment by matthiasclasen** [comment]
more information is here: https://github.com/flathub/org.gnome.Builder/issues/8

**Comment by matthiasclasen** [comment]
The title is confusing, actually. This is about org.gnome.Builder sandbox setup failing on Silverblue. See the other issue for details

**Comment by alexlarsson** [comment]
I installed silverblue f30 in a vm and installed builder, but it worked for me...

**Comment by matthiasclasen** [comment]
GRR

turns out having filesystems=/:ro; in your overrides does this to you :(
