### ISSUE TITLE
How bad is "WARNING: Failed to validate desktop file"?

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#2805]
## Linux distribution and version
Whatever is on flathub
## Flatpak version
Whatever is on flathub
## Description of the problem
Looking at a build output on flathub, I notice this error:
```
flatpak-builder: Exporting to repository^GWARNING: Failed to validate desktop file /srv/buildbot/worker/build-x86_64-4/build/builddir/export/share/applications/org.gimp.GIMP.desktop: /srv/buildbot/worker/build-x86_64-4/build/builddir/export/share/applications/org.gimp.GIMP.desktop: error: value "?????????;?????????;????;??????;????????" for locale string list key "Keywords[mr]" in group "Desktop Entry" does not have a semicolon (';') as trailing character
```
Well the good thing is that this is indeed just a non-blocking warning, as the build is otherwise successful (I remember having fixed the same error in the past and, if I recall, it used to be killing the whole build).

Now I have 2 questions regarding this error (other than the fact that we will fix the keyword on our side, of course):

1) What is the consequence of this validation failure since it is only a warning right now? Will it break the [description page](https://flathub.org/apps/details/org.gimp.GIMP) on flathub?

2) I can see that flatpak uses [desktop-file-validate](https://github.com/flatpak/flatpak/blob/master/app/flatpak-builtins-build-export.c#L457). We also use it in GIMP for unit testing to validate our desktop file and I can't reproduce this error with the same desktop file with no semicolon at end of a "keywords" (using `desktop-file-validate` from Fedora 29). What am I missing?

## Steps to reproduce

Look for instance at the output of this [successful build](https://flathub.org/builds/#/builders/12/builds/248), and you'll see the desktop validation warning.

P.S.: sorry I was not sure if it had to be a bug in flathub or flatpak, but since the use of this validation is in flatpak code, I figured…

**Comment by TingPing** [comment]
Hmm, strange it does indeed have a trailing `;`: https://github.com/GNOME/gimp/blob/gimp-2-10/po/mr.po#L574

Maybe some encoding issue on the build machine?

**Comment by matthiasclasen** [comment]
Blind guess: https://cgit.freedesktop.org/xdg/desktop-file-utils/commit/?id=d281ed4b9db22ff9e4c7e56b5cce58a72d11fc54

**Comment by Jehan** [comment]
> Hmm, strange it does indeed have a trailing ;: https://github.com/GNOME/gimp/blob/gimp-2-10/po/mr.po#L574

No it didn't have it. I fixed and added the trailing semicolon after I saw the validation error: https://github.com/GNOME/gimp/commit/054da8591121d4da70822afbd5286fd759f3e8bc

I am not saying there is a bug in the validation warning. I only wondered about the 2 questions I asked in my description:

1.  What is the consequence of this validation failure since it is only a warning right now? Will it break the description page on flathub?

2. I can see that flatpak uses `desktop-file-validate`. We also use it in GIMP for unit testing to validate our desktop file and I can't reproduce this error with the same desktop file with no semicolon at end of a "keywords" (using desktop-file-validate from Fedora 29). What am I missing?

**Comment by matthiasclasen** [comment]
My blind guess is that the versions of desktop-file-utils used are different, possibly by that commit I cited above.

**Comment by Jehan** [comment]
@matthiasclasen Ah ok. That is possible and if the desktop-file-utils is able to fix the missing trailing semicolon by itself now, it is indeed much better (I find this "error" very annoying; like we'd risk breaking the whole metadata just because of a silly semicolon which does not even add any information?!). :-D

Then it answers only the second question, yet if the warning were to disappear when you will update the tools on flathub, the first question is no more anyway.

**Comment by alexlarsson** [comment]
At some point we want to increase the appstream validation requirements on flathub, and when we do that will make the build fatal (rather than seem to succeed and then not show up). However, the requirements are not gonna be about stupid semicolons, but rather about things like listing version info, licence info, rating info, etc.
