### ISSUE TITLE
Sandbox is missing Linux AIO support

### ISSUE THREAD

**Issue by leinardi** [flatpak/flatpak#2806]
## Linux distribution and version
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Disco Dingo (development branch)
Release:	19.04
Codename:	disco
```
## Flatpak version
```
$ flatpak --version
Flatpak 1.3.1
```
## Description of the problem
It seems that the sandbox doesn't allow [Linux Asynchronous I/O syscalls](https://oxnz.github.io/2016/10/13/linux-aio/).

These syscalls are needed, for example, by the [Flexible I/O Tester](https://github.com/axboe/fio).

I want to use `fio` to build an application similar to [CrystalDiskMark](https://crystalmark.info/en/software/crystaldiskmark/) for GNU/Linux and I would like to distribute it via Flathub, the same way I've done already with [GWE](https://flathub.org/apps/details/com.leinardi.gwe).

## Steps to reproduce
Build a flatpak with both libaio and fio:
```json
{
  "name": "libaio",
  "config-opts": [
    "--buildtype=debugoptimized"
  ],
  "buildsystem": "simple",
  "build-commands": [
    "make prefix=$FLATPAK_DEST install"
  ],
  "sources": [
    {
      "type": "git",
      "url": "https://pagure.io/libaio.git",
      "tag": "libaio-0.3.111",
      "commit": "f66be22ab0a59a39858900ab72a8c6a6e8b0b7ec"
    }
  ]
}
```

```json
{
  "name": "fio",
  "config-opts": [
    "--buildtype=debugoptimized"
  ],
  "buildsystem": "simple",
  "build-commands": [
    "./configure --prefix=$FLATPAK_DEST",
    "make -j $FLATPAK_BUILDER_N_JOBS",
    "make install"
  ],
  "sources": [
    {
      "type": "git",
      "url": "http://git.kernel.dk/fio.git",
      "tag": "fio-3.13",
      "commit": "370f38977a241e173b0c60b66252757be809ad3a"
    }
  ]
}
```
Run `fio` on a file on the host made available using portal (mounted at `/run/user/$uid/doc/`).

```
./fio --loops=5 --size=1000m --filename=/run/user/1027/doc/6cc5c9e0/test2.fio --stonewall --ioengine=libaio --direct=1 --name=Seqwrite --bs=1m --rw=write
Seqwrite: (g=0): rw=write, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=1
fio-3.13
Starting 1 process
Seqwrite: Laying out IO file (1 file / 1000MiB)
fio: pid=29, err=38/file:io_u.c:1791, func=io_u error, error=Function not implemented

Seqwrite: (groupid=0, jobs=1): err=38 (file:io_u.c:1791, func=io_u error, error=Function not implemented): pid=29: Sat Apr  6 16:44:39 2019
  cpu          : usr=0.00%, sys=0.00%, ctx=6, majf=0, minf=19
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,1,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):

error = fio: io_u error on file /run/user/1027/doc/6cc5c9e0/test2.fio: Function not implemented: write offset=0, buflen=1048576
```

I've already [contacted the developer](https://github.com/axboe/fio/issues/761) of `fio` and he said that the error number is mapped to `EOPNOTSUPP`, which means that the AIO support is misisng.

If needed I can provide a PyGObject project where it is possible to reproduce the issue.

**Comment by Erick555** [comment]
Flatpak uses blacklist for syscalls so it may be blocked for a reason.

**Comment by matthiasclasen** [comment]
The seccomp blacklist is here: https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L2413

I don't see aio on it.

**Comment by alexlarsson** [comment]
> error = fio: io_u error on file /run/user/1027/doc/6cc5c9e0/test2.fio: Function not implemented: write offset=0, buflen=1048576

This file is on the document portal, which is a fuse mount. Fuse doesn't support aio, so I don't think this is fixable.

**Comment by leinardi** [comment]
I see, thanks for the clarification. For now I think I can use as a workaround `--filesystem=host`.

**Comment by matthiasclasen** [comment]
if it is not fixable, we should probably close this.
