### ISSUE TITLE
Add API documentation for runtimes

### ISSUE THREAD

**Issue by cjao** [flatpak/flatpak#281]
Application developers need to know what libraries and APIs are provided by a runtime. The contents of each runtime should be clearly documented in an easy to find location.

**Comment by alexlarsson** [comment]
This is generally available in /usr/manifest.base and /usr/manifest*.json in the runtimes, at least the ones based on the freedesktop.org runtime.

But yeah, we could make this easier to find.

**Comment by alexlarsson** [comment]
I don't think this is a flatpak issue per se. Rather something we should be better about in the various runtimes.
