### ISSUE TITLE
allow querying FlatpakRemoteRef without network access

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#2817]
It would be nice under some situations from Builder to be able to use libflatpak to query if a SDK extension is known about without having to perform synchronous network access.

Currently, flatpak_installation_list_remote_refs_sync() will likely perform network access which slows down some of our quick checks for setting up build runtimes.

**Comment by alexlarsson** [comment]
Do you want to find a locally installed one? Or a possibly cached one?

**Comment by chergert** [comment]
Possibly cached

**Comment by alexlarsson** [comment]
Does that look ok to you?

**Comment by chergert** [comment]
Yeah the API looks like it does what I need. All the `_full` API variants are sort of wart-looking, but what else can we do.

**Comment by alexlarsson** [comment]
We could call them ..Ex() instead! Then we're enterprise!

**Comment by matthiasclasen** [comment]
this is in 1.3.3
