### ISSUE TITLE
 install multiple flatpack 

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#2819]
Is it possible to install multiple flatpack applications?
flatpak install flathub org.gnome.*
does not do that.

**Comment by aiamuzz** [comment]
even i have been wanting to know on this topic ... as i recollect ... **one of the highlights of using flatpak is the ability of running multiple versions of the same applications side by side** ... which native/legacy installation does not allow !!!

**Comment by damianatorrpm** [comment]
Well what I want is install all programs in the namespace of org.gnome (boxes, gedit, totem).

I don't know how the statement above relates but I don't think it does
```
flatpak install fedora org.wesnoth.Wesnoth
Looking for matches…
Skipping: org.wesnoth.Wesnoth/x86_64/stable is already installed

flatpak install flathub org.wesnoth.Wesnoth
Looking for matches…
error: org.wesnoth.Wesnoth/x86_64/stable is already installed from remote fedora
```

**Comment by mwleeds** [comment]
> Is it possible to install multiple flatpack applications?
> flatpak install flathub org.gnome.*
> does not do that.

You have to specify them manually, e.g. `flatpak install flathub org.gnome.boxes org.gnome.gedit ...` or parse the output of `flatpak remote-ls` if you want to automate it.

> even i have been wanting to know on this topic ... as i recollect ... **one of the highlights of using flatpak is the ability of running multiple versions of the same applications side by side** ... which native/legacy installation does not allow !!!

You can install more than one branch of the same application and use `flatpak make-current` to make one current.

> ```
> flatpak install fedora org.wesnoth.Wesnoth
> Looking for matches…
> Skipping: org.wesnoth.Wesnoth/x86_64/stable is already installed
> 
> flatpak install flathub org.wesnoth.Wesnoth
> Looking for matches…
> error: org.wesnoth.Wesnoth/x86_64/stable is already installed from remote fedora
> ```

The question about installing the same app ID from more than one source was addressed in https://github.com/flatpak/flatpak/issues/2820

**Comment by anil-tudu** [comment]
string them together into one line similar to sudo apt update && sudo apt upgrade -y

sudo flatpak install /home/anil/Downloads/com.github.hugolabe.Wike.flatpakref -y && sudo flatpak install /home/anil/Downloads/com.github.maoschanz.DynamicWallpaperEditor.flatpakref -y && sudo flatpak install /home/anil/Downloads/org.flameshot.Flameshot.flatpakref -y

**Comment by hassanikka** [comment]
You can install multiple flatpaks at single cammand just download all needed apps  form  [flathub.org](http://flathub.org/) in one folder  
cd to that folder for example if it is in download folder cd Download/  ↵  then paste below command
` for i in *.flatpakref; do flatpak install -y $i; done`
After that take a break until install no need to click y or n the process will finish automatically
