### ISSUE TITLE
Flatpak update isn't working without --user flag and is showing a misleading error

### ISSUE THREAD

**Issue by TimKraemer** [flatpak/flatpak#282]
Hey there,

just started to use flatpak, I dislike the user **unfriendly** behavior shown below:

```
> flatpak list
org.gnome.Keysign
> flatpak update org.gnome.Keysign
error: org.gnome.Keysign not installed
```

I know, I'm supposed to use `flatpak --user update org.gnome.Keysign`, but to be honest, I don't really see why. And even more important, why flatpak is lying to my face: `error: org.gnome.Keysign not installed`.
Afterall I can run it with `flatpak run org.gnome.Keysign` (omitting the `--user` parameter).

**Comment by matthiasclasen** [comment]
I agree that the behavior is a bit annoying. We should try to do the right thing in the absence of an explicit --user or --system option.

**Comment by cmurf** [comment]
Yeah I'm hitting this on Fedora 25 also, flatpak-0.6.13-2.fc25.x86_64. Perhaps it'll all just get masked behind a GUI anyway so I'm not overly concerned...

[chris@f25h ~]$ flatpak list
org.libreoffice.LibreOffice
[chris@f25h ~]$ flatpak update org.libreoffice.LibreOffice
Looking for updates...
error: org.libreoffice.LibreOffice not installed

**Comment by rickysarraf** [comment]
flatpak --user is what should be the default, in my humble opinion.

The prime use case of flatpak is to help users get new/latest software.
If an admin wants to make a flatpak available to all users on the
system, it should be an extra option to pass, i.e. flatpak --system

**Comment by cmurf** [comment]
flatpak --user is inherently inefficient on multiuser systems; it also will impact backup and restore strategy. UAlso, user programs can run into quota limits. I think something smarter than a fixed default is better: --system for a user in wheel, otherwise --user.

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Tue, 2017-01-03 at 09:40 -0800, cmurf wrote:
> I think something smarter than a fixed default is better: --system for a user
> in wheel, otherwise --user.

Yes. This would be much more nicer. Thanks.

- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEQCVDstmIVAB/Yn02pjpYo/LhdWkFAlhr8OYACgkQpjpYo/Lh
dWkIBw//cLaqSTjtZ5eCiNw4EX4QVn80ikf36k7GLAHZPDVyeX4Afy1/Xb5HXj3y
HKfx6HqzYg/Y4hBOUR/iwxAAnaYqMngBHgwpmsCVkK6hvTzE1jLzHhgROPAIQMgy
WyGMhUaolvmqFHZglLCG1QUuXqfVatRgyB2P0hkJlebKEWNDMwI1AWiC1Co5ZE/Z
ZjE2+jSXXDFVtuBLHZ3ext5hQ+2E1hpC2E+ZKY78F6hPzXV80O3c4Kpk4FlMEEmv
yupWPpFz5QU16SO6rjyPOJf/wp15tw+/kHRT/2fLtGv4ebkFC4gj6olK13zHeeBG
lGtsfvMHLR5eCzs6VtAYMFOxDoViZNHdJQZmb5sYy9YEaQH+Vc18nHTezdamGX/S
/c0rAElax32FKI/pKub7D7Z6YIRx1YGNCO1QHzSDg1HSX1xLG0mo1/maOMdvw1MP
0RjmEpkUy5EdkKmls7N/c4r34AfG2C6/CTnv26rmQ8qfOm4aEFNl6B9whLpdaOEe
EZYJjUrTApeSg0/mby63wMZjmdYeYBr56ac8XITbqpl69stDXC+nUIDfT+Or8Kkg
yrxMr50gMXxQePT7SZzG6NJUazaQm3txsYSj/wlJCK3EkP9JpkfE7GyelK2N5336
N+iVt+g6u0cRMn9yl4GB8fs3KevWLpu/abYypJlYJFWsCgtPxJI=
=bOde
-----END PGP SIGNATURE-----

**Comment by rathann** [comment]
Same here, confusing as hell:
```
$ flatpak remotes
Name       Options
gnome      user
gnome-apps user
$ flatpak remote-ls gnome-apps
error: Remote "gnome-apps" not found
```
This is on Fedora 26, `flatpak-0.9.7-1.fc26.x86_64`.
