### ISSUE TITLE
install flatpak from multiple vendors

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#2820]
Most of the flatpaks work if you install them from different vendors and rename them 

To reproduce:
I have installed org.wesnoth.Wesnoth 
from 'fedora' repo into --user ($HOME/.local/share/flatpak/app/)
after that I have renamed the folder 
`$HOME/.local/share/flatpak/app/org.wesnoth.Wesnoth 
`to
`$HOME/.local/share/flatpak/app/org.wesnoth.Wesnoth2
`
it works perfectly fine (flatpak --user run org.wesnoth.Wesnoth2)  and even the configuraion stored in $HOME/.var/app/ lands automatically in the folder $HOME/.var/app/org.wesnoth.Wesnoth2 

I can install wesnoth now from flathub and it will live at  
`$HOME/.local/share/flatpak/app/org.wesnoth.Wesnoth 
`and use:
`$HOME/.var/app/org.wesnoth.Wesnoth`

My question is is this supposed to work or just lucky in this case (as all the gnome apps do NOT work if the folder is renamed)

**Comment by mwleeds** [comment]
This is definitely not a supported use case and something will probably break if you make manual changes to the flatpak directory like that. One solution would be to install one version in the system installation and another in the user installation. `flatpak run` will prefer the one in the user installation unless you use `--system`. You could also define a custom installation if you want.
