### ISSUE TITLE
Suspicious line in flatpack strace

### ISSUE THREAD

**Issue by dandelionred** [flatpak/flatpak#2821]
Here is some `strace flatpak run org.qownnotes.QOwnNotes` log https://github.com/pbek/QOwnNotes/issues/1178#issuecomment-482330305

There is such line in the log:
```
write(33, "--ro-bind\0/root\0/root\0--bind\0/ru"..., 606) = 606
```
It looks suspicious to me.

Does bubblewrap usually binds host's /root as container's /root? (even though it is readonly)
Maybe it binds some faked /root?
Or mby the line is a malware sign?

**Comment by alexlarsson** [comment]
In general, flatpak doesn't treat /root in any special way (compared to e.g. /opt, /srv or /home). If you application has --filesystem=host access, then all the regular top level directories gets mounted into the sandbox, but if it doesn't, then none of them are.

That doesn't mean that the app has *access* to it though. That is protected by the unix permissions, just like for non-sandboxed apps.

**Comment by alexlarsson** [comment]
Oh, also i think that line might be from the bubblewrap instance for the dbus proxy, which does have readonly filesystem access even if the app doesn't, so you don't even need --filesystem=host to get that in the trace.
