### ISSUE TITLE
programs should have their own config directory when from different installation

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#2828]
programs should have their own config directory when from different installation
at the moment behavior is as follows:
```
           flatpak run org.wesnoth.Wesnoth
           flatpak --user run org.wesnoth.Wesnoth
           flatpak --installation=devel run org.wesnoth.Wesnoth
```
they would all use the same config path in $HOME/.var/app/$app
I believe they should instead use
```
$HOME/.var/app/$app-[installation]
or
HOME/.var/[installation]/$app
```

this would allow for better development as one can test the application (system) and run side-by-side the development version from --user with different settings

**Comment by matthiasclasen** [comment]
The way to do that is to give the development version a different ID. Then it can be installed and used in parallel with the stable build

**Comment by damianatorrpm** [comment]
but that is only possible at compile time, not runtime, right?

**Comment by matthiasclasen** [comment]
yes
