### ISSUE TITLE
Polari flatpak can not be started

### ISSUE THREAD

**Issue by psmis** [flatpak/flatpak#283]
OS: Fedora 24 Workstation (New installation + updates)
Flatpak 0.6.9

I followed the guide on http://flatpak.org/#users to install Polari.
After the installation is finished, Polari is not starting.
`flatpak run org.gnome.Polari`
When I run this command, journalctl shows the following output but nothing happens:

```
Sep 05 16:05:25 pc dbus-daemon[1468]: Activating service name='org.gnome.Polari'
Sep 05 16:05:25 pc systemd[1441]: Started flatpak-org.gnome.Polari-3103.scope.
Sep 05 16:05:25 pc dbus-daemon[1468]: Successfully activated service 'org.gnome.Polari'
```

Here is how I installed the Polari flatpak
[flatpak.txt](https://github.com/flatpak/flatpak/files/455144/flatpak.txt)

I also created a bug report, since I was not sure where to put it:
https://bugzilla.redhat.com/show_bug.cgi?id=1373211

**Comment by psmis** [comment]
After trying to start Polari there appeared a process called "flatpak-session-helper" that wasn't there before.
Installing and starting the Gnome Maps flatpak seems to work just fine.

**Comment by matthiasclasen** [comment]
I think the problem is likely that polari requires telepathy to be present on the host system. If you don't have that installed, polari is not going to work.

**Comment by alexlarsson** [comment]
Yeah, this is just an issue with how the polari flatpak is created, no way to fix that.
