### ISSUE TITLE
cannot update flatpaks after update to flatpak 1.3.2: "Message recipient disconnected from message bus without replying"

### ISSUE THREAD

**Issue by glaubersm** [flatpak/flatpak#2832]
## Linux distribution and version
Arch Linux
## Flatpak version
1.3.2
## Description of the problem
cannot update flatpak packages.
I get this error:
"Message recipient disconnected from message bus without replying"
## Steps to reproduce
try to update flatpaks running 'flatpak update'.

**Comment by matthiasclasen** [comment]
fixed by https://github.com/flatpak/flatpak/commit/00dfce528326476aa3d9167887b2cefdaec412bd
