### ISSUE TITLE
Non standard GDK_PIXBUF_MODULE_FILE in host breaks some apps

### ISSUE THREAD

**Issue by hedning** [flatpak/flatpak#2833]
## Linux distribution and version

NixOS unstable

## Flatpak version
1.2.4

## Description of the problem

NixOS doesn't follow the FHS and will often use [`$GDK_PIXBUF_MODULE_FILE`](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Module-Interface.html) to direct applications to the correct cache path (eg. a `gnome-terminal` user will have the variable set).

The sandbox inherits this env var which can cause applications to look for the pixbuf cache in a path outside the sandbox, causing the application to fail (eg. `com.github.fabiocolacio.marker` https://github.com/NixOS/nixpkgs/issues/53441).

## Steps to reproduce

Haven't tested this on another distro, but I'm pretty sure it should reproduce.
```bash
export GDK_PIXBUF_MODULE_FILE=/some/path/not/accessibly/from/sandbox
flatpak run com.github.fabiocolacio.marker
```
The application fails to start:
```
(marker:2): GdkPixbuf-WARNING **: 13:04:24.125: Cannot open pixbuf loader module file '/nix/store/mfwiwwqvmsxqpmhvq61aqivvkaqzc1bm-librsvg-2.42.4/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory
...
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

Would it be reasonable to clear this variable here, the gnome sdk provides the file, so it should probably be preferred to get it from the sandbox anyway?:
https://github.com/flatpak/flatpak/blob/00dfce528326476aa3d9167887b2cefdaec412bd/common/flatpak-run.c#L1226

**Comment by matthiasclasen** [comment]
There's an infinite variety of environment variables that could be set. We can't clear them all. A distribution should not set GDK_PIXBUF_MODULE_FILE

**Comment by hedning** [comment]
Right, I can understand our use-case being a bit niche, no worries :)
