### ISSUE TITLE
Errors not reported from `flatpak install --noninteractive`

### ISSUE THREAD

**Issue by pwithnall** [flatpak/flatpak#2839]
If anything in the `FlatpakTransaction` when running `flatpak install` returns an error, that error won’t be reported when running with `--noninteractive`. `flatpak install` will return a `0` exit status.

For example, if I set `min-free-space=50000MB` (a valid value, but more free space than I have on my system), then run:
```
$ flatpak install --user --noninteractive org.octave.Octave
Installing runtime/org.kde.Sdk/x86_64/5.12
$ echo $?
0
$ flatpak run org.octave.Octave
error: app/org.octave.Octave/x86_64/master not installed
```

If you run without `--noninteractive`, the error is correctly reported:
```
$ flatpak install --user flathub org.octave.Octave
…
error: Failed to install org.octave.Octave: min-free-space-size 50000MB would be exceeded
```

The problem is that `FlatpakQuietTransaction` doesn’t implement the `operation_error` vfunc, so `flatpak_transaction_run()` ends up returning `FLATPAK_ERROR_ABORTED` — but
 `flatpak-builtin-install.c` explicitly squashes `FLATPAK_ERROR_ABORTED` errors, since it expects `FlatpakCliTransaction` to have already printed any relevant error.

The fix is to either not squash `FLATPAK_ERROR_ABORTED` when using `FlatpakQuietTransaction`, or implement `operation_error` in `FlatpakQuietTransaction`. I’m afraid I don’t have time to do either of those at the moment.

This is likely a problem with other builtin commands which use `FlatpakQuietTransaction`, but I’ve only tested with `flatpak install`.

This is with flatpak `0b20f3d4` (a recentish git master).

**Comment by mwleeds** [comment]
When this is fixed, I believe https://github.com/flatpak/flatpak/issues/2757 will also be fixed because a `FlatpakQuietTransaction` is used there.
