### ISSUE TITLE
--share=network build-arg not passed to shell-type source entries

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#284]
When building Mono from git, either an existing C# compiler needs to be in $PATH, or the "get-monolite-latest" Make target needs to be called, which downloads a bootstrap compiler.

It appears that whilst the main builds have network access when setting 
```
    "build-options" : {
        "build-args": [
            "--share=network"
        ]
    }
```
the same is not true for
```
            "sources": [
                {
                    "type": "shell",
                    "commands": [ "./autogen.sh",
                                  "make get-monolite-latest"
                    ]
                }
            ]
```

**Comment by alexlarsson** [comment]
Latest master has a fix for this. Although doing things this way kinda neuters a lot of the nice things flatpak-builder gives you like download cacheing and verification.
