### ISSUE TITLE
configure complains about the lack of libpcap, even if it is installed

### ISSUE THREAD

**Issue by wellinton-capixaba** [flatpak/flatpak#2845]
Hello to all, I am currently trying to compile it from the source with: 

 "./configure PKG_CONFIG_PATH=/media/34GB/Arquivos-de-Programas-Linux/Libpcap-1.9.0/lib/pkgconfig/" . Done that, it complains with "checking for cap_from_text in -lcap... no
configure: error: *** libcap needed by bubblewrap but not found"

The same happens if I create sym links to /usr/local/lib and run ldconfig or if I try to set "LDFLAGS=-L/media/34GB/Arquivos-de-Programas-Linux/Libpcap-1.9.0/lib/"

What I shall do?

**Comment by refi64** [comment]
Have you checked config.log?

**Comment by matthiasclasen** [comment]
libcap != libpcap

**Comment by wellinton-capixaba** [comment]
"libcap != libpcap". Well, the first thing duckduckgo showed to me when I entered libcap was this: https://www.tcpdump.org/ 

Would THIS be libcap website: https://directory.fsf.org/wiki/Libcap ?

**Comment by wellinton-capixaba** [comment]
If the library above is the correct one, when trying to compile it, I receive:

cap_file.c: In function ‘cap_get_fd’:
cap_file.c:188: error: ‘XATTR_NAME_CAPS’ undeclared (first use in this function)
cap_file.c:188: error: (Each undeclared identifier is reported only once
cap_file.c:188: error: for each function it appears in.)
cap_file.c: In function ‘cap_get_file’:
cap_file.c:218: error: ‘XATTR_NAME_CAPS’ undeclared (first use in this function)
cap_file.c: In function ‘cap_set_fd’:
cap_file.c:254: error: ‘XATTR_NAME_CAPS’ undeclared (first use in this function)
cap_file.c: In function ‘cap_set_file’:
cap_file.c:286: error: ‘XATTR_NAME_CAPS’ undeclared (first use in this function)
make[1]: *** [cap_file.o] Error 1
make[1]: Leaving directory `/media/34GB/Arquivos-de-Programas-Linux/libcap2-2.24/libcap'
make: *** [all] Error 2

So where is this "XATTR_NAME_CAPS" defined and where I can get it?

**Comment by mwleeds** [comment]
Any reason not to just use a linux distrubition that has already packaged the dependencies of flatpak? You didn't mention which you're on.

**Comment by alexlarsson** [comment]
XATTR_NAME_CAPS is defined in the kernel headers.

**Comment by alexlarsson** [comment]
/usr/include/linux/xattr.h on my system

**Comment by wellinton-capixaba** [comment]
I still new help with it. My xattr.h file  is only this:

#ifndef _LINUX_XATTR_H
#define _LINUX_XATTR_H

#define XATTR_CREATE	0x1	/* set value, fail if attr already exists */
#define XATTR_REPLACE	0x2	/* set value, fail if attr does not exist */

#endif

What I shall do?

**Comment by willypedroso** [comment]
I'm having this exact same problem now in 2022 trying to install flatpak 1.14.1.

After the ./configure command I get this "libcap needed" error.

How did you fix it?

**Comment by 2ndBillGates** [comment]
> I'm having this exact same problem now in 2022 trying to install flatpak 1.14.1.
> 
> After the ./configure command I get this "libcap needed" error.
> 
> How did you fix it?

want to know as well
