### ISSUE TITLE
Provide tool for Arch linux that will use Pacman to create flapaks

### ISSUE THREAD

**Issue by nycnikato** [flatpak/flatpak#2851]
Perhaps a plugin called Archpak

We have Arch Linux, an OS where everything is built from scratch and complied and people routinely package apps into AUR . Why couldn't we use this paradigm to produce flatpaks?  Of course the plugin would download any pre-compiled binaries and use them in packaging the flatpak. Also the tool would produce standalone  self-contained flatpaks, not just flatpakrefs.. Flatpakrefs would be uploaded into flathub or some similar repository.  The idea would mean that virtually any software that is in AUR now could be recompiled into flatpak. 
Hopefully someone can correct my spelling error:-)

**Comment by refi64** [comment]
Interesting idea (you may want to look at Fedora's Flatpak project for a somewhat similar idea), but it's more on-topic for the mailing list than this bug tracker.

**Comment by matthiasclasen** [comment]
yes
