### ISSUE TITLE
dns resolution failing

### ISSUE THREAD

**Issue by albfan** [flatpak/flatpak#2855]
## Linux distribution and version

arch linux updated 2019/04/24 (today)

## Flatpak version

1.3.2

## Description of the problem

apps under flatpak have no access to network

## Steps to reproduce

```
$ flatpak run --share=network --devel --command=curl org.gnome.Sdk/x86_64/master https://github.com/flatpak/flatpak
curl: (6) Could not resolve host: github.com
```

What can I check to see what's happening? config, strace. For everybody that is working so it must be my system, but not sure what to check, any ideas?

**Comment by alatiera** [comment]
Could you try to reproduce with other runtimes as well? org.freedesktop.Platform//1.6 and //18.08 would be good sample.

**Comment by albfan** [comment]
It happens in all them. Seems related with dns resolution:

```
$ curl -s https://github.com/flatpak/flatpak | head
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

$ ping -c1 github.com
PING github.com (140.82.118.4) 56(84) bytes of data.
--- github.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

$ curl https://140.82.118.4/flatpak/flatpak
curl: (60) SSL: no alternative certificate subject name matches target host name '140.82.118.4'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

$ flatpak run --share=network --devel --command=curl org.gnome.Sdk/x86_64/master https://github.com/flatpak/flatpak
curl: (6) Could not resolve host: github.com

$ flatpak run --share=network --devel --command=curl org.gnome.Sdk/x86_64/master https://140.82.118.4/flatpak/flatpak
curl: (60) SSL: certificate subject name (github.com) does not match target host name '140.82.118.4'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

not sure what to check about dns

**Comment by alexlarsson** [comment]
Unfortunately we don't have a lot of network debugging tools in the sdk.
What does `flatpak run --share=network --devel --command=python3 org.gnome.Sdk/x86_64/master -c 'import socket; print(socket.gethostbyname_ex("github.com"))'` print?

**Comment by albfan** [comment]
```
$ flatpak run --share=network --devel --command=python3 org.gnome.Sdk/x86_64/master -c 'import socket; print(socket.gethostbyname_ex("github.com"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

I'm not aware of any dns trace tool, but I can build a flatpak app just for this if you have any recommendation. (or any other network tool, or install on host and run from flatpak)

**Comment by alexlarsson** [comment]
Well, there is `dig'. Maybe you can even try running the host copy. If you're lucky its abi compat with the runtime.

**Comment by alexlarsson** [comment]
Another option is: `flatpak run --share=network --devel --command=strace org.gnome.Sdk/x86_64/master -y python3 -c 'import socket; print(socket.gethostbyname_ex("github.com"))'` which might give a hint

**Comment by albfan** [comment]
Let's go wild:

strace python3 -c 'import socket; print(socket.gethostbyname_ex("github.com"))' &> host_strace.log
flatpak run --share=network --devel --command=strace org.gnome.Sdk/x86_64/master -y python3 -c 'import socket; print(socket.gethostbyname_ex("github.com"))' &> flatpak_strace.log

[flatpak_strace.log](https://github.com/flatpak/flatpak/files/3117182/flatpak_strace.log)
[host_strace.log](https://github.com/flatpak/flatpak/files/3117183/host_strace.log)

Seems there's some difference reading /etc/resolv.conf (not really sure)

**Comment by alexlarsson** [comment]
The resolv.conf differences are immaterial. However, the flatpak strace seems to do a dns lookup to a local caching resolver at 127.0.0.1 (libnss_dns), while the host side seems to use some dbus resolver call (libnss_resolve?).

I guess this is because we're not picking up the host nss config. Unclear why the dns lookup fails though.

**Comment by albfan** [comment]
Looking into forked process, and using curl for a different app check:

```
flatpak  --share=network --devel run --command=strace org.gnome.Sdk/x86_64/master -yf curl github.com  &> flatpak_curl.log
strace -yf curl github.com  &> host_curl.log
```

I can upload strace with forks for python3 if that's interesting

[host_curl.log](https://github.com/flatpak/flatpak/files/3117699/host_curl.log)
[flatpak_curl.log](https://github.com/flatpak/flatpak/files/3117700/flatpak_curl.log)

**Comment by alexlarsson** [comment]
Same there. On the host is uses systemd-resolved dbus apis to do the lookups, whereas in the sandbox it does dns connections to 127.0.0.1:53, which is failing for some reason. Maybe there is some host issue with the caching nameserver. 

Can you try curl on the host if you remove "resolve" from hosts: in /etc/nsswitch.conf ? That should make them use the same method.

**Comment by albfan** [comment]
Yes. Removing resolve from /etc/nsswitch.conf makes it fail on host too:

removed:

```
$ cat /etc/nsswitch.conf 
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files mymachines systemd
group: files mymachines systemd
shadow: files

publickey: files

hosts: files mymachines myhostname [!UNAVAIL=return] dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files

$ curl github.com
curl: (6) Could not resolve host: github.com
```

With it:
```
$ cat /etc/nsswitch.conf 
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files mymachines systemd
group: files mymachines systemd
shadow: files

publickey: files

hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
$ curl github.com
# no error output
```

Adding  `--system-talk-name=org.freedesktop.resolve1` doesn't make a difference

**Comment by refi64** [comment]
Did you symlink your resolv.conf, or is it still using NetworkManager's? If symlinked, does it point to the resolved-generated stub-resolv.conf or resolv.conf? If the former, try changing it to `/run/systemd/resolve/resolv.conf`.

That being said this is still rather odd, because I also use resolved with Flatpak without any issues.

**Comment by albfan** [comment]
```
$ la /etc/resolv.conf 
lrwxrwxrwx 1 root root 35 feb 25 18:00 /etc/resolv.conf -> /var/run/NetworkManager/resolv.conf

$ cat /etc/resolv.conf 
# Generated by NetworkManager
search home
nameserver 127.0.0.1

$ la /run/systemd/resolve/resolv.conf 
-rw-r--r-- 1 systemd-resolve systemd-resolve 621 abr 27 10:42 /run/systemd/resolve/resolv.conf

$ cat /run/systemd/resolve/resolv.conf 
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.1
nameserver 192.168.1.1
search home
```

192.168.1.1 is my router, so that's why it resolve dns.

On flatpak it only access localhost

```
$ flatpak --share=network run --command=bash --devel org.gnome.Sdk/x86_64/master
[📦 org.gnome.Sdk ~]$ find / -name resolv.conf 2>-
/etc/resolv.conf
/run/host/monitor/resolv.conf
/usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/etc/resolv.conf
/usr/lib/x86_64-linux-gnu/ffmpeg/etc/resolv.conf
/usr/etc/resolv.conf

[📦 org.gnome.Sdk ~]$ ls -la /etc/resolv.conf
lrwxrwxrwx 1 alberto alberto 29 abr 27 11:09 /etc/resolv.conf -> /run/host/monitor/resolv.conf

[📦 org.gnome.Sdk ~]$ cat /run/host/monitor/resolv.conf 
# Generated by NetworkManager
search home
nameserver 127.0.0.1

[📦 org.gnome.Sdk ~]$ cat /usr/etc/resolv.conf 
# Generated by NetworkManager
search home
nameserver 127.0.0.1
```

I manually added 

nameserver 192.168.1.1

to `/etc/resolv.conf` or `/var/run/NetworkManager/resolv.conf` and all works again.

Hope this is not only my case but something to take care from flatpak (like it is not relying on same resolv.conf like host) But really don't know.

**Comment by sequencerr** [comment]
Hello, I have same issue inside(only) `flatpak-builder`/`org.flatpak.Builder` on Debian machine host. 100% giving `Failed to resolve 'services.gradle.org' (Temporary failure in name resolution)`/`Exception in thread "main" java.net.UnknownHostException: services.gradle.org`. Rarely it even fails with `github.com` on recipe `sources:
          - type: git`. I tried google dns `8.8.8.8, 8.8.4.4, apt install resolvconf, sudo resolvconf -u`, `sudo service NetworkManager restart`, cloudflare warp. Didn't help.

offtopic: for some reason `org.flatpak.Builder` takes 1+ min to start printing at least something.

related: https://github.com/flatpak/flatpak/issues/4263
https://unix.stackexchange.com/questions/39071/debian-problem-with-dns
https://stackoverflow.com/questions/41099217/flatpak-error-pulling-runtime-org-freedesktop-platform
https://wiki.debian.org/NetworkManager
https://developers.cloudflare.com/warp-client/get-started/linux/

**Comment by hfiguiere** [comment]
1. don't post on closed issues
2. if you re-read the documentation you will learn that the build is offline. Which is exactly what is happening.
