### ISSUE TITLE
A slow Flatpak download, can slow down everything (parallel downloads)

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#2866]
For some reason the WPS Office is always extremely slow from Flathub https://github.com/flathub/com.wps.Office/issues/32

![Screenshot from 2019-04-29 16-02-45](https://user-images.githubusercontent.com/11244308/56899030-19fd0c00-6a9b-11e9-9ae7-149256b9c547.png)

The result is that everything is waiting back, till WPS finishes

Flatpak: 1.2.4

**Comment by refi64** [comment]
I will admit parallel downloading would be nice, but it might make the Flathub hammering worse short term, and the downloading is usually paired with a deploy which probably shouldn't be done in parallel unless you want your disk I/O to skyrocket.

**Comment by clopez** [comment]
> For some reason the WPS Office is always extremely slow from Flathub [flathub/com.wps.Office#32](https://github.com/flathub/com.wps.Office/issues/32)

I guess the reason are all the `org.gnome.*` layer downloads.

They are also slow for me. Never managed to get them to download at more than 0.5 Mbytes/sec (on a connection able to pull more than 100mbps).

In contrast other layers like `org.freedesktop.*` ones are much faster.

Supporting parallel downloads would be nice.

**Comment by mwleeds** [comment]
Please re-open if you still see this with Flatpak 1.6.2

**Comment by mpfaff** [comment]
Can you reopen this issue?

**Comment by fusate** [comment]
I'm also experiencing this issue, most downloads are running at roughly 100kB/s for me.  Let me know if I can help with debugging anything.  I'm using flatpak 1.12.7-1 from arch.
