### ISSUE TITLE
Several games custom cursor themes are broken in X11 but not Wayland

### ISSUE THREAD

**Issue by FurtiveDolus** [flatpak/flatpak#2868]
## Run Wesnoth, 0AD or OpenMW in Gnome X11 and Wayland sessions. The theme will work in Wayland but not X11.
![56103136-c87b4b80-5ef6-11e9-97b8-b9a9e9165366](https://user-images.githubusercontent.com/49626275/56946817-e056f000-6af0-11e9-987e-34385651b26d.png)

**Comment by DarkArc** [comment]
Noting, this is consistent behavior with using `SDL_CreateCursor` instead of `SDL_CreateColorCursor`; this might be helpful. I'm not sure what kind of proxying/sandboxing flatpak does between the sandbox and the display buffer (appears to be at least some).

**Comment by DarkArc** [comment]
There doesn't seem to be a lot to the flatpak display forwarding for X11, so this is strange. I wonder if this is actually an X11 bug, an interesting thing to test would be running a game over an SSH forward, and seeing if the same situation occurs.

**Comment by DarkArc** [comment]
Curiously Xonotic is unaffected, though perhaps they're not actually setting the cursor in X but rendering their own mouse cursor.

**Comment by DarkArc** [comment]
Can confirm Wesnoth is using `SDL_CreateColorCursor` for its cursor creation.

`SDL_CreateColorCursor` internally under X11 uses:

```
#if SDL_VIDEO_DRIVER_X11_XCURSOR
        if (SDL_X11_HAVE_XCURSOR) {
            x11_cursor = X11_CreateXCursorCursor(surface, hot_x, hot_y);
        }
#endif
        if (x11_cursor == None) {
            x11_cursor = X11_CreatePixmapCursor(surface, hot_x, hot_y);
        }
```

This might actually be an issue with the SDL builds in the runtime not having `SDL_VIDEO_DRIVER_X11_XCURSOR` configured correctly. Both RuneScape & Wesnoth use dynamically linked SD per `ldd`.

Xonotic does not seem to create its mouse cursor via `SDL_CreateColorCursor` searching through its source via `rg CreateColorCursor`.

**Comment by DarkArc** [comment]
I've opened an issue on the freedesktop gitlab to pass this information along to (hopefully) the right people https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1188.

**Comment by nanonyme** [comment]
Does this also affect XWayland?

**Comment by DarkArc** [comment]
In my testing, it did, but I'm on KDE under nvidia so my results could be skewed by that WRT wayland.

**Comment by DarkArc** [comment]
![image](https://user-images.githubusercontent.com/778012/107172643-da639380-6993-11eb-938a-c0cf36c78d28.png)
This has been fixed upstream by https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/4342 this can be closed :) 

It is sufficient for users to update to freedesktop-platform 20.08.4 which contains the fix.

**Comment by psi29a** [comment]
Has this been revalidated against 0.47? Could have been resolved by recent bump in SDL verison.

**Comment by DarkArc** [comment]
@psi29a see my comments above, I have no idea why this hasn't been closed yet.
