### ISSUE TITLE
Library translations searched in wrong place

### ISSUE THREAD

**Issue by gkarsay** [flatpak/flatpak#2879]
## Linux distribution and version
Debian unstable (currently frozen in preparation for release of Debian 10 "Buster")

## Flatpak version
Flatpak 1.2.4
(Debian package version: 1.2.4-1)

## Description of the problem
It seems like flatpak-builder doesn't propagate the right gettext paths for libraries and gettext can't find the translation file.

I've got an app with a module that builds a shared library and an executable (app), both with their own translations. This works in a normal environment but not as a flatpak. The translation (.mo file) is installed in `/app/share/locale/...` but gettext is searching for it in `/usr/share/locale/...`. I *guess* this is flatpak-builder's fault. I get the same behaviour with GNOME runtimes 3.28, 3.30 and 3.32.

This used to work with an earlier version which I released in August 2018. I don't know the flatpak version anymore and the build system has changed meanwhile, now it's Meson instead of Autotools. 

## Steps to reproduce
I experienced this with my app Parlatype and reported it there as https://github.com/flathub/com.github.gkarsay.parlatype/issues/4

Copy & paste from there:

1) Make sure you have a locale other than C/English enabled. Parlatype is currently fully translated to German and Polish, others partially. To enable them both do this or adjust the command accordingly:
```
$ flatpak config --user --set languages "de;pl"
``` 
If the locale wasn't enabled before, you probably have to reinstall Parlatype.

2) Install Parlatype (com.github.gkarsay.parlatype) and run with this command:
```
$ flatpak run --env=LC_ALL=de_DE.utf8 com.github.gkarsay.parlatype xx
``` 
`xx` is a non-existent file.
* Expected result: A localized error message should pop up.
* Actual result: English error message "File not found: xx" pops up. Note that the app's interface is localized, just the error message (from the library) isn't.

## Other notes

The problem is that gettext is searching at the wrong place (I used strace to confirm this). It is a single module that is building the shared library and the app, maybe that's the problem. The build system Meson is invoked with standard i18n module like this: `i18n.gettext(gettext_package_lib, preset: 'glib')`, see https://github.com/gkarsay/parlatype/blob/v1.6/libparlatype/po/meson.build

flatpak-builder installs both translation files in `/app/share/locale/...`. Gettext finds the translation for the app, but not for the library.

**Comment by alexlarsson** [comment]
This is not how gettext work. The app is supposed to call bindtextdomain() to the location of its translations (i.e. the prefix its being built with).

See https://www.gnu.org/software/gettext/FAQ.html in the "How do I make use of gettext() in my package?" section for some sample code.

**Comment by alexlarsson** [comment]
Well, the thing that needs to call bindtextdomain() seems to be the library, not the app.

**Comment by gkarsay** [comment]
Thank you very much! I wasn't aware that libraries need to call bindtextdomain, too. Probably because it worked for me without this call with `/usr` and `/usr/local` prefixes.
