### ISSUE TITLE
misleading/incomplete error messages & man page from `flatpak enter`

### ISSUE THREAD

**Issue by skierpage** [flatpak/flatpak#2881]
Fedora 30
Flatpak version 1.2.4

As [issue 855 comment](https://github.com/flatpak/flatpak/issues/855#issuecomment-450595970) remarks, you need to use `sudo -E` to get `flatpak enter` to work.

## Steps to reproduce
Run a flatpak binary, then use`flatpak ps` to get its Instance ID, e.g. _942060682_. Then try to get `flatpak enter` to work.
``` lang=bash
$ flatpak enter 942060682 ls
Not running as root, may be unable to enter namespace
error: Can't chroot
```
OK, try `sudo`
``` lang=bash
$ sudo flatpak enter 942060682 ls
error: 942060682 is neither a pid nor an application or instance ID
```
But it is an instance ID! Unless you find the comment 
> Grr. This is rather stupid. Try with sudo -E. It turns out we rely on XDG_RUNTIME_DIR to find the list of instances we iterate over

you may never figure out what to do. `man flatpak-enter` says
>    This command requires extra privileges, so must be run as root or via
>     e.g. sudo. To get TAB completion for the application ID, use sudo -E.

which hints at the solution but makes it sound optional when `sudo -E`or something similar seems to be required. (It's also required to use a pid from `flatpak ps` as the INSTANCE argument to `flatpak run`.)

## Suggested fix
1. Change the error message "Not running as root, may be unable to enter namespace" to "Not running as root, may be unable to enter namespace (try sudo -E)"

2. If possible improve the error message when running as root without access to user's environment, maybe issue "warning: no XDG_RUNTIME_DIR found" before the error?

3. Improve flatpak-enter(1), something like "... must be run as root or via e.g. sudo -E . It relies on XDG_RUNTIME_DIR from the user's environment to find application instances and PIDs."

Having got `flatpak enter` to work, I'm still not sure what it does :wink:

**Comment by mwleeds** [comment]
> Having got `flatpak enter` to work, I'm still not sure what it does

The man page seems pretty clear on this part. `flatpak enter` runs the specified command in the same environment (same view of the filesystem, etc.) as the running application, and if the command is a shell, you get a shell in the application's environment.

**Comment by muelli** [comment]
similarly, `--help` currently says:

```
➜ ~>flatpak enter --help
Usage:
  flatpak enter [OPTION…] INSTANCE [COMMAND [ARGUMENT…]] - Run a command inside a running sandbox

Help Options:
  -h, --help           Show help options

Application Options:
  -v, --verbose        Show debug information, -vv for more detail
  --ostree-verbose     Show OSTree debug information

➜ ~>

```
but the command does not seem to be optional.

**Comment by btreut** [comment]
it kind of works for me if I enter it as `sudo env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR flatpak enter pid /bin/bash` with `pid` found in second collumn of `flatpak ps`. This starts an instance of bash with an error message that it can't find ls. Digging a bit in the bash reveals that a nonsense PATH variable is set to /app/bin:/usr/bin. I can't find a directory /app. I also don't know which rc file contains the call to ls, which cannot be found. If I manually set the PATH to something reasonable the bash instance appears to be usable.

**Comment by skierpage** [comment]
> it kind of works for me if I enter it as `sudo env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR flatpak enter pid /bin/bash` with `pid` found in second collumn of `flatpak ps`. This starts an instance of bash with an error message that it can't find ls.

For what it's worth I don't get that error.

> Digging a bit in the bash reveals that a nonsense PATH variable is set to /app/bin:/usr/bin. I can't find a directory /app. I also don't know which rc file contains the call to ls, which cannot be found. If I manually set the PATH to something reasonable the bash instance appears to be usable.

Flatpak apps run in a sandbox with a very different filesystem, see [the Sandbox wiki page](https://github.com/flatpak/flatpak/wiki/Sandbox), so the "nonsense PATH" is intentional. However, `flatpak enter` doesn't properly switch (chroot? pivot?) to this sandbox, this is probably issue #3059.

**Comment by matthiasclasen** [comment]
This has recently been improved, and flatpak enter should work without sudo now (most of the time).
