### ISSUE TITLE
Flatpak installation uses 100% of CPU in revokefs-fuse

### ISSUE THREAD

**Issue by create3000** [flatpak/flatpak#2882]
## Linux distribution and version
Ubuntu 19.04
15,6 GiB
Intel® Core™ i5-4460 CPU @ 3.20GHz × 4 

## Flatpak version
Flatpak 1.2.4

## Description of the problem
If I run a flatpak, for instance Gimp or VS Code, or other the CPU is at 100% and the whole system stucks. There are some seconds where the system becomes responsive, the last chance to kill the flatpak, then it takes a few seconds and the CPU is low again.

The problem occures only on my working system, see above. On a naked older computer, flatpak runs fine.

**Comment by mwleeds** [comment]
Posting the output of `top` when this occurs might be a place to start (perhaps by sshing into the computer).

**Comment by create3000** [comment]
I have started Glade and VSCode, looking at the top log I can see that a lot of processes like Gimp, Firefox, or Guake, and others, consume CPU, they don't if the system is idle.

[logs.zip](https://github.com/flatpak/flatpak/files/3156025/logs.zip)

**Comment by alexlarsson** [comment]
Tracker seems to be using a lot of CPU. I wonder if it is trying to index the ~/.local/share/flatpak directory. Do you install the flatpaks system-wide or per user?

**Comment by create3000** [comment]
I always install flatpaks per user, because I often update my system. The home directory is on a separate partition, this makes the update process quick and easy.

**Comment by mwleeds** [comment]
I would recommend filing an issue about this here: https://gitlab.gnome.org/GNOME/tracker/issues

**Comment by matthiasclasen** [comment]
from irc:

```
garnacho: hmm, tracker does not index $HOME recursively, and skips hidden files/dirs regardless. I think it's a wrong cause/effect attribution, or some misconfiguration
```

**Comment by fikrillah** [comment]
got this on my thinkpad yoga 260
![Screenshot from 2019-10-10 23-02-56](https://user-images.githubusercontent.com/48489341/66586093-42447700-ebb2-11e9-9929-ee5c7293f156.png)

**Comment by fikrillah** [comment]
the cpu goes 100% when installing a software, since it takes forever, it feels like cpu goes 100% till reboot

**Comment by rusins** [comment]
Experiencing the same issue all of a sudden, I remember I used flatpak a few days ago to install and uninstall some markdown editors, as well as run an upgrade. Running Arch Linux, Flatpak 1.5.0.
```
top - 15:00:35 up 7 days, 40 min,  1 user,  load average: 14.72, 15.22, 15.24
Tasks: 319 total,  15 running, 303 sleeping,   0 stopped,   1 zombie
%Cpu(s): 42.3 us, 57.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15731.8 total,   4381.9 free,   6879.6 used,   4470.3 buff/cache
MiB Swap:  16384.0 total,  14534.4 free,   1849.6 used.   6650.3 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1186109 flatpak   20   0    4372    124      0 R  70.6   0.0 167:44.87 revokefs-fuse
1186167 flatpak   20   0    4372    248    120 R  70.6   0.0 167:21.70 revokefs-fuse
1186042 flatpak   20   0    4372    172     48 R  64.7   0.0 167:49.48 revokefs-fuse
1186023 flatpak   20   0    4372    224     96 R  58.8   0.0 168:00.57 revokefs-fuse
1186088 flatpak   20   0    4372    236    108 R  52.9   0.0 168:39.01 revokefs-fuse
1186127 flatpak   20   0    4372    232    104 R  52.9   0.0 168:03.79 revokefs-fuse
1186147 flatpak   20   0    4372    200     72 R  52.9   0.0 168:10.85 revokefs-fuse
1186024 flatpak   20   0    4372    176     52 R  47.1   0.0 169:49.96 revokefs-fuse
1186063 flatpak   20   0    4372    212     92 R  47.1   0.0 168:42.84 revokefs-fuse
1186075 flatpak   20   0    4372    208     84 R  47.1   0.0 168:12.96 revokefs-fuse
1186096 flatpak   20   0    4372    224    104 R  47.1   0.0 169:08.47 revokefs-fuse
1186139 flatpak   20   0    4372    232    108 R  35.3   0.0 168:06.49 revokefs-fuse
1186173 flatpak   20   0    4372    180     56 R  35.3   0.0 168:47.56 revokefs-fuse
```

**Comment by mwleeds** [comment]
Would be great if anyone who can reproduce this could install debug symbols, gdb attach to the process, and get a backtrace (`thread apply all bt`).

**Comment by fikrillah** [comment]
i'll try that this weekend...

**Comment by fikrillah** [comment]
anyway, anyone know if there's pre-complied packages with debug symbol in archlinux?

**Comment by refi64** [comment]
Afaik no, you need to build the relevant packages yourself:
https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

**Comment by fikrillah** [comment]
couldn't reproduce it under gdb, since the bug appears only on normal user (without sudo)

**Comment by mwleeds** [comment]
You shouldn't need sudo to run `gdb --args flatpak run org.gimp.GIMP`

**Comment by fikrillah** [comment]
ok, i actually haven't done yet, but i think it's worth mentioning that the bug does not appear when installing an app with sudo. the bug appears only when installing an app with normal user...

**Comment by mwleeds** [comment]
Right, that makes sense, the revokefs filesystem is not used by Flatpak when Flatpak is run as root.

**Comment by mwleeds** [comment]
I guess it's the `flatpak install` command you want to run under gdb, not `flatpak run`, since revokefs is used during the installation.

**Comment by fikrillah** [comment]
i don't know if  this log has usefull information, but i tried compiling flatpak and glibc with debugging option, tell me if i miss something... 
[trace6.log](https://github.com/flatpak/flatpak/files/3747456/trace6.log)

**Comment by mwleeds** [comment]
That log just shows threads being spawned. To get a useful backtrace you'd have to gdb attach to the `revokefs` process while it's using 100% of the CPU:
```
gdb --pid=`pidof revokefs-fuse`
```
And then run `thread apply all bt`

**Comment by fikrillah** [comment]
how about this? i copied the output from terminal
[8.log](https://github.com/flatpak/flatpak/files/3747472/8.log)

**Comment by mwleeds** [comment]
Yeah that might be helpful. I don't know enough about the revokefs to diagnose the issue immediately.

**Comment by camilojm27** [comment]
Hi i have the same problem in archlinux so here is my debug, and your are right only appears when i install apps without sudo
[revokefs-fuse.log.txt](https://github.com/flatpak/flatpak/files/3762444/revokefs-fuse.log.txt)

**Comment by wjt** [comment]
It's busylooping here:

```
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
```

fd 4 is the `--exit-with-fd=4` parameter.

**Comment by jbob** [comment]
> It's busylooping here:
> 
> ```
> poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
> ```
> 
> fd 4 is the `--exit-with-fd=4` parameter.

Same for me, but I observe the behavior after the PC was in standby. `systemctl restart flatpak-system-helper` fixes it without restarting.

**Comment by RyanMarcus** [comment]
Like jbob, this happened on my X1 carbon during standby. Restarting the `flatpak-system-helper` service also temporarily fixes the issue.

**Comment by wjt** [comment]
This regressed in d91660fe2a4a508479be922140b112e7e8809180 – if I revert the two hunks of that patch which touch the revokefs code, the problem goes away. I have a fix.
