### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by orschiro** [flatpak/flatpak#2887]
As per [this comment](https://github.com/flatpak/flatpak/issues/1857#issuecomment-490283107), I would like to suggest support for a config file, for example stored in `~/.config`, for the user to store his settings, such as `assumeyes` on update. 

Anyone else in favour of this?

Regards

**Comment by matthiasclasen** [comment]
I'm not in favor of that. It only makes the behavior of the tool hard to predict.

If --assumeyes is too much to type, I suggest a shell wrapper

**Comment by orschiro** [comment]
That's a fair point. But then in general, why do programs have a config file at all?

Wouldn't that same argument apply to any other software out there?

**Comment by alexlarsson** [comment]
command line applications generally don't have config files, because they are used in shells and all sort of places where you expect the behaviour to be the same each time, not vary depending on what user is running it.
