### ISSUE TITLE
Allow specifying runtime extensions with "flatpak run"

### ISSUE THREAD

**Issue by MayeulC** [flatpak/flatpak#2889]
* Linux distribution and version: Arch Linux
* Flatpak version: 1.3.3

## Description of the problem
I downloaded the Android studio flatpak. However, I would like to be able to use my system's `flutter` executable at runtime (I could later work towards providing a `flutter` extension for this flatpak, if I correctly understood the extension mechanism).

It looks like `flutter` requires multilib, as shown with `flutter doctor` (the following in launched from within the android studio flatpak):
```
sh-4.4$ /opt/flutter/bin/flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, v1.2.1, on Linux, locale fr_FR.UTF-8)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5 (you need to enable multilib: https://wiki.archlinux.org/index.php/Official_repositories#multilib)
```

## Proposed solution
~~Not everyone will need that support within this flatpak, therefore I don't think it is a good idea to change the recipe with something like https://github.com/flathub/com.valvesoftware.Steam/blob/96fd4610c22154091905881ac1cdd1f5d5f2da08/com.valvesoftware.Steam.yml#L44-L64~~ (I now understand the issue better, and the extensions seem optional, so that's likely the way forward. However, the issue still stands, to help with debugging).

Instead, I would like to see a way to add runtimes or extensions "at runtime".

a command like `flatpak run --add-extension=org.freedesktop.Platform.Compat.i386,directory=lib/i386-linux-gnu` would probably solve the issue.

**Comment by TingPing** [comment]
The application defines what extension points it supports. It isn't up to the user to start shoving random things in.

**Comment by alexlarsson** [comment]
Yeah, this is a misunderstanding of how things work. Things that expect something to be plugged in at some place have to define that, as well as the exact ABI requirements the pluging should support. Its not about shoving random files into an app.

**Comment by MayeulC** [comment]
Maybe specifying "runtime extensions" was due to a misunderstanding on my part. The idea here is to debug a flatpak-related issue before adjusting the flatpak build process. I added the original context if that makes it clearer.
