### ISSUE TITLE
[RFE] Make debugging easier, e.g. by adding a `debug` command

### ISSUE THREAD

**Issue by genodeftest** [flatpak/flatpak#289]
I'm running into an issue where the flatpak build of Gitg fails to start and I don't know whom to blame or where to start debugging. See https://bugzilla.gnome.org/show_bug.cgi?id=770483 for a report against Gitg. The developer stated it is not a Gitg issue, so it should be somewhere in flatpak, but where?

I tried starting flatpak in gdb, but this is hard to get right:
No matter whether I set `follow-fork-mode child` or `follow-fork-mode parent`, I cannot attach to the Gitg process. I cannot attach to it manually after starting from flatpak because it crashes before I have a chance to do so. How about adding a `debug` command which runs the flatpak application inside gdb instead of directly?

Running `flatpak debug org.gnome.Gitg` would then create this process tree:
```
flatpak
  → gdb
      → Gitg
```

This is the way e.g. cargo (the Rust package manager) works, also how startup scripts for Firefox and LibreOffice no Fedora are patched to make debugging possible albeit the multi-process architecture.

**Comment by matthiasclasen** [comment]
Here is how it currently works:

flatpak run -d --command=sh
gdb gitg

**Comment by genodeftest** [comment]
…after running `flatpak --user install gnome-nightly org.gnome.Sdk` … 
Thanks!

**Comment by genodeftest** [comment]
Can you please add this info to the man page and/or website?

**Comment by alexlarsson** [comment]
We should have a "tips and tricks" page on the wiki or something.

**Comment by genodeftest** [comment]
> We should have a "tips and tricks" page on the wiki or something.

Done: https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks

I'd prefer a man page (or something else shipped to the user) though.

**Comment by alexlarsson** [comment]
"-d" is listed on "man flatpak-run" though. Its just that reading a lot of manpages is seldom a good way to find good tricks.

**Comment by genodeftest** [comment]
> "-d" is listed on "man flatpak-run" though. Its just that reading a lot of manpages is seldom a good way to find good tricks.

Thanks for the hint. `man flatpak` and `/debug[Enter]` just didn't work. Sorry for the noise.

**Comment by albfan** [comment]
I can run gdb inside flatpak but cannot launch a remote debug since there's no gdbserver. Any chances to add it? Should I open an issue about that? I want people using builder to debug its flatpak apps

**Comment by albfan** [comment]
Seems builder is designed to support that out of the box. No need for a gdbserver
