### ISSUE TITLE
flatpak dbus security

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#2893]
According to flatpak documentation an application should be only able to access the dbus matching the application. The permissions often include --share-ipc 
Is this the option for unlimited dbus access? The description in the documentation was not clear to me.
http://docs.flatpak.org/en/latest/sandbox-permissions.html

I'm running Wayland.

**Comment by matthiasclasen** [comment]
No, --share-ipc is about sharing the kernel ipc namespace with the host system. That is necessary to use shared memory between host and sandbox processes, which is needed for X. It does not affect the D-Bus access.
