### ISSUE TITLE
[UX] Flatpak update should show version information (from which to which version)

### ISSUE THREAD

**Issue by rugk** [flatpak/flatpak#2901]
## Linux distribution and version
Fedora 30

## Description of the problem

`flatpak update` currently:
```sh
 1.	   	io.atom.Atom	x86_64	stable	atom2-origin	< 144,9 MB
 2.	   	org.mozilla.FirefoxDevEdition	x86_64	master	org.mozilla.FirefoxRepo	< 79,6 MB
 3.	   	org.mozilla.FirefoxDevEdition.Locale	x86_64	master	org.mozilla.FirefoxRepo	< 1,7 MB (partial)

Proceed with these changes to the Default system installation? [Y/n]: 
```

Even the `--verbose` mode does not show more information.

IMHO, by default, `flatpak update` should show you:
* _at the very least_ the version it's updating a package **to**
* IMHO also the old version it's updating a flatpak **from**

**User story:** I, as a user, want to see what updates that command will actually do, because I may have third-party information ("a new version of X is out", "do not upgrade to Y, it's broken!") and thus want to verify _prior to installation_ whether I should/can do so.

**Logic:** You ask the user to confirm the actions. They, however, only know what will be updated, not to which version. So there are not really enough information to make an "informed" decision on whether to enter "Y" now.
And yeah, instead of showing the architecture (see https://github.com/flatpak/flatpak/issues/2794), I want version information. I hardly care about the architecture, especially not for an update. (it very likely won't or possibly even can't change during an update)

**Comparison:** Even gnome-software shows this AFAIK, so if a GUI that is trimmed down to not show you too much details, shows you this, the CLI should definitively do so.

## Steps to reproduce
`flatpak update`

**Comment by mwleeds** [comment]
I assume you mean the human readable version, like 3.32.1, as opposed to the ostree commit, like `b5df98cd83d06d97df5bcbd06239699fcd4eebde798d7c311f8db59fc0c55d45`? The latter does show up with `flatpak update -vv`.

At least in some cases the commit might change without a version number change (like a nightly build). I don't know if we'd want to show "updating from 3.32.1 to 3.32.1".

**Comment by rugk** [comment]
Ah, yes, obviously human-readable. A CLI interface is for humans here… :smile: 

> At least in some cases the commit might change without a version number change (like a nightly build).

Fair enough. As said, it would already an achievement IMHO if it would show "updating to 3.32.1". (that always fits/is correct)
Alternatively, if the version number is exactly the same, show a different string, e.g. "3.32.1 – minor update".

**Comment by mwleeds** [comment]
Obviously humans can read ostree commit hashes; it's just a trade-off between friendliness and accuracy. We do already use the commits in `flatpak info`, `flatpak remote-info`, `flatpak update --commit`, etc.

**Comment by matthiasclasen** [comment]
Version numbers are not really a thing that flatpak has. it deals with commits that are identified by hashes.

**Comment by rugk** [comment]
Hmm but the underlying applications do have version numbers.

E.g. if I update Firefox from v70 to v71, I'd like to know this happens. This is needed e.g., because I want to know/look up what things changed (changelog) or see when an update broke my applications, so I can report an upgrade from vX to vY broke things.

**Comment by mwleeds** [comment]
> Version numbers are not really a thing that flatpak has. it deals with commits that are identified by hashes.

Well, the version information is in the appstream data right? So we could show it.

**Comment by matthiasclasen** [comment]
Yes, but it is ancillary information, not a primary thing.

As for reporting breakage, saying that an update from commitA to commitB broke something is actually more useful from the flatpak perspective.
