### ISSUE TITLE
Unused runtimes not uninstalled automatically

### ISSUE THREAD

**Issue by vpodzime** [flatpak/flatpak#2917]
## Linux distribution and version
Fedora 29

## Flatpak version
Flatpak 1.2.4

## Description of the problem
Flatpak is not removing unused runtimes automatically. There is the `--unused` option to the `uninstall` command which can be used to remove unused runtimes (not 100% reliable, see #2718), but if somebody just runs `flatpak install` and then `flatpak update`, unused runtimes stay in the system and take space.

## Steps to reproduce
1. Install an application using Flatpak
2. Keep updating the application and the runtimes it requires
3. After several such updates, run `flatpak uninstall --unused`

## Results
Unused runtimes are present in the system.

## Additional info
I think it's also possible to just install an application, let it pull in the runtimes it requires and then uninstall the application. The no longer needed runtimes will not be uninstalled automatically.

**Comment by vpodzime** [comment]
Just as an example -- on my system, the Flatpak runtimes were consuming over 8 GiB of space and `flatpak uninstall --unused` freed more than 1 GiB. And with the nvidia runtimes removed manually I was able to free additional 3 GiB of space. That's over 50 % of space used for something I didn't need.

And for a comparison -- the rest of my `/` which contains a full Fedora installation takes 8 GiB of space. Quite disappointing to see that two applications installed by Flatpak (Steam and Slack) were in fact occupying the same amount of space.

**Comment by vpodzime** [comment]
Some info from the IRC chat:
> \<vpodzime\> trying to ask again -- is there any explanation why `uninstall --unused` is not happening automatically? I feel like it must have been discussed/explained already.
> \<vidal72[m]\> because it's not always what user want
> \<vpodzime\> defaults should be what most users want

**Comment by mwleeds** [comment]
The idea behind the current behavior is that if you eventually install an application that uses one of the unused runtimes, you won't have to download it again.

I wonder if there's a middle ground where we could uninstall an unused runtime if it has been unused for more than a year or something like that.

**Comment by vpodzime** [comment]
> The idea behind the current behavior is that if you eventually install an application that uses one of the unused runtimes, you won't have to download it again.

I don't think that's a good strategy. Package managers are also not doing this. And especially with old versions of runtimes the chance that some application in the future will require the old version of the runtime is not too high, right?

> I wonder if there's a middle ground where we could uninstall an unused runtime if it has been unused for more than a year or something like that.

Yes, that would be an option. As long as the interval/threshold is configurable. There are certainly cases where re-downloading is more expensive than disk space occupied by something unused. But again, those are not the typical workstation/laptop cases.

**Comment by Erick555** [comment]
> Package managers are also not doing this

Package managers don't remove unused deps automatically. At least not in Arch Linux and Ubuntu/Debian.

**Comment by vpodzime** [comment]
> Package managers don't remove unused deps automatically. At least not in Arch Linux and Ubuntu/Debian.

There are some that do this. But I meant updating -- if some package is updated, the old version of the package is not kept in the system.

**Comment by TingPing** [comment]
- Flatpak has multiple installations (system, user, custom) all which need to be accounted for
- Flatpak runtimes are large and re-downloading them is of bigger consequence than packages

**Comment by vpodzime** [comment]
> * Flatpak has multiple installations (system, user, custom) all which need to be accounted for
> 
> * Flatpak runtimes are large and re-downloading them is of bigger consequence than packages

Good points, thanks for adding them to the discussion. Nevertheless, they are arguments for both sides because multiple installations and big size also mean lots of disk space occupied.

**Comment by TingPing** [comment]
There could be a UI element to this; Like GNOME-Software or flatpak cli could say on uninstall "This package appears to be unused, remove also?"

**Comment by matthiasclasen** [comment]
Yes, we are not going to do this automatically.

**Comment by jkonecny12** [comment]
Then at least state this in a documentation.
It would be good to have the reasons written somewhere.

**Comment by vpodzime** [comment]
Exactly. See my [original question on the IRC](https://github.com/flatpak/flatpak/issues/2917#issuecomment-494833346) -- I just wanted the explanation. But I guess **Yes, we are not going to do this automatically.** is kind of hard to explain and document.

**Comment by digulla** [comment]
I would argue to do this for some packages, for example NVIDIA drivers.

Right now, I have nvidia-390-77, nvidia-390-116 and nvidia-430-34 installed.
The driver used by my kernel is 430.34.
So the 390 drivers are useless AND dangerous. If an app would use them, they wouldn't work because they can't talk to the underlying system anymore.
This just happened with me. I started steam and it wouldn't come up because the GL drivers were outdated.

The hint to run `flatpak update` is the first thing in their FAQ: https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions

I guess this is an issue which comes up often. So for some packages, it would make sense to add "hooks" which can check whether the underlying system is "good enough" and provide pointers how to fix that (for NVIDIA, warn when the driver versions don't match and ask "Can I fix this for you?" or at least provide a link how to fix it).
In this case, I'd also argue that you don't want to remove old versions automatically (the user might be experimenting with driver versions or trying to get a new card working). An warning "We detected these flatpaks which will not work anymore because ... I can update to the latest version and remove the old ones Y/n?"

**Comment by Ultrabenosaurus** [comment]
> For the record the status quo has changed since this issue was closed, and we remove unused end-of-life runtimes automatically, as long as they aren't pinned.

That's not the behaviour I'm seeing, here in the far future. Flatpak has accumulated 10 versions of the nvidia runtime on my PC, and when I try `flatpak uninstall --unused` it lists all my Flatpak apps as being dependent on all 10 of those runtimes! It also updates every single one of those runtimes if there's a single app update available. 

I felt this behaviour was distinct enough from existing open issues and historic closed issues, so I've opened #5261 with the console outputs I'm getting.

**Comment by mindinsomnia** [comment]
> For the record the status quo has changed since this issue was closed, and we remove unused end-of-life runtimes automatically, as long as they aren't pinned.

Just to clarify what you mean by this, since this is the issue which came up on Google while searching for this..

When you say 'we remove unused end-of-life runtimes automatically', does that mean if a runtime isn't 'EOL' yet it won't be removed automatically, even if it is not being used by any installed applications?

**Comment by chrisawi** [comment]
> When you say 'we remove unused end-of-life runtimes automatically', does that mean if a runtime isn't 'EOL' yet it won't be removed automatically, even if it is not being used by any installed applications?

Yes, you would need to use `uninstall --unused` in that case, or wait for it to go EOL.

Since 1.15.7, flatpak also automatically removes autoprune-able extensions (mainly old nvidia drivers).

**Comment by beedell-roke** [comment]
[`issues/2639`](https://github.com/flatpak/flatpak/issues/2639#issue-403436132) is relevant.
