### ISSUE TITLE
Cannot Delete Some Remotes

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#2920]
## Flatpak version 1.2.4

 I installed several test versions of Lutris that were built by Flathub's bot. The repositories were registered as lutris-origin, lutris2-origin, and lutris3-origin. None of these repositories can be deleted even after the removal of Lutris. Flatpak remote-delete --force does not delete them and it yields no errors either.

**Comment by fishxz** [comment]
same problem here, with the same remote... even --verbose doesnt show anything.
