### ISSUE TITLE
Flatpak crashes on flatpak override --reset

### ISSUE THREAD

**Issue by SISheogorath** [flatpak/flatpak#2922]
## Linux distribution and version
Fedora 30

## Flatpak version

1.2.4

## Description of the problem

flatpak coredumps

```
flatpak override io.atom.Atom --reset              
**
flatpak:ERROR:app/flatpak-main.c:712:flatpak_run: assertion failed: (success || error)
[1]    29492 abort (core dumped)  flatpak override io.atom.Atom --reset

```

## Steps to reproduce

1. Install io.atom.Atom as system flatpak (may works with others as well)
2. Add an override on systemlevel `sudo flatpak override io.atom.Atom --env=TMPDIR=/var/tmp`
3. Try to reset using the user-space command: `flatpak override io.atom.Atom --reset`

**Comment by matthiasclasen** [comment]
The second step is not installing a system override. It is installing an override in the root users user installation. You want --system

**Comment by matthiasclasen** [comment]
I believe the crash has been fixed
