### ISSUE TITLE
No access to mtp devices

### ISSUE THREAD

**Issue by cjao** [flatpak/flatpak#2923]
## Linux distribution and version
Silverblue 30
## Flatpak version
1.2.4
## Description of the problem

Android MTP devices are mounted under /run/user/$UID/gvfs/. This directory is not visible in flatpak applications, even with the permissions "--devices=all, filesystems=host, org.gtk.vfs.*=talk". Consequently, applications that need access to MTP devices (such as Darktable, which can import images from cameras) lose functionality.

## Steps to reproduce
1. Connect your Android device, set to MTP mode.
2. "flatpak run --command=bash org.darktable.Darktable"
3. Confirm that /run/user/$UID/gvfs is not visible from inside the sandbox, and that Darktable cannot access the camera to import images.

**Comment by refi64** [comment]
Try `--filesystem=xdg-run/gvfs`.

**Comment by cjao** [comment]
Thanks, this appears to work!
