### ISSUE TITLE
libglnx error during autogen.sh

### ISSUE THREAD

**Issue by Pshemas** [flatpak/flatpak#2929]
## Linux distribution and version
Opensuse Leap 15.1
## Flatpak version
1.0.4
## Description of the problem
As flatpak is quite broken on opensuse now I'm trying to build one of the older versions. Tried 1.0.4 and 1.0.8. I get:

automake: error: cannot open < libglnx/Makefile-libglnx.am.inc: No such file or directory

during executing autogen.sh . Any ideas how can I fix it?

**Comment by mwleeds** [comment]
`git submodule update --init`
