### ISSUE TITLE
Adwaita-dark unsupported?

### ISSUE THREAD

**Issue by memeplex** [flatpak/flatpak#2937]
## Linux distribution and version

Arch Linux up to date

## Flatpak version

1.4.0

## Description of the problem

My system theme is Adwaita-dark but flatpak apps use Adwaita. Despite being a lot of themes available as flatpaks, the official Adwaita-dark is unavailable. This seems like an important omission to me, given the status of Adwaita.

**Comment by TingPing** [comment]
Its packaged in every runtime AFAIK.

I'm guessing your method of setting is just incorrect or not making it into the sandbox. So how did you set it?

**Comment by memeplex** [comment]
I just set it from gnome tweaks, as usual. Indeed, I assumed Adwaita-dark was preinstalled, but in that case it's not taken into account by the flatpak app. The runtime is freedesktop. I also tested this in Fedora 30.

**Comment by memeplex** [comment]
If from tweaks I set the theme to, for example, Materia-dark and install the same theme to the flatpak runtime, everything works as expected. The problem is Adwaita-dark.

**Comment by TingPing** [comment]
Works fine here. Which applications did you test?

**Comment by memeplex** [comment]
com.sublimetext.three and com.visualstudio.code

**Comment by TingPing** [comment]
Ah sorry, indeed freedesktop is broken but the gnome runtime works.

(repro: `flatpak run --command=gtk3-widget-factory --socket=x11 org.freedesktop.Sdk//18.08`)

So I suggest reporting this against the runtime: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by memeplex** [comment]
Ok, I will do it, thanks.

**Comment by memeplex** [comment]
It seems like the situation is more convoluted than I had expected, see my comment in https://github.com/flathub/flathub/issues/1023 for an overview. What do you think is the best course of action? I'm rather confused at this point.

**Comment by TingPing** [comment]
Honestly that is all a completely off topic tangent.

fdo broke something and needs to fix it.

**Comment by TingPing** [comment]
Apparently fdo just doesn't ship it.

I'll make a package on Flathub tonight or so.

**Comment by memeplex** [comment]
Thank you very much. I've opened an issue in flathub tracker for this, fill free to close it afterwards.

**Comment by TingPing** [comment]
Added https://github.com/flathub/org.gtk.Gtk3theme.Adwaita-dark
