### ISSUE TITLE
[Question] Cleanup Flatpak repo folder

### ISSUE THREAD

**Issue by peteruithoven** [flatpak/flatpak#2945]
## Linux distribution and version
elementary OS 5.0 (Built on Ubuntu 18.04.2 LTS)

## Flatpak version
Flatpak 1.4.0

## Description of the problem
After trying to build the [gitg](https://gitlab.gnome.org/GNOME/gitg) flatpak I noticed my `/var/lib/flatpak/repo` folder has become very large. 
![Screenshot from 2019-06-05 23-34-42@2x](https://user-images.githubusercontent.com/523210/58992261-9990a000-87ea-11e9-9e49-034ad4001ae4.png)
I'm assuming these are build files? Is there a good way to clean these up?

## Steps to reproduce
Build the flatpak for a project like [gitg](https://gitlab.gnome.org/GNOME/gitg).

**Comment by julianrichen** [comment]
`/var/lib/flatpak/` & `~/.local/share/flatpak/` are the system & user install location for installed runtimes (e.g. `org.gnome.Platform`) and applications (e.g. `org.gnome.gitg`). The `repo/` directory is where all the checksum-ed binary files are stored, it's like a git repo.  They are not the build files unless you include the downloaded `org.gnome.Sdk//master` runtime, which would be installed here. But the SDK is shared and not specific to gitg.

If you built with `flatpak-builder` they would be in a folder called `.flatpak-builder` & the `build` folder (what ever you called it). So if you ran the following in a directory like `~/gitg-build-folder/`:
```bash
flatpak-builder --force-clean --repo=gitg-repo build org.gnome.gitgDevel.json
```
Delete `~/gitg-build-folder/build` & `~/gitg-build-folder/.flatpak-builder` to remove any build files produced during building gitg.

If you don't need to build anything in the future you could delete `org.gnome.Sdk//master`, however, a lot of the files are de-duplicated as `org.gnome.Platform` is also installed. You might also have the `*.Debug` SDK extension installed which would take a lot of space.

**Comment by peteruithoven** [comment]
Thanks @julianrichen for the information. 

I ran a `flatpak uninstall --all` and the `flatpak/repo` stopped taking up significant space. After I then reinstalled the same flatpaks `flatpak/repo` is now at 6.7GB again. 
So it is indeed definitely not build related.

Hopefully this issue will be informative for future users.

**Comment by peteruithoven** [comment]
@julianrichen Could you also share your answer on my duplicate Stackoverflow question: https://stackoverflow.com/questions/56468429/cleanup-flatpak-repo-folder
I could copy your answer from here, but I'd prefer you to get the credits.

**Comment by MarkJeronimus** [comment]
I just installed my first flatpak application, which is about 1.65GB in size, and it took up all of the remaining 10GB of my root drive. I tried `uninstall --unused` and `repair` which obviously did nothing. How can I claim free disk space back from flatpak without losing my application? I don't understand anything from [julianrichen](https://github.com/julianrichen)'s answer, probably because I didn't build it, I just installed it.

**Comment by hanyixuanten** [comment]
> I just installed my first flatpak application, which is about 1.65GB in size, and it took up all of the remaining 10GB of my root drive. I tried `uninstall --unused` and `repair` which obviously did nothing. How can I claim free disk space back from flatpak without losing my application? I don't understand anything from [julianrichen](https://github.com/julianrichen)'s answer, probably because I didn't build it, I just installed it.
> 
> [edit] there are some other packages listed in `flatpak list` other than the application, but they all look like parts of the OS (nvidia stuff, themes, h264, etc)

Same
