### ISSUE TITLE
why in C? not in Go or Rust

### ISSUE THREAD

**Issue by catastrop** [flatpak/flatpak#2946]

**Comment by waltervargas** [comment]
because C is the lingua franca of engineering, just as Latin used to be the lingua franca of mathematics.

**Comment by catastrop** [comment]
May be. But i think there is no reason to use C at this point.

When other language provide memory safety and concurrency as part of the language.

**Comment by mwleeds** [comment]
Flatpak is in RHEL 7 which I believe doesn't have tooling for officially supported Rust packages.
