### ISSUE TITLE
Rhythmbox can't access music when xdg-music is set to be outside /home

### ISSUE THREAD

**Issue by antistress** [flatpak/flatpak#2949]
## Linux distribution and version
Debian Sid with GNOME-X11 & Linux HAL 4.19.0-5-amd64 #1 SMP Debian 4.19.37-3 (2019-05-15) x86_64 GNU/Linux
## Flatpak version
1.2.4-1
## Description of the problem

Hi,

I have changed default xdg-user-dirs in ~/.config/user-dirs.dirs : my xdg-user-dirs are located in /mnt/ – for instance XDG_MUSIC_DIR is /mnt/data/Music (/mnt/data/ is on a second drive)

It seems to lead to 2 bugs with flathub/org.gnome.Rhythmbox3 :
1°) GTK File Chooser within flathub/org.gnome.Rhythmbox3 doesn't show any xdg-user-dirs
2°) GTK File Chooser within flathub/org.gnome.Rhythmbox3 doesn't allow me to browse my /mnt/ directory which is not displayed either.

I don't have these problems with the deb version of Rhythmbox provided by my distribution.

Bug was initially reported at https://github.com/flathub/org.gnome.Rhythmbox3/issues/20

Thanks !

**Comment by hadess** [comment]
> 1°) GTK File Chooser within flathub/org.gnome.Rhythmbox3 doesn't show any xdg-user-dirs

This is a bug, Flatpak doesn't handle xdg-user-dirs that point to paths outside the user's home.

> 2°) GTK File Chooser within flathub/org.gnome.Rhythmbox3 doesn't allow me to browse my /mnt/ directory which is not displayed either.

This isn't a bug. The folder selection file chooser doesn't use a portal, so doesn't show anything apart from what's available to the application without going through a portal. It should just be able to show xdg-music in this case.

**Comment by antistress** [comment]
I'd like to apologize since this isn't a bug (**I'm** the bug)

I've checked my ~/.config/user-dirs.dirs and it seems it has been reset
Once my ~/.config/user-dirs.dirs restored, I can access to XDG_MUSIC_DIR

Sorry for the annoyance

Thanks
