### ISSUE TITLE
Dash not allowed on app name - better error message

### ISSUE THREAD

**Issue by nacho** [flatpak/flatpak#295]
Here I have 2 complains :)

1. The error message does not say why it is an invalid name:
 - error: 'org.my-app.appname' is not a valid application name
2. dash works for glib app names why not for flatpak?

Cheers

**Comment by hadess** [comment]
Accepting '-' is recent. See https://bugzilla.gnome.org/show_bug.cgi?id=764754 and in GLib:
3301b852a20b3d1f75592d03dd4038d3ea2fed7c

**Comment by alexlarsson** [comment]
Also, we rely in this not being allowed to handle filename prefix naming in the "-symbolic" case.
I.e. your application can only export files that start with their app id (say org.foo.Bar) and then optionally is followed by something starting with either a dot *or* a non-allowed character.

This means these are allowed:
org.foo.bar
org.foo.bar.png
org.foo.bar-symbolic.png

But not these:
org.foo.barbar
org.foo.barbar.png

If we allow "-" in the name we make the -symbolic name invalid.

**Comment by nacho** [comment]
@alexlarsson I am fine with that but the error message should be improved

**Comment by matthiasclasen** [comment]
I guess this can be closed then
