### ISSUE TITLE
flatpak 1.4 broke gnome-software self tests due to not allowing file:// repos any more

### ISSUE THREAD

**Issue by kalev** [flatpak/flatpak#2955]
After updating gnome-software CI from flatpak 1.2 to 1.4, gnome-software self tests started failing with:

```
GsPluginFlatpak:ERROR:../plugins/flatpak/gs-self-test.c:613:update_app_action_finish_sync: assertion failed (error == NULL): Flatpakrepo URL file:///var/tmp/self-test/test.flatpakrepo not HTTP or HTTPS (gs-plugin-error-quark, 0)
1/1 gs-self-test-flatpak                    FAIL    10.70 s (killed by signal 6 SIGABRT)
```

See e.g. https://gitlab.gnome.org/GNOME/gnome-software/-/jobs/322613

Is this expected? Should gnome-software stop using file:// repos for self tests?

**Comment by alexlarsson** [comment]
I suspect this was accidentally done by https://github.com/flatpak/flatpak/issues/2727

**Comment by alexlarsson** [comment]
Eh, sorry, wrong link

**Comment by alexlarsson** [comment]
I meant https://github.com/flatpak/flatpak/pull/2740

**Comment by alexlarsson** [comment]
See e.g. https://github.com/flatpak/flatpak/pull/2740#issuecomment-470117029
Which says that file: uris broke but we support paths instead. Maybe thats not working in the library though?

**Comment by kalev** [comment]
The self tests right now use file:// repos. This is an example of a generated .flatpakref file:

```
[Flatpak Ref]
Title=Chiron
Name=org.test.Chiron
Branch=master
Url=file:///home/kalev/jhbuild/checkout/gnome-software/build/plugins/flatpak/tests/app-with-runtime/repo
IsRuntime=False
Comment=Single line synopsis
Description=A Testing Application
Icon=https://getfedora.org/static/images/fedora-logotext.png
```

**Comment by alexlarsson** [comment]
Local repos themselves *do* work fine. I have things like:

[remote "local"]
gpg-verify=false
gpg-verify-summary=false
url=file:///vcs/flatpak/repo

In my config. However what broke is probably supporting them in flatpakref files.

**Comment by alexlarsson** [comment]
I'll have a look

**Comment by alexlarsson** [comment]
Hmm, what exactly are you doing. I tested this, and it seems to work fine:
```
$ cat test.flatpakref
[Flatpak Ref]
Title=Dictionary
Name=org.gnome.Dictionary
Branch=stable
Url=file:///vcs/flatpak/link-to-repo
IsRuntime=False
$ flatpak --user install file:///vcs/gnome/flatpak/test.flatpakref

org.gnome.Dictionary permissions:
    ipc   network   wayland   x11   file access [1]   dbus access [2]

    [1] xdg-run/dconf, ~/.config/dconf:ro
    [2] ca.desrt.dconf


        ID                                        Branch               Remote                         Download
 1. [✓] org.gnome.Dictionary                      stable               dictionary-origin              1.0 kB / 676,5 kB
 2. [✓] org.gnome.Dictionary.Locale               stable               dictionary-origin              1.0 kB / 471,7 kB

Installation complete.
```

**Comment by alexlarsson** [comment]
Hmm, i see that the flatpak install CLI loads the flatpakref itself, and it has special casing for http. So maybe you're using some library API that doesn't do this.

**Comment by alexlarsson** [comment]
Oh, i see. The error is not about the flatpakref file, but the flatpakrepo file. And indeed, flatpak-transaction.c::handle_runtime_repo_deps() has this check.

But, I don't think we ever supported this for non-http uris? Also, the example .flatpakref you have there doesn't have a `RuntimeRepo` key, so it should not trigger this?

**Comment by kalev** [comment]
Oops, I pasted the wrong file. This triggers it:

```
$ cat test.flatpakrepo 
[Flatpak Repo]
Title=foo-bar
Comment=Longer one line comment
Description=Longer multiline comment that does into detail.
DefaultBranch=master
Url=file:///home/kalev/jhbuild/checkout/gnome-software/build/plugins/flatpak/tests/only-runtime/repo
Homepage=http://foo.bar

$ cat test.flatpakref 
[Flatpak Ref]
Title=Chiron
Name=org.test.Chiron
Branch=master
Url=file:///home/kalev/jhbuild/checkout/gnome-software/build/plugins/flatpak/tests/app-missing-runtime/repo
IsRuntime=False
Comment=Single line synopsis
Description=A Testing Application
Icon=https://getfedora.org/static/images/fedora-logotext.png
RuntimeRepo=file:///var/tmp/self-test/test.flatpakrepo

$ flatpak --user install file:///var/tmp/self-test/test.flatpakref
error: Flatpakrepo URL file:///var/tmp/self-test/test.flatpakrepo not HTTP or HTTPS
```

**Comment by alexlarsson** [comment]
@kalev can you try that pr?

**Comment by kalev** [comment]
Yep, that works and makes the tests pass again. Thanks, @alexlarsson!
