### ISSUE TITLE
Delete gh-pages branch?

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#2965]
Currently the `gh-pages` branch in this repository (which is `flatpak.github.io`) has an outdated version of the docs. We could update it but would it make more sense to delete it and let docs.flatpak.org be the canonical source for documentation?

**Comment by matthiasclasen** [comment]
I agree

**Comment by mwleeds** [comment]
Done. I created a `gh-pages-archived` branch in case we change our minds, and deleted `gh-pages`.
