### ISSUE TITLE
Foliate 1.3.0 closes as soon as I try to open a file 

### ISSUE THREAD

**Issue by terrestrian** [flatpak/flatpak#2967]
## I just updated Foliate to version 1.3.0. Now it doesn't open anything. When I try to open any epub file it immediately closes. This is the output from terminal.
 

> flatpak run --verbose com.github.johnfactotum.Foliate
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/veli/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/veli/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/veli/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 1946535856
F: Allocated instance id 3075340036
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 29 /usr/lib/flatpak/flatpak-dbus-proxy --args=31'
F: Running 'bwrap --args 25 com.github.johnfactotum.Foliate'
Gjs-Message: 22:22:27.951: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 1741]: reference to undefined property "isFullscreen"

**Comment by mwleeds** [comment]
You should probably file an issue here: https://github.com/flathub/com.github.johnfactotum.Foliate

**Comment by johnfactotum** [comment]
This issue is being tracked here: https://github.com/johnfactotum/foliate/issues/88
