### ISSUE TITLE
I can't find the flatpak package for Chinese input method. It's a pity.

### ISSUE THREAD

**Issue by chasezphp** [flatpak/flatpak#2970]
## Steps to reproduce
I can't find the flatpak package for Chinese input method. It's a pity.

**Comment by mwleeds** [comment]
Closing this as a duplicate of https://github.com/flatpak/flatpak/issues/2031

If that's incorrect and this is a separate issue, please re-open and give more information on exactly what flatpak you're looking for and what problem you're trying to solve.
