### ISSUE TITLE
All flatpaks stopped working

### ISSUE THREAD

**Issue by mielouk** [flatpak/flatpak#2974]
## Linux distribution and version
Arch 5.1.12

## Flatpak version
1.4.1-2 downgraded in two steps to 1.3.4-2

## Description of the problem
I didn't recognize it at first, but after a reboot my flatpaks didn't start up as usual.
Since today's update to 1.4.1-2 from 1.4.1-1 I get this with each and every flatpak:

`flatpak run org.audacityteam.Audacity
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
Fehler: ldconfig ist fehlgeschlagen, Exit-Status 256`
(This means "Error: ldconfig failed, exit-status 256)

My journal tells me 

`Jun 23 17:14:11  systemd[1376]: Started flatpak-com.wire.WireDesktop-1783.scope.
Jun 23 17:14:11  systemd[1376]: Started flatpak-org.keepassxc.KeePassXC-1790.scope.`

Which is evidently false, as those have not been started. Downgrading didn't help the issue.

## Steps to reproduce
Use Arch upgrade to 1.4.1-2

**Comment by RouZERO** [comment]
downgrade package bubblewrap It worked here.

**Comment by mielouk** [comment]
Thx, that helped.
