### ISSUE TITLE
segfault in libcurl during install

### ISSUE THREAD

**Issue by cmurf** [flatpak/flatpak#2977]
## Linux distribution and version

Fedora 30

## Flatpak version

flatpak-1.4.1-1.fc30.x86_64
ostree-2019.2-1.fc30.x86_64
bubblewrap-0.3.3-2.fc30.x86_64
curl-7.64.0-7.fc30.x86_64

## Description of the problem

Similar to issue 2934, except I'm seeing it during the installation of org.freedesktop.Platform. It doesn't always happen, maybe 50% of the time it happens. This is happening on a clean installation of Fedora 30.

## Steps to reproduce

1. No flatpak repos or anything else installed; /var/lib/flatpak/ is empty 
2. $ flatpak install --from com.slack.Slack.flatpakref

Contains gdb output for a coredump that was captured
https://bugzilla.redhat.com/show_bug.cgi?id=1723242
The dup that abrt found after multiple hours of dealing with debuginfos and gdb.
https://bugzilla.redhat.com/show_bug.cgi?id=1697566

**Comment by mwleeds** [comment]
It's hard to see how this is a Flatpak bug. It's libcurl that's crashing.

**Comment by cmurf** [comment]
It's a bug because flatpak is failing to properly handle the libcurl crash in a way that lets me clearly know there's been a problem in a library flatpak depends on. From a user perspective, it looks like a flatpak crash.

**Comment by mwleeds** [comment]
I don't know of any program which catches seg faults and converts them into another kind of error. I agree it seems like a Flatpak crash to the user, but maybe it's worth opening a bug report on libcurl in case they have some insight?

**Comment by cmurf** [comment]
https://curl.haxx.se/mail/lib-2019-06/0079.html

**Comment by tansly** [comment]
This is a libcurl bug, which is fixed. Fedora needs to update its libcurl to 7.65.

Actual crash happens at:
`#0  multi_socket (multi=multi@entry=0x562b396fe710, checkall=checkall@entry=false, s=<optimized out>, ev_bitmask=2, running_handles=0x562b38e6bdb0) at ../../lib/multi.c:2652
`
See:
https://curl.haxx.se/mail/lib-2019-05/0031.html

Also see:
https://github.com/curl/curl/issues/3904
https://github.com/curl/curl/issues/3952

Commit fixing this: https://github.com/curl/curl/commit/8581e1928ea8e125021408ec071fcedb0276c7fe

[Curl changelog](https://curl.haxx.se/changes.html) says that it is fixed in 7.65.1 ( multi: track users of a socket better ). But Fedora 30 still has 7.64.

Better file a bug against Fedora.

**Comment by tansly** [comment]
By the way, the same error also happens in gnome-software, again causing a segfault.

**Comment by cmurf** [comment]
Fedora downstream bugs are:
flatpak
https://bugzilla.redhat.com/show_bug.cgi?id=1697566
gnome-sofware
https://bugzilla.redhat.com/show_bug.cgi?id=1723242

I changed both to curl. 

The problem with the idea this is fixed in curl 7.65, is that version is already on Fedora Rawhide and I get the same crash there too, but far less often than on Fedora 30. It might be once in ~7GiB downloaded before I run into it. And it has only happened on large runtimes, so far only > 700MiB, nothing smaller.

**Comment by jay** [comment]
> The problem with the idea this is fixed in curl 7.65, is that version is already on Fedora Rawhide and I get the same crash there too

The multi fixes are in 7.65.1. As was mentioned on the mailing list if you're still having problems please try master since it's possible there's already a fix in for it.

/cc @bagder

**Comment by cmurf** [comment]
I mentioned in the libcurl-mailing list thread I'm using libcurl-7.65.1-1.fc31.x86_64

**Comment by mcatanzaro** [comment]
I agree that it's unlikely there's any flatpak bug here, certainly none actionable. (I would close this.)

I recommend reporting a new bug against libcurl, with a backtrace taken with libcurl-7.65.11-1.fc31. Having an updated backtrace might be important so that this isn't just a shot in the dark.
