### ISSUE TITLE
All qt apps in hidpi screen show tiny fonts

### ISSUE THREAD

**Issue by memeplex** [flatpak/flatpak#2980]
## Linux distribution and version

Ubuntu 19.04

## Flatpak version

1.2.4

## Description of the problem

I use qt5ct to configure the font of qt apps. I also set:

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME=qt5ct

Even with the auto scaling factor, the default qt font is tiny in my hidpi screen, so I have to increase its size from qt5ct from 10 to 11 or 12. Now, this is all lost in the isolated flatpak environment so, in brief, I'm unable to reasonably run *any* qt app installed from flatpak. This is not a matter of fancy themes, it's a basic matter of accessibility.

## Steps to reproduce

1. Use a hidpi screen (mine is 3000x2000 13'')
2. Configure font in qt5ct to look reasonably sized
3. Run a qt app with the environment described above: fine
4. Install that qt app from flathub
5. Run the flatpak version of the app
6. The font settings are ignored, fonts look tiny

## Additional comments

This report was motivated by the inability to properly install and run Anki in Ubuntu 19.04:

1. The deb package is broken (there is a bug filed for this but unattended as of today).

2. The flatpak and the snap packages use a tiny font and it doesn't seem to be possible to change it.

**Comment by memeplex** [comment]
In https://bugs.launchpad.net/snappy/+bug/1834061 I have compared the flatpak and snap versions of Anki, there is a screenshot with a detailed description.

**Comment by refi64** [comment]
I'd think Qt would have another way of handling scaling...

But at a glance, you can use `flatpak override my.app.id --env=QT_...=1 --env=...` to set environment variables on a per-app basis.

**Comment by memeplex** [comment]
There is no problem with the scaling factor when using flatpak (there is a problem when using snap, but that's another subject). What is happening is that qt5ct is not installed in the sandbox. So my qt5ct configuration is not being honored and the default font of 10pt that is set for qt out of the box is small for some combinations of dpis and scaling factors (Ubuntu system font is 11pt, for example, which works better under a variety of resolutions). There is an open issue for making flatpak work with kvantum but, at a bare minimum, it should work with breeze and some system settings like fonts and icons, also gtk dialogs. In the case of flatpak, this could be addressed by installing qt5ct in the kde runtime. Alternatively, by installing qgnomeplatform, although I have never used it since it's not packaged for Debian. Then some allowance to read a couple of config files in the user home folder will be in order too. I believe one or the other should be done and that getting this right is more important than preinstalling kvantum. If you ensure that breeze is available and also some basic consistency at the font/icon level, you get a properly working, robust, qt platform. Then you can worry about fanciness and consistency.

**Comment by hfiguiere** [comment]
Looks like a runtime problem not a flatpak problem.
