### ISSUE TITLE
Feature request:  a   --Yes_I_really_want_to_install_it   option

### ISSUE THREAD

**Issue by digimeas** [flatpak/flatpak#2985]
Hi!  I like flatpak!, but my "tubes" are being a little fractious today, and it's taking forever (over an hour so far just to install stellarium (which I actually want to install :-)) and I keep finding there's yet another question to answer which makes it even slower.

Seriously, how many people answer "no"?

Thanks
Doug

**Comment by TingPing** [comment]
`flatpak install -y`

**Comment by digimeas** [comment]
Thanks TingPing
BTW

flatpak -h
...
Help Options:
  -h, --help             Show help options
Application Options:
  --version              Print version information and exit
  --default-arch         Print default arch and exit
  --supported-arches     Print supported arches and exit
  --gl-drivers           Print active gl drivers and exit
  -v, --verbose          Print debug information during command processing, -vv for more detail
  --ostree-verbose       Print OSTree debug information during command processing

Doug

**Comment by TingPing** [comment]
`flatpak install --help`

**Comment by digimeas** [comment]
Hi @TingPing!

Got it. But how would a normal person figure that out?

Thanks
Doug

**Comment by TingPing** [comment]
Its extremely standard CLI tool stuff so I don't know what to say. The `--help` docs are correct, the `man` docs are correct, and `-y` is common for this usage.
