### ISSUE TITLE
Switch to fuse 3.x

### ISSUE THREAD

**Issue by Keruspe** [flatpak/flatpak#2987]
From the release notes of libfuse 2.9.9: 

```
Note: This is a maintenance release from the 2.9 branch of libfuse. Users are encouraged to transition to the actively developed libfuse 3.x.
```

**Comment by nullr0ute** [comment]
the last release of fuse2 was 2.9.9 in Jan 2019 so fuse2 is no longer maintained or getting security releases.

**Comment by smcv** [comment]
Yes, #4326 fixed this.
