### ISSUE TITLE
Double slashes not ignored in search paths warnings

### ISSUE THREAD

**Issue by aDogCalledSpot** [flatpak/flatpak#2989]
## Linux distribution and version
Arch 5.1.15
## Flatpak version
1.4.1
## Description of the problem
If `XDG_DATA_DIRS` has a double slash for a file path equivalent to `$HOME/.local/share/flatpak/exports/share` it will not view it as equal and throw the warning that the path is not in the `XDG_DATA_DIRS` (In my case, the file path is `$HOME/.local/share//flatpak/exports/share`).
## Steps to reproduce
Set the environment variable `XDG_DATA_DIRS="$HOME/.local/share/"`. Use flatpak update. A warning should appear.

**Comment by mwleeds** [comment]
Fixed by https://github.com/flatpak/flatpak/pull/2990
