### ISSUE TITLE
sysusers.d support

### ISSUE THREAD

**Issue by AdrianVovk** [flatpak/flatpak#2996]
Flatpak added revokefs support a few releases ago and requires a new system user for this. Could you package a sysusers.d file so that systemd systems can deal with this even when booting with an empty /etc? Thank you!

**Comment by mwleeds** [comment]
Is this not a question for each distribution that packages Flatpak, e.g. Debian?

**Comment by smcv** [comment]
Distributions that package Flatpak can certainly create system users in OS-specific ways (e.g. Debian uses `adduser(8)` in the `flatpak.postinst` dpkg maintainer script, and Fedora uses some other command in the `%post` RPM scriptlet) and at the moment that's what they have to do.

However, if the upstream project installs a suitable `sysusers.d` file, then distributions that exclusively use systemd (like Fedora) don't necessarily have to do anything OS-specific at all, and distributions that optionally use systemd (like Debian) can deal with an empty `/etc` under systemd more easily.

https://gitlab.freedesktop.org/dbus/dbus/commit/e8617fbd27d8ec058511927cabb6a405ebcdca9e is what we did in dbus.

**Comment by AdrianVovk** [comment]
One of the reasons sysusers.d exists is to make system user creation distro-agnostic (at least for the distros that opt-in to this system). Plus, it allows for the OS to deal with an empty /etc, which is great for guest sessions, factory resets, and the like

**Comment by AdrianVovk** [comment]
This seems fixed. Closing

**Comment by smcv** [comment]
I don't see any indication that this was merged? I got as far as making a commit in my fork of flatpak, but I haven't tested it or proposed it as a PR.

**Comment by AdrianVovk** [comment]
Ah. I just saw the commit and thought it was in this repo. Re-opening.

**Comment by smcv** [comment]
@AdrianVovk: if this is important to you, you're welcome to test my commit. Otherwise I'll test it myself eventually.

**Comment by AdrianVovk** [comment]
@smcv I'll get around to it eventually. I'm currently reimplementing my OS and I haven't gotten to Flatpak yet

**Comment by matthiasclasen** [comment]
Sounds like this would be nice to have.

**Comment by AdrianVovk** [comment]
Oh I've gotten to Flatpak and experienced no issues so I'm closing the issue. Thanks!
