### ISSUE TITLE
update-repo: Handle "metainfo" name as well as "appdata"

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#30]
It seems the appstream spec changed a bit, and now files/dirs are supposed to be called "metainfo" instead. We should look for these filenames too.

**Comment by hughsie** [comment]
I think that's only for non-applications, right?

**Comment by alexlarsson** [comment]
The spec (at https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) says e.g:

>  Applications are a special case here, because they are usually treated differently by software centers (and also for historical reasons). If your metainfo file covers only an application, as described in the AppData section, install it as /usr/share/metainfo/%{id}.appdata.xml. 
> 
>  The /usr/share/appdata/ path must be scanned by AppStream tools as well, to support legacy applications installing metadata there. For new software components, it is advised not to use this directory. 

So, yes, apps use appdata in the filename, but not in the directory name. And what about runtimes? Those are not apps.

**Comment by matthiasclasen** [comment]
I believe this is fixed
