### ISSUE TITLE
flatpak shows incorrect error message when running concurrent instances

### ISSUE THREAD

**Issue by genodeftest** [flatpak/flatpak#300]
Steps to reproduce:
1. run `flatpak update org.gnome.Platform` or any other command which changes the installation and takes some time.
2. run `flatpak --user list` or any other perfectly valid command

What happens:
Often, the second command shows the help page plus this error message:
`Error: Unknown Option --user` where `--user` always is the first argument of `flatpak`

What should happen:
Second command should run fine. If it cannot run due to an operation blocking the filesystem, it should tell the user and either abort (without the usage page) or wait.

Running flatpak-0.6.9-2.fc24.x86_64 (Fedora 24)

**Comment by alexlarsson** [comment]
Woa. Thats weird. I wonder what causes that.

**Comment by matthiasclasen** [comment]
seems to work in my testing with 1.0.2.

Please reopen if you still see it

**Comment by genodeftest** [comment]
> seems to work in my testing with 1.0.2.

confirmed with the same version / Fedora 28.
