### ISSUE TITLE
[Question] Preinstalling Flatpaks on a new OS

### ISSUE THREAD

**Issue by AdrianVovk** [flatpak/flatpak#3000]
I'm developing a new Linux distro where Flatpak is the only package manager. What is the best way to preinstall apps? I've been trying to find how it's done on distros like Endless and Fedora and I haven't had any success. Could you point me in the right direction?

Thank you!

**Comment by mwleeds** [comment]
For Endless we use the Python bindings for libflatpak and libostree to configure remotes, pull their appstream data and metadata, and install flatpaks as part of the image build process (it's unfortunately not open source).

**Comment by AdrianVovk** [comment]
@mwleeds Does it get installed into /var on the image? How do you handle factory resets where /var is empty?

> it's unfortunately not open source
And that's why I couldn't find it :/

**Comment by mwleeds** [comment]
> @mwleeds Does it get installed into /var on the image? How do you handle factory resets where /var is empty?

On Endless `/var/lib/flatpak` is a sym link to `/sysroot/flatpak` (`/sysroot` is an ostree concept which is roughly the same as `/`).

**Comment by AdrianVovk** [comment]
@mwleeds So would a factory reset not touch the system flatpak installation, or do you have a script to uninstall everything you didn't ship with?

**Comment by mwleeds** [comment]
Is there some distribution agnostic factory reset mechanism you're referring to? We have `eos-factory-reset` in Endless and that leaves flatpaks in place, but it's just an imperfect script that leaves other state in place too.

**Comment by refi64** [comment]
@mwleeds Likely http://0pointer.net/blog/projects/stateless.html

**Comment by AdrianVovk** [comment]
@mwleeds With OSTree, deleting /var, /etc, and /home = deleting all of the state. However, in your case, I was referring to eos-factory-reset

**Comment by matthiasclasen** [comment]
I think the questions here have been answered
