### ISSUE TITLE
renameat error when trying to install

### ISSUE THREAD

**Issue by elya5** [flatpak/flatpak#3002]
- Linux distribution and version: managed Cent OS 7 installation.
- Flatpak version: 1.0.2

## Description of the problem
I wanted to install flatpak software and I could add the remotes without problems but there are some errors when I try to install something. It says: `error: Failed to install org.gnome.Sdk/x86_64/master: Writing metadata object: renameat: Invalid cross-device link`

This is a company computer that probably uses some sort of network shared file system but I don't know the details.

**Comment by mwleeds** [comment]
Probably it would work to do `flatpak install --user ...` because then it will install to your home directory.

**Comment by mwleeds** [comment]
Closing since I doubt we support whatever filesystem setup you have, and without more details it would be impossible to.
