### ISSUE TITLE
DConf settings migration isn't clear

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak#3008]
Flatpak 1.4.x is supposed to migrate settings but it doesn't seem to be working. Some user complaints: https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/184

**Comment by matthiasclasen** [comment]
Instead of a fix, here is a post: https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

**Comment by matthiasclasen** [comment]
In short: migration needs to be explicitly opted in to. But (until earlier today), the switch to the keyfile backend was happening unconditionally. This is being fixed in GLib

**Comment by TingPing** [comment]
I see, did you figure out a way to opt-in via a flatpak-builder manifest?

**Comment by TingPing** [comment]
Also that does mean the default state is losing user settings which is of course not ideal. Maybe there needs to be some heuristic to make the transition easier? Like if you have dconf permission still keep using the keyfile?

**Comment by TingPing** [comment]
Ah I found the permission for `flatpak-builder`: `--metadata=X-DConf=migrate-path=/a/path/`

**Comment by TingPing** [comment]
We also need some GNOME wide initiative to get that added and DConf removed from all manifests.

**Comment by TingPing** [comment]
I've included this in the documentation: http://docs.flatpak.org/en/latest/sandbox-permissions.html?#dconf-access

**Comment by matthiasclasen** [comment]
> Also that does mean the default state is losing user settings which is of course not ideal. Maybe there needs to be some heuristic to make the transition easier? Like if you have dconf permission still keep using the dconf backend?

That is what glib does with the latest fixes.

**Comment by TingPing** [comment]
Fantastic, for reference that is here: https://gitlab.gnome.org/GNOME/glib/merge_requests/985

And with that I think this can be closed.
