### ISSUE TITLE
Cannot measure CPU usage non-interactively with time command, time cannot receive flags

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [flatpak/flatpak#3009]
## System and version
Tumbleweed 20190708
## Flatpak version 
1.4.2
## Description of the problem
According to https://github.com/flatpak/flatpak/issues/525, it appears one has to open a shell for `time` to capture accurate CPU usage. 
Am hoping there is now an option that can be used in scripts, as I'm trying to loop multiple configurations of HandBrake to determine settings to use, and having to manually kick every iteration will be painful.

It also appears `time` does not accept flags (adding -anything results in "sh: time: command not found"), and /usr/bin/time is not allowed.
## Steps to reproduce
Run

     /usr/bin/time -f "%P %E" -o ~/test.txt flatpak run --command=HandBrakeCLI fr.handbrake.ghb -i ~/Videos/Unfinished/Kingsman_The_Golden_Circle_[2017].mkv -o ~/Videos/Kingsman_The_Golden_Circle_[2017].mkv-4-x264-20-faster.mkv -x level=4 -e x264 -q 20 -f av_mkv --encoder-preset faster -c 1

NOTE completes successfully (assuming input file exists), with 0% CPU and probably at least a minute Elapsed time.

Run

    flatpak run --command=sh fr.handbrake.ghb
    $ time HandBrakeCLI -i ~/Videos/Unfinished/Kingsman_The_Golden_Circle_[2017].mkv -o ~/Videos/Kingsman_The_Golden_Circle_[2017].mkv-4-x264-20-faster.mkv -x level=4 -e x264 -q 20 -f av_mkv --encoder-preset faster -c 1

NOTE job completes, but only returns times without CPU%, and has to be run manually.

Run 

    flatpak run --command=sh fr.handbrake.ghb
    $ time -v HandBrakeCLI -i ~/Videos/Unfinished/Kingsman_The_Golden_Circle_[2017].mkv -o ~/Videos/Kingsman_The_Golden_Circle_[2017].mkv-4-x264-20-faster.mkv -x level=4 -e x264 -q 20 -f av_mkv --encoder-preset faster -c 1

NOTE error thrown because `time` is now unknown command.

Run 

    flatpak run --command=sh fr.handbrake.ghb
    $ time -f "%P %E" HandBrakeCLI -i ~/Videos/Unfinished/Kingsman_The_Golden_Circle_[2017].mkv -o ~/Videos/Kingsman_The_Golden_Circle_[2017].mkv-4-x264-20-faster.mkv -x level=4 -e x264 -q 20 -f av_mkv --encoder-preset faster -c 1

NOTE error thrown because `time` is now unknown command.

Run 

    flatpak run --command=sh fr.handbrake.ghb
    $ /usr/bin/time -v HandBrakeCLI -i ~/Videos/Unfinished/Kingsman_The_Golden_Circle_[2017].mkv -o ~/Videos/Kingsman_The_Golden_Circle_[2017].mkv-4-x264-20-faster.mkv -x level=4 -e x264 -q 20 -f av_mkv --encoder-preset faster -c 1

NOTE error thrown because `/usr/bin/time` is unknown command.

**Comment by cxrvh** [comment]
This is not a bug.

GNU time (/usr/bin/time, [[0]]) is simply not part of the Freedesktop SDK and therefore you get the unknown command errors. Only the shell keyword time [[1]] [[2]] is provided and Flatpak can't execute a pipeline with the --command option.

You can achieve what you want in other ways but you can't use any options from the time binary (e.g. -f results in unknown command errors, too), only what is described in the bash manpage [[3], you must define a TIMEFORMAT variable to customize the output].

#### Pass your pipeline to the -c option
Extra arguments are passed on to the application, so you can pass your commands to bash's -c option:
`flatpak run --command=bash fr.handbrake.ghb -c "time HandBrakeCLI …"`

#### Execute the script in Flatpak
Put all your commands without "flatpak run fr.handbrake.ghb" into a script and execute the script as the command:
`flatpak run --command=~/dir/all_commands.sh fr.handbrake.ghb`

Depending on the application, it can be necessary to make the script location available in the sandbox (i.e. `flatpak run --filesystem=~/dir …`).


[0]: https://linux.die.net/man/1/time
[1]: https://www.gnu.org/software/bash/manual/html_node/Pipelines.html
[2]: https://stackoverflow.com/questions/19236448/shell-execution-time-vs-usr-bin-time
[3]: https://linux.die.net/man/1/bash
