### ISSUE TITLE
[RFE] Install main app as last one

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak#3017]
Currently, if a Flatpak app that is being installed requires some additional extensions (for example _bar.foo.app.Locale_, _org.freedesktop.Platform.Compat.i386_, _org.freedesktop.Platform.ffmpeg_ etc.) these extensions are installed after the main app is installed. This causes [issues](https://gitlab.gnome.org/GNOME/gnome-software/issues/628) with GNOME Software that displays the app as installed even if there are still some extensions being installed on background. Please, consider changing the behavior so the main app is installed as the last one.

**Comment by hughsie** [comment]
Note, this needs to be fixed in libflatpak rather than gnome-software, otherwise the gnome-shell launchable gets created before it can actually be used and the same bug is visible there too.

**Comment by pwithnall** [comment]
Fixed by https://github.com/flatpak/flatpak/pull/3166.
