### ISSUE TITLE
CLI runtime

### ISSUE THREAD

**Issue by amigalemming** [flatpak/flatpak#3018]
What about adding a lightweight runtime for CLI programs?
So far, the available runtimes all come with baggage for graphical user interfaces:
http://docs.flatpak.org/en/latest/available-runtimes.html

Related: #1188, #329.

**Comment by TingPing** [comment]
It is probably a discussion to have with the freedesktop-sdk folks: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

Flatpak itself does not maintain or create a runtime itself.

**Comment by matthiasclasen** [comment]
How does the 'baggage' affect you? Unless you use flatpak exclusively for cli apps, you are going to need a bigger runtime anyway. Maintaining runtimes is not free...

**Comment by dead10ck** [comment]
@matthiasclasen it's true that if you have other GUI apps installed through Flatpak, you'll have the Freedesktop runtimes installed anyway. But at the same time, I think using Flatpak exclusively for CLI apps is a valid use case. A lot of CLI tools out there really only need glibc, and sometimes not even that. It seems excessive to have D-Bus, GLib, Gtk3, PulseAudio, X11 and Wayland in a runtime for a simple binary.

Another thing to consider is adoption. If someone is a new user giving Flatpak a try, and they decide to install ripgrep, for example, and they have to download hundreds of megabytes in runtime layers first, it gives off a bad first impression.

**Comment by TingPing** [comment]
Well anyway this isn't actionable here and would be something to discuss with the actual runtime creators.

**Comment by t1u1** [comment]
Did anyone raise an issue elsewhere to track this? Anyone that finds this issue will be able to track progress there...
