### ISSUE TITLE
Getting real desktop file ID

### ISSUE THREAD

**Issue by AdrianVovk** [flatpak/flatpak#3020]
I tried asking this on the ML but I got an email that it's awaiting moderation and I haven't heard back. Here's the email:

Hello,

I'm building a distro + DE that exclusively uses Flatpak for package management. I'm working on my notification server, and some apps (like Discord) send over their app IDs in the notification, but they send their "real" app ID (discord.desktop) and not the app ID the system knows them by (com.discordapp.Discord.desktop). Is there some way for my shell to look up which app discord.desktop belongs to? An extra key in all of Flatpak's generated desktop files would be perfect for this. I'd just loop over all of the apps on the system and check for X-Flatpak-RenamedFrom=discord.desktop and I'd know the app's real ID.

Thank you,
Adrian Vovk

**Comment by TingPing** [comment]
I feel like this is fixing it at the wrong place.

I'd rather some solution exist to rewrite the id in notifications when incorrect (similar to a libnotify->notification-portal wrapper lib).

**Comment by AdrianVovk** [comment]
I just came across another use-case. I'm working on my shell's running app list, and I (once again) cannot get the icon of discord. Discord reports its app_id as `discord.desktop` (directly via wayland), so I just have to roll with it in my shell. There is no practical way for Flatpak to take care of this with some random wrapper lib

**Comment by AdrianVovk** [comment]
So the way GNOME does this is via PID. It just reads `/proc/PID/root/.flatpak-info` for all the info it could ever need. Closing here
