### ISSUE TITLE
“flatpak build-bundle” fails on system repo

### ISSUE THREAD

**Issue by wjt** [flatpak/flatpak#3026]
## Linux distribution and version

Fedora 30 / Endless OS 3.7.0 (development branch)

## Flatpak version

1.4.2 / 1.3.3

## Description of the problem

The example invocation of `flatpak build-bundle` in its manpage is to export a bundle for an app installed in the system repo:

```
flatpak build-bundle /var/lib/flatpak/repo gnome-calculator.flatpak org.gnome.Calculator stable
```

However, this doesn't work – neither apps nor runtimes can be exported from the system repo.

## Steps to reproduce

```
$ flatpak install --system -y flathub org.gnome.Calculator
(time passes, it succeeds)
$ flatpak build-bundle /var/lib/flatpak/repo gnome-calculator.flatpak org.gnome.Calculator stable
error: Refspec 'app/org.gnome.Calculator/x86_64/stable' not found
```

`/var/lib/flatpak/repo` on the Fedora system:

```
[core]
repo_version=1
mode=bare-user
min-free-space-size=500MB

[remote "flathub"]
url=https://dl.flathub.org/repo/
xa.title=Flathub
gpg-verify=true
gpg-verify-summary=true
xa.noenumerate=false

[remote "fedora"]
url=oci+https://registry.fedoraproject.org
xa.title=Fedora
xa.title-is-set=true

[remote "fedora-testing"]
url=oci+https://registry.fedoraproject.org#testing
xa.title=Fedora (testing)
xa.title-is-set=true
xa.disable=true
```

(Endless has an unusual repo layout, shared with the system ostree repo, so I think this report is more convincing on Fedora!)

**Comment by mwleeds** [comment]
Looks like this was broken by https://github.com/flatpak/flatpak/pull/2705, working on a fix. I'm surprised it took months for anyone to notice.

**Comment by mwleeds** [comment]
Fix is in https://github.com/flatpak/flatpak/pull/3032
