### ISSUE TITLE
audio issues with audio over bluetooth

### ISSUE THREAD

**Issue by mildred** [flatpak/flatpak#3030]
## Linux distribution and version
Fefora Silverblue 30

## Flatpak version
1.4.2

## Description of the problem
Audio is sluttering with bluetooth devices with at least Totem and VLC.

## Steps to reproduce
- have a bluetooth device connected as audio receiver
- play audio using a flatpak application
- notice sound sluttering

**Comment by refi64** [comment]
Are you positive this is a Flatpak issue? Have you tried e.g. installing
Totem as a layered package and playing audio there? At a glance this sounds
a lot like [the bluetooth audio issues on Linux](
https://wiki.archlinux.org/index.php/Bluetooth_headset#Connecting_works,_but_there_are_sound_glitches_all_the_time
).

**Comment by hfiguiere** [comment]
Doesn't look like a flatpak problem.
