### ISSUE TITLE
Nuvola Apps don't open - Cant update Platform

### ISSUE THREAD

**Issue by kayfay** [flatpak/flatpak#3033]
## Linux distribution and version
Debian 9 Kernel 4.9.0-9-amd64 x86_64

## Flatpak version
0.8.9

## Description of the problem
Opening apps doesn't work

## Steps to reproduce

Trying to update platform

```
flatpak update --system; flatpak update --user
Looking for updates...
Required runtime for eu.tiliado.Nuvola/x86_64/stable (org.gnome.Platform/x86_64/3.32) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
error: app/org.shotcut.Shotcut/x86_64/stable needs a later flatpak version (0.11.4)
```

    flatpak run eu.tiliado.NuvolaAppAmazonCloudPlayer                                                                           
    error: runtime/org.gnome.Platform/x86_64/3.32 not installed

I tried Installing various versions all of them except 3.30 resulted in connection reset by peer

```
flatpak install flathub org.gnome.Platform//3.24
Installing: org.gnome.Platform/x86_64/3.24 from flathub
Receiving delta parts: 1/10 6.9 MB/s 68.5 MB/252.6 MB 26 seconds remaining                                                                               
error: While pulling runtime/org.gnome.Platform/x86_64/3.24 from remote flathub: Error receiving data: Connection reset by peer
```

Version 3.30 says its installed.

    flatpak install flathub org.gnome.Platform//3.30
    error: org.gnome.Platform/x86_64/3.30 already installed

Saw similar error with issue #2116 still open

**Comment by mwleeds** [comment]
> flatpak update --system; flatpak update --user
> Looking for updates...
> Required runtime for eu.tiliado.Nuvola/x86_64/stable (org.gnome.Platform/x86_64/3.32) is not installed, searching...
> Found in remote flathub, do you want to install it? [y/n]: y
> error: app/org.shotcut.Shotcut/x86_64/stable needs a later flatpak version (0.11.4)

It would be nice if flatpak would consider the "needs later flatpak version" error fatal only to that part of the update, and still update everything else.

>flatpak run eu.tiliado.NuvolaAppAmazonCloudPlayer                                                                           
>error: runtime/org.gnome.Platform/x86_64/3.32 not installed

So don't you want to do `flatpak install flathub org.gnome.Platform//3.32` not `flatpak install flathub org.gnome.Platform//3.30`?

**Comment by kayfay** [comment]
This morning `flatpak install flathub org.gnome.Platform//3.32` gave the same error about installing as `flatpak install flathub org.gnome.Platform//3.24` i'm not sure who maintains these repos so I included that all versions except 30 wheren't loading but it loaded now and the player loads. :unamused:
