### ISSUE TITLE
flatpak installation StorageType

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3035]
## Linux distribution and version
Fedora Rawhide Silveblue 

## Flatpak version
1.4.0

## Description of the problem
From the man page `man flatpak-installation`
```
       StorageType (string)
           The type of storage used for this installation. Possible values include: network, mmc, sdcard, harddisk.
```
I could not find any documentation what theses actually do. What is better for usb-media?
What are the differences?

**Comment by mwleeds** [comment]
There's some information in the commit that added `StorageType`: 34cf626029cae6a2336f6da829c6ea75e09c94e4

**Comment by damianatorrpm** [comment]
@mwleeds if it is there I don't see it or it's just the order which they are checked on

**Comment by mwleeds** [comment]
According to the commit it's used by GNOME Software. I haven't looked into how though.

**Comment by matthiasclasen** [comment]
I don't think gnome-software does anything with this information.  In any case, it is purely an informational field, no functionality is tied to it.
