### ISSUE TITLE
Error: Unable to load summary from remote flathub

### ISSUE THREAD

**Issue by drom98** [flatpak/flatpak#3038]
## Flatpak 1.2.4
When installing any app it gives me an error saying "error: Unable to load summary from remote flathub (...) handshake TLS"
Installing Spotify for example. (flatpak install flathub com.spotify.Client)

**Comment by mwleeds** [comment]
Duplicate of #2331

**Comment by mismatso** [comment]
I had the same problem, but it was because I had been playing with my authority certificates, to install an internal CA.

To rule out this problem, I recommend reconfiguring authority certificates to ensure that all known public CAs are being considered.

`sudo dpkg-reconfigure ca-certificates`
