### ISSUE TITLE
Create Flatpak from SFML C++ ?

### ISSUE THREAD

**Issue by richardeigenmann** [flatpak/flatpak#3041]

**Comment by richardeigenmann** [comment]
Can we create a Flatpak app from a C++ SFML library? 
A comment on the SMFL board indicates that this is not possible because SFML binds to Udev which is not supported by Flatpak. https://en.sfml-dev.org/forums/index.php?topic=20530.0

I have a sample SFML application that opens a window, shows a background picture, plays a sound and writes a text at the coordinates that change as the keyboard events are interpreted.

Being new to Flatpak I tried this json:
{
    "app-id": "org.richinet.LearnSfml",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "18.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "LearnSfml",
    "modules": [
        {
            "name": "sfml",
            "cleanup": [ "/bin" ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/SFML/SFML.git"
                }
            ],
            "buildsystem": "cmake",
            "cleanup": [
                    "/include",
                    "/lib"
            ]
        },
        {
            "name": "LearnSfml",
            "buildsystem": "simple",
            "build-commands": [
                "install -D LearnSfml /app/bin/LearnSfml"
            ],
            "sources": [
                {
                    "type": "file",
                    "path": "LearnSfml"
                }
            ]
        }
    ],
    "finish-args": [
         "--socket=x11",
         "--device=dri",
         "--socket=pulseaudio"
    ]
}

flatpak-builder build-dir --force-clean org.richinet.LearnSfml.json

ends in:
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- UDev not found.
-- UDev: You can specify includes: -DUDEV_PATH_INCLUDES=/opt/udev/include
--       currently found includes: UDEV_INCLUDE_DIR-NOTFOUND
-- UDev: You can specify libs: -DUDEV_PATH_LIB=/opt/udev/lib
--       currently found libs: UDEV_LIBRARIES-NOTFOUND
CMake Error at cmake/Modules/FindUDev.cmake:49 (MESSAGE):
  Could not find UDev library
Call Stack (most recent call first):
  cmake/Macros.cmake:398 (find_package)
  src/SFML/Window/CMakeLists.txt:278 (sfml_find_package)


-- Configuring incomplete, errors occurred!
See also "/run/build/sfml/CMakeFiles/CMakeOutput.log".
Error: module sfml: Child process exited with code 1

I am on OpenSuse 15.1. Flatpak 1.2.3

**Comment by TingPing** [comment]
While udev isn't fully functional inside Flatpak if a library has a hard dependency on it well you have to build it. Here is a manifest for it:https://github.com/flathub/shared-modules

**Comment by richardeigenmann** [comment]
Thanks. That pointer seems to have gotten me closer. 

{
    "app-id": "org.richinet.LearnSfml",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "18.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "LearnSfml",
    "modules": [
        "shared-modules/udev/udev-175.json",
        {
           "name": "foo"
        }, {
	    "name": "sfml",
            "cleanup": [ "/bin" ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/SFML/SFML.git"
                }
            ],
	    "buildsystem": "cmake",
	    "cleanup": [
		    "/include"
            ]
        }, {
            "name": "LearnSfml",
            "buildsystem": "simple",
            "build-commands": [
                "install -D LearnSfml /app/bin/LearnSfml"
            ],
            "sources": [
                {
                    "type": "file",
                    "path": "LearnSfml"
                }
            ]
        }
    ],
    "finish-args": [
  	 "--socket=x11",
	 "--device=dri",
	 "--socket=pulseaudio"
    ]
}

My app starts to open a Window and then crashes with this message:

LearnSfml: symbol lookup error: LearnSfml: undefined symbol: _ZNK2sf6Window6isOpenEv

I will have to dig deeper.....

**Comment by refi64** [comment]
At a glance, your problem likely is that you're building your application
outside the flatpak environment. Build it inside flatpak-builder.

**Comment by richardeigenmann** [comment]
Here is the final json file:

{
    "app-id": "org.richinet.LearnSfml",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "18.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "FlatpakLaunchLearnSfml.sh",
    "modules": [
        "shared-modules/udev/udev-175.json",
        {
           "name": "foo"
        }, {
	        "name": "sfml",
            "cleanup": [ "/bin" ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/SFML/SFML.git"
                }
            ],
	        "buildsystem": "cmake",
	        "cleanup": [
		        "/include"
            ]
        }, {
            "name": "LearnSfml",
            "buildsystem": "cmake",
            "build-commands": [
                "install -D FlatpakLaunchLearnSfml.sh /app/bin/FlatpakLaunchLearnSfml.sh",
                "install -D LearnSfml /app/bin/LearnSfml",
                "install -D Davos.jpg /app/bin/Davos.jpg",
                "install -D ChangaOne-Regular.ttf /app/bin/ChangaOne-Regular.ttf ",
                "install -D sound.ogg /app/bin/sound.ogg"
            ],
            "sources": [
                {
                    "type": "dir",
                    "path": "."
                }
            ]
        }
    ],
    "finish-args": [
  	 "--socket=x11",
	 "--device=dri",
	 "--socket=pulseaudio"
    ]
}

The working SFML demo project can be found here: https://github.com/richardeigenmann/LearnSfml
