### ISSUE TITLE
I need help with making a runtime extension library

### ISSUE THREAD

**Issue by trappedinspacetime** [flatpak/flatpak#3042]
## Linux distribution and version
Ubuntu 16.04
## Flatpak version
Flatpak 1.3.4
## Description of the problem
I want to make a flatpak extension  to disable client side decorations from [gtk3-nocs](https://github.com/PCMan/gtk3-nocsd.git)
I built the shared library  and copied it to `/home/$user/.var/app/com.github.birros.WebArchives/`
then issued `override`
      
       flatpak --user override --env=LD_PRELOAD=/home/$user/.var/app/com.github.birros.WebArchives/libgtk3-nocsd.so

and run it like 

     flatpak run --env=GTK_CSD=0  --env=LD_PRELOAD=/usr/lib/sdk/gtk3-nocsd/libgtk3-nocsd.so com.github.birros.WebArchives

which works well.

Instead what I want to make `Gnome` or `freedesktop` extension such as `org.freedesktop.Platform.GL.default` extension to load it to any GUI application and run it like:

      flatpak run --env=GTK_CSD=0  --env=LD_PRELOAD=/usr/lib/sdk/gtk3-nocsd/libgtk3-nocsd.so com.github.birros.WebArchives 

## Steps to reproduce

 I created the following manifest 

    {
      "id": "org.freedesktop.Sdk.Extension.gtk3-nocsd",
      "branch": "18.08",
      "runtime": "org.freedesktop.Sdk",
      "build-extension": true,
      "sdk": "org.freedesktop.Sdk",
      "runtime-version": "18.08",
      "separate-locales": false,
      "appstream-compose": false,
      "modules": [
        {
          "name": "gtk3-nocsd",
          "buildsystem": "simple",
          "build-commands": [
            "make",
            "echo ${FLATPAK_DEST}",
            "cp libgtk3-nocsd.so.0 ${FLATPAK_DEST}/libgtk3-nocsd.so"
          ],
          "sources": [
            {
              "type": "git",
              "url": "https://github.com/PCMan/gtk3-nocsd.git",
              "branch":"master"
            }
          ]
        }
      ]
    }

but I couldn't make it work.
I need   help with the manifest file.

**Comment by refi64** [comment]
This is only going to apply to apps using the Sdk as their runtime, which
isn't many. Afaik there is no universal solution for this.

**Comment by trappedinspacetime** [comment]
@refi64 Thank you for responding. How can I build it for `org.gnome.Platform`? When I try it, I get `error: No extension point matching org.gnome.Platform.Extension.gtk3-nocsd`

**Comment by refi64** [comment]
You can't unless the platform itself already defines the extension point,
which is why I said afaik there's no generic way to do this.

**Comment by trappedinspacetime** [comment]
@refi64  how come GL or theme extensions works for any application?

**Comment by refi64** [comment]
Because the runtime defines them as extension points, check them out via `flatpak info -m org.freedesktop.Platform//18.08` or with another runtime.

**Comment by trappedinspacetime** [comment]
@refi64 Do I have any chance to  override those settings and add my extension?

**Comment by refi64** [comment]
AFAIK no, not without building the runtime yourself (there may be a slick way to do this without a full runtime build, e.g. pull the runtime and add an extra commit to add the metadata separately, but off the top of my head I can't say for sure.

For future reference, in general the [Flatpak mailing list](https://lists.freedesktop.org/mailman/listinfo/flatpak) is better for questions like these.

**Comment by TingPing** [comment]
I think this has been covered, the runtime determines what extensions it will load, so that is what needs changed.
