### ISSUE TITLE
Setting default locales without disregarding AccountServices' language dbus parameter

### ISSUE THREAD

**Issue by mazen-asef** [flatpak/flatpak#3043]
the xa.language configuration for the core file of flatpak already sets all the subset locales needed for download.
However, setting this configuration disables the functionality that happens over AccountServices' dbus.

I would like to set this configuration for multiple locales and make this issue https://gitlab.gnome.org/GNOME/gnome-software/issues/697
resolved by only fetching useful content on gnome-software. This would require setting a new key (e.g. something named xa.default-languages)

Is this the best way to do it? Also, browsing the issues, this could potentionally address https://github.com/flatpak/flatpak/issues/1938, by making less dbus calls and without adding a new configuration key.

**Comment by ramcq** [comment]
> the xa.language configuration for the core file of flatpak already sets all the subset locales needed for download.
> However, setting this configuration disables the functionality that happens over AccountServices' dbus.
> 
> I would like to set this configuration for multiple locales and make this issue https://gitlab.gnome.org/GNOME/gnome-software/issues/697
> resolved by only fetching useful content on gnome-software. This would require setting a new key (e.g. something named xa.default-languages)

The idea here was to basically have a way for the user to indicate >1 language (besides their locale) they might be interested in seeing/reading/etc - maybe there is another place in the desktop that already allows this too.

> 
> Is this the best way to do it? Also, browsing the issues, this could potentionally address #1938, by making less dbus calls and without adding a new configuration key.

These seem unrelated, in as much as the default-languages key would be added to the runtime-determined (ie, calling AS over dbus) list - but related in that if you were implementing this nicely you could also add some in-memory caching of that result and fix that bug too. :)
