### ISSUE TITLE
End of Life message is confusing because the version number is missing

### ISSUE THREAD

**Issue by ocrete** [flatpak/flatpak#3046]
## Linux distribution and version
Fedora 30
## Flatpak version
flatpak-1.4.2-3.fc30.x86_64
## Description of the problem
Flatpak EOL message gives the impression that the whole org.gnome.Platform is EOL while it is actually just a specific version.

## Steps to reproduce

Install org.gnome.Platform/3.24 then run flatpak upgrade

I get:
nfo: org.gnome.Platform is end-of-life, with reason: GNOME 3.24 runtime is no longer supported as of 11th January 2019. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: GNOME 3.24 runtime is no longer supported as of 11th January 2019. Please ask your application developer to migrate to a supported platform.

**Comment by matthiasclasen** [comment]
But the message you cite does contain a version number: GNOME 3.24 runtime

**Comment by mikeSGman** [comment]
@ocrete - 'flatpak uninstall --unused' took care of it for me.  No need to invoke '--user' by the way.  The error on my part, was that I was unaware that flatpak stored old version of runtimes after updating them.  The solution as to remove the unused ones in my case.  YMMV.  HTH.

**Comment by ocrete** [comment]
> But the message you cite does contain a version number: GNOME 3.24 runtime

I think it would be easier to understand if it said "org.gnome.Platform/3.24 is end-of-life,..."

The way I understood it when I read it is "all of gnome is EOL, 3.24 is the version I have, but I can't find a new one to upgrade to"
