### ISSUE TITLE
pkg-config not reading from /app/lib/pkgconfig by default

### ISSUE THREAD

**Issue by cfoch** [flatpak/flatpak#3050]
## Linux distribution and version
Fedora 30
## Flatpak version
1.4.2

## Description of the problem
pkg-config does not recognize .pc files installed at `/app/lib/pkgconfig`. As far as I know, the PKG_CONFIG_PATH should consider first `/app/lib/pkgconfig` but that is not happening. However, if I run `PKG_CONFIG_PATH=/app/lib/pkgconfig`, pkgconfig is able to read info from files at that path.

## Steps to reproduce
For example, in [this manifest](https://gist.github.com/cfoch/0faf7cb9fecb3d8e172473a90d3509a3), these are the following results:

```
[cfoch@localhost cheese]$ flatpak run --command=pkg-config -d org.gnome.Cheese --modversion gstreamer-1.0 
1.14.4
[cfoch@localhost cheese]$ flatpak run --env=PKG_CONFIG_PATH=/app/lib/pkgconfig --command=pkg-config -d org.gnome.Cheese --modversion gstreamer-1.0 
1.16.0

```
`
I think this is the problem, why when I try to compile Cheese against GStreamer 1.16.0, it is linked again from libraries from /usr/lib instead of /app/lib

```
[📦 org.gnome.Cheese ~]$ ldd /app/bin/cheese | grep gst
	libgstreamer-1.0.so.0 => /app/lib/libgstreamer-1.0.so.0 (0x00007f26cee23000)
	libgstpbutils-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x00007f26cdea7000)
	libgstaudio-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x00007f26cde2d000)
	libclutter-gst-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libclutter-gst-3.0.so.0 (0x00007f26cde02000)
	libgstvideo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007f26cdd60000)
	libgsttag-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x00007f26cdca0000)
	libgstbase-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007f26cd442000)
`
```

**Comment by TingPing** [comment]
Runtime issues are reported here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by valentindavid** [comment]
flatpak-builder already adds /app/lib/pkgconfig in `PKG_CONFIG_PATH`. This is not an issue.

**Comment by nanonyme** [comment]
Note that in reality the party responsible of setting PKG_CONFIG_PATH is flatpak-builder https://github.com/flatpak/flatpak-builder/blob/1b546771c532f75ebcdc2be98cf2eecb84804ce8/src/builder-options.c#L977 ; everything *should* work fine out of the box. The thing is though that setting PKG_CONFIG_PATH before running flatpak-builder will override flatpak-builder default and break things. This is most likely intended behaviour by @alexlarsson
