### ISSUE TITLE
Recent files

### ISSUE THREAD

**Issue by silvain** [flatpak/flatpak#3051]

**Comment by mwleeds** [comment]
Please provide more specific information in bug reports.

**Comment by silvain** [comment]
This problem seems to be a long term problem.
I had Ubuntu 18, now I have Ubuntu 20.04, and Flatpak 1.11.1
When I save a file from a flatpak application (for exemple Scribus 1.5.7), the file is not recorded in the «Recent fles» list.
And this is presently the main on only drawback of using flatpak for me.
