### ISSUE TITLE
Network share permission granularity

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#3054]
Would it be possible for Flatpak to offer more options for the `--share=network` permission?

For cases where you want to offer access to the local network without allowing external connections. I understand daemon-like behavior is not in the project's scope but offering a detached browser GUI is another use for that. Without allowing full internet access to programs. Maybe I'm alone with this but I'm also very concerned how much data even the simplest programs try to extract from the users so Flatpak is great for that with `--unshare`, but limits my options for local network access.

[Private Address Space](https://tools.ietf.org/html/rfc1918#section-3).

**Comment by mwleeds** [comment]
This is currently technically difficult because kernel APIs require root to do network namespacing, and Flatpak runs unprivileged. See the discussion here: https://lists.freedesktop.org/archives/flatpak/2019-September/001691.html

**Comment by hadess** [comment]
See also [Support local network privacy in your app](https://developer.apple.com/videos/play/wwdc2020/10110/) which explains how local network and multicast accesses will now require explicit permissions in iOS 14 (probably the same permission we want use for [mDNS access](https://github.com/flatpak/xdg-desktop-portal/issues/505))

**Comment by hadess** [comment]
> See also [Support local network privacy in your app](https://developer.apple.com/videos/play/wwdc2020/10110/) which explains how local network and multicast accesses will now require explicit permissions in iOS 14 (probably the same permission we want use for [mDNS access](https://github.com/flatpak/xdg-desktop-portal/issues/505))

More information about the iOS implementation on the application side:
https://developer.apple.com/forums/thread/663858
In particular:
https://developer.apple.com/forums/thread/663874

**Comment by ssokolow** [comment]
For the record, I think a more useful example would be having the ability to take something that's available via Flathub and has a history of security vulnerabilities, such as Zoom, and blacklist access to the local subnet and non-routable IP ranges, so it can't be used as a relay to attack stuff behind a border firewall, such as network printers or IoT devices that aren't having security updates installed for whatever reason.

**Comment by pabloab** [comment]
As [mentioned](https://github.com/flathub/com.sweethome3d.Sweethome3d/issues/40#issuecomment-1433383702), if I understand you correctly what you want is something similar to using [OpenSnitch](https://github.com/evilsocket/opensnitch/), to ask/grant on every particular network request. Alike Android, asking only when the app use more privileges, instead of an all or nothing approach.

**Comment by digitalsignalperson** [comment]
> kernel APIs require root to do network namespacing, and Flatpak runs unprivileged

As of today we have options like slirp4netns, pasta, and netavark.

This is used as default with rootless podman, and netavark is also available. https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md#:~:text=for%20rootless%20containers%2C%20the%20default%20network%20mode%20is%20slirp4netns

For an example with bubblewrap, bubblejail has implemented slirp4netns with options for 
- setting the address or device to bind to
- disabling host loopback access
- and setting DNS servers to use

https://github.com/igo95862/bubblejail/blob/547c4692b85653a0a5774620b31a0ad3158b6ef6/src/bubblejail/services.py#L826

As far as I understand, you need to use network namespaces to prevent sandbox escape via abstract sockets like with Xorg (also mentioned here https://github.com/flatpak/flatpak/issues/5161)

**Comment by hfiguiere** [comment]
I think this is just a dupe of #1202
