### ISSUE TITLE
GPG signatures found but none are in trusted keyring, KDE

### ISSUE THREAD

**Issue by nandantumu** [flatpak/flatpak#3055]
## Linux distribution and version
Ubuntu 18.04.03 LTS
## Flatpak version
Flatpak 1.4.2
## Description of the problem
Trying to install KDE apps from flatpak, says that GPG signatures are not in the trusted keyring.
## Steps to reproduce
```
 $ flatpak remote-add --if-not-exists kde http://distribute.kde.org/flatpak-apps-testing


Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/mlab/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: GPG signatures found, but none are in trusted keyring

```

**Comment by mwleeds** [comment]
You probably need to either use the `--gpg-import` option to import the GPG keyring for that remote, or use a `.flatpakrepo` file if the remote provides one, because that would include the GPG key.
