### ISSUE TITLE
Support for libpam-tmp and local TMP directory

### ISSUE THREAD

**Issue by choffee** [flatpak/flatpak#3057]
## Linux distribution and version
Debian buster
## Flatpak version
1.2.4
## Description of the problem
Flatpak apps don't have permission to write to /tmp/user/1000 which libpam-tmp sets up as a user based tmp space and set the environment variable TMP to point to. 
## Steps to reproduce

Install libpam-tmp to use secure tmp directirectoy eg. /tmp/user/1000
Install spotify flatpak from flathub
It crashes out as it does not have access to the tmp dir.

The fix is to set environment variable TMP=/tmp in that app but it seems this might be a sensible default for flatpak for all apps so they all use a local /tmp dir that is isolated and gets cleaned up with the app.

## Workaround
Create /var/lib/flatpak/overrides/com.spotify.Client
```
[Environment]
TMP=/tmp
```

Issues from Spotify Repo.
https://github.com/flathub/com.spotify.Client/issues/84
https://github.com/flathub/com.spotify.Client/issues/48

**Comment by GD-fix** [comment]
I had created the file with content:
```[Environment]
TMP=/tmp 
ROOT=/
HOME=/home
```
It doesn't support dictionary paths (really or symbolic links) on /tmp, /var/tmp or on other paths on partition, containing root (/) and doesn't read the history journal all the same...

**Comment by GD-fix** [comment]
The workable variant (for GoldenDict-ng at least) is to add the needed paths in System Parameters / Applications Permissions:
![GD-ng_flatpak_perm_paths](https://github.com/flatpak/flatpak/assets/21008593/c649d229-5504-410f-8cae-de0b4f479516)

**Comment by smcv** [comment]
@GD-fix:
> I had created the file with content: [some text that did not include `[Environment]`]

No, that will not work. To use the workaround from the original issue report, you must include the `[Environment]` section heading.

**Comment by smcv** [comment]
Flatpak automatically unsets `TMP` since version 1.14.1 and 1.15.x (commit d8695f30):

```
$ TMP=/wrong flatpak run --command=bash org.gnome.Recipes
[📦 org.gnome.Recipes ~]$ echo ${TMP:-unset or empty}
unset or empty
```

If possible I would recommend upgrading.

In older versions of Flatpak, you can use `sudo flatpak override --env=TMP=/tmp`.

**Comment by GD-fix** [comment]
The variant with System Parameters / Applications Permissions works and I don't need anything else.

But still thanks for the info
