### ISSUE TITLE
Show a warning when running a flatpak which has updates

### ISSUE THREAD

**Issue by digulla** [flatpak/flatpak#3060]
## Linux distribution and version
OpenSUSE 15.1
## Flatpak version
Flatpak 1.2.3
## Description of the problem
When running a flatpak that has updates, I would like to get a message so I can install fixes and updates timely.

**Comment by mwleeds** [comment]
Most people run flatpaks from a desktop environment not a CLI, so I don't think a warning would be very helpful. But it would make sense for there to be a portal allowing applications to find out if they have an update available, so they could inform the user.

**Comment by digulla** [comment]
It would be nice if there was an API in flatpak itself so CLI and UI code can query it.
The solution shouldn't force every single application to add code for the check.

**Comment by matthiasclasen** [comment]
I think it is up to individual applications to show such a warning. the flatpak portal has api to let apps detect if updates are available: https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.portal.Flatpak.xml#L244

**Comment by digulla** [comment]
I would expect that you offer a hook or something where packagers can add a small script to ping the desktop's notification service.
I think that it's not the task of the individual application to do that for two reasons:

- It's a functionality of flatpak, not the app (the app also doesn't implement `flatpak update`). The app itself is not really affected by this nor does flatpak need the support/help of the application to do this - it already knows everything necessary.
- It would have to be implemented in every application. This is a clear violation of the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
