### ISSUE TITLE
Notify user of package storage size to be downloaded.

### ISSUE THREAD

**Issue by TZubiri** [flatpak/flatpak#3062]
Hello, I'm used to aptitude for installing distributions, I'm usually notified of the amount of data that is going to be transferred, this is useful for estimating download time and vital for metered connections like 4G.

Thank you.

**Comment by TingPing** [comment]
It already gives a rough estimate of largest possible download size (the actual size is often smaller but its hard to know that ahead of time).

It sounds like you are using an outdated `flatpak`.

**Comment by TZubiri** [comment]
You  were right! I'm using v 1.08, which is what I got by running 'apt-get install flatpak' on Ubuntu 18.04

**Comment by TingPing** [comment]
https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak
