### ISSUE TITLE
flatpak run fails with "prctl(PR_SET_SECCOMP): Invalid argument" on aarch64 (odroid)

### ISSUE THREAD

**Issue by MarcoFalke** [flatpak/flatpak#3069]
## Linux distribution and version

```sh
# lsb_release -c
Codename:	bionic
```

## Flatpak version

```sh
# flatpak --version
Flatpak 1.0.8
# uname -nm
odroid aarch64
```

## Description of the problem

```sh
root@odroid:~# flatpak run org.gimp.GIMP
bwrap: bwrap: prctl(PR_SET_SECCOMP): Invalid argument
prctl(PR_SET_SECCOMP): Invalid argument
root@odroid:~# flatpak run org.bitcoincore.bitcoin-qt
bwrap: bwrap: prctl(PR_SET_SECCOMP): Invalid argument
prctl(PR_SET_SECCOMP): Invalid argument
```

## Steps to reproduce

* Install Bionic from ports to odroid c2
* (on odroid) Install `flatpak`, install any package from flathub with flatpak
* `flatpak run ...` fails (see above)

See also related bug report for different package in Bionic, which was fixed in Cosmic: https://bugs.launchpad.net/stress-ng/+bug/1801856

**Comment by matthiasclasen** [comment]
This looks like a bubblewrap issue.

**Comment by tallero** [comment]
It happens on pmos/hammerhead, too.

**Comment by shvetsnikita** [comment]
Getting same issue on Lenovo X13s (Snapdragon 8cx Gen 3) with Linux 6.2rc3 ([config](https://github.com/steev/linux/blob/sc8280xp-next-20230112/arch/arm64/configs/defconfig)) and Flatpak 1.14.1 on Debian 12. bubblewrap version is 0.7.0.

**Comment by smcv** [comment]
This could mean your kernel doesn't have seccomp enabled, in which case general-purpose sandboxing software like Flatpak is not going to work there.

**Comment by MarcoFalke** [comment]
Thank you. Closing for now, as I no longer have the odroid. Maybe the error message can be improved, but I am not sure if this is a flatpak or bubblewrap issue.

**Comment by smcv** [comment]
> Maybe the error message can be improved, but I am not sure if this is a flatpak or bubblewrap issue.

The error message comes from bubblewrap, and it does not have enough information to say much beyond "Invalid argument". That is the only information we get from the kernel (specifically, we try to add a seccomp filter and it replies with error code `EINVAL`).

**Comment by smcv** [comment]
containers/bubblewrap#550 tries to clarify the error message in this case.
