### ISSUE TITLE
gpg-agent error in flatpak

### ISSUE THREAD

**Issue by pizzadude** [flatpak/flatpak#3073]
Recently, If I use flatpak in the terminal, for example, "flatpak update", I get a ton of errors about gpg-agent.

Looking for updates…
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established

I run Fedora 30 KDE with testing repos enabled.

I found a post on Arch Linux forums of some people having the same issue: https://bbs.archlinux.org/viewtopic.php?id=248745

**Comment by mwleeds** [comment]
It would be helpful to also have the output of `ostree --version`, since OSTree 2019.3 included GPG related changes. Or if you don't have the `ostree` command installed check the version of the package providing libostree.

**Comment by mwleeds** [comment]
Looks like 2019.3 hasn't made it into Fedora 30 according to https://apps.fedoraproject.org/packages/ostree

**Comment by Erick555** [comment]
I have same issue and recently updated ostree to 2019.3

**Comment by Erick555** [comment]
It's already reported there: https://github.com/ostreedev/ostree/issues/1907

**Comment by JustinLex** [comment]
I believe a fix [has already been merged into ostree](https://github.com/ostreedev/ostree/commit/522d31b2d4604026f1c0a442887ca9d4b319e9cc).
