### ISSUE TITLE
`flatpak uninstall` prompt doesn't specify operations, asks unclear question 

### ISSUE THREAD

**Issue by alexsapps** [flatpak/flatpak#3075]
## Linux distribution and version
Chrome OS Crostini Debian 9

## Flatpak version
1.2.4

## Description of the problem

Regarding this interaction:
```
$ flatpak uninstall org.freedesktop.Platform

        ID                                       Arch            Branch
 1.     org.freedesktop.Platform                 x86_64          18.08
 2.     org.freedesktop.Platform.Locale          x86_64          18.08

Proceed with these changes to the Default system installation? [Y/n]: 
```

The list above specifies runtimes but not what changes will occur to those runtimes, making it unclear what "Proceed with these changes" refers to.

**Comment by mwleeds** [comment]
Yeah, and I think this is more unclear with install or update transactions, where you might have a mix of some things being updated and others being installed.

**Comment by mwleeds** [comment]
To avoid adding another column we could add a line before each set of packages, like:

The following items will be **removed**:
```
       ID                                       Arch            Branch
 1.     org.freedesktop.Platform                 x86_64          18.08
 2.     org.freedesktop.Platform.Locale          x86_64          18.08
```

The following items will be **updated**:
```
       ID                                       Arch            Branch
 1.     org.gnome.Platform                 x86_64          3.32
 2.     org.gnome.Platform.Locale          x86_64          3.32
```

**Comment by mwleeds** [comment]
For `flatpak update`, there is an `Op` column in the table, but I'm not sure a single letter (`i`, `u`, or `r`) is very clear.

**Comment by matthiasclasen** [comment]
changing it to complete words would be very easy

**Comment by matthiasclasen** [comment]
The reason that the question is phrased the way it is is that in general, there can be a mix of different operations in the list.

**Comment by mwleeds** [comment]
Thanks, looks like despite the commit message, that patch shows the op column for all transactions, not just install.
