### ISSUE TITLE
Flatpak support for smart cards (yubikey)

### ISSUE THREAD

**Issue by tkuraku** [flatpak/flatpak#3076]
## Linux distribution and version
Debian 10
Fedora 30
RHEL 8
Centos 7

## Flatpak version
Debian - Flatpak 1.2.4
Fedora 30 - Don't have my install up and running.
## Description of the problem
I would like to use Remmina from flathub to remote into my windows work computers which requires use of my smart card, but the flatpak version of Remmina doesn't seem to support smart card pass through. The version of Remmina in the distribution repositories (Debian and Fedora) support this perfectly. This is especially a problem because on Centos/RHEL there isn't a non flatpak build of Remmina available in EPEL. Does flatpak support using smart cards with the sand boxed apps or is this a problem with the Remmina flatpak?
## Steps to reproduce
install the flatpak Remmina and try to share a smart card with the remote machine and it doesn't work.
Install through apt or dnf and it works great.

**Comment by donpellegrino** [comment]
I have verified this issue with CentOS 7.7.1908, flatpak 1.0.9, and org.gnome.Evolution/x86_64/stable. The lack of Smart Card support in flatpak prevents the use of Smart Cards for email encryption/decryption in Evolution.

**Comment by fbruetting** [comment]
If I grant a flatpak package system access, would that enable smartcard functionality if it works in the RPM package?

**Comment by tkuraku** [comment]
I am not sure. The rpm/deb version works with smart cards fine. Is this a new portal that needs to be implemented in flatpak?

**Comment by fbruetting** [comment]
I guess the portal needs to pass-through opensc (or something like that). If you pass the whole card reader device to a flatpak, it’s blocked for other applications.

**Comment by TingPing** [comment]
Yes a portal has to be implemented.

**Comment by tkuraku** [comment]
I think this is an important feature, two factor authentication with a smart card is a common use case. Without this feature flatpak isn't really a viable alternative to rpm/deb packaging.

**Comment by tkuraku** [comment]
Others are trying to use smart cards with evolution flatpak and having the same problem.

https://github.com/flathub/org.gnome.Evolution/issues/16

**Comment by tkuraku** [comment]
Looks like smart cards support has been implemented in new version of flatpak with the pcsc socket.. I haven't been able to test it yet.
