### ISSUE TITLE
Add an easy way to list files provided by a package

### ISSUE THREAD

**Issue by gdesmott** [flatpak/flatpak#3079]
One thing I missed when I started using flatpak was an easy way to list all the files provided by a given package, like `dpkg -L` or `rpm -ql`.
I realize we can find it by digging through the file system but I think having a `flatpak list-files` command or something like that would be useful.

**Comment by mwleeds** [comment]
Would be neat if at the ostree level we implemented a command to list the files in a commit as an ASCII tree:
```
$ ostree list-files app/org.gnome.Builder/x86_64/3.32
bin/
   \__gnome-builder
export/
        \_icons/
                \_org.gnome.Builder.png
```
The flatpak could just call out to that functionality.

**Comment by matthiasclasen** [comment]
Isn't

```
ostree --repo=/var/lib/flatpak/repo ls -R fedora:app/org.gnome.gedit/x86_64/stable
```

basically that ?

**Comment by matthiasclasen** [comment]
And 

```
tree `flatpak info -l org.gnome.gedit`
```
is even closer.

**Comment by kjcole** [comment]
The solution offered really isn't that close to either `rpm -ql` or `dpkg -L` being unnecessarily complicated for the user, not resulting in anything that can be easily piped into something else... Methinks:

```
find $(flatpak info -l ...)/files -type f
 ```

where `...` is the application ID is a better answer to the issue, but it still seems to me that a built-in command would be better than Bash magic.
