### ISSUE TITLE
libflatpak API makes unnecessary burden on adding refs to installation

### ISSUE THREAD

**Issue by jkonecny12** [flatpak/flatpak#3083]
## Linux distribution and version
Fedora 31

## Flatpak version
1.4.2-5

## Description of the problem
Description of problem:
To add a ref to the ``Transaction.add_install()`` method is somehow unnecessary complicated. The reason is that the Ref object give you all the required information (e.g. ``get_kind()``, ``get_name()``, ``get_arch()``) but then ``add_install()`` is not taking the Ref object but you have to create a string from all these information.

You basically have to do something like:

``transalted_kind + "/" + ref.get_name() + "/" + ref.get_arch() + "/" + ref.get_branch()``

instead of just

``Transaction.add_install_ref(ref) ``

It would make an experience much better by giving you proposed API instead of doing the above work on every use of the flatpak API.

Another solution would be to add new ``get_full_ref()`` method which would make this for you. But I would definitely prefer the first proposed solution.

**Comment by refi64** [comment]
What about flatpak_ref_format_ref:
http://docs.flatpak.org/en/latest/libflatpak-api-reference.html#flatpak-ref-format-ref

**Comment by jkonecny12** [comment]
@refi64 hmm I've missed that. Thanks, I'll look on that :)

**Comment by jkonecny12** [comment]
@refi64 thanks a lot. I was blind to miss this before. Thanks to you I've updated my solution to a better variant. 

Closing this issue now.
