### ISSUE TITLE
File picker in flatpak applications ignores dconf settings

### ISSUE THREAD

**Issue by TiZ-EX1** [flatpak/flatpak#3087]
## Linux distribution and version
Xubuntu 18.04

## Flatpak version
1.4.2 via PPA

## Description of the problem
All applications installed and run via flatpak, when they present the file picker, it unnecessarily fills the entire screen, and ignores my system setting to sort directories before files.

## Steps to reproduce
Run any Flatpak application and open a file.

**Comment by TingPing** [comment]
You need to provide more information.

Is this a file chooser ran in app or via the portal. What are the permissions of the specific application `flatpak info --show-permissions ...`.

**Comment by TiZ-EX1** [comment]
Sure, I'll try to be more specific. It's every time the GTK file picker appears. Let's say, for example, adding an attachment in Discord. Or opening a file in Geany.

The permissions info you've requested seems to include my global overrides. Here's that info for you:

```
NKU18R0311 ~ $ cat /var/lib/flatpak/overrides/global 
[Context]
filesystems=xdg-config/gtk-3.0:ro;/xusr:ro;home;
NKU18R0311 ~ $ flatpak info --show-permissions org.geany.Geany
[Context]
shared=network;ipc;
sockets=x11;
filesystems=host;/tmp;xdg-config/gtk-3.0:ro;/xusr:ro;home;
```

**Comment by TingPing** [comment]
OK so that all makes perfect sense.

Geany is *not* using the file chooser portal as it should be so the file chooser is ran inside the sandbox.

Geany does not have DConf permissions (nor should it probably).

So it behaves as expected.

The solution is to patch Geany to use the portals (`GtkFileChooserNative`).

**Comment by TingPing** [comment]
Also Discord will get that fix "soon" also: https://github.com/electron/electron/pull/19159

**Comment by TiZ-EX1** [comment]
Oh, I see. Thank you for explaining it. Is it possible to change these settings inside the sandbox in the meantime, or otherwise expose the settings to it without just giving it all of DConf? Are the settings being used now (directories with files, full screen height) the GTK defaults?

**Comment by TingPing** [comment]
No you would have to expose all of DConf.

The settings are probably indeed the defaults. In a newer runtime (GNOME 3.34) the settings would actually be saved properly but only privately per each application.

**Comment by TiZ-EX1** [comment]
Thanks for the information.
