### ISSUE TITLE
[QUESTION] does flatpak support oss and BSD?

### ISSUE THREAD

**Issue by user5145** [flatpak/flatpak#3089]
does flatpak support open sound system and are there any plans to support BSD systems in the distant future?

**Comment by refi64** [comment]
For OSS I'm going to guess "no", it's been largely superceded for over a decade and a half.

For BSD: https://github.com/flatpak/flatpak/issues/1985

**Comment by user5145** [comment]
thanks

**Comment by theoden8** [comment]
#1985 page not found

**Comment by TingPing** [comment]
Flatpak is heavily designed around Linux namespaces. BSD would need an equivalent API.

**Comment by ThisNekoGuy** [comment]
@TingPing Sorry for the necro but... Why has no such API ever been implemented...?
I'd imagine that Flatpak would benefit BSD adoption (including for myself, personally)

**Comment by TingPing** [comment]
You would really need to discuss it with people in the BSD community.

I would guess that few people want to copy Linux namespaces. Whatever else they come up with would still require effort to port Flatpak to. It all seems unlikely.
