### ISSUE TITLE
Opt-out for extensions 

### ISSUE THREAD

**Issue by nanonyme** [flatpak/flatpak#3090]
We were discussing with @TingPing earlier that it would be useful to be possible to have auto-install extensions with user opt-out for cases like gst-vaapi. Currently we can only make that kind of things opt-in even if it works for most users.

Possible syntax `flatpak mask org.freedesktop.Platform.GStreamer.gstreamer-vaapi//19.08`

**Comment by Erick555** [comment]
This seems possible right now, albeit little tricky:
```
# echo "deny org.freedesktop.Platform.openh264/*" > /var/lib/flatpak/repo/flathub.filter
$ flatpak remote-modify --filter=flathub.filter flathub
```
