### ISSUE TITLE
ref not found just after saying it was found

### ISSUE THREAD

**Issue by AnwarShah** [flatpak/flatpak#3123]
## Ref is said found when tried to use by then showing error as not found

I've used flatpak create-usb to test copy some flatpak app installation. The copy was made in internal drive instead of a usb. Then on other os, I added the repo and tried to install `html5-codecs` by 

    flatpak install local html5-codecs 

The `local` repo is correctly configured and shows the apps from `flatpak remote-ls local` command. But the above command fails by outputting 

```

Found ref ‘runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08’ in remote ‘local’ (system).
Use this ref? [Y/n]: y
error: No such ref 'runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08' in remote local

```

This is hilarious. On first line it syas it found the ref and just after the prompt, it says it didn't ! 

There should be some sane error message regarding actual problem

**Comment by mwleeds** [comment]
Any chance you could give a full set of steps to reproduce, including the `flatpak create-usb` command used and the way you added the `local` remote?

**Comment by mwleeds** [comment]
Off-hand my guess is maybe you don't have a collection ID configured on the `local` remote?

Generally the use case for installing from a local drive is you don't configure a new remote. You just have e.g. flathub configured and if the stuff on the drive is from flathub and is at least as new as what's on Flathub, it will be used transparently via `flatpak install flathub ...`. That scheme has the advantage that updates will come from flathub, whereas if you install from a local repo you have to keep updates flowing to it in order for the apps to be updated.

**Comment by mwleeds** [comment]
I do agree the error message could also be more informative.

**Comment by AnwarShah** [comment]
@mwleeds I've created the repo using a command 

`flatpak create-usb  /mnt/anwar/Flatpak org.gnome.Totem.Codecs/x86_64/stable` here `/mnt/anwar/Flatpak` is a location in internal partition, not a usb. But the repo was created fine.

Then on another system I tried using 

`flatpak remote-add local --no-gpg-verify --title="Nice Title" repo` navigating to the `/mnt/anwar/Flatpak/.ostree` directory. The repo was added fine and I was able to list the applications in that repo. 

but when tried to install using a command like this 
`flatpak install --runtime local html5-codec` it generates the error message

**Comment by mwleeds** [comment]
Again, that's not how `create-usb` is intended to be used. You shouldn't add a `local` remote at all. If you're doing the install on the same machine as `create-usb`, the relevant remote (e.g. flathub) is already configured so you should do `flatpak install --runtime flathub html5-codec`.

I submitted an update to the docs to try to make this more clear, see if it makes sense: https://github.com/flatpak/flatpak/pull/3137

**Comment by AnwarShah** [comment]
@mwleeds Ok, that make sense. But why shouldn't I install it this way when I can use usb? I use case is, I have two Linux distro installed and wanted to install in one from internet and another from local repo. Is it not supported?

**Comment by mwleeds** [comment]
> @mwleeds Ok, that make sense. But why shouldn't I install it this way when I can use usb? I use case is, I have two Linux distro installed and wanted to install in one from internet and another from local repo. Is it not supported?

If you add a GPG key and a collection ID to your remote pointing to your local repo, installing directly from it should work I think (the GPG key being Flathub's and the collection ID being `org.flathub.Stable`). See the `--gpg-import` and `--collection-id` options of `flatpak remote-add`.

But the officially supported use case is to install from Flathub and in any case where the locally mounted repo provides something that's as up to date as Flathub, it will be used. Of course if you're offline, the local repo has the most up-to-date content available so it will be used even if the Internet has something newer. The reason it works this way is that it's assumed that if you're online and there's something newer on the Internet than what you have locally, you want what's on the Internet (although ideally we would update from the local source first and then from the Internet so the delta of the Internet update would be smaller).
