### ISSUE TITLE
Various issues on Debian 10 (Flatpak 1.2.4)

### ISSUE THREAD

**Issue by go-ten** [flatpak/flatpak#3126]
Hi,

On my Debian 10 Buster Flatpak 1.2.4, when I launch an update, it tries to install a flatpak that requires a newer version of flatpak :

> flatpak update 
> Looking for updates…
> ID  Arch   Branch Remote  Download
> 1. [✗] org.freedesktop.Platform.openh264 x86_64 19.08  flathub < 593,4 kB
> Warning: org.freedesktop.Platform.openh264 needs a later flatpak version
> Installation complete.

Also when I run a flatpak uninstall --unused.
It tries to remove a package that is reinstalled with an Update :+1 : 

> flatpak uninstall --unused 
>         ID                                           Arch          Branch
>  1.     org.freedesktop.Platform.GL.default          x86_64        19.08
>  2.     org.freedesktop.Platform.GL32.default        x86_64        19.08
> 
> Proceed with these changes to the Default system installation? [Y/n]: 

I guess the problem is related to Debian, but I mention it here anyway.

Thanks

**Comment by refi64** [comment]
The latter is #2373.

**Comment by mwleeds** [comment]
Thanks for the bug report!

> Hi,
> 
> On my Debian 10 Buster Flatpak 1.2.4, when I launch an update, it tries to install a flatpak that requires a newer version of flatpak :
> 
> > flatpak update
> > Looking for updates…
> > ID  Arch   Branch Remote  Download
> > 
> > 1. [✗] org.freedesktop.Platform.openh264 x86_64 19.08  flathub < 593,4 kB
> >    Warning: org.freedesktop.Platform.openh264 needs a later flatpak version
> >    Installation complete.
> 

Flatpak 1.2.5 has the needed feature for the openh264 extension to work (extra-data support for runtime extensions). And the extension's metadata was updated [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1826/diffs) to allow 1.2.5. So once 1.2.5 makes it to Buster and an updated openh264 extension makes it to Flathub, this issue should be fixed.

> Also when I run a flatpak uninstall --unused.
> It tries to remove a package that is reinstalled with an Update :+1 :
> 
> > flatpak uninstall --unused
> > ID                                           Arch          Branch
> > 
> > 1. ```
> >    org.freedesktop.Platform.GL.default          x86_64        19.08
> >    ```
> > 2. ```
> >    org.freedesktop.Platform.GL32.default        x86_64        19.08
> >    ```
> > 
> > Proceed with these changes to the Default system installation? [Y/n]:
> 
This should also be fixed by 1.2.5 in https://github.com/flatpak/flatpak/commit/0eea5370ba5b94508e560f84d5636519f2c09833

**Comment by smcv** [comment]
Flatpak 1.2.5 [should be in the next buster point release](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=940818). The package has been uploaded, but the release team hasn't accepted it into buster-proposed-updates yet.

**Comment by go-ten** [comment]
Ok super. 

Thanks

**Comment by go-ten** [comment]
Hello,

The update to 1.2.5 from the proposed-updates channel has solved the problems.

Thanks
