### ISSUE TITLE
GL-Runtime problem

### ISSUE THREAD

**Issue by JorisGoosen** [flatpak/flatpak#3136]
## Linux distribution and version
Debian 10
## Flatpak version
flatpak 1.2.4

## Description of the problem
In an issue for our software [JASP](http://github.com/jasp-stats/jasp-desktop) @allefeld had a bit of a problem running JASP. As I cannot think of anything else that we messed up that could cause this.

The problem is that after install `org.jaspstats.JASP` @allefeld cannot run it because the following error gets thrown: `bwrap: Can't mkdir parents for /app/lib/x86_64-linux-gnu/GL: Read-only file system`.

I would honestly not expect anything to be written there because it is indeed a read-only filesystem and we certainly don't write anything there.

I thought at first that maybe there was issue with dependencies not [being followed across repositories](https://github.com/flatpak/flatpak/issues/3094) because another [similar looking issue](https://github.com/flathub/net.lutris.Lutris/issues/53) seemed to be caused by that.

But yesterday we got JASP accepted into [flathub](https://github.com/flathub/org.jaspstats.JASP) and @allefeld installed from there and still got the above error.

Hopefully somebody here can help us?

Ps. I will not be available after today till the 7th of October so any questions until then are probably best asked to @allefeld.

## Steps to reproduce
Run `org.jaspstats.JASP` on @allefeld 's pc? Maybe just running it on Debian 10 is enough.

**Comment by JorisGoosen** [comment]
As a copy from our issue, [the latest that was tried](https://github.com/jasp-stats/jasp-issues/issues/497#issuecomment-535508200):

```
$ flatpak run org.jaspstats.JASP
bwrap: Can't mkdir parents for /app/lib/x86_64-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```

I started again from a clean slate, here is the list of packages pulled in by the installation:

```
$ flatpak list
Description                                                                         Application                       Version Branch Arch   Origin  Installation
nvidia-418-74                                                                       ?esktop.Platform.GL.nvidia-418-74         1.4    x86_64 flathub system
html5-codecs                                                                        ?reedesktop.Platform.html5-codecs         18.08  x86_64 flathub system
JASP - Offers standard analysis procedures in both their classical and Bayesian fo? org.jaspstats.JASP                0.11.0  stable x86_64 flathub system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme               org.kde.KStyle.Adwaita                    5.12   x86_64 flathub system
KDE Software Development Kit - Tools and headers for developing applications using? org.kde.Sdk                               5.12   x86_64 flathub system
```

`?` stands for the `...` character which was apparently lost in copy & paste.

**Comment by allefeld** [comment]
I would like to add that while the attempts described in the linked issue were all performed on one computer (my office PC), the same happens on another computer (my home PC). Both are Debian 10 with nvidia graphics.

**Comment by abderrahim** [comment]
I'd say that the `inherit-extension` at https://github.com/flathub/org.jaspstats.JASP/blob/master/org.jaspstats.JASP.json#L7 is the problem here.

You're trying to inherit the extension from the runtime without creating the appropriate `lib/x86_64-linux-gnu/GL` where the extension is to be mounted. However, the runtime already has the extension, and there is no need to have it mounted under your app directory as well.

**Comment by JorisGoosen** [comment]
Ah ok, so I have removed the `inherit-extension` (it seemed to fix a bunch of GLX errors we got on startup though) and then @allefeld can check if the new 0.11.1 release of jasp works for him.

**Comment by allefeld** [comment]
@JorisGoosen, thanks, but how do I install the new release? Flathub still has 0.11.0, and the zip-file from the github releases page is not recognized by `flatpak install`.

**Comment by JorisGoosen** [comment]
Well, I've pushed the change to flathub, now it needs to build it. I don't know where I can check this though. Hopefully it'll be on there tomorrow.

**Comment by allefeld** [comment]
Ok, I'll check again in the following days.

**Comment by JorisGoosen** [comment]
@allefeld it's on there now.

**Comment by allefeld** [comment]
Wow, it starts. And works.
Thank you!

**Comment by JorisGoosen** [comment]
Thanks to @abderrahim yeah :)
