### ISSUE TITLE
"Sandboxed" apps have read/write access to external media

### ISSUE THREAD

**Issue by sklprogs** [flatpak/flatpak#3138]
## Flatpak 1.2.4
Though "sandboxed" apps have "Documents" folder of their own, it seems that sandboxing does not work for external media. I have an external HDD mounted at /media/WD. When I plug it in, flatpak apps can read and write it just like "normal" apps. Looks like a security breach.

**Comment by refi64** [comment]
What apps did you try? In many cases, the app can use the XDG desktop
portals to pull up an open file dialog on the host system, then only the
selected files appear inside the sandbox. Other apps may explicitly allow
external storage in their sandbox arguments if it fits in with what the app
does.

**Comment by sklprogs** [comment]
I run com.wps.Office, select "Open file", then the standard gtk3 file chooser menu appears. I see mounted volumes to the left, and that volumes are both readable and writable by that app. I haven't tried tuning permissions or sharing folders yet.

**Comment by TingPing** [comment]
```
> flatpak remote-info -m flathub com.wps.Office
...
filesystems=xdg-videos;/media;xdg-download;xdg-documents;/run/media;xdg-pictures;
...
```

Well there you go. You can run `flatpak override --user --nofilesystem=/run/media com.wps.Office`
