### ISSUE TITLE
Icon Validator Sandbox breaks on Clear Linux and  NixOS

### ISSUE THREAD

**Issue by msmart** [flatpak/flatpak#3161]
Building my manifest fails on Clear Linux during the icon validation:

`XXX.png is not a valid icon:`
`bwrap: Can't find source path /etc/ld.so.cache: No such file or directory`

Apparently, it may be the same on NixOS (see below)

The same manifest works fine on Ubuntu. 

_Originally posted by @mat8913 in https://github.com/flatpak/flatpak/pull/2618#issuecomment-469984139_

**Comment by mat8913** [comment]
Here's how we fixed it in NixOS: NixOS/nixpkgs#57889.

**Comment by matthiasclasen** [comment]
Your os doesn't have /etc/ld.so.cache ?

**Comment by mat8913** [comment]
It's farily uncommon, which is why I opted to patch it within NixOS instead of trying to come up with some general solution.

For Clear Linux, probably do something similar to this: https://github.com/clearlinux-pkgs/nautilus/commit/623788c52077e3b7cdbe3e5bea21add368bc767b

**Comment by matthiasclasen** [comment]
I this is probably distro patch territory.

**Comment by msmart** [comment]
@mat8913 Wow, thanks for the helpful links. I will look into it.

@matthiasclasen I agree, I will close this ticket. Thanks!

**Comment by matthiasclasen** [comment]
I think we have such tests already. Does the testsuite fail on clearlinux ?

**Comment by mat8913** [comment]
I think the testsuite is skipped on clearlinux: https://github.com/clearlinux-pkgs/flatpak/blob/e2ba095ff75dbf97e8ef87c240f204074e98892d/options.conf#L47

**Comment by ahkok** [comment]
`ldconfig -p | head -n 1`

But yes I'll see if we can patch this in the distro.
