### ISSUE TITLE
Need to copy some metadata fields into the AppStream

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#317]
An RFC... Currently gnome-software needs to download the metadata file synchronously to see if an application is sandboxed. This means doing flatpak_installation_fetch_remote_metadata_sync() which for me takes 1270ms (!) _for each flatpak application we're showing in the search results_. We need the permissions data for the results so we can show the security shield. Having the metadata available would make searching again fast in gnome-software as at the moment it's jarring and a visibly bad UX.

My idea here is to copy the relevant metadata into the AppStream XML at build time. I guess this would be a patch to the builder itself (rather than appstream-compose) as we need the currently-building metadata file and not just the tree of files. Luckily AppStream already supports this free text `<permission>` field so we are free to specify what we want. My suggestions would be:

```
[Context]
shared=ipc;
sockets=x11;wayland;
devices=dri;
filesystems=xdg-run/dconf;host;~/.config/dconf:ro;
```

...which would be converted to:

```
<permissions type="flatpak">
<permission>shared:ipc</permission>
<permission>sockets:x11</permission>
<permission>sockets:wayland</permission>
<permission>devices:dri</permission>
<permission>filesystems:xdg-run/dconf</permission>
<permission>filesystems:host</permission>
<permission>filesystems:~/.config/dconf:ro</permission>
</permissions>
```

...and then monkey-patched inside the `<component>` tag like you're doing for `<bundle>`. Comments welcome.

Richard.

**Comment by alexlarsson** [comment]
The metadata files are stored in the summary file already, so you should not have to download anything extra. Its weird that flatpak_installation_fetch_remote_metadata_sync takes so long though. Thats supposed to just look up something in the locally cached summary file! We should figure out why that is not happening.
