### ISSUE TITLE
`flatpak remote-info flathub <flatpak>` not returning version info

### ISSUE THREAD

**Issue by luzpaz** [flatpak/flatpak#3171]
## Linux distribution and version
Description:	Manjaro Linux
Release:	18.1.0
Codename:	Juhraya

## Flatpak version
v1.5.0

Trying to ascertain the version of a remote flathub flatpak this way:  
`flatpak remote-info flathub org.freecadweb.FreeCAD | grep Version`  
but there is no 'Version' string. In fact this is the output:  

```bash
$ flatpak remote-info flathub org.freecadweb.FreeCAD

        ID: org.freecadweb.FreeCAD
       Ref: app/org.freecadweb.FreeCAD/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 248.4?MB
 Installed: 746.2?MB
   Runtime: org.kde.Platform/x86_64/5.12

       Sdk: org.kde.Sdk/x86_64/5.12
    Commit: b0c6933e8e98ffd6f79e8495e83dc34de2c62cd43ea11b1b175bfca74d06203e
    Parent: 9d68f0e5192e227d6492c2ec952575e96be49a453b7f6f08561069ed5c6ea9e3
   Subject: add pycollada to enable collada export (#13) (2829179e)
      Date: 2019-09-18 02:25:09 +0000
```

I've been searching the flatpak docs and haven't found a clear way to to do this or anyone else with this issue. What am I doing incorrectly?

Source: https://github.com/flathub/org.freecadweb.FreeCAD/issues/16#issuecomment-541200673

**Comment by mwleeds** [comment]
The version is probably missing from the appstream data. Check if the appstream data is included in the upstream project or added by the flatpak packaging?

**Comment by luzpaz** [comment]
Solution:

```bash
$ flatpak update --appstream
$ flatpak remote-info flathub org.freecadweb.FreeCAD | grep Version
```
