### ISSUE TITLE
"Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user"

### ISSUE THREAD

**Issue by peixe80** [flatpak/flatpak#3172]
**Linux distribution and version:** Mageia 7

**Flatpak version:** 1.4.1

**Description of the problem:**

When I try to add a repo or install/execute/update apps, I get the same error:

```
$ flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
(flatpak remote-add:3960): dconf-WARNING **: 10:48:25.623: Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user
$ flatpak install flathub com.spotify.Client
Looking for matches…
Required runtime for com.spotify.Client/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/19.08) found in remote flathub
Do you want to install it? [Y/n]: 
(flatpak install:12294): dconf-WARNING **: 12:09:21.154: Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user
$ flatpak run com.spotify.Client
(flatpak run:13050): dconf-WARNING **: 12:14:17.825: Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user
```

But the directory /root/.local/share/flatpak/exports/ doesn't exist:

```
# ls -a /root/.local/share/flatpak/
./  ../  .changed  repo/
```

I guess I broke something. How can I restore it?

I have tried to uninstall the repo and all the apps, then uninstall flatpak and finally reinstall everything, but the problem persists.

Thank you very much.

**Comment by TingPing** [comment]
Those are warnings, does the application not launch?

**Comment by TingPing** [comment]
Also stop running applications as root?

**Comment by peixe80** [comment]
Yes, the applications launch.

Now I am running the applications as user, although before I did installation/execution tests as root. But after these tests I uninstalled and reinstalled flatpak.

But is it normal that I always get that warning and that the directory /root/.local/share/flatpak/exports/ does not exist?

Thank you so much.

**Comment by TingPing** [comment]
Well if your user never used DConf it is normal, and root probably never uses DConf.

**Comment by peixe80** [comment]
Well, I've reinstalled Mageia and the warning has disappeared. The directory /root/.local/share/flatpak/exports/ still doesn't exist, but the warning no longer appears. I suppose I broke something in the system, but the problem is already solved. Thank you anyway and regards.
