### ISSUE TITLE
flatpak installation progress goes backward

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#3175]
## Linux distribution and version

Fedora 30

## Flatpak version

gnome-software 3.32.4-3.fc30 and flatpak-1.4.3-1.fc30

## Description of the problem

libflatpak installation progress sometimes goes backwards. See the screencast attached here: https://gitlab.gnome.org/GNOME/gnome-software/issues/826

## Steps to reproduce

Don't know how to reproduce it.

**Comment by matthiasclasen** [comment]
largely an ostree issue. We give you the numbers we get from ostree (to the degree that ostree progress api lets us decipher them)

**Comment by mcatanzaro** [comment]
So you do want me to report this bug to ostree? Or does a bug already exist?

**Comment by matthiasclasen** [comment]
This is a well-known (to the involved people), hard-to-fix issue.

I don't think filing another issue will make any appreciable difference.
