### ISSUE TITLE
cannot search flatpak local repository

### ISSUE THREAD

**Issue by fedelibre** [flatpak/flatpak#3177]
I'm on Fedora 30 and flatpak 1.4.3.
This is a question.. which may turn into a documentation improvement, if that's the case.

I'm trying to set up a local flatpak repository, because I want to see how my new flatpak app will look like in GNOME Software.
Here's how I've created the local remote (repository?) and exported my app there:

```
$ mkdir -p ~/flatpak/local
$ flatpak remote-add --no-gpg-verify --user local file:///home/fede/flatpak/local
error: Remote listing for local not available; server has no summary file. Check the URL passed to remote-add was valid.
$ flatpak-builder --force-clean --repo=/home/fede/flatpak/local _build org.frescobaldi.Frescobaldi.yml 
```

Does the error mean that `file://` is invalid?

Anyway, the remote directory is populated of files, but the search doesn't work:

```
$ flatpak remotes
Name    Options
fedora  system,oci
flathub system
local   user,no-gpg-verify

$ flatpak search Frescobaldi
No matches found
```

What I'm missing?

**Comment by mwleeds** [comment]
> I'm on Fedora 30 and flatpak 1.4.3.
> This is a question.. which may turn into a documentation improvement, if that's the case.
> 
> I'm trying to set up a local flatpak repository, because I want to see how my new flatpak app will look like in GNOME Software.
> Here's how I've created the local remote (repository?) and exported my app there:
> 
> ```
> $ mkdir -p ~/flatpak/local
> $ flatpak remote-add --no-gpg-verify --user local file:///home/fede/flatpak/local
> error: Remote listing for local not available; server has no summary file. Check the URL passed to remote-add was valid.
> $ flatpak-builder --force-clean --repo=/home/fede/flatpak/local _build org.frescobaldi.Frescobaldi.yml 
> ```
> 
> Does the error mean that `file://` is invalid?
> 

No you just need to export to the repo with your `flatpak-builder` command first, and then add it as a remote. Otherwise it's just an empty directory and not an OSTree repository.
> Anyway, the remote directory is populated of files, but the search doesn't work:
> 
> ```
> $ flatpak remotes
> Name    Options
> fedora  system,oci
> flathub system
> local   user,no-gpg-verify
> 
> $ flatpak search Frescobaldi
> No matches found
> ```
> 
> What I'm missing?

Did you include appstream data when packaging your app? `flatpak search` searches appstream data in remotes.

**Comment by fedelibre** [comment]
> > Does the error mean that `file://` is invalid?
> 
> No you just need to export to the repo with your `flatpak-builder` command first, and then add it as a remote. Otherwise it's just an empty directory and not an OSTree repository.

Ok. Yes, if I export first and then add it as a remote there's no error.

> > Anyway, the remote directory is populated of files, but the search doesn't work:
> 
> Did you include appstream data when packaging your app? `flatpak search` searches appstream data in remotes.

What is this appstream data exactly?

The appstream metainfo file is in the source repository declared in the manifest (I'm currently using a [branch of my fork](https://github.com/fedelibre/frescobaldi/tree/879/appdata)). The xml file is in the data/ subdirectory in the source. I guess I'm missing how flatpak finds this file?

**Comment by mwleeds** [comment]
> > > Anyway, the remote directory is populated of files, but the search doesn't work:
> > 
> > 
> > Did you include appstream data when packaging your app? `flatpak search` searches appstream data in remotes.
> 
> What is this appstream data exactly?
> 
It's the data used by front-ends like GNOME Software to display information about apps.

> The appstream metainfo file is in the source repository declared in the manifest (I'm currently using a [branch of my fork](https://github.com/fedelibre/frescobaldi/tree/879/appdata)). The xml file is in the data/ subdirectory in the source. I guess I'm missing how flatpak finds this file?

The file should be named with your app ID, so you could either rename it in the source or use the `rename-appdata-file` key in your manifest to rename it (see `man flatpak-manifest`).

It also needs to be installed into `/app/share/metainfo` according to http://docs.flatpak.org/en/latest/conventions.html#appdata-files . I think that part is handled by your build system (e.g. autotools).

**Comment by fedelibre** [comment]
Thanks, I missed the `rename-appdata-file` key. I've now added it, but I get this error:

```
Renaming frescobaldi.appdata.xml to share/appdata/org.frescobaldi.Frescobaldi.appdata.xml
Renaming frescobaldi.desktop to org.frescobaldi.Frescobaldi.desktop
Renaming icon hicolor/scalable/apps/frescobaldi.svg to hicolor/scalable/apps/org.frescobaldi.Frescobaldi.svg
Rewriting contents of org.frescobaldi.Frescobaldi.desktop
Running appstream-compose
Processing application org.frescobaldi.Frescobaldi
Error loading AppData file: failed to parse /app/share/appdata/org.frescobaldi.Frescobaldi.appdata.xml: Error on line 4 char 7: <component> already set '​' and tried to replace with '
  '
Error: ERROR: appstream-compose failed: Processo figlio uscito con codice 1
```

As you can see, it's installed in `/app/share/appdata`.
The error message by appstream-compose is not clear.

AFAICS the appdata file passes the validation:

    appstreamcli validate _build/files/share/appdata/org.frescobaldi.Frescobaldi.appdata.xml

returns only 4 infos about not using HTTPS and 1 warning about the ID not being a reverse domain-name.

**Comment by mwleeds** [comment]
I'm not sure what the problem is but here are some example appdata files:

- https://gitlab.gnome.org/GNOME/gnome-builder/blob/master/data/appdata/org.gnome.Builder.appdata.xml.in
- https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.appdata.xml

It looks like both of those have the ID set to the app ID with a `.desktop` ending, maybe do that for yours?

**Comment by fedelibre** [comment]
> It looks like both of those have the ID set to the app ID with a `.desktop` ending, maybe do that for yours?

I've tried but it doesn't help.
[According to the spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) the `.<product>` suffix is designed to *increase the uniqueness and to distinguish between different pieces of a software suite*. But this is not the case, as the application has a single "piece".

**Comment by fedelibre** [comment]
I think the issue came up since I added to the manifest `rename-appdata-file: frescobaldi.appdata.xml`. Shouldn't this change not only the file name but also the ID set in the xml file? Apparently it doesn't do it:

```
$ grep '<id>' ./_build/files/share/appdata/org.frescobaldi.Frescobaldi.appdata.xml
  <id>frescobaldi</id>
```

OTOH if I change the id in the sources, appstream validation within the source repository wouldn't work.

**Comment by fedelibre** [comment]
If I comment the `rename-appdata-file` line, the build works and here's what I find:

```
$ find . -name org.frescobaldi.Frescobaldi.appdata.xml
$
$ find . -name frescobaldi.appdata.xml
./_build/files/share/metainfo/frescobaldi.appdata.xml
```

but the ID then is incorrect, as the flatpak application is using the reverse-DNS

**Comment by fedelibre** [comment]
If rename-appdata-file renames only the file name but not the <id> (bug?), then the only option is changing everything manually with a post-install? See below:

```
- name: frescobaldi
  buildsystem: simple
  build-commands:
    - python3 setup.py install --prefix=${FLATPAK_DEST} --root=/
  sources:
    - type: git
      url: https://github.com/fedelibre/frescobaldi
      branch: 879/appdata
  post-install:
    - mv /app/share/metainfo/frescobaldi.appdata.xml /app/share/metainfo/org.frescobaldi.Frescobaldi
    - sed -i 's|<id>frescobaldi</id>|<id>org.frescobaldi.Frescobaldi</id>|' /app/share/metainfo/org.frescobaldi.Frescobaldi
```

but still the application cannot be searched.
I guess I have to study more appstreamcli...

**Comment by fedelibre** [comment]
However, installing it finds it:

```
$ flatpak install org.frescobaldi.Frescobaldi
Looking for matches…
Found similar ref(s) for ‘org.frescobaldi.Frescobaldi’ in remote ‘local’ (user).
Use this remote? [Y/n]: 

org.frescobaldi.Frescobaldi permissions:
    ipc     network     pulseaudio     wayland    x11    devices    file access [1]    dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar


        ID                                    Arch             Branch           Remote          Download
 1. [\] org.frescobaldi.Frescobaldi           x86_64           master           local           1.0 kB / 45,5 MB
```

I must figure out how AppStream metadata works.

**Comment by fedelibre** [comment]
> ```
> Processing application org.frescobaldi.Frescobaldi
> Error loading AppData file: failed to parse /app/share/appdata/org.frescobaldi.Frescobaldi.appdata.xml: Error on line 4 char 7: <component> already set '​' and tried to replace with '
>   '
> Error: ERROR: appstream-compose failed: Processo figlio uscito con codice 1
> ```

It turned out that this error was due to zero-width space characters present. See full explanation in [this comment](https://github.com/ximion/appstream/issues/259#issuecomment-546576317).
