### ISSUE TITLE
add a systemd unit to a manifest

### ISSUE THREAD

**Issue by fedelibre** [flatpak/flatpak#3178]
I'm on Fedora 30 and flatpak 1.4.3.
This is a question.. which may turn into a documentation improvement, if that's the case.

## Context

I'm writing a manifest for an application which needs a MIDI synth launched in server mode (e.g. fluidsynth) to be able to play back MIDIs.
IIUC I cannot access the MIDI synth outside the sandbox so I should bundle it in the manifest and add a systemd service which will start it everytime the app is launched.

## Question

I cannot figure out how to add a systemd unit file within the manifest.

**Comment by TingPing** [comment]
You can't export systemd unit files: https://github.com/flatpak/flatpak/issues/2787

The short term solution probably means modifying IIUC to manually launch this service?

**Comment by fedelibre** [comment]
Ok, I see. I thought I could use a wrapper script.. then realized that I could easily access the MIDI synth running on the host granting access to all devices.
