### ISSUE TITLE
Unable to set video mode: X11 driver not configured with OpenGL

### ISSUE THREAD

**Issue by Rampoina** [flatpak/flatpak#3184]
## Linux distribution and version
Arch linux   5.3.6-arch1-1-ARCH
## Flatpak version
Flatpak 1.5.0
## Description of the problem
When running this flatpak:
https://gitlab.com/Rampoina/com.zenorogue.hyperrogue
After adding some debugging statements if fails with the following error:

`Unable to set video mode: X11 driver not configured with OpenGL`

Other opengl apps work well
```
flatpak list | grep nvidia                                                                                                                                                                                               
nvidia-415-25	org.freedesktop.Platform.GL.nvidia-415-25		1.4	flathub	user
nvidia-418-43	org.freedesktop.Platform.GL.nvidia-418-43		1.4	flathub	user
nvidia-418-56	org.freedesktop.Platform.GL.nvidia-418-56		1.4	flathub	user
nvidia-430-26	org.freedesktop.Platform.GL.nvidia-430-26		1.4	flathub	user
nvidia-435-21	org.freedesktop.Platform.GL.nvidia-435-21		1.4	flathub	user
nvidia-435-27-01	org.freedesktop.Platform.GL.nvidia-435-27-01		1.4	flathub	user
```
I'm not sure where the issue lies: the way the package is being built, flatpak itself etc. But some help would be appreciated.
## Steps to reproduce
build https://gitlab.com/Rampoina/com.zenorogue.hyperrogue and run it

**Comment by nanonyme** [comment]
Probably missing/mismatched nvidia GL extension.

**Comment by hfiguiere** [comment]
OP never followed up.
