### ISSUE TITLE
Updated extension has no effect on main package

### ISSUE THREAD

**Issue by jakobjakobson13** [flatpak/flatpak#3199]
## Linux distribution and version
Ubuntu 18.04.3

## Flatpak version
1.4.3

## Description of the problem
I wondered if you could answer a question with a [bug report](https://github.com/flathub/org.texstudio.TeXstudio/issues/33): [TeXstudio](https://github.com/flathub/org.texstudio.TeXstudio/blob/master/org.texstudio.TeXstudio.yaml) uses the [texlive](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive) extension in its manifest. Recently the texlive extension got updated but this had no effect on texstudio as texstudio apparently copied some files at a earlier time from the texlive extension into its own directories. So texstudio still uses the old binaries even though the extension provides newer ones.

Is this due to the manifest or is it flatpak intrinsic?

**Comment by TingPing** [comment]
TeXstudio uses it as an *sdk extension*, as in the extension is loaded at build time only and the manifest copies the contents over. So this is expected behavior that the extension updating doesn't mean anything except at build time.

**Comment by rugk** [comment]
This sounds strange. It looks like this goes against the philosophy of flatpak (and it's "updateability"/update feature)… (it should not just copy content over and then keep the old version forever…)

**Comment by TingPing** [comment]
Extensions are extremely simple, they dump files into where the extension point tells it to.

The SDK extension point puts files into the SDK. Note that TeXstudio is not the SDK.

TeXstudio could define its own extension point but that isn't ideal either because extensions are optional and that isn't where you put dependencies.

So the simple truth is you rebuild your app when you want to update your contents, which is what texlive is.

**Comment by rugk** [comment]
Hmm, so how can we solve this issue now?

**Comment by matthiasclasen** [comment]
Its just two slightly different things,(runtime or app) extension vs sdk extension. Might have been clearer to pick a different name

**Comment by TingPing** [comment]
You solve it by manually rebuildling it when texlive is updated. You can trigger one on flathub.org/builds.

It would be neat if the flathub builder could be configured to automatically do this.

**Comment by jakobjakobson13** [comment]
Thanks for all the quick replies.
