### ISSUE TITLE
how to remove pitivi-flatpak

### ISSUE THREAD

**Issue by vistad** [flatpak/flatpak#320]
Hello,
I installed pitivi-flatpak on my LinuxMint 18, but it runs only as SU and doesn't work at all. How to remove apps installed by flatpak?

**Comment by aleb** [comment]
To uninstall try with "stable" or "master" for branch:
`flatpak uninstall --user org.pitivi.Pitivi BRANCH`

If you noticed problems we'd appreciate if you file bugs. Thanks!

**Comment by vistad** [comment]
If I run a command in terminal
flatpak uninstall --user org.pitivi.Pitivi BRANCH
 I have an error-message:
error: org.pitivi.Pitivi BRANCH not installed

After installation I have a file pitivi-flatpak in a directory. I ran a command
pitivi-flatpak uninstall --user org.pitivi.Pitivi BRANCH
it responded
pitivi-flatpak: command not found

First of all I want to remove pitivi, then flatpak. It mentions file "/app/lib/pitivi/python/pitivi/application.py"
Do you think if I remove /app/lib/pitivi this app will be removed?

**Comment by aleb** [comment]
flatpak uninstall --user org.pitivi.Pitivi master
flatpak uninstall --user org.pitivi.Pitivi stable
Removing flatpak can be done depending on how you installed it. Try to remove the "flatpak" system package.
Also look into removing ~/.local/share/flatpak/

**Comment by vistad** [comment]
At first I had a 20 sec. .mp4 video, and I wanted to crop it to the first 5 sec. I had spent few hours trying to do that with Openshot, but could not make it work or figure out how it works. I looked for other Linux video editors and found pitivi. 

I installed pitivi version 0.95-1 from Linux Mint repos. It's not very intuitive, but I managed to understand how it works. It did not encode to .mp4 (just stood still), but in encoded to .webm - took 1 minute. I googled for pitivi output .mp4 plugin - didn't find it, but found pitivi website that said the new version is available for download.

I downloaded the latest version 0.97.1-50-gd520f6a, tried to install it - it said Install Flatpak first. I went to flatpak.org and installed flatpak with the command

$ sudo add-apt-repository ppa:alexlarsson/flatpak
$ sudo apt update
$ sudo apt install flatpak

Than I installed pitivi with the command

curl https://git.gnome.org/browse/pitivi/plain/build/flatpak/pitivi-flatpak -Sso pitivi-flatpak && chmod +x pitivi-flatpak && ./pitivi-flatpak --branch=stable --update

The installation downloaded 108 Mb of files and finished with pitivi starting with 2 windows, a big window with  "Pitivi" in the Title bar, and a small window with "Welcome (as superuser)" in the Title bar.

After I shut down pitivi, I could not find it in my user account menu, home directory or elsewhere. However it could be started with pitivi-flatpak file, called from terminal.

The data in terminal after starting pitivi:

$ ./pitivi-flatpak
Running org.pitivi.Pitivi (master)

** (pitivi:2): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-uxVb4OmyrD: Connection refused
Missing soft dependency:
- pycanberra not found on the system
    -> enables sound notifications when rendering is complete
Missing soft dependency:
- GnomeDesktop not found on the system
    -> file thumbnails provided by GNOME's thumbnailers


I tried to install pycanberra, but did not know how to do that.

As to Gnome desktop - I thought I have it, but actually I have Mate

After that I wanted to purge pitivi and flatpak, but could not purge either of them. Please help!

IMO when you tell how to install, you should immediately tell how to uninstall.

Thanks!

**Comment by alexlarsson** [comment]
Remove using:
```
flatpak uninstall org.pitivi.Pitivi master
flatpak uninstall org.pitivi.Pitivi stable
sudo apt-get remove flatpak
```

**Comment by vistad** [comment]
Hello Alex,
~ $ flatpak uninstall org.pitivi.Pitivi master
error: org.pitivi.Pitivi master not installed
~ $ flatpak uninstall org.pitivi.Pitivi stable
error: org.pitivi.Pitivi stable not installed

Now I have installed flatpak from our repo - which came as update today. I want to keep it. But pitivi is not working

**Comment by aleb** [comment]
Uninstall using:
flatpak uninstall --user org.pitivi.Pitivi master
flatpak uninstall --user org.pitivi.Pitivi stable

Please close the issue yourself if you succeed uninstalling.

If you want to help report Pitivi bugs, please do so on https://phabricator.freedesktop.org/project/view/15/

**Comment by vistad** [comment]
Hi aleb,
this time it worked!
Thank you guys! All the best and success in your work!
