### ISSUE TITLE
The shotcut font choose window is too big to operate.

### ISSUE THREAD

**Issue by yichuang-zh** [flatpak/flatpak#3202]
Debian Stretch 9.11 /Gnome
Flatpak 1.2.4
The shotcut font choose window is too big to operate.

Put a clip on the timeline, then add filter > text simple , check the “Use font size” box, then click the button on the left side of the checkbox, the bug appeared.
Below is the screencapture.

![capFontSize](https://user-images.githubusercontent.com/44933638/67734080-0ecf6c80-fa3b-11e9-8c7f-5dccfcdb9004.png)

ps:
The appimage version of shotcut is ok.

**Comment by TingPing** [comment]
Flatpak has nothing to do with how this dialog looks. I'm not sure what would be to blame here but you are probably best off reporting it against the app and they can triage it to where the fault is.

**Comment by yichuang-zh** [comment]
Got it~
Thank you~
