### ISSUE TITLE
Bundle not portable ?

### ISSUE THREAD

**Issue by devnewton** [flatpak/flatpak#3205]
## Linux distribution and version

Fedora x86_64 30

## Flatpak version

1.2.4

## Description of the problem

This [flatpak bundle](https://play.devnewton.fr/newtonadventure.flatpak) does not run on Fedora.

> The application fr.devnewton.NewtonAdventure/x86_64/master requires the runtime org.freedesktop.Platform/x86_64/18.08 which was not found

It works fine on Ubuntu.

## Steps to reproduce

Download the flatpak file then run flatpak install newtonadventure.flatpak

This flatpak bundle was built from: https://github.com/devnewton/newton_adventure.flatpak

**Comment by TingPing** [comment]
Bundles alone don't include the runtime. You can either bundle the runtime also or simply add the flathub repo on the other machine so it can install the runtime.
