### ISSUE TITLE
Can't update Firefox Fedora Flatpak, Can't pull from untrusted non-gpg verified remote

### ISSUE THREAD

**Issue by David-Else** [flatpak/flatpak#3212]
## Linux distribution and version
Centos 8
## Flatpak version
1.0.6
## Description of the problem
Using these command I installed the Flatpak of Firefox 69
```
flatpak remote-add --if-not-exists fedora oci+https://registry.fedoraproject.org
flatpak install -y fedora org.mozilla.Firefox
```
now when I try to update I get:
```
flatpak update
Looking for updates...
Installing in system:
org.freedesktop.Platform.openh264/x86_64/19.08 flathub 563e6c1a7173
Updating in system:
org.mozilla.Firefox/x86_64/stable fedora 445138d3b3fb
Is this ok [y/n]: y
Updating: org.mozilla.Firefox/x86_64/stable from fedora
Error: Failed to update org.mozilla.Firefox/x86_64/stable: Can't pull from untrusted non-gpg verified remote
Installing: org.freedesktop.Platform.openh264/x86_64/19.08 from flathub
Warning: Failed to install org.freedesktop.Platform.openh264/x86_64/19.08: runtime/org.freedesktop.Platform.openh264/x86_64/19.08 needs a later flatpak version (1.4.2;1.2.5;1.0.9;)
error: There were one or more errors
```
I don't think the `org.freedesktop.Platform.openh264` has anything to do with it, it said that before and worked, it is the fact that now for some reason the remote is untrusted? What happened, and how do I fix it?

I added a request for help from the Fedora packager and no luck:
https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2019-619c0a6211
and bugzilla, with no response:
https://bugzilla.redhat.com/show_bug.cgi?id=1767007
and I tried:
```
flatpak remote-delete --force fedora
flatpak remote-add --if-not-exists fedora oci+https://registry.fedoraproject.org
```
Which did nothing.

**Comment by ajgringo619** [comment]
Can you try upgrading your version of flatpak?

**Comment by David-Else** [comment]
@ajgringo619 Can't update in Centos 8, but Centos 8.1 is around the corner and there might be a new version then https://wiki.centos.org/About/Building_8.x

**Comment by David-Else** [comment]
This got fixed upstream and will be released at some point.
