### ISSUE TITLE
libflatpak: add API to determine proper SDK extension branch to use

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#3213]
## Description of the problem

When automating the initial build setup for Flatpak in GNOME Builder, we need to discover the proper `"sdk-extensions"` defined from the manifest. Those have a number of complex checks across multiple metadata that are necessary to resolve. We also need to do this before we've downloaded all the SDKs so that we can present the user a single "install dialog" for what needs to be fetched from the remote servers.

Builder issue: https://gitlab.gnome.org/GNOME/gnome-builder/issues/1073

## Proposed solution

To avoid having to write all this in Builder only for other IDEs to replicate it, it would be nice to provide an API in libflatpak to resolve the extension branch for us.

Simply as a strawman, let's propose API that looks like the following:

```c
char *flatpak_resolve_extension_branch (FlatpakRef  *sdk,
                                        const char  *sdk_extension,
                                        GError     **error); 
```

**Comment by matthiasclasen** [comment]
Do you have an implementation for this api ?

**Comment by chergert** [comment]
I don't, when talking to @alexlarsson it sounded like it had a number of caveat that was unaware of.

**Comment by allanday** [comment]
Apparently this issue is why pressing the build button in Builder doesn't Just Work for gnome-tour (it requires the correct version of the Rust extension to build). Something I've hit a few times...

**Comment by chergert** [comment]
This is fixed in Builder now by implementing the common ancestors manually. It's not pretty but it seems to work.

https://gitlab.gnome.org/GNOME/gnome-builder/-/commit/9d17bbf8f4f58786922aa9a22197db0102ed25fc
