### ISSUE TITLE
how to change flatpak's default browser?

### ISSUE THREAD

**Issue by kupiqu** [flatpak/flatpak#3216]
Flatpak is not using the system's default browser. It would be good if flatpak could read this out from the host directly, but anyway.

Given that this is not the case, I want to do the change manually, but I searched the web and couldn't find how to do it so flatpak and my system, both have the same default browser.

**Comment by TingPing** [comment]
Flatpak doesn't use anything.

`xdg-desktop-portal-gtk` does and you can use the `gio` tool to set the browser. For example: `gio mime x-scheme-handler/http firefox.desktop` and `gio mime x-scheme-handler/https firefox.desktop`

**Comment by kupiqu** [comment]
Thank you, it was very helpful!

**Comment by 70p4z** [comment]
A few moments later...
Just to mention I had to play with firefox-esr.desktop instead of firefox.desktop

**Comment by Flashwalker** [comment]
#### Hi, here is what I have:
```bash
$ gio mime inode/directory

Default application for “inode/directory”: org.kde.dolphin.desktop
Registered applications:
	org.kde.dolphin.desktop
	nemo.desktop
	org.kde.gwenview.desktop
	org.kde.kate.desktop
	thunar.desktop
Recommended applications:
	org.kde.dolphin.desktop
	nemo.desktop
	org.kde.gwenview.desktop
	org.kde.kate.desktop
	thunar.desktop



$ flatpak run --command=bash<<<"gio mime inode/directory" com.github.neithern.g4music

No default applications for “inode/directory”
```

```bash
$ xdg-mime query default inode/directory

org.kde.dolphin.desktop



$ flatpak run --command=bash<<<"xdg-mime query default inode/directory" com.github.neithern.g4music

bash: line 1: xdg-mime: command not found
```

#### But I still have Thunar as the default file browser for Flatpak applications

**Comment by chrisawi** [comment]
@Flashwalker As mentioned above, this isn't controlled by flatpak itself, but rather xdg-desktop-portal. You can check what's happening by running it in verbose mode in a terminal:

    /usr/libexec/xdg-desktop-portal --replace --verbose

When trying to open a directory via the OpenURI portal, that should produce a chunk of output.

Also note that for directories, it first tries the `org.freedesktop.FileManager1` interface before falling back to checking mime handlers. You can simulate that with:

    gdbus call --session --dest org.freedesktop.FileManager1 --object-path /org/freedesktop/FileManager1 --method org.freedesktop.FileManager1.ShowItems "['file:///etc/fstab']" ""

**Comment by Flashwalker** [comment]
@chrisawi 
Well, in my case that chunck is:
```
XDP: document portal returned empty doc id for path '/home/user/Music/song.mp3'
XDP: OpenFile: translating path value '/home/user/Music/song.mp3' to host path '/home/user/Music/song.mp3'
XDP: document portal returned empty doc id for path '/home/user/Music/song.mp3'
```
I start the Gapless player (com.github.neithern.g4music) and select the last item in the 3-dots menu, and **Thunar** starts up.

But this command `org.freedesktop.FileManager1` starts D**o**lphin.

**Comment by TingPing** [comment]
The service that provides `org.freedesktop.FileManager1` probably isn't always running, so your dbus server launches it when needed. I would expect it to be deterministic but apparently not. There are multiple dbus servers people use these days so one might behave differently.
