### ISSUE TITLE
PyCharm doesn't have access to programs

### ISSUE THREAD

**Issue by BinaryAura** [flatpak/flatpak#3217]
## Linux distribution and version
Fedora 30 (Workstation)
```bash
$ uname -r
5.3.7-200.fc30.x86-64
```
## Flatpak version
Flatpak 1.4.3
## Description of the problem
See email exchange with JetBrains:
[JetBrains_email.zip](https://github.com/flatpak/flatpak/files/3827965/JetBrains_email.zip)

I've had similar issues like this as well with Oxygen Not Included through Steam
See email exchange with Klei:
[Klei_email.zip](https://github.com/flatpak/flatpak/files/3827966/Klei_email.zip)

## Steps to reproduce
Install PyCharm via flatpak
Install dot/pdflatex
dot/pdflatex not accessible from PyCharm

**Comment by TingPing** [comment]
This isn't an issue to report against flatpak, but yes its sandboxed it can never directly execute host applications.

You can use `flatpak-spawn --host foo` to run host applications from inside the sandbox.

**Comment by BinaryAura** [comment]
Is there a way to install programs (and libraries) into the sandbox?
I found /var/lib/flatpak/.../bin and lib
The /bin files are found but, it seems that anything that I add to /lib is completely ignored

**Comment by TingPing** [comment]
You can build extensions but in practice no there is no simple method.

**Comment by robertpro** [comment]
@BinaryAura where you able to fix it ?
