### ISSUE TITLE
Error resolving “sdk.gnome.org”: Name or service not known

### ISSUE THREAD

**Issue by dln949** [flatpak/flatpak#3227]
Ubuntu 18.04.3
Flatpak 1.4.3

Today, suddenly when I ran the command   flatpak update   in the terminal, I got this strange error message:  

F: Error updating remote metadata for 'gnome': Error resolving “sdk.gnome.org”: Name or service not known

I am still a "newbie" when it comes to understanding and using flatpak, so I do not know what  this message means, what it is telling me, why it is suddenly a problem, and what I should do to fix it.  

Any help from any of you will be greatly appreciated.  

Finally, in case this might help, I reproduce below the entirety of the output:  

`main1@system1:~$ flatpak update
Looking for updates…
F: Error updating remote metadata for 'gnome': Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.gnome.Platform/x86_64/3.28 is already installed: Unable to load summary from remote gnome: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Can't find runtime/org.gnome.Platform/x86_64/3.28 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.gnome.Platform.Locale/x86_64/3.28 is already installed: Unable to load summary from remote gnome: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Can't find runtime/org.gnome.Platform.Locale/x86_64/3.28 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6 is already installed: Unable to load summary from remote gnome: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Can't find runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 is already installed: Unable to load summary from remote gnome: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Can't find runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Platform.GL.default/x86_64/1.6 is already installed: Unable to load summary from remote gnome: Error resolving “sdk.gnome.org”: Name or service not known
F: Warning: Can't find runtime/org.freedesktop.Platform.GL.default/x86_64/1.6 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving “sdk.gnome.org”: Name or service not known`

**Comment by bilelmoussaoui** [comment]
You should remove the gnome-nightly and add the new one. The old infrastructure was moved to a new thing.
Not a Flatpak issue anyway.

**Comment by dln949** [comment]
Thank you.  
I did not realize it has nothing yo do with flatpak.  

A few followup questions for you:  I don't know what a "gnome-nightly" is, nor how to remove it.  And, what is meant by " the new one", and how does a person add it?

**Comment by mwleeds** [comment]
> A few followup questions for you: I don't know what a "gnome-nightly" is, nor how to remove it. And, what is meant by " the new one", and how does a person add it?

Flatpak can have a set of configured remotes which are sources from which applications can be installed. You want to delete the `gnome` one with `flatpak remote-delete gnome`. That will probably error out saying that you have installed applications from the `gnome` remote, which you'll need to remove using the `flatpak uninstall` command. Then you can add the new `gnome-nightly` remote using the instructions [here](https://wiki.gnome.org/Apps/Nightly), and re-install your apps from it.

**Comment by dln949** [comment]
Thank you, that helped.

**Comment by Mailaender** [comment]
I can't uninstall the GNOME SDK.

```
flatpak remote-delete gnome
The following refs are installed from remote 'gnome':

   1) runtime/org.freedesktop.Sdk.Locale/x86_64/1.4
   2) runtime/org.freedesktop.Sdk/x86_64/1.4

Remove them? [y/n]: y
F: Error updating remote metadata for 'gnome': Fehler beim Auflösen von »sdk.gnome.org«: Der Name oder der Dienst ist nicht bekannt
```

I also get errors during `flatpak update`

```
Warning: org.freedesktop.Platform.openh264 needs a later flatpak version
Warning: Error updating remote metadata for 'gnome': Fehler beim Auflösen von »sdk.gnome.org«: Der Name oder der Dienst ist nicht bekannt
Warning: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Sdk/x86_64/1.4 is already installed: Unable to load summary from remote gnome: Fehler beim Auflösen von »sdk.gnome.org«: Der Name oder der Dienst ist nicht bekannt
Warning: Warning: Can't find runtime/org.freedesktop.Sdk/x86_64/1.4 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Fehler beim Auflösen von »sdk.gnome.org«: Der Name oder der Dienst ist nicht bekannt
Warning: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Sdk.Locale/x86_64/1.4 is already installed: Unable to load summary from remote gnome: Fehler beim Auflösen von »sdk.gnome.org«: Der Name oder der Dienst ist nicht bekannt
Warning: Warning: Can't find runtime/org.freedesktop.Sdk.Locale/x86_64/1.4 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Fehler beim Auflösen von »sdk.gnome.org«: Der Name oder der Dienst ist nicht bekannt
```

**Comment by Mailaender** [comment]
`flatpak uninstall monodevelop` helped.

**Comment by vanillajonathan** [comment]
```console
$ flatpak remote-delete gnome
The following refs are installed from remote 'gnome':

   1) runtime/org.gnome.Sdk/x86_64/3.26
   2) runtime/org.gnome.Platform/x86_64/3.26
   3) runtime/org.gnome.Sdk/x86_64/3.22

Remove them? [y/n]: y
**
flatpak:ERROR:common/flatpak-transaction.c:2587:mark_op_resolved: assertion failed: (commit != NULL)
Bail out! flatpak:ERROR:common/flatpak-transaction.c:2587:mark_op_resolved: assertion failed: (commit != NULL)
Aborted (core dumped)
```

**Comment by mwleeds** [comment]
@vanillajonathan please post the output of `flatpak uninstall --unused`

**Comment by vanillajonathan** [comment]
```console
$ flatpak --version
Flatpak 1.8.1
```

**Comment by mwleeds** [comment]
@vanillajonathan I filed #3744 for your issue. You may to be able to work around it with `sudo flatpak repair` and `flatpak repair --user`. You can also use `ostree --repo=/var/lib/flatpak/repo refs --delete runtime/org.gnome.Sdk/x86_64/3.26` or `ostree --repo=~/.local/share/flatpak/repo refs --delete runtime/org.gnome.Sdk/x86_64/3.26` depending on if those things are in your user or system installation (and similarly delete the other two runtimes).

**Comment by vanillajonathan** [comment]
@mwleeds Thank you!

I followed your steps and it worked!
