### ISSUE TITLE
document FLATPAK_DEST environment variable

### ISSUE THREAD

**Issue by fedelibre** [flatpak/flatpak#3229]
I'm trying to learn Flatpak also by reading manifests on Flathub. I see that some use `/app` and some use `${FLATPAK_DEST}`. I wonder if there's a best practice for this.

I found only two small explanations in the repository:

- in the [source](https://github.com/flatpak/flatpak/blob/master/app/flatpak-builtins-build.c#L487)
- in the [NEWS file](https://github.com/flatpak/flatpak/blob/master/NEWS#L1324):
> FLATPAK_DEST is set in the build environment to the installation
   destination (i.e. typically /app). It is particularly useful when
   building an extension where the destination is more complex.

A clear example would help to understand how this can be useful.

If there's no side effect, I would use `/app` as it's faster to type and to read.

**Comment by refi64** [comment]
- When you're building an extension, your install target won't be /app. It
may be something more complex like /usr/lib/sdk/something or
/app/lib/extensions/something.
- If you're writing a standalone module for use in other manifests (see
shared-modules for an example), the module may be included in any app *or*
extension; there's no way to know the path in advance.

**Comment by matthiasclasen** [comment]
FLATPAK_DEST is documented in the flatpak-manifest man page.

**Comment by fedelibre** [comment]
> FLATPAK_DEST is documented in the flatpak-manifest man page.

Well, true but it's not clear why I should use the environment variable instead of /app when I read the definition in the man page:

> FLATPAK_DEST
           The path to where the current build should install into. This is /app for application builds.

And for those looking at docs.flatpak.org the search [does not return any result](http://docs.flatpak.org/en/latest/search.html?q=FLATPAK_DEST&check_keywords=yes&area=default).

**Comment by matthiasclasen** [comment]
There really isn't any reason for you to use FLATPAK_DEST instead of /app.
It gets used by the flatpak build command.
