### ISSUE TITLE
Flatpak repair doesn't fix invalid objects

### ISSUE THREAD

**Issue by monterrr** [flatpak/flatpak#3235]
## Linux distribution and version

Fedora silverblue 31

## Flatpak version

1.4.3-3

## Description of the problem

System power went off when updating flatpaks, I'm not sure it completed the updates when power went off.

Flatpak update shows nothing to update.

Sudo flatpak repair seems doing some repairs but still shows lots of invalid objects after running it again.

Have run sudo flatpak repair for 3 times and still lots of invalid objects.

## Steps to reproduce

Don't know.

**Comment by alexlarsson** [comment]
Its really hard do do anything with so little information. Can you attach some logs of you running sudo flatpak repair?

Do you use system or per-user installs?

**Comment by monterrr** [comment]
I think it is system, they are installed on /var/lib/flatpak/app/

[flatpak repair.txt](https://github.com/flatpak/flatpak/files/3869328/flatpak.repair.txt)

**Comment by monterrr** [comment]
I compared two consecutive flatpak repairs and they show the same checksums mismatch in both instances.

**Comment by monterrr** [comment]
The repair didn't output any invalid objects as tested today. 

Was this a problem with runtime org.fedoraproject.Platform and not flatpak itself?

**Comment by alexlarsson** [comment]
I think this is an issue with the fedora runtime, it was using some non-canonical permissions that couldn't be stored in the kind of ostree repo that flatpak uses.

**Comment by alexlarsson** [comment]
I helped fix that in fedora quite some time ago though, so its a bit surprising it didn't fix itself until now...
