### ISSUE TITLE
More icon themes

### ISSUE THREAD

**Issue by georgenturner** [flatpak/flatpak#3242]
## Linux distribution and version
Debian 10

Hi Peeps, 

New to this so apologies if this is not the right way to raise this issue, but how can we get more icon themes into the flatpak repo. There are currently only two icon themes in there, and there are so many great ones available on GNOME it would be brilliant to add more into flatpak

**Comment by matthiasclasen** [comment]
if you install icon themes on your host system, flatpaks should pick them up.

**Comment by georgenturner** [comment]
I just put them in the ./icons folder in home and it doesn't sadly.

**Comment by matthiasclasen** [comment]
yeah, flatpak currently doesn't look there, but only in /usr/share/icons

**Comment by TingPing** [comment]
The issue over that is here: https://github.com/flatpak/flatpak/issues/2649

**Comment by georgenturner** [comment]
Perfect - thank you! Sorted now.

**Comment by matthiasclasen** [comment]
To make flatpaks pick up user icons, we would have to mount ~/.local/share at /run/host/user-share, and add that location in XDG_DATA_DIRS

**Comment by matthiasclasen** [comment]
flatpak master now mounts ~/.local/share/icons in /run/host/user-share/icons. Once runtimes learn to add this to XDG_DATA_DIRS, user-installed icon themes wiill start working
