### ISSUE TITLE
Left and bottom window border of Flatpak's are horribly messed up, one corruption spread to others

### ISSUE THREAD

**Issue by ioogithub** [flatpak/flatpak#3243]
## Linux distribution and version
Debian Buster 10.2

## Flatpak version
1. apt install flatpak
2. apt install gnome-software-plugin-flatpak
## Description of the problem
I have just discovered flatpacks, what a wonderful concept, excited.

I installed KeepassXC, excellent no issues. I installed wireshark- yikes a monster (see screenshot).
I uninstalled wireshark and opened Keepass, it too has turned into a monster (how?).

Somehow the corruption of wireshark has spread to keepass and killed it too. I thought Flatpaks were supposed to be sandboxed?

## Steps to reproduce
1. apt install flatpak
2. apt install gnome-software-plugin-flatpak
3. Reboot
4. Open Gnome Software Center, search for Wireshark
5. Install, Open.. feels bad
6. Open Keepass, ouch, even worse.

Keepass was totally fine until I iinstalled wireshark.

![keepass](https://user-images.githubusercontent.com/58017942/69487477-6d2d1680-0e52-11ea-8d7d-e4e67acf65a9.png)

![wireshark](https://user-images.githubusercontent.com/58017942/69487402-1ecb4800-0e51-11ea-9676-461684baf7d5.png)

No other issues to report, I have a stable unremarkable system otherwise.

**Comment by matthiasclasen** [comment]
This is not a flatpak issue. It looks like a problem with your X server or window manager.

**Comment by ioogithub** [comment]
Are you sure this is not a flatpak issue? I have never seen the issue until I installed flatpak. I installed keepass first, opened it and it looked fine. Immediately I installed wireshare, opened it and it was messed up. I then opened keepass and it was also messed up in the same way. I have since uninstalled all of the flatpaks and the issue is gone.

**Comment by refi64** [comment]
Flatpak itself doesn't really affect graphics in a way that could cause
this.

**Comment by ioogithub** [comment]
If the AppImage and deb format of an app display normally but installing the flatpak version predictably messes up the rendering and furthermore messes up the rendering of only the other flatpaks how can this be explained as not a flatpak issue then?

**Comment by matthiasclasen** [comment]
We don't know what is going on on your system, but we know what flatpak does and doesn't do. And it really does not do anything that could affect graphics in this way.

Lets establish some facts:
- whats the desktop session that this is happening with ?
- X or Wayland ?

**Comment by ioogithub** [comment]
Okay so I understand that flatpak don't do anything that can affect graphics so I guess the question is what can negatively effect the rendering of only flatpaks?

I am using Debian Buster 10.2 stable, Gnome 3.30.2 with Wayland, no shell extensions, everything is default.
VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
Laptop 1920x1080 monitor running at native resolution.

**Comment by ioogithub** [comment]
I have just learned from the Debian irc support chat room that Debian Buster includes the mesa 18.x 3D graphics library which does not support recent Intel graphics cards. This may be related to my issue. I will be looking for a distro that supports my hardware. Thanks for pointing me in the right direction.

**Comment by matthiasclasen** [comment]
hope you find newer distro release that works.

**Comment by ioogithub** [comment]
I have upgraded to Debian Bullseye "testing". The Kernel, libraries, all apps etc were majorly upgraded. I am now running the version of mesa that supports my hardware.

The issue still exists. Flatpak's left and bottom border windows are all messed up.
