### ISSUE TITLE
Cannot install flatpak on Trusty ElementaryOS Luna

### ISSUE THREAD

**Issue by kabeza** [flatpak/flatpak#3254]
## Linux distribution and version
ElementaryOS Luna - Trusty 14.04

## Flatpak version
Latest

## Description of the problem
Cannot install. Cannot find the package in the ppa

## Steps to reproduce
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak

I'm trying to install a new app which is only available through flatpak
I've added the ppa to the system, did a apt-get update, but the package cannot be found
Is there a way to make it work in this version?

Thanks
![imagen_504](https://user-images.githubusercontent.com/274856/69726260-e9e41d00-10fe-11ea-9b89-26d7fdf87f34.jpg)

**Comment by refi64** [comment]
Ubuntu Trusty has already reached its end of life several months ago, I'd
be surprised if most PPAs still worked on it.

**Comment by kabeza** [comment]
I know, but cannot upgrade directly. I'd need to format and reinstall everything again. 
Most of the ppa I use have some (alt) .deb file to manually install, and have been going that way with most of the apps I have

**Comment by mwleeds** [comment]
I'd suggest backing up your home directory, installing a newer OS, and restoring your home directory.
