### ISSUE TITLE
filesystem path as lib path of /app/etc/ld.so.conf

### ISSUE THREAD

**Issue by walking98** [flatpak/flatpak#3256]
## Steps to reproduce
It is a genernal requirement from my scenario:

1. define the lib path in hosted machine:
   /opt/flatpak-3rdparty/abc/1.0/abc.so

2. include the lib in /app/etc/ld.so.conf:
   /opt/flatpak-3rdparty/abc/1.0/

3. run with --filesystem:
   flatpak run --filesystem=/opt/flatpak-3rdparty my.app

The fact is that the ldconfig cmd has been run to generate the ld.so.cache (i.e. ~/.var/$app/.ld.so/active) before the flatpak has a chance to add the external filesystem into the sandbox file system. (common/flatpak-run.c) 

Do we have an alternative option to support this scenario?  

Thanks in advance for any reply or suggestion.

**Comment by matthiasclasen** [comment]
I don't think we want flatpaks to use libraries that are installed somewhere on the host, other than the ones that are either in the runtime that it uses, or bundled with the app.

**Comment by walking98** [comment]
Here are my simple reason of using the shared lib in host:
Using host shared libraries is more flexible than defining as extensions of the runtime. User does not need to change the runtime (e.g. metadata) when adding or removing a shared lib, instead they only need to change the /app/etc/ld.so.conf.
If a same shared lib bundled with multi apps (I understand that means to install/copy the lib into app/lib directory),  that will cause ldconfig load the lib multi times for different apps.

**Comment by walking98** [comment]
BTW, The issue can be solved by using the flatpak setting "--env=LD_LIBRARY_PATH=...", but it is not convenient enough when these libs exist in different sub-directories, that is, we need to declare each subpaths in the LD_LIBRARY_PATH.

**Comment by matthiasclasen** [comment]
This very much goes against the goals of flatpak.

**Comment by TingPing** [comment]
Libraries are only duplicated when they are different. They may be different by accident but they may be different because they have a different ABI.

Letting users put their own libs in the sandbox is most likely just going to introduce breakage and is entirely unsupportable. The entire purpose of Flatpak is to be a self-contained, portable, and reproducable format and host data is none of those.

**Comment by walking98** [comment]
The shared libs are not users own, in fact they should be thought as part of the flatpak runtime artifacts. In current fp installation directory hierarchy, there are two main entries, runtime and app. It will more understandable if we take the shared-lib as an extra entry, i.e.    
~/.local/share/flatpak/
   -- app/
   -- runtime/
   -- shared-lib/

The shared-lib holds full set of libs for multiple apps in the host (and customize the concreted ones through /app/etc/ld.so.conf for each app), the shared-lib is level between runtime and app, it brings the bundle or runtime decoupling advantage when upgrating these shared libs.  Furthermore we can use the following flatpak consistent commands to maintain them:

flatpak install --sharelib abc//1.0
flatpak update --sharelib abc//1.0

**Comment by damianatorrpm** [comment]
So basically runtime extensions?

**Comment by TingPing** [comment]
> flatpak install --sharelib abc//1.0

An explicit non-goal of the project is to become a generic package manager ala rpm or such. You get a runtime and that is all.

**Comment by walking98** [comment]
cool, I just read the blog about introducing extensions into an application: https://blog.tingping.se/2018/03/18/flatpaking-plugins.html

so my scenario can be solved using the app + ext
