### ISSUE TITLE
GPG error when installing stable apps on fedora 24

### ISSUE THREAD

**Issue by ment0s** [flatpak/flatpak#326]
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: While pulling 
                runtime/org.gnome.Platform/x86_64/3.22 from remote gnome: GPG signatures found, but none are in trusted keyring

**Comment by bagage** [comment]
Same error here; while `flatpak install gnome org.gnome.Platform 3.20` works fine, `flatpak install gnome org.gnome.Platform 3.22 ` fails.
Same issue reported on [google+](https://plus.google.com/+FelixHäcker1207/posts/98GH6r9XzQR)

**Comment by alexlarsson** [comment]
Thats weird. It seems to work with flatpak install --user with the same gpg keys.

**Comment by bagage** [comment]
Well, not exactly @alexlarsson:
```sh
$ flatpak install gnome org.gnome.Platform 3.22 --user 
9 delta parts, 74 loose fetched; 173704 KiB transferred in 617 seconds                                   
Installing related: org.gnome.Platform.Locale
Warning: Failed to install related ref: runtime/org.gnome.Platform.Locale/x86_64/3.22
$ flatpak install gnome org.gnome.Platform 3.22 --user 
error: While pulling runtime/org.gnome.Platform/x86_64/3.22 from remote gnome: GPG signatures found, but none are in trusted keyring
```

**Comment by alexlarsson** [comment]
For "reasons", the 3.22 commits were signed with the nightly key by mistake. Should work now (at least for x86-64).

The question is actually why it worked with --user. Looking into that now.

**Comment by ment0s** [comment]
flatpak remote-add --gpg-import=gnome-sdk.gpg gnome https://sdk.gnome.org/repo/
flatpak remote-add --gpg-import=gnome-sdk.gpg gnome-apps https://sdk.gnome.org/repo-apps/
**flatpak install gnome org.gnome.Platform 3.22**

3 metadata, 0 content objects fetched; 1 KiB transferred in 6 seconds                                                                                                                                                                        
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: While pulling runtime/org.gnome.Platform/x86_64/3.22 from remote gnome: **Couldn't find file object** '4b7daa6f212564dc73e696e49e532a7d990483ce3a8b71723f350938c02c15db'
-------------------------------------------------------------------------------------------------------------------------

**flatpak install gnome org.gnome.Platform 3.20**

9 delta parts, 71 loose fetched; 167691 KiB transferred in 42 seconds                                                                                                                                                                        
Installing related: org.gnome.Platform.Locale

4 metadata, 1 content objects fetched; 1 KiB transferred in 2 seconds                                                                                                                                                                        

2 metadata, 0 content objects fetched; 13 KiB transferred in 1 seconds               
                                                                                                                                                        
flatpak run org.gnome.gedit
**error: runtime/org.gnome.Platform/x86_64/3.22 not installed**

**Comment by ment0s** [comment]
**Seems to be resolved. Big Thanks !**

[ment0s@thinkD tmp]$ **flatpak install gnome org.gnome.Platform 3.22**

9 delta parts, 15 loose fetched; 118415 KiB transferred in 31 seconds                                                                                                                                                                        
Installing related: org.gnome.Platform.Locale

4 metadata, 0 content objects fetched; 1 KiB transferred in 2 seconds                                                                                                                                                                        

2 metadata, 0 content objects fetched; 13 KiB transferred in 1 seconds                                                                                                                                                                       
[ment0s@thinkD tmp]$ **flatpak run org.gnome.gedit**

** (gedit:2): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-t2FclRhBUI: Connection refused
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"

(gedit:2): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(gedit:2): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(gedit:2): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned

(gedit:2): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

**Comment by alexlarsson** [comment]
Ah, it seems --user worked because of static deltas in signed summary (https://github.com/ostreedev/ostree/issues/517)
