### ISSUE TITLE
how can i globally set the compose key to lwin?

### ISSUE THREAD

**Issue by milomak** [flatpak/flatpak#3262]
## Linux distribution and version
Solus

## Flatpak version
flatpak, version: 1.0.9, release: 30

## Description of the problem
I have the left windows key set as my compose key via .bashrc using setxkbmap -option compose:lwin

## Steps to reproduce
When I run an an app installed via flatpak, the compose key is not picked up

**Comment by srgvg** [comment]
I experience something similar (Sway/wayland), albeit that it sometimes work, and sometimes not, whiulst it always works outside of flatpak.

I'm not sure if it is application specific, or if it stops working after some time.

When it doesn't work, restarting the (flatpak) application does not help.
