### ISSUE TITLE
Missing root file system access

### ISSUE THREAD

**Issue by Bittyby** [flatpak/flatpak#3263]
## Linux distribution and version
Ubuntu 18.04

## Flatpak version
latest of ppa

## Description of the problem
When using KeePassXC, Visual Code, Dolphin, a number of functionalities do not work.

https://github.com/flathub/org.keepassxc.KeePassXC/issues/46
https://github.com/flathub/org.kde.dolphin/issues/13
https://github.com/flathub/com.visualstudio.code/issues/123

## Steps to reproduce
Install KeePassXC, Visual Code, Dolphin.
Click the links above to familiarize yourself with the problem

**Comment by TingPing** [comment]
The `/root` directory is never allowed into the sandbox.

http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

**Comment by Bittyby** [comment]
@TingPing 

If you read the links above, then I already use `flatpak override org.keepassxc.KeePassXC --filesystem = host`.
And here is a list of bugs:

Dolphin:
1. I can’t associate a file extension with respect to a program. For example: `Visual Code`.
Dolphin just does not see `Visual Code`, but sees only from its package (for example,` Ark`). Not to mention the programs in / opt /.

2. When saving files to the same / root, it simply does not save (after closing dolphin).

KeePassXC:
1. The base which lies in the same / root does not open.
2. The part of the functionality that is tied to `host FS` does not work.

Proceed?
All these problems are related to host FS. If this works for you, then you can give an example, how can I make it work?

**Comment by TingPing** [comment]
It can't really work as-is, its entirely counter to how the sandbox works.

There are methods of escaping the sandbox but that isn't really how its intended to be used and requires modifying how the applications work.

**Comment by RokeJulianLockhart** [comment]
Does a `flatpak` issue to allow access to `/root` exist?

**Comment by TingPing** [comment]
`--filesystem=host` never mounts `/root`.

`flatpak-spawn --host` can do roughly anything though, yes.

**Comment by RokeJulianLockhart** [comment]
So can we reopen this?
