### ISSUE TITLE
UpdateMonitor's check_for_updates() should check for "refresh-when-metered" setting

### ISSUE THREAD

**Issue by pwithnall** [flatpak/flatpak#3286]
A few respondents to the [GNOME metered data survey](https://tecnocode.co.uk/2019/03/21/metered-data-hackfest/) indicated that in-app updates were causing them problems by using bandwidth when they were on a metered connection. While I think those respondents were talking about some proprietary apps, or `snapd`, I took a look at the code in `portal/flatpak-portal.c` and it seems that the portal’s behaviour doesn’t change while on a metered connection. It always polls for updates every 30 minutes.

I’m not sure we can disable automatic update checks entirely when on a metered connection (since some people’s primary connections are metered, so they’d never get any updates), but we could radically reduce the frequency of update checks (to once a day, say). That’s just a suggestion to get discussion started.

**Comment by mwleeds** [comment]
Some prior discussion of this here: https://github.com/flatpak/flatpak/pull/2905#discussion_r322991073

**Comment by pwithnall** [comment]
Thanks, Here’s a related gnome-software issue I filed at the same time as this one: https://gitlab.gnome.org/GNOME/gnome-software/issues/869

**Comment by matthiasclasen** [comment]
It sounds like we either need the portal to be aware of the network environment and implement policy itself, or have some sort of configuration (gsettings ?) to let somebody else (gnome-software ?) control the policy.

**Comment by pwithnall** [comment]
Seems fine to me for the portal to be aware of the network environment and implement its own policy. It’s just a case of using a `GNetworkMonitor`.

**Comment by hadess** [comment]
> It sounds like we either need the portal to be aware of the network environment and implement policy itself, or have some sort of configuration (gsettings ?) to let somebody else (gnome-software ?) control the policy.

I think that "in-app updates" are supposed to be "network updates made by applications", for example, a feedreader downloading new items, or a mail client synchronising e-mails, not "software" updates.

In which case, there's already an "opt-in" with the `GetMetered` portal, and `network-metered` `GNetworkMonitor` property, but proper per-app network namespacing at the Flatpak level would be super useful, like being able to show usage of particular apps over time, when they got used, throttling them during "expensive" periods, how much data got used when over mobile networks, or over work or school Wi-Fi.

**Comment by hadess** [comment]
From [How to check data usage on an iPhone or iPad](https://www.digitaltrends.com/mobile/how-to-check-data-usage-on-an-iphone/):
[ios-12-cellular-data-1-1242x2208](https://user-images.githubusercontent.com/769861/70537434-ac50ac80-1b60-11ea-8520-b472ace9f19c.jpg)
[ios-12-cellular-data-2-1242x2208](https://user-images.githubusercontent.com/769861/70537432-ac50ac80-1b60-11ea-946c-896428917aef.jpg)
[ios-12-cellular-data-3-1242x2208](https://user-images.githubusercontent.com/769861/70537431-abb81600-1b60-11ea-93c4-85435941e433.jpg)

**Comment by pwithnall** [comment]
> I think that "in-app updates" are supposed to be "network updates made by applications", for example, a feedreader downloading new items, or a mail client synchronising e-mails, not "software" updates.

I can’t be totally sure, but my reading of the comments people left in response to the survey indicated that this was about software updates for apps which are automatically downloaded from within the app.

I have filed a load of other bugs against various apps for the data they use (feed updates, mail downloads, etc.).

**Comment by hadess** [comment]
> I can’t be totally sure, but my reading of the comments people left in response to the survey indicated that this was about software updates for apps which are automatically downloaded from within the app.

Steam game updates for example? I can't think of many other software for which this would be a problem, and I don't think that there would be a way for a "Flatpak network proxy" to differentiate between software and data updates. I think you did the right thing filing bugs against updates that don't have a download policy configurable.

In the long term, we'd need some sort of per-app networking interface which we can monitor and control, to impose the policy upon apps. In the meantime, we're expecting them to behave well...

**Comment by pwithnall** [comment]
> Steam game updates for example?

Steam was listed individually by a number of people, and I need to file a bug about that with Valve.

> I can't think of many other software for which this would be a problem

One example of the kind of software which does this is Signal, which automatically downloads new versions in the background. I believe they’ve turned that behaviour off in their flatpak, but the principle still holds.

> and I don't think that there would be a way for a "Flatpak network proxy" to differentiate between software and data updates. I think you did the right thing filing bugs against updates that don't have a download policy configurable.

The update monitor portal is one way of distinguishing. Any traffic from that is definitely to do with updates.

> In the long term, we'd need some sort of per-app networking interface which we can monitor and control, to impose the policy upon apps. In the meantime, we're expecting them to behave well...

That’s in the long-term plans for [Mogwai](https://gitlab.freedesktop.org/pwithnall/mogwai), but I don’t have any time scheduled for it at the moment. The basic idea would be to use systemd’s per-cgroup network limit support to monitor and cap usage on a per-app basis, and to have that be controlled by Mogwai and some user preferences.

**Comment by hadess** [comment]
> > Steam game updates for example?
> 
> Steam was listed individually by a number of people, and I need to file a bug about that with Valve.

Right.

> > I can't think of many other software for which this would be a problem
> 
> One example of the kind of software which does this is Signal, which automatically downloads new versions in the background. I believe they’ve turned that behaviour off in their flatpak, but the principle still holds.

That's definitely a bug in the application, as it won't even be able to update itself after downloading a new copy...

> > and I don't think that there would be a way for a "Flatpak network proxy" to differentiate between software and data updates. I think you did the right thing filing bugs against updates that don't have a download policy configurable.
> 
> The update monitor portal is one way of distinguishing. Any traffic from that is definitely to do with updates.

Ha!

> > In the long term, we'd need some sort of per-app networking interface which we can monitor and control, to impose the policy upon apps. In the meantime, we're expecting them to behave well...
> 
> That’s in the long-term plans for [Mogwai](https://gitlab.freedesktop.org/pwithnall/mogwai), but I don’t have any time scheduled for it at the moment. The basic idea would be to use systemd’s per-cgroup network limit support to monitor and cap usage on a per-app basis, and to have that be controlled by Mogwai and some user preferences.
> 
> (But this is now getting quite far off topic!)

And Ha! again. I finally understood what the issue was about... Let me retitle it.

**Comment by matthiasclasen** [comment]
Is that an existing setting somewhere ?

**Comment by hadess** [comment]
gnome-software's `refresh-when-metered` setting can be set to `false` to disable update checking when on a metered connection.

**Comment by matthiasclasen** [comment]
Left for future refinement: keep polling at a much reduced rate
