### ISSUE TITLE
IMPROVE CLI APPLICATION EXPERIENCE

### ISSUE THREAD

**Issue by SwitchedToGitlab** [flatpak/flatpak#3288]
@matthiasclasen Close this issue without addressing something the community has been SCREAMING about and we're going to have a real big personal problem. I get that you just dont care about what the community wants, well tough shit. You're going to make some changes here, or this project is getting forked. Flatpak needs all the support it can get from the community if it's going to be used for anything, and your terrible attitude is not helping in the least. 

WE ARENT ASKING HERE. WE'RE TELLING YOU: IMPROVE THE FLATPAK CLI EXPERIENCE.

This is not a request. 

Close this issue and I will open another one every day until this is done. We've had ENOUGH of your attitude.

**Comment by matthiasclasen** [comment]
You  think shouting and tweeing is going to make your case more compelling ? Good luck :)

**Comment by aiamuzz** [comment]
> @matthiasclasen Close this issue without addressing something the community has been SCREAMING about and we're going to have a real big personal problem. I get that you just dont care about what the community wants, well tough shit. You're going to make some changes here, or this project is getting forked. Flatpak needs all the support it can get from the community if it's going to be used for anything, and your terrible attitude is not helping in the least.
> 
> WE ARENT ASKING HERE. WE'RE TELLING YOU: IMPROVE THE FLATPAK CLI EXPERIENCE.
> 
> This is not a request.
> 
> Close this issue and I will open another one every day until this is done. We've had ENOUGH of your attitude.

@matthiasclasen Close this issue without addressing something the community has been SCREAMING about and we're going to have a real big personal problem. I get that you just dont care about what the community wants, well tough shit. You're going to make some changes here, or this project is getting forked. Flatpak needs all the support it can get from the community if it's going to be used for anything, and your terrible attitude is not helping in the least.

WE ARENT ASKING HERE. WE'RE TELLING YOU: IMPROVE THE FLATPAK CLI EXPERIENCE.

This is not a request.

Close this issue and I will open another one every day until this is done. We've had ENOUGH of your attitude.@matthiasclasen Close this issue without addressing something the community has been SCREAMING about and we're going to have a real big personal problem. I get that you just dont care about what the community wants, well tough shit. You're going to make some changes here, or this project is getting forked. Flatpak needs all the support it can get from the community if it's going to be used for anything, and your terrible attitude is not helping in the least.

WE ARENT ASKING HERE. WE'RE TELLING YOU: IMPROVE THE FLATPAK CLI EXPERIENCE.

This is not a request.

Close this issue and I will open another one every day until this is done. We've had ENOUGH of your attitude.


@SwitchedToGitlab ... Well the last time i checked ... in the open source world ... NOBODY OWE'S ANYBODY ANYTHING !!!

IF YOU WANT SOMETHING SO BADLY ... GET IN THE TRENCHES(START TO CONTRIBUTE CODE YOURSELF) AND GET DIRTY(BUT IN A CO-OPERATIVE WAY) ...

SO I GUESS THE TONE OF THIS THREAD IS GRAVELY MISPLACED !!!
