### ISSUE TITLE
Can't modify an existing remote

### ISSUE THREAD

**Issue by tannisroot** [flatpak/flatpak#3296]
## Linux distribution and version
Arch Linux, updated it yesterday
## Flatpak version
1.5.1
## Description of the problem / Reproduction Steps
I can't modify a parameter of an existing remote. I have a remote called `flathub`, which shows up if I run `flatpak remote-list`, and I want to to install apps in my user directory instead of root.
So I run `flatpak remote-modify --user flathub` on it. But I get an error: `error: Remote "flathub" not found`. I try a different option to achieve the same thing (i think?): `flatpak remote-modify --installation=extra flathub` (i've created a custom installation dir previously). Same error! But if I try another option, like `--disable`, or `--enable`, I don't get such error and it disables/enables the remote.
The expected behavior here is obviously that flatpak should modify the remote and not pretend that it doesn't exist when it clearly does.

**Comment by refi64** [comment]
--user tells Flatpak to look for the remote in the user install, not to
move it over. In general, --user and --system consistently cause Flatpak to
look solely at the corresponding installation for whatever action you're
performing.

**Comment by alexlarsson** [comment]
Does it show up as Option "user" in remote-list, or does it show up in `flatpak remote-list --user`? If not, it is a system remote and you can't expect there to be a similarly named user remote. Either create the remote using remote-add --user, or modify the system remote by not adding the --user to remote-modify.

**Comment by alexlarsson** [comment]
Basically, the behaviour:
 * If --user is specified, only work on remotes in the user installation
 * If --system is specified, only work on remotes in the system installation
 * If none is specified, and the operation takes a remote name, look in both for the remote
 * If none is specified and there is not remote name, default to system
