### ISSUE TITLE
Broken English in authentication prompt

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#330]
I was installing a flatpak bundle with "flatpak install --bundle". I received a polkit prompt: "Authentication is install software." It's missing the words "required to."

**Comment by matthiasclasen** [comment]
Odd. Works ok here. Does that mangled string appear in /usr/share/polkit-1/actions/org.freedesktop.Flatpak.policy ?

**Comment by mcatanzaro** [comment]
Yup

**Comment by mcatanzaro** [comment]
It was fixed by https://github.com/flatpak/flatpak/commit/5fe85664614647cf3492630502b401f41ac40b45
