### ISSUE TITLE
fedora runtimes take double space instead of being deduped

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3301]
## Linux distribution and version
Fedora Silverblue 31
## Flatpak version
1.4.2
## Steps to reproduce
```
# 1. [✓] org.fedoraproject.Platform  x86_64  f31  fedora 523.8 MB / 523.8 MB
# 1. [✓] org.fedoraproject.Platform  x86_64  f30  fedora 433.9 MB / 433.9 MB
=> even without ostree dedup 
=> this would be less than 1GB
du -hc --max-depth=2
....
2.3G	./runtime/org.fedoraproject.Platform
....

cd runtime/
du -sh org.fedoraproject.Platform/x86_64/f30/ org.fedoraproject.Platform/x86_64/f31/
1.2G	org.fedoraproject.Platform/x86_64/f30/
1.1G	org.fedoraproject.Platform/x86_64/f31/

du -sh org.fedoraproject.Platform/x86_64/f31/ org.fedoraproject.Platform/x86_64/f30/
1.2G	org.fedoraproject.Platform/x86_64/f31/
1.1G	org.fedoraproject.Platform/x86_64/f30/
```
Am I interpreting this the wrong way?

**Comment by TingPing** [comment]
This mostly sounds like an issue to report to the Fedora folks. It isn't too surprising that entire distros changing will not de-dupe easily but Fedora may not be as reproducible as one would hope.

**Comment by damianatorrpm** [comment]
Well not deduping is one thing but it takes twice the space flatpak reports please check the output again.

**Comment by TingPing** [comment]
I believe the numbers are download size not storage size.

**Comment by alexlarsson** [comment]
That is the download size, and the reason it is not smarter for duplication is that fedora is using OCI to ship its flatpak rather than ostree, which doesn't have any kind of delta or update smartness. Each new download is a full tarball.

On the disk the tarball will be extracted into an ostree repo, so sharing will happen.

**Comment by alexlarsson** [comment]
I should note that in *general* you can't actually expect there to be massive deduplication between two completely different versions like F30 and F31. For such a large change i think most files will have changed. For one, everything is built with a different compiler.

**Comment by damianatorrpm** [comment]
Thanks it was not clear that this is the download size. I understand in that case.
