### ISSUE TITLE
How to mass deploy flatpak app and runtime on local network?

### ISSUE THREAD

**Issue by Yvan-Masson** [flatpak/flatpak#3302]
Hi,

I would like to deploy a Flatpak app and associated runtime on many computers on a local network. What solution could be used to do this efficiently? Is there a built-in tool like `flatpak create-usb`?

Thanks all the work done and for advice,
Yvan

**Comment by refi64** [comment]
I think you probably want something like Ansible:
https://docs.ansible.com/ansible/latest/modules/flatpak_module.html

**Comment by mwleeds** [comment]
Sadly the support for pulling flatpak updates from other computers on a LAN was not in a usable state last I checked. But if you want to avoid re-downloading the same data on each computer, one option would be to mount a network share on each computer, and copy flatpaks to it with `flatpak create-usb`. Then when you install them (e.g. using Ansible) it will pull from the network share. For that to work each computer will need a collection ID set on the flathub remote (`flatpak remote-modify --collection-id=org.flathub.Stable flathub`).

**Comment by Yvan-Masson** [comment]
@refi64 You are right, and I am already using Ansible to manage this network (Windows and Linux desktops) :-) . But as @mwleeds said, I want to avoid downloading the same data on every computer (this would be a waste of resources for our WAN link and Flathub servers).

Thanks @mwleeds, this is a good idea, I will try it when I have time.

Regards,
Yvan
