### ISSUE TITLE
leaks system-cache fds when opening system installations

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#3303]
## Linux distribution and version

Debian unstable/experimental

## Flatpak version

1.4.3, 1.5.2, git master

## Description of the problem

The `testlibrary` regression test uses many file descriptors, which appear to be leaked. I noticed this while packaging development release 1.5.2 for experimental, but I can also reproduce it with 1.4.3:

```
(in one terminal)
$ watch 'ls -l /proc/$(pgrep testlib|head -n1)/fd'

(in another terminal)
$ gnome-desktop-testing-runner Flatpak/testlibrary.test
```

shows hundreds of file descriptors appearing, mostly pointing to `system-cache` or to eventfds.

While packaging 1.5.2, this caused the installed-tests to fail (when run in a virtual machine that presumably has a lower fd limit than my laptop). `testlibrary` crashes when an attempt to create an eventfd for a `GWakeup` object inside GLib fails with `EMFILE`, "Too many open files".

## Steps to reproduce

Run the `testlibrary` test.

One useful reproducer is:

```
# first make a temporary directory, cd into it, and create a file named `.testtmp` there

rm -fr *

G_TEST_SRCDIR="$srcdir/tests" \
G_TEST_BUILDDIR="$builddir/tests" \
G_DEBUG=gc-friendly \
G_SLICE_DEBUG=always-malloc \
"$builddir/libtool" \
--mode=execute \
valgrind \
--track-fds=yes \
--num-callers=20 \
--leak-check=full \
--gen-suppressions=all \
--suppressions=/usr/share/glib-2.0/valgrind/glib.supp \
"$builddir/testlibrary" \
-p /library/multiple-system-installation \
-p /library/multiple-system-installation \
-p /library/multiple-system-installation
```

which shows a lot of fds pointing to `/tmp/flatpak-test-15Q6C0/home/cache/flatpak/system-cache`.

Let's use this bug report to represent the `system-cache` leak, and if eventfds are still leaked after fixing that, it can be treated as a separate bug.

## Expected result

A few fds (perhaps between 10 and 100?) are opened during each test but closed afterwards.

**Comment by smcv** [comment]
I think the `system-cache` leak might be because in `OstreeRepo`, `ostree_repo_open()` assumes that `self->cache_dir_fd` is -1 (if there is a cache directory already open, it doesn't close it), which effectively means it's assuming that `ostree_repo_set_cache_dir()` will only be called *after* `ostree_repo_open()` - but in fact Flatpak calls `ostree_repo_set_cache_dir()` *before* `ostree_repo_open()` if I'm reading the code correctly.

If that analysis is correct, I don't know whether the leak is a Flatpak bug (should call those functions in the other order) or an ostree bug (should not assume they are called in a particular order). @cgwalters, do you have any insight into whose bug that would be?

**Comment by alexlarsson** [comment]
Ideally ostree should be self-consitent here. If it allows calling set_cache_dir() ahead of time it should be able to handle it. On the other hand, its pretty easy to just fix in flatpak and then it will work with older ostree versions too.

In any way, it will just affect the testsuite, because the override of the cache_dir in repo_open() only happens if the object dir in the system repo is writable by the user, which is not normally true.
