### ISSUE TITLE
Cannot run Steam when trying to access own files

### ISSUE THREAD

**Issue by redandvidya** [flatpak/flatpak#3306]
## Description of the problem

Hi, I installed Steam Flatpak on LMDE. It works fine, but when I try to give it access to my root folder by using the command `sudo flatpak override com.valvesoftware.Steam --filesystem="/"`,  and run Steam again, it returns `bwrap: Can't create file at /run/user/1000/pulse/native: No such device or address`

I am trying to use my entire hard drive, so I can give Steam easy access to my hard drive, which has backups of all my games on it.

## Linux distribution and version
Linux Mint Debian Edition 3, (based on Debian Stretch)

## Flatpak version
Flatpak 1.2.5

**Comment by smcv** [comment]
Does `--filesystem=host` work? That's the closest thing to `--filesystem=/` that is expected to work.

Not all of `/` can be shared because some directories, like `/run` and `/usr`, have purposes that are hard-coded in Flatpak itself (for example the runtime gets mounted on `/usr`).

**Comment by TingPing** [comment]
@smcv Don't recommend that for the Steam flatpak, it uses `--persist` and that breaks everything

**Comment by smcv** [comment]
OK, in that case: for Steam specifically, neither `--filesystem=/` nor `--filesystem=host` is meant to work. Use `--filesystem=/media/bigdisk` or similar to share specific locations.

For non-Steam Flatpak apps, `--filesystem=/` is unlikely to work, and `--filesystem=host` is the closest working equivalent.

**Comment by alexlarsson** [comment]
Yeah, this is a weirdness of how steam is sandboxed, just give it access to the game directory only.

**Comment by smcv** [comment]
@alexlarsson: Would it maybe make sense to produce a more specific/helpful error message indicating "this can't work" if a user combines `--filesystem=home` or `--filesystem=host` with `--persist=.`? (If I'm understanding correctly that `--persist=.` is the weird thing that the Steam Flatpak does.)

Similarly, maybe `--filesystem=/` should be treated as a shorthand for `--filesystem=host`, or disallowed with a helpful message?

**Comment by TingPing** [comment]
Broad filesystem permissions break all persist options.

**Comment by nthrow** [comment]
This is still broken.

**Comment by nthrow** [comment]
Then what's the point of having a steam flatpak again?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to "http://github.com/flatpak/flatpak/issues/3306#issuecomment-774544776".

Consistent automation of installation.

**Comment by pmarreck** [comment]
Ran into this issue when trying to give Steam Flatpak access just to my home directory. It simply refused to launch after that- no visible error message (at least without digging). I just want to give it access to my ~/Downloads at least, so I can run installers... sigh, this reminds me of a time when I was developing apps on Windows and 80% of the problems were actually NTFS-permissions-related

**Comment by pmarreck** [comment]
For anyone else who lands here, fire up Flatseal and in the file access permissions section for Steam, add `xdg-download:ro` to add your distro's standard Downloads directory as read-only access. That was sufficient for me, at least.

**Comment by rokejulianlockhart** [comment]
@alexlarsson, https://github.com/flatpak/flatpak/issues/3306#issuecomment-1575335587
