### ISSUE TITLE
test_install_launch_uninstall: assertion failed (progress_count > 0): (0 > 0)

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#3313]
## Linux distribution and version

Debian unstable/experimental; GLib 2.63.2; libostree 2019.6

## Flatpak version

1.5.2 or git master, with #3307, #3310, #3311, #3312 applied

## Description of the problem

```
**
flatpak:ERROR:tests/testlibrary.c:1459:test_install_launch_uninstall: assertion failed (progress_count > 0): (0 > 0)
Bail out! flatpak:ERROR:tests/testlibrary.c:1459:test_install_launch_uninstall: assertion failed (progress_count > 0): (0 > 0)
cleaning up pid 13378
FAIL: Flatpak/testlibrary.test (Child process killed by signal 6)
```

## Steps to reproduce

Run `testlibrary`. It sometimes fails with the assertion above.

In particular, it seems to reliably fail with that assertion when I configure git master with:

* `CFLAGS="-Og -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=all"`
* `LDFLAGS="-fsanitize=address -fsanitize=undefined -fsanitize-recover=all"`

and run with:

```
ASAN_OPTIONS=exitcode=0 make -C "$builddir" -j5 check-TESTS TESTS=testlibrary
```

to check whether memory leaks have been fixed.

**Comment by alexlarsson** [comment]
Should be fixed by https://github.com/flatpak/flatpak/pull/3314
