### ISSUE TITLE
XDG_DATA_DIRS warnings break flatpak-builder

### ISSUE THREAD

**Issue by dbnicholson** [flatpak/flatpak#3316]
## Linux distribution and version

Debian buster (10)

## Flatpak version

1.5.0

## Description of the problem

On our builder, `XDG_DATA_DIRS` is not set to include the flatpak exports directories because there's no intention of running the flatpaks. `flatpak` prints a harmless warning about this, but it actually breaks `flatpak-builder` in the finish stage when inheriting extensions for a runtime because it calls `flatpak info --show-metadata` and this message gets mixed in. The build then fails when it tries to load this output as a key file with:

```
Error: Can't load metadata file: Key file contains line “Note that the directories ” which is not a key-value pair, group, or comment
```

## Steps to reproduce

Probably a simpler way, but:
```
git clone https://github.com/endlessm/endless-sdk-flatpak.git
unset XDG_DATA_DIRS
make install-dependencies
make sdk
```
Or, just to see the damage:
```
XDG_DATA_DIRS= flatpak info --show-metadata org.freedesktop.Platform
```

**Comment by alexlarsson** [comment]
Yeah, i think we should only print this if stdout is a tty, and only in certain operations, like run, install, update.
