### ISSUE TITLE
Expose /dev/kvm via a --device=DEVICE flag

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#332]
The Android SDK for Linux mandates KVM support to run x86/amd64 emulators, and testing your apps is sloooooooooooooooooooooooooooooooooooooooooooooooooooow if you opt to emulate ARM instead.

I'm using --device=all, but it would be nice to have a narrower permission option.

**Comment by alexlarsson** [comment]
Can you test this in master?

**Comment by Jayuda** [comment]
yes work with --device=kvm
