### ISSUE TITLE
[question/suggestion] speedup first run

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3333]
When an application is installed and first launched depending on the application it takes a long time to start creating .var/app/%app% etc.

Is there a command to pre-generate these?
```
flatpak run --not-run-but-prepare $app
flatpak_installed_ref_prepare(FlatpakInstalledRef *ref)
```

**Comment by TingPing** [comment]
I imagine that command would be `flatpak run --command=fc-cache $app`.

**Comment by damianatorrpm** [comment]
Great. Thanks.

**Comment by damianatorrpm** [comment]
@TingPing Are you aware of something similar for mesa-shader-cache or some further improvement?
