### ISSUE TITLE
socket path too long

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3336]
gnome-boxes https://gitlab.gnome.org/GNOME/gnome-boxes/issues/267 is not the only flatpak application that is affected by this e.g rocket chat is as well and others.

If an organizations username structure is firstname.lastname@organization.org for example my username (more than one first name, not to mentioned that in some regions  middle-name's are used as well) would be 42 characters which exceeds the limit (17) mentioned in  the gnome BR.

IIRC correctly the socket path could be used as relative path instead of absolute to circumvent this issue. Would this be something feasible for flatpak?

**Comment by matthiasclasen** [comment]
This is really not a flatpak issue. Applications need to respect the limits imposed by the OS, and not blindly use paths that are too long.

**Comment by damianatorrpm** [comment]
> Applications need to respect the limits imposed by the OS, and not blindly use paths that are too long.

While probably true, a bunch of flatpaks do this, shouldn't flatpak work around this by using relative path socket names instead to provide a coherent user experience no matter how long the username is?

**Comment by refi64** [comment]
Flatpak can't really control that. It's entirely in app territory as to how
paths are handled. This in particular is likely done via code inside Boxes.

**Comment by damianatorrpm** [comment]
@refi64 What you are saying is that gnome boxes and lots of electron apps that are affected by this run with flatpak by lucky accident - the short name of .var/App directory. If it were only few characters longer all these apps would fail.
