### ISSUE TITLE
gitg under flatpak is not reading user config

### ISSUE THREAD

**Issue by albfan** [flatpak/flatpak#3337]
## Linux distribution and version
Arch linux
## Flatpak version
Flatpak 1.5.2
## Description of the problem
git config reads `$XDG_CONFIG_HOME/git/config` for config
https://git-scm.com/docs/git-config#Documentation/git-config.txt---global

```
--global
For writing options: write to global ~/.gitconfig file rather than the repository .git/config, write to $XDG_CONFIG_HOME/git/config file if this file exists and the ~/.gitconfig file doesn’t.

For reading options: read only from global ~/.gitconfig and from $XDG_CONFIG_HOME/git/config rather than from all available files.
```
But flatpak conventions http://docs.flatpak.org/es/latest/conventions.html#xdg-base-directories says that `XDG_CONFIG_HOME` is `~/.var/app/<app-id>/config`

I set some git config on `~/.var/app/org.gnome.gitgDevel/config/git/config` and it works as expected (reads those config values) but from user perspective, this is not correct as user expect to have config on `~/.config/git/config`

Is there any solution to deal with this? I found

```
--filesystem=xdg-config/git:ro
```

Which seems to do some symlink from `~/.config/git/config` to `~/.var/app/org.gnome.gitgDevel/config/git/config` but I'm not sure. I found https://github.com/flatpak/flatpak/issues/118 which discourages it and http://docs.flatpak.org/es/latest/sandbox-permissions-reference.html do not mention `xdg-config` at all.

## Steps to reproduce

Create file ~/.config/git/config

```
[user]
   name = John Doe
   email = jdoe@email.org
```

Be able to read as `$XDG_CONFIG_HOME/git/config` from flatpak

See https://gitlab.gnome.org/GNOME/gitg/merge_requests/118 and specifically https://gitlab.gnome.org/GNOME/gitg/merge_requests/118/diffs?commit_id=d0c0f42269e2d25c95509e54725af91669ae8a5e

**Comment by refi64** [comment]
#118 is referring to autostart files which go in ~/.config, not the
exposure of ~/.config itself.

**Comment by albfan** [comment]
Nor I, cause I'm looking for `~/.config/git/config`. `xdg-config` seems to work, just want to be sure.

**Comment by TingPing** [comment]
> --filesystem=xdg-config/git:ro

This is correct, did you have an actual problem?

**Comment by albfan** [comment]
No os just I didn't find documented and was unsure to use it.

Thanks!

**Comment by TingPing** [comment]
Its supposed to be documented... not sure I understand how that page is outdated: https://github.com/flatpak/flatpak-docs/blob/master/docs/sandbox-permissions-reference.rst#filesystem-permissions
