### ISSUE TITLE
Address system-helper by name, not by unique id

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#334]
If the system helper dies due to inactivity then the client will fail to talk to it again, because it keeps using the old unique id, rather than reusing the name causing re-activation.

**Comment by alexlarsson** [comment]
This was reported here: https://lists.freedesktop.org/archives/xdg-app/2016-September/000428.html

**Comment by matthiasclasen** [comment]
This was fixed in commit e4dbd107b3dc6915088d748ce72c405b61ccbbc0
