### ISSUE TITLE
flatpak (or bwrap?) breaks cgroups

### ISSUE THREAD

**Issue by Ozymandias42** [flatpak/flatpak#3340]
## Linux distribution and version
openSUSE Tumbleweed on Linux 5.3.12-1-default #1 SMP Thu Nov 21 07:21:43 UTC 2019 (a6f6081)
## Flatpak version
1.4.3
## Description of the problem
Flatpak breaks `systemd-run` cgroup-mechanism.
When doing `systemd-run --slice custom.slice --scope flatpak run com.app.flatpak` it generates a scope as per expected `systemd-run` behaviour but does not put them into the denoted slice as expected but instead leaves them under the `user-UID` slice.
## Steps to reproduce
create a .scope file in `/etc/systemd/system/custom.slice` with content like:
```
[Scope]
MemoryHigh=250M
MemoryMax=300M
```
run `systemd-run --slice custom.slice --scope flatpak run any.random.flatpak`
check against 
`systemd-cgtop` (Memory of the denoted slice is not allocated as expected by the flatpak-application) 
and 
`systemd-cgls` (search for process reveals existence of generated scope beneath user-UID but not the set slice.)
search for the started processes PID's in the created cgroups `tasks` file under `/sys/fs/cgroup/systemd/custom.slice/tasks` confirms this via absence of expected pids in there.

**Comment by Sporif** [comment]
It's because flatpak itself runs the app in a transient unit:

https://github.com/flatpak/flatpak/blob/9cd84747fb48abe9fe085a6c7f5a5f87efb4e98b/common/flatpak-run.c#L1306

You can try it yourself: `systemd-run --user --slice custom.slice  systemd-run --user <app>` will show the same issue, service or scope is irrelevant.

**Comment by Ozymandias42** [comment]
> It's because flatpak itself runs the app in a transient unit:
> 
> https://github.com/flatpak/flatpak/blob/9cd84747fb48abe9fe085a6c7f5a5f87efb4e98b/common/flatpak-run.c#L1306
> 
> You can try it yourself: `systemd-run --user --slice custom.slice systemd-run --user <app>` will show the same issue (service or scope is irrelevant).

thx. solved it by using cgroups v2 via `systemd.unified-cgroup-hierarchy=1` in the kernel-line. 
See related issue here: https://github.com/systemd/systemd/issues/14433

Seems like it is not a bug per-se but a problem with systemds unified cgroup hierarchy. The hybrid implementation seems to not do resource management using v2 hence the inability to do so from non-privileged users. Using v2 exclusively solves this.

Btw. this had nothing to do with transient units. it does not matter if a unit is transient or not. This is a matter of non-privileged units vs. privileged ones in cgroups v1, which you also highlighted with the `--user` flag in your example command.

Anyway, again thx for helping.

**Comment by Sporif** [comment]
Yes you're right in that the resource restrictions being ignored is caused by a lack of cgroups2, but the nested transient unit not working is a 'bug' with systemd. I think you ran into both issues, but like you reported in the systemd issue you can work around the nested transient unit issue by simply using `systemctl --user set-property` on the scope flatpak creates.

**Comment by akvadrako** [comment]
Is there a way to do this persistently, perhaps by specifying the scope / slice flatpak should use?

It seems like it always uses the "app" slice and a dynamic scope name.

**Comment by smcv** [comment]
If you want to set `systemd.resource-control(5)` parameters for each instance of a particular app, you can use systemd drop-ins to create a slice that will become the parent for the dynamic scope that Flatpak creates. See https://github.com/flatpak/flatpak/issues/4869#issuecomment-1116046159

**Comment by akvadrako** [comment]
Thanks @smcv, that works well.
