### ISSUE TITLE
flatpak permisson-set ignores FLATPAK_SYSTEM_DIR

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3341]
The newly introduced in 1.6 flatpak permission-set command seems to have hardcoded $HOME/.local/share/flatpak/db/flatpak 
Setting environment variable like FLATPAK_SYSTEM_DIR and FLATPAK_USER_DIR are ignored.
--user and --installation options are unkown to flatpak permission-set and thus this is broken for installations

**Comment by matthiasclasen** [comment]
All the permission-related commands talk to the PermissionStore D-Bus service, and don't access the filesystem at all.

Permissions are not specific to installations, so there is no need to have options to pick a particular installation.
