### ISSUE TITLE
dconf->keyfile settings runtime migration

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3347]
So flatpaks should use `~/.var/app/$APP/config/glib-2.0/settings/keyfile` for their own settings. 
I think this is great!

But i can not find  any application that make use of that (looking at org.gnome.Calendar)
```
[Application]
name=org.gnome.Calendar
runtime=org.gnome.Platform/x86_64/3.34
...
[Context]
...
filesystems=xdg-run/dconf;home;~/.config/dconf:ro;
...
[Environment]
DCONF_USER_CONFIG_DIR=.config/dconf
```
According to the documentation this has to be done while building the flatpak by adding `--metadata=X-DConf=migrate-path=/org/example/foo/` to finish-args.
Is there a way to do this after installing the application using overrides?

**Comment by matthiasclasen** [comment]
What you need to do to convince GSettings to use the keyfile backend is to stop plugging a sandbox hole for dconf. 

The migrate-path setting is only needed to instruct flatpak to do a one-time conversion of existing settings to the keyfile

**Comment by damianatorrpm** [comment]
flatpak --user override --nofilesystem=~/.config/dconf"
flatpak --user override --nofilesystem=xdg-run/dconf"
flatpak --user override --env=DCONF_USER_CONFIG_DIR=$HOME/var.app/$appid/config/glib-2.0/settings/"
flatpak --user override --env=GSETTINGS_BACKEND=keyfile

works great
