### ISSUE TITLE
Flatpak --subpath pulls are not fully atomic

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#335]
If you install a partial ref (i.e. with flatpak install --subpath=...) then we do multiple separate pulls of this ref (one per subpath). If anything breaks after the first one succeeds we'll still end up with a ref for the app in the local repo, and it looks like the pull succeeded.

We really should have a transaction around all these operations. However, ostree doesn't allow you to wrap a transaction around multiple pull calls atm.

**Comment by cgwalters** [comment]
Yeah, seems like it'd make sense for ostree to support that.

Though I don't understand the use case for `install --subpath`.

**Comment by alexlarsson** [comment]
@cgwalters Its to install org.foo.Bar.Locale with a subset of the locales.

**Comment by alexlarsson** [comment]
This is atomic now.
