### ISSUE TITLE
Some applications store configs in $HOME

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3351]
I build an application from .yml manifest. The application places a config file/dir in $HOME
How should this be mapped to .var/app/$appdirectory/ ?
```
1) Does the application need to be patched/configure parameters set?
2) Is it possible to retro-fit existing applications?
```

Similar to dconf->keyfile 
 - Thanks! `flatpak --user override --env=GSETTINGS_BACKEND=keyfile` works great
  - https://github.com/flathub/ca.desrt.dconf-editor/issues/12
  - https://gitlab.gnome.org/GNOME/gnome-boxes/issues/453

**Comment by TingPing** [comment]
>  The application places a config file/dir in $HOME
How should this be mapped to .var/app/$appdirectory/ ?

Patch it to respect the XDG standard. https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
