### ISSUE TITLE
Many application requires to implement enter into sandbox

### ISSUE THREAD

**Issue by nintyfan** [flatpak/flatpak#3352]
## Linux distribution and version
OpenSUSE Tumbleweed
## Flatpak version
Flatpak 1.4.3
## Description of the problem
Applications are trying to launch an new instance, when opening new document. For example:
1. There's new steam process (new flatpak sandbox), when running an game by lutris
2. Each time I opened an document in LibreOffice, new flatpak sandbox starts

**Comment by TingPing** [comment]
> Each time I opened an document in LibreOffice, new flatpak sandbox starts

This is just a LibreOffice bug, report it against that package.

> There's new steam process (new flatpak sandbox), when running an game by lutris

I'm not sure what the problem here is?

**Comment by nintyfan** [comment]
I'm not sure what the problem here is?

Imagine user don't set autologin. When Steam start twice, we have two tray icons.

**Comment by TingPing** [comment]
Understood. That is also a bug to report against the Lutris package.
