### ISSUE TITLE
error opening an html resource

### ISSUE THREAD

**Issue by ltiber** [flatpak/flatpak#3353]
## Linux distribution and version
 ubuntu 18.04
## Flatpak version
Flatpak 1.0.9
## Description of the problem
Hello,
I try to build a flatpak application.
Everything works fine till I try to display my helpfile with the default browser.
My app is written in C and based on GTK3.
I've first used this type of code     
 ```
char *cmd = g_strdup_printf("xdg-open %s",helpFilePath); //run the browser
 g_spawn_command_line_sync (cmd, &stdOut, &stdErr, &status, &err);
```
when I run my app with the  "flatpak-builder --run", I receive a dialog box to choose the wanted browser and my file displays.
When I install my app via the following command 
```
flatpak-builder --repo=repo-pwall --force-clean build-dir org.pwall.Pwall.json
flatpak --user remote-add --no-gpg-verify repo-pwall repo-pwall
flatpak --user install repo-pwall org.pwall.Pwall 

```
nothing happens when I try to display the help
I've also tried to use
`gtk_show_uri_on_window (GTK_WINDOW(pWindow), helpFilePath, GDK_CURRENT_TIME, &err); 
`
which is recommended in the help but I receive the following message
`GLib-GIO-CRITICAL **: g_dbus_connection_signal_subscribe: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
`
Thanks for your help

**Comment by mwleeds** [comment]
It might be helpful if you mention what `helpFilePath` is. Is it a `https://...` link? A `file://` link?

`gtk_show_uri_on_window()` should work in the Flatpak sandbox, whereas spawning `xdg-open` does not. Is it possible you have a bug that's leading to the assertion failure?

**Comment by ltiber** [comment]
in this case, it is `file://` link which fails. I have another function in my app which opens an `https://` link with `xdg-open` which works fine.

**Comment by mwleeds** [comment]
Fliesystem permissions in the `flatpak-builder --run` sandbox are not the same as the ones in the final build. What part of the filesystem is your HTML in? You probably need to add [a filesystem permission](http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) to access it. If it's packaged in the flatpak maybe you can use the `Instance.app-path` in `/.flatpak-info` (which exists in the sandbox) to build a path to it.

**Comment by ltiber** [comment]
The file is packaged in the flatpak.
I use /app/extra/export/share/help.html assuming that my file have been installed in this path.
I've used this build command in my json manifest to install the file at this location
```
"build-commands": [
		...
                "install -D res/pwall/help.html /app/extra/export/share/help.html",
                ...
            ] 

```
It seems to be the correct place when I use the flatpak-builder --run sandbox.
I can see the file at the right location in the build-shell.

**Comment by mwleeds** [comment]
While you're in that shell, try running `xdg-open` manually?

**Comment by ltiber** [comment]
`sh-4.3$ xdg-open /app/extra/export/share/help.html`
gives me the following error
`Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files`

**Comment by mwleeds** [comment]
You need to install xdg-desktop-portal and xdg-desktop-portal-gtk on the host.

**Comment by ltiber** [comment]
xdg-desktop-portal and xdg-desktop-portal-gtk are already on the host. 
To be clear, the shell I use comes from the build-shell. I get it with the following command 
`flatpak-builder build-dir org.pwall.Pwall.json  --force-clean --disable-cache  --build-shell=pwall`

**Comment by alexlarsson** [comment]
The build shell is slightly different (need to fix this really), can you try installing it and running with a regular flatpak run?

**Comment by ltiber** [comment]
I've made a workaround with calling a http page which works quite well.
Thanks for your help.
