### ISSUE TITLE
Can't update flatpak

### ISSUE THREAD

**Issue by popey** [flatpak/flatpak#3361]
Running Ubuntu Focal (20.04) today. Previously I was on 19.10.

Flatpak version 1.4.3

I installed one flatpak - GNOME Builder - a few months back, by following instructions in their [documentation](https://builder.readthedocs.io/en/latest/installation.html). Today I tried to update my system with `flatpak update` having not done it for a while, and got this error:

```
$ flatpak update
Looking for updates…
Unable to update app/org.gnome.Builder/x86_64/stable: Remote "org.gnome.Builder-origin" not found
Unable to update runtime/org.gnome.Builder.Locale/x86_64/stable: Remote "org.gnome.Builder-origin" not found
```

(in addition it reported some updates which could be performed)

```
        ID                                    Arch   Branch Remote  Download
 1.     org.gnome.Sdk                         x86_64 3.32   flathub < 686.1 MB
 2.     org.gnome.Sdk.Locale                  x86_64 3.32   flathub < 323.4 MB (partial)
 3.     org.freedesktop.Platform.html5-codecs x86_64 18.08  flathub   < 3.3 MB
 4.     org.freedesktop.Platform.VAAPI.Intel  x86_64 18.08  flathub   < 1.8 MB

Proceed with these changes to the Default system installation? [Y/n]: 
```

I have not proceeded, because I wanted to preserve this error state to file this issue.

Some additional debug data:

```
$ flatpak remote-list -d
Name          Title                 URL                                 Collection ID Filter Priority Options … … Homepage Icon
flathub       Flathub               https://dl.flathub.org/repo/        -             -      1        system  … … -        -
flathub       Flathub               https://dl.flathub.org/repo/        -             -      1        user    … … -        -
gnome-nightly GNOME Nightly Runtime https://sdk.gnome.org/nightly/repo/ -             -      1        user    … … -        -
```

```
$ flatpak info org.gnome.Builder

Builder - An IDE for GNOME

           ID: org.gnome.Builder
          Ref: app/org.gnome.Builder/x86_64/stable
         Arch: x86_64
       Branch: stable
      Version: 3.32.4
      License: GPL-3.0+ and GPL-2.0+ and LGPL-3.0+ and LGPL-2.0+ and MIT
       Origin: org.gnome.Builder-origin
 Installation: system
    Installed: 129.7 MB
      Runtime: org.gnome.Sdk/x86_64/3.32
          Sdk: org.gnome.Sdk/x86_64/3.32

Active commit: 62f1fecadde4bf83e65c17ece600385c45cc06c9249dc905f5313c2bd460990e
Latest commit: ref not present in origin
```

Why can't I update the software I installed a few months ago?

**Comment by refi64** [comment]
Which steps on that page did you follow exactly?

**Comment by popey** [comment]
Thanks for the quick reply.

It's been a while (timestamp on `/var/lib/flatpak/app/org.gnome.Builder` is August 1st last year) and I have `GNOME Builder` `3.32.4` from `flatpak-stable` according to the about box.

![image](https://user-images.githubusercontent.com/1841272/72170268-7bb29b80-33c8-11ea-8fa4-f9ec65e8ffa4.png)

But I am pretty sure I just copy pasted the command line options directly into a terminal for installing the stable release.

**Comment by barthalion** [comment]
This is because sdk.gnome.org was deprecated. You should first uninstall Builder and then install again as described on [GNOME Wiki](https://wiki.gnome.org/Apps/Builder/Downloads).

**Comment by popey** [comment]
Forgive my ignorance. How do I remove this flatpak?I read the [documentation](https://docs.flatpak.org/en/latest/using-flatpak.html) and it doesn't work.

```
alan@KinkPad-K450:~$ flatpak uninstall Builder
Found installed ref ‘app/org.gnome.Builder/x86_64/stable’ (system). Is this correct? [Y/n]: y
error: Remote "org.gnome.Builder-origin" not found
alan@KinkPad-K450:~$ flatpak uninstall org.gnome.Builder
error: Remote "org.gnome.Builder-origin" not found
```

**Comment by mwleeds** [comment]
> Forgive my ignorance. How do I remove this flatpak?I read the [documentation](https://docs.flatpak.org/en/latest/using-flatpak.html) and it doesn't work.
> 
> ```
> alan@KinkPad-K450:~$ flatpak uninstall Builder
> Found installed ref ‘app/org.gnome.Builder/x86_64/stable’ (system). Is this correct? [Y/n]: y
> error: Remote "org.gnome.Builder-origin" not found
> alan@KinkPad-K450:~$ flatpak uninstall org.gnome.Builder
> error: Remote "org.gnome.Builder-origin" not found
> ```

For posterity, the answer here is to either use Flatpak >= 1.5.0, or create a remote with the name given, as in #3557.
