### ISSUE TITLE
Flatpak's ld cache generation with ldconfig fails

### ISSUE THREAD

**Issue by Avamander** [flatpak/flatpak#3365]
## Linux distribution and version
Ubuntu 19.10

## Flatpak version
1.4.3

## Description of the problem
Flatpak's ld cache generation fails non-root (and flatpak doesn't launch as root):
```
~ flatpak run --verbose com.valvesoftware.Steam
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/user/.var/app/com.valvesoftware.Steam/.ld.so/21621dfc1839ba74851eb82a71384c92a075123fb320e2a884c73d88476bb3d5
F: Running: 'bwrap --args 21 ldconfig -X -C /run/ld-so-cache-dir/21621dfc1839ba74851eb82a71384c92a075123fb320e2a884c73d88476bb3d5'
ldconfig: Can't create temporary cache file /run/ld-so-cache-dir/21621dfc1839ba74851eb82a71384c92a075123fb320e2a884c73d88476bb3d5~: Permission denied
error: ldconfig failed, exit status 256
```

## Steps to reproduce
Install the Steam flatpak

**Comment by Avamander** [comment]
I also tried removing and reinstalling the flatpak, still throws the same flatpak error.

**Comment by Avamander** [comment]
Installing the flatpak with `--user` fixed the issue, but this problem still stands, if special flags have to be passed then why isn't it the default?

**Comment by alexlarsson** [comment]
Its really weird that it works when you install with --user. That should not affect the generation of the ld cache, that is always per user. This seems like its failing to create a backup for the old cache as: `/run/ld-so-cache-dir/21621dfc1839ba74851eb82a71384c92a075123fb320e2a884c73d88476bb3d5~` where `/run/ld-so-cache-dir` will be a bind mount of `~/.var/app/com.valvesoftware.Steam/.ld.so/`.

Is the permissions of the later strange in some way?

**Comment by Avamander** [comment]
> Is the permissions of the later strange in some way?

I haven't manually modified it in any way. I don't see a way for permissions to stop the root user?

**Comment by refi64** [comment]
I think this is just #3029.

**Comment by Avamander** [comment]
The error message is different though.

**Comment by akallabeth** [comment]
Got the same issue here on a thinkpad e485 and ubuntu 19.10 (also with 20.04)
used to work with 19.04.
Interesting thing is that it only affects users with enabled ´fscrypt´ home directories.

**Comment by akallabeth** [comment]
Oh, and for reference I have 2 other machines working flawlessly with the same setup (fscrypt home and ubuntu 19.10 or 20.04)

**Comment by LaurentBonnaud** [comment]
Hi,

I have a similar problem with MS Teams:
```
$ flatpak run com.microsoft.Teams
Overriding TZ to Europe/Paris
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/teams/teams --type=zygote --electron-shared-settings=eyJjci5jb21wYW55IjoiRWxlY3Ryb24iLCJjci5kdW1wcyI6IiIsImNyLmVuYWJsZWQiOmZhbHNlLCJjci5wcm9kdWN0IjoiRWxlY3Ryb24iLCJjci5zZXNzaW9uIjoiIiwiY3IudXJsIjoiIiwiY3IudmVyc2lvbiI6IiJ9
ldconfig: Can't create temporary cache file /run/ld-so-cache-dir/a485e4ccbd64628cfc712adeaa05ca7b691609e80c48c199c62b03af4b0ffd55.lTin0s~: Required key not available
error: ldconfig failed, exit status 256
```
In my case the error message "Required key not available" is more explicit about fscrypt than "Permission denied" from the original report.

**Comment by LaurentBonnaud** [comment]
Strangely, the ld.so file is there and permissions seem correct:
```
.var/app/com.microsoft.Teams/.ld.so/:
total 48
drwxr-xr-x 2 bonnaudl bonnaudl  4096 Feb  2 12:50 ./
drwxr-xr-x 6 bonnaudl bonnaudl  4096 Feb  2 12:50 ../
-rw-r--r-- 1 bonnaudl bonnaudl 42206 Feb  2 12:50 a485e4ccbd64628cfc712adeaa05ca7b691609e80c48c199c62b03af4b0ffd55
lrwxrwxrwx 1 bonnaudl bonnaudl    66 Feb  2 12:50 active -> a485e4ccbd64628cfc712adeaa05ca7b691609e80c48c199c62b03af4b0ffd55
```

**Comment by crashbit666** [comment]
Same problem here:
I'm usgin Arch Linux with sway.

❯ com.visualstudio.code
ldconfig: no s’ha pogut crear el fitxer temporal de memòria cau «/run/ld-so-cache-dir/c68702b5a3e492a7b56f2d86d5b25f716bdb7877d0f2c8d07ad7225b38d5c873.uBMHdV~»: S’ha denegat el permís
error: ldconfig failed, exit status 256

❯ uname -a
Linux GT62VR-6RE 6.6.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000 x86_64 GNU/Linux

❯ ls -ld /run
drwxr-xr-x root root 580 B Wed Dec 20 14:13:32 2023  /run

 nvme0n1                                                                                   
├─nvme0n1p1 vfat   FAT32              2F31-A4C5                             230,2M    55% /boot
└─nvme0n1p2 btrfs                     db62f12e-aa86-4f20-ae5c-977e5e5b7894  627,7G    34% /var/log
                                                                                          /var/cache/pacman/pkg
                                                                                          /home
                                                                                          /.snapshots
                                                                                          /                           

❯ flatpak info com.visualstudio.code

Visual Studio Code - Code editing. Redefined.

          ID: com.visualstudio.code
         Ref: app/com.visualstudio.code/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.84.2-1699528352
     License: LicenseRef-proprietary=https://code.visualstudio.com/license
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 12,9 MB
     Runtime: org.freedesktop.Sdk/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 1ca9a657ba6d4687d52e262616c6a5a2352084266f81f11fb2c352ae2548930c
      Parent: 09d080cae687eff56acd21966c987ffee98ae8359ab41f3a9e205d32e953e91e
     Subject: Update 2 modules (c2704e2c)
        Date: 2023-12-02 10:23:55 +0000

❯ flatpak info --show-permissions com.visualstudio.code
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=all;
features=devel;
filesystems=xdg-config/gtk-3.0:ro;home;xdg-config/kdeglobals:ro;host;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
org.freedesktop.Notifications=talk
com.canonical.AppMenu.Registrar=talk
com.canonical.AppMenu.Registrar.*=talk
org.freedesktop.secrets=talk

[System Bus Policy]
org.freedesktop.login1=talk

[Environment]
LD_LIBRARY_PATH=/app/lib
NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
ZYPAK_SPAWN_LATEST_ON_REEXEC=0
