### ISSUE TITLE
Shortcut not found Ubuntu 19 Software menu

### ISSUE THREAD

**Issue by RobertChilewskiGit** [flatpak/flatpak#3367]
Ubuntu 19

Flatpak 1.6 (i think )

![Screenshot from 2020-01-19 20-18-49](https://user-images.githubusercontent.com/59810888/72692368-7a385000-3af9-11ea-86f6-2a99822306d7.png)

Shortcut icon not showing in Ubuntu 19 Menu

https://www.gimp.org/downloads/

**Comment by TingPing** [comment]
Probably just reboot once and menu entries will show up.

**Comment by RobertChilewskiGit** [comment]
Yup That did it Thank you Sir I noticed after a reboot! <3
