### ISSUE TITLE
XDG_SESSION_TYPE is not available in a flatpak

### ISSUE THREAD

**Issue by amikha1lov** [flatpak/flatpak#3370]
Fedora 31 - Flatpak 1.4.3

Hello. In my program, you need to check which session the desktop is running in. I'm use Python and `os.environ ['XDG_SESSION_TYPE']`. In  Wayland session he returns to me-raise `KeyError(key) from None KeyError: 'XDG_SESSION_TYPE' Application excited`

And if you just call `os.environ`, then `XDG_SESSION_TYPE` is simply not there.
In this case, the correct result is returned in the terminal, but not in flatpak. I got this error on two computers

Is it available from flatpak ?

**Comment by TingPing** [comment]
It gets passed through fine here, is it set on the host?

**Comment by amikha1lov** [comment]
"finish-args" : [
"--share=network",
"--share=ipc",
"--socket=fallback-x11",
"--socket=wayland",
"--socket=pulseaudio",
"--device=dri",
"--talk-name=org.gnome.Shell.Screencast",
"--filesystem=xdg-videos
maybe this data can somehow help?
just my friend has this command returns the same result.
here is his manifest file
https://github.com/ivan-tretyak/Youtube-dl-GTK/blob/master/com.github.ivantretyak.Youtube-dlGTK.json
it turns out on three PCs it does not work

**Comment by amikha1lov** [comment]
in the terminal I get the right value without any problems

**Comment by TingPing** [comment]
Environment variables are not a permission thing, Flatpak just lets most of them through.

**Comment by amikha1lov** [comment]
> Environment variables are not a permission thing, Flatpak just lets most of them through.

is there any way to fix this ?

**Comment by TingPing** [comment]
What desktop do you use?

I don't think `flatpak` is relevant here but for whatever reason the launch environment of `flatpak` doesn't have it set.

**Comment by amikha1lov** [comment]
> What desktop do you use?
> 
> I don't think `flatpak` is relevant here but for whatever reason the launch environment of `flatpak` doesn't have it set

Gnome 3.34 (Fedora 31)

**Comment by alexlarsson** [comment]
Whenever you launch a (flatpak) application the application will inherit the environment from its parent, which typically includes the XDG_SESSION_TYPE. Flatpak does nothing special to this environment variable (although it *does* on some other special ones).

**Comment by alexlarsson** [comment]
You can see this like:
```
$ flatpak run --command=python3 org.gnome.gedit -c "import os; print(os.environ['XDG_SESSION_TYPE'])"
x11
```
Its possible that somewhere you're launching flatpak apps from *doesn't* have it set in the launching app, but that is not an issue with flatpak, i.e. would affect non-flatpak apps too.
