### ISSUE TITLE
wrong dnd behavior

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3371]
## Linux distribution and version
Fedora SB
## Flatpak version
Latest
## Description of the problem
Drag and Drop does not work if dragged from external media.

## Steps to reproduce
Get Rhythmbox.
Drag file from external media using nautilus into rhythmbox. No error. Nothing.
If copied into home it works from there it works.
It also works with VLC, probably other permissions.
I did not open this against rhythmbox as double clicking the file works!
And I think this is some portal stuff.

**Comment by TingPing** [comment]
The DnD portal is currently only supported by GTK4.

**Comment by TingPing** [comment]
In the mean time you can: `flatpak override --user --filesystem=host org.gnome.Rhythmbox3` (host can be replaced with a specific path)
