### ISSUE TITLE
Applications do not start at all if $HOME is a subdirectory of /usr

### ISSUE THREAD

**Issue by sboukortt** [flatpak/flatpak#3379]
## Flatpak version
1.4.2

## Description of the problem
One of the machines that I use has the home directory under `/usr`. On that machine, trying to run any flatpak application fails with a message along the lines of:

    bwrap: Can't mkdir parents for /usr/.../home/$USER/.var/app/org.darktable.Darktable/config/user-dirs.dirs: Read-only file system

I am only speculating that this is due to `$HOME` being under `/usr` but it seems like a plausible explanation to me, given the blacklisting of `/usr` [mentioned in the documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access).

In any case, contrary to what the message indicates, it did manage to create the parent directories in question.

**Comment by sboukortt** [comment]
I just tried with `HOME` overriden to a subdirectory of `/tmp` and it worked, so being under `/usr` does seem to be the problem.

**Comment by alexlarsson** [comment]
Yes, this is never going to work, because flatpak assumes that /usr is under control of the runtime. We can't in general modify what exists there, and we can't even mount the home directory there because the required mountpoint will not exist in the runtime.

**Comment by beck** [comment]
I find myself with this issue. Every `flatpak run ...` fails.

Example, running `flatpak run org.gnome.Calendar` errors with:
```
bwrap: Can't mkdir parents for /usr/local/home/doug/.var/app/org.gnome.Calendar/config/user-dirs.dirs: Read-only file system
```

Reading through the permissions docs and setting all manner of `flatpak override`, system-wide access to `host` - same error.

Any suggestions? :confused: :shrug:
