### ISSUE TITLE
Slow download speed from flathub

### ISSUE THREAD

**Issue by nazar2sfive** [flatpak/flatpak#3380]
![image](https://user-images.githubusercontent.com/12841320/73116765-454a5400-3f64-11ea-8666-4770f0c4d171.png)

**Comment by barthalion** [comment]
Depends where you're downloading from; if CDN server close to your location doesn't have our data cached, it will be slow at first.

**Comment by clopez** [comment]
This may be related to #3412 
`flatpak install` seems unable to use static deltas and that causes it to fetch the repository objects one by one, which causes slow speeds in general (and specially on repositories that contain many small files).
To verify if its the same issue you can retry exporting the environment variable ```OSTREE_DEBUG_HTTP=1``` and seeing if `flatpak install` its doing many (in the order of thousands) `GET` petitions when downloading the data.

**Comment by mwleeds** [comment]
Right, this should be less of an issue with Flatpak 1.6.2

**Comment by arun54321** [comment]
![image](https://user-images.githubusercontent.com/42943340/76546799-1bb4a000-64b2-11ea-97b4-25d59381a93f.png)
Worst download speeds.
Distro: ARCH
Flatpak version: 1.6.2

**Comment by mwleeds** [comment]
@arun54321 looks like you're downloading from gnome-nightly, not flathub. So likely that's because that one doesn't use a CDN (I'm guessing).

**Comment by clopez** [comment]
It might be also caused because that repository has not enabled static-deltas. Try re-running it with the env var ```OSTREE_DEBUG_HTTP=1``` and count the number of ```GET``` petitions.
Something like
```
OSTREE_DEBUG_HTTP=1 flatpak install [.....]  2>&1 | grep GET | wc -l
```
If its in the order of hundreds then static deltas are working, but  if its in the order of thousands then there is a problem with that. Likely the one uploading the repo has not enabled static-deltas in their build. Ask them to do that.

Check https://docs.flatpak.org/en/latest/hosting-a-repository.html for how to enable them

Maybe the option to enable static-deltas should default to enabled?

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/80226587-475ba600-866c-11ea-9836-2ed669cf3903.png)

**Comment by itsnotsaved** [comment]
https://github.com/flatpak/flatpak/issues/4874

**Comment by rotty** [comment]
Same for me (from Austria, 30MBit connection).
![slow-flatpak](https://github.com/flatpak/flatpak/assets/3920/97b447be-ec0f-45bc-88cc-9a118e19402f)

**Comment by impulse200** [comment]
This is still an issue. On 500mbs connection I got this
![image](https://github.com/flatpak/flatpak/assets/16685266/a700e86d-97b1-49d2-ac60-bd600511d9ab)

**Comment by headkittens** [comment]
Yeah, I'm getting sub-30kb/s speeds on new installs and updates, sometimes it fails, sometimes it succeeds, but it's frustrating, on a relatively fresh install of Fedora KDE Plasma Desktop.
![image](https://github.com/flatpak/flatpak/assets/109193516/36b87c2d-5045-4eee-a1d7-b1dda1e116fe)

**Comment by headkittens** [comment]
Yeah, I'm getting sub-30kb/s speeds on new installs and updates, sometimes it fails, sometimes it succeeds, but it's frustrating, on a relatively fresh install of Fedora KDE Plasma Desktop.
![image](https://github.com/flatpak/flatpak/assets/109193516/c994f056-4103-4512-83d3-004e00aa6e90)

**Comment by rickmacgillis** [comment]
Same issue here.
![image](https://github.com/flatpak/flatpak/assets/8941225/06811868-df35-4a11-8e65-8994ce1f8ca7)

**Comment by eternal-sorrow** [comment]
![photo_2023-11-04_06-10-52](https://github.com/flatpak/flatpak/assets/4847726/503a8f62-b1a1-43f1-98e8-31a70fe561d2)

**Comment by maxkolenko** [comment]
I have the same issue

**Comment by dlabaja** [comment]
same here, downloading nvidia drivers from flathub
![obrazek](https://github.com/flatpak/flatpak/assets/72014646/5fcb67ab-e7e5-4fa9-9d47-3d1964dee546)

**Comment by GBSpada** [comment]
Same here
![Screenshot_20231108_220217](https://github.com/flatpak/flatpak/assets/123422041/7f084689-7960-4ee7-b25c-5699cfd1aa4e)
