### ISSUE TITLE
Click on a Flatpak to install and Kate opens

### ISSUE THREAD

**Issue by GraveDigger1** [flatpak/flatpak#3381]
I'm running Manjaro KDE 18.1.5 RC1 Testing Build and have setup the system to use Flatpacks, but every time I click on a downloaded Flatpak and click to install it Kate opens. I'm not seeing any error messages, so I have no idea what happened.

**Comment by TingPing** [comment]
You downloaded a `.flatpakref` file. I would guess you don't have an application registered to handle that file type (Plasma Discover?).

**Comment by GraveDigger1** [comment]
i have installed flatpack support in manjaro. are you saying i also need discover as well?

**Comment by barthalion** [comment]
Sorry but it's hard to say what "flatpak support" means in Manjaro. You need an application to handle `.flatpakref` files by default and KDE Discover is one of them. If it's not installed, install it and it should work fine.

**Comment by GraveDigger1** [comment]
ok just installed discover, tested with a file i have for flash and it open in discover. thanks much appreciated.
