### ISSUE TITLE
[Suggestion] Override Context filesystems alias???

### ISSUE THREAD

**Issue by kbjji** [flatpak/flatpak#3384]
## Linux distribution and version
Fedora Silverblue rawhide

## Flatpak version
flatpak-1.5.2-1.fc32.x86_64

## Description of the problem
Korean:
최근에 org.qutebrowser.qutebrowser app 을 사용 중입니다. 매우 만족해서 주 웹 브라우저로 사용 중입니다.
DRM 비디오를 시청하기 위해 widevine 를 사용해야 하는데 /opt/google/chrome 와 같은 특정 경로를 참조하게 되어 있습니다. 그래서 아래와 같이 설정하여 사용 중입니다.
English:
I am using org.qutebrowser.qutebrowser app recently. It is very cool so I use it as my main web browser. To watching DRM video (widevine), it supposed to refer to a specific path like /opt/google/chrome. So I am using it by setting as below.
- HOST: /opt/google/chrome/libwidevinecdm.so
\# ~/.local/share/flatpak/overrides/org.qutebrowser.qutebrowser
```
[Context]
filesystems=/opt/google/chrome;
```
Korean:
이경우 Host 에서는 실제로 사용하지 않을 경로의 디렉토리를 생성해야 합니다.
관리면에서 불편하기 때문에 몇몇 경우 아래와 같은 형태로 설정했으면 어떨까 합니다.
English:
In this case, Host needs to create a directory with a path that is not actually used.
Because it is inconvenient for management, how about setting form as follows as necessary?
- HOST: /path/to/want/libwidevinecdm.so
```
[Context]
filesystems=/path/to/want:/opt/google/chrome;
```

I used a translator because my English skills were poor. Sorry.

**Comment by alexlarsson** [comment]
For security reasons flatpak doesn't allow apps to remap paths in ways that are under the apps control, as this can be used to confuse the host in security sensitive cases like portals.
