### ISSUE TITLE
flatpak --user returns error while the same command using --system does not return error

### ISSUE THREAD

**Issue by dwrobel** [flatpak/flatpak#3385]
## Linux distribution and version
`fedora 31`
## Flatpak version
`flatpak-1.4.3-3.fc31.x86_64`
## Description of the problem
Using `flatpak` with `--user` return error while the same command without `--user` or using `--system` option does not report error.

## Steps to reproduce
```
$ flatpak install --user org.freedesktop.Platform org.freedesktop.Sdk
Looking for matches…
error: No remote refs found similar to ‘org.freedesktop.Platform’
```

The same using `--system` option:

```
$ flatpak install --system org.freedesktop.Platform org.freedesktop.Sdk
Looking for matches…
Found similar ref(s) for ‘org.freedesktop.Platform’ in remote ‘flathub’ (system).
Use this remote? [Y/n]:
```

**Comment by barthalion** [comment]
From flatpak's point of view, `--user` and `--system` are completely separate installations, meaning that you need to add remotes to both.
