### ISSUE TITLE
Applications inside flatpak don't work internet

### ISSUE THREAD

**Issue by MaChInEgUn3** [flatpak/flatpak#3388]
I use Arch Linux
And at some point the applications stopped working with the internet
Applications like Skype and Spotify
I've tried to reinstall, but without effect, anyone could help me?

image
![image](https://user-images.githubusercontent.com/28672726/73211557-411c6300-412b-11ea-906c-609ffb57b3af.png)

image
![image](https://user-images.githubusercontent.com/28672726/73211571-45e11700-412b-11ea-9b1d-b489631cf0b3.png)

**Comment by refi64** [comment]
Known issue from the Arch p11-kit update, downgrade that package for now.

**Comment by pizzadude** [comment]
Also happens in fedora after this update https://bodhi.fedoraproject.org/updates/FEDORA-2020-f7bb54009e

**Comment by smcv** [comment]
I've opened https://github.com/p11-glue/p11-kit/issues/275 to ask the maintainers of p11-kit whether flatpak is doing something that is expected to work (in which case this is a p11-kit bug), or whether flatpak is doing something they consider to be unsupportable (in which case this is a flatpak bug, and the flatpak feature that shares the host p11-kit trust store with the container, added by #1757, would probably have to be removed), or something else.

Workaround (for users): keep p11-kit at version 0.23.18 or older on the host system.

Workaround (for runtime maintainers): upgrade all runtimes to p11-kit 0.23.19 or later. (This appears to be already in progress for org.freedesktop.Platform//18.08 and //19.08, and for derived runtimes like GNOME.)

**Comment by MaChInEgUn3** [comment]
Thanks guys, I downgraded the "p11-kit" and it went back to work

Is there a place I can keep track of when I could upgrade this package again?

**Comment by phw** [comment]
They released p11-kit 0.23.20 reverting the problematic RPC change, see https://github.com/p11-glue/p11-kit/releases/tag/0.23.20

Currently in testing repo for Arch (https://www.archlinux.org/packages/testing/x86_64/p11-kit/). I installed it and it indeed resolves the issues with flatpak apps.

**Comment by alexlarsson** [comment]
Closing this then

**Comment by kryptt** [comment]
Upgrading to p11-kit 0.23.20 also fixed my issue in gentoo!
