### ISSUE TITLE
Slow downloading speeds

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#339]
For example:

[alex@me ~]$ flatpak install gnome org.gnome.Sdk 3.22
Receiving objects: 21% (7273/33066) 46.2 kB/s 10.6 MB

**Comment by alex285** [comment]
Actually this might a thing with GNOME Server. I'll try KDE.

**Comment by alex285** [comment]
I didnt find the KDE flatpak to try, but I wget some files from sdk.gnome.org and speed is better. I get around 300 kB/s. My max is around 1000 kB/s. 

With Flatpak it stays around 50 kB/s

**Comment by alexlarsson** [comment]
I've seen this too, but only sometimes.  Now I'm getting much more that that for instance. 
I wonder if its related to https://github.com/flatpak/flatpak.github.io/pull/101

**Comment by Alexander-Wilms** [comment]
I'm having the same issue. speedtest.net shows 10 Mb/s download speed, but flatpak install has a download speed of 20 - 100 kB/s and often stops with the error "connection refused".

**Comment by hualet** [comment]
I'm having the same issue, too. 
Anyone can guide me that how can I provide a mirror for that slow server? It seems a bit off topic through. :)

**Comment by ICHx** [comment]
maybe the devs should implement libtorrent imo, also off topic

torrenting can auto distribute the traffic just like a cdn.

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/80226725-740fbd80-866c-11ea-9dba-6d1c3701692c.png)

**Comment by itsnotsaved** [comment]
https://github.com/flatpak/flatpak/issues/4874
