### ISSUE TITLE
Add support for ALSA-only audio

### ISSUE THREAD

**Issue by foresto** [flatpak/flatpak#3390]
##  Description of the problem

Audio does not currently work on ALSA-only systems, because /dev/snd is not exposed to the container. This can be worked around with --device=all, but that exposes far more to the container than should be required for audio.

A --device=snd option would solve the problem. Implemented in PR #3389.

**Comment by hfiguiere** [comment]
What's wrong with using `--socket=pulsaudio`. It exposes the `/dev/snd` sub directory.

**Comment by Mikenux** [comment]
@hfiguiere: Nothing, because this was added: https://github.com/flatpak/flatpak/pull/3663. I think this can be closed, especially since there is no response since February...
