### ISSUE TITLE
Messages about end of life runtimes are unclear

### ISSUE THREAD

**Issue by dln949** [flatpak/flatpak#3391]
Ubuntu 18.04
Flatpak 1.6.1

Today when updating some flatpak applications, I got this strange message:  

Info: org.gnome.Platform is end-of-life, with reason: GNOME 3.30 Runtime has been declared as End of life, please upgrade to a newer version of the Platform.

I don't know what this message is attempting to communicate to me, it is one of those messages that leaves a person wondering, "So....  How do I do what you want me to do?"  

1)  I got this message while running the command  flatpak update  So.... Why didn't this "runtime" get updated?  Something must be wrong Flatpak?  

2)  I don't know what the "newer version of the Platform" is.  How does a person find that?  (If it knows there's a newer version, why doesn't it just tell me what that version is?)  

3)  I had the probably foolish idea, Well, maybe I should just uninstall this "runtime".  So I ran this command,   flatpak uninstall org.gnome.Platform     But, I got this output:  

Similar installed refs found for ‘org.gnome.Platform’:

   1) runtime/org.gnome.Platform/x86_64/3.30 (system)
   2) runtime/org.gnome.Platform/x86_64/3.34 (system)
   3) runtime/org.gnome.Platform/x86_64/3.32 (system)
   4) All of the above

Which do you want to use (0 to abort)? [0-4]: 

(I selected "0" to abort.)  

(I don't know what a "refs" is.)  

So, the way I interpret that, I have 3 (!) versions of the runtime installed.  I had no idea, I never asked for that to happen, how can that happen?  Something must be wrong with Flatpak that it would do that.  Also - Since I already have what appears to be version 3.34 of the runtime installed, there is obviously something wrong with Flatpak that it is asking me to upgrade the 3.30 version of the runtime.  

Can someone please tell me what the problems are with Flatpak that it is giving these odd messages?  And how I can fix those problems?  

Thank you.

**Comment by TingPing** [comment]
Well the situation for you as a user is that you probably ignore them and do nothing.

Flatpak is doing a poor job at communicating here. Runtimes and applications may not be supported for ever and to signal that they are marked end of life. We don't want users to install end of life software expecting support and we want users to know when their software stops getting support.

Runtimes are a bit tricky though because the user largely doesn't care about those, they care about the applications. So perhaps Flatpak should say which applications depend on the outdated runtime. Eitherway this are relatively technical ideas.

**Comment by dln949** [comment]
Thank you very much!  

If I understand you correctly, I am not seeing this message because there is something wrong with flatpak.  Instead, it is telling me that there are flatpak applications that are relying on a runtime that is soon to stop being supported.  Now I understand.  

You are right, the message is very misleading, I thought that I needed to go about updating a runtime.  

How does a person determine which flatpak applications are dependent on the runtime that is a problem?  It is very nice that they tell me that a runtime is going away, but I hope there is a tool that enables me to know which flatpak applications are impacted.

**Comment by TingPing** [comment]
`flatpak list --app-runtime=org.gnome.Platform//3.30` If none are listed you can just remove the runtime.

**Comment by dln949** [comment]
Thank you!!!!

**Comment by Mikaela** [comment]
Could the messages tell me which flatpaks depend on the EOL runtimes without having to find out that command?

**Comment by TingPing** [comment]
Not as-is. The message is a static string set by the runtime. However `flatpak` could just always generate its own warnings for eol'd runtimes.

**Comment by Mikaela** [comment]
Is there an issue for that or should I open one?
