### ISSUE TITLE
[Suggestion] Environment variable to override Configuration file location

### ISSUE THREAD

**Issue by sjkosinski** [flatpak/flatpak#3395]
Hello,

Not an issue but I didn't know where else I could post this suggestion.

It could be useful to be able to specify a/several custom location(s) for the conf file used to define the installation location.

I'm actually installing the apps on a central location, a NFS mount, so that I do not have to install them on each one of the 40+ workstations of our company. I do so by using a conf file stored in /etc/flatpak/installation.d

That works great but in order for the users to be able to launch the apps the conf file has to be available on their workstation and I'd rather specify the location of this configuration file using an env variable than having to propagate it on each one of the stations each time I amend it.

Just an idea....

**Comment by alexlarsson** [comment]
There is a FLATPAK_CONFIG_DIR env var you can use.
