### ISSUE TITLE
[Question] Requesting clarification on XWayland sandbox permissions

### ISSUE THREAD

**Issue by corecontingency** [flatpak/flatpak#3396]
Currently there are three sandbox portals for display server protocols:

```
--socket=x11
--socket=wayland
--socket=fallback-x11
```
Which of these portals gives programs access to using XWayland?

I would assume `--socket=wayland` would and the others wouldn't, as XWayland is an X server built into the Wayland protocol. The [documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html) wasn't exactly clear on this, so I wanted to ask.

**Comment by TingPing** [comment]
With that *specific* combination of permissions the application does not have any permission to use XWayland.

- `--socket=x11` Access to X
- `--socket=wayland` Access to Wayland
- `--socket=fallback-x11` Access to X **if** not on Wayland, overrides `--socket=x11` permission.

**Comment by corecontingency** [comment]
Sorry, still a little confused. Does just `--socket=wayland` include permission for XWayland?

For example, let's say there is a program that only runs with X11 or XWayland, i.e. it is not natively Wayland compatible. I am running a wayland desktop session, i.e. GNOME Wayland. If I only gave the program `--socket=wayland` permissions, would it be able to run using XWayland?

Thanks, I appreciate the help and quick response.

**Comment by TingPing** [comment]
> Sorry, still a little confused. Does just `--socket=wayland` include permission for XWayland?

No it does not. `--socket=x11` is what provides permission to use XWayland.

**Comment by corecontingency** [comment]
Ah, makes sense now. So passing both `--socket=wayland` and `--socket=fallback-x11` would prevent a program from using XWayland on a wayland desktop session.

Thanks!
