### ISSUE TITLE
Unable to use ibus in qt apps

### ISSUE THREAD

**Issue by ymshenyu** [flatpak/flatpak#3398]
## Linux distribution and version
Ubuntu 18.04
## Flatpak version
1.6.1
## Description of the problem
Unable to use ibus in qt apps since KDE runtimes update(qt 5.13.2 to 5.14.1) yesterday.
## Steps to reproduce
use ibus in a qt app like telegram.

**Comment by tumut** [comment]
@ymshenyu did you manage to fix the issue? I'm having the same problem.
