### ISSUE TITLE
Support for Debian Buster and older

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [flatpak/flatpak#3399]
## Linux distribution and version
Debian Buster or older
## Flatpak version
N/A
## Description of the problem
Flatpak in Debian doesn't install anything because is too old
## Solution
Provide newer versions as .deb files, as is done with Ubuntu 16.04

**Comment by alexlarsson** [comment]
Buster seems to have 1.2.5: 
  https://packages.debian.org/buster/flatpak

We don't currently do (or plan to) backports to debian, all debian flatpak packaging happens upstream, so you'll have to bring this up with the debian maintainers.
