### ISSUE TITLE
API to list refs which need an update due to locale change

### ISSUE THREAD

**Issue by wjt** [flatpak/flatpak#3402]
## Linux distribution and version

Endless OS 3.8.0 (development branch)

## Flatpak version

Flatpak 1.5.0 (yes, I know)

## Description of the problem

`flatpak_installation_list_installed_refs_for_update()` only lists refs where the local commit is older than the remote commit. It does not (as is document, and by design as discussed on #360) list refs where the local commit is not deployed yet. It also does not list Locale extensions that need an update because the set of needed locales has increased.

If the current locale is not available, apps fall back to the `C` locale. This leads to problems with (for example) non-ASCII filenames, not just missing translations. Having switched my computer to `fr_FR.UTF-8`, I tried to save a file as `дау.odt` in LibreOffice. According to LibreOffice, its name is `Ð´Ð°Ñƒ.odt` (which is the result of encoding `дау` as UTF-8 and then reading it back as ISO-8859-1) and its name in the real filesystem is `??????.odt`. (See #3061 for a related report.)

GNOME Software currently relies on `flatpak_installation_list_installed_refs_for_update()` to work out what needs to be upgraded. As a result, it does not indicate that the Locale extensions need to be updated to pick up the new locale (or that there are updates which are pulled but not deployed).

Digging through the code, I see that `flatpak update` doesn't use that function. Instead it add all (relevant) installed refs for update to a transaction, then run it, and list what needs to be done in `::ready`.

I guess that in order to list available updates, GNOME Software could do the same thing, gather the list in `::ready`, then return `FALSE` to cancel the transaction. This does seem a little obscure. At the very least, I think `flatpak_installation_list_installed_refs_for_update()` should document more vigorously that it's not actually the function you want to call to answer the question "what needs to be updated?"; and ideally one would have a `flatpak_installation_list_what_flatpak_update_at_the_cli_would_do()` function to avoid these situations where the CLI and UIs build with libflatpak show different things.

**Comment by alexlarsson** [comment]
Since e..g https://github.com/flatpak/flatpak/commit/61f9d19eaeea4e92eeac930a9a14fc367053064c flatpak_installation_list_installed_refs_for_update is a lot smarter. I'm not sure it does locale changes though.

**Comment by mwleeds** [comment]
> Since e..g [61f9d19](https://github.com/flatpak/flatpak/commit/61f9d19eaeea4e92eeac930a9a14fc367053064c) flatpak_installation_list_installed_refs_for_update is a lot smarter. I'm not sure it does locale changes though.

I believe it does not but it will after #3537

**Comment by wjt** [comment]
#3537 landed and was released in 1.7.3.
