### ISSUE TITLE
GTK3 apps fonts unhinted on wayland

### ISSUE THREAD

**Issue by eternal-sorrow** [flatpak/flatpak#3410]
## Linux distribution and version
Gentoo
## Flatpak version
1.6.1
## Description of the problem
GTK flatpak apps have horrible fonts. See screenshot of some gtk3-demo window.
![2020-02-10-075033](https://user-images.githubusercontent.com/4847726/74110688-94100480-4b86-11ea-82ce-0cb40307d643.png)
Outside of flatpak fonts rendering works normal. Nemo settings window for comparison:
![2020-02-10-075932](https://user-images.githubusercontent.com/4847726/74110816-7db67880-4b87-11ea-922d-788fd3edae0e.png)
On X11 GTK gets font rendering settings from Xsettings. Where does it get these settings on wayland? How do I set  it up on flatpak?

## Steps to reproduce
1. Install any gtk application (the last I tried was Flatseal, but Sublime-text has the same issues)
2. Start it
3. Fonts are horrible

**Comment by TingPing** [comment]
> On X11 GTK gets font rendering settings from Xsettings. Where does it get these settings on wayland? How do I set it up on flatpak?

It gets them from `xdg-desktop-portal >= 1.1.0` which gets them from `GSettings` on the host.

**Comment by eternal-sorrow** [comment]
> It gets them from xdg-desktop-portal >= 1.1.0 which gets them from GSettings on the host.

Do I need gtk-settings-daemon running on my system for that to work? Because non-flatpak gtk apps work normal without gtk-settings-daemon.

**Comment by TingPing** [comment]
No, gsd isn't involved in the process. The GSettings the portal reads happen to be the same GSettings gsd reads but that is all.

**Comment by eternal-sorrow** [comment]
Okay, I triple checked all my DConf settings storage and found nothing. No settings for font hinting, anti-aliasing etc. Where does xdg-desktop-portal get them from?

**Comment by TingPing** [comment]
`org.gnome.settings-daemon.plugins.xsettings.hinting` = `'slight'` here.

**Comment by eternal-sorrow** [comment]
I guess, it won't work if I don't have gsd installed and hence don't have gsettings schemas for `/org/gnome/settings-daemon/*`?

**Comment by TingPing** [comment]
Hmm, yeah, this setting should be moved to `gsettings-desktop-schemas`. That is probably something to request with that project or `gnome-settings-daemon` itself.

At the end of the day though it is just a single text file it depends on and its not like gsd needs to be running or anything.

**Comment by eternal-sorrow** [comment]
I manually installed and compiled schemas from gnome-settings-daemon, but it didn't do the trick. The problem persists.

**Comment by TingPing** [comment]
Might be an issue to report to GTK itself then.

**Comment by eternal-sorrow** [comment]
@matthiasclasen, as you [said](https://gitlab.gnome.org/GNOME/gtk/issues/2426#note_707477), continuing discussion here.

> what portal backends do you have installed ?

xdg-desktop-portal-gtk

**Comment by alexlarsson** [comment]
@eternal-sorrow When you compiled them, does `gsettings get org.gnome.settings-daemon.plugins.xsettings hinting` on the host print anything?

**Comment by eternal-sorrow** [comment]
@alexlarsson Yes, it prints `'medium'`.

**Comment by 0pendev** [comment]
I'm still having this issue. Is there a fix for it ?

**Comment by chrisawi** [comment]
This should be fixed now in the sense of getting reasonable default settings, see https://github.com/flatpak/flatpak/issues/2861#issuecomment-2027900633
