### ISSUE TITLE
Flatpak Repair Does Not Verify The Existence of Directories

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#3419]
## Version: flatpak-1.4.3-3.fc31.x86_64

I had a lot of empty folders in my home directory so I ran a find command to find and delete all the empty directories that I had created.

The find command deleted a lot of empty directories that were actually in use by flatpak and its runtimes and applications. Afterwards, all flatpak apps stopped functioning. 

I ran flatpak repair to no avail. It found no fault in the apps and runtimes and it subsequently did nothing. I had to manually run 'flatpak --user install --reinstall' on all the installed apps and runtimes to make them all work again. It would have saved me a lot of trouble if flatpak repair simply recreated the directories.

**Comment by alexlarsson** [comment]
I think `flatpak repair --reinstall-all` would have done what you wanted. That would redeploy the apps and create new files and directories, should any deployed file have changed.

In your specific situation it would have been possible to do this in a more efficient way by just re-deploying existing refs as (i assume) you hadn't lost any files in the ostree repo that needed to be re-downloaded. However, such an operation would have failed in the normal case where some object file was also damaged, so I don't think exposing that option is a great idea. Its not like flatpak repair is a commonly used operation.
