### ISSUE TITLE
Finer-grained access policies for audio playback/capture

### ISSUE THREAD

**Issue by vinipsmaker** [flatpak/flatpak#3425]
Currently FlatPak sandbox only allows either full/none access to the PulseAudio socket.

Is there a way to restrict audio device access only to playback -- and not capture?

If this place is inappropriate to fill the issue, maybe you could point out whether this bug is more likely to belong to PulseAudio or PipeWire? I sure would like an option Portal-like where I can change the permission while the application is running and until I give it explicit permission to run, any attempt from the application to capture audio will result in it reading from /dev/zero or some in the likes. But again, maybe this behaviour is better modelled with policies in the upper-layer (PulseAudio or PipeWire) and current behaviour is fine.

**Comment by TingPing** [comment]
At some point there was some discussion about Pulseaudio making that possible but it never happened, as-is you just get all or nothing. So we are just waiting for Pipewire.

**Comment by vinipsmaker** [comment]
Should I close the issue then? Or would it be useful to leave it open for some more PipeWire releases?

**Comment by TingPing** [comment]
Pipewire will be ready when pipewire is ready and flatpak will support it as soon as possible. Not much to track here IMO.

**Comment by nbenitez** [comment]
I believe this should be fixed when [Audio portal](https://github.com/flatpak/xdg-desktop-portal/discussions/1142) gets implemented.
