### ISSUE TITLE
Support self update like snap ?

### ISSUE THREAD

**Issue by abcfy2** [flatpak/flatpak#3427]
## Linux distribution and version
Debian stretch

## Flatpak version
0.8.9

## Description of the problem
Would you please support self update, just like snap?

`snap install core` will upgrade snap to the latest version, I think it's cool that flatpak could support this feature.

Maybe `flatpak install flatpak` is better.

**Comment by TingPing** [comment]
That just isn't possible. Flatpak cannot run inside of `flatpak` itself for various reasons, and the task of installing host packages involves things like dependencies. Its a shame but your distro just stay up to date or use a third party repository. In your case a slightly less outdated version is in `stretch-backports`
