### ISSUE TITLE
Locale runtime is getting installed even without main flatpak executable.

### ISSUE THREAD

**Issue by sundeep-co-in** [flatpak/flatpak#3431]
## Linux distribution and version
```
[root@localhost suanand]# uname -a
Linux localhost.localdomain 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Fedora 31 (Workstation Edition)
```
## Flatpak version
```
[root@localhost suanand]# /usr/local/bin/flatpak --version
Flatpak 1.6.1
[root@localhost suanand]# /usr/bin/flatpak --version
Flatpak 1.4.4

```
## Description of the problem
Locale runtime is getting installed even without main flatpak executable. For example:
`org.videolan.VLC.locale` is getting installed without `org.videolan.VLC` and pulls all the available translations.

Whereas, if we install `org.videolan.VLC` first - it works fine!
Should `org.videolan.VLC.locale` be dependent on `org.videolan.VLC`?

## Steps to reproduce
```
[~] flatpak install org.videolan.VLC.Locale
[~] pwd; ls

/usr/local/var/lib/flatpak/runtime/org.videolan.VLC.Locale/x86_64/stable/active/files

ach  an  ast  bn   bs   co  da  eo  eu  fi   fy  gl  hi  hy  it  kab  kn  ku
lt   ml  ms  nl  pa  pt  si  sq  ta  th  ug  vi  zu af   ar  be   br   ca   cs  
de  es  fa  fr   ga  gu  hr  id  ja  kk   ko  ky  lv   mn  nb  nn  pl  ro  sk  
sr  te  tr  uk  wa am   as  bg   brx  cgg  cy  el  et  ff  fur  gd  he  hu  
is  ka  km   ks  lg  mai  mr  ne  oc  ps  ru  sl  sv  tg  tt  uz  zh

```

**Comment by mwleeds** [comment]
Looks like you compiled flatpak yourself. Did you mean to use `--with-system-install-dir=/var/lib/flatpak` instead of creating another installation?

**Comment by sundeep-co-in** [comment]
kindly refer:

```
[root@localhost runtime]# /usr/bin/flatpak install org.videolan.VLC.Locale
Looking for matches…
Found similar ref(s) for ‘org.videolan.VLC.Locale’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: Y


        ID                                Arch            Branch          Remote           Download
 1. [✓] org.videolan.VLC.Locale           x86_64          stable          flathub          13.3 MB / 13.2 MB

Installation complete.
[root@localhost runtime]# pwd
/var/lib/flatpak/runtime
[root@localhost runtime]# ls org.videolan.VLC.Locale/x86_64/stable/active/files/
ach  an  ast  bn   bs   co  da  eo  eu  fi   fy  gl  hi  hy  it  kab  kn  ku  lt   ml  ms  nl  pa  pt  si  sq  ta  th  ug  vi  zu
af   ar  be   br   ca   cs  de  es  fa  fr   ga  gu  hr  id  ja  kk   ko  ky  lv   mn  nb  nn  pl  ro  sk  sr  te  tr  uk  wa
am   as  bg   brx  cgg  cy  el  et  ff  fur  gd  he  hu  is  ka  km   ks  lg  mai  mr  ne  oc  ps  ru  sl  sv  tg  tt  uz  zh
```

**Comment by mwleeds** [comment]
I don't see the problem here. You asked flatpak to install `org.videolan.VLC.Locale` and it did so. If you wanted only a subset of the locales you could use the `--subpath` option for the `install` command. In normal use, when the locale is installed automatically, only the appropriate subpaths are pulled.

**Comment by sundeep-co-in** [comment]
Sorry perhaps I didn't convey the message right.

I understand that, however standalone `*.Locale` may not be that much meaningful. Hence I was asking - Should `tld.namespace.app.locale` be dependent on `tld.namespace.app` ?

**Comment by mwleeds** [comment]
One might want to install a locale extension on its own to inspect it during development.
