### ISSUE TITLE
Token type metadata in undefined endianness

### ISSUE THREAD

**Issue by dbnicholson** [flatpak/flatpak#3434]
## Linux distribution and version
Endless OS master
## Flatpak version
1.6.2
## Description of the problem
The `xa.token-type` commit metadata and `tokt` sparse cache metadata are in an undefined endianness.
## Steps to reproduce
Export a flatpak with `--token-type=1`. `ostree show --raw` shows `'xa.token-type': <16777216>` and `ostree summary --raw` shows `{'tokt': <1>}` on a little endian system. I guess the latter is because `g_variant_byteswap` only swaps explicit numeric types. Either way, I think it's clear from the code that flatpak isn't handling the endianness of these values in any particular way.

**Comment by dbnicholson** [comment]
Obviously, changing this would also require flat-manager to do the same.

**Comment by alexlarsson** [comment]
Hmm, this is unfortunate. But i think we should just define it as little endian at this point, as that is what most clients and essentially all servers use.

**Comment by dbnicholson** [comment]
I'm fine with that. It's actually a pet peeve of mine that people continue to define things as big endian when roughly 99% of the world's computers are little endian. It will always look weird from an ostree perspective, but since it's not an ostree metadata field it doesn't matter.

**Comment by dbnicholson** [comment]
Since you're looking at this code, can I request a review of https://github.com/flatpak/flatpak-builder/pull/331?
