### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by guilieb** [flatpak/flatpak#3437]
## Linux distribution and version
Fedora 31 🙂

## Flatpak version
Flatpak 1.4.4

## Description of the problem
I don’t want to flood the issue tracker but I’m just opening this issue in order to have a unified way to track French translation. I did not find anything pertinent about the translation or any adopted process, so I’m opening this in order to ensure everyone that wants to work on it is here 🙈.

I’m involved in the GNOME French Team, I think it’s better in order to maintain consistency in translation between for instance GNOME Builder and flatpak.

**Comment by alexlarsson** [comment]
There is no real translation coordination atm for flatpak, buf if you have a translation for some language, just do a PR and it'll get merged.

**Comment by thibaultamartin** [comment]
I believe this issue can be closed, given the translations are tracked in GNOME’s translation platform Damned Lies as mentioned in #864 

It might still need to be documented somewhere
