### ISSUE TITLE
Limiting resources

### ISSUE THREAD

**Issue by H3sm4n** [flatpak/flatpak#3439]
## Linux distribution and version
Fedora 31 Workstation
## Flatpak version
1.4.4
## Description of the problem
Hello, I'm trying to make some flatpak applications running on the same desktop.
Is there a way to limit CPU and memory resources for each app within flatpak, if not, will it be added in the near future?

## Steps to reproduce

None

**Comment by gasinvein** [comment]
I believe this can be done by systemd. Flatpak spawns sandboxes in systemd scopes like `flatpak-APPID-PID.scope`. You can create a systemd override for an app scope and apply resource limits there.
Run `systemd --user edit --force flatpak-APPID-.scope` and put there something like
```
[Scope]
CPUQuota=10%
```
Refer to [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html) for details.

**Comment by H3sm4n** [comment]
Well sadly, this looks like a workaround for me, because whenever you start an application it gets an random flatpak-APPID-Number.scope file. changing this file to limit resources and restarting the application will result in a new flatpak-APPID-Number.scope file.
Could this be added within a YAML or JSON flatpak-builder file to make it easier to use? 

#### For example adding this to finish args: 

>   "finish-args": [
>         "--cpu=10%",
>         "--memory=1024"
>     ]

**Comment by gasinvein** [comment]
@H3sm4n You need neither to include PID number in the override file, nor edit generated scope unit file. Please read my post carefully. Override file `~/.config/systemd/user/flatpak-APPID-.scope.d/override.conf` will apply to all scopes matching `flatpak-APPID-`.

**Comment by H3sm4n** [comment]
Well, i did do that, nevertheless my suggestion with adding this within finish-args still stands.
anyway, what's the point of limiting network, filesystem etc? except the hardware resources?
I'm just trying to start an discussion about this topic and helping making flatpak a success as project.

**Comment by Iey4iej3** [comment]
> I believe this can be done by systemd. Flatpak spawns sandboxes in systemd scopes like `flatpak-APPID-PID.scope`. You can create a systemd override for an app scope and apply resource limits there.
> Run `systemd --user edit --force flatpak-APPID-.scope` and put there something like
> 
> ```
> [Scope]
> CPUQuota=10%
> ```
> 
> Refer to [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html) for details.

First, `systemd` should be replaced by `systemctl`.

On my system, it seems that `CPUQuota` does not work for userspace daemons, cf. https://bbs.archlinux.org/viewtopic.php?id=243622

Do you know any solution? I am currently using `cpulimit`, but there seem side effects.

**Comment by ell1e** [comment]
Can this be done without systemd?

It would be nice to have memory limits integrated into flatpak in particular. This could be useful for browsers, so that if in doubt the browser crashes rather than something essential, given browsers on Linux seem to often do a poor job with being conservative with memory use (compared to e.g. Android).
