### ISSUE TITLE
no instruction for gnome 3.22

### ISSUE THREAD

**Issue by medeotl** [flatpak/flatpak#344]
Flatpak's web site still miss installation instruction to install gnome 3.22 runtime (and apps). 
One of the great benefits of flatpak is that people can try new software without waiting for their distro to update (archlinux haven't yet it on stable repository, and there's no yet fedora 25).

afaik instruction for 3.20 runtime doesn't even work in fedora 24.

having flatpak instruction updated from day one would be a great boost for gnome discoverability IMO
sorry for my english

**Comment by alexlarsson** [comment]
The instructions on http://flatpak.org/index.html#users uses 3.20, but just switching that to 3.22 should work.
3.22 is listed at http://flatpak.org/runtimes.html

Not sure exactly what you meant should be different?

Also, how did the 3.20 runtime not work? It should.

**Comment by mwleeds** [comment]
Given how outdated this is I think it's safe to close (and runtimes install by default now when you install an app). @medeotl if you run into further issues please open a new issue.
