### ISSUE TITLE
Writing to shared memory from a container

### ISSUE THREAD

**Issue by H3sm4n** [flatpak/flatpak#3444]
## Linux distribution and version
Fedora 31

## Flatpak version

1.4.4

## Description of the problem

Hello, I'm trying to reach shared memory on the host within my flatpak application.
therefor, i downloaded simple C scripts to read and write to shared memory.
writing to the shared memory on the host and then reading the shared memory in the container is working, but i would like to write from inside the container and read the shared memory on the host.
Is this possible with flatpak?

## Steps to reproduce
None

**Comment by H3sm4n** [comment]
found out the solution myself.

**Comment by DamirPorobic** [comment]
What was the solution?
