### ISSUE TITLE
5484% of the installation completed

### ISSUE THREAD

**Issue by rnsavinelli** [flatpak/flatpak#3449]
![5484](https://user-images.githubusercontent.com/52708458/76135186-58d8e800-6003-11ea-919e-7d56609bb725.png)

## Linux distribution and version
Archlinux 5.4.6-arch3-1

## Flatpak version
1.6.2

## Description of the problem
5484% of the installation completed

**Comment by mwleeds** [comment]
Duplicate of #3448
