### ISSUE TITLE
Access permissions as in android (Function request)

### ISSUE THREAD

**Issue by wuniversales** [flatpak/flatpak#3453]
I think it would be interesting to add a flatpak permission system as in android.

The interesting thing would be to know what permissions the applications need, for example, write and read permissions on the disk, internet access, access to the local network, camera access, microphone access, printer access, among others.

If the applications do not have any permission activated (for example, the internet permit), that application cannot access the internet.

When viewing the applications, in a simple way in an application store, the permissions required by each application, (Internet access, writing and reading on the hard disk, etc.) would be displayed.

I do not know if I have explained the concept well, with this in my opinion the security of the applications would be greatly improved.

Cheers

**Comment by TingPing** [comment]
It already has permissions.

`flatpak info --show-permissions org.foo.bar` shows them.

The app store you use may or may not show part of them.

There is an app to graphically modify them here: https://flathub.org/apps/details/com.github.tchx84.Flatseal

So I don't think anything else is actionable here.
