### ISSUE TITLE
[Idea][Save/Open portal] Allow to suggest check document before saving

### ISSUE THREAD

**Issue by nintyfan** [flatpak/flatpak#3454]
## Description of the problem
Currently we have sandboxing and portals to save/open file outside the sandbox. That's great. But user will be more happy/secure, if flatpak allows to check file is correct and don't contains viruses.

## Possible of implementation ##
Sorry for that, but I'm not 100% sure how portals works, so I cannot make full project of this feature. I think, that user select file as now (in save dialog), but flatpak saves it into another location instead of override or create new file. In next step it will test file for viruses and it is correct (based on selected mime type). If there's error, portal will show warning to user with two option: move file into location prompted by user or cancel operation. When file test goes well, it will proceed without prompt. 
## Example
1. User are going to replace file with execution permission (for example a.sh) with photo
2. Application look at file extension and decided to override script with malicious code
3. Flatpak detects user tries to replace shell script or scan file send from program and detects it's malicious/shell script and warn user
4. User cancel operation

I know, it's very rare cases, but maybe someone will implement this in future.

**Comment by alexlarsson** [comment]
Virus scanning is outside the scope of sandboxing/portals. In needs to happen in a system context and is no different from a sandboxed app to any other app.

Also, the semantics of portals is not such that we can just put in arbitrary steps between apps and the files they write, this will break apps. Portals just limit what files you have access to, not how apps use them.
