### ISSUE TITLE
Flatpak Applications Freeze when Trying to Open Files

### ISSUE THREAD

**Issue by mrjpaxton** [flatpak/flatpak#3462]
## Linux distribution and version
Debian Unstable with Linux version 5.4.0-4-amd64

## Flatpak version
Flatpak 1.6.2

## Description of the problem
When I try to open a file in certain programs, such as in Drawpile, Dolphin Emulator, or Telegram's file attachment, it freezes immediately, and does not show any error messages.

## Additional details
Yes, I have read the following issue first: https://github.com/flatpak/flatpak/issues/2558

And this fix does NOT work for me. Any help would be great to debug this issue. Perhaps there is something I need to install?

I use a minimal Debian install with `i3` and `sway` as my window managers of choice.

I also have `xdg-desktop-portal` and `xdg-desktop-portal-gtk` installed, but they do not help fix the problem.

I also have no graphical file managers installed, but I previously tried installing Thunar and PCManFM on my host system. Both of which also do not solve the issue.

Using this command line to turn of sandboxing:

`flatpak run --command=sh --devel --system-talk-name=org.freedesktop.login1 <app>`

Then running the name of the application in Debian's DASH shell also did not help solve the problem.

**Comment by mrjpaxton** [comment]
Okay, this is very strange. The file chooser pops up in sway WM but not i3! I actually think this might be an i3 related bug! Hmm....

Sorry about this. I had no idea this problem was going to be WM specific. Although in sway, it is a bit messy, the window gets resized incorrectly when it is the inactive window vs active window. But at least it works in that WM.

Gonna close for now. I'll go downstream and report this to i3 instead.

**Comment by KeivnL** [comment]
I'm having the same problem, my distro is Feren OS (Ubuntu 20.04) with KDE Plasma 5.21.5
Dolphin Emulator, RPCS3 and FlightGear stop responding after trying to open to open file (in case of Dolphin, when selecting game directory), the window can be resized but responds to nothing, can't be closed either

**Comment by garciadias** [comment]
I am having the same problem in Pop!_OS 21.04 x86_64. Multiple applications cause the sane issue and the system needs a energy cut to reboot. Not even terminal interfaces respond.

**Comment by smcv** [comment]
@KeivnL, @garciadias: I think you are likely to be seeing similar symptoms, but for a different reason.

If you are using a recent-ish Linux kernel, then this might be the same thing as #4609 and #4595, which is a kernel bug and is fixed in kernels 5.16-rc3, 5.15.6, 5.10.83, 5.4.163 and 4.19.219. There is nothing Flatpak can do to solve this: it needs to be fixed in the kernel. If this is the root cause, then you would see a crash dump similar to the one in #4609 in your system log.

Otherwise, please open a *separate* issue with full details, instead of replying to an issue that was closed a year and a half ago.

**Comment by garciadias** [comment]
Thank you, @smcv. I am using 5.15.5-76051505-generic kernel. Giving permission for the apps to read the disk solved the problem. I think not having permission should not cause the whole system to freeze. I hope they solve it soon.

**Comment by smcv** [comment]
> I think not having permission should not cause the whole system to freeze

Not having permission to read everything means Flatpak needs to use FUSE to give apps permission to read individual files. Using FUSE should not cause the whole system to freeze, but in some recent kernels it does; this is a kernel bug, and is not something that Flatpak can fix.

Please report this to your distribution and ask them to update the kernel, if this is not already in progress.
