### ISSUE TITLE
Add builder options for custom (non build-api) workflows

### ISSUE THREAD

**Issue by mattdangerw** [flatpak/flatpak#347]
I'm currently looking at a story for making flatpaks for [electron apps](http://electron.atom.io/). Have a runtime going, and am working on adding flatpak support to the packaging stages of electron apps.

It's an interesting problem, as nodejs build processes are all over the place. For a lot of apps, the packaging phase involves downloading a lot of prebuilt binaries and shoving them into a variety of packaging formats. A linux build might target rpm, deb and appimage for x86_64, i386 and arm in a single run all without actually compiling a thing.

flatpak-builder has a lot of nice features I wanted to take advantage of, particularly the desktop and icon renaming, but doesn't quite fit in with the electron app build flows. Added two options so it could. [PR here](https://github.com/flatpak/flatpak/pull/346).

The first, `flatpak builder --finish-only` allows you to pick up where a `--build-only` build left off, and run only the cleanup, build-finish and export stages. Then you can have a flow that looks like this

``` shell
flatpak-builder --build-only build manifest.json
# run some build commands manually
flatpak-builder --finish-only build manifest.json
```

Seems like this option could be useful for GNOME Builder looking at https://wiki.gnome.org/Apps/Builder/Flatpak. And Endless is using flatpak-builder with some custom debian steps where this could also make things easier.

The second, `flatpak builder --allow-missing-runtimes` will keep flatpak builder from immediately aborting if the app's sdk and platform are not installed locally. For a normal workflow this is pretty useless, as soon as you try to run a `flatpak build` command for building a module, the process will exit because the sdk is missing.

But coupled with the option above, it allows you to support a build flow where you are just copying files and not building anything. In this case you target three architectures without downloading gigabytes of sdks, or worrying about arm emulation despite not actually needing to compile a thing.

Haven't started digging into the edge cases yet (`--finish-only` w/o running `--build-only` first?), first wanted to see people reactions on adding options like this in the first place.

**Comment by mattiasb** [comment]
I'm interested in making a Flatpak out of an Electron app as well sometime soon so this is valuable to me. Where can I follow your progress, do you have a repo somewhere?

**Comment by mattdangerw** [comment]
@mattiasb yeah! Totally work in progress at the moment, but here's what I got.

Runtime
https://github.com/mattdangerw/electron-flatpak-runtime/tree/flatpak

Some tooling
https://github.com/mattdangerw/flatpak-bundler/tree/flatpak
https://github.com/mattdangerw/electron-installer-flatpak/tree/flatpak
https://github.com/mattdangerw/grunt-electron-installer-flatpak/tree/flatpak

Some ports
https://github.com/mattdangerw/webtorrent-desktop/tree/flatpak
https://github.com/mattdangerw/brave-browser-laptop/tree/flatpak
https://github.com/mattdangerw/Ghost-Desktop/tree/flatpak

Everything is on flatpak branches at the moment so I can open up PRs into master and get comments, but will move to master soon.

I'm looking at a full runtime and tooling so its easy for existing electron apps to write ports. If you are interested in just building an electron app on an existing runtime (probably freedesktop), you could use this as a start for a builder app manifest https://github.com/mattdangerw/electron-flatpak-runtime/blob/flatpak/io.atom.electron.Sdk.json.in

**Comment by mattiasb** [comment]
Awesome, thanks!

**Comment by alexlarsson** [comment]
This is pretty cool! Having an easy way to create electron apps is going to be a huge boon.
I'm somewhat bothered by having the separate runtime though. Are you going to be constantly updating that one as the base runtime (fd.o one) gets e.g. security updates? Maybe it would be better if the node and the other dependencies were bundled with the app instead.

I wonder if we could use a model similar to the way the runtimes inherit from a parent build. I.e. you could ship a base electron app that has the dependencies, and we could create a new app based on that. Would that make sense?

**Comment by mattdangerw** [comment]
Thanks!

So this "base app" would just be all the library dependencies in `/app` without any desktop files or actual app code? And we'd add an extension to `flatpak-builder` to allow that sort of setup?

Get the security concern, and how basing on freedesktop directly would help.

My main concern is with keeping the level of effort required from an app developer on par with targeting debs and rpms. Think that would definitely help adoption. If every flatpak app build had to compile all those deps in from source that could take hours in the multi-arch case up from minutes for other package formats. But if its just downloading prebuilt "base apps" that's probably more appealing. Especially if there's a way to generate arm builds without a full cross compilation setup in the case where your just shipping a bunch of javascript on top of the electron binaries (see PR comment https://github.com/flatpak/flatpak/pull/346#issuecomment-253609737).

**Comment by alexlarsson** [comment]
> So this "base app" would just be all the library dependencies in /app without any desktop files or actual app 
> code? And we'd add an extension to flatpak-builder to allow that sort of setup?

Yes, this is not unlike how e.g. the gnome runtime is built:
  https://git.gnome.org/browse/gnome-sdk-images/tree/org.gnome.Sdk.json.in

See how it says "build-runtime=true", but it already lists a runtime. That means the "parent" (freedesktop) runtime is already installed and we build the gnome one on top of that. We can do something similar (but less hacky) for apps.

**Comment by alexlarsson** [comment]
I added support for this to flatpak-builder here:
https://github.com/flatpak/flatpak/commit/4cb3f7fd798d2ae403be4cf6c69390c3bcd0b755

**Comment by mattiasb** [comment]
If you use this approach, and put your Electron-apps in the same repo, does that mean that the Electron-app stuff is deduplicated by ostree automatically?

**Comment by alexlarsson** [comment]
Yes (as long as they use the same version of the base app).

**Comment by mattdangerw** [comment]
@alexlarsson thanks! I'll try out the new options.

What's the mental math on whether something should be a "base app" or a runtime? Function of how much active maintenance will be done? Seems like with the base app you have an easier time getting security fixes from freedesktop, but if you wanted to patch a bug in gtk2, everyone has to re-release their electron flatpaks.

Long term goal with either the base app or runtime would be to have this maintained as part of the electron project. I'll try to strike up a conversation with Atom/Electron team soon and want to make sure I have a clear picture here.

Also with those new builder options landed I think this issue can be considered complete.

**Comment by mattdangerw** [comment]
Also what happens if the base app was built against a totally different platform that the current app. Should we protect against that in builder somehow?

**Comment by alexlarsson** [comment]
"Should it be a runtime" is mostly a question of maintainance, rather than techincal reasons imho. Shipping an entire runtime makes you on the hook for a lot more dependencies. I agree that you still get some level of maintainance load to fix bugs in the bundled app dependencies, but its generally far less than shipping your own glibc, openssl and libjpeg. Its true that to pick up updates the individual apps have to get updates, but that is also true for fixes to electron itself, which is more likely to need updates than e.g. gtk2.

**Comment by alexlarsson** [comment]
As for the different platform question, we should probably at least warn about it.

**Comment by alexlarsson** [comment]
Closing this as we seem to have most things you want now. If not, open separate issues.

**Comment by tallero** [comment]
@alexlorsson there could be the chance of setting scripts as compilation methods?
