### ISSUE TITLE
[Feature Request] Add flag on uninstall subcommand to remove deprecated/eol versions of various flatpaks

### ISSUE THREAD

**Issue by tristan957** [flatpak/flatpak#3473]
## Linux distribution and version
Fedora 31
## Flatpak version
1.4.4
## Description of the problem
Today I updated flatpaks on my system and received the following warning:
```
Info: org.gnome.Sdk is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
Info: org.gnome.Sdk.Locale is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
```
The warning was easy to fix with various uninstall commands, but I was thinking that if flatpak already knows about eol/deprecated flatpaks, a flag could exist like --unused currently, that allows for a user to remove all eol/deprecated flatpaks.

This is something I would be willing to provide a PR for given enough time to get a grasp of the code base.

**Comment by mwleeds** [comment]
Well, we don't want to uninstall something that's deprecated but still used right? Then the app using it would no longer work.

**Comment by tristan957** [comment]
@mwleeds surely flatpak would know not to remove eol/depreceated flatpaks in the dependency graph if currently being used by another flaptak

**Comment by mwleeds** [comment]
So you're proposing something like `flatpak uninstall --unused-deprecated`. Sure, sounds reasonable.

**Comment by tristan957** [comment]
Yep that is a good way to put it. Cool. Should be pretty straightforward. I suspect I can learn a lot from the current `--unused` code. Does flatpak also have something like `flatpak list --end-of-life`? That could probably be a nice to have in my future PR.

**Comment by mwleeds** [comment]
> Yep that is a good way to put it. Cool. Should be pretty straightforward. I suspect I can learn a lot from the current `--unused` code. Does flatpak also have something like `flatpak list --end-of-life`? That could probably be a nice to have in my future PR.

No, that could be added. We probably should use the same term for both (either end-of-life of deprecated).

**Comment by tristan957** [comment]
I think `end-of-life` makes the most sense, since that is what is reported in the messages I posted in the issue.

**Comment by wvagner** [comment]
> ## Linux distribution and version
> 
> Fedora 31
> ## Flatpak version
> 
> 1.4.4
> ## Description of the problem
> 
> Today I updated flatpaks on my system and received the following warning:
> 
> ```
> Info: org.gnome.Sdk is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
> Info: org.gnome.Sdk.Locale is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
> Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
> Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
> ```
> 
> The warning was easy to fix with various uninstall commands, but I was thinking that if flatpak already knows about eol/deprecated flatpaks, a flag could exist like --unused currently, that allows for a user to remove all eol/deprecated flatpaks.
> 
> This is something I would be willing to provide a PR for given enough time to get a grasp of the code base.

Although it can be easy and simple for some user, I believe it's not a rule and many users do not know what to do when face such messages (me included). It would be great to have some sort of orientation of what to do. Tks!

**Comment by mwleeds** [comment]
Would be nice if we also added library API for this. For now we only have `flatpak_installation_list_unused_refs()`

**Comment by tristan957** [comment]
I can definitely do that.

**Comment by jgarciao** [comment]
After finding the not so useful message explained at #3687 I also think that these options could be very useful:
```
flatpak list --end-of-life

flatpak uninstall --end-of-life
```
I've found that normally apps that use deprecated runtimes are apps that I tried longtime ago and I don't need them anymore

**Comment by alexlarsson** [comment]
In master this is much better already. It auto-uninstalles unused, non-pinned runtimes that are eol. And for used eol:ed runtimes it will explain which apps are using it.

**Comment by tristan957** [comment]
Thanks @alexlarsson. Should this ticket be closed then?

**Comment by jgarciao** [comment]
Thanks @alexlarsson !

**Comment by mwleeds** [comment]
Yeah I think we can close this. The EOL messages could still be improved (#3531), but we don't need a command to remove unused EOL items since Flatpak does that by default in `flatpak update`.
