### ISSUE TITLE
No mDNS hostname lookup support

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#348]
I tried a Flatpak'ed network application, and it couldn't connect to my NAS. Turns out there's no mdns support within the sandbox. Or support for "myhostname mymachines" hosts name services, that systemd added recently.

**Comment by alexlarsson** [comment]
Is this just a matter of libavahi not being in the runtime, or is this something more complex?

**Comment by hadess** [comment]
You need mdns4_minimal installed and setup in the runtime, which probably needs some sort of access to Avahi (D-Bus?) I'm worried that other types of NSS modules will need to be supported in the future (LDAP or NIS support?) and I wonder how we'd support that. Proxy through nscd?

**Comment by alexlarsson** [comment]
Yeah, simo wanted to talk to me about this. I don't think we can really set up NSS inside the sandbox, the solution is likely to be something like nscd instead.

**Comment by hadess** [comment]
On the one hand, it's nice to be able to resolve dot-local hostnames, on the other, what do we do when an app wants to funnel all the LDAP user names.

**Comment by ahayzen** [comment]
FWIW, this also affects auto discovery and broadcast of DAAP shares within Rhythmbox https://github.com/flathub/org.gnome.Rhythmbox3/issues/4.

**Comment by ahayzen** [comment]
Follow up for Rhythmbox, we were able to use `--system-talk-name=org.freedesktop.Avahi` which allows this to work when the host has Avahi installed. https://github.com/flathub/org.gnome.Rhythmbox3/issues/4

**Comment by hadess** [comment]
This bug is about mDNS lookups, not about access to Avahi for service discovery. Being able to talk to Avahi will not fix or work-around this bug.

> You need mdns4_minimal installed and setup in the runtime, which probably needs some sort of access to Avahi (D-Bus?) I'm worried that other types of NSS modules will need to be supported in the future (LDAP or NIS support?) and I wonder how we'd support that. Proxy through nscd?

Adding mdns4_minimal to the runtime might be the way to fix this problem.

**Comment by charliehorse55** [comment]
Hello, just piping in to share that this bug affects me! I'm using flatpak to run Barrier to control a VM, and I can't connect via hostname since that's discovered through mDNS.

**Comment by hadess** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1013 is a portion of it. I don't think there's anything specific that Flatpak needs to be doing here.

**Comment by z3t4m4n** [comment]
Hi, Floorp's oficial flathub is unable to resolve .local domains using mDNS, locally installed firefox has no such problem. Kind regards.
