### ISSUE TITLE
[Feature Request] Add elementary dark variant into the themes

### ISSUE THREAD

**Issue by validatedev** [flatpak/flatpak#3486]
## Linux distribution and version
elementary OS 5.1.2 Hera
## Flatpak version
Flatpak 1.6.2
## Description of the problem
Well, there is a theme `org.gtk.Gtk3theme.elementary`, but not `org.gtk.Gtk3theme.elementary-dark`. I'm using the dark variant of the elementary theme all over the system.
## Steps to reproduce
Use dark variant of the elementary theme
Open any app (e.g. Geary)
You can see that it doesn't apply on the Geary

**Comment by TingPing** [comment]
This isn't a place to ask for packages. You can request it here and I'll try to get around to it soon: https://github.com/flathub/org.gtk.Gtk3theme.elementary/issues

**Comment by validatedev** [comment]
> This isn't a place to ask for packages. You can request it here and I'll try to get around to it soon: https://github.com/flathub/org.gtk.Gtk3theme.elementary/issues

Thanks for the info!
