### ISSUE TITLE
Make create-usb allow partial refs by default

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#3491]
As discussed on IRC today:

In https://github.com/flatpak/flatpak/commit/b8d2196c2e31814a0d55c70376a463dbbf9cf208 we made `flatpak create-usb` error out if any ref is only partially deployed and `--allow-partial` wasn't used (since the install on the target computer might fail if they use a different language). But locale extensions are only partially downloaded by default, so this means `create-usb` will fail in the most common use case. We should instead print a warning if a deploy is partial, and perhaps attempt to download the full locale extension if we're online.

**Comment by mwleeds** [comment]
Relatedly, create-usb currently [omits partially installed extensions](https://github.com/flatpak/flatpak/blob/fec3cd13fa284920b620f204336e19c6cb589ce0/app/flatpak-builtins-create-usb.c#L164), but I think we want to include them. Some translation is better than none right?

**Comment by abderrahim** [comment]
> Some translation is better than none right?

Actually, this translation is useful more often than not. The other person you're giving the usb key to is quite likely to speak the same language. (They may have a different language set-up in their computer, though)
