### ISSUE TITLE
`flatpak --user` is taking too much space in ~/.local/share/flatpak/repo

### ISSUE THREAD

**Issue by genodeftest** [flatpak/flatpak#350]
I've installed and uninstalled some apps through flatpak. Right now, I don't have any flatpak apps installed. Still, `~/.local/share/flatpak/repo` takes 2.0 GB of my disk space. This looks wrong.

In case this folder is just used for caching, please move it to `~/.cache/flatpak` or `~/.cache/flatpak/repo`. And please provide a `clean` command similiar to `dnf clean`. 

In case this folder is not used for caching, is there any chance we can get this be smaller? 2 GB per user is way too much to be feasible on a multi-seat installation.

**Comment by alexlarsson** [comment]
Maybe you still have some runtimes installed?
What does `flatpak list -d --app --runtime` say?

**Comment by genodeftest** [comment]
```
$ flatpak list -d --app --runtime
org.gnome.Platform.Locale/x86_64/3.20   gnome         821e798dce9a -            139,2 MB user,runtime /de
org.gnome.Platform.Locale/x86_64/master gnome-nightly bc358aca1311 d9c34ad53d7b 137,7 MB user,runtime /de
org.gnome.Platform/x86_64/3.20          gnome         62cd43189e62 1f5e189869a4 645,5 MB user,runtime    
org.gnome.Platform/x86_64/master        gnome-nightly 8d2f15347b95 1162a45747ef 664,9 MB user,runtime    
org.gnome.Sdk.Locale/x86_64/master      gnome-nightly e092ac1ca13a 75240618501b 137,7 MB user,runtime /de
org.gnome.Sdk/x86_64/master             gnome-nightly eb5edbd7427d b24e793d02b2 1,4 GB   user,runtime    
```
So yes, I have some old runtimes installed.
Running
```
$ flatpak --user uninstall org.gnome.Platform 3.20
Zugehörige werden deinstalliert: org.gnome.Platform.Locale
$ flatpak --user uninstall org.gnome.Platform master
Zugehörige werden deinstalliert: org.gnome.Platform.Locale
$ flatpak --user uninstall org.gnome.Sdk
Zugehörige werden deinstalliert: org.gnome.Sdk.Locale
```
removed them, now the `~/.local/share/flatpak/repo` folder is just 2 MB, which is Ok.

Looks like this is a user error, so feel free to close. Thanks for the hint and sorry for the noise.

**Comment by alexlarsson** [comment]
NP.
