### ISSUE TITLE
Clamtk flatpak from flathub doesn't detect mtp devices (phones etc.)

### ISSUE THREAD

**Issue by monterrr** [flatpak/flatpak#3507]
## Linux distribution and version 
Fedora 31
## Flatpak version 
1.4.4-2
## Description of the problem
When scanning a directory on clamtk doesn't detect mtp devices (phones).
When asked about this, the dev said it "isn't really something we can work around afaik"
## Steps to reproduce
Run clamtk and have a mtp device connected, it wont detect it for scan.

**Comment by refi64** [comment]
...I am not very smart, I just googled it and found a solution *that I
wrote*: https://github.com/flatpak/flatpak/issues/2923

I'll add it tomorrow, it's pretty justifiable given the use case of ClamTk.
That being said this definitely isn't a Flatpak bhg, so this should be
closed.
