### ISSUE TITLE
On GNOME-Wayland, a lot of Flatpak applications don't start as long as Xwayland is not running

### ISSUE THREAD

**Issue by antistress** [flatpak/flatpak#3509]
## Linux distribution and version
Debian Sid GNOME-Wayland **with XWayland On-Demand experimental function**
## Flatpak version 
1.6.2-1
## Description of the problem
Hi,
Here is an always reproductible bug that I've found concerning several Flatpak applications from FlatHub :
On my Debian Sid GNOME-Wayland system, I've started to try the experimental function from GNOME 3.34 (I'm running GNOME 3.34.2) that allows Xwayland to start on demand :
`$ gsettings set org.gnome.mutter experimental-features "['autostart-xwayland']"`
(see https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.34-Mutter-X-On-Demand)

Here what I've noticed concerning [VLC](https://github.com/flathub/org.videolan.VLC/issues/99), [LibreOffice](https://bugs.documentfoundation.org/show_bug.cgi?id=131623), FileZilla, Audacity, Avidemux, Calibre, Frozen Bubble, GIMP, Thunderbird :

- As long as XWayland is not running, these applications-Flatpak don't start.
- As soon as XWayland is running, these applications-Flatpak can be started.
- Launch one of these applications-Flatpak and then later start XWayland : the application-Flatpak finally appears on my desktop.

Note that keying `flatpak run --socket=wayland org.videolan.VLC` don't solve the problem.

By comparison, the same applications in their deb package version from Debian repos can start without Xwayland.

How I've tested :
I've checked that my system starts without Xwayland by checking my processes
To start Xwayland, I've launched an X11-application (like Thunderbird or Firefox from Debian repos) which consequently starts Xwayland which consequently allow the application-Flatpak to start.
I've checked that Xwayland was running by checking my processes.

Finally, note that Shotwell, Pitivi and Transmission don't suffer from this bug.

Thanks

**Comment by refi64** [comment]
Out of curiosity, is [this](https://github.com/flatpak/flatpak/issues/938#issuecomment-601479851) the error you get if you start from the CLI?

**Comment by antistress** [comment]
> Out of curiosity, is [this](https://github.com/flatpak/flatpak/issues/938#issuecomment-601479851) the error you get if you start from the CLI?

No, if I key `flatpak run --socket=wayland org.videolan.VLC` I get no error. Terminal displays "VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)" and then wait.

**Comment by antistress** [comment]
Here are some additional information :

1°) At present time **all my flatpak applications are supposed to run natively on Wayland** (either it's the case by default, or I have manually activated the wayland socket in their launcher). I've checked by myself for each application by running $ xlsclients.
However the bug is still there.
Therefore having some applications that are blocked and don't show themselves graphically is independant from the fact they are running natively under Wayland or not.

2°) Sometimes while running one of these applications, something else appears in $ xlsclients about XDG portal GTK
Maybe it's the cause of this bug if that component needs XWayland ?

Thanks

**Comment by abderrahim** [comment]
I did some digging into the issue, so what happens is that there are both an "abstract" socket and a "unix" socket that mutter/gnome-shell listen on, but 1. mutter/gnome-shell only starts Xwayland if it receives a connection on the abstract socket and 2. flatpak apps seem to try to connect to the unix socket.

So the flatpak apps would block waiting for Xwayland to start, but it won't start unless something tries to connect on the abstract socket.

So arguably, this is a bug in mutter as it should use both sockets. But it would be interesting to know why flatpak apps use the unix socket (is it impossible to use the abstract one?)

**Comment by Erick555** [comment]
AFAIK abstract socket won't exist is separate network namespace (in case when app doesn't have network permission).

**Comment by nanonyme** [comment]
@abderrahim  is there already an issue on Mutter side about this?

**Comment by refi64** [comment]
Is this still reproducible? I think this was a Mutter/Shell issue that has since been fixed, haven't had any issues on 3.36 for some time now.

**Comment by antistress** [comment]
On my Debian Testing GNOME-Wayland system with flatpak 1.6.3-1 & mutter 3.36.2-1 & gnome-shell 3.36.2-1
Bug is still there

**Comment by antistress** [comment]
This comment on bugzilla.mozilla.org may be related :
(In reply to Robert Mader [:rmader] from comment #75)
> Site note while working on it: there`s still no equivalent to `GLX_MESA_query_renderer` to get vendor and device IDs. I opened an issue for it here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/2976
> 
> Atm we use GLX even on Wayland if available, in order to e.g. whitelist devices for Webrender rollout. On Gnome Shell the Xwayland on demand feature is getting closer to get enabled by default - so we'd need to start up Xwayland together with FF just to query those two IDs :(

https://bugzilla.mozilla.org/show_bug.cgi?id=788319#c75

**Comment by BjoernDaase** [comment]
FWIW, [this](https://gitlab.gnome.org/GNOME/mutter/-/issues/1289) is the corresponding issue on the Mutter side.

**Comment by Manizuca** [comment]
This bug has been [fixed](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1424) for mutter 3.38. I don't know if it will be backported to 3.36.6

**Comment by antistress** [comment]
Indeed, bug is fixed on my Debian testing system with mutter 3.38.1-2

Thanks !
