### ISSUE TITLE
Export /app/share/pixmaps

### ISSUE THREAD

**Issue by mattdangerw** [flatpak/flatpak#351]
Not sure if we actually want this, but opening for discussion.

Working on flatpaking electron apps, and most of those (Slack and Atom for example) are sticking giant pngs in `/usr/share/pixmaps` for their icons. Think apple requires 1024x1024 icons these days.

We could demand apps stick things in `/usr/share/icons`, but hicolor doesn't support 1024x1024 at the moment https://bugs.freedesktop.org/show_bug.cgi?id=98301

Might be easiest to just add `/app/share/pixmaps` to the list of exported locations.

Happy to write the patch for this if this is in fact something we want.

**Comment by alexlarsson** [comment]
We're not actually forbidding you to export pixmaps. The only special casing is in that we automatically export things from $prefix/share/icons. If your scripts manually puts icons in export/share/pixmaps that will work fine.

I'm not sure we should make it *too* simple to support that though, as it is kind of the "old way" to do things.

**Comment by mattdangerw** [comment]
That works! Did not realize that exports were free form like this.

This does mean there will be no way to get something like this working with `flatpak-builder`, and anyone wanting to ship at 1024x1024 icon will have to run some custom scripting after `flatpak build-finish` (which errors if export dir already exists) or wait for distros to gain support for them massive icons in `$prefix/share/icons`. So from the app devs point of view its an extra hurdle.

Do understand if we don't want to encourage the "old way" though, if so we can probably close this issue.
