### ISSUE TITLE
Flatpak update triggers Sophos Anti-Virus Alert

### ISSUE THREAD

**Issue by MBoegers** [flatpak/flatpak#3512]
## Linux distribution and version
Ubuntu (Gnome) 19.08
## Flatpak version
Flatpak 1.4.3, like shipped by apt install
## Description of the problem
When executing `$ flatpak update` an Sophos Anti-Virus  Alert is triggered. It says that a lock file in `/var/tmp/flatpak-cache[...]`  can not be scanned due to denied access.

Full error alert for Gerary (same for all packages)
``` bash
********************** Sophos Anti-Virus Alert ***********************
Error scanning file
"/var/tmp/flatpak-cache-3BWQI0/org.gnome.Geary.Locale-LSJFI0/repo-2oMYlz/tmp/staging-045008da-5b84-46d1-99f0-aae5f411f008-46QYAq-lock".

Access to the file has been denied

**********************************************************************
```

## Steps to reproduce
1.  Install Sophos Anti Virus like [here](https://wiki.ubuntuusers.de/Sophos_Anti-Virus_f%C3%BCr_Linux/)
2.  run `$ flatpak update`

**Comment by javaseeds** [comment]
I am getting this too - tried intalling Spotify with Flatpak and got the same error dozens of times

**Comment by TingPing** [comment]
Sounds like something you should e discussing with Sophos.

**Comment by hfiguiere** [comment]
not a flaptak issue.
