### ISSUE TITLE
flatpak downloads the summary twice for every ref it tries to pull

### ISSUE THREAD

**Issue by abderrahim** [flatpak/flatpak#3515]
## Linux distribution and version
Debian sid
## Flatpak version
master
## Description of the problem
A long time passes between flatpak starting to install a ref, and the progress bar actually starting to refresh.

I traced it down to `ostree_repo_pull_with_options` which is called twice (once from `flatpak_dir_setup_extra_data` and once directly from `flatpak_dir_pull`), and downloads the summary every time.

## Steps to reproduce
Just try it, it should be noticeable even with a fast connection. Otherwise, try to somehow limit your bandwidth. At ~1MB/s it should be noticeable pulling from flathub.

**Comment by alexlarsson** [comment]
Gah, i hate the `flatpak_dir_setup_extra_data` hack, but we should be able to do better now that we simplified things by dropping the p2p stuff

**Comment by alexlarsson** [comment]
When i try it seems to be reusing the cached summary though.

**Comment by abderrahim** [comment]
Something important I forgot to mention in the OP is that this happens with system installation, I didn't try user install.

A short dive in gdb shows that the repo we pass to `ostree_repo_pull_with_options` has a `cache_dir == NULL`. I'll try to track this down.

**Comment by abderrahim** [comment]
#3562 is what I came up with. It seems to me that the child repos don't look at their parent for cached summary, so I explicitly  set the cache dir. It seems to fix the issue here, please tell me if this is unacceptable.

**Comment by Mikenux** [comment]
@abderrahim: Your PR has since been merged. Does it actually solve your issue? If so, could you please close it? Thanks!
