### ISSUE TITLE
'flatpak import --from' with wrong GPGKey: misleading 'Socket I/O timed out' error

### ISSUE THREAD

**Issue by stbergmann** [flatpak/flatpak#352]
When using a LibreOffice.flatpakref

> [Flatpak Ref]
> Title=The Document Foundation LibreOffice
> Name=org.libreoffice.LibreOffice
> Branch=fresh
> Url=http://download.documentfoundation.org/libreoffice/flatpak/repository
> IsRuntime=False
> GPGKey=mQENBFgF0QQBCADIBDCu2oUvPVvhfCL5OVXxcRcAWKT/RnG6K6eWTuuZgv1MtZQ2GDcznTYQxbuzci7+AhhE5T6YZuBFeSloXfzpR2lypnkarSsTir1D9oG+bk4YaZcvOsorEdYe6qKGHM7fFNefXFiE7gqApGloEytDxtY99Dpg9TyrXaBUeJK3wHSEMoOg+qBjSXwdsG6AGXwuw/sF0BeXC/s8kol2fa4sj2HJK12BOnuxiAmrlsrywgafguJiACrjJu7zzgrbae0Mfw5wAzQd+6KSrtA8TzbR1jzWI5FqQuMgHOn6BhSpodGyu+ZODQxsyMNoazkIGK0JaPdNc+6zaq5PfR1OM/p7ABEBAAG0BHRlc3SJATcEEwEIACEFAlgF0QQCGwMFCwkIBwIGFQgJCgsCBBYCAwECHgECF4AACgkQ+Xifln4PTdYOXwgAi5s2t5b0ZQgZSZ4q3NNgeyy3bR3i6vuODlr/sJBmuzxaAa5iiByus+3sZlgD1JoGLyipuJ1xJx0ZvG8rFauJHGWJBASFtZaLci1J/jA0s+ueib+WqwSL34PobONL+htdiqU2e3hdQgaIvFpQhkOqdnFSF/qTJ/qn/i+DjRIbr1GzDphuY9kEaauMssJFv8+22xrTOQsI47vbe6I6jdzfANGW9ITjTdTIrfy4893KCoFy3SjsJAUFo75RVfYMn1tBM/s1INfhOSgsQJet0rNgOPqjfj8F82/y+JHbgu2XZR7/NqcMUKuAIs37MpNW5QIWFF4xQMZiF110zwYznztodrkBDQRYBdEEAQgAtJI1/W35ZKFT1+0kLav2QFpapriabzaoHZR5UmZmtJoX9g6gmesl3yq/1Z0Qp3vLJqN43tuhwB6JvcZEy48Dg30V4oxPcg6YAi6VRIR419zXJ/kJLA8NQ8SAb8HtBq+UcbN0k2iwcnrC0F1YatSlOKAi228LtXB/0/Xr2CM0mKeru6Gzaca3jMoSY8JNdkH6hrE+S3MDmFTtQOmz4tO2cZO3RjXFN5v2/Rv/tVu973L0MswviEsn4wjze7V1tQ///P7gah2IcLWZMzlDqjdPc182wBTPkccf5VGeTlvCbjst/FOwNFCuJN/Xn/shkpakGR7E8/AxC4WjZlby3+8ukwARAQABiQEfBBgBCAAJBQJYBdEEAhsMAAoJEPl4n5Z+D03W0foH/3xmfTheO4a/GxKv4LWUIvJEb92rjDXHfy12W3i5jl6kjAdm7r0rXGlBk6vWBcgOEPBcLpl36qmECDIHdmpIY7OJnMye5uP1O/QmRGnqHSmBKX2As23xbTaMRcjLgSDYE4u770tK4sB4sVVK04085DepHqofvXJ0Q5sdRvrZscksAlYby1DYWn6fT8KtkCTpx6sBzo5Uf00IWNgeodaZg1ln6w5mMTA4pECT06m/aRcN0g9ea8Knh6TbAXvF7fYravatKUB2II5BJurWxXkDDWO3OUdpgG/Ehg16s38hfcY1hFR+s+pc0eKMdVLK7sEmamyvdG40MxWyfnTHTlhADXI=

with a bogus GPGKey line, 'flatpak import --from LibreOffice.flatpakref' fails with a misleading

> error: While pulling app/org.libreoffice.LibreOffice/x86_64/fresh from remote org.libreoffice.LibreOffice-1-origin: Socket I/O timed out

instead of with an error about the wrong GPGKey.

**Comment by mwleeds** [comment]
I just tried installing from a flatpakref file with a mangled GPGKey= line and got a pretty reasonable error "error: Error modifying remote: GPG: Unable to export keys: GPGME: No data"
