### ISSUE TITLE
Desktop file has wrong command

### ISSUE THREAD

**Issue by lazka** [flatpak/flatpak#3534]
## Linux distribution and version

Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal

## Flatpak version

Flatpak 1.6.2

## Description of the problem / Steps to reproduce

I've installed zulip and somehow the command written to the desktop file is wrong, which makes only "flatpak run" work. I'm not sure if this is a flatpak issue or a packaging issue. I assume the Exec line in the desktop file is auto generated.

```
> flatpak install --system org.zulip.Zulip
Looking for matches…
Found similar ref(s) for ‘org.zulip.Zulip’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Skipping: org.zulip.Zulip/x86_64/stable is already installed
```

```
cat /var/lib/flatpak/exports/share/applications/org.zulip.Zulip.desktop | grep command
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zulip --file-forwarding org.zulip.Zulip @@u %U @@
```

```
> flatpak info -m org.zulip.Zulip | grep command
command=zulip-wrapper
```

**Comment by refi64** [comment]
I believe this is a bug in the Zulip Flatpak, which should edit its desktop
file to point to the wrapper command.

**Comment by TingPing** [comment]
Indeed.
