### ISSUE TITLE
Flatpak Software do not show up on Desktop

### ISSUE THREAD

**Issue by Antibiotikum** [flatpak/flatpak#3536]
## Linux distribution and version
OpenSuse Leap 15.2 Beta with KDE
(Problem occurred on Leap 15.1 too)

## Flatpak version
1.6.2.

## Description of the problem
Flatpak Software do not show up on Desktop.

I can start Software from the Konsole but get the following Message:

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/penecelin/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

## Steps to reproduce
I am having the problem for a long time so i am not sure, but i think it showed up after i tried my Desktop under Wayland. I am back to x11 again.

##  Debugging so far
"echo $XDG_DATA_DIRS" gives me no output.

'/var/lib/flatpak/exports/share' seams to exist.

'/home/penecelin/.local/share/flatpak/exports/share' does not exist on my System.

I tried reinstalling Flatpak via "zypper in -f flatpak" with no effect. 

This is my first bug report ever, so if something is missing, let me know.

-> Edit: If this is a Duplicate please let me know, i could not find any solution. Same for troubleshooting.

**Comment by adhamsalama** [comment]
Same issue here with Kubuntu and Wayland

**Comment by hfiguiere** [comment]
This is a distro bug / setup.
