### ISSUE TITLE
flatpak segfault

### ISSUE THREAD

**Issue by LargePrime** [flatpak/flatpak#3538]
## Linux distribution and version
clear Linux 32760
## Flatpak version
1.6.2
## Description of the problem
sudo flatpak repair
Working on the system installation at /var/lib/flatpak
Segmentation fault

sudo flatpak repair --user
Working on the user installation at /root/.local/share/flatpak
Segmentation fault

## Steps to reproduce
be me, do
sudo flatpak repair
sudo flatpak repair --user

I don't know how to test further. I imagine this is a curl thing

**Comment by mwleeds** [comment]
Any chance you can install debug symbols and get a backtrace?
1. `dnf search flatpak` and note which packages have `dbgsym` in them. Install them with `sudo dnf install ...`
2. `sudo gdb --args flatpak repair`
3. `run`
4. Wait for seg fault and then `thread apply all bt`

**Comment by LargePrime** [comment]
> Any chance you can install debug symbols and get a backtrace?
> 
>     1. `dnf search flatpak` and note which packages have `dbgsym` in them. Install them with `sudo dnf install ...`
> 
>     2. `sudo gdb --args flatpak repair`
> 
>     3. `run`
> 
>     4. Wait for seg fault and then `thread apply all bt`

1 dnf search flatpak
Unable to detect release version (use '--releasever' to specify release version)
No matches found.

2-4 see https://pastebin.com/Lmy7GJzb

**Comment by mwleeds** [comment]
What does `ls /var/lib/flatpak/repo` show?

**Comment by lebensterben** [comment]
> Any chance you can install debug symbols and get a backtrace?
> 
> 1. `dnf search flatpak` and note which packages have `dbgsym` in them. Install them with `sudo dnf install ...`


FYI Clear Linux doesn't use DNF for software management. To install flatpak with debug information requires one to build it from source.

**Comment by LargePrime** [comment]
ls /var/lib/flatpak/repo
config  extensions  objects  refs  state  tmp

**Comment by mwleeds** [comment]
The pastebin link expired and this isn't actionable unless someone can [get usable debug info](https://wiki.gnome.org/Community/GettingInTouch/Bugzilla/GettingTraces).

**Comment by LargePrime** [comment]
sudo gdb --args flatpak repair
Password: 
/usr/share/gdb/python/gdb/command/prompt.py:48: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.value is not '':
/usr/share/gdb/python/gdb/command/prompt.py:60: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.value is not '':
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-generic-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from flatpak...
(No debugging symbols found in flatpak)
(gdb)

**Comment by mwleeds** [comment]
Looks like there was no segfault in that instance

**Comment by LargePrime** [comment]
still editing

**Comment by LargePrime** [comment]
no longer giving segfault
