### ISSUE TITLE
How to clean flatpak repo/objects folder?

### ISSUE THREAD

**Issue by JanChytry** [flatpak/flatpak#3542]
Hi all, 

#2945 has not given me a proper response so I am asking straightforward:

I have uninstalled all flatpaks on my computer, the folder /var/lib/flatpak/repo/objects/ is still huge, taking up almost 9 GB of space. 
How can I clean it or remove it? If there is no dedicated flatpak command, can I safely remove the whole /var/lib/flatpak folder manually after I have: `sudo apt remove flatpak ` ?

Thanks!

### Configuration:
Linux Mint 19.2
Flatpak 1.0.9

**Comment by TingPing** [comment]
Just a guess: `sudo ostree prune --repo=/var/lib/flatpak/repo`

**Comment by refi64** [comment]
`flatpak uninstall` should already prune iirc, are you sure there aren't any leftover runtimes?

**Comment by JanChytry** [comment]
I am dead sure, I used `flatpak  uninstall --unused` many times and `flatpak list` returned an empty space. /var/lib/flatpak/repo is still cluttered.

I mean I consider `sudo apt uninstall flatpak` entirely and assume then it must be safe to remove, innit.

**Comment by JanChytry** [comment]
@TingPing 
`sudo ostree prune --repo=/var/lib/flatpak/repo` 
returned:

`
error: No such metadata object b652ad50773fd61316b7aac0c3b7419742a5283abe3909ab3fb04d1c96d37dab.dirtree
`

**Comment by TingPing** [comment]
`sudo flatpak repair` ?

**Comment by JanChytry** [comment]
Oh my god, I have it and seemingly with a very stupid mistake...
`
~$ flatpak repair
Verifying flathub:appstream2/x86_64...
Removing non-deployed ref flathub:runtime/org.freedesktop.Sdk/x86_64/19.08...
Pruning objects
error: No such metadata object b652ad50773fd61316b7aac0c3b7419742a5283abe3909ab3fb04d1c96d37dab.dirtree
`
returned an error one would never expect because I didn't use good ol' SUDO.

`
~$ sudo flatpak repair
Verifying flathub:appstream2/x86_64...
Removing non-deployed ref flathub:runtime/org.freedesktop.Sdk/x86_64/19.08...
Pruning objects
~$
`
And voila! Repo folder is nearly empty.

I suggest changing how flatpak handles missing sudo error. This was very frustrating.
I think we can close this.

**Comment by dennismayr** [comment]
> Oh my god, @TingPing you are right.
> 
> ```
> ~$ flatpak repair
> Verifying flathub:appstream2/x86_64...
> Removing non-deployed ref flathub:runtime/org.freedesktop.Sdk/x86_64/19.08...
> Pruning objects
> error: No such metadata object b652ad50773fd61316b7aac0c3b7419742a5283abe3909ab3fb04d1c96d37dab.dirtree
> ```
> 
> returned an error one would never expect because of not using the good ol' SUDO.
> 
> ```
> ~$ sudo flatpak repair
> Verifying flathub:appstream2/x86_64...
> Removing non-deployed ref flathub:runtime/org.freedesktop.Sdk/x86_64/19.08...
> Pruning objects
> ~$
> ```
> 
> And voila! Repo folder is nearly empty.
> 
> I suggest changing how flatpak handles missing sudo error. This was very frustrating.
> I think we can close this.

I've done this exactly, but I wanted to ask first, since something looks odd:

```sh
$ sudo flatpak repair

[71/145] Verifying flathub:[package name, etc]
Pruning objects
Erasing .removed
```

Why would `flatpak repair` stop at just `71`? would this behaviour be expected?

**Comment by refi64** [comment]
@dennismayr Looks like it's just a bug in the progress reporting, should be fixed in #4410.

**Comment by dennismayr** [comment]
Got it; thanks for the update!

**Comment by QuestionMark001** [comment]
> `sudo flatpak repair` ?

@TingPing Thanks for you,Bro.👍

**Comment by stacode123** [comment]
> `sudo flatpak repair` ?

hmm seems not to work for me.
would only having 200mb of disk space affect that?

**Comment by pabloab** [comment]
Using Flatpak 1.11.1. After a `remove --unused`, `sudo flatpak repair` had reduced my `du -sh /var/lib/flatpak/` from 1.5G to 89M. Shouldn't this be considered a bug?  Shouldn't clean up/repair at least every time in a while?

**Comment by jwverzijden** [comment]
fyi I deleted the directory and it was not a problem. 
maybe it's best if flatpak simply cleans up this junk when its not needed anymore.

**Comment by meghadeep-com** [comment]
Flatpak definitely needs to implement some sort of automatic cleanup, I went from 626GB

![Image](https://github.com/user-attachments/assets/2349a968-907d-42d8-bf57-defd2bca0ce6)

to 55GB

![Image](https://github.com/user-attachments/assets/4fdd33b5-5f59-4671-baf4-19ed305e045e)

**Comment by razzeee** [comment]
> Flatpak definitely needs to implement some sort of automatic cleanup, I went from 626GB
> 
> ![Image](https://github.com/user-attachments/assets/2349a968-907d-42d8-bf57-defd2bca0ce6)
> 
> to 55GB
> 
> ![Image](https://github.com/user-attachments/assets/4fdd33b5-5f59-4671-baf4-19ed305e045e)

which flatpak version are you using?

**Comment by meghadeep-com** [comment]
Flatpak 1.16.0

**Comment by razzeee** [comment]
> Flatpak 1.16.0

right now and all those flatpaks were only installed with 1.16.0?

**Comment by meghadeep-com** [comment]
Definitely not, been using this system for a while. Probably about 2% of my Flatpaks were installed with 1.16.0.

**Comment by razzeee** [comment]
As far as I've heard, there were some bugs in older versions, that did cause stuff not being cleaned up correctly, but that should be over.
