### ISSUE TITLE
Question: what is sideload ?

### ISSUE THREAD

**Issue by rffontenelle** [flatpak/flatpak#3546]
I'm updating Flatpak translation and came across with the new term **sideload** in source strings, which I don't fully understand. What is sideload in Flatpak, and what is it for? Thanks in advance

**Comment by mwleeds** [comment]
When you put apps and/or runtimes on a USB drive using `flatpak create-usb`, you can later install them from the USB, "sideload" them, by adding a symbolic link to the USB mount in `/var/lib/flatpak/sideload-repos` or `/run/flatpak/sideload-repos` and then doing the install/update. See `man flatpak`. Or you can use the `--sideload-repo` option for `flatpak install` or `flatpak update`.

It's not a new feature, but it's been rewritten and renamed, and used to work differently.

**Comment by mwleeds** [comment]
I guess we should add a `TRANSLATORS:` comment in the source for this.

**Comment by milotype** [comment]
@rffontenelle Don't know if it helps, but I've translated the term as "local download" in Croatian. (I'm not a technician nor programmer)

**Comment by rffontenelle** [comment]
@mwleeds My question was answer. May I close this or you want to keep it to add a `TRANSLATORS:` comment at some point?

**Comment by mwleeds** [comment]
Let's leave it open to be closed by #3579
