### ISSUE TITLE
AARCH64 fails to block migrate_pages syscall

### ISSUE THREAD

**Issue by rinigus** [flatpak/flatpak#3548]
## Linux distribution and version

Sailfish OS, 3.2.1

## Flatpak version

1.6.2, arm (32 bit)

## Description of the problem

On Sailfish, we have AARCH64 devices with AARCH64 kernel, but using 32-bit user space. So, flatpak and its libraries are compiled using ARM. I can install aarch64 apps and try to run them. This will fail with the message

```
error: Failed to block syscall -10097
```

Failure occurs in https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L2753 while being called with `migrate_pages`. If I replace the error handling with a warning and allow `setup_seccomp` function to continue, I can run applications. (well, within limits as there is no hardware acceleration, but that is Sailfish OS issue that we will have to resolve on our side). All other syscalls are blocked without issues.

Sailfish can also be used on x86_64 tablet, user space using i386. In this case, Flatpak can run x86_64 without problems.

## Steps to reproduce

See above in the description. Let me know if the formalized steps are needed.

**Comment by alexlarsson** [comment]
Do you have any idea why it fails for you? Is SCMP_ARCH_AARCH64 defined during build? We run all the arm builds on aarch64 kernels, and those works, so it definitely *should* be possible to filter it.

It probably wouldn't hurt to make this failure some kind of warning instead, but it would be nice to figure out why it fails.

**Comment by rinigus** [comment]
Hi! Where is SCMP_ARCH_AARCH64 expected to be defined? Should it be for flatpak build?

**Comment by alexlarsson** [comment]
It is defined in `/usr/include/seccomp.h` for me.

**Comment by rinigus** [comment]
Thanks, I will look into it.

**Comment by alexlarsson** [comment]
Maybe you need a new version of libseccomp?

**Comment by Mikenux** [comment]
@rinigus: Any news about your issue?

**Comment by rinigus** [comment]
@Mikenux: let's close this issue. Situation has changed and we have full AARCH64 support now. For some reason I didn't managed to get it working on my devices and we cannot use Flatpak on SFOS now. But the reasons, as far as I remember, are not related.

Closing and sorry for keeping it open over here.
