### ISSUE TITLE
Ability to set the --user flag as default

### ISSUE THREAD

**Issue by avrelaun** [flatpak/flatpak#3552]
I find myself always installing/managing flatpak apps as user apps.
Is there a way to configure the --user flag as default instead of --system ?
I understand an shell alias could do the trick, but it would be cleaner if set directly on flatpak config IMHO.
If such a feature does not exist, please consider this ticket as a feature request.

**Comment by mwleeds** [comment]
If the system installation is empty, you should be able to leave off `--user` and have the user installation still be used. Is your use case that you have some things installed system-wide and others per-user?

**Comment by avrelaun** [comment]
Yes, I removed system apps and now it implicitely use  `--user`.
Thanks @mwleeds

**Comment by teohhanhui** [comment]
I'd really like to be able to do `flatpak install ...` as `--user` by default, instead of it telling me nothing matches (because the specified remote doesn't exist in `--system`).

**Comment by mwleeds** [comment]
> I'd really like to be able to do `flatpak install ...` as `--user` by default, instead of it telling me nothing matches (because the specified remote doesn't exist in `--system`).

Not sure what Flatpak version you're on but the expected behavior is that the `install` command will automatically detect that the per-user installation should be used if the specified remote exists there and only there.

**Comment by teohhanhui** [comment]
Uhh, you're right. Sorry about that.

It just gives a confusing message when the branch is not matched, e.g.

    $ flatpak install flathub org.mozilla.firefox//beta
    Looking for matches…
    error: Nothing matches org.mozilla.firefox in remote flathub

**Comment by mwleeds** [comment]
Yeah that's confusing, added a comment to #3996

**Comment by teohhanhui** [comment]
Another example:

    $ flatpak install --from https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxNightly.flatpakref

Expected result: It should default to `--user`.

Actual result: It defaults to `--system`.

**Comment by akdev1l** [comment]
https://docs.flatpak.org/en/latest/using-flatpak.html

> Flatpak commands are run system-wide by default. If you are installing applications for day-to-day usage, it is recommended to stick with this default behavior.  
> 
> However, running commands per-user can be useful for testing and development purposes, since objects that are installed in this way won’t be available to other users on the system. To do this, use the --user option, which can be used in combination with most flatpak commands. 

where is the behaviour above documented? The flatpak website seems to say `--user` is always required

**Comment by rusty-snake** [comment]
You mean which flatpaks command has no support for `--user`? 

All where it makes no sense. Look at `flatpak <command> --help`. Example: `flatpak enter --help`.

**Comment by akdev1l** [comment]
No, the documentation suggests `flatpak install`  *always* works on the system wide storage.

This thread seems to say I can or cannot use `--user` as long as I have a configured remote as `--user`. 

> Not sure what Flatpak version you're on but the expected behavior is that the install command will automatically detect that the per-user installation should be used if the specified remote exists there and only there.

This isn't documented anywhere that I could see, except here. (if it is feel free to point me there)

**Comment by SteveLauC** [comment]
Well, `flatpak -h` does not mention that the `--user` option can be used directly with `flatpak` but it actually can, so one can do the following alias:

```sh
$ alias flatpak='flatpak --user'
$ flatpak install flathub xx.xx.xx
```

**Comment by rusty-snake** [comment]
Now try to run `flatpak ps`.

**Comment by SteveLauC** [comment]
> Now try to run `flatpak ps`.

Everything seems to be ok?

**Comment by rusty-snake** [comment]
Good for you.

```console
$ LANG=C flatpak --user ps
error: Unknown option --user
```

**Comment by rusty-snake** [comment]
Expected because `flatpak ps -h` has no `--user` (do not make sense after all).

**Comment by SteveLauC** [comment]
Maybe this hack will only work in specific versions

**Comment by tribbloid** [comment]
after this, how to override this and install on the system level?

`flatpak --system` doesn't work
