### ISSUE TITLE
Import/export issue

### ISSUE THREAD

**Issue by danrobi11** [flatpak/flatpak#3555]
I went seek help in the flatpak subreddit but no luck so far: https://www.reddit.com/r/flatpak/comments/fzk670/importexport_files/
Some apps wont let me import/export while others do.
Freetube and lbry does let me.
Firefox, Tor browser, falkon and thunderbird wont let me.

**Comment by mwleeds** [comment]
This bug tracker is for bugs in Flatpak itself. For particular apps, you can file a bug in their repo under https://github.com/flathub if they come from Flathub.
