### ISSUE TITLE
Can't uninstall an app if its remote is not known

### ISSUE THREAD

**Issue by sknorr** [flatpak/flatpak#3557]
## Linux distribution and version

openSUSE Leap 15.1

## Flatpak version

flatpak 1.2.3

## Description of the problem

I can't uninstall an app if its remote is not known to Flatpak. I don't quite know how I got into this situation but I think I just downloaded and installed a Flatpak from a gitlab.gnome.org pipeline and it somehow installed its remote in a weird way.

What I got, was this situation where I could suddenly not uninstall an app just because there was no remote for it:

```
$ flatpak remove  --force-remove  org.gnome.TodoDevel
error: Remote "tododevel-origin" not found

$ flatpak remote-list
Name             Options
flathub          user
gnome-nightly    user
```

Adding a bogus remote helped with the uninstall:

```
$ flatpak --user  remote-add tododevel-origin http://example.com/
error: GPG verification enabled, but no summary found (check that the configured URL in remote config is correct)

$ flatpak remove  --force-remove  org.gnome.TodoDevel

        ID                         Arch          Branch
 1. [-] org.gnome.TodoDevel        x86_64        master

Uninstall complete.
```

Now, to make this bug a two-fer, I can't seem to get rid of the bogus remote anymore:

```
$ flatpak remote-delete --force tododevel-origin 

$ flatpak remote-list
Name             Options
flathub          user
gnome-nightly    user
tododevel-origin user
```

(I have now found the file .local/share/flatpak/repo/config and removed the remote there.)

----

Ftr, this commenter seems to have the same issue with uninstallation failing because of a broken remote: https://github.com/flatpak/flatpak/issues/3361#issuecomment-573347719

**Comment by mwleeds** [comment]
From the changelog for Flatpak 1.5.0:
`* Uninstall now always work, even if the remote it came from was force removed.`

If you can reproduce the issue of not being able to delete a remote on a more recent version of Flatpak, feel free to open a bug report for that.
