### ISSUE TITLE
Ugly fonts for GNOME apps under KDE/Plasma

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#356]
When I run

`flatpak run org.gnome.gedit`

in a KDE/Plasma session, fonts look awful.  The problem does not exist when I run the same flatpak under GNOME or MATE.

Here is a screenshot:

![gedit-flatpack](https://cloud.githubusercontent.com/assets/2168323/19486800/17e5276c-9560-11e6-8161-4f4883b88cf3.png)

**Comment by hadess** [comment]
Is that under X.org or Wayland? Looks like the font could be missing from the runtime, or the session XSettings are overriding the defaults, switching the font to another one.

**Comment by alexlarsson** [comment]
We're exposing the system fonts to the sandbox, so it should not be the case that the font is missing. (Unless there is a bug with this i guess.)

**Comment by LaurentBonnaud** [comment]
This is with X.org.

**Comment by lassana** [comment]
Same problem with monodevelop:
![screenshot_20161119_151423](https://cloud.githubusercontent.com/assets/2004960/20455377/9020f7a0-ae6b-11e6-8ca8-d9812f799db4.png)

**Comment by alexlarsson** [comment]
Turns out this was a misconfiguration of the fontconfig config in the runtime. I pushed a fix, and when its rebuilt and propagateda simple `flatpak update` should fix this.

**Comment by alexlarsson** [comment]
Verified that the latest runtime version fixes this. Just `flatpak update` and you should be ok.

**Comment by LaurentBonnaud** [comment]
I confirm that the bug is now fixed.  Thanks a lot!
