### ISSUE TITLE
Gimp's Shortcut doesn't appear after flatpak installation on Fedora 31

### ISSUE THREAD

**Issue by dmontalvo51** [flatpak/flatpak#3560]
## Gimp shortcut doesn't appear  after installing Gimp
I followed the steps in Gimp's website  [Gimp](https://www.gimp.org/downloads/)

1. Dowloaded flatpakref file
2. Executed command flatpak install https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref

After instalation is complete I can execute the program with the command 

**flatpak run org.gimp.GIMP//stable**

but there is no shortcut created. I know I could create my own desktop file but I think flatpak is supposed to create it on the installation isn't it?

**Comment by refi64** [comment]
If this is a brand new Flatpak install, reboot and see if it shows up.
Otherwise, I believe if you use fish as your login shell these won't show
up.

**Comment by dmontalvo51** [comment]
Thank you! It worked
