### ISSUE TITLE
Can't add local directory permission to spotify

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [flatpak/flatpak#3566]
## Linux distribution and version
opensuse Leap 15.1
## Flatpak version
1.2.3
## Description of the problem
I need to add /home/james/mnt/windisk/Music directory to the spotify local music scan folder.
So I did
`sudo flatpak override com.spotify.Client --filesystem=/home/james/mnt/windisk/Music/`
But when I restart spotify, in the adding local folder popup window, I can only see /home/james/, and a bunch of unrelated folders. 

BTW, I don't know if it's related, but the folder was a windows partition that is automatically mounted under /home/james/mnt/

**Comment by refi64** [comment]
Make sure Spotify is a system installation, if it's a user one drop the
sudo from the override command and pass --user.

**Comment by GreatBigWhiteWorld** [comment]
It's a user one.  Passing "--user" works!
I wonder if there is something I need to do about my previous incorrect command (sudo flatpak override...)? Do I need to undo it somehow?

**Comment by GreatBigWhiteWorld** [comment]
Spotify would freeze when scanning for local files after a few minutes. I have 30G of music files or so.

**Comment by TingPing** [comment]
This is just a package, it can't fix Spotify bugs.
