### ISSUE TITLE
Please add Ubuntu 16.10 (yakkety) to your PPA

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#357]
I am using this PPA:

`  https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak`

and would like to see packages built for Ubuntu 16.10.

**Comment by alexlarsson** [comment]
Is there now. Its not perfect (see mailing list) but it works.

**Comment by LaurentBonnaud** [comment]
Thanks!
