### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by robertdaleweir** [flatpak/flatpak#3572]
Can I use Flatpak to install a newer version of Flatpak, so I can install Flatpak Applications on an older Linux OS?  It says it requires at least 0.10.3 (for me to install a Thunderbird Flatpak Version) and I only have 0.8.7.
Robert

**Comment by refi64** [comment]
What OS are you using? If it's Debian Stretch, grab the Flatpak version
from backports.

**Comment by mwleeds** [comment]
No, since Flatpak is for installing desktop apps whereas Flatpak itself is a system component which requires among other things a service that runs as root (flatpak-system-helper).
