### ISSUE TITLE
Why not to add /var/lib/flatpak/exports/bin to PATH?

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#3573]
## Linux distribution and version
Fedora 31
## Flatpak version
1.4.4
## Description of the ~~problem~~ question
Why not to add /var/lib/flatpak/exports/bin to PATH?

**Comment by ieugen** [comment]
I'm also interested in having better command line application support. I keep coming back to check the status on this since I have a quite a few cli apps that I would like to package as flatpack apps. 

Things can be improved in this area. There was some discussion https://github.com/flatpak/flatpak/issues/1188 . However it did not bode well with the developers/maintainers of the project and it was closed.

**Comment by nemith** [comment]
I just read somewhere that our company, who support feodra, looking into silverblue, and in general should embrace flatpaks are deciding to looking to snaps based on this very issue.

Even if there is a prompt during the installation install an alias to the flatpak so it is opt-in.

**Comment by TingPing** [comment]
To state the obvious you opt-in by modifying `$PATH`. The only discussion is about defaults.

**Comment by ieugen** [comment]
Thanks @TingPing for pointing the obvious. I did that and it is helpful. However regarding CLI apps that need to be part of scripts, it's not very helpful without aliases. 

Managing aliases manually is not the best experience. I think there is a lot of room for improvement here.

**Comment by TheAlgorythm** [comment]
I don't understand why everyone claims there would be a problem with shadowing, as `$PATH` has a traversal order.

Let's say binaries called `foo` are in the directories `/primary` and `/secondary`. As long as `PATH` is `/primary:/secondary` the call `$ foo` will execute the binary from `/primary`.

If there would be no `foo` in `/primary` then it would execute the binary from `/secondary`. But this is **not** shadowing.
This would just be an installation of additional binaries, where I don't see much security implications.

Theoretically the presence of an executable could alter the control flow of a program, but this is much less of a risk than shadowing.

**Comment by TingPing** [comment]
@TheAlgorythm This doesn't appear to be true.

```
echo '#!/bin/sh\necho Here' > ~/.local/share/flatpak/exports/bin/sudo
chmod +x ~/.local/share/flatpak/exports/bin/sudo
sudo
> here
```

**Comment by TheAlgorythm** [comment]
I had the information from these links:
- https://stackoverflow.com/a/13088816
- https://superuser.com/a/238993

Well there seem to be problems.

## bash

As described. (Maybe problems when hashing enabled, but `hash` will reset to order)

## zsh

Uses hashing by default on my machine and therefore the first added executable.
There is a [workaround](https://stackoverflow.com/a/36547391) to call `hash -r`/`rehash`.

## fish

[Seems](https://github.com/fish-shell/fish-shell/issues/4087) to work as expected.

## generic executable

I tried it in Rust and it worked as expected.

## Python

Worked as expected.

## Conclusion

Some shells use hashing for performance reasons, but the intended behaviour can be enforced by calling `hash`/`hash -r`/`rehash` after adding an executable to the `PATH`.

(Learned something interesting today)
