### ISSUE TITLE
Damn slow download of flatpak in ubuntu 20.04

### ISSUE THREAD

**Issue by nazar2sfive** [flatpak/flatpak#3574]
```
android@clr:~$ flatpak --version
Flatpak 1.6.3
android@clr:~$ 

```
![image](https://user-images.githubusercontent.com/12841320/80229426-2006d800-8670-11ea-99db-8598a59c1e00.png)

**Comment by FestplattenSchnitzel** [comment]
I can confirm this for Ubuntu 18.04.4 when trying to download something from FlatHub. When I installed Flatpak it only took a second to get the searching for updates of `flatpak update` done. Now it tooks minutes.

**Comment by Rawieo** [comment]
Same on Arch

![Screenshot_20200725_220637](https://user-images.githubusercontent.com/5720631/88463683-94e2eb80-cec5-11ea-928c-82aed29ddf51.png)

**Comment by Rawieo** [comment]
Oh never mind it's [teamspeak's servers that are slow](https://github.com/flathub/com.teamspeak.TeamSpeak/blob/master/com.teamspeak.TeamSpeak.yaml#L49), not flathub's

**Comment by alexlarsson** [comment]
Network performance is rarely a problem with flatpak itself, but some infrastructure issue at flathub (or other server). Closing this as there isn't really much to do here.
