### ISSUE TITLE
OpenURI portal dialog box should match application theme (in case of dark variant)

### ISSUE THREAD

**Issue by antistress** [flatpak/flatpak#3575]
## Linux distribution and version
Debian GNU/Linux Testing GNOME-Wayland with libgtk-3-0 3.24.18-1
## Flatpak version
Flatpak 1.6.3-1
## Description of the problem
Hi,
I'm running org.pitivi.Pitivi in its default dark GTK+3 theme flavor.
Despite this, I've noticed that OpenURI portal dialog box is light grey.
See screenshot :
![OpenURI in Pitivi](https://user-images.githubusercontent.com/2436957/79172947-b243ec00-7de5-11ea-906b-cdbe93a16d93.png)
## Steps to reproduce
Get org.pitivi.Pitivi at http://developer.pitivi.org/Install_with_flatpak.html
Add clip onto the timeline
Click Render
Then click Play

Thanks

**Comment by chrisawi** [comment]
Nowadays, the portal dialogs will respect the global color scheme preference (dark mode), but allowing a specific app to request color-matching dialogs would require new portal API. You could open an issue in https://github.com/flatpak/xdg-desktop-portal for that, but I don't think it's likely to happen.
