### ISSUE TITLE
Themes do not apply in flatpaks when on Window Maker

### ISSUE THREAD

**Issue by Charadon** [flatpak/flatpak#3591]
## Linux distribution and version
Manjaro
## Flatpak version
Flatpak 1.7.2
## Description of the problem
Themes do not apply correctly on window maker
## Steps to reproduce
0. Install and launch Window Maker session
1. Install the Materia GTK theme
2. Use a GTK configuration tool (like lx-appearance) to set GTK theme.
3. Install the Materia GTK theme flatpak
4. Install any GTK app from Flathub
5. It will use normal adwaita instead of materia.

**Comment by Brn9hrd7** [comment]
I've seen this with other window managers as well(Bspwm, qtile, Openbox, i3, awesomewm, etc.)

**Comment by Charadon** [comment]
Yeah i've noticed that too. I wonder if there's a way to manually set a theme? Because I can't find anything on doing that.

**Comment by Charadon** [comment]
So, I did find a workaround. You have to specify the environment variable GTK_THEME. So if I wanted to use Materia I would do GTK_THEME=Materia
Now this solves the theme issue for GTK, but I don't know the equivalent for QT.

**Comment by Brn9hrd7** [comment]
I am aware of the GTK_THEME environment variable, but unforfunately that causes issues when using applications that use a different theme (e.g. Planner forces the Elementary theme and looks broken when there is a GTK_THEME variable set).

**Comment by Charadon** [comment]
Maybe you can set an alias or make a script to unset the GTK_THEME variable when running those specific applications? Though you're probably already doing/done that.

**Comment by Brn9hrd7** [comment]
Making a script is definitely possible, but the theming should still be improved, because the average user won't create an environment variable and scripts just to get the theming right. I personally am just using the native versions (either repo or AUR) for the time being (at least for GTK applications), unless I have a reason to use the flatpak version(e.g. I've had issues with Gnome Boxes installed from the Arch repo).

**Comment by Brn9hrd7** [comment]
I just found a solution to the problem. You can install xfce4-settings and put `xfsettingsd` in the autostart section of your window manager, then you can configure the theme through `xfce4-settings-manager`. It may work with other settings daemons as well (e.g. gnome-settings-daemon), although I haven't tried that.

**Comment by TingPing** [comment]
Yes you just need an XSettings service.
