### ISSUE TITLE
HandBrake flatpak not working

### ISSUE THREAD

**Issue by superbonaci** [flatpak/flatpak#3592]
## Linux distribution and version
Ubuntu 20.04 LTS

## Flatpak version
Flatpak 1.6.3

## Description of the problem
Unable to install HandBrake

## Steps to reproduce
Go to: https://handbrake.fr/downloads2.php
Download: https://handbrake.fr/rotation.php?file=fr.handbrake.HandBrakeCLI-1.3.1-x86_64.flatpak

```
flatpak install fr.handbrake.HandBrakeCLI-1.3.1-x86_64.flatpak

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/ed/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: The application fr.handbrake.HandBrakeCLI/x86_64/stable requires the runtime org.freedesktop.Platform/x86_64/19.08 which was not found
```

**Comment by mwleeds** [comment]
Flatpak bundles don't include the needed runtime. You'll have to get it from [Flathub](https://flathub.org/) with `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak install flathub org.freedesktop.Platform/x86_64/19.08` and try again. Ideally when Handbrake is building that bundle they would include the runtime repo URL with `flatpak build-bundle --runtime-repo=...` but evidently they didn't.

**Comment by superbonaci** [comment]
@mwleeds thank you very much, it worked. But now how to I launch `handbrake`? It doesn't seem to be installed on any directory from my $PATH. It's so difficult this flatpak thing.

**Comment by superbonaci** [comment]
Apparently you have to manually launch it (now works):
```
flatpak run fr.handbrake.HandBrakeCLI --help
```

**Comment by mwleeds** [comment]
Yeah it might not include a desktop icon if it's a CLI app.

You can also add `/var/lib/flatpak/exports/bin` to your `$PATH` to be able to launch it with `fr.handbrake.HandBrakeCLI` (if you install system-wide).

**Comment by superbonaci** [comment]
That's another point Iitlooked suspicious to me. It turns out the HandBrake faltpak is just the CLI, not the GUI. When I wanted to install the deb file wasn't available for ubuntu 20.04, but now that it is, I've replaced the flatpak CLI with package GUI+CLI and ended up saving ~1.4GB:

```
flatpak uninstall fr.handbrake.HandBrakeCLI org.freedesktop.Platform.GL.default org.freedesktop.Platform.GL.nvidia-435-21 org.freedesktop.Platform.Locale org.freedesktop.Platform.openh264 org.gtk.Gtk3theme.Greybird org.freedesktop.Platform
```
```
sudo apt install handbrake handbrake-cli
```

**Comment by mwleeds** [comment]
Yeah, the per-app disk space used when you have one flatpak installed is pretty high. If you have many that share runtimes it's not so bad.

**Comment by bradleysepos** [comment]
@superbonaci https://handbrake.fr supplies a GUI Flatpak that also includes the CLI, and a CLI-only Flatpak.

Be aware, the Ubuntu repo packages are modified and known broken in various ways, hence the team's decision not to offer any support for them. Sadly, we don't have any control over this.

**Comment by superbonaci** [comment]
@bradleysepos I see, but the flatpak with GUI is a recent build, a few days ago there was available only the CLI.

**Comment by bradleysepos** [comment]
We've shipped the GTK GUI as Flatpak for something like 3 years and downloads show in our logs, so I'm not sure what you're referring to.

Anyway, feel free to chat more with us on one of our [community support channels](https://handbrake.fr/community.php), I don't want to clog this issue tracker more than we already have. 😸
