### ISSUE TITLE
ALSA and dmix

### ISSUE THREAD

**Issue by keleset** [flatpak/flatpak#3593]
## Linux distribution and version
5.4, Void
## Flatpak version
Latest
## Description of the problem
I'm using Steam through Flatpak, and ALSA inside Flatpak's sandbox refuses to use "plug" or dmix.

Why I'm using alsa instead of pulse? Well, my favorite game got weird glitches with pulse and it's perfectly fine on alsa. Plus, personal preference - alsa is flawless experience for me, aside from this problem with flatpak here. I'm not "ALSA veteran" by any means and I don't have any experience in solving problems with it (as I said, it always "just worked" for me before).

So, what works:
```
pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw           
    card 1
}
```
This^ as only alsa config (using `ALSA_CONFIG_PATH` env var). BUT (you guessed right) every single application inside flatpak (Steam, any game) devours my sound card whole as dmix is not used. So, I'm trying this (example from https://www.alsa-project.org/main/index.php/Asoundrc):
```
pcm.!default {
        type plug
        slave.pcm "dmixer"
}

pcm.dmixer  {
        type dmix
        ipc_key 1024
        slave {
                pcm "dmixerhw"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

pcm.dmixerhw {
        type hw
        card 1
}

ctl.dmixer {
        type hw
        card 1
}
```
and it results in (no sound):
```
ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_plug_open
ALSA lib ../../src/dlmisc.c:295:(snd1_dlobj_cache_get) symbol _snd_pcm_plug_open is not defined inside [builtin]
[0502/094352.248350:ERROR:alsa_util.cc(204)] PcmOpen: default,No such device or address
ALSA lib ../../../src/pcm/pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM plug:default
[0502/094352.248424:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,No such file or directory
```

also tried this:
```
pcm.!default  {
        type dmix
        ipc_key 1024
        slave {
                pcm "dmixerhw"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

pcm.dmixerhw {
        type hw
        card 1
}

ctl.dmixer {
        type hw
        card 1
}
```

which instead results in:
```
ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_dmix_open
ALSA lib ../../src/dlmisc.c:295:(snd1_dlobj_cache_get) symbol _snd_pcm_dmix_open is not defined inside [builtin]
[0502/095157.547278:ERROR:alsa_util.cc(204)] PcmOpen: default,No such device or address
ALSA lib ../../../src/pcm/pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM plug:default
[0502/095157.547336:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,No such file or directory
```

I've also tried to use the same config as my system provides and it also results in `_snd_pcm_plug_open` not defined.

So, the question is, why can't alsa use plug and dmix in flatpak, while it's totally fine outside of it? Would appreciate any help/info, thank you in advance.

**Comment by alexlarsson** [comment]
Dmix is an entire host-side daemon, similar to pulseaudio. This is not accessible in the sandbox, nor is it supportable as a sandboxing option (that would require strong ABI and protocol compat requirements). What is available in the sandbox is the kernel ALSA apis.
