### ISSUE TITLE
`flatpak install` from local remote fails if repo path contains a space character

### ISSUE THREAD

**Issue by Yvan-Masson** [flatpak/flatpak#3595]
## Linux distribution and version
Debian testing (Bullseye) 64 bits
## Flatpak version
1.6.3-1
## Description of the problem
`flatpak install` from local remote fails if repo path contains a space character.
## Steps to reproduce
I am packaging an application called MyApp, following [the documentation](https://docs.flatpak.org/en/latest/first-build.html#put-the-app-in-a-repository):
```
flatpak-builder --repo=~/some\ directory/flatpak-repo --force-clean flatpak-build/ org.something.MyApp.yml
…
flatpak build-update-repo flatpak-repo
flatpak --user remote-add --no-gpg-verify my-repo ~/some\ directory/flatpak-repo
flatpak --user install my-repo org.something.MyApp
…
Error: /home/yvan/some%20directory/flatpak-repo: opendir(/home/yvan/some%20directory/flatpak-repo): No such file or directory
error: Failed to install org.something.MyApp: /home/yvan/some%20directory/flatpak-repo: opendir(/home/yvan/some%20directory/flatpak-repo): No such file or directory
```
If I move the local repo to a path without space, `flatpak install` works perfectly. I checked commits since the Flatpak release I use and could not find anything related to this issue.

Regards,
Yvan

**Comment by refi64** [comment]
I believe this was fixed by [this OSTree PR](https://github.com/ostreedev/ostree/pull/2293).
