### ISSUE TITLE
flatpak_installation_list_installed_refs_for_update does not return downloaded but not deployed updates

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#360]
Do `flatpak_installation_update(FLATPAK_UPDATE_FLAGS_NO_DEPLOY)` on an update, then call `flatpak_installation_list_installed_refs_for_update()` and the application doesn't seem to be listed.

Perhaps list_installed_refs_for_update needs to check if a commit has been deployed rather than just pulled?

Richard

**Comment by alexlarsson** [comment]
Doesn't that break the way you're using list_installed_refs_for_update() currently in gnome-software. I.e. the docs say:

> However, even though an app is not returned by this it can have local updates available that has not been deployed. Look at commit vs latest_commit on installed apps for this.

I specifically made it do that to match gnome-softwares two-phase install thing, where list_installed_refs_for_update() is what you call to get what you want to download, and then list_installed() can be used to see which local app updates are downloaded and need deploying.

**Comment by hughsie** [comment]
Okay, that works for me. Sorry for the noise.
