### ISSUE TITLE
xdg-open opens a dialog instead of applying system's mimeapps.list

### ISSUE THREAD

**Issue by kupiqu** [flatpak/flatpak#3601]
## Linux distribution and version

KDE neon user edition 18.04 (on top of Ubuntu LTS 18.04)

## Flatpak version

1.7.2-flatpak2~bionic deb package from Ubuntu repo:
http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic/main amd64 Packages

## Description of the problem

I want to use an external editor in Octave (https://github.com/flathub/org.octave.Octave). As suggested in https://github.com/flathub/org.octave.Octave/issues/105, I can workaround this using `system ('xdg-open file.txt')`, however xdg-open does not use default system's text editor as specified in mimeapps.list (which is the one I want to use), but instead it displays a dialog with some alternatives to choose from

## Steps to reproduce

Use `xdg-open` inside a flatpak sandbox. A specific example is explained above.

**Comment by TingPing** [comment]
That is working as intended. From inside the sandbox an application can not see the systems applications and there is also some security risk of being able to just launch any application with any data.

After you select the same application a few times it will stop asking, and there is a command to just tell it to always open the same one that I don't have on-hand.

**Comment by kupiqu** [comment]
> After you select the same application a few times it will stop asking

Indeed! That is all I needed, I guess I gave up too soon :)
