### ISSUE TITLE
Flatpak forum

### ISSUE THREAD

**Issue by roipoussiere** [flatpak/flatpak#3602]
I'm new to Flatpak and considering the potential of the project I'm surprised to note the absence of an official discussion forum.

A discussion forum is good for:
- trust: potential app packagers will be more confident to learn how to create a flatpak if they know that there is a place where they can easily ask questions and find answers.
- mutual assistance: on developing flatpak or other;
- follow flatpaks development: to easily know which flatpak is missing for a famous app, which one is in development, etc;
- suggest flatpaks: for instance via a "wish list" topic, where users can suggest their favorite app and packagers can easily find on which flatpak to work;
- organize: it's a good place to organize events like online hackathon where people are encouraged to create flatpaks during a fixed period;
- suggest or report something: issues centers like here are well designed for developers but may be complicated for end-users, whose are more familiar with online forums;
- communicate: a dedicated topic could be created to spread news such as new releases and eventually let users write comments about them;
- get users opinion about something such as a new feature or something else;
- etc.
- considering these points, get attention of more developers, that will increase the number of flatpak apps.

For instance, [Discourse](https://www.discourse.org/) is user-friendly and might be a good candidate.

**Comment by refi64** [comment]
There's one for Flathub: https://discourse.flathub.org/

**Comment by roipoussiere** [comment]
Thank you. Maybe a link to that forum can be added to the Flatpak documentation?

I know that flatpak and flathub are not the same thing but it's nice to help users to find help. Others forums dedicated to other repos could be added too, if necessary.
