### ISSUE TITLE
Flatpak Vocal showing as 140 TB

### ISSUE THREAD

**Issue by WendyBug** [flatpak/flatpak#3604]
## Steps to reproduce

Looked at downloading the podcasting software Vocal and the first file was showing as 140 TB. I cancelled the download. Is this file size showing in/correctly?

**Comment by alexlarsson** [comment]
Likely yes, there was an unintialized memory bug in the code that calculated the download size, so sometimes it was essentially random. It has since been fixed but there remains old flatpak out there with wrong sizes.
