### ISSUE TITLE
Qemu user support

### ISSUE THREAD

**Issue by marcthe12** [flatpak/flatpak#3605]
## Linux distribution and version
All
## Flatpak version
All
## Description of the problem
Qemu user can run executable of another archiecture/ for example rpi can run wine via qemu user. When combined with binfmt it can run any excutable of any arch.
Flatpak could allow a way to run qemu user in the flatpak if available on the host (I doubt binfmt is namespace ready) on foriegn arch. This could also run flatpak on arch that flathub still does not support for example.

If its possible already could you do this, can it be documented
## Steps to reproduce
None

**Comment by alexlarsson** [comment]
This should already work fine. See eg.e:
http://www.hadess.net/2016/10/flatpak-cross-compilation-support.html

**Comment by marcthe12** [comment]
Hmm I wasn't aware of this change
