### ISSUE TITLE
"upgrade" command: just do what I mean

### ISSUE THREAD

**Issue by nekohayo** [flatpak/flatpak#3607]
Flatpak 1.6.3 on Fedora 32:

```
$ flatpak upgrade
error: 'upgrade' is not a flatpak command. Did you mean 'update'?
```

I keep typing "upgrade" because that's the term APT and DNF use.

In the real world, linguistically, update and upgrade are synonyms (the only exception is APT, but YUM and DNF chose to not make the distinction), even Flatpak itself acknowledges that by suggesting this. So why is it making me waste my time re-typing the command every time? Just consider it as an alias, like DNF does, and silently "do what I mean"—that is, update when I say upgrade.

**Comment by mwleeds** [comment]
Yeah, we already alias `remove` to `uninstall`. We can alias for this too.
