### ISSUE TITLE
"remove" command not specified in man page

### ISSUE THREAD

**Issue by taminaru** [flatpak/flatpak#3611]
I have noticed that the ``man`` page of flatpak does not mention anything about the ``flatpak remove`` alias. Shouldn't this be specified in order to help yum/dnf/apt users even more?

As a sidenote, if [upgrade command alias](https://github.com/flatpak/flatpak/pull/3610) is merged this should also be specified in the ``man`` page.

**Comment by TheEvilSkeleton** [comment]
I'd suggest to add `flatpak upgrade` in the manpage also, if the merge request gets accepted https://github.com/flatpak/flatpak/pull/3610

**Comment by mwleeds** [comment]
I don't see how that's needed. If you're going to look at the man page, you can just use what's there. If you don't look at the man page and use your muscle memory from apt/dnf, it still works.

As far as I can tell apt and dnf don't put aliases in their man pages.
