### ISSUE TITLE
Extension of an extension? (debuginfo)

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak#3614]
Just for clarification, I think it's a known problem, but I couldn't find an older bug report about it:

At the moment it would not be possible, to provide an extension with debug symbols for the Mesa drivers, because they are already in an extension (`org.freedesktop.Platform.GL.default`), correct?

**Comment by nanonyme** [comment]
Does it really need to be per say extension of an extension? Isn't it enough that debuginfo are present and can be mounted somewhere where gdb will know to look for them?

**Comment by eszlari** [comment]
> Isn't it enough that debuginfo are present and can be mounted somewhere where gdb will know to look for them?

And how do you distribute it? This is about providing a convenient way to get debuginfo.

**Comment by nanonyme** [comment]
Isn't it just a regular extension with a name ending with .Debug in that case?

**Comment by eszlari** [comment]
I guess you could create your own debug extension by hand. It would be nice, if this was done automatically for extensions too, like it is for apps/runtimes.

**Comment by nanonyme** [comment]
For Mesa GL extension it's really quite trivial to create debug counterpart. The interesting part is making it work with gdb. It only loads symbols from quite specific locations.

**Comment by alexlarsson** [comment]
There really is not really a physical thing like "an extension". There are only two kind of flatpak refs, "app" and "runtime". All extensions are "runtimes", which just means "things you don't directly run". Then, there is an "extension point" which is configuration in the app or the runtime the app uses, which is a configuration snippet in the metadata that is parsed by flatpak on run and install time to do things like download or mount other runtimes into the app.

The dependency model of flatpak is intentionally limited to avoid it becoming a full packaging system (i.e. the deb resolver can solve sudokus), so no recursion is allowed. Only extension points in the app, or the main runtime specified by the app is considered.  The `org.freedesktop.Platform.GL` extension point is defined by the freedesktop (and derived) runtime, and if you want other extension points like `org.freedesktop.Platform.GLDebug` that can be added in the same location. Then it is up to the runtime to add the path of this to the debug search path, just like its already the case with the regular Sdk debug extension path.

**Comment by nanonyme** [comment]
@alexlarsson are we allowed to call it .debug or will flatpak get in the way?

**Comment by alexlarsson** [comment]
`org.freedesktop.Platform.GL.debug` is a bit iffy, because `org.freedesktop.Platform.GL` is already a subdir=true extension point, which means that the names of the implementers of it is `org.freedesktop.Platform.GL.*`, which conflicts with `org.freedesktop.Platform.GL.debug`.

However, i guess in your case the name would be `org.freedesktop.Platform.GL.mesa.debug` or suchlike, and that won't conflict, so its probably ok.

**Comment by alexlarsson** [comment]
Otoh, maybe you actually want `org.freedesktop.Platform.GL.debug.mesa` so you can use a subdir=true extension point for that too.

I *think* that will work. But better test it

**Comment by nanonyme** [comment]
Yeah, we'll do some testing. The plan is we're going to also be providing mesa-git (through Flathub beta) as an opt-in thing and debug info would be especially nice for that.

**Comment by lw64** [comment]
I also want to split out debug info from a runtime extension. Is there already a working solution I can look at?

**Comment by nanonyme** [comment]
Nope. If you have time to test Alex's suggestion, information would be appreciated.

**Comment by lw64** [comment]
Another question about it:

How would you add the debug extension? Wirh apps you would do it with --devel, but for a custom solution this would not work I guess?

**Comment by lw64** [comment]
> Otoh, maybe you actually want org.freedesktop.Platform.GL.debug.mesa so you can use a subdir=true extension point for that too.

Wouldn't this require another extension point "org.freedesktop.Platform.GL.debug" in the runtime?

Also in my case I have an extension for the extension point "org.freedesktop.Sdk.Extension". Is that different?

**Comment by doraskayo** [comment]
> Otoh, maybe you actually want `org.freedesktop.Platform.GL.debug.mesa` so you can use a subdir=true extension point for that too.
> 
> I _think_ that will work. But better test it

See MR implementing this suggestion here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/13047

**Comment by doraskayo** [comment]
@eszlari, @alexlarsson, `org.freedesktop.Platform.GL.Debug.default` has been released for a few months at this point and allows mounting debug information for `org.freedesktop.Platform.GL.default` in the sandbox.

I think this issue can be closed.
