### ISSUE TITLE
--socket=fallback-x11 has weird dependency on--socket=wayland

### ISSUE THREAD

**Issue by nanonyme** [flatpak/flatpak#3615]
Noticed with Firefox Flatpak that if app has fallback-x11 and no wayland socket, then it will silently get neither when running on Wayland.  Not sure what the best way and level to handle this is.

**Comment by TingPing** [comment]
Sorry but, duh? Fallback x11 means you only get x11 when on x11 not when on wayland. Use the `x11` permission.

**Comment by nanonyme** [comment]
I still think either flatpak or flatpak-builder should give error in this situation. It is clearly broken on Wayland and will be hard to debug for end user.

**Comment by TingPing** [comment]
Its not broken, it does what its documented to do.

*Maybe* a warning is warranted but I don't think its a big deal.
