### ISSUE TITLE
With fractional scaling, applications are blurry only on flatpak

### ISSUE THREAD

**Issue by WhyNotHugo** [flatpak/flatpak#3619]
## Linux distribution and version
```
Linux aphrodite 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux
```

## Flatpak version
```
Flatpak 1.7.2
```
## Description of the problem

Some applications are very blurry when using fractional scaling. However, running the native application is rendered perfectly smooth.

I initially though this was a Flatseal problem (since I noticed the issue with their app), but after some debugging, it happens with other apps too.

Further details on our previous efforts to narrow down the cause here: https://github.com/tchx84/Flatseal/issues/71

## Steps to reproduce

- Enable fractional scaling on your compositor.
- Install flatseal via flatpak
- Run flatseal (it's blurry!)
- [Optional] Build flatseal and run it natively -- no blurriness.

**Comment by TingPing** [comment]
Just to clarify you mean GNOME-Shell's fractional scaling?

**Comment by TingPing** [comment]
Oh you use swaywm. Its possible some settings just aren't getting through that normally GNOME sets and `xdg-desktop-portal-gtk` lets through.

**Comment by WhyNotHugo** [comment]
Uhm, shouldn't those settings be let through?

I'm a bit confused though; isn't the scaling factor a standard setting across compositors? Why do GTK apps pick them up fine when running natively?

**Comment by refi64** [comment]
Isn't this supposed to be part of the xdg-output protocol?

**Comment by TingPing** [comment]
Its very possible but `flatpak` isn't involved in `wayland`. It is however involved in toolkit settings so it might be worth looking into.

**Comment by tobias47n9e** [comment]
Seems to happen with the emulators of Android Studio too. There it is especially noticeable.

**Comment by WhyNotHugo** [comment]
I can't find any application that _doesn't_ fail to scale properly.

> Its possible some settings just aren't getting through that normally GNOME sets and xdg-desktop-portal-gtk lets through.

Still don't really follow here -- I'm not using GNOME. If GNOME needs to set some variable, wouldn't native applications fail to scale too?

**Comment by alexlarsson** [comment]
On X11 the scaling is a bit wonky and something like gnome-settings-daemon need to set the correct xsettings for apps to pick it up. However, for wayland window scale is native and should work automatically.

In fact, I don't know of any way flatpak could affect the handling of scaling on wayland at all (all we do is forward the socket), so I have no idea why it would act differently.

Are you sure the apps are using wayland? Maybe they end up going via Xwayland for some reason?

**Comment by WhyNotHugo** [comment]
@tobias47n9e Sounds like you're running the application via XWayland.

See [these instructions](https://github.com/swaywm/sway/wiki#is-an-application-using-xwayland) to confirm this.

**Comment by WhyNotHugo** [comment]
@alexlarsson Definitely sure they're running on Wayland. The symptoms are the same even if I disable the xorg socket in flatpak and / or kill XWayland. I've also check via `swaymsg -t get_tree`, and sway confirms the app is running via wayland. I've also done the xeyes-test.

**Comment by instagendleg** [comment]
Also experiencing the same issue. Appends on every flatpack applications I install (a dozen). Even the gnome system title bar is blurry.

**Comment by J-email** [comment]
Can confirm this. 

- openSUSE Tumbleweed
- KDE Plasma 5.23.2
- Flatpak 1.12.2

> @tobias47n9e Sounds like you're running the application via XWayland.
> 
> See [these instructions](https://github.com/swaywm/sway/wiki#is-an-application-using-xwayland) to confirm this.

I confirm that all my impacted applications seems to be running on XWayland (Pycharm, Zoom, Ungoogled Chromium, etc.).

**Comment by dqalombardi** [comment]
I'm experiencing this as well. Not sure if it comes across well but the whole app (not just the text ... also including the Gnome header) is much blurrier than the top bar.

![Screenshot from 2023-08-10 09-54-01](https://github.com/flatpak/flatpak/assets/54324552/989b238c-c38a-422d-9de9-dec30cb79f41)

**Setup**
- OS: Fedora Linux 38 (Workstation Edition) x86_64
- Host: Inspiron 14 5425 1.5.0
- Resolution: 1920x1200
- DE: GNOME 44.3 
- WM: Mutter
- Gnome Scaling: 1.5X

**Application**
```
          ID: com.spotify.Client
         Ref: app/com.spotify.Client/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.2.11.916.geb595a67
     License: LicenseRef-proprietary=https://www.spotify.com/us/legal/end-user-agreement/
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 7.5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 7a095d1e1ffc3a1aa42a58579a9a733950c8eac306b1b2cd38495c2811bb4744
      Parent: d12294b12687bd28fc64f1a13149615c8d47ba538d44bb52d641933b89491ccc
     Subject: Update spotify.snap to 1.2.11.916.geb595a67 (b957384d)
        Date: 2023-05-19 19:04:50 +0000
```

**Comment by chrisawi** [comment]
The original screenshot in https://github.com/tchx84/Flatseal/issues/71 appears to be the GTK text antialising issue (https://github.com/flatpak/flatpak/issues/2861), rather than the blurriness that everyone else is talking about.

Xwayland apps being blurry with fractional scaling is not anything flatpak-specific. It's an issue with Xwayland and/or the compositor (e.g. mutter for GNOME). The best workaround is to see if you can make the app use Wayland natively, if possible.

**Comment by WhyNotHugo** [comment]
Yeah, I think that this was a dupe of https://github.com/flatpak/flatpak/issues/2861.
Thanks for the housekeeping.
