### ISSUE TITLE
gnome-keyring portal

### ISSUE THREAD

**Issue by mildred** [flatpak/flatpak#362]
I am packaging electron, based on chromium, that can be compiled against gnome-keyring. I can disable gnome-keyring but I feel this should be made into a portal. I want the applications that I run to be able to store secrets on my keyring while making sure it cannot access secrets from other applications.

**Comment by alexlarsson** [comment]
There has been talk about this, but the current idea is that we should use a different model for storing secrets in the app. Essentially there would be a way for the app to get a per-app "secret" that it can then use to encrypt its own secrets with. Then we could have a library that does the actual encryption or whatnot. But we shouldn't have a single database with the info for all apps.

And anyway, the idea of a per-computer keyring is getting kinda stale in todays multi-device world.

**Comment by matthiasclasen** [comment]
there is an open issue against xdg-desktop-portal for this

**Comment by chpio** [comment]
im having issues with Fractal, which is storing the login data (password & token) in the gnome-keyring, but is not able to access it if the keyring is locked (there is no type-in-the-password-request to unlock the keyring). Is my issue with the keyring in any way related to this problem?

**Comment by TingPing** [comment]
@chpio 	IME the app just needs to explicitly try unlocking it.

**Comment by jcaesar** [comment]
It is [unlocking the password](https://gitlab.gnome.org/GNOME/fractal/-/blob/008e2b3eb8116b962fe99a9f6600296c5c8e6bb9/fractal-gtk/src/passwd.rs#L228), I think. Does it need to unlock the collection, too?
