### ISSUE TITLE
Allow apps to declare subapps dynamically

### ISSUE THREAD

**Issue by Yajo** [flatpak/flatpak#3628]
## Linux distribution and version

Fedora 32 Silverblue

## Flatpak version

Flatpak 1.6.3

## Description of the problem

I use Epiphany's web apps. I cannot use them if installed via flatpak, due to https://gitlab.gnome.org/GNOME/epiphany/commit/77a09886ee78af0bc1adad9c1d8b43b8691f2901 which disables it on purpose because it says this would never work under flatpak.

If that's the case, then IMHO Flatpak is missing this feature.

## Steps to reproduce

Install [Epiphany from Flathub](https://flathub.org/apps/details/org.gnome.Epiphany) and you'll see there's no option to save as a web app in the hamburger menu.

**Comment by TingPing** [comment]
Related https://github.com/flatpak/xdg-desktop-portal/issues/326

**Comment by mwleeds** [comment]
Epiphany now [has](https://gitlab.gnome.org/GNOME/epiphany/-/merge_requests/1067) the ability to install web apps under Flatpak on the development branch, and it will be released in GNOME 43.
