### ISSUE TITLE
Does flatpak’s `merge-dirs` extension option support two extensions writing into the same directory?

### ISSUE THREAD

**Issue by jmaibaum** [flatpak/flatpak#3633]
## Linux distribution and version

Arch Linux, updated on May 24, 2020.

## Flatpak version

    $ flatpak --version
    Flatpak 1.7.2

## Description of the problem

I am currently trying to outsource the KiCad schematic symbols, footprints, and 3D model libraries into flatpak extensions, to reduce the disk footprint of org.kicad_pcb.KiCad (currently ~6.2G installed size, mostly due to the official 3D MCAD models), see https://github.com/flathub/org.kicad_pcb.KiCad/issues/32.

One of the issues seems to be that while each of these different library parts installs stuff into their own directory, there is a special `template` directory, where each of the libraries installs a few library-specific files into, i.e. several extensions try to put files into this directory.

My question is: Is this supported at all, using the `merge-dirs` option when defining the extension point?

#### Directory tree of extension A

```
A/share/kicad/symbols/<lots-of-subdirectories-and-files>
A/share/kicad/template/a-single-symbol-template-file
```

#### Directory tree of extension B
```
B/share/kicad/modules/<lots-of-subdirectories-and-files>
B/share/kicad/template/a-single-footprint-template-file
```

The extenstion definition in the main manifest now defines `"merge-dirs": "share/kicad"` which makes the `symbols` and `footprint` directories show up in the expected place, and with their expected contents. But the `template` dir only contains a single template file (I assume from the extension which happened to be loaded first/last). Is this use-case supported at all?

**Comment by alexlarsson** [comment]
merge-dir is used for things like opengl where the extension has a bunch of private stuff, plus a directory "*.d" style directory with config files like `vulkan/icd.d/nvidia_icd.json`, where the `merge-dirs=vulkan/icd.d` causes all the various modules to be visible. In such a case you need the merged dir to have uniquely named files (just like you would if the file was installed on the host distro in a shared `* *.d*` dir). So, using merge-dir with filenames that are not guaranteed to be uniqe doesn't work.

In the case of the app loading things like this I don't see why you would have to mess around with hacks  like this though? Just make the app itself look for things in all the extensions? Its just an extra for loop.

**Comment by jmaibaum** [comment]
I think that I have now finally wrapped my head around `merge-dirs`. Thanks for clarifying @alexlarsson.
