### ISSUE TITLE
Option to disable xdg-dbus-proxy completely

### ISSUE THREAD

**Issue by gasinvein** [flatpak/flatpak#3636]
Some apps do not use D-Bus at all, even indirectly. In such case, `xdg-dbus-proxy` process spawned by flatpak does nothing but increases startup time (sometimes significantly compared to the app itself).
It would be nice to have an option like `--disable-dbus-proxy`.
This could be especially useful for CLI apps.

**Comment by alexlarsson** [comment]
There is a `flatpak run --no-session-bus` which does this. But i guess you mean something that the app itself specifies rather than the user supplies?

**Comment by gasinvein** [comment]
AFAICT `--no-session-bus` doesn't prevent `xdg-dbus-proxy` from starting:
```
$ flatpak run --command=true -v --no-session-bus com.visualstudio.code-oss
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/gasinvein/.local/share/flatpak
F: Opening user flatpak installation at path /home/gasinvein/.local/share/flatpak
F: Opening user flatpak installation at path /home/gasinvein/.local/share/flatpak
F: Cleaning up unused container id 366214886
F: Allocated instance id 1539714592
F: Add defaults in dir /com/visualstudio/code-oss/
F: Add locks in dir /com/visualstudio/code-oss/
F: Allowing dri access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/gasinvein/.config/pulse/client.conf': Error opening file /home/gasinvein/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 51 xdg-dbus-proxy --args=53'
F: Running 'bwrap --args 51 true'
```

**Comment by alexlarsson** [comment]
Is that the session bus though? Could be the a11y bus? Try `--no-a11y-bus` too.

**Comment by gasinvein** [comment]
Tried that, `--no-a11y-bus` doesn't seem to affect this, too.

**Comment by gasinvein** [comment]
>i guess you mean something that the app itself specifies rather than the user supplies?

Well, if app maintainer could specify such option in metadata - it would be even better.
