### ISSUE TITLE
[Feature Request] Flatpak as Sandbox

### ISSUE THREAD

**Issue by valoq** [flatpak/flatpak#3638]
While flatpak is intended to be an alternative to regular package managers, it also includes an interesting approach to sandboxing desktop applications.

For those that prefer their native package manager however, the attributes as a sandboxing tool are kind of lost as it goes hand in hand with using the flatpak apps.

Compared to other application sandboxing projects such as firejail, flatpak has a way better and safer approach to sandboxing and even without the attributes as an independent package manager it could serve as a valuable sandboxing tool.

Wouldn't it be possible to change flatpak in a way as to leave the user with the choice to use their native packages in combination with the flatpak sandboxing features?

I believe there is an increasing demand for sandboxing such as provided by flatpak, but many users will still want to keep using their native packages or even no package manager at all. It would therefore increase to possible user base of flatpak if it could be used independently of the provided packages to provide sandboxing for their native packages as well.

I would like to know if this is something that would go along with the project.

**Comment by TingPing** [comment]
I don't speak for the project but this should just be a separate tool.

The portability is core to how everything is structured and functions.

The idea of just 'sandboxing' a native package is a much more impossible task than you realize since its arbitrary code loading arbitrary data never designed or tested to be sandboxed.

**Comment by marcthe12** [comment]
Maybe should another issuse for this, but for some api that really only make sense in flatpak or only work in flatpak (flatpak-spawn or background api). This could mean having different codepaths between flatpak and native version which may not be palatable to some(maintenance cost maybe higher).

**Comment by valoq** [comment]
Looking at both the sandbox only projects and flatpak, the areas that need the most works according to the bug reoports seem to be the rulesets for the specific applications.

I think it would be better to combine the efforts to build sandboxing instead of creating yet another project. Even if the sandboxing features is only a small part of flatpak, allowing flatpak to be used as a sandbox without the package would draw additional developers to the project and help with the quality of the sandbox rule sets in flatpak.

I am interested to know if @alexlarsson thinks this could be a viable path for the future development of flatpak.

**Comment by sudo-give-me-coffee** [comment]
Now available, the sandbox is separate from the flatpak. It's called BubbleWrap, the binary is bwrap:

https://github.com/containers/bubblewrap

**Comment by TingPing** [comment]
The "sandbox" has 3 components: `bubblewrap`, `xdg-desktop-portal`, and `xdg-dbus-proxy`. All can certainly be used externally for example `WebKitGTK` does. It would require a relatively small program to do the same maybe providing 'rules' for native applications.

**Comment by alexlarsson** [comment]
I have no interest in making flatpak some generic mechanism to sandbox other kinds of apps, there are many details in the implementation of flatpak that intermix in complex ways will which make this a lot of work with zero gain for flatpak. However, much of the required tools to do such sandboxing (bwrap, etc) is extracted like @TingPing said, so anyone who wants to can do this.
