### ISSUE TITLE
L4T Ubuntu - can't launch flatpak softwares

### ISSUE THREAD

**Issue by FellFromTheSky** [flatpak/flatpak#3642]
## Linux distribution and version
L4T Ubuntu 3.0.0 full : 
https://gbatemp.net/threads/l4t-ubuntu-a-fully-featured-linux-on-your-switch.537301/
In fact, it's an aarch64 port of Ubuntu 18.04 for the Nintendo Switch.
## Flatpak version
Flatpak 1.7.2
## Description of the problem
This error message :
> bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
> error: ldconfig failed, exit status 256

As you can read, one of the authors of  the distro just said me that he doesn't care about fixing flatpak :
> @FellFromTheSky flatpack doesn't work.... Havnt tried to fix it, mainly because I dont care to, it isn't a priority, and I am more invested in developing other distros for the switch.... Also all Linux distros have a kernel..... As for ldconfig, that requires root access, as it adds/deletes libraries from the linker db.

So how to fix the problem?

## Steps to reproduce
Try to run Gimp from terminal trough flatpak run org.gimp.GIMP//stable
or from Ubuntu Unity launcher.

**Comment by TingPing** [comment]
Where did you get the `flatpak` package?

**Comment by FellFromTheSky** [comment]
I installed Flatpak trough [Flatpak PPA](https://flatpak.org/setup/Ubuntu/) for Ubuntu, the distro is only providing normal Ubuntu packages in APT.

When I try to run this command :
sysctl kernel.unprivileged_userns_clone=1
I'm getting this error message :
sysctl: can't get stat from /proc/sys/kernel/unprivileged_userns_clone: No file or folder of this type

**Comment by FellFromTheSky** [comment]
@TingPing 
Could I bypass suid permissions?
Or is there any other way to make Flatpak work?

**Comment by TingPing** [comment]
`sudo chmod u+s /usr/bin/bwrap`

**Comment by FellFromTheSky** [comment]
It still didn't worked, even with "sudo chmod u+s /usr/bin/bwrap" :
flatpak run org.gimp.GIMP//stable 
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
error: ldconfig failed, exit status 256

**Comment by FellFromTheSky** [comment]
Why not just make Flatpak use group system like SDKMAN does?

**Comment by FellFromTheSky** [comment]
I don't know what fixed it but it must be a combination of those commands :
# echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/00-local-userns.conf
# sudo chmod u+s /usr/bin/bwrap
# service procps restart
