### ISSUE TITLE
flatpak run app fails on ChromeOS 83 with bwrap error message

### ISSUE THREAD

**Issue by lwbt** [flatpak/flatpak#3644]
## Linux distribution and version

Ubuntu 20.04 in Crostini on Chrome OS

## Flatpak version

Flatpak 1.7.2

## Description of the problem

After upgrading Chrome OS to version 83 my flatpak apps won't launch anymore. Everything has been fine before the upgrade from 81 to 83 (stable). I tried looking for possible solutions and trying to understand what the issue is with bubblewarp, but I all the reports and wiki articles, like on Arch Linux Wiki, I can find lack instructions how to troubleshoot this problem. If it's a bug in Chrome OS and I can prove it, then I'll report it there. I have yet to read the entire Flatpak documentation (when I have time to finish that), but so far I could not find anything about bwrap. :(

## Steps to reproduce

- Have a device with Chrome OS
- Update it to Chrome OS version 83
- Enable Linux Apps
- (Install Ubuntu instead of Debian as the container OS https://www.reddit.com/r/Crostini/wiki/howto/run-ubuntu)
- Install flatpak
- Install a flatpak app, like Lollypop (my example and usecase), or Gedit, or Firefox (https://www.reddit.com/r/Crostini/comments/gfi45d/flatpak_broken_on_m83beta_830410342/)
- Try to run the app:
   ```
  flatpak run org.gnome.Lollypop
  bwrap: Can't mount proc on /newroot/proc: Operation not permitted
  ```

**Comment by alexlarsson** [comment]
This is bubblewrap trying to mount procfs inside the container, and the kernel returning EPERM. I have no idea why this happens, but we do need that to be possible.

I wonder if it is caused by selinux or similar level of protection in chromeos?

**Comment by lwbt** [comment]
Sorry for the late reply. I finally found some time today to first learn more about the Chromebook Linux Apps environment and how to setup and test different releases, to then reduce the burden of verifying that an issue is reproducible.

# Fix
Run the following command to resolve the issue for the `penguin` container.
```bash
(termina) chronos@localhost ~ $ lxc config set penguin security.nesting true
```

Related bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1087937

**Comment by eevleevs** [comment]
For others not familiar where to put the command above, hit `ctrl+alt+T` on the browser, then give `vsh termina`.

**Comment by Gibberditoslumber** [comment]
use Xorg and sudo -i then the program you want to run my exampal ; xhost -si:localuser:root ; sudo -i flatpak run org.srb2.SRB2
