### ISSUE TITLE
Delay of several seconds when starting flatpak apps

### ISSUE THREAD

**Issue by elya5** [flatpak/flatpak#3648]
## Linux distribution and version
Fedora 32 running GNOME 3.36.2
## Flatpak version
1.6.3
## Description of the problem
When I start a flatpak application, there is a 5-10 second delay until the application actually shows up. It's reproducible with every flatpak application I have installed.  Sometimes gnome-shell freezes for several seconds as well.

```
> flatpak run -vv org.gnome.Evince
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Cleaning up unused container id 1879793369
F: Allocated instance id 3673961184
F: Add values in dir '/org/gnome/evince/', prefix is '/org/gnome/Evince/'
F: Add defaults in dir /org/gnome/Evince/
F: Add locks in dir /org/gnome/Evince/
F: writing D-Conf values to /home/user/.var/app/org.gnome.Evince/config/glib-2.0/settings/keyfile
F: Disallowing network access
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
...
```
The delay happens after the "writing D-Conf values" output.

## Steps to reproduce
Start the application.  It does not matter whether the application is started via the commandline or by clicking on it in the gnome-shell

**Comment by LinuxOnTheDesktop** [comment]
If I may piggyback on this report . .

On Mint 19.3 x64 Cinnamon, and on two separate computers (one a quad-core with an nvme drive and 16GB RAM), the 'fwupd' flatpak always takes some _thirty seconds_ to start in a terminal, even if told merely to display its help text. I reported the issue against fwupd but someone [there](https://github.com/fwupd/fwupd/issues/2156#issuecomment-637705296) suggested that I report it on this repo. My version of flatpak itself: 1.0.9-0ubuntu0.1.

**Comment by elya5** [comment]
> If I may piggyback on this report . .
> 
> On Mint 19.3 x64 Cinnamon, and on two separate computers (one a quad-core i7 and a nvme drive and 16GB RAM), the 'fwupd' flatpak always takes some _thirty seconds_ to start in a terminal, even if told merely to display its help text. I reported the issue against fwupd but someone [there](https://github.com/fwupd/fwupd/issues/2156#issuecomment-637705296) suggested that I report it on this repo. My version of flatpak itself: 1.0.9-0ubuntu0.1.

I think that's probably a different issue

**Comment by elya5** [comment]
I found the problem (by accident). xdg-document-portal wasn't working (similar to #1359).

Running `systemctl status --user xdg-document-portal` showed the error message `xdg-document-portal[7333]: error: Failed to load db from '/home/elias/.local/share/flatpak/db/documents': invalid gvdb header` and simply deleting that file solved the problem for me.
