### ISSUE TITLE
/etc/profile.d/flatpak is not sh-compatible:

### ISSUE THREAD

**Issue by jeeger** [flatpak/flatpak#3649]
## Linux distribution and version
Gentoo, package 1.4.4 from flatpak-overlay 
## Flatpak version
Flatpak 1.4.4
## Description of the problem
When running Bash, it will try and source the profile script in /etc/profile.d/flatpak.sh. However, Bash will also do this when running in POSIX mode, and will not support some language constructs. This means that it's not able to source the flatpak profile script.

Bash version is 5.0.17(1).

## Steps to reproduce
sh /etc/profile.d/flatpak.sh

Expected: Nothing, XDG_DATA_DIRS is updated.
Actual: 
```
/etc/profile.d/flatpak.sh: line 16: syntax error near unexpected token `;;'
/etc/profile.d/flatpak.sh: line 16: `                    *":$share_path/:"*) :;;'
```

**Comment by refi64** [comment]
On Bash 5.0.11 and Flatpak 1.6.3, I can't seem to reproduce this, whether I run:

```
$ sh --posix /etc/profile.d/flatpak.sh
$ sh /etc/profile.d/flatpak.sh
$ bash --posix /etc/profile.d/flatpak.sh
```

(and yes, sh is a symlink to bash)

**Comment by jeeger** [comment]
Ah, I'll try and update. Thanks!

**Comment by jeeger** [comment]
Update corrected the error.
