### ISSUE TITLE
Says the signature is BAD and I'm unable to install anything.

### ISSUE THREAD

**Issue by Scupake** [flatpak/flatpak#3657]
## Linux distribution and version
Debian Bullseye (Debian Testing)
## Flatpak version
1.6.3-1
## Description of the problem
this 
```
error: Failed to install org.freedesktop.Platform: Signature made Thu 01 Jan 1970 12:00:00 AM +00 using [unknown name] key ID 562702E9E3ED7EE8
BAD signature from "Flathub Repo Signing Key <flathub@flathub.org>"
Primary key ID 4184DD4D907A7CAE
Primary key expires Mon 14 Jun 2027 02:18:56 PM +01
```

## Steps to reproduce
I installed Firefox, after that I get that error everytime  I try to install something even Firefox.
I have no idea what would've cause the to "glitch out".

**Comment by Scupake** [comment]
NVM, just decided to fix itself!

**Comment by cobratbq** [comment]
I had the same issue, but it is gone now. I had not installed anything new, but did try to update. (`flatpak update`).
`flatpak --version`: `Flatpak 1.6.3`

Seemed like an issue of bad data on the server. Maybe files updated in the wrong order.

**Comment by ardevd** [comment]
I'm still getting this error.
