### ISSUE TITLE
Apps don't show on menu, only can run by command

### ISSUE THREAD

**Issue by hrqmonteiro** [flatpak/flatpak#3658]
## Linux distribution and version
Void Linux rolling-release
## Flatpak version
Flatpak 1.6.3
## Description of the problem
Apps don't run through the menu, neither .desktop files can be acessed through PATH
## Steps to reproduce
I just can't open the apps through menu, just typing the command for each one

**Comment by alexlarsson** [comment]
This is a distro packaging issue, the XDG_DATA_DIRS env var must contain ~/.local/share/flatpak/exports/share and /var/lib/flatpak/exports/share. There are severeal snippets shipped with flatpak to allow this (for example a gdm config file and a systemd user env generator.

However, it may also be that your distro correctly ships these and you need to log out and then in again to pick them up.
