### ISSUE TITLE
Warnings during checkout when .gitmodules doesn't exist

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#366]
When building gnome-games nightly, I get:

```
Fetching git repo https://github.com/libretro/bsnes-libretro.git
fatal: Path '.gitmodules' does not exist in 'df18e30ff7fc7c9db643b14bf9526e8874c21ab6'
Fetching git repo https://github.com/libretro/gambatte-libretro.git
fatal: Path '.gitmodules' does not exist in '3e8d200624e6153455317d6d2d29b3fe2c088b82'
Fetching git repo https://github.com/libretro/pcsx_rearmed
Fetching git repo git://notaz.gp2x.de/~notaz/libpicofe.git
fatal: Path '.gitmodules' does not exist in '21604a047941b8fe81d381ede0371c75da964afd'
Fetching git repo git://notaz.gp2x.de/~notaz/warm.git
fatal: Path '.gitmodules' does not exist in 'a6f015da3b10b82a476250793645c071340decbc'
Fetching git repo https://git.gnome.org/browse/retro-gtk
fatal: Path '.gitmodules' does not exist in 'e8ab44d280b21e6682974fbf71e4a0fa1e173161'
Fetching git repo https://git.gnome.org/browse/grilo
fatal: Path '.gitmodules' does not exist in 'd04576a9530995277b0ac23e2afddac05203c802'
Fetching git repo https://git.gnome.org/browse/grilo-plugins
fatal: Path '.gitmodules' does not exist in 'fb45b333607ad1c3c5ba68273c4c0a8778417660'
```

Obviously, those are fatal warnings to the stand-alone git command that was run, not to flatpak-builder, but it would be nicer if the command didn't run if the file didn't exist. See #216 

CC @bochecha

**Comment by bochecha** [comment]
Yeah, that started when I redid the submodule handling back at GUADEC.

I agree it's not pretty, but I haven't found any way to tell git not to print these. As far as I know we'd need to suppress completely stderr from the `git` command, and I'm not sure that's a good idea.

**Comment by hadess** [comment]
What's the command that generates this warning?

**Comment by bochecha** [comment]
If I recall correctly it's the `git show $revision:.gitmodules` one:

https://github.com/flatpak/flatpak/blob/master/builder/builder-source-git.c#L285
https://github.com/flatpak/flatpak/blob/master/builder/builder-source-git.c#L421

**Comment by mwleeds** [comment]
We could suppress output just from this `git-show` command, but we'd have to add a parameter to `flatpak_spawnv` for `GSubprocessFlags` and call that directly rather than going through `git()`. Would such a patch be welcome?

**Comment by alexlarsson** [comment]
@mwleeds Yeah, that would be nice.

**Comment by bochecha** [comment]
Wouldn't that suppress other errors, which could be important?

The reason I didn't do it in the first place is that I'm not sure what other error messages `git show` might print.

**Comment by hadess** [comment]
I don't understand why we'd run those 2 commands if `.gitmodules` doesn't exist.

**Comment by bochecha** [comment]
We're not in a checkout dir, so we can't just list the files, we need to ask git to give us the content of the `.gitmodules` blob in the `master` tree.

Running `git show` gives you the contents of this blob if it exists, but until you've run it you don't know whether `.gitmodules` exists.

Unless you know of another way? :)

**Comment by mgautierfr** [comment]
I see two ways to check that .submodule file is existing or not :
- Use `git rev-parse --verify --quiet master:.submodule` and check return code (or check output of the command who is the sha of the blob if present)
- Print the content of the root dir with `git show master:./` and check that `.gitsubmodule` is present.
