### ISSUE TITLE
(document portal?) "/run/user/1000/doc" cluttered with a lot of impossible to remove folders

### ISSUE THREAD

**Issue by felipehw** [flatpak/flatpak#3660]
## Linux distribution and version

`Fedora 32.20200605.0 (Silverblue)`

## Flatpak version

`Flatpak 1.6.3`

## Description of the problem

I'm trying to understand what is happening.

I look at `/run/user/1000/doc/` and this dir has some exported files that I use with Flatpaks but a lot of empty dirs.

I can remove the exported files with `flatpak document-unexport`, but the empty dirs I couldn't.
I couldn't remove these empty dirs with `flatpak document-unexport` neither with `rm`.
But these empty dirs have their names listed with `flatpak documents` and some of them are listed in `/run/user/1000/doc/by-app/` for apps that I removed a long time ago.

How can I remove these dirs (and, I suppose, these "phantom" exported documents)? Seems like zombie/phantom *documents*.

- Example of impossible to remove folder:
```
$ flatpak documents
ID
1c8750eb
(...)
6967a5e4
(...)
d6f10499
$ flatpak document-unexport /run/user/1000/doc/6967a5e4
Not exported
$ flatpak document-unexport /run/user/1000/doc/d6f10499
error: Invalid fd passed
```

- Long time removed app with impossible to remove empty dir:
```
$ ls /run/user/1000/doc/by-app/io.github.celluloid_player.Celluloid/6967a5e4/
```

**Comment by felipehw** [comment]
**Solution:** Just remove `~/.local/share/flatpak/db` and restart. The system will recreate `~/.local/share/flatpak/db` and start to populate `/run/user/1000/doc/` on the go, again, as *document portal* demands go on.
	- **Beware** this will make some Flatpak apps "forget" the last opened file and other minor annoyances (e.g.: *Password Safe* will forget his vault, *Foliate* the actual file opened). If you wanna be cautious, make a backup from `~/.local/share/flatpak/db` before.

[Thanks to](https://github.com/flathub/com.borgbase.Vorta/issues/23#issuecomment-640239989) @Erick555

**Comment by juanje** [comment]
I was checking this issue (the `df: /run/user/1000/doc: Operation not permitted` error, which still happens in Slibervlue) and I saw this **SELinux** labels at the `/run/user/1000/` directory. I think that the problem comes from here: 
```
[juanje@xps ~]$ ls -1Z /run/user/1000/
   unconfined_u:object_r:user_tmp_t:s0 app
   unconfined_u:object_r:user_tmp_t:s0 bus
   unconfined_u:object_r:user_tmp_t:s0 containers
   unconfined_u:object_r:user_tmp_t:s0 crun
   unconfined_u:object_r:config_home_t:s0 dconf
         system_u:object_r:fusefs_t:s0 doc
   unconfined_u:object_r:user_tmp_t:s0 gdm
   unconfined_u:object_r:user_tmp_t:s0 gnome-session-leader-fifo
   unconfined_u:object_r:user_tmp_t:s0 gnome-shell
   unconfined_u:object_r:user_tmp_t:s0 gnupg
         system_u:object_r:fusefs_t:s0 gvfs
   unconfined_u:object_r:user_tmp_t:s0 ICEauthority
       system_u:object_r:user_tmp_t:s0 inaccessible
   unconfined_u:object_r:user_tmp_t:s0 keyring
   unconfined_u:object_r:user_tmp_t:s0 libpod
   unconfined_u:object_r:user_tmp_t:s0 netns
   unconfined_u:object_r:user_tmp_t:s0 pipewire-0
   unconfined_u:object_r:user_tmp_t:s0 pipewire-0.lock
   unconfined_u:object_r:user_tmp_t:s0 pulse
   unconfined_u:object_r:user_tmp_t:s0 systemd
   unconfined_u:object_r:user_tmp_t:s0 toolbox
   unconfined_u:object_r:user_tmp_t:s0 webkitgtk
```

Removing the local directory might resolve temporarily the problem, but it doesn't look like a solution to me. It feels like **Flatpak** should use the right labels or do something about it.
Maybe this has nothing to do with it, but manually remove a directory and restart doesn't seem like the expected behavior. I think it's a bug.

**Comment by Erick555** [comment]
What's the actual problem? Warning message in df? You can safely ignore it. You don't have to remove anything.

**Comment by Erick555** [comment]
What happens here is that `df` tries to use `statfs` call on all mountpoints but that's being denied in default config for `fuse` filesystems which is what `/run/user/1000/` is. There is no bug here, just things working as expected. If you desperately want to get rid of _Operation not permitted_ message then run `df` as root, i.e. `sudo df` however I don't see the point of this.

**Comment by ryan-beisner** [comment]
This is impactful to anything that expects ```df``` to exit 0 as a non-root user.

```
me@here:~$ df -h
df: /run/user/1000/doc: Operation not permitted
Filesystem                 Size  Used Avail Use% Mounted on
tmpfs                      3.1G  4.6M  3.1G   1% /run
/dev/mapper/vgubuntu-root  914G  184G  684G  22% /
tmpfs                       16G  810M   15G   6% /dev/shm
tmpfs                      5.0M  4.0K  5.0M   1% /run/lock
tmpfs                      4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/nvme0n1p2             705M  218M  436M  34% /boot
/dev/nvme0n1p1             511M  7.8M  504M   2% /boot/efi
tmpfs                      3.1G  192K  3.1G   1% /run/user/1000
me@here:~$ echo $?
1

me@here:~$ sudo df -h
Filesystem                 Size  Used Avail Use% Mounted on
tmpfs                      3.1G  4.6M  3.1G   1% /run
/dev/mapper/vgubuntu-root  914G  184G  684G  22% /
tmpfs                       16G  808M   15G   6% /dev/shm
tmpfs                      5.0M  4.0K  5.0M   1% /run/lock
tmpfs                      4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/nvme0n1p2             705M  218M  436M  34% /boot
/dev/nvme0n1p1             511M  7.8M  504M   2% /boot/efi
tmpfs                      3.1G  192K  3.1G   1% /run/user/1000
me@here:~$ echo $?
0

me@here:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
me@here:~$ uname -a
Linux p100 5.8.0-32-generic #34-Ubuntu SMP Fri Nov 27 15:10:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by original-birdman** [comment]
Not sure what this has to do with flatpak.

I'm on Kubuntu 20.10 and do not have flatpak installed, but I am _also_ getting this warning (and warnings should NOT be treated as normal).

This appears to be an `xdg-desktop-portal` issue (as that is what sets this up).

https://github.com/flatpak/xdg-desktop-portal/issues/512

It seems that no-one wants to accept responsibility for the problem.
