### ISSUE TITLE
Apps that follow Elementary OS guidelines clash with flatpaks

### ISSUE THREAD

**Issue by sandorex** [flatpak/flatpak#3667]
##  Description of the problem
Elementary OS guidelines require apps to be named using the scheme like flatpak (`com.x.y.z`), and because the desktop file is named same in both flatpak and regular package one of the desktop files is not shown (depends on installation order)

## Steps to reproduce
- Install an elementary app using the package manager (for example lets use [minder](https://github.com/phase1geo/Minder/issues/147))
- Install the same app using flatpak ([minder flatpak](https://flathub.org/apps/details/com.github.phase1geo.minder))

Now only one version will be shown in apps

---

I understand that this not flatpak's fault, but i think in terms of overall user experience it should be looked into

**Comment by TingPing** [comment]
Thats how its expected to work.

**Comment by sandorex** [comment]
@TingPing But they you cannot install it alongside one another, isnt flatpak supposed to not clash with the system

**Comment by TingPing** [comment]
It doesn't clash in that there is no actual conflicts. However that doesn't mean a desktop file won't overlap in name.
