### ISSUE TITLE
Explain how to use under jhbuild

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#367]
flatpak master currently uses an unreleased ostree, which means it's a better idea than ever to run a locally compiled version in a separate tree.

However, because of the integration with polkit and d-bus activation, it means that the system version will often be activated instead of the jhbuilt one.

```
$ jhbuild run flatpak remote-add --gpg-import=gnome-sdk.gpg gnome https://sdk.gnome.org/repo/
<password prompt>
$ jhbuild run flatpak remote-add --gpg-import=gnome-sdk.gpg gnome-apps https://sdk.gnome.org/repo-apps/
<password prompt>
$ jhbuild run flatpak install gnome org.gnome.Platform 3.20
error: Remote "gnome" not found
```

Building with `--disable-system-helper` doesn't help either, as flatpak helpers for the session and system are still running.

It would be nice to be able to install "system-wide" in the jhbuild install tree, without disturbing the system installation, so that new features can be tested, especially the ones related to building flatpaks.

**Comment by alexlarsson** [comment]
--disable-system-helper now makes it not use another system-helper either.
