### ISSUE TITLE
Snaps disappear due to redefinition of XDG_DATA_DIRS

### ISSUE THREAD

**Issue by ruanformigoni** [flatpak/flatpak#3678]
## Linux distribution and version
OS: Ubuntu 20.04 LTS x86_64 
Host: 81V7 Lenovo IdeaPad S145-15API 
Kernel: 5.4.0-37-generic 
Uptime: 3 mins 
Packages: 2613 (dpkg), 5 (flatpak), 22 (snap) 
Shell: fish 3.1.0 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Yaru-dark 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: x-terminal-emul 
CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
GPU: AMD ATI 03:00.0 Picasso 
Memory: 1706MiB / 5882MiB 
## Flatpak version
Flatpak 1.6.3
## Description of the problem
Snaps disappear after instalation of flatpak and gnome-software-plugin-flatpak
## Steps to reproduce
Follow the steps in https://flatpak.org/setup/Ubuntu/
## Pull request
The error is in the file `/usr/share/gdm/env.d/flatpak.env`
I submmited a pull request #3679 to change `flatpak.env.in`, I do not know if the file `60-flatpak` also needs to be changed.

**Comment by alexlarsson** [comment]
Should be fixed by #3693
