### ISSUE TITLE
I cant edit Linear gradient colort in Inskscape 1.0

### ISSUE THREAD

**Issue by morfyum** [flatpak/flatpak#3682]
IU/UX usability issue!!!

## Linux distribution and version
Fedora 32 - Flatpak Inskcape v1.0

I dont know, I do not found or immposible to edit linear-gradient tool colors...
What I try:
 - Secelct on top menu, and edit selection color 
 - Navigate to right "Fill" menu, and go "Linear Gradient" menu, and add, or modify colors, but I cant.
    > Double click open nothing on actual color
    > "Create a duplicate gradient" option is add new option, but if i click anywhere, this new gradient is disappear.

I Dont Understand! Yt tutorial show on windows version: Top menu button to select gradient colors. I have no this option. The video: https://www.youtube.com/watch?v=1sV3rBb-Was
I cant understand this description: https://inkscape-manuals.readthedocs.io/en/latest/creating-gradients.html

Please, be clearer this option. <3

**Comment by hadess** [comment]
This is where the Inkscape Flatpak bug reports should go:
https://github.com/flathub/org.inkscape.Inkscape/issues
but it looks like a more generic Inkscape issue:
https://inkscape.org/contribute/report-bugs/
