### ISSUE TITLE
android studio stops on 19.5mb

### ISSUE THREAD

**Issue by HexaOneOfficial** [flatpak/flatpak#3683]
system info:
os     Manjaro Linux
kernel 5.7.0-3-MANJARO
memory 1834M / 11898M

when i try to download android studio from this command flatpak install flathub com.google.AndroidStudio 
it hangs on 19.5mb / 928,5 mb:

Looking for matches…

com.google.AndroidStudio permissions:
    ipc                   network               pulseaudio       ssh-auth
    wayland               x11                   devices          multiarch
    file access [1]       dbus access [2]

    [1] host, xdg-run/keyring
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications,
        org.freedesktop.secrets

        ID                         Branch   Op   Remote   Download
 1. [—] com.google.AndroidStudio   stable   i    flathub  19,5 MB / 928,5 MB

Installing… █▊                     9%  1,6 MB/s  02:01%      

when you restart the terminal it still happens

**Comment by barthalion** [comment]
You can try to pass `OSTREE_DEBUG_HTTP` to `flatpak` to see what requests are being sent.

**Comment by HexaOneOfficial** [comment]
details of where it stopped

        ID                         Branch   Op   Remote   Download
 1. [\] com.google.AndroidStudio   stable   i    flathub  19,5 MB / 928,5 MB

Installing… █▊                     9%  1,2 MB/s  02:41> GET /dl/android/studio/ide-zips/4.0.0.16/android-studio-ide-193.6514223-linux.tar.gz HTTP/1.1
> Soup-Debug-Timestamp: 1592204691
> Soup-Debug: SoupSession 1 (0x55efc4d25100), SoupMessage 1 (0x55efc4d12d80), SoupSocket 1 (0x7fd7706425d0)
> Host: dl.google.com
> User-Agent: Flatpak 1.7.2
> Connection: Keep-Alive

**Comment by barthalion** [comment]
That may be an issue with reporting extra-data download progress. You can also check whether `https://dl.google.com/dl/android/studio/ide-zips/4.0.0.16/android-studio-ide-193.6514223-linux.tar.gz` downloads fine for you. If it's a problem with Google's servers, you should contact them instead.

**Comment by HexaOneOfficial** [comment]
sure thanks for your time
