### ISSUE TITLE
[Question] Does Flatpak support sandbox of X11 ?

### ISSUE THREAD

**Issue by Nokia808** [flatpak/flatpak#3684]
## Linux distribution and version
Fedora 32 X64 bit Cinnamon edition
## Flatpak version
1.6.3

Dears I would like to ask if, currently, flatpak has ability to sandbox X11 like Firejail already do, or not?
Firejail has ability to sandbox X11 via xpra / xephyr - see:
https://firejail.wordpress.com/documentation-2/x11-guide/

If yes, kindly give me the command for this.

**Comment by TingPing** [comment]
No, direct X11 access is granted.

**Comment by youdontneedtoknow22** [comment]
> 
> 
> No, direct X11 access is granted.
> 
> As of now its never been planned with the recommendation of using Wayland when possible.

I'm probably too late, but why not?
Ubuntu-based distros (most used linux distros) still don't use wayland as default. Even fedora started using it up Fedora 34, not before.

**Comment by TingPing** [comment]
Fedora has been using it for many years and its been the default in GNOME for many years. I believe its a single package away in Ubuntu.

Anyway the reason is that sandboxing x11 well is a more difficult problem with more risks. Wayland is meant to expose less and that work didn't need to be done.
