### ISSUE TITLE
EOL message: Which application?

### ISSUE THREAD

**Issue by langdon** [flatpak/flatpak#3687]
## Linux distribution and version
f32 silverblue (32.20200615.0)
## Flatpak version
Flatpak 1.6.3
## Description of the problem

This may seem similar to #3485 and #353. However, I wanted to point out that the EOL message also doesn't seem to tell you *which* application developer to contact. In other words, I get:

```
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
```

But, unless the Platform and Locale themselves are the problem, it doesn't tell me which applications are relying on them to file a bug with the application. If they are actually the problem, this phrasing is super confusing (and should probably just be buried). 

In a perfect world, I would get some nice output that included application name, author, and link to where to file a bug.

**Comment by mwleeds** [comment]
Yeah, we could pretty easily say which applications depend on it. To get the developer name and bug report URL we'd have to refer to the appstream data.

**Comment by mwleeds** [comment]
Let's keep #3531 open instead of this one.
