### ISSUE TITLE
Is there a way to disable GPG verification when installing from a .flatpakref file?

### ISSUE THREAD

**Issue by craigbarnes** [flatpak/flatpak#369]
For convenience, I've been using the `--no-gpg-verify` flag of `flatpak remote-add`. I find having the option to *not* sign repo commits very useful, since it saves me having to enter my Yubikey PIN twice per `flatpak build-export` command.

However, I've just started testing the installation of an app from a `.flatpakref` file, which seems to combine `flatpak remote-add` and `flatpak install` into a single command. Unfortunately, it doesn't seem possible to pass the `--no-gpg-verify` flag to the `remote-add` part of the process and there seems to be no documented way to disable GPG verification from within the `.flatpakref` file itself.

Have I overlooked something? Is the any way to modify the command `flatpak --user install --from example.flatpakref` or the file itself in a way that will disable GPG verification? If not, does it seem like a reasonable feature request or should I just keep doing `flatpak remote-add` and `flatpak install` as separate steps?

**Comment by alexlarsson** [comment]
Hmm, I think you should be able to leave out the gpg key element in the flatpakref and then use --no-gpg-verify --from.  I agree that this is a bit weird though, we should support overriding this from the config file.
