### ISSUE TITLE
Hyphens in application IDs (again)

### ISSUE THREAD

**Issue by fmuellner** [flatpak/flatpak#370]
Flatpak now allows for hyphens in application IDs, but only in the last component. This restriction is a bit too tight at the moment, as it allows "com.example.Some-Application", but not "com.example.Some-Application.Locale" or "com.example.Some-Application.Debug" ...

**Comment by alexlarsson** [comment]
Its hard to change this (see previous iterations), but there really is no reason for the locale and debug extensions to perfectly match the app id. We could just rename them to com.example.Some_Application.Locale

**Comment by hanaral** [comment]
@alexlarsson Is there a real reason this isn't possible? There are large amounts of GitHub users who have hyphens in their names, elementary AppCenter will be hit hard by this since it's integrated with GitHub ([there is already an example here](https://github.com/dr-Styki/ScreenRec/issues/34))

**Comment by hadess** [comment]
Don't comment on 5-year old (!) closed (!) issues.
