### ISSUE TITLE
Potential threading issue

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#3701]
## Linux distribution and version
Fedora 32

## Description of the problem
This was originally reported in Discover, it felt like it could be useful for you to have it.
https://bugs.kde.org/show_bug.cgi?id=422983

As you can see on the backtrace, I'm calling flatpak_installation_update_appstream_full_sync from two different threads and it seems to clash somewhere in curl.

I'm guessing this would be solved by calling them sequentially but shouldn't this work anyway?

**Comment by alexlarsson** [comment]
It looks like its crashing with two parallel calls to curl_multi_init() in ostree. Curl claims to be threadsafe, and we're not reusing any curl objects between different threads. 

The actual crash seems to be in openssl, but  according to https://curl.haxx.se/libcurl/c/threadsafe.html it should be fine with openssl >= 1.1.0, and the report has fedora 32 which is openssl 1.1.1g.

@cgwalters Do you have any idea about this?

**Comment by alexlarsson** [comment]
@aleixpol And yes, libflatpak *should* be fully threadsafe.

**Comment by mcrha** [comment]
I see something similar with flatpak-1.13.3-5 under Fedora 37, the gnome-software receives weird bugs about memory corruption:
https://bugzilla.redhat.com/show_bug.cgi?id=2118145
https://bugzilla.redhat.com/show_bug.cgi?id=2118402

I ran it under valgrind and it shows, when installing a Flatpak app, something like this (I've got also invalid read/write in one run, where the write is a bigger problem):
```
==9745== Thread 5 pool-org.gnome.:
==9745== Invalid free() / delete / delete[] / realloc()
==9745==    at 0x48450E4: free (vg_replace_malloc.c:872)
==9745==    by 0x4C4D7DC: g_free (in /usr/lib64/libglib-2.0.so.0.7302.0)
==9745==    by 0x1E98D190: check_header (flatpak-utils-http.c:275)
==9745==    by 0x1E98D277: _header_cb.lto_priv.0 (flatpak-utils-http.c:295)
==9745==    by 0x5C77719: ??? (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C86E5F: ??? (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C6FA86: ??? (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C7245D: curl_multi_perform (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C4754A: curl_easy_perform (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x1E98DD96: flatpak_download_http_uri_once.lto_priv.0 (flatpak-utils-http.c:507)
==9745==    by 0x1E9BE30C: flatpak_load_uri_full.constprop.0 (flatpak-utils-http.c:957)
==9745==    by 0x1E9B07D3: UnknownInlinedFun (flatpak-utils-http.c:997)
==9745==    by 0x1E9B07D3: UnknownInlinedFun (flatpak-dir.c:12172)
==9745==    by 0x1E9B07D3: _flatpak_dir_get_remote_state.constprop.0 (flatpak-dir.c:12522)
==9745==  Address 0xab1 is not stack'd, malloc'd or (recently) free'd
==9745==
==9745== Invalid write of size 2
==9745==    at 0x484C413: memmove (vg_replace_strmem.c:1385)
==9745==    by 0x4C6B1F5: g_string_insert_len (in /usr/lib64/libglib-2.0.so.0.7302.0)
==9745==    by 0x1E98D2CC: _write_cb.lto_priv.0 (flatpak-utils-http.c:340)
==9745==    by 0x5C775FC: ??? (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C358CD: ??? (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C87B10: ??? (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C6FA86: ??? (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C7245D: curl_multi_perform (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x5C4754A: curl_easy_perform (in /usr/lib64/libcurl.so.4.8.0)
==9745==    by 0x1E98DD96: flatpak_download_http_uri_once.lto_priv.0 (flatpak-utils-http.c:507)
==9745==    by 0x1E9BE30C: flatpak_load_uri_full.constprop.0 (flatpak-utils-http.c:957)
==9745==    by 0x1E9B07D3: UnknownInlinedFun (flatpak-utils-http.c:997)
==9745==    by 0x1E9B07D3: UnknownInlinedFun (flatpak-dir.c:12172)
==9745==    by 0x1E9B07D3: _flatpak_dir_get_remote_state.constprop.0 (flatpak-dir.c:12522)
==9745==  Address 0xd9d5c6d89bdedfca is not stack'd, malloc'd or (recently) free'd
```

Looking into the `flatpak-utils-http.c`, the `data` in question is always stack-allocated. The `FlatpakHttpSession` does not prevent download interleaving, which could not cause any problem with the libsoup, but libcurl is different. It's not completely about the libcurl (not) being thread safe, it's about the way the libcurl is used here. Specifically, when two threads are using the same FlatpakInstallation, which uses the same libcurl object, from two threads, then the calls to
```
  curl_easy_setopt (curl, CURLOPT_WRITEDATA, (void *)data);
  curl_easy_setopt (curl, CURLOPT_HEADERDATA, (void *)data);
```
can overwrite the data being used by the call in the other thread.

I verified that this can happen with this debug patch:

```diff
diff -up flatpak-1.13.3/ flatpak-1.13.3/
diff -up flatpak-1.13.3/common/flatpak-utils-http.c.3 flatpak-1.13.3/common/flatpak-utils-http.c
--- flatpak-1.13.3/common/flatpak-utils-http.c.3	2022-06-17 00:48:22.000000000 +0200
+++ flatpak-1.13.3/common/flatpak-utils-http.c	2022-08-16 14:04:12.139000000 +0200
@@ -243,6 +243,7 @@ G_DEFINE_AUTOPTR_CLEANUP_FUNC (auto_curl
 
 struct FlatpakHttpSession {
   CURL *curl;
+  gint ongoing;
 };
 
 static void
@@ -450,6 +451,8 @@ flatpak_download_http_uri_once (FlatpakH
   long response;
   CURL *curl = session->curl;
 
+  if (g_atomic_int_add (&session->ongoing, 1) > 0)
+	g_warning ("%s: Already under pressure", __FUNCTION__);
   g_debug ("Loading %s using curl", uri);
 
   curl_easy_setopt (curl, CURLOPT_URL, uri);
@@ -508,6 +511,7 @@ flatpak_download_http_uri_once (FlatpakH
 
   curl_easy_setopt (session->curl, CURLOPT_HTTPHEADER, NULL); /* Don't point to freed list */
 
+  g_atomic_int_add (&session->ongoing, -1);
   if (res != CURLE_OK)
     {
       set_error_from_curl (error, uri, res);
```

and when I saw the warning, the gnome-software crashed shortly afterwards, with a memory corruption claim:

```
12:33:48:0783 flatpak flatpak_download_http_uri_once: Already under pressure
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

Thread safety of the libcurl is questionable, see the documentation for the [curl_easy_init](https://curl.se/libcurl/c/curl_easy_init.html), where they claim you might call the `curl_global_init` from the "main" thread (I'm paraphrasing here), which doesn't fully match the [curl_global_init](https://curl.se/libcurl/c/curl_global_init.html) documentation, but it still can make sense to do that. Nonetheless, libcurl is not to blame here.
