### ISSUE TITLE
No alpha beta repo/ software by default

### ISSUE THREAD

**Issue by romulasry** [flatpak/flatpak#3702]
## Linux distribution and version
Clear Linux OS
## Flatpak version
1.6.3
## Description of the problem
No beta/alpha software from the GUI
## Steps to reproduce
Using Gnome Software 3.34.2 or flathub website
No alpha/beta software
Proft?

**Comment by eszlari** [comment]
> Using Gnome Software 3.34.2 or flathub website
> No alpha/beta software

For GNOME Software report it here:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues

For Flathub, there is already a bug report:
https://github.com/flathub/linux-store-frontend/issues/178
