### ISSUE TITLE
some Flatpaks lag until forced to redraw

### ISSUE THREAD

**Issue by Pobega** [flatpak/flatpak#3716]
## Linux distribution and version
Fedora Silverblue 32

## Flatpak version
Flatpak 1.6.4

## Description of the problem
Very often my Flatpaks (specifically Steam and Firefox) will lag when under heavy load. This seems to occur more often due to heavy Javascript use in web pages, but sometimes it seems to happen randomly too. The application will appear frozen as if it's not drawing new frames, but it will continue to run (you continue to hear audio and videos continue to play.) 

The apps can be forced to redraw by alt tabbing out of them, then when you come back they'll be fine but will generally freeze again.

## Steps to reproduce
I'm honestly not sure, all I did is install Firefox and Steam from Flathub.

Since I don't have a repro case I was wondering if there's a good way to debug this - so far logs have shown me nothing of interest.

Edit: It's been a while but I do believe the problem began occurring after upgrading to Fedora 32. Perhaps it's Mesa mismatch related?

$ glxinfo (outside sandbox)
`OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.2`

$ flatpak list
`default	org.freedesktop.Platform.GL.default		19.08	flathub	system`

**Comment by alexlarsson** [comment]
This sounds very likely to be some combination of different versions of something not quite working well together. However, its very tricky to know from this description what software you are running. For example, are you using gnome? kde? something else? X11 or Wayland? What GL driver? Does the issue go away if you change some of the above things?

**Comment by Pobega** [comment]
Yeah, this is kind of a weird issue, sorry for the lack of information but it's not very apparent to me _what_ might be causing it.

The issue has been very consistent since upgrading to Fedora 32 about 3 weeks ago, though I haven't seen it occur in 12 hours. I'll try changing to an X11 window manager next time I see it show up again.

I'm using Silverblue so it's a very stock Fedora setup with very little modification;

- Gnome 3.36.3 (with display scaling at 125%)
- Wayland environment (and --socket=wayland flag in Firefox but not Steam, if that matters)
- Mesa 20.1.2
- Flatpak 1.6.4
- Open source AMDGPU driver (AMD Ryzen 5 Raven Ridge APU)

**Comment by Pobega** [comment]
So I did some A/B testing with `--socket=wayland` and without, and my gut feeling coming away from it is that this may be related to Gnome display scaling. This seemed to not make a difference which I kinda figured since Steam uses X and exhibits the same behavior.

I played around a bit more and it seems like something changed in 3.36 where **125% display scaling causes Flatpaks to lag**.

I'm not sure if this is the right place for this issue rather than Gnome's bug tracker. Thoughts?

**Comment by alexlarsson** [comment]
Fundamentally I don't think this is the right place, because the issue is not really in flatpak, but rather inbetween two other pieces of software. Its true that flatpak causes this interaction to happen, but the developers of flatpak are not in a good situation to know much about these other pieces of software to debug it.

**Comment by Pobega** [comment]
Okay, thanks. Then let this hopefully serve as a Google result for anyone running into the same issue.

I'll try to get more info and see if I can open up a bug with Gnome, but I worry that ultimately they'll end up saying it's a Flatpak issue since the scaling works fine with native applications.
