### ISSUE TITLE
openSUSE rpmlint results

### ISSUE THREAD

**Issue by DimStar77** [flatpak/flatpak#372]
The openSUSE rpmlint script identified those shortcomings on flatpak (last tested 0.6.13)

it would be nice to get those assess and, possibly, fixed.

```
[  118s] flatpak.x86_64: W: missing-call-to-setgroups-before-setuid /usr/bin/flatpak
[  118s] This executable is calling setuid and setgid without setgroups or initgroups.
[  118s] There is a high probability this means it didn't relinquish all groups, and
[  118s] this would be a potential security issue to be fixed. Seek POS36-C on the web
[  118s] for details about the problem.
[  118s] 
[  118s] flatpak.x86_64: W: missing-call-to-chdir-with-chroot /usr/bin/flatpak
[  118s] This executable appears to call chroot without using chdir to change the
[  118s] current directory. This is likely an error and permits an attacker to break
[  118s] out of the chroot by using fchdir. While that's not always a security issue,
[  118s] this has to be checked.

```

**Comment by alexlarsson** [comment]
For the setgroups part, I don't see how this affects us. The bubblewrap binary is not setgid, only setuid, so we should never have increased the privileges in terms of groups (be it primary or supplementary groups), so we don't need to drop them. In fact, we don't call setgid() either. 

For the chroot issue, we call chroot in two places in the code, in bubblewrap:
```
  /* Now make /newroot the real root */
  if (chdir ("/newroot") != 0)
    die_with_error ("chdir newroot");
  if (chroot ("/newroot") != 0)
    die_with_error ("chroot /newroot");
  if (chdir ("/") != 0)
    die_with_error ("chdir /");
```

And in libglnx:
```  
  if (chroot (".") != 0)
    _perror_fatal ("chroot: ");

  if (chdir ("/") != 0)
    _perror_fatal ("chdir: ");
```

Only the former is actually used in flatpak, but both of these seem to call chdir, so I don't understand why it is warning about this?

@cgwalters Does the above look correct to you?

**Comment by DimStar77** [comment]
> ./app/flatpak-builtins-enter.c:  if (setgid (gid))

**Comment by alexlarsson** [comment]
Yes, but "flatpak enter" is not setuid, its meant to run as root.
