### ISSUE TITLE
Releases 1.8.1, 1.6.5 do not have commits in any branch on this repository

### ISSUE THREAD

**Issue by rinigus** [flatpak/flatpak#3729]
As of today, releases 1.8.1 and 1.6.5 do not have commits in the repository. When checking the commit, github displays "This commit does not belong to any branch on this repository. " . Please push them to the corresponding branches.

**Comment by refi64** [comment]
Where exactly are you seeing this? If I compare 1.8.1 to 1.8.0 in the
GitHub UI, all the commits are on the flatpak-1.8.x branch.

**Comment by pwithnall** [comment]
Merged fixes from @mwleeds since it seemed important to do this quickly before any translators pushed to those branches (I’m not really a flatpak maintainer)
