### ISSUE TITLE
AMD VA-API support

### ISSUE THREAD

**Issue by mikelpr** [flatpak/flatpak#3736]
## Linux distribution and version
Fedora 32

## Flatpak version
1.6.4

## Description of the problem
There is no VAAPI extension for AMD GPUs, only for Intel (#4).
as for Nvidia there's VDPAU. but for AMD there is none, and both the open source and closed source drivers support both.

## Steps to reproduce
try to hardware accelerate decoding on AMD with a flatpak app - can't be done

**Comment by mikelpr** [comment]
I can't actually confirm this - seems like it's working now

**Comment by dm17** [comment]
> I can't actually confirm this - seems like it's working now

Meaning VA-API is expected to work in a browser running in flatpak on AMD GPUs?
