### ISSUE TITLE
.desktop files start system application instead of flatpak [written by flatpak'ed applications weird behavior - e.g steam]

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3737]
Reproduce:
```
1) Have steam installed from flatpak and from system.
2) Have some game installed in both (system & flatpak)
=> Steam Games install there .desktop files (system) to $HOME/.local/share/applications
=> or as flatpak to $HOME/.var/app/com.valvesoftware.Steam/.local/share/applications/
```

The weird behavior is if you start `$HOME/.var/app/com.valvesoftware.Steam/.local/share/applications/GAME.desktop`
the game (and steam) launched will not be the flatpak'ed steam but system steam instead.

**Comment by TingPing** [comment]
This isn't a `flatpak` problem.

The Steam flatpak would have to export its .desktop files to the host.
