### ISSUE TITLE
Flatpaks not working after latest Manjaro testing update

### ISSUE THREAD

**Issue by SecretAgentAgentX** [flatpak/flatpak#3738]
This morning I did the testing updates for Manjaro KDE 20.0.3 and after a reboot noticed I was missing 2 systray icons, qBittorrent and Green With Envy. I thought it was a KDE applications update issue since they were just updated from 5.19.2 to 5.19.3, but mow I'm not entirely sure if it's a KDE issue or flatpak needs an update to be properly compatible with the new KDE applications version. Flatpak and my flatpak apps are all up to date since I just ran Topgrade yesterday and the core components updated for flatpak.  Any thoughts on what might be causing the issue and a possible fix would be greatly appreciated. Besides the 2 threads below I have created a bug report on KDE's bug report site. Thanks

https://forum.kde.org/viewtopic.php?f=289&t=166954

https://forum.manjaro.org/t/applications-missing-from-systray-and-wont-run-after-07102020-testing-updates/152661

**Comment by Bleuzen** [comment]
Seems to be a bug with the 5.7.8 Kernel. Flatpaks work with the 5.4 Kernel on my system.

**Comment by SecretAgentAgentX** [comment]
Did you test this? Thought yesterday of updating to the 5.8 cause I vaguely remember someone stating they weren't having any issues on it.

**Comment by Bleuzen** [comment]
Yes I tested this with Discord and Teams. They both start just fine with Kernel 5.4. However only 5.7.8 doesn't work.

**Comment by SecretAgentAgentX** [comment]
GWE is in autostart, QBT starts on it's own normally. Also missing something else cause I should have 15 icons showing and I only have 12.

**Comment by mwleeds** [comment]
@SecretAgentAgentX per your comment on the Manjaro forum, this seems fixed in kernel 5.8
