### ISSUE TITLE
Applications don't share recently used files

### ISSUE THREAD

**Issue by mrksu** [flatpak/flatpak#3743]
## Linux distribution and version

Fedora 32 Workstation and Silverblue, RHEL 8

## Flatpak version

1.6.4 on Fedora and 1.0.6 on RHEL

## Description of the problem

In Gnome, Nautilus and the file selection dialog include a list of recently used files. With applications installed from regular packages, the list of used files is shared among all applications. For example, if I open a text file in Gedit, I can then easily find it in the "open file" dialog in any other application, and I can easily move the file between applications without looking up the path each time.

Each Flatpak application, on the other hand, keeps its own, private list of recently used files. The file dialog can't see files accessed by other applications. This makes the "recently used" feature significantly less useful, to the point of being confusing.

## Steps to reproduce

1. Install at least two Flatpak applications that feature a file dialog.
2. Open a file in one application.
3. In the other application, open the file dialog and navigate to recently used files.
4. The file that you opened in the first application doesn't show in the file dialog of the other application. There is no explanation.

## Suggestions

I've discussed this with @tpopela, and he pointed out that sharing recently used files among applications might be a security risk. @tpopela then said that a new portal could be written for this use case.

As far as I understand Flatpak, it looks like this could possibly be solved on the level of the file portal, so that only the portal remembers the recently used files, and the applications can't access the list on their own.

Alternatively, if you decide that applications shouldn't be able to see recently used files, please consider removing that category from the file dialog. If it's there but it's half-empty and doesn't actually show recently used files that you'd expect, it's counter-productive to even have that category there.

**Comment by mwleeds** [comment]
Hi, thanks for reporting this issue but it's a duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/215
