### ISSUE TITLE
Strange Artifacts on Multiple Electron Flatpak-Apps (Signal, Riot, Zoom)

### ISSUE THREAD

**Issue by mogoh** [flatpak/flatpak#3749]
## Linux distribution and version
Ubuntu 20.04
## Flatpak version
~~~
$ flatpak --version
Flatpak 1.6.3
~~~
## Description of the problem

Some Flatpak-App (Signal, Riot, Zoom) have this graphic issues as you can see in the screenshot below.

Those are all Electron-apps, installed via Flatpak.
Not all Electron-apps that I have installed have this issue.
Discord and VSCode are working fine and are not installed via flatpak.

![Screenshot_20200715_093630](https://user-images.githubusercontent.com/580975/87524773-df27c980-c688-11ea-9cce-5680eb710242.png)

## Steps to reproduce

My only step to reproduce is install and start.

**Comment by mwleeds** [comment]
Would be helpful if you could post the `flatpak info us.zoom.Zoom` output

**Comment by mogoh** [comment]
```
$ flatpak info us.zoom.Zoom

Zoom - Video Conferencing, Web Conferencing, Webinars, Screen Sharing

         Kennung: us.zoom.Zoom
             Ref: app/us.zoom.Zoom/x86_64/stable
     Architektur: x86_64
           Zweig: stable
         Version: 5.1.422789.0705
         License: LicenseRef-proprietary
        Ursprung: flathub
      Collection: org.flathub.Stable
    Installation: system
       Installed: 93,2 kB
Laufzeitumgebung: org.freedesktop.Platform/x86_64/19.08
             Sdk: org.freedesktop.Sdk/x86_64/19.08

          Commit: ab3b78a624e8777ea250f7d62acad907b7257aad13e3c26a3edc33336f4cb494
          Parent: 8c7a75cd011df2159517309776876b0c35fe238e1c37f8074459a6d78bd4b92f
         Subject: Update zoom.tar.xz to 5.1.422789.0705 (3bf51a6c)
            Date: 2020-07-06 14:26:37 +0000
```

**Comment by PorcelainMouse** [comment]
Does this happen immediately when you start the app or boot your computer?  Or, does it get worse over time?

**Comment by mogoh** [comment]
Immediately. It stays the same over time. The artefacts are flickering a bit, but that's all.

**Comment by alexlarsson** [comment]
It sounds to me like this could be caused by the GL driver in the runtime (which might be slightly different than what is used outside of flatpaks).

**Comment by dan9qt** [comment]
I have the same problem on Pop OS. My graphics card is an AMD 5500 XT in case it matters.

Working - Telegram / Thunderbird / Nextcloud / Glimpse
Not working - Blender / Signal / Discord / 

I will do a proper list of apps tomorrow that I have installed if it helps

**Comment by AKDub** [comment]
Same issue for me on PopOS 20.04

**Comment by thoddi** [comment]
I'm also having this problem. It seems to apply to every flatpak I have tried. 

My cpu and gpu are Ryzen 5 3600x and Radeon RX 5500 XT.

There is one (sort of) exception. When I run Eclipse IDE (flatpak) it works fine except for the "Welcome" screen. The "Welcome" screen is the only part of that program that has the artefacts described above.

![image](https://user-images.githubusercontent.com/5701441/92656215-2d9cc180-f2e2-11ea-96e6-361694c71b19.png)
![image](https://user-images.githubusercontent.com/5701441/92656277-486f3600-f2e2-11ea-8790-9169ac73fc78.png)

**Comment by ayylmaonade** [comment]
Did anybody figure out a solution to this? I randomly started encountering it on my Arch system. Ryzen 9 5900X, RX 6800 XT. Using the open source mesa-git drivers.

**Comment by ayylmaonade** [comment]
> I didn't notice any problems until Blender 3.0. Now it feels unusable – it flickers a lot, and I often can't see the grid etc. **But** when I download Blender directly from blender.org, I have **zero** issues.
> 
> The problem occurs with different versions of Pop!_os, including 20.10 and 21.10.

I just recompiled my mesa drivers and it solved the issue. Perhaps a reinstall on those distros would help? Or switching to mesa-git.

**Comment by Vii-GitHub** [comment]
![image](https://user-images.githubusercontent.com/85794280/172143842-05ac4794-3a05-4a0a-a525-b102813aa08b.png)
Getting this on Steam as well, I use a 5500 XT too.

**Comment by Nuckal777** [comment]
Same issue for me with a 5500 XT on Arch.

**Comment by wlinna** [comment]
I use Pop 22.04 and Blender 3.2 now, and haven't noticed my [the problem](https://github.com/flatpak/flatpak/issues/3749#issuecomment-1024033234) since

**Comment by zilti** [comment]
Can confirm on OpenSUSE Tumbleweed. All Flatpak Electron programs are broken. Non-Flatpak ones work fine though.

**Comment by fsievers** [comment]
Just a quick solution that worked for me. Install `flatpak install org.freedesktop.Platform.GL.mesa-git` (I selected version 22.08beta). And than uninstall all mesa packages for the default version `flatpak uninstall org.freedesktop.Platform.GL.default` (select 'All of the above' when asked which version to uninstall).

**Comment by dxciBel** [comment]
I encountered this same issue after a mesa update on my Linux Mint install. Reverting the driver update made it work fine again, but I wanted to switch to openSUSE TW anyway so that was the straw that broke the camel's back. Appears OOTB on openSUSE for me now. Everything else is behaving normally. I'm also using a 5500 XT.

**Comment by Mango2000** [comment]
running the following command:
AMD_DEBUG=nodcc
as suggested here:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3323
fixed this issue for me

there is some link to make this solution permanent in that thread too

**Comment by smcv** [comment]
If this is a problem with Mesa, libdrm or the app, then it will never be fixed *by a change in flatpak*, because flatpak is not responsible for the content of Mesa, libdrm or the app. You use flatpak to install them, but as long as the libraries that the app maintainer thinks you should be using have been installed correctly, flatpak is working as designed (whether those libraries have bugs or not).

The versions of Mesa and libdrm that are used by typical Flatpak apps come from <https://gitlab.com/freedesktop-sdk>.

**Comment by hfiguiere** [comment]
Not a flatpak bug.
