### ISSUE TITLE
Flatpak downloads every nvidia driver from flathub at every update

### ISSUE THREAD

**Issue by trialism** [flatpak/flatpak#3750]
## Linux distribution and version

Ubuntu 20.04

## Flatpak version

1.6.3

## Description of the problem

Every time a new nvidia driver gets released I need to update the flatpaks and this already slow process(with SSD and very fast internet) becomes slower because it redownloads every driver again. This happened three times so far. Now it downloaded every driver from 430.xy to 450.xy. Maybe this is a flathub issue and the maintainers just constantly update every driver package(which is ridiculous), or maybe the dependency resolution modules are not working properly.

Bonus bug: in the terminal the, checkboxes stop appearing after a few resizes.

## Steps to reproduce

Run `flatpak update` when there is a new nvidia driver available.

**Comment by TingPing** [comment]
`flatpak uninstall --unused`

**Comment by mwleeds** [comment]
You're saying that when the nvidia driver is updated, flatpak offers to update it? I don't see how that's a bug?

**Comment by TingPing** [comment]
Well it is an issue of how its packaged that it updates often, sadly not easily avoidable.

**Comment by trialism** [comment]
@mwleeds it downloads every driver again - even the old ones - not just the one which was just released.

@TingPing then maybe I should report it somewhere else. Or if it's a won't fix then I'm just going to close this.

**Comment by TingPing** [comment]
You can report it to the nvidia package. https://github.com/flathub/org.freedesktop.Platform.GL.nvidia

Its not that its a WONTFIX, its just that its a tricky problem to solve.
