### ISSUE TITLE
"flatpak update" takes up to 10 minutes

### ISSUE THREAD

**Issue by Mershl** [flatpak/flatpak#3755]
## Linux distribution and version
Silverblue 32.20200716.0

## Flatpak version
flatpak-1.6.4-1

## Description of the problem
`flatpak update` is taking up to 10 minutes. gnome-software seems to be stuck and will not show updates.

It seems to be take the longest time on `Transaction: install/update ...` the longest time when running `flatpak update -vv`. Not one particular package but every package takes 10-20 seconds. 

Side question: Is there a cmdline tool to show timestamps per line for the output of `-vv` to measure which step is taking the longest?

## Steps to reproduce
`kill gnome-software` // to ensure gnome-software is not keeping a lock
`flatpak update`

## Steps I've tried
`rpm-ostree cleanup -m`
`flatpak repair`

## Enabled repos
```
Name    Options
fedora  system,oci
flathub system
```

## System info
28 installed flatpak apps.
36 installed runtimes.

**Comment by mwleeds** [comment]
It's not clear this is actually a bug. Without knowing the size of the updates and the speed of your internet connection, it's hard to know what a reasonable update time would be. Maybe you could post your log file of `flatpak update -vv` and the output of `flatpak history` which will have timestamps?

Note also there is [ongoing work](https://blogs.gnome.org/alexl/2020/05/13/putting-container-updates-on-a-diet/) to make OCI updates smaller.

**Comment by Mershl** [comment]
To clarify the issue: the time until the update prompt is shown takes up to 10 minutes. The download and installation of the updates themselves is fast afterwards.

After your comment I started several sequential runs of `flatpak update -vv`:
- Most runs are really slow, I've attached the latest as [flatpak_update_slow.txt](https://github.com/flatpak/flatpak/files/4949601/flatpak_update_slow.txt).
- A single run was instantly showing the available updates.

**Comment by Mershl** [comment]
Another finding that came up in a single run today:
```
$ flatpak update
Looking for updates…
Login required remote fedora (realm https://registry.fedoraproject.org/)
User:
<prompt canceled by user>
```

**Comment by Mershl** [comment]
An `strace -tttT` is showing several timeouts. I've cut out the timeout including 200 lines before it.

Log file: [strace_cut_200lines.txt](https://github.com/flatpak/flatpak/files/5053252/strace_cut_200lines.txt)

**Comment by alexlarsson** [comment]
In general, if something seems to get "stuck" for 30 seconds, that is the default timeout for dbus messages and that means something got sent a message which didn't get a reply. In flatpak dbus is used for the authenticator when getting http tokens for OCI remotes (such as the fedora one). In that case it would be the `flatpak-oci-authenticator` process that is supposed to reply. Maybe it crashed?

**Comment by alexlarsson** [comment]
It might be interesting to run: `/usr/libexec/flatpak-oci-authenticator -r -v --no-idle-exit` in a different shell before starting the update and see what it prints.

**Comment by alexlarsson** [comment]
Further off-github debugging seems to indicate that flatpak is calling `org.freedesktop.locale1` on the system bus and starting that times out.

**Comment by alexlarsson** [comment]
However, I don't think we should repeatedly call localed anyway. We should really cache the value after the first time (or cache the failure).

**Comment by Mershl** [comment]
The root cause was an SElinux policy hindering systemd-localed.service from starting up which tried to repeatly restart by the calls from flatpak. After fixing the SElinux policy flatpak update performed as expected.
