### ISSUE TITLE
Home in /usr/... is broken

### ISSUE THREAD

**Issue by Xenopathic** [flatpak/flatpak#3764]
## Linux distribution and version

Debian testing

## Flatpak version

Flatpak 1.6.3

## Description of the problem

For a user with a home directory under `/usr`, e.g. `/usr/local/homes/$USER` (no, I didn't choose this), trying to run some Flatpak apps (tested with Steam) either installed in the user installation or in the system installation fails with a cryptic error message:

    bwrap: Can't mkdir parents for /usr/local/homes/Xenopathic/.: Read-only file system

I dug into why this happens, and it looks like bwrap is making sure the home directory path exists, but `/usr` is mounted as read-only before it tries to `mkdir /usr/local`. `/usr` is of course mounted read-only from the Flatpak image, so this fails.

At the very least, this should be a better error message, indicating why Flatpak is trying to mkdir this path in the first place, and that it cannot because `/usr` lies in a read-only mount from the Flatpak image. Ideally, homes in `/usr` or other weird places should be supported, with the real home directory being located somewhere else in the sandbox.

## Steps to reproduce

1. Create a user with a home directory under `/usr`
2. Try to run an app (that asks for certain permissions?) when logged in as that user.

**Comment by mwleeds** [comment]
Similar to #534

Why is your home directory under `/usr/local/`? Seems like a violation of https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

**Comment by Xenopathic** [comment]
Poor decisions made by my sysadmin :confused: 

I managed to hack around the problem by lying to flatpak though:

```
#!/bin/bash

bad_home=/usr/local/homes/Xenopathic
good_home=/Xenopathic

if ! mountpoint $good_home; then
    sudo mount --bind $bad_home $good_home
fi

while read -r line; do
    line=$(sed "s@$bad_home@$good_home@g' <<< "$line")
    export "$line"
done < <(env)

exec flatpak "$@"
```

**Comment by mwleeds** [comment]
I think the bug here is in your system setup not in Flatpak.
