### ISSUE TITLE
[Question] Does updating an already launched flatpak application can break something ?

### ISSUE THREAD

**Issue by Nokia808** [flatpak/flatpak#3766]
Hi. 

From time to time I updating my flatpak applications using "flatpak update" while some of them already launched & running - I forgot to close them. Example, I was already launched "ksnip" flatpak (that I'm already installed it from GitHub) & minimize it to try icon, so I forgot that it is already launched & running & performed "flatpak update" while ksnip is already running ..... Is this can break something ? Do I need to uninstall ksnip flatpak & re-install it again ?

Thank you.

**Comment by TingPing** [comment]
No all mounted data is kept and unchanged so it is safe.
