### ISSUE TITLE
moving flatpaks from one location to another?

### ISSUE THREAD

**Issue by XN17** [flatpak/flatpak#3768]
I installed lots of flatpak application. Now my home folder is almost full, so I want to move them to an external location.

Is there a way to move flatpak installed in home directory to external location (one from /etc/flatpak/installations.d/extra.conf) and make it work just fine. 

When I moved the directories from app, exports and runtime to the new location they are detected by flatpak but flatseal does not recognize any application after that(even the one I installed after moving).

**Comment by TingPing** [comment]
Its probably just a flatseal issue of not knowing about installations.

**Comment by XN17** [comment]
Moving the issue to Flatseal

**Comment by tchx84** [comment]
Just in case someone else ends up here:

Flatseal does support custom installations, please check mhttps://github.com/tchx84/Flatseal/blob/master/TIPSANDTRICKS.md#enable-custom-installations
