### ISSUE TITLE
Failed to load module "canberra-gtk-module" -> Mattermost & Nextcloud

### ISSUE THREAD

**Issue by PixnWave** [flatpak/flatpak#3775]
## flatpak run org.nextcloud.Nextcloud
Gtk-Message: 16:11:24.354: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:11:24.355: Failed to load module "canberra-gtk-module"
## flatpak run com.mattermost.Desktop
Gtk-Message: 16:33:09.386: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:33:09.386: Failed to load module "canberra-gtk-module"

**Comment by TingPing** [comment]
This is not an issue and can be ignored. The missing module doesn't provide anything important.
