### ISSUE TITLE
`gtk-key-theme` is not respected in flatpaks

### ISSUE THREAD

**Issue by chee** [flatpak/flatpak#3787]
first up: thank you, this project is really great

## Linux distribution and version
void linux.
`uname -a` :: Linux sweeties 5.7.14_1 #1 SMP Sat Aug 8 06:24:11 UTC 2020 x86_64 GNU/Linux
## Flatpak version
Flatpak 1.6.3
## Description of the problem
`gtk-key-theme` is not respected in flatpaks. i used the setting `Emacs` so that apps let me use emacs-style readline-like bindings for editing text. this does not work in flatpak apps.
## Steps to reproduce
1. `$ gsettings set org.gnome.desktop.interface gtk-key-theme Emacs`
2. `$  gconftool-2 -s --type string /desktop/gnome/interface/gtk_key_theme Emacs`
3. `$ dconf write /org/gnome/desktop/interface/gtk-key-theme "'Emacs'"`
4. open a gtk flatpak app (such as Midori or Slack)
5. try to use an emacs binding in a text area
6. cry

**Comment by alexlarsson** [comment]
There are several ways this could work.
1) On X11 the gnome desktop propagates the dconf settings to xsettings which the app will read. If you're not using gnome i think you may be able to run just the xsettings daemon from that.
2) On Wayland it will read the settings from the settings portals
3) If neither of the above is true you can grant dconf access to the app (in the build, or custom at your site using `flatpak override` with the options in https://docs.flatpak.org/en/latest/sandbox-permissions.html#dconf-access

But, in general this is an app issue and not a core flatpak bug.

**Comment by parisni** [comment]
hi @chee . have you been able to fix this ?
