### ISSUE TITLE
Fallo de inicio de gnome al realizar dist-upgrade

### ISSUE THREAD

**Issue by Geovanns** [flatpak/flatpak#3789]
## 1. Realizar un dist-upgrade.

Al actualizarse todos los paquetes a su última versión y reiniciar el sistema operativo genera una pantalla blanca de error de inicio de sesión o imprime en pantalla el código de clean y NO permite la carga de gnome.

Los errores hallados:
GRAVE
1- Un conflicto de version de libffi todo el sistema se actualizo para implementar libfii.so.7 pero flatpak no reconoce la nueva versión de la librería y genera error, solicitando la dependencia libffi.so.6 pero está ya no está disponible en el repositorio de Focal.

GRAVE
Error generdo por Flatpak al actualizar libsoup2.4-1 el paquete a la versión 2.70.0-1 error generado falta de de método o función que maneja el tiempo. Genera error al usar el comando apt y gdm y comandos para realizar conecciones de red entre otros.
 
Solución temporal.
Instalación manual de libffi.so.6 mediante archivo de de la distribucion de ubunrtu 18 (no he notado que conductos genera) 

Instalación manual de libsoup2.4_1 se realiza un downgrade para usar la versión 2.52.2-1 aunque está permite el arranque de la interfaz gráfica gnome hay muchas aplicaciones que no funcionan y pide actualizar libsoup pero al actualizar vuelve a generarse el error en el arranque y no permite cargar gnome ni usar apt y comandos de red.

**Comment by alexlarsson** [comment]
Sorry, I don't speak spanish so i have no idea what this says.

**Comment by alexlarsson** [comment]
Google translate says:
When updating all the packages to their latest version and restarting the operating system, it generates a white screen of login error or prints the clean code on the screen and does NOT allow the gnome to load.

Errors found:
SERIOUS
1- A libffi version conflict the whole system was updated to implement libfii.so.7 but flatpak does not recognize the new version of the library and generates an error, requesting the libffi.so.6 dependency but it is no longer available in the Focal repository.

SERIOUS
Error generated by Flatpak when updating the package libsoup2.4-1 to version 2.70.0-1 error generated lack of method or function that handles time. It generates an error when using the apt and gdm command and commands to make network connections among others.

Temporary solution.
Manual installation of libffi.so.6 using the ubunrtu 18 distribution file (I haven't noticed what conduits it generates)

Manual installation of libsoup2.4_1, a downgrade is performed to use version 2.52.2-1, although it allows the gnome graphical interface to be started, there are many applications that do not work and it asks to update libsoup but when updating the error is generated again on startup and it doesn't allow loading gnome or using apt and network commands.

**Comment by alexlarsson** [comment]
I don't know where you got flatpak 1.6.3 from, but the only version of flatpak for ubuntu that we (upstream) provide is the ppa (https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak) and that has 1.8.1. So, this seems to be a distribution problem and you should bring it up there.
