### ISSUE TITLE
[Feature request and Documentation request/improvement]

### ISSUE THREAD

**Issue by rubyFeedback** [flatpak/flatpak#3793]
Hey there flatpak devs and everyone else using flatpak,

I have installed flatpak on my oldschool slackware system (rocking
for life; actually zenwalk, but slackware-based). It is working
fine.

However had, I also have an old computer with windows7. That one
works fine too but I do not use it that often.

Recently, though, I wondered whether I could use flatpak + some
KDE applications, such as okular - see kde-reddit for a recent
discussion on what people download (if they use windows, and
want to use some KDE applications). Okular is a quite decent 
.pdf viewer, so I think it makes sense to want to use it.

Now: flatpak traditionally focuses on linux. I understand that,
no problem.

Would it be possible that flatpak could also support windows?

I don't want to add a lot of unnecessary extra work to a dev
team that focuses on linux first and foremost, that is fine;
but I am wondering what would be missing to make this work.

On that windows machine I have access to the www so I can 
download literally anything. I guess in principle what I
imagine would be a "download this tarball/exe file to make
flatpak work on windows", and when this is done, we could 
then go on and use all the applications that use flatpak.

I could even use ruby for batch-installation perhaps - I
registered lots of flatpak URLs such as:

  https://flathub.org/repo/appstream/org.gnome.Evolution.flatpakref

(I am not yet familiar with how this works with KDE though;
I compile all of KDE from source on linux, so I am now a 
noob when it comes to windows right now.)

Would it be possible to support something like a "minimum
flatpak" for windows user too? Does not have to include
all applications by the way; my use case is literally 
limited to okular, and perhaps kate (the editor). I don't
intend to have a "WSL 3.0" or something like that, just
a simple way to install packages on windows too.

Anyway, if this is too much work please do just feel free
to close this issue. (By the way, machomebrew originally
only supported OSX, but they do have some kind of linux
support, even though it does not seem to work as well as
the OSX parts, understandably so.)

I have a second, smaller issue request, though, and this
is documentation. Right now https://github.com/flatpak/flatpak
does not mention which operating systems are supported.

I understand that this may be only limited to linux
right now :-) but perhaps a new file, or a short subsection,
could briefly mention goals or outlooks for other operating
systems? Evidently not just windows, but perhaps OSX, 
ReactOS, HaikuOS and so forth. May be wishful thinking but
it would be kind of cool to have one-appform-to-rule-them-all
really, in the long run (even if we may need some common
runtime on windows, but that is fine; downloads are simply
and I used msys/mswin/cygwin in the old days too).

**Comment by alexlarsson** [comment]
Flatpak is very much linux only, it relies on lots of linux-kernel specific options. And anyway, even if it did work on windows (it might actually somewhat work with WSL2) the apps require a linux desktop to work (including and Xserver and whatnot), running them under regular windows just isn't possible.
