### ISSUE TITLE
Access to icon exports from the sandbox

### ISSUE THREAD

**Issue by tinywrkb** [flatpak/flatpak#3800]
If I understand this correctly there's no way to access icon exports from the sandbox without bind mounting and giving blanket access to the whole Flatpak installation dir (i.e. `/var/lib/flatpak` or `${XDG_DATA_HOME}/flatpak`), and that's probably not a proper solution with regards to security, especially when access is given to the Flatpak user installation dir, where the Flatpak app has a write permission.

It would be better if the icon exports will be accessible from the Flatpak sandbox without the need to give access to the whole Flatpak installation dir. 

Here's a scenario:  
* Fcitx is exporting icons and is registering a [StatusNotifierItem](https://freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/) via D-Bus to create a system tray icon while it set the IconName to the same Flatpak exported icon name, using the icon name and not a file path so it's theme-able.
* Waybar is a status bar that is registering itself as StatusNotifierHost to create a system tray. When it runs on the host then there's no problem of accessing the Flatpak exported icons of Fcitx.  
But when Waybar is running in the Flatpak sandbox then the exported icons are not available, so a workaround like the following is needed:
```
  - --filesystem=/var/lib/flatpak
  - --env=XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share
```

Example packaging of the mentioned apps:
* [Waybar](https://github.com/tinywrkb/flatpaks/blob/master/com.github.alexays.waybar/com.github.alexays.waybar.yaml)
* [Fcitx](https://github.com/tinywrkb/flatpaks/blob/master/com.fcitx_im.fcitx/com.fcitx_im.fcitx.yaml)

**Comment by alexlarsson** [comment]
Hmm, accessing icons exported by other apps is a bit unclear security-wise. For instance it would let a sandboxed app see what other installed apps there are, which in turn can improve things like finger-printing or targeted attacks on other apps. 

In the scenario above the somewhat uncommon thing to do is to run waybar (which is kindof a desktop-level service) as a flatpak. I feel that its not necessarily a bad thing that you have to expose this higher level access to the user via the workaround permissions.

**Comment by tinywrkb** [comment]
Thanks for the response. I didn't think about the mentioned security implications and they do sound valid. I guess filesystem workaround permission within the app's manifest is a better choice, so I closing this issue.
