### ISSUE TITLE
Dark theme not working in flatpak?

### ISSUE THREAD

**Issue by lock042** [flatpak/flatpak#3802]
OS: Debian testing

Version: Last version of flatpak

Bug: It looks like that `g_object_set(settings, "gtk-application-prefer-dark-theme", TRUE, NULL);` has no effect in flatpak. The theme is light. It can be checked with eog/Siril and probably other apps.

To reproduce: Starts application that should have dark theme, at least at first start. It works as expected for the same apps coming from deb packages.

**Comment by TingPing** [comment]
Helps to mention which theme.

**Comment by lock042** [comment]
I'm running adwaita on my debian

**Comment by TingPing** [comment]
Try just installing `org.gtk.Gtk3theme.Adwaita-dark`

**Comment by lock042** [comment]
@TingPing : Looks like it works. Does it mean that applications using dark theme should have this package as a dep?

**Comment by TingPing** [comment]
No, it *should* be automatically installed by `flatpak`, but sometimes the setting it reads isn't set.

I'll just close this since everything seems fine.

**Comment by lock042** [comment]
OK thx @TingPing
