### ISSUE TITLE
Error: Not enough disk space to complete this operation

### ISSUE THREAD

**Issue by kandarpgautam** [flatpak/flatpak#3813]
## Linux distribution and version
Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux

## Flatpak version
Flatpak 1.8.1

## Description of the problem
I was installing android studio and it showed me this error:
`Error: Not enough disk space to complete this operation
error: Failed to install org.freedesktop.Platform: While pulling runtime/org.freedesktop.Platform/x86_64/19.08 from remote flathub: opcode open-splice-and-close: opcode close: min-free-space-size 500MB would be exceeded, at least 5.8 kB requested`
![Screenshot_20200822_161154](https://user-images.githubusercontent.com/22766673/90954486-460f7e00-e492-11ea-99fc-a6d96aef5387.png)

now I have separate partitions for tmp(1.7GB free of 1.9GB), var(495MB free of 2.3GB), home (190 free of 207GB), and root(0byte free of 10.9GB)
so the problem is probably because my root directory is exhausted.
here's a screenshot:
![Screenshot_20200822_162435](https://user-images.githubusercontent.com/22766673/90954684-12355800-e494-11ea-94ad-d5788c897dc5.png)

I think if it's filling up my root directory I want to configure flatpak the right way so the files don't fill up the root directory. 

## Steps to reproduce
1. I ran the command: `flatpak install flathub com.google.AndroidStudio`
2. separate partitions for tmp, home, and var.

**Comment by AniDevWired** [comment]
Thanks for your hardwork. I have successfully fixed this same issue.
