### ISSUE TITLE
[Question] Is there a way to install certain locale (not all locale) beside that corrspond to system locale?

### ISSUE THREAD

**Issue by Nokia808** [flatpak/flatpak#3816]
Hi. 

Kindly, look for the following issue:
https://github.com/flathub/org.libreoffice.LibreOffice/issues/126

We solved this issue but on the cost of installing the ALL locates that are currently available.

My question is that: is there a way to install only certain locales instead of all locales ? In my case I like only English + Arabic when my Fedora Linux set at English but I like certain programs like Libre Office to be in Arabic & allow me to switch to English, so I need only 2 locale: English & Arabic.

Thank you.

**Comment by mwleeds** [comment]
Yes. You can use the `--subpath` option of the install command, e.g. `flatpak install --subpath=/en --subpath=/ar flathub org.libreoffice.LibreOffice.Locale`

And you can also use `flatpak config` if you want Flatpak to automatically pull locales for a specific set of languages for future installs and upgrades, e.g. `flatpak config --set languages "sv;en;fi"`

**Comment by Nokia808** [comment]
@mwleeds 
Thank you too much ! 

However, I need further help to proceed:
1) what about "org.freedesktop.Platform.Locale//19.08" ? Do it need to specific command ?

2) I'm already run:
flatpak install --reinstall org.freedesktop.Platform.Locale//19.08 
and 
flatpak install --reinstall org.libreoffice.LibreOffice.Locale
So, I'm now has too much locale most of them not needed. To correct it so that to make only remain English & Arabic locale, are the following sequence correct or wrong:
a- run:
flatpak config --set languages "en;ar"
b- remove both "org.freedesktop.Platform.Locale//19.08" & "org.libreoffice.LibreOffice.Locale" by:
flatpak uninstall org.freedesktop.Platform.Locale//19.08
&
flatpak uninstall org.libreoffice.LibreOffice.Locale
c- finally install these 2 package again by:
flatpak install flathub org.freedesktop.Platform.Locale//19.08
&
flatpak install flathub org.libreoffice.LibreOffice.Locale
Are the above sequence correct or not ? Or I need to remove whole libreoffice then re-install it again ?

**Comment by mwleeds** [comment]
Those look correct.

**Comment by Nokia808** [comment]
@mwleeds 
Hi. I performed them but I 1st uninstall these 2 packages then run [latpak config --set languages "en;ar"] & finally installed these 2 packages again.

Every thing run normally without error messages. I asked for root (sudo) password for performing [latpak config --set languages "en;ar"].

But after finishing, I launched LibreOffice to see available locale but I see ALL locale as they were ! Not only English & Arabic !! Why ?

I need a command to check if [latpak config --set languages "en;ar"] run okay or not ?

**Comment by Nokia808** [comment]
@mwleeds 
Hi again. I run just "flatpak config" & output is:

```
$ flatpak config
languages: en;ar (default: en)
extra-languages: *unset*
```

**Comment by mwleeds** [comment]
You can use `flatpak info org.libreoffice.LibreOffice.Locale | grep Subdirectories` to see what languages are installed for it.

**Comment by Nokia808** [comment]
@mwleeds 
I run flatpak info org.libreoffice.LibreOffice.Locale | grep Subdirectories
but the output was no thing ! What this mean ?!

**Comment by mwleeds** [comment]
That means you have the full locale extension installed, every language.

**Comment by mwleeds** [comment]
What version of flatpak are you using and what OS?

**Comment by Nokia808** [comment]
@mwleeds 
I run flatpak info org.freedesktop.Platform.Locale//19.08 | grep Subdirectories
& also the output was no thing ?? 

I'm using Fedora Linux 32 X64 Cinnamon edition with flatpak version 1.6.5

**Comment by Nokia808** [comment]
@mwleeds 
Yes it is a bug ! I solve if by the following workaround:
1) remove these 2 packages by run:
flatpak uninstall org.freedesktop.Platform.Locale//19.08
&
flatpak uninstall org.libreoffice.LibreOffice.Locale
2) install them again by using --subpath command as following:
flatpak install --subpath=/en --subpath=/ar flathub org.freedesktop.Platform.Locale//19.08
&
flatpak install --subpath=/en --subpath=/ar flathub org.libreoffice.LibreOffice.Locale
Every think was okay. Libre Office became available only in English & Arabic.
This what was done at night.

Today, after awake from sleep & tried:
flatpak update
it asked me to update all locale. I put my hand on my heart. But during updates it download for each very few kbs. I take deep breath that it update locale to make them set (corrected) at new setting (en;ar). Indeed it is the case! After update I examine Libre Office & still with only English & Arabic UI options ....
So, I'm fixed it by such workaround, but it remain a bug. So, kindly, keep this issue opened to be fixed from you side by definite future commit. You can even change title of the issue ....

Thank you for being patient with me. You learn me too much !

**Comment by mwleeds** [comment]
Actually, maybe this isn't a bug. Users aren't generally expected to explicitly install a locale extension (as opposed to having it pulled as a dependency) and if you do so it makes sense that all the subpaths would be pulled unless `--subpath` was used.
