### ISSUE TITLE
Drawing Flatpak App's Sandbox

### ISSUE THREAD

**Issue by opqriu** [flatpak/flatpak#3819]
https://flathub.org/apps/details/com.github.maoschanz.drawing

https://www.imageupload.net/image/NBFtk

I haven't lifted the sandbox restrictions for that Flatpak App. This is the default sandboxed option, just after installation.

In Flatpack, this Drawing app is not subject to any sandboxing. I can freely open and save files to USER HOME and ROOT Directory.

os : Debian 10.

**Comment by refi64** [comment]
The app itself cannot see all of your files. Rather, it uses *portals* to
ask the host system to open a file chooser, then on open, only tue selected
files are exposed into the sandbox.
