### ISSUE TITLE
failing to install org.freedesktop.Platform.GL.default while installing org.libretro.retroarch

### ISSUE THREAD

**Issue by badlydrawnface** [flatpak/flatpak#3835]
Manjaro Linux Lyria 20.0.3
version 1.8.1
Installing RetroArch results in it not opening, because org.freedesktop.Platform.GL.default fails in install

$ sudo flatpak install org.libretro.retroarch
Looking for matches…
Found similar ref(s) for ‘org.libretro.retroarch’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/org.libretro.RetroArch/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y

org.libretro.RetroArch permissions:
    ipc                    network        pulseaudio       wayland
    x11                    devices        multiarch        file access [1]
    dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar, org.freedesktop.ScreenSaver

        ID                                  Branch Op Remote  Download
 1. [✗] org.freedesktop.Platform.GL.default 19.08  i  flathub   1.0 kB / 89.1 MB
 2. [✓] org.libretro.RetroArch.Locale       stable i  flathub   3.6 kB / 129.5 kB
 3. [✓] org.libretro.RetroArch              stable i  flathub 184.7 MB / 251.3 MB

Warning: While trying to checkout f68c8e930d048d0490c605d992a82e11499c78cf374a67ef69fa15a4210b636b into /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/19.08/.f68c8e930d048d0490c605d992a82e11499c78cf374a67ef69fa15a4210b636b-P02GQ0: Opening content object fa9d39464ac4c561b7215ecfb5e04454b05d9712b79aeb0d915be7e0378c1c81: Couldn't find file object 'fa9d39464ac4c561b7215ecfb5e04454b05d9712b79aeb0d915be7e0378c1c81'
Installation complete.

**Comment by fabricemarie** [comment]
Looks like your locally cached metadata are out of sync with the remote cache?
I had a similar problem and running `flatpak update --appstream` before running the install command worked for me.

**Comment by wennaspeedy** [comment]
It can be solved by command: `flatpak repair --user`
