### ISSUE TITLE
Permission denied for user installation?

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [flatpak/flatpak#3836]
## Linux distribution and version
opensuse leap 15.2
## Flatpak version
Flatpak 1.6.3
## Description of the problem
`flatpak install flathub org.onlyoffice.desktopeditors`, then opting for user gives "permission denied".
It can only be installed with "sudo" privilege.

What I also need to understand is that in flatpak.org instructions, the installation commands mostly don't use root privilege.
Is it possible to install all flatpak apps without root privilege by using --user option?
## Steps to reproduce
1. `flatpak install flathub org.onlyoffice.desktopeditors`
2. choose "user"

**Comment by mwleeds** [comment]
If you could post the full command and output that would be helpful.

>What I also need to understand is that in flatpak.org instructions, the installation commands mostly don't use root privilege.
Is it possible to install all flatpak apps without root privilege by using --user option?

Yes, you can install things in your user installation which exists in your home directory using `--user` and no root privileges will be required. Most system-wide operations don't require elevated privileges either and the ones that do authenticate with polkit so that `sudo` isn't required.

It sounds like you might have a flathub remote in both your per-user and system-wide installations. If you want to only use one or the other you can delete the remote you don't want (with `flatpak remote-delete`) and Flatpak won't prompt you to choose between them.

The relevant docs are [here](https://docs.flatpak.org/en/latest/using-flatpak.html#system-versus-user).

**Comment by GreatBigWhiteWorld** [comment]
Thanks for the reply. I did seem to have both system and user-wide installation, for different apps. So as you suggested I deleted the system-wide installed apps. No problem. Now "flatpak list" shows only per-user apps.

The problem however seems unrelated at the moment. Below is the result of me trying to install the package onlyoffice and I got the permission denied error at the end.

```
:~> flatpak install flathub org.onlyoffice.desktopeditors --user
Looking for matches?

org.onlyoffice.desktopeditors permissions:
    ipc     network     pulseaudio     wayland     x11     devices     file access [1]    dbus access [2]

    [1] /tmp, host, xdg-config/gtk-3.0
    [2] org.gtk.vfs, org.gtk.vfs.*


        ID                                      Branch           Op           Remote           Download
 1. [?] org.onlyoffice.desktopeditors           stable           i            flathub          1.0 kB / 267.4?MB

Error: Permission denied
error: Failed to install org.onlyoffice.desktopeditors: Permission denied
```

There's no popup for authentication. However if I use
 `sudo flatpak install flathub org.onlyoffice.desktopeditors --user`
it could install.

**Comment by mwleeds** [comment]
Combining `sudo` and `--user` isn't right. That would install into the root user's installation not yours.

Not sure what your issue is. Any chance you manually made changes in `~/.local/share/flatpak/`?

**Comment by GreatBigWhiteWorld** [comment]
> Combining `sudo` and `--user` isn't right. That would install into the root user's installation not yours.
> 
> Not sure what your issue is. Any chance you manually made changes in `~/.local/share/flatpak/`?

I don't think I did any change there. But I prolly used quite some "sudo --user" combinations sometimes.

That said, any suggestion to get out of the situation? I don't mind uninstalling all flatpak apps and start again as there aren't many yet.
Just FYI, I do remember that an authentication window would popup when I install flatpak apps. So it was not always like this.

**Comment by mwleeds** [comment]
You can try `flatpak --user repair`

**Comment by GreatBigWhiteWorld** [comment]
> You can try `flatpak --user repair`

Did this but the result is the same. Got "permission denied".

**Comment by refi64** [comment]
Is it possible that you somehow got ~/.local/share/flatpak owned by root?

**Comment by GreatBigWhiteWorld** [comment]
Just checked with "ll ~/.local/share/flatpak". Its ownership is like any other folder there : username:users.

**Comment by mwleeds** [comment]
You can run `strace -yy flatpak --user repair > strace.log 2>&1` and upload `strace.log` here.

**Comment by GreatBigWhiteWorld** [comment]
> You can run `strace -yy flatpak --user repair > strace.log 2>&1` and upload `strace.log` here.

I tried to remove some personal info in the log and found that the log is actually more than 500MB?

**Comment by GreatBigWhiteWorld** [comment]
Solved it by a complete re-installation.
