### ISSUE TITLE
Something (maybe flatpak?) spammed my machine with bwrap ldconfig calls, eventually killing it

### ISSUE THREAD

**Issue by aaronjensen** [flatpak/flatpak#3840]
## Linux distribution and version

Linux pop-os 5.8.6-xanmod1 #0~git20200904.bf1e66e SMP PREEMPT Fri Sep 4 17:09:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## Flatpak version

Flatpak 1.6.5

## Description of the problem

I can't say for 100% that this was flatpak, but I don't know what else runs bwrap ldconfig. When I woke up this morning, my machine had a load over 700. `ps -e v` revealed many (I didn't get a count before my machine crashed) `bwrap ldconfig` processes.

![Photo Sep 07, 7 50 23 AM](https://user-images.githubusercontent.com/8588/92400254-800e9000-f0e0-11ea-9f45-a84062c41022.jpg)

Eventually my machine became completely unresponsive and I had to reboot.

## Steps to reproduce

No idea. I hope it never happens again.

**Comment by mwleeds** [comment]
Flatpak [does run that bwrap command](https://github.com/flatpak/flatpak/blob/dfde010a49ed02c966ee9050e8ea4dc75033bdb6/common/flatpak-run.c#L3710) but there's not really enough info here to debug.

**Comment by mwleeds** [comment]
Actually on closer inspection it's not clear the bwrap command Flatpak would produce matches that one exactly.
