### ISSUE TITLE
Issue Installing Flatpaks on Chrome OS

### ISSUE THREAD

**Issue by Aspiring-Writer** [flatpak/flatpak#3855]
## Linux distribution and version
Debian 9 (Linux Beta on Chrome OS)
## Flatpak version
Flatpak 1.2.5
## Description of the problem
I keep getting this error whenever I try to install a flatpak:
```
error: Nothing matches "FLATPAKNAME" in remote flathub
```
Notice, I am on a Chromebook so maybe that is the issue? I was able to use Flatpaks before though, I'm not sure what happened or if I did something.

In case this is important, I'm using the **Lenovo Chromebook C300** and **Chrome OS Version 86.0.4240.27 (Official Build) beta (32-bit).**

I have included two log files, the first one seems to have installed successfully (I have no idea why because it would not install when I tried to run it without the other commands) and the second one did not.

[flatpak.log](https://github.com/flatpak/flatpak/files/5214865/flatpak.log) (successful)  
[flatpak (2).log](https://github.com/flatpak/flatpak/files/5214866/flatpak.2.log) (unsuccessful)

## Steps to reproduce
I just try to install any flatpak that I find on the flathub repository by running the command from the website.

For example: `flatpak install flathub io.brackets.Brackets` will output:
```
Looking for matches…
error: Nothing matches io.brackets.Brackets in remote flathub
```

**Comment by refi64** [comment]
Not all Flatpaks support x86.

**Comment by Aspiring-Writer** [comment]
Oh, maybe that's why. How do I know which support x86 and which don't?

**Comment by refi64** [comment]
Nowadays the majority do not, as the semi-latest runtime has dropped support for x86.
