### ISSUE TITLE
How to handle setcap?

### ISSUE THREAD

**Issue by rderooy** [flatpak/flatpak#3858]
## Linux distribution and version
- Fedora 32
## Flatpak version
1.8.2
## Description of the problem
I'm creating a new flatpak for DOSBox-X, an enhanced dosbox fork.

So far I have managed to create the manifest, and the build is successful.
But there is one issue I don't know how to solve.

DOSBox-X has NE2000 network emulation, and for that to work it uses libpcap.
And then the following command is normally run as root when you do a make install, or install the RPM package
``
setcap cap_net_raw+ep /usr/bin/dosbox-x
``
But after adjusting the path, and trying to run that as one of post-install commands causes it to fail with a permission error, since setcap requires root.

Is there some way to handle this with flatpak, or will it simply not be possible?

**Comment by alexlarsson** [comment]
Setcap does not work in unprivileged user namespaces (which flatpak relies on). This is an intentional kernel limitation (for security), so unfortunately it cannot be fixed.
