### ISSUE TITLE
Flatpak causes my operating system to crash

### ISSUE THREAD

**Issue by Androide7461** [flatpak/flatpak#3861]
## Linux distribution and version
Linux 5.8.8-arch1-1 x86_64
## Flatpak version
Flatpak 1.8.1
## Description of the problem
After 2 days of investigating I'm pretty certain, that these crashes are being caused by flatpak.
The last weeks I was getting into developing apps with gnome-builder. Now after 3 days or so my machine kept frequently crashing if I did something that included working with flatpaks. Sometimes when I wanted to compile my project my machine just crashed. Then I was trying out multiple things and discovered that when I wanted to update my flatpaks with
```
flatpak update
```
my machine crashes after downloading them. Then I tried to remove all flatpaks from my system und updated again. Because there were no flatpaks to update it did not crash my system.
But now when I want to reinstall the flatpaks needed for gnome-builder development my system crashes again. "journalctl" outputs nothing at the time when the crash happens, so there is nothing to be found there.
## Steps to reproduce
```
flatpak update
```
... with some packages installed that needed an update (maybe the flatpaks for developing with gnome-builder themselve are causing the crash idk)

or now:
Launching gnome-builder, clicking on the button to install the needed flatpaks. (But it always feels like that the act of installing the flatpaks are causing the system to crash)

*if I say "crash" I mean that everything freezes and I have to manually restart.

## Maybe it's not flatpak
I've just had a crash, where I did nothing with flatpak what so ever. So i don't know anymore what to do. It just crashed when I was browsing. I don't know anymore. Funny thing is, that the only reliable way I can reproduce this bug is by installing flatpaks.

Right now I'm using gnome on wayland as my desktop environment. But I also installed xfce4 now, for testing reasons. And it also crashes on xfce. So I believe it's not gnome related ... . As I said: journalctl tells me nothing at all ... . It's also certainly not hardware related because I ran windows yesterday on the same machine (dual boot) for a couple of hours and nothing crashed. So it has to be at least Linux related. But it also is not the Kernel because I rolled back to 5.7.11 and the crashes also appeard. If anyone has any clues what I could search for or what could cause the problem I would really appreciate it.

**Comment by psyhigh** [comment]
I have the same problem but only with update or openshot, everythin else worls
