### ISSUE TITLE
Runtime alsa libraries built without pcm plugin support

### ISSUE THREAD

**Issue by tassig** [flatpak/flatpak#3864]
## Linux distribution and version
Linux axiom 5.7.9-Axiom

## Flatpak version
flatpak-1.4.3

## Description of the problem
We are running a novel Linux distro: Axiom, which primary uses alsa for audio backend. Pulseaudio is not provided for this system. The reasons for not using pulseaudio are out of scope at this moment.
  
Flatpak runtimes provided alsa-lib, but it is compiled without pcm plugin support. Since our audio configuration is base on plugins such as 'dmix' or 'softvol', audio simply won't work with flatpak audio applications. By default, alsa-lib compliles with pcm plugins, so there must be a reason to provide it without such support. At the moment, we apply the followong workaround: to recompile alsa-lib, with pcm plugin support, and override runtime provided one, on flatpak start. But this temporary workaround has many drawbacks. 

Do you have any particular reason not to provide alsa pcm support?

**Comment by eszlari** [comment]
You should file your bug against the runtime:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues

**Comment by tassig** [comment]
Thank you for the answer, and sorry for my late reply. 
I will close this issue and follow your link. This should be done for GNOME and KDE runtimes too.
