### ISSUE TITLE
Huge memory usage when uninstalling with --delete-data

### ISSUE THREAD

**Issue by ranisalt** [flatpak/flatpak#3869]
## Linux distribution and version

Arch Linux, latest update as of 22/Sep/2020 19:07 UTC

## Flatpak version

Flatpak 1.8.1

## Description of the problem

When uninstalling packages with `--delete-data`, `xdg-permission-store` keeps allocating memory until system locks up completely due to lack of free memory. It does not deallocate memory after it finishes uninstalling a package, so if you uninstall multiple, it will fill the entire memory.

![image](https://user-images.githubusercontent.com/1993083/93926266-d1d13000-fd06-11ea-8fbd-2e29bcee23cb.png)

## Steps to reproduce

Uninstall packages. In that case, I tried uninstalling `eog` and `steam` together, with the `--delete-data` flag. After I get asked to delete data for the packages and agree, it starts increasing memory usage.

**Comment by jkotra** [comment]
cannot reproduce with `Flatpak 1.9.1` (built from master)

**Comment by rezad1393** [comment]
I can reproduce and reported here,
https://github.com/flatpak/xdg-desktop-portal/issues/748

**Comment by hfiguiere** [comment]
not a flatpak bug.

also as a side note I was never able to reproduce.

And on the other hand, it's taking way too much time to run this.

**Comment by ranisalt** [comment]
I don't have this anymore, on a completely different system now
