### ISSUE TITLE
Fails to install org.gnome.Platform//3.36

### ISSUE THREAD

**Issue by TheAlienDrew** [flatpak/flatpak#3872]
## Linux distribution and version
Ubuntu 18.04.5 LTS (via a virtual machine in VirtualBox on Windows 10 Pro Build 2004)

## Flatpak version
Flatpak 1.0.9

## Description of the problem
Trying to install the [Dynamic Wallpaper Editor](https://flathub.org/apps/details/com.github.maoschanz.DynamicWallpaperEditor) fails when it tries to download and install `org.gnome.Platform//3.36`... and it appears that it just randomly stops downloading within the first few seconds.

## Steps to reproduce
Run the following command on a fresh ubuntu 18.04.5 install (after installing flatpak and enabling the flathub repo)
`flatpak install flathub com.github.maoschanz.DynamicWallpaperEditor`

Technically, the command you need to run to see the error is just:
`flatpak install flathub org.gnome.Platform//3.36`

## Error usually given
Here's the error I get when it tries to install `org.gnome.Platform`

```
aliendrew@ubuntu:~$ flatpak install flathub org.gnome.Platform//3.36
Installing in system:
org.gnome.Platform/x86_64/3.36                   flathub 6a3d0df724a4
org.gnome.Platform.Locale/x86_64/3.36            flathub 0d4935f35fec
org.freedesktop.Platform.GL.default/x86_64/19.08 flathub f68c8e930d04
org.gtk.Gtk3theme.Adwaita-dark/x86_64/3.22       flathub 7c055bbc0667
org.freedesktop.Platform.openh264/x86_64/2.0     flathub 73f998362a6f
Is this ok [y/n]: y
Installing: org.gnome.Platform/x86_64/3.36 from flathub
[#=                  ] Downloading files: 76/19682 7.0 MB (7.0 MB/s)
error: Failed to install org.gnome.Platform/x86_64/3.36: While pulling runtime/org.gnome.Platform/x86_64/3.36 from remote flathub: Writing content object: Corrupted file object; checksum expected='ffe5eab253c65d003e4fb18119013599e6a274869a4642837bd85ed182991376' actual='859b2c8f578627163feac27917ab9d04f332c43c5c0a53e22f4279160df0023b'
```

**Comment by Manoj-Sri** [comment]
Yeah I too have same problem, while installing gnome builder.

```
Error: While pulling runtime/org.gnome.Sdk/x86_64/3.38 from remote flathub: opcode open-splice-and-close: opcode close: Corrupted file object; checksum expected='aae5042eaa5ccbfe51f5926d3691a2f637b81b4439c3d984ee44cf20bf240c5a' actual='c353d4b281ba2b7d28370cdf54b052e63a58daaed6e3ebb1f443562edbe3673f'
^[[17;61Rerror: Failed to install org.gnome.Sdk: While pulling runtime/org.gnome.Sdk/x86_64/3.38 from remote flathub: opcode open-splice-and-close: opcode close: Corrupted file object; checksum expected='aae5042eaa5ccbfe51f5926d3691a2f637b81b4439c3d984ee44cf20bf240c5a' actual='c353d4b281ba2b7d28370cdf54b052e63a58daaed6e3ebb1f443562edbe3673f'

```

**Comment by TheEvilSkeleton** [comment]
@Manoj-Sri there's a fix for it: https://github.com/flathub/flathub/issues/1850#issuecomment-700189235

@TheAlienDrew you can try the fix above. I'm not sure if it'll work for you because your issue is for 3.36 whereas the fix was for 3.38, but it's worth a try.

**Comment by Manoj-Sri** [comment]
@TheEvilSkeleton it worked for 3.38, Thanks.
@TheAlienDrew you too try it.

**Comment by alexlarsson** [comment]
Closing this as it was a flathub issue, now fixed
