### ISSUE TITLE
Allow specifying host filesystem as runtime

### ISSUE THREAD

**Issue by cjao** [flatpak/flatpak#3874]
IDEs typically work poorly in sandboxed environment unless they were designed for the sandbox from the beginning. Pycharm is one example of this; the unofficial flatpak version has no way to make use of the system python interpreters. On the other hand, the officially supported snap distribution of Pycharm uses snap's "classic" mode (a.k.a. no sandboxing at all), which essentially runs the program in the host's mount namespace.

Allowing an option like `--filesystem=/usr` would essentially replicate this "classic" mode. Is something like this reasonable?

**Comment by alexlarsson** [comment]
No, it is not reasonable, because it will not work. There are zero guarantees that what is on the system /usr is compatible with your app. If this was not a problem then flatpak need not exist at all, as you could just e.g. run the arch binaries on a debian 7 system.
