### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by VosaXalo** [flatpak/flatpak#3895]
## Linux distribution and version
KDE Neon 20.04
## Flatpak version
1.8.2
## Description of the problem
When I run the command
`flatpak update --system`
the list of updatable packages is printed, then after confirming that I want to update, nothing happens.
The message "Updating 1/22..." shows up, but the process never goes on.

The result of the command
`flatpak remotes -d`
on my system is the following:
```
Name    Title   URL                          Collection ID Filter Priority Options … … Homepage Icon
flathub Flathub https://dl.flathub.org/repo/ -             -      1        system  … … -        -
```
## Steps to reproduce
1) Open a terminal
2) Run the command `flatpak update --system`
3) Confirm the update with "Y"
4) The message "Updating 1/22" is printed
5) Instead of starting to download the updates, nothing happens. Here a screenshot:
![Screenshot_20201009_150524](https://user-images.githubusercontent.com/6298140/95586466-00f2db80-0a41-11eb-8941-774ec193bfb7.png)
    ==> usually this takes a minute at maximum, but now the process never ends.

**Comment by VosaXalo** [comment]
@mwleeds This is the entire Konsole window:
![Screenshot_20201010_165134](https://user-images.githubusercontent.com/6298140/95658195-ea1fb800-0b18-11eb-92d7-f7bbc4158408.png)

**Comment by VosaXalo** [comment]
If I use the command
`flatpak update -v`
This is the output:
```
Proceed with these changes to the system installation? [Y/n]: y
Updating 1/26…                                                    F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
```

And the process never goes on.
Hope this can help.

**Comment by VosaXalo** [comment]
Good news!
I have updated my system and made a reboot. Now the update process works again. Really happy for that :-)
So, this support ticket for me can be closed

Thanks

**Comment by eszlari** [comment]
You are free to close the issue, if you think it is solved.
