### ISSUE TITLE
Error when trying to update to nvidia-450-80-02

### ISSUE THREAD

**Issue by Faidros1** [flatpak/flatpak#3899]
## Linux distribution and version: 
Ubuntu 20.10
## Flatpak version: 
1.8.2
## Description of the problem:
I get

Warning: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

when flatpak tries to update nvidia-450-66 to nvidia-450-80

## Steps to reproduce:
flatpak update

when nvidia-450-66 is already installed.

**Comment by eszlari** [comment]
Maybe open the issue under: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues

**Comment by Faidros1** [comment]
Thanks!
