### ISSUE TITLE
flatpak-builder: Report error when base runtime or its extensions is partially installed

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#390]
After cleaning up my build directories and trying to generate the runtime again, I get the following error message in the first component that installs locales.

```
Makefile:126: recipe for target 'install' failed
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /usr/share/locale/af/LC_MESSAGES.  Maybe need
  administrative privileges.
```

**Comment by alexlarsson** [comment]
Ah, sorry i didn't see this before.
The reason for this is that you have a partial org.freedesktop.Sdk.Locale installed.
I.e. if you flatpak list -d --runtime it'll say something like:
```
org.freedesktop.Sdk.Locale/x86_64/1.4      gnome      15a25faa6d8a - 512 bytes user /en
```
See the /en at the end? That means it just has the english subdirectory.
To build a full runtime you need all the directories of the locale extension.
Easiest is to uninstall and re-install the .Locale part only.

**Comment by aleixpol** [comment]
Hi,
I removed the ones that had a /en and reinstalled the `org.freedesktop.*`, my runtimes look like this now:
```
org.freedesktop.Platform.Locale/x86_64/1.4 gnome    9eef015785ce - 399,0 MB system 
org.freedesktop.Platform/x86_64/1.4        gnome    7e37145d501c - 532,1 MB system 
org.freedesktop.Sdk.Debug/x86_64/1.4       gnome    4bbc1c0ff61e - 2,5 GB   system 
org.freedesktop.Sdk.Locale/x86_64/1.4      gnome    15a25faa6d8a - 399,0 MB system 
org.freedesktop.Sdk/x86_64/1.4             gnome    6fe05489235b - 1,3 GB   system 
org.kde.Platform/x86_64/master             kdelocal a5f977566dc2 - 703,9 MB system 
org.kde.Sdk/x86_64/master                  kdelocal 357d79268d17 - 1,5 GB   system 
```
But I'm still getting the same error.

**Comment by grulja** [comment]
I can confirm that reinstalling locale runtimes worked for me. Alex, you need to remove completely your previous build.

**Comment by cmollekopf** [comment]
I'm also still running into the same issue. I removed all /en specific Locale runtimes with "flatpak --user uninstall ..." then installed them again so I get about the same listing as @aleixpol. When I then try to build the kde runtime (also with --user) I still get the original error.

@grulja How do I remove my previous build completely?

**Comment by aleixpol** [comment]
I can confirm it got fixed, closing the issue for now.

@cmollekopf I added a `make clean` target in the project, so you can reproduce the fix. :)

**Comment by aleixpol** [comment]
FWIW, it still should give an error message or something, otherwise it's really to figure out.
(or well, it means ask Alexander to figure out :D)
