### ISSUE TITLE
The plugin has been renamed - So what?  

### ISSUE THREAD

**Issue by dln949** [flatpak/flatpak#3903]
Ubuntu 18.04.5, Flatpak 1.8.2

When I run the command flatpak update, I get this seemingly useless output:  

Looking for updates…
Info: org.freedesktop.LinuxAudio.LadspaPlugins.swh is end-of-life, with reason: The plugin has been renamed to org.freedesktop.LinuxAudio.Plugins.swh
Nothing to do.

I know it says, "Nothing to do" - nevertheless, my question is, What should I do?  

I don't know what it is telling me, nor even  which flatpak application is at issue.  

And - How do I make this message go away?  Or, do I just have to live with it forever?  And over the years these kinds of messages will simply pile up?  

Can you see my bewilderment?  

Thanks for any help with this.

**Comment by mwleeds** [comment]
Agreed, that's not a great UX

**Comment by dln949** [comment]
So, how do I make the message go away?  Or, is it there forever?

**Comment by eszlari** [comment]
`flatpak uninstall --unused `

**Comment by dln949** [comment]
That worked, thanks.

**Comment by mwleeds** [comment]
This should hopefully be fixed by #3871
