### ISSUE TITLE
How to restore the remote named "gnome"

### ISSUE THREAD

**Issue by dln949** [flatpak/flatpak#3904]
Ubuntu 18.04.5, Flatpak 1.8.2

While trying to figure out a different issue, I think I accidentally deleted a remote, and now I don't know how to add it back.  

When I ran the command flatpak remotes, I used to get this output:  

Name    Options
flathub system
gnome   system

But, after going through some flatpak commands - that I admit I do not fully understand - I now see that the output of that same command is different:  

Name    Options
flathub system

As you can see, the "gnome" remote is missing.  

Well, I thought, that's no problem, I'll just add back that remote, I had read that the command is flatpak remote-add, so I tried this:  

flatpak remote-add gnome

But, it didn't like that, it seems I need the URL of the remote called "gnome".  

The problem is, I don't know what that URL is.  

And, now I don't know what problems will be created for which apps by having accidentally deleted the "gnome" remote.  

How do I find the URL for the "gnome" remote so I can add it back?  

Thanks.

**Comment by mwleeds** [comment]
You probably don't want to add that remote back as [it's no longer an active repository](https://www.reddit.com/r/gnome/comments/dut47k/what_happened_to_sdkgnomeorg_flatpak_repos/). If you have runtimes installed from it, uninstall them and install from Flathub instead. See also #3227

Is that missing remote causing some issue for you, like warnings in the output of a command?

**Comment by dln949** [comment]
No, not causing any issues (that I am aware of).  I just saw it go away and feared that unknown horrible things would happen.
