### ISSUE TITLE
gnome-software-plugin-flatpak install issues debian bullseye

### ISSUE THREAD

**Issue by mnt-grrrl** [flatpak/flatpak#3914]
## Linux distribution and version
Debian bullseye
## Flatpak version
1.8.2-1 
## Description of the problem
apt install flatpak
ran fine
but apt install gnome-software-plugin-flatpak
gave me errors
apt-get -f install returns:
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up python3-aptdaemon (1.1.1+bzr982-0ubuntu19) ...
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 1570
    async = reply_handler and error_handler
          ^
SyntaxError: invalid syntax

dpkg: error processing package python3-aptdaemon (--configure):
 installed python3-aptdaemon package post-installation script subprocess returne
d error exit status 1
dpkg: dependency problems prevent configuration of python3-aptdaemon.gtk3widgets
:
 python3-aptdaemon.gtk3widgets depends on python3-aptdaemon (= 1.1.1+bzr982-0ubu
ntu19); however:
  Package python3-aptdaemon is not configured yet.

dpkg: error processing package python3-aptdaemon.gtk3widgets (--configure):
 dependency problems - leaving unconfigured

## Steps to reproduce
apt install flatpak
but apt install gnome-software-plugin-flatpak

**Comment by mwleeds** [comment]
You should [report this bug to Debian](https://www.debian.org/Bugs/Reporting). It seems like a packaging bug.
