### ISSUE TITLE
How to start an application maximized?

### ISSUE THREAD

**Issue by anagram3k** [flatpak/flatpak#3916]
## Linux distribution and version
Ubuntu 20.04
## Flatpak version
 Flatpak 1.6.5
## Description of the problem

I did search the web and looked at the command reference in https://docs.flatpak.org but didn't find how to start an application in a maximized state. 
It is possible?

**Comment by refi64** [comment]
Flatpak doesn't do anything special here, so it would presumably be identical to how you'd start a given app maximized if it were not a Flatpak.
