### ISSUE TITLE
Flatpak applications do not start after system update for Deepin V20

### ISSUE THREAD

**Issue by pidroo1968** [flatpak/flatpak#3918]
## Description of the problem 
     After automatic system updating Deepin V20 on Oct 22, 2020 All flatpak application won't star and
      even freezes the computer

**Comment by mwleeds** [comment]
Probably something to report to Deepin, unless there's evidence this is caused by a bug in Flatpak.

**Comment by voncamel** [comment]
me too,i have already uninstalled all flatpak apps

**Comment by abmBispo** [comment]
The same is happening to me in Deepin v20 (community 1003), any good news @pidroo1968 ?

**Comment by fariquelme** [comment]
Same issue here, i'm running dde-kwin. As soon as i open a flatpak app the desktop environment freezes. Has anyone been able to solve this issue or find a workaround ?

**Comment by hfiguiere** [comment]
lack of info. nothing actionable on flatpak side.
