### ISSUE TITLE
bubble wrap fails at launch of any flatpak app

### ISSUE THREAD

**Issue by kawaiiamber** [flatpak/flatpak#3920]
## Linux distro
VOID Linux
## Flatpak version
Flatpak 1.8.2_1
## Steps to reproduce 
from flathub
flatpak install com.discordapp.Discord
flatpak run com.discordapp.Discord
bwrap: Can't mkdir parents for /run/host/fonts: Permission denied

Also, not sure if relavent, but also asks for authentication with my password when I try installing discord. I've looked at other closed issues, but those steps do not fix the problem, so not a duplicate. I've tried everything
flatpak repair com.discordapp.Discord
xbps-install -Sf flatpak
etc

**Comment by mwleeds** [comment]
Have you tried reporting this bug to your linux distribution?

**Comment by kawaiiamber** [comment]
Not yet. I'm fairly confident this is with flatpak. If I went to VOID I imagine they would have asked if I have tried reporting it to flatpak. I just remembered something else to reproduce the bug. I was trying to use fcitx and ran this command
`$ sudo flatpak override --env=GT_IM_MODULE="fcitx" --filesystem=/ com.discordapp.Discord`
I've tried overriding back to $HOME, nothing seems to work. Even after trying to purge flatpak and reinstall it, it still seems to remember it somehow. I've clearned .var, .config, .local, .cache.

**Comment by kawaiiamber** [comment]
I am getting a different issue at this point. It seems to be failing to create directories stating that it lacks permission. I'll try reporting this to distro. I'll close and if it's truly something with flatpak reopen as opposed to making a new issue if I can.
