### ISSUE TITLE
Error: Wrong size for extra data

### ISSUE THREAD

**Issue by krishnaTORQUE** [flatpak/flatpak#3954]
## Linux distribution and version
Ubuntu 20.04

## Flatpak version
1.8.2

## Description of the problem
Error: Wrong size for extra data https://dl.google.com/dl/android/studio/ide-zips/4.1.1.0/android-studio-ide-201.6953283-linux.tar.gz
**error**: There were one or more errors

_This is error I am getting when updating only android studio_

## Steps to reproduce
Flatpak update -y

**Comment by sonnyp** [comment]
This was an issue with the android-studio manifest from flathub

Was fixed in https://github.com/flathub/com.google.AndroidStudio/pull/92

Please try again and close.

**Comment by krishnaTORQUE** [comment]
thank you
yes this issue has been fixed

**Comment by Marypoppins-oss** [comment]
Run in konsole it worked for me.

flatpack remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
