### ISSUE TITLE
Android Studio update failed and can't install again

### ISSUE THREAD

**Issue by expl0r3rgu1** [flatpak/flatpak#3956]
## Description of the problem: I was updating Android Studio through the Pop Store and it was stuck. I canceled the update and tried again. It was stuck again. So I tried to uninstall and reinstall Android Studio. Obviously, it didn't work.

This is the point it gets stuck.
![Screenshot from 2020-11-12 19-36-38](https://user-images.githubusercontent.com/35142289/98981974-f2578280-251e-11eb-88f3-0f1163d33bb2.png)

I know I can install it via web and via snap but I'd like to be able to use the integrated store.

**Comment by alexlarsson** [comment]
Can you try `flatpak repair` first?

**Comment by alexlarsson** [comment]
Oh, also, i think this might actually work, there just is a bug with progression reporting for extra data, and its downloading 949 meg from google as extra-data.

**Comment by expl0r3rgu1** [comment]
> Can you try `flatpak repair` first?

I tried:
`flatpak repair`
`flatpak repair --dry-run`
`flatpak uninstall --unused` because I saw there were some traces like com.google.AndroidStudio.local
nothing worked.
The attached screenshot was taken after all of this.
