### ISSUE TITLE
allow access to /dev/ttyACM0

### ISSUE THREAD

**Issue by doniks** [flatpak/flatpak#3959]
## Linux distribution and version
ubuntu 20.10
## Flatpak version
1.8.2
## Description of the problem
I would like to allow access to serial uart adapters like /dev/ttyACM0, /dev/ttyACM1, /dev/ttyUSB0, etc. As discussed here: https://stackoverflow.com/questions/41252334/accessing-serial-ports-with-an-application-runs-in-flatpak 

The only solution I could find is to allow `--device=all` access. If I understand it right, this is a very big hammer, opening a lot from the sandbox. Is there a way to give more fine grained access?

## Steps to reproduce
(this repro is a bit specific, sorry for that, but I think the description above is hopefully clear enough so you can make a simpler reproduction)
- connect a serial uart device (e.g., https://pycom.io/product/expansion-board-3-0/,  or https://www.sparkfun.com/products/12731 or an arduino)
- make sure a /dev/ttyACMx or /dev/ttyUSBx got created
- depending on your os, make sure you have access (on ubuntu you have to add your user to group dialout)
- install atom editor flatpak 
- install pymakr plugin in atom https://docs.pycom.io/gettingstarted/software/atom/
=> observe that pymakr cannot access /dev/ttyACM0
- close atom 
- start it with `flatpak run --device=all io.atom.Atom `
=> observe that pymakr can access it now, but probably has access to everything else as well

**Comment by alexlarsson** [comment]
There is no other approach atm, and it is in fact quite tricky to add one as serial nodes are dynamic and the /dev setup only happes once, on sandbox setup. So, `--dev=all` is what you have to use. Its not necessarily such a big hammer as you'd think though, as device nodes there are protected by regular unix permissions that denies use for most of them.

**Comment by alexlarsson** [comment]
Conceptually we could add a portal for serial access, but that would require some changes to how apps open the serial port.

**Comment by doniks** [comment]
OK. Thanks for the explanation!

**Comment by eternal-sorrow** [comment]
This is a shame. Flatpak should add an option to use a specific device in the sandbox.

**Comment by eternal-sorrow** [comment]
Bubblewrap has `--dev-bind` for this.
