### ISSUE TITLE
Themes should install automatically

### ISSUE THREAD

**Issue by arteeh** [flatpak/flatpak#3960]
## Linux distribution and version
Debian Testing

## Flatpak version
1.8.2-3

## Description of the problem
When I switch to Adwaita Dark on GNOME and launch an app, it's still in my old theme. I have to run `flatpak update` in order for Flatpak to install their version of the GTK theme, and as a result for all my apps to be in the new theme. As a user I expect all my apps to immediately be in the new theme as soon as I switch. This may be even more important in distros and/or future versions of GNOME that include a dark mode switch in Settings.

Therefore with Flatpak's current approach to themes in mind, I think Flatpak should include some kind of background process that watches for a GTK theme change, and automatically installs the new theme if it wasn't already installed, and if the theme is in the Flatpak repos.

## Steps to reproduce
- In Tweaks, switch to a GTK theme that isn't already installed by Flatpak
- Open an app that's a Flatpak (this app should still be in the old theme)
- Close the app
- Run `flatpak update`
- Reopen the same app (it should now be in the new theme)

**Comment by alexlarsson** [comment]
I understand how this would be nice, but its just not possible for flatpak to know that something else change the theme and trigger any code to run.
