### ISSUE TITLE
"flatpak run" is not intended to be ran with sudo

### ISSUE THREAD

**Issue by devurandom** [flatpak/flatpak#3963]
## Linux distribution and version

CentOS 8.2.2004

## Flatpak version

1.6.2

## Description of the problem

`sudo -u ... flatpak run ...` results in `"flatpak run" is not intended to be ran with sudo` and there is no other obvious way to run a flatpak as another user.

## Steps to reproduce

1. `flatpak --system install ...`
2. `sudo -u ... flatpak run ...`

**Comment by alexlarsson** [comment]
The problem is that if you run under sudo various env vars point to the old users paths and the "new" user writes and reads files there which cause problems later.

**Comment by alexlarsson** [comment]
You should be able to e.g. "su -l" to get a proper shell for a different user instead.

**Comment by devurandom** [comment]
@alexlarsson Thank you for your response. In #3975 I try to improve the error message by guiding the user towards the correct way to call `flatpak run` as another user.
