### ISSUE TITLE
Auto-installed extensions also drag Sources

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#3973]
`flatpak-1.8.2-2.fc33.x86_64`

Installing `org.gnome.Totem` from Flathub should also drag the "auto-installed" `org.gnome.Totem.Videosite.YouTubeDl` extension, but that ends up also pulling the sources "application" `org.gnome.Totem.Videosite.YouTubeDl.Sources`.

The same happens with some other auto-installed extensions, like the Qt themes.

eg.
```sh
$ flatpak list -a | grep Sources
Sources	org.gnome.Totem.Videosite.YouTubeDl.Sources		stable	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QGnomePlatform.Sources		5.12	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QGnomePlatform.Sources		5.13	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QGnomePlatform.Sources		5.14	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QGnomePlatform.Sources		5.15	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QtSNI.Sources		5.12	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QtSNI.Sources		5.14	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QtSNI.Sources		5.15	x86_64	flathub	system
Sources	org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources		5.12	x86_64	flathub	system
Sources	org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources		5.13	x86_64	flathub	system
Sources	org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources		5.14	x86_64	flathub	system
Sources	org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources		5.15	x86_64	flathub	system
```

**Comment by alexlarsson** [comment]
This is pretty weird, .Sources refs don't even have an extension point, so they should not ever be auto-installed for anything.

**Comment by hadess** [comment]
In my case, `org.gnome.Totem.Videosite.YouTubeDl.Sources` got auto-installed at the same time as `org.gnome.Totem.Videosite.YouTubeDl` got autoinstalled. Is it "globbing" all the extensions and pulling those in?

This is the definition for the extension point:
https://github.com/flathub/org.gnome.Totem/blob/master/org.gnome.Totem.json#L59-L65
and the extension itself:
https://github.com/flathub/org.gnome.Totem.Videosite.YouTubeDl/blob/master/org.gnome.Totem.Videosite.YouTubeDl.yaml
