### ISSUE TITLE
"Invalid AUTH line, aborting" message when trying to request a D-Bus service name with sd-bus

### ISSUE THREAD

**Issue by X-m7** [flatpak/flatpak#3978]
## Linux distribution and version
Fedora Silverblue 33

## Flatpak version
1.8.2, also with 1.8.3

## Description of the problem
I've been trying to get [cmus](https://github.com/cmus/cmus) to work in a flatpak, and I haven't been able to get its MPRIS support working without granting access to the entire session bus. When I run it with `--log-session-bus`, I see this message: `Invalid AUTH line, aborting`, while cmus itself reports that the connection has been reset by peer (which is what the failing function returned, ECONNRESET). The specific line that fails in cmus' code is [here](https://github.com/cmus/cmus/blob/d1290d50f9f7585c43b9e1326c0d6d1e0b4583f6/mpris.c#L503).

For some context, cmus uses sd-bus (systemd's dbus library), and here is the doc [page](https://www.freedesktop.org/software/systemd/man/sd_bus_request_name.html) for the function that failed, which is `sd_bus_request_name`. Also, I noticed that the `Invalid AUTH line, aborting` message appears in commit 52346bf187b5a7f1c0fe9075b328b7ad6abe78f6 as well as in [xdg-dbus-proxy](https://github.com/flatpak/xdg-dbus-proxy/blob/15d2803039b1964dc95112d6d1624a291d338c4e/flatpak-proxy.c#L2652) (the latter is a copy of the former according to the commit message there), and I couldn't find any references to anyone else getting that error message.

The specific service name has already been granted in the manifest (org.mpris.MediaPlayer2.cmus), and as far as I can tell it is the same as the one the code is requesting.

## Steps to reproduce
1. Get the manifest and needed patches from [here](https://github.com/X-m7/flathub/tree/cmus) (the dependencies are all optional, the only required additional file is the configure patch)
2. Build and install the flatpak (feel free to cut the filesystem permissions and pulseaudio for testing, the error occurs regardless of them for me)
3. Run it with `--nosocket=session-bus` (or remove `--socket=session-bus` from the manifest before building)
4. To see if the `Invalid AUTH line, aborting` message appears run with `--log-session-bus` too

**Comment by alexlarsson** [comment]
I wonder if this is reltated to https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1403

**Comment by X-m7** [comment]
I noticed that the systemd commit referenced there was first added in v242-rc1 (the commit itself was in March 2019), so I tried recompiling cmus with the freedesktop 18.08 runtime (which has systemd v241 according to its manifest.json), and I still get the same error.

**Comment by refi64** [comment]
Pretty sure this is flatpak/xdg-dbus-proxy#21.

**Comment by X-m7** [comment]
Oh, in one if the linked/mentioned issues (fcitx/fcitx5#99) the same behaviour is described as here (same error message, also using sd-bus, app reports unable to request bus name), unfortunately the workaround they found there is to simply not use sd-bus, sigh. I wonder why my search for the error message (Invalid AUTH line, aborting) didn't show that (tried Google, Bing and DDG), I guess search engines don't bother with code snippets/blocks.

I suppose I'll just close this then, since it sure looks like it's either systemd/systemd#16610 or flatpak/xdg-dbus-proxy#21.
