### ISSUE TITLE
Consider combining summary.idx with summary.idx.sig

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#3983]
I notice that the new summary design in 1.9.1 has the summary index in `summary.idx`, and a detached GPG signature in `summary.idx.sig`.

The apt package manager used to have a similar design for the top-level index of a repository (in our case the filenames are `Release` and `Release.gpg`), and Debian/Ubuntu have had trouble in the past with the cache lifetime of the `Release` file and the cache lifetime of the signature getting out of sync, leading to failed signature verification. As a result, recent apt tooling combines them into the same file, `InRelease`: in apt it's a "clearsigned" GPG message as produced by `gpg --clearsign -a`, similar to traditional non-MIME email signing, which means non-GPG-capable tools can still strip the GPG headers and read the actual content, but a binary GPG message as produced by `gpg -s` would also be reasonable.

Perhaps Flatpak should do similarly? This would mean that when the summary index is updated, CDNs and web proxies that might have been caching it would atomically switch from the old index to the new index, with no period in which it might be serving the old index with the new signature or vice versa.

If this change happens, it should probably happen soon, so that Flatpak repository providers don't have to keep serving `summary.idx.sig` forever.

**Comment by smcv** [comment]
https://github.com/ostreedev/ostree/issues/2250#issuecomment-740701041 has an alternative approach to making the summary update as close to atomic as possible (addressing signatures by the hash of the signed object).

**Comment by alexlarsson** [comment]
@smcv Yeah, made that change in the above PR if you want to look at it.
