### ISSUE TITLE
Raspberry Pi install missing directories

### ISSUE THREAD

**Issue by ingfabby** [flatpak/flatpak#3987]
## Linux distribution and version
Raspberry Pi OS
## Flatpak version
Flatpak 1.0
## Description of the problem
I'm trying to install Repomaker on a Raspberry Pi, the whole install process runs smoothly but when I try to run Repomaker ( using this command : flatpak run --runtime=org.gnome.Sdk org.fdroid.Repomaker ) I'm getting this error:
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/pi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: runtime/org.gnome.Sdk/arm/3.36 not installed

**Comment by sebastianwagner** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906288
https://bugs.launchpad.net/debian/+source/lxde-common/+bug/1905289

**Comment by mwleeds** [comment]
>error: runtime/org.gnome.Sdk/arm/3.36 not installed

What happens if you `flatpak install runtime/org.gnome.Sdk/arm/3.36`?

**Comment by hfiguiere** [comment]
I think this issue was fixed with https://github.com/RPi-Distro/raspberrypi-ui-mods/pull/30

The problem was that their patches did override XDG_DATA_DIRS. This change is in the latest Buster udpdate and in Bullseye.
