### ISSUE TITLE
Add flathub repository by default to installed package

### ISSUE THREAD

**Issue by soredake** [flatpak/flatpak#3989]
## Linux distribution and version
Kubuntu 20.10
## Flatpak version
Flatpak 1.8.2
## Description of the problem
This will allow using flatpak out of the box, without adding the repository manually with command `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

related: https://bugs.launchpad.net/ubuntu/+source/flatpak/+bug/1903706
## Steps to reproduce
Install flatpak, then try to install something from flathub without adding flathub repo manually.

**Comment by smcv** [comment]
Beware that not all distributions are going to want this. I have considered enabling the Flathub repo by default in the Debian package (which is almost certainly what you end up using a recompiled version of in Kubuntu), but if I did, I'd immediately get pulled into a tedious argument about whether that constitutes a dependency on software outside Debian, and/or an encouragement to install non-free software. Even if I was eventually able to get consensus that it's fine, I'd have to waste a lot of time on internal politics to reach that point, and I just don't have enough energy to have that argument.

Having the Flathub repo available-but-disabled by default might be considered more acceptable, although, again, I suspect I'd have to sink a lot of time into tedious mailing list threads before reaching consensus.

If this isn't handled carefully, distributions that are less pragmatic and more Free-Software-idealist than Debian (such as anything approved by GNU) would almost certainly see Flathub's not-100%-Free-Software nature as a reason to remove Flatpak completely, which seems like the opposite of what we want.

**Comment by Arxcis** [comment]
Well put @smcv . I think the correct approach for `flatpak`, is to stay neutral on this matter, and let each distro decide. Already we have Ubuntu with no default, Fedora and Elementary OS with their own remotes as default, Pop OS and Clear Linux with `flathub.org` as default (last time I checked), so their are clearly different oppinions out there.

**Comment by alexlarsson** [comment]
It is up to each distro to chose to install any particular repo or not, and they can already do so in their flatpak package (or otherwise) if they want. Flatpak is not in the business of controlling what app sources a distro should ship by default, so we add none by default.
