### ISSUE TITLE
Password request to update system-wide flatpak when malcontent enabled

### ISSUE THREAD

**Issue by bigon** [flatpak/flatpak#3995]
Hello,

With flatpack from debian unstable (1.8.3, with malcontent enabled) and system-wide installed flatpak, I get a polkit password request ("Authentication is required to install software which is restricted by your parental controls policy") because gnome-software is trying to update them. This is quite annoying as the password just pops-up without user interactions.

I'm the only user on my system and there is obviously no age restriction set

Looks like endless has patched their rule file: https://github.com/endlessm/flatpak/blob/master/system-helper/org.freedesktop.Flatpak.rules.in

CC: @smcv @pwithnall

**Comment by smcv** [comment]
Note that normal Debian systems are using polkit from the distant past, with .pkla files. However, I looked at [updating our .pkla file to be equivalent to upstream's JavaScript file](https://salsa.debian.org/debian/flatpak/-/merge_requests/3) and I don't think it would actually make any difference: `org.freedesktop.Flatpak.override-parental-controls` is configured with `auth_admin` (meaning ask for a privileged user's password) either way.

@bigon, are you using polkit 0.105 with .pkla files, or polkit 0.11x from experimental with JavaScript? If you are using 0.105, have you tried the merge request linked here?

**Comment by smcv** [comment]
I think the UX I would have expected is for members of the privileged group (in Debian that's `sudo`, although in upstream Flatpak it's build-time configurable) to return `yes` for `org.freedesktop.Flatpak.override-parental-controls`, either when active or at all times. That would mean:

* privileged users are not prompted for a password 
* unprivileged users are prompted for a privileged user's password

That's similar to one of the configurations described in `/usr/share/polkit-1/actions/org.freedesktop.Flatpak.policy`, but is not the default. @pwithnall, can you remember why that isn't the case?

**Comment by pwithnall** [comment]
flatpak only checks the `override-parental-controls` action in polkit if you don’t meet the parental controls policy. It’s not checked unconditionally. What’s the output of `malcontent-client get-app-filter $USER`? Is the software being updated in the system repo, or the user repo?

See [the big comment in `o.fd.Flatpak.policy.in`](https://github.com/flatpak/flatpak/blob/e08e8344db567c348dff8a6de29ebcabac6351db/system-helper/org.freedesktop.Flatpak.policy.in#L239-L286). I think at the moment we have the third configuration by default. We could have one of the other two.

**Comment by bigon** [comment]
@pwithnall 

```
bigon@edoras:~$ malcontent-client get-app-filter bigon
App filter for user bigon retrieved:
  (No OARS values)
App installation is allowed to user repository
App installation is disallowed to system repository
```

The problem could be: "App installation is disallowed to system repository?

Why is this the case? IIRC I didn't change anything here

**Comment by pwithnall** [comment]
> The problem could be: "App installation is disallowed to system repository?

Could be. You can test by changing those settings: `malcontent-client set-app-filter bigon --allow-user-installation --allow-system-installation` and see what gnome-software does.

> Why is this the case? IIRC I didn't change anything here

I think those are the default settings in malcontent, and we might need to update them. They are from a time when I thought user repositories were more widely used than they actually are.

**Comment by bigon** [comment]
OK I allowed "system-installation" and the request for the password is gone

I think it should be allowed by default as `gnome-software` is installing packages at system level anyway(?)

**Comment by pwithnall** [comment]
> OK I allowed "system-installation" and the request for the password is gone

:+1: Thanks for testing

> I think it should be allowed by default as `gnome-software` is installing packages at system level anyway(?)

Probably, although gnome-software just installs packages wherever the flatpak repo is configured. So it really depends on where flatpak/the distro have pre-configured repos.

I’ll put a fix together soon

**Comment by pwithnall** [comment]
Fix available here: https://gitlab.freedesktop.org/pwithnall/malcontent/-/merge_requests/111

**Comment by pwithnall** [comment]
I’m going to close this issue since the fix is being tracked on gitlab.fdo, and won’t close this one automatically.
