### ISSUE TITLE
Investigate libva/VDPAU support

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#4]
_From @hadess on May 9, 2016 16:7_

Similar to the joystick, or optical drives support, we'll need to investigate libva/VDPAU support.

_Copied from original issue: alexlarsson/xdg-app#158_

**Comment by alexlarsson** [comment]
_From @gcampax on May 9, 2016 16:42_

Shouldn't be handled like GL?
As far opening the device, you only need /dev/dri, which you have.

By the way, the intel libva driver is not built, but the vdpau-to-libva adapters (from mesa) are built, and so are the gallium vdpau drivers. Which means it should "just work" on radeon/nvidia with the free drivers.

**Comment by alexlarsson** [comment]
I don't really know how vdpau stuff works, but i *think* I added the right modules for this to the fd.o runtimes, and with dri access this should "just work". But, i've never tested it.

Didn't know we were missing an intel driver. We should add that then.

**Comment by alexlarsson** [comment]
_From @hadess on May 10, 2016 8:10_

Then we'd likely need an extension point for that, as the Intel libva driver apparently contains patent encumbered code.

**Comment by alexlarsson** [comment]
ah...

**Comment by TingPing** [comment]
Just as an update only the Intel libva driver isn't shipped, which as I understand it depends upon a non-free version of libva. There is an upstream issue over working with the free one though: https://github.com/Intel-Media-SDK/MediaSDK/issues/10

**Comment by hadess** [comment]
> Just as an update only the Intel libva driver isn't shipped, which as I understand it depends upon a non-free version of libva.

That's not the problem. The free version of the Intel libva driver is patent encumbered. The proprietary library and drivers didn't even come into question.

**Comment by TingPing** [comment]
Ah, it still may be acceptable for flathub to distribute though?

**Comment by hadess** [comment]
That depends on Flathub's policies, it's not a technical problem...

**Comment by MatMaul** [comment]
So the VAAPI Intel driver is considered patent encumbered ? Even if most of the decoding happens on the hardware accelerator ? What is the legal difference with the gallium VDPAU driver then ? Thanks.

**Comment by hadess** [comment]
> So the VAAPI Intel driver is considered patent encumbered ? Even if most of the decoding happens on the hardware accelerator ?

Yes, because there's an MPEG parser that's still very much in the sources. That might or might not still be a problem, ask a lawyer.

**Comment by MatMaul** [comment]
What a joke... I would pointlessly argue that I don't think they have any patent on the parsing, it would imply that they found a new method to improve the parsing that you couldn't avoid when implementing the standard and I don't think parsing is complicated enough to allow that. Anyway, I said pointlessly because I can't prove it without a million dollars to hire experts and lawyers so...

Back to sane territory : I implemented an extension point & extension for that yesterday, I'll send a PR soon.

**Comment by MatMaul** [comment]
BTW my rant was about the insanity of the patents system especially in the US, not the policy ;)

**Comment by TingPing** [comment]
For what its worth Flathub already ships encumbered ffmpeg codecs, so I don't think there is a policy issue of hosting this extension there.

**Comment by TingPing** [comment]
So this should all be fixed now, the Intel VAAPI driver is packaged and hosted on flathub and the Nvidia VDPAU driver is now correctly packaged.
