### ISSUE TITLE
builder: Add meson support

### ISSUE THREAD

**Issue by thiblahute** [flatpak/flatpak#400]
The [meson](http://mesonbuild.com) build system is becoming more and more popular and various GNOME modules start to us it, flatpak-builder should support it natively the same way as it supports autotools and cmake.

**Comment by TingPing** [comment]
I have an ugly branch that adds it similar to `cmake` support but really this sort of depends on #39 happening so the build system is more abstracted out.

**Comment by alexlarsson** [comment]
I agree with both of you, would anyone want to look at this? (starting with https://github.com/flatpak/flatpak/issues/39)

**Comment by TingPing** [comment]
I played with the idea but the main issue is I didn't want to break the existing format.

**Comment by alexlarsson** [comment]
There is no need to break anything, just keep "cmake: true" an alias for "buildsystem: cmake".

**Comment by TingPing** [comment]
Sure but I was more thinking about changing the autotools options which is a more invasive change. Properties like `rm-configure`, `no-autogen`, `make-args`, etc are all extremely autotools specific. For the code it is currently just a giant if else block for each and It would be nice to pull that out into an interface and each build system would expose its own options.

The format would be something like:

```json
{
  "buildsystem": "autotools",
  "buildsystem-options": {
     "no-autogen": true,
  }
}
```

Also you will need to add `ninja` and `meson` to the runtime.

**Comment by alexlarsson** [comment]
True...

**Comment by alexlarsson** [comment]
Actually, in the "common" case that is kinda verbose though. It will add a lot of extra lines to "typical" modules.
