### ISSUE TITLE
flatpak 1.8.3 asserting on ppc64le

### ISSUE THREAD

**Issue by nanonyme** [flatpak/flatpak#4000]
## Linux distribution and version
freedesktop-sdk 20.08
## Flatpak version
flatpak 1.8.3
## Description of the problem
```
flatpak:ERROR:./common/flatpak-variant-impl-private.h:2223:var_sparse_cache_entry_get_key: assertion failed: (end < v.size)
Bail out! flatpak:ERROR:./common/flatpak-variant-impl-private.h:2223:var_sparse_cache_entry_get_key: assertion failed: (end < v.size)
```
## Steps to reproduce
Requires ppc64le machine so involved to reproduce. If one exists, https://gitlab.com/freedesktop-sdk/freedesktop-sdk 
Install buildstream 1.6.1 and bst-external and run`make export`

**Comment by nanonyme** [comment]
Looks like the previous flatpak version we used which did work was 1.6.5.

**Comment by alexlarsson** [comment]
This looks like a dup of https://github.com/flatpak/flatpak/issues/3503 ?
