### ISSUE TITLE
How can apps like htop, top, dstat, conky run without read access to pids dirs in /proc?

### ISSUE THREAD

**Issue by iphands** [flatpak/flatpak#4001]
## Linux distribution and version
Clear Linux 5.9.9-1001.native

## Flatpak version
Flatpak 1.8.3

## Description of the problem
More of a question really.... using flatpak by default I see that my sandbox is scoped to only show two /proc/$pid ... myself and sytemd?

What can be done for applications that need to read all /proc/$pid dirs for files like status and statm ?

I noticed there seem to be options like:
```
--parent-pid=PID
--parent-expose-pids
```

I figured I could set `parent-pid=1` and `--parent-expose-pids`...
But I got errors like:
```
Cleaning up
Committing stage cleanup to cache
Finishing app
error: Unknown option --parent-pid=1
Error: Child process exited with code 1
``` 

When building using `flatpak-builder` and having those as `finish-args`.
Any idea of what could work here?

**Comment by Erick555** [comment]
Not possible. Such tools are out of scope for flatpak. You may see description what those option do [here](https://github.com/flatpak/flatpak/commit/62797b4be9b06de19639ca881c57fb9a15db190f).

**Comment by iphands** [comment]
Ahh bummer :(
Thanks for the answer though! Preciate ya!
