### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by siyia2** [flatpak/flatpak#4002]
If we have an EOL system that uses lets say for example flatpak version 1.0, does this mean that it can update some flatpack apps like the browser pretty much indefinately without a problem?

**Comment by alexlarsson** [comment]
Not forever, some apps choose to set a minumum flatpak version on the new version, but that is uncommon and mostly if they rely on some new feature. In general i should keep working. However, there are all kinds of othre risks with running an un-updated host system connected to the net.
