### ISSUE TITLE
library and preferences won't be saved if some directories don't exist

### ISSUE THREAD

**Issue by ntorresalberto** [flatpak/flatpak#4003]
**Linux distribution and version**: Fedora 32
**Flatpak version**: 5.0.93

## Description of the problem

After finishing installation, settings (like data sync info) and library won't be saved without further action.
I'm not sure if this is due to recent changes in flatpak permissions or what happened but Zotero needs these directories in order to store preferences/library:

- `~/Zotero`
- `~/.zotero/zotero`

## Steps to reproduce

1. [Install the flatpak ](https://flathub.org/apps/details/org.zotero.Zotero) and launch the application.
2. After syncing or doing any changes to setings/library, close it.
3. Next launch won't have any of the previous changes.

## Workaround / Temporary Fix

1. Finish installation.
2. Manually create the necessary directories by running: `mkdir -pv ~/Zotero ~/.zotero/zotero`

Again, *I'm not sure this is an issue with the flatpak* (I hope the maintainers will confirm that) but I guess this is the best place to share this workaround/document the problem for future users.

**Comment by mwleeds** [comment]
This sounds like an issue with the app, or an issue with the app's packaging. You can report that here: https://github.com/flathub/org.zotero.Zotero/issues

It also sounds like Zotero isn't following the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) as to where user data should be stored.

**Comment by ntorresalberto** [comment]
I thought I was on that repository, my bad.
