### ISSUE TITLE
Add option to enable SDK Extensions by default

### ISSUE THREAD

**Issue by Bleuzen** [flatpak/flatpak#4012]
## Linux distribution and version
Kubuntu 20.10
## Flatpak version
1.8.2
## Description of the problem
I use VSCodium with TexLive often. Usually I run Codium from my DE (KDE menu or shortcuts). But this way texlive doesn't work.
To use it, I have to run Codium from command line:

`FLATPAK_ENABLE_SDK_EXT=texlive flatpak run com.vscodium.codium`

... which is not a very good user experience.
Why are SDK extensions not enabled by default if they are installed?
If not making it the default, please add an option to do so.

## Steps to reproduce
1.) Install VSCodium and texlive SDK extension
2.) Launch VSCodium from your graphical environment and see texlive not working

**Comment by gasinvein** [comment]
This environment variable is handled by the editors, not by flatpak itself. And you can make it persistent using `flatpak override`.
