### ISSUE TITLE
[Issue] org.gnome.platform/x86_64/master detection broken

### ISSUE THREAD

**Issue by Simeonlps** [flatpak/flatpak#4026]
## Distro
Kubuntu 20.08 LTS
## Flatpak Version
1.6.5
## Description of the problem
org.gnome.platform/x86_64/master isnt getting detected properly, for installing souk for example, or trying flatpak update, it shows as not being installed, trying to installit results in it saying it is indeed installed
## Steps to reproduce
nothing special, i just tried installing souk

## Image
![grafik](https://user-images.githubusercontent.com/58338843/101948377-35764580-3bf2-11eb-8425-58cfc45b79e4.png)

**Comment by alexwender1** [comment]
flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo

**Comment by mwleeds** [comment]
Please post the full commands you ran and their output, not just an excerpt. And please post the output of `flatpak remotes`. There may by a confusion here between the system and user installations.

**Comment by smcv** [comment]
`org.gnome.platform/x86_64/master` is not the same as `org.gnome.Platform/x86_64/master`. Runtime names are case-sensitive.
