### ISSUE TITLE
What is the best way to make node visible with PhpStorm?

### ISSUE THREAD

**Issue by ubermanu** [flatpak/flatpak#4029]
## Linux distribution and version

Arch Linux
5.9.14-arch1-1

## Flatpak version

Flatpak 1.9.2

## Description of the problem

This is actually a question
I've installed PhpStorm (2020.3) via flatpak, but i can't access node nor npm (installed using pacman)

1. I 've tried to add "/usr/bin" as accessible but i think it's not possible with the newly generated /usr in the sandbox (not sure tho)

```bash
flatpak override --filesystem="/usr/bin":ro com.jetbrains.PhpStorm
```

2. I've noticed the PATH in the integrated terminal contains `~/.var/app/com.jetbrains.PhpStorm/data/node/bin/`
I've created the path (that didn't existed), linked the 2 exec, but still i can't use them
(I tried to add this path to the override config as well, but it didn't work)

What would be the best way to make node and npm accessible in this sandboxed environment?

**Comment by alexlarsson** [comment]
If you have host filesystem access (or optionally, host-os which is supported on later versions on flatpak) you should see it in /run/host/usr/bin. However, in general you can't expect an arbitrary binary from the host to work in the sandbox. Thats like copying a binary from ubuntu and running it on fedora. If it worked, then there would be no need for flatpak to exist.

**Comment by gasinvein** [comment]
@ubermanu In general you should assume that binaries from your OS are not available inside flatpak sandbox to run them directly. You have two options:
- Run host binary in host environment with, e.g. `flatpak-spawn --host node` (this is a sandbox bypass and requires corresponding permission, IDEs are likely to have it already)
- Install flatpak SDK extension with the tool you need (in node.js case, it's e.g. `org.freedesktop.Sdk.Extension.node14`)
