### ISSUE TITLE
Chromium or Flatpak sandbox is active?

### ISSUE THREAD

**Issue by HulaHoop0** [flatpak/flatpak#4032]
I am unsure where I should I ask this. I was wondering if this particular Chromium package disables the flatpak sandbox or is built with its own sandbox disabled by default to allow the application to run:

https://www.flathub.org/apps/details/org.chromium.Chromium

Where can I find this info in the future?

**Comment by refi64** [comment]
The Chromium Flatpak has patches on it to utilize Flatpak's support for
nested sandboxing.

For any other Chromium-specific issues in the future, the bug tracker on
that repo would be a better fit:
https://github.com/flathub/org.chromium.Chromium/issues
