### ISSUE TITLE
This Broke My OS

### ISSUE THREAD

**Issue by B00bleaTea** [flatpak/flatpak#4033]
this package broke my whole update system and when i try to update, it says 

" unable to download updates: E: the repository 'http://ppa.launchpad.net/alexrarsson/flatpak/ubuntu groovy release' does not have a release file. "

this is the worst package ever.

**Comment by refi64** [comment]
The instructions [explicitly mention](https://flatpak.org/setup/Ubuntu/) that the PPA should only be used on older Ubuntu installs, and 20.10 is rather new, so I'm not sure why you expected this to work... Regardless I believe the PPA can be removed using:

```
sudo add-apt-repository -r ppa:alexlarsson/flatpak
```

**Comment by danieltomasz** [comment]
Are there any plans to add 20.10 to the PPA?

**Comment by TruncatedDinoSour** [comment]
> this package broke my whole update system and when i try to update, it says
> 
> " unable to download updates: E: the repository 'http://ppa.launchpad.net/alexrarsson/flatpak/ubuntu groovy release' does not have a release file. "
> 
> this is the worst package ever.

god i am so sorry for this, i am sorry the way i came across at the time

i cant recall how i felt, but i probably felt so frustrated at flatpak for 'breaking' my system, ive learned and im very sorry lol, flatpak is cool but these days i prefer the system package manager
