### ISSUE TITLE
Enable the way to run Electron-based app on the system with disabled unprivileged user namespaces flag and without a need to call "sudo chmod 4755 $(which bwrap)"

### ISSUE THREAD

**Issue by vladimiry** [flatpak/flatpak#4035]
Linux distribution and version: Arch Linux, kernel 5.9.11-3

Flatpak version: 1.9.2

Steps to reproduce:
- Disable the unprivileged user namespaces flag by `sudo sysctl kernel.unprivileged_userns_clone=0`
- Try to run any Electron-based app built on the most recent stable @electron version (v11.1.0 as of now)

I believe before it was possible to do using zypak-wrapper tool or just passing --no-sandbox arg to the electron binary. But currently none of those options help to run the Electron-based app on the system with disabled unprivileged user namespaces.

See the console output of running the app (the app uses the most recent stable @electron version, v11.1.0 as of now):
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
error: ldconfig failed, exit status 256

See the app example in https://github.com/flathub/com.github.vladimiry.ElectronMail/tree/beta if needed.

**Comment by vladimiry** [comment]
Basically, the need is to allow using the app on any system without a need to manually tweak the system in any way.

**Comment by refi64** [comment]
I think you slightly misdiagnosed the issue here.

Flatpak's own top-level, mandatory sandbox **requires** a functioning bwrap, which itself needs either unprivileged user namespaces or the setuid bit to work. Zypak works from *inside* this sandbox, i.e. at the point where this error happens, Zypak is not even running yet.

(I *think* Arch used to use setuid bwrap at some point but switched away? This may be the cause for the behavior you originally observed.)

IMO if you're changing kernel defaults, you do just need to be prepared to have to make system modifications to make things work.

**Comment by vladimiry** [comment]
> I think you slightly misdiagnosed the issue here.

I understand the pipeline but placing the issue I though it worked before on my system with disabled user namespaces flag (I might be wrong since I used to toggle that kernel flag often and test/run the flatpak thing very rerely). But if using bwrap by flatpak is not a recent change then I'm wrong saying that there was no original issue occurring before.

> (I think Arch used to use setuid bwrap at some point but switched away? This may be the cause for the behavior you originally observed.)

I thought the same too but https://archlinux.org/packages/extra/x86_64/bubblewrap/ package didn't have updates since 2020-03.

> IMO if you're changing kernel defaults, you do just need to be prepared to have to make system modifications to make things work.

Changing kernel defaults is a clearly: 1) changing the system setting 2) doing it globally. IMO this is not a user friendly approach leading to bad UX. If a not advanced user installs the app on the system with disabled user namespaces flag it just won't start. What the non advanced user will do is just removing the app and forget about that non functional stuff.

**Comment by vladimiry** [comment]
Ultimately the thing is that for every other package type, including appimage and snap there is a way to start the app on any system regardless the user namespaces. But flatpak doesn't allow to do so.

**Comment by vladimiry** [comment]
I guess to slightly improve the UX the approach like adding simple loader tool in the package might help. The loader would test that bwrap/sandboxing is functional and then it would start the electron binary or display the alert message. Currently the issue get printed to console but not every user looks into the console or system logs.

**Comment by vladimiry** [comment]
It appears that the flatpak's technical design doesn't allow to enable the desired behavior and there are no signs of the situation to be improved. So closing since the issue is not going to be solved any time soon.

**Comment by inventor500** [comment]
For posterity, this is caused when running the `linux-hardened` kernel on Arch Linux. The fix for this is described in the Arch Wiki, [https://wiki.archlinux.org/title/Flatpak#Flatpak_does_not_run_on_the_linux-hardened_kernel](here).

Install `bubblewrap-suid` instead of `bubblewrap`.

**Comment by smcv** [comment]
The user namespace requirements are described here: https://github.com/flatpak/flatpak/wiki/User-namespace-requirements
