### ISSUE TITLE
Don't alias update as "upgrade"

### ISSUE THREAD

**Issue by maoschanz** [flatpak/flatpak#4036]
## Linux distribution and version

debian sid

## Flatpak version

1.8.3

## Description of the problem

I want to type flatpak update, but pressing tab doesn't autocomplete because of the "upgrade" alias.

This problem feels even more absurd when you consider that both options do the same thing: i have to input at least 2 more keys for literally nothing

Suggestions of possible solutions:

- get rid of the useless alias
- only autocomplete actual commands, not aliases
- alias update as "up" so i can validate the command even when autocompletion gets stuck

**Comment by alexlarsson** [comment]
Yeah, i think it shouldn't autocomplete on aliases.

**Comment by maoschanz** [comment]
i forgot about it when opening the issue, but this inconvenience also exists with the "remote-something" commands and the "remove" alias, though it's not something i often use
