### ISSUE TITLE
Unable to create GL context on PinePhone

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#4037]
## Linux distribution and version

Mobian (based on Debian 11) for PinePhone (3GB RAM model)
PostmarketOS v20.05 (based on Alpine Linux 3.12) for PinePhone (3GB RAM model)

## Flatpak version

Mobian: 1.8.3
PostmarketOS: 1.6.3

## Description of the problem

Unable to create GL context.

## Steps to reproduce

1: Install software through flatpak.

2: Load and use software

I've tried Epiphany, RetroArch, Celluloid.

RetroArch's menu works fine (though freezes if you navigate too far down in the Online Updater menu), but cores fail to load. Switching the Video Driver away from gl causes more issues with the menu and cores still don't load.

Epiphany gives this error when you try to load a video:

`** (epiphany:3): WARNING **: 22:24:20.423: GDK is not able to create a GL context, falling back to glReadPixels (slow!): Unable to create a GL context`

Celluloid gives this error:

`** (io.github.celluloid_player.Celluloid:3): CRITICAL **: 22:21:52.491: Failed to initialize render context`

**Comment by eszlari** [comment]
Mesa3D drivers are provided by the runtime, you should report it there:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by Mikenux** [comment]
@GeorgesStavracas: I think this can be closed as the author is no longer on github to provide more information if this was possibly an issue in flatpak.

**Comment by GeorgesStavracas** [comment]
Sure
