### ISSUE TITLE
Allow flatpak build to support extensions

### ISSUE THREAD

**Issue by Kekun** [flatpak/flatpak#4040]
I want to develop and build a command line Rust app by doing `flatpak-builder --stop-at=my-app app com.foo.MyApp.json` and then using Cargo with`flatpak build` to build the `my-app` module, using the `org.freedesktop.Sdk.Extension.rust-stable` extension.

While building the whole thing with flatpak-builder works, Cargo — which is provided by the extentions — can't be found by `flatpak build`. I looked at its options, and nothing seems to allow using extensions.

It would be convenient to have extensions used in `flatpak-builder` to directly be usable in `flatpak build`.

**Comment by refi64** [comment]
flatpak-builder is just a frontend for the flatpak build* commands, check
out build-init's --sdk-extension argument.

**Comment by chergert** [comment]
I think this can be closed, `--sdk-extension` is the proper way to do this.
