### ISSUE TITLE
Permanently Override Runtime

### ISSUE THREAD

**Issue by tustvold** [flatpak/flatpak#4042]
## Linux distribution and version

```
Linux 5.9.14-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux
```

## Flatpak version

Flatpak 1.9.2

## Description of the problem

I'm relatively new to flatpak so there could be some way to do this that I'm not familiar with, but I'd like a way to permanently override the runtime used by a particular installed application.

## Steps to reproduce

I am trying to get screen sharing from Firefox running inside Flatpak via pipewire

Install firefox 85.0b4 from the beta flathub repo

```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install org.mozilla.firefox
```

Then set some overrides

```
flatpak override --socket=wayland --env=MOZ_ENABLE_WAYLAND=1 --filesystem=xdg-run/pipewire-0:ro org.mozilla.firefox
```

This would normally be sufficient, but unfortunately the firefox flatpak is based on org.freedesktop.Platform/x86_64/19.08 which has pipewire 0.2, which has compatibility issues with the newer pipewire 0.3 bundled with Arch Linux.

The following does, however, work

```
flatpak run --runtime=org.freedesktop.Platform/x86_64/20.08 org.mozilla.firefox 
```

I'd like to make this permanent, ideally in much the same way as it is possible to override other aspects of the configuration. Whilst my use-case is perhaps a little bit unusual, I imagine these sort of host <-> flatpak runtime incompatibilities are not that abnormal and so having some easy way to mitigate them might be beneficial.

**Comment by nanonyme** [comment]
Afaik this feature is not really according to flatpak design principles. Firefox will move to 20.08 soon.

**Comment by teohhanhui** [comment]
The workaround suggested in flathub/org.chromium.Chromium.BaseApp#2 for using the `org.gnome.Platform` runtime for having working input method support under GTK4 (`--gtk-version=4`) and Wayland (`--ozone-platform-hint=auto`) works great, but it means having to manually edit all the `.desktop` files for the PWAs (automatically created by [flextop](https://github.com/refi64/flextop)) to add the `--runtime` flag.

Having this flag in flatpak override would be helpful...

**Comment by hfiguiere** [comment]
Runtime are not meant to be overridden like that.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flatpak/flatpak/issues/4042#issuecomment-1937236922

@hfiguiere, hence the FR — if they cannot be, we shall make them be. Without addressing why you've reason to believe your opinion upon *whether* that is a good idea should supercede those supporting this proposal should be explained, else you'll unnecessarily invoke ire.

**Comment by nanonyme** [comment]
Especially in context of Firefox this doesn't make any sense. Firefox has base app which is strongly bound to ABI of a specific freedesktop-sdk runtime version. How flatpak base design works is if you want runtime changed for app, build the app yourself.

**Comment by LSeelig** [comment]
I am on a space-constrained system. Some apps use old runtimes, but using env to run newer runtimes works fine. I still can't install the old runtime because they those apps are still installed. I would really like to remove them. Why couldn't I just override the runtimes or mask them to replace the old with the new?
