### ISSUE TITLE
Allow a --repo or FLATPAK_REPO argument to specify where the preferred repo is

### ISSUE THREAD

**Issue by magcius** [flatpak/flatpak#405]
Split from https://github.com/flatpak/flatpak/issues/137#issuecomment-257703504 : For build systems and build servers, it's convenient to "start fresh" from no repo when doing a build. I would like some sort of `--repo` argument or `FLATPAK_REPO` override envvar so I can work in a fresh repo every single time.

The undocumented `FLATPAK_SYSTEM_DIR` envvar is close, but even if the directory is writable by the user, we still require polkit access. Perhaps we just fix that bug instead and document the envvar.

**Comment by alexlarsson** [comment]
If you want to avoid issues with polkit, use `FLATPAK_USER_DIR` and --user instead maybe?

**Comment by magcius** [comment]
Sounds good -- could you ensure that this envvar is stable and documented?

**Comment by alexlarsson** [comment]
Its stable, but i'm not sure we have a great way to document these things. I guess we need some general manpage for the environment and filesystem layout.
