### ISSUE TITLE
Add additional default installation for multios installation

### ISSUE THREAD

**Issue by nintyfan** [flatpak/flatpak#4052]
## Linux distribution and version
Any Linux distro/version

## Flatpak version
I don't know, sorry

## Description of the problem
It was related to issues:
1. https://github.com/flatpak/flatpak/issues/3620
2. https://github.com/flatpak/flatpak/issues/2337
3. https://github.com/flatpak/flatpak/issues/1224

Read also: https://forums.opensuse.org/showthread.php/548449-Idea-Flatpak-Current-computer-installation
And: https://bugzilla.opensuse.org/show_bug.cgi?id=1180493

Basically: It's sensible to add multi-distro flatpak installation for allowing to reduce space, allow to change distro without reinstalling applications or simply use the same applications on many systems.
## Steps to reproduce
N/A

## Solution
1. Flatpak maintainers should discus about path to mount an special partition, where flatpak keeps multios flatpaks. Alternatively, flatpak could have this additional installation on /home directory/partition, so we solve some problems (many users had the same home directory across many distribution, but /home belongs to other partition than /, and don't like to install application only for single user)
2. If you decide that multi-os installation should be on separate partition or decide to give user selection, you must create standard of label/tag this kind of multi-os flatpak installation's partition. For example systemd could mount any partition labeled FLATPAK under /var/lib/flatpak-multios/$$, where $$ is number of partition with FLATPAK label. Systemd should also create needed /etc/flatpak/installation.d/$$.conf files
3. System installers could have checkbokses called 'create separate partition for flatpak programs' and  'add multi-user installation of flatpak programs under /home'

This idea isn't new, but I added two part to it:
1. Automounting flatpak partition
2. Configure flatpak to use flatpak partition by default (automatic configuration needed in case, where there exist multiple partition called FLATPAK?)
3. Allow to create FLATPAK partition in OS installer
4. Standardize this solution across many distributions

**Comment by nintyfan** [comment]
And yet... There exist flatpak for Windows, which uses WSL/WSL2. I've read Microsoft made easier to install WSL. It's needed only single command by now, so we can add integration of this special partition also to Windows. I known there's only little chance to proceed, because fat is very primitive, but...

Many years ago, I created script, which could ran under Windows and GNU/Linux systems. I uses something like conditional comments in IE browser. One missing part in my scripts is that Windows opened terminal window for it and tries to execute #!/bin/bash . Maybe solution could be added #!/bin/bash command to Windows. This command would do nothing.

Why I describe this? Because flathub could provide single link to install programs for both windows and linux users.

**Comment by hfiguiere** [comment]
out of scope for flatpak.
