### ISSUE TITLE
Difference between remove and uninstall

### ISSUE THREAD

**Issue by alvarlagerlof** [flatpak/flatpak#4053]
## Linux distribution and version
Fedora 33 Workstation

## Flatpak version
1.8.4

## Description of the problem
I get a different list of ids when using `flatpak uninstall --unused` as opposed to `flatpak remove --unused`

## Steps to reproduce
Do not know how to do this. I have only used flatpack like a normal user casually adding and removing stuff. If there is anything I can run to provide more information I am happy to.

![image](https://user-images.githubusercontent.com/14835120/103769695-0bfbde80-5025-11eb-93cb-3142c4f1dc44.png)

**Comment by mwleeds** [comment]
Perhaps another process made changes to your flatpak installation? `flatpak remove` is an alias for `flatpak uninstall`.

You can check `flatpak history` to see if anything changed.

**Comment by alvarlagerlof** [comment]
Ah, that is a resonable explanation. Closing this.
