### ISSUE TITLE
Installing from a flatpakref does not handle --arch properly

### ISSUE THREAD

**Issue by mattdangerw** [flatpak/flatpak#406]
If you have an installation of a app or runtime for your default arch, and try to install for another arch with
`flatpak install --user --arch archThatIsNotInstalled --from my.flatpakref`
you will see.
`error: App [appid], branch [branch] is already installed`

Instead we should install the ref for the new arch.

**Comment by malept** [comment]
Can this be closed? Unless I'm misreading `NEWS`, it appears that #474 is both in master and 0.8.2.

**Comment by alexlarsson** [comment]
Yeah, thanks
