### ISSUE TITLE
`flatpak build` regression after recent CVE fixes: LD_LIBRARY_PATH not set

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#4080]
## Linux distribution and version

Originally reported for Debian 10, reproduced in Debian unstable (rolling release)

## Flatpak version

Originally reported for 1.2.5-0+deb10u2 (basically a2719715), reproduced in 1.10.0

## Description of the problem

Downstream bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980323

**If** you are using a setuid-root `bwrap`, then `flatpak build` does not set `LD_LIBRARY_PATH` any more. This means that libraries provided by `/app/lib` or an extension are not found.

(This is not reproducible if you are not using the setuid-root `bwrap`.)

## Steps to reproduce

```
$ flatpak install org.freedesktop.Sdk//20.08
$ flatpak install org.freedesktop.Platform//20.08
$ flatpak build-init _flatpak-build com.example.App org.freedesktop.Sdk org.freedesktop.Platform 20.08
$ flatpak build _flatpak-build -- sh -c 'echo "$LD_LIBRARY_PATH"'
```

## Expected result

```
/app/lib:/usr/lib/x86_64-linux-gnu/GL/default/lib:/usr/lib/x86_64-linux-gnu/openh264/extra
```

## Actual result

(no output)

**Comment by smcv** [comment]
I think this is because:

In 6d1773d2 and its backports, I systematically converted all environment variable settings into `--setenv` arguments. This made it seem unnecessary to do that individually for `LD_LIBRARY_PATH` (bde6fa52) and `TMPDIR` (b8d22711), so I removed those from `flatpak_run_add_environment_args()`.

However, my new code to convert environment variable setting into `--setenv` arguments is only reached when we are in `flatpak_run_app()` (called from `flatpak run` and `flatpak_installation_launch_full()`). It is skipped in the two other callers of `flatpak_run_add_environment_args()`: those are `apply_extra_data()`, and `flatpak build`.

I see two possible solutions to this.

One is to reinstate the code that I removed from `flatpak_run_add_environment_args()`.

The other is to call `flatpak_bwrap_envp_to_args()` every time we are going to exec `bwrap`, which means we will systematically transform *all* environment variables into `--setenv`, in all code paths that exec `bwrap`.

**Comment by smcv** [comment]
Uses of `FlatpakBwrap` to run `bwrap` that might be affected by this:

* The single use calling `execvpe()` in `app/flatpak-builtins-build.c` is this bug.
* `apply_extra_data()` in `common/flatpak-dir.c` uses the `flatpak_run_get_minimal_env()`, and regressed in the same way as `flatpak build`.
* `flatpak_dir_run_triggers()` in `common/flatpak-dir.c` currently ignores `bwrap->envp` and always inherits the parent process's environment. I'm not completely sure what this is used for, and so I'm not sure whether that's a bug or working as intended, but either way it didn't regress when the recent CVE was fixed.
* `start_dbus_proxy()` in `common/flatpak-run.c` instantiates the `flatpak_run_get_minimal_env()`, but then ignores it and inherits the parent process's environment - which seems maybe appropriate, because the dbus-proxy is basically running on a slightly adjusted version of the host system's mount namespace, rather than being in the runtime? Again I'm not completely sure whether that's a bug or working as intended, but either way it didn't regress when the recent CVE was fixed.
* `regenerate_ld_cache()` in `common/flatpak-run.c` uses the `flatpak_run_get_minimal_env()`, but doesn't make any attempt to avoid `LD_LIBRARY_PATH` being filtered out by `bwrap`. Perhaps that's a bug, but it didn't regress when the recent CVE was fixed.
* `flatpak_run_app()` in `common/flatpak-run.c` already uses `flatpak_bwrap_envp_to_args()`.

**Comment by smcv** [comment]
> I see two possible solutions to this.
> 
> One is to reinstate the code that I removed from `flatpak_run_add_environment_args()`.

#4082.

> The other is to call `flatpak_bwrap_envp_to_args()` every time we are going to exec `bwrap`, which means we will systematically transform _all_ environment variables into `--setenv`, in all code paths that exec `bwrap`.

#4081. I think I prefer this one: it seems more like the direction that we ought to be going in.

**Comment by alexlarsson** [comment]
flatpak_dir_run_triggers() is not used to run a flatpak sandbox, just to make /usr read-only while running triggers such as the mimedata, icon and desktop database generation for the "exports" directory. These will be using the host libraries and binaries in the same place as usual, so I don't think those rely on LD_LIBRARY_PATH.

**Comment by smcv** [comment]
> start_dbus_proxy() in common/flatpak-run.c instantiates the flatpak_run_get_minimal_env(), but then ignores it and inherits the parent process's environment - which seems maybe appropriate, because the dbus-proxy is basically running on a slightly adjusted version of the host system's mount namespace, rather than being in the runtime? Again I'm not completely sure whether that's a bug or working as intended, but either way it didn't regress when the recent CVE was fixed.

I think this is maybe working as intended, then, with the same reasoning you had for `flatpak_dir_run_triggers()` - so we don't want to touch that one, and I was correct to avoid it in #4081?
