### ISSUE TITLE
" The pkg-config script could not be found or is too old. "

### ISSUE THREAD

**Issue by wellinton-capixaba** [flatpak/flatpak#4101]
Flatpak version

I am trying to build flatpak 1.8. During the configure execution, this is printed on the screen:

"checking for ARCHIVE... no
configure: error: in `/media/34GB/Arquivos-de-Programas-Linux/flatpak-1.8.4':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables ARCHIVE_CFLAGS
and ARCHIVE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details."

I want to know if I can edit configure to skip this test, or to check for a lower pkg-config (mine is 0.22), or if it will necessary to install a second, newer pkg-config outside system default searched directories, and then try to set PATH before configure as to make configure find it before the system default version (or perhaps to create a symbolic link on /usr/local/bin to do the same).

**Comment by mwleeds** [comment]
Seems like you need to install a newer `pkg-config`

**Comment by wellinton-capixaba** [comment]
I hacked the configure.ac file to accept my older pkg-config. Now the same issue is happening with libarchive. How do I check my version of it? I want to try the same trick.

**Comment by refi64** [comment]
`pkg-config --modversion PACKAGE` will tell you what version of the given package you have installed.

That being said, this would probably go better on the mailing list than here...

**Comment by wellinton-capixaba** [comment]
Ok, I hacked the configure.ac again to try to bypass this libarchive' limitation, and this time it did not work. In fact, running "pkg-config --modversion libarchive" or "pkg-config --modversion archive" results in the same: "No package 'archive' found" or "No package 'libarchive' found"

This isn't tar stuff? If yes, I am seriously thinking in deleting the line "PKG_CHECK_MODULES(ARCHIVE, [libarchive >= 2.8.0])"

**Comment by refi64** [comment]
libarchive is needed for the OCI remote support, you just really need to update your host system dependencies...
