### ISSUE TITLE
failure to update

### ISSUE THREAD

**Issue by samuraied** [flatpak/flatpak#4103]
## Linux distribution and version
fedora 32
## Flatpak version
Flatpak 1.10.1
## Description of the problem
i already tried to find a solution online, but to no avail, i have been having this problem for about a week, i thought an update could fix it, but sadly no.
## Steps to reproduce
simply attempt to update
[NewTXT.txt](https://github.com/flatpak/flatpak/files/5910473/NewTXT.txt)

**Comment by samuraied** [comment]
i have already attempted a repair,
following this issue, despite being old, i though it could help, but no
https://github.com/flatpak/flatpak/issues/1134

**Comment by dustContributor** [comment]
I have a similar issue. I when I do `flatpak update` I get a correct list of things to update and install, but when confirming the update I get TLS errors in the form:

> Warning: While pulling runtime/org.freedesktop.Platform.Compat.i386/x86_64/20.08 from remote flathub: Error performing TLS handshake: An unexpected TLS packet was received.

I already updated flatpak to the most recent in my distro, which is `1.10.1` in debian testing.

**Comment by hfiguiere** [comment]
Looks like an infra problem.
