### ISSUE TITLE
Should rename-desktop-file also rename the DesktopId in search providers?

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#411]
Right now, gnome-calculator upstream ships `gnome-calculator.desktop`.

As a result, the flatpak-builder manifest has `"rename-desktop-file": "gnome-calculator.desktop",`

But then, the installed gnome-shell search provider contains:

```
$ cat /var/lib/flatpak/exports/share/gnome-shell/search-providers/org.gnome.Calculator-search-provider.ini 
[Shell Search Provider]
DesktopId=gnome-calculator.desktop
...
```

Could flatpak-builder rename the `DesktopId` in this file when `rename-desktop-file` is used?

I'm happy to work on a patch, but I'm not sure that's desired in the first place.

**Comment by alexlarsson** [comment]
No, i'm not going to add gnome-specific features like that.
