### ISSUE TITLE
Cannot specify both remote and --user

### ISSUE THREAD

**Issue by overlisted** [flatpak/flatpak#4110]
## Linux distribution and version
Fedora 33

## Flatpak version
Flatpak 1.10.1

## Description of the problem
The CLI syntax can't the find explicit remote in an `install` command if you put `--user` flag before it. 

## Steps to reproduce
- Execute `$ flatpak install --user gnome-nightly org.gnome.Builder`

**Comment by mwleeds** [comment]
Perhaps you don't have the `gnome-nightly` remote in your user installation? The command should work. If it doesn't provide the full output from it and the output of `flatpak remotes`.

**Comment by overlisted** [comment]
> Perhaps you don't have the `gnome-nightly` remote in your user installation? The command should work. If it doesn't provide the full output from it and the output of `flatpak remotes`.

I do; here are all my remotes:
```
Name          Options
fedora        system,oci
flathub       user
flathub-beta  user
gnome-nightly user
```

**Comment by overlisted** [comment]
Ok, apparently, it works now...
