### ISSUE TITLE
(Feature Request) Support CLI apps

### ISSUE THREAD

**Issue by dtantono** [flatpak/flatpak#4113]
At this moment, I know flatpak support GUI apps only which is quite different than snap. Is it possible for flatpak to support GUI and CLI apps like snap?

**Comment by mwleeds** [comment]
Flatpak already supports CLI apps. See for example vim: https://flathub.org/apps/details/org.vim.Vim

There has been discussion on various existing issues on improving the experience for using CLI apps, see e.g. #1258

**Comment by dtantono** [comment]
But, this app (https://github.com/starship/starship/issues/2178) have a problem to publish it on flatpak. I hope flatpak can solve it

**Comment by anthr76** [comment]
It would be great to make this support better. I'm ready to undergo a handful GoLang flatpak CLI tools to flatpak but the usage of calling the FQDN is holding me back. Users won't want to do that and neither will I. Surely you can write a script or do better better things but this is something that should be supported out of the box.
