### ISSUE TITLE
remote-modify does not update metadata when using the system helper 

### ISSUE THREAD

**Issue by mariospr** [flatpak/flatpak#413]
I just found today that `flatpak remote-modify <remote> --update-metadata` does not work as intended when using the system helper, as it leaves the remote configuration intact at the end of the process (which works just fine when run using `sudo`, btw).

I investigated the problem and it seems that it's caused because `flatpak_dir_modify_remote()` gets [called with the outdated OSTree repo configuration for the remote-modify command](https://github.com/flatpak/flatpak/blob/master/app/flatpak-builtins-add-remote.c#L508), basically because the [call to flatpak_dir_update_remote_configurtion() a few lines before](https://github.com/flatpak/flatpak/blob/master/app/flatpak-builtins-add-remote.c#L492) did not update the configuration of`dir`'s internal OSTree repo after having the system helper updating the local configuration on disk.

My understanding is that the right way of fixing this would be doing something like `flatpak_installation_drop_caches()` from here, but perhaps that's a bit overkill for a CLI utility that just runs once and dies, so I'm thinking we can perhaps work this around easily enough by inverting the order  `flatpak_dir_modify_remote()` and `flatpak_dir_update_remote_configuration()` gets called?

**Comment by mariospr** [comment]
> My understanding is that the right way of fixing this would be doing something like `flatpak_installation_drop_caches()` from here, but perhaps that's a bit overkill for a CLI utility that just runs once and dies, so I'm thinking we can perhaps work this around easily enough by inverting the order  `flatpak_dir_modify_remote()` and `flatpak_dir_update_remote_configuration()` gets called?

Actually, that won't work because it would simply change the problem: doing that we'll ensure that the remote's metadata gets  updated when using the system helper simply because it's the last thing being executed, but other flags passed to modify the configuration (e.g. `--disable`) will get lost due to the same problem.

I don't know, maybe we should implement something like the drop mechanism from FlatpakInstallation, or even rewrite this command in terms of the public API (so that flatpak_installation_drop_caches() gets used automatically).

Other option, if we want to keep it simple, could be to just return after calling `flatpak_dir_update_remote_configuration()` when `--update-metadata` gets passed, which is probably enough in most cases, although a bit confusing (would need documenting).

@alexlarsson any preference in one approach or another?

**Comment by alexlarsson** [comment]
@mariobl I believe this should fix it, but can you verify that?

**Comment by mariospr** [comment]
It does fix it, thanks!
