### ISSUE TITLE
Authentication required during update

### ISSUE THREAD

**Issue by AngusP** [flatpak/flatpak#4136]
## Linux distribution and version

Fedora 33 Silverblue `Linux 5.10.15-200.fc33.x86_64 #1` `Fedora 33.20210216.0 (Silverblue)`

## Flatpak version

`Flatpak 1.10.1`

## Description of the problem

Asked to authenticate many times during a `flatpak update`, this hasn't happened before. There were updates to multiple "system" apps (`org.gnome.something`) as well as apps I'd installed later. The previous many times I've updated this wasn't required. Example:

```
==== AUTHENTICATING FOR org.freedesktop.Flatpak.metadata-update ====
Authentication is required to update metadata
Authenticating as: Angus (angus)
Password: 
```

```
                                                            ==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: Angus (angus)
Password: 
```

This kinda sucks as an experience, having to type the same password ~20 times during an update. Also note the header seems to take a random offset.

Running the update using sudo didn't work, there was an issue with `dbus` (unfortunately I didn't grab the exact message)

Running in `tmux` from a gnome-terminal tty as user 1000 (default non-root user, not over ssh) `groups: angus wheel`

Perhaps related to #2328

I've swapped most default apps from the `fedora` to `flathub` repo.

## Steps to reproduce

Run `flatpak update` as non-root user in group `wheel`

I will install an update to Silverblue and check if the problem persists, it's possible it's just a bad build.

**Comment by AngusP** [comment]
Apologies if there's a simple config way of preventing this, but I couldn't find one after a quick search.

**Comment by AngusP** [comment]
I've upgraded to `33.20210220.0` and the issue cleared. I'm wondering if I got my shell into a strange state where the session was on a pts not tty.

I think my confusion could be solved by having some docs that I'd have discovered when googling the problem, and also by explaining why permission is needed when trying to do an update.

**Comment by dreua** [comment]
Were you logged in through SSH by accident?
