### ISSUE TITLE
Cannot read all devices and write to uinput with --device=all

### ISSUE THREAD

**Issue by sezanzeb** [flatpak/flatpak#4137]
## Linux distribution and version
5.10.7-3-MANJARO

## Flatpak version
- extra/flatpak 1.10.0-1
- extra/flatpak-builder 1.0.11-1

## Description of the problem
Can only see one device with --device=all, and write access to /dev/uinput is not given

## Steps to reproduce
https://github.com/sezanzeb/key-mapper/pull/31#discussion_r575656152

**Comment by refi64** [comment]
Given `--device=all`, Flatpak will just [forward all the devices directly](https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L1359-L1363); are you sure there's just not missing write access to /dev/uinput?

**Comment by sezanzeb** [comment]
since `flatpak run` "is not intended to be ran with sudo", I guess the user running the GUI would have to get those permissions by e.g. being in the appropriate group.

The cleaner solution would then be to have a new user only for the purpose of running the GUI, who is in the input (and potentially plugdev) input groups.

**Comment by smcv** [comment]
> I guess the user running the GUI would have to get those permissions by e.g. being in the appropriate group?

Yes, or setting `TAG+=uaccess` like [steam-devices](https://github.com/ValveSoftware/steam-devices/) does.

If you don't have a particular privilege (for example access to `/dev/uinput`) before entering the Flatpak sandbox, then you still won't have that privilege inside the sandbox. If you did, that would be a security vulnerability.
