### ISSUE TITLE
Fedora 25 Permissions issues (Pitivi)

### ISSUE THREAD

**Issue by didli** [flatpak/flatpak#414]
Not sure if it is related to Flatpak or Pitivi, but with Fedora 25, following the instructions from Pitivi website, Flatpak fails as a simple user with this :
`error: Permission denied
Traceback (most recent call last):
  File "./pitivi-flatpak", line 654, in <module>
    app_flatpak.run()
  File "./pitivi-flatpak", line 443, in run
    self.update_all()
  File "./pitivi-flatpak", line 590, in update_all
    m.update()
  File "./pitivi-flatpak", line 317, in update
    return self.install()
  File "./pitivi-flatpak", line 313, in install
    comment="Installing %s" % self.name)
  File "./pitivi-flatpak", line 144, in flatpak
    return subprocess.check_call(command)
  File "/usr/lib64/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'install', '--user', 'pitivi', 'org.pitivi.Pitivi', 'master']' returned non-zero exit status 1`

**Comment by aleb** [comment]
Try to run the command from the command line prompt and see what error it prints:
```
flatpak install --user pitivi org.pitivi.Pitivi master
```

**Comment by didli** [comment]
Thanks aleb for your help. So ... I'm getting a very quiet "error: permission denied" (and nothing else). But the same command with sudo is successfull ... I'm guessing I have some permissions issues ?

**Comment by aleb** [comment]
flatpak should not be run as sudo. 
What does this print:
```
$ which flatpak
$ ls -l $(which flatpak)
```

**Comment by didli** [comment]
`flatpak --version`
/usr/bin/flatpak
Flatpak 0.6.13
`ls -l $(which flatpak)`
-rwxr-xr-x 1 root root 572192 27 oct.  10:14 /usr/bin/flatpak

**Comment by alexlarsson** [comment]
Maybe you ran it with sudo at some point and it created some file owned by root?
Can you try: `find  ~/.local/share/flatpak/ -uid 0`

**Comment by didli** [comment]
I'm sure I've made that mistake first time I tried flatpak (at the time I didn't know it was not recommended).
Here's the result :
/home/user/.local/share/flatpak/exports
/home/user/.local/share/flatpak/exports/share
/home/user/.local/share/flatpak/exports/share/applications
/home/user/.local/share/flatpak/exports/share/applications/mimeinfo.cache
Hopefully there's a way to correct that right ? Maybe from scratch ?

**Comment by aleb** [comment]
You could remove (or move to a different place) the `/home/user/.local/share/flatpak` folder, then install again Pitivi http://wiki.pitivi.org/wiki/Install_with_flatpak

**Comment by didli** [comment]
Works perfectly. Thanks a lot !
