### ISSUE TITLE
[Suggestion] Add '--nopersist' or an equivalent to remove user-defined persist

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flatpak/flatpak#4143]
## Description of the problem

There's no flag to remove or undo the user defined `--persist` option.

I know I could use Flatseal, but I would prefer having an option in the terminal without needing to go to the `overrides` directory, or launch a separate program for a little thing.

**Comment by chrisawi** [comment]
Closing in favor of https://github.com/flatpak/flatpak/issues/5042
