### ISSUE TITLE
Allow installing bundles without specifying --bundle

### ISSUE THREAD

**Issue by hifi** [flatpak/flatpak#415]
For improved usability, `--bundle` should not be required for offline package installation with the CLI if the last argument looks like a bundle. Package managers like `yum` and `dnf` support installing local packages in the same way like you install from a repository by specifying the file path instead of a package name. It's convenient.

These should be valid ways to install or update a bundle:
```
flatpak install path/to/app.flatpak
flatpak path/to/app.flatpak
```

It's very inconvenient for users who are not using a GUI to use the CLI when they need to add multiple long arguments to do an unprivileged local install like so:
```
flatpak install --user --bundle path/to/app.flatpak
```

The error message for `flatpak install foo.flatpak` isn't very helpful either:

```
error: REPOSITORY and NAME must be specified
```

**Comment by jgarciao** [comment]
I also think this could be very useful for end users, specially when using distros that don't have the last version of Gnome Software that support installing flatpak bundles and flatpakref files.

With the same purpose this equivalences could be useful too:
```
flatpak install --from https://sdk.gnome.org/gedit.flatpakref
flatpak https://sdk.gnome.org/gedit.flatpakref
```

```
flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
flatpak https://sdk.gnome.org/gnome.flatpakrepo  (& include a default name for the repo in the flatpakrepo file)
```

If you don't want to change the main "flatpak" program maybe a "flatpak-installer" script/program could implement this.

**Comment by jgarciao** [comment]
Thank you!

**Comment by beedell-roke** [comment]
This isn't working with `flatpak-1.16.1-1.fc42.x86_64`:

1. ~~~sh
   #!/usr/bin/env sh
   flatpak install https://github.com/NickvisionApps/Parabolic/releases/download/2025.5.4-beta1/org.nickvision.tubeconverter.qt.flatpak
   ~~~

1. > ~~~YAML
   > error: Remote bundles are not supported
   > ~~~

**Comment by beedell-roke** [comment]
> [`#issuecomment-2904913321`](https://github.com/flatpak/flatpak/issues/415#issuecomment-2904913321)

I've ascertained that it actually doesn't support 301s, for it did invoke (albeit expectedly unsuccessfully) when I supplied it with [`https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250523%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250523T155326Z&X-Amz-Expires=300&X-Amz-Signature=47e4694a09c952e4b3e2cd418ddc724982201a8a46890eadbd048774db7f22c7&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dorg.nickvision.tubeconverter.qt.flatpak&response-content-type=application%2Foctet-stream`][1] instead:

<blockquote>

~~~MA
flatpak install https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250523%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250523T155326Z&X-Amz-Expires=300&X-Amz-Signature=47e4694a09c952e4b3e2cd418ddc724982201a8a46890eadbd048774db7f22c7&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dorg.nickvision.tubeconverter.qt.flatpak&response-content-type=application%2Foctet-stream
[1] 73984
[2] 73985
[3] 73986
[4] 73989
[5] 73990
[6] 73992
[7] 73995
bash: X-Amz-Credential=releaseassetproduction%2F20250523%2Fus-east-1%2Fs3%2Faws4_request: command not found...
bash: X-Amz-Date=20250523T155326Z: command not found...
bash: X-Amz-Expires=300: command not found...
bash: X-Amz-Signature=47e4694a09c952e4b3e2cd418ddc724982201a8a46890eadbd048774db7f22c7: command not found...
bash: X-Amz-SignedHeaders=host: command not found...
bash: response-content-disposition=attachment%3B%20filename%3Dorg.nickvision.tubeconverter.qt.flatpak: command not found...
bash: response-content-type=application%2Foctet-stream: command not found...
Looking for matches…
F: An error was encountered searching remote ‘fedora’ for ‘https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256’: 'https:' is not a valid name: Name can't contain :
F: An error was encountered searching remote ‘flathub’ for ‘https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256’: 'https:' is not a valid name: Name can't contain :
F: An error was encountered searching remote ‘flathub-beta’ for ‘https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256’: 'https:' is not a valid name: Name can't contain :
error: No remote refs found for ‘https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256’
[1]   Exit 1                  flatpak install https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256
[3]   Exit 127                X-Amz-Date=20250523T155326Z
[7]+  Exit 127                response-content-disposition=attachment%3B%20filename%3Dorg.nickvision.tubeconverter.qt.flatpak
~~~

</blockquote>

This remains a significant deficiency in comparison to `dnf5`.

[1]: https://objects.githubusercontent.com/github-production-release-asset-2e65be/439665747/a7a6cad4-bf72-4253-b615-ebbb3f5af88f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250523%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250523T155326Z&X-Amz-Expires=300&X-Amz-Signature=47e4694a09c952e4b3e2cd418ddc724982201a8a46890eadbd048774db7f22c7&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dorg.nickvision.tubeconverter.qt.flatpak&response-content-type=application%2Foctet-stream
