### ISSUE TITLE
Can I use a flatpak app to run others?

### ISSUE THREAD

**Issue by Starslayerx** [flatpak/flatpak#4159]
## System
- Chrome Os(debain 10 inside)
## Flatpak version
- 1.2.5
## Description of the problem
I installed neovim through flatpak, cause I need the 0.4 version.I installed coc.nvim for vim, but coc requires nodejs.
But it can't excute node command.
![image](https://user-images.githubusercontent.com/53030987/110211034-9484e700-7ecf-11eb-8e47-5bd24e8bfc7e.png)
![Screenshot 2021-03-06 at 22 59 31](https://user-images.githubusercontent.com/53030987/110211074-d6159200-7ecf-11eb-8a50-881976ae2001.png)

## Steps to reproduce
- Installed flatpak
- Using flatpak install neovim 
- Install vim plug(flatpak version)
- coc.nvim can't use installed nodejs

**Comment by Mek101** [comment]
You can't because flatpak provides a per-app environment isolated from the rest of the system.
You need to use `flatpak spawn` to run commands on the host system: https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn

**Comment by refi64** [comment]
For this particular case, you should be able to grab one of the Node SDK extensions which will then be accessible under `/usr/lib/sdk/node`.

**Comment by Starslayerx** [comment]
thx
