### ISSUE TITLE
Missing library in flatpak packages in PPA for Ubuntu 16.10 

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#416]
Hi,

here is the problem:

```
# flatpak update
flatpak: error while loading shared libraries: libgpgme-pthread.so.11: cannot open shared object file: No such file or directory
```

This is with this package version:
```
Package: flatpak
Architecture: amd64
Version: 0.6.13-0alexlarsson1~yakkety1
```

**Comment by LaurentBonnaud** [comment]
The problem comes from the fact that my system has KDE neon installed.  It installs this library:

`ii  libgpgme11:amd64                                1.8.0-neon0+16.04+build30                   amd64        GPGME - GnuPG Made Easy (library)`

that replaces the Ubuntu one:

`ii  libgpgme11:amd64                                1.6.0-3                                     amd64        GPGME - GnuPG Made Easy (library)`

and lacks the libgpgme-pthread.so.11 library.

**Comment by alexlarsson** [comment]
Yay ppas!
