### ISSUE TITLE
Issues with Spotify Client Accessing the Internet

### ISSUE THREAD

**Issue by mjones12209** [flatpak/flatpak#4160]
## Flatpak List:
     Spotify                  com.spotify.Client                       1.1.46.916.g416cacf1     stable     system
     Freedesktop Platform     org.freedesktop.Platform                 20.08.6               20.08   system
    default                  org.freedesktop.Platform.GL.default                               20.08      system
    Intel                    org.freedesktop.Platform.VAAPI.Intel                              20.08      system
    openh264                 org.freedesktop.Platform.openh264        2.1.0                    2.0      system
    Freedesktop SDK          org.freedesktop.Sdk                      20.08.6                  20.08    system

## Description of the problem
I am trying to use flatpak to install Spotify on Arch Linux but I get this error when I load the system up:
![image](https://user-images.githubusercontent.com/61482297/110215233-8d7dba80-7e76-11eb-86de-16e9ab4711f6.png)

## Steps to reproduce
[]$ flatpak run com.spotify.Client 
[]$ /app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
[spotifywm] spotify window found
Gtk-Message: 11:55:42.152: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[spotifywm] spotify window found
[spotifywm] attached to spotify
[spotifywm] spotify window found

I started here:

https://bbs.archlinux.org/viewtopic.php?id=252390
https://bugs.archlinux.org/task/65284

I cannot successfully downgrade libp11-kit and p11-kit.  I was wondering if anyone might have an thoughts on how to fix this issue?

**Comment by hfiguiere** [comment]
Nothing actionable here. If the problem still persist, file it with the flathub package.
