### ISSUE TITLE
Flatpak apps sometimes fail at DNS on Fedora 34 beta / systemd 248~rc2

### ISSUE THREAD

**Issue by garrett** [flatpak/flatpak#4162]
## Linux distribution and version

Fedora 34 beta as of 2012-03-07, both Silverblue and standard Workstation

## Flatpak version

flatpak-1.10.1-3.fc34.x86_64
systemd-248~rc2-1.fc34.x86_64

## Description of the problem

Flatpak applications have issues looking up some sites; others are fine.

## Steps to reproduce

1. Use Firefox (from Flathub; not sure if Fedora's Firefox Flatpak is affect or not) _or_ Epiphany Technology Preview in a Flatpak
2. Attempt to visit Amazon.com or Amazon.de
3. DNS issue shows up

Notes:
- When visiting other sites, such as GitHub.com, DNS lookup is fine, so it's not for all sites.
- Make sure Firefox isn't using DNS-over-HTTPS, which sidesteps the problem

This _might_ be related to systemd switching to varlink for DNS lookups using systemd-resolved, as it switched in systemd v247 (and I think F33 is on v246 still, whereas F34 beta is on 248 rc2).

**Comment by iqovoid** [comment]
I have the same problem, is there any easy fix to it?

**Comment by garrett** [comment]
For Firefox, there's a workaround to change your DNS provider in the settings to a DoH provider, like Cloudflare. It's an ugly hack and I, too, don't want to use Cloudflare for DNS, but that's what I know so far. Otherwise, we'd have to use non-Flatpak'd browsers...

Hopefully there's an actual fix soon.

**Comment by smcv** [comment]
My understanding is that this is believed to be a regression in systemd's DNS resolver stub, which is not noticeable for non-Flatpak apps on the host system, because those use the varlink interface instead.

**Comment by garrett** [comment]
Yep. It was exclusively hitting Flatpaks, so I wasn't sure if the issue and fix should be here or there.

I've upgraded to systemd locally to `systemd-248~rc2-3.fc34.x86_64` and can confirm that it works with sites that previously did not.

Closing. (Please reopen if there's still an issue with the newer systemd version.)

Thanks!

**Comment by garrett** [comment]
Whoops! I tested this wrongly (as I thought I was testing in a Flatpak browser, but it was a native one... the Flatpak one is still broken). Some additional DNS lookups are working, but there are still some issues, even in the newer version of systemd.

However, as this is a systemd bug, it should be fixed there.
