### ISSUE TITLE
Questions about flatpak

### ISSUE THREAD

**Issue by Nokia808** [flatpak/flatpak#4165]
Hello:

1) If user has 2 or more account, 1st is 1st user account that created during fresh installation & has all root powers while all other are created later on & have no any root powers. In this case can we installed per user (--user) from within 1st user account ?
I mean: I have user1 account with root power & user2 which is regular user without any root power. Is it possible to login to user1 & from within user1 run install command with --user option to install a flatpak application within user2 ? If possible then can you, kindly, give an example for that.

2) does run "flatpak update" from a user account will update flatpak packages per that user per all users ? Does this depend on nature of user account being 1st user / regular user or not ?

**Comment by mwleeds** [comment]
> Hello:
> 
> 1. If user has 2 or more account, 1st is 1st user account that created during fresh installation & has all root powers while all other are created later on & have no any root powers. In this case can we installed per user (--user) from within 1st user account ?
>    I mean: I have user1 account with root power & user2 which is regular user without any root power. Is it possible to login to user1 & from within user1 run install command with --user option to install a flatpak application within user2 ? If possible then can you, kindly, give an example for that.

Installing with `--user` will install into the current user's home directory, not that of any other user.
> 2. does run "flatpak update" from a user account will update flatpak packages per that user per all users ? Does this depend on nature of user account being 1st user / regular user or not ?

That command will list updates available both in the per-user and the system-wide installations.

That said, this is supposed to be an issue tracker. Questions about Flatpak should go in the IRC channel, the mailing list, or the Flathub forum.
