### ISSUE TITLE
Installation from USB fails under some cases

### ISSUE THREAD

**Issue by egrath** [flatpak/flatpak#4167]
OS: Endless OS 3.10 Development Branch
Flatpak version: 1.8.2

**Description:**

When creating a USB Media to carry applications to offline computers using the <code>flatpak create-usb</code> method, there are some cases when it's not possible to use this media as a source.

```
Error: While pulling app/org.videolan.VLC/x86_64/stable from remote flathub: /run/flatpak/sideload-repos/automount-run-media-egon-5d83b4ca%5Cx2df5e9%5Cx2d43b4%5Cx2d9924%5Cx2d18422c88a050/.ostree/repo: opendir(/run/flatpak/sideload-repos/automount-run-media-egon-5d83b4ca%5Cx2df5e9%5Cx2d43b4%5Cx2d9924%5Cx2d18422c88a050/.ostree/repo): No such file or directory
error: Failed to install org.videolan.VLC: While pulling app/org.videolan.VLC/x86_64/stable from remote flathub: /run/flatpak/sideload-repos/automount-run-media-egon-5d83b4ca%5Cx2df5e9%5Cx2d43b4%5Cx2d9924%5Cx2d18422c88a050/.ostree/repo: opendir(/run/flatpak/sideload-repos/automount-run-media-egon-5d83b4ca%5Cx2df5e9%5Cx2d43b4%5Cx2d9924%5Cx2d18422c88a050/.ostree/repo): No such file or directory
```

I nailed it down to the name of the mountpoint of the filesystem on the USB media. If this path contains dashes, the installation fails. The path contains dashes, if the filesystem on the USB stick does not contain a Label. In this case, the mountpoint is the UUID of the filesystem (ext4) or serial number (FAT), both containing dashes. As soon as the already created USB stick is assigned a label, installation completes successfully as expected.

**Reproduce**:
1. Format a USB stick as ext4 but don't assign a name (label)
2. Export the application to the usb device using the <code>flatpak create-usb</code> command
3. Head over to another computer and insert the USB stick (or uninstall the previously exported application on the current computer)
4. Install the application in question with <code>flatpak install</code>, it will take it from the USB device
5. The installation fails with the above error message
6. Unmount the USB stick and assign a Label without dashes
7. Mount the USB stick again and re-try the installation
8. The installation succeeds.

**Comment by mwleeds** [comment]
Thanks for the report. This has been fixed in libostree by https://github.com/ostreedev/ostree/pull/2293 and the fix will be in Endless OS 3.9.4.
