### ISSUE TITLE
Better handling of CRLF and LF in the same patch file

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#417]
We all know CRLF/LF is hell, and life is much easier when all files in git are committed with unified endings. I don't disagree. But reality is some repos don't have that, and I even long for consistent line endings *per file* in some cases.

When applying patches, it might be nice to pass the `--binary` flag to `patch`, to better handle cases where the line endings aren't consistent (e.g. patching a DOS-endings file with a UNIX-endings patch file)

**Comment by alexlarsson** [comment]
I wonder if this is helped by: https://github.com/flatpak/flatpak/issues/6 
i.e. if you say "use-git" then the patch is applied with git, which supports binary diffs.

**Comment by directhex** [comment]
```13:50:59 error: patch failed: md-addins.sln:777
13:50:59 error: md-addins.sln: patch does not apply
13:50:59 Error: module monodevelop: Child process exited with code 1```

**Comment by alexlarsson** [comment]
With that you can say `options: ["--binary"]`
