### ISSUE TITLE
'flatpak search' | Header not printed to destination file

### ISSUE THREAD

**Issue by Ricky-Tigg** [flatpak/flatpak#4176]
**OS:** Fedora; **Flatpak version:** 1.10.1; **Bash version:** 5.0.17

**Description of the problem**: `flatpak search` which prints as intended its header to _stdout_
```
$ flatpak search signal
Name             Description        Application ID       Version   Branch  Remotes
Signal Desktop   Private messenger  org.signal.Signal    1.40.1    stable  flathub
[...]
```
**does not print** it while forwarding to a destination file.
```
$ flatpak search signal >> output; cat output
Signal Desktop   Private messenger  org.signal.Signal    1.40.1    stable  flathub
[...]
```
This causes functions set with pipeline as input and who have the ability to extract content, to be unable to extract the header.
```
$ flatpak search signal | awk 'NR==1{print;next} tolower($1)=="signal"'
Signal Desktop   Private messenger  org.signal.Signal    1.40.1    stable  flathub
```

**Comment by mwleeds** [comment]
Some flatpak commands intentionally change their output when stdout is not a tty to make it easier to parse. Can't you just change your `awk` command accordingly?

**Comment by Ricky-Tigg** [comment]
Hello! After all the behaviour i depicted here is not tied to the use of the _flatpak_ function. It could be illustrated as well by applying a forwarding to a file, to the initial tty's stdout, for instance either by the use of the option '`>`' or '`>>`'; e.g. '`flatpak search signal > <destination_file>`'. 

Could you please consider bringing to your answer a **clue** in order to achieve my goal and produce an _stdout_ for a **forwarding to file** that would be identical to the _stdout_ produced  for a _tty_? I lack developer's knowledge to investigate what could be a valid command to be executed.

**Comment by mwleeds** [comment]
> Could you please consider bringing to your answer a **clue** in order to achieve my goal and produce an _stdout_ for a **forwarding to file** that would be identical to the _stdout_ produced for a _tty_? I lack developer's knowledge to investigate what could be a valid command to be executed.

I asked above why you thought the output needed to be identical in both cases (tty vs file). Doesn't seem like you answered.

**Comment by Ricky-Tigg** [comment]
Your messages |
- Lack fundamental coherence
- Not even related to context
- For more, just name them; you know yourself!

No thank you. Users do expect developers on GitHub.
