### ISSUE TITLE
bwrap: Can't bind mount /oldroot/var/lib/flatpak/runtime/org.freedesktop.Sdk on /newroot/usr/lib/i386-linux-gnu: No such file or directory

### ISSUE THREAD

**Issue by fastrizwaan** [flatpak/flatpak#4184]
## Linux distribution and version
 lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye

## Flatpak version
flatpak --version
Flatpak 1.10.2

## Description of the problem
**$ flatpak run org.DolphinEmu.dolphin-emu** 
```
bwrap: Can't bind mount /oldroot/var/lib/flatpak/runtime/org.freedesktop.Sdk.Compat.i386/x86_64/20.08/a1f0728770a18427fc0f5cb2ee5cf89c16b55802943c6d85579439bdadae0c98/files on /newroot/usr/lib/i386-linux-gnu: No such file or directory
error: ldconfig failed, exit status 256
```

## Steps to reproduce

1. install dolphin-emu (perhaps sdk.compat.i386 too)
2. run dolphin emu
3. we get the above error

**Comment by smcv** [comment]
This looks like the same issue as #4175, which is a bug in the current KDE runtime.

**Comment by Eonfge** [comment]
Have this as well, when I install `org.freedesktop.Sdk.Compat.i386` all KDE applications stop working. And yes, seems the smae as #4175

**Comment by smcv** [comment]
From #4175:
> Should be fixed in the latest KDE runtime build, please re-check.

**Comment by Eonfge** [comment]
Tested with Kid3 and Qbittorrent and both work
