### ISSUE TITLE
Package installation fails in 50% of cases: Timeout was reached

### ISSUE THREAD

**Issue by kirbykevinson** [flatpak/flatpak#4185]
* Fedora 33
* Flatpak 1.10.2

When installing any kind of packages, approximately half of them give up because of the connection timing out while another half installs just fine. Meanwhile, there are no problems accessing the Flathub website. The issue may be related to CDN choosing process as the machine I'm using is located in located in the Western Sibera region of Russia, and this country is notorious for blocking arbitrary things on the Internet. Here are the logs of the process happening: [flatpak.log](https://github.com/flatpak/flatpak/files/6175337/flatpak.log).

**Comment by kirbykevinson** [comment]
I couldn't reproduce the issue under a VPN, so this can be additionaly a Flathub issue.

**Comment by kirbykevinson** [comment]
The issue miraculously vanished after I reset my router. Sorry for disturbing you.

**Comment by xmready** [comment]
I'm having the same issue, on multiple different routers, different ISPs and different computers. I get timeouts constantly and the speed is super slow even on fiber. I don't see a flag during flatpak install to retry if this happens. There is something that needs to be fixed, I have no idea what.
