### ISSUE TITLE
Make it possible to limit used CPU on flatpak-builder

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#419]
AFAIU flatpak-builder is using automatically all available CPU cores, our sysadmins ask me if it's possible to tune. A fast look at the code suggested me it's not:
```
int
builder_context_get_n_cpu (BuilderContext *self)
{
  return (int) sysconf (_SC_NPROCESSORS_ONLN);
}
```
Did I miss something? Would it be possible to do something to that end?

**Comment by alexlarsson** [comment]
You can set "no-parallel-make" for the module on a per-module basis, and I guess you can add a make-args that overrides the -j value. However, those require changing the manifest, which seems a bit ugly. It should be easy to add a flag to builder itself to modify this.

**Comment by alexlarsson** [comment]
That should help you.

**Comment by aleixpol** [comment]
Thanks!
