### ISSUE TITLE
Apps that are installed via flatpak can't see other installed programs

### ISSUE THREAD

**Issue by Midorina** [flatpak/flatpak#4195]
## Linux distribution and version
Pop!_OS 20.10
## Flatpak version
Flatpak 1.8.5
## Description of the problem
Any package that I install via flatpak can not see other installed packages for some reason. For example:
### PyCharm
PyCharm installed via flatpak can not see the interpreters that are installed by the user. I installed Python 3.9 and it is located in  `/usr/bin/python3.9` but PyCharm can't see it, meanwhile these are visible and usable by PyCharm:
`/usr/bin/python3.7`
`/usr/bin/python3`
but not `/usr/bin/python3.9`.

I tried `/var/run/host/usr/bin/python3.9` and PyCharm can see it, however, PyCharm is giving weird errors with it and the interpreter is not usable.
**See this:** https://stackoverflow.com/questions/51517053/pycharm-doesnt-see-python3-7-interpreter
And this: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009391540-PyCharm-can-t-see-python-binaries-even-if-they-are-there-
### FileZilla
Similarly, I can't change the default text editor application in FileZilla because it can't see `gedit` or `Atom` that I installed as a debian package.
**See this:** https://askubuntu.com/questions/1090543/filezilla-3-38-1-file-associations-on-ubuntu-18-04-1-lts
And this: https://forum.filezilla-project.org/viewtopic.php?t=50590
### Birdtray
Similarly, It can't see my Thunderbird if I install Thunderbird as a debian package.
I set thunderbird location: `/usr/bin/thunderbird`
Resulting error: `execvp link to executable not found`
## Steps to reproduce
1- Download any flatpak package
2- In the package, try to access newly installed packages that are located in `/usr/bin/` (that is not installed via flatpak)
3- It can't see the other package.

I'm relatively new to Linux, and this issue is making me lose my desire to use Ubuntu. Is this by design and should I uninstall every program that I installed via flatpak, or is there a workaround? Thank you.

**Comment by nanonyme** [comment]
This is working as designed. The apps are operating insid sandbox.

**Comment by Midorina** [comment]
> Step 2 is working as designed. The apps are operating inside sandbox.

Yes, I've read through [this](https://docs.flatpak.org/en/latest/sandbox-permissions.html) and tried to give them access to see these files, however, it didn't work. Anyway, I won't bother trying to deal with Flatpak anymore. I've uninstalled every application I've installed via flatpak. Also, [see this.](https://flatkill.org/) Closing the issue now.

**Comment by mariobaldini** [comment]
I'm facing the same as @Midorina and consider a valid use case -- not in conflict with Flatpak purpose.

Even though sandboxing is desired, accessing some system resources also is. 
Just like a photo app shall access ~/Pictures/, in this case the resource is an extra python interpreter. 

Sandboxing is maintained here: we don't want replace the flatpak py version -- that shall indeed remain the same;
but instead provide a way for accessing `/usr/bin` in some other way.

I've tried with `flatpak override --user --filesystem=/usr/bin com.jetbrains.PyCharm-Professional`
or granting other permissions with Flatseal, without success.

**Comment by hfiguiere** [comment]
> Sandboxing is maintained here:

No it is not. This is where you misunderstand how this work.
