### ISSUE TITLE
Problems while installing arduino-ide and antimicroX

### ISSUE THREAD

**Issue by thetechnician274** [flatpak/flatpak#4198]
HI
I am using linux Alpine 3.13.3 32bit and Flatpak 1.10.2
When trying to install arduino ide using `flatpak install flathub cc.arduino.arduinoide` i get this error `Looking for matches…
error: Nothing matches cc.arduino.arduinoide in remote flathub
`
I have also tried installing it using `flatpak install cc.arduino.arduinoide.flatpakref`, but i got this messege `error: No such ref 'app/cc.arduino.arduinoide/i386/stable' in remote flathub`
Same thing happens when trying to install antimicroX.
However some applications (eg. Atom) installed without any problems.

Thanks for all answers

**Comment by smcv** [comment]
Flatpak is correctly telling you that there is no i386 (32-bit) version of `cc.arduino.arduinoide` available on Flathub. This is not a Flatpak bug, there really is no i386 version available: if you run

```
$ flatpak remote-ls --arch=i386 -d flathub
$ flatpak remote-ls --arch=x86_64 -d flathub
```

you'll see that there are a lot more apps available for x86_64 than for i386.

Newer versions of the freedesktop.org runtime (19.08 and 20.08) only support x86_64 and aarch64 64-bit systems (see flathub/flathub#1201, flathub/flathub#1531), and the Arduino IDE uses the 20.08 runtime.

Either Atom is still using an older runtime such as 18.08 that had i386 support, or you have an old/unmaintained version installed and it used that older runtime.
