### ISSUE TITLE
flatpak-builder: Allow using a local checkout as the source of a git repo

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#42]
If you're checking in a builder manifest into the git repo of your app and using flatpak to build it, it doesn't necessarily make a lot of sense to download the git repo again. We should have some way to support using the existing repo, maybe even the current outstanding changes to it.

Not sure exactly how this would work though. Its complicated both how to reference to the current git repo, and how to reuse the current checkout without old builds affecting the new build.

**Comment by mwleeds** [comment]
This feature would be very helpful in getting working flatpak support into GNOME Builder. I can work on it if no one else is. The first step would be to allow a path to be specified for git sources like it is for archive sources, right?

**Comment by muelli** [comment]
FWIW: I've tried to use smth like

            "sources": [
                {
                    "type": "git"
                    , "url": "."

which seems to work. Sort of. I then can't convince my flatpak-builder 0.6.7 that things have changed, e.g. it'll always tell me that it has a cache hit instead of picking up new commits.  Using an absolute file:// URI works better. I need, however, to create commits in order for flatpak to pick it up.

**Comment by cmollekopf** [comment]
This would indeed be great. The crude hack that I'm using right now is:
* Define the git repo with a file url.
* Replace the corresponding directory in .flatpak-builder/git/ with a symlink to the local git repostiories .git directory
* Add a second source line of type patch with a static location
* Build using a wrapper script that always first dumps "git diff" into the patchfile

That works, but it's not pretty.

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#13
