### ISSUE TITLE
Open file limit is too small for Flatpaks

### ISSUE THREAD

**Issue by Avamander** [flatpak/flatpak#4201]
## Linux distribution and version
Ubuntu 20.04.2

## Flatpak version
1.6.5

## Description of the problem
In the specific Flatpak's repository I was told that it's a general Flatpak issue https://github.com/flathub/com.valvesoftware.Steam/issues/736

After increasing open file limit in host's settings (`/etc/systemd/system.conf`, `/etc/security/limits.conf`) some games still crash with `eventfd: Too many open files`. It's unclear if and how this limit can be increased for the Steam Flatpak. 

I think other people have encountered this problem as well (https://gist.github.com/stefanocoding/ec7d54116559781455d67019439e4ae5), but I've encountered this with Stardew Valley. 

## Steps to reproduce
Install the Steam flatpak and try to play the games mentioned.

**Comment by smcv** [comment]
What are the soft and hard limits on the number of open files per process on the host system? `ulimit -a -S` and `ulimit -a -H`, look for "open files (-n)")

What are the soft and hard limits on the number of open files per process inside the Flatpak sandbox? (`flatpak run --command=bash com.valvesoftware.Steam -c "ulimit -a -S"` and `flatpak run --command=bash com.valvesoftware.Steam -c "ulimit -a -H"`)

When I try those on Debian 11, I get a soft limit of 1024 and a hard limit of around a million (actually 1024×1024), matching the recommendations in https://github.com/zfigura/wine/blob/esync/README.esync. systemd >= 234 sets those limits by default, so many newer distributions (e.g. Debian 11) will already have them, and I'm somewhat surprised if Ubuntu doesn't. A limit of 512×1024 has been seen elsewhere and is probably enough.

**Comment by smcv** [comment]
> I've encountered this with Stardew Valley

I'm surprised by this. The usual reason for Steam games to need a lot of file descriptors is that they are running under Proton, which contains a modified version of Wine that uses eventfd-based synchronization ("esync") - but Stardew Valley is a native Linux game that shouldn't normally be running on Proton. It's working fine for me, both with and without Flatpak.

**Comment by Avamander** [comment]
> What are the soft and hard limits on the number of open files per process on the host system? ulimit -a -S and ulimit -a -H, look for "open files (-n)")

```
➜ ulimit -S -n              
1024
➜ ulimit -H -n
1048576
```

> What are the soft and hard limits on the number of open files per process inside the Flatpak sandbox?

```
➜  flatpak run --command=bash com.valvesoftware.Steam -c "ulimit -S -n"
1024
➜  flatpak run --command=bash com.valvesoftware.Steam -c "ulimit -H -n"
1048576
```

> but Stardew Valley is a native Linux game that shouldn't normally be running on Proton. It's working fine for me, both with and without Flatpak.

It takes minutes, the crash is not instant.

**Comment by smcv** [comment]
If you're using Proton to run the Windows version of Stardew Valley, and it is gradually leaking eventfds, then that might indicate that in Windows, it would be leaking mutexes (which are a less limited resource).

**Comment by Avamander** [comment]
I'm using proton yes, it works because it doesn't use pressure-vessel. I can't however interpret the `ls -l` output so that it'd help.
