### ISSUE TITLE
OBS Studio doesnt work with NVENC 

### ISSUE THREAD

**Issue by iWeaker4you** [flatpak/flatpak#4207]
Debian 11 Testing
Flatpak version 1.10.2-1
Install OBS using this guide https://flathub.org/apps/details/com.obsproject.Studio
When I start OBS for the first time, I detect that I had NVENC without any problem and I install the necessary dependencies correctly, but when recording, it gives me an NVENC error

I have installed the dependencies on my Debian correctly, the packages are
libnvcuvid1 and libnvidia-encode1

"Failed to open NVENC"

![Captura de pantalla de 2021-04-02 20-42-35](https://user-images.githubusercontent.com/49424816/113466878-00397180-93f4-11eb-84df-7815a9860be5.png)

**Comment by Magicrafter13** [comment]
Did you close the issue because you fixed the problem? I get the same message.
