### ISSUE TITLE
GSettings get reset after update to org.gnome.Sdk 3.38

### ISSUE THREAD

**Issue by gjanssens** [flatpak/flatpak#4209]
## Linux distribution and version
Reported on several distributions, eg  Fedora 32  (my own system), Fedora 33, Ubuntu  20.04, Debian bullseye,...
## Flatpak version
On Fedora 32,  flatpak is version 1.8.2
## Description of the problem
I'm a maintainer of the gnucash project and we release our application as a flatpak via Flathub. With the most recent release (4.5) we upgraded to org.gnome.Sdk 3.38. Users are now complaining that when they update to our  latest package, all of their GSettings for gnucash are lost.
I have tested on my own system and I see the same issue. GSettings is still working though - all changes made will be retained.
Downgrading the gnucash flatpak to a previous version, which still is based on org.gnome.Sdk 3.36 restores all these settings to what they were before upgrading to Sdk 3.38.

## Steps to reproduce
* Configure the flathub repo
* Install the org.gnucash.GnuCash flatpak: `flatpak install  --user org.gnucash.GnuCash'
* Downgrade to gnucash 4.4-4: `flatpak update --commit 298cf1b5b77a15d7afda8a58721b075ec8ec0c59f4b16e1e19db98e37c097b07 org.gnucash.GnuCash`
* Run the application: `flatpak run org.gnucash.GnuCash`
* Assuming this is the very first time you ever run gnucash it will offer a few first-run dialogs. Dismiss those and indicate you don't want those be shown again (that preference will go into  GSettings).
* Restart gnucash
  * Observe the first-run dialog is not presented again. This shows GSettings is working.
* Quit gnucashand update to the most recent version: `flatpak update org.gnucash.GnuCash`
  * At the time of this writing that should install gnucash 4.5
* Run the application: `flatpak run org.gnucash.GnuCash`
  * Observe the first-run dialog is shown again, indicating the GSettings configuration has been reset.
* Dismiss the dialog and indicate you don't want it to see the first-run dialog again next startup. As another GSettings tweak, uncheck the box in the Tip-of-the-day window to prevent it from being shown on the next run. This way the GSettings are now in a different state from what they were when running  gnucash 4.4-4.
* Restart gnucash
  * Observe the first-run dialog and the tip-of-the-day window are not presented again. This shows GSettings is working.
* Quit gnucash.
* Downgrade to gnucash 4.4-4 again: `flatpak update --commit 298cf1b5b77a15d7afda8a58721b075ec8ec0c59f4b16e1e19db98e37c097b07 org.gnucash.GnuCash`
* Run the application: `flatpak run org.gnucash.GnuCash`
  * Observe the first-run dialog is not presented, but the tip-of-the-day window is. This shows the GSettings state from before the upgrade to gnucash  4.5/sdk 3.38 is being used again.

**Comment by AdrianVovk** [comment]
@gjanssens I took a quick look at your manifest and it looks like you're still using the dconf hole. [This blog post](https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/) should be helpful. This is an old change, so I'm not entirely sure what triggered gsettings to finally tansition you into the new storage mechanism; maybe a regression introduced between 3.36 and 3.38 broke the "keep gsettings in legacy mode for old apps" feature, or maybe the GNOME team did some code clean-up and decided it's been long enough to let people transition

**Comment by gjanssens** [comment]
Thank you for the link to the blog post. It was very enlightening.
Unfortunately we're still stuck. There's a nasty detail in the dconf  migration option. As per [the flatpak manual](https://docs.flatpak.org/en/latest/sandbox-permissions.html#dconf-access):

> The path must be similar to your app-id or it will not be allowed (case is ignored and _ and - are treated equal).

Unfortunately we can't do that. For historical reasons gnucash uses "/org/gnucash/" as base path in GSettings while the app-id is "/org/gnucash/GnuCash". I have found no way for flatpak to accept the shorter GSettings path. When running gnucash it will  generate this error:

> F: Ignoring D-Conf migrate-path setting /org/gnucash/

Is there a way to relax the sanity check ? Altering our GSettings base path is not obvious as far as I know without affecting our complete user base, not only flatpak users.
