### ISSUE TITLE
GPG signatures found, but none are in trusted keyring

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#421]
Hi,

here is the problem:

```
# flatpak install gnome-apps  org.gnome.Totem/x86_64/stable
Updating: org.gnome.Platform/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome
No updates.
Installing: org.gnome.Totem/x86_64/stable from gnome-apps

1 delta parts, 6 loose fetched; 6805 KiB transferred in 6 seconds                                                                             
Installing: org.gnome.Totem.Locale/x86_64/stable from gnome-apps


Warning: Failed to install org.gnome.Totem.Locale/x86_64/stable: While pulling runtime/org.gnome.Totem.Locale/x86_64/stable from remote gnome-apps: GPG signatures found, but none are in trusted keyring
```

**Comment by LaurentBonnaud** [comment]
I am not the only one with this problem, see:

https://askubuntu.com/questions/848982/how-to-add-the-runtime-org-gnome-nautilus-locale-x86-64-stable-flatpaks-gpg-sig

**Comment by LaurentBonnaud** [comment]
BTW, the error message "Failed to install" is misleading because a second try gives this output:
```
# flatpak install gnome-apps  org.gnome.Totem/x86_64/stable
error: org.gnome.Totem/x86_64/stable already installed
```

**Comment by alexlarsson** [comment]
Seems some refs are not properly signed. I wonder how that happened.

**Comment by alexlarsson** [comment]
Should be fixed now, reopen if some app is broken still

**Comment by LaurentBonnaud** [comment]
I confirm that the problem is fixed.  Thanks a lot!

**Comment by Corax42** [comment]
I get the same error when trying to install the gnome-recipes.flatpakref from http://flatpak.org/apps.html . The feedreader.flatpakref from the same site installed just fine, so it would appear the recipes file is inorrectly signed.

**Comment by Vistaus** [comment]
I get the same error when trying to install Spotify from Flathub.
