### ISSUE TITLE
Assign flatpak run org.chromium.Chromium to an alias

### ISSUE THREAD

**Issue by softshipper** [flatpak/flatpak#4212]
Hi all,
Linux distribution: PopOS 20.10
Flatpak version: 1.8.5

I am using https://www.cypress.io/ for react components e2e testing. The CypressJS could not detect the installed Chromium on my computer, because I have installed it with `flatpark`.  

One of the contributor of CypresJS told me the following:

> It appears that we do not currently support flatpak browser detection
> due to flatpaked programs not appearing in path. If you can assign
> `flatpak run org.chromium.Chromium` to an alias or a standalone
> executable in $PATH, the autodetection may work.

Is it possible to assign `flatpak run org.chromium.Chromium` to an alias? If yes, then how?

Thanks

**Comment by happy-san** [comment]
Hey @softshipper, Did you get this done?

**Comment by refi64** [comment]
You can do something like

```
$ echo -e '#!/bin/sh\nexec flatpak run org.chromium.Chromium' | sudo tee /usr/local/bin/chromium
$ chmod +x /usr/local/bin/chromium
```
