### ISSUE TITLE
Allow multiple version for `add-extensions` extension point

### ISSUE THREAD

**Issue by hfiguiere** [flatpak/flatpak#4238]
## Linux distribution and version

Fedora 34

## Flatpak version

1.10.2

## Description of the problem

Allow multiple version for the same extension point.

The idea here is to allow multiple branches.
I triggered #4234 by trying to put `"version": "20.08;stable"`
The idea would be to have `20.08` and `stable` branch of the extensions mounted wheb specifying the above version property.
The order would determine the priority in case of duplicate. First come first loaded, so an extension in `stable` would be ignore if there is one in `20.08`

The background: Allowing Linux Audio plugins that are linked statically (read, no source code) to be loaded without the burden of having to have multiple branches over time. It would help simplifying the packaging. This plugins are already distributed as static binaries.

## Steps to reproduce

n/a

**Comment by gasinvein** [comment]
Doesn't the `versions` (note the `s`) property do exactly what you want?

**Comment by hfiguiere** [comment]
Yes, yes it does. And for some reason I missed it in the documentation.

**Comment by hfiguiere** [comment]
Thanks!

**Comment by abique** [comment]
I'm not aware of `versions`.
Is it documented?

**Comment by smcv** [comment]
The `flatpak-metadata(5)` man page and https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-metadata (same content) are the reference documentation for everything you can put in a manifest.

**Comment by abique** [comment]
@smcv Thank you very much.
But I'm not sure what is the correct syntax for specifying multiple versions.
Was it in the man?

**Comment by hfiguiere** [comment]
> @smcv Thank you very much.
> But I'm not sure what is the correct syntax for specifying multiple versions.
> Was it in the man?

Like elsewhere, a string with components separated with a ';'.  It's in the description of this issue :-)

**Comment by abique** [comment]
So can I do: `versions: '20.08;19.08'`?
Would that work:
 - `versions: '20.08;stable'`
 - `versions: '<=20.08'`

**Comment by hfiguiere** [comment]
> So can I do: `versions: '20.08;19.08'`?

In theory yes, in practice it's not a good idea.

> Would that work:
> 
>     * `versions: '20.08;stable'`

That's the idea here. TBF I'm torn between `stable` that is the default, and something else as an explicit branch.

>     * `versions: '<=20.08'`

It's a string not a version number, so this make no since.

**Comment by abique** [comment]
https://flathub.org/builds/#/builders/32/builds/45544 is starting.

**Comment by abique** [comment]
Yes it works, I can use Surge from 19.08.
