### ISSUE TITLE
How to change "per-user" applications to "system-wide" ?

### ISSUE THREAD

**Issue by FarhadMohammadiMajd** [flatpak/flatpak#4243]
## Linux distribution and version
Fedora 34
## Flatpak version
Flatpak 1.10.2
## Description of the problem
Hello, I mistakenly installed one application with the --user option **by the root account |:** while I can't and don't want to run applications by the root account, so I need to change its installation mode or doing other works to make it accessible by all other users.

THANKS VERY MUCH

**Comment by gasinvein** [comment]
You can't change installation for installed flatpaks. Just uninstall it and install back the correct way.
Untested, but can probably wipe all root-user flatpaks with `sudo flatpak uninstall --user --all`
