### ISSUE TITLE
Adwaita-Dark GTK4

### ISSUE THREAD

**Issue by nickavem** [flatpak/flatpak#4244]
## Linux distribution and version
Fedora Linux SIlverblue 34.20210421.n.0
## Flatpak version
Flatpak 1.10.2
## Description of the problem
GTK4 apps like Solanum and To-Do (Nightly) no longer respect adwaita-dark when changing the theme using gnome-tweaks. This functionality is expected since native apps like gtk4-demo do change to a dark theme.
## Steps to reproduce
1. Install `gnome-tweaks`
2. Navigate to Gnome Tweaks > Appearance > Applications > Adwaita-dark

Actual Behavior: GTK4 flatpak apps are still the standard adwaita theme.

Expected Behavior: GTK4 flatpak apps respect the adwaita dark theme.

**Comment by BrainBlasted** [comment]
Dark theme as actually not supported as part of the GNOME platform currently, and Adwaita-dark does not exist for GTK4 apps. There is Adwaita:dark which is different and set by each individual app. This is not an issue with flatpak, to my knowledge.

**Comment by nickavem** [comment]
Well, that kind of sucks. Is there any plan to bring adwaita dark back?

**Comment by Exalm** [comment]
Adwaita-dark no, a proper dark mode that's not adwaita-dark yes.

**Comment by nickavem** [comment]
Nice! So, can I ask the GTK4 app devs to implement the adwaita:dark solution until then, or is there anything I can do on my end?

**Comment by BrainBlasted** [comment]
All there is for now is to wait for a proper dark mode solution :)
