### ISSUE TITLE
[Build Option] No package 'polkit-agent-1' found - is polkit mandatory?

### ISSUE THREAD

**Issue by rubyFeedback** [flatpak/flatpak#4246]
Hey guys.

I wrote a pseudo-package manager in ruby a long time ago; it handles all the programs
I want to compile or install. Anyway, that's just for a bit of background info partially
pertaining to this issue request. I try to test code, repackage different formats and
so forth, so that's mostly my use case, so I like to test flatpak as well.

For this I tend to prefer to compile from source. Flatpak makes this convenient
via github, like this URL:

    https://github.com/flatpak/flatpak/releases/download/1.10.2/flatpak-1.10.2.tar.xz

However had, this fails for me right now:

    No package 'polkit-agent-1' found

Now I know how to get this all installed, polkit and what not. But I was also wondering
whether it would be possible to avoid polkit altogether? I don't know the internals so
I don't know whether flatpak needs it 100%. I'd be fine with reduced functionality; for
me it's simpler to just keep things small-ish when possible.

I looked at "./configure --help" for options including "pol", "kit" or "sec" but could not
find such an option.

This leads me to the issue request:

- Would it be possible to avoid using polkit altogether? Something like "--disable-polkit"
or something like that?

This is probably a low priority thing, but on the other hand it may be quite simple to change
IF the flatpak team decides this would have merit. If vital functionality is handicapped then
please just disregard and close this issue altogether. If the functionality is not vital, though,
then this would be quite convenient. I already keep track of remote flatpak URLs locally, so
it would complement if I could also offer ad-hoc building and repackaging as is. Thanks
for reading anyway!

**Comment by nanonyme** [comment]
It's this component that currently results in the polkit dependency FWIW `system-helper: The flatpak-system-helper service, which runs as root on the system bus and allows non-root users to modify system installations`

**Comment by smcv** [comment]
If you configure with `--disable-system-helper` then polkit shouldn't be needed.

**Comment by refi64** [comment]
If the above solution does not work, please mention it here so this can be re-opened, otherwise closing now.

**Comment by nanonyme** [comment]
It definitely does work. Freedesktop-sdk uses flatpak without polkit in its CI.
