### ISSUE TITLE
Epiphany Flatpak (stable, 3.22) Generates Multiple systemd-coredump Processes Until CPU is Hogged

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#425]
I'm using Flatpak on openSUSE Tumbleweed. I installed Epiphany via flatpak atop the stable GNOME 3.22 runtime. Epiphany installed through openSUSE (zypper) runs like a charm but Epiphany installed via Flatpak keeps generating systemd-coredumps until the CPU Is capped and the system isn't usable.

**Comment by mcatanzaro** [comment]
It works for me nowadays. Unless you're still hitting this, I suggest this be closed.
