### ISSUE TITLE
Cannot install in NTFS partition

### ISSUE THREAD

**Issue by Srijan1214** [flatpak/flatpak#4250]
## Linux distribution and version
Arch

## Flatpak version
Flatpak 1.10.2

## Description of the problem
I am trying to install flatpak apps on a separate NTFS partition by following the steps from `man flatpak-installation`.

But I am getting some errors. Some apps get installed successfully while some don't. However, while installing, almost all installs give the following warning. `Warning: Cannot create repo on revokefs mountpoint /var/tmp/flatpak-cache-AJKI20/org.freedesktop.Platform.GL.nvidia-465-24-02-FX9C20: mkdirat: Permission denied`. Usually, I can still install the app if I get this warning.

Sometimes I get the following error `Warning: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256` This results in me being completely unable to install the software. One example is `android studio`. I can install it at the default location but cannot do so in the NTFS partition.

I am sure that I have the permissions to the mount point because the uid and gid is set to my current user in fstab. Also, the /var/tmp/flatpak-cache-AJKI20 has the `drwxr-xr-x` permissions and it belongs to the current user and group (not root).

I only get this problem when trying to install to the NTFS partition and not in the default install location.

## Steps to reproduce
Create a file `/etc/flatpak/installations.d/extra.conf`.

The following are the contents.

[Installation "extra"]
Path=/mnt/sda3/Arch_Flatpak_Installations/
DisplayName=NTFS Partition
StorageType=harddisk
SetDefaultInstall=yes

run `flatpak --installation=extra remote-add flathubhttps://flathub.org/repo/flathub.flatpakrepo`

Try to install any app (an example would be `android studio`)

**Comment by hfiguiere** [comment]
I don't think this can be supported. The problem is NTFS here (either the filesystem design or its implementation)
