### ISSUE TITLE
Subsummaries broke installation of cross-arches from libflatpak

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#4252]
In Builder, for years we've allowed selecting an alternate architecture for the project (such as aarch64). GNOME Builder would automatically install the SDKs for you and happily go along w/ QEMU.

It appears that since the addition of subsummaries, this no longer works. We fail to find the runtime because there is no information on `aarch64` in the list of refs we see.

While not an ABI break, it's certainly an expectation break. How should we go about fixing this from the client side. We don't have access to the internals that the flatpak command does such as `flatpak_remote_state_ensure_subsummary()`.

**Comment by chergert** [comment]
One possible way to fix this without breaking ABI would be to add something like `FLATPAK_QUERY_FLAGS_ALL_ARCHES` and we can just use `flatpak_installation_list_remote_refs_sync_full()`.

**Comment by alexlarsson** [comment]
Yeah, a new query flags sounds about right. Another alternative would be to be able to give a list of arches of interest, but that is more complex and would need an API addition.

**Comment by alexlarsson** [comment]
Can you verify that the PR helps you?

**Comment by chergert** [comment]
Almost.

I can find the `FlatpakRef` now but I still get a failure when running a `FlatpakTransaction` which did an `_add_install(..., "gnome-nightly", "org.gnome.Sdk/aarch64/master")`.
