### ISSUE TITLE
Application & appid rename

### ISSUE THREAD

**Issue by okias** [flatpak/flatpak#4253]
I'm looking into problem:

- we need rename application
- we also at that occasion like to change appid to correspond to the new name

Can we somehow tell flatpak in latest bugfix release under old appid to migrate to new one? So when we release org.app.xy 5.1.2 to migrate to org.app.abc 6.0 ?

Or which way for user and settings migration is recommended for seamless user experience?

Thank you

**Comment by mwleeds** [comment]
Have you checked out the `flatpak build-export --end-of-life-rebase` option? It can redirect your users to the new app ID.

**Comment by refi64** [comment]
No reply, assuming the rebase option worked.
