### ISSUE TITLE
'create-usb' | No creation of application onto USB device

### ISSUE THREAD

**Issue by Ricky-Tigg** [flatpak/flatpak#4259]
**OS:** Fedora 34; **Flatpak version**: 1.10.2

Nothing written onto USB device.
```
# flatpak --system -y update
# flatpak remote-modify --collection-id=org.flathub.Stable flathub
$ cat /var/lib/flatpak/repo/config | grep ^collection-id
collection-id=org.flathub.Stable
# flatpak create-usb /run/media/yk/4C22-9648/ org.zaproxy.ZAP
Warning: Related ref ‘runtime/org.freedesktop.Platform.Locale/x86_64/19.08’ is partially installed. Use --allow-partial to suppress this message.
Writing objects: 676
```
The lack of context of the reported warning makes its mention irrelevant.  As a prerequisite `flatpak -y install` is expected to install applications properly.

**Comment by mwleeds** [comment]
Yeah the issue is that locale extensions are by default installed with only the user's language rather than all available, to save disk space. But this becomes an issue if the user is trying to share an application offline with a user who speaks a different language (albeit this is probably not the usual case), hence the warning. Even online it's not possible to share an application in a language other than the main configured one, unless the user knows to manually install the full locale extension.

I agree, the user experience here isn't great because all of that is not clear from that warning message.

We have an issue open already for one potential improvement: https://github.com/flatpak/flatpak/issues/3505

**Comment by mwleeds** [comment]
> Nothing written onto USB device.

Are you sure? It writes to the hidden-by-default `.ostree` directory on the drive.

**Comment by Ricky-Tigg** [comment]
Indeed.
```
$ tree --noreport --filelimit 7 -aL 3 .ostree/
.ostree/
└── repo
    ├── config
    ├── extensions
    ├── .lock
    ├── objects
    ├── refs
    │   ├── heads
    │   ├── mirrors
    │   └── remotes
    ├── state
    │   └── f9bbe3b3c6a139ed3136c737fd14dc73991eafc4ed305732b9c9c90a859a5917.commitpartial
    └── tmp [9 entries exceeds filelimit, not opening dir]
```
No binary present in that directory to start up the application. Do you observe the same on your USB drive?

**Comment by mwleeds** [comment]
The intention is for you to be able to install from the USB not run the application directly. See the docs [here](https://docs.flatpak.org/en/latest/usb-drives.html) or the create-usb man page.

**Comment by Ricky-Tigg** [comment]
While an installation became corrupted, is then `--reinstall-all` instead of `install` compatible with `--sideload-repo=`?

**Comment by Ricky-Tigg** [comment]
While an installation became corrupted, is then `flatpak repair --reinstall-all` instead of `flatpak install`, compatible with `--sideload-repo=`?

**Comment by Ricky-Tigg** [comment]
While an installation became corrupted, is then `flatpak repair --reinstall-all --sideload-repo=/run/media/yk/4C22-9648/ .ostree/repo flathub org.zaproxy.ZAP` supported instead of `flatpak install --sideload-repo=/run/media/yk/4C22-9648/ .ostree/repo flathub org.zaproxy.ZAP`?

**Comment by mwleeds** [comment]
> While an installation became corrupted, is then `flatpak repair --reinstall-all --sideload-repo=/run/media/yk/4C22-9648/ .ostree/repo flathub org.zaproxy.ZAP` supported instead of `flatpak install --sideload-repo=/run/media/yk/4C22-9648/ .ostree/repo flathub org.zaproxy.ZAP`?

No, there's no `--sideload-repo` option for the `repair` command, but you can configure sideload directories system-wide for all commands using a symbolic link in `/run/flatpak/sideload-repos`, as documented in the `flatpak` man page.

**Comment by Ricky-Tigg** [comment]
"_See the docs **here** or the create-usb man page._"|  The case covering `flatpak install --sideload`is dully documented in the page of that link, since it is illustrated by a practical guidance. Unfortunately It is not the case regards to the page whose link is located in that quote: "_it’s possible to specify sideload sources (...) without the need for a --sideload-repo option. See **the flatpak man page**._"

In that page –  "_Copyright 2017, 2018_" –  a practical guidance would be welcome in order to at last be able to achieve the goal depicted there.

**Comment by mwleeds** [comment]
`flatpak(1)` says:

>        Flatpak supports installing from sideload repos. These are partial copies of a repository (generated by flatpak create-usb) that are used as
>        installation source when offline (and online as a performance improvement). Such repositories are configured by creating symlinks to the sideload
>        sources in the sideload-repos subdirectory of the installation directory (i.e. typically /var/lib/flatpak/sideload-repos). Additionally symlinks
>        can be created in /run/flatpak/sideload-repos which is a better location for non-persistent sources (as it is cleared on reboot). These symlinks
>        can point to either the directory given to flatpak create-usb which by default writes to the subpath .ostree/repo, or directly to an ostree repo.

So in other words you can use a command such as `ln -s /run/media/yk/4C22-9648/ /run/flatpak/sideload-repos/yk-4C22-9648` to set up sideloading from that mounted drive until the next reboot.

The copy of the man page on docs.flatpak.org is outdated but that is a separate issue.
