### ISSUE TITLE
[SUGGESTION] Add (user-mode) emulation to run Flatpak Apps across CPU architectures.

### ISSUE THREAD

**Issue by gauthamkrishna9991** [flatpak/flatpak#4261]
As we're seeing a new wave of new non-x86_64 devices showing up and becoming popular (`Raspberry Pi 4/400`, `PINE64`, `M1 Apple MacBook`), it would be nice to have `flatpak` run other architecture applications (which are previously unavailable for a specific architecture) **by virtue of emulation**, like what is seen by [Rosetta](https://en.wikipedia.org/wiki/Rosetta_%28software%29) or [Windows on ARM](https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/).

As far as I've used, one can install applications of other architectures, but can only run it if the present architecture allows it (`i686` and `x86_64`), which puts architectures like `aarch64` (64-bit ARM) and `riscv64` (64-bit RISC-V) in obvious disadvantage. But it would be better if those architectures could run it using emulation using, for example, like QEMU user-mode emulation.

## What it is
- It is a user-mode emulation of applications from Flatpak-side which would let applications built for other architectures run almost as if it's running natively.

## What it is NOT
- It is **NOT** emulating a whole operating system (for people who don't know this). A few emulators (especially QEMU) have user-mode emulation of applications, which seem to be very good as far as I've seen till now.
- It doesn't need significantly, as what's needed for full-system emulation, as it seems to work as a wrapper on top of normal system, like how WINE works for Windows Apps.

## Why
- Flatpak is **very** favorably positioned for one to include emulation in it, as all apps are packaged with all it's runtimes, so it seems to potentially be much easier to run over an emulation layer.
- For applications which are proprietary and don't have other architectures, it's easy to run it on other architectures through emulation.
- QEMU user-mode emulation seems to be good enough to get this working (though, I would need to check out whether one would be able to do this, when there are more variables)

## Pros
- It would enable and promote multi-architecture devices and would let the application developers deploy their apps to a wider audience.
- This would give flatpaks a very significant advantage among other application frameworks, if it could run it's cross compiled applications without much modifications on other architectures.
- It would give users at least an option for them to decide whether they could run the app (albeit not natively), rather than it being an obvious no.

## Cons
- More abstraction, potentially a lot more work into getting it to work.
- While emulators like QEMU are *extremely* fast, it's not as fast as native, and also presently because majority of these devices  aren't as fast as the machines they're trying to emulate, there could be significant power/performance regressions.
- There would be no way for an application in the emulation layer to connect to the native system directly, either due to the lack of the emulation layer (which might cause it to not work at all) or though the emulation layer, could be problematic when one is dealing with platform-specific code over it, among other things.

I don't know a lot about flatpak internals other than what has taught me from the brief amount of time I read the [documentation](https://docs.flatpak.org/en/latest/basic-concepts.html), but it would be nice to see something like this, as being a feature on Flatpaks, and that would also help us see more applications distributed more equally among architectures (if possible).

**Comment by gasinvein** [comment]
Doesn't flatpak already support qemu-user-static?

**Comment by gauthamkrishna9991** [comment]
My system shows an error when I try this I guess?

![Screenshot showing failed execution](https://user-images.githubusercontent.com/32835351/117438771-a0cd0500-af4f-11eb-9169-0cc517156409.png)

I'm guessing `qemu-user-static` fixes that?

Can we have have a warning or inform the user to a documentation page which describes this? I didn't know that was a feature Flatpaks had, actually...

**Comment by gasinvein** [comment]
> I'm guessing `qemu-user-static` fixes that?

Yes, installing it should be enough. Works for me:
```
$ uname -m
x86_64
$ flatpak run --command=uname org.gnome.gedit/aarch64/stable -m
aarch64
```

**Comment by gauthamkrishna9991** [comment]
Oh damn, you're right!

I just officially got my mind blown!

You guys are awesome!

**Comment by refi64** [comment]
I'm not sure if this is actually tied to qemu, it might just be some binfmt files installed with QEMU to auto-use it for non-native binaries?

**Comment by gasinvein** [comment]
Well, at least on Fedora, the `qemu-user-static` package comes with a lot of binfmt drop-in configs for different architectures.

**Comment by gauthamkrishna9991** [comment]
> > > I'm guessing `qemu-user-static` fixes that?
> > 
> > Yes, installing it should be enough. Works for me:
> > 
> > ```
> > $ uname -m
> > x86_64
> > $ flatpak run --command=uname org.gnome.gedit/aarch64/stable -m
> > aarch64
> > ```
> 
> When you say installing `qemu-user-static`, are you referring to a Flatpak package, or a distro package (apt, dnf, pacman, etc.)?

Distro Package. It needs to be installed through DNF, for Flatpak to do Emulation. 

Though it was designed to do multiarch testing, it seems to be that it can be used in a way to run apps from other architectures mostly well (had some issues with running x86_64 Spotify on aarch64), I'm sure with some tweaks/modifications to either the app or the platform, you could probably run apps very fairly well.

**Comment by CuriousTommy** [comment]
> Distro Package. It needs to be installed through package manager, for Flatpak to do Emulation.

I want to take a step back and say that we should not be depending on the distro's package in order to do emulation. In my opinion, Flatpak should provide a way for someone to package box86, fex-emu, or qemu-user-static and have it seamlessly integrate with the non-native flatpak (without even needing the creator to modify their non-native flatpak).

**Comment by orowith2os** [comment]
@CuriousTommy I know I'm 3 years late, but I'll comment on this.

You're basically asking Flatpak to vendor a binfmt utility, similar to how it does bwrap. And the integration with non-native arch flatpaks would need some work in app storefronts as well. Expecting flatpak to not rely on the system utilities is not a good idea - flatpak itself isn't a flatpak, after all. 

What you should be doing is asking those emulation utilities to provide binfmt configs and work with storefronts like GNOME Software to seamlessly support non-native-arch Flatpaks.
