### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by dreua** [flatpak/flatpak#4263]
## Linux distribution and version
Fedora Linux 34
## Flatpak version
1.10.2
## Description of the problem
No name resolution possible. Seems to affect all runtimes.
## Steps to reproduce
```
[da@David-UB ~]$ flatpak run --share=network --command=sh org.kde.Platform
Similar installed refs found for ‘org.kde.Platform’:

   1) runtime/org.kde.Platform/x86_64/5.14 (user)
   2) runtime/org.kde.Platform/x86_64/5.15 (user)

Which do you want to use (0 to abort)? [0-2]: 2
[da@David-UB ~]$ dig
sh: dig: command not found
[da@David-UB ~]$ wget 192.168.0.1
--2021-05-07 09:51:13--  http://192.168.0.1/
Connecting to 192.168.0.1:80... connected.
[Edit: IP-address based network access works fine]

[da@David-UB ~]$ wget google.de
--2021-05-07 09:51:18--  http://google.de/
Resolving google.de (google.de)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'google.de'
```

Also: https://github.com/signalapp/Signal-Desktop/issues/5231

**Comment by mwleeds** [comment]
Copying and pasting important info from https://github.com/signalapp/Signal-Desktop/issues/5231 which seems to show this only happens under Flatpak:

> DNS seems to work fine on the host:
> 
> ```
> $ dig textsecure-service.whispersystems.org
> 
> ; <<>> DiG 9.16.11-RedHat-9.16.11-5.fc34 <<>> textsecure-service.whispersystems.org
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47584
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;textsecure-service.whispersystems.org. IN A
> 
> ;; ANSWER SECTION:
> textsecure-service.whispersystems.org. 46 IN A	34.199.170.23
> textsecure-service.whispersystems.org. 46 IN A	52.2.110.252
> textsecure-service.whispersystems.org. 46 IN A	52.6.1.159
> textsecure-service.whispersystems.org. 46 IN A	18.213.186.185
> textsecure-service.whispersystems.org. 46 IN A	3.224.233.47
> textsecure-service.whispersystems.org. 46 IN A	3.220.219.206
> textsecure-service.whispersystems.org. 46 IN A	50.17.184.136
> textsecure-service.whispersystems.org. 46 IN A	34.235.226.106
> 
> ;; Query time: 1 msec
> ;; SERVER: 192.168.0.1#53(192.168.0.1)
> ;; WHEN: Fr Mai 07 09:19:10 CEST 2021
> ;; MSG SIZE  rcvd: 194
> ```
>

**Comment by mwleeds** [comment]
Since this is hard to reproduce it would be hard to debug unless someone can find the conditions under which it's reproducible:
```
0 ✓ mwleeds@localhost ~ (1 key)
↳ flatpak info --show-runtime org.signal.Signal 
org.freedesktop.Platform/x86_64/20.08
0 ✓ mwleeds@localhost ~ (1 key)
↳ flatpak run --share=network --command=sh org.freedesktop.Platform//20.08
sh: __vte_prompt_command: command not found
0 ✓ mwleeds@localhost ~
↳ wget google.de
--2021-05-07 10:14:55--  http://google.de/
Resolving google.de (google.de)... 2607:f8b0:4002:c09::5e, 172.217.164.67
Connecting to google.de (google.de)|2607:f8b0:4002:c09::5e|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.de/ [following]
--2021-05-07 10:14:55--  http://www.google.de/
Resolving www.google.de (www.google.de)... 2607:f8b0:4002:80b::2003, 173.194.219.94
Connecting to www.google.de (www.google.de)|2607:f8b0:4002:80b::2003|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                  [ <=>                                                                          ]  13.35K  --.-KB/s    in 0.01s   

2021-05-07 10:14:55 (1.05 MB/s) - ‘index.html’ saved [13672]
```

**Comment by mwleeds** [comment]
Is the DNS failure temporary? Did you do anything with the host networking like connect to a VPN?

**Comment by dreua** [comment]
It was indeed temporary and now fixed by a reboot. Let's hope it doesn't come back.

**Comment by dreua** [comment]
It happened again. Can we fix this in a way that doesn't involve rebooting every time? Feels like Windows 95 :laughing:
