### ISSUE TITLE
Flatpak can't update aarch64 refs anymore

### ISSUE THREAD

**Issue by guihkx** [flatpak/flatpak#4264]
## Linux distribution and version
Ubuntu 20.04.2 LTS
## Flatpak version
1.11.1 (PPA)
## Description of the problem
I have the `aarch64` SDK installed for cross-compilation purposes, but I can't seem to update them anymore:

```
$ flatpak --user list --columns=name,application,version,ref,origin
Name                        Application ID                                  Version             Ref                                                          Origin
default                     org.freedesktop.Platform.GL.default                                 org.freedesktop.Platform.GL.default/aarch64/20.08            flathub
Freedesktop SDK             org.freedesktop.Sdk                             20.08.8             org.freedesktop.Sdk/aarch64/20.08                            flathub
```
```
$ flatpak update
Looking for updates…
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Sdk/aarch64/20.08 is already installed: No such ref 'runtime/org.freedesktop.Sdk/aarch64/20.08' in remote flathub
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Sdk.Locale/aarch64/20.08 is already installed: No such ref 'runtime/org.freedesktop.Sdk.Locale/aarch64/20.08' in remote flathub
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Platform.GL.default/aarch64/20.08 is already installed: No such ref 'runtime/org.freedesktop.Platform.GL.default/aarch64/20.08' in remote flathub
Nothing to do.
```

If I uninstall the `flatpak` package from PPA (v1.11.1) and install the one provided by Ubuntu (v1.6.5), I'm able to run `flatpak update` just fine.

Also, trying to uninstall the `aarch64` SDK without specifying the architecture doesn't work either (but it works on v1.6.5):

```
$ flatpak uninstall org.freedesktop.Sdk
error: org.freedesktop.Sdk/*unspecified*/*unspecified* not installed
```

## Steps to reproduce
1. `flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
2. `flatpak --user install flathub org.freedesktop.Sdk/aarch64/20.08 -y`
3. `flatpak update`

**Comment by mwleeds** [comment]
Sorry about that. This should be fixed by https://github.com/flatpak/flatpak/pull/4256 (which has not yet been merged or released).
