### ISSUE TITLE
Can't update flatpak

### ISSUE THREAD

**Issue by ALENTL** [flatpak/flatpak#4265]
## Linux distribution and version
21.04 pop-os beta release
## Flatpak version
1.8.5
## Description of the problem
I can't update my flatpak version. I need to update  to the latest version

**Comment by mwleeds** [comment]
If 1.8.5 is the latest available version in Pop!_OS 21.04, you should talk to Pop!_OS and ask them to provide a newer version.

Ubuntu 21.04 has Flatpak 1.10.2 so I'd be surprised if Pop!_OS doesn't.
