### ISSUE TITLE
Remotes missing appstream should not error when updating

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak#427]
This applies to both `flatpak update --appstream` and `gnome-software`. A warning should be sufficient for the cli at least and software probably doesn't need to expose that to the user.

**Comment by alexlarsson** [comment]
This was fixed in commit 224c4ee9e65dd39931cc1eb839040147b0a7da0d no?

**Comment by TingPing** [comment]
Not certain the version but I probably was on 0.6.13 at the time. I also don't have another remote missing it any longer to easily test.
