### ISSUE TITLE
Reopen issue 3542?

### ISSUE THREAD

**Issue by CliffEs** [flatpak/flatpak#4270]
## Description of the problem:
 ~$ `sudo flatpak repair` command fails to prune objects in /var/lib/flatpak/repo/objects 
(folder has 256 folders containing 20,033 items, totaling 1.6 GB, despite my having installed only one flatpak, i.e. FileZilla 3.53.1 in /var/lib/flatpak/runtime, as confirmed by running the command ~$ `flatpak list` * )

## Steps to reproduce:
1. per "final" solution comment found at gitub flatpak issue 3542 (now closed), I ran the terminal command ~$ `sudo flatpak repair`.  According to the thread, this command "prunes" all objects not needed by currently installed flatpaks.
2. However, in my case it did nothing. Aftert a restart /var/lib/flatpak/repo/objects still has 256 folders with 20,033 items.

*Please note that `flatpak list` also shows 3 freedesktop.Platform runtimes in /var/lib/flatpak/runtime that were not installed by me.  Most other Freedesktop files are stored in various subfolders of /usr/ rather than /var/.

Also note that I have been unable to complete one of the freedesktop updates due to lack of space in one of the affected folders. Error msg says update requires 500 MB but that available space is 2.6 MB short of that. (I looked without success for a folder with 497.4 MB total space available.) Nevertheless it seems doubtful that all 20,033 object items are needed.
----------
The user in issue 3542 reported that the command worked for him, but I want to suggest adding a footnote/disclaimer to the effect noted herein. 

Finally, it would be lovely if someone can provide a more reliable solution for cleaning out repo/objects.

**Comment by mwleeds** [comment]
It's not clear there's a bug here. If `flatpak repair` didn't prune any objects the default hypothesis should be that no objects were unneeded. Despite that you only installed FileZilla, that app needs a runtime (as you noted `org.freedesktop.Platform` was automatically installed) so one would not expect a small number of files.

For what it's worth this command:
```
tree `flatpak info -l org.freedesktop.Platform//20.08`/files
```
outputs "1005 directories, 14216 files" on my machine.

If it is the case that `flatpak repair` is not pruning properly, that bug would probably need to be reproduced on a newer version of Flatpak to be worth looking into.

**Comment by CliffEs** [comment]
Thanks for the attention you've given to my issue. FWIW, I finally gave up
fighting the /var space shortage problem and simply reinstalled my OS
properly.
That restored full access to my 320 GB HDD, so repo objects can now hog as
much space as they want.

All the best,
Cliff Esler

*Although the nature of mind is called "clear light," its every ascription
is baseless verbal fiction.  *- Tilopa (988-1069 CE)
