### ISSUE TITLE
Firefox v88.0 Drag and Drop

### ISSUE THREAD

**Issue by bugaro** [flatpak/flatpak#4274]
## Linux distribution and version
ArcoLinux 5.10.33-1lts
WM: bspwm
## Flatpak version
1.10.2
## Description of the problem
firefox browser v88.0 drag and drop file not working
## Steps to reproduce
1. Open https://css-tricks.com/examples/DragAndDropFileUploading/?submit-on-demand
2. Drag some file to upload area
Expected result: You must see file name in upload area
Actual result: Nothing changed

**Comment by refi64** [comment]
I believe this is a Firefox-specific issue, the drag and drop appears to work just fine with Flatpak Chrome.

**Comment by mwleeds** [comment]
If this is reproducible on recent versions of Firefox, I'd recommend opening a bug report on Firefox.

**Comment by da-anda** [comment]
I also can't drag any file into the recent flatpack version of firefox (on Fedora 39). It works fine on native install. Any suggestion what I could try to fix it? I'm not a Linux expert (just about to migrate from Win to Linux, so new to the game)
