### ISSUE TITLE
Glitched context menues in chromium based apps

### ISSUE THREAD

**Issue by Vendicated** [flatpak/flatpak#4276]
## Linux distribution and version
Arch Linux 5.12.3-1-ck-zen

## Flatpak version
Flatpak 1.10.2

## Description of the problem
(right click) Context menues are glitched in chromium/electron based apps. Examples of this are com.discordapp.Discord, im.riot.Riot, com.spotify.Client and com.github.Eloston.UngoogledChromium, all from flathub. The issue does not occur in their non flatpak equivalents, so for example https://aur.archlinux.org/packages/spotify/

Looks like [this is also an issue with Snaps](https://bbs.archlinux.org/viewtopic.php?id=266350) 🤔 

Screenshots:
![image](https://user-images.githubusercontent.com/45497981/118210313-a902d400-b46a-11eb-8d27-3485239cfe19.png)

![image](https://user-images.githubusercontent.com/45497981/118210539-cc2d8380-b46a-11eb-8ce8-90b3a6e89788.png)

## Steps to reproduce
Install any of the above mentioned apps and open the context menu

**Comment by salva09** [comment]
Hey, I have the same problem using Arch Linux with kernel 5.10.36-1-lts, flatpak 1.11.1. On both Gnome and Plasma

**Comment by nhubaotruong** [comment]
It's a mesa problem. I downgraded `mesa` and `lib32-mesa` (arch linux btw) and the problem is gone

**Comment by Vendicated** [comment]
Yep, downgrading fixed it too for me. But that makes me wonder, why does it work as expected in the "native" apps but is broken only in flatpaks?

**Comment by lionirdeadman** [comment]
I believe this might've been a bug fixed in mesa 21.1.1, this version has been pushed to flathub.

`flatpak update` and report. o/

**Comment by nhubaotruong** [comment]
After update from flathub, the problem is gone

**Comment by Vendicated** [comment]
Yep its fixed now
