### ISSUE TITLE
suggestion: Block flatpak portals (Open URI)

### ISSUE THREAD

**Issue by Schokokex** [flatpak/flatpak#4278]
## Linux distribution and version
debian 11 bullseye 5.10.0-6-amd64
## Description of the problem
I like to put every app into a separate profile by setting HOME=~/.home/appname before launching.
That way i can have different setups for the same app.
I found out that Discord starts Firefox in the standard Home directory, which starts firefox without an adblocker and so on :(
calling browser apps (through portal) appearantly doesnt preserve environment variables.
## Steps to reproduce
```
export HOME=/home/jj/.home/myapp
flatpak install -y firefox discord
flatpak run com.discordapp.Discord
```
-> A /home/jj/.var directory is created for firefox ignoring export HOME

**Comment by mwleeds** [comment]
I don't see how your issue title "Block flatpak portals (Open URI)" makes sense. Certainly Flatpak doesn't want to block its own portals from being used. It sounds like what you want is a way to set an environment variable for an application no matter how it's started. Have you tried using `flatpak override --env...` for that?
