### ISSUE TITLE
Hyphens in usernames

### ISSUE THREAD

**Issue by hanaral** [flatpak/flatpak#4284]
## Linux distribution and version
elementary OS 6 Early Access
## Flatpak version
`Flatpak 1.10.2`
## Description of the problem
Despite git providers such as GitHub allowing hyphens in usernams, flatpak-builder is not at all able to compile apps that have hyphens in the username part of said apps' reverse DNS name. This is causing issues with platforms that are in the process of switching to a GitHub + flatpak distribution method such as elementary AppCenter, since there are developers that have hyphens in their usernames ([such as with this developer, who isn't able to prepare their apps](https://github.com/dr-Styki/ScreenRec/issues/34#issuecomment-844848752))

@alexlarsson Apologies for tagging you directly, but there was previously an issue that was resolved for adding hyphens to the names of apps themselves in the reverse DNS - could this possibly get the same treatment?
## Steps to reproduce
Attempt to build an app by a developer with a hyphen in their username

**Comment by smcv** [comment]
Flatpak follows the AppStream and Desktop Entry specifications, which have a recommendation for this: replace the hyphen with an underscore. This also avoids syntax issues with name components that have leading digits.

> Well-known names containing the dash are allowed but not recommended, because the dash is not allowed in some related uses of reversed DNS names, such as D-Bus object paths and interface names, and Flatpak app IDs. If the author's domain name contains a dash, replacing it with an underscore is recommended: this cannot cause ambiguity, because underscores are not allowed in DNS domain names.
>
> If the author's domain name contains a label starting with a digit, (which is not allowed in D-Bus well-known names), prepending an underscore to that element of the desktop entry name is recommended. For example, 7-zip.org might release an application named org._7_zip.Archiver. 
> — https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#file-naming

> To ensures the greatest possible compatibility of an AppStream ID, it is recommended to replace any hyphens in the ID with underscores, and prefix every leading digit of a section with an underscore as well. Since the underscore is not a valid character in domain names, the uniqueness of the ID is kept. For example, the ID org.7-zip.7zip could become org._7_zip._7zip. 
> — https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent

This cannot create collisions with other Github users' apps, because underscores are not allowed in Github usernames (as a result of them not being allowed in DNS names).

If elementary doesn't allow this, then please raise that with elementary.
