### ISSUE TITLE
[Usability] The gnome repo with the designated stable default runtimes should always be available per default

### ISSUE THREAD

**Issue by JonasT** [flatpak/flatpak#430]
The gnome repo with the designated stable default runtimes should always be available per default. I don't know if this caused by the distribution packagers including flatpack or how flatpack itself is provided with its default config for packaging, hence I am also filing a ticket here.

The runtimes at http://flatpak.org/runtimes.html makes it very clear that those are the very standard runtimes that are supposed to be used by a lot of developers, and adding them with ```flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo``` is not something the average user can easily know, even from reading the usage page ```flatpak --help```. Also, what is the point if pretty much everyone trying to use flatpak for a larger amount of applications will need to do this anyway?

Therefore, flatpak should really be configured in a way so that the stable runtimes are always available for use.

The corresponding fedora bug (in case this is a problem of how it is packaged by fedora specifically) is here: https://bugzilla.redhat.com/show_bug.cgi?id=1401215

---
And if you don't want to install/provide the GNOME-specific ones per default, at least make sure the org.freedesktop ones are available to have *something* a flatpak can rely on if the developer wants to ship it in a way that makes it run everywhere with minimum effort for the end user.

**Comment by alexlarsson** [comment]
git master now allows a .flatpakref to point to a repo for runtimes which is automatically installed, so this should no longer be needed.
