### ISSUE TITLE
Sandbox issue: Cant access my apps nor my files

### ISSUE THREAD

**Issue by danrobi11** [flatpak/flatpak#4301]
I thought one of the reason for flatpaks was about being user-friendly. Its obviously not!

Im a non-technical user and I have so much issue with the sandbox

The flatpak sandbox breaks apps. Im using flatseal and I still cant manage to access all my apps and files :(

Even tho I've spend times reading some documentations, I cant figure it out.

Im running emacs and emacs is broken af. 
When I `cd` I cant see usr/local/bin from any terminals in emacs
dmenu doesnt see any of my apps.
Consult-find mostly doesnt find anything!

So many thing that doesnt work because of the flatpak sandbox, Its a total shit show!

Need more obvious user-friendly info on how to make flatpaks properly works!

Sorry for the rant but im so fedup with this :( 

I wonder whats the point with this sandbox thingy if its going to break the apps ?

Emacs at this point is almost useless.

Any way to completely disable the sandbox ?

Heres all the stuff I tried in flastseal

![flatseal settings1](https://user-images.githubusercontent.com/48020114/120530135-2e630f80-c3ab-11eb-93ab-a875701b7c10.png)
![flatseal settings2](https://user-images.githubusercontent.com/48020114/120530146-31f69680-c3ab-11eb-9acf-6183831551b1.png)
![flatseal settings3](https://user-images.githubusercontent.com/48020114/120530167-3753e100-c3ab-11eb-8a25-2cfdb7268418.png)

**Comment by SISheogorath** [comment]
> Any way to completely disable the sandbox ?

To make the answer short: No.

Flatpaks are intentionally sandboxed and should only be used for apps that are supposed to be sandboxed. Interaction to other application should take place through portals and (dbus-)APIs, not through app A calling binary B that hopefully application C put there at some point in time.

If you want unsandboxed applications, then these are system application. System applications are not managed by Flatpak.

**Comment by danrobi11** [comment]
> To make the answer short: No

@SISheogorath Ya you're right. I do not use flatpak anymore. That's the best fix!
