### ISSUE TITLE
[asla-plugins plughw] Impossible to record audio with Bitwig Studio using ALSA

### ISSUE THREAD

**Issue by abique** [flatpak/flatpak#4304]
## Linux distribution and version
Archlinux, up to date

## Flatpak version
Flatpak 1.11.1

## Description of the problem
It seems that flatpak does not give direct access to ALSA. There is something in between I suppose.
The result is that I can't record my audio interface inputs; while if I start bitwig but without flatpak, I can record from ALSA.

## Steps to reproduce
- install com.bitwig.BitwigStudio
- configure the audio interface using ALSA
- try to record audio from your audio interface

![image](https://user-images.githubusercontent.com/31200/120648746-4787c100-c47c-11eb-9b40-41d7d0339299.png)

**Comment by abique** [comment]
We open `plughw:0,0` and that could be the problem.

**Comment by abique** [comment]
I'm pretty sure that `plughw:0,0` does not work and this should be fixed by the flatpak runtime.
Bitwig asks for a float sample format and it gets int32 instead, which never happened on archlinux or ubuntu.

**Comment by GeorgesStavracas** [comment]
Looking at FreeDesktop 20.08, it looks like [alsa-lib is indeed built with the `plug` pcm plugin enabled](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/elements/components/alsa-lib.bst). So in theory it should be there

**Comment by abique** [comment]
> Looking at FreeDesktop 20.08, it looks like [alsa-lib is indeed built with the `plug` pcm plugin enabled](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/elements/components/alsa-lib.bst). So in theory it should be there

We'd need to check the build logs. And run the test suite if there is one.

**Comment by GeorgesStavracas** [comment]
Given that the plugin is there, but behaves differently between host and Flatpak, it would be helpful if you could provide:

 * The alsa-libs version on your host system
 * `strace`s of host and Flatpak

I advise you also ask on #alsa at FreeNode

**Comment by abique** [comment]
Maybe this one is missing plughw?
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/elements/components/alsa-lib.bst

**Comment by GeorgesStavracas** [comment]
It's not, the plugin is called `plug` and is listed there. But I think one possibility is that the `lfloat` plugin is necessary for float sample formats.

**Comment by abique** [comment]
Archlinux don't pass options at all: https://github.com/archlinux/svntogit-packages/blob/packages/alsa-lib/trunk/PKGBUILD
Why not do the same?

**Comment by GeorgesStavracas** [comment]
You'll have to raise this question to freedesktop-sdk. In fact, seems like this bug should be filed against freedesktop-sdk.

**Comment by abique** [comment]
@valentindavid from git blame you were the latest one to change the set of plugs

**Comment by abique** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/5092

**Comment by hfiguiere** [comment]
This will break ABI afaik, so it might require 21.08.

**Comment by refi64** [comment]
This should be fixed in runtime 21.08 afaik, which will be released in the near future.
