### ISSUE TITLE
Uninstall with URL that has port results in error: Invalid branch 127.0.0.1:8000: Branch can't contain :

### ISSUE THREAD

**Issue by felixfontein** [flatpak/flatpak#4307]
## Linux distribution and version
Multiple systems: Arch Linux (latest), Fedora 31 to 34, and Ubuntu 16.04, 18.04 and 20.04. On every system, using the latest flatpak system provided by system packages.

## Flatpak version
1.11.1-2 (on Arch Linux)

## Description of the problem
Running `flatpak uninstall --user --noninteractive http://127.0.0.1:8000/repo/com.dummy.App1.flatpakref` results in `error: Invalid branch 127.0.0.1:8000: Branch can't contain :`.

## Steps to reproduce
Run `flatpak uninstall --user --noninteractive http://127.0.0.1:8000/repo/com.dummy.App1.flatpakref` (no HTTP server needed, it will already fail before trying to contact the server)

**Comment by felixfontein** [comment]
Note: this doesn't happen when installing. Installation with such URLs just works fine.

**Comment by refi64** [comment]
`flatpak install` doesn't take URLs, you need to pass the Flatpak ID itself.
