### ISSUE TITLE
third-party non-flatpak applications can add non-privileged code in non-system directories and get flatpak run it anytime

### ISSUE THREAD

**Issue by illwieckz** [flatpak/flatpak#4315]
## Linux distribution and version

```sh
$ lsb_release -d
Description:	Ubuntu 20.04.2 LTS
```

## Flatpak version

```sh
$ flatpak --version
Flatpak 1.6.5
```

## Description of the problem

When I try to run some flat pak, I get this error:

```sh
$ flatpak run com.play0ad.zeroad
/usr/bin/env: ‘bash’: No such file or directory
error: ldconfig failed, exit status 32512
```

```sh
$ flatpak run net.unvanquished.Unvanquished
/usr/bin/env: ‘bash’: No such file or directory
error: ldconfig failed, exit status 32512
```

I first got the issue on 0 A.D. flatpak: https://github.com/flathub/com.play0ad.zeroad/issues/18

So at first I thought it was pecific to 0 A.D.

But now I get it as well with Unvanquished flatpak: https://github.com/flathub/net.unvanquished.Unvanquished/

And I this one works on my another computer (laptop) running the same distribution… So it looks like the problem is on flatpak side and happens with some configuration that may differ between both computers. The difference is yet to be determined.

## Steps to reproduce

I don't know how to reproduce it outside of _this_ computer. On my laptop also running Ubuntu 20.04 I have no problem.

So I'm looking for help on how to debug the problem, especially get more verbose logs… because this does not look helpful enough:

```sh
$ flatpak run --verbose com.play0ad.zeroad
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/illwieckz/.var/app/com.play0ad.zeroad/.ld.so/6049eb049a44eeea969d0f8c31deae8551de1ba0b423254b0dca802ecf958c14
F: Running: 'bwrap --args 13 ldconfig -X -C /run/ld-so-cache-dir/6049eb049a44eeea969d0f8c31deae8551de1ba0b423254b0dca802ecf958c14'
/usr/bin/env: ‘bash’: No such file or directory
error: ldconfig failed, exit status 32512
```

```sh
$ flatpak run --verbose net.unvanquished.Unvanquished
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/illwieckz/.var/app/net.unvanquished.Unvanquished/.ld.so/0c8bb886e18be212f6f53845e93902099ae98daa2f9551f3bc0b84eee6e661ed
F: Running: 'bwrap --args 13 ldconfig -X -C /run/ld-so-cache-dir/0c8bb886e18be212f6f53845e93902099ae98daa2f9551f3bc0b84eee6e661ed'
/usr/bin/env: ‘bash’: No such file or directory
error: ldconfig failed, exit status 32512
```

Doing this fixes nothing:

```sh
sudo flatpak repair --system --reinstall-all
```

**Comment by illwieckz** [comment]
Hmm, and now I just thought about it…

I use a `bwrap` wrapper that can be found there: https://github.com/NicolasBernaerts/ubuntu-scripts/blob/master/nautilus/bwrap

It is stored as `/usr/local/bin/bwrap` and is a wrapper around `/usr/bin/bwrap`. I use it to fix many shortcoming of bwrap. I totally forgot about it.

This wrapper being a bash script, it probably fails to find bash the way flatpak runs it, if flatpak does not provide bash.

Renaming the custom wrapper to not take precedence in path fix the named flatpak… but then all the bwrap issues (outside of flatpak) are back again…

That said, flatpak probably wants to rely on system's bwrap (`/usr/bin/bwrap`).

I just verified that adding a custom script named `bwrap` in my path (even in my home directory) makes this fake `bwrap` being run by flatpak.

So, it means every non-flatpak software that can write in `${HOME}` can inject man-in-the-middle code to any `flatpak run` operation by doing a custom `bwrap` binary, storing it in `${HOME}` and adding it to `${PATH}` by editing some `.bashrc` or similar files.

For example I added this `bwrap` fake tool to my `${PATH}`:

```sh
#! /bin/sh
echo HOHO
```

```sh
$ flatpak run --verbose net.unvanquished.Unvanquished
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/illwieckz/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 3113369734
F: Allocated instance id 224927693
F: Add defaults in dir /net/unvanquished/Unvanquished/
F: Add locks in dir /net/unvanquished/Unvanquished/
F: Allowing dri access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/illwieckz/.config/pulse/client.conf': Error opening file /home/illwieckz/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 28 xdg-dbus-proxy --args=32'
DEFEATED
```

**Comment by smcv** [comment]
If your assumption is that third-party code is run without a sandbox and can edit your `~/.bashrc`, then you have already completely trusted the third-party code. If it wants to run a malicious "payload", there's no need for it to use Flatpak to achieve that: it can just put the "payload" in your `~/.bashrc`, and bash will execute it during login.

**Comment by illwieckz** [comment]
> If your assumption is that third-party code is run without a sandbox and can edit your ~/.bashrc, then you have already completely trusted the third-party code.

Yes but should flatpak trust it as well? Should flatpak developpers/flatpak packagers trust it as well?

For example the `/lib64/ld-linux-x86-64.so.2` helper is not in `${PATH}`. Maybe `bwrap` is that kind of helerr for which the path should be enforced?

Isn't part of flatpak purpose to reduce incompatibilities from the various differences coming from the environment? Maybe “desktop isolation” words can also mean « isolating from the desktop » ?

**Comment by refi64** [comment]
Any application that has $HOME access already has a high degree of control, and realistically there is nothing Flatpak could do in this case that couldn't be trivially bypassed (being able to set`LD_PRELOAD` in particular is a rather large "hammer" of sorts). In addition, Flatpak intentionally lets you use a different bwrap for testing via the `FLATPAK_BWRAP` environment variable.

As for the original issue, you could probably just edit your custom bwrap to hardcode the full path to bash.

**Comment by illwieckz** [comment]
> Flatpak intentionally lets you use a different bwrap for testing via the `FLATPAK_BWRAP` environment variable.

Oh, that is a good argument in favor of implementing the proposed solution, which is hardcoding the path to the system `bwrap` since this `FLATPAK_BWRAP` environment variable successfully removes the need to rely on `PATH` to test custom `bwrap`. This variable is the perfect answer to give to people wanting to test custom bwrap for flatpak after having solved this issue and seems to already exist so nothing seems to prevent the implementation of the proposed solution anymore.

The present issue, which is not solved, is about flatpak using custom bwrap that is not provided by `FLATPAK_BWRAP` and that is not provided to fix any flatpak issue or test any flatpak behaviour. I renamed the issue accordingly, thanks for helping me pointing out the best way to express the issue..

The proposed solution is similar to what already do scripts and binaries: they already hard code the path to their initial loader, being `/lib64/ld-linux-x86-64.so.2` or `/usr/bin/env` for example, such path not being modifiable with `$HOME` access. The solution is not about fixing a security problem but a reliability problem anyway. Even a developer who have full control on his system and may want to be able to fully customize parts of the loading (like by using `FLATPAK_BWRAP`) may still want to get stock flatpak running the way upstream want it to run when _not_ using any specific `FLATPAK` environment variable.

> As for the original issue, you could probably just edit your custom bwrap to hardcode the full path to bash.

That would not be a flatpak solution, one could even set `FLATPAK_BWRAP` to the system one, which is the contrary of the purpose of such variable if I get it right. Such custom bwrap as the one quoted in the issue has no purpose in fixing any flatpak issue, so flatpak does not need any of such custom bwrap. And as you said, it already exists `FLATPAK_BWRAP` for those who want to test flatpak with custom bwrap, meaning there is no need to support custom bwrap outside of one being provided by `FLATPAK_BWRAP`.

So, to re-express the issue : the issue is about flatpak using custom bwrap that is not provided by `FLATPAK_BWRAP` and that is not provided to fix any flatpak behaviour. Thanks to existence of `FLATPAK_BWRAP` environment variable it is possible to flatpak to implement a solution similar to what other binary loaders do with `/lib64/ld-linux-x86-64.so.2` or `/usr/bin/env` and then make flatpak reliable for both flatpak users and flatpak developers. This would also make flatpak reliable for bwrap developers or modders on the process.
