### ISSUE TITLE
Flatpak application fails to delete directories to "Trash"

### ISSUE THREAD

**Issue by joshas** [flatpak/flatpak#4317]
## Linux distribution and version
Fedora 34

## Flatpak version
Flatpak 1.10.2

## Description of the problem
While working on my first PR for application update on Flathub [1] I ran into strange issue, where application fails to delete directories, if setting to use "Recycle bin" is enabled. File deletion works correctly, they end up in Trash, but trying to delete directory operation silently fails.

## Steps to reproduce
I've tried debugging package with "command=sh" and running gio trash directory_name inside package gives following error message:
gio: file:///home/user/projects/com.xnview.XnViewMP/directory_name: Trash portal failed on /home/user/projects/com.xnview.XnViewMP/directory_name
File deletion with this command works correctly.
I'm using org.freedesktop.Platform//20.08 on Fedora 34. Same issue was observed on GNOME and KDE platforms.

[1] https://github.com/flathub/com.xnview.XnViewMP/pull/8/files

**Comment by refi64** [comment]
This is due to: https://github.com/flatpak/xdg-desktop-portal/issues/518
