### ISSUE TITLE
Manually copy a flatpak installation with apps to a new device (Because a commit we needed was removed from flatpak)

### ISSUE THREAD

**Issue by OnTheLink** [flatpak/flatpak#4325]
## Linux distribution and version
ChromeOS Linux Container - Latest version available for the Chromebook 3180 (KEFKA)
## Flatpak version
No access to a Chromebook to check the version number right now
## Description of the problem
I would like to know if it was possible to copy all of flatpak and it's installed apps to another machine manually and what I would need to transfer the files (File orders, configurations, desktop icons) without having to actually install it onto the new system using apt and the flatpak install commands.

(We need this because of one of the commits that was removed lately and we need that specific update on more machines, it's about the qgis software, using this commit: f3e180bb9ddc0cc9fc304e899b7c71405d10db81a8200f3d34dfb6288fec15b9)

## Steps to reproduce
To get the error message:
Install Flatpak
Install gnome-software-plugin-flatpak
Setup the main config
Install org.qgis.qgis using `flatpak -y --user install qgis.flatpakref`
Attempting to install the commit over the installed version using:
`flatpak -y --user update --commit=f3e180bb9ddc0cc9fc304e899b7c71405d10db81a8200f3d34dfb6288fec15b9 org.qgis.qgis`
Oh and this is was required to make the commit work before it went down:
`flatpak -y --user install runtime/org.kde.Platform/x86_64/5.12`

Thanks in advance,

Greetings,
Misha Opstal

**Comment by mwleeds** [comment]
Flatpak has support for copying apps and their dependencies across machines (see [here](https://docs.flatpak.org/en/latest/usb-drives.html)) and it sounds like that's what you're looking for. Copying an app's configuration data is not really a supported use case 
 since that is generally machine-specific but it can be found in subdirectories of `~/.var/app/`.
