### ISSUE TITLE
Broken flatpak installation after cancelling an installation

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#4330]
## Linux distribution and version
Fedora 33
## Flatpak version
Flatpak 1.10.2
## Description of the problem
While installing `org.gimp.GIMP.Debug` (`org.gimp.GIMP//stable` was already installed and up-to-date), I had to cancel the installation with ctrl-c because the install was stuck after connectivity loss.
I assumed I could just cancel, that flatpak would catch the ctrl-c and leave a clean state as do other installation tools, and that I could retry when I had better internet connection.

Unfortunately since then, trying to install the debug package again always fails with:

```
$ flatpak install --user flathub org.gimp.GIMP.Debug
Looking for matches…


        ID                           Branch          Op         Remote          Download
 1. [✗] org.gimp.GIMP.Debug          stable          i          flathub         1.0 kB / 955.5 MB

Error: While trying to checkout 799ca7428102d7c76b31da31ea3e7a33b2136289841e3e4fe42f57dcbfa28bdf into /home/jehan/.local/share/flatpak/runtime/org.gimp.GIMP.Debug/x86_64/stable/.799ca7428102d7c76b31da31ea3e7a33b2136289841e3e4fe42f57dcbfa28bdf-YJ4N50: Opening content object c772fd599157df015fae01c05b4ca1f874b1bba8ff112e2dcfddffcf868d8ed7: Couldn't find file object 'c772fd599157df015fae01c05b4ca1f874b1bba8ff112e2dcfddffcf868d8ed7'
error: Failed to install org.gimp.GIMP.Debug: While trying to checkout 799ca7428102d7c76b31da31ea3e7a33b2136289841e3e4fe42f57dcbfa28bdf into /home/jehan/.local/share/flatpak/runtime/org.gimp.GIMP.Debug/x86_64/stable/.799ca7428102d7c76b31da31ea3e7a33b2136289841e3e4fe42f57dcbfa28bdf-YJ4N50: Opening content object c772fd599157df015fae01c05b4ca1f874b1bba8ff112e2dcfddffcf868d8ed7: Couldn't find file object 'c772fd599157df015fae01c05b4ca1f874b1bba8ff112e2dcfddffcf868d8ed7'
```

I tried `flatpak repair`, it does a bunch of stuff, no error. But every time I retry the installation of the debug package, the same failure happens. A `flatpak update` also updates everything, no error, but no improvement on the install.

A `flatpak uninstall` now also fails with assertion:

```
$ flatpak uninstall --user org.gimp.GIMP//stable
**
flatpak:ERROR:common/flatpak-transaction.c:2971:mark_op_resolved: assertion failed: (commit != NULL)
Bail out! flatpak:ERROR:common/flatpak-transaction.c:2971:mark_op_resolved: assertion failed: (commit != NULL)
Aborted (core dumped)
```

For the record, `org.gimp.GIMP.Debug` is not listed by a `flatpak list`.

## Steps to reproduce

1. Run `flatpak install --user flathub org.gimp.GIMP.Debug`
2. Cancel at some point with ctrl-c (in my case, because the installation was stuck for a long time because of lack of connectivity).
3. Try again the first install command.

I would assume these steps don't reproduce the issue all the time and that I must have cancelled the install at a very wrong time which left my flatpak environment in a very bad state.

Short term, I would appreciate if I could get some info on how to get back a working flatpak environment.

Long term, it would be nice if flatpak could catch such interruption (ctrl-c sends SIGINT if not mistaken), and make sure to always leave its environment in the same condition it was before.

Thanks!

**Comment by guihkx** [comment]
I think that because you've installed the Debug package as an user, I believe you should pass `--user` to the `repair` command, i.e.

```
flatpak --user repair
```

**Comment by Jehan** [comment]
@guihkx Hmmm… I was going to say that obviously, I did run the call with `--user`, but I tried just now to be sure, and it works. So either I did indeed forget the `--user` flag, or `flatpak` got updated in-between when I reported the issue and now, and a fix got in. Anyway it works now. Let's close. Thanks. 🤷
