### ISSUE TITLE
Flatpak history not really working

### ISSUE THREAD

**Issue by mrckndt** [flatpak/flatpak#4332]
## Linux distribution and version
Fedora Silverblue 34

## Flatpak version
1.10.2

## Description of the problem
Commands like `flatpak history --columns=all` or `flatpak history --columns=time,application` are returning "error: is not application or runtime" or "error: appstream2/x86_64 is not application or runtime" (two different machines, exact same setup). `flatpak history --columns=time,installation` works somewhat but also return lines like 

```
Jun 25 17:59:25 system
Jun 25 17:59:26 system
```
which should not happen according to the manpage 

> This will be either the ID of a Flatpak installation, or the path to a temporary OSTree repository.

## Steps to reproduce
While using flatpak history use different column field combinations.

**Comment by ajgringo619** [comment]
Also happening with v1.11.2 (via PPA)

**Comment by hackel** [comment]
Dupe #4121

**Comment by JaneSmith** [comment]
Same issue here... Just came to report this.

I'm running Fedora Silverblue 34.20210724.0 with Flatpak 1.10.2-4.

**Comment by repsorp** [comment]
$ flatpak history -vv
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/test/.local/share/flatpak
error: appstream2/x86_64 is not application or runtime

Ubuntu 21.04

**Comment by mwleeds** [comment]
Fix available in #4526

**Comment by bdaase** [comment]
Could the fix please be backported to all affected stable branches?

**Comment by mwleeds** [comment]
> Could the fix please be backported to all affected stable branches?

Sure, https://github.com/flatpak/flatpak/pull/4729 and https://github.com/flatpak/flatpak/pull/4635
