### ISSUE TITLE
cannot install apps as user

### ISSUE THREAD

**Issue by christianrauch** [flatpak/flatpak#4336]
## Linux distribution and version
Ubuntu 20.04 with the Flatpak PPA
## Flatpak version
Flatpak 1.11.2
## Description of the problem
I am not able to install as user (`--user`).
## Steps to reproduce
1. enable flathub:
```
$ flatpak remote-list
Name          Optionen
flathub       system
```
2. install an app as user:
```
$ flatpak install flathub org.gnome.Fractal --user
Looking for matches…
Fehler: No remote refs found similar to ‘flathub’
```

**Comment by ajgringo619** [comment]
That's because the user repo has not been added. Run this in the terminal:
`flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo`
You should be good to go now.

**Comment by christianrauch** [comment]
Is this a bug or a feature? Why can't I install as a user from a system repo? It makes no sense to me that I have to add the same repo twice for this.

**Comment by ajgringo619** [comment]
Can't tell you why it's necessary; probably need to wait for one of the devs to explain.

**Comment by refi64** [comment]
IIRC it was because then it would be possible to remove the repo from the system but leave anything that depends on it still in the user installation. The only "solution" would be to keep track of all dependent users from within the system repo, which would be a mess.

**Comment by christianrauch** [comment]
> IIRC it was because then it would be possible to remove the repo from the system but leave anything that depends on it still in the user installation.

I don't understand the issue. Removing the repo should only mean that I won't be able to update the packages anymore. With any common Linux distribution, removing the repos (or something like a ppa) will still leave the software installed. Not sure what the benefit would be if this wasn't the case.

I am curious what the technical limitations are that make this necessary.

**Comment by flrnd** [comment]
It's a bug, console output when I try to pass the --user flag

```
flatpak --user install org.chromium.Chromium
Looking for matches…
error: No remote refs found for ‘org.chromium.Chromium’
```
This is on openSUSE tumbleweed btw.

**Comment by hfiguiere** [comment]
> It's a bug, console output when I try to pass the --user flag

You command line is different that the OP.

But if you haven't set a remote for `--user` then it's expected it can't find a remote for the package.

I believe an answer was given.
