### ISSUE TITLE
How can I uninstall this?

### ISSUE THREAD

**Issue by edoantonioco** [flatpak/flatpak#434]
Hello. Im trying to uninstall monodevelop, but flatpak doesnt detect it.

> ~]$ flatpak list
com.xamarin.MonoDevelop
~]$ flatpak uninstall com.xamarin.MonoDevelop
error: com.xamarin.MonoDevelop master not installed

What am I supposed to do? Just to take in mind than I didnt obtained that monodevelop package from a repository, I downloaded the flatpack file and installed it locally.

This on manjaro.

**Comment by alexlarsson** [comment]
Did you install it system-wide or with --user. If the later you need to specify --user when uninstalling.
Its a bit confusing that flatpak list shows both the user and system apps...

**Comment by edoantonioco** [comment]
"flatpak uninstall --user com.xamarin.MonoDevelop" did the trick. Solved.

**Comment by grompes** [comment]
@alexlarsson Большое спасибо
