### ISSUE TITLE
Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by nexcode** [flatpak/flatpak#4345]
## Linux distribution and version
CentOS 8
## Flatpak version
Flatpak 1.8.5
## Description of the problem
If run it from root then everything works:
```
flatpak run org.chromium.Chromium
```
But if make a new user:
```
groupadd testuser
useradd -g testuser -d /opt/testuser testuser
```
And now we will start from a new user:
```
flatpak run org.chromium.Chromium
Cannot autolaunch D-Bus without X11 $DISPLAY
(zenity:8): Gtk-WARNING **: 17:13:28.767: cannot open display: 
```

**Comment by smcv** [comment]
> start from a new user

What does this mean, exactly?

To use programs that require D-Bus (including Chromium) you need a D-Bus session bus. Getting a D-Bus session bus is outside Flatpak's scope. Generally, a high-quality Linux distribution will ensure that if you log in to a GUI session, you get a D-Bus session bus for that user. Depending on the distribution, logins via ssh or a virtual console might also have a D-Bus session bus.

If you are logged in as one user (such as root) and you use tools like `su` or `runuser` or `sudo` to switch to another user (such as testuser), you will generally *not* have a D-Bus session bus.

If you use tools like `su` or `runuser` or `sudo` you will generally also be unable to access the X11 DISPLAY of the user you switched from. This is a good thing! If `testuser` could access `root`'s X11 DISPLAY, then they could inject input into `root` applications, take screenshots, and so on.

**Comment by nexcode** [comment]
Yes, I use the `su - testuser` call to repeat it.

But the task is to solve the same error that appears when running as a **systemd** service:
```
[Service]
User=testuser
Group= testuser
WorkingDirectory=/opt/testuser
ExecStart=/usr/bin/node --enable-source-maps build/index.js
```
And script (build/index.js) tries to run chromium for tests...

**Comment by smcv** [comment]
This is nothing to do with Flatpak.

If you want to run programs in a systemd system service that behave as though they are a tiny login session for D-Bus purposes, you should probably either use `dbus-run-session(1)`, or if your OS includes `/usr/lib/systemd/user/dbus.socket`, register the systemd service as a login session by setting its `PAMName=` to a PAM stack (see `/etc/pam.d` or similar) that includes `libpam_systemd`.

**Comment by nexcode** [comment]
But if run the browser from the rpm package, then everything works, so I assumed that this is flatpak requirement.
