### ISSUE TITLE
Filesystem overrides on --user apps

### ISSUE THREAD

**Issue by ralphocdol** [flatpak/flatpak#4354]
## Linux distribution and version
Manjaro 21.1.0 (Pahvo)
KDE Plasma 5.22.4
## Flatpak version
1.11.2
## Description of the problem
I have a script that automatically creates symbolic links of my GTK theme of choice to each config of all my flatpak applications, and have my overrides set to `--filesystem=~/.themes:ro`. All flatpak applications installed as `--system` has access to my **overrides** but my `--user` apps does **not**, I have to manually set each application which defeats the purpose of using **overrides**.
## Things I've tried but to no avail
`sudo flatpak override --user --filesystem=~/.themes:ro`
## Steps to reproduce
1. `sudo flatpak override --filesystem=~/.themes:ro` --> to have access to the installed GTK themes
2. `sudo flatpak override --filesystem=~/.config/gtk-3.0:ro` --> needed for step 4
3. `sudo flatpak override --filesystem=~/.config/gtk-4.0:ro` --> needed for step 5
4. `ln -nsf ~/.config/gtk-3.0 ~/.var/app/<gtk_packagename_installed_as_user>/config/gtk-3.0`
5. `ln -nsf ~/.config/gtk-4.0 ~/.var/app/<gtk_packagename_installed_as_user>/config/gtk-4.0`

As stated, the following steps above will work for applications installed as `--system` but not to `--user`, I may have missed something so please help

**Comment by smcv** [comment]
> `sudo flatpak override --user --filesystem=~/.themes:ro`

This configures an override for root's `--user` apps. Try `flatpak override --user --filesystem=~/.themes:ro`, without sudo?

**Comment by ralphocdol** [comment]
> You should only need to use `sudo` if you are doing system-wide

Rather than _missed something_, it's more like I _messed up something_. Thank you for this, though I could not verify it now because I removed the `--user` as it uses extra storage for some dependency.
