### ISSUE TITLE
How to set up configurations before running flatpak program?

### ISSUE THREAD

**Issue by pyrotek45** [flatpak/flatpak#4355]
Hi, I'm trying to write a script that automatically sets up setting files for programs (vscode,gedit) and I'm not able to add any configuration files untill after I start the programs first (since flatpak programs dont create their folder untill after first run)

Is there an elegant solution or a simple script that I can write to solve this issue?

**Comment by mwleeds** [comment]
This is a bug tracker. For support see the forums listed in the README: https://github.com/flatpak/flatpak/blob/master/README.md
