### ISSUE TITLE
org.gnome.Sdk.Docs extension get unmounted but not remounted when updating it when an app is using it

### ISSUE THREAD

**Issue by Vanadiae** [flatpak/flatpak#4356]
## Linux distribution and version

Fedora 34

## Flatpak version

```
> flatpak --version
Flatpak 1.10.2
```

## Description of the problem

Updating an sdk extension seems to unmount it from running apps, but without remounting it at all. I would have expected at the very least that the extension be remounted after the unmounting that happens when updating. But in fact, I would have expected 
the old .Docs sdk extension to be kept alive in the app's sandbox until restarted, and not disrupt the app by unmounting it to mount the new one. Talking to a fdo-sdk maintainer, the later is what's supposed to happen.

## Steps to reproduce

(here it is with the gnome-nightly flatpaks installed user-wide, but I suppose non nightly/devel flatpaks system-wide have the issue too, like from flathub)

1. Install devhelp using `flatpak install gnome-nightly org.gnome.Devhelp.Devel`. The org.gnome.Sdk.Docs should have been installed as sdk extension dependency.
2. Open devhelp. You should see like ~20 different libraries documentation available in the sidebar.
3. Open a terminal and tile it with the devhelp window so that they are next each other, both visible at the same time so you can notice when and how it starts unmounting.
4. Downgrade org.gnome.Sdk.Docs. Check with `flatpak remote-info --show-commit --log gnome-nightly org.gnome.Sdk.Docs` the different available commits, pick an older commit and revert to it using `flatpak update --commit=<commit> org.gnome.Sdk.Docs`
5. Now look the progress going through the revert, and at one point you'll start seeing the different documentation disappearing in devhelp's sidebar, and they will all disappear at the end. Even when the revert finishes the documentation won't reappear in the list.
6. You can also check in Devhelp's sandbox using `flatpak enter`: the /usr/share/doc and /usr/share/gtk-doc (and all the other directories that are included in the .Docs sdk) are broken symlinks. The place they link to, /usr/share/runtime/docs, isn't mounted anymore (and even its /usr/share/runtime parent directory isn't mounted too, and it also contains the .Locale extension(s))

**Comment by smcv** [comment]
> Updating an sdk extension seems to unmount it from running apps, but without remounting it at all

I think what's really happening here is that the old version is being deleted. Its top level directory stays mounted, but is now empty. When you see the documentation gradually disappearing, that's the equivalent of `rm -fr`.

Flatpak doesn't unmount and remount extensions when updated (and in fact I don't think it can - the kernel wouldn't allow it), but they should keep a reference to the old version, so that it won't be deleted as long as an app that uses the extension is still running. I think the bug is that when devhelp has a dependency on `.Docs`, that reference isn't being held correctly.

**Comment by Vanadiae** [comment]
Actually I think I know what's going on here. Devhelp and Builder don't explicitely depend on org.gnome.Sdk.Docs, they only get it the same way as apps get the .Gtk3theme.* extensions mounted in their sandbox without depending explicitely on it. I can't test this because Builder has a bug that breaks building flatpak apps that have an sdk extension, but that's probably the problem here so I think I'm just going to close this issue as there doesn't seem be anything wrong in flatpak after all. :)

**Comment by smcv** [comment]
> Devhelp and Builder don't explicitely depend on org.gnome.Sdk.Docs, they only get it the same way as apps get the .Gtk3theme.* extensions mounted in their sandbox without depending explicitely on it

If `flatpak run` is mounting an extension, for whatever reason, then it should be taking out a lock on it to prevent it from being garbage-collected. It looks as though this is done in `flatpak_run_add_extension_args()`, but perhaps something is going wrong here?
