### ISSUE TITLE
don't ask for confirmation if there is only one remote repository  installed

### ISSUE THREAD

**Issue by rezad1393** [flatpak/flatpak#4364]
## Linux distribution and version
archlinux
## Flatpak version
Flatpak 1.11.2
## Description of the problem
even though I have only one remote configured ,flatpak still ask me if I am sure that I want to use that repo when searching for an app to install

## Steps to reproduce
only have the default flatpak repo installed then run:

flatpak install app/org.rolisteam.rolisteam/x86_64/stable
Looking for matches…
Found similar ref(s) for ‘app/org.rolisteam.rolisteam/x86_64/stable’ in remote ‘flathub’ (user).
Use this remote? [Y/n]: 

the question is redundant when use only has one repo.

**Comment by mwleeds** [comment]
Thanks for the bug report, fix available in #4382

**Comment by rezad1393** [comment]
I dont know if it is also needed but I will add it here:

there are two scenarios with one remote installed.

first:
 install with a general word like " flatpak install freefilesync" which is the one I should used in my original post as an example because that would give the output :

```
flatpak install freefilesync
Looking for matches…
Found similar ref(s) for ‘freefilesync’ in remote ‘flathub’ (user).
Use this remote? [Y/n]: 
Found ref ‘app/org.freefilesync.FreeFileSync/x86_64/stable’ in remote ‘flathub’ (user).
Use this ref? [Y/n]: 

org.freefilesync.FreeFileSync permissions:
    ipc      network      pulseaudio      wayland      x11      file access [1]      dbus access [2]

    [1] host, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.gtk.vfs, org.gtk.vfs.*


        ID                                              Branch            Op           Remote            Download
 1.     org.freefilesync.FreeFileSync.Locale            stable            i            flathub             < 6.2 MB (partial)
 2.     org.gnome.Platform.Locale                       40                i            flathub           < 333.7 MB (partial)
 3.     org.freefilesync.FreeFileSync                   stable            i            flathub            < 31.7 MB

Proceed with these changes to the user installation? [Y/n]:

```

the second scenario is when user installs with a complete name ( I dont know what is the technical word for it ) like "flatpak install org.freefilesync.FreeFileSync"

which would give :

```

 flatpak install org.freefilesync.FreeFileSync              
Looking for matches…
Found similar ref(s) for ‘org.freefilesync.FreeFileSync’ in remote ‘flathub’ (user).
Use this remote? [Y/n]: 

org.freefilesync.FreeFileSync permissions:
    ipc      network      pulseaudio      wayland      x11      file access [1]      dbus access [2]

    [1] host, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.gtk.vfs, org.gtk.vfs.*


        ID                                              Branch            Op           Remote            Download
 1.     org.freefilesync.FreeFileSync.Locale            stable            i            flathub             < 6.2 MB (partial)
 2.     org.gnome.Platform.Locale                       40                i            flathub           < 333.7 MB (partial)
 3.     org.freefilesync.FreeFileSync                   stable            i            flathub            < 31.7 MB

Proceed with these changes to the user installation? [Y/n]: 
```

as can be seen the first scenario has the redundant question which is the question number one.

the second scenario has only one question but it the the first scenario's first question:
```
Found similar ref(s) for ‘org.freefilesync.FreeFileSync’ in remote ‘flathub’ (user).
Use this remote? [Y/n]: 
```

so if you remove the first scenario's first question then it may impact the second scenario too because the second scenario doesnt ask for 
```
Found ref ‘app/org.freefilesync.FreeFileSync/x86_64/stable’ in remote ‘flathub’ (user).
Use this ref? [Y/n]: 
```

**Comment by mwleeds** [comment]
Yeah the PR changes the behavior in both cases to avoid the `Found similar ref(s)...` question, which is okay because the user is still asked for confirmation before the installation proceeds. The reason you don't get the `Found ref ...` question in the second scenario is that the ref was specified precisely already (`org.freefilesync.FreeFileSync`).

**Comment by rezad1393** [comment]
> Yeah the PR changes the behavior in both cases to avoid the `Found similar ref(s)...` question, which is okay because the user is still asked for confirmation before the installation proceeds. The reason you don't get the `Found ref ...` question in the second scenario is that the ref was specified precisely already (`org.freefilesync.FreeFileSync`).

what I mean was that even in second scenario the user needs to see from what remote it is going to be installed. if you remove that found similar ref question the user still see that in 1st case but if you remove the question, then in second case user will not see the remote used in the installation.
I dont know if this will happen because I only have on default repo but I am saying it here so that other that may have more that one still benefit from the removing of redundant question but also know which remote is used.

for example imagine user has two repos, one defaut and one that has, say, firefox experimental builds.
now if he uses `flatpak install org.mozilla.firefox-experimental`

then the user should only get one question that combines both info into one.
so instead of asking if user is sure to use the exp-firefox-repo remote then NOT asking for ref  just ask
`Found similar ref(s) for ‘org.mozilla.firefox-experimental’ in remote ‘**exp-firefox-repo**’ (user).`
`Use this **remote**? [Y/n]: `

this way when there is one ref, user only is asked one question that has repo info in too.

**Comment by mwleeds** [comment]
> > Yeah the PR changes the behavior in both cases to avoid the `Found similar ref(s)...` question, which is okay because the user is still asked for confirmation before the installation proceeds. The reason you don't get the `Found ref ...` question in the second scenario is that the ref was specified precisely already (`org.freefilesync.FreeFileSync`).
> 
> what I mean was that even in second scenario the user needs to see from what remote it is going to be installed. if you remove that found similar ref question the user still see that in 1st case but if you remove the question, then in second case user will not see the remote used in the installation.

No, the user will still see the remote being used since it is one of the columns in the table that precedes the question `Proceed with these changes to ...`

**Comment by rezad1393** [comment]
> > > Yeah the PR changes the behavior in both cases to avoid the `Found similar ref(s)...` question, which is okay because the user is still asked for confirmation before the installation proceeds. The reason you don't get the `Found ref ...` question in the second scenario is that the ref was specified precisely already (`org.freefilesync.FreeFileSync`).
> > 
> > 
> > what I mean was that even in second scenario the user needs to see from what remote it is going to be installed. if you remove that found similar ref question the user still see that in 1st case but if you remove the question, then in second case user will not see the remote used in the installation.
> 
> No, the user will still see the remote being used even when they have more than one configured and don't explicitly specify which to use in the `install` command, since "Remote" is one of the columns in the table that precedes the question `Proceed with these changes to ...`

you are right.
i forgot about that.
as I said I saw that you fixed my first issue.
just wanted to be sure that the fix wouldnt mess other people's routine or maybe even make their routine better.

thanks for the answer.

**Comment by mwleeds** [comment]
Reopening this until the PR is merged
