### ISSUE TITLE
Discord Flatpak is not properly sandboxed

### ISSUE THREAD

**Issue by newknowledg** [flatpak/flatpak#4367]
## Description of the problem
The current build of Discord is not properly sandboxed.
The app has access to / /etc /bin and several others that it should never be able to have access to.
## Steps to reproduce
Install the current version of Discord available on Flathub

**Comment by refi64** [comment]
This doesn't sound correct at all, are you sure you're not just looking at the rootfs *inside* the sandbox? Flatpak runtimes have their own /etc, /bin, etc, but it's isolated from your host system.

**Comment by newknowledg** [comment]
Upon further investigation @refi64 you are right. The behaviour of the nautilus is different in Discord than on other apps. Which threw me off. Thank you
