### ISSUE TITLE
Error pulling runtime/org.freedesktop.Platform/x86_64/1.4

### ISSUE THREAD

**Issue by abelncm** [flatpak/flatpak#437]
Hi, I am having the same issue with runtime/org.freedesktop.Platform/x86_64/1.4
I'm on Ubuntu 16.04LTS

```
 flatpak install gnome org.freedesktop.Platform//1.4
Installing: org.freedesktop.Platform/x86_64/1.4 from gnome

Receiving delta parts: 0/9 6.1 kB/s 98.3 kB/120.1 MB 5 hours 25 minutes
Receiving delta parts: 0/9 25.1 kB/s 426.0 kB/120.1 MB 1 hours 19 minut
Receiving delta parts: 0/9 34.9 kB/s 627.5 kB/120.1 MB 57 minutes 7 sec
Receiving delta parts: 0/9 34.8 kB/s 660.3 kB/120.1 MB 57 minutes 17 se
Receiving delta parts: 0/9 48.6 kB/s 971.6 kB/120.1 MB 40 minutes 52 se
Receiving delta parts: 0/9 84.5 kB/s 1.8 MB/120.1 MB 23 minutes 20 seconds remaining

error: While pulling runtime/org.freedesktop.Platform/x86_64/1.4 from remote gnome:
Error resolving 'sdk.gnome.org': Temporary failure in name resolution
```

Sometimes it skips the "Receiving delta parts" and goes straight to the error.

**Comment by alexlarsson** [comment]
This sounds like a dns issue with gnome.org

**Comment by alexlarsson** [comment]
Do you have multiple dns servers configured? Maybe it just works on some of them?

**Comment by abelncm** [comment]
It's a desktop computer, I don't believe I have virtual hosts set up

**Comment by alexlarsson** [comment]
I mean, do you have multipe "nameserver" lines in /etc/resolv.conf.

**Comment by abelncm** [comment]
No

# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search lan

**Comment by alexlarsson** [comment]
127.0.1.1 ? I guess you have a local caching dns server then? As a test, can you try (temporarily) replacing 127.0.1.1 with 8.8.8.8 and see if that makes it work?

**Comment by abelncm** [comment]
It's downloading now.
I have never edited this file though /etc/resolv.conf

**Comment by alexlarsson** [comment]
Yeah, its normally configured via e.g. networkmanager or some config UI.
It seems to point to a dns server that gets temporary failures for you though...

**Comment by abelncm** [comment]
You Sir are a national Hero,
I now can carry on with some .NET programming on MonoDevelop.

Thank you very much
