### ISSUE TITLE
downloads doesn't start over or resume after failure 

### ISSUE THREAD

**Issue by allaeddineomc** [flatpak/flatpak#4370]
os : fedora silverblue 34
Flatpak version : 1.10.2
Description of the problem : when a download fails due to bad internet connection it shows this error message 

Error: Error pulling from repo: While pulling app/net.lutris.Lutris/x86_64/beta from remote flathub-beta: fsck 312027344d4e984d7e2c6d76bc9e1264301394f860f0278633327f65cf3b49fd.dirtree: No such metadata object 312027344d4e984d7e2c6d76bc9e1264301394f860f0278633327f65cf3b49fd.dirtree
error: Failed to install net.lutris.Lutris: Error pulling from repo: While pulling app/net.lutris.Lutris/x86_64/beta from remote flathub-beta: fsck 312027344d4e984d7e2c6d76bc9e1264301394f860f0278633327f65cf3b49fd.dirtree: No such metadata object 312027344d4e984d7e2c6d76bc9e1264301394f860f0278633327f65cf3b49fd.dirtree

and when i try to run flatpak install again on the same package it will not even try downloading again and shows the same error , the workaround i use is to re try installing from a different user account and it works
Steps to reproduce
flatpak install "app name" (with an unstable internet connection)

**Comment by refi64** [comment]
Try running `flatpak repair --user`.

**Comment by allaeddineomc** [comment]
it does work but what it does ? and why it doesn't execute by default after the failure to avoid having a hidden state ?

**Comment by refi64** [comment]
[`flatpak-repair` tries to repair any issues with the Flatpak installation.](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-repair) There's an existing issue for suggesting a repair when something goes wrong during update, see #3773.
