### ISSUE TITLE
flatpak run chat.rocket.RocketChat fails to load gtk modules

### ISSUE THREAD

**Issue by peterge1998** [flatpak/flatpak#4375]
## Linux distribution and version
Fedora 34
## Flatpak version
Flatpak 1.10.2
## Description of the problem
`flatpak run chat.rocket.RocketChat` gives failed to load gtk modules:
```
$ flatpak run chat.rocket.RocketChat
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Rocket.Chat/rocketchat-desktop --type=zygote
[bugsnag] Loaded!
Gtk-Message: 09:47:53.041: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:47:53.041: Failed to load module "pk-gtk-module"
Gtk-Message: 09:47:53.041: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:47:53.041: Failed to load module "pk-gtk-module"

```
## Steps to reproduce
flatpak install flathub chat.rocket.RocketChat
flatpak run chat.rocket.RocketChat

**Comment by refi64** [comment]
Afaik these are entirely docile warnings and not really a Flatpak-specific issue regardless.
