### ISSUE TITLE
opening repo: opendir() fails when path contains non-ASCII chars or spaces

### ISSUE THREAD

**Issue by Lesik** [flatpak/flatpak#4378]
## Linux distribution and version

Debian 10

## Flatpak version

Flatpak 1.10.2
flatpak-builder 1.0.5

## Description of the problem

My understanding is that when using `--install` flag on flatpak-builder, it adds a local remote to flatpak. If the directory where `flatpak.{yaml,json}` is located contains non-ASCII characters or spaces, adding the local remote fails. This sucks for non-English speakers and non-technical people who might use spaces in their folder names.

```
Downloading sources
Initializing build dir
Committing stage init to cache
Starting build of org.flatpak.Hello
========================================================================
Building module hello in /home/user/работа/flatpak-bug/.flatpak-builder/build/hello-1
========================================================================
Running: install -D hello.sh /app/bin/hello.sh
Committing stage build-hello to cache
Cleaning up
Committing stage cleanup to cache
Finishing app
Please review the exported files and the metadata
Committing stage finish to cache
Exporting org.flatpak.Hello to repo
Commit: [hash]
Metadata Total: 9
Metadata Written: 2
Content Total: 3
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Installing app/org.flatpak.Hello/x86_64/master
Error: Failed to install org.flatpak.Hello: While pulling app/org.flatpak.Hello/x86_64/master from remote hello-origin: opening repo: opendir(/home/user/%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0/flatpak-bug/.flatpak-builder/cache): No such file or directory
Install failed: Child process exited with code 1
```

## Steps to reproduce

1. Create a directory that somewhere in its path has a non-ASCII character or space (e.g. `/home/user/работа/`, `/tmp/GüntherJauch/`, `/mnt/施氏食獅史/flatpak`, `/home/user/work for client/`)
1. Inside, create `hello.sh` and `flatpak.yaml` as described in https://docs.flatpak.org/en/latest/first-build.html
1. Run `flatpak-builder build-dir flatpak.yml --install --user`

**Comment by smcv** [comment]
What version of libostree are you using? This might be the same issue fixed in ostreedev/ostree#2293.

**Comment by Lesik** [comment]
@smcv Does this help? `libostree-1-1/buster-backports,now 2020.8-2~bpo10+1`

**Comment by smcv** [comment]
Yes, that's libostree, and that version does not have the fix I linked to.

**Comment by refi64** [comment]
This seems to have an OSTree bug that's now fixed, so closing.
