### ISSUE TITLE
File system access issue

### ISSUE THREAD

**Issue by ersinware** [flatpak/flatpak#4379]
## Linux distribution and version
Fedora 34
## Flatpak version
the latest version on dnf
## Description of the problem
I use Fedora 34 and I have installed WebStorm through Flatpak.

WebStorm does not find node, which is in the file system.

WebStorm has full access to filesystem,
node is located in /usr/bin folder,
as you can see on screenshoots, WebStorm does not find node when I look for node

I have installed WebStorm through JetBrains' website, It's ok now. However, I want to use it through Flatpak.
## Steps to reproduce
Screenshots:
![dh4zqz1EMwvCGJU539fqiA](https://user-images.githubusercontent.com/54334949/130228732-ca893324-16b1-45ff-8d9c-d8925554b3ef.png)
![DTSAf81G8-YaXT3wLXwt9A](https://user-images.githubusercontent.com/54334949/130228743-30b4523d-3021-470d-a52c-6b6eff898e36.png)
![M1MQaIhsfkKMp-wgyENLBg](https://user-images.githubusercontent.com/54334949/130228754-1c9af12e-e9ff-4d6f-aa90-f4605623d359.png)
![0pxKS7m7miRI7L3Y9jupkw](https://user-images.githubusercontent.com/54334949/130228762-f7ca79a9-e4c0-496e-9339-6666888f3915.png)
![DQWGyzGDCAX8tSr5i_FoAQ](https://user-images.githubusercontent.com/54334949/130228770-93548144-a618-498e-a5c8-ccd9123ccb49.png)
![ca5biZ0p0ycJ-31sjORF_Q](https://user-images.githubusercontent.com/54334949/130228775-a836caee-e242-46fe-8790-20c4984d5e83.png)

**Comment by gasinvein** [comment]
You can't use `node` installed in you host OS in flatpak sandbox; instead install `org.freedesktop.Sdk.Extension.node14` (or any other available version to your liking) from Flathub.

**Comment by mwleeds** [comment]
`/usr` in the Flatpak sandbox is based on the Flatpak runtime used for your app, so that's why your app can't find something in the host `/usr`.
