### ISSUE TITLE
Hard to know which install option is for what

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#439]
Today I tried to figure out how to install a `.flatpak` file from the command line and failed. One reason for this is that the options weren't clear in the help. The help currently contains the following:

```
  --bundle             Install from local bundle file
  --from               Load options from file or uri
```

It would be helpful if it could indicate which file types can be used from each option. I also found the word "options" confusing - it wasn't clear which options it was referring to.

On a slightly higher level, it would be cool if the `flatpak install` options could mirror the file types (this somewhat relates to #375). For example, `flatpak install --app-from` could install `.app` files, and `flatpak install --repo-from` could install repo files (or something along those lines.

**Comment by TingPing** [comment]
> On a slightly higher level, it would be cool if the flatpak install options could mirror the file types (this somewhat relates to #375). For example, flatpak install --app-from could install .app files, and flatpak install --repo-from could install repo files (or something along those lines.

Or just accept all file types with the same install command?

**Comment by alexlarsson** [comment]
The plan is to look for the right extensions and magically just do the right thing.
Then everything is just `flatpak install`.
