### ISSUE TITLE
flatpak-spawn binary is missing on Pop_OS!

### ISSUE THREAD

**Issue by Kangaroux** [flatpak/flatpak#4397]
⭐ If this isn't the right place to post this issue let me know where I should post it.

## Linux distribution and version

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute
```
## Flatpak version

```
$ apt info flatpak
Package: flatpak
Version: 1.11.2-1pop1~1627328845~21.04~d349217
Priority: optional
Section: admin
Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Installed-Size: 4,738 kB
Depends: adduser, bubblewrap (>= 0.4.0), dbus, xdg-dbus-proxy (>= 0.1.0), libappstream-glib8 (>= 0.6.1), libarchive13 (>= 3.0.4), libc6 (>= 2.33), libdconf1 (>= 0.26.0), libfuse2 (>= 2.9.2), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.57.2), libjson-glib-1.0-0 (>= 1.5.2), libostree-1-1 (>= 2020.8), libpolkit-agent-1-0 (>= 0.105), libpolkit-gobject-1-0 (>= 0.101), libseccomp2 (>= 1.0.1), libsoup2.4-1 (>= 2.41.90), libsystemd0, libxau6 (>= 1:1.0.9), libxml2 (>= 2.7.4), libzstd1 (>= 1.3.2)
Recommends: desktop-file-utils, hicolor-icon-theme, gtk-update-icon-cache, libpam-systemd, p11-kit, policykit-1, shared-mime-info, xdg-desktop-portal (>= 1.6), xdg-desktop-portal-gtk (>= 1.6) | xdg-desktop-portal-backend
Suggests: avahi-daemon
Conflicts: xdg-app
Replaces: xdg-app
Download-Size: 1,134 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
```

## Description of the problem

`flatpak-spawn` binary is not available. From what I can tell it should be part of the `flatpak` package.

```
$ which flatpak-spawn
$ ls /usr/bin | grep flatpak
flatpak
flatpak-bisect
flatpak-coredumpctl
pop-flatpak-repos
```

**Comment by smcv** [comment]
This isn't a bug. flatpak-spawn is meant to be available inside the app's sandbox, not on the host system, like this:

```
host$ which flatpak-spawn || echo no
no
host$ flatpak run --command=bash org.gnome.Recipes
[📦 org.gnome.Recipes ~]$ flatpak-spawn --help
Usage:
  flatpak-spawn [OPTION…] COMMAND [ARGUMENT…]
...
```

(The maintainers of Flatpak also do not control how Flatpak is packaged in particular distributions. If Flatpak was packaged incorrectly in Pop_OS then that would be an issue to report to Pop_OS, not to us.)

**Comment by Kangaroux** [comment]
> This isn't a bug. flatpak-spawn is meant to be available inside the app's sandbox, not on the host system, like this:
> 
> ```
> host$ which flatpak-spawn || echo no
> no
> host$ flatpak run --command=bash org.gnome.Recipes
> [📦 org.gnome.Recipes ~]$ flatpak-spawn --help
> Usage:
>   flatpak-spawn [OPTION…] COMMAND [ARGUMENT…]
> ...
> ```
> 
> (The maintainers of Flatpak also do not control how Flatpak is packaged in particular distributions. If Flatpak was packaged incorrectly in Pop_OS then that would be an issue to report to Pop_OS, not to us.)

Was trying to get it to work in vscode which is running in a container, but it seems the integrated terminal already is using `flatpak-spawn`
