### ISSUE TITLE
Using "yes" with flatpak doesn't work - prompt is answered with 'n' instead of 'y'.

### ISSUE THREAD

**Issue by RDKRACZ** [flatpak/flatpak#4409]
## Linux distribution and version
Doesn't matter / Multiple OS's tested 
## Flatpak version
1.11.2
## Description of the problem
command `yes | flatpak update`/`install` should update/install packages without waiting for a user input but instead, the command is cancelled.
![image](https://user-images.githubusercontent.com/43277609/133003098-fedfe017-b034-4914-93cc-242edb9d2f2e.png)

## Steps to reproduce
yes | flatpak update

**Comment by refi64** [comment]
Afaik this is intentional, Flatpak essentially "assumes" no answer when there's no tty present. For what you want, I believe `flatpak install -y` should do the trick.
