### ISSUE TITLE
[Feature Request] Add first party command to change themes for flatpak applications.

### ISSUE THREAD

**Issue by CTZxVULKAN** [flatpak/flatpak#4414]
**System Information** :
* Artix Linux OpenRC ( 5.13.16-hardened1-1-hardened )
* Flatpak 1.11.3

**The Issue**

Flatpak already has a repository for themes and also has the functionality to download them and set them. However this functionality requires the use of a third party application like Gnome-Tweaks. 
Gnome tweaks used to theme GTK based flatpak apps is only available for the Gnome-DE, this hinders the ability of users outside Gnome DE (eg i3-wm,dwm) to customize their flatpak apps.

**Proposed Solution**

Add some **first party commands** to set themes directly via the terminal like:

```
flatpak set-theme <THEME> <APPLICATION ID>
```
> This command could either set the theme for every flatpak application on system or could work on a per app basis.

OR

Create an **graphical utility** to manage themes for fatpak Apps.

I would love to hear what the developers have their thoughts on this :)

**Comment by TingPing** [comment]
Flatpak doesn't maintain a theme separate from the host, and I'm not sure why it should.

It simply looks for what is set in gsettings, which desktop tools like GNOME-Tweaks and Plasma's settings, already do.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flatpak/flatpak/issues/4414#issuecomment-920080977

The reason for the suggestion is that Fatpak is meant to be portable. Not everyone uses gsettings, and KDE Plasma for me has never correctly configured the GTK theme for Flatpak correctly.

**Comment by TingPing** [comment]
gsettings isn't a desktop specific API.

You likely just have an outdated installation of Plasma. The first thing I did when implementing this feature was get them to support this.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I have only used OpenSUSE Tumbleweed and Kubuntu, and always the most new versions that have been available. I am not the only one that has been unable to cause the themes to be applied, as my research has demonstrated, but I have never managed to remediate it. Regardless, this probably should not be discussed here.

**Comment by CTZxVULKAN** [comment]
I am using a tiling window manager **not** a desktop enviorment. I dont have acess to gsettings on my system. 

This is why I am unable to change flatpak themes on my system.

Flatpaks are supposed to run on all kinds of linux distributions, then all its features should also be functional in all kinds of linux distrobutions.

A first party solution in this case would be great.

**Comment by TingPing** [comment]
> I am using a tiling window manager not a desktop enviorment. I dont have acess to gsettings on my system.

You do... its a command line tool.

There is no difference between:

`flatpak set-theme foo` and `gsettings set org.gnome.desktop.interface gtk-theme foo`.

Honestly if this feature were to exist, the former command would just do the latter.

I'm closing this. Its just beyond the scope of `flatpak`. Themes are a system setting, flatpak does not override that system setting at all, it simply reads from it to install packages automatically.
