### ISSUE TITLE
Parental control checks broken on system repo

### ISSUE THREAD

**Issue by dbnicholson** [flatpak/flatpak#4418]
## Linux distribution and version
Endless OS master

## Flatpak version
1.10.2

## Description of the problem
When installing to the system repo, the user's parental controls settings are ignored. This was introduced in #4022. See https://github.com/flatpak/flatpak/pull/4022#issuecomment-920593414. Note that this continues to work for the user repo.

## Steps to reproduce

1. Add an app filter to not allow installing to the system repo - `malcontent-client set-app-filter --disallow-system-installation`
2. Install an app to the system repo - `flatpak install --system --noninteractive flathub org.gnome.Todo`
3. Installation succeeds but should be prevented. You should see `Error: Failed to install org.gnome.Todo: Installing app/org.gnome.Todo/x86_64/stable is not allowed by the policy set by your administrator`.

**Comment by pwithnall** [comment]
Fix available in https://github.com/flatpak/flatpak/pull/4436
