### ISSUE TITLE
Accessing flatpak directories

### ISSUE THREAD

**Issue by CuvlBoi** [flatpak/flatpak#4424]
I want to add my .mp3 files to a locale directory that the spotify i dowloaded from flatpak can access
I am quite new to linux, explanation would be appreciated.
I am on Arch Linux

**Comment by fabriciojardim** [comment]
Hi. My answer is not technical so take my words with a grain of salt. 

You can install an app called [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) that let you manage permissions for all your Flatpak apps. You can then add your current mp3 directory to the list Spotify is allowed to see.
This is probably what you want.

Or

If you really want to look into into a flatpak local data or config files look under `your_home_folder/.var/app/the_app_id_name`. This is like your "home" as seen by a sandboxed application.
