### ISSUE TITLE
`flatpak update` wants to install eol platforms with no apparent reason

### ISSUE THREAD

**Issue by dreua** [flatpak/flatpak#4425]
## Linux distribution and version
Fedora 34
## Flatpak version
Flatpak 1.10.2

## Description of the problem
```
$ flatpak update
Looking for updates…
Info: org.freedesktop.Platform.VAAPI.Intel//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version


        ID                                              Branch            Op           Remote            Download
 1.     org.freedesktop.Platform.GL.default             19.08             i            flathub           < 89,1 MB
 2.     org.freedesktop.Platform.VAAPI.Intel            19.08             i            flathub            < 8,7 MB
$ flatpak uninstall --unused
Nothing unused to uninstall
```

Flatpak informed me about those eol platforms, I subsequently uninstalled them without problems. The annoying thing is, that flatpak wants to reinstall them on each update for no apparent reason. 

`flatpak list --app-runtime=org.freedesktop.Platform.GL.default//19.08` returns nothing

Related to #3531 

## Steps to reproduce
`flatpak update`
This is probably an issue specific to my environment, let me know what I can do to help debugging this.

**Comment by dreua** [comment]
Just saw a similar issue #4369 , one of those should be probably closes as duplicate.

To answer @mwleeds question in my case: 
Flatpak does not offer to remove those two packages if installed (neither with `update` nor `uninstall --unused`) *but* it informs me about the "end-of-life" status on each update which is annoying and not helpful if I can't do anything about it.

**Comment by mwleeds** [comment]
>flatpak list --app-runtime=org.freedesktop.Platform.GL.default//19.08 returns nothing

This is because the runtime extension is not being used directly by an app. It is being pulled in by a runtime which itself is probably installed by an app. The solution is to either uninstall the offending app if you don't want to use the outdated runtime, or get the application maintainer to update the app to use a newer runtime.

The Flatpak CLI can also be improved, but for that we already have #3531
