### ISSUE TITLE
configuarations files from flatpak install?

### ISSUE THREAD

**Issue by hajonnes** [flatpak/flatpak#4433]
## Linux distribution and version
Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.15-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 960/PCIe/SSE2
Nvidia graphics driver version 470.63.01
## Flatpak version
Flatpak 1.11.3
#nvidia driver version in flatpak:
nvidia-470-63-01

Hi,
I use a program called Xmind8 have tried to install it with both flatpak and from the AUR repository. The flatpak version uses much more GPU and hence performes much better than the AUR version. 

So now I wonder if there is a way to see what nvidia settings the flatpak version is using and comparing them to my own to deduct where the problem might be. 
So now I wonder where a flatpak install gets it's nvidia settings from. I could not find any '.nvidia-settings-rc', 'xorg.conf', nvidia.conf or .xinitrc files under '/var/lib/flatpak' .

Also, just out of curiosity, does flatpak mount an environment during execution of a program, if so where does it reside. I searched in  '/proc/mounts'  when xmind in flatpak was running, but could not find any obivous location of the flatpak environment.

**Comment by fabriciojardim** [comment]
Config files and other program data are usually under `home_path/.var/app/app-id-name/`.

See: https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories

**Comment by hajonnes** [comment]
Thanks for replying.
Do you know where the settings for the nvidia driver is,
this is all I have in home_path/.var/app:
.
└── app
    └── net.xmind.XMind8
        ├── cache
        │   ├── fontconfig
        │   │   ├── 027ed4baa1ca4c80313205c19a90e206-le64.cache-7
        │   │   ├── 053808e43ffc5f55cb0102b3c9a4c019-le64.cache-7
        │   │   ├── 16a197dc3bff509b8c88d6f4cc0eac7c-le64.cache-7
        │   │   ├── 22d9eddab25b79ce859d7db518d88693-le64.cache-7
        │   │   ├── 232bc1edfffbf7e8a8cd4e10b164e0d0-le64.cache-7
        │   │   ├── 2a1131895124967f6d20401e2f028595-le64.cache-7
        │   │   ├── 46251b2d3d0cca9a3f5cf18615bbecfd-le64.cache-7
        │   │   ├── 4b0f8a2f69fe591da6cf9ff3308b18f7-le64.cache-7
        │   │   ├── 5148b94535b24520129dbf9aba9b36f7-le64.cache-7
        │   │   ├── 6607b64457902fb5502bbda69691078f-le64.cache-7
        │   │   ├── 6855fba38af6e49dbdd0c734554a6c4c-le64.cache-7
        │   │   ├── 69872ceeb5e8cc6c583db5cac5df3b26-le64.cache-7
        │   │   ├── 7d4ba368d5928cb3384361e02118d156-le64.cache-7
        │   │   ├── 84138a19d307d0fd3aee4a2b6f98773f-le64.cache-7
        │   │   ├── 85879d2b833a6067bc9906a86b440a8c-le64.cache-7
        │   │   ├── b7bfdde75c42672b235e77fec00f45c9-le64.cache-7
        │   │   ├── cb343c317113e4c83fd77ad8a987be44-le64.cache-7
        │   │   └── fb38f64d099233443b3859f4b84279bd-le64.cache-7
        │   └── tmp
        ├── config
        │   ├── gtk-2.0
        │   │   └── gtkfilechooser.ini
        │   └── user-dirs.dirs
        └── data
            └── recently-used.xbel


In the document you linked to they talked about having the directories /etc, /usr and /app in the container but they do not mention how to access it. I think the settings must be there but I have no Idea on how to access it or if it is possible to extract the information somehow.

**Comment by fabriciojardim** [comment]
No idea.

**Comment by mwleeds** [comment]
Nvidia drivers are packaged separately for Flatpaks than other apps: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia

Closing this to not clutter the issue tracker with things that aren't bugs.
