### ISSUE TITLE
`?`-characters in weird places in terminal, guessing they're supposed to be either unicode characters and/or formatting (color//bold/italic/ect)?

### ISSUE THREAD

**Issue by OwenAR** [flatpak/flatpak#4435]
Ubuntu 20.04.3 LTS
Flatpak 1.11.2

The feedback from flatpak in my terminal has a bunch of `?`-characters in weird places,
and I'm guessing they're supposed to be either unicode characters (a lot of them are placed like some sort of quotation marks)
and/or formatting (color//bold/italic/ect)?

It looks like this:
```
> flatpak search discord
Name    Description                                                                                            Application ID      Version        Branch Remotes
Discord Messaging, Voice, and Video Client                                                                     ?discordapp.Discord 0.0.16         stable flathub
Veloren Veloren is a multiplayer voxel RPG written in Rust. It is inspired by games such as Cube World, Legen? net.veloren.veloren 0.11.0-nightly stable flathub
Airshi? Airshipper is the official launcher for Veloren.                                                       ?veloren.airshipper 0.5.0          stable flathub
Guilded Messaging, Voice, and Video Client                                                                     gg.guilded.Guilded  1.0.9109710    stable flathub

> flatpak install discord
Looking for matches?
Found similar ref(s) for ?discord? in remote ?flathub? (system).
Use this remote? [Y/n]: Y
Found ref ?app/com.discordapp.Discord/x86_64/stable? in remote ?flathub? (system).
Use this ref? [Y/n]: Y
Required runtime for com.discordapp.Discord/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: Y

com.discordapp.Discord permissions:
    ipc     network     pulseaudio     x11     devices     file access [1]     dbus access [2]     tags [3]

    [1] xdg-download, xdg-pictures:ro, xdg-videos:ro
    [2] com.canonical.AppMenu.Registrar, com.canonical.Unity.LauncherEntry, com.canonical.indicator.application, org.freedesktop.Notifications, org.kde.StatusNo
    [3] proprietary


        ID                                             Branch            Op           Remote            Download
 1. [?] org.freedesktop.Platform.GL.default            21.08             i            flathub           128.3?MB / 128.6?MB
 2. [?] org.freedesktop.Platform.Locale                21.08             i            flathub            17.7?kB / 324.9?MB
 3. [?] org.freedesktop.Platform.openh264              2.0               i            flathub             1.5?MB / 1.5?MB
 4. [?] org.gtk.Gtk3theme.Breeze-Dark                  3.22              i            flathub            93.1?kB / 156.9?kB
 5. [?] org.freedesktop.Platform                       21.08             i            flathub           152.3?MB / 198.4?MB
 6. [?] com.discordapp.Discord                         stable            i            flathub            80.3?MB / 81.7?MB

Installation complete.
⏎
```

(
I will admit it *might* be something to do with my slightly weird locale
(region `en_CA` (`UTF-8`), except I have time set to `en_SE` in an attempt to fix the time/date display to YYYY-MM-DD and 24H time)
but experimenting with that is too slow and cumbersome for me right now, because it requires rebooting,
so I figured I may as well report it already since it seems reasonably likely to be nothing to do with that.
)

**Comment by mwleeds** [comment]
Many of those are definitely unicode characters. Maybe the font you're using in your terminal emulator doesn't have support for them.

**Comment by smcv** [comment]
> I do seem to have it fixed now, and it seems that it was caused by some weird interaction with locales.

Maybe this is the same regression in #4411 that caused #4471? Although I wouldn't have expected that to affect Ubuntu 20.04, only 18.04 and older.

Anyway, if it's fixed for you and nobody else reports the same thing, I think we can assume misconfiguration and move on.

**Comment by woodvale** [comment]
Welp, I can confirm that this bug is still here, just stumbled into it on my new install of KDE Neon, Flatpak 1.12.7
![image](https://user-images.githubusercontent.com/81210414/207465720-cf9b5ea3-bdf3-471c-b178-1f127b1e6b0a.png)

**Comment by smcv** [comment]
These are Unicode (UTF-8) characters, being transliterated by GLib to `?` because your locale settings claim to have no better way to display them. You would probably get similar behaviour from running this program, which prints a UTF-8 ellipsis `…`:

```
/* gcc -o print-unicode print-unicode.c; ./print-unicode */
#include <glib.h>
int main (void)
{
  g_print ("\xe2\x80\xa6\n");
  return 0;
}
```

Please check that your locale settings are correct and consistent, specifying a UTF-8 locale such as `en_US.UTF-8` or `de_DE.utf8`.

**Comment by thornySoap** [comment]
Hello,

I've been trying things for a while now but I still get the same behavior.
My locale settings look reasonable to me:
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Following [this Stackoverflow answer](https://stackoverflow.com/a/79570947/20806524) I modified your sample to
```c
/* gcc -o print-unicode print-unicode.c; ./print-unicode */
#include <glib.h>
#include <locale.h>
int main (void)
{
  setlocale(LC_ALL, "");
  g_print ("\xe2\x80\xa6\n");
  return 0;
}
```
, which resulted in the correct printing of the ellipsis character.

Citing from the [manpage](https://linux.die.net/man/3/setlocale) linked in the answer:

> The locale "C""" or "POSIX""" is a portable locale; its LC_CTYPE part corresponds to the 7-bit ASCII character set.
> 
> [...]
> 
> On startup of the main program, the portable "C""" locale is selected as default. A program may be made portable to all locales by calling:
> 
> setlocale(LC_ALL, "");

I suggest to add such a call here, too.

Apologies if that is nonsense, I unfortunately have zero experience with C.
