### ISSUE TITLE
add a portal for self-updates

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#444]
A surprising number of apps want to update themselves from inside their ui. And homegrown methods of doing so are unreliable at best, and insecure at worst. It seems that flatpak could easily improve this situation by offering a portal that sandboxed apps can use to find out about and trigger updates. This would be strictly limited to updating the app itself, nothing else. Suggested API:

GetAvailableUpdate
InstallUpdate

Since this is closely tied to flatpak itself, and the implementation would likely use libflatpak, it may make sense to put this portal into flatpak itself, instead of xdg-desktop-portal.

**Comment by hadess** [comment]
Is this really useful when there's a unified way to get updates?

As an example, macOS X has tons of apps with the "live update" ability, but none of the apps shipped through the macOS App Store, or iOS App Store have such UIs.

I'd say that this isn't needed. The way to get updates is to let automatic updates do their job!

**Comment by directhex** [comment]
If nothing else, consider apps which advertise multiple simultaneous releases (e.g. alpha/beta/stable, stable/LTS, etc). These are the apps which often ship their own updater, and are aware of their own versions - there should still be a mechanism to switch branches & inform the user of updates when running inside a sandbox.

![image](https://user-images.githubusercontent.com/308992/28574348-abc49a16-711b-11e7-9ff0-51ae80f72028.png)

**Comment by TingPing** [comment]
> there should still be a mechanism to switch branches & inform the user of updates when running inside a sandbox.

Would be nice for frontends like gnome-software to show branches to switch too. Don't think package management should be in every application though.

**Comment by alexlarsson** [comment]
In addition to "update yourself" we need "restart myself" I guess. In particular this is interesting if the app us updated from e.g. gnome-software and the app detects the "/app/.updated" file being created.

**Comment by directhex** [comment]
> Would be nice for frontends like gnome-software to show branches to switch to. Don't think package management should be in every application though.

A mechanism for an app to see available branches, and ask $misc_frontend to switch & run the update, is more than sufficient IMHO. Current branch can already be parsed from /.flatpak-info

**Comment by alexlarsson** [comment]
I'm removing this from the 1.0 milestone, due to a) lack of time, and b) its really implementable outside flatpak in the portals.

**Comment by hadess** [comment]
Maybe best to close this, and move the request to xdg-desktop-portal?

**Comment by matthiasclasen** [comment]
yes

**Comment by Skycoder42** [comment]
Was this actually moved to xdg-desktop-portal? I was not able to find such an issue there. If yes, it would be nice to mention it here, so it's easier to find
