### ISSUE TITLE
Please update 'Filesystem' wiki page

### ISSUE THREAD

**Issue by xpseudonym** [flatpak/flatpak#4447]
## Linux distribution and version
n/a
## Flatpak version
n/a
## Description of the problem
File system described here:
https://github.com/flatpak/flatpak/wiki/Filesystem
is over 5 years old and doesn't (seem to) reflect what is current (on my system)
## Steps to reproduce
Go to https://github.com/flatpak/flatpak/wiki/Filesystem

Thanks

**Comment by wjt** [comment]
What part of the page do you think is inaccurate? It looks completely accurate to me.

**Comment by Mikenux** [comment]
@xpseudonym: Could you tell what is wrong? Thanks!

**Comment by xpseudonym** [comment]
I'm sorry - I've no idea...  2021 is a long time ago now...  It may have been something to do with Firefox and trying to maintain a consistent profile between flatpak installed and dnf installed versions - but, I really have no idea.  Not a very good bug report is it...  I'll close it.

**Comment by Mikenux** [comment]
Thanks. Maybe you thought about the filesystem permission? It's about the organization of the sandbox files (and repositories). Other than that, maybe it could be clarified in the wiki (the title) that it's about the sandbox filesystem. @allanday

**Comment by xpseudonym** [comment]
I can say that the wiki does reflect my file system now - I do have a vague recollection of having a nightmare trying to maintain a flatpak install and distro install of Firefox and permissions would make sense, but it really is vague - I'd be embarrassed if anyone spent more time thinking about this - I'm embarrassed at such a useless bug report as it is.

**Comment by Mikenux** [comment]
No need to think more about. At least the title of the page should match the title in the sidebar. Aside, sharing a configuration between a flatpak and a "native" install (rpm, deb, ...) is not possible (if that was you meant by "profile").
