### ISSUE TITLE
Deprecation of ‘flatpak_installation_install_ref_file’

### ISSUE THREAD

**Issue by mcrha** [flatpak/flatpak#4453]
## Description of the problem

The flatpak has deprecated `flatpak_installation_install_ref_file` as can be seen here:

```
../plugins/flatpak/gs-flatpak.c:3480:9: warning: ‘flatpak_installation_install_ref_file’ is deprecated: Use flatpak_transaction_add_install_flatpakref instead [-Wdeprecated-declarations]
 3480 |         xref = flatpak_installation_install_ref_file (self->installation,
      |         ^~~~
In file included from /usr/include/flatpak/flatpak.h:38,
                 from ../plugins/flatpak/gs-flatpak-app.h:12,
                 from ../plugins/flatpak/gs-flatpak.c:23:
/usr/include/flatpak/flatpak-installation.h:379:37: note: declared here
  379 | FLATPAK_EXTERN FlatpakRemoteRef *   flatpak_installation_install_ref_file (FlatpakInstallation *self,
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      
```
I did not get how the `flatpak_transaction_add_install_flatpakref` replaces the `flatpak_installation_install_ref_file`. The main problem is that I need the FlatpakRemoteRef instance, but I cannot get to it from the transaction, or I do not know how. What I tried:
```
	/* get name */
	ref_name = g_key_file_get_string (kf, "Flatpak Ref", "Name", error);
	if (ref_name == NULL) {
		gs_utils_error_convert_gio (error);
		return NULL;
	}

	/* create transaction */
	transaction = gs_flatpak_transaction_new (self->installation, cancellable, error);
	if (transaction == NULL) {
		g_prefix_error (error, "failed to build transaction: ");
		gs_flatpak_error_convert (error);
		return NULL;
	}

	/* install the remote, but not the app */
	ref_file_data = g_bytes_new (contents, len);
	if (!flatpak_transaction_add_install_flatpakref (transaction, ref_file_data, error)) {
		g_prefix_error (error, "failed to add to transaction: ");
		gs_flatpak_error_convert (error);
		return NULL;
	}
	if (!flatpak_transaction_run (transaction, cancellable, error)) {
		g_prefix_error (error, "failed to run transaction: ");
		gs_flatpak_error_convert (error);
		return NULL;
	}
	xref = flatpak_installation_fetch_remote_ref_sync (self->installation,
							   ref_name,
							   #kind,
							   #name,
							   #arch,
							   #branch,
							   cancellable,
							   error);
```
This looks like a chincken-egg problem, because I "install" the ref from a file, but the only thing I know is the ref_name. I've no idea of the `#kind, #name, #arch, #branch`. Where do I get those?

The returned `xref` from the `flatpak_installation_install_ref_file` is used to get those unknown values from...

By the way, this is gnome-software, specifically [thus function](https://gitlab.gnome.org/GNOME/gnome-software/-/blob/main/plugins/flatpak/gs-flatpak.c#L3425).

I think you should de-deprecate the `flatpak_installation_install_ref_file`, the idea to use the transaction is very bad, making things overcomplicated and uncertain.

**Comment by mwleeds** [comment]
> 	/* install the remote, but not the app */

I don't see how this is only installing the remote. It looks like you're installing the app when you run the transaction. If you want information about the ref before running the transaction, see `flatpak_transaction_get_operations()`

> xref = flatpak_installation_fetch_remote_ref_sync (self->installation,
> 							   ref_name,
> 							   #kind,
> 							   #name,
> 							   #arch,
> 							   #branch,
> 							   cancellable,
> 							   error);

The second argument to that function is the remote name, not the ref name.

> By the way, this is gnome-software, specifically thus function.

When linking to a specific line, you might want to link to it from a particular commit rather than the branch. Because as the branch moves, your link will start pointing somewhere else than you intend. For example the link you gave currently points to a closing curly brace in a function and I doubt that's what you intended. Here's a link to a line of code that's stable over time: https://gitlab.gnome.org/GNOME/gnome-software/-/blob/1a32bd3eaaf7ec0322c46599e3b949080a410806/AUTHORS#L6

> I think you should de-deprecate the flatpak_installation_install_ref_file, the idea to use the transaction is very bad, making things overcomplicated and uncertain.

The `FlatpakTransaction` interface is much more powerful than the `FlatpakInstallation` functions that preceded it. I don't think we're going to turn back now. Better to improve `FlatpakTransaction` in any way that's needed.

**Comment by mcrha** [comment]
Ah, right, the code moved. It was supposed to be the [gs_flatpak_file_to_app_ref](https://gitlab.gnome.org/GNOME/gnome-software/-/blob/1a32bd3eaaf7ec0322c46599e3b949080a410806/plugins/flatpak/gs-flatpak.c#L3441) function.

The variable is called `ref_name`, because it comes from the file, `[Flatpak Ref] Name=...`, it is like that already in the gnome-software code. The only thing I wanted to change was to replace the deprecated function, not to rewrite it all. If I read the code properly, the resulting `xref` is used to construct the description of the remote, as a `GsApp` instance. I believe this is not meant to install anything, the users can click the "Install" button if they want to, but this function only wants to get some info about the remote.

**Comment by mwleeds** [comment]
@mcrha I have a branch here to remove use of the deprecated function in g-s: https://gitlab.gnome.org/GNOME/gnome-software/-/tree/mwleeds/fix-deprecated-install

However it does involve some added complexity, so I'm open to ideas of better approaches. If we were to un-deprecate `flatpak_installation_install_ref_file()`, it means we would have to maintain two implementations for installing flatpakref files indefinitely, with one only being advantageous in the unusual use case GNOME Software has of only wanting to get information about the thing that could be installed without actually installing it. I wonder if a more forward-looking option would be to make `FlatpakTransaction` more user-friendly for this case.

Or, if you think it's good enough, you can propose those changes on the g-s repo. However, looks like there's a unit test failure so I guess the branch is not quite MR ready in any case.

**Comment by mcrha** [comment]
Thanks for a deep investigation. I agree, if the gnome-software unit tests depend on an invalid or obsolete behaviour of the used functions, then the tests should be fixed.

Having the tests depend on some patched/latest version of flatpak would be unfortunate, thus if you can make this working properly without any change on the flatpak side, and in a way where the tests won't break when the flatpak is fixed, then let's do it and open a merge request from your branch on the gnome-software side.

**Comment by mwleeds** [comment]
Closing this in favor of https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1087
