### ISSUE TITLE
Keeping /var/lib/flatpak in a separate partition

### ISSUE THREAD

**Issue by pdureau** [flatpak/flatpak#446]
Hello,

I will reinstall my GNU/Linux OS soon and I am thinking about keeping my flatpak apps and runtimes (/var/lib/flatpak) in a separate partition.

Why?
* first, to preserve the applications between 2 OS fresh installations without downloading everything each time (my flatpak files take 3GB, and growing...)
* next, maybe, to share the flatpak apps between 2 computers

Is it technically possible today? If not, is it to possible to add this feature ?

Thanks so much for building the most exciting Linux technology of 2016.

**Comment by alexlarsson** [comment]
It should work fine. Or just make it a symlink to some other place.
Recent master even lets you configure this in a config file.

**Comment by mariospr** [comment]
You could use the new feature landed in master that allows you to define multiple installations, as @alexlarsson said, but a symlink would work fine and it's probably the simplest solution if you are planning to move everything, as it seems to be the case here.

**Comment by pdureau** [comment]
Thanks for your answers. The new --installation=NAME featurelooks interesting.

However, a simple mount point from /dex/sdxx to /var/lib/flatpak will fit my needs.
