### ISSUE TITLE
error: Failed to install No such metadata object

### ISSUE THREAD

**Issue by BryanQuigley** [flatpak/flatpak#4476]
## Linux distribution and version
Fedora Linux 35
## Flatpak version
1.12.0
## Description of the problem
sudo flatpak install org.gnome.Shotwell
..choose flathub
        ID                          Branch         Op         Remote          Download
 1. [✗] org.gnome.Shotwell          stable         i          flathub         1.0 kB / 7.4 MB

Error: While trying to checkout 13f9ff2031811feb895e601513e3e21f2a5a8ed31558751c9751ddace20371ae into /var/lib/flatpak/app/org.gnome.Shotwell/x86_64/stable/.13f9ff2031811feb895e601513e3e21f2a5a8ed31558751c9751ddace20371ae-4XGBB1: No such metadata object 30605bbc4a7f6f291e1957a848165873a5b4783519b84f6ef63d001ac09ea575.dirtree
error: Failed to install org.gnome.Shotwell: While trying to checkout 13f9ff2031811feb895e601513e3e21f2a5a8ed31558751c9751ddace20371ae into /var/lib/flatpak/app/org.gnome.Shotwell/x86_64/stable/.13f9ff2031811feb895e601513e3e21f2a5a8ed31558751c9751ddace20371ae-4XGBB1: No such metadata object 30605bbc4a7f6f291e1957a848165873a5b4783519b84f6ef63d001ac09ea575.dirtree

Repair also errors out:
sudo flatpak repair
[45/95] Verifying flathub:runtime/org.freedesktop.Platform.GL32.nvidia-470-74/x86_64/1.4…
[95/95] Verifying flathub:app/com.github.tchx84.Flatseal/x86_64/stable…
Checking remotes...
Pruning objects
error: Querying object 2f25eed3abd2f79db1e426d05ff2aa3ee46645c892c1323f567458032d8a8e1a.file: No such file or directory

sudo ostree --repo=repo fsck --delete --all
Validating refs...
Validating refs in collections...
Enumerating objects...
Verifying content integrity of 53 commit objects...
error: No such metadata object 6c83b08e94c1a6c82ba1f40e0eca72e6360a38b79ff540bcd9bb3f0e2f489ba2.dirtree

## Steps to reproduce
I built and installed shotwell locally a bit ago. I'm guessing I messed something up there?

## What I've tried
> sudo flatpak repair (above)
> Removing all user flatpaks
> Manually removing /var/lib/flatpak/app/org.gnome.Shotwell
> Running ostree directly fsck manually (above)

## Other notes:
sudo flatpak remotes -d
Name         Title           URL                                    Collection ID Subset Filter Priority Options    … … Homepage             Icon
fedora       Fedora Flatpaks oci+https://registry.fedoraproject.org -             -      -      1        system,oci … … -                    -
flathub      Flathub         https://dl.flathub.org/repo/           -             -      -      1        system     … … https://flathub.org/ https://dl.flathub.org/repo/logo.svg
flathub-beta Flathub beta    https://dl.flathub.org/beta-repo/      -             -      -      1        system     … … https://flathub.org/ https://dl.flathub.org/repo/logo.svg

**Comment by mwleeds** [comment]
FWIW installing Shotwell works on my machine.

**Comment by BryanQuigley** [comment]
Well, it turns out this isn't a flatpak or ostree problem.   Failed to delete /var/lib/flatpak -- eventually did btrfs check --repair

The file flatpak/repo/objects/2f/25eed3abd2f79db1e426d05ff2aa3ee46645c892c1323f567458032d8a8e1a.file was stuck in some kind of zombie like state. Couldn't be deleted but also couldn't be read.
