### ISSUE TITLE
XDG_STATE_HOME is not set

### ISSUE THREAD

**Issue by lionirdeadman** [flatpak/flatpak#4477]
## Linux distribution and version
Fedora Linux 35

## Flatpak version
Flatpak 1.11.3

## Description of the problem
XDG_STATE_HOME is unset meaning applications will try to write to $HOME/.local/share instead which will in turn break it due to lack of permission.

## Steps to reproduce
- Install any flatpak
- flatpak run --command=bash com.example.App
- echo $XDG_STATE_HOME

**Comment by mwleeds** [comment]
Could you give a specific example of an app that is trying to use `$XDG_STATE_HOME` and failing as you describe?

**Comment by lionirdeadman** [comment]
> Did you verify this, or are you guessing? I would have expected that $HOME/.local/state would be a tmpfs:

Ah, If it's a tmpfs then that's why the bug happened. My script puts a file that needs to be referenced later so it would disappear and not work.

> This would presumably still be a problem for your app - it will happily save state to a directory that is going to vanish on exit, resulting in data loss, unless you use --persist (which should be accompanied by --unset-env as in my previous comment, to avoid being broken by custom XDG_STATE_HOME settings).

The script assumes .local/state if `XDG_STATE_HOME` is unset as per spec which in turn breaks because it checks the file (which in turn means that we download the file needed at every application startup). Is XDG_STATE_HOME expected to be emptied?
