### ISSUE TITLE
DNS using wrong destination address

### ISSUE THREAD

**Issue by KhalilSantana** [flatpak/flatpak#4481]
## Linux distribution and version
```
% cat /etc/*-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
(Up to date as of 12/10/2021)

## Flatpak version
```
% flatpak --version
Flatpak 1.12.1
```
## Description of the problem
When resolving domain names using DNS, some flatpaks seem to utilize the wrong resolver address. On my machine I use systemd-resolved, which by default listens on 127.0.0.53 port 53 (and a few others), however some flatpaks seem to try to use 127.0.0.1:53 as the DNS resolver address, which of course fails because systemd-resolved is not listening on that ip:port combo.

![image](https://user-images.githubusercontent.com/26551202/136891931-cb158551-6da2-4add-9c5c-d6607fcfe043.png)

![image](https://user-images.githubusercontent.com/26551202/136892066-6314cc46-eab3-4273-8b64-971024b767fc.png)

## Steps to reproduce

1. Install ArchLinux and use systemd-resovled as your resolver. Then symlink /etc/resolv.conf (on the host) to resolved's file (as described [here](https://wiki.archlinux.org/title/Systemd-resolved#DNS))
3. Try to navigate the web using a flatpak like org.mozilla.firefox (unsure if all flatpaks are affected)
4. Open Wireshark and log traffic on the loopback interface
5. Observe packets going to 127.0.0.1 instead of  127.0.0.53

--
EDIT: Reworded a few things to make it clearer.

**Comment by mwleeds** [comment]
Looks like there was some work in this area not too long ago by @mcatanzaro: https://github.com/flatpak/flatpak/commit/e5da98ff4b12a080044d58b4cd2fb4edb4491132
