### ISSUE TITLE
[Bug]: flatpak cannot recover from connection breakage during download

### ISSUE THREAD

**Issue by nanonyme** [flatpak/flatpak#4492]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.12.1

### What Linux distribution are you using?

Fedora Linux

### What architecture are you using?

x86_64

### How to reproduce

This is quite hard to reproduce. You need connection to fail during flatpak download. For me it was enough to get this while trying to install Firefox from Flathub beta
```
error: Failed to install org.mozilla.firefox: While pulling app/org.mozilla.firefox/x86_64/beta from remote flathub-beta: While fetching https://dl.flathub.org/beta-repo/objects/63/5aa15aeb44597e45eafd28f50627d11d45352c71de962a0a3d5a415babcb29.filez: [92] Stream error in the HTTP/2 framing layer
```

### Expected Behavior

When you try to install again, download resumes using already downloaded contents.

### Actual Behavior

You get esoteric errors like
```
error: Failed to install org.mozilla.firefox: Error pulling from repo: While pulling app/org.mozilla.firefox/x86_64/beta from remote flathub-beta: Opening content object 7aa0dd5c75c8e15f6b33430eed4018bff391a112d8b765658bbee30e69b28445: Opening content object 7aa0dd5c75c8e15f6b33430eed4018bff391a112d8b765658bbee30e69b28445: Couldn't find file object '7aa0dd5c75c8e15f6b33430eed4018bff391a112d8b765658bbee30e69b28445'
```

### Additional Information

There's actually quite a few reports about this but it's not obvious from them what's broken so filing error about the specific issue.

**Comment by mwleeds** [comment]
I added #679 to a 1.13.1 milestone and hope to work on it soon. I don't think we need to leave this open in addition.

**Comment by vcarceler** [comment]
Sometimes you can see on `/var/lib/flatpak/app` a directory for the half-installed app but the app doesn't appear on `flatpak list`.

For us, when `flatpak repair` doesn't repair the problem is ok to delete the app dir (e.g. `rm -rf /var/lib/flatpak/app/org.mozilla.firefox`) and then reinstall the flatpak app.
