### ISSUE TITLE
[Bug]: status icons do not seem to be exported

### ISSUE THREAD

**Issue by eduardosm** [flatpak/flatpak#4495]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Arch Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Install an application that provides status icons (in `/app/share/icons/hicolor/*/status`). For example, org.remmina.Remmina from flathub.
2. Look at exported icons in `/var/lib/flatpak/export/share/icons`

### Expected Behavior

The icons in `/app/share/icons/hicolor/*/status` should be exported to `/var/lib/flatpak/export/share/icons/hicolor/*/status`, so they can appear in the system tray.

### Actual Behavior

These icons are not exported, so they will not appear in the system tray (e.g., https://github.com/flathub/org.remmina.Remmina/issues/84)

**Comment by smcv** [comment]
What, specifically, are the names of the icons exported by this app?

I don't think Flatpak can/should export *all* icons provided by an app, because if it did, that would let a malicious or compromised app export icons that are unrelated to the app itself, causing the rest of your UI to become misleading.

**Comment by eduardosm** [comment]
In remmina the missing icon is named `remmina-status.svg`

**Comment by eduardosm** [comment]
If the icon was named `org.remmina.Remmina-status.svg`, would it have been exported?

**Comment by smcv** [comment]
> If the icon was named `org.remmina.Remmina-status.svg`, would it have been exported?

I'm not sure exactly what naming convention is required, but it should be something like that.
