### ISSUE TITLE
Recognize running flatpaks by name

### ISSUE THREAD

**Issue by nhlfr** [flatpak/flatpak#453]
It would be very helpful to have a functionality of:

- listing currently running flatpaks
- being able to `flatpak enter` by name, not by PID

The problem with flatpak enter is that the only working "one-liner" for entering to some application's sandbox looks like `flatpak enter $(pgrep application_name) bash`. But what if we are running the same application outside of sandbox as well? Or if we are running many flatpaks for the same named application?

My proposition is to:

- give each running flatpak with some UUID or incremental number, i.e. `org.gnome.gedit-1` or `org.gnome.gedit-2542a1d5-2dde-49ca-aa14-afb6ed11244e`
- implement the `flatpak ps` command which will list the names of all flatpaks which are running
- allow the flatpak name as an argument of `flatpak enter`

**Comment by alexlarsson** [comment]
flatpak is fundamentally stateless. i.e. there is no "manager" service that keeps track what is running and what is not. This is by design, as such things are likely to break in various ways, and miss or contain stale information.

**Comment by alexlarsson** [comment]
It might be possible if we get the actual data from the kernel of course.

**Comment by matthiasclasen** [comment]
see flatpak ps
