### ISSUE TITLE
[Bug]: viber is not starting on centos 7

### ISSUE THREAD

**Issue by marinovgit** [flatpak/flatpak#4533]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.0.9

### What Linux distribution are you using?

CentOS

### Linux distribution version

CentOS Linux release 7.9.2009 (Core)

### What architecture are you using?

x86_64

### How to reproduce

flatpak run com.viber.Viber

### Expected Behavior

To start :)

### Actual Behavior

[root@local /home/user]# flatpak run com.viber.Viber
/app/extra/viber/Viber: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

### Additional Information

yum install qt5-qtbase
Package qt5-qtbase-5.9.7-5.el7_9.x86_64 already installed and latest version

----------------------------------
[root@local /home/user]# locate libQt5Core.so.5
/opt/calibre/lib/libQt5Core.so.5
/opt/google/earth/pro/libQt5Core.so.5
/usr/lib64/libQt5Core.so.5
/usr/lib64/libQt5Core.so.5.9
/usr/lib64/libQt5Core.so.5.9.7
/var/lib/flatpak/app/com.viber.Viber/x86_64/stable/587a3af5930847519a2981c6f8c3b79864b9ef08086709b1322868af325f5e58/files/extra/viber/lib/libQt5Core.so.5

After: flatpak update
/opt/calibre/lib/libQt5Core.so.5
/opt/google/earth/pro/libQt5Core.so.5
/usr/lib64/libQt5Core.so.5
/usr/lib64/libQt5Core.so.5.9
/usr/lib64/libQt5Core.so.5.9.7
/var/lib/flatpak/app/com.viber.Viber/x86_64/stable/587a3af5930847519a2981c6f8c3b79864b9ef08086709b1322868af325f5e58/files/extra/viber/lib/libQt5Core.so.5
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/20.08/7898e3822e6f10310c8f2b6ae8aa630ed102eb1e3341c7e57e0aa9757987d2ea/files/lib/x86_64-linux-gnu/libQt5Core.so.5

**Comment by mwleeds** [comment]
You might try opening an issue against viber unless it's clear this is a bug in Flatpak: https://github.com/flathub/com.viber.Viber/issues

>yum install qt5-qtbase

The Flatpak is going to exclusively use libraries that are bundled with it or in its runtime, not libraries installed on the host operating system.

**Comment by marinovgit** [comment]
@mwleeds Thank you.
I understand that but is there a way to find out where exactly it looks for this file libQt5Core.so.5
I tried -v with run command but no luck.

**Comment by hfiguiere** [comment]
in that case it's a bug with the viber package. It's a proprietary app that come with its own stack.

Nothing we can do.
