### ISSUE TITLE
[Bug]: flatpak search lists results with some invalid app ids ("Names must contain at least 2 periods")

### ISSUE THREAD

**Issue by cobratbq** [flatpak/flatpak#4535]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Debian

### Linux distribution version

bullseye

### What architecture are you using?

x86_64

### How to reproduce

When searching for flatpak applications using the commandline, some applications are listed with invalid app id. So far, all occurrences I have encountered are listed with app id consisting of 2 parts (1 separating period) which is illegal. In all occurrences I found, the actual app id is different, valid. So the listing shows incorrect information.

1. `flatpak search telegram`
```
    Name                         Description                                            Application ID                         Version          Branch          Remotes
    Telegram Desktop             Telegram Desktop messenger                             org.telegram                           3.1.9            stable          flathub
    Kotatogram Desktop           Kotatogram Desktop messenger                           io.github.kotatogram                   1.4.1            stable          flathub
    LibreTrack                   Private, cross-platform package tracking app           ru.proninyaroslav.libretrack           1.3.0            stable          flathub
    Franz                        Messenger for the desktop                              com.meetfranz.Franz                    5.7.0            stable          flathub
    Delta Chat                   Delta Chat email-based messenger                       chat.delta                             v1.22.2          stable          flathub
```
- It lists `org.telegram` but in actuality the app id is `org.telegram.desktop`.  
  command: `flatpak remote-info flathub org.telegram`  
  `error: Invalid id org.telegram: Names must contain at least 2 periods`
  command: `flatpak remote-info flathub org.telegram.desktop`  
  ```
  ID: org.telegram.desktop
  Ref: app/org.telegram.desktop/x86_64/stable
  Arch: x86_64
  Branch: stable
  Collection: org.flathub.Stable
  Download: 83.0 MB
  Installed: 218.0 MB
  Runtime: org.freedesktop.Platform/x86_64/21.08
  Sdk: org.freedesktop.Sdk/x86_64/21.08

  Commit: 78991b6beea36e4922f0992690920b74df2e800c1f42afeb0811c64f115f3bb7
  Parent: 5e29c92bb322315dfd478a67bf1e1063ee9c9722a4b8613eea858c6b6e779614
  Subject: Update tdesktop.git to 3.1.9 (22d03ba7)
  Date: 2021-10-12 19:45:56 +0000
  ```
- It lists `chat.delta` but in actuality the app id is `chat.delta.desktop`.

### Expected Behavior

Search results of `flatpak search` should list actual app id, and preferably without arbitrary truncation in case of long app id. (truncated with `...`)

### Actual Behavior

Include in reproduction recipe. Lists wrong app id. Should be correct app id.

**Comment by mwleeds** [comment]
Thanks for the bug report. Fix available in #4536
