### ISSUE TITLE
[Teamspeak3]: QCoreApplication::applicationDirPath: Please instantiate the QApplication object first

### ISSUE THREAD

**Issue by peterge1998** [flatpak/flatpak#4538]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

1. flatpak install flathub com.teamspeak.TeamSpeak
2. flatpak run com.teamspeak.TeamSpeak

### Expected Behavior

Open Teamspeak3

### Actual Behavior

➜  ~ flatpak run com.teamspeak.TeamSpeak           
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
Qt: Session management error: None of the authentication protocols specified are supported

**Comment by mwleeds** [comment]
You might try opening an issue here: https://github.com/flathub/com.teamspeak.TeamSpeak/issues

**Comment by peterge1998** [comment]
> You might try opening an issue here: https://github.com/flathub/com.teamspeak.TeamSpeak/issues

Thanks! Opened an [issue](https://github.com/flathub/com.teamspeak.TeamSpeak/issues/29) there. did not know it exists^^
