### ISSUE TITLE
[Bug]: unable to make the connection to flathub

### ISSUE THREAD

**Issue by boistordu** [flatpak/flatpak#4550]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.10.5

### What Linux distribution are you using?

Debian

### Linux distribution version

pureos 11

### What architecture are you using?

x86_64

### How to reproduce

Is it because of my riseupvpn? 
Did you seriously put a protection in place? 

### Expected Behavior

that it works?

### Actual Behavior

```
sudo flatpak install im.fluffychat.Fluffychat
Looking for matches…
Found similar ref(s) for ‘im.fluffychat.Fluffychat’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: Y
Required runtime for im.fluffychat.Fluffychat/x86_64/stable (runtime/org.gnome.Platform/x86_64/40) found in remote flathub
Do you want to install it? [Y/n]: Y

im.fluffychat.Fluffychat permissions:
    ipc           network               fallback-x11          pulseaudio              wayland       x11
    devices       file access [1]       dbus access [2]       bus ownership [3]

    [1] xdg-download
    [2] org.freedesktop.Notifications
    [3] chat.fluffy.fluffychat


        ID                                  Branch          Op          Remote           Download
 1. [✗] org.gnome.Platform.Locale           40              i           flathub             1.0 kB / 333.8 MB
 2. [✗] org.gnome.Platform                  40              i           flathub             1.0 kB / 363.9 MB
 3. [ ] im.fluffychat.Fluffychat            stable          i           flathub          < 27.3 MB

Warning: While pulling runtime/org.gnome.Platform.Locale/x86_64/40 from remote flathub: Could not connect: Connection refused
Error: While pulling runtime/org.gnome.Platform/x86_64/40 from remote flathub: Could not connect: Connection refused
error: Failed to install org.gnome.Platform: While pulling runtime/org.gnome.Platform/x86_64/40 from remote flathub: Could not connect: Connection refused

```

```

sudo flatpak install im.fluffychat.Fluffychat
Looking for matches…
Found similar ref(s) for ‘im.fluffychat.Fluffychat’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: Y
error: Unable to load summary from remote flathub: Could not connect: Connection refused
```

### Additional Information

vpn riseup in this case activated

**Comment by mwleeds** [comment]
In general issues with flathub can be reported in this repo: https://github.com/flathub/flathub

Flathub uses a CDN to deliver content and maybe the CDN is blocking some connections from VPNs. You can try circumventing the CDN by changing the URL on the flathub remote to not have the `dl.` part: `flatpak remote-modify --url=https://flathub.org/repo/ flathub`
