### ISSUE TITLE
[Bug]: Can not open URLs from any applications

### ISSUE THREAD

**Issue by daotrunghieu** [flatpak/flatpak#4554]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

5.14.14-300.fc35.x86_64

### What architecture are you using?

x86_64

### How to reproduce

Upgrade from Fedora 34 to Fedora 35. 
Open any Flatpak applications. 
Click URLs in application UI.

### Expected Behavior

The default browser will open the link.

### Actual Behavior

Nothing happened.

### Additional Information

1. Start and enter inside the sandbox:
`$ flatpak run --command=sh <application-id>`
2. Execute application
`[📦 com.example.app ~] $ /bin/app/exe`
3. Click any URLs in application UI.
(nothing happened)
4. Get error in the shell prompt:
`Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop`

**Comment by smcv** [comment]
What desktop environment are you using?

What version of `xdg-desktop-portal` do you have installed on the host?

What version of `xdg-desktop-portal-gtk` do you have installed on the host?

What other xdg-desktop-portal backends (if any) do you have installed on the host?

**Comment by mwleeds** [comment]
Opening URLs from flatpaks works for me, both on F35 Silverblue and F35 Workstation

**Comment by daotrunghieu** [comment]
> What desktop environment are you using?
```
$ echo $XDG_SESSION_TYPE
x11
$ echo $XDG_CURRENT_DESKTOP
i3
```
> What version of xdg-desktop-portal do you have installed on the host?
> What version of xdg-desktop-portal-gtk do you have installed on the host?
> What other xdg-desktop-portal backends (if any) do you have installed on the host?

I'm not sure if this is a correct way to check:
```
$ dnf list installed | grep xdg
xdg-dbus-proxy.x86_64               0.1.2-5.fc35
xdg-desktop-portal.x86_64           1.10.1-1.fc35
xdg-desktop-portal-gtk.x86_64       1.10.0-1.fc35
xdg-user-dirs.x86_64                0.17-9.fc35
xdg-utils.noarch                    1.1.3-10.fc35
```

> Opening URLs from flatpaks works for me, both on F35 Silverblue and F35 Workstation

It's broken after upgrading to F35. My attempt at repairing 
```
$ flatpak --user repair --reinstall-all
```
had no luck. With your said, seems like this issue occurs only in my environment.
Opening URLs in applications (installed outside Flatpak) are fine. And 
```
$ xdg-open https://flathub.org/
```
works.

**Comment by smcv** [comment]
This appears to be because Fedora compiles xdg-desktop-portal-gtk [with the AppChooser feature disabled](https://src.fedoraproject.org/rpms/xdg-desktop-portal-gtk/blob/rawhide/f/xdg-desktop-portal-gtk.spec). You can probably work around this by installing `xdg-desktop-portal-gnome` or `xdg-desktop-portal-kde`.

See also https://github.com/flatpak/xdg-desktop-portal-gtk/issues/120 and https://github.com/flatpak/xdg-desktop-portal-gtk/issues/355.
