### ISSUE TITLE
[Bug]: org.freedesktop.Platform 21.08 does not resolve DNS

### ISSUE THREAD

**Issue by akallabeth** [flatpak/flatpak#4559]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.10.5

### What Linux distribution are you using?

Debian

### Linux distribution version

11

### What architecture are you using?

x86_64

### How to reproduce

`flatpak run --share=network --devel --command=python3 org.freedesktop.Platform/x86_64/21.08 -c 'import socket; print(socket.gethostbyname_ex("github.com"))'`

### Expected Behavior

Resolves host to IP

### Actual Behavior

does not resolve

### Additional Information

`org.freedesktop.Platform/x86_64/21.08` runtime has this issue, but I failed to find a less generic issue tracker for that.

Did first report at wrong place here: https://bugzilla.mozilla.org/show_bug.cgi?id=1739404

**Comment by smcv** [comment]
How is your DNS resolution configured on the host system?

**Comment by akallabeth** [comment]
yes, dhcp by network manager.
resolution works fine when using older versions of the `org.freedesktop.Platform` or local (non flatpak) applications

**Comment by smcv** [comment]
> dhcp by network manager

What does this mean, specifically? There are lots of ways DNS can be set up.

What's in `/etc/nsswitch.conf` on the host?

What's in `/etc/resolv.conf` on the host?

If `/etc/resolv.conf` is a symbolic link, what file does it point to and what is in that file?

**Comment by akallabeth** [comment]
`/etc/nsswitch.conf`
```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files systemd
group:          files systemd
shadow:         files
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns mdns4 wins myhostname mymachines
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

`/etc/resolv.conf` 
```
# Generated by NetworkManager
search md.thincast.com lan
nameserver 192.168.50.2
nameserver 192.168.50.4
nameserver 192.168.1.1
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver fd2c:c159:f568:0:c66e:1fff:fe73:4406
```

```
ls -lah /etc/resolv.conf 
-rw-r--r-- 1 root root 297 Nov 10 07:46 /etc/resolv.conf
```

**Comment by akallabeth** [comment]
I´ve tried this now also on freshly set up `debian 11` and `ubuntu 20.04` VM
both have the same issue, so this does not seem to be limited to my machine.

**Comment by akallabeth** [comment]
ok, figured it out.
The runtime ignores the host `DNS` configurations and tries to use `systemd-resolved`.
That one was not configured and could not resolve anything so everything using this runtime failed miserably.

Installed and fixed `systemd-resolved` (e.g. `libnss-resolve`) now also the runtime can resolve `DNS` again.

**Comment by mwleeds** [comment]
If this is an issue in the runtime, the right place to report it would be https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by nanonyme** [comment]
Here's the sandbox nsswitch.conf. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/files/nsswitch-flatpak.conf
It has fallback for systemd-resolved enabled

**Comment by nanonyme** [comment]
I completely fail to reproduce this. Runtime falls back to /etc/resolv.conf in absence of file `/run/systemd/resolve/io.systemd.Resolve` as expected.

**Comment by akallabeth** [comment]
that is indeed strange. I´ll try to reproduce with a fresh vm tonight, maybe I can find the part missing in the initial description.

**Comment by mcatanzaro** [comment]
So after reading through this issue report, it sounds like the systemd provided by the runtime is misbehaving. I don't think there is any flatpak bug here. You already reported this at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1351 which was good, so this issue can be closed now.

**Comment by nanonyme** [comment]
Note that this is for quite old version of the runtime. I don't remember whether or not the varlink setup was in fact in use with that.

**Comment by akallabeth** [comment]
ok, no longer using that runtime and as already pointed out looks like an upstream bug.
