### ISSUE TITLE
[Bug]: Slow opening some applications

### ISSUE THREAD

**Issue by bupy7** [flatpak/flatpak#4565]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [ ] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.10.5

### What Linux distribution are you using?

Debian

### Linux distribution version

11 Bullseye (5.10.70-1 kernel version)

### What architecture are you using?

x86_64

### How to reproduce

1) install flatpak

2) install any flatpak app

3) reboot pc

4) run mousepad (for example)

5) wait for start up about a few minute

### Expected Behavior

No any delay to starting up app.

### Actual Behavior

Delay when I try to start up any app.

### Additional Information

The same problem: https://forum.level1techs.com/t/gtk-applications-are-super-slow-at-startup/166540/4

I had to remove Flatpak and all its dependencies to solve my problem.

**Comment by mwleeds** [comment]
I doubt you are using Debian 5 as that is from 2012?

> The same problem: https://forum.level1techs.com/t/gtk-applications-are-super-slow-at-startup/166540/4

I would not recommend removing xdg-dbus-proxy as they suggest there. It is a required component of Flatpak.

**Comment by bupy7** [comment]
Do you have any advice to solve that problem?

**Comment by mwleeds** [comment]
There is not enough information here to debug what's going on. Possibly checking the output from apps launched from a Terminal or monitoring the session D-Bus with a tool like Bustle could give some useful information.

**Comment by bupy7** [comment]
Ok, as soon as possible I will check it and give you log.

**Comment by bupy7** [comment]
@239 I had problem not only with app installed from FlatPak. Even Mousepad had been slowly.

**Comment by bupy7** [comment]
I had again installed Flatpack.

```bash
mazafaka@vb-debian-11:~$ sudo apt install flatpak
```

After it, I had tried to start Mousepad and waiting 30 seconds. Mousepad hadn't any output.

Next, I had tried run Telegram. It's an official build from https://desktop.telegram.org/. I had been waiting for 2 minutes approximately. Here we have output:

```bash
mazafaka@vb-debian-11:~$ telegram
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
```

and Telegram log from file where is:

```
[2022.04.10 04:20:55] XDP File Dialog Error: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)
```

**Comment by bupy7** [comment]
The similar problem: https://github.com/telegramdesktop/tdesktop/issues/23896

**Comment by smcv** [comment]
@bupy7: On Debian systems, `/etc/X11/Xsession.d/20dbus_xdg-runtime` from the dbus-user-session package and/or /etc/X11/Xsession.d/95dbus_update-activation-env from the dbus-x11 package should be doing that for you. xdg-desktop-portal and xdg-desktop-portal-gtk both depend on either dbus-user-session or dbus-x11.

**Comment by bupy7** [comment]
@smcv, I have `/etc/X11/Xsession.d/20dbus_xdg-runtime` only. Should I run its from `.xinitrc` instead of `dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY`?

**Comment by bupy7** [comment]
Additionally, I found [this articlel](https://momi.ca/posts/2021-10-11-startxdebian.htm) I understood I rewrote `/etc/X11/xinit/xinitrc` by `~/.xinitrc` where has run `/etc/X11/Xsession` that has run the scripts from `/etc/X11/Xsession.d/*`. Therefore, I just have moved `~/.xinitrc` to `~/.xsessionrc`, dropped the line `dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY`, that I added before, and everything is working perfectly!

Thanks a lot @smcv ! This was my fault.

**Comment by smcv** [comment]
Closing this as system misconfiguration.
