### ISSUE TITLE
[Bug]: 32-bit binaries no longer run when starting Flatpak with --devel

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak#4573]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

1. Use a Flatpak that uses 32-bit runtime extension and contains some 32-bit binaries inside (for example Steam from Flathub with native games with 32-bit binaries installed).
2. Run `flatpak run --devel --command=sh org.foo.App`.
3. Switch (`cd`) to a directory with 32-bit binary.
4. `file ./binary` # to confirm that the binary is 32-bit
5. `./binary`

### Expected Behavior

Binary runs fine.

### Actual Behavior

```
$ file System/ut-bin
System/ut-bin: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=5b058463aafb486e6fa9dabf36254a0f0ea348a2, stripped

$ ./System/ut-bin
sh: ./System/ut-bin: No such file or directory
```

### Additional Information

The same binary runs fine when starting the Flatpak without `--devel`.

**Comment by refi64** [comment]
This is [an issue in the fd.o SDK](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1056) that can't easily be fixed:

> Yes, `/usr/lib/i386-linux-gnu` is the mount point for the `org.freedesktop.Sdk.Compat.i386` extension. Making `/usr/lib/i386-linux-gnu` a symlink to `/app` would make cross-compiling on freedesktop-sdk impossible.

If you need to run debugging system calls, use `--allow=devel` instead, which is like `-d` but doesn't change the runtime to point to the SDK.

**Comment by AsciiWolf** [comment]
Ah, thanks for the info!
