### ISSUE TITLE
Provide features for a local rebuild of packages/apps

### ISSUE THREAD

**Issue by dmedri** [flatpak/flatpak#459]
*BSD users know how to update and build packages using Ports.
Gentoo Linux has it's own buildsystem (Portage) quite close to the above example.
Debian also has its own way to rebuild .deb packages.

Are there Flatpack planned features to:
- download locally app source code (if available);
- rebuild locally an app (if source code and dependencies are available);
- rebuild locally an app and its dependencies (with a non-reduntant approach);
- rebuild locally all apps installed in your own system.

**Comment by TingPing** [comment]
Flatpak isn't intended to replace ports at all. That said you can easily grab the manifest file of an application and rebuild it with `flatpak-builder` but that doesn't really scale up.

**Comment by matthiasclasen** [comment]
I think you'll see some nice integration of this soon, with a context menu item in gnome shell that lets you open an installed app in gnome-builder, make changes, wrap it up in a flatpak, and share it with your friends. I know some people are working on this.

**Comment by dmedri** [comment]
IMHO
- "soon" or short-term is =< 1.0 release. The above features should be evaluated in long-term;
- the right place to expose these actions is CLI.
