### ISSUE TITLE
[Bug]: --env doesn't expand $HOME

### ISSUE THREAD

**Issue by hfiguiere** [flatpak/flatpak#4596]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

1. set --env=LV2_PATH=$HOME/.lv2 with flatseal or in the manifest `finish-args`
2. run the flatpak with `--command=sh`
3. type `env`
4. `LV2_PATH` still contain the literal `$HOME`

alternative: use `~`. Same.

### Expected Behavior

`$HOME` be expanded as expected.

### Actual Behavior

`$HOME` is verbatim into the environment

### Additional Information

The environment has to be set to point the user directory. There is no way to do that.

**Comment by smcv** [comment]
This is working as designed: the argument to `--env` in manifest `finish-args` is a literal string that does not undergo any sort of variable expansion or other transformation. The ability to set environment variables to values that contain the expansion of other environment variables would be a new feature.

**Comment by smcv** [comment]
Changing the semantics of the arguments in `finish-args` so that they expanded variables would technically be an incompatible change: it would change the meaning of any argument that contains a literal `$`.

**Comment by tinywrkb** [comment]
Is there maybe a proper target to bind mount home as done with the xdg-dirs onto `/var/{cache,config,data}`?  
IIRC `/var/home` is used by Fedora already, or at least Silverblue, so what about `/var/homedir`?

**Comment by hfiguiere** [comment]
It's not `/var/home` I'm interested in. It's `$HOME` with a value that actually resolve so that the app can use it. But I guess I'm gonna have to go with a hackery that cost more time in maintenance...

**Comment by smcv** [comment]
I think this would need a new option, `--env-expand` or something (and we'd need to define what the semantics are if environment variables refer to each other recursively).

The most useful semantics would probably be to apply `--env-expand` *last*, after setting up all the variables that are special-cased by Flatpak itself?

**Comment by hfiguiere** [comment]
in any case this hackery has to been done, because by the time flatpak has been updated to the right version, we'll be all on a different problem.

**Comment by hfiguiere** [comment]
in case, I already did it for Ardour. One done, many to go.

**Comment by hfiguiere** [comment]
ok then. WONTIFX
