### ISSUE TITLE
Change appstream metainfo export directory

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#4599]
> @alexlarsson Is it possible to change the directory default to share/metainfo? The share/appdata directory is deprecated for ages, and AppStream will completely remove support for it with the 1.0 release (and some newer code doesn't even read it anymore today already).

-- @ximion in https://github.com/flatpak/flatpak/pull/4350#issuecomment-974889512

**Comment by ximion** [comment]
Thank you for creating the proper issue report! :-)
