### ISSUE TITLE
Could use a better directory for app's home

### ISSUE THREAD

**Issue by cosimoc** [flatpak/flatpak#46]
Currently flatpak uses `$HOME/.var/` as toplevel directory to keep all the "home dirs" of applications. `$HOME/.var` is not a great choice though, since it does not follow the XDG directory scheme, and we've been trying to avoid toplevel dot directories in the home for a while.

Any reason not to use something inside `~/.local/share/flatpak` instead?

**Comment by alexlarsson** [comment]
There was a long discussion with desrt about this. I forgot the details though.

**Comment by alexlarsson** [comment]
I think .var is fine, and its imho too late to change now.

**Comment by ZerdoX-x** [comment]
Awful. This is one of the reasons why I forced to refuse from flatpak

**Comment by Fogapod** [comment]
It's never too late. At least ad an option to customize this behaviour

**Comment by Baerbeisser** [comment]
> I think .var is fine

Not for me. How do i change this?

> and its imho too late to change now.

Why?

Because of this (191)?

> The ~/.var/app location for per-application data as reached after a long discussion, including with some of the developers of the xdg basedir spec. We never got to updating the spec for this, but that will happen eventually.

Main advantage of the xdg basedir spec is the possibility *to change places with a simple environment variable*.

I didn't look in the sourcecode so far, don't tell me you have `.var` hardcoded in 100 different places?!

**Comment by offsetcyan** [comment]
> I think .var is fine, and its imho too late to change now.

This is software. We can always work to improve it.
