### ISSUE TITLE
updating standalone bundle fails

### ISSUE THREAD

**Issue by jscurtu** [flatpak/flatpak#462]
When I try to update a bundle (flatpak file) while using "flatpak install --bundle" I get the error.

`Error: org.gnome.feedreader/x86_64/master already installed`

What is the correct way to update a bundle or what is necessary in the json to create a bundle that can update?
Is it possible that this is not implemented yet.. 

Flatpak version:
0.8.0

**Comment by alexlarsson** [comment]
That should work, unless we regressed on this (which is possible, the bundle install codepath changed recently). Are you sure the bundle actually is newer? If not, it will give an error like that.

**Comment by jscurtu** [comment]
Pretty much sure they are newer, ive been building them the last few days while learning the whole flatpak process.. which is awsoem btw.
