### ISSUE TITLE
[Bug]: X11 Bad Alloc when running flatpaks 

### ISSUE THREAD

**Issue by Jacalz** [flatpak/flatpak#4629]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

Fedora 35 with Gnome 41.2: 5.15.8-200.fc35.x86_64 #1 SMP

### What architecture are you using?

x86_64

## Getting the code
I suggest building and installing https://github.com/fyne-io/flatpak_demo locally, but the same is seen with https://github.com/Jacalz/wormhole-gui/issues/23 as well.

## On wayland
1. Run any Fyne flatpak.
2. Notice that there is an X error and that the application doesn't start.

## On X11
1. Run any Fyne flatpak.
2. The application works.

### Expected Behavior

The applications should work just as well on Wayland (though XWayland) as they do on X11. This used to be the case up until a few days, or possibly a week, ago.

### Actual Behavior

Whenever I use the wayland session and launch a Fyne application, I get this error:
```
[jacob@workstation ~]$ flatpak run io.github.jacalz.wormhole_gui 
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  147 ()
  Minor opcode of failed request:  7
  Serial number of failed request:  225
  Current serial number in output stream:  228
```

### Additional Information

This used to work but I think this might have been broken by one of the latest updates to the FreeDesktop runtime. I did do a Fedora update at the same time, but given that I can run these Fyne apps more than good enough locally outside of flatpak, I think it is an issue here. I can only replicate this with Fyne apps but I have used them in flatpak for a while now and this just started to occur recently. It is strange though that it only seems to happen to these Fyne apps. Sorry if I opened this in the wrong place.

**Comment by shoop** [comment]
I see the same for PrusaSlicer on Silverblue 35, reported as flathub/com.prusa3d.Prusaslicer/#41 .

**Comment by Jacalz** [comment]
I just tested this again today on a fresh reinstall of Fedora 35 and the issue is still there.

**Comment by Jacalz** [comment]
I found an interesting thing here though. It seems to not reproduce on Wayland when running on KDE Plasma. I'm starting to wonder if this perhaps could be an issue with Gnome and their XWayland code.

**Comment by Jacalz** [comment]
I’ll close this as it might be an issue some there else. The graphics card has been getting worse and worse lately. KDE didn’t even remotely work and things crash randomly. Either the graphics card is braking down or the graphics drivers are working badly with newer kernels.
