### ISSUE TITLE
the Flatpak remote for nightly graphics apps at 209.132.179.2/ is unreachable

### ISSUE THREAD

**Issue by skierpage** [flatpak/flatpak#465]
http://flatpak.org/apps.html#nightly-graphics says
> To add the nightly-graphics repository, run:
> ```flatpak remote-add --from nightly-graphics http://209.132.179.2/nightly-graphics.flatpakrepo```

but I'm getting
```
Can't load uri http://209.132.179.2/nightly-graphics.flatpakrepo: Could not connect: No route to host
```
Is there a better URL (a domain name that supports https) for nightly graphics apps yet? Thanks!

**Comment by alexlarsson** [comment]
Should be up again

**Comment by feeef** [comment]
It seems to have been unreachable for some time again. Have the nightly-graphics apps been permanently removed, or did the server changed? Does it have a domain now?

I'd like to install gimp 2.9.

Thanks!

**Comment by skierpage** [comment]
@feeef Commenting on a closed issue may not get a response. I don't see a way to reopen a closed issue.

**Comment by feeef** [comment]
It has been closed but not fixed in some way so I just didn't want to open a duplicate issue. It is why I commented here, I am sorry if it wasn't the right thing to do. 

I have noticed there is another related issue. I am going to comment on that one.

Cheers anyway!
