### ISSUE TITLE
[Feature request]: kimageformats package for KDE apps

### ISSUE THREAD

**Issue by arun54321** [flatpak/flatpak#4652]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Image formats like avif, heic and jxl doesn't work on KDE apps like dolphin and gwenview as they depend on package  kimageformats.

**Comment by mwleeds** [comment]
This doesn't seem like a bug in Flatpak. It sounds like those KDE apps should include the appropriate package in their Flatpak manifests and that would solve the problem. Perhaps the bug should be reported on those apps, e.g. at https://github.com/flathub/org.kde.dolphin/issues?
