### ISSUE TITLE
[Feature request]: Allow an application to publicize its minimum requirements

### ISSUE THREAD

**Issue by Mek101** [flatpak/flatpak#4655]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

An application should be able to advertise to the user its minimum hardware requirements to run properly, this should be especially important with big applications like Android Studio or Eclipse

**Comment by mwleeds** [comment]
Applications can already specify hardware requirements such as amount of memory required in their metainfo: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-relations-memory

Presenting that information to the user is the job of each software center like GNOME Software, but there is an argument to be made that the Flatpak CLI should also present such requirements to the user when they're available. Is that what you're asking for?
