### ISSUE TITLE
[Bug]: Automatic response to solicitation of response by Flatpak subsequent to invocation of "Start-Transcript -Append -NoClobber -IncludeInvocationHeader" via the consequence of compilation of "http://github.com/PowerShell/PowerShell".

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flatpak/flatpak#4657]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

Linux fedora 5.15.12-200.fc35.x86_64 #1 SMP Wed Dec 29 15:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1stly, have invoked "pwsh -NOEXIT -COMMAND "START-TRANSCRIPT -APPEND -NOCLOBBER -INCLUDEINVOCATIONHEADER"".
2ndly, have invoked "flatpak".

### Expected Behavior

Solicitation of response by "/usr/bin/flatpak" after invocation of "START-TRANSCRIPT -APPEND -NOCLOBBER -INCLUDEINVOCATIONHEADER" via "/opt/microsoft/powershell/7/pwsh" without automatic response.

PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /> START-TRANSCRIPT -APPEND -NOCLOBBER -INCLUDEINVOCATIONHEADER
Transcript started, output file is /home/BEEDELLROKEJULIANLOCKHART/PowerShell_transcript.fedora.dyCrnPp8.20220108184543.txt
PS /> flatpak --verbose -vv --ostree-verbose install --installation=default --or-update org.kde.dolphin.Debug
F: Opening system flatpak installation at path /var/lib/flatpak
Looking for matches?
F: Calling system helper: GenerateOciSummary
F: Fetching summary index file for remote ?flathub?
F: Loading https://dl.flathub.org/repo/summary.idx using libsoup
F: Received 2737 bytes
F: Loaded indexed summary file 8bc8f01224e2e3c231e4d0a601f67c33ea14e9c37d5fffe4cddf003a1f777a92 from cache for remote ?flathub?
F: Fetching summary index file for remote ?flathub-beta?
F: Loading https://dl.flathub.org/beta-repo/summary.idx using libsoup
F: Received 2687 bytes
F: Loaded indexed summary file 09a8b88597bca5ff9eae28b03a3eb60114eeb74d2675306210787d80a3743835 from cache for remote ?flathub-beta?
F: Fetching summary index file for remote ?gnome-nightly?
F: Loading https://nightly.gnome.org/repo/summary.idx using libsoup
F: Received 3293 bytes
F: Loaded indexed summary file 5f0a42527b4bd4869f78981a0e389bfb7681babd8bf7691028f7e1e2d6436959 from cache for remote ?gnome-nightly?
F: Fetching summary index file for remote ?kdeapps?
F: Loading http://distribute.kde.org/flatpak-apps-testing/summary.idx using libsoup
F: Received 910 bytes
F: Loaded indexed summary file 8148ce7400b4b6b2a0acb2f782045623b706f9540118a87e73ed1de96766faa0 from cache for remote ?kdeapps?
F: Fetching summary index file for remote ?org.mozilla.FirefoxRepo?
F: Loading https://firefox-flatpak.mojefedora.cz/repo/summary.idx using libsoup
F: Fetching summary file for remote ?org.mozilla.FirefoxRepo?
F: Adding GPG keyring data from org.mozilla.FirefoxRepo.trustedkeys.gpg to verifier
F: GnuPG >= 2.1.17, skipping gpg-agent cleanup in /tmp/ostree-gpg-SmcmNw
F: Fetching summary index file for remote ?winepak?
F: Loading http://dl.winepak.org/repo/summary.idx using libsoup
F: Fetching summary file for remote ?winepak?
F: Adding GPG keyring data from winepak.trustedkeys.gpg to verifier
F: GnuPG >= 2.1.17, skipping gpg-agent cleanup in /tmp/ostree-gpg-4JV21w
F: Failed to download optional summary: Signature made Fri Jul 20 02:30:34 2018 using RSA key ID A959831C080B608F
BAD signature from " <julian@richen.io>"
Key expired Tue Jun  9 18:16:34 2020
F: An error was encountered searching remote ?winepak? for ?org.kde.dolphin.Debug?: Unable to load summary from remote winepak: Signature made Fri Jul 20 02:30:34 2018 using RSA key ID A959831C080B608F
BAD signature from " <julian@richen.io>"
Key expired Tue Jun  9 18:16:34 2020
Remotes found with refs similar to ?org.kde.dolphin.Debug?:

   1) ?flathub? (system)
   2) ?kdeapps? (system)

Which do you want to use (0 to abort)? [0-2]: 

### Actual Behavior

Automatic response to solicitation of response by "/usr/bin/flatpak" after invocation of "START-TRANSCRIPT -APPEND -NOCLOBBER -INCLUDEINVOCATIONHEADER" via "/opt/microsoft/powershell/7/pwsh".

PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /> START-TRANSCRIPT -APPEND -NOCLOBBER -INCLUDEINVOCATIONHEADER
Transcript started, output file is /home/BEEDELLROKEJULIANLOCKHART/PowerShell_transcript.fedora.93cQk7oR.20220108184213.txt
PS /> flatpak --verbose -vv --ostree-verbose install --installation=default --or-update org.kde.dolphin.Debug
Looking for matches?
F: Opening system flatpak installation at path /var/lib/flatpak
F: Calling system helper: GenerateOciSummary
F: Fetching summary index file for remote ?flathub?
F: Loading https://dl.flathub.org/repo/summary.idx using libsoup
F: Received 2737 bytes
F: Loaded indexed summary file 8bc8f01224e2e3c231e4d0a601f67c33ea14e9c37d5fffe4cddf003a1f777a92 from cache for remote ?flathub?
F: Fetching summary index file for remote ?flathub-beta?
F: Loading https://dl.flathub.org/beta-repo/summary.idx using libsoup
F: Received 2687 bytes
F: Loaded indexed summary file 09a8b88597bca5ff9eae28b03a3eb60114eeb74d2675306210787d80a3743835 from cache for remote ?flathub-beta?
F: Fetching summary index file for remote ?gnome-nightly?
F: Loading https://nightly.gnome.org/repo/summary.idx using libsoup
F: Received 3293 bytes
F: Loaded indexed summary file 5f0a42527b4bd4869f78981a0e389bfb7681babd8bf7691028f7e1e2d6436959 from cache for remote ?gnome-nightly?
F: Fetching summary index file for remote ?kdeapps?
F: Loading http://distribute.kde.org/flatpak-apps-testing/summary.idx using libsoup
F: Received 910 bytes
F: Loaded indexed summary file 8148ce7400b4b6b2a0acb2f782045623b706f9540118a87e73ed1de96766faa0 from cache for remote ?kdeapps?
F: Fetching summary index file for remote ?org.mozilla.FirefoxRepo?
F: Loading https://firefox-flatpak.mojefedora.cz/repo/summary.idx using libsoup
F: Fetching summary file for remote ?org.mozilla.FirefoxRepo?
F: Adding GPG keyring data from org.mozilla.FirefoxRepo.trustedkeys.gpg to verifier
F: GnuPG >= 2.1.17, skipping gpg-agent cleanup in /tmp/ostree-gpg-ayujjz
F: Fetching summary index file for remote ?winepak?
F: Loading http://dl.winepak.org/repo/summary.idx using libsoup
F: Fetching summary file for remote ?winepak?
F: Adding GPG keyring data from winepak.trustedkeys.gpg to verifier
F: GnuPG >= 2.1.17, skipping gpg-agent cleanup in /tmp/ostree-gpg-RuicLF
F: Failed to download optional summary: Signature made Fri Jul 20 02:30:34 2018 using RSA key ID A959831C080B608F
BAD signature from " <julian@richen.io>"
Key expired Tue Jun  9 18:16:34 2020
F: An error was encountered searching remote ?winepak? for ?org.kde.dolphin.Debug?: Unable to load summary from remote winepak: Signature made Fri Jul 20 02:30:34 2018 using RSA key ID A959831C080B608F
BAD signature from " <julian@richen.io>"
Key expired Tue Jun  9 18:16:34 2020
Remotes found with refs similar to ?org.kde.dolphin.Debug?:

   1) ?flathub? (system)
   2) ?kdeapps? (system)

Which do you want to use (0 to abort)? [0-2]: 0
error: No remote chosen to resolve matches for ?org.kde.dolphin.Debug?
PS />

**Comment by beedell-roke** [comment]
> https://github.com/flatpak/flatpak/issues/4657#issue-1097382578

This report has been transferred to https://github.com/PowerShell/PowerShell/issues/16717#issue-1097006618.
