### ISSUE TITLE
[Feature request]: flatpak install flathub <appname>

### ISSUE THREAD

**Issue by Mr-Bajs** [flatpak/flatpak#4658]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

To install in the terminal from flathub you enter something like 

_flatpak install flathub com.spotify.Client_

The _com.spotify.Client_ isn't that great from a user standpoint if you compare to the _sudo apt install spotify_. 

Why this choice and is there any plans to change this to a more intuitive style more in the terms like _sudo flatpak install flathub spotify_ in the long term?

Sure there is _flatpak search_ and the web based installation. I just find this thing a little anoying as a user.

Edit: maybe this is a flathub not a flatpak issue

**Comment by smcv** [comment]
App names are not globally unique, and Flatpak repositories do not attempt to guarantee that there is only one app with a particular short name. When non-Flatpak distributions like Debian and Fedora try to package all known apps with a short name, we quite regularly get conflicts  (for example the Node Javascript framework vs. the Node ham radio tool, the Chromium browser vs. the Chromium vertically-scrolling shooter game, and the git version control system vs. GNU Interactive Tools; in each pair, the first one is more popular, but the second one had taken the obvious name in Debian already).

In all recent-ish versions (since 0.6.9 if I'm reading NEWS correctly), if you give only part of the name, the Flatpak CLI will look for similar names and ask which one you meant:

```
$ flatpak install flathub spotify
Found ref ‘app/com.spotify.Client/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: 

$ flatpak install flathub steam
Looking for matches…
Similar refs found for ‘steam’ in remote ‘flathub’ (system):

   1) app/org.rolisteam.rolisteam/x86_64/stable
   2) runtime/com.valvesoftware.Steam.CompatibilityTool.Boxtron/x86_64/stable
   3) runtime/com.valvesoftware.Steam.CompatibilityTool.Proton/x86_64/stable
   4) runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable
   5) runtime/com.valvesoftware.Steam.Utility.protontricks/x86_64/stable
   6) app/com.valvesoftware.SteamLink/x86_64/stable
   7) runtime/com.valvesoftware.Steam.Utility.MangoHud/x86_64/stable
   8) runtime/com.valvesoftware.Steam.Utility.vkBasalt/x86_64/stable
   9) runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-Exp/x86_64/stable
  10) runtime/com.valvesoftware.Steam.Utility.gamescope/x86_64/stable
  11) app/com.github.dariasteam.cowsrevenge/x86_64/stable
  12) app/com.valvesoftware.Steam/x86_64/stable
  13) runtime/com.valvesoftware.Steam.VulkanLayer.MangoHud/x86_64/stable

Which do you want to use (0 to abort)? [0-13]: 
```

Alternatively, use a GUI like GNOME Software or KDE Discover. The `flatpak(1)` CLI is not intended to be the only user interface for installing and managing Flatpak apps.

**Comment by mwleeds** [comment]
Seems like a feature request for a feature we already have. See also #1258

**Comment by Mr-Bajs** [comment]
> App names are not globally unique, and Flatpak repositories do not attempt to guarantee that there is only one app with a particular short name. When non-Flatpak distributions like Debian and Fedora try to package all known apps with a short name, we quite regularly get conflicts (for example the Node Javascript framework vs. the Node ham radio tool, the Chromium browser vs. the Chromium vertically-scrolling shooter game, and the git version control system vs. GNU Interactive Tools; in each pair, the first one is more popular recently, but the second one had taken the obvious name in Debian already).
> 
> In all recent-ish versions (since 0.6.9 if I'm reading NEWS correctly), if you give only part of the name, the Flatpak CLI will look for similar names and ask which one you meant:
> 
> ```
> $ flatpak install flathub spotify
> Found ref ‘app/com.spotify.Client/x86_64/stable’ in remote ‘flathub’ (system).
> Use this ref? [Y/n]: 
> 
> $ flatpak install flathub steam
> Looking for matches…
> Similar refs found for ‘steam’ in remote ‘flathub’ (system):
> 
>    1) app/org.rolisteam.rolisteam/x86_64/stable
>    2) runtime/com.valvesoftware.Steam.CompatibilityTool.Boxtron/x86_64/stable
>    3) runtime/com.valvesoftware.Steam.CompatibilityTool.Proton/x86_64/stable
>    4) runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable
>    5) runtime/com.valvesoftware.Steam.Utility.protontricks/x86_64/stable
>    6) app/com.valvesoftware.SteamLink/x86_64/stable
>    7) runtime/com.valvesoftware.Steam.Utility.MangoHud/x86_64/stable
>    8) runtime/com.valvesoftware.Steam.Utility.vkBasalt/x86_64/stable
>    9) runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-Exp/x86_64/stable
>   10) runtime/com.valvesoftware.Steam.Utility.gamescope/x86_64/stable
>   11) app/com.github.dariasteam.cowsrevenge/x86_64/stable
>   12) app/com.valvesoftware.Steam/x86_64/stable
>   13) runtime/com.valvesoftware.Steam.VulkanLayer.MangoHud/x86_64/stable
> 
> Which do you want to use (0 to abort)? [0-13]: 
> ```
> 
> Alternatively, use a GUI like GNOME Software or KDE Discover. The `flatpak(1)` CLI is not intended to be the only user interface for installing and managing Flatpak apps.

Oh, don't know about the found ref feature. That's great. Thanks for the info.
