### ISSUE TITLE
Exports are not automatically linked into the XDG directories

### ISSUE THREAD

**Issue by TheRealCuran** [flatpak/flatpak#466]
I've installed Skype through Flatpak (0.8.0-1) and noticed, that the `.deskop` file for it was apparently not picked up by the system/desktop environment (KDE 5 as in Debian Testing). The problem seems to be, that Flatpak only links its exports to `~/.local/share/flatpak/exports` and not – where appropriate – into the relevant XDG directories, which are part of the default search paths.

For example: `com.skype.Client.desktop` is linked to `~/.local/share/flatpak/exports/share/applications/com.skype.Client.desktop` but not `~/.local/share/applications` where KDE and shell auto-completion would pick it up.
While I can [add another directory to the search paths](https://userbase.kde.org/KDE_System_Administration/KDE_Filesystem_Hierarchy), I would find it preferable, if these files would be linked into the XDG directories, if no file of a similar name already exists (just to prevent accidental replacements). Bonus points, if Flatpak cleans those links up again, when the application is uninstalled.

**Comment by TheRealCuran** [comment]
Sorry for the noise, needed a relogin for the Skype to show up in KRunner. Maybe this should be added to the documentation prominently (including the flatpak-run man page)

**Comment by bam80** [comment]
Plasma 5 at least should pick it up immediately, without relogin
