### ISSUE TITLE
[Bug]: linker does not see libraries in /app/lib at runtime

### ISSUE THREAD

**Issue by Ratevandr** [flatpak/flatpak#4685]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/master/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.5

### What Linux distribution are you using?

Debian

### Linux distribution version

11 (bullseye)

### What architecture are you using?

x86_64

### How to reproduce

1. Build flatpak https://github.com/Ratevandr/gtkmmRuntimeBuildFlatpak org.ratevandr.gtkmmInFlatpak-IDE.json
2. Run app

### Expected Behavior

App is linking correctly

### Actual Behavior

Getting an error
```
Consolidate compiler generated dependencies of target gtkmmInFlatpak
[ 50%] Linking CXX executable gtkmmInFlatpak
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lgtkmm-3.0
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -latkmm-1.6
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lgdkmm-3.0
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lgiomm-2.4
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lpangomm-1.4
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lglibmm-2.4
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lcairomm-1.0
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lsigc-2.0
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gtkmmInFlatpak.dir/build.make:97: gtkmmInFlatpak] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gtkmmInFlatpak.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

### Additional Information

I want to build an IDE that takes libraries from the flatpack itself. I need this for testing and developing apps for flatpack.
The link to the repository above shows that the application (org.ratevandr.gtkmmInFlatpak.json) is built correctly in the flatpack itself, but I need to do this in runtime.
I try added "--env=LD_LIBRARY_PATH=/app/lib:/app/lib/x86_64-linux-gnu" to manifest, and 
```
       {
            "name": "setup-ld",
            "buildsystem": "simple",
            "build-commands": [
                "install -Dm644 ld.so.conf /app/etc/ld.so.conf"
            ],
            "sources": [
                {
                    "type": "file",
                    "dest-filename": "ld.so.conf",
                    "url": "data:/app/lib/"
                }
            ]
        }
```
but it did not help.
Is this a bug or can I fix it myself somehow?

**Comment by ssokolow** [comment]
I haven't tried `--env`, because that looks like something a user could break using Flatseal, but this wrapper script worked for getting my custom build of SDL_mixer to see its `libmodplug.so`:

```json
        {
            "type": "script",
            "commands": [
                "# Workaround for 'flatpak run' not setting LD_LIBRARY_PATH=/app/lib",
                "# and SDL_mixer needing that to find /app/lib/libmodplug.so*",
                "",
                "export LD_LIBRARY_PATH='/app/lib:$LD_LIBRARY_PATH'",
                "pysol.py \"$@\""
            ],
            "dest-filename": "pysol"
        }
```

**Comment by hfiguiere** [comment]
Your manifest change the PKG_CONFIG_PATH and LD_LIBRARY_PATH for no reason. Many app build with gtkmm in flatpak.

Not a flatpak bug anyway.
