### ISSUE TITLE
ffmpeg doesn't work in the gnome runtime

### ISSUE THREAD

**Issue by ltiber** [flatpak/flatpak#4688]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/master/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.0.9

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

18.04

### What architecture are you using?

x86_64

### How to reproduce

I try to package my software to a flatpak environment.
My software use ffmpeg facilities to capture frames from video files.
All my spawned commands running ffmpeg failed with the error "Unable to find a suitable output format for ..."
To troubleshoot, I've run very simple ffmpeg command in the flatpak shell (flatpak run --command=sh --devel org.myapp.Myapp) with the same error.
Here is a simple command that failed
ffmpeg -i 20211222_190005.mp4 -ss 00:00:01.000 -vframes 1 output.png
Unable to find a suitable output format for 'output.png'
output.png: Invalid argument
I add that these simple commands work fine in my ubuntu system.
The flatpak runtime that I use is org.gnome.Platform version 3.24

### Expected Behavior

Accept running ffmpeg command with the g_spawn_command_line_sync function coming from Glib C library.
I use the permission --filesystem=host
And other spawn command work perfectly

### Actual Behavior

I always have the same error "Unable to find a suitable output format for"
It seems that the ffmpeg command doesn't work properly in the flatpak environment.
ffmpeg belongs to the org.gnome.Plateform.
I use the permission --filesystem=host
And other spawn commands work perfectly in the software under flatpak environment

**Comment by mwleeds** [comment]
Hi, you can report issues with the GNOME runtime here: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues

**Comment by ltiber** [comment]
I've entered this issue in gnome https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/473

**Comment by Erick555** [comment]
1. ffmpeg is handled at https://gitlab.com/freedesktop-sdk/freedesktop-sdk not in gnome repo.
2. gnome 3.24 (and coresponding freedesktop-sdk) was abandoned long time ago: `End-of-life: GNOME 3.24 runtime is no longer supported as of 11th January 2019` so there is no chance to help. You need to try with some modern runtime like gnome 41 and report to freedesktop-sdk if you still encounter problem.
