### ISSUE TITLE
Builder can't strip created .so file

### ISSUE THREAD

**Issue by RomanKharin** [flatpak/flatpak#469]
Trying to create manifest fo building tcl (and tk) with flatpak-builder.
```
{
    "id": "tk.tcl.Platform",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "1.4",
    "sdk": "org.freedesktop.Sdk",
    "writable-sdk": false,
    "branch": "8.6.6",
    "build-runtime": false,
    "modules": [
        {
            "name": "tcl8.6",
            "sources": [
                {
                    "type": "archive",
                    "url": "http://prdownloads.sourceforge.net/tcl/tcl8.6.6-src.tar.gz",
                    "sha256": "a265409781e4b3edcc4ef822533071b34c3dc6790b893963809b9fe221befe07"
                }
            ],
            "subdir": "unix",
            "build-options" : {
                "no-debuginfo": false
            }
        }
    ]
}
```
But builder fails at later stages after `make install` phase
```
stripping /path/to/build/files/bin/tclsh8.6 to /path/to/build/files/lib/debug/bin/tclsh8.6.debug
stripping /path/to/build/files/lib/itcl4.0.5/libitcl4.0.5.so to /path/to/build/files/lib/debug/lib/itcl4.0.5/libitcl4.0.5.so.debug
stripping /path/to/build/files/lib/libtcl8.6.so to /path/to/build/files/lib/debug/lib/libtcl8.6.so.debug
eu-strip: while opening '/path/to/build/files/lib/libtcl8.6.so': Permission denied
Error: module tcl8.6: Child process exited with code 1
```
This can be avoided only with `"no-debuginfo": false`, but stripping would be nice.

btw `"writable-sdk": true` increase build time with 12x and did'nt helps

**Comment by RomanKharin** [comment]
Note: seems to be while installing 
```
user@pc:___/.flatpak-builder/build/tcl8.6-6/unix$ ls -la *.so
-rwxrwxr-x 1 user user 1909560 Jan  5 14:34 libtcl8.6.so
```
`rwx` transform to `r-x`
```
bash-4.3$ ls -la /app/lib/*.so
-r-xr-xr-x 1 user user 1909560 Jan  5 14:34 /app/lib/libtcl8.6.so
```
Is this normal?

**Comment by RomanKharin** [comment]
As noted at IRC this is error in upstream build system. And can be avoided with
```
"post-install": [
    "chmod 755 /app/lib/libtcl8.6.so"
]
```

**Comment by mildred** [comment]
I have the exact same problem with irssi https://github.com/irssi/irssi/ version 1.1.1

I don't understand how this is a problem in the build system. The strip operation happens after the `make install`, and seems to be done by flatpak itself... How could the build dystem be improved to fix this problem?

**Comment by mildred** [comment]
Ok, nevermind, the problem is that the `make install` is installing files with non readable permissions. An `install -m755` could probably fix the issue. The problem appears in the `.flatpak-builder` directory because after the `make install` step, the files installed in `/app` are moved in `.flatpak-builder/rofiles`.
