### ISSUE TITLE
[Bug with flatpak.org]: Too much whitespace - top of the page

### ISSUE THREAD

**Issue by alexsch01** [flatpak/flatpak#4694]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/master/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.3

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

Linux arch 5.15.15-1-lts #1 SMP Sun, 16 Jan 2022 09:28:22 +0000 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Go to https://flatpak.org/
2. Notice that you have to scroll to get to the start of content (including Setup button)

### Expected Behavior

Go to https://flatpak.org/

It should look like this

![image](https://user-images.githubusercontent.com/5721147/150535000-663af91e-a0c1-4a76-b7e5-3a4d7946f841.png)

### Actual Behavior

Go to https://flatpak.org/

It currently (1/21/2022) looks like this when you go to the page

![image](https://user-images.githubusercontent.com/5721147/150535179-2660a83f-35a7-4d1a-910d-dfbdf967a4e8.png)

You have to scroll to get to the actual start of the website

![image](https://user-images.githubusercontent.com/5721147/150535277-71e50f74-993b-4b6c-b307-ec57e4d5d54b.png)

### Additional Information

I understand this issue doesn't belong in the flatpak app repo but there is no repo for the actual flatpak.org website (as I know)

**Comment by mwleeds** [comment]
The repo for the website is here: https://github.com/flatpak/flatpak.github.io

**Comment by mwleeds** [comment]
For what it's worth I don't see the same issue in Brave.

**Comment by alexsch01** [comment]
@mwleeds can you move this issue over there?

**Comment by alexsch01** [comment]
Nevermind about moving it there. I'll just copy and paste my issue over there
