### ISSUE TITLE
[Bug]: I'm no longer getting GPU acceleration in some Flatpak apps

### ISSUE THREAD

**Issue by JaneSmith** [flatpak/flatpak#4698]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/master/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.3

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

35.20220122.0

### What architecture are you using?

x86_64

### How to reproduce

Hello. I've been experiencing a strange issue over the past few days, where certain Flatpak apps are not getting any GPU acceleration. Unfortunately this is going to be a vague one as I don't even know where to begin troubleshooting this, and am not entirely sure Flatpak itself is at fault. I'll apologise in advance if I'm reporting this in the wrong place.

It all started a few days ago, when I updated Fedora Silverblue from 35.20211221.0 to 35.20220120.0. This resulted in a variety of system-wide issues, such as missing sound, running Xorg instead of Wayland, systemd errors, etc. This turned out to be caused by SELinux, and it was suggested that I reset my SELinux policy files. After doing so, most of those issues were fixed.

However, ever since I updated, I am now no longer getting GPU acceleration in certain Flatpak apps. Even if I roll back to the old Fedora Silverblue version, this is still happening. So I don't know whether it's actually anything to do with the update, but it started at the exact same time. It could just be a coincidence... [Here is a full list of packages that changed in the update, just in case it's relevant.](https://pastebin.com/raw/FKr56z0P)

So what do I mean when I say I'm no longer GPU acceleration? Here are some examples:

- The biggest issue is with Firefox, as I use my web browser so often. When I try to open `org.mozilla.firefox` 96.0.2 (Flathub), it crashes immediately on startup. If I run it from the terminal, there is an error message saying: *"No GPUs detected via PCI"*. After multiple crashes, it automatically switches to safe mode and launches. This safe mode uses software rendering with all extensions disabled.
- Another issue is with Celluloid, my preferred video player. When I open `io.github.celluloid_player.Celluloid` 0.22 (Flathub), there is an error message saying: *"Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkWaylandToplevel': Sandbox does not provide an OpenGL implementation"* and *"celluloid-CRITICAL **: 07:18:09.838: Failed to initialize render context"*.
- I also tried an alternative video player, GNOME Videos. If I run it normally, it simply fails to launch. If I run it from the terminal, I see the error message: *"Unable to initialize Clutter: Unable to initialise the Clutter backend: no available drivers found."*

This could point to my graphics card (AMD Radeon RX 550) potentially being broken, but I don't believe that is the case, for the following reasons:

- I'm still running a GNOME Wayland session as normal, with it being displayed on my 4k monitor at 120 Hz as normal.
- There are no display glitches.
- If I run `lspci -nnv`, the graphics card is listed as normal, and it shows it's using the `amdgpu` driver.
- If I run `glxgears`, it launches and appears to work without any issues.
- If I run the non-Flatpak version of Firefox, it launches without crashing, and I can see in `about:support` that it is running a normal Wayland WebRender session with GPU acceleration and at 120 Hz.

So it seems like the issue I'm having is GPU acceleration (or perhaps specifically video acceleration?) only with Flatpak apps. The GNOME desktop, native `glxgears` app, and native Firefox app, all work fine.

But then some other Flatpak apps that I've tried seem to work okay. If I run `org.gimp.GIMP` 2.10.30 (Flathub), or `org.kde.krita` 5.0.2 (Flathub), or `org.blender.Blender` 3.0.0 (Flathub),  these all launch and (at least at a quick glance) appear to function. However, I can't be sure whether these are actually using GPU acceleration or whether they might be using software rendering. Perhaps it's specifically video decoding that's the issue?

I'm really stumped at this point. I don't know if the issue is with just some specific Flatpak apps (Firefox, Celluloid, GNOME Videos), or with specific runtimes (although Firefox uses a different runtime), or the overall Flatpak system and its sandboxing, or something else on my system. So I apologise if I'm posting in the wrong place, but my best guess at this point is that it's Flatpak. If there's any advice you could give me on troubleshooting this, or if you could point me in another direction if you think it's something else, I'd really appreciate it.

Again, the issue only started a few days ago, seemingly coinciding with my Fedora Silverblue update, which did update the kernel and Flatpak packages. I've been using Silverblue and Flatpak apps for several years with no issues until now.

### Expected Behavior

Flatpak apps should have GPU acceleration / hardware video decoding support.

### Actual Behavior

(Some) Flatpak apps do not have GPU acceleration / hardware video decoding support. Native apps work fine.

**Comment by rowbawts** [comment]
I also run Silverblue and have updated to this version without issue so if I can help troubleshoot from a working install I'd be willing to provide someone that knows how to help with this issue whatever they need that may help.

**Comment by shimmark** [comment]
Had this too a few days ago, I think on Silverblue 35.20220120.0, though it might have been one version earlier or later. Only seemed to affect Flatpak apps, not native or Toolbox. The problem disappeared by itself since.

**Comment by JaneSmith** [comment]
I've now updated to Silverblue 35.20220123.0, and I'm still experiencing the issue. Unfortunately there's no sign of this just disappearing by itself. I have SELinux Troubleshooter installed and I'm not getting any warnings, so I don't believe there are any lingering SELinux issues.

I really need help troubleshooting this. Surely there must be some commands I can run within the sandbox to try to check the GPU status and diagnose this? There must be some way of seeing why the sandbox doesn't have GPU access?

**Comment by fishxz** [comment]
exact same problem here. it doesnt seem to be silverblue related.

vlc flatpak (hardware acceleration doesnt work):
```
[00005592875080e0] main libvlc: VLC wird mit dem Standard-Interface ausgeführt. Benutzen Sie 'cvlc', um VLC ohne Interface zu verwenden.
Gtk-Message: 22:35:38.647: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:35:38.647: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[0000559287597970] main playlist: playlist is empty
[00005592875e0e30] main audio output error: too low audio sample frequency (0)
[00007ff994c194d0] main decoder error: failed to create audio output
[00005592875e0e30] main audio output error: too low audio sample frequency (0)
[00007ff994c194d0] main decoder error: failed to create audio output
[00005592875e0e30] vlcpulse audio output error: digital pass-through stream connection failure: Input/Output error
[00005592875e0e30] main audio output error: module not functional
[00007ff994c194d0] main decoder error: failed to create audio output
[00007ff980002d10] gl gl: Initialized libplacebo v4.157.0 (API v157)
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
[00007ff980002d10] glconv_vaapi_x11 gl error: vaDeriveImage: operation failed
[00007ff9a0015f50] main video output error: video output creation failed
[00007ff994c2bfa0] main decoder error: failed to create video output
[00007ff98018b780] gl gl: Initialized libplacebo v4.157.0 (API v157)
Failed to open VDPAU backend libvdpau_radeonsi.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Failed to open VDPAU backend libvdpau_radeonsi.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
[00007ff94001b040] gl gl: Initialized libplacebo v4.157.0 (API v157)
QObject::~QObject: Timers cannot be stopped from another thread
```
vlc on host (hardware acceleration works):
```
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
[0000558b66598b70] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[0000558b6663a550] main playlist: playlist is empty
[0000558b6663c9f0] main audio output error: too low audio sample frequency (0)
[00007fbdfe5404e0] main decoder error: failed to create audio output
[0000558b6663c9f0] vlcpulse audio output error: digital pass-through stream connection failure: Input/Output error
[0000558b6663c9f0] main audio output error: module not functional
[00007fbdfe5404e0] main decoder error: failed to create audio output
[00007fbdec005d60] gl gl: Initialized libplacebo v4.157.0 (API v157)
libva info: VA-API version 1.13.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[00007fbdec005d60] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
[00007fbdfcc4f440] avcodec decoder: Using Mesa Gallium driver 21.2.3 for AMD RENOIR (DRM 3.42.0, 5.14.10-300.fc35.x86_64, LLVM 13.0.0) for hardware decoding
```

hardware acceleration on obsproject also doesnt work on flatpak.

strange enough chrome/discord works.

**Comment by shimmark** [comment]
In my case visiting webkit://gpu in Epiphany caused Epiphany to crash with the hardware acceleration policy set to “always” (which is not yet the default) while removing the `--device=dri` permission now merely causes it to use llvmpipe but doesn’t cause a crash when visiting webkit://gpu. So it’s probably more complicated than the sandbox merely not having GPU access.

You can use `flatpak run -vv` to see exactly what Flatpak is doing.

**Comment by JaneSmith** [comment]
I finally got a solution to this thanks to [a kind poster on the Ask Fedora forums](https://ask.fedoraproject.org/t/no-longer-getting-gpu-acceleration-in-some-flatpak-apps-after-updating-fedora-silverblue/19927/6).

The problem was that I had `org.freedesktop.Platform.GL.default` (21.08) installed from `gnome-nightly` instead of `flathub`. For whatever reason, the `gnome-nightly` runtime is broken. After uninstalling the `gnome-nightly` version and installing the `flathub` version for 21.08, the issue is resolved.

I'm a little bit confused though as to how this situation came about or why it happened the way that it did. Surely a `gnome-nightly` runtime should only be used by `gnome-nightly` apps? It was my understanding that it would work that way... Or is it normal and intended that the runtimes don't need to be installed from the same source as the app itself? An app can target a specific runtime, but you can then drop a different runtime in instead even though it wasn't built for or tested with that runtime?

Thanks.

**Comment by refi64** [comment]
I believe that would be due to #3128 which was fixed in #4508.

**Comment by smcv** [comment]
> An app can target a specific runtime, but you can then drop a different runtime in instead even though it wasn't built for or tested with that runtime?

Runtimes are meant to be uniquely identified by their full name (it would be `runtime/org.freedesktop.Platform.GL.default/x86_64/21.08` in your case), globally across all remotes. If that didn't work, then it wouldn't be possible to install a beta app from `flathub-beta`, or an app that you compiled 5 minutes ago with gnome-builder, but still get the stable version of its runtime from `flathub`.

**Comment by JaneSmith** [comment]
That makes sense. Thanks for clarifying!

**Comment by IganKuhz** [comment]
The solution I found was set environment variables with Flatseal, like this:

<img width="616" height="185" alt="Image" src="https://github.com/user-attachments/assets/0ac94ee9-df70-42ec-bb74-aef57ca67059" /
