### ISSUE TITLE
[Feature request]: update: list version from and to

### ISSUE THREAD

**Issue by frogtile** [flatpak/flatpak#4717]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

on the listing of `flatpak update` print from which version  to which version packages will be updated.

**Comment by mwleeds** [comment]
duplicate of #4515

**Comment by frogtile** [comment]
@mwleeds sorry, didn't quite look at the issue search.
