### ISSUE TITLE
Output of `flatpak list --columns=name,size -v` is not sortable with `sort -h`

### ISSUE THREAD

**Issue by ernstki** [flatpak/flatpak#4720]
**This is not a bug**, and I plan to close the issue immediately after opening it.

The output of `flatpak list --columns=name,size -v` is not directly sortable using `sort -h`, which is a reasonable expectation for people who work with byte figures in the terminal a lot.

That's due to the [insertion of a non-breaking space](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/548) between the numerical value and the unit by Glib's [`g_format_size`](https://docs.gtk.org/glib/func.format_size.html), which is used by `flatpak list` [here](https://github.com/flatpak/flatpak/blob/1def449850ee40b6eacf8135f6fa8cd1f2eb71e5/app/flatpak-builtins-list.c#L291).

This behavior is beyond the scope of Flatpak, and obviously not the Flatpak developers' fault or responsibility. This issue simply documents for posterity how to sort such output with `sort`.

### Solution

Simply remove the Unicode [non-breaking space](https://www.fileformat.info/info/unicode/char/00a0/index.htm), `0xc2a0`.

```bash
flatpak list --columns=name,version,size -v 2>/dev/null \
  | sed 's/\xc2\xa0//' 
  | sort -t$'\t' -k3,3rh \
  | column -nts $'\t'
```

Note that `-n` is a Debian-only that tells `column` not to combine multiple consecutive delimiters. A cross-platform alternative is `[xsv](https://github.com/BurntSushi/xsv) table -d '\t'`.

### Related reading

* the Glib [GitLab issue](https://gitlab.gnome.org/GNOME/glib/-/issues/1625) and [merge request](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/548) that added the non-breaking space to the output of `g_format_size`

**Comment by mwleeds** [comment]
For the record Flatpak already outputs tab-delimited columns when writing to a pipe or file rather than a tty, in `flatpak list` and other commands.

**Comment by ernstki** [comment]
> For the record Flatpak already outputs tab-delimited columns when writing to a pipe or file rather than a tty, in `flatpak list` and other commands.

Nice. I love those little touches where the tool checks to see what stdin/stdout are connected to, even if it can seem a bit too magical at first (_e.g._ `mysql` seems to infer `--batch` in a pipe).

I appreciate your guys' chiming in on this, and I'm glad there was this conversation, but really the surprise of the non-breaking space and the fact that my go-to `sort -h` didn't work as expected was really all I'd hoped to document here.

I agree that _if_ CLI utilities using Glib's `g_format_size` for byte figures is very commonplace, then GNU sort being able to interpret that format would make a good feature request, though. Do you feel that it _is_ that commonplace?
