### ISSUE TITLE
[Bug]: runtime org.freedesktop.Platform/x86_64/21.08 not found but flatpak says it's installed

### ISSUE THREAD

**Issue by RDKRACZ** [flatpak/flatpak#4724]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/master/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Clear Linux

### Linux distribution version

Linux clearlinux 5.16.5-1120.native #1 SMP Tue Feb 1 10:03:19 PST 2022 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### Expected Behavior

Brave from flathub-beta should install fine.
Reported to brave flatpak https://github.com/flathub/com.brave.Browser/issues/107

### Actual Behavior

Brave requires org.freedesktop.Platform which is installed but brave doesn't detect it?
```
flatpak install flathub-beta com.brave.Browser
Looking for matches…
error: The application com.brave.Browser/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found
```
```
flatpak install org.freedesktop.Platform
Looking for matches…
Remotes found with refs similar to ‘org.freedesktop.Platform’:

   1) ‘flathub-beta’ (system)
   2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 2
Similar refs found for ‘org.freedesktop.Platform’ in remote ‘flathub’ (user):

   1) runtime/org.freedesktop.Platform/x86_64/19.08
   2) runtime/org.freedesktop.Platform/x86_64/1.6
   3) runtime/org.freedesktop.Platform/x86_64/20.08
   4) runtime/org.freedesktop.Platform/x86_64/21.08
   5) runtime/org.freedesktop.Platform/x86_64/18.08

Which do you want to use (0 to abort)? [0-5]: 4
Skipping: org.freedesktop.Platform/x86_64/21.08 is already installed
```

**Comment by mwleeds** [comment]
This is because you have the `flathub` remote configured in your per-user installation and the `flathub-beta` one in the system-wide installation, and Flatpak [doesn't use](https://github.com/flatpak/flatpak/blob/994accceb7ad2b296aaf5de5468eec1a2cae1380/common/flatpak-transaction.c#L531) per-user dependencies for things that are installed system-wide.

That said, the error message could definitely be friendlier!

**Comment by RDKRACZ** [comment]
Thank you, the issue is gone after adding flathub as system-wide and installing org.freedesktop.Platform.
Do I now have two org.freedesktop.Platform installed (one in user-specific directory and the other in the system one)?

>That said, the error message could definitely be friendlier!

Should I open a new issue for this?

**Comment by TheEvilSkeleton** [comment]
> > That said, the error message could definitely be friendlier!
> 
> Should I open a new issue for this?

I suggest doing that.

> Do I now have two org.freedesktop.Platform installed (one in user-specific directory and the other in the system one)?

Yes. You can run `flatpak remove --user org.freedesktop.Platform` to remove the one in your user.

**Comment by andirsun** [comment]
to solve the issue:
1. Install flathub system wide with
```
sudo flatpak remote-add --if-not-exists --system flathub \
  https://flathub.org/repo/flathub.flatpakrepo
```

**Comment by SurnameGuy** [comment]
I had a similar problem, not related to yours, but can help someone who reads this. plasma-discover terminal output:
```
...
"org.kde.plasma.libdiscover.backend.flatpak: could not find runtime "org.freedesktop.Platform/x86_64/22.08" FlatpakResource(0x5d7fe4d626e0, name = "..........")"
...
```
Solved by installing the missing package with ``flatpak install flathub org.freedesktop.Platform/x86_64/22.08``.
