### ISSUE TITLE
[Bug]: bwrap: Can't bind mount /oldroot/ on /newroot/: No such device

### ISSUE THREAD

**Issue by ViejoRS** [flatpak/flatpak#4731]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/master/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.2

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

21.10

### What architecture are you using?

x86_64

### How to reproduce

1. Launch any application installed via Flatpak, application fails to launch.

**flatpak run com.github.iwalton3.jellyfin-media-player**
`bwrap: Can't bind mount /oldroot/media on /newroot/media: No such device
error: Failed to sync with dbus proxy`

### Expected Behavior

Application should launch.

### Actual Behavior

Application fails to launch.

### Additional Information

5.13 kernel
GCC 4:11.2

This behavior started last night after I attepted to run "flatpak update". The updates seemed to go through without issue, however after I rebooted I was unable to launch any Flatpak applications.

**flatpak run -vv --command=true com.github.iwalton3.jellyfin-media-
player**
```F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/viejo/.local/share/flatpak
F: Opening user flatpak installation at path /home/viejo/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.github.iwalton3.jellyfin-media-player/x86_6
4/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/viejo/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 284108010
F: Allocated instance id 3123957652
F: Add defaults in dir /com/github/iwalton3/jellyfin-media-player/
F: Add locks in dir /com/github/iwalton3/jellyfin-media-player/
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/viejo/.config/pulse/client.conf': Error openin
g file /home/viejo/.config/pulse/client.conf: No such file or directory
F: bwrap --args 37 = --ro-bind /boot /boot --ro-bind /home /home --ro-bind /etc /etc --ro-b
ind /media /media --bind /var /var --symlink usr/bin /bin --ro-bind /dev /dev --symlink usr
/lib /lib --symlink usr/lib32 /lib32 --symlink usr/lib64 /lib64 --symlink usr/libx32 /libx3
2 --ro-bind /mnt /mnt --ro-bind /opt /opt --ro-bind /proc /proc --ro-bind /root /root --bin
d /run /run --symlink usr/sbin /sbin --ro-bind /srv /srv --ro-bind /sys /sys --bind /tmp /t
mp --ro-bind /usr /usr --ro-bind /cdrom /cdrom --bind /run/user/1000/.dbus-proxy/ /run/user
/1000/.dbus-proxy/ --file 35 /.flatpak-info
F: bwrap --args 40 = --fd=39 unix:path=/run/user/1000/bus /run/user/1000/.dbus-proxy/sessio
n-bus-proxy-HZUJH1 --filter '--own=com.github.iwalton3.jellyfin-media-player.*' '--own=org.
mpris.MediaPlayer2.com.github.iwalton3.jellyfin-media-player.*' --talk=com.canonical.AppMen
u.Registrar --talk=org.freedesktop.ScreenSaver --talk=org.freedesktop.PowerManagement '--ca
ll=org.freedesktop.portal.*=*' '--broadcast=org.freedesktop.portal.*=@/org/freedesktop/port
al/*' unix:path=/var/run/dbus/system_bus_socket /run/user/1000/.dbus-proxy/system-bus-proxy
-FDVJH1 --filter --talk=org.freedesktop.login1 'unix:path=/tmp/dbus-lr9rHWoxoi,guid=c499879
c4fb86d1af22e1ec962014e19' /run/user/1000/.dbus-proxy/a11y-bus-proxy-C94JH1 --filter --slop
py-names --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Embed@/org/a11y/atspi/accessi
ble/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Unembed@/org/a11y/atspi/acces
sible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Registry.GetRegisteredEvents@/org/
a11y/atspi/registry --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.Get
KeystrokeListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Reg
istry=org.a11y.atspi.DeviceEventController.GetDeviceEventListeners@/org/a11y/atspi/registry
/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.
NotifyListenersSync@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Re
gistry=org.a11y.atspi.DeviceEventController.NotifyListenersAsync@/org/a11y/atspi/registry/d
eviceeventcontroller
F: Running 'bwrap --args 37 xdg-dbus-proxy --args=40'
bwrap: Can't bind mount /oldroot/media on /newroot/media: No such device
error: Failed to sync with dbus proxy
```

If I try to test bwrap, it repeats the same error:

**bwrap --bind / / true**
`bwrap: Can't bind mount /oldroot/ on /newroot/: No such device`

**Comment by ViejoRS** [comment]
Ok, well things have gotten a whole lot weirder...

After running the following:
`
sudo rm -rf ~/.local/share/flatpak/repo/tmp/staging-*
sudo rm -rf /var/tmp/flatpak-cache-*
sudo flatpak repair
sudo flatpak repair --user
`
I can now open Jellyfin from the launcher I have pinned on Latte-Dock, however if I try to run Jellyfin from terminal the same exact error persists:

**flatpak run com.github.iwalton3.jellyfin-media-player**
`bwrap: Can't bind mount /oldroot/media on /newroot/media: No such device
error: Failed to sync with dbus proxy
`

I'm also still unable to open other programs like Tauon Music Box, either from the Latte launcher or from terminal. Very weird that the launcher for Jellyfin, and only that one, is now working...

`flatpak run com.github.taiko2k.tauonmb
bwrap: Can't bind mount /oldroot/media on /newroot/media: No such device
error: Failed to sync with dbus proxy`

**Comment by smcv** [comment]
> If I try to test bwrap, it repeats the same error:
>
> ```
> bwrap --bind / / true
> bwrap: Can't bind mount /oldroot/ on /newroot/: No such device
> ```

I think that indicates that this is a bwrap problem, not a Flatpak problem: you've removed all the Flatpak from the scenario you're testing, but the problem persists.

> I can now open Jellyfin from the launcher I have pinned on Latte-Dock, however if I try to run Jellyfin from terminal the same exact error persists

This suggests to me that there is something different between the execution environment of your launcher and the execution environment of your terminal.

Might you perhaps have a version of bubblewrap (and/or Flatpak) that you installed from a `.deb` package and a separate version that you installed from source code, or something like that?

From the same terminal where you can reproduce this, please try:

```
dpkg-query -W bubblewrap flatpak
which bwrap
which flatpak
bwrap --version
flatpak --version
```

and paste their output here.

When pasting output from commands, if you use this syntax, with triple ``` ` ``` before and after:

`````
```
$ dpkg-query -W bubblewrap flatpak
bubblewrap 0.5.0-1
flatpak 1.12.4-1
```
`````

it will preserve line-breaks and be easier to read.

> `sudo flatpak repair --user`

It is probably not relevant to this specific issue, but just to reduce how much this meme spreads: this is probably not the command you wanted. This is doing a `flatpak repair` on `/root/.local/share/flatpak`, which is only used by root, and is not relevant when only non-root users will run Flatpak apps. You probably wanted `sudo flatpak repair` (to repair `/var/lib/flatpak`) and `flatpak repair --user`, without sudo (to repair your own `~/.local/share/flatpak`).

**Comment by smcv** [comment]
Unfortunately, this looks like bubblewrap 0.4.1 or older (which would be right for Ubuntu 21.10), and that's a version from before I improved its error-reporting in containers/bubblewrap#434.

**Comment by ViejoRS** [comment]
Hi smcv, thank you for the response. I agree this seems to be more of an issue with bwrap than an issue with Flatpak itself. Do you think I should, or any recommendations on updating or fixing bwrap? It's odd this issue came up, because I know bwrap hasn't updated itself recently through apt.

Running "sudo flatpak repair" temporarily fixes (only) Jellyfin, and (only) through Latte launcher. 

```
dpkg-query -W bubblewrap flatpak
bubblewrap      0.4.1-3build1
flatpak 1.10.2-3ubuntu0.1

which bwrap && which flatpak
/usr/bin/bwrap
/usr/bin/flatpak

bwrap --version && flatpak --version
bubblewrap 0.4.1
Flatpak 1.10.2
```

**Comment by smcv** [comment]
I'm confused by this, because I don't see how you can get the error code `ENODEV` (which translates to `No such device` in the error message) when doing a bind-mount, and it isn't clear to me how you can get different results for different apps either.

Would you be able to download and compile https://github.com/containers/bubblewrap (don't install it, just compile it), and then run this in the build directory?

```
./bwrap --bind / / true
```

I'm hoping that will give you a better error message, perhaps something like:

```
bwrap: Can't bind mount /oldroot/ on /newroot/: Unable to mount source on destination: No such device
```

and that will tell us which specific operation is getting this error code.

Another thing you could perhaps try would be running `bwrap` via `strace`?

**Comment by smcv** [comment]
This issue should ideally be transferred to https://github.com/containers/bubblewrap but I don't have the necessary access level to do that. @alexlarsson, perhaps you can move it?

**Comment by smcv** [comment]
> I'm not sure if I'm trying to do the Github bubblewrap test you mentioned correctly. I'm downloading the archive, extracting it, and from within the directory I was going to run:
> ```
> ./configure
> make
> ```
>
> But that doesn't seem to jive, looks like it has unsatisfied dependencies or system conflict?

You might not need to do this now, but FYI: yes, you will usually need extra "development" packages to compile software yourself, which are not required to just run it.

In Ubuntu, you can get the necessary packages to compile bubblewrap with `sudo apt-get build-dep bubblewrap`. The first one you're getting an error for is `libcap-dev`, but not all of them will have been checked yet, so perhaps other packages are missing too.

**Comment by smcv** [comment]
> Here is the output from strace bwrap

I'd forgotten the details of exactly how to do this, but `strace -f bwrap --bind / / true` will let the tracing follow into the child process that does the `mount` system calls, and will tell us exactly which system call is failing. There will be a lot of output, so it's probably better to put it on a [gist](https://gist.github.com/) or in an attachment.

**Comment by smcv** [comment]
> somehow I found out that the issue seems to be related to Conky doing something

... a system monitor is interfering with bubblewrap?! That seems very strange.

How did you install Conky? (apt? Flatpak? AppImage? Snap?)

**Comment by ViejoRS** [comment]
I installed Conky via apt, I have version 1.11.6 right now. The only change I've made recently is with network mapping in my house which has put my whole wifi on a different subnet, so I know Conky isn't able to find some of the network drives it's supposed to be monitoring. I'd figure that should just have it error out or not display though, no idea how it's screwing with stuff bad enough to stop bubblewrap from accessing mount points.

Here is the strace -f bwrap output **without** conky running:

https://gist.github.com/ViejoRS/1d787e603957627c64601aae57b40984

And here it is **with** Conky running:
https://gist.github.com/ViejoRS/6d4ee2a4023a8a0e64fe602889730150

I'm going to edit my Conky config and comment out my network drives to see if that has an impact, and try running it from the terminal to see if that tells me anything.

**Comment by ViejoRS** [comment]
Lol yep! If I comment out the Conky lines that point to where my SMB drive is supposed to be mapped (currently unmapped due to my network changing and the .automount file not pointing correctly) then Bubblewrap doesn't have an issue when Conky is in the background.

```
#${voffset 7}${color1}SMB ${stippled_hr 3 3}
#${voffset 5}${color1}Used: ${color3}${fs_used /media/viejo/Media}${color1}${goto 200}Free:${goto 250}${color3}${fs_free /media/viejo/Media}
#${color2}${fs_bar /media/viejo/Media}
```

So somehow Conky is interfering with mount operations, I guess. Incredibly odd, seems like an overstretch for Conky to do this.

...I'm also just now noticing it may at least be worth noting that both programs I was using to test Flatpak with, Tauon and Jellyfin, rely on that SMB server for their databases. I'd figure the app should still launch and just fail to connect or ask me to correct the server, but maybe that's also having an impact? I don't see how or why Conky would play into that though.

**Comment by smcv** [comment]
Ah, here it is:

```
[pid 12025] mount("none", "/newroot/media/viejo/Media", NULL, MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND|MS_SILENT|MS_RELATIME, NULL) = -1 ENODEV (No such device)
```

So the problem is: we are trying to remount a copy of `/media/viejo/Media` inside the sandbox, to add the `MS_NODEV` flag, which prevents accessing device nodes on that mount point (not that there should be any device nodes outside `/dev` *anyway*, but this is Unix and everything is potentially a trap, so bubblewrap wants to be careful).

But because the network drive is not working (because the files are on a machine you can't access), that call (and presumably anything else that we might do to it) is failing with `No such device`.

Possible workarounds (choose any or all):

1. Fix your network drive configuration
2. Unmount your non-functional network drives, and disable the automount units until you have fixed them
3. Mount network drives (and all other external media) with with options that include `nosuid,nodev` - which could be a good bit of security hardening for your system *anyway*, because there's no legitimate reason why a network drive should contain setuid executables or device nodes, and if it somehow does, then a malicious or compromised fileserver could use them to attack you

> Incredibly odd, seems like an overstretch for Conky to do this

I think it's just that you have configured Conky to try to access the network drives via the filesystem, so it does as it's told, and that triggers the automount.

> I'm also just now noticing it may at least be worth noting that both programs I was using to test Flatpak with, Tauon and Jellyfin, rely on that SMB server for their databases

If they are using the kernel-level mount point in `/media`, and you were not running Conky, then you might find that running either Tauon or Jellyfin on its own "works" (launches but fails to connect), but then it makes bwrap fail with `No such device` if you additionally run the other one.

If they are using a user-space implementation of SMB, then they should just not work.

**Comment by smcv** [comment]
As far as possible solutions in bubblewrap go, here is the code for what's failing:

```
          if (new_flags != current_flags &&
              mount ("none", mount_tab[i].mountpoint,
                     NULL, MS_SILENT | MS_BIND | MS_REMOUNT | new_flags, NULL) != 0)
            {
              /* If we can't read the mountpoint we can't remount it, but that should
                 be safe to ignore because its not something the user can access. */
              if (errno != EACCES)
                return BIND_MOUNT_ERROR_REMOUNT_SUBMOUNT;
            }
```

I'm not sure whether it's safe to treat `ENODEV` as equivalent to `EACCES`, or whether that would be a potential security vulnerability (because the device might start working, and then we wouldn't have applied the `new_flags` to it). If it's a potential security vulnerability, then we cannot do anything about this in bubblewrap, and the only solution will be to fix your network drives.

We should probably improve bubblewrap's error-reporting (again) so it can report which specific mount point is the problem.

**Comment by ViejoRS** [comment]
I need to fix my network addressing, just a separate project I'm trying to wrap up (I'm far from a network guru so it's taking me a little time).

Thank you for your suggestion of adding those mount flags, I'll add them to the file so when I have everything lined up correctly again that'll be in place.

On both Jelly and Tauon I just put in the server IP of Jellyfin, so it's not really going through SMB, but I guess since SMB points to the same device it still causes issues with SMB's intended mount point.

After all of this I agree 100% the issue is obviously with my own system/environment and nothing intrinsic with either Bubblewrap or Flatpak. I need to finish my firewall/router setup so this stops being an issue... 

Thank you VERY much for your help and info smcv, I really appreciate it. Have a great rest of the week :)

**Comment by hyuri** [comment]
Just a heads up:
I just got a similar error "bwrap: Can't bind mount /oldroot ..." when running Chromium and the problem was:
I added permissions to `xdg-data:/applications` and `xdg-data:/icons`, through Flatseal. Changing these permissions to `~/.local/share/applications` and `~/.local/share/icons" solved the problem.
