### ISSUE TITLE
[Bug]: Flatpak apps don't read user defined fontconfig files

### ISSUE THREAD

**Issue by Motor-head** [flatpak/flatpak#4742]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

1. create a user defined font config file (say `mylist.conf`)  in `~/.config/fontconfig/conf.d/`
2. run any flatpak app (ex., Ungoogled Chromium or Libreoffice)

### Expected Behavior

The flatpak apps should read the `mylist.conf` and load defined fonts in order to render Complex Text Layout (CTL) fonts.

### Actual Behavior

Flatpak apps don't read `mylist.conf`, using `DejaVu Sans` as default font (in my case) for CTL fonts.

### Additional Information

`Mylist.conf` is a list of fallback fonts I made for rendering Indic fonts. All non-flatpak apps obey this file, except Flatpak. Temporary solution is to create a symlink of `fontconfig` folder in `~/.var/app/<APP>/config/` folder. But this is not feasible in case there are too many flatpak apps. Flatpak should automatically read and obey user defined config file.

**Comment by rusty-snake** [comment]
#3947

**Comment by mhtvsSFrpHdE** [comment]
I made a script for who just don't want to take care about the details  
Use Obsidian as a example

Save this code to `FixFlatpakFont.sh`, `chmod +x FixFlatpakFont.sh`
```
#!/bin/bash
FONT_CONF="$HOME/.config/fontconfig"
DEST="$HOME/.var/app/$1/config/fontconfig"

ln -s $FONT_CONF $DEST
```
And run FixFlatpakFont.sh md.obsidian.Obsidian, close Obsidian, open again, confirm font rendering is fixed.

For other flatpak apps, look at `ls ~/.var/app`, folders inside this path go to script first argument.

**Comment by liferooter** [comment]
@mhtvsSFrpHdE the same effect can be achieved using `flatpak override --filesystem=xdg-config/fontconfig`.

**Comment by mhtvsSFrpHdE** [comment]
> @mhtvsSFrpHdE the same effect can be achieved for all applications using `flatpak override --filesystem=xdg-config/fontconfig`.

It will be up-to-date automatically, sync with latest user config, like if using symbolic link?

I don't have Linux machines these days, so I can't make a test.

**Comment by chrisawi** [comment]
duplicate of #3947
