### ISSUE TITLE
error: While opening repository /home/*/.local/share/flatpak/repo: opening repo: opendir(objects): No such file or directory

### ISSUE THREAD

**Issue by slrslr** [flatpak/flatpak#4756]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.7

### What Linux distribution are you using?

Debian

### Linux distribution version

11 (stable), kernel 5.10

### What architecture are you using?

x86_64

### How to reproduce

https://github.com/nix-community/impermanence/issues/71

### Expected Behavior

works without error

### Actual Behavior

works with error

**Comment by slrslr** [comment]
my $ history, ~/.bash_history no longer shows what i did and i do not remember, SE not returned any results that would suggest flatpak has any command history log, so i can not tell what else i did, i quite doubt i did any special commands beside what was mentioned. So if not reproducible and not knowing what caused this, close it.

**Comment by guglovich** [comment]
I have the same thing, but I probably didn't create the folder myself, because the files are in it.

**Comment by Summertime** [comment]
A case I've found that causes this, on Fedora Silverblue, creating a new user led to this error in the new user. I'm guessing because the `/etc/skel` lacks the right files, and perhaps some later step isn't being ran. Downstream but points to a potential cause.
