### ISSUE TITLE
[Feature request]: One-Time File Access

### ISSUE THREAD

**Issue by SViN24** [flatpak/flatpak#4758]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

For a lot of applications, specifically messaging applications it is very common for people (and by people i mean the general population that has no idea how computers work) to share files from directories that are not permitted for the application to touch on its own.

Problem with this then the application will probably throw an error since it does not know what is actually going on(See for example discord). So my thought was what if there was a way for the user to make a one time exception allow the application to actually load the file `~/restricted_directory/picture_of_cat.jpg` without giving an application the ability to actually look at other files in the folder like `~/restricted_directory/picture_of_dog.jpg`

Benefits of said approach:
1) So easy my dad can use it
2) Its still secure since the application has no idea what is going on in the restricted directory.

Issues:
1) applications will probably have to implement it because i can't see how this can work with current implementations.

**Comment by rusty-snake** [comment]
How does this differ from the [document portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Documents)?
