### ISSUE TITLE
[Feature request]: Resource requests(from the application with the user's permission)

### ISSUE THREAD

**Issue by SViN24** [flatpak/flatpak#4759]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

A story beforehand: A while ago i installed a flatpak of a torrent client, said torrent client was configured by me to use its own directory called ~/Torrents. I assumed it all worked fine because the Torrent client did not complain and it said it started downloading files just fine. I never noticed that it had no permissions to use that specific directory since it never showed me an error. I later found out that it never saved anything on that folder. And it in fact could not find what it downloaded after a restart of the application. Since i know how to use my computer it wasn't hard for me to figure out what was going wrong(and why i had to eventually change its permissions) but realistically this is a scenario that should never happen to the average person just trying to do their job and doesn't know as much about linux. 

I think a feature where the application can request access to resources(directories other things) and the system(assuming the user permits so with a yes or no prompt) allows it. Would be great.

Example:
1. User wants a game launcher to use a specific directory from another hard drive to save his games.
2. User chooses the directory from the application `/path/to/games/dir/`
3. A prompt shows up informing that the application is requesting access to that directory(assuming its not already in control of it)
4. User accepts or denies the request.(similar to the "application running in the background" request)

**Comment by rusty-snake** [comment]
Again, how does this differ from the [document portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Documents)? Why would we need it? Why does the document portal does not meet these requests?

**Comment by SViN24** [comment]
sorry about that first i saw the notifications. Not sure what the documents portal(not that familiar with flatpak development) is but i assumed since no application does this this was simply not a feature.

**Comment by rusty-snake** [comment]
From the documentation:

> The document portal allows to make files from the outside world available to sandboxed applications in a controlled way.
> 
> Exported files will be made accessible to the application via a fuse filesystem that gets mounted at `/run/user/$UID/doc/`. The filesystem gets mounted both outside and inside the sandbox, but the view inside the sandbox is restricted to just those files that the application is allowed to access.
>
> Individual files will appear at `/run/user/$UID/doc/$DOC_ID/filename`, where `$DOC_ID` is the ID of the file in the document store. It is returned by the [Add()](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Documents.Add) and [AddNamed()](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Documents.AddNamed) calls.
>
> The permissions that the application has for a document store entry (see [GrantPermissions()](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Documents.GrantPermissions)) are reflected in the POSIX mode bits in the fuse filesystem.

**Comment by rusty-snake** [comment]
> no application does this

IDK which flatpaks you tested, but if you want to test install `org.mozilla.firefox` (which has only `filesystems=xdg-download;`) and Ctrl-O a file form e.g. `~/Pictures`.

**Comment by SViN24** [comment]
i see, thanks for the explanation.
i had no idea about this. Closing the issues then.

**Comment by smcv** [comment]
If the application doesn't use the portal (either in its own code, or via a library like GTK that it uses) then it will not be able to take advantage of this mechanism; but that's an application bug, not a Flatpak bug.

GTK and Qt applications usually use the documents portal automatically, but the rest of the world has not necessarily caught up yet. The maintainers of Flatpak cannot magically add support for this into individual applications.
