### ISSUE TITLE
Usage of pcreposix.so from FreeDesktop SDK

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#476]
Our KDE Runtime is using the pcreposix.so binary, when our applications link to it, we get an error such as:
bugs.kde.org/show_bug.cgi?id=374358

Now I understand the solution would be to include this library together with the platform, because the FreeDesktop platform is only including the binary in the SDK and not the Runtime.

I wonder if we should be getting a build error or something. After all, we're distributing a binary with unmet dependencies:
```
$ ldd /app/lib64/plugins/okularpart.so | grep pcreposix
        libpcreposix.so.0 => not found
```

**Comment by alexlarsson** [comment]
It seems like the platform only includes libpcre, but the sdk has libpcre-dev, which pulls in also libpcreposix and libpcrecpp. I guess we should add those to the platform manually.

**Comment by alexlarsson** [comment]
I pushed a fix for this, lets see if it builds.

**Comment by aleixpol** [comment]
Brilliant, thanks!

**Comment by alexlarsson** [comment]
Should be in now
