### ISSUE TITLE
[Bug]: open link in browser, browser crashes after a few seconds

### ISSUE THREAD

**Issue by KVAnton-WEB** [flatpak/flatpak#4761]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

KDE neon 5.24 (based on Ubuntu 20.04), Linux pc 5.13.19-051319-generic

### What architecture are you using?

x86_64

### How to reproduce

1. open any flatpak app (I tested on org.telegram.desktop and org.kde.kasts)
2. click on url 
3. after click - browser open (default for system) (I tested on not flatpak Firefox 97.0 and  Falkon)
4. wait few second (10-20) 

### Expected Behavior

normal browser behavior

### Actual Behavior

browser crashes after a few seconds without any error messages

### Additional Information

The problem is only with flatpak applications (I did not find others)
Video demonstration:
https://user-images.githubusercontent.com/12401787/154753175-fb92e0ea-7c9e-43a6-85bd-2e8aecdff313.mp4

**Comment by KVAnton-WEB** [comment]
Video 1.5 MByte if it matters

**Comment by smcv** [comment]
What version of xdg-desktop-portal are you using?

What is logged in the systemd journal when this happens?
