### ISSUE TITLE
[Bug]: AppStream file wrongly moved from /app/share/metainfo/

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#4775]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.7

### What Linux distribution are you using?

Debian

### Linux distribution version

Debian 5.10.92-1

### What architecture are you using?

x86_64

### How to reproduce

1. Install GIMP from Flathub:
```
flatpak install flathub org.gimp.GIMP
```
2. Also install the SDK:
```
flatpak  install org.gnome.Sdk/x86_64/41
```
3. Run: `flatpak run --devel --command=bash org.gimp.GIMP//stable`
4. Now check the contents of `/app/share/metainfo/` inside the sandbox.

### Expected Behavior

GIMP installs its AppStream file inside `$DATADIR/share/metainfo/` as per the [spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location). So `/app/share/metainfo/org.gimp.GIMP.appdata.xml` should exists.

### Actual Behavior

The file is not where it was installed. Nevertheless it can be found on `/app/share/appdata/org.gimp.GIMP.appdata.xml`.

Why it is a problem for us (at GIMP) is that I just implemented a "welcome dialog" feature making use of the `<release>` tag in the appstream to show the release notes on first launch after an update. We obviously take into account potential different $DATADIR set at configuration. But I was not expecting that flatpak would apparently move the file altogether which is not so nice.

Also even though the `appdata/` folder is acceptable since it is legacy, it is not even the recommended folder anymore (`metainfo/` is), so it's even more surprising. Flatpak is moving the file from the recommended location (by specs) to the legacy location.

Why is flatpak doing this? I couldn't find any information on this.

**Comment by smcv** [comment]
This is actually done by the version of flatpak-builder in use on the system that built this app (probably Flathub), not the version of Flatpak in use on the system where you installed it. 

> Why is flatpak doing this?

Because `appdata/` was the only supported location in older runtimes, and moving all appdata files to one place makes it simpler to do programmatic edits on its content, which flatpak-builder needs to do.

**Comment by smcv** [comment]
This is flatpak/flatpak-builder#252.

**Comment by Jehan** [comment]
Ok thanks.
