### ISSUE TITLE
[Bug]: GTK3 File dialog looses focus when opened

### ISSUE THREAD

**Issue by yttrium** [flatpak/flatpak#4781]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.2

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Ubuntu 21.10 Impish

### What architecture are you using?

x86_64

### How to reproduce

Reproduce this on Gnome Shell. I found that the issue does not happen on Xfce.

1. Have either Flatpak Chromium, Foliate, Firefox or Thunderbird installed
2. Load the application
3. Hit Ctrl+O to open the "Open File" GTK3 dialog
4. The first time in your session, all is OK. The dialog keeps keyboard focus and you can directly type a file name. Instead hit Esc to close the dialog
5. Hit Ctrl+O again: the dialog opens, but immediately acquires the colors of a window that is not in focus. Indeed, you cannot type a file name, hit escape to close the dialog, etc. If working with Chrome, typing goes to the URL bar in the main Chrome window in the background.

### Expected Behavior

When opening a GTK3 file dialog ("File open" or "Save"), the dialog should remain focused, i.e., accept keyboard input.

### Actual Behavior

When opening a GTK3 file dialog ("File open" or "Save"), the dialog stays on top, but looses focus (including keyboard focus).  This is seen by the window getting window decorations of a not focused window.

**Comment by rusty-snake** [comment]
Maybe related:
- https://github.com/flatpak/xdg-desktop-portal-gtk/issues/306
- https://github.com/flatpak/xdg-desktop-portal-gtk/issues/137

**Comment by yttrium** [comment]
Thanks for pointing out these issues. The second one describes the problem precisely as far as I see, however in language that a normal user seeing the issue will never find back. I will hereby close this issue as duplicate.

**Comment by yttrium** [comment]
Duplicate of https://github.com/flatpak/xdg-desktop-portal-gtk/issues/137
