### ISSUE TITLE
Installing pitivi using its flatpakref does not install the required gnome runtime

### ISSUE THREAD

**Issue by thiblahute** [flatpak/flatpak#479]
```
 INSERT  thiblahute  ~  flatpak remote-delete gnome 
 INSERT  thiblahute  ~  rm -R /home/thiblahute/.local/share/flatpak                    
 INSERT  thiblahute  ~  flatpak install --user http://flatpak.pitivi.org/pitivi.flatpakref
This application depends on runtimes from:
  http://sdk.gnome.org/repo/
Configure this as new remote 'gnome' [y/n]: y
Installing: org.pitivi.Pitivi/x86_64/stable
Installing: org.pitivi.Pitivi/x86_64/stable from org.pitivi.Pitivi-origin

6 delta parts, 34 loose fetched; 117805 KiB transferred in 42 seconds                                                                                                                                                                         
 INSERT  thiblahute  ~  flatpak run org.pitivi.Pitivi                                     
error: runtime/org.gnome.Platform/x86_64/3.22 not installed
```

We can see that the `gnome` repo has been set and everything seems to be in place.

**Comment by alexlarsson** [comment]
This is because the remote doesn't have the flatpak metadata cache in the summary, which we use to find the app dependencies. You need to run flatpak build-update-repo on the repo.

I pushed some warning spew to flatpak to make this more obvious in the future.

**Comment by thiblahute** [comment]
> This is because the remote doesn't have the flatpak metadata cache in the
summary, which we use to find the app dependencies. You need to run flatpak
build-update-repo on the repo.

Thanks for the explanation, problem seems to be due the fact that I was
using `ostree summary -u --gpg-sign=739E841A` on the build bot (because the
flatpak alternative was not existing when I set it up), works perfectly now.


On Thu, Jan 12, 2017 at 6:47 AM, Alexander Larsson <notifications@github.com
