### ISSUE TITLE
[Bug]: Getting Glib-CRITICAL messages when searching

### ISSUE THREAD

**Issue by alosarjos** [flatpak/flatpak#4794]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.13.1

### What Linux distribution are you using?

Arch Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Do a search of an app with flatpak CLI

### Expected Behavior

Get results

### Actual Behavior

I'm getting the same message multiple times before the results

`(flatpak search:15526): GLib-CRITICAL **: 09:26:26.963: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed`

### Additional Information

Already tried with:

- `sudo flatpak repair` and reinstalling
- Removing `/var/lib/flatpak` and reinstalling

**Comment by smcv** [comment]
This is https://github.com/ximion/appstream/issues/384 and should be fixed by the next libappstream release (I already sent a patch to fix it, which was merged).

Bugs in Flatpak's dependencies will not be fixed by a Flatpak change, so I'm closing this as not actionable for Flatpak.

Note that 1.13.x is a development prerelease for early adopters, and is not the current stable release (that's 1.12.6).

**Comment by xerexcoded** [comment]
AppStream version: 0.15.2 , still does not have this merged , hopefully the next version will resolve the error .
@alosarjos  I am running Fedora Silverblue rawhide , I too get the error with Flatpak version: 1.13.2 , so appstream has to be updated first and then this error will be resolved

**Comment by Flashwalker** [comment]
have the same on Ubuntu, flatpak 1.14.0-2flatpak1~22.04.1

**Comment by smcv** [comment]
> have the same on Ubuntu

This is a libappstream bug, not a Flatpak bug, so you will continue to get this until Ubuntu 22.04's libappstream is updated or gets a backport of the fix. https://bugs.launchpad.net/ubuntu/+source/appstream/+bug/2006110
