### ISSUE TITLE
Connection terminated unexpectedly

### ISSUE THREAD

**Issue by Datertec** [flatpak/flatpak#4809]
Hello, 

Version 1.12.4 - Arch Linux

I'm trying to run the below command:
`flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
but I get the following error after waiting a long time
`error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: Connection terminated unexpectedly`

When opening the discover I also get the following error:
`"error pulling from repo: error updating appstream2: while pulling appstream2/x86_64 from remote flathub: opening content object"`

Any idea on how to resolve this?

Kind regards,

Datertec

**Comment by mwleeds** [comment]
Sounds like an issue with your Internet connection. Does `wget https://flathub.org/repo/flathub.flatpakrepo` work? Or opening `https://flathub.org/repo/flathub.flatpakrepo` in a web browser?

**Comment by Datertec** [comment]
@mwleeds using Firefox web browser and it works fine (prompting me to download the repo file)

wget results:
```
 wget https://flathub.org/repo/flathub.flatpakrepo
--2022-03-15 20:11:44--  https://flathub.org/repo/flathub.flatpakrepo
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving flathub.org (flathub.org)... 46.235.231.150, 46.235.230.111, 2a00:1098:82:e::1:1, ...
Connecting to flathub.org (flathub.org)|46.235.231.150|:443... connected.
HTTP request sent, awaiting response... Read error (The TLS connection was non-properly terminated.) in headers.
Retrying.
```

Curl:
curl https://flathub.org/repo/flathub.flatpakrepo
[Flatpak Repo]
Title=Flathub
Url=https://dl.flathub.org/repo/
Homepage=https://flathub.org/
Comment=Central repository of Flatpak applications
Description=Central repository of Flatpak applications
Icon=https://dl.flathub.org/repo/logo.svg
GPGKey=mQINBFlD2sABEADsiUZUOYBg1UdDaWk.......
