### ISSUE TITLE
Exporting Gnome shell extensions

### ISSUE THREAD

**Issue by 183amir** [flatpak/flatpak#481]
Some apps like https://github.com/codito/gnome-pomodoro come with a Gnome shell extension when you install it. Is it possible to install the extension too (export) when it is packaged with flatpak?

**Comment by alexlarsson** [comment]
It might be possible, but i'm not sure. If you put the right files in export/share/gnome-shell in your app then these will be exported and the shell should ideally pick it up. However, all exported filenames have to be prefixed by the app-id, so it may not work.

**Comment by 183amir** [comment]
The extension must contain at least two files with names of `metadata.json` and `extension.js`.
I don't think Shell supports any other filename.

**Comment by alexlarsson** [comment]
Yeah, then it won't work.
Of course, one could also consider this a good thing, as it would otherwise be very easy to circumvent the sandbox...

**Comment by 183amir** [comment]
I understand that this could have some potential issues both technical and in terms of security.
But, if current developers choose to distribute their apps with flatpak, the installation becomes a two step process.
They need to install the flatpak and also install the extension separately (either manually or through https://extensions.gnome.org) while other installation methods is just one package to install.
Maybe this can be done through portals? You can install the extension per user too. So maybe at the beginning the app asks the user if they want the extension and through the portals they save the extension in `~/.local/share/gnome-shell/extensions/`?
The extension then would not be uninstalled with the flatpak but it can be uninstalled through removing that folder or through the extension management interface (Gnome tweak tool or https://extensions.gnome.org/local/).
Or maybe support for flatpak based Shell extensions can be added to Shell itself.

**Comment by alexlarsson** [comment]
Well, flatpak is designed to package apps, and gnome-shell extensions is more on the "parts of os" side, and also generally don't run inside flatpak, so I think it is out of the scope for flatpak.

**Comment by 183amir** [comment]
I agree, thank you for discussing this.

**Comment by oilipheist** [comment]
Sorry to drag up an old closed issue but an alternative way of solving the underlying problem is to use something like [this](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1705) to notify the user in app either through a banner or by other means that they can install the official GNOME extension by clicking this button. You cant bundle it with the flatpak itself but you can bundle it conceptually at least and let users fetch it from extensions.gnome.org in the app itself.
