### ISSUE TITLE
[Bug]: Flatpak creates ~/.config/flatpak even though $XDG_CONFIG_HOME is somewhere else

### ISSUE THREAD

**Issue by Anas-Sherif** [flatpak/flatpak#4815]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

5.16.15-arch1-1

### What architecture are you using?

x86_64

### How to reproduce

1. Change $XDG_CONFIG_HOME & $XDG_CACHE_HOME
2. Reboot
3. Flatpak still uses ~/.config & ~/.cache

### Expected Behavior

Use $XDG_CONFIG_HOME & $XDG_CACHE_HOME instead of ~/.cache & ~/.config

### Actual Behavior

Uses ~/.config & ~/.cache instead of $XDG_CONFIG_HOME & $XDG_CACHE_HOME

### Additional Information

My $XDG_CONFIG_HOME & $XDG_CACHE_HOME are ~/.local/etc & ~/.local/cache

**Comment by smcv** [comment]
> Change $XDG_CONFIG_HOME & $XDG_CACHE_HOME

Change them how, exactly?

> Flatpak still uses ~/.config & ~/.cache

Which exact processes or operations still use those?

The reason I ask is because some parts of Flatpak are run directly by your desktop environment or by you in a terminal, but other parts of Flatpak are background services run by D-Bus activation and/or `systemd --user`, and depending on exactly how you go about setting those environment variables, it's entirely possible that D-Bus-activated services and/or systemd services are not receiving them.

**Comment by Anas-Sherif** [comment]
> Change them how, exactly?
Setting them in .zshenv

>Which exact processes or operations still use those?
>The reason I ask is because some parts of Flatpak are run directly by your desktop environment or by you in a terminal, but other parts of Flatpak are background services run by D-Bus activation and/or systemd --user, and depending on exactly how you go about setting those environment variables, it's entirely possible that D-Bus-activated services and/or systemd services are not receiving them.
I'm not using a desktop environment just a wm I launch my apps using the terminal or dmenu.

**Comment by smcv** [comment]
> Setting them in .zshenv

That's only going to change the environment variables within your zsh sessions, and not for system components that are "larger" than your zsh session, notably `systemd --user` and any service that it starts.

To affect `flatpak-session-helper.service`, `flatpak-portal.service` and other components that are "larger" than your zsh session, look into `systemd.environment-generator(7)` or `pam_env(7)`.

**Comment by Anas-Sherif** [comment]
Thanks! It worked it also fixed other things like dconf.
