### ISSUE TITLE
[Bug]: Flatpak apps open vscode instead of the file manager

### ISSUE THREAD

**Issue by nu111** [flatpak/flatpak#4819]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.6.5

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

20.04.4 LTS

### What architecture are you using?

x86_64

### How to reproduce

when I open a directory from a Flatpak app such as [DropBox](https://flathub.org/apps/details/com.dropbox.Client) or [Cryptomator](https://flathub.org/apps/details/org.cryptomator.Cryptomator), it opens it in Visual Studio Code instead of Dolphin. This doesn't happen if I open a directory from a non Flatpak app. Also `xdg-open ~` as expected opens Dolphin. So it seems to be a Flatpak issue.

Visual Studio Code is installed with apt, [the official way to install it](https://code.visualstudio.com/Download).

I notice the same issue opening a directory from [Chromium Browser](https://snapcraft.io/chromium) installed as a Snap.

### Expected Behavior

Dolphin Filemanager should be opened

### Actual Behavior

Visual Studio Code is opened instead of Dolphin

**Comment by wannest** [comment]
I'm having the same issue. I recently upgraded to Kubuntu 22.04 and the problem persists since 20.04.1. It not only happens with vscode, but other apps as well like Baobab. I am using the Bottles flatpak app and it tries to open vscode first when trying to browse files, if I uninstall vscode it then tries to browse files with Baobab, which is a folder size analyzer, so not what you want. My intention was to browse files with the default file manager, Dolphin. It'ss an annoying problem, I hope they fix it soon.

**Comment by mwleeds** [comment]
> I notice the same issue opening a directory from [Chromium Browser](https://snapcraft.io/chromium) installed as a Snap.

That seems like pretty good evidence it's not a Flatpak issue, though it's still possible it's an [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal/) issue since snaps also use portals.

**Comment by nu111** [comment]
Me to was thinking about `xdg`, but it seems not be involved, `xdg-open .` works as expected.

**Comment by mwleeds** [comment]
`xdg-open` is not the same as `xdg-desktop-portal`. They are named similarly due to being related to the Cross-Desktop Group. That being said, `xdg-open` from within a Flatpak sandbox would call to `xdg-desktop-portal` to work.

**Comment by mwleeds** [comment]
Closing this in favor of https://github.com/flatpak/xdg-desktop-portal/issues/842
