### ISSUE TITLE
confusing to have remote-ls and remote-list

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#482]
maybe we can do better with the naming here? the 'ls' part of remote-ls effectively is an abbrevation of "list" and remote-list does have different functionality than remote-ls. maybe something more descriptive?

maybe we can make a simplification nad simply have "flatpak list" list both remotes, and applications and runtimes, while "flatpak remote-list" is only for listing apps and runtimes on a given remote? then there is also less commands to remember. :-)

( ping @noverby )

**Comment by alexlarsson** [comment]
In git, it is `git remote show NAME` to show the remote contents, and in general `git remote OP`, but `git remote` to list the remotes.

Maybe we can do something like this, say `flatpak remotes` to list the remotes?

**Comment by matthiasclasen** [comment]
flatpak remotes sounds good to me

**Comment by bastianilso** [comment]
sounds good to me too
