### ISSUE TITLE
[Bug?]: Substring match is done in strings that look like a ref

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#4829]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Debian

### Linux distribution version

unstable

### What architecture are you using?

x86_64

### How to reproduce

Preconditions:

* `flathub` and `flathub-beta` remotes are both configured
* `flathub` has `app/com.google.ChromeDev/x86_64/stable`
* `flathub-beta` has `app/com.google.Chrome/x86_64/beta`
* Neither remote has the "other" version of Chrome
* Neither version of Chrome is installed

To reproduce:

* flatpak install chrome
* flatpak install com.google.Chrome
* flatpak install com.google.Chrome//
* flatpak install com.google.Chrome/x86_64/
* flatpak install com.google.Chrome//stable
* flatpak install app/com.google.Chrome/x86_64/stable
* flatpak install flathub app/com.google.Chrome/x86_64/stable
* etc.
* (say no when prompted to actually install anything)

### Expected Behavior

`flatpak install chrome` should search for apps with `chrome` in their names, including both `Chrome` and `ChromeDev`. (It does, and this is fine.)

`flatpak install com.google.Chrome` I'm unsure what should happen: it would be reasonable for it to be treated as either a search term, or a literal app-ID. (In fact it is treated as a search term, and this is fine.)

For the other syntaxes with Flatpak ref syntax in them, I expected to get specifically `com.google.Chrome` or an error similar to "not found"; I did not expect to be offered `com.google.ChromeDev`.

### Actual Behavior

In all cases, I'm offered `com.google.ChromeDev` as a possible match.

**Comment by smcv** [comment]
My understanding had been that the way to get an exact match was to specify the app as a ref, using a format that is as complete as possible.

If that wasn't actually how it's meant to work, then an option like `--exact-match` that turns off the substring ref matching would be another way to resolve this. For instance, with that option, `com.google.Chrome/x86_64/` would still match `app/com.google.Chrome/x86_64/stable` (empty fields should still use a default or act as a wildcard), but shouldn't match `app/com.google.ChromeDev/x86_64/stable` (non-empty fields should be treated as a requirement for an exact match).

**Comment by mwleeds** [comment]
> ### Expected Behavior
> `flatpak install chrome` should search for apps with `chrome` in their names, including both `Chrome` and `ChromeDev`. (It does, and this is fine.)
> 

Agreed

> `flatpak install com.google.Chrome` I'm unsure what should happen: it would be reasonable for it to be treated as either a search term, or a literal app-ID. (In fact it is treated as a search term, and this is fine.)

Treating it as a search term seems correct; otherwise if someone is one letter off from the correct app ID we wouldn't offer the correct one as an option.

> 
> For the other syntaxes with Flatpak ref syntax in them, I expected to get specifically `com.google.Chrome` or an error similar to "not found"; I did not expect to be offered `com.google.ChromeDev`.
> 

What do we want the behavior to be if someone specifies the full ref but gets one letter wrong, e.g. `flatpak install flathub app/com.google.Chrom/x86_64/stable`? Just saying "ref not found" seems pretty user unfriendly. At worst we should at least give a hint.

**Comment by mwleeds** [comment]
> > For the other syntaxes with Flatpak ref syntax in them, I expected to get specifically `com.google.Chrome` or an error similar to "not found"; I did not expect to be offered `com.google.ChromeDev`.
> 
> What do we want the behavior to be if someone specifies the full ref but gets one letter wrong, e.g. `flatpak install flathub app/com.google.Chrom/x86_64/stable`? Just saying "ref not found" seems pretty user unfriendly. At worst we should at least give a hint.

Or perhaps it's not worth worrying about, since typically a full four-part ref might be copy-pasted or produced programmatically, not sure.

**Comment by smcv** [comment]
> Treating it as a search term seems correct; otherwise if someone is one letter off from the correct app ID we wouldn't offer the correct one as an option.

How desirable is that really, though? System-level package managers don't do this with their machine-readable package names, git doesn't do this with branch names, curl doesn't attempt to autocorrect `ttps://example.com`, and so on.

I think the closer our input is to being human-readable text (like `flatpak install chrome`), the more reasonable it is to "do what I mean"; but the closer our input is to being a machine-readable identifier (like `flatpak install app/com.google.Chrom/x86_64/stable`), the more I think we should be doing exactly what the user says (or failing to do so, as appropriate).

For example, Flatpak's shared library is named `libflatpak0` on Debian. I can `apt install libflatpak0:amd64/unstable` (the closest direct equivalent of our 4-part refs), or I can omit parts to get default behaviour (`apt install libflatpak0:amd64`, `apt install libflatpak0/unstable` and `apt install libflatpak0` all do something sensible), but `apt install libflatpak` or `apt install libflatpack0` just tells me (correctly!) that there is no package with that name.

Some Unix tools will try to guess what you meant if you have a typo, but they'll generally give you an error message with suggestions for what you might have meant, rather than silently applying corrections or prompting interactively.

If the default behaviour is to try to guess what the user meant, then I think there'd be value in having a way to be explicit about "don't guess, just do as I say or fail". That could be implicit in writing a string with slashes, or it could be an explicit `--exact-match` option.

**Comment by mwleeds** [comment]
> That could be implicit in writing a string with slashes

Sounds good to me. I actually thought this was already the behavior until you filed this issue. If we want to add a hint in the error message it would be analogous to what git does when you get a command wrong:
```
$ git chckout main
git: 'chckout' is not a git command. See 'git --help'.

The most similar command is
	checkout
```
It's also what compilers tend to do if you get a function name wrong. But either way would probably be fine.
