### ISSUE TITLE
[Feature request]: Easily exclude certain packages from update

### ISSUE THREAD

**Issue by superuser-miguel** [flatpak/flatpak#4830]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I typically update my system using `dnf -y update; flatpak -y update` although on occasion I exclude some packages from being updated for cause, ex: `dnf -y update -x nvidia-* -x dkms*` . This functionality is not currently available in flatpak . Is it feasible to have a `flatpak -y update -x org.blender.Blender` ? There could be instances to update your packages but exclude 1 or 2 for cause. 

I have looked into the man pages and found `flatpak mask` but not sure how this would work in a process to update all other packages, where `-x` is a more elegant solution.

**Comment by mwleeds** [comment]
> I have looked into the man pages and found `flatpak mask` but not sure how this would work in a process to update all other packages, where `-x` is a more elegant solution.

Yes, `flatpak mask` is the supported way to exclude certain Flatpaks from being updated. After using that to mask some updates, you can run `flatpak update` as normal to update the rest. We are unlikely to add another interface for the same functionality unless there's a compelling reason to do so.
