### ISSUE TITLE
install at alternative location

### ISSUE THREAD

**Issue by v1nce** [flatpak/flatpak#4833]
I'm running low on disk storage and I'd like to install new pak at alternative location.
This issue is already described and fixed by

https://github.com/flatpak/flatpak/issues/1224

But, would it be possible to add further enhancement so that you don't have to tweak etc by hand ?
e.g.

flatpak --installation=/alternative/path/foo/ remote-add flathub https://flathub.org 

will take care of creating the necessary entry for us in /etc/flatpak/installations.d/

[Installation "automatic entry 2022-03-31"]
Path=/alternative/path/foo/
DisplayName=automatic entry 2022-03-31
StorageType=harddisk

**Comment by mwleeds** [comment]
Creating a file in `/etc` is a standard thing for administrating a linux system. I'm not sure there's much value in adding a workaround for it, and that would be another use case to maintain when honestly we're already struggling to maintain all the existing functionality.
