### ISSUE TITLE
[Bug]: Authentication required to update (not in SSH session)

### ISSUE THREAD

**Issue by nicekiwi** [flatpak/flatpak#4838]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.2

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

Kubuntu 21.10

### What architecture are you using?

x86_64

### How to reproduce

When updates are available for flatpak, and I try to run the update in KDE Discover I get a message saying 
![image](https://user-images.githubusercontent.com/738975/161642080-6f25eb4c-99cd-4d10-9db3-861d703456e4.png)

`Aborted due to failure (Flatpak system operation Deploy not allowed for user)`

When I run `flatpak update` in Konsole (not in an SSH session) I see:

![image](https://user-images.githubusercontent.com/738975/161642365-16eea3c2-4ba1-47fd-ba6c-fcd301c244e6.png)

And if I say yes, I get this:

```
==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: Ezra Sharp,,, (ezra)
Password: 
```

i enter my password and it says `AUTHENTICATION COMPLETE` then shows:

```
==== AUTHENTICATING FOR org.freedesktop.Flatpak.app-update ====
Authentication is required to update software
Authenticating as: Ezra Sharp,,, (ezra)
Password: 
```

I enter password again and get: 

```==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: Ezra Sharp,,, (ezra)
Password: 
```

That will repeat for every library or app that needs to be updated until it's done or until I run `sudo flatpak update`.

### Expected Behavior

Flatpak updates the apps and libs without requiring my password.

### Actual Behavior

Flatpak asks for my sudo password twice for every app or lib that has an update.

### Additional Information

2 other bugs here reference this issue, but neither have an answer and suggest that this is an issue with running flatpak in an SSH session, which is not the case here.

**Comment by nicekiwi** [comment]
I installed all flatpaks without sudo, but `flatpak list` says "Installation" for all the apps in "System", could that have an impact?

**Comment by smcv** [comment]
> I installed all flatpaks without sudo, but flatpak list says "Installation" for all the apps is "System", could that have an impact?

That's normal, and you need some sort of authorization from polkit to act on the repository that is shared by all users of the system. What is *meant* to happen is that `/usr/share/polkit-1/actions/org.freedesktop.Flatpak.policy` configures polkit so that any user who is logged-in to an active local session (meaning GUI or tty, but not ssh) can update apps and runtimes that are installed system-wide.

However, it looks as though your GUI login session is not being detected by polkit, which breaks that.

The `AUTHENTICATING FOR whatever` prompts also indicate that polkit does not know that your GUI login session is there, or does not know that Discover and Konsole are part of the GUI login session: if it did, then you would be getting a GUI prompt from KDE's polkit agent, not a text-mode prompt from `pkttyagent` via Flatpak itself.

If you run `loginctl session-status`, is your current login session shown? Does it list `State: active`, and a non-empty `Seat` and `TTY`?

Similarly, if you run `loginctl user-status`, does it list your session as active?

It is probably best to report this to your distribution (Kubuntu) as a problem with polkit or the session infrastructure: they will have a much better overview of how your distribution and desktop session are put together than Flatpak developers do.

**Comment by mwleeds** [comment]
> What is meant to happen is that /usr/share/polkit-1/actions/org.freedesktop.Flatpak.policy configures polkit so that any user who is logged-in to an active local session (meaning GUI or tty, but not ssh) can update apps and runtimes that are installed system-wide.


Not quite, it's any user with an active local session who is in the `sudo` or `wheel` group (the exact group is configured at compile time): https://github.com/flatpak/flatpak/blob/ecafded3b19e25622897aa31ee8812a4f5d9eeee/system-helper/org.freedesktop.Flatpak.rules.in#L8

**Comment by mwleeds** [comment]
@nicekiwi you didn't build Flatpak from source right?

**Comment by smcv** [comment]
> Not quite, it's any user with an active local session who is in the sudo or wheel group (the exact group is configured at compile time)

That's a second layer. `/usr/share/polkit-1/actions/org.freedesktop.Flatpak.policy` does what I said, for all users; and then the layer you're thinking of is that `/usr/share/polkit-1/rules.d/org.freedesktop.Flatpak.rules` or `/var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.Flatpak.pkla` (depending on polkit version) additionally lets root-equivalent users install *new* apps and runtimes (as opposed to upgrading existing apps and runtimes, which non-root-equivalent users can do).

**Comment by nicekiwi** [comment]
> @nicekiwi you didn't build Flatpak from source right?

No, I installed from APT and reinstalled, but didn't change anything.

**Comment by nicekiwi** [comment]
> 

from those commands it did see the the session was active, seat was not empty. didn't see reference to `TTY` but it made reference to `chrome-remote-desktop` app.

I uninstalled it and rebooted, then flatpak worked as expected in Discovery and from CLI.

**Comment by smcv** [comment]
> didn't see reference to TTY but it made reference to chrome-remote-desktop app

I think this means logind/polkit were treating chrome-remote-desktop as a non-local login session (like a ssh session), but somehow giving the chrome-remote-desktop session a higher priority than your (KDE?) GUI session for the purposes of deciding which polkit rules to apply, and which authentication agent to use to ask you for your password when authentication is required.

That seems more like a problem with logind, polkit or chrome-remote-desktop than a Flatpak bug.
