### ISSUE TITLE
[Bug]: dbus-daemon/dbus-broker not told to reload after installing new D-Bus services

### ISSUE THREAD

**Issue by sophie-h** [flatpak/flatpak#4849]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.5

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

35/36

### What architecture are you using?

x86_64

### How to reproduce

```sh
$ flatpak install --user https://flathub.org/beta-repo/appstream/org.gnome.World.PikaBackup.flatpakref -y
```

Try to start Pika Backup from GNOME Shell. 

### Way to reproduce

 Try

### Expected Behavior

App starts.

Calling

```sh
$ busctl --user call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ListActivatableNames
```

lists 3 names that contain PikaBackup.

### Actual Behavior

Nothing happens.

Try

```sh
$ busctl --user call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ListActivatableNames
```

and see that none of the three names containing PikaBackup is listed.

### Additional Information

The bug described in https://github.com/bus1/dbus-broker/issues/202#issuecomment-533310276 sounds very similar.

A beta tester posted the issue ["Unable to launch from gnome-shell"](https://gitlab.gnome.org/World/pika-backup/-/issues/193). The problem is reducible on a fresh install of Fedora 35 and 36. It can, for example, be fixed by one of these actions:

- Calling `systemctl reload --user dbus-broker.service`
- Restarting the system
- Replacing the symlinks with the actual files

If Pika was installed before, it will (partially) work after installing the new beta version.

This is blocking the planned release of Pika Backup. Therefore, I would also be grateful for a workaround, even if I'm not doing something wrong.

**Comment by sophie-h** [comment]
I have created a script that creates a flatpak only with a number of activatable services and lists the activatable service names afterward.

- On fresh Fedora 35/36 installs it does not list any activatable names
- On my Debian testing that I use daily, all activatable names are listed

At the same time, installing other apps from Flathub and starting them (via DBus activation) works fine on all systems.

Here is the script if it helps with debugging https://gitlab.gnome.org/-/snippets/3343

**Comment by mcatanzaro** [comment]
> Calling systemctl reload --user dbus-broker.service

This seems like a pretty straightforward workaround

**Comment by chrisawi** [comment]
I think this is https://github.com/flatpak/flatpak/issues/3342

It looks like the last comment there has identified the ultimate cause:

> So it seems that because the services directories do not exist when the session is started, when they are created when a flatpak is installed, DBus does not react to any changes in them.

This does typically work when the export directory already exists, but reloading dbus-broker is probably the only solution to account for when it doesn't.

**Comment by mcatanzaro** [comment]
> I think this is https://github.com/flatpak/flatpak/issues/3342

Agreed.

**Comment by smcv** [comment]
Closing as duplicate of #3342, but I copied this issue report's better title to #3342.
