### ISSUE TITLE
suggestion: flatpak info <app> should show extensive information about a given application

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#485]
I think it would be nice if "flatpak info <app>" was made a bit more extensive in terms of what information it provides. I think it would be nice if for example "flatpak info org.gnome.Builder" would show what permissions and access grants gnome builder has on my system, and whether this particular app is installed system-wide or as --user.

maybe something extensive like:

[bastian@archxps ~]$ flatpak info org.gnome.Builder
Unique ID: app/org.gnome.Builder/x86_64/master org.gnome.Builder-origin 11b875d563ea5d411b86df7a7107732d0c27869cbc3d24eff10e97c9e531211e
Name: GNOME Builder
Version: 3.22.4
Branch: Stable
Application ID: org.gnome.Builder
Installation location: Installed as for --user 'bastian' at ~/.local/share/flatpak/app/org.gnome.Builder
Depends on: org.gnome.Sdk/master
Installed size: 79,62 MB
Upstream URL: https://wiki.gnome.org/Apps/Builder

[Permissions]
 --share=ipc                                                  IPC Access
 --socket=x11                                               XShm Access
 --socket=wayland                                        Wayland Access
 --share=network                                          Network Access
 --filesystem=xdg-run/dconf                          Filesystem Access

**Comment by matthiasclasen** [comment]
yes, that sounds useful

**Comment by matthiasclasen** [comment]
See https://github.com/flatpak/flatpak/pull/755

**Comment by matthiasclasen** [comment]
I think this is mostly in place now
