### ISSUE TITLE
[Feature request]:  Flatpak SDK containing flatpak-builder on Flathub :D

### ISSUE THREAD

**Issue by shuriken1812** [flatpak/flatpak#4864]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Distro - Fedora Silverblue 35

I have my SDKs and Dev tools like VS Codium installed from flathub. However they are not able to access flatpak-builder installed as layered package which ofc it will not be able to see.

 As the system root is blacklisted, there seems to be no way getting VS Codium get the flatpak-builder. 

Solution 1 - Having a way to use system packages (unlikely)
Solution 2 - Having an SDK which has flatpak-builder and use env=FLATPAK_ENABLE_SDK_EXT=something  to get it working.

**Currently there seems to be no way of using flatpak-builder to build flatpaks from a flatpak app for flatpak on flathub. XD**

**A good way to test this would be https://open-vsx.org/extension/bilelmoussaoui/flatpak-vscode inside VS Codium installed from flathub.**

**Comment by mwleeds** [comment]
There is already a flatpak of flatpak-builder: https://github.com/flathub/org.flatpak.Builder

**Comment by shuriken1812** [comment]
> There is already a flatpak of flatpak-builder: https://github.com/flathub/org.flatpak.Builder

There is but it is not provided as an SDK so I can easily use it inside other flatpak containers like Code editors / other development environments installed as a flatpak.

**Comment by kugelzucker** [comment]
> i can't easily use it inside other flatpak containers like Code editors / other development environments installed as a flatpak.
ran into this just now and after finding out about the `FLATPAK_ENABLE_SDK_EXT` env landed here. is there a smart way to solve this issue while staying inside the (nice and tidy) borders of flatpak itself?

**Comment by orowith2os** [comment]
[distrobox](https://github.com/89luca89/distrobox) would probably fit your use cases. Just set the flatpak of VSCode to enter a specific container for your dev stuff.

**Comment by hfiguiere** [comment]
not a flatpak issue. flatpak doesn't build runtimes or packages.

Not sure if flatpak-builder can be run from inside the sandbox though.
