### ISSUE TITLE
[Bug]: readonly filesystem permission disables document portal

### ISSUE THREAD

**Issue by sonnyp** [flatpak/flatpak#4868]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

36

### What architecture are you using?

x86_64

### How to reproduce

If an app that uses file-forwarding for file editing is given `host:ro` - the document portal is disabled, the real file path is passed to the application and saving the file will fail with `Read-only file system`

You can reproduce with [Commit](https://github.com/sonnyp/Commit/) and adding `host:ro`.

```sh
flatpak install re.sonny.Commit

# OK - the app is passed a document portal path
flatpak run --file-forwarding re.sonny.Commit @@ ~/foo.txt @@

# Add host:ro
flatpak --user override re.sonny.Commit --filesystem=host:ro

# KO - the app is passed the real path and saving fails with
flatpak run --file-forwarding re.sonny.Commit @@ ~/foo.txt @@
# GLib.FileError: Failed to create file “/home/sonny/foo.txt.QCU9K1”: Read-only file system
```

### Expected Behavior

The app is passed a document portal path.

### Actual Behavior

file-forwarding / document protal is disabled and the app is passed the real path

### Additional Information

As the author of [Commit](https://github.com/sonnyp/Commit/) - I want to give it `host:ro` permission so that it can access the current working directory in order to display the name of the repository.

If the file is only accessible ro, the document portal should be used and the app should be passed a document portal path so it keeps working as intended. 

I'm not sure about whether the document portal / file-forwarding should be disabled if the app has rw permissions to that file.

**Comment by sonnyp** [comment]
> I think if permission says that specific path is read-only then it's consistent that it isn't writable otherwise there would be bug reports about ability to overwrite read-only files smile 

This is not how it works. An app without filesystem permissions can still read and write an arbitrary file if the document portal (via xdg-desktop-portal or `--file-forwarding`) was used.

I still believe this a bug as it deviates from the documentation

https://docs.flatpak.org/en/latest/flatpak-command-reference.html

> --file-forwarding

> If this option is specified, the remaining arguments are scanned, and all arguments that are enclosed between a pair of '@@' arguments are interpreted as file paths, exported in the document store, and passed to the command in the form of the resulting document path. Arguments between '@@u' and '@@' are considered uris, and any file: uris are exported. The exports are non-persistent and with read and write permissions for the application.

**Comment by Erick555** [comment]
This is exactly how it works. Document portal explicitly [checks](https://github.com/flatpak/xdg-desktop-portal/blob/main/document-portal/document-portal.c#L646-L661) for  `--filesystem` permission and [won't allow](https://github.com/flatpak/xdg-desktop-portal/blob/main/document-portal/document-portal.c#L452) you to overwrite read-only file. You can read form the comments this is intended behavior.

**Comment by sonnyp** [comment]
I had not realized this was intentional. Thanks for clarifying.
