### ISSUE TITLE
[Feature request]: Better cgroup path handling / Make cgroup path persistent

### ISSUE THREAD

**Issue by thjderjktyrjkt** [flatpak/flatpak#4869]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

# The Problem

Currently when a flatpak is started, a corresponding cgroup is created at: `/user.slice/user-$uid.slice/user@$uid.service/app.slice/app-flatpak-$package-$pid.scope` (might be varied by distribution)

It's not very predictable, since the `$pid` part is dynamic, considering a program that tries to work with specific flatpak app in cgroup/pid view, it would have to either:

- check a list of directory under `/sys/fs/cgroup/user.slice/user-$pid.slice/user@$pid.service/app.slice/` and use a wildcard/regexp to match the target app
- or to export the pid where flatpak is started by, then join `app-flatpak-$package-` with `$pid.scope` and use the combined string to look after its cgroup node

both are very inefficient, especially when working with transient configuration tools such as `nftables`.

# My proposal solution

### 1) Change the cgroup node from single to double level

Instead of being a single level of cgroup node with both package name ($package) and the initial pid ($pid):

`...`  `/`  `app.slice`  `/`  `app-flatpak-$package-$pid.scope`  `/`  `...`

 make the directory look like this:

`...`  `/`  `app.slice`  `/`  `app-flatpak-$package.slice`  `/`  `$pid.scope`  `/`  `...`

```
app.slice
|- app-flatpak-some.app.slice
|   |- 100005.scope
|   |   |- ...
|   |   -- ...
|   |
|   -- 100240.scope
|       |- ...
|       -- ...
|
|- app-flatpak-some.other.slice
|   |- 106378.scope
|   |   |- ...
|   |   -- ...
|   |
|   -- 108345.scope
|       |- ...
|       -- ...

...
```

This way an external tool gets a reliable cgroup path to work with: `/user.slice/user-$uid.slice/user@$uid.service/app.slice/app-flatpak-$package.slice`.
This should be the preferred solution.

### 2) Follow the parent process

Make the Flatpak's cgroup scope always the child-node of the parent process.

For example:

```
> systemd-run --slice custom.slice --scope -S
> echo $$
1005567
> exec flatpak run some.app
```

This cgroup will be created: `/custom.slice/app-flatpak-some.app-1005567.scope`

This way, flatpak cgroup path could be defined by an external tool.

This should be the fallback solution when solution 1) is not approachable.

### 3) Allow user defined cgroup node

Add an option in `flatpak-run` that allows user to define which scope a flatpak belongs to.

For example:

```
flatpak run --cgroup="/custom.slice" some.app
```

A sub-node under `custom.slice` will be created, such as `/custom.slice/app-flatpak-some.app-1005567.scope`

This way, flatpak cgroup path could be defined by an external tool.

**Comment by thjderjktyrjkt** [comment]
issues aside, why is `--no-desktop` deprecated? I can't find anything related, searching on github is not helpful. All i found was this:

https://github.com/flatpak/flatpak/blob/8ad534f65c48ff0a91f6f4472924b152752bbf74/common/flatpak-context.c#L1542

Only thing i can assume is due to security concern (because no sandbox).

**Comment by thjderjktyrjkt** [comment]
I believe this is where the naming scheme came from:
https://github.com/flatpak/flatpak/blob/8617ab0ad0243f5ae78f505041566b16d8bb45db/common/flatpak-run.c#L2166

And this is where the cgroup creation is happening:
https://github.com/flatpak/flatpak/blob/8617ab0ad0243f5ae78f505041566b16d8bb45db/common/flatpak-run.c#L2181

According to my brief look at [flatpak-run.c](https://github.com/flatpak/flatpak/blob/main/common/flatpak-run.c).

**Comment by thjderjktyrjkt** [comment]
No a programmer here, can someone explain how `systemd_manager_call_start_transient_unit_sync` came up of nowhere? Can't find any documentation on the web, and it doesn't occur a second time searching through the whole project.

**Comment by thjderjktyrjkt** [comment]
Guess the easier way would be just changing
https://github.com/flatpak/flatpak/blob/8617ab0ad0243f5ae78f505041566b16d8bb45db/common/flatpak-run.c#L2166

to

```c
 name = g_strdup_printf ("app-flatpak-%s.scope", appid_escaped); 
```

But since I'm not sure why PID is included in the first place, it's better not to touch it.

**Comment by smcv** [comment]
> issues aside, why is --no-desktop deprecated?

It's deprecated because it no longer does anything. In old versions of Flatpak, `systemd --user` was required at runtime, unless you used `--no-desktop` to turn that code off. In newer versions of Flatpak, `systemd --user` is used to put app instances in cgroups if possible, but it is not an error to run Flatpak on non-systemd systems.

**Comment by smcv** [comment]
> Change the cgroup node from single to double level

Because of the way the scope names are constructed, you can already do this yourself, if you want to:

```
$ mkdir -p ~/.config/systemd/user/app-flatpak-org.gnome.Recipes-.scope.d
$ cat > ~/.config/systemd/user/app-flatpak-org.gnome.Recipes-.scope.d/local.conf <<EOF
[Scope]
Slice=app-flatpak-org.gnome.Recipes.slice
$ systemctl --user daemon-reload
$ flatpak run org.gnome.Recipes
```

Result:

```
│   │ ├─app.slice (#6966)
│   │ │ ├─app-flatpak.slice (#34210)
│   │ │ │ └─app-flatpak-org.gnome.Recipes.slice (#34243)
│   │ │ │   └─app-flatpak-org.gnome.Recipes-381810.scope (#34309)
│   │ │ │     → user.xdg.inactive-since: 103720720078
│   │ │ │     ├─381810 bwrap --args 41 gnome-recipes
│   │ │ │     ├─381814 bwrap --args 41 xdg-dbus-proxy --args=43
│   │ │ │     ├─381815 xdg-dbus-proxy --args=43
│   │ │ │     ├─381820 bwrap --args 41 gnome-recipes
│   │ │ │     └─381821 gnome-recipes
```

**Comment by smcv** [comment]
> `name = g_strdup_printf ("app-flatpak-%s.scope", appid_escaped); `

For apps that can run more than one instance, that would mix together processes of several different instances (which can have different permissions if you use `flatpak run` command-line options) into a single scope, which I suspect is considered to be undesired.

Flatpak is following https://systemd.io/DESKTOP_ENVIRONMENTS/ for its scope naming: the part labelled RANDOM in that specification is a process ID rather than being truly random, but it fulfils the same purpose of being an arbitrary string chosen to avoid collisions with other instances of the same app.

**Comment by smcv** [comment]
> No a programmer here, can someone explain how systemd_manager_call_start_transient_unit_sync came up of nowhere?

It's in C code provided by Flatpak, but the code is generated by gdbus-codegen at compile-time, rather than being written by hand. It's a call to systemd's `StartTransientUnit()` method, as documented in https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/ and https://www.freedesktop.org/software/systemd/man/org.freedesktop.systemd1.html.

**Comment by thjderjktyrjkt** [comment]
Thank you for your replying. I guess it's much more complicated than it looks.

> Because of the way the scope names are constructed, you can already do this yourself, if you want to
This worked perfectly, and my issue was resolved already. It's just that I've never thought this would be possible.

> the code is generated by gdbus-codegen at compile-time
I'm still having issue setting up the development environment but I'll check that out later.
Is there any `Hello World` equivalent tutorial for systemd programming? specifically this transient cgroup thing?

**Comment by thjderjktyrjkt** [comment]
ok why is there a `app-flatpak.slice`? Not a issue but why?
It wasn't there before the `local.conf` creation

**Comment by smcv** [comment]
> ok why is there a `app-flatpak.slice`? Not a issue but why?
> It wasn't there before the `local.conf` creation

Slice names are hierarchical, with `-` in a slice name behaving like `/` in a directory. If you have `app-flatpak-org.gnome.Recipes.slice`, then you must also have `app-flatpak.slice` and `app.slice` to put it in.

This is a systemd fact, and not really anything to do with Flatpak: see [systemd.slice(5)](https://www.freedesktop.org/software/systemd/man/systemd.slice.html).
