### ISSUE TITLE
Unable to run MonoDevelop with root privileges when installed as regular user. 

### ISSUE THREAD

**Issue by Applebit** [flatpak/flatpak#487]
When i am trying run MonoDevelop as root with flatpak it gives permission denied error. I am not able to understand why sudo is not able to access files in linux.

here is command run by me.
`sudo flatpak run com.xamarin.MonoDevelop `
**Can't find source path /home/ashutosh/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/1.4/989048e48ab6ba026edb19636dd41ceb0f858b36abce038588363a2ad6a9f404/files: Permission denied**

**Comment by jscurtu** [comment]
why would you want to do that?
I am not aware of any scenario where you need to run MonoDevelop as root.

**Comment by Applebit** [comment]
My application need some Linux system library to run so without root I can't really do that.

**Comment by jscurtu** [comment]
that wont work like that, MonoDevelop is sandboxed and does not have access to Linux system Lib. 
You need to use MonoDevelop packaged from your distribution. 

The flatpak'd MonoDevelop only has access to home, network and PolicyKit over d-bus.
