### ISSUE TITLE
[Translation]: Split sentence in flatpak-quiet-transaction.c

### ISSUE THREAD

**Issue by libreajans** [flatpak/flatpak#4877]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

Hi,

IMHO, this sentence from flatpak-quiet-transaction.c, seems split.

> %s Failed to %s %s: %s

```
  g_printerr (_("%s Failed to %s %s: %s\n"),
              non_fatal ? _("Warning:") : _("Error:"),
              op_type_to_string (op_type),
              flatpak_ref_get_name (rref),
              msg);
```
(https://github.com/flatpak/flatpak/blob/main/app/flatpak-quiet-transaction.c#L148) 

### Expected Behavior

We shouldn't split sentences. It's very hard accurately translate a split sentence and may confuse user.

### Actual Behavior

It is a split sentence.

**Comment by mwleeds** [comment]
Fix available in #4963
