### ISSUE TITLE
[Bug]: default --filesystem options cause drag & drop to not work in any path other than $HOME

### ISSUE THREAD

**Issue by Asghwor** [flatpak/flatpak#4882]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.2

### What Linux distribution are you using?

Linux Mint

### Linux distribution version

20.3

### What architecture are you using?

x86_64

### How to reproduce

1. Install any program that has a drag & drop feature, such as Amberol, Clapper or Metadata Cleaner.
2. Try to drag & drop a file / folder from `$HOME` and see it works.
4. Try to drag & drop a file / folder from `/mnt`, `/media` or `/tmp` and see it doesn't work.
5. Try using the file-picker from inside the app to open a file / folder in any of them and see that it actually works.
6. Add these paths to the `--filesystem` of the app using the terminal or Flatseal.
7. Restart the apps.
8. Try to drag & drop items to any of these apps and see that it now works.

### Expected Behavior

It would allow dragging & dropping files / folders from any path that you would be able to do the same using the file-picker.

### Actual Behavior

It doesn't allow dragging & dropping files / folders from certain paths even though you can open them from these same paths using the file-picker.

**Comment by hfiguiere** [comment]
It's not a bug, it's a feature. That's what xdg-desktop-portal is for. Gtk4 use it by default. Including in Amberol (I fixed an issue in the portal, available in 1.18.2, to support directories)
