### ISSUE TITLE
[Bug]: Strawberry music player (Flatpak version) not finding Kvantum style

### ISSUE THREAD

**Issue by linlinxza** [flatpak/flatpak#4884]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

KDE Neon (Ubuntu 20.04)

### What architecture are you using?

x86_64

### How to reproduce

1. Run in terminal: `flatpak install flathub org.kde.KStyle.Kvantum`
2. Install `runtime/org.kde.KStyle.Kvantum/x86_64/5.15-21.08`
3. Run in terminal: `flatpak run --env=QT_STYLE_OVERRIDE=kvantum --filesystem=xdg-config/kvantum:ro org.strawberrymusicplayer.strawberry`

### Expected Behavior

The app should be able to find the Kvantum style like all the other Flatpak apps can.

### Actual Behavior

21:41:52.476 WARN  unknown                          QApplication: invalid style override 'kvantum' passed, ignoring it. 
21:41:52.476 WARN  unknown                              Available styles: Windows, Fusion 
21:41:52.487 DEBUG main:213                         Style: "fusion"

### Additional Information

All the other Flatpak apps can find the Kvantum style. Except for this one.

**Comment by mwleeds** [comment]
Maybe report this issue against the Strawberry Music Player's bug tracker, unless there's some reason to believe it's an issue in Flatpak itself.

**Comment by milkknife** [comment]
>The Kvantum QT6 version is not available for Flatpak.
https://forum.strawberrymusicplayer.org/topic/629/strawberry-flatpak-version-not-seeing-kvantum-style

It's an issue with flatpak

**Comment by milkknife** [comment]
>All the other Flatpak apps can find the Kvantum style. Except for this one.

related: https://github.com/flathub/org.kde.KStyle.Kvantum/issues/16

**Comment by smcv** [comment]
It seems this is an issue with not all versions of the Kvantum style being available, so there is no change that could be made in Flatpak-the-piece-of-software to resolve this.

**Comment by linlinxza** [comment]
> * [Build for Qt6 (`org.kde.Platform//6.x`) flathub/org.kde.KStyle.Kvantum#16](https://github.com/flathub/org.kde.KStyle.Kvantum/issues/16)
> 
>     * https://forum.strawberrymusicplayer.org/topic/629/strawberry-flatpak-version-not-seeing-kvantum-style

I made that post lol

**Comment by linlinxza** [comment]
> It seems this is an issue with not all versions of the Kvantum style being available, so there is no change that could be made in Flatpak-the-piece-of-software to resolve this.

I really wish people would not use Qt6 for this reason. lol

**Comment by linlinxza** [comment]
Here: https://github.com/tsujan

Communicate with each other. Please.
