### ISSUE TITLE
[Feature request]: Make Flatpak apps able to open host applications?

### ISSUE THREAD

**Issue by linlinxza** [flatpak/flatpak#4891]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

It would be great is there was a way to make Flatpak apps able to open other apps on the host OS. 

For example, I use the Flatpak version of KeePassXC. I would like it if the Flatpak version of LibreWolf could use KeePassXC. Until then, I have to use the version native to my distro. But at the same time, I'm really wanting to move away from external PPAs to prevent any potential system breakage.

Or... Is there a way to do this already? Can flatpak-spawn work?

**Comment by rusty-snake** [comment]
https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn

> `--host`
> Run the command unsandboxed on the host. This requires access to the org.freedesktop.Flatpak D-Bus interface

**Comment by linlinxza** [comment]
> https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn
> 
> > `--host`
> > Run the command unsandboxed on the host. This requires access to the org.freedesktop.Flatpak D-Bus interface

I'll try it! Thank you! :)

**Comment by linlinxza** [comment]
> https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn
> 
> > `--host`
> > Run the command unsandboxed on the host. This requires access to the org.freedesktop.Flatpak D-Bus interface

It's not good for the web browser. Any extension that's looking for a host application will cause the browser to crash. So, I'll have to keep using the native version of the web browser. Thank anyways!

**Comment by rusty-snake** [comment]
> Any extension that's looking for a host application will cause the browser to crash. 

If an extension (WebExtension) causes a Browser crash, that's a bug in the Browser.

**Comment by linlinxza** [comment]
> > Any extension that's looking for a host application will cause the browser to crash.
> 
> If an extension (WebExtension) causes a Browser crash, that's a bug in the Browser.

This only happens when using the Flatpak version of LibreWolf. Like I said, the extensions are looking for the apps directly on the host. And that is what's causing the crash.

Guess my hope is to contact each and every extension creator about this.

**Comment by JakobDev** [comment]
Maybe this is related to flatpak/xdg-desktop-portal#705

**Comment by linlinxza** [comment]
> Maybe this is related to [flatpak/xdg-desktop-portal#705](https://github.com/flatpak/xdg-desktop-portal/pull/705)

I don't know how to work that

**Comment by linlinxza** [comment]
> You don#t need to know that.. You only need to wait,until the linked PR is merged, your Distro shipping to new Portals and KeePassXC and LibreWolf make use of them.

Alright then.

**Comment by hfiguiere** [comment]
answered
