### ISSUE TITLE
[Bug]: Can't open / access files inside ~/.var/app/ by flatpak editors

### ISSUE THREAD

**Issue by fastrizwaan** [flatpak/flatpak#4895]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

Flatpak 1.12.7

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

35, 36

### What architecture are you using?

x86_64

### How to reproduce

1. install org.gnome.TextEdit or use flatpaked text editors like scite, geany etc.
2. open a configuration file for say ~/.var/app/io.mpv.Mpv/config/mpv/mpv.conf,
3. these editors can't access/open files from ~/.var/app/ either from GUI or from CLI even with --filesystem=host option

Fedora Silverblue uses flatpaked gedit, so we can't edit configuration files of  other flatpak apps inside ~/.var/app/

### Expected Behavior

Text editors with permissions should be allowed to access files in ~/.var/app

### Actual Behavior

even when mpv.conf file has `#asdf#vo=xv` the file does not load
![image](https://user-images.githubusercontent.com/1161682/168284056-a5062b96-dca7-4670-b5ae-c536dc092b5e.png)

**Comment by rusty-snake** [comment]
Try `flatpak override --user --filesystem=~/.var/app org.gnome.gedit`.

**Comment by fastrizwaan** [comment]
> 
Thanks 
`flatpak run --filesystem=~/.var/app org.gnome.TextEditor  mpv.conf` worked 
but `flatpak run --filesystem=host org.gnome.TextEditor  mpv.conf` does not work

I guess `host` means all mounted filesystems. Why can't `--filesystem=host` work with ~/.var/app files?

**Comment by rusty-snake** [comment]
> I guess host means all mounted filesystems.

Documentation: https://docs.flatpak.org/en/latest/sandbox-permissions.html
but it is missing that flatpak paths like `~/.var/app` or `~/.local/share/flatpak` are hidden too.

**Comment by fastrizwaan** [comment]
> > I guess host means all mounted filesystems.
> 
> Documentation: https://docs.flatpak.org/en/latest/sandbox-permissions.html but it is missing that flatpak paths like `~/.var/app` or `~/.local/share/flatpak` are hidden too.

Thank you.

We just need remember to use `--filesystem=~/.var/app` or add `~/.var/app` in `flatseal`
![image](https://user-images.githubusercontent.com/1161682/168332024-2d8a9af6-4315-4b0d-b327-ad4f45b1279d.png)

**Comment by fastrizwaan** [comment]
/tmp is also not accessible without override

`flatpak override --user --filesystem=/tmp org.gnome.TextEditor`
`flatpak override --user --filesystem=/tmp org.gnome.gedit`

**Comment by rusty-snake** [comment]
But `/tmp` is documented to not being shared with `host`.
