### ISSUE TITLE
[Feature request]: Allow flatpak apps to access /usr/share/themes

### ISSUE THREAD

**Issue by Gornius** [flatpak/flatpak#4896]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Flatpak doesn't load themes if they are in /usr/share/themes - and that's the place where all system-wide themes are placed, including default themes.

This means if DE sets theme - eg. Default Plasma on Fedora, app doesn't load theme set in Plasma.

The workaround is to copy all themes from /usr/share/themes to ~/.themes, but in my opinion in shouldn't be needed - if I'm wrong and this creates security hole, please explain it.

Visual Studio code from flatpak by default on KDE Plasma with dark theme:
![image](https://user-images.githubusercontent.com/34241360/168340438-8f834e48-7608-4212-ad52-613be89a70c9.png)

Visual Studio code from flatpak with copied themes on KDE Plasma with dark theme:
![image](https://user-images.githubusercontent.com/34241360/168340777-c5c96b31-d1f8-4bbd-a4c2-64bd7214a788.png)

**Comment by bigbutch** [comment]
When I try to print in LibreWolf print close nothing happens. I installed flatseal and turned on cups. Still no print. After talking with librewolf ythe asked if I had talked with flatpak.

**Comment by bigbutch** [comment]
U

**Comment by hfiguiere** [comment]
There are extension points for both KDE and Gtk themes.

Punching a hole into the sandbox for this isn't really worth it.
