### ISSUE TITLE
[Feature request]: Document --filesystem details

### ISSUE THREAD

**Issue by sophie-h** [flatpak/flatpak#4897]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I have been struggling with my `--filesystem` flags a lot. Here are some things I have learned so far

- `~/.var/app` is not completely available with `--host`
- `XDG_DATA_HOME/flatpak` is not available with `--host`
- `/var` is not available with `--host`
- `xdg-run/<dir>` will be mounted at the same location as on the host. However, the `XDG_RUNTIME_DIR` inside the flatpak will still be `/run/user/<id>` independent of the host's path. (This makes it hard to know where `xdg-run/dir` is actually mounted inside the flatpak, therefore I filled #4885)
- `xdg-data/flatpak` will be mounted at to two locations, `XDG_DATA_HOME/flatpak` and `.var/app/<appid>/data/flatpak`. It does not seem to be possible to only mount it at one location.
- In `/var` the folders `cache`, `config`, and `data` data are the same as in `.var/app/<appid>`.
- While `/var` cannot be made available in `/run/host` via `--host`, it can be added via `--filsystem=/var`. However, `cache`, `config`, `data`, `tmp` will no longer be available in `/var` or the version from the host if available.
- Folders that are hidden by flatpak will be writable but not persistent
- Some `XDG_` variables from the host are available with `HOST_` prefix
- `HOST_HOME` does not exist. Instead, `HOME` is mounted inside the flatpak at the same location as on the host, and `HOME` is set accordingly.

Maybe some of the things are actually documented but I overlooked them.

**Comment by bbhtt** [comment]
Most of these are now documented at docs.flatpak.org:

> 1. ~/.var/app is not completely available with --host
> 2. XDG_DATA_HOME/flatpak is not available with --host
> 3. /var is not available with --host
> 4. In /var the folders cache, config, and data data are the same as in .var/app/<appid>.
> 5. While /var cannot be made available in /run/host via --host, it can be added via --filsystem=/var. However, cache, config, data, tmp will no longer be available in /var or the version from the host if available.

https://docs.flatpak.org/en/latest/sandbox-permissions.html#reserved-paths

> 6. Folders that are hidden by flatpak will be writable but not persistent

See the line in `--persist` in https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

> 7. Some XDG_ variables from the host are available with HOST_ prefix

https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories
