### ISSUE TITLE
flatpak list doesn't need --app option

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#490]
The help for `flatpak list` indicates that `--app` will make it only list apps, but this seems to be the default behaviour.

**Comment by alexlarsson** [comment]
Yeah, but you can also use `--app --runtime` to list both.

**Comment by allanday** [comment]
Ah, that wasn't obvious. The `--app` option actually made me think that `flatpak list` lists everything by default.

An `--all` option might be more semantically correct.
