### ISSUE TITLE
[Bug]: flatpak failed to run in transient scope

### ISSUE THREAD

**Issue by nicolas-graves** [flatpak/flatpak#4902]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Guix c61746b8aa85bc7d69225f47fc56b1f3821b2d00

### What architecture are you using?

x86_64

### How to reproduce

1. Install flatpak trough `guix install flatpak` and add flathub remote for --user. 
2. On a machine running under Wayland, with pulseaudio and wayland properly configured, install us.zoom.Zoom or com.skype.Client with flatpak. 
3. `flatpak --user --socket=wayland -v run us.zoom.Zoom` or `flatpak --user --socket=wayland -v run com.skype.Client` 

### Expected Behavior

The app should start properly.

### Actual Behavior

The apps fail without warning without the -v flag. 
WIth the -v flag, they fail this way : 
```
F: No installations directory in /gnu/store/rq5c76znkav3f84w4zlm30h2kdxl1gz0-flatpak-1.12.7/etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/graves/.local/share/flatpak
F: Opening user flatpak installation at path /home/graves/.local/share/flatpak
F: Opening user flatpak installation at path /home/graves/.local/share/flatpak
F: /home/graves/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/aded519497b3817b395cf872f38719a7afce74ec838acf49fb1502042d19bc3c/files/lib32 does not exist
F: Allocated instance id 3938481964
F: Add defaults in dir /us/zoom/Zoom/
F: Add locks in dir /us/zoom/Zoom/
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running '/gnu/store/y1h70f99139jsjglxd9af6jsqbsp4gcg-bubblewrap-0.5.0/bin/bwrap --args 34 /gnu/store/033mfs2yk7z4a8a69f70nv6w5ar7r22l-xdg-dbus-proxy-0.1.2/bin/xdg-dbus-proxy --args=36'
F: Running '/gnu/store/y1h70f99139jsjglxd9af6jsqbsp4gcg-bubblewrap-0.5.0/bin/bwrap --args 34 zoom'
```

```
F: No installations directory in /gnu/store/rq5c76znkav3f84w4zlm30h2kdxl1gz0-flatpak-1.12.7/etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/graves/.local/share/flatpak
F: Opening user flatpak installation at path /home/graves/.local/share/flatpak
F: Opening user flatpak installation at path /home/graves/.local/share/flatpak
F: /home/graves/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/aded519497b3817b395cf872f38719a7afce74ec838acf49fb1502042d19bc3c/files/lib32 does not exist
F: Cleaning up unused container id 1681767800
F: Cleaning up per-app-ID state for com.skype.Client
F: Cleaning up unused container id 2762486916
F: Cleaning up per-app-ID state for com.skype.Client
F: Allocated instance id 2145010197
F: Add defaults in dir /com/skype/Client/
F: Add locks in dir /com/skype/Client/
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running '/gnu/store/y1h70f99139jsjglxd9af6jsqbsp4gcg-bubblewrap-0.5.0/bin/bwrap --args 34 /gnu/store/033mfs2yk7z4a8a69f70nv6w5ar7r22l-xdg-dbus-proxy-0.1.2/bin/xdg-dbus-proxy --args=36'
F: Running '/gnu/store/y1h70f99139jsjglxd9af6jsqbsp4gcg-bubblewrap-0.5.0/bin/bwrap --args 34 skype'
```

### Additional Information

Other flatpak apps implementing wayland work (firefox or chromium for instance). I've read a lot of the same issues on the topic, but couldn't find  a working solution, and have seen that "Systemd --user is now optional in 0.6.10" (https://github.com/flatpak/flatpak/issues/160)
Two message errors might be the origin: 
- `F: /home/graves/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/aded519497b3817b395cf872f38719a7afce74ec838acf49fb1502042d19bc3c/files/lib32 does not exist`
- `F: Failed to run in transient scope: No systemd user session available, cgroups not available`

I'm not sure about this first error, I would tend to think the error comes from the second. 
I don't have systemd on my system, but have libcgroup and elogind installed. Might it be a problem with the apps themselves ? I suppose that they are working fine on other systems (at least Zoom supports wayland in principle).

**Comment by smcv** [comment]
> F: Failed to run in transient scope: No systemd user session available, cgroups not available

This is not a fatal error. Flatpak tries to put apps into a `systemd --user` cgroup, but if it can't, it continues anyway (since #160 was closed).

> I don't have systemd on my system, but have libcgroup and elogind installed

If that's the case, then you cannot expect features of `systemd --user` to work; but those features are not mandatory. If you get as far as `Running blahblahblah/bwrap ...` then this is not the root cause of the problem you are having.

**Comment by smcv** [comment]
> F: /home/graves/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/aded519497b3817b395cf872f38719a7afce74ec838acf49fb1502042d19bc3c/files/lib32 does not exist

This is not an error either. You will see this debug message in `flatpak -v run ...` for any app based on the freedesktop.org runtime.

Flatpak is trying to set up `/lib32 -> usr/lib32`, just for completeness, but the runtimes that people genuinely use do not have `/usr/lib32`, so this is unnecessary and doesn't happen.

**Comment by smcv** [comment]
`flatpak -v -v run us.zoom.Zoom` might provide more information.

Comparing the apps' output to a simple, "known-good" app like `org.gnome.Recipes` might also be useful.

**Comment by smcv** [comment]
> On a machine running under Wayland, with pulseaudio and wayland properly configured

Wayland is not an implementation, Wayland is a protocol. If you mean you are running a Wayland compositor - like GNOME Shell, or KDE Plasma, or Sway, or Weston - then please say which one.

> Might it be a problem with the apps themselves ? I suppose that they are working fine on other systems (at least Zoom supports wayland in principle)

Do you mean you are using a pure Wayland session, with no X11 compatibility via Xwayland available?

I would not recommend that as something that is likely to work, particularly if you want to run proprietary apps or apps implemented using non-GTK, non-Qt toolkits.

Proprietary apps and apps that use non-GTK, non-Qt toolkits are often limited to X11-only, which means they require Xwayland in order to work in a Wayland session.

Typically, "larger" Wayland environments like GNOME Shell and KDE Plasma automatically set up Xwayland for you (recent versions of GNOME even start Xwayland on-demand, instead of having it running in the background all the time), but if you're using a smaller or more specialized Wayland environment, it's up to you to provide what your apps need.

**Comment by smcv** [comment]
`org.freedesktop.Platform.GlxInfo` (the `glxinfo` CLI tool, packaged on Flathub) is a good way to check whether X11 compatibility is working correctly.

**Comment by nicolas-graves** [comment]
OK you are right. 
I was using Sway with XWayland disabled, enabled it and both indeed work now (I'll have to test screensharing and all, but will later). 
Thanks a lot for this accurate and quick answer !
