### ISSUE TITLE
[Bug]: Seg fault when flatpak list cant access common/flatpak-dir when running as normal user

### ISSUE THREAD

**Issue by eyduh** [flatpak/flatpak#4908]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.5

### What Linux distribution are you using?

Alpine Linux

### Linux distribution version

Linux 5.15.40-0-lts #1-Alpine SMP x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

Not sure as it started happening randomly, but basically:

1. setup-disk -e -L -m sys /target/disk
2. setup-xorg-base
3. [setup kde plasma](https://wiki.alpinelinux.org/wiki/KDE#Standard_plasma_installation)
4. apk add flatpak

use it for a bit and at some point seemingly at random `flatpak list` stopped working

### Expected Behavior

`flatpak list` to work

### Actual Behavior

seg fault when trying to `flatpak list`

### Additional Information

gdb:

```
Reading symbols from /usr/bin/flatpak...
Reading symbols from /usr/lib/debug//usr/bin/flatpak.debug...
(gdb) run
Starting program: /usr/bin/flatpak list
[New LWP 20507]
[New LWP 20508]
[New LWP 20509]

Thread 1 "flatpak" received signal SIGSEGV, Segmentation fault.
0x00005555555c3967 in flatpak_deploy_get_deploy_data (deploy=deploy@entry=0x0, required_version=required_version@entry=4, cancellable=cancellable@entry=0x0, error=error@entry=0x0) at common/flatpak-dir.c:1388
1388    common/flatpak-dir.c: No such file or directory.
(gdb) thread apply all bt

Thread 4 (LWP 20509 "flatpak"):
#0  0x00007ffff7fbc413 in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7fb972d in ?? () from /lib/ld-musl-x86_64.so.1
#2  0x00007ffff6ca3b74 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 3 (LWP 20508 "gdbus"):
#0  0x00007ffff7fbc413 in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7fb972d in ?? () from /lib/ld-musl-x86_64.so.1
#2  0x00007ffff6cd8b74 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 2 (LWP 20507 "gmain"):
#0  0x00007ffff7fbc413 in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7fb972d in ?? () from /lib/ld-musl-x86_64.so.1
#2  0x00007ffff6d06b74 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 1 (LWP 20503 "flatpak"):
#0  0x00005555555c3967 in flatpak_deploy_get_deploy_data (deploy=deploy@entry=0x0, required_version=required_version@entry=4, cancellable=cancellable@entry=0x0, error=error@entry=0x0) at common/flatpak-dir.c:1388
#1  0x000055555558902f in print_table_for_refs (error=<optimized out>, cancellable=0x0, columns=0x7ffff6da3440, app_runtime=0x0, arch=0x0, refs_array=0x7ffff6c651a0, print_apps=1) at app/flatpak-builtins-list.c:175
#2  print_installed_refs (error=<optimized out>, cancellable=0x0, cols=0x7ffff6da3440, app_runtime=0x0, arch=0x0, dirs=<optimized out>, runtime=<optimized out>, app=1) at app/flatpak-builtins-list.c:379
#3  flatpak_builtin_list (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=<optimized out>) at app/flatpak-builtins-list.c:424
#4  0x000055555557f1b1 in flatpak_run (res_error=0x7fffffffdf50, argv=<optimized out>, argc=<optimized out>) at app/flatpak-main.c:842
#5  main (argc=<optimized out>, argv=<optimized out>) at app/flatpak-main.c:947
```

---

I noticed it because I had used flatpak list to reinstall all user apps as system, and to get info on specific apps that were misbehaving. At some point I was greeted with an error, for instance:

```
$ flatpak info $(flatpak list --columns=app | grep protonmail)
error: NAME must be specified

See 'flatpak info --help'
```

**Comment by smcv** [comment]
> `common/flatpak-dir.c: No such file or directory`

This is because you don't have flatpak source code in your debugging environment. It is nothing to do with the actual cause of the crash.

**Comment by eyduh** [comment]
> 

do I need to do something other than `# apk add flatpak-dev` ? cause I did, and still get

```
Reading symbols from /usr/bin/flatpak...
Reading symbols from /usr/lib/debug//usr/bin/flatpak.debug...
(gdb) run
Starting program: /usr/bin/flatpak list
[New LWP 20975]
[New LWP 20976]
[New LWP 20977]

Thread 1 "flatpak" received signal SIGSEGV, Segmentation fault.
0x00005555555c3967 in flatpak_deploy_get_deploy_data (deploy=deploy@entry=0x0, required_version=required_version@entry=4, cancellable=cancellable@entry=0x0, error=error@entry=0x0) at common/flatpak-dir.c:1388
1388    common/flatpak-dir.c: No such file or directory.

```

**Comment by eyduh** [comment]
Ok, some permissions error it seems. ran as root and `flatpak list` worked fine.

shouldn't I be able to run flatpak list as a normal user?

**Comment by mwleeds** [comment]
> Ok, some permissions error it seems. ran as root and `flatpak list` worked fine.
> 
> shouldn't I be able to run flatpak list as a normal user? I seem to remember doing this before.

Yes, `flatpak list` should work as a normal user.

**Comment by ratijas** [comment]
```
Core was generated by `flatpak list'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055ffc9412544 in flatpak_deploy_get_deploy_data (error=<optimized out>, cancellable=<optimized out>, required_version=<optimized out>, deploy=<optimized out>) at ../flatpak/common/flatpak-dir.c:1477
1477      return flatpak_load_deploy_data (deploy->dir,
[Current thread is 1 (Thread 0x7f8264687a40 (LWP 65321))]
```

This is the error that `flatpak list` blows up with.

Flatpak crashes when parsing malformed app config override. For example, using KDE's new (and not yet ironed out) Flatpak permissions KCM, I somehow ended up with the following config:

![image](https://user-images.githubusercontent.com/6737986/217115371-5750f2c9-ba09-452f-bd95-e7b6a841b211.png)

The bug is gone as soon as I remove the offending override file from `$HOME/.local/share/flatpak/overrides/`.

For now I will remove env editing from our config page from public access until it is fixed at least on our side. But ideally Flatpak should also work on robustness, as to not let users shot themselves so easily.

**Comment by smcv** [comment]
@eyduh, is your crash triggered by malformed app-config overrides, the same as @ratijas? (So far, we don't have enough information to know that.)

@ratijas, do you have out-of-band information that says @eyduh's crash has the same root cause as yours? If not, reporting your crash as a separate issue would perhaps be better, to avoid mixing up two causes for a crash in the same issue thread.

**Comment by eyduh** [comment]
I wouldn't know, I've since switched distro. I'll set up a virtual machine and try it out.

**Comment by eyduh** [comment]
I can't seem to reproduce in the VM. Closing for now

**Comment by ratijas** [comment]
> @ratijas, do you have out-of-band information that says @eyduh's crash has the same root cause as yours?

No, I do not. It's just that the function in the backtrace is the same, and this issue is the only one that mentioned it. I'll open a new bug report then.

**Comment by eyduh** [comment]
I tried to set some invalid overrides using Flatseal because I do often use flatseal to edit permissions or to force GTK apps to use the KDE file picker but I still couldnt reproduce the error. I'll keep an eye on your report as well for a possible solution should this crop up again. C:

**Comment by smcv** [comment]
> I can't seem to reproduce in the VM

Sorry, there's not much we can do with non-reproducible crashes.

I *can* reproduce the maybe-related crash that @ratijas reported, so #5293 is more actionable.
