### ISSUE TITLE
Flatpak install hangs with heavy I/O use.

### ISSUE THREAD

**Issue by niarbeht** [flatpak/flatpak#491]
EDIT: This was on Flatpak 0.8.0, I believe.  Forgot to record that in the original bug report.

It's been stuck at this for over five minutes.  At first, when it hit 195.3MB, it was slowly counting down it's "MB/s" rate, but now it's just been totally frozen for five minutes.

```
flatpak install --user --from Downloads/LibreOffice.flatpakref
Installing: org.libreoffice.LibreOffice/x86_64/fresh
Updating: org.gnome.Platform/x86_64/3.20 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.20 from gnome
No updates.
Installing: org.libreoffice.LibreOffice/x86_64/fresh from org.libreoffice.LibreOffice-1-origin

Receiving delta parts: 13/13 1.6 MB/s 195.3 MB/200.6 MB 3 seconds remaining
```

iotop suggests that there's a lot of disk I/O going on somehow, but when I check df, I don't seem to be changing how much disk is actually being used, so I'm not sure where all the writes are going.  There might be something to advise here on a better way to determine what a process is doing for disk I/O.

I'm using btrfs as my filesystem.  Is this known to cause any issues?

```
Total DISK READ :       0.00 B/s | Total DISK WRITE :      25.15 M/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:      25.51 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND          
  149 be/4 root        0.00 B/s   24.88 M/s  0.00 % 33.47 % [kworker/u16:5]
  150 be/4 root        0.00 B/s  277.75 K/s  0.00 %  0.00 % [kworker/u16:6]
    1 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % init
    2 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kthreadd]
    3 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [ksoftirqd/0]
    5 be/0 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kworker/0:0H]
    6 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kworker/u16:0]
    7 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [rcu_preempt]
    8 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [rcu_sched]
    9 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [rcu_bh]
   10 rt/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [migration/0]
   11 be/0 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [lru-add-drain]
   12 rt/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [watchdog/0]
   13 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [cpuhp/0]
   14 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [cpuhp/1]
   15 rt/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [watchdog/1]
   16 rt/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [migration/1]
   17 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [ksoftirqd/1]
   19 be/0 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kworker/1:0H]
   20 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [cpuhp/2]
   21 rt/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [watchdog/2]

```

/etc/fstab
`UUID=615180fd-1df5-4b79-9d7d-03da1240f80b       /               btrfs           rw,relatime,space_cache 0 0
`

"killall -15 flatpak" and "killall -9 flatpak", run as either my user or as root, don't seem to do anything.

Finally, when attempting to reboot, my system hangs.  I should probably include a picture of the message it gives while doing so.

I'm running Arch Linux 64-bit, updated as of today (20160118), on flatpak-0.8.0.

I'm sure there are troubleshooting steps I'm missing here, but I'm new to flatpak.  What's next to try to figure out what's going on?

**Comment by alexlarsson** [comment]
This is just downloading a few (somewhat large) files. I don't see how this could cause problems on the i/o side.

I see you're using btrfs. Do you by any chance have a low diskspace situation (i.e. nearly full metadata as reported by btrfs filesystem df )?

**Comment by niarbeht** [comment]
I should hope not.  That btrfs install is on a 4TB drive, and about half the space is free (as of about two days ago).  I'll have to check when I get home from work.

**Comment by alexlarsson** [comment]
It doesn't have to be full for the metadata partition to be full though.

**Comment by niarbeht** [comment]
Finally had time to run the command.
```
$ sudo btrfs fi df /
Data, single: total=2.52TiB, used=1.83TiB
System, DUP: total=40.00MiB, used=336.00KiB
System, single: total=4.00MiB, used=0.00B
Metadata, DUP: total=9.00GiB, used=3.04GiB
Metadata, single: total=8.00MiB, used=0.00B
GlobalReserve, single: total=512.00MiB, used=0.00B
```

So, if I'm reading this right, my metadata isn't full.  Should I run a metadata balance anyway just for kicks?  I probably should have made sure I understood btrfs better before experimenting with it...

**Comment by niarbeht** [comment]
After upgrading to 0.8.1, it seems to have magically disappeared.  Possibly.

```
$ flatpak install --user --from Downloads/LibreOffice.flatpakref
Installing: org.libreoffice.LibreOffice/x86_64/fresh
Updating: org.gnome.Platform/x86_64/3.20 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.20 from gnome
No updates.
Installing: org.libreoffice.LibreOffice/x86_64/fresh from org.libreoffice.LibreOffice-3-origin

Receiving delta parts: 0/13 3.0 MB/s 6.1 MB/200.6 MB 1 minutes 3 seconds remaini13 delta parts, 92 loose fetched; 195914 KiB transferred in 125 seconds
```

Huh.  I guess close it?

**Comment by alexlarsson** [comment]
weird...
