### ISSUE TITLE
[Bug]: Gnome Wacom tablet buttons settings are ignored on Electron Flatpak applications on Wayland Session

### ISSUE THREAD

**Issue by jp7677** [flatpak/flatpak#4910]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

36

### What architecture are you using?

x86_64

### How to reproduce

I'm using a Wacom tablet  where I switched the pen buttons with the Gnome Settings Wacom Tablet section (Button 1 to Right Mouse Click etc). 

- This works perfectly for all applications running directly on the host on an X11 session.
- This works perfectly for all Flatpak apps (e.g. Bottles/GTK, VS-Code/Discord which is Electron) on an X11  session.
- This works perfectly for all applications running directly on the host on an Wayland session.
- This works perfectly for GTK applications (e.g. Bottles) within Flatpak on Wayland session. 
- It does *not* work for Electron applications (e.g. VS-Code, Discord or Spotify) within Flatpak on a Wayland session. Here I'm.having the default button mapping.

Reproduction scenario:
1. Start Gnome on Wayland Session
2. Change Wacom Tablet Pen button mapping in Gnome Settings
3. Start VS-Code (or e.g. Discord) FlatPak Application
4. Observe the default the Pen button mapping in VS-Code (or e.g. Discord, Spotify).

### Expected Behavior

The button mapping for VS-Code, Discord (and probably other Electron application) Flatpak applications on a Wayland session is taken over from the host.

### Actual Behavior

The button mapping for VS-Code, Discord, Spotify (and probably other Electron application) Flatpak applications on Wayland not is taken over from the host. 
The behavior is correct though when using X11 instead of Wayland or when using a GTK Flatpak application on Wayland. 

### Additional Information

I'm not sure if this is the correct place for this issue, please redirect me in case I got it wrong.

**Comment by jp7677** [comment]
Alright, I stand corrected, this statement of mine turned out to be wrong:
- This works perfectly for all applications running directly on the host on an Wayland session.
I'm also seeing that e.g. Steam directly on the host is also not using my modified button mapping, so this is more a general Wayland issue with non-GTK applications. 

I'll open an issue at Gnome/Mutter.

**Comment by jp7677** [comment]
Hi @lriesebos Sorry, I haven't opened an issue elsewhere because at that time I wasn't sure where that issue belongs to. I thought Gnome/Mutter* initially, but started to doubt that later. This combined with the state of Wayland for NVIDIA and actually other issues with Wacom tablets (the cursor isn't coming back visible above a GTK4 application (Gnome Settings) after the dual cursor issue had been solved, clicks are ignored on popups (Gnome Calendar) and others) made me realize that I'm a few years to early with my setup for Wayland.

If you decide to open an issue, would you please link that here? I also would like to keep track of this.

* My best guess today is, that this issue here is related to Mutter and XWayland. All apps through XWayland seems to ignore or do not know about the button mapping.

**Comment by UlyssesZh** [comment]
Should not be related to Wayland or Electron. I reproduces this issue with GTK4 and X11.

**Comment by lriesebos** [comment]
I see. I also noticed @jp7677 opened an issue for gnome/mutter to address, not exactly the same, but related, issues https://gitlab.gnome.org/GNOME/mutter/-/issues/2879

**Comment by jp7677** [comment]
I had reported the button mapping issue later in https://gitlab.gnome.org/GNOME/gtk/-/issues/5935 which resulted in https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6168 and https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6169
Unfortunately there hasn't been a GTK3 release since that PR was merged, so the mappings are still inconsistent on Fedora 39. May be that will change by the end of the year considering comments on the GTK3 PR. 
I never had button mapping issues on Gnome X11, hopefully that hasn't changed. Currently tablet  support in Gnome 45 in an X session is unfortunately completely broken (https://gitlab.gnome.org/GNOME/mutter/-/issues/3120), so don't know if anything changed recently.

Other Wayland specific issues like https://gitlab.gnome.org/GNOME/mutter/-/issues/2879 or https://gitlab.gnome.org/GNOME/mutter/-/issues/2658 haven't gotten any attention lately, so tablet support on Gnome Wayland is (at least for me, being interested in mouse emulation with a tablet) still far away :(
