### ISSUE TITLE
[Bug]: unable to install applications

### ISSUE THREAD

**Issue by DoubleShotgun** [flatpak/flatpak#4911]
### Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [x] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

Flatpak 1.6.5

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

20.04

### What architecture are you using?

arm

### How to reproduce

root@localhost:/home/doubles# flatpak --user install '/home/doubles/org.turbowarp.TurboWarp.flatpakref'

### Expected Behavior

Install Turbowarp

### Actual Behavior

error: Failed to open file ?/proc/sys/kernel/random/boot_id?: Permission denied

### Additional Information

I straight up can't install anything.
I even tried every single other methods to install applications and all of them has not work.

**Comment by mwleeds** [comment]
You might try filing a bug with Ubuntu's issue tracker, or updating to a newer Operating System.
