### ISSUE TITLE
Not available on MAC

### ISSUE THREAD

**Issue by 0x414a** [flatpak/flatpak#4916]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I want it to work on the MAC

**Comment by rusty-snake** [comment]
If you mean MacOS, you need to port the Linux Kernel first. ;)

**Comment by calvinweb** [comment]
if you really like flatpak, there are only way to use it, that is sall you mac and buy a pc with linux,lol

**Comment by mwleeds** [comment]
See https://flatpak.org/faq/#Is_Flatpak_tied_to_Linux_
