### ISSUE TITLE
error: The permission of the setuid helper is not correct

### ISSUE THREAD

**Issue by neoedmund** [flatpak/flatpak#4934]
I make a fresh install from building source from github, then 
` flatpak --installations `
returns ` /usr/local/var/lib/flatpak `
(this dir not exists)
then try with `flatpak -v repair` 
```
F: Calling system helper: EnsureRepo
error: The permission of the setuid helper is not correct
```
so , what is this error exactly means , what program is missing setuid?

**Comment by neoedmund** [comment]
After I do repair and install all by root user. 
`flatpak  run com.valvesoftware.Steam`
```
Failed to start proxy for unix:path=/var/run/dbus/system_bus_socket: Error binding to address (GUnixSocketAddress): Address already in use
error: Failed to sync with dbus proxy
```

**Comment by mwleeds** [comment]
Sounds like an issue with the D-Bus tools in your base Operating System. 

> I make a fresh install from building source from github, then `flatpak --installations` returns `/usr/local/var/lib/flatpak` (this dir not exists) then try with `flatpak -v repair`
> 

1. If you use the configure option `--localstatedir=/var` when compiling, Flatpak should use the normal path `/var/lib/flatpak` for the system installation.
2. Generally creating the `/var/lib/flatpak` directory is done by the package manager (rpm/deb) at package install time, but Flatpak can also do it, that's what the `EnsureRepo` call below is about.

> ```
> F: Calling system helper: EnsureRepo
> error: The permission of the setuid helper is not correct
> ```
> 
> so , what is this error exactly means , what program is missing setuid?

This may be helpful: https://lists.debian.org/debian-user/2015/08/msg01066.html

**Comment by mwleeds** [comment]
In the future if you're looking for help with a custom compiled Flatpak, it's best to provide all the commands you used to compile it, and your base OS version. It's also probably best to use the mailing list or chat room (linked in the README) rather than the bug tracker.

**Comment by mwleeds** [comment]
Unfortunately we don't have the resources to do support here.

**Comment by neoedmund** [comment]
> This may be helpful: https://lists.debian.org/debian-user/2015/08/msg01066.html

Thank you . the command `chmod u+s /usr/lib/dbus-1.0/dbus-daemon-launch-helper` mentioned in to post fix the problem instantly. It's really something should be put into  FAQ.

**Comment by Rwarcards762** [comment]
@neoedmund I appreciate you posting this -- in a completely unrelated scenario, I was running into the same issue about "The permission of the setuid helper is not correct" but for `Setroubleshootd`. 

It was the same solution -- the SETUID bit had gotten removed from the `dbus-daemon-launch-helper`, in my case at `/usr/libexec/dbus-1/dbus-daemon-launch-helper`.
