### ISSUE TITLE
[Bug]: Flatpaks that are preinstalled in Fedora Silverblue don't use icon theme located in /.local/share/icons for their in-app icons

### ISSUE THREAD

**Issue by user1-github** [flatpak/flatpak#4960]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

Fedora Linux 36.20220617.0 (Silverblue)

### What architecture are you using?

x86_64

### How to reproduce

-Download a custom icon theme
-Extract it to /.local/share/icons
-Apply it via the command gsettings set org.gnome.desktop.interface icon-theme 'IconThemeName'

### Expected Behavior

Flatpaks should use a custom icon theme for their in-app icons.

### Actual Behavior

The custom icon theme doesn't work for in-app icons.

### Additional Information

According to #3247, I understand that Flatpaks supposedly should use a custom icon theme located in /.local/share/icons. I have the [WhiteSur](https://www.gnome-look.org/p/1405756/) icon theme in that location, but it doesn't work in all of the preinstalled Flatpaks in Fedora Silverblue. As you can see in the screenshots of Text Editor and Image Viewer, some icons revert to the default icon theme, while others show a blank rectangle.
The custom icon theme works only for the app icon of the Flatpaks (in Gnome Dash / Activities Overview), but not for in-app icons.

Edit: I'm not sure if that's really the cause, but the directory structure in Fedora Silverblue is a bit different compared to other distributions. For example, the home directory is "/var/home/user" instead of "/home/user".
On the other hand, if you don't have Silverblue, maybe it's still worth trying to reproduce it because this bug may also not be specific to Silverblue.

![Screenshot from 2022-06-21 13-23-08](https://user-images.githubusercontent.com/56021366/174782995-1ff963b2-449f-4a2f-aedd-be0ed5763995.png)
![Screenshot from 2022-06-21 13-24-23](https://user-images.githubusercontent.com/56021366/174783003-62b05c42-b880-4713-912a-0419996f8060.png)

**Comment by user1-github** [comment]
Another interesting finding: I moved my custom icon theme from "/.local/share/icons" to "/.icons" to see if that will change something. Now the Text Editor started using the custom icons properly. On the other hand, they stopped working in Amberol, and all the other Gnome Flatpaks still either revert to the default icon theme or show blank icons just like before.

So judging by these findings, I think something is broken with the custom icon detection of Flatpak.

![Screenshot from 2022-06-22 19-00-57](https://user-images.githubusercontent.com/56021366/175083218-8feb865f-c848-4b6e-b829-aede9bc1e9d2.png)

**Comment by refi64** [comment]
This sounds like it might be a configuration issue in the Fedora Flatpak runtime itself?

**Comment by user1-github** [comment]
@refi64 Seems you're right. I just tried the Flathub versions of the same Gnome apps and their in app icons work properly. Should I close this issue? (Someone commented about a similar issue in telegram)

**Comment by hfiguiere** [comment]
closing then
