### ISSUE TITLE
flatpak cannot run steam

### ISSUE THREAD

**Issue by oeriu** [flatpak/flatpak#4971]
I recently installed Steam, I don't know about the errors below so I just ignored them and went forward with the next step
<pre>
cabbage:~$ doas flatpak --user install com.valvesoftware.Steam
Looking for matches…
Required runtime for com.valvesoftware.Steam/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: y

com.valvesoftware.Steam permissions:
    ipc                          network               pulseaudio           wayland
    x11                          devices               bluetooth            devel
    multiarch                    per-app-dev-shm       file access [1]      dbus access [2]
    system dbus access [3]       tags [4]

    [1] xdg-music:ro, xdg-pictures:ro, xdg-run/app/com.discordapp.Discord:create
    [2] org.freedesktop.Notifications, org.freedesktop.PowerManagement,
        org.freedesktop.ScreenSaver, org.gnome.SettingsDaemon.MediaKeys,
        org.kde.StatusNotifierWatcher
    [3] org.freedesktop.NetworkManager, org.freedesktop.UDisks2, org.freedesktop.UPower
    [4] proprietary

        ID                                      Branch    Op    Remote    Download
 1. [✓] org.freedesktop.Platform.Compat.i386    21.08     i     flathub    89.0 MB / 101.7 MB
 2. [✓] org.freedesktop.Platform                21.08     i     flathub   153.7 MB / 200.3 MB
 3. [✓] com.valvesoftware.Steam                 stable    i     flathub    12.7 MB / 13.9 MB

Warning: Not exporting file com.valvesoftware.Steam.cmd.metainfo.xml of unsupported type.
Warning: Not exporting file com.valvesoftware.Steam.appdata.xml of unsupported type.
Installation complete.
</pre>
I tried to run it, however says that it is not installed when the application is already installed in the list
<pre>
cabbage:~$ flatpak --user run com.valvesoftware.Steam
error: app/com.valvesoftware.Steam/x86_64/master not installed
</pre>

<pre>
cabbage:~$ doas flatpak list
Name                Application ID                        Version  Branch Installation
Steam               com.valvesoftware.Steam               1.0.0.74 stable user
Freedesktop Platfo… org.freedesktop.Platform              21.08.14 21.08  user
i386                org.freedesktop.Platform.Compat.i386           21.08  user
Mesa                org.freedesktop.Platform.GL.default   21.3.8   21.08  user
default             org.freedesktop.Platform.GL32.default          21.08  user
openh264            org.freedesktop.Platform.openh264     2.1.0    2.0    user
</pre>

I did the update and also the repair command, I had no other clue what's next to fix this. I'm hoping for any answers that can solve this issue.

os: Alpine Linux
1.12.5 Flatpak version

**Comment by smcv** [comment]
> `doas flatpak --user`

If `doas` runs commands as root (like `sudo`), then this is installing Steam "for this user only" as root, which means only root can run it (not what you want).

The two ways to install a Flatpak app are:

1. `flatpak [--system] install` - install system-wide (for all users), into `/var/lib/flatpak`
    * On a well-set-up system, you can do this without being root, with polkit prompting
    * Or you can do this as root by wrapping it in something like `sudo`, `doas` or `pkexec`
    * Any user will be able to run this app
2. `flatpak --user install ...` - install for the current user only, into `~/.local/share/flatpak`
    * This usually only makes sense without `sudo`, `doas`, `pkexec`, etc.
    * Only this user will be able to run this app

**Comment by smcv** [comment]
Not a bug: Flatpak is doing what you asked it to, but you asked it to do something that is very rarely useful.

If you use `sudo` as your privilege-elevation tool, Flatpak will detect this and fail with a helpful error message if you're doing something that is unlikely to be useful, but it doesn't have this special case for `doas` or other less mainstream privilege-elevation tools.
