### ISSUE TITLE
[Bug]: Internationalized reverse domain names are not useable for app-id

### ISSUE THREAD

**Issue by llothar** [flatpak/flatpak#4974]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

36

### What architecture are you using?

x86_64

### How to reproduce

Use a  manifest with an app-id and a punnycode internationalized domain name 

app-id: com.xn--microct-bxa.example

### Expected Behavior

This should not raise an error.  

### Actual Behavior

Using flatpak-builder on this manifest give us  an error 

error: 'com.xn--microct-bxa.example' is not a valid application name: Only last name segment can contain -

### Additional Information

International Domain names are just as normal as other domain names for billions of users outside USA and UK. 

There is absolutely no reason why the "-"  should be restricted in hostnames. 
This is just another anti-pattern of too strict input validation and restriction without reason.

**Comment by smcv** [comment]
> error: 'com.xn--microct-bxa.example' is not a valid application name: Only last name segment can contain -

Changing that error message to give a hint would make sense, perhaps something like:

```
error: 'com.xn--microct-bxa.example' is not a valid application name: Only last name segment can contain - (use _ instead)
```

or a link to https://docs.flatpak.org/en/latest/conventions.html#application-ids.

Please send a merge request to https://github.com/flatpak/flatpak-builder if you're interested in contributing that.

Similarly, https://docs.flatpak.org/en/latest/conventions.html#application-ids could probably be clearer about replacing dashes with underscores, and the fact that IDNs are a common form of name that uses dashes. https://github.com/flatpak/flatpak.github.io is the source for that document.
