### ISSUE TITLE
[Request]: Change how Flatpak is promoted

### ISSUE THREAD

**Issue by TheHooly** [flatpak/flatpak#4983]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Request

Currently Flatpak promotes itself as "a system for building, distributing, and running sandboxed desktop applications on Linux."

However, I believe that this is misleading for users that do not understand the implications of the permission system, and specifically dangerous permissions like X11, PulseAudio, filesystem=host/home, among others.

In its current state, an app can simply declare these permissions in their manifest and Flatpak will grant them these permissions without further user interaction. Compare this to e.g. [Android](https://source.android.com/security/app-sandbox), [iOS](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AuthenticationAndAuthorizationGuide/Permissions/Permissions.html), [MacOS](https://manuals.info.apple.com/MANUALS/1000/MA1902/en_US/apple-platform-security-guide.pdf#page=119), [Windows (only for sandboxed UWP apps)](https://docs.microsoft.com/en-us/windows/uwp/security/intro-to-secure-windows-app-development#41-windows-app-model), where user interaction is mandatory before access to sensitive data is granted.

I am aware that most Windows apps are not sandboxed at all, but Microsoft makes that very clear in their [documentation](https://support.microsoft.com/en-us/windows/app-permissions-aea98a7c-b61a-1930-6ed0-47f0ed2ee15c) and most people do not expect their desktop apps to be sandboxed to begin with: 
> Access all your files, peripheral devices, apps, programs, and registry: The app has the ability to read or write to all your files (including documents, pictures, and music) and registry settings, which allows the app to make changes to your computer and settings. It can use any peripheral devices that are either attached or part of your device (such as cameras, microphones, or printers) without notifying you. It also has access to your location, and can use platform features, such as  location history, app diagnostics, and more, which are denied to most Store apps. You can't control most of the permissions for this app in Settings > Privacy. Note that while the app has the ability to access these resources, it might not actually do so. For more info about what the app collects or uses, review the privacy policy of the developer.

I believe that a false sense of security is worse than being aware that there is no security, as then the user would be more inclined to behave accordingly.
Reference: https://www.jwz.org/xscreensaver/toolkits.html
> And if the screen locker is not secure, then it's better to not lock the screen at all: giving the impression of security when there is no actual security is far worse than having no security at all. It's a matter of expectations: if people don't expect to be able to lock their screens, they'll log out. But if they expect to be able to lock their screens and it doesn't actually work, then they're screwed.

While some frontends like Gnome Software warn about dangerous permissions (X11, filesystem=host/home, but not PulseAudio), others do not, e.g. KDE Discover. As such, it cannot be assumed that users actually review the app's permissions which leads to them blindly trusting the app to declare a policy for themself, essentially making security optional.

I propose that Flatpak rather promotes itself as a framework for building, distributing, and running applications on Linux, and enabling OS developers to build application sandboxes on operating systems that provide the necessary OS-level integrations and APIs (Wayland, PipeWire, portals, prompts, etc.).

Daniel Micay, a security researcher and lead developer of GrapheneOS, had this to say about Flatpak (and Snap):
> It's a fundamentally broken approach to implementing a sandbox. It doesn't draw an actual security boundary and fully trusts the applications. The design choices are being made based on the path of least resistance rather than actually trying to build a proper security model. There's a big difference between opportunistic attack surface reduction like this and an application sandbox, which these are not implementing. They cannot even be used to properly sandbox an application no matter how the application chooses to configure the security policies, even if the app is fully trustworthy and trying to do it. The implementation is not that complete. It could certainly be done properly but it would require a huge amount of work across the OS as a whole treating it as a unified project, along with a massive overhaul of the application ecosystem. I can't see it happening. It requires throwing out the traditional distribution model and moving to a well-defined base OS with everything outside of that being contained in well-defined application sandboxes with a permission model supporting requesting more access dynamically, or having the user select data as needed without granting overly broad forms of persistent access.

In its current state and compared to the progress that other popular operating systems have made in providing meaningful application sandboxes, and the acknowledgements from your own developers that Flatpak doesn't aim to improve security on distros that do not use secure OS APIs like Wayland and PipeWire, I believe it is not adequate for Flatpak to be promoted as a meaningful sandbox.

**Comment by mwleeds** [comment]
> While some frontends like Gnome Software warn about dangerous permissions (X11, filesystem=host/home, but not PulseAudio), others do not, e.g. KDE Discover.

This sounds like an issue to file on KDE's bug tracker, or whatever their process is for suggesting enhancements. It may also make sense to have the Flatpak CLI inform users about which permissions constitute a sandbox escape, similar to what GNOME Software does. Feel free to open a focused issue for that on this issue tracker.

Anyway this issue tracker is for bugs and enhancements for the Flatpak software. For forums designated for open-ended discussion, see the ones linked in the README.
