### ISSUE TITLE
flatpak - Unknown file system path

### ISSUE THREAD

**Issue by CharonIkh** [flatpak/flatpak#4987]
Hello..  I had a problem with the flatpack. I'm trying to install Genshin via Anime Launcher, but it doesn't matter, in order to change the game's installation folder - I need to enter the following commands
`mkdir -p `
and then
`flatpak override`
With this, there was a problem. I want to install the game in HDD, but I get an error

`error: Unknown file system path media/charonkaplya/Backup, Available types: host, host-os, host-etc, home, xdg-*[/…], ~/dir, /dir`
since the path is copied crookedly, I recognized it through the terminal, i.e. it looked like this

`charonkaplya@pop-os:/media/charonkaplya/Backup Plus/s*x with allah$`

Accordingly, I decided that this is the right way, but the error says the opposite, should I replace, add or remove something? I want to install the game exactly in S*x with Allah

This is the complete list of my activities.
```
charonkaplya@pop-os:~$ mkdir -p **/media/charonkaplya/Backup Plus/s*x with allah/**prefix /**media/charonkaplya/Backup Plus/s*x with allah**/game **/media/charonkaplya/Backup Plus/s*x with allah**/temp
charonkaplya@pop-os:~$ flatpak override --filesystem=media/charonkaplya/Backup Plus/s*x with allah com.gitlab.KRypt0n_.an-anime-game-launcher
error: Unknown file system path media/charonkaplya/Backup, Available types: host, host-os, host-etc, home, xdg-*[/…], ~/dir, /dir
```
And these are the **recommendations of the launcher developers**. Maybe I don't understand everything?

First, create some needed directories: (replace **$GAME_PATH** with where you want the game)
`mkdir -p $GAME_PATH/prefix $GAME_PATH/game $GAME_PATH/temp`
Then, grant the flatpak permission to access these paths:
`flatpak override --user --filesystem=$GAME_PATH com.gitlab.KRypt0n_.an-anime-game-launcher`

**Comment by rusty-snake** [comment]
If your path contains a literal `*` you need to escape it.
If your path contains a literal ` ` (space) you need to escape it.

**Comment by CharonIkh** [comment]
> If your path contains a literal `*` you need to escape it. If your path contains a literal ` ` (space) you need to escape it.

I don't have this. Where there are two ** - I wanted to highlight, for easy reading, but I forgot that if you add this to the CODE mode on the forum, they will not change anything. And where * is alone, that is, in the word sex, this is due to the fact that on Reddit it does not allow posting such things without censorship, that is, that's not the point.

**Comment by CharonIkh** [comment]
> If your path contains a literal `*` you need to escape it. If your path contains a literal ` ` (space) you need to escape it.

To be honest, I really hoped that I was dumb, removed all the spaces in the path and unfortunately it did not help(

**Comment by rusty-snake** [comment]
Ok, clarified that.

Is `flatpak override --filesystem=media/...` instead of <code>flatpak override --filesystem=<strong>/</strong>media/...</code> a typo/copy-paste-mistake or your actual command?

**Comment by CharonIkh** [comment]
> Ок, уточнил.
> 
> `flatpak override --filesystem=media/...`Вместо опечатки/копирования-вставки или вашей фактической команды ?`flatpak override --filesystem=**/**media/...`

I am not strong in english. If I understand you correctly. Then it's pasted from the terminal. As I understand it, you think that the error is in "/" , even if you didn't mean it, it's worth a try, I'll write it off right away, I'm sorry if it looks stupid from the outside.

**Comment by rusty-snake** [comment]
Yes because the path you give to `--filesystem` must start with an `/` (or `~`, `xdg-*`, ...).

**Comment by CharonIkh** [comment]
> Yes because the path you give to `--filesystem` must start with an `/` (or `~`, `xdg-*`, ...).

Let's visualize what's happening. This is the folder where I need to change the installation path. It is a separate, external hard drive that connects via USB.

![image](https://user-images.githubusercontent.com/108890524/178121316-1990c0f2-769e-40fa-9ae1-f614d53df72b.png)

And this is what the hell is happening in my terminal at the moment. If it can help, of course. As for the language, all errors are translated in the main part. Maybe I'm still doing something wrong.

![image](https://user-images.githubusercontent.com/108890524/178121379-75569f90-2a7e-4602-8b67-b6642aac61d4.png)

**Comment by rusty-snake** [comment]
1. There is no space after `=`. The syntax is `--filesystem=<PATH>`.
2. `~`, `/`, `xdg-*` (which is not a literal star) have meanings, look at the documentation.
3. You never tried `flatpak override --filesystem=/media/...` right? Because that your command.

**Comment by CharonIkh** [comment]
> 1. There is no space after `=`. The syntax is `--filesystem=<PATH>`.
> 2. `~`, `/`, `xdg-*` (which is not a literal star) have meanings, look at the documentation.
> 3. You never tried `flatpak override --filesystem=/media/...` right? Because that your command.

Ok, i will try it later. I'm very tired, I think your advice will help me, it sounds very logical. I'll write about it tomorrow for sure!

**Comment by JakobDev** [comment]
You should try [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) instead of using the cli

**Comment by hfiguiere** [comment]
An arbitrary path either start with `/` or `~`. See the manpage for `flatpak-override`. So `--filesystem=media/` is invalid.
