### ISSUE TITLE
[bug]: build failed

### ISSUE THREAD

**Issue by neoedmund** [flatpak/flatpak#4989]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.13.3

### What Linux distribution are you using?

Debian

### Linux distribution version

debian 11

### What architecture are you using?

x86_64

### How to reproduce

```
./autogen.sh --disable-documentation 
./configure --localstatedir=/var --disable-documentation
make -j22
```
```
common/flatpak-chain-input-stream.c: In function ‘flatpak_chain_input_stream_get_type’:
/usr/include/glib-2.0/glib/gatomic.h:112:5: error: argument 2 of ‘__atomic_load’ discards ‘volatile’ qualifier [-Werror=incompatible-pointer-types]
```

### Expected Behavior

expect build ok

### Actual Behavior

build failed

### Additional Information

gcc version 12.1.0 (GCC)

**Comment by smcv** [comment]
> /usr/include/glib-2.0/glib/gatomic.h:112:5: error: argument 2 of ‘__atomic_load’ discards ‘volatile’ qualifier [-Werror=incompatible-pointer-types]

This is a bug in GLib when used together with gcc 12 and `-Werror`, not a bug in Flatpak.

The version of GLib in Debian 11 should compile correctly with the version of gcc provided by Debian 11, but gcc 12 is newer than the version included in Debian 11.

**Comment by smcv** [comment]
The GLib bug: https://gitlab.gnome.org/GNOME/glib/-/issues/2418

**Comment by neoedmund** [comment]
Thanks for the info, upgrade GLib solve the problem.
