### ISSUE TITLE
[Bug]: Trying to install a flatpak with --user returns an error.

### ISSUE THREAD

**Issue by oswaldtechnic** [flatpak/flatpak#4998]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

1. Install Fedora 35.
2. Try installing anything using the --user parameter.

### Expected Behavior

Using the --user parameter installs an application for the specific user.

### Actual Behavior

Using the --user parameter returns an error.

```
[jack@ct-primary ~]$ flatpak install --user flathub org.telegram.desktop
Looking for matches…
error: No remote refs found similar to ‘flathub’
[jack@ct-primary ~]$ flatpak install flathub org.telegram.desktop
Looking for matches…

org.telegram.desktop permissions:
    ipc                    network      pulseaudio           wayland
    x11                    devices      file access [1]      dbus access [2]
    bus ownership [3]

    [1] host:ro, xdg-download, xdg-run/pipewire-0
    [2] com.canonical.AppMenu.Registrar, com.canonical.Unity,
        com.canonical.indicator.application, org.ayatana.indicator.application,
        org.freedesktop.Notifications, org.freedesktop.ScreenSaver,
        org.gnome.Mutter.IdleMonitor, org.kde.StatusNotifierWatcher
    [3] org.mpris.MediaPlayer2.tdesktop


        ID                                   Branch Op Remote  Download
 1.     org.freedesktop.Platform.ffmpeg-full 21.08  i  flathub  < 4.2 MB
 2.     org.telegram.desktop.webview         stable i  flathub < 35.9 MB
 3.     org.telegram.desktop                 stable i  flathub < 55.3 MB

Proceed with these changes to the system installation? [Y/n]: 


```

**Comment by rusty-snake** [comment]
You need to setup flathub for the user installation as well.

**Comment by oswaldtechnic** [comment]
> You need to setup flathub for the user installation as well.

I see. I ran the command to add a repo with --user.

`flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

That seems to have fixed the issue. I honestly would not have thought of that otherwise.
