### ISSUE TITLE
Flatpak misses app-name rules

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#50]
```
$ flatpak remote-ls gnome-apps --app

org.gnome.Builder
org.gnome.Calculator
org.gnome.Calendar
org.gnome.Characters
org.gnome.Dictionary
org.gnome.Epiphany
org.gnome.Evince
org.gnome.Maps
org.gnome.Polari
org.gnome.Rhythmbox3
org.gnome.Todo
org.gnome.Weather
org.gnome.bijiben
org.gnome.clocks
org.gnome.eog
org.gnome.gedit
org.gnome.iagno
```

Some app names start with capital some lowercase. 

On http://flatpak.org/developer.html there isn't some name ruling for the packaging. Should be camel case, hyphen split, all lower-cases etc?

**Comment by alexlarsson** [comment]
Its not true that there are *no* app names rules. They have to be valid dbus names, and in fact, if you're using dbus in your app you need to have the same app name as dbus name for things to work.

This means that its complicated for many of the above names to change, since they have pre-existing dbus names which are a form of ABI.

However, I guess we should give some kind of recommendation for new apps. I wonder if there is some recommendation for dbus? @smcv do you know of any?

**Comment by smcv** [comment]
The prefix is a domain that you own/control,  and the suffix is up to you. That's the extent of the rules. "You" might mean an individual, a company/corporation, or a community like GNOME.

It seems to be vaguely conventional that the prefix indicating the namespace (author, publisher, etc.) is all-lowercase, and the part indicating the project within that namespace has initial caps; so org.gnome.Evince is "Evince as defined by gnome.org", and org.freedesktop.Telepathy.AccountManager is "Telepathy.AccountManager as defined by freedesktop.org". That isn't a strict rule or anything though.

**Comment by smcv** [comment]
> They have to be valid dbus names

In particular this means you can't use hyphens. You can use underscores, but it's relatively unconventional to do so.

In the corner cases where you have a domain name that isn't a syntactically valid D-Bus name, I'd recommend replacing `-` with `_` and prepending `_` before any digits that start a component, so the owner of `7-zip.org` might publish an app named `org._7_zip.Archiver`.

**Comment by matthiasclasen** [comment]
Not sure there's anything to fix here. Somebody could send a request to add that 'corner-case' recommendation to the docs at flatpak.readthedocs.io
