### ISSUE TITLE
[Feature request]: Switch to g_info() for --verbose messages

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#5001]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

At the moment, Flatpak has this output:

* normally: GLib's implicit default, `G_LOG_LEVEL_MESSAGE` and up (from any domain)
* with `--verbose`: `G_LOG_LEVEL_DEBUG` and up for the `flatpak` domain
* with `-v -v`: `G_LOG_LEVEL_DEBUG` and up, both for the `flatpak` domain and a separate `flatpak2` domain

This can result in reviewers not wanting some `g_debug()` messages to be emitted, because they are too verbose and would be confusing to users of `flatpak -v`. But having a separate `flatpak2` domain for extra-verbose messages is also odd, and will cause those messages to be skipped if you run with `G_MESSAGES_DEBUG=flatpak`, which is unlikely to be what anyone expected.

In steam-runtime-tools, which recycles quite a lot of Flatpak code, I've had good results from this setup:

* normally: GLib's implicit default, `G_LOG_LEVEL_MESSAGE` and up (from any domain)
* with `--verbose`: `G_LOG_LEVEL_INFO` and up
* with my project's equivalent of `-v -v`: `G_LOG_LEVEL_DEBUG` and up

`G_MESSAGES_DEBUG` also activates both `G_LOG_LEVEL_INFO` and `G_LOG_LEVEL_DEBUG` messages from the selected domains. I think that makes this a good pattern to encourage in any GLib-based software.

Does that sound like a reasonable model for Flatpak? If yes, the way to get there would be:

* change all `g_debug()` to `g_info()`
* change all `flatpak_debug2()` to `g_debug()`, and remove `flatpak_debug2()`
* optionally review the debug messages and check whether any are at the wrong level

**Comment by mwleeds** [comment]
SGTM but it looks like Alex is the one who added the flatpak2 domain: aec35fd9d9e9b4e0ee3473216066354ea290be06
