### ISSUE TITLE
[Bug]: Various Flatpak test failures due to fusermount error

### ISSUE THREAD

**Issue by TheComputerGuy96** [flatpak/flatpak#5027]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Arch Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Have an **up-to-date** Arch Linux install ready using the Arch install guide
2. Install all the dependencies listed in the Flatpak PKGBUILD
3. Clone the Flatpak Arch package build files
4. Run `makepkg -s` in the directory with the build files

(these instructions are bad, but I want to quickly post this issue)

### Expected Behavior

There should be no test failures

### Actual Behavior

There are ~26 test failures because of this error:
```
+ fusermount -u /tmp/test-flatpak-iyk1Fm/runtime/doc
fusermount: entry for /tmp/test-flatpak-iyk1Fm/runtime/doc not found in /etc/mtab
```

Which causes the failing tests to say `too few tests run`

### Additional Information

The error above shows up near all failing tests

I also tried building 1.13.3 but I get the same error (and I tried rebooting my system too)

BTW my build has a patch to remove ptrace from blocked syscalls (VMProtect needs ptrace for some reason), but i doubt that would affect the results

**Comment by swick** [comment]
The output is misleading but the root cause is simply `fuse3` not being installed. E.g. in the toolbox a `sudo dnf install fuse3` fixed the issue. Seems like the arch PKGBUILD needs updating as well.

Still running into issues on toolbox but they are unrelated. This issue can be closed.
