### ISSUE TITLE
opening a file that is on a restricted filesystem seems to permanantly allow access to this file

### ISSUE THREAD

**Issue by abc-mikey** [flatpak/flatpak#5028]
As has been discussed in many other issues, I would like to sandbox my applications and prevent them from accessing sensitive files in my home.

Testing this I can see that files that the application wants to open are in accessible as long as filesystem permissions are set to no. 

If I try and open a file via a dialogue then the application is grated access to that file regardless of where it is. This is apparently down to xdg-desktop-portals.

Accepting that this is the designed behaviour, I would have expected is that this access is only granted for the current session, but it appears that once granted the access is permanent. 

At a very minimum I would expect some way to view and revoke permissions, short of uninstalling the entire application.

**Comment by rusty-snake** [comment]
> At a very minimum I would expect some way to view and revoke permissions, short of uninstalling the entire application.

- `flatpak documents`
- `flatpak document-info`
- `flatpak document-export`
- `flatpak document-unexport`
- `flatpak documents --columns=origin | tail -n+1 | xargs -d"\n" -L1 flatpak document-unexport`

**Comment by abc-mikey** [comment]
uninstalling the application didn't work, but this did. Thank you very much @rusty-snake!
