### ISSUE TITLE
[Bug]: GLib-GIO-CRITICAL after sending SIGINT

### ISSUE THREAD

**Issue by pabloab** [flatpak/flatpak#5032]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.11.1

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

20.04

### What architecture are you using?

x86_64

### How to reproduce

1. Install mpv: `flatpak install flathub io.mpv.Mpv`
1. Run `flatpak run io.mpv.Mpv anyvideo.webm` (same with avi and any format I tried).
1. Press <kbd>Ctrl+C</kbd> (SIGINT).

### Expected Behavior

Just to stop.

### Actual Behavior

Stops and this is sent to stderr:
```
(process:2): GLib-GIO-CRITICAL **: 18:25:10.679: g_dbus_connection_emit_signal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
(process:2): GLib-GIO-CRITICAL **: 18:25:10.685: g_dbus_connection_unregister_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
(process:2): GLib-GIO-CRITICAL **: 18:25:10.685: g_dbus_connection_unregister_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

### Additional Information

Following [this](https://github.com/mpv-player/mpv/issues/10488) mpv issue and [this](https://github.com/flathub/io.mpv.Mpv/issues/81) mpv flatpak package issue. [They believe](https://github.com/flathub/io.mpv.Mpv/issues/81#issuecomment-1207197959) the issue should be addressed here.

Of course, I could hide this (and all stderr) with `2> /dev/null` but maybe flatpak developers are interested in handling SIGINT and close everything gracefully. Even removing the session bus (using Flatseal) [doesn't stop the error](https://github.com/flathub/io.mpv.Mpv/issues/81#issuecomment-1207115242) message from showing up.

**Comment by smcv** [comment]
This isn't a Flatpak bug. The process ID in the messages is 2, indicating that they're being emitted by a process inside the container created by Flatpak, which is almost certainly mpv (of course, the bug could be in any library or loadable module loaded by mpv, not necessarily mpv itself).

**Comment by smcv** [comment]
If you run mpv as

```
G_DEBUG=fatal-criticals flatpak run io.mpv.Mpv /path/to/some/video
```

it will crash after emitting the first critical warning. The crash dump collected by systemd-coredump indicates that, yes, this is the `/app/bin/mpv` process inside the container, and the bug is probably in its `/app/etc/mpv/scripts/mpris.so` plugin.
