### ISSUE TITLE
[Bug]: Mixed DPI monitor setup not working correctly for many applications

### ISSUE THREAD

**Issue by hzulla** [flatpak/flatpak#5033]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04 (with their default Gnome configuration on Wayland)

### What architecture are you using?

x86_64

### How to reproduce

1. Connect two monitors to your computer
2. Configure one to 100% scaling, the second to 200% scaling
3. Use previous .deb version of Firefox on pre-22.04 versions of Ubuntu
4. .deb-Firefox is scaled correctly on each monitor, 100% on the first one and 200% on the second one.
5. Move .deb-Firefox from one monitor to the other, it will switch scaling correctly as it enters the other screen.
6. Now upgrade to 22.04 Ubuntu and remove snap-Firefox
7. Install various flatpak applications, including flatpak-Firefox
8. flatpak-Firefox will always be scaled at 200%, even when moving them to the 100% monitor.
9. Same goes for Thunderbird, Signal, VLC, GIMP
10. Meanwhile, flatpak Noson and Inkscape behaves as expected and switches scaling according to each monitor

### Expected Behavior

Expected consistent scaling behaviour for each app

### Actual Behavior

It's hit and miss. Even regressions for Firefox and Thunderbird, which worked correctly as .deb but now do not as flatpak.

### Additional Information

I am unsure whether this is a generic or an app-specific bug. I can file this for each applications individually, but there seems to be a generic problem behind this when apps that used to work correctly as .deb now do not scale correctly any more.

**Comment by smcv** [comment]
I suspect the important difference between .deb and Flatpak here might be that in a Wayland desktop session, Flatpak apps that support both Wayland and X11 are usually only given access to the Wayland socket for better sandboxing (unless it doesn't exist, in which case they're given access to the X11 socket instead), whereas non-sandboxed .deb apps always get access to both.

Please try this, exiting from Firefox completely after each one:

```
# X11 only
flatpak run --nosocket=fallback-x11 --socket=x11 --nosocket=wayland org.mozilla.firefox

# Wayland only
flatpak run --nosocket=fallback-x11 --nosocket=x11 --socket=wayland org.mozilla.firefox

# both available, app's choice
flatpak run --nosocket=fallback-x11 --socket=x11 --socket=wayland org.mozilla.firefox
```

and similar for the other problematic apps.

Another possibility is that the apps that have regressed might have been built with different options, different patches and/or different versions between the .deb version available from Ubuntu and the Flatpak version available from Flathub.

**Comment by hzulla** [comment]
> Please try this, exiting from Firefox completely after each one

Okay, thanks. Indeed, flatpak-Firefox and flatpak-Thunderbird both worked as desired with these command line options:

`flatpak run --nosocket=fallback-x11 --nosocket=x11 --socket=wayland`

(My system runs on Wayland.)

So, should I report this to the individual flatpak packagers of each affected application or is this a generic problem?

**Comment by smcv** [comment]
> flatpak-Firefox and flatpak-Thunderbird both worked as desired with [`--nosocket=fallback-x11 --nosocket=x11 --socket=wayland`]

This indicates that they handle mixed-DPI correctly when forced to use Wayland...

> did not work: `--nosocket=fallback-x11 --socket=x11 --socket=wayland`

... but this strongly suggests that they default to using X11 if both X11 and Wayland are available, and do not behave as you would expect when using X11 in a mixed-DPI Xwayland setup.

This might well be unfixable other than by making those apps prefer Wayland, because I don't think X11 has a concept of mixed-DPI at all.

In any case this is not a bug in Flatpak itself.

**Comment by Erick555** [comment]
> > flatpak-Firefox and flatpak-Thunderbird both worked as desired with [`--nosocket=fallback-x11 --nosocket=x11 --socket=wayland`]
> 
> This indicates that they handle mixed-DPI correctly when forced to use Wayland...

This is suspicious as those apps don't even work on native wayland out of the box. How they work without x11 socket then? Could they escape sandbox through abstract socket?

**Comment by hzulla** [comment]
@Erick555 

> How they work without x11 socket then?

I have no idea.

Jjust tested again to be sure:

I can confirm that on my Ubuntu 22.04 default installation with Wayland and a two-monitor setup, Thunderbird works as expected with `--nosocket=fallback-x11 --nosocket=x11 --socket=wayland`: It will display its window and the UI will change its scaling according to the monitor's scaling settings it is moved to.

UI also appears as expected with `--nosocket=fallback-x11 --socket=x11 --socket=wayland` and with `--nosocket=fallback-x11 --socket=x11 --nosocket=wayland`, but in both cases Thunderbird will not change scaling when moving between monitors.

Let me know if there's any way I can help debugging this on my system.

**Comment by hzulla** [comment]
Reported to Firefox upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1784447
