### ISSUE TITLE
[Bug]: `--filesystem=/usr/share/aspell:ro` has no effect (unable to add subdirectories of `/usr/share` with `run --filesystem=…` or `override --filesystem=…`)

### ISSUE THREAD

**Issue by posita** [flatpak/flatpak#5040]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Pop!_OS

### Linux distribution version

5.18.10-76051810-generic #202207071639~1659403207~22.04~cb5f582

### What architecture are you using?

x86_64

### How to reproduce

I am using [flathub/org.gnu.emacs](https://github.com/flathub/org.gnu.emacs) and am unable to use Emacs' spell checking functionality because `/usr/share/aspell` is not available in the execution environment. (See https://github.com/flathub/org.gnu.emacs/issues/14#issuecomment-1213088686.) I cannot cure this on my own, because `flatpak override --user --filesystem=/usr/share/aspell:ro` is not honored at runtime.

``` sh
% flatpak override --user --filesystem=/usr/share/aspell:ro --socket=ssh-auth org.gnu.emacs
% flatpak info --show-permissions org.gnu.emacs                                                                                
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
filesystems=/var/tmp;/usr/share/aspell:ro;/tmp;host;
```

### Expected Behavior

I would expect that Emacs (and processes started therefrom) would be able to see `/usr/share/aspell` after I explicitly added that path to the runtime configuration, but that's not the case.

### Actual Behavior

``` sh
% flatpak run org.gnu.emacs
emacs-wrapper-wrapper: Setting up NPM packages                                                                                                          
emacs-wrapper-wrapper: Setting up Cargo packages
emacs-wrapper-wrapper: Setting up Python packages
Gtk-Message: 08:09:15.524: Failed to load module "appmenu-gtk-module"
Gtk-Message: 08:09:15.558: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:09:15.558: Failed to load module "canberra-gtk-module"
```

From within Emacs, I run `M-x shell` and am still unable to see `/usr/shared/aspell`:

``` sh
sh-5.1$ ls /usr/share/aspell
ls: cannot access '/usr/share/aspell': No such file or directory
sh-5.1$ aspell dicts
[no output]
```

**Comment by smcv** [comment]
Mounting a `--filesystem` below `/usr` is not intended to be possible. The same is true for `/app` and a few other reserved paths.

The `/usr` provided by the Flatpak runtime is read-only, so Flatpak cannot mount arbitrary directories over its subdirectories (that would require teaching bubblewrap to be able to mount overlay filesystems).

Mounting arbitrary host directories into the runtime's `/usr` is also not a good idea even if it was possible, because in general, the libraries and versions in a Flatpak runtime will not be compatible with the libraries and versions on the host system.

**Comment by posita** [comment]
Oh! I see now. `/usr/bin/aspell` comes from elsewhere. Is there a way to see where so I can approach the owner of that location? I'm getting multiple hits on what Emacs can see:

``` sh
% cd ~ && find .local -name aspell | xargs md5sum | awk '$1 == "fb9497c6d53f6ca0e5006aa0d8af94bd"'
fb9497c6d53f6ca0e5006aa0d8af94bd  .local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/c7252386179c4c1ecf5d93bdaec6ca82852dddfdae7112b5c3177f7424c4a928/files/bin/aspell
fb9497c6d53f6ca0e5006aa0d8af94bd  .local/share/flatpak/runtime/org.freedesktop.Sdk/x86_64/21.08/829d2745d7122e1669f0dabdc8a1906effb7a41b5f30bebbded350089b779b06/files/bin/aspell
fb9497c6d53f6ca0e5006aa0d8af94bd  .local/share/flatpak/runtime/org.gnome.Platform/x86_64/42/ac7d5eca440d2bb783676c2a2e75bb1f8b5c85ea5a5fa0e7354200b766f810c7/files/bin/aspell
```

How do other folks add dictionaries and similar static data to their builds?

**Comment by posita** [comment]
See https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1242.
