### ISSUE TITLE
[Feature Request] Autosuggest To Remove Runtime After Last Depending App Has Been Uninstalled

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#506]
Flatpak supports having different runtimes. As such, a user might install apps that depend on different runtimes. However, the user might decide to uninstall a set of apps (such as GNOME nightly apps, or apps that depend on an older gnome runtime). This leaves the runtime installed and the user, with time, will have multiple zombie runtimes on his/her system. As such, it would be nice if flatpak would suggest, after the uninstallation of the last app depending on a certain runtime, to remove the runtime itself.

**Comment by alexlarsson** [comment]
This is somewhat complicated, because multiple installations may refer to the runtime. For instance maybe you have a per-user installed app still using the system installed version of the runtime.

However, you're right, we could always *mention* this so the user can manually decide what to do.

**Comment by alexlarsson** [comment]
Alternatively, we could have a command to look for unused runtimes, in case you ran some unattended update command that made the runtime unused.

**Comment by LaurentBonnaud** [comment]
A good start would be a way to display the dependencies between apps and runtimes.  For instance this could be added to "flatpak info".

**Comment by matthiasclasen** [comment]
flatpak info does show it:

$ flatpak info org.gnome.Recipes//master
Ref: app/org.gnome.Recipes/x86_64/master
ID: org.gnome.Recipes
Arch: x86_64
Branch: master
Origin: gnome-nightly-apps
Commit: 59cc716ffe5d7a2cf6ff075770cb3b73ab6fa606518c2cb240f9ec12d1dc7c8b
Location: /var/lib/flatpak/app/org.gnome.Recipes/x86_64/master/59cc716ffe5d7a2cf6ff075770cb3b73ab6fa606518c2cb240f9ec12d1dc7c8b
Installed size: 10.7 MB
Runtime: org.gnome.Platform/x86_64/master

**Comment by gjsieben** [comment]
Definitely necessary. Otherwise, we could be clogging systems up with unused runtimes over a long period of time.

**Comment by rstrube** [comment]
Has there been any progress on this?  It would be really useful to have an command line option like "flatpak autoremove" to remove old, unused zombie runtimes.

**Comment by rolfen** [comment]
Yes, please. As far as I'm concerned - from a user pespective, flatpak is littering my SSD with hundreds of megabytes of leftovers (in `/var/lib/flatpak` or `~/.local/share/flatpak`) and after uninstalling flatpak I have to go in and remove them manually.

Having multiple installations of flatpak sounds like an edge case to me.

I have posted a related issue here:
https://github.com/flatpak/flatpak/issues/1391

**Comment by pasha-pivo** [comment]
+1. Flatpak takes A LOT of space in my case. Those two apps do not need so much data. I am pretty sure that maximum 500M of ~5G actually can be used by them.

**Comment by Leeo97one** [comment]
So, still no way to know which runtime is unused?

**Comment by Leeo97one** [comment]
Oh sorry, I just saw the 0.11.8 changelog. Seems to be a good step forward. :ok_hand:

**Comment by nekohayo** [comment]
These days there is the command `flatpak uninstall --unused` which seems to work well, though it still relies on the user thinking about running it (or even thinking about its existence). Shouldn't that check command just be run whenever the user uninstalls something, no matter if it's the "last one" to use the runtime or not? It was instantaneous on my side so I don't see the cost of chaining it up.

**Comment by tliron** [comment]
@matthiasclasen Could you explain why this was closed? Has this feature been implemented?

**Comment by matthiasclasen** [comment]
@tliron as the last comment says: flatpak uninstall --unused works well

**Comment by afranke** [comment]
> flatpak uninstall --unused works well

I’m not so sure about that. Here it offers to remove things that seem to be used.

```
$ flatpak list
Ref                                                    Options     
com.visualstudio.code.oss/x86_64/stable                user,current
org.audacityteam.Audacity/x86_64/stable                user,current
org.blender.Blender/x86_64/stable                      user,current
org.darktable.Darktable/x86_64/stable                  user,current
org.gimp.GIMP/x86_64/stable                            user,current
org.gnome.Builder/x86_64/master                        user,current
org.gnome.Calendar/x86_64/stable                       user,current
org.gnome.Fractal/x86_64/stable                        user,current
org.gnome.Maps/x86_64/stable                           user,current
org.gnome.Recipes/x86_64/stable                        user,current
org.gnome.Weather/x86_64/stable                        user,current
org.inkscape.Inkscape/x86_64/stable                    user,current
org.perezdecastro.Revolt/x86_64/master                 user,current
org.stellarium.Stellarium/x86_64/stable                user,current
org.audacityteam.Audacity.Codecs/x86_64/stable         user,runtime
org.freedesktop.Platform.GL.default/x86_64/1.6         user,runtime
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0  user,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6        user,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08      user,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6             user,runtime
org.freedesktop.Platform.html5-codecs/x86_64/18.08     user,runtime
org.freedesktop.Platform/x86_64/1.6                    user,runtime
org.freedesktop.Platform/x86_64/18.08                  user,runtime
org.freedesktop.Sdk.Extension.rust-stable/x86_64/1.6   user,runtime
org.freedesktop.Sdk.Extension.rust-stable/x86_64/18.08 user,runtime
org.freedesktop.Sdk/x86_64/1.6                         user,runtime
org.gnome.Platform/x86_64/3.24                         user,runtime
org.gnome.Platform/x86_64/3.26                         user,runtime
org.gnome.Platform/x86_64/3.28                         user,runtime
org.gnome.Platform/x86_64/3.30                         user,runtime
org.gnome.Platform/x86_64/master                       user,runtime
org.gnome.Sdk.Docs/x86_64/3.26                         user,runtime
org.gnome.Sdk.Docs/x86_64/3.28                         user,runtime
org.gnome.Sdk.Docs/x86_64/master                       user,runtime
org.gnome.Sdk/x86_64/3.26                              user,runtime
org.gnome.Sdk/x86_64/3.28                              user,runtime
org.gnome.Sdk/x86_64/master                            user,runtime
org.kde.KStyle.Adwaita/x86_64/5.11                     user,runtime
org.kde.Platform/x86_64/5.11                           user,runtime

$ flatpak uninstall --unused
Uninstalling from user:
org.audacityteam.Audacity.Codecs/x86_64/stable
org.audacityteam.Audacity.Locale/x86_64/stable
org.darktable.Darktable.Locale/x86_64/stable
org.freedesktop.Platform.GL.default/x86_64/1.6
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0
org.freedesktop.Platform.Locale/x86_64/1.6
org.freedesktop.Sdk.Extension.rust-stable/x86_64/1.6
org.freedesktop.Sdk.Extension.rust-stable/x86_64/18.08
org.freedesktop.Sdk.Locale/x86_64/1.6
org.gimp.GIMP.Locale/x86_64/stable
org.gnome.Calendar.Locale/x86_64/stable
org.gnome.Fractal.Locale/x86_64/stable
org.gnome.Maps.Locale/x86_64/stable
org.gnome.Platform.Locale/x86_64/3.30
org.gnome.Platform/x86_64/3.24
org.gnome.Platform.Locale/x86_64/3.24
org.gnome.Platform/x86_64/master
org.gnome.Platform.Locale/x86_64/master
org.gnome.Recipes.Locale/x86_64/stable
org.gnome.Sdk.Docs/x86_64/3.26
org.gnome.Sdk.Locale/x86_64/3.26
org.inkscape.Inkscape.Locale/x86_64/stable
org.kde.KStyle.Adwaita/x86_64/5.11
org.kde.Platform.Locale/x86_64/5.11
Is this ok [y/n]: n
```

Why does it want to remove `Audacity.Codecs` or any of the `.Locale`?

**Comment by matthiasclasen** [comment]
Please open a new issue to report a new issue. And please don't forget to specify your flatpak version when doing so. Thanks!

**Comment by nill14** [comment]
`$ flatpak update
Looking for updates…
Info: org.freedesktop.Sdk//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.VAAPI.Intel//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
`

This is confusing. Is it possible to add there a text: "You can remove unused runtimes by `flatpak uninstall --unused` command?
