### ISSUE TITLE
[Bug]: Apps installed through flatpak hides the app installed through apt or deb in App Menu

### ISSUE THREAD

**Issue by XRohitKS** [flatpak/flatpak#5063]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [x] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7-1

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04.1

### What architecture are you using?

x86_64

### How to reproduce

1. Install any flatpak app and also from apt or deb file
2. so now we have two SAME apps.
3. since the name of both apps is same so ubuntu only detecting one app in system menu.

### Expected Behavior

Both apps must be shown but only one is shown in application menu because of same names of .desktop files

### Actual Behavior

Actually both apps must be shown but only one is shown.
The posible solution is that ::
Create symlinks of flatpak apps at "/var/lib/flatpak/exports/share/applications" with <app_name>.flatpak.desktop so that the system detects both the apps.

**Comment by AdrianVovk** [comment]
I’d say this is intended behavior. What use-case do you have for having both copies of an app around?

**Comment by hfiguiere** [comment]
Not a flatpak bug. #4790 is a complain that they are indistinguishable (like in gnome shell)
