### ISSUE TITLE
Can't install from local repo when offline

### ISSUE THREAD

**Issue by owtaylor** [flatpak/flatpak#507]
(I don't think this is the same as #35)

Running a development script on a plane:

+ flatpak --user remote-add --if-not-exists --no-gpg-verify PurpleEgg-devel /home/otaylor/Projects/PurpleEgg/_flatpak/_flatpak/repo
+ flatpak --user install PurpleEgg-devel org.gnome.PurpleEgg
Warning: Problem looking for related refs: Error resolving 'sdk.gnome.org': No address associated with hostname
Updating: org.gnome.Platform/x86_64/master from gnome-nightly
error: Error resolving 'sdk.gnome.org': No address associated with hostname

**Comment by alexlarsson** [comment]
Hmm, i believe this is flatpak trying to see if there is an updated runtime for the install.
The installation still succeeded, though, right?
Maybe we should report this better.

**Comment by owtaylor** [comment]
No, the installation didn't succeed. There's both a warning and an error above, and it seems like the error is fatal and keeps the actual installation from happening.
