### ISSUE TITLE
Flatpak from Official PPA for Ubuntu(20.04.5) Not Working as intended

### ISSUE THREAD

**Issue by CapeCrusader321** [flatpak/flatpak#5071]
I am using Ubuntu 20.04.5, i had to reinstall ubuntu 20.04.5 after a messy upgrade to 22.04.1, earlier as per flatpak quick setup page for ubuntu i added the Flatpak ppa by alex larsson termed official  by flatpak and it used to work properly but in my new installation i observed that the previous ppa i used doesnt have latest flatpak version and on going directly to flatpak site's quick setup for ubuntu i discovered a new ppa containing the latest version but maintained by Flatpak team as per the ppa, The  new ppa after proper following of all procedures and a restart , Flatpak refuses to download apps from flathub and gives the following output-

**_Warning: Could not unmount revokefs-fuse filesystem at /var/tmp/flatpak-cache-QIC6R1/org.gtk.Gtk3theme.Greybird-R97BS1: Child process exited with code 1_** 

Earlier the flatpak used to run properly i think there is something wrong with the maintainers and the ppa so i decided to raise the issue with flatpak instead of Ubuntu first, Flatpak recommends two different ppas for ubuntu, the one maintained by alex is old but works and the new one termed as by flatpak team is malfunctioning.

PLEASE LOOK INTO THIS URGENTLY AND PROVIDE A FIX, FLATPAK IS A LIFELINE FOR ME ON MY UBUNTU DESKTOP......

Here are the two different flatpak pages recommending two different ppas-
A) https://flatpak.org/setup/Ubuntu
B)https://flatpak.org/setup/Ubuntu

BOTH TECHNICALLY SEEMS SAME BUT LOOKING AT THEIR PPAs one can differenciate.
A) https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak
B)https://launchpad.net/~flatpak/+archive/ubuntu/stable (The ppa having the latest but the buggy version)

**Comment by CapeCrusader321** [comment]
IMAGE FOR REFERENCE-


![FlatBug](https://user-images.githubusercontent.com/100503303/187915769-5be4fe87-ea45-44ba-848e-86526a4f0c68.png)

**Comment by smcv** [comment]
> Here are the two different flatpak pages recommending two different ppas-
> A) https://flatpak.org/setup/Ubuntu
> B)https://flatpak.org/setup/Ubuntu

Those are the same link.

> https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

That PPA hasn't been updated for quite a long time, because only Alex can update it.

> https://launchpad.net/~flatpak/+archive/ubuntu/stable

That's the correct one to use.

**Comment by CapeCrusader321** [comment]
Installing fuse3 affects the dependency of other packages, i first deduced the same solution but it affects the packages using fuse and yes i do respect the efforts of the volunteers and the community.


![Flatfuse](https://user-images.githubusercontent.com/100503303/188036296-1fac94ab-5e2d-499d-80f8-5a6d8f27c68b.png)

**Comment by CapeCrusader321** [comment]
Currently its working, Thanks for checking out...
