### ISSUE TITLE
Doing "npm install" at build time

### ISSUE THREAD

**Issue by casept** [flatpak/flatpak#508]
I'm trying to package [pibakery](https://github.com/davidferguson/pibakery) as a flatpak (link to my repo: https://github.com/casept/flatpak-pibakery). What's blocking my progress is the fact that the installation requires running `npm install` after cloning the pibakery repo. This fails with
`npm ERR! fetch failed https://github.com/beeman/node-df/tarball/master`.
I remember reading somewhere that flatpak does not permit access to the network once the dependencies have been pulled in order to ensure reproducibility. Unfortunately, this also breaks the build procedure. Is it possible to allow access to the network during the build somehow?
The only other ways to solve this would be to either:
- Fork the repo and vendor the packages
- Convince upstream to do so
- Use some crazy hacks to do the `npm install` on the host system

None of these options are appealing to me for obvious reasons.

**Comment by alexlarsson** [comment]
Its not recommended to do this, as it makes the build non-repeatable, but you can add a build-options either globally or in the module that needs it, which has a build-args that contains --share=network. This lets you access the network during the buil.d
