### ISSUE TITLE
[Bug]: cross-architecture SDKs not found by flatpak 1.6.x

### ISSUE THREAD

**Issue by talregev** [flatpak/flatpak#5080]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.6.5

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

20.04

### What architecture are you using?

x86_64

### How to reproduce

1. sudo apt update 
1. sudo apt install -y flatpak flatpak-builder qemu-system-arm qemu-user-static
1. sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
1. sudo flatpak install -y flathub org.gnome.Sdk/aarch64/42 flathub org.gnome.Platform/aarch64/42

In general it cannot find when I install:
sudo flatpak install -y flathub
- org.gnome.Sdk/aarch64
- org.gnome.Platform/aarch64
- org.freedesktop.Platform/aarch64
- org.freedesktop.Sdk/aarch64
- org.gnome.Sdk/arm
- org.gnome.Platform/arm
- org.freedesktop.Platform/arm
- org.freedesktop.Sdk/arm

### Expected Behavior

Install the aarch64/arm Platform and Sdk.

### Actual Behavior

```bash
Looking for matches…
error: Nothing matches org.gnome.Sdk in remote flathub
```

### Additional Information

![image](https://user-images.githubusercontent.com/7043539/188499685-8cdda29b-8ed5-4adb-b7af-f9a69cc6a388.png)

**Comment by smcv** [comment]
I think this might be fallout from [#4880](https://github.com/flatpak/flatpak/pull/4880).

If it is, then a workaround would be to use Flatpak 1.10 or newer (perhaps from [the PPA](https://launchpad.net/~flatpak/+archive/ubuntu/stable/)) if you are trying to cross-compile.

**Comment by smcv** [comment]
Flatpak 1.6.x is no longer supported by the Flatpak developers. Your distribution (Ubuntu) might have some level of support for their version of Flatpak 1.6.x, but probably only for security fixes, and not for ordinary bug fixes or features.

Ubuntu 22.04 LTS is their newest LTS release, and has a newer version of Flatpak (1.12.x).

**Comment by talregev** [comment]
For ubuntu 22.04 LTS I have other issue with flatpak. (Certificate issues). But before that. The github action is ubuntu 20.04, and I cannot change that. How I can install the latest flatpak? There is pps? 
Thank you for your quick answer.

**Comment by rusty-snake** [comment]
> There is pps?

https://github.com/flatpak/flatpak/issues/5080#issuecomment-1237374566:

> perhaps from [the PPA](https://launchpad.net/~flatpak/+archive/ubuntu/stable/)

**Comment by talregev** [comment]
the command to add the ppa:
`sudo add-apt-repository ppa:flatpak/stable`
?

**Comment by talregev** [comment]
Thank you for your quick respond. This is solve the issue!
