### ISSUE TITLE
[Bug]: can't run any flatpaks, ldconfig failed, exit status 34560

### ISSUE THREAD

**Issue by agoogleuser** [flatpak/flatpak#5081]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [ ] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

KUbuntu 22.04.1

### What architecture are you using?

x86_64

### How to reproduce

Two methods:
A) From GUI as every application:
run from taskbar or application runner 

B) from terminal using `flatpak run <appname>`

### Expected Behavior

Application opens

### Actual Behavior

A) Program simply doesn't run.

B)error output the following
```
error: ldconfig failed, exit status 34560
```

### Additional Information

I've updated everything to the latest, run `flatpak repair`, purged and reinstalled flatpak and nothing new happened. I've searched for this error code on goggle and it found nothing.

**Comment by agoogleuser** [comment]
I fixed the issue by basically removing everything related to flatpaks then reinstalling, 

- Uninstall all flatpaks on my Kubuntu

```
flatpak uninstall -all
```
- Removed `flatpak` and its dependencies doing the following
```
sudo apt --autoremove flatpak
sudo purge flatpak
sudo autoremove
sudo clean
```
- Reinstalled flatpak
```
sudo apt install flatpak
```
- added flathub and kdeapps flatpak repositories
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --if-not-exists kdeapps --from https://distribute.kde.org/kdeapps.flatpakrepo
```
- Installed a small app from Discover in order to download required flatpaks to run application, such as KHangMan from kdeapps repo, then it ran after downloading multiple stuff.

**Comment by cyangalaxy** [comment]
For anyone who has this (or similar) issue:

Make sure `~/.var/app `and its subdirectories have Read+Write permission and that you (the user) are the owner.

**If the folders have a little lock-icon, you need to fix the permissions by running:**

`sudo chown -R your_username:your_username /home/your_username/.var/app`

This will fix it
