### ISSUE TITLE
[Bug]: Can't link to libflatpak from meson file

### ISSUE THREAD

**Issue by Lestibournes** [flatpak/flatpak#5087]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Pop!_OS

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

Create GNOME application project in GNOME Builder that's installed as a native package (same problem with the flatpak package, though)
Add an include for flatpak.h
add libflatpak to the dependencies, alongside libadwaita-1
Click Run

### Expected Behavior

My app should compile and run without error.

### Actual Behavior

I get an error saying that it can't find libflatpak.

### Additional Information

Tried every method I could find to add the flatpak library to the build file/compiler, but I just keep getting a message that /usr/include/flatpak doesn't exist, even though it does exist and I have libflatpak-dev installed and the header files are there.

I tried using `gcc 'pkg-confiv -cflags flatpak' ` to compile a test source file that includes flatpak.h, and it worked.

Either I'm an idiot that doesn't understand the meson docs, which is possible, or for some strange reason libflatpak isn't registered on the system in a way that allows meson to see it, which would be extremely weird.

**Comment by smcv** [comment]
> add libflatpak to the dependencies

The dependency is called `flatpak`, not `libflatpak`. In general, if a project has a `.pc` file, then the name of the `.pc` file (without `.pc`) is the name you need to give to Meson. Some projects (like libadwaita and libpng) have chosen to include the `lib` prefix in the name of their `.pc` file, because they consider it to be part of their project's name. Other projects (like flatpak and GTK) don't include the prefix.

> I tried using `gcc 'pkg-confiv -cflags flatpak'`

I don't think you did, because that's not how pkg-config is spelled, and the option to list compiler flags is `--cflags`. Please be precise when programming: the computer can't guess what you mean.

Here is a minimal Meson project which successfully calls into libflatpak on my system. `meson.build`:

```meson
project('flatpak-issue-5087', 'c')
flatpak = dependency('flatpak')
executable('flatpak-issue-5087', 'main.c', dependencies: [flatpak])
```

and `main.c`:

```c
#include <stdio.h>
#include <flatpak.h>

int main(void)
{
  printf ("%d\n", flatpak_error_quark ());
  return 0;
}
```

Please try that. The expected result is that running the compiled `flatpak-issue-5087` executable from a terminal should print a nonzero number.

> I get an error saying that it can't find libflatpak

Please quote the actual error message if you report other bugs in future.

**Comment by Lestibournes** [comment]
I started a fresh GNOME Application project to make sure it's not me. Here is the entire src/meson.build file after updating it according to what you wrote:

```
freddi_sources = [
  'main.c',
  'freddi-window.c',
  'freddi-application.c',
]

flatpak = dependency('flatpak')

freddi_deps = [
  dependency('libadwaita-1', version: '>= 1.0'),
  flatpak
]

gnome = import('gnome')

freddi_sources += gnome.compile_resources('freddi-resources',
  'freddi.gresource.xml',
  c_name: 'freddi'
)

executable('freddi', freddi_sources,
  dependencies: freddi_deps,
  install: true,
)

```

I added the line `#include <flatpak.h>` to the includes section of src/main.c.

Here is the relevant output from building the project:
```
Run-time dependency flatpak found: NO (tried pkgconfig and cmake)

../../../../../../Projects/freddi/src/meson.build:7:0: ERROR: Dependency "flatpak" not found, tried pkgconfig and cmake
```

> I don't think you did, because that's not how pkg-config is spelled, and the option to list compiler flags is --cflags. Please be precise when programming: the computer can't guess what you mean.

I had some typos I didn't catch when writing the bug report. Notice that I wrote that I used it and it worked.

**Comment by smcv** [comment]
> Dependency "flatpak" not found, tried pkgconfig and cmake

If `pkg-config --cflags flatpak` works when you run it manually, but doesn't work when GNOME Builder does the same thing, then there must be something different about the environment in which GNOME Builder is building the project. Try building the project manually, from a terminal?

**Comment by Lestibournes** [comment]
You're right. Building from terminal does work. The problem is with Builder, not Flatpak. I'll have to submit the report on their bug tracker.

**Comment by Lestibournes** [comment]
But report on Builder:
[https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/1784](https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/1784)
