### ISSUE TITLE
[Bug]: Flatpak update and install returns 503 Service Unavailable

### ISSUE THREAD

**Issue by ipkpjersi** [flatpak/flatpak#5088]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak update`
2. It fails with `error: Server returned status 503: Service Unavailable`

### Expected Behavior

I expect flatpak to update my applications.

### Actual Behavior

A 503 error is returned.

### Additional Information

This issue happens on my desktop running Ubuntu 22.04 LTS and on my Steam Deck as well. Also, running `sudo flatpak update`  doesn't help either, it still returns a 503.

Also, further, I get a 503 from this URL: https://dl.flathub.org/repo/appstream/com.anydesk.Anydesk.flatpakref

![](https://i.imgur.com/f4Cpojh.png)

Is this a known issue, or possibly something on my end?

**Comment by martywd** [comment]
@ipkpjersi typed:
`Is this a known issue, or possibly something on my end?`

I'm seeing this issue as well on Linux Mint 21 MATE 64-bit, flatpak 1.12.7-1.  I thought maybe it was a VPN issue, but I've tried several different connects, but all return the error 503.
.

**Comment by smcv** [comment]
This seems like a problem with the Flathub service, rather than Flatpak. If your web browser and Flatpak both report the same error, then Flatpak is working as designed and it's Flathub (maintained by different people) that is not working correctly.
