### ISSUE TITLE
libflatpack runtime

### ISSUE THREAD

**Issue by Lestibournes** [flatpak/flatpak#5089]
I'm making an app that interacts with libflatpak and want to package it as a flatpak, but I can't find any runtime, at least not on Flathub, that offers libflatpak, nor did I find a forum. Therefor I'm requesting help here.

**Comment by JakobDev** [comment]
You can't access Flatpak from inside the Sandbox

**Comment by Lestibournes** [comment]
> You can't access Flatpak from inside the Sandbox

That sounds like a design flaw. How can someone distribute a frontend for Flatpak as a Flatpak if it's blocked? Also, I think Fedora has a runtime that includes Flatpak, although I haven't tried since it's in a different repo and I want what I'm doing to work on any repo.

**Comment by hfiguiere** [comment]
1. you would build the dependency part of your flatpak
2. yes you can't access flatpak from inside the sandbox.
