### ISSUE TITLE
Some Flatpaks fail to launch when XDG_CURRENT_DESKTOP is set to 'X-Cinnamon'

### ISSUE THREAD

**Issue by pvaret** [flatpak/flatpak#5092]
Flatpak version: 1.12.7

When environment variable XDG_CURRENT_DESKTOP is set to 'X-Cinnamon', some flatpaks fail to run. For example:

```shell
$ flatpak run com.obsproject.Studio                                                                                                                   
Gtk-Message: 17:34:06.017: Failed to load module "xapp-gtk3-module"

(obs:2): GLib-GIO-ERROR **: 17:34:06.034: Settings schema 'org.cinnamon.desktop.interface' is not installed
```

Whatever the actual issue, the smoking gun here appears to be `Settings schema 'org.cinnamon.desktop.interface' is not installed`. The schema in question is correctly installed on my machine:

```shell
$ ls -l /usr/share/glib-2.0/schemas/org.cinnamon.desktop.interface.gschema.xml
-rw-r--r-- 1 root root 11153 Jan 25  2022 /usr/share/glib-2.0/schemas/org.cinnamon.desktop.interface.gschema.xml
```

However, this schema is not in any of the Flatpak runtimes:

```shell
$ find ~/.local/share/flatpak/runtime/ -name org.cinnamon.desktop.interface.gschema.xml | wc -l
0
```

For some reason, the Gnome equivalent does ship with several Flatpak runtimes:

```shell
$ find ~/.local/share/flatpak/runtime/ -name org.gnome.desktop.interface.gschema.xml | wc -l
7
```

This is a recent problem. The very same flatpaks used to run fine a few months ago.

As a workaround, unsetting the `XDG_CURRENT_DESKTOP` env variable before running the flatpak fixes the issue. Setting this variable to 'GNOME' also fixes the issue.

It feels like either Flatpak should trust the XDG_CURRENT_DESKTOP variable that comes out of the sandbox and then use the 'settings schema' (whatever those are...) from outside the sandbox, or it should ignore that variable.

**Comment by pvaret** [comment]
Thanks! I observed the issue on rather a lot of Flatpaks, so it was not clear to me the problem was in the Flatpaks themselves.

I will try and identify if there is a common dependency between the faulty Flatpaks that may need updating -- I don't know exactly which one ships this QGnomePlatform component.

I'll note that having an environment variable from outside the sandbox affect the behavior of code inside the sandbox in a potentially breaking way does feel like a breach of isolation. What do you think?

**Comment by smcv** [comment]
> I will try and identify if there is a common dependency between the faulty Flatpaks that may need updating -- I don't know exactly which one ships this QGnomePlatform component.

I think the KDE runtime ships it, but if individual Qt apps bundle their own Qt rather than using the KDE runtime, they might also bundle QGnomePlatform.

> I'll note that having an environment variable from outside the sandbox affect the behavior of code inside the sandbox in a potentially breaking way does feel like a breach of isolation

The trust boundary is one-way: Flatpak apps trust the host system, but the host system does not trust Flatpak apps (unless they have suitably powerful permissions).

A few environment variables are specifically filtered, but a lot of them have to inherit from the host system into the sandbox, otherwise we'd be breaking the expectations of random app components. Flatpak always has to strike a balance between two extremes: too much isolation, and people will complain that their app isn't "native" enough; not enough isolation, and the app will arbitrarily fail to work (as in this case).

**Comment by pvaret** [comment]
Spot-checking a few broken Flatpaks does point to `org.kde.Platform` as the culprit (versions 5.15-21.08 and 6.3 at least). All Flatpaks that depend on it are currently broken for Cinnamon users, it seems.

Thank you for the explanations and for opening the follow-up bug with the QGnomePlatform project! I hope they will fix it soon.
