### ISSUE TITLE
[Bug]: Using `--socket=gpg-agent`and `--filesystem=xdg-run/gnupg` at the same time crash flatpak

### ISSUE THREAD

**Issue by ImBearChild** [flatpak/flatpak#5095]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.0

### What Linux distribution are you using?

openSUSE

### Linux distribution version

MicroOS 20220906

### What architecture are you using?

x86_64

### How to reproduce

1. run or build an application with `--socket=gpg-agent` and `--filesystem=xdg-run/gnupg` at the same time
2. see it crash with SIGSEGV

### Expected Behavior

From my view, there should be a warning instead of crash with `SIGSEGV`. Maybe we can mark `--filesystem=xdg-run/gnupg` as outdated and encourage developers (and packagers) to use `--socket=gpg-agent`.

### Actual Behavior

```
> flatpak --verbose --ostree-verbose run --socket=gpg-agent --filesystem=xdg-run/gnupg runtime/org.freedesktop.Platform/x86_64/22.08
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/tux/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/tux/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/tux/.cache/flatpak/ld.so/8f7c2af590399b2779abe46e1b50f979cdf106914e6b338627ff7727723db6b5
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/32aada23b18a565e838e55391259789242e9177d2820ad90c1750f8e94de044a/files/lib32 does not exist
F: Running: 'bwrap --args 20 ldconfig -X -C /run/ld-so-cache-dir/8f7c2af590399b2779abe46e1b50f979cdf106914e6b338627ff7727723db6b5.7PAXFU'
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/32aada23b18a565e838e55391259789242e9177d2820ad90c1750f8e94de044a/files/lib32 does not exist
F: Cleaning up unused container id 3116562629
F: Allocated instance id 2657008602
F: Add defaults in dir /org/freedesktop/Platform/
F: Add locks in dir /org/freedesktop/Platform/
F: Disallowing ipc access
F: Disallowing network access
fish: Job 1, 'flatpak --verbose --ostree-verb…' terminated by signal SIGSEGV (Address boundary error)
```

### Additional Information

There's some earlier discussion: 

https://github.com/flathub/flathub/pull/3182#issuecomment-1242996427
https://github.com/flathub/org.kde.kleopatra/issues/1

**Comment by travier** [comment]
Likely introduced with https://github.com/flatpak/flatpak/pull/4958

**Comment by tyrylu** [comment]
I could not reproduce the crash on Archlinux with Flatpak 1.15.1 and using org.gnome.Platform 43 instead of the org.freedesktop.Platform runtime mentioned in the example command.

**Comment by smcv** [comment]
> see it crash with SIGSEGV

If you can reproduce a crash, please provide a [backtrace](https://www.suse.com/support/kb/doc/?id=000016799) for that crash.

**Comment by smcv** [comment]
Actually, never mind, I can reproduce this on Debian 12 with Flatpak 1.14.1.

**Comment by smcv** [comment]
This doesn't seem to be anything to do with combining `--socket=gpg-agent` with `--filesystem=xdg-run/gnupg`. I get a crash almost every time that I use `--socket=gpg-agent` on a test machine, independent of whether I add `--filesystem=xdg-run/gnupg` or not. When I only use `--filesystem=xdg-run/gnupg` I don't get a crash.

@ImBearChild, does this match what you see?

**Comment by smcv** [comment]
> From my view, there should be a warning instead of crash

At the risk of stating the obvious, any crash is a bug that should be fixed, even if it only occurs with an unusual combination of options. Fixing bugs will happen more quickly if you can provide a minimal reproducer (in this case, any use of `--socket=gpg-agent`) or a backtrace.

I suspect this means you are the first person to have seriously tried to use `--socket=gpg-agent`, which makes me wonder how much testing was done on the PR that added it.

> Likely introduced with #4958

Well, yes, if the minimal steps to reproduce a bug include use of a particular feature, then obviously having that feature is a prerequisite for seeing the bug :-)

**Comment by Erick555** [comment]
> I suspect this means you are the first person to have seriously tried to use --socket=gpg-agent, which makes me wonder how much testing was done on the PR that added it.

FWIW there are at least 3 apps on [flathub](https://github.com/search?q=org%3Aflathub+%22--socket%3Dgpg-agent%22&type=code) using `--socket=gpg-agent` for few months and I don't see anyone reported crashes there so I think it's possible to miss the crash case even with testing.
