### ISSUE TITLE
[Bug]: user/1000/doc/ open everytime when i   download file  in  flatpak version of chrome.

### ISSUE THREAD

**Issue by pakosaan** [flatpak/flatpak#5097]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.0

### What Linux distribution are you using?

Manjaro Linux

### Linux distribution version

5.15.66-1-MANJARO

### What architecture are you using?

x86_64

### How to reproduce

Download any file in flatpak chrome browser

### Expected Behavior

Any normal folder 

### Actual Behavior

user/1000/doc/

### Additional Information

It works fine in normal version of firefox installed from official repositories.

**Comment by hfiguiere** [comment]
it's a problem with the chrome package.
