### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [flatpak/flatpak#51]
I would like to point out that identifiers like "[`__FLATPAK_H__`](https://github.com/flatpak/flatpak/blob/c24528d3697c62cad8ff746a56992a59f31d333d/lib/flatpak.h#L21)" and "[`_FlatpakRef`](https://github.com/flatpak/flatpak/blob/c24528d3697c62cad8ff746a56992a59f31d333d/lib/flatpak-ref.h#L28)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by alexlarsson** [comment]
In practice though, for the (C, not C++) compilers we use (we're targeting Linux only and using specific gcc/clang extensions) this is not a problem, and in fact large parts of the stack we depend on (glib & co) does the same.

So, I don't think we need to change this.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
