### ISSUE TITLE
[Feature request]: Allow for flatpaks to request other flatpaks to be installed during runtime

### ISSUE THREAD

**Issue by orowith2os** [flatpak/flatpak#5105]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Currently, a number of flatpaks have dependencies on some optional extensions. Allowing flatpaks to request other flatpaks to be installed would allow for them to properly request other apps/extensions, without breaking the sandbox. 

This might be better fit for an x-d-p protocol, tbh. But I'll file it here, since it's mainly targeted at flatpaks, and I can't think of any native apps that utilize external flatpaks at the moment.

My idea is for them to set a repository to pull from (typically Flathub), and an app ID. The user can override this, and choose their own install location for the flatpak, such as as a system package. If no overrides are set, Flathub is added as a `--user` repository, and the requested apps are pulled from there.

**Comment by soredake** [comment]
https://github.com/flatpak/flatpak/issues/4046

**Comment by orowith2os** [comment]
Ah, yeah, this is a duplicate of that. Closing in favor of it.
