### ISSUE TITLE
[Bug]: cannot create an override for another application directory

### ISSUE THREAD

**Issue by theotheroracle** [flatpak/flatpak#5115]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

36

### What architecture are you using?

x86_64

### How to reproduce

1. use flatseal to create an override to a directory in ~/.var/app/
2. attempt to access that directory from within a flatpak application
3. it does not work

### Expected Behavior

i expected the override to allow access

### Actual Behavior

the override does not allow acess

### Additional Information

this is useful for applications to be granted permission to modify other application data, for example in gradience, i would like to modify firefox user.css

**Comment by rusty-snake** [comment]
WFM

```console
$ flatpak override --user --filesystem=~/.var/app/net.minetest.Minetest/.minetest/debug.txt org.gnome.TwentyFortyEight
$ flatpak info -M org.gnome.TwentyFortyEight
[Context]
...
filesystems=!host:reset;/home/rusty-snake/.var/app/net.minetest.Minetest/.minetest/debug.txt;!host;
$ flatpak run --command=head org.gnome.TwentyFortyEight ~/.var/app/net.minetest.Minetest/.minetest/debug.txt 


-------------
  Separator
-------------

2022-06-16 09:36:33: ERROR[Main]: Irrlicht: Error: Need running XServer to start Irrlicht Engine.
2022-06-16 09:36:33: ERROR[Main]: Irrlicht: Could not open display, set DISPLAY variable
```

Can you give more details? i.e. `flatpak info -M` and the used flatpaks.

**Comment by theotheroracle** [comment]
i think this may be an issue with the package, sorry about that
