### ISSUE TITLE
org.freedesktop.Platform.GL.default is end of life

### ISSUE THREAD

**Issue by NextGenRyo** [flatpak/flatpak#5117]
I keep getting this message now about this flatpak.

> runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
>    org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

And asks me if I want to remove it. Yes or no.

If i remove it, it just installes again when I update. What exactly is going on? If it's end of life where is the new version??

**Comment by nabeelcodes** [comment]
Gettiing the same issue on Zorin 16.1 core (Kernel : `Linux 5.15.0-48-generic`) x11 session

```bash
➜ flatpak update                                            
Looking for updates…
Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   com.system76.Popsicle
Info: org.freedesktop.Platform.VAAPI.Intel//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Nothing to do.
```

**Comment by rusty-snake** [comment]
@nabeelcodes https://github.com/flathub/com.system76.Popsicle/issues/4

**Comment by rusty-snake** [comment]
@mixalis1987 you must report this to the affected applications (like https://github.com/flathub/org.seul.pingus/issues/7, https://github.com/flathub/org.megaglest.MegaGlest/issues/8, https://github.com/flathub/in.p1x.TanksOfFreedom/issues/5) and hope that someone updates the runtime.

**Comment by repoash** [comment]
Already did that.

```
$ flatpak uninstall --unused
Nothing unused to uninstall
```

**Comment by rusty-snake** [comment]
Are they pined (`flatpak pin`)? Which flatpak version?

**Comment by repoash** [comment]
```
$ flatpak --version                                
Flatpak 1.14.0
```

**Comment by nabeelcodes** [comment]
> @mixalis1987 you must report this to the affected applications (like [flathub/org.seul.pingus#7](https://github.com/flathub/org.seul.pingus/issues/7), [flathub/org.megaglest.MegaGlest#8](https://github.com/flathub/org.megaglest.MegaGlest/issues/8), [flathub/in.p1x.TanksOfFreedom#5](https://github.com/flathub/in.p1x.TanksOfFreedom/issues/5)) and hope that someone updates the runtime.

---
Updated runtime in yaml file and opened PR for the same
`https://github.com/flathub/com.system76.Popsicle/pull/5`

**Comment by rusty-snake** [comment]
@repoash and if you explicitly uninstall them `flatpak uninstall org.freedesktop.Sdk` do you get an error about being used?

**Comment by RhFortuna** [comment]
Same here.

> Info: org.freedesktop.Platform is at the end of its life, with reason: org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> Info: org.freedesktop.Platform.VAAPI.Intel [...]
> Info: org.freedesktop.Platform.Locale [...]
> Info: org.freedesktop.Platform.GL.default [...]

> Error: Could not remove org.freedesktop.Platform/x86_64/20.08 as it is needed for: info.colobot.Colobot/x86_64/stable
> error: Failed to uninstall org.freedesktop.Platform: Could not remove org.freedesktop.Platform/x86_64/20.08 as it is needed for: info.colobot.Colobot/x86_64/stable

Xubuntu 20.04
Flatpak 1.6.5

**Comment by RamprakashGovindaraj** [comment]
same here.. I'm on Ubuntu 22.04.1 LTS x86_64, Kernel: 5.15.0-48-generic, GNOME 42.4, Flatpak 1.12.7

I get this when I run `flatpack update`

`Looking for updates…
Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   io.github.Figma_Linux.figma_linux
Info: org.freedesktop.Platform.VAAPI.Intel//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Nothing to do.`


Should I report this to the Figma community, can Figma work on this?? Or may I ask, do you have any workaround or recommendations? I don't know but I'll try removing the Figma from the flatpak and install a snap.

Any advice or help would be greatly appreciated.

**Comment by rusty-snake** [comment]
As a FTR for everyone how gets this "error":
- Got to https://github.com/flathub
- Search for the reported flatpaks
- Look at the open issues of it. Maybe this has already been reported.
- If not, open an issues there.

**Comment by 1bcb** [comment]
I'm getting the same issue on Mint 21.  None of the apps I have installed use org.freedesktop.Platform.GL.default//20.08 or org.freedesktop.Platform//20.08, and uninstalling org.freedesktop.Platform.GL.default//20.08 does not return any errors.  However, running `flatpak update` causes org.freedesktop.Platform.GL.default//20.08 to be reinstalled, and `flatpak uninstall --unused` does not uninstall it even though it is unused and not pinned.

**Comment by piquant00** [comment]
> Xubuntu 20.04 Flatpak 1.6.5

Had the same on Xubuntu 22.04, `flatpak uninstall --unused` worked for me.

**Comment by mixalis1987** [comment]
@piquant00 but does a flatpak update reinstall it again?

**Comment by yhojann-cl** [comment]
In Ubuntu 22.04 LTS run `flatpak uninstall --unused` but does not work, has same results:

```
whk@machine:~$ flatpak uninstall --unused


        ID                                                              Rama             Op
 1. [-] org.freedesktop.Platform.openh264                               2.3.0            r
 2. [-] org.gnome.Platform                                              41               r
 3. [-] org.gnome.Platform.Locale                                       41               r
 4. [-] org.kde.KStyle.Adwaita                                          6.2              r
 5. [-] org.kde.Platform                                                6.2              r
 6. [-] org.kde.Platform.Locale                                         6.2              r
 7. [-] org.kde.PlatformTheme.QGnomePlatform                            6.2              r
 8. [-] org.kde.WaylandDecoration.QGnomePlatform-decoration             6.2              r

Desinstalación completada.
whk@machine:~$ flatpak update
Buscando actualizaciones…
Info: org.freedesktop.Sdk//20.08 terminó su vida útil, con motivo:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//20.08 terminó su vida útil, con motivo:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Nada que hacer.
```

**Comment by zensir** [comment]
When I `flatpak uninstall --unused` i get:
```
These runtimes in installation 'system' are pinned and won't be removed; see flatpak-pin(1):
  runtime/org.freedesktop.Platform.GL.default/x86_64/20.08
Nothing unused to uninstall
```

**Comment by RhFortuna** [comment]
To me:
> Nothing unused to uninstall

**Comment by smokingsnakes83** [comment]
> > Xubuntu 20.04 Flatpak 1.6.5
> 
> Had the same on Xubuntu 22.04, `flatpak uninstall --unused` worked for me.

Worked for me too

**Comment by cstamas** [comment]
same here Fedora36:
```
[cstamas@urnebes ~]$ flatpak update
Looking for updates…
Info: org.freedesktop.Sdk//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Nothing to do.
[cstamas@urnebes ~]$ flatpak uninstall --unused 
Nothing unused to uninstall
[cstamas@urnebes ~]$ flatpak pin 
No pinned patterns
[cstamas@urnebes ~]$ 
```

**Comment by RhFortuna** [comment]
I uninstall Colobot - the only package that generated the error for me - and ran the uninstall unused command. No warning now.

**Comment by DarkArc** [comment]
At the very least, this error message should be changed to be more helpful. I have no idea as a user what I've done to even end up with that runtime, let alone how to remove it.

**Comment by danzpaim** [comment]
> I keep getting this message now about this flatpak.
> 
> > runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
> > org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> 
> And asks me if I want to remove it. Yes or no.
> 
> If i remove it, it just installes again when I update. What exactly is going on? If it's end of life where is the new version??

2023 and this problem persists here.

**Comment by deontay3579** [comment]
I was able to fix this problem by following the advice here: https://www.danweitzel.net/post/freedesktop/.

**Comment by stemy2** [comment]
> I was able to fix this problem by following the advice here: https://www.danweitzel.net/post/freedesktop/.

It does not work for me because of this:
`
Failed to uninstall org.kde.Platform: Can't remove org.kde.Platform/x86_64/5.15-21.08, it is needed for: org.clementine_player.Clementine`

**Comment by Hasshu** [comment]
@stemy2 flathub/org.clementine_player.Clementine#117

**Comment by hfiguiere** [comment]
work as expected. question answered

**Comment by dhow** [comment]
For me it was the application com.gitlab.coringao.cavestory-nx ([Cave Story NX](https://flathub.org/apps/com.gitlab.coringao.cavestory-nx)) showing this after I upgraded to Debian 12 (bookworm) on my Chromebook, since I no longer need this game I just uninstalled it -- of course the end-of-life message is no longer shown. 

I'm not sure what is the right way to do this, since it is a problem caused by an application using old version of a library, until the author updates the application and link to a newer version of the the library I think this message will always be there. 

```:~$ flatpak update
Looking for updates…

Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.gitlab.coringao.cavestory-nx

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.gitlab.coringao.cavestory-nx
:~$ flatpak remove com.gitlab.coringao.cavestory-nx


        ID                                           Branch          Op
 1. [-] com.gitlab.coringao.cavestory-nx             stable          r
 2. [-] org.freedesktop.Platform.GL.default          21.08           r
 3. [-] org.freedesktop.Platform.Locale              21.08           r
 4. [-] org.freedesktop.Platform                     21.08           r

Uninstall complete.
:~$ flatpak uninstall --unused


        ID                                         Branch          Op
 1. [-] org.freedesktop.Platform.openh264          2.0             r

Uninstall complete.
:~$ flatpak update
Looking for updates…

Nothing to do.```
