### ISSUE TITLE
[Feature request]: Make the Inhibit portal a deniable permission

### ISSUE THREAD

**Issue by imaspeer** [flatpak/flatpak#5133]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

[Some (arguably misbehaving) applications](https://github.com/ValveSoftware/steam-for-linux/issues/5607) may use the Inhibit portal to prevent sleep unconditionally, or otherwise when it is not desired.

I suggest adding a permission, possibly granted by default, that when denied would prevent the application from using this portal.

**Comment by hfiguiere** [comment]
This is an issue for the portal: https://github.com/flatpak/xdg-desktop-portal/issues
