### ISSUE TITLE
flatpak shouldn't permit unconditional access to `/sys/block` with bwrap for better security

### ISSUE THREAD

**Issue by adrelanos** [flatpak/flatpak#5138]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.7

### What Linux distribution are you using?

Debian

### Linux distribution version

bullseye

### What architecture are you using?

x86_64

### How to reproduce

1. flatpak while access to `/sys/block` is restricted to root ([`/lib/systemd/system/hide-hardware-info.service`](https://github.com/Kicksecure/security-misc/blob/master/lib/systemd/system/hide-hardware-info.service))
2. run flatpak

### Expected Behavior

flatpak shouldn't unconditionally need access to `/sys/block` because that's dangerous for security.

### Actual Behavior

flatpak hardcoded, requires access to `/sys/block`.

    flatpak run org.mozilla.firefox                                                               

> bwrap: Can't find source path /sys/block: Permission denied

### Additional Information

flatpak in https://github.com/flatpak/flatpak/blob/main/common/flatpak-run.c#L3529 uses:

>                          "--ro-bind", "/sys/block", "/sys/block",

What's the purpose of this?

It's the block devices.

    ls /sys/block

> xvda  xvdb  xvdc  xvdd

I don't see why flatpak needs access to these?

**Comment by nanonyme** [comment]
Seems this is super-old. It's part of migration to filtered sys back from xdg-app days https://github.com/flatpak/flatpak/commit/e72beada8aefebe96b17c74d5c0c438d897a433d
