### ISSUE TITLE
[Bug]: Issue with File picker not opening when saving

### ISSUE THREAD

**Issue by linlinxza** [flatpak/flatpak#5147]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

KDE Neon 22.04

### What architecture are you using?

x86_64

### How to reproduce

1. In any app that uses the QT file picker.
2. Attempt to open save dialog by trying to save anything.

### Expected Behavior

File picker should open.

### Actual Behavior

File picker does not open.

### Additional Information

After running:

`systemctl --user status xdg-desktop-portal`

Shows error:

`Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Unit xdg-desktop-portal-gtk.service is masked`

**Comment by hfiguiere** [comment]
Do you have xdg-desktop-portal-kde installed? (since you run KDE)

**Comment by linlinxza** [comment]
> Do you have xdg-desktop-portal-kde installed? (since you run KDE)

Kind of a long time, dude. I figured this out a long time ago. Yes. The portal is installed. If I remember correctly, all I had to do was mask and unmask the service. That fixed it.

**Comment by hfiguiere** [comment]
closing as resolved then.
