### ISSUE TITLE
Build cmake modules

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#515]
Hi!

So I'm trying to build Jasper 2.0.10: http://www.ece.uvic.ca/~frodo/jasper/#download
Jasper is now a cmake build so I set:

> "cmake": true,

flatpak-builder fails with:

> CMake Error at build/cmake/modules/InSourceBuild.cmake:7 (message):
>  The use of an in-source build is not recommended.  For this reason, the use
>  of in-source build is disabled by default.  If you want to override this
>  default behavior, add the -DALLOW_IN_SOURCE_BUILD option to cmake.
> Call Stack (most recent call first):
>  build/cmake/modules/InSourceBuild.cmake:16 (prevent_in_source_build)
>  CMakeLists.txt:9 (include)
>
> -- Configuring incomplete, errors occurred!
> See also "/run/build/jasper/CMakeFiles/CMakeOutput.log".
> Error: module jasper: Child process exited with code 1

Adding:

>             "config-opts": [ "-DALLOW_IN_SOURCE_BUILD" ],

It fails with:

> Parse error in command line argument: -DALLOW_IN_SOURCE_BUILD
> Should be: VAR:type=value

Fine. It looks like CMakeCache.txt syntax is expected.

> "config-opts": [ "ALLOW_IN_SOURCE_BUILD:BOOL=ON" ],

Now fails with:

> ========================================================================
> Building module jasper in /home/jehan/dev/flatpak/.flatpak-builder/build/jasper-11
> ========================================================================
> CMake Error: The source directory "/run/build/jasper/ALLOW_IN_SOURCE_BUILD:BOOL=ON" does not exist.
> Specify --help for usage, or press the help button on the CMake GUI.
> Error: module jasper: Child process exited with code 1

Looking in a source directory "/run/build/jasper/ALLOW_IN_SOURCE_BUILD:BOOL=ON"?
Either I did not understand how that works at all, or there is a bug.
Thanks! :-)

**Comment by TingPing** [comment]
You can set `"builddir": true` to build out of tree.

**Comment by Jehan** [comment]
Oh ok. I'll try this, it should work! It would be good to have possibility to configure a cmake build as well though. :-)

**Comment by TingPing** [comment]
You can pass config options to cmake, but for this at least it is the wrong solution.

**Comment by Jehan** [comment]
TingPing: I agree that it was the right solution, knowing now of builddir option. Just for future reference then, in case I get into another dependency using cmake, what's the way to pass an option to cmake in flatpak/flatpak-builder?

**Comment by TingPing** [comment]
config-opts is correct, the value you wanted was probably `'-DALLOW_IN_SOURCE_BUILD=ON'`.

**Comment by alexlarsson** [comment]
Yes TingPing is right, here are some examples:
https://github.com/alexlarsson/nightly-build-apps/blob/c5d3df68987f5dabee21919be8c51bdd9fd6c73f/org.darktable.DarktableDevel.json#L81
