### ISSUE TITLE
[Feature request]: modify python version that an installed program uses

### ISSUE THREAD

**Issue by brandy125** [flatpak/flatpak#5150]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Is it possible to change the python version that an installed program uses?
Example:  org.qgis.qgis uses now python 3.9 
Is it possible to change the python version of qgis to python3.10?
How could I do this?

**Comment by hfiguiere** [comment]
Python is linked to the runtime. Unless you build a different version (with all the problam that it entails) you can't change this.
