### ISSUE TITLE
Thunderbird and MarkText Graphical Glitch Pop OS! 

### ISSUE THREAD

**Issue by alepersichetti** [flatpak/flatpak#5154]
![faltpak_issues_markText_thunderbird](https://user-images.githubusercontent.com/82945650/198741195-329942d7-d05a-4020-87ce-d2b3d539899b.png)

Graphical Glitch occurring with both Thunderbird and MarkText. The .deb versions work fine.

Machine specs.

  OS: Pop!_OS 22.04 LTS x86_64 
 Host: H410M H 
 DE: GNOME 
 GPU: AMD ATI Radeon RX 5500/5500M / P

**Comment by Aisyk** [comment]
Same thing here.
It's the move from Mesa 22.2.0

Applications concerned : 
All applications uses flatpak runtimes 21.08 (it doesn't occurs with 20.08 or 22.08).
It is very annoying !

**Comment by smcv** [comment]
> This is [bug](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1460) in mesa in 21.08 runtime. Flatpak itself can't do anything here.

Closing this since a bug in a specific runtime is not going to be fixed by a change to Flatpak itself.
