### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gantsevdenis** [flatpak/flatpak#5178]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.2.5

### What Linux distribution are you using?

Debian

### Linux distribution version

Debian buster, kernel 5.10.0

### What architecture are you using?

x86_64

### How to reproduce

Is it even possible to use flatpak-ed applications with X forwarding?
(I have no trouble running graphical application which *do not* use flatpak)
```
$ ssh -X denis@$my-other-laptop
...
$ echo $DISPLAY
localhost:11.0
$ flatpak run org.mozilla.firefox
Error: no DISPLAY environment variable specified
.. 
$ flatpak run org.mozilla.firefox -c "DISPLAY=localhost:11.0"
Error: no DISPLAY environment variable specified
```

### Expected Behavior

Would like to use flatpak-ed application with X forwarding

### Actual Behavior

can't specify display

**Comment by smcv** [comment]
> Is it even possible to use flatpak-ed applications with X forwarding?

Not in version 1.2. This became possible in version 1.12 (#397).

Debian 10 reached end-of-life about 2 months ago, and no longer receives support from Debian or most upstream developers. End-of-life Debian releases also do not receive backports of newer versions of packages like Flatpak.

Debian 11 is the current stable release. The Flatpak version in Debian 11 (Flatpak 1.10.x) was also too old to support X forwarding, but there is an official backport of Flatpak 1.14.x available, and X forwarding should approximately work in that backport.

Note that X11 does not have much of a boundary between applications, so a Flatpak app running with access to X forwarding will be able to do things on the forwarded X display that you might not want it to, such as keyboard input logging and screen captures.

X forwarding is also generally decreasing in usefulness, as apps become more reliant on the ability to do direct rendering, use shared memory buffers to transfer their frames to the compositor, and share other state with the desktop environment (such as the filesystem and D-Bus). A purpose-built remoting protocol like VNC (RDP), RFB or SPICE will often work better.

**Comment by smcv** [comment]
X forwarding also requires the application to have the `--share=network` permission, although that's not going to be a problem for Firefox.
