### ISSUE TITLE
[Bug]: --unused tag and pinned apps

### ISSUE THREAD

**Issue by libreajans** [flatpak/flatpak#5184]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.0

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

- I just installed shotcut from Flathub `flatpak install org.shotcut.Shotcut`
- After installing I checked size of Flatpak folder `sudo du -sh /var/lib/flatpak/` : 2,4G
- It was a big app and I removed it again `flatpak remove org.shotcut.Shotcut`
- After removing the app I checked size of Flatpak folder again `sudo du -sh /var/lib/flatpak/` : 2,3G
- I tried to clean up unused runtimes `flatpak remove --unused`

Now I have no installed app but 2.3G wasted/blocked space.

```
$ LC_ALL=C flatpak remove --unused 

These runtimes in installation 'system' are pinned and won't be removed; see flatpak-pin(1):
  runtime/org.freedesktop.LinuxAudio.Plugins.swh/x86_64/21.08
  runtime/org.freedesktop.Platform.GL.default/x86_64/21.08
  runtime/org.freedesktop.Platform.GL.nvidia-515-65-01/x86_64/1.4
  runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/21.08
  runtime/org.freedesktop.Platform.openh264/x86_64/2.0
  runtime/org.kde.KStyle.Adwaita/x86_64/5.15-21.08
  runtime/org.kde.Platform.Locale/x86_64/5.15-21.08
  runtime/org.kde.Platform/x86_64/5.15-21.08
  runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/5.15-21.08
  runtime/org.kde.PlatformTheme.QtSNI/x86_64/5.15-21.08
  runtime/org.kde.WaylandDecoration.QGnomePlatform-decoration/x86_64/5.15-21.08
Nothing unused to uninstall
```

There is no app installed only runtimes left.

```
LC_ALL=C flatpak list
Name                                 Application ID                                                 Version            Branch                Installation
SWH                                  org.freedesktop.LinuxAudio.Plugins.swh                         0.4.17             21.08                 system
Mesa                                 org.freedesktop.Platform.GL.default                            21.3.9             21.08                 system
nvidia-515-65-01                     org.freedesktop.Platform.GL.nvidia-515-65-01                                      1.4                   system
Intel                                org.freedesktop.Platform.VAAPI.Intel                                              21.08                 system
openh264                             org.freedesktop.Platform.openh264                              2.1.0              2.0                   system
Adwaita theme                        org.kde.KStyle.Adwaita                                                            5.15-21.08            system
KDE Application Platform             org.kde.Platform                                                                  5.15-21.08            system
QGnomePlatform                       org.kde.PlatformTheme.QGnomePlatform                                              5.15-21.08            system
QtSNI                                org.kde.PlatformTheme.QtSNI                                                       5.15-21.08            system
QGnomePlatform-decoration            org.kde.WaylandDecoration.QGnomePlatform-decoration                               5.15-21.08            system

```

### Expected Behavior

Flatpak should remove this artifects.

### Actual Behavior

Even after removing and purging flatpak from my system, there are 2G wasted space.

### Additional Information

Pinned runtime behaviour seems odd/buggy.

**Comment by Erick555** [comment]
Was `/var/lib/flatpak/` empty before you installed shotcut? The fact all those runtimes are shown as pinned suggests they were installed manually. If not then some strange bug happened indeed.

**Comment by libreajans** [comment]
Possible. I just tested again nightly version of GNOME OS, it didn't happen again.
