### ISSUE TITLE
[Bug]: re.rizin.cutter.plugin.rz-ghidra was of type addon but had no extends

### ISSUE THREAD

**Issue by ThaiDangFr** [flatpak/flatpak#5187]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

36

### What architecture are you using?

x86_64

### How to reproduce

1. open a terminal and do "flatpak search <package name>" 
ex. flatpak search Slack
2. 

### Expected Behavior

the list of flatpak packages

### Actual Behavior

(flatpak search:2442147): As-WARNING **: 19:35:04.146: re.rizin.cutter.plugin.rz-ghidra was of type addon but had no extends

followed by the list of packages

![image](https://user-images.githubusercontent.com/26742137/203623625-0d24bd20-92cb-4de8-ac03-ce52c5a40749.png)

**Comment by kempy13** [comment]
I'm having the same issue. I'm on Ubuntu 22.04.1 but otherwise, everything else the same.

**Comment by MeteorKLINT** [comment]
I have the same issue on Pop!_OS 22.04.

**Comment by RobViren** [comment]
I have same issue new install Linux Mint 21
'''
Kernel: 5.15.0-53-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.12
tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
'''

**Comment by lamyergeier** [comment]
Same issue on Ubuntu 22.04

Installed kernel: 5.17.0-1019-oem

**Comment by taupezen** [comment]
Same issue on Ubuntu 22.04 (kern 5.15.0-56-generic)

**Comment by zetaomegagon** [comment]
@taupezen @lamyergeier @RobViren @MeteorKLINT @kempy13 @ThaiDangFr 

See: https://github.com/flathub/re.rizin.cutter.plugin.rz-ghidra

**Comment by MeteorKLINT** [comment]
@zetaomegagon thank you for your link. I am not sure how that repository helps us. I used the commands
```bash
flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.gnome.Recipes
flatpak search test
```
and got the same error. Have I taken the right steps?

**Comment by zetaomegagon** [comment]
No. The bug isn't with flathub at all. It's with the upstream plugin's appstream metadata.

Like in the issue I linked stated, the maintainer needs to add `<extends>re.rizin.cutter</extends>` to their appstream metadata

All you did was re-add the flathub repo; then install a random flatpak
--
Best,

Elijah Beale

Dec 11, 2022 18:38:07 MeteorKLINT ***@***.***>:

**Comment by zetaomegagon** [comment]
@MeteorKLINT Oh, I accidentally linked the repo and not the issue. The issue isn't with flatpak it's with `re.rizin.cutter.plugin.rz-ghidra`

Here's the issue I meant to link: https://github.com/flathub/re.rizin.cutter.plugin.rz-ghidra/issues/1

**Comment by hfiguiere** [comment]
so it's not flatpak and was solved.
