### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gobybear** [flatpak/flatpak#5201]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.0

### What Linux distribution are you using?

Void Linux

### Linux distribution version

Linux thevoid 6.0.10_1

### What architecture are you using?

x86_64

### How to reproduce

flatpak run com.unity.UnityHub
Click "connect to an account"

### Expected Behavior

It is supposed to open my web browser (mozilla firefox) so i can log in my account and use unity

### Actual Behavior

I get the following error
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

**Comment by smcv** [comment]
Please install [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) and a desktop-environment-specific backend suitable for your choice of UI, such as [xdg-desktop-portal-gnome](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome) for GNOME Shell, [xdg-desktop-portal-kde](https://github.com/KDE/xdg-desktop-portal-kde) for KDE Plasma, or [xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk) for environments that do not offer anything more specific.

Your OS distribution's packaging system should install these as a required dependency (Debian `Depends`, RPM `Requires`,etc.) or a recommended dependency (Debian `Recommends`, etc.) when you install Flatpak. If it does not, please report this to your OS distribution as a bug.

If you installed Flatpak from source, please suggest somewhere in the documentation that you would have seen a recommendation to install the portals.
