### ISSUE TITLE
[Bug]: cannot share all of /run with a Flatpak app

### ISSUE THREAD

**Issue by monroth** [flatpak/flatpak#5207]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

 Linux steamdeck 5.3.0-valve21.3-1-neptune

### What architecture are you using?

x86_64

### How to reproduce

Not sure exactly how this happened, as issue makes it difficult to debug, but I think steps were as follows
1. Install Flatseal
2. Use it to allow all flatpaks access to /run and some other folders (difficult to tell which because of issue)
3. Probably reboot
4. Try to launch any flatpak

### Expected Behavior

I expected flatpak to start and have access to my filesystem

### Actual Behavior

Flatpak did not launch with with terminal message
```
bwrap: Can't mkdir parents for /run/host/os-release: Permission denied
```

### Additional Information

Issue https://github.com/flatpak/flatpak/issues/1357 might be related, but I searched symlinks for / via command
```
sudo find -maxdepth 1 -type l -ls
```
and find only 5 old symlinks in /usr and in /var, nothing new or in /run

**Comment by smcv** [comment]
> allow all flatpaks access to /run

That can't work. Flatpak relies on the `/run` inside the container being a tmpfs under its control so that it can create `/run/host`, `/run/flatpak` and potentially others, which it will be unable to do if you change `/run` to be shared from the host system.

Probably Flatpak should ignore `--filesystem=/run`, ideally with a warning, the same way it already ignores `--filesystem=/usr`.

Instead of sharing `/run` with the host, share individual sockets in `/run` with the host (and try to do that as minimally as possible, because each socket you share is an extra route through which a malicious or compromised app might escape from the sandbox).

**Comment by smcv** [comment]
> Use it to allow all flatpaks access to /run and some other folders (difficult to tell which because of issue)

Please include the full list of overrides in issue reports, particularly if you suspect the overrides are part of the reason for failure. You can see the overrides with:

1. `flatpak override --show --system`
2. `flatpak override --show --system APP`
3. `flatpak override --show --user`
4. `flatpak override --show --user APP`

replacing *APP* with an app ID like `org.gnome.Recipes`. The first and third commands show overrides that apply to all apps, the second and fourth commands show overrides that are specific to one app. The first and second show overrides that apply to all users, the third and fourth show overrides that apply to you specifically.

To remove overrides that are causing trouble, either use Flatseal, or you can remove *all* overrides with:

1. `sudo flatpak override --reset --system`
2. `sudo flatpak override --reset --system APP`
3. `flatpak override --reset --user`
4. `flatpak override --reset --user APP`

Similar to the `--show` commands, the first and third commands remove overrides that apply to all apps, while the second and fourth commands remove overrides that are specific to one app. The first and second remove overrides that apply to all users, the third and fourth remove overrides that apply to you specifically. To remove *all* overrides, you would potentially need all four of these commands.

**Comment by monroth** [comment]
yes, there was /run in overrides, and after I removed them issue resolved

**Comment by smcv** [comment]
#5213 avoids this by refusing to share all of `/run` with the app, with a warning message.
