### ISSUE TITLE
[Feature request]: Enable ARM64 in official Flatpak PPA for flatpak-builder

### ISSUE THREAD

**Issue by theofficialgman** [flatpak/flatpak#5210]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

@alexlarsson @smcv please enable ARM64 builds in the flatpak official ppa https://launchpad.net/~flatpak/+archive/ubuntu/stable

I would like to use it over the older alexllarsson ppa that does have arm64 enabled for flatpak-builder https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

**Comment by smcv** [comment]
> please enable ARM64 builds in the flatpak official ppa

They're already enabled: this PPA is configured to build for amd64, arm64 and i386 (but Launchpad refuses to do the i386 builds due to Ubuntu phasing out support for i386), and according to https://launchpad.net/~flatpak/+archive/ubuntu/stable/+packages there are arm64 binaries available.

**Comment by theofficialgman** [comment]
Please reopen. I would not have made the issue if the binaries we're available which they are not. Reread the issue description and look at this screenshot.

![Screenshot_20221212-120809](https://user-images.githubusercontent.com/28281419/207109083-688e4993-a6bc-49fd-9aa0-99c9567a189b.png)

**Comment by smcv** [comment]
So your request is not for arm64 to be enabled, but for some packages to be rebuilt for older LTS suites?

Which suites and which packages? I don't mind kicking off new builds for some of the less obsolete suites, but I don't want to go back all the way to 16.04 if nobody is using the result.

**Comment by theofficialgman** [comment]
currently there are no arm64 flatpak-builder packages in the new ppa for ubuntu bionic.

there is an arm64 flatpak-builder package in the old ppa for ubuntu bionic. I understand if the latest version of flatpak-builder cannot be built on bionic but at least there should be an arm64 version of 1.0.14 in <https://launchpad.net/~flatpak/+archive/ubuntu/stable> since there is one in <https://launchpad.net/~flatpak/+archive/ubuntu/stable>

**Comment by smcv** [comment]
A rebuild versioned 1.0.14-0flatpak2~bionic is now in the https://launchpad.net/~flatpak/+archive/ubuntu/stable/+packages PPA and should be published soon (just waiting for Launchpad now).

For some reason 1.0.14-0flatpak1~bionic was built for aarch64 in https://launchpad.net/~flatpak/+archive/ubuntu/development/+packages, but not in the stable equivalent. It's the same source code, imported from Alex's older PPA at about the same time, and they don't intentionally have different settings...
