### ISSUE TITLE
[Bug]: flatpak can't exit after update finished

### ISSUE THREAD

**Issue by lumingzh** [flatpak/flatpak#5214]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.0

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

1. run `flatpak update` in terminal
2. waiting for update finish

### Expected Behavior

flatpak command will exit immediately after update finished.

### Actual Behavior

flatpak will waiting for a very long time (some minutes) to exit after the 'update finished' message showed up.

**Comment by mwleeds** [comment]
Probably this means that some changes from the updates are being written to disk, and perhaps you are using a slow spinning disk HDD. Without more information like a backtrace from when the process seems stalled, it's impossible to say if there's an actual bug here.

**Comment by ErrorNoInternet** [comment]
Also happens to me, it even freezes after "Nothing to do". I am using a SSD.
I ran strace on it, but unfortunately didn't save the whole snippet but it was something along the lines of:

```
recvfrom(34, "x\24E\17&\314\fq\234(\344\3251\374\21$\33@\34wO\6\217V\1.'\263\316\327A\265"..., 1086, 0, NULL, NULL) = 1086
poll([{fd=35, events=POLLOUT}], 1, -1)  = 1 ([{fd=35, revents=POLLOUT}])
write(35, "\354\275ks\24G\2620\374\375\371\25\35\376\360\304\356\273H\232\213\346\2061\347\10l\344\v`\f\30"..., 16384) = 16384
poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=34, revents=POLLIN|POLLRDNORM}])
recvfrom(34, "\27\3\3@\21", 5, 0, NULL, NULL) = 5
recvfrom(34, "\337\312\240V\336\257\300\253Y\334\367\35\344b\306\236KpLXZ%\"\332\363\306\351Cj\236@j"..., 16401, 0, NULL, NULL) = 207
recvfrom(34, 0x561502b9d237, 16194, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
poll([{fd=34, events=POLLIN}, {fd=32, events=POLLIN}], 2, 1000) = 1 ([{fd=34, revents=POLLIN}])
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=34, revents=POLLIN|POLLRDNORM}])
recvfrom(34, "\366LPd2\\GX\344\361\320o\347\326+\201\367Ix\267\277\246\r\33\266\306\1l\360\374\233l"..., 16194, 0, NULL, NULL) = 1298
recvfrom(34, 0x561502b9d749, 14896, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
poll([{fd=34, events=POLLIN}, {fd=32, events=POLLIN}], 2, 1000) = 1 ([{fd=34, revents=POLLIN}])
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=34, revents=POLLIN|POLLRDNORM}])
recvfrom(34, "2\31\\ \306\345\200\27\237\33\314\302g\314\314t\204%Xj\272\3219\372 \244P\207!t^v"..., 14896, 0, NULL, NULL) = 1298
recvfrom(34, 0x561502b9dc5b, 13598, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
```

While I was searching for other people having the same issues, the command finally exited after about 10 minutes.
And then it worked normally after that, quits right after "Nothing to do".

Fedora KDE 38 x86_64
Flatpak 1.15.4

**Comment by lumingzh** [comment]
> Also happens to me, it even freezes after "Nothing to do". I am using a SSD. I ran strace on it, but unfortunately didn't save the whole snippet but it was something along the lines of:
> 
> ```
> recvfrom(34, "x\24E\17&\314\fq\234(\344\3251\374\21$\33@\34wO\6\217V\1.'\263\316\327A\265"..., 1086, 0, NULL, NULL) = 1086
> poll([{fd=35, events=POLLOUT}], 1, -1)  = 1 ([{fd=35, revents=POLLOUT}])
> write(35, "\354\275ks\24G\2620\374\375\371\25\35\376\360\304\356\273H\232\213\346\2061\347\10l\344\v`\f\30"..., 16384) = 16384
> poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=34, revents=POLLIN|POLLRDNORM}])
> recvfrom(34, "\27\3\3@\21", 5, 0, NULL, NULL) = 5
> recvfrom(34, "\337\312\240V\336\257\300\253Y\334\367\35\344b\306\236KpLXZ%\"\332\363\306\351Cj\236@j"..., 16401, 0, NULL, NULL) = 207
> recvfrom(34, 0x561502b9d237, 16194, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
> poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
> rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
> poll([{fd=34, events=POLLIN}, {fd=32, events=POLLIN}], 2, 1000) = 1 ([{fd=34, revents=POLLIN}])
> rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, 8) = 0
> rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
> poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=34, revents=POLLIN|POLLRDNORM}])
> recvfrom(34, "\366LPd2\\GX\344\361\320o\347\326+\201\367Ix\267\277\246\r\33\266\306\1l\360\374\233l"..., 16194, 0, NULL, NULL) = 1298
> recvfrom(34, 0x561502b9d749, 14896, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
> poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
> rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
> poll([{fd=34, events=POLLIN}, {fd=32, events=POLLIN}], 2, 1000) = 1 ([{fd=34, revents=POLLIN}])
> rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, 8) = 0
> rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
> poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=34, revents=POLLIN|POLLRDNORM}])
> recvfrom(34, "2\31\\ \306\345\200\27\237\33\314\302g\314\314t\204%Xj\272\3219\372 \244P\207!t^v"..., 14896, 0, NULL, NULL) = 1298
> recvfrom(34, 0x561502b9dc5b, 13598, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
> poll([{fd=34, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
> rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fdb2d59cb70}, NULL, 8) = 0
> ```
> 
> While I was searching for other people having the same issues, the command finally exited after about 10 minutes. And then it worked normally after that, quits right after "Nothing to do".
> 
> Fedora KDE 38 x86_64 Flatpak 1.15.4

Interesting, this bug didn't happen again after I updated flatpak 1.15.4 with fedora silverblue 38.

**Comment by ErrorNoInternet** [comment]
> Interesting, this bug didn't happen again after I updated flatpak 1.15.4 with fedora silverblue 38.

It stopped happening to me too after leaving it alone for a while.

My (probably wrong) guess is that it was updating something (maybe not a package), but kept failing? But then finally succeeded and started to work properly after that.

**Comment by ErrorNoInternet** [comment]
Got the strace: https://envs.sh/dev.txt
This time it didn't freeze for that long, but it still hovered at "Nothing to do." for about 15 seconds.

**Comment by freedriven** [comment]
Same problem. It's intermittent, but it's real.  Sometimes more than 20s, so I cntl-c out of it.
ubuntu 23.10
Kernel 6.5.0-14

**Comment by koutheir** [comment]
It's still an ongoing bug, and `flatpak update` hangs for multiple minutes. This have never happened before, and I've been using flatpaks for years.
