### ISSUE TITLE
[Bug]: Couldn't forward installed vst plugins to flatpack application

### ISSUE THREAD

**Issue by NTMan** [flatpak/flatpak#5216]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

38

### What architecture are you using?

x86_64

### How to reproduce

I wanna forward `/usr/lib64/vst3`, `/usr/lib/vst3` and `/usr/share/surge-xt` to the flatpack app (Bitwig Studio). Judging by the documentation https://docs.flatpak.org/en/latest/sandbox-permissions.html `/usr` is completely blacklisted and this is done not out of harm, but to substitute runtime libraries there. And no Flatseals can make an exception for the directories I need. Although in the same paragraph it is written that exceptions are made for `/run/media`. The question is, is it possible to forward the `/usr/lib64/vst3` and `/usr/lib/vst3` directories to the container?

![Screenshot from 2022-12-13 17-04-10](https://user-images.githubusercontent.com/200750/207329449-13ec22c9-118f-4c3b-8db0-1dde8c6081b9.png)

Also I ties launch Bitwig Studio with follow command line:
`flatpak run --filesystem=/usr/lib/vst3 --filesystem=/usr/lib64/vst3 --filesystem=/usr/share/surge-xt com.bitwig.BitwigStudio`

### Expected Behavior

Host directories `/usr/lib64/vst3`, `/usr/lib/vst3` and `/usr/share/surge-xt` available for flatpack application.

### Actual Behavior

Host directories `/usr/lib64/vst3`, `/usr/lib/vst3` and `/usr/share/surge-xt` not available for flatpack application.

**Comment by smcv** [comment]
> I wanna forward /usr/lib64/vst3, /usr/lib/vst3 and /usr/share/surge-xt to the flatpack app (Bitwig Studio)

This is not possible, for two reasons:

1. the libraries in /usr are built for your host system's library stack, which in general will be incompatible with the libraries in the Flatpak runtime;
2. inside the Flatpak sandbox, /usr is read-only to avoid file corruption, which means Flatpak would not be able to create the necessary mount points for the directories you want to share

If you configure the Flatpak app with `--filesystem=host-os`, then the host `/usr` appears in the sandbox as `/run/host/usr`, bypassing the second of those reasons; but the first reason means that loading plugins from the host system out of `/run/host/usr` will probably still not work.

The way to do plugins in Flatpak is for the app to load *extensions*, which contain binaries built for the Flatpak runtime's libraries. This is how things like graphics drivers are handled. It looks as though [Bitwig](https://github.com/flathub/com.bitwig.BitwigStudio/blob/master/com.bitwig.BitwigStudio.yaml) is already set up to load any extensions that implement the `org.freedesktop.LinuxAudio.Plugins` extension point, and there seem to be mentions of a `vst3` directory there, so see whether the plugins you are using have been packaged as extensions.
