### ISSUE TITLE
[Feature request]: Improve running non-native arch apps on alternative architectures

### ISSUE THREAD

**Issue by orowith2os** [flatpak/flatpak#5225]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Currently, Flatpak handles running aarch64 (and x86_64) flatpaks on other architectures by way of qemu-user-static.

I believe this could be improved by allowing different methods of architecture emulation, particularly useful for the @asahiLinux project, as they might want to use, say, box86 or Rosetta 2 for x86 translation rather than qemu-user-static.

**Comment by smcv** [comment]
> Currently, Flatpak handles running aarch64 (and x86_64) flatpaks on other architectures by way of qemu-user-static

Does it? I don't think Flatpak does anything special to run non-native-architecture apps: it tells the kernel "run this" and the kernel does whatever it is configured to do. That will often (but not always) be to run qemu-user-static via binfmt_misc.

**Comment by orowith2os** [comment]
I drew the conclusion from other issues in this repo, but I don't really understand C so I can't check to be sure >>

**Comment by orowith2os** [comment]
Turns out it *is* using binfmt_misc, TIL. I'll have to document that sometime.
