### ISSUE TITLE
[Bug]:  How to disable "xxx is running in the background" dialog?

### ISSUE THREAD

**Issue by sgehrman** [flatpak/flatpak#5226]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

Flatpak 1.12.7

### What Linux distribution are you using?

Pop!_OS

### Linux distribution version

Linux pop-os 6.0.6-76060006-generic #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N x86_64 x86_64 x86_64 GNU/Linux

### What architecture are you using?

i386

### How to reproduce

make an app, run it

### Expected Behavior

why is this annoying dialog appearing?  I tried reading the docs, but nothing made sense.

### Actual Behavior

![Screenshot from 2022-12-17 08-35-06](https://user-images.githubusercontent.com/287137/208252271-f83779da-9cad-4e5e-8f69-6085337bd2c4.png)

**Comment by kojq** [comment]
I want to add that it makes sense for this not to be a default behavior.

In addition, an application will constantly force quit itself when the `Force quit` option is selected. The force quit persists across reboots. Such behavior should not occur. Let me know if this should be a seperate issue.

**Comment by mwleeds** [comment]
I don't know the answer to your question, but the notification is going away in future versions of GNOME; see https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/6
