### ISSUE TITLE
[Bug]: bwrap: execvp ldconfig: Exec format error / ARM64 

### ISSUE THREAD

**Issue by ymurawski** [flatpak/flatpak#5228]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04

### What architecture are you using?

arm

### How to reproduce

Tried to install Podman Desktop

### Expected Behavior

Tried to install Podman desktop 

### Actual Behavior

The App installs but wont start, it always comes an error.
idconfig failed status 256
bwrap: execvp ldconfig: Exec format error

Im using Ubunutu ARM64 on my Mac M1 via parrallels desktop

**Comment by davidhaley** [comment]
I get the same error when trying to run `dev.lizardbyte.sunshine`.

```
bwrap: execvp ldconfig: Exec format error
error: ldconfig failed, exit status 256
```

Flatpak 1.15.1
x86_64
EndeavourOS

**Comment by hfiguiere** [comment]
How about you file with the respective flathub packages? See https://github.com/flathub/io.podman_desktop.PodmanDesktop/issues
