### ISSUE TITLE
[Bug]: Wrong size for extra data; Nvidia Driver

### ISSUE THREAD

**Issue by bfapps** [flatpak/flatpak#5230]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04

### What architecture are you using?

i386

### How to reproduce

flatpak update -y

### Expected Behavior

Flatpak should update Nvidia Driver by downloading and installing: org.freedesktop.Platform.GL.nvidia-515-86-01 

### Actual Behavior

The updating process keeps going for a few seconds, and then it stops updating. It shows this error:
Warning: Wrong size for extra data https://us.download.nvidia.com/XFree86/Linux-x86_64/515.86.01/NVIDIA-Linux-x86_64-515.86.01.run

**Comment by mwleeds** [comment]
Hi,

If you try updating again, do you still see the same error message?

According to [this](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/data/nvidia-515.86.01-i386.data), the expected size for `NVIDIA-Linux-x86_64-515.86.01.run` is `363743089 bytes`, and that's what I get when I run `wget https://us.download.nvidia.com/XFree86/Linux-x86_64/515.86.01/NVIDIA-Linux-x86_64-515.86.01.run`.

So I think your network connection faltered during the 347 MB download.

**Comment by ZechariahB** [comment]
This isn't invalid. I can reproduce this with invalid checksum as well. Could be specific to 515.86.01

**Comment by spenkluker645** [comment]
Nope, this is happening to me as well. Please help, every flatpak download is SUPER slow. I am running Linux Mint and my computer is a Lenovo Legion 5. 
![image](https://github.com/flatpak/flatpak/assets/114310071/61df0534-27eb-46f2-8f51-98873e57bacf)
