### ISSUE TITLE
[Bug]: flatpak updates seem prone to break with slow internet connections, seemingly due to unconditionally parallel downloads

### ISSUE THREAD

**Issue by ell1e** [flatpak/flatpak#5231]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

SteamOS, but happened with Fedora 36 in the past too

### What architecture are you using?

x86_64

### How to reproduce

1. Let some updates pile up without updating so that you have 10+ waiting
2. Have slow internet
3. Run ~~`flatpak update` with no arguments (so it will attempt to update everything in one go)~~ edit: seems to be possibly limited to both GNOME Software and KDE Discover but not the raw command line for some reason? unless I'm interpreting the output and UIs wrong

### Expected Behavior

The updates are apparently downloaded with all the outdated things at once at least in the KDE/GNOME UIs, which seems to have the following very negative effects for me (since I have slow internet): 1. whatever else I'm doing on same or different device in the same wifi is broken with basic web pages often needing like 5 refresh attempts until they load, 2. flatpak's own downloads seem to stumble over themselves with often the majority(!) of them throwing some sort of connection error. The output indicates this happens in parallel, so them being downloaded in parallel, which I'm guessing as a conclusion isn't a great idea to unconditionally do without more knowledge about the internet connection.

Fedora's `dnf` suffers from this problem too for me but not nearly as much, it also does parallel downloads. The reason it seems to fare better appears to be that it downloads ~3 things at once rather than 10+ which has a higher chance to work. It however still suffers from this more than "regular" downloads that just use one connection at a time.

I assume that the reason the flatpak updates behave like this is that it's marginally faster for people with fast internet. That doesn't seem like a reasonable trade-off if it leads to it not working at all with slow internet (when other sort of downloads work fine).

I suggest a good reasonable default behavior would be to download one thing at once. And more should be either a user option, or based on some sort of smart connection speed probing instead of being an unconditional default as it seems to be now. The priority should be that it works.

### Actual Behavior

The flatpak updates seem to happily try to download 10+ things at once on a slow connection and won't give up even as the majority of them error out and everything else is kind of falling over itself too.

I just had it try 1.2GB worth of updates, after it was "done" KDE Discover still showed 0.9GB queued up  to be updated because that all failed, as it seems like due to the parallel downloads.

### Additional Information

Maybe these points can provide more arguments for the importance of a solid default behavior, even if it's slower for people with faster connections:

- Steam OS on Steam Deck seems to fetch flatpak updates unattended in its own system update. Since with my wifi that causes it to always fail on something, that leads to the system update getting stuck. (At least that would explain a few things I'm seeing, I don't know for sure but reddit suggests this is a step it often gets stuck on.)

- GNOME Software and KDE Discover also use it semi-unattended in a way where a less knowledgeable user won't understand how to make it use less connections to avoid this, even if they figure out at all why it keeps constantly falling over itself despite normal browser downloads etc. all working fine.

- postmarketOS based on Alpine runs on literal phones, as do mobian and others. They all ship flatpak and GNOME Software, so it would be helpful if it was possible to run it on a mobile data connection with all its potential problems and hiccups without diving into manual configuration changes just to make the downloads work.

- Since flatpak updates usually just run in the background, what's the benefit of it being a little faster anyway if it potentially has these consequences? Can't it just be a little slower by default and work for more people?

**Comment by ell1e** [comment]
Actually, is it possible that GNOME Software and KDE Discover both download in parallel but a raw `flatpak update` doesn't (or doesn't anymore, did it do so in the past)? I thought I saw it do that but now that I'm trying again outside of KDE Discover it doesn't seem to be the case - although I'm not sure since the output is pretty broken, some of the rewrite-in-place functionality doesn't seem to work.

Sorry if this is actually an issue with the UI frontends, it's pretty interesting that both of these have this issue.

**Comment by Lordakius** [comment]
I can't (non-artificially) reproduce this setting, but according to #5162 flatpak by itself does not download in parallel. 

I took a short glance at the [Discover code](https://invent.kde.org/plasma/discover/-/tree/master/libdiscover/backends/FlatpakBackend) handling flatpak but couldn't find anything right now.

So does this also happen with the flatpak CLI ? If not, then this should probably be opened at the Discover or GNOME Software repositories.

**Comment by fyoory** [comment]
Same here.   Can we just have a limit to X threads in preferences for downloads?

In my experience tools or apps that allow that, have a much higher rate of success, but I only have observed this.  IE I do not have measurements in terms of numbers.   When you change threads to 1 and it just works, you walk away happier than you were before.

**Comment by ell1e** [comment]
@fyoory it seems a bit like for most people flatpak on the command line only downloads sequentially, do you know any setting you might have possibly changed to influence that?

@Lordakius I've made a KDE Discover ticket now so hopefully we can figure out on which side this goes wrong: https://bugs.kde.org/show_bug.cgi?id=474135

**Comment by fyoory** [comment]
@ell1e no, I  do not use it enough to have changed anything and generally avoid snap/flatpaks if I can build something from more traditional means.   Sometimes we do like to just test them but could not comment on that further.   It would have been the first time on this machine (manjaro linux) I used flatpak or discover commands.

Discover is a bit more flakey for sure tho.   If you queue a few things up, it will just stall them all.

**Comment by ell1e** [comment]
It seems like that KDE Discover devs think this problem is on the discover side, I've also seen GNOME Software do this but less since it seems to only queue up 2 at once which is still kind of problematic with shaky wifi. I assume the issues reported by @fyoory might just be with a normal sequential download then, maybe, could that be possible?

If all of that is correct, then this ticket is invalid, sorry for that, and the problem is only in KDE Discover and less so, GNOME Software, with the command line tool so far unaffected unless #5162 is ever implemented **and** enabled by default which I hope doesn't happen. (As an option, it's fine of course.)

Should I close this ticket?

**Comment by ell1e** [comment]
This seems to be something done by KDE Discover and not inside flatpak itself, so I'm assuming it makes sense to close this.
