### ISSUE TITLE
[Bug]: Dotnet application unable to launch programs unless manually launched before from within the flatpak shell

### ISSUE THREAD

**Issue by Miepee** [flatpak/flatpak#5232]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.1

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

Rolling Release | Linux ArchPC 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Install https://flathub.org/apps/details/io.github.am2r_community_developers.AM2RLauncher
2. Follow its instructions until the play button (click on the download button, select an AM2R_11.zip, click on install)
3. Click on the play button

### Expected Behavior

A game should launch.

### Actual Behavior

No game launches. Instead it first has to be launched via `flatpak run --command="~/.var/app/io.github.am2r_community_developers.AM2RLauncher/data/AM2RLauncher/Profiles/Community Updates (Latest)/runner" io.github.am2r_community_developers.AM2RLauncher`.
After that command has been executed, clicking the play button from the application works, even after reinstalls of the application.

### Additional Information

This only seems to happen to some users, and not all.

Users also were able to reproduce this on OpenSUSE Tumbleweed as well as SteamOS.

A patch to test this without copyrighted files is available here:
[0001-test-to-not-require-copyrighted-files.txt](https://github.com/flatpak/flatpak/files/10304497/0001-test-to-not-require-copyrighted-files.txt)

**Comment by mwleeds** [comment]
Hi,

You may want to comment on the issue here: https://github.com/AM2R-Community-Developers/AM2RLauncher/issues/37

Or open another issue on that bug tracker. This does not appear to be a bug in Flatpak itself, so closing.

**Comment by Miepee** [comment]
I am an upstream maintainer, and I already commented under the issue.
I don't think that it's an issue with the application, as it does (AFAIK) everything correctly in order to launch programs: mark them as executable first, and then launch them.
For some reason, it's *only* under a flatpak sandbox where it refuses to launch the program unless they have been already started before manually via a flatpak sandbox. Meaning, I can tell it to launch the program 100 times, I can restart the system, completely wipe the flatpak application+data and reinstall it, it **will** refuse to launch the program. But once I launch the program within the sandbox directly, I can repeat all previous steps and they suddenly all work. The fact that after that fix one can just reinstall the application+data with it working, also suggests to me that it's a flatpak bug, as to my knowledge, different application results from the same blank slate shouldn't happen.

**Comment by Miepee** [comment]
For any future viewers: was indeed an issue on our end - we tried to write to a file whose directory did not exist, and the method for writing didn't automatically create it. The reason why launching the program directly worked, is because that program created the directory automatically.
Sorry for the troubles!
