### ISSUE TITLE
'Kill' No Longer an Option for the flatpak Command?

### ISSUE THREAD

**Issue by haleba-hotmail** [flatpak/flatpak#5233]
I was experimenting with using Flatpak versus apt and installed Audacity, which locked up. I could not close the app and Ubuntu did not see Audacity as an application I couldn't kill it.

Multiple sources mention a flatpak command "kill" option, but the installed flatpak command does **_not_** list "kill" as an option

`flatpak --help
Usage:
  flatpak [OPTION…] COMMAND

Builtin Commands:
 Manage installed apps and runtimes
  install             Install an application or runtime
  update              Update an installed application or runtime
  uninstall           Uninstall an installed application or runtime
  list                List installed apps and/or runtimes
  info                Show info for installed app or runtime
  config              Configure flatpak
  repair              Repair flatpak installation
  create-usb          Put apps and/or runtimes onto removable media

 Finding applications and runtimes
  search              Search for remote apps/runtimes

 Running applications
  run                 Run an application
  override            Override permissions for an application
  make-current        Specify default version to run
  enter               Enter the namespace of a running application
  ps                  Enumerate running applications

 Manage file access
  document-export     Grant an application access to a specific file
  document-unexport   Revoke access to a specific file
  document-info       Show information about a specific file
  document-list       List exported files

 Manage dynamic permissions
  permission-remove   Remove item from permission store
  permission-list     List permissions
  permission-show     Show app permissions
  permission-reset    Reset app permissions

 Manage remote repositories
  remotes             List all configured remotes
  remote-add          Add a new remote repository (by URL)
  remote-modify       Modify properties of a configured remote
  remote-delete       Delete a configured remote
  remote-ls           List contents of a configured remote
  remote-info         Show information about a remote app or runtime

 Build applications
  build-init          Initialize a directory for building
  build               Run a build command inside the build dir
  build-finish        Finish a build dir for export
  build-export        Export a build dir to a repository
  build-bundle        Create a bundle file from a ref in a local repository
  build-import-bundle Import a bundle file
  build-sign          Sign an application or runtime
  build-update-repo   Update the summary file in a repository
  build-commit-from   Create new commit based on existing ref
  repo                Print information about a repo

Help Options:
  -h, --help             Show help options

Application Options:
  --version              Print version information and exit
  --default-arch         Print default arch and exit
  --supported-arches     Print supported arches and exit
  --gl-drivers           Print active gl drivers and exit
  -v, --verbose          Print debug information during command processing, -vv for more detail
  --ostree-verbose       Print OSTree debug information during command processing`

>flatpak --version
Flatpak 1.0.9

>lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by cho2** [comment]
> Flatpak 1.0.9

It looks outdated, `kill` available since [1.1.0](https://github.com/flatpak/flatpak/releases/tag/1.1.0)

> > New command flatpak kill to kill running flatpak instances.
