### ISSUE TITLE
[Bug]: Characters aren't working properly

### ISSUE THREAD

**Issue by NoobieOnGitHub** [flatpak/flatpak#5234]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

Try to download something and there is a question mark instead of characters
![i7hLTVF - Imgur](https://user-images.githubusercontent.com/7833263/209718625-1d6cd77b-4259-46fc-8ee9-2fc1e4e292a1.png)

same with progress bar, instead of showing progress bar it shows question mark 
![KxIuJ8m - Imgur](https://user-images.githubusercontent.com/7833263/209718646-42eeac2d-a262-40a5-9b4c-d95000c07930.png)

### Expected Behavior

Characters show up as usual and the progress bar appears

### Actual Behavior

Shows question mark instead of actual characters

**Comment by mwleeds** [comment]
This means that either the font you're using or the terminal emulator you're using doesn't support Unicode characters. For example the character in between the size and the units in the download column is a [non-breaking space character](https://en.wikipedia.org/wiki/Non-breaking_space). It's not a bug in Flatpak.
