### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

### ISSUE THREAD

**Issue by NoobieOnGitHub** [flatpak/flatpak#5236]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

run: flatpak run net.ankiweb.Anki

### Expected Behavior

Anki opens

### Actual Behavior

Gives out an error
Anki starting...
Traceback (most recent call last):
  File "aqt", line 13, in <module>
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aqt", line 15, in <module>
Exception: Anki requires a UTF-8 locale.

![hfRhwZI - Imgur](https://user-images.githubusercontent.com/7833263/209859104-4b69f6f8-77aa-484e-9f0f-ed042ee3ce93.png)

**Comment by mwleeds** [comment]
Hi,

Please upload images using GitHub's built-in functionality, by dragging them into the text field, rather than using imgur.

**Comment by mwleeds** [comment]
Looks like you've already reported this here: https://github.com/flathub/net.ankiweb.Anki/issues/83

Generally, you should only report a bug to Flatpak if it becomes clear or likely that it's not a bug in the particular app. Otherwise the bug tracker here can become overwhelmed with irrelevant bug reports.

I'll comment on the Anki issue you opened and close this one.

**Comment by NoobieOnGitHub** [comment]
Ok sir
