### ISSUE TITLE
Error when running obs-studio: cannot open shared object file

### ISSUE THREAD

**Issue by haltriumph** [flatpak/flatpak#5240]
Hi:

I am trying to run obs-studio on a Centos 7 machine.  I get the following error:
     obs: error while loading shared libraries: libQt6Core.so.6: cannot open shared object file: No such file or directory

I have search the web and cannot find how to put libQt6Core.so.6 on the os.  However, a find shows that there is a version that is associated with flatpak at
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.3/da5db79df3afb70fe080b06f44b84ef1db3400ea8eb8cba77c22ab07c9065f64/files/lib/x86_64-linux-gnu/libQt6Core.so.6

Is there anyway to get flatpak to use that?

**Comment by mwleeds** [comment]
Hi,

This bug tracker is for bugs in Flatpak. If you need help, please use a support forum for your linux distribution or linux in general.
