### ISSUE TITLE
Cannot measure CPU usage with time command

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#525]
Hi,

I am trying to measure the efficiency of the firefox flatpak build by measuring the CPU time for a given scenario inside firefox:

```
$ time flatpak run org.mozilla.FirefoxDevEdition -no-remote -ProfileManager
[...]
real	0m24.867s
user	0m0.008s
sys	0m0.008s
```

Unfortunately the measured CPU time is close to 0 and is probably only a measure of flatpak itself.

**Comment by matthiasclasen** [comment]
yes, you will have to enter the sandbox using --command=sh and run the time command inside

**Comment by LaurentBonnaud** [comment]
Thanks for the hint!

Here is a complete example:

```
$ flatpak run --command=sh org.mozilla.FirefoxDevEdition/x86_64/master
sh-4.3$ time firefox --no-remote
real    0m50.363s
user    0m12.447s
sys     0m1.923s
```

**Comment by all-the-good-ones-are-gone** [comment]
Is this still the only way, or is there another syntax that allows for non-interactive?

I'm trying to compare runnings of HandBrake, and having to kick each iteration off manually instead of using a looped script really hurts.
