### ISSUE TITLE
[Bug]: Some characters doesn't show on GTK4 and libadwaita apps

### ISSUE THREAD

**Issue by zalnaRs** [flatpak/flatpak#5268]
### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

1. Install an app (I will use Gnome builder as that is the most noticable)
2. Some characters doesn't show

### Expected Behavior

The characters to show :)

### Actual Behavior

![image](https://user-images.githubusercontent.com/53659756/215171035-e4a5b4d0-1491-4908-ac5e-a660abae72bb.png)

### Additional Information

Happened after updating flatpak's Mesa and Gnome Platform.

**Comment by wobec** [comment]
Same issue here after upgrading these packages about 15 minutes ago:
* org.freedesktop.Platform.GL32.default
* org.freedesktop.Platform.GL.default
* org.freedesktop.Platform
* org.freedesktop.Platform.Compact.i386

Rebooting didn't fix it.

![Screenshot_Spotify](https://user-images.githubusercontent.com/84247447/215176022-8b53d1d8-1c4a-492f-a343-5b8bb93e5dd0.png)
![Screenshot_Steam](https://user-images.githubusercontent.com/84247447/215176063-384fa8ab-bf32-4fa5-b99f-f9be0a784c71.png)
![Screenshot_Flatpak_Runtimes](https://user-images.githubusercontent.com/84247447/215178624-6432ed4a-96bb-483a-a856-8e9b2af1be31.png)

--
**Specs:**
- Fedora Linux 37 (KDE Plasma)
- Kernel: 6.1.7-200.fc37.x86_64
- mesa-22.3.3-3.fc37
- Flatpak runtimes: 22.3.3
- zsh 5.9 (x86_64-redhat-linux-gnu)

**Comment by mystrdat** [comment]
Same issue on Silverblue 37 / 6700 XT. I have 90% of apps installed as flatpaks so you can imagine my how fun my OS looks atm 😄

**Comment by A6GibKm** [comment]
Known issue, please keep your seatbelts on during the descend.

**Comment by joseph-20** [comment]
Can confirm what @wobec said and also I fixed it by downgrading the first three packages they listed to their previous commit

**Comment by pastthepixels** [comment]
Same here on Fedora Silverblue 37. Downgrading didn't seem to work for me but I noticed a new update to these packages that fixed this.

**Comment by zalnaRs** [comment]
> Same issue here after upgrading these packages about 15 minutes ago:
> 
>     * org.freedesktop.Platform.GL32.default
> 
>     * org.freedesktop.Platform.GL.default
> 
>     * org.freedesktop.Platform
> 
>     * org.freedesktop.Platform.Compact.i386
> 
> 
> Rebooting didn't fix it.
> 
> ![Screenshot_Spotify](https://user-images.githubusercontent.com/84247447/215176022-8b53d1d8-1c4a-492f-a343-5b8bb93e5dd0.png) ![Screenshot_Steam](https://user-images.githubusercontent.com/84247447/215176063-384fa8ab-bf32-4fa5-b99f-f9be0a784c71.png) ![Screenshot_Flatpak_Runtimes](https://user-images.githubusercontent.com/84247447/215178624-6432ed4a-96bb-483a-a856-8e9b2af1be31.png)
> 
> -- **Specs:**
> 
>     * Fedora Linux 37 (KDE Plasma)
> 
>     * Kernel: 6.1.7-200.fc37.x86_64
> 
>     * mesa-22.3.3-3.fc37
> 
>     * Flatpak runtimes: 22.3.3
> 
>     * zsh 5.9 (x86_64-redhat-linux-gnu)

This is true. I aleardy reset flatpak completely to see if it's some mesa corruption. And also tried reinstalling on the native system but then I realized that flatpaks have its own.

**Comment by zalnaRs** [comment]
For some reason it's now fixed.
Probably it upgraded in the background.
![image](https://user-images.githubusercontent.com/53659756/215261356-9ed45271-c7bf-4a9b-9035-51b399e1b940.png)

**Comment by gonzoknows** [comment]
Having the same issue highlighted here https://github.com/Vanilla-OS/os/issues/110#issuecomment-1407343684
