### ISSUE TITLE
Sceensharing fail in Firefox

### ISSUE THREAD

**Issue by ludvigng** [flatpak/flatpak#5273]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

1. Use firefox from flathub to go to any page to share the desktop (i.e., https://mozilla.github.io/webrtc-landing/gum_test.html)
2. Click screen capture.
3. Choose a window or an entire monitor.
4. Crash.

### Expected Behavior

Should be able to share a window or the desktop without crash.

### Actual Behavior

Crashes:
```
flatpak run org.mozilla.firefox
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[Parent 2, Main Thread] WARNING: gdk_wayland_window_configure: assertion 'width > 0' failed: 'glib warning', file /builds/worker/checkouts/gecko/toolkit/xre/nsSigHandlers.cpp:167

(firefox:2): Gdk-CRITICAL **: 07:38:34.149: gdk_wayland_window_configure: assertion 'width > 0' failed
ExceptionHandler::GenerateDump cloned child 620
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```

### Additional Information

I first thought this was a firefox problem and reported it in their issue tracker: https://github.com/webcompat/web-bugs/issues/117526

However, even rolling back to a previous version where I was sure it was working didn't help, which was weird. After further testing it seems to be related to the flatpak version, even starting from a completely clean environment (i.e. a liveCD), I can reproduce the issue by just installing firefox in flatpak 1.14 and sharing a window anywhere (meet, zoom, etc). Using a live environment with flatpak 1.12 makes the issue go away.

Interestingly it works on chrome, so I'm still not completely sure where the fault lies.

**Comment by hfiguiere** [comment]
I use Firefox flatpak screensharing regularly. Does this still happen? There have been numerous changes done in the stack.

**Comment by ludvigng** [comment]
No, I think this one has been solved since I reported it. I'll close it!
