### ISSUE TITLE
[Bug]: missing file in POTFILES.in

### ISSUE THREAD

**Issue by sabriunal** [flatpak/flatpak#5275]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

recent from git

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.10

### What architecture are you using?

x86_64

### How to reproduce

Hi, it seems we missed a file in POTFILES.in

> There are some missing files from POTFILES.in: common/flatpak-exports.c

A warning from Damned Lies : https://l10n.gnome.org/module/flatpak/

**Comment by smcv** [comment]
I believe this is the same issue that was fixed in #5283, and therefore in 1.15.2.

The 1.14.x branch doesn't currently have localizable text in `common/flatpak-exports.c`. I'll try to remember to include #5283 as part of the 1.14.x backport of #5213, which added those localizable strings.
