### ISSUE TITLE
[Bug]: Very slow Download Speeds

### ISSUE THREAD

**Issue by arthurmohn** [flatpak/flatpak#5276]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

Any app install or update

### Expected Behavior

I have a internet connection of  arrounf 550 mbps and can only download and update flatpak apps 20 - 100 kbps.

### Actual Behavior

![image](https://user-images.githubusercontent.com/52223014/216500556-abac7699-8bfb-487c-96b8-b8b3ee457f42.png)

**Comment by stroobandt** [comment]
FYI, your screenshot shows 104.4 kB(yte)/s, which actually corresponds to 835.2 kb(it)/s.
However, that is still a slow download speed.

**Comment by Lanhild** [comment]
Same issue, Fedora 37 as well

**Comment by Sharkitty** [comment]
I'm having the same issue with flatpak 1.14.4 on a fresh install of fedora-KDE 37. With download speed ranging between 28kB/s and 34kB/s (And my connection isn't particularly slow). Although it only happens with flathub remote for me! Download speed is fine with fedora remote.

Also, my downloads fail if I wait long enough to download one of the runtimes:
`Warning: While pulling runtime/org.freedesktop.Platform.GL.default/x86_64/22.08 from remote flathub: While fetching `<file_url>`: [92] Stream error in the HTTP/2 framing layer`

As a side note: I did some tests on fedora 38 beta inside a VM on a previous installation, and I did not encounter this problem in this environment. And I was running Pop!_OS 22.04 before that and never had this problem there either.

**Comment by sidt4** [comment]
flatpak install dowloads at  8 Mbps max, when my network bandwidth is > 200 Mbps.

Poor advertisement for flatpak.

**Comment by SanekTheDrone** [comment]
Same here, my ISP connection is 1Gbs, but flatpak downloads working on 25kb
![Screenshot from 2024-01-09 00-40-15](https://github.com/flatpak/flatpak/assets/40390416/7612153f-9e53-4d0b-adb7-bb3fcbd36207)
/s

**Comment by haseebabid72** [comment]
Having the same issue. Flatpak is on 20kB/s while my dnf goes upto 1-2MB/s.

**Comment by hfiguiere** [comment]
This is is flatpak doesn't operate any repository. Also like anything else, download speed can vary for many reason including you geographical location, the quality of your ISP peering, the geopolitical situation, etc.

There is very little that is actionable for flatpak.

**Comment by mitchsmith** [comment]
Not sure I buy the distance-from-cdn-excuse either, for the same reason as @hfiguiere mentions. On the other hand, what's the alternative? Snap? Gross!

**Comment by Lanhild** [comment]
It looks like this issue isn't an issue anymore for me as of Fedora 39. Downloads speeds are back to normal.

**Comment by hfiguiere** [comment]
There is nothing actionable.

Flatpak does not have any server to provide package. You all come in for "metoo" instead.
