### ISSUE TITLE
[Bug]: "Open with" portal chooser prompt dialog should automatically calculate the required height and show all applications without needing to expand / scroll, when possible

### ISSUE THREAD

**Issue by nekohayo** [flatpak/flatpak#5279]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

1. In a sandboxed application (such as Nautilus nightly), try to open any file
2. The file mimetype vs applications chooser dialog will appear, with tiny height and very limited choices, even when it the screen's real estate doesn't warrant this.

### Expected Behavior

Show all available choices, and size the window's height correctly by default to avoid scrolling, as long as there is enough vertical space available on the screen. [Don't make me scroll](https://fortintam.com/blog/dont-make-me-scroll/), don't make me waste an extra click to show all possibilities:

![image](https://user-images.githubusercontent.com/479401/216678978-a32cef22-b165-4a4c-a1dd-30872458d1a5.png)

### Actual Behavior

The current dialog shows up hardcoded to showing only 3 choices:

![Screenshot from 2023-02-03 13-21-49](https://user-images.githubusercontent.com/479401/216679438-650b630d-e04d-4957-89d0-9ace7a3ecae7.png)

...even if there is plenty of available height on my screen, and even if there were only 4 or 5 choices. Needing me to click the "..." line to reveal one more (or 2-3 more) items, and to scroll or resize the window, is [wasteful / annoying](https://zachholman.com/posts/shit-work/) for users.

**Comment by smcv** [comment]
Flatpak is not responsible for this dialog: Flatpak is not a GUI and does not contain any GUI code.

From the appearance of that dialog, I would guess that it's probably xdg-desktop-portal-gnome, which does not do bug tracking on Github. Please report issues with x-d-p-gnome to <https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues>.

If this behaviour is reproducible with xdg-desktop-portal-gtk, we can move this issue to https://github.com/flatpak/xdg-desktop-portal-gtk.

**Comment by nekohayo** [comment]
Ah, I did not know that, thank you for the pointers!

**Comment by nekohayo** [comment]
Filed as https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/69, hoping it's the right place, because I've been utterly unable to test whether the gtk portal is affected...
