### ISSUE TITLE
[Bug]: flatpak update won't run in the background

### ISSUE THREAD

**Issue by skierpage** [flatpak/flatpak#5296]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

In a terminal (I run zsh):
1. Enter `flatpak update` when there are flatpaks with updates.
2. When it offers "Proceed with these changes to the system installation?" enter `y`.
3. Press Ctrl-Z to suspend.
4. Enter `bg` to continue updating in the background so you can do other things in the terminal.

### Expected Behavior

Flatpak updating should proceed in the background, even if the cool progress spinners and updating mess up other terminal output.

### Actual Behavior

Most of the time the update won't proceed in the background, instead reporting
```
[1]  + suspended (tty output)  flatpak update
```
You have to enter `fg` to return the process to the foreground in order for the update for it to proceed.

### Additional Information

After I enter `fg` to proceed, I can no longer press Ctrl-Z to suspend `flatpak update` a second time, even after it reports 100% Updating progress and is (I assume) just cleaning up.

For comparison, I can suspend, background, foreground, re-suspend a `sudo dnf update` command at any time.

I want to see what's going to be updated, confirm it, then run the actual update in the background. I realize its `--noninteractive` and `--assumeyes` options probably affect its behavior, so I could run the command twice. But it would be nice if Ctrl-Z and bg "just worked."

**Comment by hfiguiere** [comment]
It's actually by design. Either pass `-y --noninteractive` or expect tty output for a background process to ask questions. As an alternative, just open another shell, or use something like tmux or screen.
