### ISSUE TITLE
installing runtime takes a lot of time

### ISSUE THREAD

**Issue by biji** [flatpak/flatpak#53]
My system is fedora 24 using BTRFS

flatpak install gnome org.freedesktop.Sdk 1.4

15 delta parts, 67 loose fetched; 188501 KiB transferred in 93 seconds

real	9m8.343s
user	0m0.094s
sys	0m2.421s

**Comment by alexlarsson** [comment]
That is very weird. I mean, it took forever, but it didn't use *either* system time or user time. Basically, that means it spent all the time waiting. 

@cgwalters any idea what could cause ostree to do something like this?

**Comment by alexlarsson** [comment]
Did you run this as root or your user?

**Comment by cgwalters** [comment]
Hard to say without tracing, but fsync could be a culprit?  We should have more instrumentation in the pull/commit process.

**Comment by biji** [comment]
as user, then I allow permission to install globally

**Comment by alexlarsson** [comment]
@biji If you can reproduce (i.e. by uninstalling the runtime first), can you try to reprocude with something like

```
sudo strace -o log -ftt flatpak install gnome org.freedesktop.Sdk 1.4
```
And attach the log file?

**Comment by alexlarsson** [comment]
Also, check if this makes it perform better:
https://github.com/flatpak/flatpak/commit/733a28c9c468d350b2276043b7876377368349d0

**Comment by biji** [comment]
The log is very big, here a few lines , when I tailf many fsync repeated

http://pastebin.com/0G7AkaPU

**Comment by alexlarsson** [comment]
Yeah, i believe https://github.com/flatpak/flatpak/commit/733a28c9c468d350b2276043b7876377368349d0 will fix this. Try again with 0.6.3 which i just released (will build packages).
