### ISSUE TITLE
Add the possibility to bisect applications regressions

### ISSUE THREAD

**Issue by thiblahute** [flatpak/flatpak#530]
On our [pitivi CI server](https://ci.gstreamer.net/job/pitivi-flatpak/)  we build pitivi and GStreamer for each and every git commit, meaning that we should be able to very simply bisect regressions using our flatpak builds.

Flatpak should introduce a new `flatpak bisect` command, the workflow should probably be similare to `git bisect` as people are familiar with it but we might be able to make something even simpler for flatpak.

The huge advantage of it over using `git bisect` is that we won't have to rebuild and we will be able to bisect all our built dependencies at once, even if that implies that it won't be as precise it will give us good hint very quickly.

**Comment by ebassi** [comment]
I'm not sure I understand how `flatpak bisect` would work.

Flatpak has no history to bisect; how do you bisect the progress between two states if you don't have the intermediate states?

Are you sure you don't want to just use `git bisect run` on your Git repository and build a Flatpak for every bisection steps?

**Comment by thiblahute** [comment]
flatpak will need to get the history basically using `ostree pull --depth=--1` and bisecting the ostree repo.

**Comment by alexlarsson** [comment]
I don't think the flatpak core should have a bisect command, but it should be doable in an external script, and we should have the core features in flatpak to support it. At the moment we *do* have flatpak update --commit=XXX, but we lack any history-listing for remote refs. One could probably do that with ostree though.

It might be an interesting experiment to try to write a script for this and see how far from this we are.

**Comment by thiblahute** [comment]
Just pushed a commit adding a `flatpak-bisect` python script, would you be interesting in distributing that as part of flatpak or how do you imagine it?

**Comment by alexlarsson** [comment]
I guess having it in the git repo makes sense.

It seems to break for system-installed apps.

**Comment by thiblahute** [comment]
> I guess having it in the git repo makes sense.
>
> It seems to break for system-installed apps.

Right, it currently only support user installs, also having it support system installs means it has to be run as root, do we want that?

I will also add it to the build system if you want it in tree, so it is installed.

**Comment by alexlarsson** [comment]
Hmm, maybe requiring it to be user installed for bisecting makes sense, you don't want to mess with system installs when doing this. However, maybe it should handle the case with a system installed app better. I.e. print an explanation instead of an error in this case.

**Comment by thiblahute** [comment]
> Hmm, maybe requiring it to be user installed for bisecting makes sense, you don't want to mess with system installs when doing this. However, maybe it should handle the case with a system installed app better. I.e. print an explanation instead of an error in this case.

DONE.

I also added the possibility to bisect runtimes and the script is now installed.
