### ISSUE TITLE
[Bug]: Flatpak Firefox Does Not Respect Scaling Factor in Wayland

### ISSUE THREAD

**Issue by anditosan** [flatpak/flatpak#5300]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### What architecture are you using?

x86_64

### How to reproduce

When using KDE Plasma in Wayland (Latest unstable version) we see that Firefox (flatpak edition) does not respect the scaling factor set by wayland and resorts to the maximum possible scaling.

In Plasma, users can access the package settings through system settings. I did this and enabled the X11 fallback in the checkable settings. Once I did this, firefox started behaving properly again using settings from X11.

This package should change to have this option enabled by default until proper wayland support is available. Other applications, particularly Electron-based applications suffer from the same problem and don't respect the scaling factor.

### Expected Behavior

Apply the set scaling factor.

### Actual Behavior

Shows application in 4k native resolution.

**Comment by matkeith** [comment]
I'm sure this is of no surprise but I am seeing the same behavior in fedora 37 using kde 5.27 and also while using the install from dnf

**Comment by smcv** [comment]
> also while using the install from dnf

The install of what? Firefox?

If a bug is specific to one app, and it's the same for that app installed via Flatpak or that same app installed via the system package manager (apt/dpkg, dnf/rpm or similar), then that can't be a Flatpak bug. Please report it to the developers of the app, which in this case is Firefox.

That's why we have the "If this is an issue with a particular app..." checkbox in the issue reporting template.

**Comment by smcv** [comment]
> This package should change to have [X11] enabled by default until proper wayland support is available

This issue tracker is for the Flatpak tool itself, which doesn't have any special-case code for specific apps.

If you think a particular package should have its permissions or other metadata changed, please report that to the source of your package for that app. For Firefox specifically, that's its upstream developer Mozilla. For other apps on Flathub like the Electron-based apps mentioned in the issue report, each app has an issue tracker like <https://github.com/flathub/com.discordapp.Discord/issues>.
