### ISSUE TITLE
[Feature request]: Please give a way to see how much RAM a running Flatpak is using

### ISSUE THREAD

**Issue by BillDietrich** [flatpak/flatpak#5301]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I want to see how much RAM each running Flatpak app is using, including all of its sub-processes etc.

I'm using Flatpak 1.14.0, systemd 245 (245.4-4ubuntu3.19), Zorin OS 16.

systemctl --user show -p MemoryCurrent app-flatpak-org.mozilla.firefox-9273.scope says "[not set]".

systemctl status --user app-flatpak-org.mozilla.firefox-9273.scope does not show memory used.

systemctl --user show -p MemoryAccounting app-flatpak-org.mozilla.firefox-9273.scope says "MemoryAccounting=yes".

systemd-cgtop does not show scopes.

**Comment by smcv** [comment]
Flatpak is not doing anything special to enable or disable memory accounting on the scopes that it creates. I would suggest talking to your OS vendor: it shouldn't be up to Flatpak to second-guess whether systemd keeps track of memory use.

> systemctl --user show -p MemoryCurrent app-flatpak-org.mozilla.firefox-9273.scope says "[not set]".

The equivalent is working for me on Debian 12 alpha (systemd 252.5-2), and gives me a memory use figure.
