### ISSUE TITLE
API/specifications of the FUSE portals.

### ISSUE THREAD

**Issue by stefbon** [flatpak/flatpak#5321]
Hi,

as a writer of OSNS I'm interested in the FUSE portal filesystems. Maybe I want to add these to my project.
Info about OSNS: this is a set of applications to enable the user on a workstation to cooperate better with others in an office environment. To make that work the OSNS client creates FUSE mountpoint(s) like 

`/run/network/1000/fs/`

where a browseable map is created by OSNS to provide the user an overview what is available on the network. A typical map looks like:

             Open Secure Network/bononline.nl/myserver/{home,public}

This proved fs access to the shared home and public folder in de host myserver in the bononline.nl domain.

To do this I've written my own FUSE implementation (userspace) (and SSH and SFTP library).
If I want to add support for the various fuse.portal filesystem to my project (eg write my own FUSE fs and mount them when a session starts and umount when it ends at the desired mountpoints), where can I find the documentation?

Thanks in advance,

S. Bon

See: https://github.com/stefbon/OSNS
(repo is not synced for a year, a lot has been changed since then, I will update it soon).

**Comment by jtojnar** [comment]
It is apparently possible to use FUSE by escaping the sandbox by creating a fake `fusermount` in `/app/bin` that calls `fusermount` on the host using [flatpak-spawn](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn). See e.g. [Pika Backup](https://github.com/flathub/org.gnome.World.PikaBackup/blob/958af8d4670fd03fff84dc08ff3b668c8f953e10/org.gnome.World.PikaBackup.yml#L72) for an example, and [File Roller MR](https://gitlab.gnome.org/GNOME/file-roller/-/merge_requests/112#note_1792253) for more info.

> **Warning** This completely breaks sandboxing so it may be inadvisable.

**Comment by hfiguiere** [comment]
This is for https://github.com/flatpak/xdg-desktop-portal
