### ISSUE TITLE
[Bug]: GLib-CRITICAL logs while performing a search through CLI

### ISSUE THREAD

**Issue by Tejaromalius** [flatpak/flatpak#5323]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

1. Open a bash window
2. Write "flatpak search telegram" (in this case telegram is an example)

### Expected Behavior

a list of applications that may be related telegram

### Actual Behavior

hundreds of lines of logs in critical level indicating the same problem:
```(flatpak search:33567): GLib-CRITICAL **: 22:49:08.658: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed

(flatpak search:33567): GLib-CRITICAL **: 22:49:08.658: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed

(flatpak search:33567): GLib-CRITICAL **: 22:49:08.659: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed

(flatpak search:33567): GLib-CRITICAL **: 22:49:08.659: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed

(flatpak search:33567): GLib-CRITICAL **: 22:49:08.659: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed

(flatpak search:33567): GLib-CRITICAL **: 22:49:08.659: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed
```

### Additional Information

Currently I use the "software" application to avoid this problem

**Comment by smcv** [comment]
This is a bug in libappstream, and I contributed a fix for it a year ago: https://github.com/ximion/appstream/issues/384. Please ask Ubuntu to upgrade their libappstream or backport the fix.

https://bugs.launchpad.net/ubuntu/+source/appstream/+bug/2006110 is a request for a newer libappstream to be incorporated into a 22.04 update.

**Comment by Tejaromalius** [comment]
Okay, thank you for your response!
