### ISSUE TITLE
Error: The application org.flatpak.flat-manager-client/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/18.08 which was not found

### ISSUE THREAD

**Issue by BlackMage2** [flatpak/flatpak#5324]
I have the error: "The application org.flatpak.flat-manager-client/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/18.08 which was not found". but i have already org.freedesktop.Platform in version 22.08rc.3 installed.

**Comment by smcv** [comment]
o.fd.Platform version 18.08 is not equal to, or compatible with, o.fd.Platform version 22.08. Each new o.fd.Platform version (one per year) removes deprecated libraries that were in the previous year's runtime.

If this application needs a runtime that was EOL several years ago, then your choices are: either don't install that application, or find a copy of the old runtime from somewhere, or rebuild the application against a newer SDK.

**Comment by smcv** [comment]
Flatpak is installed on your host OS. You can't install Flatpak by using Flatpak.

`org.flatpak.flat-manager-client/x86_64/beta` is something different, possibly https://github.com/flatpak/flat-manager.
