### ISSUE TITLE
[Bug]: finish-args: --filesystem=host/home overrides --env=PATH=/app/bin:/usr/bin, uses ~/.bashrc's PATH value

### ISSUE THREAD

**Issue by fastrizwaan** [flatpak/flatpak#5328]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Rocky Linux 9.1

### What architecture are you using?

x86_64

### How to reproduce

`--filesystem=host` is reading ~/.bashrc and setting that PATH value.

```
finish-args:
  - --filesystem=host:ro
  - --env=PATH=/app/bin:/usr/bin

```

e.g., apps which use `--filesystem=host` show this 

```
[rizvan@localhost flatpak-winezgui]$ flatpak install scite
[rizvan@localhost flatpak-winezgui]$ flatpak run --command=bash org.scintilla.SciTE
[📦 org.scintilla.SciTE flatpak-winezgui]$ echo $PATH
/home/rizvan/.local/bin:/home/rizvan/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/rizvan/.bin
```
if we remove `host` access, the PATH is assigned properly

```
[rizvan@localhost flatpak-winezgui]$ sudo flatpak override --nofilesystem=host org.scintilla.SciTE 
[sudo] password for rizvan: 
[rizvan@localhost flatpak-winezgui]$ flatpak run --command=bash org.scintilla.SciTE
[📦 org.scintilla.SciTE ~]$ echo $PATH
/app/bin:/usr/bin
```

### Expected Behavior

`flatpak --command=bash x.y.z` echo $PATH should show `/app/bin:/usr/bin` even when `--filesystem=host` access is given.

### Actual Behavior

`--env=PATH=/app/bin:/usr/bin` is not applied when `finish-args:`  include `--filesystem=host` or `--filesystem=home`
```
[rizvan@localhost flatpak-winezgui]$ sudo flatpak override --filesystem=home org.scintilla.SciTE 
[sudo] password for rizvan: 
[rizvan@localhost flatpak-winezgui]$ flatpak run --command=bash org.scintilla.SciTE
[📦 org.scintilla.SciTE flatpak-winezgui]$ echo $PATH
/home/rizvan/.local/bin:/home/rizvan/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/rizvan/.bin
```

### Additional Information

Both `--filesystem=HOST` and `--filesystem=HOME` are overriding `PATH` variable of the flatpak sandbox.

**Comment by fastrizwaan** [comment]
the position of `--norc `needs to be `at the end of cmdline` always. 
But the `--norc` has no effect for these (`command=bash` and` -c "echo $PATH"`)
```
[rizvan@localhost ~]$ gnome-terminal --wait -- flatpak run --command=bash org.scintilla.SciTE -c "echo $PATH; sleep 5s" --norc
[rizvan@localhost ~]$ gnome-terminal --wait -- flatpak run --command=bash org.scintilla.SciTE -c "echo $PATH; sleep 5s" 
```
The above both showing `PATH` from `~/.bashrc`

Also, since, `home` and `host` are already using `PATH` from `.bashrc`, perhaps _appending flatpak manifest's_` --ENV=PATH=/app/bin:/abc/xyz` to the _runtime PATH in sandbox_  like `PATH=$PATH_from_bashrc:PATH_from_flatpak_ENV_variable` could be a solution.` /app/bin ` is  _**the required sandboxed PATH**_  

Isn't it absurd that bash inside sandbox, can't find binaries from `/app/bin`;  because, it is reading `~/.bashrc PATH` which has no idea about sandboxed binary locations `/app/bin`?

**Comment by smcv** [comment]
> Also, since, `home` and `host` are already using `PATH` from `.bashrc`, perhaps _appending flatpak manifest's_` --ENV=PATH=/app/bin:/abc/xyz` to the _runtime PATH in sandbox_ like `PATH=$PATH_from_bashrc:PATH_from_flatpak_ENV_variable` could be a solution.

No, by the time your `.bashrc` has changed the `PATH`, Flatpak no longer has control over the environment. (You're welcome to try to implement this if you don't believe me; and maybe you'll prove me wrong, but more likely you'll find that it isn't possible.)

> Isn't it absurd that bash inside sandbox, can't find binaries from `/app/bin`; because, it is reading `~/.bashrc PATH` which has no idea about sandboxed binary locations `/app/bin`?

bash does what you tell it to do (via .bashrc or otherwise), whether it's absurd or not. If you tell it to stop using /app/bin, it will stop using /app/bin.

**Comment by smcv** [comment]
If you make your `.bashrc` append or prepend to the `PATH`, something like

```
export PATH=/home/rizvan/.local/bin:/home/rizvan/bin:/usr/lib64/ccache:$PATH`
```

or

```
export PATH="$PATH:/home/rizvan/.bin"
```

instead of overwriting it completely, then the PATH will continue to have /app/bin in it.

The .bashrc is your configuration, under your control, and fully programmable. So you can make it do whatever you want, but equally, if you make it do something that you *don't* want, it's up to you to fix that.

**Comment by fastrizwaan** [comment]
It's not just for my single use, my application winezgui (gui for wine) provides shell access using gnome-terminal, so that users could run `winetricks` or `wine` from `/app/bin`

this `/app/bin` not in the `PATH`  is breaking my app feature with `home ` and `host ` filesystem access. Usually games are huge in size, so they'll be place in a different partition, so host access is required. or home is required if user has games place in different directories.

This is the command which will be launched on user selecting open shell
```
gnome-terminal --wait -- \
    flatpak  --command=bash run ${FLATPAK_NAME} \
    -c  "cd \"${PREFIXDIR}\"; exec bash -i"
```

So, my requirement is both `host` and `PATH=/app/bin` which is expected.

Is there a way to skip reading `~/.bashrc PATH` variable ? like `flatpak run x.y.z --command=bash --norc ~/.bashrc`

tried setting PATH for bash subshell but it does not work for flatpak bash. like 

#### works on host/system
```
[rizvan@localhost io.mpv.Mpv]$ export PATH=$PATH:/app/bin bash 
[rizvan@localhost io.mpv.Mpv]$ echo $PATH
/home/rizvan/.local/bin:/home/rizvan/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/rizvan/.bin:/app/bin:/app/bin
```


#### but same this fails
```
[rizvan@localhost io.mpv.Mpv]$ flatpak run --filesystem=host --command=bash org.winehq.Wine -c "export PATH=$PATH:/app/bin bash"
[rizvan@localhost io.mpv.Mpv]$ echo $PATH
/home/rizvan/.local/bin:/home/rizvan/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/rizvan/.bin
```

**Comment by smcv** [comment]
> What's the point of having --ENV=XX=yy when it is not respected?

Even if we wanted `--env` to win, the behaviour you are asking for doesn't seem to be implementable, and we can't do impossible things.

Also, I could equally well say: what's the point of having `~/.bashrc` when it's not respected? And we can't both win: one of them has to take precedence over the other. We might as well go with the one that's possible, and not try to do the one that isn't.

> ```
> [rizvan@localhost io.mpv.Mpv]$ export PATH=$PATH:/app/bin bash 
> [rizvan@localhost io.mpv.Mpv]$ echo $PATH
> ```

Those commands don't do what you think they do. The first command exports `PATH`, and also exports a variable named `bash` (which probably isn't set). The second command prints the value of `PATH`. Neither one launches a subshell.

The syntax for what you are trying to demonstrate here would be either

```
parent shell$ export PATH=$PATH:/app/bin; bash
subshell$ echo $PATH
subshell$ exit
parent shell$
```

or

```
parent shell$ PATH=$PATH:/app/bin bash
subshell$ echo $PATH
subshell$ exit
parent shell$
```

but trying to combine the two won't work. (Yes, shell script is an awful programming language.)

> Is there a way to skip reading ~/.bashrc PATH variable ?

No. You can skip reading .bashrc completely, or you can read it, but you can't selectively apply only part of it.

> This is the command which will be launched on user selecting open shell
>
> ```
> gnome-terminal --wait -- \
>     flatpak  --command=bash run ${FLATPAK_NAME} \
>     -c  "cd \"${PREFIXDIR}\"; exec bash -i"
> ```

Something more like this might work (untested):

```
gnome-terminal --wait -- \
    flatpak  --command=bash run ${FLATPAK_NAME} \
    --norc -c  "cd \"${PREFIXDIR}\"; exec bash --norc -i"
```

If the value of `PREFIXDIR` contains double quotes or other scary stuff, then you have an unrelated shell injection vulnerability in that code. Again, shell script is an awful programming language.

Something like this would avoid the shell injection vulnerability (again, untested):

```
gnome-terminal --wait -- \
    flatpak  --command=bash run "${FLATPAK_NAME}" \
    --norc -c  'cd "$1"'; shift; exec bash --norc -i' sh "$PREFIXDIR"
```

(This is the sort of nonsense you have to be aware of to write robust programs in shell script. I don't recommend it.)

**Comment by fastrizwaan** [comment]
> 
```
gnome-terminal --wait -- \
    flatpak  --command=bash run ${FLATPAK_NAME} \
    --norc -c  "cd \"${PREFIXDIR}\"; exec bash --norc -i"
```
and
```
gnome-terminal --wait -- \
    flatpak  --command=bash run "${FLATPAK_NAME}" \
    --norc -c  'cd "$1"; shift; exec bash --norc -i' sh "$PREFIXDIR"
```
both work, thanks.
