### ISSUE TITLE
About something being printed during installation or update of apps

### ISSUE THREAD

**Issue by adityashah1212** [flatpak/flatpak#533]
I am getting this when an app is either updated to installed. I don't remember if it comes during app uninstallation.
```
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /root/.local/share
- /usr/local/share/
- /usr/share/
```
I don't exactly know what it means or how to fix it, but I don't remember changing anything related to those to environment variables. There one thing though, I didn't encounter any problems either during the installation/update or while running the app.

**Comment by alexlarsson** [comment]
I wonder if this is fixed by https://github.com/flatpak/flatpak/commit/78c3391b78f8ff8fb295fe328d36d0b29983801b

If so, it should be in 0.8.1. What version do you have?

**Comment by adityashah1212** [comment]
I have fedora 25 repo version 0.8.2

**Comment by alexlarsson** [comment]
Weird. Just to check, when you've logged in, what is the value of the XDG_DATA_DIRS environment variable?

**Comment by adityashah1212** [comment]
/home/aditya/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/

**Comment by adityashah1212** [comment]
It didn't show up today... weird.

**Comment by alexlarsson** [comment]
Closing for now then.

**Comment by ndmax** [comment]
I'm still seeing this message:

`flatpak --user --assumeyes update`

> Note that '/home/user/.local/share/flatpak/exports/share' is not in the search path set by the XDG_DATA_HOME and XDG_DATA_DIRS

The odd thing is that it seem to be correctly set for the session:

`echo $XDG_DATA_DIRS`

> /usr/share/budgie-desktop:/home/user/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop

And it seems to be set correctly by this X-session init script:

`/etc/X11/Xsession.d/20flatpak`

What is triggering the warning?  It seems like a false positive; all install flatpak apps seem to fire up and work just fine...

**Comment by melolontha-melolontha** [comment]
Strange! After one week this one was closed, just because syndrome was not show up on one day. But later one more came up with it. And of course, when I installed the flatpack-version of Roger Router under Xubuntu 18.04.4 I also saw this weird message:

`
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them.
`

In my case I get

`a@w:~$ echo $XDG_DATA_HOME        # this one returns nothing
`
`a@w:~$ echo $XDG_DATA_DIRS          # but this one does
/usr/share/xfce4:/home/adalbert/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share`
`a@w:~$ `

**I think this case should have been re-opened at least when ndmax commented it.** This bug has also been noticed by others who pointed me to this thread when I asked them what to do. But unfortunately I did not find an explanation for it here nor what I have to do to prevent such an error message from being shown. The one who pointed me tho this thread described it as a "bug in flatpak".

**Comment by refi64** [comment]
That message is rather old, did you [install the latest version from the PPA](https://flatpak.org/setup/Ubuntu/)?

**Comment by Brog33** [comment]
I still get this. Flatpak 1.6.5

**Comment by mwleeds** [comment]
@Brog33 that is a very old version of Flatpak, and if you are using a shell other than Bash that might also be relevant (#3109)

**Comment by Brog33** [comment]
I'm just using the default in Ubuntu 20.04 repos + bash. Which version do you recommend to upgrade to?

**Comment by mwleeds** [comment]
You can get a newer version here: https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

**Comment by smcv** [comment]
> You can get a newer version here: https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

I think we should probably prefer to recommend https://launchpad.net/~flatpak/+archive/ubuntu/stable/ which doesn't have Alex as a single-point-of-failure for updates.

**Comment by baskin77** [comment]
This problem still exists with Flatpak 1.14.3 (currently latest) on Ubuntu 20.04 LTS

**Comment by careca1970** [comment]
I confirm affirmation from @baskin77.  Flatpak 1.14.4 on Fedora 37.

“False positive” message seems still to persist.

This is the message during flatpak packages update,
by issuing:

$ sudo flatpak -y update

```
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:
```

This are actual contents of system variables:

```
$ echo $XDG_DATA_HOME

```

```
$ echo $XDG_DATA_DIRS
/home/Alex/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```


Thou, flatpak's applications just seem to just function fine!

Regards, Careca

**Comment by careca1970** [comment]
I got an explanation for my issue.

I was issuing the update command as "root", by means of sudo.
It must be made as the actual user, do that the system variables are indeed correctly set.

**Comment by liza** [comment]
> I got an explanation for my issue.
> 
> I was issuing the update command as "root", by means of sudo. It must be made as the actual user, do that the system variables are indeed correctly set.

thanks @careca1970 for posting this. 

i forgot i added myself to the _flatpak group; so i have no need to use sudo when working with flatpaks. i used it on a recent uninstall and it threw that error message. 

i can't find the documentation for installation setups involving admins and users. i thought that information was at flathub but can't find it. may be my dyslexia, but all i can see is documentation for developers. 

anyhow, seems there's need to write out clearly how to set up perms for admins and end-users and what error messages to expect such as this one. 

just a gentle reminder that you can't have buy in if admins and regular end-users have to run around piecing together information about how to best manage their flapps installations.

so the **TL;DR** : if as an admin or lonely linux end-user, you're part of the **"_flatpak"** group, **you do not need to use sudo**. if you do, this message will pop-up. this 

cheers.

**Comment by bremme** [comment]
Just did a fresh in stall of Debian 12. I also just got this message while uninstalling a package:

```shell
        ID                           Branch        Op
 1. [-] com.visualstudio.code        stable        r

Uninstalling…
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /root/.local/share
        ID                           Branch        Op
 1. [-] com.visualstudio.code        stable        r
```


```shell
$ echo $XDG_DATA_DIRS 
/home/<username>/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop

$ echo $XDG_DATA_HOME             

$ flatpak --version 
Flatpak 1.14.4
```

**Comment by melolontha-melolontha** [comment]
As the version of Flatpak is part of this discussion, I repeat some command now to show my versions and environment:

`v@w:/home/a$ date
2023-07-13T16:28:41+02:00
v@w:/home/a$ flatpak --user --assumeyes update

Note that the directory 

'/home/verwalter/.local/share/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for updates…
Nothing to do.
v@w:/home/a$  echo $XDG_DATA_HOME        # this one returns nothing

v@w:/home/a$  echo $XDG_DATA_DIRS          # but this one does 
/usr/share/xubuntu:/usr/share/xfce4:/home/**a**/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share
v@w:/home/a$ flatpak --version
Flatpak 1.11.2
v@w:/home/a$ uname -rm
5.4.0-152-generic x86_64
v@w:/home/a$`

I have two users, a and v. v has administrative rights (but I did not have to uses `sudo` in this, so it did not really matter). The strange thing is that `$XDG_DATA_DIRS` refers to **a**'s home directory.

Could it be a clue to this issue?

**Comment by melolontha-melolontha** [comment]
N.B.: Why is this discussion closed, although it is nor resolved? The real reason and possible consequences seem not to have been covered in this discussion.
