### ISSUE TITLE
Trying to run LibreOffice Flatpak

### ISSUE THREAD

**Issue by inukaze** [flatpak/flatpak#534]
Hi there, i recently download the Flatpak from LibreOffice website
https://www.libreoffice.org/download/flatpak/

and make the process:
```
wget https://sdk.gnome.org/keys/gnome-sdk.gpg
flatpak remote-add --user --gpg-import=gnome-sdk.gpg gnome https://sdk.gnome.org/repo/
flatpak install --user gnome org.gnome.Platform 3.20
flatpak install --user gnome org.gnome.Platform.Locale 3.20
flatpak install --user --bundle LibreOffice.flatpak
```

and try to run:
`flatpak run org.libreoffice.LibreOffice`
> Can't mkdir parents for /home/inukaze/.cache/.dbus-proxy/: No such file or directory

and LibreOffice don't load

How i fix it ???

**Comment by alexlarsson** [comment]
I belive this is fixed by https://github.com/flatpak/flatpak/commit/161401317e7ceefb950a79888fc53f08f5e85e98 and should be in 0.8.2

**Comment by inukaze** [comment]
Ok i am updating now : 

```

cd /media/Compartido/Software/Liñux/src/git/
git clone https://github.com/flatpak/flatpak
cd flatpak/
./autogen.sh
./configure --prefix=usr
make
su -c "make install ; ldconfig" root
flatpak run org.libreoffice.LibreOffice
error: Failed to execute child process "/usr/local/libexec/flatpak-bwrap" (No existe el fichero o el directorio)
```

Ok i go try again
```
su -c "make uninstall" root
su -c "rm -rf /usr/bin/flatpak" root
make clean
./autogen.sh
make
su -c "make install"
su -c "ln -s /usr/local/bin/flatpak /usr/bin/flatpak" root

flatpak --version
Flatpak 0.9.1

flatpak run org.libreoffice.LibreOffice```
Can't mkdir parents for /home/inukaze/.cache/.dbus-proxy/: No such file or directory

Ok the same again i go to trying remove LibreOffice and Install it again first

**Comment by alexlarsson** [comment]
Can you run: 
```
strace -o log -f  flatpak run org.libreoffice.LibreOffice
```
and put the `log` file somewhere i can read it

**Comment by inukaze** [comment]
```
strace -o log -f  flatpak run org.libreoffice.LibreOffice
Can't mkdir parents for /home/inukaze/.cache/.dbus-proxy/: No such file or directory
```

Nothing happen

**Comment by alexlarsson** [comment]
strace writes a file called log, which i'd like to see

**Comment by inukaze** [comment]
You can read [here](http://pasted.co/013575a9)

**Comment by alexlarsson** [comment]
That reads very very strange. Take this part for instance:
```
6776  stat("/newroot/home/inukaze/.cache", 0x7fff478a2040) = -1 ENOENT (No such file or directory)
6776  mkdir("/newroot/home/inukaze/.cache", 0755) = -1 EEXIST (File exists)
```
I.e. "oh, its not there, lets create it", then "can't create it because it already exists".

I can't really explain why this is happening at all...

**Comment by alexlarsson** [comment]
What filesystem is /home on?

**Comment by inukaze** [comment]
i ever use ext3, btrfs or xfs. let me check. this is ext3 :)

and why the flatpak not use something like

```
if test -d "$HOME/.cache"
then
       commands
fi

if test ! -d "$HOME/.cache"
then
       mkdir -p "$HOME/.cache"
fi
```

for example, i ever use commands like that on my bash scripts.

**Comment by alexlarsson** [comment]
That is not a bash script, those are kernel system calls.

**Comment by iprok** [comment]
Got the same issue with linphone flatpak, with last (0.8.7) version of flatpak. Got the message:
Can't mkdir parents for /var/run/user/1001/.dbus-proxy/: No such file or directory
it was because /var/run is symlink to /run and XDG_RUNTIME_DIR=/var/run/user/1001. I've resolved the issue by running:
XDG_RUNTIME_DIR=/run/user/1001 flatpak run com.belledonnecommunications.linphone

**Comment by ahhsia** [comment]
I'm getting a similar error with version 0.8.7 on RHEL7 but while trying to run the inkscape flatpak
```
flatpak run org.inkscape.Inkscape
Can't mkdir parents for /home/username/.local/share/flatpak: No such file or directory
```
My XDG_RUNTIME_DIR is pointing to the right place under /run/user

**Comment by samson-jerome** [comment]
Hello,
I have a similar pb with Builder...
```
$ flatpak run org.gnome.Builder
Can't mkdir /production/people/jerome: No such file or directory
```
Any idea ?

**Comment by pythoneer** [comment]
I am also having trouble running various packages 

`
$ flatpak --version
Flatpak 0.9.10

flatpak run org.gnome.Builder 
Can't mkdir parents for /home/<USER>/.local/share/flatpak: No such file or directory
`

i have to note here that `~/.local` is symlinked similar to what is reported here #749

**Comment by YogSottot** [comment]
```
>flatpak --version
Flatpak 0.9.98.2

```
```
flatpak run com.skype.Client 
Can't mkdir parents for /var/run/user/1000/.dbus-proxy/: No such file or directory
 
```
The directory exists and is writable for the current user

This workaround is works for me.
`>XDG_RUNTIME_DIR=/run/user/1000 flatpak run com.skype.Client
`

**Comment by EoD** [comment]
The issue still exists
```
$ flatpak --version
Flatpak 0.10.3
```

Strace also reveals, that the folder is indeed accessible and that flatpack created an object inside the folder:
```strace
1083 newfstatat(AT_FDCWD, "/var/run/user/1000/.dbus-proxy", {st_mode=S_IFDIR|0755, st_size=620, ...}, AT_SYMLINK_NOFOLLOW) = 0
1084 open("/var/run/user/1000/.dbus-proxy/a11y-bus-proxy-WQU6DZ", O_RDWR|O_CREAT|O_EXCL, 0600) = 16
1085 close(16)                               = 0
...
1125 read(15, Can't mkdir parents for /var/run/user/1000/.dbus-proxy/: No such file or directory
```

So I assume that the error message is wrong here.

**Comment by netcrave** [comment]
RIP

**Comment by inukaze** [comment]
Well right now i am under "Devuan Jessie 1.0"

```
$ flatpak --version
Flatpak 0.8.9

#This version is from Official Debian Jessie Backports Repository.

$ flatpak run ca._0ldsk00l.Nestopia
Can't mkdir parents for /home/inukaze/.cache/.dbus-proxy/: No such file or directory

```

This issue still exists. that should be fixed in newer versions xD [after i will going to purge the installation of repository and try download from github an compile, evers its much better do that]

well follow the workaround of EoD i try

`XDG_RUNTIME_DIR=/run/user/$UID flatpak run ca._0ldsk00l.Nestopia`
> Failed to read config file /home/inukaze/.var/app/ca._0ldsk00l.Nestopia/config/nestopia/nestopia.conf: Using defaults.
> Couldn't initialize SDL: Could not setup connection to PulseAudio

¬¬

**Comment by hfiguiere** [comment]
I run LibreOffice everyday with Faltpak.

out of date.
