### ISSUE TITLE
[Feature request]: The word "Installations" is confusing and counter productive

### ISSUE THREAD

**Issue by airtonix** [flatpak/flatpak#5347]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Explaining, search for and remembering what this concept is for results in wasted time and misunderstanding.

Call it `Collection` instead.

**Comment by hfiguiere** [comment]
the issue is confusing and counter productive as it provide too little context to explain what the problem is.
