### ISSUE TITLE
[Feature request]: How to make calibre(flatpak) find wine(flatpak)

### ISSUE THREAD

**Issue by tiklii** [flatpak/flatpak#5359]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I am using Calibre with the plugin 'kfx output'. It depends on Kindle_Previewer, a windows only application. On linux, it expects kindle previewer to be installed in ~/.wine prefix and wine to be present at /usr/bin. I already have a wine prefix with kindle previewer installed at the right location.

Both Calibre and wine (org.winehq.Wine 8.0) are installed as flatpaks. How would I make Calibre find the flatpak wine? Of course, other than installing wine from my distro package manager.

**Comment by hfiguiere** [comment]
The short answer is that you can't.
