### ISSUE TITLE
[Bug]: We had gnu octave package in flatpak but not rtmidi present on image

### ISSUE THREAD

**Issue by jcbritobr** [flatpak/flatpak#5364]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

fedora 37

### What architecture are you using?

x86_64

### How to reproduce

1 - Intall gnu octave 8.1 from flathub
2 - try to install audio package - pkg install -forge audio
3 - it fails as flatpck image doesn't has rtmidi-devel dependencies, even if you have installed in local machine as rpm

### Expected Behavior

1 - Intall gnu octave 8.1 from flathub
2 - try to install audio package
3 - pkg install -forge audio
4 - all needs work correctly

### Actual Behavior

Gnu Octave can't rtmidi as its dependencies in fedora 37 installing it from flathub

### Additional Information

>> pkg install -forge audio
configure: error: RTMIDI required to install octave audio package
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for mkoctfile... /app/bin/mkoctfile-8.1.0
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for RTMIDI... no

error: pkg: error running the configure script for audio
error: called from
    configure_make at line 101 column 9
    install at line 202 column 7
    pkg at line 619 column 9
>>

$ sudo dnf install rtmidi-devel
Last metadata expiration check: 0:29:15 ago on Tue 21 Mar 2023 11:37:23 AM -03.
Package rtmidi-devel-4.0.0-3.fc37.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by Alexander-Wilms** [comment]
The dependency will need to be added to the Flatpak manifest here: https://github.com/flathub/org.octave.Octave

**Comment by smcv** [comment]
Flatpak apps intentionally don't use dependency libraries from the host system. We can't have it both ways: the application cannot be both separated from the host system, and tightly integrated with the host system.

If you want to use dependency libraries from the host system, please use something that isn't Flatpak (for example RPM packages). Or if you want to load plugins into a Flatpak app, the plugins or their dependencies need to be included in the app or the app's runtime, or packaged separately as an extension.

**Comment by jcbritobr** [comment]
will get this log and put in flatpak application repository

**Comment by Alexander-Wilms** [comment]
I added it here: 

https://github.com/flathub/org.octave.Octave/pull/277

Can you test if it works for you when the build ist done? You can run the Test build with `flatpak run org.octave.Octave//test`
