### ISSUE TITLE
[Feature request]: Simple way to switch the remote for an installed flatpak

### ISSUE THREAD

**Issue by AdamWill** [flatpak/flatpak#5365]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Recently I wanted to test a candidate update for a Fedora flatpak. This is similar to testing an update for an RPM package, which is a common thing to do.

For RPM packages, it's easy, and we have nice clear instructions for folks to do it. For flatpaks, we have no instructions, so I had to figure it out for myself, and it turned out to be rather difficult.

First I had to enable the necessary remote. OK, that makes sense, and it's not hard - `flatpak remote-modify --enable fedora-testing`. I can write instructions for that.

For the RPM case, all you have to do is enable the updates-testing repository, and update the package you want to test. The package manager will see there's a newer version of the package in the newly-enabled repository and update to it.

Flatpak apparently doesn't do this, though. Even though I'd enabled the remote, and it contained a newer version of the flatpak than the one I had installed from the 'stable' remote, running `flatpak update` did not update it. It appears I have to tell flatpak that I want it to pull an update from the newly-configured remote.

That's a bit harder, but at least if there was a simple command to do that, it wouldn't be so bad. But...I couldn't find one. Instead, I had to remove the flatpak entirely and reinstall it:

    flatpak remove --force-remove org.fedoraproject.Platform
    flatpak install org.fedoraproject.Platform

as you can see, this was particularly awkward since the update I wanted to test was for a runtime - I had to find out about `--force-remove`, because obviously I have a lot of other flatpaks installed that depend on the runtime.

This feels like it's way more awkward than it needs to me, and it'd be a shame to have to write instructions that explain you need to do all this just to test a candidate update. Did I miss any existing way to do this more easily? If not, could there be a way to do this more easily?

Thanks!

**Comment by refi64** [comment]
Does using `--reinstall` work?

**Comment by smcv** [comment]
> flatpak install org.fedoraproject.Platform

This is a shorthand command meaning "install org.fedoraproject.Platform from ... somewhere", which won't do anything if you already have a valid copy of it.

> Even though I'd enabled the remote, and it contained a newer version of the flatpak than the one I had installed from the 'stable' remote, running flatpak update did not update it

Flatpak doesn't have a concept of apps or runtimes being "older" or "newer" than each other: it's not like apt or yum where the newest version of a .deb or RPM across all repositories is the default. Remotes are more like git remotes than apt repositories: if you have `runtime/org.freedesktop.Platform/x86_64/22.08` installed from the remote `flathub`, then `flatpak update` will try to replace it with the version of `runtime/org.freedesktop.Platform/x86_64/22.08` that `flathub` says is current now.

I think what you want here is something more like:

```
flatpak remote-modify --enable fedora-testing
flatpak install fedora-testing org.fedoraproject.Platform
# or org.fedoraproject.Platform//38, or maybe even runtime/org.fedoraproject.Platform/x86_64/38
```

**Comment by smcv** [comment]
If you were acting on an app rather than a runtime, you might also need a command like `flatpak make-current org.gnome.Recipes 44` to force a specific branch of that app to be the one that is seen by the rest of the system.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flatpak/flatpak/issues/5365#issue-1636511429

@AdamWill, this appears similar to https://github.com/flatpak/flatpak/issues/5470#issue-1792212421.

**Comment by chrisawi** [comment]
Closing as this seems to be covered by `flatpak install --reinstall`.
