### ISSUE TITLE
[Feature request]: Support (configuring) systemd's resource controls

### ISSUE THREAD

**Issue by nbraud** [flatpak/flatpak#5368]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Currently, [`flatpak_run_in_transient_unit`] doesn't set properties other than `PIDs` on the app's scope.  Since those scopes are named `app-flatpak-{appid}-{pid}.scope`, systemd's drop-ins mechanism cannot be used to have custom settings either.

This is especially problematic in the context of resource control settings, as the defaults are inappropriate in the context of flatpak:
- `OOMPolicy` inherits from the system-wide default, *i.e.* the entire app will be taken down when *any* of its process dies due to OOM.  For instance, this results in an entire browser being taken down when (outside flatpak) a single tabs would have been. 
- `Delegate` is off, meaning apps cannot use cgroups and various kind of BPF filters for their own sandboxing; this is again a major issue in the context of browsers etc.

I believe the simplest way to change that would be to make flatpak's app scopes follow a template, letting users leverage systemd's drop-ins mechanism:
- `app-flatpak@{appid}-{pid}.scope` allows configuring defaults for all apps easily;
- `app-flatpak-{appid}@{pid}.scope` allows per-app settings.

[`flatpak_run_in_transient_unit`]: https://github.com/flatpak/flatpak/blob/23ec4eda2f52e1570e2296061f9fd4763d7e3721/common/flatpak-run.c#L2227-L2236

**Comment by rusty-snake** [comment]
> Currently, [flatpak_run_in_transient_unit](https://github.com/flatpak/flatpak/blob/23ec4eda2f52e1570e2296061f9fd4763d7e3721/common/flatpak-run.c#L2227-L2236) doesn't set properties other than PIDs on the app's scope. Since those scopes are named app-flatpak-{appid}-{pid}.scope, systemd's drop-ins mechanism cannot be used to have custom settings either.

Can you explain how this naming breaks systems drop-ins?


FTR: 
- > The list of directories searched for drop-ins includes names formed by repeatedly truncating the unit name after all dashes.
- https://docs.flatpak.org/en/latest/tips-and-tricks.html#configuring-resource-limits-for-apps

**Comment by smcv** [comment]
Using wildcards in that precise way isn't supported, you want `app-flatpak-.scope.d/something.conf` (no wildcard, just a trailing `-` before the `.`).

**Comment by nbraud** [comment]
Yes, I didn't mean a `*` in the directory name, just the "usual" systemd wildcard mechanism.

Anyhow, I retried again and this seems to work, so I guess I messed something up the first time around.  :sweat_smile: 
Sorry for the bother, and thanks for linking the relevant documentation & confirming the approach I was trying was the correct one.
