### ISSUE TITLE
Left 4 Dead 2 mods not working in Flatpak

### ISSUE THREAD

**Issue by Alex-Bujorianu** [flatpak/flatpak#5371]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.0

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.10

### What architecture are you using?

x86_64

### How to reproduce

Install Steam in Flatpak, install Left 4 Dead 2, and install any mod (Workshop or manual vpk). Although the mod is marked as enabled and no errors pop-up, the mod will not be visible in-game.

### Expected Behavior

Mods operate as they do in the non-flatpak version of Steam.

### Actual Behavior

The mod is not effective in-game, although it is marked as installed.

**Comment by smcv** [comment]
> If this is an issue with a particular app

This is pretty clearly an issue that is specific to https://github.com/flathub/com.valvesoftware.Steam.
