### ISSUE TITLE
Unclear Message issued during updates - "System variables not set"

### ISSUE THREAD

**Issue by careca1970** [flatpak/flatpak#5377]
Similar to issue [#533](https://github.com/flatpak/flatpak/issues/533#top), I confirm latest affirmation from @baskin77. 

I have Flatpak 1.14.4 on Fedora 37.

“False positive” message on "system variables not set" seems still to persist.

This is the message during flatpak packages update,
by issuing:

$ sudo flatpak -y update

```
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:
```

These are actual contents of system variables:

```
$ echo $XDG_DATA_HOME

```

```
$ echo $XDG_DATA_DIRS
/home/Alex/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```

Thou, flatpak's applications just seem to function fine!

Regards, Careca

_Originally posted by @careca1970 in https://github.com/flatpak/flatpak/issues/533#issuecomment-1493392288_

**Comment by Erick555** [comment]
You run the first command as `root` user through `sudo`. The rest commands are run as `Alex` user. You shouldn't run flatpak as root so instead `sudo flatpak -y update` just do `flatpak -y update`.

**Comment by careca1970** [comment]
Yeah, thanks for this explanation.
This makes everything clear.
I'm closing this issue.
