### ISSUE TITLE
[Bug]: flatpak not installing on my chromebook

### ISSUE THREAD

**Issue by Bravo1dan** [flatpak/flatpak#5385]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

The latest 

### What Linux distribution are you using?

ChromeOS

### What architecture are you using?

x86_64

### How to reproduce

I don’t know 

### Expected Behavior

I expected that when I put in the information to install the flatpak on my Chromebook Linux environment that it would work. But it did not work. The flatpak that I am trying to install is “flatpak/org.upscayl.app.json”

### Actual Behavior

It came up on the terminal that the flatpak could not be found 

### Additional Information

I don’t know if I’m doing the wrong or right thing or it can’t work at all.

**Comment by hard02** [comment]
@Bravo1dan,
Kindly follow the following steps mentioned here:
https://github.com/flatpak/flatpak/issues/5385

If you still find some problem in installing, feel free to ping me.
