### ISSUE TITLE
[Bug]: Steam Deck Hardware Decoding is broken for flatpak apps

### ISSUE THREAD

**Issue by ranger149** [flatpak/flatpak#5388]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

5.13.0-valve36-1-neptune (SteamOS)

### What architecture are you using?

x86_64

### How to reproduce

1. Update all apps on the KDE Discover store and Install an app which utilizes hardware decoding from the KDE discover store (such as Moonlight or Chiaki).
2.  Launch said app, and get a hardware decoding error, such as it not being detected or available.

### Expected Behavior

Expect the flatpak app to be able to utilize hardware decoding

### Actual Behavior

For example:

- Moonlight states: No functioning hardware accelerated video decoder was detected.

- Chiaki says failed to initialize FFMPEG decoder.

### Additional Information

This issue only occurs with flatpak apps. The Moonlight AppImage does not have this issue. This issue is wide spread for Steam Deck users:

See:

- https://github.com/streetpea/chiaki4deck/issues/63

- https://www.reddit.com/r/SteamDeck/comments/12pu215/problem_with_moonlight_and_sunshine_decoder/

- https://www.reddit.com/r/SteamDeck/comments/12qqwod/can_anybody_help_me_pls_i_can_not_remote_play/

- https://www.reddit.com/r/SteamDeck/comments/12qfq7j/steamos_346_chiaki_error/

**Comment by TingPing** [comment]
The runtime which provides Mesa is here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by ranger149** [comment]
Thank you
