### ISSUE TITLE
[Bug]: Unable to load db file .goutputstream-2OZ6Z1: invalid gvdb header when uninstalling applications

### ISSUE THREAD

**Issue by zastrixarundell** [flatpak/flatpak#5390]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

38

### What architecture are you using?

x86_64

### How to reproduce

`flatpak install us.zoom.Zoom -y && flatpak uninstall --delete-data us.zoom.Zoom -y`

### Expected Behavior

```
Looking for matches…

us.zoom.Zoom permissions:
    ipc      network      pulseaudio      wayland      x11      devices      file access [1]      dbus access [2]      bus ownership [3]     tags [4]

    [1] ~/.zoom:create, ~/Documents/Zoom:create
    [2] org.freedesktop.ScreenSaver
    [3] org.kde.*
    [4] proprietary


        ID                   Branch         Op        Remote         Download
 1. [✓] us.zoom.Zoom         stable         i         flathub        169.4 MB / 169.9 MB

Installation complete.


        ID                Branch      Op
 1. [-] us.zoom.Zoom      stable      r

Uninstall complete.
```

### Actual Behavior

```
Looking for matches…

us.zoom.Zoom permissions:
    ipc      network      pulseaudio      wayland      x11      devices      file access [1]      dbus access [2]      bus ownership [3]     tags [4]

    [1] ~/.zoom:create, ~/Documents/Zoom:create
    [2] org.freedesktop.ScreenSaver
    [3] org.kde.*
    [4] proprietary


        ID                   Branch         Op        Remote         Download
 1. [✓] us.zoom.Zoom         stable         i         flathub        169.4 MB / 169.9 MB

Installation complete.


        ID                Branch      Op
 1. [-] us.zoom.Zoom      stable      r

Uninstall complete.
error: Unable to load db file .goutputstream-2OZ6Z1: invalid gvdb header
```

### Additional Information

This happens on my desktop Fedora Kinoite (KDE version of silverblue). On my Fedora Kinoite laptop I don't have this issue so it might just be happening due to permission errors as I'm using a recreated user with the same UID and GID.

**Comment by zastrixarundell** [comment]
When deleting multiple flatpaks I get the error on every flatpak and the uninstallation stops. The data is deleted for one app at a time, so I have to repeat the command multiple times.

**Comment by zastrixarundell** [comment]
I switched to another user account and I don't have the issue there so it's only happening on my main user profile. I've got hundreds of gigabytes of data in flatpaks so switching everything to another really isn't ideal to fix this issue. (Mostly game installations).

**Comment by zastrixarundell** [comment]
Probably borked FS. Eventually I did a reinstall and issue doesn't exist.

**Comment by Wilker-uwu** [comment]
i've always had the same problem, and it's always when i try to use `--delete-data`.

v1.16.3 under Fedora 43.
