### ISSUE TITLE
[Bug]: Writing not consistent with file permissions

### ISSUE THREAD

**Issue by MikeNavy** [flatpak/flatpak#5391]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Linux Mint

### Linux distribution version

Linux Mint 20.3 Mate, based on Ubuntu focal

### What architecture are you using?

x86_64

### How to reproduce

Hi, 
I use Thunderbird 102.10.0 and Firefox 112.0.1 flatpaks, with their default file permissions.
Firefox: the only file permission is "xdg-download".
Thunderbird: file permissions are "~/.gnupg", "/run/.heim_org.h5l.kcm-socket", "xdg-run/gnupg:ro", "xdg-download".
(Permissions checked with Flatseal).
However, when using Firefox, I can save files (an image from a website, as an example) in any of my "/home" directories or subdirectories, or in "/tmp" directory.
When using Thunderbird, I can save an attachment in any of my "/home" directories or subdirectories, or in "/tmp" directory.
I use flatpak 1.14.1 from flatpak stable PPA.
Firefox permissions:
![Capture du 2023-04-20 15-21-56](https://user-images.githubusercontent.com/62835567/233383435-2151d16c-22ae-4336-ae65-f2dabf5dd83b.png)
Thunderbird permissions:
![Capture du 2023-04-20 15-21-32](https://user-images.githubusercontent.com/62835567/233383543-fff64577-ec07-47fe-b137-70884be5a2c6.png)

### Expected Behavior

According to [https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#filesystem-permissions](url), it should not be possible to save files in another place than my downloads directory (since I use a French version of Linux Mint, it is in fact "~/Téléchargements" one). Saving in another directory of my home should request "filesystem=home" permission, not allowed, and saving in "/tmp" directory should request "filesystem=host" one, not allowed.

Note that Flatseal does not seem to be involved, the result is the same with Flatseal installed or uninstalled.

### Actual Behavior

It is possible to write in any "/home" directory or subdirectory, while "filesystem=home" is not allowed; and in "/tmp" directory, while "filesystem=host" is not allowed.

### Additional Information

Note that in "printenv" output there is no xdg-download variable. Related?
Here is the content of my "/etc/xdg/user-dirs.defaults":

DESKTOP=Desktop
DOWNLOAD=Downloads
TEMPLATES=Templates
PUBLICSHARE=Public
DOCUMENTS=Documents
MUSIC=Music
PICTURES=Pictures
VIDEOS=Videos
(Then translated in user locale).

**Comment by MikeNavy** [comment]
It does not seem related to application, but rather to flatpak behavior. Same thing with Ungoogled-Chromium flatpak, I can save an image everywhere in my home.

**Comment by Mikenux** [comment]
This is because they are using the file chooser portal. Portals and folder permissions are complementary. I think the permission to access xdg-download is for Firefox automatic download to the Téléchargements folder.

**Comment by MikeNavy** [comment]
@Mikenux 
Ok, I understand. From Flatpak documentation on portals, [https://docs.flatpak.org/en/latest/sandbox-permissions.html](url):
"In many cases, portals use a system component to implicitly ask the user for permission before granting access to a particular resource. For example, in the case of opening a file, the user’s selection of a file using the file chooser dialog is interpreted as implicitly granting the application access to whatever file is chosen.

This approach enables applications to avoid having to configure blanket access to large amounts of data or services and gives users control over what their applications have access to."

Since file chooser portal is under the control of user, there is no risk.
So, "it is not a bug, it is a feature"!
I close the issue

**Comment by Mikenux** [comment]
If you want to know, there are some related issues which are about strictly respecting set permissions or clarifying this kind of detail in user interfaces: https://github.com/flatpak/xdg-desktop-portal/issues/995 and https://github.com/flatpak/flatpak/issues/3977.
