### ISSUE TITLE
[Bug]: Launch helper exited with unknown return code 1

### ISSUE THREAD

**Issue by Mi605** [flatpak/flatpak#5392]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

antiX 23 (Debian Bookworm based) 6.1.10-antix.1-amd64-smp #1 SMP PREEMPT_DYNAMIC Tue Feb  7 14:21:35 EET 2023 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Follow the steps to install flatpack found at https://flatpak.org/setup/Debian (_apt install flatpak_ installs perfectly fine, no errors, no missing dependencies)

2. When applying step 2 from the beforementioned flatpack instructions site you'll get an error message:
```
$ flatpak -vv remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
F: Opening system flatpak installation at path /var/lib/flatpak
F: Loading https://flathub.org/repo/flathub.flatpakrepo using curl
F: Received 4040 bytes
F: Calling system helper: ConfigureRemote
Fehler: Launch helper exited with unknown return code 1
```

### Expected Behavior

The flathub space should be added to proceed with installing flatpacked software.

### Actual Behavior

No installation of any flatpack packaged software is possible without completing the flatpack preparation steps from https://flatpak.org/setup/Debian

```
$ flatpak install flathub org.tabos.roger
Suchen nach Übereinstimmungen …
Fehler: No remote refs found for ‘flathub’
```

### Additional Information

Flatpack seems to be the single option provided to install the urgently needed software _roger-router_ on debian 12 bookworm and antiX 23, since the native .deb package of this software is only available for debian 11 bullseye (where it is working perfectly fine on antiX 21/22).

**Comment by smcv** [comment]
> `Launch helper exited with unknown return code 1`

This means that a D-Bus service (probably `flatpak-system-helper`) has failed to start, with exit status 1.

If antiX uses systemd, please check the system log (systemd journal) for log messages.

If antiX doesn't use systemd, there might be something useful in the syslog, but probably not much. Running `/usr/libexec/flatpak-system-helper` as root might provide more information.

**Comment by Mi605** [comment]
Many thanks for looking into this.

antiX doesn't support systemd, and as you've expected, no new information is present in system log provided by _dmesg_ after running the command
```
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```
There is no systemd journal on antiX.

Running the suggested command throws another unknown error:

```
$ sudo '/usr/libexec/flatpak-system-helper'
Can't get polkit authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: Launch helper exited with unknown return code 127
```

But antiX supports D-Bus (command copied from https://unix.stackexchange.com/questions/46301/a-list-of-available-d-bus-services , not sure what all this means. At least I can definitely tell D-Bus is returning something):
```
$ dbus-send --system --print-reply --dest=org.freedesktop.DBus  /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1682104262.569878 sender=org.freedesktop.DBus -> destination=:1.4803 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "org.freedesktop.login1"
      string ":1.4691"
      string ":1.395"
      string ":1.4625"
      string ":1.4"
      string "net.connman"
      string ":1.4626"
      string ":1.4803"
      string ":1.5"
      string "fi.w1.wpa_supplicant1"
      string ":1.412"
      string ":1.6"
      string ":1.4051"
   ]
```

**Comment by smcv** [comment]
> `Error calling StartServiceByName for org.freedesktop.PolicyKit1: Launch helper exited with unknown return code 127`

This might mean your D-Bus `.service` file for polkit (usually `/usr/{local/,}share/dbus-1/system-services/org.freedesktop.PolicyKit1.service`) lists an `Exec` command that doesn't exist, or it might mean the `dbus-daemon-launch-helper` used for D-Bus system service activation (on-demand service starting) is missing or broken. Neither of those is going to be fixed by making changes in Flatpak, so please contact whatever are the appropriate support channels for wherever you got dbus and polkit from (presumably antiX).

**Comment by Mi605** [comment]
Hi, many thanks for your reply.

Please see:

```
$ cat /usr/share/dbus-1/system-services/org.freedesktop.PolicyKit1.service
[D-BUS Service]
Name=org.freedesktop.PolicyKit1
Exec=/usr/lib/polkit-1/polkitd --no-debug
User=root
SystemdService=polkit.service
```

On-demand service for policykit is obviously `libpolkit-agent-1-0` , and it is installed and working fine for all other programs except for flatpack:

```
$ ls /usr/share/dbus-1/system-services
fi.w1.wpa_supplicant1.service  org.cmst.roothelper.service    org.freedesktop.login1.service         org.freedesktop.PolicyKit1.service
org.blueman.Mechanism.service  org.freedesktop.Avahi.service  org.freedesktop.ModemManager1.service

```
So neither polkid nor dbus is broken. Single conclusion is this must be somehow flatpack related.

Is there something specific about how flatpack tries to invoke the service? Please note antiX 23 doesn't support neiter sysvinit nor systemd or elogind. All services are managed by runit, Is flatpack limited to a specific init system (e.g. systemd, or sysvinit)?

**Comment by smcv** [comment]
> Is there something specific about how flatpack tries to invoke the service?

No, it's using `libpolkit-gobject-1.so.0` and `libpolkit-agent-1.so.0` in the usual way.

**Comment by smcv** [comment]
> Please note antiX 23 doesn't support neither sysvinit nor systemd or elogind

Flatpak doesn't require a specific init system, but polkitd does require some sort of login session tracking (normally systemd-logind or elogind) so that it can tell which users are or aren't currently logged in at the console.
