### ISSUE TITLE
Host PulseAudio daemon killed when using `--device=all --socket=pulseaudio`

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#540]
Some apps currently need `--device=all`, to handle devices outside the current small set of explicit `--device` values - for example, GNOME Games needs it for `/dev/input/`, Android's `adb` needs it for `/dev/bus/usb/`

When using `--device=all`, it seems a pulse daemon attempts to spawn inside the container, killing the host pulse daemon, even when `--socket=pulseaudio` is specified. There's no problem without `--device=all`, but obviously this means no access to the previously cited stuff

**Comment by alexlarsson** [comment]
What? There isn't even a pulseaudio daemon in the runtime, how can it spawn?

**Comment by alexlarsson** [comment]
I just ran:
```
flatpak run --socket=pulseaudio  --device=all --command=paplay --filesystem=host org.gnome.Sdk//3.22 /home/alex/cembalo-1.wav
```
and it worked fine.

**Comment by directhex** [comment]
I think the problem lies with some apps which iterate multiple sound output libraries, without defaulting to Pulse.

Let me get an example video going, with the Android emulator example.

**Comment by directhex** [comment]
Huh. So I recorded a video, but the recording stopped as soon as the Android emulator started & killed pulse, so.... smartphone recording time I guess.

**Comment by directhex** [comment]
https://www.youtube.com/watch?v=Pf7pie3HynY

I didn't claim it made sense!

**Comment by bochecha** [comment]
I've been seeing the same with org.gnome.Games for a while now, but never got around to figuring it out.

Just running org.gnome.Games and playing a game which will play sound is enough. After that I have the same symptoms as @directhex in his video:

* no application in the sound settings
* apps can't play music
* sound works fine in org.gnome.Games

Stopping org.gnome.Games does not bring things back to normal. At this point, killing pulseaudio is the only thing which works.

**Comment by directhex** [comment]
This is a PulseAudio/sandbox interaction bug - see https://bugs.freedesktop.org/show_bug.cgi?id=92141

Fixed in Pulse 9 via config, 10 by default. Which doesn't help existing users.

**Comment by hadess** [comment]
Could warrant a mention in a README somewhere, and a mail to distributor-list.

**Comment by directhex** [comment]
Inadvertently fixed by https://github.com/flatpak/freedesktop-sdk-images/commit/9c84d22e56332e84495b940a8cd578b63d4a06e1
