### ISSUE TITLE
[Bug]: ~/local/share/flatpak/repo contains files from packages that have been removed

### ISSUE THREAD

**Issue by wastemans** [flatpak/flatpak#5402]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Void Linux

### Linux distribution version

Linux hostname 6.1.25_1 #1 SMP PREEMPT_DYNAMIC Thu Apr 20 16:09:40 UTC 2023 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

Hard to describe, but if you install a package, and remove it, files from it are left behind afterwards.

Here's the output of:
`flatpak --user list`
```
Name                                                Application ID                                              Version                      Branch
ungoogled-chromium                                  com.github.Eloston.UngoogledChromium                        112.0.5615.165               stable
Codecs                                              com.github.Eloston.UngoogledChromium.Codecs                                              stable
Flatseal                                            com.github.tchx84.Flatseal                                  1.8.1                        stable
WPS Office                                          com.wps.Office                                              11.1.0.11691                 stable
LibreWolf                                           io.gitlab.librewolf-community                               112.0.1-2                    stable
Freedesktop Platform                                org.freedesktop.Platform                                    21.08.18                     21.08
Freedesktop Platform                                org.freedesktop.Platform                                    22.08.11                     22.08
Mesa                                                org.freedesktop.Platform.GL.default                         21.3.9                       21.08
Mesa                                                org.freedesktop.Platform.GL.default                         23.0.2                       22.08
Mesa (Extra)                                        org.freedesktop.Platform.GL.default                         23.0.2                       22.08-extra
nvidia-525-105-17                                   org.freedesktop.Platform.GL.nvidia-525-105-17                                            1.4
Intel                                               org.freedesktop.Platform.VAAPI.Intel                                                     21.08
Intel                                               org.freedesktop.Platform.VAAPI.Intel                                                     22.08
ffmpeg-full                                         org.freedesktop.Platform.ffmpeg-full                                                     22.08
openh264                                            org.freedesktop.Platform.openh264                           2.1.0                        2.0
openh264                                            org.freedesktop.Platform.openh264                           2.1.0                        2.2.0
openh264                                            org.freedesktop.Platform.openh264                           2.1.0                        2.3.0
Freedesktop SDK                                     org.freedesktop.Sdk                                         22.08.11                     22.08
GNU Image Manipulation Program                      org.gimp.GIMP                                               2.10.34                      stable
GNOME Application Platform version 43               org.gnome.Platform                                                                       43
Zenmap                                              org.nmap.Zenmap                                             7.93                         stable
Remmina                                             org.remmina.Remmina                                         1.4.30                       stable
```

Here's what I tried to systematically remove them:
`flatpak --user uninstall --delete-data --unused -y`
`flatpak --user repair`

Here's the sample package in question:
`com.sindresorhus.Caprine.desktop`

And here's a result of a search inside ~/.share:
```
./share/applications/com.sindresorhus.Caprine.desktop
./share/flatpak/repo/refs/remotes/flathub/app/com.sindresorhus.Caprine
./share/flatpak/repo/refs/remotes/flathub/app/com.sindresorhus.Caprine/x86_64
./share/flatpak/repo/refs/heads/deploy/app/com.sindresorhus.Caprine
./share/flatpak/repo/refs/heads/deploy/app/com.sindresorhus.Caprine/x86_64
./share/flatpak/appstream/flathub/x86_64/0924788554ce1f8d85a1b4aa88083723ea54e58c202b63a64a655847af45fc40/icons/64x64/com.sindresorhus.Caprine.png
./share/flatpak/appstream/flathub/x86_64/0924788554ce1f8d85a1b4aa88083723ea54e58c202b63a64a655847af45fc40/icons/128x128/com.sindresorhus.Caprine.png
./share/flatpak/appstream/flathub/x86_64/65830da0e20ca1736dc43e97f24cc1595e43352c3a8cb64857702db83812c1fc/icons/64x64/com.sindresorhus.Caprine.png
./share/flatpak/appstream/flathub/x86_64/65830da0e20ca1736dc43e97f24cc1595e43352c3a8cb64857702db83812c1fc/icons/128x128/com.sindresorhus.Caprine.png
```

### Expected Behavior

Leftover junk should be removed.

### Actual Behavior

Leftover junk is not removed.

**Comment by smcv** [comment]
> ./share/applications/com.sindresorhus.Caprine.desktop

Flatpak doesn't create this, only the version in `~/.local/share/flatpak/exports/share/applications` or `/var/lib/flatpak/exports/share/applications`.

If you use a menu editor to change a field in the .desktop file, for example to hide it from your desktop environment's menus, then your edited version gets copied to `~/.local/share/applications` by the menu editor, so that it will override the version written out by Flatpak. Flatpak doesn't know about that one (and deleting it could be considered to be loss of user data) so it won't delete it.

> ./share/flatpak/appstream/flathub/...

This part is working as designed. When you add Flathub as a remote, a cache of details of all of the applications available from Flathub (metadata and icons) appear in `~/.local/share/flatpak/appstream` or `/var/lib/flatpak/appstream`, whether you have them installed or not, so that UIs like GNOME Software and KDE Plasma Discover can show them as available for installation.

> ./share/flatpak/repo/refs/remotes/flathub/app/com.sindresorhus.Caprine
> ./share/flatpak/repo/refs/remotes/flathub/app/com.sindresorhus.Caprine/x86_64
> ./share/flatpak/repo/refs/heads/deploy/app/com.sindresorhus.Caprine
> ./share/flatpak/repo/refs/heads/deploy/app/com.sindresorhus.Caprine/x86_64

I'm not sure whether these are meant to stay around after the app is uninstalled or not, but they're extremely small (each one contains a sha256 and nothing else).

**Comment by wastemans** [comment]
OK, thanks for clearing that up.
