### ISSUE TITLE
[Bug]: Chinese fonts look terrible

### ISSUE THREAD

**Issue by rikonaka** [flatpak/flatpak#5425]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Pop!_OS

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

1. Install `joplin` or `telegram` via flathub.
2. Open it.
3. Install `joplin` or `telegram` via official tool.
4. Comparing them font size.

### Expected Behavior

The font size should be the same.

### Actual Behavior

This `joplin` is installed from flatpak.
![Screenshot from 2023-05-30 09-13-00-1](https://github.com/flatpak/flatpak/assets/13602602/474afae5-bf07-43df-a9d5-c94fdc085fe0)

This is from official tool.
![Screenshot from 2023-05-30 09-12-30-1](https://github.com/flatpak/flatpak/assets/13602602/fb359b06-1e77-47a9-8e70-84a624a81df6)

There is one large and one small font, same problem in `telegram`.

telegram from flatpak.
![Screenshot from 2023-05-30 09-32-30](https://github.com/flatpak/flatpak/assets/13602602/0b975532-e2a2-4783-841b-50905ea294ec)

telegram from official tool.
![Screenshot from 2023-05-30 09-32-55](https://github.com/flatpak/flatpak/assets/13602602/47081122-da22-4f8c-a5ec-3d78b82614bc)

### Additional Information

Previously flatpak had been working fine without the above problem, and it was only during a recent system update a week ago that the problem appeared.

**Comment by eiglow** [comment]
On Fedora 38 (KDE Spin), the fonts look fine for me, characters like 时 or 远 don't look weird for me like they do for you. I guess this issue depends on your distro.

**Comment by rikonaka** [comment]
> On Fedora 38 (KDE Spin), the fonts look fine for me, characters like 时 or 远 don't look weird for me like they do for you. I guess this issue depends on your distro.
> 
> Have you tried the suggestion in this comment? [#4571 (comment)](https://github.com/flatpak/flatpak/issues/4571#issuecomment-1606258732)

Thank you for responding, I've tried to uninstall some of the tools like this comment, but I can't.

```bash
➜  ~ sudo apt remove xfonts-base xfonts-100dpi xfonts-75dpi

[sudo] password for hero: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'xfonts-100dpi' is not installed, so not removed
Package 'xfonts-75dpi' is not installed, so not removed
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: xorg but it is not going to be installed
               Recommends: geary but it is not going to be installed
               Recommends: libreoffice-calc but it is not going to be installed
               Recommends: libreoffice-impress but it is not going to be installed
               Recommends: libreoffice-writer but it is not going to be installed
               Recommends: libreoffice-gnome but it is not going to be installed
               Recommends: libreoffice-ogltrans
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by random-integer** [comment]
@rikonaka You should try the method outlined in this comment: https://github.com/flatpak/flatpak/issues/4571#issuecomment-977935945. I have also been deeply, deeply troubled by the same issue for months now. Then I stumbled upon this comment with the workaround for the issue.

(你應該試試 https://github.com/flatpak/flatpak/issues/4571#issuecomment-977935945 說的暫時解法。我也被這個問題搞得很煩，也是好幾個月了。幸好，我發現了那個留言的解法，如下：)

1. `cd ~/.var/app/org.telegram.desktop/config` (you can replace `org.telegram.desktop` with the name of another Flatpak app, e.g. `net.cozic.joplin_desktop` for Joplin) (可以把 `org.telegram.desktop` 置換成其他 app 的目錄名稱，比如 `net.cozic.joplin_desktop`)
2. `mkdir -p fontconfig/conf.d`
3. `cd fontconfig/conf.d`
4. `cp /etc/fonts/conf.d/*.conf ./`
5. Restart Telegram (or another app). (重新啟動 Telegram。)

Below are two screenshots from a Flatpak app ([Tuba](https://flathub.org/apps/dev.geopjr.Tuba)) to demonstrate this:

(以下是兩張來自某個 Flatpak app ([Tuba](https://flathub.org/apps/dev.geopjr.Tuba)) 的截圖：）

Before:

![image](https://github.com/flatpak/flatpak/assets/44129226/4032366c-aa00-4bbc-9944-7105ba1df4d5)

After:

![image](https://github.com/flatpak/flatpak/assets/44129226/6245ded2-eab7-4aae-855b-2f04c70123fa)

**Comment by rikonaka** [comment]
> @rikonaka You should try the method outlined in this comment: [#4571 (comment)](https://github.com/flatpak/flatpak/issues/4571#issuecomment-977935945). I have also been deeply, deeply troubled by the same issue for months now. Then I stumbled upon this comment with the workaround for the issue.
> 
> (你應該試試 [#4571 (comment)](https://github.com/flatpak/flatpak/issues/4571#issuecomment-977935945) 說的暫時解法。我也被這個問題搞得很煩，也是好幾個月了。幸好，我發現了那個留言的解法，如下：)
> 
>     1. `cd ~/.var/app/org.telegram.desktop/config` (you can replace `org.telegram.desktop` with the name of another Flatpak app, e.g. `net.cozic.joplin_desktop` for Joplin) (可以把 `org.telegram.desktop` 置換成其他 app 的目錄名稱，比如 `net.cozic.joplin_desktop`)
> 
>     2. `mkdir -p fontconfig/conf.d`
> 
>     3. `cd fontconfig/conf.d`
> 
>     4. `cp /etc/fonts/conf.d/*.conf ./`
> 
>     5. Restart Telegram (or another app). (重新啟動 Telegram。)
> 
> 
> Below are two screenshots from a Flatpak app ([Tuba](https://flathub.org/apps/dev.geopjr.Tuba)) to demonstrate this:
> 
> (以下是兩張來自某個 Flatpak app ([Tuba](https://flathub.org/apps/dev.geopjr.Tuba)) 的截圖：）
> 
> Before:
> 
> ![image](https://user-images.githubusercontent.com/44129226/272925374-4032366c-aa00-4bbc-9944-7105ba1df4d5.png)
> 
> After:
> 
> ![image](https://user-images.githubusercontent.com/44129226/272925609-6245ded2-eab7-4aae-855b-2f04c70123fa.png)

非常感謝您的回復！這個方法解決了我的問題！

**Comment by random-integer** [comment]
> 非常感謝您的回復！這個方法解決了我的問題！

很高興能幫上忙！

**Comment by zlylong** [comment]
> (你應該試試 [#4571 (comment)](https://github.com/flatpak/flatpak/issues/4571#issuecomment-977935945) 說的暫時解法。我也被這個問題搞得很煩，也是好幾個月了。幸好，我發現了那個留言的解法，如下：)
你应该试试这个办法：
https://blog.geekgo.tech/linux/flatpak-%E5%BA%94%E7%94%A8%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E9%97%AE%E9%A2%98/

**Comment by random-integer** [comment]
> 你应该试试这个办法：
>
> https://blog.geekgo.tech/linux/flatpak-%E5%BA%94%E7%94%A8%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E9%97%AE%E9%A2%98/

這太棒了，不用對每個應用程式重覆！謝謝

@rikonaka
