### ISSUE TITLE
support %f and %F in desktop files

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#543]
this is useful for letting sandboxed apps act as mime handlers. In my case, GNOME recipes supports exporting recipes in a file format, and sending the resulting file by mail. I am making recipes install a mimetype for this file, and recipes supports opening such files when passed as arguments on the commandline.

I would like to add the mimetype to the desktop file, and add a %f to the Exec line. But currently, flatpak does not do anything special with these placeholders when it rewrites the Exec line. As a result, passing a file that is, say, in the users home directory: /home/mclasen/cookies.gnome-recipes-export will not work, since that file is not visible in the sandbox.

What needs to happen here is that the file needs to be exported in the document portal, and the resulting document portal path needs to be substituted for %f instead of the origin path.

This should be done by the flatpak binary. In order to deal with escaping and possible clashes, Alex suggested something like

flatpak --enable-file-escaping --command="recipes @@%f@@" run org.gnome.Recipes

as the replacement Exec line. The @@ act as markers, so flatpak can fine out where the file names to be exported are in the commandline, and --enable-file-escaping is specified to trigger the special handling of these file names.

**Comment by TingPing** [comment]
Something like this needs to happen for `%U` also when the URI is a `file://` also?
