### ISSUE TITLE
Some flatpaks ignore nofilesystem overrides

### ISSUE THREAD

**Issue by bananaliker** [flatpak/flatpak#5431]
Distro: Debian Bookworm
Flatpak version: 1.14.4-1

This is an issue I have noticed with several other flatpaks, but I will use org.nicotine_plus.Nicotine as an example.

The above flatpak comes with access to host filesystem by default. Opening a file dialog from within the program (ie selecting download folder) confirms this. 

However, following an override with --nofilesystem=host, although host is no longer listed under filesystems in --show-permissions, opening the same file dialog as previously mentioned still shows the flatpak has full access to the home directory.

Is this a bug, or some quirk related to the GTK file picker within flatpak that I'm not aware of?

**Comment by smcv** [comment]
There are two things that might be happening here:

1. If the application is (correctly) using the file chooser portal (part of xdg-desktop-portal) to select files to open or save, then the actual file chooser (the "open" or "save as..." dialog) runs outside the actual application and outside the sandbox, so seeing a file in the file chooser does not imply that the app can access it. When you confirm a selection, the app is given access to the relevant file (but not other files in general) via a FUSE filesystem (xdg-document-portal).

2. If the application has both `--filesystem=host` and a "narrower" permission like `--filesystem=home`, then `--nofilesystem=host` will disable the wider permission, but keep the narrower permission. You can use `flatpak info -M org.nicotine_plus.Nicotine` to see what permissions the app has.

(Or it might be both.)

I see Nicotine is some sort of peer-to-peer file-sharing. A common reason for apps to want direct filesystem access via `--filesystem` is that they want to access all files in a directory (in this case perhaps a "downloads" or "published" directory?), and not just the one specific file that you chose. The file chooser portal cannot currently do that, and getting a design for that feature that is not misleading to users is proving to be difficult.

**Comment by bananaliker** [comment]
I see, thank you very much for explaining! It sounds like the former, as I already checked that --show-permissions showed that no filesystems were available (I was planning to just put what I wanted to use with the program under its folder in .var). I was just surprised that the file choose showed everything regardless, but if I know the program itself can't access those files, then that's a relief.
