### ISSUE TITLE
[Bug]: opening repo: opendir(/var/lib/flatpak/repo): Permission denied

### ISSUE THREAD

**Issue by Meow-purr** [flatpak/flatpak#5432]
### Checklist

- [ X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [ X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [ X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [ X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

23.04

### What architecture are you using?

x86_64

### How to reproduce

try to install

### Expected Behavior

it would install

### Actual Behavior

it says 
`error: While opening repository /var/lib/flatpak/repo: opening repo: opendir(/var/lib/flatpak/repo): Permission denied`

### Additional Information

i tryed chmoding (777) but same happend

**Comment by smcv** [comment]
> 1.144

There is no such version. Probably you mean 1.14.4.

> 22.03

There is no such version of Ubuntu. Probably you mean 22.04.

> try to install

You'll need to be more specific: if you want a bug to be solvable, then details matter.

**Comment by Meow-purr** [comment]
fixed it

**Comment by Meow-purr** [comment]
i fixed via
`sudo chmod 777 /var/lib/flatpak`

**Comment by Meow-purr** [comment]
you shoukd add a better error message

**Comment by smcv** [comment]
> i fixed via `sudo chmod 777 /var/lib/flatpak`

That is not a correct solution, and if you have more than one local user, you have probably made yourself vulnerable to attacks by one user on other users.

> you shoukd add a better error message

You haven't explained how the problem can be reproduced! We can't add a better error message for a specific situation if we don't know what your situation is or how you got there.
