### ISSUE TITLE
[Bug]: flatpak repository not updating

### ISSUE THREAD

**Issue by BTW-l-Use-Arch** [flatpak/flatpak#5436]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.8

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Linux parrot 6.1.0-1parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Parrot 6.1.15-1parrot1 (2023-04-25) x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

I've have the same issue as in post https://github.com/flatpak/flatpak/issues/5434
but when i looked at the comments i was told to update my flatpak repository when i did, this error occurred 

### Expected Behavior

For the flatpak repository to update and the https://github.com/flatpak/flatpak/issues/5434
issue to fix

### Actual Behavior

![Screenshot_20230612_100259](https://github.com/flatpak/flatpak/assets/84948029/049f3c75-74d7-4baf-8799-efdd88023744)

### Additional Information

I searched up this issue [found](https://stackoverflow.com/questions/56218562/how-to-fix-modulenotfounderror-no-module-named-apt-pkg) but when i tried the solutions suggested in this, this happened:

![Screenshot_20230612_165540](https://github.com/flatpak/flatpak/assets/84948029/c4b16433-0775-4a10-9738-10e112469c9b)

so i guess that doesn't work

**Comment by smcv** [comment]
(Where possible please copy text as text, not screenshots: that makes it searchable, as well as being more accessible for users of screen readers and other accessibility tools.)

This is the same issue as #5434. It is really a bug in appstream-glib, not a bug in Flatpak.

Please ask your distribution vendor (which in your case seems to be something called "Parrot"?) to either upgrade appstream-glib to 0.8.1 or later, or backport the targeted fixes from https://github.com/hughsie/appstream-glib/pull/403 and https://github.com/hughsie/appstream-glib/pull/446.

Here are some examples of other distributions backporting those fixes, which your distribution vendor might find useful as a reference: [Ubuntu](https://bugs.launchpad.net/ubuntu/+source/appstream-glib/+bug/2023215), [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037214).

**Comment by smcv** [comment]
> `sudo apt-add-repository ppa:flatpak/stable`

The Flatpak PPA is intended for Ubuntu. You seem to be running something called Parrot, which is not Ubuntu.

If you are trying to work around #5434 by upgrading to Flatpak 1.14.x, please talk to your distribution vendor's support channels about how to achieve that in a supportable way. This is a question for your distribution vendor, not for Flatpak upstream.

Parrot seems to be derived from Debian, so one way to do that might be to use the version of Flatpak from Debian's `bullseye-backports` - but I am not a user or developer of Parrot, so I don't know whether using `bullseye-backports` is something that is intended to be supported in Parrot.
