### ISSUE TITLE
[Feature request]: Asks frameworks vendor to create long-maintained branches

### ISSUE THREAD

**Issue by nintyfan** [flatpak/flatpak#5438]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Force FreeSoftware Fundation, KDE and GNOME folks to provide long-supported branches.
Why? For some software, keep going for newest libraries are not good. Windows do not change often and developers still rely on WinAPI (Win32, but maybe in 64-bit). Dropping support for some frameworks to quick creating problems, because developers cannot be as fast as they need to made they software rely on supported frameworks. It creates high-disk-usage-problems. If programmers seen some frameworks version will be supported for 3-5 years, it will compile for it and place identification of this versions in manifests.

https://akselmo.dev/posts/my-thoughts-on-flatpak-that-nobody-asked-for/

**Comment by Mikenux** [comment]
Forcing people from these organizations is certainly not possible.

They don't necessarily have the resources to develop the software and maintain runtimes and applications long term. Also, 3-5 years is a long time and some developers may prefer new versions to use new features (if there are any). Also, I don't think there will be developers who want to go ahead with new features and have recent versions of their app compiled with old runtimes (too much to maintain)... An example , apart from the runtimes, is that the Evince developers have raised the minimum required version of the poppler library to avoid opening bugs solved by new versions of the library (at least in part) and to develop workarounds for old versions, thus making it easier to maintain Evince.

That said, any distributor can have their own runtimes with their own repository (this is the case with Fedora) and their own patches to compile new versions of applications with old runtimes, but that's up to them and you probably won't have the app you want to be maintained as it depends on the packagers.

**Comment by smcv** [comment]
Flatpak cannot force unrelated projects to do work that they don't want to do. I don't know what power you imagine we have, but we don't have it.

If you want to employ enough developers to maintain a runtime with a 3-5 year support lifetime, or look for enough volunteers to do that, then you're very welcome to do so (but be aware that it will be a lot of work, and doing a good job will probably require paying the salaries of multiple full-time maintainers). Runtimes based on Debian LTS or the CentOS/Rocky family of distributions would probably be the best candidates for a basis for a long-term-supported runtime.

However, that is outside the scope of this bug tracker, which tracks bugs and feature requests in the `flatpak` piece of software.

**Comment by nintyfan** [comment]
Thanks. Yes - maybe releasing Debain (KDE/GNOME or KDE+GNOME?) runtime as Redhat releases own runtime is best choice.
