### ISSUE TITLE
flatpak make-current won't update application menu completely

### ISSUE THREAD

**Issue by xhorak** [flatpak/flatpak#544]
When changing current branch by using for example:
`sudo flatpak make-current org.mozilla.Firefox wayland `
only the icon is updated in Gnome Shell application list, not the application title and previous branch is executed when launched from application list (commandline works fine). 
This remains until session restart.
On `flatpak-0.8.2-1.fc25.x86_64`

**Comment by alexlarsson** [comment]
Does the actual file change in /var/lib/flatpak/exports/share/applications/ ?
Maybe the problem is that the shell does not detect that change?

**Comment by fmuellner** [comment]
This could indeed be https://bugzilla.gnome.org/show_bug.cgi?id=773636.

**Comment by matthiasclasen** [comment]
Lets assume this was fixed, then
