### ISSUE TITLE
Component not found despite its existence is attested

### ISSUE THREAD

**Issue by Ricky-Tigg** [flatpak/flatpak#5440]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

38

### What architecture are you using?

x86_64

### How to reproduce

```
$ flatpak install -vy io.bernard.Funkcio
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/yk/.local/share/flatpak
Looking for matches…
F: Calling system helper: GenerateOciSummary
F: Calling system helper: GenerateOciSummary
F: Fetching summary index file for remote ‘flathub’
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 10001 bytes
F: Loaded indexed summary file 90d0debd124741bd9f89305a636c2531a02f529ecd26d906ab8d35592e1ad734 from cache for remote ‘flathub’
error: No remote refs found for ‘io.bernard.Funkcio’
```

### Expected Behavior

The existence of _io.bernard.Funkcio_ is attested; shouldn't it then be found?

### Actual Behavior

Obviously the queried component was not found.

### Additional Information

```
$ flatpak remotes --columns=name,url,options
Name           URL                                            Options
fedora         oci+https://registry.fedoraproject.org         system,oci
fedora-testing oci+https://registry.fedoraproject.org#testing system,oci
flathub        https://dl.flathub.org/repo/                   system,filtered
$ flatpak search funkcio
Name       Description                   Application ID       Version   Branch   Remotes
Funkcio    Draw functions from points    im.bernard.Funkcio   0.3       stable   flathub
```

**Comment by smcv** [comment]
> `io.bernard.Funkcio`

> `im.bernard.Funkcio`

Those are not the same app-ID.

**Comment by smcv** [comment]
If you don't want to copy/paste app IDs, `flatpak install Funkcio` will look for refs with names containing that substring. Or you can use a GUI such as GNOME Software or KDE's Plasma Discover.
