### ISSUE TITLE
Filesystem permissions inside a flatpak

### ISSUE THREAD

**Issue by Nostritius** [flatpak/flatpak#545]
I'm trying to move some wine games to flatpak containers including the wine prefixes. I am using wine 2.0. The Problem is now, that wine needs write permissions to the wineprefix directory, because one specific game (Jade Empire) is creating save games inside its root directory. Is this possible and if so how would i do this? I have tried using --filesystem=/app.

**Comment by alexlarsson** [comment]
It is not possible for the app to write to /app or /usr, these are read-only mounts. The only place you can be sure to write is in the per-app directory in your homedir (~/.var/app/$appid). Various subdirectories of this directory are available at fixed paths in the sandbox though, such as /var/data. If you know where the app will be writing, you could replace that directory with a symlink to /var/data maybe?

**Comment by Nostritius** [comment]
Ok, i tried to symlink to /var/data and after some testing it worked. but there is another problem. I can now create save games, but the game also creates a configuration file (with settings like the resolution), which lies in the root directory of the game. Is there a possible solution for this? Also, could there be an empty folder which is exactly for custom data? I recognized that the /var/data directory is not empty.

**Comment by matthiasclasen** [comment]
I think the best way forward is a patch to make the app in question use the xdg directories, then everything will work just right automatically, inside and outside the sandbox.

**Comment by alexlarsson** [comment]
If you need an empty directory you can create it in your app. For instance by running the app via a shellscript wrapper that creates the directory.

Fixing the app writing to its root directory is harder though... Flatpak apps are fundamentally read-only.

**Comment by Nostritius** [comment]
Sorry, but this app is proprietary (which is one of the reasons why i want to sandbox it). Also it is very unlikely that the manufacturer (bioware in this case) would add a patch (the game was released 2007). Furthemore I have some other games which share the same problem (for example skyrim).
Concernig the empty directory, it is actually a good idea to create it via a script. I will try this.

**Comment by Nostritius** [comment]
I have found a solution for the file problem. You can create a symlink to a file in the /var/data directory and create it over a touch command. If this is done, the Application can write to this specific file. This solved my problem this task can be closed

**Comment by Croydon** [comment]
@Nostritius Just close the issue by yourself or you cause people like me to come here for no reason :P

**Comment by Limero** [comment]
@Nostritius Is it possible for you to share your manifest? It would be really useful as a template for other applications.

**Comment by Nostritius** [comment]
@Limero To be honest, I was not using any manifest files, because for some games i needed to do special stuff which was not or complex to do with manifest files. My main tool was the "flatpak build" command. If you want, i can see if i can provide some scripts for some of my games. Is there any information you would be specifically interested?

**Comment by Limero** [comment]
@Nostritius I think that what you are referring to as "scripts" are actually manifests. The .json files, those used with "flatpak build", with instructions on how to build Wine.

**Comment by Limero** [comment]
For anyone interested in putting Wine i Flatpaks, people have started bundling Windows executables with [this script](https://pastebin.com/kGRTe8YL).
