### ISSUE TITLE
[Feature request]: Add "--latest" flag to install the latest version of a package

### ISSUE THREAD

**Issue by krath1bb** [flatpak/flatpak#5450]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

It would be great to have the ability to have a "--latest" flag for "flatpak install". 

This would allow for scripting noninteractive installations without requiring user intervention to select package versions during install.

**Comment by hfiguiere** [comment]
as answered.
