### ISSUE TITLE
[Feature request]: Structured patches

### ISSUE THREAD

**Issue by faan11** [flatpak/flatpak#5451]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Hi

I've read this issue [https://github.com/NixOS/nixpkgs/issues/39392](39392) on NixOS/nixpkgs repo and i thought that the same idea can be applied in Flatpak. In Flatpak manifest, patches are not described by any metadata [1]. 

This issue proposes the introduction of "metadata" field in the patch objects.
The metadata field semantically describes the patch.
Useful sub properties have been suggested in this post [2]:
- type or function (cvePatch,tmpPatch,permanentPatch,specPatch)
- description, cve (only for cvePatch), from-thread (only for cvePatch), sha (this can be added outside the metadata field)

These fields, if applied to properly, can:
- identify security updates in the client side. Flatpak cli would identify these patches and apply them automatically.
- identify whether a package is affected or not by a vulnerability.   

[1] https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#idm46203909168976
[2] https://github.com/NixOS/nixpkgs/issues/39392#issuecomment-394151197

**Comment by hfiguiere** [comment]
This is completely out of the scope of flatpak.
