### ISSUE TITLE
flatpak-builder: document that cmake requires -DCMAKE_INSTALL_PREFIX=/app

### ISSUE THREAD

**Issue by grzegorzmazur** [flatpak/flatpak#546]
From my admittedly limited experiments it seems that using flatpak-builder to build an application with cmake requires setting -DCMAKE_INSTALL_PREFIX=/app. Otherwise either the make install step fails because of insufficient access rights or the just-built binary is not found. Unfortunately, no such advice can be found in the documentation.

**Comment by TingPing** [comment]
It shouldn't be required: https://github.com/flatpak/flatpak/blob/master/builder/builder-module.c#L1482-L1483

**Comment by grzegorzmazur** [comment]
Thanks for pointing this out, but I'm not completely sure it actually works. The line
```
configure_prefix_arg = g_strdup_printf ("-DCMAKE_INSTALL_PREFIX:PATH='%s'",
                                         builder_options_get_prefix (self->build_options, context));
```
should set prefix to ```/app``` by default and manually adding ```"-DCMAKE_INSTALL_PREFIX=/app"``` shouldn't have any effect. But it apparently has. The manifest 
```
{
    "app-id": "net.sf.yacas",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.22",
    "sdk": "org.gnome.Sdk",
    "command": "yacas",
    "finish-args": [
        "--socket=x11",
        "--share=network",
        "--filesystem=home"
    ],
    "modules": [
        {
            "name": "yacas",
            "sources": [
                {
                    "type": "archive",
                    "url": "https://github.com/grzegorzmazur/yacas/archive/v1.6.1.tar.gz",
                    "sha256": "6b94394f705bed70a9d104967073efd6c23e9eb1a832805c4d805ef875555ae5"
                }
            ],
            "buildsystem": "cmake",
            "config-opts": [
                "-DCMAKE_BUILD_TYPE=Release",
                "-DENABLE_CYACAS_GUI=Off",
                "-DENABLE_CYACAS_KERNEL=Off",
                "-DENABLE_JYACAS=Off"
            ],
            "cleanup": [
                "/include",
                "/lib"
            ]
        }
    ]
}
```
fails with
```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/share/yacas/scripts
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot make directory "/usr/local/share/yacas/scripts": No
  such file or directory
```
and can be fixed by explicitly setting the installation prefix 

OK, I admit that this is my first attempt at using flatpak, so perhaps I'm doing something completely wrong, but I can't see what would it be.

**Comment by alexlarsson** [comment]
That is very strange. It definitely works for a lot of other cmake builds without manually specifying it.
If you pass -v to flatpak-builder it should print the commandlines it runs, you can see what gets passed to cmake that way.

**Comment by alexlarsson** [comment]
Ah, this was a case where it worked with `cmake: true`, but not "buildsystem: cmake`. Fixing.
