### ISSUE TITLE
Read source code files of module at runtime

### ISSUE THREAD

**Issue by aadcg** [flatpak/flatpak#5469]
Is there an idiomatic way to achieve it? When issuing `flatpak-builder` I see that the source is read at `/run/build/module-name`, but at runtime that seems to be gone. 

What's the default cleanup stage for a module? Is it possible to disable cleanup completely?

I couldn't figure it out from the documentation. Thanks.

**Comment by orowith2os** [comment]
Check the `.flatpak-builder` directory; it probably has some of what you're looking for.

You can disable cleanup by removing the options for it from your manifest.

**Comment by orowith2os** [comment]
You can read the locally installed flatpak manifest (manifest.json) inside of the local binaries and check the links contained there. But other than that, and maybe the .Debug extension, you're out of luck.

The build caches contain the source code files used to build it. Unless it's explicitly shipped, packages don't usually contain it.

**Comment by smcv** [comment]
> I need to access the source code of the app I'm packaging when it's running

How would you do this for a traditional packaging format like dpkg or RPM? The solution is very likely to be the same for Flatpak.

How this would typically be done for dpkg or RPM is: identify the subset of your source code that is needed at runtime (perhaps that's all of it, or not), install it somewhere below `/usr/share/myapp`, and load it from there. For a Flatpak app, you'd typically do the same, except the installation directory would be more like `/app/share/myapp`.
