### ISSUE TITLE
[Bug]: fails to compile: ‘AS_FORMAT_STYLE_COLLECTION’ undeclared

### ISSUE THREAD

**Issue by Justinzobel** [flatpak/flatpak#5472]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

git master

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

39

### What architecture are you using?

x86_64

### How to reproduce

Attempt to compile flatpak.

```
main❯ ninja
[91/281] Compiling C object app/liblibflatpak-app.a.p/flatpak-builtins-utils.c.o
FAILED: app/liblibflatpak-app.a.p/flatpak-builtins-utils.c.o 
ccache cc -Iapp/liblibflatpak-app.a.p -Iapp -I../app -I. -I.. -Icommon -I../common -Isubprojects/libglnx -I../subprojects/libglnx -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/appstream -I/usr/include/json-glib-1.0 -I/usr/include/ostree-1 -I/usr/include/polkit-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O0 -g -include config.h -Werror=shadow -Werror=empty-body -Werror=strict-prototypes -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=pointer-arith -Werror=init-self -Werror=missing-declarations -Werror=return-type -Werror=overflow -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=misleading-indentation -Werror=missing-include-dirs -Wno-sign-compare -Wno-error=sign-compare -Wno-cast-function-type -Wno-error=cast-function-type -Wno-missing-field-initializers -Wno-error=missing-field-initializers -Wno-unused-parameter -Wno-error=unused-parameter -fvisibility=hidden -fPIC -pthread -MD -MQ app/liblibflatpak-app.a.p/flatpak-builtins-utils.c.o -MF app/liblibflatpak-app.a.p/flatpak-builtins-utils.c.o.d -o app/liblibflatpak-app.a.p/flatpak-builtins-utils.c.o -c ../app/flatpak-builtins-utils.c
../app/flatpak-builtins-utils.c: In function ‘flatpak_dir_load_appstream_store’:
../app/flatpak-builtins-utils.c:1133:40: error: ‘AS_FORMAT_STYLE_COLLECTION’ undeclared (first use in this function); did you mean ‘AS_FORMAT_STYLE_LAST’?
 1133 |   as_metadata_set_format_style (mdata, AS_FORMAT_STYLE_COLLECTION);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        AS_FORMAT_STYLE_LAST
../app/flatpak-builtins-utils.c:1133:40: note: each undeclared identifier is reported only once for each function it appears in
[104/281] Compiling C object common/libflatpak-common.a.p/flatpak-dir.c.o
ninja: build stopped: subcommand failed.
```

### Expected Behavior

Compile

### Actual Behavior

Error

**Comment by smcv** [comment]
What version of libappstream are you using? Presumably also git main, since 0.16.2 still has `AS_FORMAT_STYLE_COLLECTION`, and Fedora seems to be still on 0.16.1?

#5473 should fix this, please test.

> git master

This can't be true, we don't have a master branch any more.

**Comment by Justinzobel** [comment]
Heh yeah, that's my brain just saying git default branch. I should just say that in future but muscle memory is hard to undo.

**Comment by Justinzobel** [comment]
This fixes the build issue, thanks!
