### ISSUE TITLE
[Bug]: Flatpak hangs on trying to install or update any packages

### ISSUE THREAD

**Issue by postcanonical** [flatpak/flatpak#5477]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4-1

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

6.1.38-1-lts

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak update` or `flatpak install flathub <app name>`

### Expected Behavior

Apps are updated/ installed

### Actual Behavior

Shows `Looking for updates…` when updating or `Which do you want to use (0 to abort)? [0-2]: 2` (2 is user input) forever

### Additional Information

Also gnome-software doesn't load any apps. Maybe some problem with connection to flathub?

**Comment by spburtsev** [comment]
I have the same issue on Fedora 38 Workstation Edition, x86_64, flatpak version 1.15.4

**Comment by spburtsev** [comment]
@FattyNess Looks like it may be a flathub issue. Did you try removing flathub from repos and check if update/install commands work?

**Comment by fluentmoheshwar** [comment]
`flatpak repair` fixed for me

**Comment by mranv** [comment]
A SYSINIT is needed after the installation from iso file!
`
flatpak repair`

will repair it!

**Comment by postcanonical** [comment]
It is fixed for me with `flatpak repair`, sorry for the late update.

**Comment by Abdull** [comment]
`flatpak update` hang after providing the stdout output `Updating 1 of x`.

I had to restart the `flatpak-system-helper.service`:
 
```
systemctl restart flatpak-system-helper.service
```

Afterwards, `flatpak update` ran successfully.

**Comment by agelvez** [comment]
> `flatpak update` hang after providing the stdout output `Updating 1 of x`.
> 
> I had to restart the `flatpak-system-helper.service`:
> 
> ```
> systemctl restart flatpak-system-helper.service
> ```
> 
> Afterwards, `flatpak update` ran successfully.

worked, thanks!

**Comment by babzai** [comment]
I've tried both  flatpak repair and systemctl restart flatpak-system-helper.service and neither have helped me.
