### ISSUE TITLE
no network access from the build process

### ISSUE THREAD

**Issue by grzegorzmazur** [flatpak/flatpak#548]
The build process seems to be containerized in such a way that network access is blocked. Unfortunatelly, this breaks builds using eg cmake's [ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html). Could this restriction be somehow lifted?

**Comment by LiliC** [comment]
Have you tried using `"--share=network"` in your `"build-args"` of the specific module?

**Comment by grzegorzmazur** [comment]
Thanks for the hint, but it doesn't seem to work.

**Comment by LiliC** [comment]
How did you specify it?
```
"build-options": {
      "build-args": [
             "--share=network" 
```

**Comment by alexlarsson** [comment]
Yeah, the above should work.

**Comment by grzegorzmazur** [comment]
Ups, sorry. I've missed the build-options part. Now it works as expected. Sorry for the noise and thanks a lot for your help.
