### ISSUE TITLE
[Feature request]: Ask user where to install applications

### ISSUE THREAD

**Issue by RafaelLinux** [flatpak/flatpak#5480]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

First, I have to say that I was not a fan of Flatpak applications per se, I won't go into the technical details here, but I prefer to control where applications are installed. However, a recent discovery has further confirmed my prejudice against Flatpak.

In my user partition ($HOME), I only store DATA to keep track of the available space on the partition and to be able to make backups without surprises. Apps in AppImage format, I store in another partition. 

The (unpleasant) surprise came when I suddenly noticed that my data partition was running out of space. After a scan, I found that 21GB of my user partition had been taken by Flatpak (.local/share/Flatpak) because it seems to install applications at user or system level (without asking the user).

After a bit of a walk around, I discovered that with the command `flatpak remote-delete flathub` I can delete all Flatpak applications, and that's what I'm going to do.

However, before I avoid installing Flatpak applications at all, I would like to ask here that, if there is a way to force ALL Flatpak applications to ALWAYS be installed in system folders (or in a user-specified folder), please tell me about it, and if there isn't, please implement it. 

Thanks

**Comment by orowith2os** [comment]
Flatpak will, by default, ask you where to install an app. Your issue is likely with the frontend, like GNOME Software, not flatpak itself.

**Comment by smcv** [comment]
> Flatpak will, by default, ask you where to install an app

That's not quite it:

When you add a remote (a source of Flatpak apps and runtimes, like Flathub), you add it to either the system-wide installation directory (/var/lib/flatpak, which is the default), or the per-user installation directory (~/.local/share/flatpak), or an additional custom system-wide installation directory (flatpak-installation(5)). You cannot add a remote without choosing which installation it is added to, either explicitly with an option, or implicitly by using the default (which is /var/lib/flatpak).

When you install an app (or a runtime), it's installed into whichever installation directory the remote was added to.

If the same app (or runtime) is available from more than one remote, *then* the flatpak(1) CLI will ask you which one you want.

The consequence is: if you want all of your apps and runtimes to be in a particular installation, you should add remotes to that installation, and only that installation.

**Comment by RafaelLinux** [comment]
First of all, thank you for your answers. 

Maybe installation process is distinct between desktops. I use "Discover" (KDE Plasma application to install easily applications) that includes from one or two years ago Flatpak applications. When I install a NON Flatpak application, nothing special is asked. As any application that need to be installed, it ask me about root password, but no questions at all about folders. So I always guessed that Flatpak applications will be installed system wide, but not. 

Example: I just installed "Bottles" (cause unfortunately AppImage was not fine and now they don't compile it) from Discover. When I look for files instaled, all are in ".local/shares/flatpak".

![imagen](https://github.com/flatpak/flatpak/assets/13048959/980c8a4f-d166-4c33-89ba-89867d3323f1)

However, you are talking "add remotes" and/or manually ad folder to install. Is there any application GUI to manage Flatpak that ask for folder to install. If there is, please, tell me its name and I'll try it instead Discover (or I can ask KDE developers about that feature).

**Comment by smcv** [comment]
> Example: I just installed "Bottles" (cause unfortunately AppImage was not fine and now they don't compile it) from Discover. When I look for files instaled, all are in ".local/shares/flatpak".

Someone or something must have added Flathub as a remote to one of your "installations" (installation directories), otherwise Discover would not know that Flatpak apps are available from Flathub.

If Discover is installing Flatpak apps into `~/.local/share/flatpak`, then there are two possible explanations: either the remote was only added to `~/.local/share/flatpak`, or the remote was added to more than one of the possible installations and Discover is defaulting to `~/.local/share/flatpak` in preference to the other one.

I don't know what that "someone or something" is. For example, it could be you (perhaps by following instructions from https://flatpak.org/setup/ or elsewhere), or it could be your OS vendor (you haven't mentioned what OS you're using).

The instructions on https://flatpak.org/setup for most (all?) distributions use `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`, which adds the remote to the `/var/lib/flatpak` installation. That's the default if no special parameters are given, and `flatpak remote-add --system ...` would be the a explicit version of the same thing.

If you are getting apps installed into `~/.local/share/flatpak`, then either you or your OS vendor must have done something differently, for example `flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo` or some GUI equivalent of that.

**Comment by RafaelLinux** [comment]
First of all, I apologise for not mentioning the operating system, since I assumed that what was really relevant was the desktop I use, since KDE-Plasma is the one that manages Flatpak.

In any case, I've been trying to find information about Flatpak through Discover and its configuration, and the only thing I've found is information that is not displayed in full, as you can see in the screenshot.

So, both for my knowledge and to inform KDE about this problem and what they should do to let the user decide where the applications are installed, how do you configure Flatpak at console level to install everything in system folders (I don't mean the data, which I understand will be stored in ".local").

**Comment by hfiguiere** [comment]
Flatpak can't install in random places. So it can't really do that. There is a choice of "user" and "system" install, and one can set an "installation".

**Comment by RafaelLinux** [comment]
Thank you very much for the information. I've been looking on the internet about it and, definitely, not being able to have full control of where I want the installation and its data to be stored, Flatpak is not for me. RPMs and AppImage do, so for my part, I don't use anything Flatpak-only anymore.

**Comment by Mikenux** [comment]
@RafaelLinux:

You have already received a response: https://github.com/flatpak/flatpak/issues/5480#issuecomment-1637149828

See also: https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation, https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-installation

**Comment by RafaelLinux** [comment]
> @RafaelLinux:
> 
> You have already received a response: [#5480 (comment)](https://github.com/flatpak/flatpak/issues/5480#issuecomment-1637149828)
> 
> See also: https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation, https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-installation

Yes, thank you very much for reminding me. However, it is an added difficulty that could be solved if Flatpak was an environment that allowed to clearly inform the user where each application is going to be installed at the time of installation, not having to resort to forums or to learn commands to find out why he suddenly ran out of space in his data folder (/home). To make a very clear analogy, "Steam" also installs applications, even more complex ones (because it allows you to install Windows applications). However, "Steam" allows to install applications (basically games) **anywhere**, clearly informing the user how much disk space the application will occupy, the available space and the destination path. 

Flatpak, however, **is not user-friendly**. It seems to me - in my opinion - that Flatpak has been developed with only technical issues in mind and they should have taken some time to think about the user. I reiterate that in that respect, Steam beats Flatpak by a thousand times. After all, both applications do the same thing, install applications, but Steam has thought about the user and their needs.

In the meantime, I can take the AppImage on a USB stick to any Linux or put it in a folder on my intranet with the security that it will be able to run it and that it won't unknowingly devour my user space.
