### ISSUE TITLE
[Feature request]: recommend foss alternatives

### ISSUE THREAD

**Issue by RustoMCSpit** [flatpak/flatpak#5483]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

say i want discord, flatpak will recommend element or something yoy get the gist. also ability to scan your system and detect apps with foss alternatives and then tell you the pros and cons

**Comment by Mikenux** [comment]
This seems more of an app store thing than a command line thing.

**Comment by RustoMCSpit** [comment]
> This seems more of an app store thing than a command line thing.

wait is this not the flatpak website repo?

**Comment by Mikenux** [comment]
If you are talking about having such feature in app stores like GNOME Software or Discover (KDE/Plasma), maybe then open an issue in them ( don't forget to search if an issue already exist first). App Stores already have access to the license information with AppStream, so it is up to them to use it.

If you want this in flatpak, that means you want this within the command line interface.

**Comment by rusty-snake** [comment]
> wait is this not the flatpak website repo?

No, the repo of the [flatpak website](https://flatpak.org/) is https://github.com/flatpak/flatpak.github.io. If you actually looking for the repo of the flat*hub* website: https://github.com/flathub/flathub.

Also you can be more specific where/when you want such an suggestion.

**Comment by basings** [comment]
This can be closed

**Comment by hfiguiere** [comment]
not flatpak scope.
