### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by julesbl** [flatpak/flatpak#5508]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Linux Mint

### Linux distribution version

21.1 Cinnamon

### What architecture are you using?

x86_64

### How to reproduce

This is a problem with phpStorm External libraries install.

Basically its a way of adding external style sheets to the project without adding them explicitly to the project files.

1. Hover over the external style style sheet in the html where it is loaded.
2. Select the Download library
3. The library is downloaded to common storage and added to the External Libraries
4. The style sheet ends up in the list with .js appended to the filename which prevents it being interpreted properly
5. Both the .css file and the .css.js files are there in the common storage, but there is no easy way to select the corect file.

### Expected Behavior

Same as the above except:

4. Style sheet should appear in the external list with .css on the end not .css.js

### Actual Behavior

The .css file is downloaded and named correctly but a duplicate file is created with .css.js on the end and that is what the external library is pointed at.

**Comment by smcv** [comment]
> This is a problem with phpStorm External libraries install

That doesn't sound like a general problem with Flatpak. Please report it to the maintainers of whatever app you are using.

> Hover over the external style style sheet in the html where it is loaded

Flatpak does not know anything domain-specific about HTML, JavaScript or CSS.
