### ISSUE TITLE
The build environment behaves differently in Fedora and Ubuntu

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#551]
I have been trying to run our GIMP Flatpak build on a Ubuntu 16.04.1 LTS server but I am having various problems which I don't have when running the build on my Fedora laptop. In particular it would seem that I have issues when the build system uses python2 instead of python3 (a workaround, when possible, is that I have to explicitly set the PYTHON env variable so that configure scripts chooses python3).

Ex on Ubuntu:

> $ flatpak build-init test org.gimp.Test org.gnome.Sdk org.gnome.Platform 3.22
> $ flatpak build test /usr/bin/gdbus-codegen
> $ flatpak build test echo $?
> 132
> $ flatpak build test python2 /usr/bin/gdbus-codegen
> $ flatpak build test echo $?
> 132
> $ flatpak build test python3 /usr/bin/gdbus-codegen
> $ flatpak build test echo $?
> 0

The exact same commands on Fedora work (whether I use python2 or python3), i.e. gdbus-codegen returns 0 whereas I use python2 (the default python) or python3.
Both the Ubuntu PPA and Fedora's flatpak display a version of 0.8.2.
I have exactly the same runtimes on both machines (same hashes):

> $ flatpak list  --show-details --runtime
> org.gnome.Platform.Locale/x86_64/3.22 gnome 9e84078aa202 - 512 bytes user /en
> org.gnome.Platform/x86_64/3.22        gnome 95c5dcfcdcda - 797.4 MB  user
> org.gnome.Sdk.Locale/x86_64/3.22      gnome 3d5e72a18c9f - 512 bytes user /en
> org.gnome.Sdk/x86_64/3.22             gnome ec39ddff4809 - 1.6 GB    user

So I would expect the flatpak environment, which is self-contained, to behave the same on both machines. Yet gdbus-codegen fails when run with python2 on Ubuntu, which means my GIMP build fails as well unless I try to track down every failure one by one and work around it.

Note also that this is not about gdbus-codegen only. For instance I had the exact same issue with `/usr/bin/g-ir-scanner`, which also returns 132 when run with run with python2 (and with python3, it would crash with various python error, but at least Python would run! In the end, I just disabled gobject introspection in GEGL, which is ok since anyway that should not be needed for a GIMP flatpak). And same when webkit would run custom python files from its repository (this one was worked around by setting $PYTHON).

132 apparently means the signal 4 (http://tldp.org/LDP/abs/html/exitcodes.html) which is "Illegal Instruction". But why does all these commands fail with python2?

Running this works:

> $ flatpak build test python2 -c 'print "hello world"'
> $ flatpak build test echo $?
> 0

Even writing this to a file and running it works.
I am available if you need me to run tests to diagnose the issue or whatever.

**Comment by hadess** [comment]
Probably the same bug as https://github.com/flatpak/flatpak/issues/143 where Python2 crashes randomly.

**Comment by Jehan** [comment]
Indeed looks quite similar. Probably the same bug. Sorry I did not see this other report!

**Comment by hadess** [comment]
No problem. I'll close this as I believe it is a duplicate. If you can gather the backtrace that was requested in the other bug, that would be most helpful.
