### ISSUE TITLE
[Bug]: Error while executing flatpak search

### ISSUE THREAD

**Issue by Mr-EmPee** [flatpak/flatpak#5517]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Debian

### Linux distribution version

6.1.0-12

### What architecture are you using?

x86_64

### How to reproduce

Install debian 12 without selecting utility tools
Install flatpak with apt
Execute flatpak search text-here

### Expected Behavior

A list of possible apps

### Actual Behavior

F: Could not parse XML data: Entity: line 1: parser error : Start tag expected, '<' not found
^

No matches found

**Comment by Mr-EmPee** [comment]
missing some packages

**Comment by brick310** [comment]
@Mr-EmPee Could you please clarify which packages are included in "some packages"? I hit this exact same error recently using flatpak on a fresh installation of Debian 12 myself. (Strangely, it only happens when doing `flatpak --user search`, but `flatpak search` appears fine; not sure what's different with `--user`.)

**Comment by Mr-EmPee** [comment]
I don't remember sorry

**Comment by stairclimber** [comment]
> I don't remember sorry

Why you closed this issue?

**Comment by Mr-EmPee** [comment]
I don't know why I remember it know but whatever, I was probably using some minimal installation of a distro without some utility packages to decompress stuff

**Comment by stairclimber** [comment]
> I don't know why I remember it know but whatever, I was probably using some minimal installation of a distro without some utility packages to decompress stuff.
> 
> -- EDIT Oh I mentioned it on the reproduction steps
> 
> > Install debian 12 without selecting utility tools

I wonder that what components are flatpak needs in this step

**Comment by Mr-EmPee** [comment]
Try to install a version of debian 12 without the utility tools package
