### ISSUE TITLE
[Bug]: Disagreement between Flatpak and Freedesktop Icon Theme Specification

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak#5518]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

openSUSE Tumbleweed

### What architecture are you using?

x86_64

### How to reproduce

1. Read https://docs.flatpak.org/fr/latest/conventions.html
2. Find the following: 

> These icons should be provided in accordance with the [Freedesktop icon specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html).
[...]
Icons must be square shaped, ie their width and height must be the same. The maximum size allowed by the specification is 512x512px.

3. Confirm that this matches the behavior of the Flathub buildbot:

`error: /srv/buildbot/worker/build-x86_64/build/builddir/export/share/icons/hicolor/1024x1024/apps/eu.vcmi.VCMI.png is not a valid icon: Image too large (1024x1024). Max. size 512x512`

4. Compare this to the Freedesktop spec

### Expected Behavior

Either the Freedesktop spec mentions 512 px being the maximum allowed icon size, or Flatpak and its docs allow icons of arbitrary size.

### Actual Behavior

The Freedesktop spec does not mention a maximum allowed icon size, while Flatpak and its documentation do reference amaximum allowed size.

### Additional Information

I tested the `flatpak-builder` behavior here:

https://github.com/flathub/eu.vcmi.VCMI/pull/138

I removed the following line from the manifest:

`rm -rf /app/share/icons/hicolor/1024x1024 /app/share/icons/hicolor/2048x2048`

VCMI installs 1024 and 2048 icons:
https://github.com/vcmi/vcmi/blob/7f321b2fcbe5528e3e19280d529405b3921fa330/client/CMakeLists.txt#L475

If I don't delete them, the test build fails:

```
Exporting eu.vcmi.VCMI to repo
]2;flatpak-builder: Exporting to repositoryFB: Running: flatpak build-export --arch=x86_64 '--subject=Don'\''t delete 1024 px and 2048 px icons (e6f9d860)' '--exclude=/lib/debug/*' --include=/lib/debug/app '--exclude=/share/runtime/locale/*/*' /srv/buildbot/worker/build-x86_64/build/repo builddir test
error: /srv/buildbot/worker/build-x86_64/build/builddir/export/share/icons/hicolor/1024x1024/apps/eu.vcmi.VCMI.png is not a valid icon: Image too large (1024x1024). Max. size 512x512
Export failed: Child process exited with code 1
```

**Comment by hfiguiere** [comment]
At no point the specification linked to secify that 1024x1024 is a valid size. So it's not a disagreement.
