### ISSUE TITLE
Can't use "flatpak update" with a bundle

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#552]
The only way to update from a bundle is to remove and install. I'd expect something like `flatpak update --user --bundle foo.flatpak` to work.

**Comment by jscurtu** [comment]
That is because you are using a old version of flatpak, this was adressed already and fixed.
https://github.com/flatpak/flatpak/issues/462

#462 

FYI : We now have a flatpak repository.

**Comment by hadess** [comment]
Using 0.8.2. That fix was in 0.8.1, so that's not it.

**Comment by jscurtu** [comment]
Intressting... maybe it was only deployed to fedora?

**Comment by alexlarsson** [comment]
flatpak update never worked for bundles, but you can flatpak install a newer version and that will cause it to update

**Comment by hadess** [comment]
> flatpak update never worked for bundles, but you can flatpak install a newer version and that will cause it to update

Right, and it's possible that the build script I used generated the same version for my 2 attempts, but it didn't show those version numbers, eg. like in @jscurtu's it complains:
```
Error: org.gnome.feedreader/x86_64/master already installed
```

**Comment by matthiasclasen** [comment]
Nothing to fix here, I think
