### ISSUE TITLE
Can't save pictures/videos etc in normal file location (only happens when using Flatpaks.)

### ISSUE THREAD

**Issue by linuxmintg** [flatpak/flatpak#5530]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

 1.12.4

### What Linux distribution are you using?

Linux Mint

### What architecture are you using?

x86_64

### How to reproduce

When I want to save pictures, it doesn't go to the normal place to save. Instead of going to documents, it goes to documents in the Flatpak sandbox /run/user/1000/doc/6b980a99/documents **Has this problem been fixed in later versions of Flatpak?** (I feel a bit nervy to download anything new.) I want it to save pictures (for example) in the /home/user/documents file path.

This problem is in Snaps as well.... 

This makes more clicks than I should every time I save a picture.

I'm a big believer in flatpaks but I've really noticed this as a problem lately in browsers and in Telegram.

### Expected Behavior

Save documents in normal location eg: /home/user/documents file path

### Actual Behavior

 /run/user/1000/doc/6b980a99/documents

### Additional Information

Appreciate any help.
I tried to search if this was a problem already in the archives but it doesn't seem to be discussed. Please bear with me as I'm new to Github (at least new in participating.) Thanks.

**Comment by chrisawi** [comment]
`/run/user/$UID/doc/...` is a document portal path. This is what you get when using the File Chooser portal to select a file that the app does not have access to. As @rust86 demonstrated, it's possible to grant direct access for the app (that's a screenshot of Flatseal), but this is inherently insecure.

If the problem is that the file chooser presents a document portal path back to the user, that's https://github.com/flatpak/xdg-desktop-portal/issues/982, which was fixed in xdg-desktop-portal 1.18.
