### ISSUE TITLE
[Feature request]: Implement a permission flag for allowed commands for flatpak-spawn on host

### ISSUE THREAD

**Issue by mirkobrombin** [flatpak/flatpak#5538]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

@89luca89 and I have analyzed the apps that currently use `flatpak-spawn` to access areas of the host, and we have found several of them on Flathub. From what we understand this behavior is discouraged by Flathub and is the cause of potential rejections in publication because `flatpak-spawn` allows arbitrary code execution on the host, posing a potential security risk, albeit limited by not having administrative privileges.

We have thought a lot about this issue in recent weeks and have found a possible solution that would allow applications to execute commands on the host using a semaphore.

As of now, correct me if I'm wrong, `flatpak-spawn` (like `host-spawn`) makes host-side calls by talking with the `org.freedesktop.Flatpak` Dbus. Our proposal is that applications should declare in their manifest, similar to how permissions are declared, which commands can be executed. So, when a `flatpak-spawn` request is made to execute a specific command, it is checked whether that specific command is in the list of commands declared in the manifest. For example, if the flatpak declares access to the `podman` command, at the moment it executes:

- `docker`: denied
- `htop`: denied
- `podman ps -a:` allowed
- `podman list`: allowed
- `rm -f /`: denied

This way, it is immediately clear what that flatpak is trying to execute on the host. It's not a complete security measure, but it's certainly better than the current situation, where it's a yes or no question regarding a hole in the bubblewrap.

The concept could be extended to the depth of the command, for example, by declaring:
- `podman`: it will be possible to use all `podman` commands
- `podman ps`: only subcommands of `podman ps` can be used
- `docker list`: only subcommands of `docker list` can be used

In the examples above, I used `podman` and `docker`, which are both container engines, but there's no specific reason for that choice.

Please let us know if we have misunderstood any concepts, and if this reasoning makes sense.

**Comment by axtloss** [comment]
It may be better to use a portal for this, giving the user a popup similiar to "let <application> run <command>", since these static permissions could still be abused to gain more priviliges.

It could also be coupled with the static permission described to simply reject any command that is not allowed and show the pop up for those that are allowed.

**Comment by smcv** [comment]
> using a semaphore

This is not at all what I understand "a semaphore" to mean, so I've retitled the issue.

**Comment by smcv** [comment]
If you're familiar with tools like `sudo`, you'll recognise this as being "the same shape" as the problem with granting `sudo` access on a finer granularity than `ALL`. The privilege boundary being crossed is a different one (for Flatpak it's sandboxed -> unsandboxed, for sudo it's typically non-root -> root) but the limitations of trying to filter by command name are the same.

**Comment by mirkobrombin** [comment]
@Smcv I understand your point and it's correct. The problem persists even without a responsibility on the part of Flatpak. Our idea is not to secure access to flatpak-spawn but to filter the commands that can be executed via it.

In my opinion the idea of axtlos:

> It may be better to use a portal for this, giving the user a popup similiar to "let run ", since these static permissions could still be abused to gain more priviliges.
> 
> It could also be coupled with the static permission described to simply reject any command that is not allowed and show the pop up for those that are allowed.

is actually a great idea. Having a portal that works that way could make more evidence of what’s happen under the hood.

Me and Luca are still discussing those things and the usage of a portal was one of the ideas that was being discussed.

**Comment by mirkobrombin** [comment]
> Only if it's not justified. I had no issue publishing an app "Junction" that needs flatpak-spawn --host
Then Flathub must provide clear guidelines of what it intend for "justified". For example.
- Is [Distrobox](https://github.com/89luca89/distrobox) be a justified case? It requires podman in the host and need to communicate with it via command line.
- Is talking with `org.freedesktop.Flatpak` justified in Atoms? It is required for Atoms to talk with Distrobox containers.


> "Pods" 😉

Is this a citation or what? I don't get the irony here.


> if you really want it not to be marked as unsafe

Never said that filtering access to flatpak-spawn would mark any app secure.


> Podman ships an official Flatpak app (unsafe but trusted) that communicates with podman on the host

That app talks with `org.freedesktop.Flatpak`, which means it has access to `flatpak-spawn` as well. Based on what you said on Mastodon: `There is no way to guarantee an executable won't do something disallowed by the sandbox/permissions.` and this is the same in this context. What if the podman binary in the host gets compromised? Is that flatpak's fault since it was executed by the flatpak, or user's fault because they got ~~hacked~~?


> Pods can manage containers by communicating with the Flatpak Podman app

Not aware of this and it's pretty weird since the Podman flatpak is just a frontend, not podman itself. Pods manage containers using the Podman client via Unix socket, that's why Pods does not need to talk with  `org.freedesktop.Flatpak`. 


> But personally I think it's fine for developer tools to be considered unsafe for now.

I agree with this.

**Comment by mirkobrombin** [comment]
> Anyway, if we agree it's fine for developer tooling to be considered unsafe, let's close this and focus on specific use cases we can solve with portals.

We were not only talking about development applications. As I said, podman and docker were just examples. I can see [many](https://github.com/search?q=org%3Aflathub%20--talk-name%3Dorg.freedesktop.Flatpak&type=code) apps talking with `org.freedesktop.Flatpak`. Like a [music player](https://github.com/flathub/org.gnome.Lollypop/blob/master/org.gnome.Lollypop.json#L20), a [file manager](https://github.com/flathub/org.kde.dolphin/blob/master/org.kde.dolphin.json#L18), a [wiki browser](https://github.com/flathub/org.zim_wiki.Zim/blob/master/org.zim_wiki.Zim.yaml#L23), a [tool for comparing text files](https://github.com/flathub/io.github.mightycreak.Diffuse/blob/3732e22a0af030757f0e9aba90e71d32c348ea01/io.github.mightycreak.Diffuse.yml#L12), a [video editor](https://github.com/flathub/org.openshot.OpenShot/blob/fc93fa446fba672e8c85df76184d3d987946546d/org.openshot.OpenShot.yaml#L17), a [virtual assistant](https://github.com/flathub/edu.stanford.Almond/blob/19ff86bfc26b22d94a1406291e19b3f320dd0130/edu.stanford.Almond.json#L27), an [utility to add stream services to steam](https://github.com/flathub/com.github.theCalcaholic.StreamDeck/blob/e21345db6097fb31e86ed56d1d80796db09c88a5/com.github.theCalcaholic.StreamDeck.yml#L20), and many, many others which are not development utilities, and which, IMHO, should have limited access to flatpak-spawn.

**Comment by Mikenux** [comment]
Exactly :slightly_smiling_face: 

Issue https://github.com/flatpak/xdg-desktop-portal/issues/283 might be of interest. For commands, you can read from https://github.com/flatpak/xdg-desktop-portal/issues/283#issuecomment-1485555778. Note that @orowith2os already requested this: https://github.com/flatpak/xdg-desktop-portal/issues/1003

**Comment by mirkobrombin** [comment]
Thank you for the discussion and interest on the matter.
