### ISSUE TITLE
[Bug]: flatpak uninstall --unused removes offers to remove old version of Nvidia driver but doesn't offer to unsinatll equivalent 32-bits version of driver

### ISSUE THREAD

**Issue by MateusRodCosta** [flatpak/flatpak#5539]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

39 Beta

### What architecture are you using?

x86_64

### How to reproduce

1. Update Nvidia driver version
2. Reboot
3. Run flatpak update
4. Flatpaks for newer drivers versions are installed
5. Use `flatpak uninstall -unused`
6. Only 64-bits version of the old driver is offered to be uninstalled (`org.freedesktop.Platform.GL.nvidia-535-104-05`)

### Expected Behavior

Both the 64-bits (`org.freedesktop.Platform.GL.nvidia-535-104-05`) and the 32-bits (`org.freedesktop.Platform.GL32.nvidia-535-104-05`) versions should be offered for unsinatll at the same time.

### Actual Behavior

Only the 64-bits (`org.freedesktop.Platform.GL.nvidia-535-104-05`) is offered for uninstall.

**Comment by chrisawi** [comment]
This was fixed in https://github.com/flatpak/flatpak-builder/pull/577.

Updating apps to use `autoprune-unless = active-gl-driver` in their GL32 extensions is still in progress. Steam is already fixed, and anything using the Wine baseapp should be covered by https://github.com/flathub/org.winehq.Wine/pull/113.
