### ISSUE TITLE
[Bug]: User data is not stored in $XDG_DATA_HOME

### ISSUE THREAD

**Issue by salarua** [flatpak/flatpak#5541]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

38

### What architecture are you using?

x86_64

### Expected Behavior

Flatpak stores user data of installed apps in `$XDG_DATA_HOME`.

### Actual Behavior

Flatpak ignores `XDG_DATA_HOME` and instead stores user data in a new hidden directory, `.var/app`.

**Comment by smcv** [comment]
This is working as designed, and has been discussed at length in #46, #1651, #1991, #3997 and probably others.

**Comment by arvaid** [comment]
It's designed wrong then
