### ISSUE TITLE
[Feature request]: Allow modularity of runtimes for each app

### ISSUE THREAD

**Issue by blacklightpy** [flatpak/flatpak#5550]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Allow apps to have multiple runtimes instead of just one. As in, instead of a single large runtime, use smaller runtimes. If the larger runtime contains smaller runtimes, then it can be used instead of duplication.

**Comment by hfiguiere** [comment]
While runtime aren't Flatpak responsibility, in general it's not part of the design to reproduce the problem of distros.
