### ISSUE TITLE
[Bug]:  With updates, flatpak shows strange charactets when finished ...

### ISSUE THREAD

**Issue by Dutchglory** [flatpak/flatpak#5551]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

23.10 - Mantic Minotaur 

### What architecture are you using?

amd64

### How to reproduce

run flatpak update

### Expected Behavior

--
### Actual Behavior

this is what i get: 

Looking for updates…

ID                                             Branch                 Op            Remote             Download
1.     org.freedesktop.Platform.GL.default            22.08                  u             flathub            < 143,1 MB
2.     org.freedesktop.Platform.GL.default            22.08-extra            u             flathub            < 143,1 MB
3.     org.freedesktop.Platform.Locale                22.08                  u             flathub            < 333,4 MB (partial)
4.     org.gtk.Gtk3theme.Breeze                       3.22                   u             flathub            < 191,9 kB
5.     org.freedesktop.Platform                       22.08                  u             flathub            < 211,7 MB

Updating 5/5… ████████████████████ 100%  3,2 MB/s  00:00^[[32;66R^[[32;66RR[[32;75R
^[[32;75RAlle snaps zijn bijgewerkt.
verwijs@verwijs-kubuntu:~$ ;1R;9R;17R;60R;49R;59R;59R;59R;68R;68R;68R;59R;59R;68R;66R;66R;66R;66R;66R;75R;84R;60R;49R;59R;59R;59R;59R;59R;66R;66R;66R;75R;84R;60R;49R;49R;67R;51R;40R;49R;49R;67R;60R;49R;59R;59R;59R;59R;59R;50R;50R;59R;66R;66R;66R;66R;66R;66R;75R

### Additional Information

OS INFORMATION
~~~~~~~~~~~~~~~

Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.3.0-7-generic (64-bit)
Graphics Platform: X11
Processors: 2 × Intel® Core™2 CPU 6700 @ 2.66GHz
Memory: 5.7 GiB of RAM
Graphics Processor: NVD9

**Comment by chrisawi** [comment]
Thanks for the report, but this has already been reported.

Duplicate of #2712
