### ISSUE TITLE
[Bug]:  flatpak fail to run ;erroneous "No space left on device"

### ISSUE THREAD

**Issue by develroo** [flatpak/flatpak#5555]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Debian

### Linux distribution version

Testing/Trixie

### What architecture are you using?

x86_64

### How to reproduce

Some flatpak fail to start from the desktop and when run from the command line throw this error. 

`error: Failed to write file “/run/user/1000/.flatpak/2162479098/info.FTGPC2”: write() failed: No space left on device`

### Expected Behavior

flatpak apps should execute normally. 

### Actual Behavior

This does not occur on all flatpak apps, though some that did not work started working without reason, while others are broken 

```
/usr/bin/flatpak -vv run  org.telegram.desktop
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/8745946eed14ab6da3e21a642a467c994fe0f2bea1ad27a933464dca63ceabe4/files/lib32 does not exist
F: Cleaning up unused container id 2230375910
F: Failed to load instance info file '/run/user/1000/.flatpak/2230375910/info': No such file or directory
F: Not cleaning up per-app dir: Unable to load keyfile /run/user/1000/.flatpak/2230375910/info
F: Allocated instance id 3252110424
error: Failed to write file “/run/user/1000/.flatpak/3252110424/info.0Y8WC2”: write() failed: No space left on device

```

```
/usr/bin/flatpak -vv run  org.kde.krita
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/9d00a8cd4b3ea5f83c871a060303d5f84330dc674d2bc555629aa808ef11c2e2/files/lib32 does not exist
F: Cleaning up unused container id 3252110424
F: Failed to load instance info file '/run/user/1000/.flatpak/3252110424/info': No such file or directory
F: Not cleaning up per-app dir: Unable to load keyfile /run/user/1000/.flatpak/3252110424/info
F: Allocated instance id 2162479098
error: Failed to write file “/run/user/1000/.flatpak/2162479098/info.FTGPC2”: write() failed: No space left on device

```

### Additional Information

Kernel 6.5.0-1-amd64 

- **Memory:**                                      64.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 4800H with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               2.0 TB

## Software Information:
- **OS Name:**                                     Debian GNU/Linux trixie/sid
- **OS Type:**                                     64-bit
- **GNOME Version:**                               44.5
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.0-1-amd64

The error is spurious because `/run/` is nether full, nor are permissions incorrect. 

```
Filesystem                         Size  Used Avail Use% Mounted on
udev                                32G     0   32G   0% /dev
tmpfs                              6.3G  2.6M  6.3G   1% /run

```

```
ls -la /run/user/
total 0
drwxr-xr-x  3 root    root      60 Oct  8 22:38 .
drwxr-xr-x 48 root    root    1400 Oct  8 22:23 ..
drwx------ 22 user user  740 Oct  8 22:38 1000

```

**Comment by develroo** [comment]
For reference,
 here is a strace of trying to run `org.kde.krita` 
 
 [flatpak.debug.txt](https://github.com/flatpak/flatpak/files/12843986/flatpak.debug.txt)

**Comment by smcv** [comment]
`/run/user/1000` is usually a separate tmpfs, and it seems that yours is full.

Flatpak is not lying to you, the kernel is genuinely telling Flatpak that the filesystem is full:

> ```
> 245310 openat(AT_FDCWD, "/run/user/1000/.flatpak/938417231/info.52QQC2", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0666) = 32
> 245310 newfstatat(AT_FDCWD, "/run/user/1000/.flatpak/938417231/info", 0x7fff9228e0d0, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
> 245310 fallocate(32, 0, 0, 2432)        = -1 ENOSPC (No space left on device)
> 245310 write(32, "[Application]\nname=org.kde.krita"..., 2432) = -1 ENOSPC (No space left on device)
> ```

**Comment by develroo** [comment]
Hmmm, that  seems so now?

How does tmpfs get so full after login then? 

Looking at the `/run/user/1000/` seems there is a  folder `psd` which is full of browsers profiles taking up 99% of the space ? 

What is `psd` and how does it not clear on reboot? Or does it just fill up as soon as I login? 

```
...
user-firefox-s07iooil.Sandbox-1683826247874
user-firefox-t85m97ro.default-esr-5
user-firefox-ug6d09z9.ModtoolboxTest
user-firefox-vn8rnmdm.LegacyJavaProfile
user-firefox-xpvhoe3e.AmazonVideo-1568634096880
user-vivaldi
...
```

**Comment by rusty-snake** [comment]
If you use profile sync deamon, you have to set it up correctly, including the tmpfs where you sync to.

If the sync happens after login or with browser start is something idk.

**Comment by develroo** [comment]
Yeah. Can't say I ever even heard of it before today. So I will investigate. Thanks all the same. As you can see df did not show it right away but the strace later did. hey ho.

**Comment by ostap-tymchenko** [comment]
Hi, I had the same issue, fixed by restarting computer.

**Comment by develroo** [comment]
FWIW seems the core issue was psd, or profile-sync-daemon 

> Symlinks and syncs browser profiles to RAM (tmpfs) thus reducing HDD/SSD calls and speeding up browsers.

I have *many* browser profiles over many years for testing, and that was gobbling up tmpfs. (yes 32Gb fills up in seconds) 

I nullified this by making psd make reflinks/overlay instead of copying it there.  It is all documented in the man page.
