### ISSUE TITLE
"env" does not accept environment variable

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#556]
To temporarily bypass another bug of flatpak, I made a temporary script inside the source directory of a module and in "build-options" > "env", I tried to update $PATH this way:

> "PATH": "$PWD/tmp-bin:$PATH"

But it failed immediately and autogen.sh was just unable to find any command.
Fortunately that was quite easy to bypass since we are in a very static environment and we know that PATH is "/app/bin:/usr/bin" by default, so I could set instead (module being named "gimp"):

> "PATH": "/run/build/gimp/tmp-bin:/app/bin:/usr/bin"

Yet we would definitely expect environment variables to get expanded as they normally would in a shell script. For setting many environment variables, it's quite a common trick to extend it from its previous value that you'd want to reuse in the new value (like lists of directory, i.e. in $PATH).

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#18
