### ISSUE TITLE
[Feature request]: Ability to install multiple locales

### ISSUE THREAD

**Issue by kra-mo** [flatpak/flatpak#5560]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

For using spellcheckers on documents that don't match your system's language, you may want to install the locale for that specific language.

Currently, the only way to install a locale not matching your system one is to `--reinstall` the `.Locale` package and install all available locales.

This is not a great solution as you would normally only want 2-3 specific locales. Providing a proper way to install specific locales would also allow for integration into other (GUI) software, streamlining the process.

**Comment by mfschumann** [comment]
How about specifying the additional locales using `flatpak config --user --set extra-languages` ? For all flatpaks that you install afterwards, you should get the locale matching your system plus all locales that you specified as extra-languages.

Documentation for the command is [here](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-config).

**Comment by kra-mo** [comment]
Ah yes, that is what I was looking for, I just didn't know it existed.
