### ISSUE TITLE
Question: Why are .desktop files using the entire /usr/bin/flatpak path?

### ISSUE THREAD

**Issue by firefoxlover** [flatpak/flatpak#5562]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Regular applications are simply created as desktop entries, assuming they are in the system PATH.

Every Linux Distro that has Flatpak installed will have it in its path, or not? Is there an example why it is necessary to set `/usr/bin/flatpak run x.y.z` instead of just `flatpak run x.y.z` ?

This seems irrelevant, but I dont get it.

**Comment by chrisawi** [comment]
The short answer seems to be that the same code is used to rewrite exported D-Bus .service files, and those [must have absolute paths](https://github.com/flatpak/flatpak/commit/767b89cd718735b4dd1b51bfa688ef7ce780c202).

An absolute path is slightly more robust, and [there is now an override env var](https://github.com/flatpak/flatpak/commit/a99b748931e6444dadb0d0c8c1565da23f755800) (`FLATPAK_BINARY`) for the rare case where it needs to be changed, e.g. flatpak-builder used inside the sandbox.

The decision of whether to use PATH lookup needs to be applied consistently to avoid having half-broken apps. So, if .service files can't use PATH, nothing can. FWIW, I can't find anything in the D-Bus spec that says .service files need to use absolute paths, but this rule is universally followed in the files on my system, so I expect it's required by the implementation.
