### ISSUE TITLE
[Bug]: Flatpak Bleachbit Won't Launch After Update "Traceback (most recent call last):"is:issue is:open 

### ISSUE THREAD

**Issue by KrauzerPH94** [flatpak/flatpak#5568]
## Checklist
- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

## Flatpak version
1.15.4

## What Linux distribution are you using?
Fedora Linux

## Linux distribution version
Linux fedora 6.5.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 20 15:53:48 UTC 2023 x86_64 GNU/Linux

## What architecture are you using?
x86_64

## How to reproduce
There are two ways to reproduce

### Via GUI
1. Install the app using your desired software center;
2. Try to launch it via your app launcher and/or shortcut;
3. Observe the app process hanging then closing itself.

### Via CLI
1. Install and run the application:
```bash
$ flatpak install org.bleachbit.BleachBit
$ flatpak run org.bleachbit.BleachBit
```
2. Observe the feedback error:
```bash
Traceback (most recent call last):
  File "/app/bin/bleachbit", line 28, in <module>
    from bleachbit import _
ModuleNotFoundError: No module named 'bleachbit'
```

## Expected Behavior
For the app to open, either via GUI or CLI, and display me it's window

## Actual Behavior
App won't launch after last update, no error message, it just hangs without response.
I'm currently on **version v4.5.0**, app installed via [Flatpak using the Flathub](https://flathub.org/apps/org.bleachbit.BleachBit) repository.

## Additional Information
- **Bug Ocurrence:** everytime I open the app, using either one of the above methods
## My Environment
- OS: Fedora 38
- DE: GNOME 44.5
- Kernel: 6.5.7
- WM: Xorg (X11)
- App version: v4.5.0
- App repo: [Flathub](https://flathub.org/)

**Comment by KrauzerPH94** [comment]
Solved itself with an update

**Comment by smcv** [comment]
> If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself

I don't think you did this. This is definitely an issue with a particular app.

**Comment by KrauzerPH94** [comment]
@smcv in fact I did, here is my issue on the app's GitHub: https://github.com/bleachbit/bleachbit/issues/1566
