### ISSUE TITLE
[Bug]: Can't access `/usr` with permission

### ISSUE THREAD

**Issue by JakobDev** [flatpak/flatpak#5575]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Manjaro Linux

### Linux distribution version

latest

### What architecture are you using?

x86_64

### How to reproduce

Give a Flatpak the `filesystem=host:ro` permission. now you can access the `/usr `directory f the Host as `/run/host/usr` inside the Flatpak.

Now remove the `filesystem=host:ro`  permission and add the `filesystem=/usr/share/applications:ro` instead.

### Expected Behavior

You should be able to access `/usr/share/applications` from the host inside the Flatpak as `/run/host/usr/share/applications`.

### Actual Behavior

When starting the Flatpak you get an `F: Not sharing "/usr/share/applications" with sandbox: Path "/usr" is reserved by Flatpak` error and can't access the directory.

**Comment by JakobDev** [comment]
> Maybe `--filesystem=host-os/share/applications` or so would make this more explicit.

Unbfortunally not.

```
Unknown filesystem location host-os/share/applications, valid locations are: host, host-os, host-etc, home, xdg-*[/…], ~/dir, /dir
```

**Comment by smcv** [comment]
This is not possible. As the error message says, `/usr` is "owned" by Flatpak (for the runtime) and you cannot add it as a permission: that's why we have `host-os`, to give you a different route to access the host's `/usr`.

**Comment by smcv** [comment]
`host-os` does not support sharing subsets of `/usr`: as a simplification, it's all-or-nothing. All of `/usr` is controlled by the OS vendor and/or sysadmin, via OS-level package managers or similar, so it doesn't seem like there's any security advantage to having access to some but not all of it?

**Comment by qoijjj** [comment]
@smcv greatly appreciate your input on this, that makes complete sense. I'll pursue a thread with freedesktop requesting the extension functionality you mentioned. Thanks again for pointing me in the right direction.

**Comment by qoijjj** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1680
