### ISSUE TITLE
bwrap: Can't find source path /run/user/1000/doc/by-app/com.spotify.Client: Permission denied

### ISSUE THREAD

**Issue by Lyton505** [flatpak/flatpak#5580]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

38

### What architecture are you using?

x86_64

### How to reproduce

Install spotify flatpak
Try to run
Fails

### Expected Behavior

I expected Spotify to run

### Actual Behavior

I get the following output

```
bwrap: Can't find source path /run/user/1000/doc/by-app/com.spotify.Client: Permission denied
```

### Additional Information

I've tried killing `xdg-document-portal` and restarting it.

Output of `env G_MESSAGES_DEBUG=all /usr/libexec/xdg-document-portal --replace --verbose` when I attempt to start the flatpak:

```
(/usr/libexec/xdg-document-portal:75095): GLib-GIO-DEBUG: 19:40:48.192: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
XDP: Providing portal org.freedesktop.portal.Documents
XDP: Providing portal org.freedesktop.portal.FileTransfer
XDP: org.freedesktop.portal.Documents acquired
XDP: INIT
XDP: ACCESS 1
XDP: LOOKUP 1:.Trash
XDP: LOOKUP -> error ENOENT
XDP: LOOKUP 1:.Trash-1000
XDP: LOOKUP -> error ENOENT
XDP: GETATTR 1
(/usr/libexec/xdg-document-portal:75095): GLib-GIO-DEBUG: 19:40:56.824: GTask 0x5563f9418a40 (source object: (nil), source tag: (nil)) finalized without ever returning (using g_task_return_*()). This potentially indicates a bug in the program.
^CXDP: DESTROY
```

**Comment by smcv** [comment]
Are other apps affected by this, or is this specific to Spotify?

**Comment by Lyton505** [comment]
All flatpaks were, at the time of writing, affected by this. However, everything seems to be working now

**Comment by chrsrns** [comment]
This happens to me. I still don't know the cause of it. A complete restart always fixes it, but only for the time being. Does anyone have any idea on how to fix it?

**Comment by Francewhoa** [comment]
## Confirmed

This is to confirm this challenge

----------------

## Temporary Workaround

For those facing this challenge, the steps below temporary fixed this challenge. But the same challenge comes back after a few hours or days.

Steps:

1. Kill this process `xdg-document-portal`. For those not familiar with "kill", it means to both end and close an active app. To do so choose one of the following two options:
   * Option 1: Using **[jdSystemMonitor](https://flathub.org/en/apps/page.codeberg.JakobDev.jdSystemMonitor)** or **GNOME System Monitor** or any other system monitor to your liking, kill the `xdg-document-portal` process. It will automatically restart fresh.
   * Option 2: Using Debian, if not already done, install the **sudo** package. Then, using [Konsole](https://flathub.org/en/apps/org.kde.konsole) or Terminal, execute this command: `sudo systemctl --user restart xdg-document-portal`

1. Fully exit the Flatpak app. Including all its windows.

1. Start the Flatpak app

1. Error is gone

1. For your information, killing `xdg-document-portal` means that your Linux risk to be increasingly unstable. When this happen, restart the device to resolve this challenge.

----------------

## Related Ticket

Including screenshot and steps to reproduce at https://github.com/flatpak/xdg-desktop-portal/issues/1410

----------------

## Cause

I do not know what is the cause of this challenge. My guess is the XDG Document Portal is unstable. It need fixing love.

https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome

https://packages.debian.org/trixie/xdg-desktop-portal

https://packages.debian.org/trixie/xdg-desktop-portal-kde

https://packages.debian.org/trixie/xdg-desktop-portal-gnome

https://packages.debian.org/trixie/xdg-desktop-portal-gtk

**Comment by AdivonSlav** [comment]
This shouldn't be closed, still happens on my sistem and the above workaround fixes it temporarily.

Fedora 40
KDE Plasma 6.1
Flatpak 1.15.8

**Comment by smcv** [comment]
> the above workaround fixes it temporarily

This contradicts what the original reporter of this issue said: they said "I've tried killing xdg-document-portal and restarting it", with the implication that doing that didn't fix the issue for them.

I think that might mean you are seeing a similar symptom for a different reason, so please open your own issue with as much debug information as you can provide.

**Comment by caleskog** [comment]
I have the same problem. Using Fedora with KDE 40 Plasma.

Btw, this issue is exactly the same as this: #5860

**Comment by caleskog** [comment]
My flatpak app (Spotify) started after restarting _xdg-document-portal_. Thou, it took around 30 seconds until it opened, and I thought it crashed due to the icon disappearing from the taskbar.

This are the commands I used for restarting _xdg-document-portal_:
```console
systemctl kill --user xdg-document-portal
systemctl start --user xdg-document-portal
```

**Comment by skafiend** [comment]
it Just happened to me too. it seems the cause of the issue is btrfs snapshots. after restoring root to the previous state all flatpak apps went nuts; though killing and restarting xdg-document-portal fixed the issue

**Comment by sqrt-7** [comment]
Having the same issue.
Fedora 40 (Gnome)
Killing and restarting xdg-document-portal allows me to start the application (after a 30 second load time) but then goes back to the same issue.

Rebooting the computer always fixes it.

**Comment by Renner0E** [comment]
@skafiend
this seems to happen to me on F40 Kinoite.
If you run it from the .desktop entry which executes `/usr/bin/btrfs-assistant-launcher` and then prompts you for your password this issue happens consistently to me.

However if you run it with `sudo btrfs-assistant` [no GUI password prompt] flatpaks will work.

After I ran a manual snapshot of my home dir (no rootfs) flatpak also still worked.

**Comment by skafiend** [comment]
> @skafiend this seems to happen to me on F40 Kinoite. If you run it from the .desktop entry which executes `/usr/bin/btrfs-assistant-launcher` and then prompts you for your password this issue happens consistently to me. This is a wayland window.
> 
> However if you run it with `sudo btrfs-assistant` [no GUI password prompt] flatpaks will work (Xwayland window).
> 
> After I ran a manual snapshot of my home dir (no rootfs) flatpak also still worked.
> 
> If you run `pkexec btrfs-assistant --xdg-runtime="${XDG_RUNTIME_DIR}" --platform="${QT_QPA_PLATFORM}" --display="${WAYLAND_DISPLAY}"` which is pretty much just what [btrfs-assistant-launcher](https://gitlab.com/btrfs-assistant/btrfs-assistant/-/blob/a396b1b1dcfb0ba7b12907635cce1d359892bbb6/src/btrfs-assistant-launcher) does
> 
> This script basically overwrites the permissions for /run/user/1000/doc and is completely empty after that

thank you for the response, I'll try that

**Comment by Renner0E** [comment]
> > @skafiend this seems to happen to me on F40 Kinoite. If you run it from the .desktop entry which executes `/usr/bin/btrfs-assistant-launcher` and then prompts you for your password this issue happens consistently to me. This is a wayland window.
> > However if you run it with `sudo btrfs-assistant` [no GUI password prompt] flatpaks will work (Xwayland window).
> > After I ran a manual snapshot of my home dir (no rootfs) flatpak also still worked.
> > If you run `pkexec btrfs-assistant --xdg-runtime="${XDG_RUNTIME_DIR}" --platform="${QT_QPA_PLATFORM}" --display="${WAYLAND_DISPLAY}"` which is pretty much just what [btrfs-assistant-launcher](https://gitlab.com/btrfs-assistant/btrfs-assistant/-/blob/a396b1b1dcfb0ba7b12907635cce1d359892bbb6/src/btrfs-assistant-launcher) does
> > This script basically overwrites the permissions for /run/user/1000/doc and is completely empty after that
> 
> thank you for the response, I'll try that

More context:
https://discussion.fedoraproject.org/t/btrfs-assistant-increasing-flatpak-apps-boot-time/120497/8
https://gitlab.com/btrfs-assistant/btrfs-assistant/-/issues/105

**Comment by ilippert** [comment]
for me it helps to run `systemctl --user restart xdg-document-portal.service`, indicated in https://github.com/ublue-os/bazzite/issues/1415

**Comment by gmipf** [comment]
@ilippert Had the same issue today on Fedora 41 KDE, your command helped, thanks a lot!

**Comment by razorree** [comment]
The same happenned to me on Ubuntu 25.04, freshly installed package:

```
flatpak run org.gnome.World.PikaBackup                                                                                                      
bwrap: Can't find source path /run/user/1000/doc/by-app/org.gnome.World.PikaBackup: Permission denied

```

systemctl --user restart xdg-document-portal.service  - helped
