### ISSUE TITLE
[Bug]: Input of «angle quotes» is broken in Flatpak apps after upgrading libxkbcommon to 1.6.0

### ISSUE THREAD

**Issue by gentoo-root** [flatpak/flatpak#5585]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

rolling

### What architecture are you using?

x86_64

### How to reproduce

1. Install Telegram from flatpak on GNOME on Arch Linux. Use the Wayland session.
2. Configure misc:typo and lv3:ralt_switch XKB options.
3. Start Telegram and try to type `«»` into any text field using RightAlt+<, RightAlt+>.

### Expected Behavior

Angle quotes `«»` should appear in the text field.

### Actual Behavior

Nothing happens.

### Additional Information

I'm running GNOME 45.1 on Wayland on Arch Linux, and I'm using a keyboard layout that has angle quote characters `«»` on the third layer (e.g., ru+ruu or misc:typo with lv3:ralt_switch would work for the test).

After I upgraded libxkbcommon and libxkbcommon-x11 from 1.5.0 to 1.6.0, I can't enter these angle quotes `«»` into any text field in Telegram (see the related issue there: https://github.com/telegramdesktop/tdesktop/issues/26976#issuecomment-1802788266) or Lutris installed from flatpaks. It's still possible to copy and paste those into the affected apps, or to type them from the keyboard into any other Qt or GTK non-flatpak application.

**Comment by eshfield** [comment]
I still have the problem with not inputable «angle quotes» on Fedora 40 with Telegram Desktop v. 5.1.4 installed from Fedora flatpak with Software app
