### ISSUE TITLE
[Bug]: Update progress echoes each step in one line per step

### ISSUE THREAD

**Issue by rscm** [flatpak/flatpak#5586]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

39.20231109.0

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak update -y`
2. Just watch the terminal

### Expected Behavior

The update process acted like before, with the progress bars filling up in place and refreshing without echoing one line per step.

### Actual Behavior

When the updates start downloading, you can see that for every step in the progress a line is get used to echo that progress

As an example:
```
Actualizando 1/19…
Actualizando 1/19…                        0%  0 bytes/s
Actualizando 1/19… ▊                      4%
Actualizando 1/19… ████████████████████ 100%
Actualizando 2/19…
Actualizando 2/19…                        0%  0 bytes/s
Actualizando 2/19… ▊                      4%
Actualizando 2/19… ████████████████████ 100%
Instalando 3/19…
Instalando 3/19…                        0%  0 bytes/s
Instalando 3/19… ███▊                  19%
Instalando 3/19… ███████████████▍      77%
Instalando 3/19… ████████████████████ 100%
Instalando 4/19…
Instalando 4/19…                        0%  0 bytes/s
Instalando 4/19… ██                    10%
Instalando 4/19… █████▏                26%
Instalando 4/19… █████▍                27%
Instalando 4/19… █████▊                29%  9,9 MB/s
Instalando 4/19… █████▊                29%  10,0 MB/s
Instalando 4/19… ██████▏               31%  10,7 MB/s
Instalando 4/19… ██████▌               33%  5,8 MB/s
Instalando 4/19… ███████               35%  6,3 MB/s
Instalando 4/19… ████████████████████ 100%  6,3 MB/s
Instalando 5/19…
Instalando 5/19…                        0%  0 bytes/s
Instalando 5/19… ██████▌               33%
Instalando 5/19… ████████████████████ 100%
```

### Additional Information

![Captura desde 2023-11-09 16-35-41](https://github.com/flatpak/flatpak/assets/6588120/43135fef-1a36-46fe-a4af-6b17afe4d19c)
![Captura desde 2023-11-09 16-35-55](https://github.com/flatpak/flatpak/assets/6588120/d4472296-976d-400e-90c1-e85ce54dbe34)

**Comment by chrisawi** [comment]
Flatpak is operating in "plain output" mode as if it's not outputting to a tty.

https://github.com/flatpak/flatpak/blob/main/app/flatpak-tty-utils.c#L45-L70

You don't have `FLATPAK_FANCY_OUTPUT=0` or `G_MESSAGES_DEBUG` set in your environment (`env`),  do you?

**Comment by rscm** [comment]
> Flatpak is operating in "plain output" mode as if it's not outputting to a tty.
> 
> https://github.com/flatpak/flatpak/blob/main/app/flatpak-tty-utils.c#L45-L70
> 
> You don't have `FLATPAK_FANCY_OUTPUT=0` or `G_MESSAGES_DEBUG` set in your environment (`env`), do you?

I do have `G_MESSAGES_DEBUG` but only defined to one app that I needed to debug
```
❯ cat /etc/environment 
G_MESSAGES_DEBUG=easyeffects
```
It is not set to `all`

```
❯ cat env.c 
#include <stdio.h>
#include <stdlib.h>

int main () {
   printf("G_MESSAGES_DEBUG : %s\n", getenv("G_MESSAGES_DEBUG"));

   return(0);
}
```
```
❯ ./env 
G_MESSAGES_DEBUG : easyeffects
```

from looking the code its clearly that you only check for it to exists/to be defined, and you don't check what is defined by it. (a space-separated list)

ref: https://docs.gtk.org/glib/running.html
```
G_MESSAGES_DEBUG
    A space-separated list of log domains for which informational and debug messages should be printed. By default, these messages are not printed. You can also use the special value all. This environment variable only affects the default log handler, g_log_default_handler().
```

I removed it, refreshed the variables and everything works fine with flatpak. That was it

**Comment by chrisawi** [comment]
Here's the original commit with the rationale for adding that check: 784bc5566db03310c766d13f9727d2fa106cd570

Flatpak uses multiple libraries with different log domains; it would be impractical to try to check if any of them have debug logging enabled.

I don't think `G_MESSAGES_DEBUG` was intended to be set globally. Specifying a log domain is useful when you only want to see debug logging from a specific component when debugging an app. I'd suggest putting it somewhere like easyeffects's D-Bus service file instead.

I'm provisionally closing this. If any of the flatpak developers disagree, they can reopen it.
