### ISSUE TITLE
[Feature request]: List running flatpaks of other users

### ISSUE THREAD

**Issue by devurandom** [flatpak/flatpak#5598]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

# What I would like

I am looking for a way to list running flatpaks of other users.

# What I tried to achieve this

`flatpak ps` shows me my own running flatpaks. `sudo flatpak ps` and `sudo -u $USER flatpak ps` (i.e. sudoing to my own user and listing running flatpaks) do not show anything.

**Comment by chrisawi** [comment]
That doesn't work because sudo doesn't set `XDG_RUNTIME_DIR`. I'd suggest using `machinectl shell -q ${USER}@ /usr/bin/flatpak ps` as an alternative.

I don't think there's anything Flatpak can do here.

**Comment by devurandom** [comment]
Thanks! That worked.

I wrote myself a little script:
```sh
#!/bin/bash

user="$1" ; shift
[[ "${user}" ]] || exit 1

exec machinectl shell --quiet "${user}"@ /usr/bin/flatpak ps
```
