### ISSUE TITLE
[Feature request]: Purpose: Game Status Portal 

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [flatpak/flatpak#5601]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Discord can't detect games running from Steam because a flatpak app process is isolated, is the same with Lutris or Bottles.

Purpose: A Flatpak Game Portal that can be a alternative, a client can give to portal frontend the game that are running,
and a other client can too view if a gaming are running.

If some thing look this can be developed will be great not just for Discord, but for others apps that can view if a game is running, it can be not just using for simple things like a status about playing but for optimizations in applications and system side, in this case reduce animations, reduce effects in application or Shell and in some cases the system can modify the Governor and Energy settings if game is detected

**Comment by Mikenux** [comment]
You can request portals to https://github.com/flatpak/xdg-desktop-portal/discussions > New Discussion > New Portals. Direct link: https://github.com/flatpak/xdg-desktop-portal/discussions/new?category=new-portals

For getting window names (any, not only games), there is already suggestions to use an accessibility API (which I think is in the works).

> but for optimizations in applications and system side, in this case reduce animations, reduce effects in application or Shell and in some cases the system can modify the Governor and Energy settings if game is detected

There is already the GameMode portal which allow apps to request to activate game mode.

> reduce effects in application

Which effects? UI effects? Pausing any active video or animation?

**Comment by smcv** [comment]
I see you have opened https://github.com/flatpak/xdg-desktop-portal/discussions/1222.

Flatpak does not generally provide portals itself: if a portal is needed for Flatpak, then it's usually equally needed for Snap or other, future app frameworks. (The only exception to this is `flatpak-portal`, which is to do with Flatpak containers specifically, and would not be useful for Snap or other frameworks.) So this feature request will not be provided by a change to flatpak: if it's implemented, then it should be in xdg-desktop-portal instead.
