### ISSUE TITLE
[Bug]: net.epson.epsonscan2 cannot find scanner connected via USB

### ISSUE THREAD

**Issue by markman8** [flatpak/flatpak#5603]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

openSUSE

### Linux distribution version

Tumbleweed

### What architecture are you using?

x86_64

### How to reproduce

1. flatpak run net.epson.epsonscan2
2. The window for selecting the scanner appears yet cannot detect the EPSON Perfection 4490 PHOTO scanner that is connected via USB on the laptop.
3. Running scanimage -L finds the same scanner and outputs: device `epkowa:interpreter:002:005’ is a Epson Perfection 4490 flatbed scanner

### Expected Behavior

I expected by the time the proprietary drivers for EPSON for linux are already installed on the system and as scanimage -L and iscan program runs and scans images with the same set up that the flatpak run net.epson.epsonscan2 program should detect the scanner at least...

### Actual Behavior

The application runs yet it does not detect the scanner.

### Additional Information

```
markman8@pc-57:~> lsusb
Bus 001 Device 002: ID 8087:8001 Intel Corp. Integrated Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 004: ID 8087:0a2a Intel Corp. Bluetooth wireless interface
Bus 002 Device 003: ID 138a:0017 Validity Sensors, Inc. VFS 5011 fingerprint sensor
Bus 002 Device 002: ID 04f3:012d Elan Microelectronics Corp. Touchscreen
Bus 002 Device 005: ID 04b8:0119 Seiko Epson Corp. GT-X750 [Perfection 4490 Photo]
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
markman8@pc-57:~> flatpak run net.
net.displaycal.DisplayCAL net.epson.epsonscan2 net.sourceforge.qtpfsgui.LuminanceHDR
markman8@pc-57:~> flatpak run net.epson.epsonscan2
Qt: Session management error: Could not open network socket
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
markman8@pc-57:~> flatpak run net.epson.epsonscan2 -l
Device is not found…

markman8@pc-57:~> scanimage -L
device `epkowa:interpreter:002:005’ is a Epson Perfection 4490 flatbed scanner
markman8@pc-57:~>
```

**Comment by hfiguiere** [comment]
if only you filed that with the flathub package instead the maintainer may have seen it.

**Comment by hfiguiere** [comment]
and I meant there: https://github.com/flathub/net.epson.epsonscan2/issues

**Comment by markman8** [comment]
Hello @hfiguiere 
could you be more specific about the problem you faced in this Bug thread?  I specified that net.epson.epsonscan2 is the package that has the problem.  What exactly do you nedd?

**Comment by hfiguiere** [comment]
That the place to report the problem is there: 

https://github.com/flathub/net.epson.epsonscan2/issues

*hint* I'd have seen it when it was file instead of just now.
