### ISSUE TITLE
[Bug]: After updating nvidia runtime I have to restart the computer

### ISSUE THREAD

**Issue by Svenum** [flatpak/flatpak#5616]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

NixOS

### Linux distribution version

NixOS 24.05 (Uakari)

### What architecture are you using?

x86_64

### How to reproduce

1. Update nvidia runtime
2. Start an game with Steam or Lutris that uses the runtime.
3. Enjoy the 5 FPS

### Expected Behavior

The Game should run smothly as ever.

### Actual Behavior

The game runs at very low fps.

### Additional Information

To resolve this issue I have to restart the hole PC. Restating the game/launcher (like steam or lutris) does not work.

**Comment by smcv** [comment]
The user-space driver and the kernel driver need to be of a matching version, and switching to a new kernel driver version requires a reboot. This is a limitation of the proprietary Nvidia driver, and Flatpak cannot solve limitations of code outside our control, so this issue is likely to have to be "won't fix" (or more accurately "can't fix").

> Update nvidia runtime

What exact steps does this involve? What Flatpak runtimes, what host OS libraries and what kernel modules were changed by this operation?

**Comment by Svenum** [comment]
The only thing I do is 
`flatpak update`

**Comment by chrisawi** [comment]
When this happens, please compare the nvidia version in `flatpak --gl-drivers` to the driver version in `nvidia-smi`. Also confirm that `org.freedesktop.Platform.GL.nvidia-VERSION` is installed, using something like `flatpak list --runtime | grep nvidia`

The output of the guilty `flatpak update` command (or the relevant excerpt from `flatpak history`) could also be helpful.

**Comment by Svenum** [comment]
Never happend again.... I close the Issue and reopen if needed
