### ISSUE TITLE
[Feature request]: Add lua sdk support

### ISSUE THREAD

**Issue by 00pandora00** [flatpak/flatpak#5622]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

hi, first of all, i don’t know if this is the place to put this request. if this is not the place to put this issue, please help me to find the correct place.

said the above, there are any plans to add lua sdk ? (the same way rust sdk is implemented)

why i ask for this?
some programs (vstudiocode, vscodium) need that sdk, and i think that allowing them get it from the system (if that is possible) Detroit the idea of flatpak a little (the sandbox part)

**Comment by nanonyme** [comment]
Is this a request for creation of new Sdk extension? If so, probably wrong issue tracker, eg Rust Sdk extension lives in Flathub.

**Comment by 00pandora00** [comment]
> Is this a request for creation of new Sdk extension? If so, probably wrong issue tracker, eg Rust Sdk extension lives in Flathub.

yes, if a request for  creation of new Sdk extension (lua is not in flatpak)

I posted this request here since I didn't know if I should post it here or in flatpak discussions.

note: I also opened an order in flatpak discussions:
https://discourse.flathub.org/t/add-lua-sdk-support/5641

**Comment by nurupo** [comment]
Flatpak is not Flathub. Flatpak is the technology, Flathub is just a popular Flatpak repository. Flatpak has nothing to do with SDKs. Flathub is the one that hosts SDKs and such.

Flathub is this way -> https://github.com/flathub/flathub

**Comment by smcv** [comment]
Yes, this isn't an actionable request for Flatpak. Flathub would be the place to ask for new SDKs.

**Comment by 00pandora00** [comment]
> Flatpak is not Flathub. Flatpak is the technology, Flathub is just a popular Flatpak repository. Flatpak has nothing to do with SDKs. Flathub is the one that hosts SDKs and such.
> 
> Flathub is this way -> https://github.com/flathub/flathub

OK i will make my request there

**Comment by 00pandora00** [comment]
new request here: https://github.com/flathub/flathub/issues/4940
