### ISSUE TITLE
[Feature request]: Clearer "No matches" when searching

### ISSUE THREAD

**Issue by razzeee** [flatpak/flatpak#5628]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I'm not 100% sure how to best tackle this, but there have been more and more users asking/wondering why they can't install specific flatpaks.

Mostly due to different arches, so it seems a bit nontransparent.

For the search path, we could for e.g. change https://github.com/flatpak/flatpak/blob/65bc369a9f7851cc1344d2a767b308050cd66fe3/app/flatpak-builtins-search.c#L338 `No matches found` to something like `No matches for architecture found` - which unfortunately increases the technicality of the message.

**Comment by JakobDev** [comment]
It would be even better, if Flatpak can tell if a App exists, but it's not available for the current architecture.

**Comment by hfiguiere** [comment]
See #5474
