### ISSUE TITLE
Add webkitgtk to GNOME runtime/sdk

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#563]
Currently, the GNOME runtime only has webkitgtk4. GTK+2 applications still depends on webkitgtk, based on the 2.4 branch.

This is the case for GIMP and every time flatpak considers that the cache version is a miss for some reason, it will rebuild, and it takes like half a day on the computer I build flatpak on (whereas all the other dependencies + GIMP, all together, must just take like what… 2 hours? Maybe even less). This is very counter-productive so I would like to propose to have webkitgtk installed in GNOME runtime.
Would it be OK?

The GNOME runtime repository is hosted by GNOME but there seem to be no project on the bugzilla, and you don't host any mirror on github either. What is the expected procedure to propose a patch for the GNOME runtime/sdk?

Anyway patch attached (added a `.txt` so that github accepts it. Crazy that it won't even allow patch files by default!)
[0001-Adding-webkitgtk-2.4.-branch-to-the-platform.patch.txt](https://github.com/flatpak/flatpak/files/772427/0001-Adding-webkitgtk-2.4.-branch-to-the-platform.patch.txt)

**Comment by TingPing** [comment]
The old version of webkit gtk is not maintained and full of known security vulnerabilities. No distribution should ship it:  https://blogs.gnome.org/mcatanzaro/2017/02/08/an-update-on-webkit-security-updates/

**Comment by Jehan** [comment]
I thought that would be the answer. And I basically agree with the arguments and conclusion, but for the fact that we still have this dependency and it won't disappear for GIMP 2.10.

Also a lot of distribution still ship it (at least Fedora/Debian/Ubuntu do).

But if you won't change your mind (which I understand, your arguments are right, as I said), I guess it would mean GIMP flatpak will have to ship it itself then. :-/

**Comment by TingPing** [comment]
For what its worth I am not the one to make the decision, just wanted to mention the security concerns.

**Comment by alexlarsson** [comment]
Yeah, that is exactly the reason why it is not in there...
