### ISSUE TITLE
[Bug]: --user install doesn't work from command line

### ISSUE THREAD

**Issue by tripleo1** [flatpak/flatpak#5636]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

23.04

### What architecture are you using?

x86_64

### How to reproduce

This is OK:

```
flatpak install flathub org.kde.haruna
Looking for matches…
Required runtime for org.kde.haruna/x86_64/stable (runtime/org.kde.Platform/x86_64/5.15-22.08) found in remote flathub
Do you want to install it? [Y/n]:
```

This is NOT:
```
flatpak install --user flathub org.kde.haruna
flatpak install flathub --user org.kde.haruna
flatpak --user install flathub org.kde.haruna
```

### Expected Behavior

Should accept `--user` flag

### Actual Behavior

Fails with:

```
Looking for matches…
error: No remote refs found for ‘flathub’
```

**Comment by chrisawi** [comment]
Remotes are per installation. You need to separately add flathub to the user installation.

Unless you've already done that (`flatpak remote-add --user flathub ...`), this is the expected behavior.

**Comment by tripleo1** [comment]
> Unless you've already done that (`flatpak remote-add --user flathub ...`), this is the expected behavior.

Is this documented somewhere? Not trying to create work for you, trying to create less surprise for me.

Feel free to close...

**Comment by rusty-snake** [comment]
> Unless overridden with the --user or --installation options, this command changes the default system-wide installation.

https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-remote-add

**Comment by tripleo1** [comment]
I'll fix the world later

thx
