### ISSUE TITLE
add a way to forward to a different repo

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#565]
The concrete use case is that I want to take over hosting the flatpak repo for recipes, so I don't have to bother Alex every time for an update. People who have already installed the flatpak from alex' repo should be informed that newer updates can be found in my repository.

**Comment by jscurtu** [comment]
That would be neat indeed.. for future decisions though, you could use a domain and add a CNAME entry that points to the real domain / repo. Later you would just have to adjust the CNAME record to the new server .

**Comment by matthiasclasen** [comment]
this is covered now by eol markers, I believe
