### ISSUE TITLE
[Bug]:       Error reading from file: Bad address                                                

### ISSUE THREAD

**Issue by WizardOfWor1969** [flatpak/flatpak#5652]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Debian

### Linux distribution version

6.1.69-1 

### What architecture are you using?

x86_64

### How to reproduce

1. Requires Nvidia drivers 
2. flatpak update --appstream && flatpak update -y

### Expected Behavior

To install nvidia-545-23-08

### Actual Behavior

Download does complete (4.4GB / 4.4 B) but get the following error:
Warning: Error pulling from repo: Error reading from file: Bad address

**Comment by TsunamiMommy** [comment]
I can confirm this issue under Ubuntu 22.04. Seems to be an issue with the runtime itself or Flatpak version 1.14.4. Been needing this runtime for the last couple of days and the update is broken. I have a feeling that it is related to it being a cuda-driver version only. Also, this update is rather large compared to typical runtime updates.

**Comment by Quantumdit** [comment]
Same issue under (virtualized) Fedora 38 with Flatpak version 1.15.4.

**Comment by zietbukuel** [comment]
I'm having the same issue on RHEL9 using Flatpak 1.12.8. It's not able to install org.freedesktop.Platform.GL.nvidia-545-23-08 and I keep downloading the same package over and over (it's a 4.4gb package!).

**Comment by jerobarraco** [comment]
I have the same problem in KDE Ubuntu 22.04.3 LTS, with KDE backports.
I have the same problem as zietbukuel the packages are also 4.4gb

![image](https://github.com/flatpak/flatpak/assets/3729895/3ac72f3e-d223-465b-a358-07a10925bb1f)

![image](https://github.com/flatpak/flatpak/assets/3729895/95e2a5d8-2b2d-4133-ad62-54b8769887ad)


given the size of the image i wonder if there's a problem with the code that counts how many bytes have been written and just overflows (e.g. 32 bits).
also a 4.4 gb update is ridiculous.

**Comment by FedericoCarboni** [comment]
Can confirm on debian 12 with nvidia drivers and cuda installed

**Comment by aborealis** [comment]
The same on Debian 12.

The Nvidia drivers of the last version are installed (not via flatpack)

nvidia-smi                                                                                                                            [0:52:18]
Thu Jan 18 00:52:18 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+


And still, flatpak suggests updates that fail:

> flatpak update:                                                                                                                 
1. [✗] org.freedesktop.Platform.GL.nvidia-545-23-08           1.4              i            flathub                         4,4 Gb / 4,4 Gb

**Comment by jerobarraco** [comment]
ok, so something weird happened today.
in the last days i usually got only 2 nvidia packages version to update. but sometimes i get like 10. so i decided to update one by one (manually unticking them) and starting from the oldest. i thought maybe there was a dependency issue.
i managed to install 2 and then decided to try installing them all. and it worked.
i was using discover with flatpak backend on kde ubuntu 22 lts with kde backports.

**Comment by WizardOfWor1969** [comment]
Seems to work now for me.
