### ISSUE TITLE
Error: Wrong size for extra data

### ISSUE THREAD

**Issue by ClodoaldoPinto** [flatpak/flatpak#5655]
Flatpak version 1.15.6

Fedora Linux 39

x86_64

```
# flatpak install com.google.EarthPro
Looking for matches…

com.google.EarthPro permissions:
    ipc                   network      pulseaudio      x11      dri      file access [1]
    dbus access [2]

    [1] xdg-download
    [2] org.freedesktop.Notifications


        ID                           Branch          Op         Remote          Download
 1. [✗] com.google.EarthPro          stable          i          flathub         57.8 MB / 58.7 MB

Error: Wrong size for extra data https://dl.google.com/dl/linux/direct/google-earth-pro-stable_7.3.6_amd64.deb
error: Failed to install com.google.EarthPro: Wrong size for extra data https://dl.google.com/dl/linux/direct/google-earth-pro-stable_7.3.6_amd64.deb
```

**Comment by flexagoon** [comment]
This issue should be reported at https://github.com/flathub/com.google.EarthPro

Also, I tried downloading the file, and the size seems to be correct. I'm also able to install the app just fine. Maybe it was an issue with your network connection? Have you tried installing the app again?

**Comment by smcv** [comment]
> This issue should be reported at https://github.com/flathub/com.google.EarthPro

Yes. If an app's manifest tells Flatpak "download a file from `https://whatever`, the size should be 1234567 bytes, the content should have hash xyz", but when Flatpak downloads the file it finds that it has an unexpected size or content, there is unlikely to be anything that Flatpak can do to resolve that.
