### ISSUE TITLE
flatpak complains when installing corebird from github

### ISSUE THREAD

**Issue by marcosps** [flatpak/flatpak#566]
Currently the flatpak file of corebird is in HTML, so install command complains about it.

if we change:
https://github.com/baedert/corebird-flatpak/blob/master/org.baedert.corebird.flatpakref

to the raw format of the file:
https://raw.githubusercontent.com/baedert/corebird-flatpak/master/org.baedert.corebird.flatpakref

it fixes the problem.

**Comment by alexlarsson** [comment]
I don't understand. Did you try to install something like: 
```
flatpak install https://github.com/baedert/corebird-flatpak/blob/master/org.baedert.corebird.flatpakref
```
Then yeah, that obviously won't work, but that is hardly a flatpak bug. You need to either use the full raw link, or even better, put the flatpakref somewhere on the same server as the repo itself so the link is shorter.

**Comment by marcosps** [comment]
Sorry @alexlarsson , I wasn't clear. These instructions are in the flatpak page[1], so more users will hit the same problem when trying to see the magic of flatpak, and they may be frustrated because the link is wrong in the website!

I don't know if this is the right place to report a problem about the site, and if it isn't, please tell me a better place to report the problem. Thanks!
[1] http://flatpak.org/apps.html

**Comment by alexlarsson** [comment]
Fixed here:
https://github.com/flatpak/flatpak.github.io/commit/4aed76fdf04d8537955acb4a88d86a158ad19e1e

**Comment by marcosps** [comment]
Great, thanks!
