### ISSUE TITLE
[Feature request]: Easily change an app name and linking it to the same package

### ISSUE THREAD

**Issue by firefoxlover** [flatpak/flatpak#5663]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

It is really annoying to have apps use the names they had years ago as package names

Example: im.riot.Riot

probably more. Not even talking about GNOME apps here, which are totally confusing and always different from the displayed name.

Would it be possible to
- keep the installed apps with the same name, to still get all the updates (a TUI could warn users but a GUI would have problems)
   - and then have the app appear normally with its new name, so that new installs all use the new one
   - the app install directory etc only change if it is newly installed, existing apps never change and the old version is then basically just a symlink in the repo
   - so: already installed: nothing changes but their updates are actually just renamed versions of thew new version
   - newly installed can just change the name, as they dont depend on updates
- OR rebase the app somehow to the new name?

This may be a minor issue, but with the current implementation apps can NEVER change their name. They will keep the old name forever, as there will never be the point where nobody has them installed, and deprecating it from the repo would be unproblematic.

**Comment by chrisawi** [comment]
There is already a mechanism for apps to migrate to a new app ID: eol-rebase. The Element flatpak just hasn't used it: https://github.com/flathub/im.riot.Riot/issues/221

**Comment by smcv** [comment]
> There is already a mechanism for apps to migrate to a new app ID: eol-rebase

Yes. If an app isn't using this mechanism but should be, please talk to that app's maintainers.
