### ISSUE TITLE
[Bug]: script failed, exit status 256

### ISSUE THREAD

**Issue by B3rtm3n** [flatpak/flatpak#5666]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

flatpak-1.12.8-1.el19.x86_64

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Oracle Linux (UEK) 9.3

### What architecture are you using?

x86_64

### How to reproduce

Install Oracle Linux 9.3 with secure configuration ANSSI-BP-028 (enhanced).
All partitions including swap encrypted with Luks2 except the boot partition.

### Expected Behavior

Installing and opening the apps Flatpak without any problem.

### Actual Behavior

Flatpak refuses to install org.freedesktop.Platform.openh264 but it does install the other needed files.
None of the other apps are working as well.

f.ex. LibreOffice

[root@localhost admin]# flatpak install libreoffice
Looking for matches…
Similar refs found for ‘libreoffice’ in remote ‘flathub’ (system):

   1) app/org.libreoffice.LibreOffice/x86_64/stable
   2) runtime/org.libreoffice.LibreOffice.Help/x86_64/stable
   3) runtime/org.libreoffice.LibreOffice.BundledExtension.Voikko/x86_64/stable

Which do you want to use (0 to abort)? [0-3]: 1

org.libreoffice.LibreOffice permissions:
    ipc                   network               fallback-x11            pulseaudio       wayland       x11      dri
    file access [1]       dbus access [2]       bus ownership [3]

   .  [1] host, xdg-config/fontconfig:ro, xdg-config/gtk-3.0, xdg-run/gvfsd
   . [2] com.canonical.AppMenu.Registrar, org.gtk.vfs.*
   . [3] org.libreoffice.LibreOfficeIpc0

  .      ID                                                                             Branch           Op           Remote            Download
  .      ID                                                                             Branch           Op           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264             2.2.0              i               flathub           614.6 kB / 944.3 kB
 2. [✓] org.libreoffice.LibreOffice.Locale                   stable            i               flathub             1.4 MB / 83.0 MB
 3. [✓] org.libreoffice.LibreOffice                               stable            i               flathub           294.0 MB / 315.7 MB
 
Warning: While trying to apply extra data: apply_extra script failed, exit status 256
Installation complete.

### Additional Information

I tried this on 2 different hardware systems with the same result.
I reinstalled Oracle Linux but with no secure configuration enabled and with auto configuration (1 partition encrypted with Luks2) and Flatpak works again without any problem.

**Comment by smcv** [comment]
> Flatpak refuses to install org.freedesktop.Platform.openh264

Please report this as a bug in that extension. I believe its issue tracking is at <https://gitlab.com/freedesktop-sdk/openh264-extension/-/issues/>.

Flatpak itself does not have any information beyond this:

* the extension contains a script used to set up codec stuff that had to be downloaded out-of-band for legal reasons (an "apply_extra script");
* but that script failed with exit status 1 ("wait status" 256)

There doesn't seem to have been any output from the script itself, which is likely to make this very difficult to diagnose.

> with secure configuration ANSSI-BP-028 (enhanced)

I don't know what this is specifically, but if it uses a Linux kernel security module like SELinux or AppArmor for hardening, you might find useful information in the system log (syslog or systemd Journal) or the auditd log.
