### ISSUE TITLE
[Bug]: Guillemets (»«) in French and German keyboard layout not working in Wayland

### ISSUE THREAD

**Issue by Namoria** [flatpak/flatpak#5667]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

39.20240124.0 (Silverblue)

### What architecture are you using?

x86_64

### How to reproduce

1. In _GNOME Settings,_ go to _Keyboard_ > _Output Sources_ > and add _French_ (`fr`) and _German_ (`de`) if you haven’t already.
2. Switch your keyboard layout accordingly (in top right of the screen in vanilla GNOME). Let’s use the German (`de`) input layout in the following example.
3. In _GNOME settings_ > _Keyboard_, click on the three dots next to _German_ or _French_ and _View Keyboard Layout_. Look up the input for the guillemets (these are guillemets: » «). Since we are using _German_ (`de`) as example: On German or US keyboards, using the German input layout, write, as defined by the keyboard layout, guillemets by pressing right (!) `Alt Gr` and `Y` or right (!) `Alt Gr` + `X`: »«. You can do this in any application that is not a Flatpak (and also in some Flatpak applications, see below). 
4. In some Flatpak applications the guillemets will work, e.g. Geany, Typora, or Flatseal. In other Flatpak applications, however, the input for guillemets will be ignored, e.g. Mozilla Firefox, Mozilla Thunderbird, Deluge, gThumb, LibreOffice Writer.
5. Using the X11 window manager solves the problem. However, in some Flatpak applications using Wayland, the guillemets input _does_ work, e.g. Geany.
6. In regular, non-Flatpak versions of Mozilla Firefox, etc. (see above), provided by Fedora Package Sources or the Arch repository, the guillemets input _does_ always work..
7. Pressing the compose key (usually right `Meta/Super`) and tapping `>` two times will always work to write guillemets. So this is an issue with the specific keyboard layouts. 
8. Maybe more keyboard layouts are affected, I only tested _French_ and _German_.

### Expected Behavior

The guillemets shortcuts, as defined by the selected keyboard layout, should work in _every_ Flatpak app using Wayland, including LibreOffice Writer, Mozilla Firefox and Mozilla Thunderbird; and not only in _some_ applications using Wayland.

### Actual Behavior

The guillemets shortcuts, as defined by the selected keyboard layout, do not work in certain Flatpak apps using Wayland, e.g. LibreOffice Writer, Mozilla Firefox and Mozilla Thunderbird.

### Additional Information

This behavior I can attest in Fedora Workstation, Fedora Silverblue, Arch Linux, and OpenSUSE Tumbleweed. I checked in with a friend and the unexpected behavior was reproducible.

Similar issue: https://github.com/flatpak/flatpak/issues/5585

**Comment by chrisawi** [comment]
This is definitely the same issue as #5585. That one has a link to https://github.com/xkbcommon/libxkbcommon/issues/435 where the problem has been isolated. It's caused by an xorgproto change synced into libxkbcommon 1.6 that is incompatible with libxkbcommon 1.5 in the flatpak runtime.

I don't think there's anything flatpak itself can do here. And updating the runtime to 1.6 seems not to be an option due to their ABI policy: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/15535

**Comment by chrisawi** [comment]
> Could you elaborate? There is only one comment by your link, mentioning 6 added functions. Does that really break the ABI? Nothing is removed nor changed in an incompatible way. Also, where is that policy mentioned?

It's counter-intuitive, but added symbols can cause breakage if something is built against them and then run against an older version of the runtime (in the same branch). I don't know of anywhere where the policy is clearly stated, but [CONTRIBUTING.md](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/CONTRIBUTING.md) says:
> Additionally it will check for ABI changes. Crypto components may break forward ABI (not backward ABI) compatibility for security updates on a stable branch

That implies that non-security updates cannot break forward compatibility by adding symbols.

> Does it also mean flatpak is forever stuck with libxkbcommon 1.5? If so, that sounds like a huge design flaw (inability to upgrade libraries to fix bugs and vulnerabilities).

That MR is specifically for merging into the stable 23.08 branch. The next release (24.08) will have it included.

**Comment by chrisawi** [comment]
Duplicate of #5585
