### ISSUE TITLE
[Bug]: Y/N propts seem not translated

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#5669]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

39

### What architecture are you using?

x86_64

### How to reproduce

Just try to install any app in a localized Flatpak.

```
flatpak install io.posidon.Paper
```

> Eşleşmeler aranıyor…
> io.posidon.Paper/x86_64/stable (runtime/org.gnome.Platform/x86_64/43) için gerekli çalışma ortamı flathub uzağında bulundu
> Kurmak istiyor musunuz? [Y/n]:

### Expected Behavior

> ....
> Kurmak istiyor musunuz? [E/h]:

### Actual Behavior

>...
> Kurmak istiyor musunuz? [Y/n]:

### Additional Information

When I install a program via DNF, I can respond to the prompt with the letters E/H, which are the abbreviations for the Turkish translation of 'Yes/No' (Evet/Hayır).

However, when I install with Flatpak, it seems I need to use Y/N letters, which stand for Yes/No. This is different from other package managers.

```
sudo dnf install kate
```

![resim](https://github.com/flatpak/flatpak/assets/6218679/484dbb6e-bcd9-44b3-bfd5-773f7ce369d3)

```
flatpak install io.posidon.Paper 
```

![resim](https://github.com/flatpak/flatpak/assets/6218679/d2dc2be7-91ea-4800-b86a-46dc8e39a54d)

Related to flatpak_yes_no_prompt method: https://github.com/flatpak/flatpak/blob/main/app/flatpak-tty-utils.c#L159-L197

**Comment by chrisawi** [comment]
This is https://github.com/flatpak/flatpak/issues/2277

dnf just [translates the strings](https://github.com/rpm-software-management/dnf/blob/master/dnf/cli/output.py#L642), also allowing y/n when they don't conflict. A similar approach is probably reasonable.

It would be interesting to see how other package managers (etc.) do it.

**Comment by chrisawi** [comment]
Duplicate of #2277
