### ISSUE TITLE
Making flatpak capable of oneclick install, even if remote is completely unknown

### ISSUE THREAD

**Issue by adityashah1212** [flatpak/flatpak#567]
I am pretty sure the title is messy, and this might be a little early for what I am trying to propose but here it goes. I don't like what canonical is doing with snaps (obviously), but I see one important pro in having a single repo, that being user doesn't have to go searching for the remote to install the app. What I can think of to solve this is to have a remote database listing available remotes, applications/runtimes on that remote and a name for the remote. This database, I think can be maintained by each distro (perhaps if someone is willing to donate a server then even on that server). flatpak when told to install a app/runtime, it will search for it in the available remotes, if not available then search in the remote database, get the actual remote location of application, add it to its remote list and then install from there. This way we can have a more cross distro application deployment system without having to have a single centralized repo as in case of canonical's snaps.

**Comment by TingPing** [comment]
Flatpakref files can now list the repo that contains the runtime they depend upon which effectively solves that problem. I think gnome-software currently has an issue with supporting this though.

**Comment by adityashah1212** [comment]
I think I miss-conveyed what I was trying to say, yes flatpakref have link to the runtime, but I still need to go hunting for that flatpakref. What I think is that we can have a second layer of remote server storing only the information about these flatpakrefs, thus the user doesn't have to search for libreoffice.flatpakref for example, all he has to do is lets say, something like

flatpak search <remote-db> 'libreoffice'

to get the flatpakref and hence the libreoffice itself. This <remote-db> can be maintained by the distributions themselves, the developers don't have to worry about them.

**Comment by alexlarsson** [comment]
What you want is a centralized system with a single store. That is not what flatpak is, by design. We plan to make a flatpak store that will have official builds of most upstream releases, but that is work in progress. Once that is done, if you add that then everything should just appear in nicely in your UI app installer ( like gnome-software). We've got some way to go before then though.

**Comment by adityashah1212** [comment]
Yeah, I thought it might be too early. But in any case looking forward to it

**Comment by matthiasclasen** [comment]
flathub exists now
