### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by eduardomozart** [flatpak/flatpak#5672]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.7

### What Linux distribution are you using?

Debian

### Linux distribution version

Deepin 20.9

### What architecture are you using?

x86_64

### How to reproduce

1. Install Remote Desktop Manager (2023.3.1.7) through Flathub.
2. Open Remote Desktop Manager on menu.
3. It creates a second item on Dock and the program icon isn't shown on Dock.

### Expected Behavior

In this case, I believe that when executing binaries, there's no way to append icons for it, so Flatpak should use the same icon of the main Desktop file used to run the program.

### Actual Behavior

When docking the program or running it through menu, it works as expected, but no icon is shown on Dock.

### Additional Information

I have to edit the file ``~/.config/dock/scratch`` manually and replace the ``Icon`` parameter of the docked Desktop file to ``net.devolutions.RDM``. I also needed to edit the corresponding SH file on same folder to run ``dex /var/lib/flatpak/exports/share/applications/net.devolutions.RDM.desktop``, so now when running the program through menu or dock, no second icon is shown on dock.

**Comment by TingPing** [comment]
Report this against the specific applications package.
