### ISSUE TITLE
Shell redirections for Flatpak apps?

### ISSUE THREAD

**Issue by korpe1** [flatpak/flatpak#5678]
How can I use shell redirections for Flatpak apps? For example, `echo "test" | flatpak run com.visualstudio.code -`? With that command Visual Studio Code read stdin, but since Bash does the plumbing works in the host it doesn't get them into the sandbox.

Flatpak is for CLI and GUI apps. There is already many CLI apps and support for redirections is a must have feature.

**Comment by rusty-snake** [comment]
std-streams get inherited by the sandbox:

```console
$ echo hello | flatpak run --command=cat org.gnome.Platform//45
hello
```

**Comment by korpe1** [comment]
****

> std-streams get inherited by the sandbox:
> 
> ```
> $ echo hello | flatpak run --command=cat org.gnome.Platform//45
> hello
> ```

I can confirm that. So, why VSCode doesn't work?

**Comment by chrisawi** [comment]
The VSCode flatpak uses a [wrapper script](https://github.com/flathub/com.visualstudio.code/blob/master/code.sh). Any change in behavior is likely due to that. You can open an issue in that repo.

**Comment by chrisawi** [comment]
Closing as this doesn't seem to be a flatpak issue. Please open an issue against the VSCode flatpak: https://github.com/flathub/com.visualstudio.code/issues
