### ISSUE TITLE
flatpak-builder dependency resolution and caching is unpredictable

### ISSUE THREAD

**Issue by matze** [flatpak/flatpak#568]
I'm building a flatpak for Inkscape which has several dependencies and build times are getting out of hand partly due to `flatpak-builder`'s inability to specify proper dependencies and tendency to invalidate its cache entries for no particular reasons. For example, I just added another `post-install` command to the last module, yet, almost all other modules are rebuilt.

**Comment by alexlarsson** [comment]
In general flatpak-builder doesn't do dependencies in that way. Its just a ordered build, and everything after the changed thing gets rebuilt. However, it stores the exact build id of the sdk in the cache, so things get rebuilt if the sdk isupdated, which tends to happen now and then.

I agree that this is a bit overkill, as sdk:s are supposed to be ABI stable (unless you're building against a git-master sdk build). So, in flatpak master I've changed this to not take the sdk into account for the cache unless you specify --rebuild-on-sdk-change.

**Comment by alexlarsson** [comment]
If the sdk *didn't* change and it still rebuilt everything when you just changed the last module, that would be a bug, and we need to look into that.

**Comment by matze** [comment]
>  so things get rebuilt if the sdk isupdated, which tends to happen now and then.

I see and will have a closer look next. But anyway, I'll try flatpak master for the next builds. Thanks!

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#19
