### ISSUE TITLE
[Bug]: fusermount used unconditionally of fuse3 or fuse2 used

### ISSUE THREAD

**Issue by pabloyoyoista** [flatpak/flatpak#5694]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

main branch

### What Linux distribution are you using?

Alpine Linux

### Linux distribution version

inux alpine-edge 6.6.15-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Thu, 01 Feb 2024 17:07:32 +0000 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Build flatpak with fuse3 dependency
2. See lots of tests fail with missing fusermount

### Expected Behavior

When compiling against fuse3, flatpak checks for fusermount3 instead of fusermount. According to libfuse 3.0.0 [release notes](https://github.com/libfuse/libfuse/releases/tag/fuse-3.0.0): "The fusermount and mount.fuse binaries have been renamed to fusermount3 and mount.fuse3 to allow co-installation of libfuse 2.x and 3.x". I guess other distros probably install a default symlink, but I guess it cannot really be expected?

### Actual Behavior

Lots of tests fail with missing fusermount

### Additional Information

I'm mostly wondering if a patch to fix this would be accepted. I had to write it to test locally anyway.

**Comment by smcv** [comment]
> I'm mostly wondering if a patch to fix this would be accepted

I'd certainly consider it!

We have had other issues where a copy of fusermount or fusermount3 in the PATH from non-distro-provided sources like Linuxbrew has overridden and broken the system copy, so probably the best way would be to add a build-time option `fusermount` which can be set with `meson setup -Dfusermount=/usr/bin/fusermount3` or `meson setup -Dfusermount=fusermount` or similar. To solve your issue, it could default to the empty string, which could be special-cased to select either `fusermount` or `fusermount3` depending on FUSE version?

**Comment by smcv** [comment]
> other issues where a copy of fusermount or fusermount3 in the PATH from non-distro-provided sources like Linuxbrew has overridden and broken the system copy

#5104

**Comment by pabloyoyoista** [comment]
> select either fusermount or fusermount3 depending on FUSE version?

That's what I had in my mind, yes :)

> the best way would be to add a build-time option 

This wouldn't be hard to implement, but are you really sure you want *another* build-time option? I was transitioning alpine's build to meson and I was quite overwhelmed by the sheer amount of options already available.

**Comment by smcv** [comment]
> are you really sure you want _another_ build-time option?

I think so. Or at least, I don't see any other way to accommodate both "search the PATH for the correct `fusermount`" (our historical behaviour, which is robust against distributions randomly moving things around without needing to recompile Flatpak) and "I know that in this distro, the correct `fusermount` is `/usr/bin/fusermount` and I'm willing to hard-code that" (which is the only way I can see to avoid accidentally picking up an incompatible `~/.local/bin/fusermount` or similar, causing #5104).
