### ISSUE TITLE
[Bug]: Developer name is listed instead of app name in "flatpak list"

### ISSUE THREAD

**Issue by kparal** [flatpak/flatpak#5700]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

39

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak list --app`
2. Look at the Name column
3. Apps which have `<developer><name>FOO</name></developer>` tag ([documentation](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer)) in their manifest display **FOO** as the app name, instead of the actual app name

### Expected Behavior

App name should be displayed correctly in `flatpak list`

### Actual Behavior

Developer name is displayed instead of the app name.

### Additional Information

Here's a trimmed example of selected apps installed from Flathub:
```
$ flatpak list --app
Name                    Application ID                      Version           Branch    Origin         Installation
Janne Pulkkinen         com.github.Matoking.protontricks    1.11.1            stable    flathub        system
Xournalpp Developers    com.github.xournalpp.xournalpp      1.2.2             stable    flathub        system
Bottles Contributors    com.usebottles.bottles              51.11             stable    flathub        system
Zenju                   org.freefilesync.FreeFileSync       13.4              beta      flathub-beta   system
```
As you can see, the **Name** column displays the [developer name](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer) instead of the app name.

**Comment by chrisawi** [comment]
The incorrect name is getting into the deploy data. It looks like the parser in flatpak takes any `<name>` element, so the new `<developer><name>` syntax is confusing it.

https://github.com/flatpak/flatpak/blob/main/common/flatpak-appdata.c#L122

**Comment by geraldosimiao** [comment]
yeah, I'm seeing this too, even on the info output:

```
flatpak info org.telegram.desktop

John Preston - Fast. Secure. Powerful.

        ID: org.telegram.desktop
       Ref: app/org.telegram.desktop/x86_64/stable
      Arq.: x86_64
      Ramo: stable
    Versão: 4.15
   Licença: GPL-3.0
    Origem: flathub
   Coleção: org.flathub.Stable
Instalação: system
 Instalado: 213,7 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: b280758ce502a3386033f001ec5f97fcca7a661b0ca7aba7772541bcd9e1e182
       Pai: 8a2eb06ae31255b4882bb7fae73b958cc384cf72f55d11619d6656af8ebb236f
   Assunto: Update libjxl-0.9.2.tar.gz to 0.10.0 (dd43793f)
      Data: 2024-02-22 04:52:52 +0000
```

**Comment by bbhtt** [comment]
Am I missing something because this doesn't seem fixed in 1.15.7+?

![image](https://github.com/flatpak/flatpak/assets/62639087/7347aaec-25c1-4bdc-b2c2-06a76dd2951e)

**Comment by chrisawi** [comment]
> Am I missing something because this doesn't seem fixed in 1.15.7+ ?

It will persist until each app is updated or reinstalled because the incorrect name was in stored the deploy data.

I've just reconfirmed that it's fixed in F40 with 1.15.8.

**Comment by bbhtt** [comment]
Yea that was it thanks. I didn't notice it was being stored in the deploy file separately.

**Comment by boredsquirrel** [comment]
hi, thanks for taking care of it! Is there no way to force reload the metadata?
