### ISSUE TITLE
[Feature request]: kernel and more

### ISSUE THREAD

**Issue by daktras420** [flatpak/flatpak#5704]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I understand kernel as well as pipewire wayland and other libraries are currently provided by the package maintaners of the choose distro.
Could an operating system based off flatpak to include not just de and apps packaged using flatpak but also the kernel and base system?
My goal is to setup an operating system using flatpak only if possible and maintain it.

**Comment by chrisawi** [comment]
This is out of scope for flatpak, but an operating system can be constructed from the same building blocks, namely ostree and freedesktop-sdk. See for example GNOME OS. In theory, it could even be possible to [merge the system and flatpak ostree repos](https://blogs.gnome.org/alexl/2023/07/11/composefs-state-of-the-union/#comment-21469) in the future.
