### ISSUE TITLE
[Feature request]: add pipewire permission

### ISSUE THREAD

**Issue by trytomakeyouprivate** [flatpak/flatpak#5706]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Apps often need `filesystem=xdg-run/pipewire-0:ro` permission.

This makes them display as "potentially insecure".

First I would like understand what this permission does, and nonetheless it looks like a separate permission would be useful.

Example: https://github.com/wwmm/easyeffects

**Comment by rusty-snake** [comment]
Duplicated of #5130

**Comment by hfiguiere** [comment]
> This makes them display as "potentially insecure". 

this information isn't displayed by flatpak anywhere. Not a flatpak problem.
