### ISSUE TITLE
[Bug]: I can not update my flatpak packages inspite working well Internet connection !

### ISSUE THREAD

**Issue by Nokia808** [flatpak/flatpak#5709]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

38

### What architecture are you using?

x86_64

### How to reproduce

Run "flatpak update"

### Expected Behavior

Installed flatpak packages on my system should be updated.

### Actual Behavior

Installed package on my system failed to update !

### Additional Information

Please see the following link which contain the issue as I reported to Flathub:
https://github.com/flathub/flathub/issues/4945

**Comment by chrisawi** [comment]
What does `flatpak remote-ls flathub` output? If it gives an error, please share it.

Also, what is `DISPLAY` set to? (`echo $DISPLAY`)

**Comment by Nokia808** [comment]
I run flatpak remote-ls flathub & result appeared - after a long delay - with the following error:

```
$ flatpak remote-ls flathub
error: Unable to load summary from remote flathub: While fetching https://dl.flathub.org/repo/summary.idx: [28] Timeout was reached
```

I run echo $DISPLAY & output was as following:
```
$ echo $DISPLAY
:0
```

**Comment by Nokia808** [comment]
I tried to open https://dl.flathub.org/repo/summary.idx by my Firefox using normal Internet connection but it did not opened. Then I tried to open it by Tor browser & it was opened, being a file !! 

What does this mean ?? Is this mean that my ISP block https://dl.flathub.org/repo/summary.idx ??

**Comment by Nokia808** [comment]
I tested issue on other ISP & every think pass very okay & "flatpak remote-ls flathub" showed me list of repositories available from FlatHub & "flatpak update" worked very well & I updated my flatpak packages ! It seem that some ISP blocking certain sites wrongly from time to time ! Yes, this happened in my country, Iraq, I we need to inform ISP to fix wrong blockage & re-allowed them again ! I experienced such cases before on occasional base ....

I will let you to decide if to close this issue or not .....
