### ISSUE TITLE
[Bug]: Critical message `GFileInfo created without standard::is-symlink` when launching any app

### ISSUE THREAD

**Issue by guihkx** [flatpak/flatpak#5711]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

rolling

### What architecture are you using?

x86_64

### How to reproduce

1\. Simply create a directory in Flatpak's [unmaintained](https://docs.flatpak.org/en/latest/extension.html#unmaintained-flatpak-extensions) extensions directory:

```sh
$ sudo mkdir /var/lib/flatpak/extension/org.freedesktop.Platform.GL.host/x86_64/1.4
```

2\. Run this test command and observe its output:

```sh
$ flatpak run --system --command=true org.freedesktop.Platform

(flatpak run:4162): GLib-GIO-CRITICAL **: 12:07:32.118: GFileInfo created without standard::is-symlink

(flatpak run:4162): GLib-GIO-CRITICAL **: 12:07:32.118: file ../glib/gio/gfileinfo.c: line 1677 (g_file_info_get_is_symlink): should not be reached
```

### Expected Behavior

No critical message from glib.

### Actual Behavior

We get a critical message from glib.

### Additional Information

I've followed [this guide](https://blog.tingping.se/2018/08/26/flatpak-host-extensions.html) to create an unmaintained extension for my NVIDIA drivers.

Despite that critical message, the `host` driver extension gets picked up correctly and 3D apps work just fine.

**Comment by chrisawi** [comment]
Thanks for the report, but this has already been fixed in https://github.com/flatpak/flatpak/commit/1a5fd13ca5749a6902704d27e1636af75973885d.

It's not yet in a release.

**Comment by guihkx** [comment]
Oh, nice. Thanks for letting me know.

I'll close this one then.
