### ISSUE TITLE
[Bug]: for steam fix

### ISSUE THREAD

**Issue by sillyguy28093214** [flatpak/flatpak#5724]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

ChromeOS

### Linux distribution version

Linux penguin 6.1.64-09049-g010fe86d9eae #1 SMP PREEMPT_DYNAMIC Thu, 1 Feb 2024 01:25:43 +0000 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

try to launch steam

### Expected Behavior

it will load the game

### Actual Behavior

![Screenshot 2024-03-14 1 09 17 PM](https://github.com/flatpak/flatpak/assets/159817938/f06d3782-ca75-4464-b096-e0f862ae48c7)

### Additional Information

[images.txt](https://github.com/flatpak/flatpak/files/14605703/images.txt) log file :D

**Comment by smcv** [comment]
If you are not running Steam under Flatpak, then this cannot possibly be a Flatpak bug.

Please read what the message says, and act accordingly.

> What Linux distribution are you using?
>
> ChromeOS

I don't think Valve officially supports ChromeOS, which is not a normal desktop Linux distribution.

**Comment by smcv** [comment]
The Steam issue tracker is over here: https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by sillyguy28093214** [comment]
thanks for the help sm
