### ISSUE TITLE
[Bug]: Steam Overlay Doesn't work on Flatpak steam.

### ISSUE THREAD

**Issue by Abdulsarhan** [flatpak/flatpak#5727]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

Linux arch 6.7.9-arch1-1

### What architecture are you using?

x86_64

### How to reproduce

1 - update your system. (sudo pacman -Syyu)
2 - Download flatpak steam
3 - Download a game on steam
4 - Run steam game
5 - Steam overlay doesn't work when you hit shift + tab
yes, I did enable the steam overlay globally, and I did enable it for the games that I tested. 
And yes, my overlay key is bound to shift+tab. I just checked it. 
Also, it doesn't matter if the game is native, running through proton, or it's a non-steam game. The steam overlay doesn't work on anything. 

### Expected Behavior

I want the steam overlay to come up when I hit shift+tab.

### Actual Behavior

Game loads,  I hit shift+tab, no steam overlay. 
The FPS counter doesn't work either.
And I don't get that notification telling me that I can hit shift+tab to open up the steam overlay.

### Additional Information

The overlay works just fine on the native version of steam. 
The flatpak version's overlay doesn't work.

**Comment by hfiguiere** [comment]
Flatpak doesn't distribute Steam.

Reporting it to the Flathub package is probably more appropriate:

https://github.com/flathub/com.valvesoftware.Steam/issues
