### ISSUE TITLE
[Bug]: No desktop entries for Flatpaks apps

### ISSUE THREAD

**Issue by Ombrelin** [flatpak/flatpak#5732]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.2

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04LTS

### What architecture are you using?

x86_64

### How to reproduce

Install Flatpak apps

### Expected Behavior

Having desktop entries for the installed flatpak apps

### Actual Behavior

No desktop entries for the installed flatpak apps

### Additional Information

1. I've tried the recommended fixes : logout/login, gnome session reset, reboot ...
2. This is a computer to which I access exclusively via Remote Desktop (xRDP)

**Comment by chrisawi** [comment]
> This is a computer to which I access exclusively via Remote Desktop (xRDP)

This seems like the key detail. Flatpak wants `XDG_DATA_DIRS` to include its export dirs (e.g. `/var/lib/flatpak/exports/share`). It attempts to set this various ways, but I suspect that none of them are working for your setup. It ships systemd environment generators, as well as a profile drop-in (`/etc/profile.d/flatpak.sh`) and the equivalent for fish.

Is `XDG_DATA_DIRS` set correctly? It's specifically the environment of the gnome-shell process that matters:

    cat /proc/$(pidof gnome-shell)/environ | tr '\0' '\n' | grep XDG_DATA_DIRS

If `pidof gnome-shell` doesn't work correctly, you can manually replace that with the PID of gnome-shell.

**Comment by Ombrelin** [comment]
Hi, thanks for you quick answer !
So `pidof gnome-shell` return two pids, I ran the command for both :

```
$ cat /proc/4136/environ | tr '\0' '\n' | grep XDG_DATA_DIRS
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
$ sudo cat /proc/1839/environ | tr '\0' '\n' | grep XDG_DATA_DIRS
XDG_DATA_DIRS=/usr/share/gdm/greeter:/usr/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```
The second one (which required `sudo` to `cat` has the flatpak exports, but not the first one

**Comment by chrisawi** [comment]
> XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/

That's what I expected to see. I don't really know anything about xrdp, but I do see that `/etc/xrdp/startwm.sh` sources `/etc/profile`, which seems like it should be enough to get that variable set correctly.

You could check `echo $XDG_DATA_DIRS` in a terminal and then again after creating a login shell with `bash -l`. If the new shell has flatpak's export directories, then the profile drop-in is doing its job.

I don't know if the way you're using xrdp involves that script, but unless that `bash -l` test fails, I don't think this is a flatpak bug. Any environment needs to either (or both):
* use a login shell (for `/etc/profile.d/flatpak.sh`)
* be started by the systemd user manager (for `/usr/lib/systemd/user-environment-generators/60-flatpak`)

**Comment by chrisawi** [comment]
I wonder how the flatpak exports got added twice there. The profile drop-in is meant to be idempotent.

> I don't use bash as login shell (I use powershell)

Using a non-posix shell as your login shell is a bit perilous. Flatpak doesn't ship a profile drop-in for powershell (assuming such a mechanism exists). I expect a PR adding one would be accepted though.

I would consider keeping bash as the login shell and configuring your terminal to launch powershell as a custom command.

> (I access that other machine physically though).

GDM [imports the environment](https://gitlab.gnome.org/GNOME/gdm/-/commit/448134d3cdbc54e5359ea33d387993b0defdaefa) of the systemd user manager, so that's probably how it's working.

**Comment by Ombrelin** [comment]
> I wonder how the flatpak exports got added twice there. The profile drop-in is meant to be idempotent.

I'm not sure either, you think this could be related to my problem ?
If no, do you have any other lead to identify the source of this problem, or do you think this is rather a xRDP issue rather than flatpak ?

**Comment by Ombrelin** [comment]
Okay, is there any manual action which I could do to solve my problem, like copying over desktop entries so that my flatpak apps appear in the desktop ?

**Comment by davidhedlund** [comment]
* https://github.com/flatpak/flatpak/issues/1286

**Comment by davidhedlund** [comment]
# Steps to reproduce:

Run this:

```
wget -P "$HOME/Downloads/" "https://dl.flathub.org/repo/appstream/org.mozilla.firefox.flatpakref"
flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/org.mozilla.firefox.flatpakref"
```

Output:
```
Installing runtime/org.mozilla.firefox.Locale/x86_64/stable
Installing app/org.mozilla.firefox/x86_64/stable

Note that '/home/blues/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /home/blues/.local/share
- /usr/share/mate
- /usr/share/mate
- /usr/share/gnome
- /home/blues/.local/share/flatpak/exports/share
- /home/blues/flatpak/exports/share
- /var/lib/flatpak/exports/share
- /usr/local/share
- /usr/share
```


* Add this to ~/.bashrc:
```
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$HOME/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
```

* Log out/log in
* Firefox not visible in the menu under "Internet".

Install another app to see it the setting has take effect:
```
wget -P "$HOME/Downloads/" "https://dl.flathub.org/repo/appstream/dev.tchx84.Gameeky.flatpakref"
flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/dev.tchx84.Gameeky.flatpakref"
```

Output seems fine this time (ignore the GNOME runtime complain -- it's a separate issue):
```
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Installing runtime/org.gnome.Platform.Locale/x86_64/45
Installing runtime/org.gnome.Platform/x86_64/45
Installing app/dev.tchx84.Gameeky/x86_64/stable
```

* Log out/log in: Gameeky is not visible under "Game" in the menu

**Comment by davidhedlund** [comment]
# Steps to reproduce:

Run this:

```
wget -P "$HOME/Downloads/" "https://dl.flathub.org/repo/appstream/org.mozilla.firefox.flatpakref"
flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/org.mozilla.firefox.flatpakref"
```

Output:
```
Installing runtime/org.mozilla.firefox.Locale/x86_64/stable
Installing app/org.mozilla.firefox/x86_64/stable

Note that '/home/testuser/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /home/testuser/.local/share
- /usr/share/mate
- /usr/share/mate
- /usr/share/gnome
- /home/testuser/.local/share/flatpak/exports/share
- /home/testuser/flatpak/exports/share
- /var/lib/flatpak/exports/share
- /usr/local/share
- /usr/share
```


* Add this to ~/.bashrc:
```
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$HOME/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
```

* Log out/log in
* Firefox not visible in the menu under "Internet".

Install another app to see it the setting has take effect:
```
wget -P "$HOME/Downloads/" "https://dl.flathub.org/repo/appstream/dev.tchx84.Gameeky.flatpakref"
flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/dev.tchx84.Gameeky.flatpakref"
```

Output seems fine this time (ignore the GNOME runtime complain -- it's a separate issue):
```
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Installing runtime/org.gnome.Platform.Locale/x86_64/45
Installing runtime/org.gnome.Platform/x86_64/45
Installing app/dev.tchx84.Gameeky/x86_64/stable
```

* Log out/log in: Gameeky is not visible under "Game" in the menu

**Comment by davidhedlund** [comment]
# SOLVED

# Steps to reproduce:

Run this:
```
wget -P "$HOME/Downloads/" "https://dl.flathub.org/repo/appstream/org.mozilla.firefox.flatpakref"
flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/org.mozilla.firefox.flatpakref"
```

Output:
```
$ flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/org.mozilla.firefox.flatpakref"

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/testuser/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Installing runtime/org.mozilla.firefox.Locale/x86_64/stable
Installing app/org.mozilla.firefox/x86_64/stable
```

* Add this to ~/.bashrc:
```
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
```

Note: The colon (:) is not used in the XDG_DATA_HOME variable because it represents a single directory path, while it is used in XDG_DATA_DIRS because it represents multiple directory paths.

* Firefox is not yet visible in the menu under "Internet".
* Log out/log in
* Firefox is now visible in the menu under "Internet".

**Comment by davidhedlund** [comment]
# SOLVED

Run this:
```
wget -P "$HOME/Downloads/" "https://dl.flathub.org/repo/appstream/org.mozilla.firefox.flatpakref"
flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/org.mozilla.firefox.flatpakref"
```

Output:
```
$ flatpak install --user --noninteractive --assumeyes "$HOME/Downloads/org.mozilla.firefox.flatpakref"

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/testuser/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Installing runtime/org.mozilla.firefox.Locale/x86_64/stable
Installing app/org.mozilla.firefox/x86_64/stable
```

* Add this to ~/.bashrc:
```
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
```

Note: The colon (:) is not used in the XDG_DATA_HOME variable because it represents a single directory path, while it is used in XDG_DATA_DIRS because it represents multiple directory paths.

* Firefox is not yet visible in the menu under "Internet".
* Log out/log in
* Firefox is now visible in the menu under "Internet".

**Comment by davidhedlund** [comment]
> Okay, is there any manual action which I could do to solve my problem, like copying over desktop entries so that my flatpak apps appear in the desktop ?

* https://github.com/flatpak/flatpak/issues/1286
