### ISSUE TITLE
Support request: Provide push privileges to WPS-office

### ISSUE THREAD

**Issue by NL-TCH** [flatpak/flatpak#5734]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

As the old maintainer stated, we are allowed to request push permissions to the WPS office repo.
https://discourse.flathub.org/t/new-wps-office-maintainer-wanted/1321 

I want this permissions to merge some PR's and keep WPS up to date (fixes quite some security problems in the process)

User: NL-TCH
Permission: Push (merge + commit)
repo: https://github.com/flathub/com.wps.Office

**Comment by smcv** [comment]
Sorry, this project is for the Flatpak library and command-line tool, not the Flathub app-store (they are not maintained by the same people, although there is some overlap). Please send access requests to <https://github.com/flathub/flathub/issues>.
