### ISSUE TITLE
[Feature request]: add the ability to use box64 instead of qemu for user mode emulation

### ISSUE THREAD

**Issue by m1m1k4tz** [flatpak/flatpak#5736]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I think it would be cool to be able to use box64 for user mode emulation of other architectures rather than just qemu

**Comment by chrisawi** [comment]
I don't believe flatpak has any direct support for qemu. It works via binfmt_misc with the 'F' flag. There's an open issue for box64 to do the same thing: https://github.com/ptitSeb/box64/issues/1361.

I saw where the box64 developer told you that the static build lacks GPU support. I don't know if that's an insurmountable limitation, but it needs to be static to work this way.

**Comment by m1m1k4tz** [comment]
> I don't believe flatpak has any direct support for qemu. It works via binfmt_misc with the 'F' flag. There's an open issue for box64 to do the same thing: [ptitSeb/box64#1361](https://github.com/ptitSeb/box64/issues/1361).
> 
> I saw where the box64 developer told you that the static build lacks GPU support. I don't know if that's an insurmountable limitation, but it needs to be static to work this way.

Sweet thanks for clearing that up
