### ISSUE TITLE
[Bug]: some applications are not updated to latest version available from origin

### ISSUE THREAD

**Issue by carlocastoldi** [flatpak/flatpak#5741]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1:1.15.6-2

### What Linux distribution are you using?

Arch Linux

### What architecture are you using?

x86_64

### How to reproduce

1. go to https://flathub.org/apps/us.zoom.Zoom
2. see latest version is 5.17.5.2543
3. run: `flatpak list --app --columns=application,version,origin | grep -i zoom`
4. output: `us.zoom.Zoom	5.14.7.2928	flathub`
5. run `flatpak update`, `flatpak update --user` and `sudo flatpak update`
6. output: `Nothing to do.`

### Expected Behavior

I would expect flatpak to download from the latest version of `us.zoom.Zoom` FlatHub.

### Actual Behavior

Does not update the out-of-date application

### Additional Information

This problem is not restricted to Zoom only. I actually noticed it for com.slack.Slack first
I then uninstalled the application and re-installed it. Now it downloaded the latest version from origin
This made me think that I may had other applications with the same problem. I immediately found us.zoom.Zoom also didn't update.
More may have the same issue, i just didn't investigate further

I have not yet updated Zoom from by re-installing in case my current configuration could be useful for debugging.

**Comment by chrisawi** [comment]
Do you have any masked patterns? `flatpak mask` or `flatpak mask --user`

Also, please share the output of `flatpak info us.zoom.Zoom`  and `flatpak -v update us.zoom.Zoom`

**Comment by carlocastoldi** [comment]
Oh god, I completely forgot i had masked those two problematic applications.
I'm terribly sorry for this blunder of mine

If I may, i'd like to suggest to show an indication of an application being masked. Either during `update` or `list`

That said I am aware that this is my fault for forgetting it

Thank you!

**Comment by chrisawi** [comment]
This is definitely a bit of a foot gun.

> If I may, i'd like to suggest to show an indication of an application being masked. Either during update or list

There's a similar request here: https://github.com/flatpak/flatpak/issues/5024
