### ISSUE TITLE
[Bug]: after running Flatpak app for some time I won't able to connect to D-Bus again inside it

### ISSUE THREAD

**Issue by L11R** [flatpak/flatpak#5742]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

6.8.1-arch1-1

### What architecture are you using?

amd64

### How to reproduce

I am developing my own app using Golang and github.com/godbus/dbus package to work with OpenVPN3 using D-Bus. While I am using it without Flatpak everything is okay, app activates services, connects and receive stats about connection. But in case of Flatpak I am getting non-constant behavior:

1. I open the app, it works, activates services, connects, etc.
2. Works for quite long, maybe hours.
3. But at some point it fails to connect to D-Bus.

Errors I get:
```
time=2024-03-22T09:16:35.267+01:00 level=ERROR msg="Error while trying to start service by name!" openvpn.err="read unix @->/run/user/1000/.dbus-proxy/system-bus-proxy-HG5KK2: EOF"
time=2024-03-22T09:16:35.267+01:00 level=ERROR msg="Error while trying to start service by name!" openvpn.err="read unix @->/run/user/1000/.dbus-proxy/system-bus-proxy-HG5KK2: EOF"
time=2024-03-22T09:16:35.267+01:00 level=ERROR msg="Error while trying to start service by name!" openvpn.err="read unix @->/run/user/1000/.dbus-proxy/system-bus-proxy-HG5KK2: EOF"
time=2024-03-22T09:16:35.668+01:00 level=ERROR msg="Error while trying to start service by name!" openvpn.err="dbus: connection closed by user"
time=2024-03-22T09:16:35.668+01:00 level=ERROR msg="Error while trying to start service by name!" openvpn.err="dbus: connection closed by user"
time=2024-03-22T09:16:35.668+01:00 level=ERROR msg="Error while trying to start service by name!" openvpn.err="dbus: connection closed by user"
time=2024-03-22T09:16:35.926+01:00 level=ERROR msg="Error while getting statistics property of session!" openvpn.err="dbus: connection closed by user"
```

So basically app is trying to invoke some D-Bus method or read properties, but fails.

Also at first start I rarely get this (maybe it's related):
```
time=2024-03-22T13:27:27.274+01:00 level=ERROR msg="Error while trying to start service by name!" openvpn.err="read unix @->/run/user/1000/.dbus-proxy/system-bus-proxy-TFPIK2: recvmsg: connection reset by peer"
```

### Expected Behavior

App works with D-Bus as usual

### Actual Behavior

D-Bus connection problems

### Additional Information

Sorry, I could just don't understand something about D-Bus and maybe work with it incorrect. Currently I think that probably something wrong with my D-Bus reconnection flow, but I still don't understand why I am getting those problems only while app in Flatpak's sandbox.

**Comment by mcatanzaro** [comment]
You noticed this is xdg-dbus-proxy#46. Let's close this and continue there.
