### ISSUE TITLE
[Bug]: Flatpak is not displaying items in `flatpak list` properly, and putting the Developer/Author/Company name in the "Name" field

### ISSUE THREAD

**Issue by sfalken** [flatpak/flatpak#5743]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

openSUSE

### Linux distribution version

Kalpa (Tumbleweed)

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak list | grep neochat`   See that the contents of the "Name" field are "The KDE Community"
2. Run `flatpak remote-ls flathub | grep neochat` See that the contents of the "Name" field is "NeoChat"
3. Run `flatpak remote-ls fedora | grep neochat` See that the contents of the "Name" field is "NeoChat"
4. Go look at the kcm_flatpak control panel in Plasma, and see that it is picking up it's Application Names, from the "Name" field in `flatpak list`    (Attached Screenshot of behavior, Neochat is not shown in the screen shot, but you can see "John Preston" and "Kovid Goyal")
![Screenshot_20240322_135654](https://github.com/flatpak/flatpak/assets/95936027/2d34bc4b-0691-42ad-afe3-1a77c698d9a9)

### Expected Behavior

`flatpak list` and by extension, things like kcm_flatpak, flatseal, or warehouse display the application name, and not the Developer/Author/Company name.

### Actual Behavior

`flatpak list` Shows Author/Developer/Company names in the "Name" field.

**Comment by chrisawi** [comment]
Duplicate of #5700

This will be fixed in the next release, but apps will need to be reinstalled or updated before they'll have the correct information.
