### ISSUE TITLE
[Bug]: Gnome Backups (DejaDup) suddenly unable to open paths!?

### ISSUE THREAD

**Issue by 6-AND-9** [flatpak/flatpak#5747]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Fedora Kinoite 6.7.9-200.fc39.x86_64 (KDE Plasma)

### What architecture are you using?

i386

### How to reproduce

1. Add any backup path in HOME or elsewhere.
2. Try to commence backup.
3. Get message: "The following folders cannot be backed up because Backups does not have access to them: [listed dirs]"

### Expected Behavior

GNOME Backups to be able to access any directory in HOME or any other user-created directories (incl. those on other mounted drives).

Flatseal or `flatpak override` to be able to allow filesystem access. 

### Actual Behavior

GNOME Backups cannot access any directory in HOME or elsewhere. Simply states: "This folder cannot be backed up because Backups does not have access to it". 

Flatseal or `flatpak override` 'allow' filesystem access, but GNOME Backups is still unable to use it.

### Additional Information

Hello,

```
## Rationale for opening an issue ticket here

I know you recommend going first to GNOME Backups (Deja Dup) to try and solve this issue, but I am more than 90% certain that this is a Flatpak issue not with the specific app. The reasoning behind this is: 


1. I actually had GNOME Backups Flatpak version working two days ago, without any issues (albeit I changed/updated _something_ since then, but I fail to see what could have been so radical of a change to create this mess; 
2. I notice some issues with how permissions/overrides are set (inconsistency), which are Flatpak-dependant; 
3. The non-Flatpak version works just fine, but I prefer the Flatpak one; 
4. There are users with similar/same issue but for different apps, or altogether all Flatpak apps: (example: https://discussion.fedoraproject.org/t/flatpaks-cant-seem-to-access-most-folders-including-home/76543/4); 
5. This (https://gitlab.gnome.org/World/deja-dup/-/issues/113) issue ticket is similar and old, and supposedly 'solved', but it is not solved for me; 
6. I am at the end of my wits here (while being a relative Linux newbie).
```

That being said, 

## Intro

I had a fine run using Gnome Backups (DejaDup) Flatpak version as my backup solution until today, when the software refuses to use paths located in my HOME directory saying that: This folder cannot be backed up because Backups does not have access to it. Access is given through Flatseal to the whole HOME dir as well as to these separate dirs, but to no avail. Some of these directories are Unicode (Cyrillic), some are pure Latin and common system paths (i.e. ~/Music/ or even xdg-music). 

I first thought that I had an issue with my locale, but it doesn't seem like it (or maybe I'm wrong?).

Layered (non-Flatpak) DejaDup is working, but I REALLY prefer to use the Flatpak version so I don’t have to layer anything through rpm-ostree.

## Locale stuff

`flatpak run --command=locale org.gnome.DejaDup` used to print this (BTW the same is printed for VLC, Flatseal):

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="xx_XX.utf8"
LC_NUMERIC="xx_XX.utf8"
LC_TIME="xx_XX.utf8"
LC_COLLATE="xx_XX.utf8"
LC_MONETARY="xx_XX.utf8"
LC_MESSAGES="xx_XX.utf8"
LC_PAPER="xx_XX.utf8"
LC_NAME="xx_XX.utf8"
LC_ADDRESS="xx_XX.utf8"
LC_TELEPHONE="xx_XX.utf8"
LC_MEASUREMENT="xx_XX.utf8"
LC_IDENTIFICATION="xx_XX.utf8"
LC_ALL=xx_XX.utf8
```

but  was repaired with `flatpak config --set languages en` to:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
``` 

System-run locale command gives:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Also tried changing all settings in System settings → Region & Language to defaults, modified a few system files (e.g. /etc/locale.conf), etc… ran flatpak repair, trying to solve the issue. Nothing helps. 

## Inconsistency with applied permissions

Weirdly enough, it seems that Flatseal applies permissions _for itself and for KDE_, but they don’t apply to DejaDup. I can see them ‘applied’ from both within Flatseal and KDE settings → Flatpak permissions, but when I try `flatpak permission-show org.gnome.DejaDup` there’s nothing printed. When I also try `flatpak override --show org.gnome.DejaDup` nothing is printed. `flatpak repair reinstall-all` didn’t fix the issue as well.

## Wrap up

It seems as if DejaDup is living in a separate reality from the system, and refuses to accept new permissions. Even when I reset them through Flatseal, or `flatpak override --reset org.gnome.DejaDup` (which should in theory allow ‘All system files’ access to the app), it still cannot access any directory that I choose.

I also rebooted my whole system a good deal of times between all these changes.

What is going on?!

## Post scriptum

P.S. GNOME Backups and Flatseal are installed as system Flatpaks, not user ones: `flatpak list --system` prints them out, `--user` doesn't.

**Comment by hfiguiere** [comment]
Issues about specific **FLATHUB** package are to but submitted to the specific flathub tracke for the package.

Flatpak doesn't provide package.

**Comment by 6-AND-9** [comment]
> xx_XX is not a valid locale.

This was solved already, was just put for reference.

> Issues about specific FLATHUB package are to but submitted to the specific flathub tracke for the package.
> 
> Flatpak doesn't provide package.

I know, but this seems to be a Flatpak issue, not the specific app's one. :)

**Comment by hfiguiere** [comment]
> I know, but this seems to be a Flatpak issue, not the specific app's one. :)

Correlation is not causation. I don't see where you pinpoint the problem to flatpak itself.

**Comment by 6-AND-9** [comment]
> > I know, but this seems to be a Flatpak issue, not the specific app's one. :)
> 
> Correlation is not causation. I don't see where you pinpoint the problem to flatpak itself.

I don't intend to come off as arrogant here, please don't take it as such. 

I believe the problem is due to flatpak itself because the program worked just two days ago, some other people report similar issues of Flatpaks not being able to access _any_ filesystem dirs, and finally and most important, it seems it has something to do with inconsistency of permissions which is a Flatpak issue - not Deja Dup's. :)

If you don't think I could get help in solving this here, and I don't think I can get it in Deja Dup's Gitlab (because they'll point me out back to Flatpak), what should I do? It is a _very_ weird problem, one that I never met before.

**Comment by hfiguiere** [comment]
> I don't intend to come off as arrogant here, please don't take it as such.

yet you do.

**Comment by 6-AND-9** [comment]
> > I don't intend to come off as arrogant here, please don't take it as such.
> 
> yet you do.

Where?
