### ISSUE TITLE
[Bug]: `flatpak list --columns=name` shows developer name instead of application name

### ISSUE THREAD

**Issue by mkhl** [flatpak/flatpak#5755]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

rolling

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak list --columns=name`

### Expected Behavior

The output lists the names of installed flatpaks.

### Actual Behavior

The output lists the names of *developers* of installed flatpaks, e.g. Sonny Piers for re.sonny.Workbench, or Evangelos "GeopJr" Paterakis for dev.geopjr.Tuba.

**Comment by smcv** [comment]
This looks like a duplicate of https://github.com/flatpak/flatpak/issues/5700 which was fixed in 1.15.7. If your distro is tracking the 1.15.x development prereleases (which I wouldn't necessarily advise, but it seems they are) then please ask them to upgrade.
