### ISSUE TITLE
German translation of a string might be confusing

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak#576]
Using flatpak 0.8.2, when trying to add a remote flatpak repo which has been added already, the following error message is displayed:

"Fehler: Entfernte Quelle gnome existiert bereits"

"Entfernte" can mean "remote" as well as "removed". dict.cc suggests the unambiguous translations "Remote-" or "Rechnerferne".

**Comment by piotrdrag** [comment]
@nazgul77 — could you please take a look at this?

**Comment by nazgul77** [comment]
@piotrdrag sure, I will take care of this.

@Alexander-Wilms Hallo Alexander, viele Dank für deinen Bericht. Die Mehrdeutigkeit des Wortes selbst ist definitiv vorhanden. Im Zusammenhang des ganzen Satzes sehe ich aber keinen Spielraum für eine andere Deutung als jene, dass »Entfernte« tatsächlich »Entfernt gelegene« meint. Wie könnte eine Quelle, die entfernt wurde, bereits vorhanden sein? Das ergibt keinen Sinn.
An dieser Stelle ersetze ich einfach »Entfernte« durch »Entfernt gelegene«. Damit ist es zweifelsohne eindeutig.

**Comment by nazgul77** [comment]
Pull request #912

**Comment by nazgul77** [comment]
Request was merged. ok to close?

**Comment by Alexander-Wilms** [comment]
Yes, thanks.
