### ISSUE TITLE
Improve "Remote not found" error message

### ISSUE THREAD

**Issue by csoriano1618** [flatpak/flatpak#577]
I tried to uninstall all gnome-builder remotes, and I did flatpak remote-delete org.gnome.Builder*
and this was the error:
error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code1: Remote "org.gnome.Builder*" not found
.
Maybe it shouldn't spit out the gdbus error?

**Comment by alexlarsson** [comment]
Yeah, i hate these things. You have to randomly un-fuck-up GErrors in some places...

**Comment by nedrichards** [comment]
Furthermore, it'd be great if the error actually showed all of the reasons why you can't remove the remote at once. e.g. this system:

`nick@endless-nedr:~/Projects$ flatpak remote-delete kderuntime 
error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: Can't remove remote 'kderuntime' with installed ref runtime/org.kde.Sdk.Locale/x86_64/5.9 (at least)
nick@endless-nedr:~/Projects$ flatpak uninstall org.kde.Sdk.Locale
Uninstalling org.kde.Sdk.Locale/x86_64/5.9
nick@endless-nedr:~/Projects$ flatpak remote-delete kderuntime 
error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: Can't remove remote 'kderuntime' with installed ref runtime/org.kde.Platform.Locale/x86_64/5.9 (at least)
`

Repeat ad-infinitum, it's a bit frustrating.

**Comment by matthiasclasen** [comment]
I think the better solution for this would be a --purge option, like

$ flatpak remote-delete --purge foo
the following refs are installed from remote foo:
bla1
bla2
bla3
Remove all of these ? (y/n)
