### ISSUE TITLE
error code sigsegv in ungoogled chromium flatpak edition

### ISSUE THREAD

**Issue by Devious3901** [flatpak/flatpak#5774]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Debian

### Linux distribution version

Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

This happened after the flatpak update

### Expected Behavior

Hi, two weeks ago I updated all the apps to flashpak, and I got this problem that pops up in ungoogled chrome, how to fix it, before that it was not there, that is, before the update of the flashpak version.

### Actual Behavior

Check screenshot https://imgur.com/a/JmFnKYa
or smth like that https://imgur.com/a/44YQOnH
https://imgur.com/a/PX4K7ES

### Additional Information

Version 123.0.6312.105 (Official Build, ungoogled-chromium) (64-bit)

**Comment by hfiguiere** [comment]
This is the issue tracker for flatpak, not or individual flatpaked apps.
