### ISSUE TITLE
Android Studio Verification

### ISSUE THREAD

**Issue by 3knight** [flatpak/flatpak#5781]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I would like to apologize upfront if those is inappropriate or unwelcomed. Android Studio is an important/useful tool and it being available as a flatpak would be great. It is currently available, however it is unverified. I assume Android themselves are not maintaining it. Would it be possible for someone to reach out to Android and see if it would be something they would be interested in taking over/verifying? I tried to find a way to contact them but couldn't find anything. Maybe someone knows someone or knows how? Sorry again if this is not cool, feel free to delete if that's the case. Thanks

**Comment by smcv** [comment]
> Sorry, I should have posted this on FlatHub issues

Closing as not actionable for Flatpak-the-tool: this is something to take up the upstream developers of Android Studio, or with the current maintainers of the Android Studio app.
