### ISSUE TITLE
[Bug]: front ends and consuments of flatpak command output have no reliable way to retrieve an application name, which is important for users

### ISSUE THREAD

**Issue by hg42** [flatpak/flatpak#5784]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.5, 1.15.8

### What Linux distribution are you using?

Debian

### Linux distribution version

mix of stable, testing, unstable, experimental, ubuntu

### What architecture are you using?

x86_64

### How to reproduce

`flatpak info io.github.tdesktop_x64.TDesktop`
`flatpak remote-info flathub io.github.tdesktop_x64.TDesktop`
`flatpak list`

### Expected Behavior

the info commands should show the same name of the package

the list command should show the names

consumers of flatpak output should have a machine readable way to retrieve the package name and description (`flatpak info -m`)

### Actual Behavior

newer package versions show the developer name instead of the package name

consumers of flatpak command output don't have a way to retrieve the name and description in a machine readable way,
for newer package versions retrieving the name is completely impossible via flatpak commands (e.g. no trace of "64Gram Desktop" in any flatpak command output.

### Additional Information

Note, I am a flatpak user only (though also software developer), I don't have knowledge of flatpaks internals.
The bug appeared in the buah frontend, but seems to be related to packaging, because it changes from the proper name to the developer name when updating to newer packages.

At the root of the problem is an inconsistency for the newer packages (25 of my installed 57 packages).
I take 64Gram as an example, because it shows the problem, it creates for a user.

`flatpak info` outputs:

```
Husky - Unofficial desktop version of Telegram messaging app

          ID: io.github.tdesktop_x64.TDesktop
         Ref: app/io.github.tdesktop_x64.TDesktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.1.18
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 235.6 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 303bf90a920d10b8ff39470d6a83b581ade9714ff96fecf810082c1866f9d1a9
      Parent: ce55fd6f7df059ef2ed228303bca6ab224d914b6e2d70855a4f138ffd5578132
     Subject: Update Qt patches to desktop-app/patches@f81dfc6 (d4f4f625)
        Date: 2024-04-18 23:16:13 +0000
```

but `flatpak remote-info flathub io.github.tdesktop_x64.TDesktop` shows:

```
64Gram Desktop - Unofficial desktop version of Telegram messaging app

        ID: io.github.tdesktop_x64.TDesktop
       Ref: app/io.github.tdesktop_x64.TDesktop/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 1.1.18
   License: GPL-3.0
Collection: org.flathub.Stable
  Download: 89.3 MB
 Installed: 235.6 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: 303bf90a920d10b8ff39470d6a83b581ade9714ff96fecf810082c1866f9d1a9
    Parent: ce55fd6f7df059ef2ed228303bca6ab224d914b6e2d70855a4f138ffd5578132
   Subject: Update Qt patches to desktop-app/patches@f81dfc6 (d4f4f625)
      Date: 2024-04-18 23:16:13 +0000
```

the title is different, for unknown reason `flatpak info` uses the developer name (I looked into *.metainfo.xml).

`flatpak info -m` doesn't contain the name or description at all, so there is no proper way to retrieve the field in a future proof way.

Apps like bauh need a proper name to display to the user.
Currently it shows "Husky" instead of "64Gram Desktop", because it uses the only possible way to retrieve the name from flatpak command output.

But it's not a bauh problem, because `flatpak list` also shows the developer names for the newer packages:
```
% flatpak list 
Name                                             Application ID                                       Version            Branch             Installation
Adobe Reader                                     com.adobe.Reader                                     9.5.5              stable             system
DIY Layout Creator                               com.diy_fever.DIYLayoutCreator                       4.37.0             stable             system
DSView                                           com.dreamsourcelab.DSView                            1.3.0              stable             system
Giada Developers                                 com.giadamusic.Giada                                 1.0.0              stable             system
Gittyup                                          com.github.Murmele.Gittyup                           v1.3.0             stable             system
Marker                                           com.github.fabiocolacio.marker                       2023.05.02         stable             system
Julián Unrrein                                   com.github.junrrein.PDFSlicer                        1.8.8              stable             system
[...]
Dave Patrick Caberto                             io.github.seadve.Mousai                              0.7.7              stable             system
Husky                                            io.github.tdesktop_x64.TDesktop                      1.1.18             stable             system
Chart Geany                                      io.sourceforge.chart_geany.chart-geany               6.3.1              stable             system
Lorenzo Paderi                                   it.mijorus.collector                                 1.0.1              stable             system
[...]
```

**Comment by hg42** [comment]
this is the related issue for bauh:
https://github.com/vinifmor/bauh/issues/356

**Comment by smcv** [comment]
At the risk of stating the obvious, this is not Flatpak working as designed, this is a bug. Specifically, it's #5700.

In the 1.15.x branch, this should be fixed in 1.15.7 and up, but it seems that the name that was already stored for apps that were installed while using an affected version of Flatpak remains wrong even after Flatpak is upgraded. As far as I'm aware, reinstalling or upgrading the affected apps resolves this, so it should solve itself "naturally" over time.

In the 1.14.x branch, this is fixed in 1.14.6, with the same caveats. I am [waiting for permission](https://lists.debian.org/debian-release/2024/04/msg00332.html) from the Debian stable release managers to get this fixed in bookworm.

**Comment by smcv** [comment]
> mix of stable, testing, unstable, experimental, ubuntu

Sorry, from a Debian point of view this is unsupportable. Please stick to one of: stable (+ optionally backports), or testing (+ optionally unstable + optionally experimental), or Ubuntu.

**Comment by hg42** [comment]
> this is a bug. Specifically, it's #5700

nice, that it's already fixed, thanks for the good work.

I only searched for open bugs, because I still saw the effect in 1.15.8.
But I should have followed my own conclusions (that I got after searching), that it's "related to packaging".
Sorry, for bothering you.

According to rejecting stable:
Actually, it's the main purpose of Debian testing/unstable/experimental to iron out upcoming bugs.

**Comment by smcv** [comment]
> According to rejecting stable:
> Actually, it's the main purpose of Debian testing/unstable/experimental to iron out upcoming bugs.

I know, but that doesn't make it correct to mix testing/unstable/experimental with stable within a single system. The recommended setup is to either run a stable-based system (+ maybe backports) if you value minimal changes, or a testing-based system (+ maybe unstable and experimental) if you value getting new things sooner: but for each computer, please choose one or the other, not both. More information: https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

>  So, they don't use Debian stable

As far as I know, it should be the version of Flatpak that installed the upgrade that matters, not the version that prepared it.

Upstreams might be able to work around this in affected versions by changing how the fields in their AppStream XML are ordered, with `<name/>` either before or after `<developer><name/></developer>` (I don't know which way round is the better one).

**Comment by hg42** [comment]
> correct to mix testing/unstable/experimental with stable within a single system

well, I would not recommend that for the average user, but it works well for me for many years (>10?)...
you just have to resolve conflicting dependencies manually in a sane way (using aptitude, disabling automatic dependency selection).
Tools like Synaptic do not work well with it.
For example the current t64 transition held back a lot of packages and now slowly solves itself.

Systems like Arch basically do the same... but without the detailed and well tested dependency tree.

**Comment by hg42** [comment]
> As far as I know, it should be the version of Flatpak that installed the upgrade that matters, not the version that prepared it

ok, I tested it more thoroughly...

I said packaging, because only one of the few updated packages changed it's name, the others kept the developer name.

I now tried uninstall+install on some packages and they changed to the correct name.
I also tried downgrade+upgrade and this worked, too.
Both without getting a new version of the package.
So, you semm to be right, or those tested packages are already updated upstream.

Unfortunately, I am no more sure which packages updated today and did not change their names.
I will reinstall all of them and come back later.

**Comment by hg42** [comment]
ok, `flatpak history` helped...
```
Apr 24 15:28:01 pull           io.dbeaver.DBeaverCommunity                          stable       system       flathub
Apr 24 15:28:01 deploy update  io.dbeaver.DBeaverCommunity                          stable       system       flathub
```

I thought `DBeaver Community` would be the developer name, but it's only the variant.

So, it is definitely dependent on the flatpak version when installing, not the packaging.
Thanks for clearing that and sorry for my wrong conclusions.
