### ISSUE TITLE
[Bug]: error: runtime/org.gnome.Sdk/x86_64/44 not installed

### ISSUE THREAD

**Issue by MLSci** [flatpak/flatpak#5790]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Fedora Kinoite 40

### What architecture are you using?

x86_64

### How to reproduce

1. In terminal, `flatpak run --command=sh --devel net.poedit.Poedit`.
Returns an `error: runtime/org.gnome.Sdk/x86_64/44 not installed`
2. Install org.gnome.Sdk from flathub
3. Repeat step 1 and get the same error

### Expected Behavior

No error. Successfully creates a sandbox for the application

### Actual Behavior

`error: runtime/org.gnome.Sdk/x86_64/44 not installed`

### Additional Information

Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.7-300.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7500 CPU @ 3.40GHz
Memory: 46.9 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B250-HD3

**Comment by rusty-snake** [comment]
> Install org.gnome.Sdk from flathub

Install org.gnome.Sdk or org.gnome.Sdk//44?

Is the installed version 44?

**Comment by hfiguiere** [comment]
You pass --devel, then it is assumed you have the SDK. Works as advertised.

**Comment by mcatanzaro** [comment]
Pretty sure you've just installed an org.gnome.Sdk version other than version 44.

**Comment by MLSci** [comment]
Since my OS is immutable, I usually reply on Flatpak providing the latest packages. You're right in this case the org.gnome.Sdk ver. is older than 44.

I thought SDKs like this was bundled when user set up Flatpak. The second best solution is to at least include this info in the [official document](https://docs.flatpak.org/en/latest/debugging.html) so that users can follow the correct instruction
