### ISSUE TITLE
[Bug]: Using `flatpak build-bundle` to bundle debug symbols fails if the app ID contains dashes

### ISSUE THREAD

**Issue by guihkx** [flatpak/flatpak#5792]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

rolling

### What architecture are you using?

x86_64

### How to reproduce

1\. Clone the testing app:

```
git clone https://github.com/guihkx/flatpak-app-detect-it-easy.git
```

2\. Build it:

```
cd flatpak-app-detect-it-easy
flatpak-builder --user --install-deps-from flathub --arch x86_64 --delete-build-dirs --force-clean --repo repo/ --sandbox builddir/ io.github.horsicq.detect-it-easy.yaml
```

3\. Try to create a Flatpak bundle of only the debug symbols:

```
flatpak build-bundle --arch x86_64 repo/ --runtime detect_it_easy.Debug.flatpak 'io.github.horsicq.detect-it-easy.Debug' master
```

### Expected Behavior

The command should succeed.

### Actual Behavior

The command fails with an error:

```
error: 'io.github.horsicq.detect-it-easy.Debug' is not a valid name: Only last name segment can contain -
```

**Comment by chrisawi** [comment]
A bundle can only be made of an app, not an extension. This is https://github.com/flatpak/flatpak/issues/165

**Comment by guihkx** [comment]
So the fact that bundling debug symbols works fine if an app has no dashes on its id, is simply a happy accident?

**Comment by chrisawi** [comment]
Sorry, you're right. I somehow never noticed the `--runtime` option.

Apparently, flatpak-builder [handles this](https://github.com/flatpak/flatpak/issues/370) by changing the `-` to `_` for extensions, so your debug extension should actually be `io.github.horsicq.detect_it_easy.Debug`.

**Comment by guihkx** [comment]
Oh, wow, thanks for that. It worked! :)
