### ISSUE TITLE
Flatpak errors weirdly

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#580]
Does this need changes on the system? Testing on the Plasma Phone stack.

```
$ flatpak run org.gnome.gedit   
Can't find source path /run/user/32011/doc/by-app/org.gnome.gedit: Permission denied
$ ls -l /run/user/32011/doc/by-app/org.gnome.gedit/
total 0
$ sudo ls -l /run/user/32011/doc/by-app/org.gnome.gedit/
ls: cannot access '/run/user/32011/doc/by-app/org.gnome.gedit/': Permission denied
```

**Comment by alexlarsson** [comment]
That is weird. Is `xdg-document-portal` running? What does `grep /doc /proc/self/mountinfo` print?

**Comment by alexlarsson** [comment]
oh, you can't sudo to look at the doc mounts. Its a fuse filesystem that can only be read by your user.

**Comment by alexlarsson** [comment]
But flatpak should be running as your user. I don't understand why its getting EPERM for you.

**Comment by aleixpol** [comment]
Solved, uploaded the steps I took here: https://community.kde.org/Plasma/Mobile/SettingUpFlatpak

Thanks Alex!
