### ISSUE TITLE
[Bug]: Locale not supported by C library.

### ISSUE THREAD

**Issue by Mamol27** [flatpak/flatpak#5814]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Manjaro Linux

### Linux distribution version

Linux aorus 6.6.26-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:11:08 UTC 2024 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

apps, run with flatpack does not support my locale.
```
$ flatpak run com.jetbrains.IntelliJ-IDEA-Community
idea-wrapper: Setting up NPM packages
idea-wrapper: Setting up Cargo packages
idea-wrapper: Setting up Python packages
idea-wrapper: Setting up Ruby packages
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true

(process:2): Gtk-WARNING **: 15:12:04.968: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 15:12:04.969: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:12:04.969: Failed to load module "canberra-gtk-module"
```
```
$ flatpak run --command=locale com.jetbrains.IntelliJ-IDEA-Community
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=
```
```
$ flatpak info com.jetbrains.IntelliJ-IDEA-Community 

JetBrains s.r.o. - Capable and Ergonomic Java IDE

          ID: com.jetbrains.IntelliJ-IDEA-Community
         Ref: app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2024.1.1
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2,5 GB
     Runtime: org.freedesktop.Sdk/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: edceb1da4c1fbf671df1f1c1de41d708ad2eb910528c2517412d43fc2e05c40a
      Parent: bb01d1af6b191535b20fdc548e7c73c848b76d6b6f9e459d325aeda3d64a4e46
     Subject: Activate PulseAudio permission and enable access to the system's audio infrastructure (950a6025)
        Date: 2024-05-13 18:14:54 +0000
```
my location settings:
```
$ localectl
System Locale: LANG=en_US.UTF-8
               LC_NUMERIC=ru_RU.UTF-8
               LC_TIME=ru_RU.UTF-8
               LC_MONETARY=ru_RU.UTF-8
               LC_PAPER=ru_RU.UTF-8
               LC_NAME=ru_RU.UTF-8
               LC_ADDRESS=ru_RU.UTF-8
               LC_TELEPHONE=ru_RU.UTF-8
               LC_MEASUREMENT=ru_RU.UTF-8
               LC_IDENTIFICATION=ru_RU.UTF-8
    VC Keymap: ru
   X11 Layout: us,ru
  X11 Options: grp:alt_shift_toggle
```
```
$ flatpak config --list
languages: en;ru (default: en;ru)
extra-languages: ru
```

### Expected Behavior

Works fine with `ru` and `en` symbols.

### Actual Behavior

Instead russian symbols i have '?'

**Comment by chrisawi** [comment]
> locale: Cannot set LC_ALL to default locale: No such file or directory

Is the `LC_ALL` env var set? If so, to what?

Have you run `flatpak update` after making any locale changes?

**Comment by Mamol27** [comment]
Thank you. After setting languages in flatpak, I didn't run update. Probably update helps. Now it works fine.
