### ISSUE TITLE
bump Webkit in runtime to 2.14.4

### ISSUE THREAD

**Issue by jscurtu** [flatpak/flatpak#582]
Can we please get a update to webkit 2.14.4+ in the org.gnome.Platform//3.22 runtime? 
It solves alot of issues with nVidia and closed driver + closes some CVE bugs.

Reference:
https://github.com/jangernert/FeedReader/issues/327
https://github.com/jangernert/FeedReader/issues/391#issuecomment-281166637

**Comment by jangernert** [comment]
Actually 2.14.4 is the version that fixes the bug in FeedReader. And since 2.14.5 is also out already I suggest to move to the most recent version :)

**Comment by jscurtu** [comment]
@jangernert ups, changed it.

**Comment by jscurtu** [comment]
Its been deployed. closing ... thank you!
