### ISSUE TITLE
[Bug]: ip rule add (RTNETLINK answers: Operation not permitted)

### ISSUE THREAD

**Issue by glaumar** [flatpak/flatpak#5825]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

latest

### What architecture are you using?

x86_64

### How to reproduce

```shell

flatpak remote-add --if-not-exists v2raya-flatpak https://glaumar.github.io/v2raya-flatpak/index.flatpakrepo

flatpak install --system io.github.glaumar.v2raya_flatpak

sudo -i

flatpak run --command=sh io.github.glaumar.v2raya_flatpak

ip rule add fwmark 0x40/0xc0 table 100
```

### Expected Behavior

No error output

### Actual Behavior

RTNETLINK answers: Operation not permitted

### Additional Information

1. I'm not sure if this is a bug or if I did something wrong, but I know it was working fine a few months ago
2.  In a non-flatpak environment, v2raya needs to run as root and it calls the `ip rule` command

**Comment by hfiguiere** [comment]
1. flatpak should never be run as root.
2. flatpak become unprivileged.

**Comment by glaumar** [comment]
So, the current behavior is expected by Flatpak, and it won't be allowed in the future, correct?

**Comment by glaumar** [comment]
Thanks
