### ISSUE TITLE
allow /etc/os-release in the sandbox

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#583]
I want to show some OS information in an about dialog, and would like to read this file to get it.

**Comment by alexlarsson** [comment]
You mean the host one? Isn't that somewhat of an information leak?

**Comment by matthiasclasen** [comment]
Yes, a deliberate one.

Do you think the information in there is in any real way dangerous ? It tells you that you're on Fedora 25...

We could certainly allow making the information up: --pretend-to-be="GNOME OS"

**Comment by matthiasclasen** [comment]
irc conversation was going in the direction of suggesting an "OS Info" portal, similar to the "Account info" portal we have.

**Comment by undeconstructed** [comment]
If I may jump onto this old topic, it seems like the zoom client expects to find useful information in this file: https://forums.puri.sm/t/screen-sharing-with-zoom-blocked-by-default/7113/6

Inside the flatpak it finds:

```
NAME=Freedesktop.org
VERSION="19.08.10 (Flatpak runtime)"
VERSION_ID=19.08.10
ID=org.freedesktop.platform
```

And then reports that wayland screen sharing isn't supported. Ignoring the question of whether that's a good system: 1) is it currently possible to control what's in os-release? 2) is there a supported feature that we could encourage zoom to use?

**Comment by TingPing** [comment]
Relying on `os-release` is never the correct way to detect features, so thats an application bug.

**Comment by undeconstructed** [comment]
> Relying on `os-release` is never the correct way to detect features, so thats an application bug.

Probably yes, although potentially it's a non-technical issue, e.g. they only wish to support a feature on distros their support staff are aware of.

> Zoom should use this portal for screen capturing: https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.ScreenCast

I sent a support request, that they probably won't read.
