### ISSUE TITLE
[Bug]: org.freedesktop.Platform.GL32.nvidia-550-78 seems to miss dependencies

### ISSUE THREAD

**Issue by jpo234** [flatpak/flatpak#5837]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

40

### What architecture are you using?

x86_64

### How to reproduce

1. Requires a newish NVidia card + nvidia-550-78 driver
2. Install com.usebottles.bottles
3. Create a bottle
4. Install Ubisoft Connect
5. Run Ubisoft Connect

### Expected Behavior

Ubisoft Connect starts

### Actual Behavior

Error message:
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.550.78 not found, ignoring: Missing dependencies: **Could not find "libcrypto.so.1.1"** in LD_LIBRARY_PATH "/app/lib:/app/lib32:/home/jpo/.var/app/com.usebottles.bottles/data/bottles/runners/ge-proton9-7/files/lib:/home/jpo/.var/app/com.usebottles.bottles/data/bottles/runners/ge-proton9-7/files/lib64:/home/jpo/.var/app/com.usebottles.bottles/data/bottles/runners/ge-proton9-7/files/lib64/wine/x86_64-unix:/home/jpo/.var/app/com.usebottles.bottles/data/bottles/runners/ge-proton9-7/files/lib/wine/i386-unix", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib

### Additional Information

It seems the 32bit version of libcrypto.so.1.1 seems to be missing

**Comment by smcv** [comment]
This is not a bug in the Flatpak program, which does not have control over the contents of either runtimes or drivers.

There are three possible ways to get rid of that warning:

* the Flathub packaging of the Nvidia driver could stop providing `libnvidia-pkcs11.so.*`: this is https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/259
* or the fd.o Platform could provide OpenSSL 1.1 again: if this is wanted, it would be a request for https://gitlab.com/freedesktop-sdk/freedesktop-sdk, but that request would probably be closed as "won't fix"
* or the pressure-vessel containerization tool in Steam, which seems to be also used in Bottles, could special-case `libnvidia-pkcs11.so.*` as "it's OK if this library is present-but-broken" and silence the warning

None of those is a bug in the piece of software that is maintained at https://github.com/flatpak/flatpak, so I'm closing this as "won't fix" for this particular issue tracker.
