### ISSUE TITLE
[Bug]: Printing dialog only in English

### ISSUE THREAD

**Issue by KierPrev** [flatpak/flatpak#5842]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

6.8.11-300.fc40.x86_64

### What architecture are you using?

x86_64

### Expected Behavior

Printing dialogue should correspond to the system locale

### Actual Behavior

Printing dialog mostly in English
![imagen](https://github.com/flatpak/flatpak/assets/44746791/9297b632-b590-4c12-b4bd-5a1eb879fe7f)

**Comment by chrisawi** [comment]
What app is this? Does it happen with any others?

Please provide the output of `flatpak config`.

**Comment by chrisawi** [comment]
org.onlyoffice.desktopeditors [has set](https://github.com/flathub/org.onlyoffice.desktopeditors/blob/master/org.onlyoffice.desktopeditors.json#L22)  `LC_ALL=C.UTF-8`, which would effectively disable localization for that GTK3 print dialog. I have no idea why they did that; you can open an issue in that repo.

Can you give an example of another app where this is happening?

**Comment by hfiguiere** [comment]
Assuming the previous comment is the answer and that it is specific to that app.
