### ISSUE TITLE
missing Variant Schema Compiler from subprojects folder 

### ISSUE THREAD

**Issue by sidrat** [flatpak/flatpak#5845]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Beyond Linux From Scratch (systemd Edition) - Version r12.1-1037

### What architecture are you using?

x86_64

### How to reproduce

mkdir build
cd build 
meson setup --prefix=/usr -Dbuildtype=release ..
ninja

### Expected Behavior

ninja output

flatpak 1.15.8

    Build system helper     : YES
    Build selinux module    : NO
    Build bubblewrap        : YES
    Build dbus-proxy        : YES
    fusermount executable   : /usr/bin/fusermount3
    Use sandboxed triggers  : YES
    Use seccomp             : YES
    Privileged group        : wheel
    Use dconf               : YES
    Use libsystemd          : YES
    Use libmalcontent       : NO
    Use libzstd             : YES
    Use auto sideloading    : NO
    Wayland security context: YES

  Subprojects
    bubblewrap              : YES 1 warnings
    dbus-proxy              : YES 1 warnings
    libglnx                 : YES

  User defined options
    buildtype               : release
    prefix                  : /usr

### Actual Behavior

../common/meson.build:90:18: ERROR: Program '/sources/GIT_files/flatpak/subprojects/variant-schema-compiler/variant-schema-compiler' not found or not executable

### Additional Information

I fixed this by adding Variant Schema Compiler to the subprojects folder from
https://gitlab.gnome.org/alexl/variant-schema-compiler
and was able to build flatpack after adding 

cp -r /usr/lib/locale/locale-archive ${DIR}/usr/lib/locale/C.UTF-8
to tests/make-test-runtime.sh 

original:
mkdir -p ${DIR}/usr/lib/locale/
error occurred here:  cp -r /usr/lib/locale/C.* ${DIR}/usr/lib/locale/en_US

new:
mkdir -p ${DIR}/usr/lib/locale/
cp -r /usr/lib/locale/locale-archive ${DIR}/usr/lib/locale/C.UTF-8
cp -r /usr/lib/locale/C.* ${DIR}/usr/lib/locale/en_US

**Comment by smcv** [comment]
This project uses submodules. To compile a project that uses submodules, you need to populate the submodule directories after `git clone`, for example using `git submodule update --init`.

**Comment by smcv** [comment]
> original:
> ```
> mkdir -p ${DIR}/usr/lib/locale/
> error occurred here: cp -r /usr/lib/locale/C.* ${DIR}/usr/lib/locale/en_US
> ```
>
> new:
> ```
> mkdir -p ${DIR}/usr/lib/locale/
> cp -r /usr/lib/locale/locale-archive ${DIR}/usr/lib/locale/C.UTF-8
> cp -r /usr/lib/locale/C.* ${DIR}/usr/lib/locale/en_US
> ```

That change is resolving a valid bug (or at least avoiding an assumption that isn't true on your Linux-From-Scratch-based system), but it's introducing new assumptions and would probably not work for all distributions either. Please describe how the locale files are set up on BLFS so that we can hopefully find a way for that script to work on all distributions.

**Comment by sidrat** [comment]
ok the file structure  of the locale files are first done in the LFS book, before the BLFS is used.

mkdir -pv /{boot,home,mnt,opt,srv}
mkdir -pv /etc/{opt,sysconfig}
mkdir -pv /lib/firmware
mkdir -pv /media/{floppy,cdrom}
mkdir -pv /usr/{,local/}{include,src}
mkdir -pv /usr/lib/locale # this is where the locale-archive is placed.
mkdir -pv /usr/local/{bin,lib,sbin}
mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -pv /usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -pv /usr/{,local/}share/man/man{1..8}
mkdir -pv /var/{cache,local,log,mail,opt,spool}
mkdir -pv /var/lib/{color,misc,locate}

---------------------------------------------------------
in chapter 8.5. Glibc-2.39
Individual locales installed using the localedef program.
they are stored in /usr/share/i18n/locales/ and /usr/share/i18n/charmaps/
 
localedef -i C -f UTF-8 C.UTF-8
localedef -i cs_CZ -f UTF-8 cs_CZ.UTF-8
localedef -i de_DE -f ISO-8859-1 de_DE
localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
localedef -i de_DE -f UTF-8 de_DE.UTF-8
localedef -i el_GR -f ISO-8859-7 el_GR
localedef -i en_GB -f ISO-8859-1 en_GB
localedef -i en_GB -f UTF-8 en_GB.UTF-8
localedef -i en_HK -f ISO-8859-1 en_HK
localedef -i en_PH -f ISO-8859-1 en_PH
localedef -i en_US -f ISO-8859-1 en_US
localedef -i en_US -f UTF-8 en_US.UTF-8
localedef -i es_ES -f ISO-8859-15 es_ES@euro
localedef -i es_MX -f ISO-8859-1 es_MX
localedef -i fa_IR -f UTF-8 fa_IR
localedef -i fr_FR -f ISO-8859-1 fr_FR
localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
localedef -i is_IS -f ISO-8859-1 is_IS
localedef -i is_IS -f UTF-8 is_IS.UTF-8
localedef -i it_IT -f ISO-8859-1 it_IT
localedef -i it_IT -f ISO-8859-15 it_IT@euro
localedef -i it_IT -f UTF-8 it_IT.UTF-8
localedef -i ja_JP -f EUC-JP ja_JP
localedef -i ja_JP -f SHIFT_JIS ja_JP.SJIS 2> /dev/null || true
localedef -i ja_JP -f UTF-8 ja_JP.UTF-8
localedef -i nl_NL@euro -f ISO-8859-15 nl_NL@euro
localedef -i ru_RU -f KOI8-R ru_RU.KOI8-R
localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
localedef -i se_NO -f UTF-8 se_NO.UTF-8
localedef -i ta_IN -f UTF-8 ta_IN.UTF-8
localedef -i tr_TR -f UTF-8 tr_TR.UTF-8
localedef -i zh_CN -f GB18030 zh_CN.GB18030
localedef -i zh_HK -f BIG5-HKSCS zh_HK.BIG5-HKSCS
localedef -i zh_TW -f UTF-8 zh_TW.UTF-8

make localedata/install-locales installs in the  /usr/lib/locale folder

i don't know how other distro's setup the locale file structure , I'm using ubuntu as my host OS.

**Comment by sidrat** [comment]
can you please add this to the readme.md file 
so others don't get cought out , thank you.

git submodule update --init

**Comment by GeorgesStavracas** [comment]
Can you open a pull request for that? Happy to review and merge it

**Comment by smcv** [comment]
I merged #5800 instead, so we no longer have any submodules, and therefore `git submodule update --init` is no longer required.
