### ISSUE TITLE
Using DB like Cassandra in Flatpak

### ISSUE THREAD

**Issue by filosof86** [flatpak/flatpak#5849]
Hi all,

I wonder if it's possible (and advisable) to pack DBs like Cassandra in a flatpak and use it.  I.e. use the flatpak for serving the server-side applications. 
Can it be easily deployed, accessed from the application outside the flatpak environment, etc?

Thank you in advance for your answers!

**Comment by hfiguiere** [comment]
Flatpak is not a use case for server applications.

Nothing per see prevent from doing it, but the UX will be suboptimal.
