### ISSUE TITLE
[Feature request]: Install or update only the latest version of a specific runtime

### ISSUE THREAD

**Issue by codingepaduli** [flatpak/flatpak#5851]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I'd like to install the latest version of an app for a specific runtime.

For example, when I try to install ``org.kde.kontact``, it install the latest version available:

```
flatpak install  org.kde.kontact
Looking for matches…
Required runtime for org.kde.kontact/x86_64/stable (runtime/org.kde.Platform/x86_64/6.7) found in remote flathub
Do you want to install it? [Y/n]: 
```

I'd like to install it, but for the previous runtime ``org.kde.Platform/x86_64/6.6``.

Should be nice to have a command that automatically search the required runtime in the commit history, for example : 
``flatpak install --runtime org.kde.Platform/x86_64/6.6  org.kde.kontact``

The same feature request is for the update of an app. It should be updated only if the runtime requirement is fulfilled.

Thank you for your help

**Comment by hfiguiere** [comment]
Not gonna happen. By design runtimes are not interchangeable because the package is build against its sdk.
