### ISSUE TITLE
Environment DRI_PRIME causing segfault on everything

### ISSUE THREAD

**Issue by TegarOk** [flatpak/flatpak#5859]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [ ] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

41

### What architecture are you using?

x86_64

### How to reproduce

1. Open terminal
2. Run `flatpak run --env=DRI_PRIME=1 io.mpv.Mpv or flatpak --env=DRI_PRIME=1 com.obsproject.Studio`

### Expected Behavior

1. Open Terminal
2. Run `flatpak run --env=DRI_PRIME=1 io.mpv.Mpv or similar`
3.  Windows show up

### Actual Behavior

1. Run the application with DRI_PRIME=1 option.
2. No window and no log, dmesg report segfault

Example Error:
`vo[45870]: segfault at 7f33982a18a4 ip 00007eeb98950155 sp 00007eeb915ff730 error 4 in libEGL_mesa.so.0.0.0[7eeb98933000+2c000] likely on CPU 15 (core 7, socket 0)`
`obs[47158]: segfault at 7b7943c248a4 ip 00007b31442d3155 sp 00007ffcf8cb5460 error 4 in libEGL_mesa.so.0.0.0[7b31442b6000+2c000] likely on CPU 15 (core 7, socket 0)`

This happening in recent version. seems like Mesa or the SDK messed up, i already try `org.freedesktop.Platform.GL.default` to older version seems doesnt fix it the behaviour.

### Additional Information

Nearly all application that are heavy on GPU stutter the entire desktop because my main GPU is low end (Only for display). My GPU is HD 5570 & RX 570.
There is a fix for this, but this fix is temporary and i dont know what happen if you have 2 Vulkan supported GPU. Adding `MESA_LOADER_DRIVER_OVERRIDE=zink` to Environment Variable will force the application to run on GPU that support Vulkan.

I dont know where to report this bug, so im sorry if this is irrelevant here.
Note that `DRI_PRIME=1` work flawlessly without Flatpak or using the native binary from distro, i already tested on my Debian Testing.

**Comment by hfiguiere** [comment]
I doubt this is a flatpak issue.

**Comment by TegarOk** [comment]
> I doubt this is a flatpak issue.

Where do you think should i report this?
Since this happening in both applications, so i dont think i should report to application maintainer (like OBS or MPV).

**Comment by TegarOk** [comment]
It fixed in the latest version of `org.freedesktop.Platform.GL.default` (Other should follow too).
