### ISSUE TITLE
Can't reuse host fontconfig caches

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#589]
Flatpak runtimes and app can contain fonts, and the fontconfig setup in the runtime is set up to pick these, and the caches for it. This works fine, as long as you ensure the caches record mtime=0, which flatpak-builder does.

However, flatpak also exposes the host system and user fonts in /run/host/fonts and /run/host/user-fonts.
Unfortunately we can't reuse the host caches for these, so the first time the app is started we need to scan these directories and regenerate the cache, which is then stored in the per-app cache location.

This is unfortunate, but I don't see a great way to solve this. The cache is looked up by hashing the absolute pathname of the directory, and the two will differ between the host and the sandbox.

**Comment by alexlarsson** [comment]
Also, as part of this we probably need to export the system fontconfig config files, as these affect how the system fonts are supposed to be rendered.

**Comment by alexlarsson** [comment]
Iniial work for this is happening here: https://bugs.freedesktop.org/show_bug.cgi?id=101889

**Comment by matthiasclasen** [comment]
Is this fixed now ?

**Comment by alexlarsson** [comment]
This is fixed if you're using the 2.13 fontconfig on the host.
