### ISSUE TITLE
Question regarding env. variables prevalence

### ISSUE THREAD

**Issue by Tiagoquix** [flatpak/flatpak#5893]
Hello there. I have a question about env. variables that I was not able to found the answer.

Suppose I specify an override (via `flatpak override`) or a runtime option (via `flatpak run`), be it either setting an env. variable or unsetting it (empty value). Then, when the programs opens, it follows its own shell script to `export` new variables.

For example, think that I unset (clear) the env. variable `TEST_ONE` via `flatpak override` `unset-env`, but `program.sh` has:
```bash
#!/bin/bash
export TEST_ONE=POSITIVE
/usr/bin/program
```
What would prevail is the order of operations. But what is the order of operations?

Does Flatpak only unset the env. variable before the program does anything, or does it force the env. variable to be unset at all times, no matter what happens?

I think the prevalence is that it unsets first, and if the program by itself `export`s the same variable, then the latter would prevail, as Flatpak would only impact the launch process, and not the running program afterwards (in regards to env. variables).

-------------------------------------

Additional questions:
1. How can I check the env. variables a sandboxed Flatpak application is using? Using `export` only gives me the env. variables of the current shell. Can I, like, run a terminal inside the sandboxed environment to check them?
2. Why is that when I unset an env. variable via `flatpak override`, it adds the same variable for both `[Environment]` (where the variable is set to an empty value), and `[Context]` (where the variable is in the `unset-environment` list). As far as I can tell, this is done to mantain compatibility with old Flatpak versions. If so, is there anything more to it, or is this just made for compatibility reasons?

-------------------------------------

It might be interesting to include the answers to my questions in the Flatpak documentation.
Thanks in advance for your attention.

**Comment by rusty-snake** [comment]
> Can I, like, run a terminal inside the sandboxed environment to check them?

In the case you want to run a terminal inside the sandbox, you need to install one: https://flathub.org/apps/search?q=terminal

In the more likely case of a shell: `flatpak run --command=/bin/sh <APP-ID>`

> How can I check the env. variables a sandboxed Flatpak application is using?

`tr '\0' '\n' </proc/PID/environ`

**Comment by smcv** [comment]
> Does Flatpak only unset the env. variable before the program does anything

Yes.

> or does it force the env. variable to be unset at all times, no matter what happens?

No. Even if we wanted that behaviour, I don't think it would be possible to implement it (or at least, I don't see how).

> Why is that when I unset an env. variable via flatpak override, it adds the same variable for both [Environment] (where the variable is set to an empty value), and [Context] (where the variable is in the unset-environment list). As far as I can tell, this is done to mantain compatibility with old Flatpak versions.

Yes, it's for backwards-compatibility. Older Flatpak versions didn't implement `unset-environment`, so the closest you could get to unsetting an environment variable was to set it to an empty value. (See this project's commit history for more information.)
