### ISSUE TITLE
[Bug]: Zotero 7 plugin

### ISSUE THREAD

**Issue by Gigiux** [flatpak/flatpak#5899]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

40

### What architecture are you using?

x86_64

### How to reproduce

1. install Zotero 7 (or use the upgraded version from pre-installed a fully functioning zotero)
2. Go to Zotero>Tools>plugins
3. You will see a link to zotero website for an xpi file, but the guys from zotero told me such a file is no longer available but fully incorporated within zotero installer.
4. go to LibreOffice Writer, try to use zotero with the icon installed in the previous version of zotero
5. zotero crashes
6. Disinstall zotero from LO Writer plugin amanger
7. it is no longer possible to re-install zotero plugin

### Expected Behavior

Insert references and modify references as needed.

### Actual Behavior

Crash

### Additional Information

The problem has been reported by several people on forums eg:
https://forums.zotero.org/discussion/comment/470963#Comment_470963
https://github.com/flathub/org.zotero.Zotero/issues/207

**Comment by smcv** [comment]
App-specific issues should be reported to the app's issue reporting channel, which in this case was already done (https://github.com/flathub/org.zotero.Zotero/issues/207).

This issue tracker is for Flatpak itself. We are not responsible for individual apps.
