### ISSUE TITLE
Git : support recursive submodules cloning

### ISSUE THREAD

**Issue by jcelerier** [flatpak/flatpak#59]
When your git repository has a submodule on another lib and this other lib itslef has submodules...

Would it be a matter of adding "--recursive" in  
https://github.com/flatpak/flatpak/blob/501802270ed1b8860987c104681b1066e57b1f1c/builder/builder-source-git.c#L465

?

**Comment by alexlarsson** [comment]
No, thats not quite enought. We locally mirror each of the involved git repos and rewrite the submodule urls to point to the local mirrors, while a --recursive thing will make "git submodule update" pull from the network.

Do you know of a repo that uses this so we can test on it?

**Comment by jcelerier** [comment]
Well the one I work on ( https://github.com/OSSIA/i-score ) does but I haven't started porting to flatpak yet so I don't think that it would be useful to you.

**Comment by hbons** [comment]
aren't git submodules deprecated by git subtree?

**Comment by jcelerier** [comment]
Imho submodules and subtrees are both useful different approaches. Submodules link to a particular commit while subtrees copies the whole repository into yours if I am not mistaken.

**Comment by alexlarsson** [comment]
I believe this should work fine in master now (gnome-games uses this and now builds).
