### ISSUE TITLE
[Bug]: flatpak remote-ls shows installed version instead of remote version

### ISSUE THREAD

**Issue by gapan** [flatpak/flatpak#5903]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Salix 15.0

### What architecture are you using?

x86_64

### How to reproduce

1. Have some old versions of apps installed that have available updates that are newer versions than the installed ones
2. Run `flatpak remote-ls --updates`

### Expected Behavior

For apps that have available updates, according to the documentation, the available versions should be displayed. If I visit the app pages in flathub.org I see there are indeed newer versions available. For specific examples, I can currently see:

* https://flathub.org/apps/com.mongodb.Compass version 1.43.5
* https://flathub.org/apps/com.obsproject.Studio version 30.2.3
* https://flathub.org/apps/com.skype.Client version 8.125.0.201
* https://flathub.org/apps/us.zoom.Zoom version 6.1.6.1013

### Actual Behavior

What I actually get are the versions that I have already installed, not the available ones I would be upgrading to.
```
$ flatpak remote-ls --app --updates
Name                   Application ID               Version           Branch       Arch
MongoDB Compass        com.mongodb.Compass          1.43.4            stable       x86_64
OBS Studio             com.obsproject.Studio        30.2.0            stable       x86_64
Skype                  com.skype.Client             8.119.0.201       stable       x86_64
Zoom                   us.zoom.Zoom                 6.0.12.5501       stable       x86_64
$ flatpak list --app
Name                            Application ID                                 Version              Branch          Installation
MongoDB Inc.                    com.mongodb.Compass                            1.43.4               stable          system
OBS Project                     com.obsproject.Studio                          30.2.0               stable          system
Microsoft Corporation           com.skype.Client                               8.119.0.201          stable          system
zoom.us                         us.zoom.Zoom                                   6.0.12.5501          stable          system
```
(I have removed other apps from the `flatpak list` output which didn't have available updates)

### Additional Information

This is somewhat related to issue #3685 as it is impossible to determine the package version that I would be upgrading to.

**Comment by gapan** [comment]
I should add that there is same issue with `remote-info`.

```
$ flatpak remote-info flathub us.zoom.Zoom

Zoom - Video Conferencing, Web Conferencing, Webinars, Screen Sharing

        ID: us.zoom.Zoom
       Ref: app/us.zoom.Zoom/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 6.0.12.5501
   License: LicenseRef-proprietary
Collection: org.flathub.Stable
  Download: 5,0 MB
 Installed: 10,9 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: babd2544653d8b4cc150f8e856a6971e92b9d9d1e0e020093c88a431e267584b
    Parent: 1c74b3b1b17e512c6998c7cc1fde52161f9ebc5ac55be6a012f3b65e9bc41e8d
   Subject: Replace xdg-desktop-portal path in correct executable path (5e2ae78a)
      Date: 2024-08-15 18:58:32 +0000
```

**Comment by lostfictions** [comment]
@gapan Have you encountered this any more since then? I'm seeing the same issue and opened #5974.

**Comment by gapan** [comment]
@lostfictions Actually yes! It previously worked fine, but I just tried it and the problem showed up again!
