### ISSUE TITLE
[Bug]: `/var/lib/flatpak/repo/objects/` taking up 295GB of space

### ISSUE THREAD

**Issue by G2-Games** [flatpak/flatpak#5904]
### Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

40

### What architecture are you using?

x86_64

### How to reproduce

1. Run `du -h -s /var/lib/flatpak/repo/objects/` to check the size of the directory.

### Expected Behavior

I have seen some other issues saying this directory takes up around 9GB, 12GB, 1.6GB, 20GB, etc. 
Referenced issues: #3894, #4270, #2147, #3542

### Actual Behavior

The command returns `296G    /var/lib/flatpak/repo/objects/`. 

### Additional Information

This is excessive, and while I do have quite a few applications installed through Flatpak it hardly makes sense for it to be nearly 300GB! Using `flatpak list --columns=size` gives me a list of installed sizes, and the largest installed program is 2.5GB, and all the others do not come even close to the full size of the directory.

Additionally, I have attempted to use `flatpak remove --unused` and `flatpak repair` with no change in the space taken.

I love using Flatpak otherwise though, thank you for developing this awesome platform!

**Comment by G2-Games** [comment]
![image](https://github.com/user-attachments/assets/67891f10-2f30-4fcf-914d-077ec23a4c82)

Extra context, here is my root directory when viewed with Filelight.

**Comment by G2-Games** [comment]
After reading #5057, I checked the folder with `du -shl /var/lib/flatpak/repo/objects/` and it still reports the same size.

**Comment by unconfused** [comment]
I have the same issue.  /var/lib/flatpak/repo/objects consumes 50% of my SSD.

Flatpak 1.15.8
Fedora 40

**Comment by G2-Games** [comment]
An update, checking it again today and it is now 301GB, so it's progressively getting worse. Eventually I will run out of disk space at this rate.

**Comment by firstuanl** [comment]
Can it be deleted?

**Comment by G2-Games** [comment]
@firstuanl, is it safe to delete this data?

**Comment by firstuanl** [comment]
safe
No abnormalities were detected , only some icon is missing.

**Comment by G2-Games** [comment]
I was able to fix this by running `flatpak repair` as root. This reduced the size to 21GB, which is reasonable, but still large.

**Comment by G2-Games** [comment]
As I have been using Flatpak on my system since my last update on this bug report, the size of the base directory has grown to 29GB from 21GB. I have definitely not installed 8GB worth of flatpak-only applications, so I do not understand where this size is coming from. It is by far the largest folder in my system's root.

**Comment by razzeee** [comment]
Probably runtime updates and apps switching to newer/supported runtimes behind the scenes.

This might be helpful to grasp it a bit better:
https://blogs.gnome.org/wjjt/2021/11/24/on-flatpak-disk-usage-and-deduplication/
