### ISSUE TITLE
[Feature request]: Enable .flatpak bundle files to be downloadable via the flathub webpage

### ISSUE THREAD

**Issue by thepragmaticmero** [flatpak/flatpak#5906]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I was traveling to an inside province of my home country Peru (cute country btw, go visit, there are cute llamas and alpacas). And I encountered a very peculiar problem for my setup. I have a miniPC and small screen that I carry with me when I travel. The home I was staying at had no internet but a nearby coffee shop had. I couldn't carry my minipc to that place. So I resorted to download my apps through my phone. Question is, I couldn't "download" the apps from flathub. I had to resort to downloading .AppImages (eew). I know that flatpak has the capability of offline installs. But appears to be that flathub doesn't.

https://github.com/rustdesk/rustdesk/releases/download/1.3.0/rustdesk-1.3.0-x86_64.flatpak

I downloaded successfully this app. But it was outside of flathub, and most apps don't have that option, it was annoying to be honest. I tried to fix the problem using Termux on my phone but apparently even with root enabled (my phone has root) I couldn't install flatpak, I had to change my kernel to do that lol. Imagine changing the kernel in your phone to download an application xddd.

**Comment by smcv** [comment]
> I tried to fix the problem using Termux on my phone but apparently even with root enabled (my phone has root) I couldn't install flatpak

This is "won't fix", or more accurately "can't fix": if the Android kernel and OS won't allow what Flatpak needs to do, then Flatpak can't work.

**Comment by smcv** [comment]
> I know that flatpak has the capability of offline installs. But appears to be that flathub doesn't.

That's a feature request for Flathub, not Flatpak, so please report it to https://github.com/flathub/flathub/issues.
