### ISSUE TITLE
[Feature request]: cryptographically signed flatpak apps

### ISSUE THREAD

**Issue by olumolu** [flatpak/flatpak#5908]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

The integration of a signature verification mechanism for Flatpak updates would significantly enhance application security. This feature, similar to the signed APKs used in Android, would prevent malicious actors from distributing unauthorized updates. By verifying the authenticity of updates, we can significantly reduce the risk of compromised applications.

**Comment by rusty-snake** [comment]
#5878 opened one month ago by @olumolu.

Looks very much the same.
