### ISSUE TITLE
[Bug]: Fatal crashes, seemingly at random, in multiple apps

### ISSUE THREAD

**Issue by hazelthatsme** [flatpak/flatpak#5909]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

40,  6.10.4-200.fc40.x86_64 (reproduced on multiple kernel versions over weeks)

### What architecture are you using?

x86_64

### How to reproduce

1. Launch an app through Flatpak through KRunner, console, shortcuts
2. Seemingly at random, receive notification from abrt-applet that the app has crashed, or check console for error.

### Expected Behavior

The application starts.

### Actual Behavior

The application has to be started multiple times until it runs without crashing. When this occurs while running through console, this error appears:
![image](https://github.com/user-attachments/assets/e64cfa9f-e7b3-4e40-bc27-de23ce21da9d)

Fatal error "Failed to reserve virtual memory for CodeRange" is identical between my Flatpak apps (Signal, FreeTube and Vesktop)

**Comment by hazelthatsme** [comment]
After a few tries, I did indeed get this to fail with the Chromium Flatpak app. There is, however,

**Comment by smcv** [comment]
https://issues.chromium.org/issues/335524387 looks similar, so another possible cause is that the configured SELinux policy is preventing these apps from working as intended. Do you get similar `avc: denied { execheap }` SELinux denials in your system log (systemd Journal) when one of the affected apps fails to start?

If yes, please report this to your OS vendor (Fedora).

**Comment by hazelthatsme** [comment]
After a few tries was able to get the same fail with Chromium. Will report to Fedora, thank you very much.

**Comment by hazelthatsme** [comment]
In case someone finds this with the same issues, here's an already existing thread on Fedora Discussions about the issue: https://discussion.fedoraproject.org/t/selinux-execheap-denials/120638/47
