### ISSUE TITLE
Flatpak documentation doesn’t mention rename-icon needs to be stripped of suffix

### ISSUE THREAD

**Issue by jurf** [flatpak/flatpak#591]
I believe this has to do with the fact that I’m placing the icons there manually, instead of cmake.

This is the snippet I used:
```
        …
        {
          "type": "shell",
          "commands": [ "for i in 16x16 32x32 128x128 256x256 512x512 1024x1024; do install -Dm644 resources/iconsets/artwork/icon_${i}.png /app/share/icons/hicolor/${i}/apps/scribus.png; done" ]
        }
        …
```

I get this error: 
```
Renaming scribus.appdata.xml to net.scribus.Scribus.appdata.xml
Renaming scribus.desktop to net.scribus.Scribus.desktop
Error: icon scribus.png not found below /home/juraj/Stavby/flatpak/scribus/scribus/files/share/icons
```
Changing it to `cp` does nothing.

If I changed the destination filename to `net.scribus.Scribus.png` (which is the id also) flatpak exports them correctly, but the desktop file doesn’t use them so it’s useless to do it that way.

**Comment by LiliC** [comment]
Files that are exported by a flatpak must be prefixed using the application ID. See [here](http://docs.flatpak.org/en/latest/flatpak-builder.html?highlight=desktop#file-renaming) and [here](http://docs.flatpak.org/en/latest/elements-of-a-flatpak-app.html?highlight=export#application-structure).

Just replace the icon name in your desktop file for example with `sed` to `net.scribus.Scribus.png`, or specify a custom `.desktop` file and export it manually to `/app/share/...`.

**Comment by DoctorJellyface** [comment]
Of course I can do that, but why does the `rename-icon` option exist then, since it combines both steps in a much more clear and predictable manner?

**Comment by alexlarsson** [comment]
What is the rename-icon value? It should not contain the suffix (i.e. .png).

**Comment by DoctorJellyface** [comment]
It contained the suffix. However that’s not mentioned in the documentation, and the other rename things require the suffix so it’s quite confusing.
