### ISSUE TITLE
[Bug]: assertion failure in libostree: sock_cb: code should not be reached

### ISSUE THREAD

**Issue by LispyIsMuch** [flatpak/flatpak#5926]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.10

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

6.10.7-arch1-1

### What architecture are you using?

x86_64

### How to reproduce

I am not sure what caused this to happen but here is what I have tried so far:
- `sudo flatpak repair --system` and `flatpak repair --user`
- Tried multiple versions of OStree by `sudo downgrade ostree`
- Deleted cache after `yay -R flatpak` by `yay -Yc`
- I did `coredumpctl debug {my most recent flatpak PID}` and this the results:
```
> coredumpctl debug 63954
           PID: 63954 (flatpak)
           UID: 1000 (lispy)
           GID: 1000 (lispy)
        Signal: 6 (ABRT)
     Timestamp: Wed 2024-09-04 17:51:32 SAST (15min ago)
  Command Line: flatpak install flathub org.gnome.Sdk//44
    Executable: /usr/bin/flatpak
 Control Group: /user.slice/user-1000.slice/user@1000.service/kitty-4818-0.scope
          Unit: user@1000.service
     User Unit: kitty-4818-0.scope
         Slice: user-1000.slice
     Owner UID: 1000 (lispy)
       Boot ID: 971c915afaee4eabb1bbd8517abf871f
    Machine ID: dc1d3b9e28d14626a2396a83d9408c0c
      Hostname: lispix
       Storage: /var/lib/systemd/coredump/core.flatpak.1000.971c915afaee4eabb1bbd8517abf871f.63954.1725465092000000.zst (present)
  Size on Disk: 1.4M
       Message: Process 63954 (flatpak) of user 1000 dumped core.
                
                Stack trace of thread 63954:
                #0  0x000078feb0dcc3f4 n/a (libc.so.6 + 0x963f4)
                #1  0x000078feb0d73120 raise (libc.so.6 + 0x3d120)
                #2  0x000078feb0d5a4c3 abort (libc.so.6 + 0x244c3)
                #3  0x000078feb18bd11b n/a (libglib-2.0.so.0 + 0x1e11b)
                #4  0x000078feb1928d79 g_assertion_message_expr (libglib-2.0.so.0 + 0x89d79)
                #5  0x000078feb153188b n/a (libostree-1.so.1 + 0xa488b)
                #6  0x000078feb11e72af n/a (libcurl.so.4 + 0x1e2af)
                #7  0x000078feb11e7b04 n/a (libcurl.so.4 + 0x1eb04)
                #8  0x000078feb121b463 curl_multi_cleanup (libcurl.so.4 + 0x52463)
                #9  0x000078feb153128f n/a (libostree-1.so.1 + 0xa428f)
                #10 0x000078feb1693065 g_object_unref (libgobject-2.0.so.0 + 0x21065)
                #11 0x000078feb14f1b50 ostree_repo_pull_with_options (libostree-1.so.1 + 0x64b50)
                #12 0x00005b195042eed3 n/a (flatpak + 0x117ed3)
                #13 0x00005b195040c7ee n/a (flatpak + 0xf57ee)
                #14 0x00005b195041226c n/a (flatpak + 0xfb26c)
                #15 0x00005b19503a0d13 n/a (flatpak + 0x89d13)
                #16 0x00005b195037cce7 n/a (flatpak + 0x65ce7)
                #17 0x00005b195035436a n/a (flatpak + 0x3d36a)
                #18 0x000078feb0d5be08 n/a (libc.so.6 + 0x25e08)
                #19 0x000078feb0d5becc __libc_start_main (libc.so.6 + 0x25ecc)
                #20 0x00005b1950355b35 n/a (flatpak + 0x3eb35)
                
                Stack trace of thread 63956:
                #0  0x000078feb0e4163d __poll (libc.so.6 + 0x10b63d)
                #1  0x000078feb195ee0d n/a (libglib-2.0.so.0 + 0xbfe0d)
                #2  0x000078feb18fb795 g_main_context_iteration (libglib-2.0.so.0 + 0x5c795)
                #3  0x000078feb18fb7f2 n/a (libglib-2.0.so.0 + 0x5c7f2)
                #4  0x000078feb192c1b6 n/a (libglib-2.0.so.0 + 0x8d1b6)
                #5  0x000078feb0dca39d n/a (libc.so.6 + 0x9439d)
                #6  0x000078feb0e4f49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 63955:
                #0  0x000078feb0e4d1fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000078feb1957eb0 g_cond_wait (libglib-2.0.so.0 + 0xb8eb0)
                #2  0x000078feb18c495c n/a (libglib-2.0.so.0 + 0x2595c)
                #3  0x000078feb19317f7 n/a (libglib-2.0.so.0 + 0x927f7)
                #4  0x000078feb192c1b6 n/a (libglib-2.0.so.0 + 0x8d1b6)
                #5  0x000078feb0dca39d n/a (libc.so.6 + 0x9439d)
                #6  0x000078feb0e4f49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 63958:
                #0  0x000078feb0e4163d __poll (libc.so.6 + 0x10b63d)
                #1  0x000078feb195ee0d n/a (libglib-2.0.so.0 + 0xbfe0d)
                #2  0x000078feb18fcfa7 g_main_loop_run (libglib-2.0.so.0 + 0x5dfa7)
                #3  0x000078feb138f674 n/a (libpolkit-agent-1.so.0 + 0x4674)
                #4  0x000078feb192c1b6 n/a (libglib-2.0.so.0 + 0x8d1b6)
                #5  0x000078feb0dca39d n/a (libc.so.6 + 0x9439d)
                #6  0x000078feb0e4f49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 63960:
                #0  0x000078feb0e4163d __poll (libc.so.6 + 0x10b63d)
                #1  0x000078feb195ee0d n/a (libglib-2.0.so.0 + 0xbfe0d)
                #2  0x000078feb18fb795 g_main_context_iteration (libglib-2.0.so.0 + 0x5c795)
                #3  0x000078feb1a0f2fe n/a (libdconfsettings.so + 0x62fe)
                #4  0x000078feb192c1b6 n/a (libglib-2.0.so.0 + 0x8d1b6)
                #5  0x000078feb0dca39d n/a (libc.so.6 + 0x9439d)
                #6  0x000078feb0e4f49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 63957:
                #0  0x000078feb0e4163d __poll (libc.so.6 + 0x10b63d)
                #1  0x000078feb195ee0d n/a (libglib-2.0.so.0 + 0xbfe0d)
                #2  0x000078feb18fcfa7 g_main_loop_run (libglib-2.0.so.0 + 0x5dfa7)
                #3  0x000078feb17e3d04 n/a (libgio-2.0.so.0 + 0x112d04)
                #4  0x000078feb192c1b6 n/a (libglib-2.0.so.0 + 0x8d1b6)
                #5  0x000078feb0dca39d n/a (libc.so.6 + 0x9439d)
                #6  0x000078feb0e4f49c n/a (libc.so.6 + 0x11949c)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/flatpak...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Reading symbols from /home/lispy/.cache/debuginfod_client/329031aeaf9378dbf9900f9dd0523130a7c045c2/debuginfo...
[New LWP 63954]
[New LWP 63956]
[New LWP 63955]
[New LWP 63958]
[New LWP 63960]
[New LWP 63957]
Downloading separate debug info for /usr/lib/libcurl.so.4
Downloading separate debug info for system-supplied DSO at 0x78feb1a20000                                                       
[Thread debugging using libthread_db enabled]                                                                                   
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `flatpak install flathub org.gnome.Sdk//44'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
[Current thread is 1 (Thread 0x78feafc2f680 (LWP 63954))]
```

### Expected Behavior

I just want to install an application which is only available on flatpak, I want to install `flatpak install flathub io.github.dgsasha.Remembrance` but I instead I get:

### Actual Behavior

```
Looking for matches…
Required runtime for io.github.dgsasha.Remembrance/x86_64/stable (runtime/org.gnome.Platform/x86_64/46) found in remote flathub
Do you want to install it? [Y/n]: y

io.github.dgsasha.Remembrance permissions:
    ipc                            network         fallback-x11         pulseaudio
    wayland                        x11             dri                  dbus access [1]
    system dbus access [2]

    [1] org.freedesktop.secrets
    [2] org.freedesktop.login1


        ID                                                   Branch              Op        Remote         Download
 1. [/] io.github.dgsasha.Remembrance.Locale                 stable              i         flathub            1.0 kB / 42.2 kB
 2. [ ] org.freedesktop.Platform.GL.default                  23.08               i         flathub        < 170.7 MB
 3. [ ] org.freedesktop.Platform.GL.default                  23.08-extra         i         flathub        < 170.7 MB
 4. [ ] org.freedesktop.Platform.GL.nvidia-560-35-03         1.4                 i         flathub        < 323.4 MB
 5. [ ] org.freedesktop.Platform.VAAPI.Intel                 23.08               i         flathub         < 13.4 MB
 6. [ ] org.freedesktop.Platform.openh264                    2.4.1               i         flathub        < 976.5 kB
 7. [ ] org.gnome.Platform.Locale                            46                  i         flathub        < 380.0 MB (partial)
 8. [ ] org.gnome.Platform                                   46                  i         flathub        < 347.5 MB
 9. [ ] io.github.dgsasha.Remembrance                        stable              i         flathub          < 6.2 MB

Installing 1/9…                        0%  0 bytes/s**
OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached
Bail out! OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached
[10]    77528 IOT instruction (core dumped)  flatpak install flathub io.github.dgsasha.Remembrance

```

### Additional Information

_please help me I spent like 9 hours trying to fix this, this is literally my first issue on github, that's how desperate I am._

**Comment by smcv** [comment]
> OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached

This is likely to be a bug in libostree rather than in Flatpak.

**Comment by slonkazoid** [comment]
turned out to be a mismatch between system libcurl and the version of libcurl flatpak was linked against

**Comment by LispyIsMuch** [comment]
Yeah turns out it was just because I was using the git version of curl, not a OSTree issue nor flatpak issue.

**Comment by clipcarl** [comment]
I'm having the same issue right now on current Alpine Edge with flatpak 1.14.10 / ostree 2024.5 / libcurl 8.10.0 / curl 8.10.0. Perhaps dependencies aren't being specified correctly?

**Comment by clipcarl** [comment]
On Alpine Edge downgrading curl / libcurl from the current 8.10.0 to 8.9.1 fixes the problem. Should this particular version of curl be a hard dependency for flatpak?

**Comment by clipcarl** [comment]
Perhaps this issue should be reopened because it is clearly still a problem.

**Comment by ell1e** [comment]
Seeing the same thing on Alpine.

**Comment by slonkazoid** [comment]
> On Alpine Edge downgrading curl / libcurl from the current 8.10.0 to 8.9.1 fixes the problem. Should this particular version of curl (8.9) be a hard dependency for flatpak?
> Perhaps this issue should be reopened because it is clearly still a problem.

is this not the responsibility of the alpine maintainers? or does the flatpak team maintain the alpine package as well?

**Comment by ell1e** [comment]
It seems like flatpak doesn't pin the libcurl version in any way: https://github.com/flatpak/flatpak/blob/79abc960a6d695af3928aa7c5ca34b059e0d55f5/meson.build#L181 so I get that it working only with the specific version it was built with may be surprising. But I'm not a packager so I don't know what the usual expectation is.

**Comment by nekopsykose** [comment]
> so I get that it working only with the specific version it was built with may be surprising

the issue there is not 'runtime dep doesnt match buildtime dep', but rather a new change in libcurl itself that breaks it; a rebuild wouldn't fix it.

pinning the version also doesn't fix the issue at all- it just gives someone 'i told you so' power (if they used a newer version against someone's wishes), but the fundamental error doesn't get fixed and it would still be 'broken with the new version'.

> Perhaps this issue should be reopened because it is clearly still a problem.

this issue report (at the time it was made) did not have a way to run into [the actual issue](https://github.com/ostreedev/ostree/issues/3299) you are experiencing (said code was not merged in curl yet), even though the error message is the same, so this specific report is actually unrelated. and it has already been reported to ostree in the correct place; you can follow that to see how it gets resolved (since it's an issue either in libcurl or in ostree). but this issue is the wrong place :)

**Comment by justaCasualCoder** [comment]
same issue here

**Comment by clipcarl** [comment]
> it has already been reported to ostree in the correct place; you can follow that to see how it gets resolved (since it's an issue either in libcurl or in ostree). but this issue is the wrong place :)

I think the correct place is **both** here and in whichever other project the flatpak developers open there own bug report.

As a user I did not install ostree. I did not install libcurl. I installed **flatpak** and from my perspective **flatpak** is what isn't working. So while the cause of the problem might be in some other package that flatpak depends on it's really still a bug in flatpak too. 

I think the correct way to handle this is to leave this bug open here and to link its resolution to the resolution of the appropriate bug in ostree or curl.

**Comment by comio** [comment]
See https://bugs.gentoo.org/939813

**Comment by Zeitsperre** [comment]
Seeing this today on Void Linux for Flatpak 1.15.10 with `curl`/`libcurl` 8.10.1 and `ostree` 2024.3.

**Comment by SpidFightFR** [comment]
Same as well, using Void-Linux. A recompilation against up to date curl and ostree doesn't help.

**Comment by smcv** [comment]
This appears to be a libostree bug, https://github.com/ostreedev/ostree/issues/3299, triggered by updating libcurl. It is not a Flatpak bug and there is no Flatpak change that will fix it.

Patches are available in libostree PR https://github.com/ostreedev/ostree/pull/3307 but are not yet included in a libostree release. Until a libostree update becomes available, rolling release distributions should either apply those patches, or configure libostree to use libsoup instead of libcurl.

We do not need additional reports that other rolling release distributions are affected. Adding comments here will not get a libostree release out any sooner: the Flatpak maintainers are not able to make new libostree releases happen.

**Comment by SpidFightFR** [comment]
> This appears to be a libostree bug, [ostreedev/ostree#3299](https://github.com/ostreedev/ostree/issues/3299), triggered by updating libcurl. It is not a Flatpak bug and there is no Flatpak change that will fix it.
> 
> Patches are available in libostree PR [ostreedev/ostree#3307](https://github.com/ostreedev/ostree/pull/3307) but are not yet included in a libostree release. Until a libostree update becomes available, rolling release distributions should either apply those patches, or configure libostree to use libsoup instead of libcurl.
> 
> We do not need additional reports that other rolling release distributions are affected. Adding comments here will not get a libostree release out any sooner: the Flatpak maintainers are not able to make new libostree releases happen.

i try to upstream the ostree patch on the voidlinux side, thank you for your answer tho ! :+1:

**Comment by cgwalters** [comment]
https://github.com/ostreedev/ostree/releases/tag/v2024.8 includes the fix for this.

**Comment by SpidFightFR** [comment]
> https://github.com/ostreedev/ostree/releases/tag/v2024.8 includes the fix for this.

aye ! thanks for the tag !
Indeed your patch already fixed the issue within Void, and it's up-streamed in the void repos. I'll check if i can update ostree by the end of the week. Thanks a lot for your participation in the community fronts ! :pray:
