### ISSUE TITLE
[Not a Bug - help needed] change default location of flatpak (flathub) apps downloaded from discover app on arch kde to home directory

### ISSUE THREAD

**Issue by whycook** [flatpak/flatpak#5949]
Hi i need some help i did some research on it but was unsuccessful,
can someone help me to change the location of all the discover apps on arch kde 6 installed and future installations to home directory from /var/lib/flatpak cause i thought 25 GB would be more than enough for root partition i have like 200GB free on home directory /home/best
ik this is duplicate but i wanted so that my all app's data would be preserved there were some issues i faced using symbolic method like old apps didnt sync with discover app and all... maybe i did the wrong way so i wanted someone to give me step by step commands
thank you

**Comment by chrisawi** [comment]
This isn't a support forum. Please open a topic on the [Flathub Discourse](https://discourse.flathub.org/). If you link it back here, I'll respond there.
