### ISSUE TITLE
[Bug]: flatpak error updating/installing app's

### ISSUE THREAD

**Issue by ljpinho** [flatpak/flatpak#5950]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Debian

### Linux distribution version

6.10.6+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.6-1~bpo12+1 (2024-08-26) x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. sudo flatpak update
2. ... [Y/n]

### Expected Behavior

Update flatpak apps installed

### Actual Behavior

Installing 1/9…**
OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:526:sock_cb: code should not be reached
Bail out! OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:526:sock_cb: code should not be reached
Aborted

**Comment by smcv** [comment]
This is [a libostree bug](https://github.com/ostreedev/ostree/issues/3299), fixed in 2024.8. Are you using a backport of libcurl?

I would recommend not using backported library packages unless you have a particular reason to need the newer version.

We'll probably need to do a stable-update of libostree in Debian, but that's something for Debian rather than upstream.

**Comment by ljpinho** [comment]
Yes, I'm using a backport of libcurl and now I don't figure out how to downgrade!

**Comment by ljpinho** [comment]
Thank you @smcv
