### ISSUE TITLE
[Bug]: flatpak seems to prevent bubblewrap from working inside the flatpak

### ISSUE THREAD

**Issue by benaryorg** [flatpak/flatpak#5953]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.6

### What Linux distribution are you using?

NixOS

### Linux distribution version

24.05

### What architecture are you using?

x86_64

### How to reproduce

1. `flatpak run net.lutris.Lutris`
1. click any game/application in Lutris and select "Open Bash Terminal" in the extra menu at the bottom
1. in the opened terminal window try to run `bwrap --unshare-all --share-net --ro-bind / / /bin/sh`

### Expected Behavior

Running bubblewrap inside flatpak should (IMHO) Just Work™ since it can be used to further sandbox individual games from a "game launcher" PoV, plus other applications may make use of bubblewrap for some shenanigans too (though I can't think of something off the top of my head).

### Actual Behavior

```text
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
```

### Additional Information

On my machine I can nest bubblewrap arbitrarily deeply, and I would like to use this in Steam or Lutris to do some hacky stuff like providing a Command Prefix (Lutris) or just overriding the Launch Options (Steam) to prefix a game launch and e.g. copy the entire game to a tmpfs mount prior to starting, which with bwrap would be relatively easy since I can just `--ro-bind / /`, then `--ro-bind` the game to a second (different) location, then `--tmpfs` the original location, and have something like `sh -c 'rsync -ra temporary_dir/ original_now_tmpfs_dir/ && "$@"' -s` as the command. This would shove an entire game into tmpfs on startup which would be really cool and useful for a lot of games that are known to be incredibly latency sensitive for instance.

However from the looks of it the namespace created by flatpak itself locks down that potential use-case by itself already:

https://github.com/flatpak/flatpak/blob/1561e0f39cbc1a157c821f9dd4729f08e9a08550/common/flatpak-run.c#L2222-L2238

Is there any way to work around this, and what exactly is the intention here?

The idea for flatpaks that do this is probably to actually use *flatpak-spawn* or whatsitcalled to spawn a separate layer of encapsulation, however that would require a lot of coupling with flatpak as opposed to having a user-provided command prefix or such as both Lutris and Steam allow. I also can't see a way to solve my issue with *flatpak-spawn* either.

**Comment by smcv** [comment]
> Running bubblewrap inside flatpak should (IMHO) Just Work™

Sorry, Flatpak cannot allow this. If it did, then a malicious or compromised app could make use of that to present a crafted `/.flatpak-info`, which would trick OS-level services like xdg-desktop-portal into behaving as though it was a different app, or a non-Flatpak app that is in the trusted computing base. OS-level services need to be able to trust that `/proc/$pid/root/.flatpak-info` is under Flatpak's control.

> Is there any way to work around this

No, this restriction is security-sensitive and cannot be bypassed.

> The idea for flatpaks that do this is probably to actually use flatpak-spawn or whatsitcalled to spawn a separate layer of encapsulation

Yes. You can use `flatpak-spawn` to ask Flatpak to create a separate sandbox, in parallel with your original sandbox, with either the same security restrictions or tighter security restrictions.

This does not give you completely arbitrary control over the sandbox contents, and that is by design: if it did, then that would be an indirect sandbox escape. So that probably doesn't work for your use-case of moving a game onto a tmpfs. (However, note that if the Linux kernel's disk cache is working correctly, and if you have enough RAM to be able to do this, the game's entire working set will be cached in memory after the first time it's read *anyway* - so don't assume that copying it onto a tmpfs will actually improve latency unless you have a benchmark that proves it.)

**Comment by benaryorg** [comment]
Ahh, I thought flatpak would be using capability based design to ensure sandbox privileges, not that the content of the sandbox was used to provide security guarantees (which now that I write it out sounds kinda spooky).
Given that's the chosen design here I understand why bypassing isn't possible though, thanks for the explanation.

However I wonder whether this is documented anywhere as I've looked around and haven't seen anything of sorts? Maybe I just didn't hit the right keywords, but so far I find nothing. Neither the [User namespace requirements](https://github.com/flatpak/flatpak/wiki/User-namespace-requirements) nor the [Sandbox Permissions](https://docs.flatpak.org/en/latest/sandbox-permissions.html) list anything of sorts.

> so don't assume that copying it onto a tmpfs will actually improve latency

With a working set of around my memory size it's inevitable that pages are being dropped, especially since most everything is read based for a video game so there are barely any dirty pages, at least not in the game directory itself. However I'd much prefer to have the tmpfs content swapped to zram instead of the pages dropped entirely which will lead to reads from the underlying storage which in my case is a relatively low latency multi-pathed 10G uplink to a Ceph cluster (and CephFS does a great job at utilizing the Linux fscache), but still reading from HDDs, so even with metadata on SSD and the MDSs having plenty of in-memory cache it's still a lot faster to have kswapd shuffle around and re-/decompress some data.
My assumption has a basis in reality, don't worry.
