### ISSUE TITLE
[BUG or QUESTION] why flatpak wrapper script does not simply pass options to in-sandbox executable?

### ISSUE THREAD

**Issue by anatawa12** [flatpak/flatpak#5955]
Hello.
I'm developer of one tool and I have some questions related to compatibility with non-flatpak tools.

I could not find suitable issue templete and no github discussion is found on this repository so I made this issue from blank.

**Questions**

Question 1: 

Why arguments passed to `/var/lib/flatpak/exports/bin/com.unity.UnityHub` starting with `-` is not passed to unity hub?
Is this bug or expected behavior?

I feel this is not expected behavior if `com.unity.UnityHub` is intended to be used as replacement of original executable.

Question 2: 

If the Question 1 is expected behavior, Could you provide some simple executable script that shows this behavior?

I do not want to add check if the executable is flatpak version or not and add '--' depending on the result in my tool.
Because there are many package manager (with sandbox) and I do not want to add check for each package manager.

**Problem**

The arguments passed to `/var/lib/flatpak/exports/bin/com.unity.UnityHub` starting with `-` is not passed to unity hub.

I want not to add special handling for flatpak in my tool because there are many package manager (with sandbox) and I do not want to add support for each package manager.

**Background of this Issue**

I'm a developer of an tool that calls unity hub as a part of tool.
My tool calls unity hub with three arguments `--headress editors -i`.
(important one is first argument is starting with `-` I think)

I was received a feature request to support flatpak installation of unity hub. (vrc-get/vrc-get#1332)
I received with "I can add location of flatpak version of unity hub to default unity hub search location" but flatpak users told me that is not working.

1. flatpak is using sandbox so we cannot simply call original executable
2. We can use `flatpak run com.unity.UnityHub -- --headress editors -i` to call executable
3. There is wrapper script at `/var/lib/flatpak/exports/bin/com.unity.UnityHub` but we still need to pass extra `--` before `--headress editors -i` to be passed to unity hub.

With the third response, I feel this is not expected behavior in flatpak if the `com.unity.UnityHub` is intended to be used as replacement of original executable. (this is question 1)
And I want some workaround to this problem (question 2).

**Comment by smcv** [comment]
It looks to me as though this is an app bug, not a Flatpak bug.

The generated wrapper script *does* simply pass options to an in-sandbox executable. You can see this if you run something like:

```
$ flatpak install flathub org.gnome.Recipes
$ /var/lib/flatpak/exports/bin/org.gnome.Recipes --help
Usage:
  gnome-recipes [OPTION…]
…
```

Notice that the output is gnome-recipes' `--help`, not Flatpak's `--help`.

However, assuming the app you are running is https://github.com/flathub/com.unity.UnityHub, it does not run `unityhub-bin` directly. Instead, it runs `start-unityhub`, which is a copy of https://github.com/flathub/com.unity.UnityHub/blob/master/unityhub.py, which ends up running:

```
    os.execvpe('zypak-wrapper',
               ['zypak-wrapper', '/app/extra/unityhub-bin', *sys.argv[1:]],
               env)
```

If the maintainers of https://github.com/flathub/com.unity.UnityHub intend for it to be usable as a drop-in replacement for a non-Flatpak version of the same program, then it should probably run something more like this instead (untested):

```
    os.execvpe('zypak-wrapper',
               ['zypak-wrapper', '--', '/app/extra/unityhub-bin', *sys.argv[1:]],
               env)
```

or maybe

```
    os.execvpe('zypak-wrapper',
               ['zypak-wrapper', '/app/extra/unityhub-bin', '--', *sys.argv[1:]],
               env)
```

Please report this to https://github.com/flathub/com.unity.UnityHub.

**Comment by smcv** [comment]
> We can use `flatpak run com.unity.UnityHub -- --headress editors -i` to call executable

This passes arguments `-- --headress editors -i` to the command inside the sandbox. You can verify this with something like:

```
flatpak run --command=echo com.unity.UnityHub -- --foo bar
```

This ends up running `echo -- --foo bar`, which outputs `-- --foo bar` to the terminal.

What the command inside the sandbox does with those arguments is outside Flatpak's control, and if you believe it's doing the wrong thing with those arguments, please talk to the app maintainer.

**Comment by smcv** [comment]
To debug what is happening and which command is receiving the arguments you specify, it might be useful to run

```
flatpak run com.unity.UnityHub --help
```

or

```
flatpak run com.unity.UnityHub --version
```

which might give you a clue about which component is interpreting the arguments you gave.
