### ISSUE TITLE
better handling of locales

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#596]
I just had the following situation:

1) Somebody installed recipes (on the commandline, in en_US)
2) I ask them to run it in German to try something out with my German translations
3) UI comes up in English

I think if we want to do the optimization of installing locales partially, we need to work harder on making it transparent

**Comment by matthiasclasen** [comment]
I've put a suggestion in https://github.com/flatpak/flatpak/pull/910

**Comment by ramcq** [comment]
I think two further changes would be good:
- the first is that when installing or upgrading a Locale extension which is deployed with subpaths, we should evaluate the current --subpaths options (or, if not provided, the subpaths setting on the repo) and reinstall it with new subpaths if they are different
- the second is, per #910, if not configured explicitly/manually on the repo, initialise the default locales for the system repo to a list derived from the system's configuration and users

**Comment by aleb** [comment]
In the command line the following gtk-warning message can be seen:
```
$ LANG=de_DE.UTF-8 flatpak run org.gnome.Books/x86_64/stable
(org.gnome.Books:3): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
```

**Comment by albfan** [comment]
For the record:

    $ flatpak run --env=LC_ALL=de_DE.utf8 org.gnome.Books
