### ISSUE TITLE
[Bug]: I cannot update nor install VS code flatpak : While trying to apply extra data: apply_extra script failed, exit status 256

### ISSUE THREAD

**Issue by jacekkowalczyk82** [flatpak/flatpak#5961]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.6

### What Linux distribution are you using?

Pop!_OS

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

First I just regular update of system by software center it failed with this error:
While trying to apply extra data: apply_extra script failed, exit status 256

Later I was trying to update VS code from command line: 

```
(base) jacek@pop-os:~$ flatpak update 
Looking for updates…


        ID                             Branch          Op          Remote          Download
 1. [|] com.visualstudio.code          stable          u           flathub         < 114.2 MB
        ID                             Branch          Op          Remote          Download
 1. [|] com.visualstudio.code          stable          u           flathub         108.3 MB / 114.2 MB

Updating… ████████████████████ 100%  8.3 MB/s  00:00tar: data.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
        ID                             Branch          Op          Remote          Download
 1. [✗] com.visualstudio.code          stable          u           flathub         108.3 MB / 114.2 MB

Error: While trying to apply extra data: apply_extra script failed, exit status 256
Updates complete.
error: There were one or more errors
(base) jacek@pop-os:~$ 

```

in the end I removed the VS code flatpak and tried to install it 

```
(base) jacek@pop-os:~$ flatpak install com.visualstudio.code
Looking for matches…

com.visualstudio.code permissions:
    ipc              network         pulseaudio             ssh-auth               x11
    devices          devel           file access [1]        dbus access [2]        system dbus access [3]
    tags [4]

    [1] host
    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*, org.freedesktop.Flatpak, org.freedesktop.Notifications,
        org.freedesktop.secrets
    [3] org.freedesktop.login1
    [4] proprietary


        ID                             Branch          Op          Remote          Download
 1. [|] com.visualstudio.code          stable          i           flathub         < 114.2 MB
        ID                             Branch          Op          Remote          Download
 1. [|] com.visualstudio.code          stable          i           flathub         108.3 MB / 114.2 MB

Installing… ████████████████████ 100%  7.7 MB/s  00:00tar: data.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
        ID                             Branch          Op          Remote          Download
 1. [✗] com.visualstudio.code          stable          i           flathub         108.3 MB / 114.2 MB

Error: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.visualstudio.code: While trying to apply extra data: apply_extra script failed, exit status 256
(base) jacek@pop-os:~$ 
(base) jacek@pop-os:~$ flatpak --version
Flatpak 1.14.6
(base) jacek@pop-os:~$ 
```

### Expected Behavior

VS code flatopak should be installed

### Actual Behavior

it is failing to install or update

**Comment by jacekkowalczyk82** [comment]
now I do not have VS code at all :-(

**Comment by jacekkowalczyk82** [comment]
I tried with verbose

{code}
(base) jacek@pop-os:~$ flatpak install --verbose com.visualstudio.code
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/jacek/.local/share/flatpak
Looking for matches…
F: Fetching summary index file for remote ‘flathub’
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 10001 bytes
F: Loaded indexed summary file 27486e325626b458f91265bb5d827b9a4794303710a15b6754bcbc11271534d7 from cache for remote ‘flathub’
F: Fetching summary index file for remote ‘flathub’
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 10001 bytes
F: Loaded indexed summary file 27486e325626b458f91265bb5d827b9a4794303710a15b6754bcbc11271534d7 from cache for remote ‘flathub’
F: Transaction: install flathub:app/com.visualstudio.code/x86_64/stable[*]
F: Looking for remote metadata updates for flathub
F: marking op install:app/com.visualstudio.code/x86_64/stable resolved to 909cf0030b06fe01395c204c58354b58510a1129f35206b84bdb1d44da2cf275
F: Updating dependency org.freedesktop.Sdk/x86_64/24.08 of com.visualstudio.code/x86_64/stable
F: Transaction: update flathub:runtime/org.freedesktop.Sdk/x86_64/24.08[$old]
F: marking op update:runtime/org.freedesktop.Sdk/x86_64/24.08 resolved to 5f3431dd027264af9f122292901bb502be8d7079e65f155d16527666b6d4c9cd
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/24.08[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/24.08extra[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Sdk.Locale/x86_64/24.08[/en]
F: Transaction: install/update flathub:runtime/org.gtk.Gtk3theme.Pop-dark/x86_64/3.22[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.openh264/x86_64/2.4.1[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/24.08[*]
F: marking op install/update:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/24.08 resolved to 6fc3d2dde22ded1fd7f23bf07fca3a4d217d25244a85c7926a9e5631a1756f29
F: marking op install/update:runtime/org.freedesktop.Platform.openh264/x86_64/2.4.1 resolved to 50b21d3fc221e861a8573f642bd3e582453b68c8be9962614461ee4d1b0ea38e
F: marking op install/update:runtime/org.gtk.Gtk3theme.Pop-dark/x86_64/3.22 resolved to cb13fccb1a397f172bbfa27e7f9b6e1b4d16b5a316768f67f3ba178e14f1ad6a
F: marking op install/update:runtime/org.freedesktop.Sdk.Locale/x86_64/24.08 resolved to b47cfa93e77185ffa0bdce2fbbe8210e21b322f88df364692e819db513e32b1a
F: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/24.08extra resolved to c26d510a3f92f79eee1a87bbdf672558128ff9b7291aa9d64cc0a4c61ca9de8a
F: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/24.08 resolved to f14011a6e1dae5e30dab762e7659f7591c750f0386305e1641434454528294fd

com.visualstudio.code permissions:
    ipc	network	pulseaudio	ssh-auth	x11
    devices	devel	file access [1]	dbus access [2]	system dbus access [3]
    tags [4]

    [1] host
    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*, org.freedesktop.Flatpak, org.freedesktop.Notifications,
        org.freedesktop.secrets
    [3] org.freedesktop.login1
    [4] proprietary


 1.	  	com.visualstudio.code	stable	i	flathub	< 114.2 MB

Proceed with these changes to the user installation? [Y/n]: y
Installing…
F: flatpak_dir_pull: Using commit 909cf0030b06fe01395c204c58354b58510a1129f35206b84bdb1d44da2cf275 for pull of ref app/com.visualstudio.code/x86_64/stable from remote flathub

(flatpak install:22913): GLib-CRITICAL **: 07:52:31.713: Failed to set scheduler settings: Operation not permitted
Installing…                        0%  0 bytes/s
Installing… █                      5%
F: Loading https://update.code.visualstudio.com/1.94.0/linux-deb-x64/stable using curl
Installing… ██▌                   13%  6.7 MB/s
Installing… █████████▌            48%  23.9 MB/s
Installing… ███████████████▍      77%  27.5 MB/s
Installing… ███████████████████▊  99%  27.0 MB/s  00:00
Installing… ████████████████████ 100%  27.1 MB/s  00:00
F: Received 108315656 bytes
F: No checksum specified, getting tip of app/com.visualstudio.code/x86_64/stable from origin flathub
F: tip resolved to: 909cf0030b06fe01395c204c58354b58510a1129f35206b84bdb1d44da2cf275
F: extracting extra data to /home/jacek/.local/share/flatpak/app/com.visualstudio.code/x86_64/stable/.909cf0030b06fe01395c204c58354b58510a1129f35206b84bdb1d44da2cf275-wQCWxa/files/extra
F: Opening user flatpak installation at path /home/jacek/.local/share/flatpak
F: /home/jacek/.local/share/flatpak/runtime/org.freedesktop.Sdk/x86_64/24.08/5f3431dd027264af9f122292901bb502be8d7079e65f155d16527666b6d4c9cd/files/lib32 does not exist
F: Disallowing ipc access
F: Disallowing network access
F: Running /app/bin/apply_extra 
tar: data.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'usr/share/code': No such file or directory
rm: cannot remove 'data.tar.xz': No such file or directory
rm: cannot remove 'usr': No such file or directory
Error: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.visualstudio.code: While trying to apply extra data: apply_extra script failed, exit status 256
(base) jacek@pop-os:~$ 
{code}

**Comment by jacekkowalczyk82** [comment]
But I was able to install VS codium 

VSCodium                                com.vscodium.codium                                   1.94.1.24283               stable        user

**Comment by jacekkowalczyk82** [comment]
This the difference I found . Version of the VS code vs VScodium 

```
(base) jacek@pop-os:~$ flatpak search com.vscodium.codium 
Name                       Description                        Application ID                      Version                    Branch       Remotes
VSCodium                   Telemetry-less code editing        com.vscodium.codium                 1.94.1.24283               stable       flathub
VSCodium - Insiders        Telemetry-less code editing        com.vscodium.codium-insiders        1.93.0.24242-insider       stable       flathub
(base) jacek@pop-os:~$ flatpak search com.visualstudio.code |grep -v oss |grep "Visual Studio Code" 
Visual Studio Code	Code editing. Redefined.	com.visualstudio.code	1.94.0	stable	flathub
(base) jacek@pop-os:~$ 

```

**Comment by hfiguiere** [comment]
Because VSCode is proprietary, VSCode uses `extra-data` which involve downloading stuff from the vendor at installation time.

Noting flatpak can do about. It's a problem with the package. You can report issues there:
https://github.com/flathub/com.visualstudio.code/issues

**Comment by jacekkowalczyk82** [comment]
Thanks  for a  comment and link/
