### ISSUE TITLE
[Feature request]: Add the ability to read the content of '/usr/' subdirectories.

### ISSUE THREAD

**Issue by MikeNavy** [flatpak/flatpak#5963]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Hi,
Some applications such as LibreOffice or HTTraQT have their html help stored in a subdirectory of '/usr/share' ('/usr/share/libreoffice/help/' for LibreOffice; '/usr/share/httraqt/help/' for HTTraQt).

But '/usr/' is a reserved path in flatpak:

> Reserved Paths
The following paths and subpaths of them are reserved and asking access to them with --filesystem will have no effect: /app, /bin, /dev, /etc, /lib, /lib32, /lib64, /proc, /run/flatpak, /run/host, /sbin, /usr

This prevents to read these applications helps with a flatpak browser such as Firefox (or any flatpak browser) and implies installing another non-flatpak browser as default to read them when help is called from the application.

Feature request: add flatpak applications the capability to access subdirectories of '/usr/' in read-only mode (such as '/usr/share/libreoffice/help/:ro' or '/usr/share/httraqt/help/:ro' in Flatseal).

Regards,

MN

**Comment by MikeNavy** [comment]
Here are the 'index.html' files found in '/usr' subdirectories on my operating system (Linux Mint 21.3 based on Ubuntu 22.04):
> /usr/local/share/resynthesizer/help/en/index.html
/usr/share/cockpit/apps/index.html
/usr/share/cockpit/metrics/index.html
/usr/share/cockpit/networkmanager/index.html
/usr/share/cockpit/packagekit/index.html
/usr/share/cockpit/shell/index.html
/usr/share/cockpit/storaged/index.html
/usr/share/cockpit/systemd/index.html
/usr/share/cockpit/users/index.html
/usr/share/cups/doc-root/index.html
/usr/share/cups/doc-root/da/index.html
/usr/share/cups/doc-root/de/index.html
/usr/share/cups/doc-root/es/index.html
/usr/share/cups/doc-root/fr/index.html
/usr/share/cups/doc-root/ja/index.html
/usr/share/cups/doc-root/pt_BR/index.html
/usr/share/cups/doc-root/ru/index.html
/usr/share/doc/adduser/examples/adduser.local.conf.examples/skel.other/index.html
/usr/share/doc/dia/html/de/index.html
/usr/share/doc/dia/html/en/index.html
/usr/share/doc/dia/html/eu/index.html
/usr/share/doc/dia/html/fr/index.html
/usr/share/doc/dia/html/pl/index.html
/usr/share/doc/doc-base/doc-base.html/index.html
/usr/share/doc/gdisk/index.html
/usr/share/doc/info/html/Index.html
/usr/share/doc/info/html/index.html
/usr/share/doc/libexpat1-dev/expat.html/index.html
/usr/share/doc/libjs-underscore/index.html
/usr/share/doc/libusb-1.0-doc/api-1.0/index.html
/usr/share/doc/lintian/api.html/index.html
/usr/share/doc/lintian/api.html/Lintian/Index.html
/usr/share/doc/nvidia-driver-390/index.html
/usr/share/doc/python3/index.html
/usr/share/doc/python3-caja/html/index.html
/usr/share/doc/python3-xlib/html/index.html
/usr/share/doc/shared-mime-info/shared-mime-info-spec.html/index.html
/usr/share/doc/vmware-vix/index.html
/usr/share/doc/xorg/index.html
/usr/share/doc/xsane-common/html/index.html
/usr/share/gtk-doc/html/mate-dict/index.html
/usr/share/gufw/media/tutorial/index.html
/usr/share/httraqt/help/index.html
/usr/share/javascript/mathjax/test/index.html
/usr/share/libreoffice/help/index.html
/usr/share/synaptic/html/index.html

Regards,
MN

**Comment by chrisawi** [comment]
I'm afraid this is a fundamental consequence of Flatpak's sandbox design. `/usr` is the mountpoint for the runtime, so there's no way to expose the host's `/usr` at the same location. However, you can add the `--filesystem=host-os` permission and browse `/run/host/usr` inside the sandbox.

For what it's worth, it is possible to access such files via the document portal, but this only provides access to the page itself, so images and links to other pages won't work.

See also https://github.com/flatpak/xdg-desktop-portal/issues/555
