### ISSUE TITLE
[Bug]: Can't add main repo or install flatpaks when installing at a custom location

### ISSUE THREAD

**Issue by merll002** [flatpak/flatpak#5971]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

Kali Linux 2024-09-26

### What architecture are you using?

x86_64

### How to reproduce

create a custom config file to install at another location: `nano /etc/flatpak/installations.d/extra.conf`
in my case it is:
```
[Installation "extra"]
Path=/media/leo/Extended storage/flatpaks/
DisplayName=Extra Installation
StorageType=harddisk
```

Then try to install a flatpak or add the base repo.

### Expected Behavior

The repo is added or the flatpak gets installed.

### Actual Behavior

When running: `flatpak --installation=extra remote-add flathub https://flathub.org/repo/flathub.flatpakrepo`
The output is:
`error: Remote "flathub" not found`
When trying to install an application with `flatpak --installation=extra install com.vscodium.codium.flatpakref`:

```The remote 'flathub', referred to by 'com.vscodium.codium' at location https://dl.flathub.org/repo/ contains additional applications.
Should the remote be kept for future installations? [Y/n]: 
The application com.vscodium.codium depends on runtimes from:
  https://dl.flathub.org/repo/
Configure this as new remote 'flathub' [Y/n]: 
error: Remote "codium-origin" not found

### Additional Information

_No response_

**Comment by smcv** [comment]
> in my case it is:
>
> ```
> Path=/media/leo/Extended storage/flatpaks/
> DisplayName=Extra Installation
> StorageType=harddisk
> ```

That isn't a complete/correct installation definition. Is there an `[Installation "extra"]` line that you didn't quote?

**Comment by merll002** [comment]
Oops yeah there was. I dont know where it went!

**Comment by smcv** [comment]
I couldn't reproduce this when running in a Debian testing/unstable container:

```
$ podman run --rm -it debian:sid-slim
# apt install flatpak ca-certificates
# mkdir -p /etc/flatpak/installations.d
# cat > /etc/flatpak/installations.d/extra.conf <<EOF
[Installation "extra"]
Path=/mnt/extra/
DisplayName=Extra
StorageType=harddisk
EOF
# flatpak -vv --installation=extra remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
F: Opening system (extra) flatpak installation at path /mnt/extra
F: Loading https://flathub.org/repo/flathub.flatpakrepo using curl
F: Received 4040 bytes
F: Imported 1 GPG key to remote "flathub"
F: Clearing cached summaries for remote flathub
F: Fetching summary index file for remote ?flathub?
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 10001 bytes
F: Loading https://dl.flathub.org/repo/summaries/5df5ad327f466fa5ba4d946726cf0103c677fa9f156286379082bbec63a61830.idx.sig using curl
F: Received 592 bytes
F: Fetching indexed summary file 61be218843539e42d27eea72dbce144d3d5e91da32c16251667f0839d8b9684e.gz for remote ?flathub?
F: Loading https://dl.flathub.org/repo/summaries/61be218843539e42d27eea72dbce144d3d5e91da32c16251667f0839d8b9684e.gz using curl
F: Received 1308586 bytes
# flatpak -vv --installation=extra install org.gnome.Recipes
F: Opening system (extra) flatpak installation at path /mnt/extra
Looking for matches?
F: Fetching summary index file for remote ?flathub?
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 10001 bytes
F: Loaded indexed summary file 61be218843539e42d27eea72dbce144d3d5e91da32c16251667f0839d8b9684e from cache for remote ?flathub?
F: Fetching summary index file for remote ?flathub?
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 10001 bytes
F: Loaded indexed summary file 61be218843539e42d27eea72dbce144d3d5e91da32c16251667f0839d8b9684e from cache for remote ?flathub?
F: Transaction: install flathub:app/org.gnome.Recipes/x86_64/stable[*]
F: Looking for remote metadata updates for flathub
F: marking op install:app/org.gnome.Recipes/x86_64/stable resolved to fb219fd392f8fc586e221a9b962f7c0f82f3c13979ebdf115faa946f9d419157
F: Installing dependency org.gnome.Platform/x86_64/46 of org.gnome.Recipes/x86_64/stable
Required runtime for org.gnome.Recipes/x86_64/stable (runtime/org.gnome.Platform/x86_64/46) found in remote flathub
Do you want to install it? [Y/n]: 
```

(Actually doing the installation will not all work in an unprivileged podman container because we can't run nested containers - extensions with extra-data, like org.freedesktop.Platform.openh264, will fail to install with an error message "bwrap: Creating new namespace failed: Operation not permitted", and running the app will fail with the same error - but it's a good way to get a predictable environment to test the "package manager" layer of Flatpak.)

If you use `flatpak -vv ...` to get extra debug information, does that tell you anything useful?

Is there already any content in `/media/leo/Extended storage/flatpaks/`?

Does a path without a space work?

What filesystem is mounted on `/media/leo` or `/media/leo/Extended storage`?

**Comment by smcv** [comment]
I am surprised by you getting the error message `error: Remote "flathub" not found` in response to **adding** a remote. Are you sure that error message corresponded to the command? (If unsure, copy/pasting an exact shell transcript into a ```` ``` ```` block is more unambiguous than describing what you did in words.)

**Comment by merll002** [comment]
Running in verbose mode I get:
```
F: Opening system (extra) flatpak installation at path /media/leo/Extended storage/flatpaks
F: Loading https://flathub.org/repo/flathub.flatpakrepo using curl
F: Received 4040 bytes
F: Calling system helper: ConfigureRemote
==== AUTHENTICATING FOR org.freedesktop.Flatpak.configure-remote ====
Authentication is required to configure software repositories
Authenticating as: leo,,, (leo)
Password: 
==== AUTHENTICATION COMPLETE ====
F: Clearing cached summaries for remote flathub
error: Remote "flathub" not found
```
The filesystem is mounted on /media/leo/Extended storage

**Comment by hfiguiere** [comment]
and what kind of filesystem is `/media/leo/Extended storage` ?

**Comment by merll002** [comment]
> and what kind of filesystem is `/media/leo/Extended storage` ?
ext4

**Comment by merll002** [comment]
I will upload a screen recording

**Comment by merll002** [comment]
![image](https://github.com/user-attachments/assets/14bbd6aa-732f-4699-a075-97f090f839f8)

**Comment by merll002** [comment]
![out-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/b32b6dd6-14b7-43f0-b7c6-3282bd5612cf)

**Comment by merll002** [comment]
After a reboot, the issue is fixed! Not sure what was causing this to happen...
