### ISSUE TITLE
[Bug]: `flatpak list` seems to have unfortunate priorities when shortening lines

### ISSUE THREAD

**Issue by ell1e** [flatpak/flatpak#5975]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

postmarketOS Edge

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak list` in a 80 column width terminal:

```
 $ flatpak list
… App… Version                  Branch       Origin                 Installation
… …top 2.0~publicbeta40         master       threema-desktop-origin system
… …top v1.46.8                  stable       flathub                system
… …ate 3.1.1                    stable       flathub                system
… …eal 2.2.0                    stable       flathub                system
… …aft 1.0.1221                 stable       flathub                system
… …era 112.0.5197.53            stable       flathub                system
… …eam 1.0.0.79                 stable       flathub                system
… …are v0.14.2                  stable       flathub                system
… …ghb 1.8.2                    stable       flathub                system
… …eko 0.12.0                   stable       flathub                system
```

### Expected Behavior

The list output shortens the columns that the average user is likely going to care the least about. Maybe it's preposterous of me to even assume this, but aren't most users going to care most about the 1. name and the 2. version? This means the most likely candidates for shortening would be all the other columns, branch, origin, installation etc. Yet the name seems to be the first thing that is chopped off. I have a suspicion most users are going to find that output almost useless since they can't tell what's even being listed, although maybe it's just me. Sorry if the majority of people actually wants this behavior as it is.

### Actual Behavior

The columns being shortened seem to be picked with an unfortunate suboptimal priority for most users, although it could be just me.

**Comment by rusty-snake** [comment]
Related: #4719

**Comment by ell1e** [comment]
It seems like mine is a duplicate, sorry. I didn't pick it up in the issue search. I'll close this one!
