### ISSUE TITLE
[Bug]: detecting disabled unprivileged userns even when it is enabled

### ISSUE THREAD

**Issue by ranisalt** [flatpak/flatpak#5981]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.10

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

Linux taylor 6.11.5-3-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 25 Oct 2024 18:41:19 +0000 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### Expected Behavior

Apps should recognize that `kernel.unprivileged_userns_clone` is set to 1 or that `bubblewrap` is suid and start normally.

### Actual Behavior

Apps (I tested Brave, Chrome, Chromium, Edge, Opera and Steam) installed from Flathub fail to start with some message telling me to set `kernel.unprivileged_userns_clone=1` with sysctl, or to install `bubblewrap-suid` instead of `bubblewrap`. However, that sysctl key is already set to 1, and installing `bubblewrap-suid` does nothing (even after a restart):

![image](https://github.com/user-attachments/assets/b0f11016-146f-45cc-b828-3d91c47de635)

I tried to `flatpak repair` but it did not help.

I tried to uninstall Chromium (with `--delete-data`) and then reinstall, to no avail. Chrome spits multiple error dialogs but opens eventually. The other apps I noticed don't work all have some form of Chromium embedded, that could mean something, since Firefox works with no issue. Podman Desktop also requires the setting too (I think, not sure) and works without issues.

### Additional Information

Neither of these apps have any meaningful override. Steam has the following overrides:

```ini
[Context]
filesystems=!xdg-pictures;!xdg-music;

[Session Bus Policy]
com.steampowered.PressureVessel.LaunchAlongsideSteam.*=own
com.steampowered.PressureVessel.LaunchAlongsideSteam=own

[System Bus Policy]
org.freedesktop.NetworkManager=talk

[Environment]
VKD3D_CONFIG=dxr,dxr11
PATH=/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/gamescope/bin;/usr/lib/extensions/vulkan/MangoHud/bin
LD_BIND_NOW=1
```

My kernel command line is (removing LUKS flags):

```
audit=1 lockdown=integrity lsm=landlock,lockdown,yama,integrity,bpf quiet splash
```

**Comment by smcv** [comment]
> Apps should recognize that kernel.unprivileged_userns_clone is set to 1 or that bubblewrap is suid and start normally.

This message comes from the apps, not from Flatpak (Flatpak does not have any GUI itself).

If there is some feature that the app requires but it is detecting that Flatpak cannot provide it, what we would need to know is what the app is doing, what it expected to happen, and what actually happened.

It might provide helpful information if you run in one terminal:

```
G_MESSAGES_DEBUG=all /usr/libexec/flatpak-portal --verbose --verbose --replace
```

and in another terminal, something like

```
G_MESSAGES_DEBUG=all flatpak run --verbose --verbose --command=flatpak-spawn org.gnome.Recipes --verbose true
```

replacing `org.gnome.Recipes` with the app ID of any affected app.

> installing bubblewrap-suid does nothing

These specific apps are known to **not** work with a setuid version of bubblewrap. Flatpak itself can work with a setuid bubblewrap, but with limited functionality.

**Comment by smcv** [comment]
> Steam

Steam has some diagnostic tools that might be helpful. If you run it as

```
flatpak run --env=SRT_LOG=debug com.valvesoftware.Steam
```

you should find additional information in `~/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs`, most likely in `console-linux.txt`.

**Comment by ranisalt** [comment]
Welp. Curiously, I was having these issues for over a month, and the apps just started working after a restart. I guess some leftover causing issues removed itself. If it happens again I'll return with the logs requested, but for now thanks for your magical presence that fixed the issue :sweat_smile:
