### ISSUE TITLE
[Feature request]: command to show number of available updates

### ISSUE THREAD

**Issue by maxsupermanhd** [flatpak/flatpak#5988]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Something similar to `checkupdates` but for flatpak. Just listing update-available packages would be perfectly reasonable.

Excuse me if this feature was already suggested/implemented, I can not find it in the docs and issues.

**Comment by chrisawi** [comment]
This exists in the form of `flatpak remote-ls --updates`

Please let me know if that doesn't cover your use case.

**Comment by maxsupermanhd** [comment]
Works, thank you!
