### ISSUE TITLE
[Bug]: Don't ask user to ask the developer to update

### ISSUE THREAD

**Issue by tapir** [flatpak/flatpak#5989]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Debian

### Linux distribution version

12

### What architecture are you using?

x86_64

### How to reproduce

1. flatpak install tauno
2. flatpak update

### Expected Behavior

Flatpak can complain that an application is using an obsolete platform while installing it but asking the user to contact the developer everytime user tries to run an update is just counterintuitive. For most users, an application using an obsolete dependency is not even a bug. The application keeps working. This notification should probably be part of flathub (or maybe already is) and message directly developer.

### Actual Behavior

```
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   art.taunoerik.tauno-monitor, com.leinardi.gst
```

I get this everyday when I run my flatpak update

**Comment by chrisawi** [comment]
That message is provided by the runtime when it declares itself EOL, rather than flatpak itself.

There's an existing issue about how flatpak displays these messages: https://github.com/flatpak/flatpak/issues/3531
