### ISSUE TITLE
[Bug]: GTK4 apps using org.gnome.Platform/x86_64/47 have very poor font rendering in Plasma Wayland

### ISSUE THREAD

**Issue by SpinningVinyl** [flatpak/flatpak#5993]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.10

### What Linux distribution are you using?

openSUSE

### Linux distribution version

Tumbleweed 20241104

### What architecture are you using?

x86_64

### How to reproduce

1. Run any GTK4 app using org.gnome.Platform/x86_64/47 in Plasma Wayland and take a screenshot
2. Run the same app in X11 and take a screenshot
3. Compare the two screenshots in terms of font rendering. 

I am attaching two screenshots showing FlatSeal when run under Wayland and under X11. The difference is very noticeable, especially when it comes to smaller and thinner fonts (e.g. in tooltips)

This is in X11:
![Flatseal under X11](https://github.com/user-attachments/assets/1de26892-9e60-401d-9ded-ffada9c02f25)

This is the same app in Wayland:
![Flatseal under Wayland](https://github.com/user-attachments/assets/6189d18d-cce7-47c9-a9e5-2a3ea998f01e)

### Expected Behavior

There is no difference in font rendering in X11 and Wayland

### Actual Behavior

Font rendering in Wayland is noticeably worse.

### Additional Information

The problem only affects GTK4 apps using org.gnome.Platform/x86_64/47. Apps that are either GTK3 or use org.gnome.Platform/x86_64/46 are not affected.

**Comment by chrisawi** [comment]
This isn't a bug in flatpak itself.

I did a quick search and found https://www.reddit.com/r/kde/comments/1gg9kd8/has_anyone_noticed_gtk4_apps_look_kinda_saturated/

It seems to be related to GTK's new renderers.

Please consider [opening an issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/) against GTK. I don't see an existing one, but I may have missed it.
