### ISSUE TITLE
[Bug]: Most flatpak apps can't run on wayland (Ubuntu 24.10)

### ISSUE THREAD

**Issue by ryoikitokuiten-ix** [flatpak/flatpak#5996]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

24.10

### What architecture are you using?

x86_64

### How to reproduce

1. Install Signal flatpak (or vlc media player or spotify)
2. Click on the icon
3. It won't open at all, neither in wayland nor in x11
4. Open Flatseal (which too didn't open on wayland btw, i had to select x11 on login and then it opened on x11)
5. In the sockets section of signal app, disable "wayland windowing system" **and** "fallback to x11 windowing system". only keep "x11 windowing system" enabled.
6. Now login with wayland and open signal app
7. It'll open on xwayland (since command "xlsclients" shows signal app running)

### Expected Behavior

After uptate to ubuntu 24.10, it seems like I can't run most flatpak apps on wayland. Some apps like Zen browser, transmission and libreoffice do run on wayland. But apps like signal, anytype notes, spotify, bottles and most importantly vlc media player won't open on wayland at all. So I forced them to open on x11 using flatseal and so they do open in xwayland now.

### Actual Behavior

I want them to run on wayland, that's all.

**Comment by morganist** [comment]
everything hardware-accelerated broke overnight for me on opensuse tumbleweed. libadwaita applications don't launch at all, firefox and librewolf only start in safe mode, steam doesn't launch, etc. etc.
some applications work just fine, for instance libreoffice, gimp, qbittorrent.
disallowing them to use wayland solves this as a temporary workaround, but i really wonder where this came from...

**Comment by razzeee** [comment]
https://github.com/flathub/flathub/issues/5938

**Comment by hfiguiere** [comment]
it's not a flatpak bug. It's a mesa bug that it propagated through the freedesktop runtime.

**Comment by morganist** [comment]
@hfiguiere got it, thank you! that makes sense, hope they update the runtime asap

**Comment by hfiguiere** [comment]
https://github.com/flathub/flathub/issues/5938#issuecomment-2544290026
