### ISSUE TITLE
[Bug]: STOP UPDATING THIS CRAP

### ISSUE THREAD

**Issue by TheSainEyereg** [flatpak/flatpak#6006]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

Flatpak 1.15.10

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

Linux pc 6.11.8-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 15 Nov 2024 15:35:07 +0000 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Go to https://www.reddit.com/r/linuxquestions/comments/1ezwtox/flatpak_how_to_optimize_networking_for_faster/
2. RUN ANY COMMAND

### Expected Behavior

Everything worked like 3 months ago

### Actual Behavior

```
$> flatpak remote-modify --enable-deltas flathub                                                                                                                                                             
error: Unknown option --enable-deltas
$> flatpak config --set downloader aria2c                                                                                                                                                                      
zsh: correct 'config' to '.config' [nyae]? n
error: Unknown configure key 'downloader'
$> sudo flatpak config --set max-downloads 10                                                                                                                                                                  
error: Unknown configure key 'max-downloads'
```

### Additional Information

I was trying to speed up downloading and found a post on Reddit published 3 MONTHS AGO and NONE OF THE COMMANDS FROM THAT THREAD WORK

**Comment by hfiguiere** [comment]
then the reddit post is wrong. We are no responsible of what people write on the internet.

**Comment by TheSainEyereg** [comment]
> then the reddit post is wrong. We are no responsible of what people write on the internet.

If it worked, the “wrong” here is only the flatpak maintainers who removed what they weren't asked to remove

**Comment by TheSainEyereg** [comment]
![image](https://github.com/user-attachments/assets/c6d9177b-ae99-484d-94fa-2c7d6f7e5459)
Oh well. Then FUCK GPT USERS.

Sorry flatpak team
