### ISSUE TITLE
[Feature request]: Add command to flatpak info

### ISSUE THREAD

**Issue by Justinzobel** [flatpak/flatpak#6011]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

It would be nice to know the command that is called when the Flatpak is run. This would be good in the `flatpak info` command, but if it's already feeling full of info you could add it in a flag e.g. `flatpak info -v`.

**Comment by chrisawi** [comment]
You can get it from `flatpak info --show-metadata` (`-m`). Is that sufficient?

**Comment by Justinzobel** [comment]
Sorry for the noise. I should have dug into the arguments further.
