### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MBA380** [flatpak/flatpak#6017]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.11

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

6.12.1-arch1-1

### What architecture are you using?

x86_64

### How to reproduce

1. Type flatpak update
OR
1. Download org.freedesktop.Platform.openh264 branch 2.2.0
2. Type flatpak update

### Expected Behavior

Flatpak updates all packages and exits cleanly

### Actual Behavior

Flatpak exits with error:
"core dumped with SIGSEGV (11)" (produced using nushell)
"13245 segmentation fault (core dumped)  flatpak update" (produced using zsh)

### Additional Information

I have tried uninstalling branch 2.2.0 of org.freedesktop.Platform.openh264, however that results in the same error when I run "flatpak update" (branch 2.2.0 gets reinstalled).
I have also tried flatpak uninstall --unused, which also results in flatpak installing branch 2.2.0 and throwing the same error again.

**Comment by smcv** [comment]
This looks like a duplicate of #6009, a regression in Flatpak 1.15.11. Please try again when Flatpak 1.15.12 becomes available.

**Comment by hfiguiere** [comment]
this is also an extra-data package, so likely a duplicate.
