### ISSUE TITLE
[Feature request]: Ability to use the Host’s Alternatives System

### ISSUE THREAD

**Issue by Janfel** [flatpak/flatpak#6020]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Fedora and Debian both use an Alternatives System (see [`alternatives(8)`](https://linux.die.net/man/8/alternatives)) to let the user choose which package provides certain commands and libraries. This system works by managing (absolute) symlinks in `/etc/alternatives` which point to the chosen packages.

As it currently stands, I have not found a way to use symlinks provided by this system from Flatpak applications. Because the host root is mounted at `/run/host` the absolute symlinks in `/etc/alternatives` are broken and thus nonfunctional.

Fedora uses this system to manage different Java JRE versions. Each JRE package is installed in `/usr/lib/jvm/${NEVRA}`, where `${NEVRA}` is the unique package identifier (see below). This identifier changes on each package update. While Fedora does provide stable symlinks to each JRE version, those symlinks go through the Alternatives System and so cannot be used from a Flatpak.

~~~ console
$ ls -l /usr/lib/jvm
total 32
drwxr-xr-x. 1 root root 74 Nov 30 09:50 java-17-openjdk-17.0.13.0.11-3.fc41.x86_64
drwxr-xr-x. 1 root root 74 Nov 10 21:31 java-21-openjdk-21.0.5.0.11-1.fc41.x86_64
lrwxrwxrwx. 1 root root 21 Nov 10 21:34 jre -> /etc/alternatives/jre
lrwxrwxrwx. 1 root root 24 Nov 30 09:50 jre-17 -> /etc/alternatives/jre_17
lrwxrwxrwx. 1 root root 32 Nov 30 09:50 jre-17-openjdk -> /etc/alternatives/jre_17_openjdk
lrwxrwxrwx. 1 root root 42 Nov  8 01:00 jre-17-openjdk-17.0.13.0.11-3.fc41.x86_64 -> java-17-openjdk-17.0.13.0.11-3.fc41.x86_64
lrwxrwxrwx. 1 root root 24 Nov 10 21:34 jre-21 -> /etc/alternatives/jre_21
lrwxrwxrwx. 1 root root 32 Nov 10 21:34 jre-21-openjdk -> /etc/alternatives/jre_21_openjdk
lrwxrwxrwx. 1 root root 41 Oct 19 02:00 jre-21-openjdk-21.0.5.0.11-1.fc41.x86_64 -> java-21-openjdk-21.0.5.0.11-1.fc41.x86_64
lrwxrwxrwx. 1 root root 29 Nov 10 21:34 jre-openjdk -> /etc/alternatives/jre_openjdk
$ ls -l /etc/alternatives/j*
lrwxrwxrwx. 1 root root 63 10. Nov 21:34 /etc/alternatives/java -> /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64/bin/java
lrwxrwxrwx. 1 root root 71 10. Nov 21:34 /etc/alternatives/java.1.gz -> /usr/share/man/man1/java-java-21-openjdk-21.0.5.0.11-1.fc41.x86_64.1.gz
lrwxrwxrwx. 1 root root 63 10. Nov 21:34 /etc/alternatives/jcmd -> /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64/bin/jcmd
lrwxrwxrwx. 1 root root 71 10. Nov 21:34 /etc/alternatives/jcmd.1.gz -> /usr/share/man/man1/jcmd-java-21-openjdk-21.0.5.0.11-1.fc41.x86_64.1.gz
lrwxrwxrwx. 1 root root 54 10. Nov 21:34 /etc/alternatives/jre -> /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64
lrwxrwxrwx. 1 root root 55 30. Nov 09:50 /etc/alternatives/jre_17 -> /usr/lib/jvm/java-17-openjdk-17.0.13.0.11-3.fc41.x86_64
lrwxrwxrwx. 1 root root 54 30. Nov 09:50 /etc/alternatives/jre_17_openjdk -> /usr/lib/jvm/jre-17-openjdk-17.0.13.0.11-3.fc41.x86_64
lrwxrwxrwx. 1 root root 54 10. Nov 21:34 /etc/alternatives/jre_21 -> /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64
lrwxrwxrwx. 1 root root 53 10. Nov 21:34 /etc/alternatives/jre_21_openjdk -> /usr/lib/jvm/jre-21-openjdk-21.0.5.0.11-1.fc41.x86_64
lrwxrwxrwx. 1 root root 54 10. Nov 21:34 /etc/alternatives/jre_openjdk -> /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64
~~~

[PrismLauncher](https://flathub.org/apps/org.prismlauncher.PrismLauncher) is affected by this issue.

**Comment by chrisawi** [comment]
I'm not sure I understand the goal here. In general, you shouldn't be using libraries from the host inside the flatpak sandbox.

**Comment by hfiguiere** [comment]
This issue is based in an incorrect understanding on how flatpak works. If PrismLauncher is broken then that package should be fixed.

**Comment by Janfel** [comment]
> I'm not sure I understand the goal here. In general, you shouldn't be using libraries from the host inside the flatpak sandbox.

I wasn’t talking about using host libraries to run the sandboxed application. Apologies for being unclear in my initial description. My issue is solely about the Alternatives System of the host being broken when accessed from within the sandbox using the `host-os` permission.

The `host-os` permission grants access to the host’s binaries and libraries, and it explicitly includes the host’s Alternatives System. But that system doesn’t work within the sandbox because it relies on absolute symlinks. As a result some parts of the host system become inaccessible using standard paths, like the `/usr/lib/jvm/jre-*` directories on Fedora.

> This issue is based in an incorrect understanding on how flatpak works. If PrismLauncher is broken then that package should be fixed.

PrismLauncher is not broken. I mentioned it because it uses external JREs to launch the game instances. Those JREs can either be downloaded at runtime, or selected from the filesystem. When running outside of a sandbox, this enables the use of the system JREs to launch game instances. I was trying to recreate that functionality on the Flatpak version of PrismLauncher by manually granting the `host-os` permission.

If I am still misunderstanding something fundamental, please feel free to ignore this issue.

**Comment by chrisawi** [comment]
> I wasn’t talking about using host libraries to run the sandboxed application. Apologies for being unclear in my initial description. My issue is solely about the Alternatives System of the host being broken when accessed from within the sandbox using the `host-os` permission.

Why would you be accessing them if not to use them?

> The host-os permission grants access to the host’s binaries and libraries, and it explicitly includes the host’s Alternatives System. But that system doesn’t work within the sandbox because it relies on absolute symlinks.

For background, `/run/host/usr` was add to `filesystem=host` in https://github.com/flatpak/flatpak/commit/9eedc60cd23e4295a619e509218b915e32da38b7 to "access data from the host".  The `host-os` subset was later introduced in https://github.com/flatpak/flatpak/commit/fe2536b8441858e3b22f6780dca64a516ee4e48c, with one suggested use case being using the host graphics stack (nothing has come of that AFAIK). That was when  `/etc/alternatives` was first singled out. As you've discovered, this seems not very useful with Fedora's (and Debian's?) absolute symlinks, unless you remount it as `/usr` in a sub-sandbox or something.  (@smcv?)

In any case, it's a very unusual case where an app should want to access those files. PrismLauncher using a JRE from the host isn't really in line with the design and goals of Flatpak.

**Comment by rusty-snake** [comment]
> As you've discovered, this seems not very useful with Fedora's (and Debian's?) absolute symlinks, unless you remount it as /usr in a sub-sandbox or something. 

`openat2` `RESOLVE_IN_ROOT` magic.

> PrismLauncher using a JRE from the host isn't really in line with the design and goals of Flatpak.

Using JRE from the host through `flatpak-spawn --host`  would be the way and should work. Running a host JRE inside the flatpak sandbox does not sound like a good idea.

**Comment by smcv** [comment]
I don't remember a specific reason for including `/etc/alternatives` as part of `host-usr`. I might have been thinking of the small minority of shared libraries (such as ATLAS/LAPACK/BLAS) that have some sort of indirection through `/etc/alternatives`, which means that `/usr` is not complete, and it isn't even possible to examine those libraries programmatically (never mind use them!) without `/etc/alternatives` being present.

You can examine alternatives symlinks with `readlink()` and resolve them by knowing that `/usr` becomes `/run/host/usr`, but you can't dereference them directly. This is similar to how you can look at host libraries below `/run/host/usr`, but you can't rely on being able to load them into an executable (because the Flatpak environment's glibc is not, in general, the same as the host system's glibc, but glibc must match up with libdl, which must match up with `ld.so(8)`, which is at a hard-coded path per architecture - so a container can have a `ld.so` that works with the Flatpak runtime's glibc, *or* a `ld.so` that works with the host glibc, but never both at the same time).

> Using JRE from the host through `flatpak-spawn --host` would be the way and should work. Running a host JRE inside the flatpak sandbox does not sound like a good idea.

Yes, this. It is not possible to do this without a sandbox escape, so any app that does this will not be meaningfully sandboxed, but running arbitrary host programs in the sandbox is not expected to work anyway.

**Comment by Janfel** [comment]
Thank you for clarifying and for the additional background information.
