### ISSUE TITLE
[Bug]: `flatpak list` shows last part of app-id instead of name

### ISSUE THREAD

**Issue by brunvonlope** [flatpak/flatpak#6023]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Debian

### Linux distribution version

12.8

### What architecture are you using?

x86_64

### How to reproduce

1. Create flatpak with four-part app-id (on GIMP, we are trying to use `org.gimp.GIMP.Devel` in our nightly flatpak)
2. Install .flatpak "bundle"
3. `flatpak list`

### Expected Behavior

Name is "(Nightly) GNU Image Manipulation Program"

### Actual Behavior

Name is "Devel"

### Additional Information

![Captura de tela 2024-12-01 204749](https://github.com/user-attachments/assets/f8f1b756-d782-435a-82e6-dee022f51a44)

**Comment by hfiguiere** [comment]
it doesn't have a version either. are you sure there is an appstream file with the right name installed? If not then it's a guess game and assume the last component is the package name.

**Comment by brunvonlope** [comment]
@hfiguiere That was the same guess of one of our contributors (https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/1834#note_2288585).  But, unless I missed something, the appstream file looked correct in my skimming.

**Comment by hfiguiere** [comment]
yes, the file isn't renamed

`rename-appdata-file` is missing.

**Comment by brunvonlope** [comment]
Wow, that was fast. Thank you very much

**Comment by hfiguiere** [comment]
would have been faster had you linked to the MR.
