### ISSUE TITLE
[Bug]: Can't open generated ld.so.cache

### ISSUE THREAD

**Issue by gother666** [flatpak/flatpak#6024]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.11

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

T2

### What architecture are you using?

x86_64

### How to reproduce

Launch an application (firefox, vlc, steam, ...)

### Expected Behavior

Application starts.

### Actual Behavior

Exists with the following message: Can't open generated ld.so.cache

### Additional Information

...
F:     /app/share:/usr/share
F: Running: 'true --args 15 ldconfig -X -C /run/ld-so-cache-dir/82455d7593f202fb186c8cd942442aa33aaa4a8e1f9632f30c0912f6ed5d23a3.NtqVio'
error: Can't open generated ld.so.cache

**Comment by smcv** [comment]
>  F: Running: 'true --args 15 ldconfig -X -C /run/ld-so-cache-dir/82455d7593f202fb186c8cd942442aa33aaa4a8e1f9632f30c0912f6ed5d23a3.NtqVio'

You or your distribution seem to have compiled Flatpak to use `true` (as in `/bin/true`) as its implementation of `bwrap`. Don't do that: it will make Flatpak not work at all.

In the 1.15.x branch, the correct way to use a system copy of bubblewrap is something like `-Dsystem_bubblewrap=bwrap` or `-Dsystem_bubblewrap=/usr/bin/bwrap`, for example as seen in [Debian](https://salsa.debian.org/debian/flatpak/-/blob/debian/1.15.12-1/debian/rules?ref_type=tags) and [Fedora](https://src.fedoraproject.org/rpms/flatpak/blob/rawhide/f/flatpak.spec).

In the 1.14.x branch with its Autotools build system, it's `--with-system-bubblewrap=bwrap` or `--with-system-bubblewrap=/usr/bin/bwrap`. `--with-system-bubblewrap=yes`, or equivalently `--with-system-bubblewrap` with no argument, is a shortcut for `--with-system-bubblewrap=bwrap`, but there is no equivalent shortcut in the Meson build system.

> T2

I am not familiar with that distro, but if your distro has a miscompiled/non-working version of Flatpak, please report that to their support channels.

**Comment by hfiguiere** [comment]
> You or your distribution seem to have compiled Flatpak to use `true` (as in `/bin/true`) as its implementation of `bwrap`.

This bit me the other day. Not with bwrap but with dbus-proxy.

**Comment by smcv** [comment]
I'd be happy to review a pull request to make the build system error out with an explanatory message if the user specifies `true` (perhaps also `enabled`) as their bwrap or xdg-dbus-proxy implementation.
