### ISSUE TITLE
[Bug]: Open Several flatpak apps don't start anymore since about a week or two

### ISSUE THREAD

**Issue by kludikovsky** [flatpak/flatpak#6026]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Linux Mint

### Linux distribution version

5.15.0-126-generic  (MINT 21.3)

### What architecture are you using?

x86_64

### How to reproduce

Example with KMahjongg - below are other affected apps listed
1. Run the following command in the terminal (CLI)
```
$ /usr/bin/flatpak run --verbose  --branch=stable --arch=x86_64 --env=LD_DEBUG=files --command=kmahjongg org.kde.kmahjongg -qwindowtitle %c
```

### Expected Behavior

The program starts and executes

### Actual Behavior

The program does not start but exits with an error code of 134

### Additional Information

# Some of the other affected apps are:
This are two incomplete lists

- KiCAD
- Stellarium
- KAlgebra
- FreeCAD
- Zoom

# Not affected are (so far) 
- onlyoffice
- OBS

# Some of my tests I have performed so far:

I have since about a week or two an issue with an increasing number of flatpak apps failing. All of the errors are looking similar. I have already tried several countermeasures, non worked so far.

It's about two weeks ago, when I tried to join a **Zoom** session which I wasn't able to. 
Then when trying to start **Kmahjongg** it failed. 
Short after that I installed **KiCAD**, which also reported an error, but at least it started, but created constantly errors during usages.
I have then tried **KAlgebra**, which also failed, as well as **Stellarium**.

**OBS** and **Onlyoffice** start and run without any recognizable issue.

This is just a brief list.

Below I do place some reports from the FP-Apps, captured via the 'start in Terminal' option of the start icon or when started at the CLI.

# Error logs:

## Zoom
Command
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zoom --file-forwarding us.zoom.Zoom @@u %U @@
```

Status 0
No Start.
No output.
***********************************

## OBS
Started.
Command
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obs com.obsproject.Studio
```
Started and executes.
Output till execution start.
See attached file.
[OBS_Output.txt](https://github.com/user-attachments/files/18064093/OBS_Output.txt)
***********************************

## KMahjongg
Command
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=kmahjongg org.kde.kmahjongg -qwindowtitle %c
```

Status 134
No Start.
Output.
```
Gtk-Message: 15:29:42.533: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
```
***********************************

## KMahjongg - from CLI with extended report

Command
```
$ /usr/bin/flatpak run --verbose  --branch=stable --arch=x86_64 --env=LD_DEBUG=files --command=kmahjongg org.kde.kmahjongg -qwindowtitle %c
```
Status 134
No Start.
Output.
See attached file.
[KMahjongg_exnted_Report.txt](https://github.com/user-attachments/files/18064092/KMahjongg_exnted_Report.txt)
***********************************

## FreeCAD
Command
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=FreeCAD --file-forwarding org.freecadweb.FreeCAD @@ %F @@
```

Status 134
No Start.
Output.
```
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Gtk-Message: 15:32:27.214: Failed to load module "xapp-gtk3-module"
(qt.glx) qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
(qt.glx) qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
```
=====================================================

# Environment
Linux MINT 21.3 with Cinnamon
AMD Ryzen 5600G with NVIDIA T600  (AMD graphics not used)
Flatpak 1.12.7
(I have also Anaconda in use, just in case this might have an influence)

***********************************
## Tested until now
What I have testet/tried/performed so far:

### 'flatpak repair'
 No effect

### GLX Info
```
$ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA T600/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 550.127.08
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 550.127.08
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 550.127.08
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

## Show runtime
```
$ flatpak info --show-runtime  org.kde.kmahjongg
org.kde.Platform/x86_64/6.7
```

## NVidia updates from the FP-history for the related time frame 
(the issue started definitely in November)
```
Okt 31 19:27:03	deploy install	org.freedesktop.Platform.GL.nvidia-550-127-05	1.4	system	flathub
Okt 31 19:27:58	deploy install	org.freedesktop.Platform.GL32.nvidia-550-127-05	1.4	system	flathub
Nov 22 10:05:51	deploy update	org.freedesktop.Platform.GL.nvidia-535-104-05	1.4	system	flathub
Nov 22 10:06:33	deploy update	org.freedesktop.Platform.GL.nvidia-535-104-12	1.4	system	flathub
Nov 22 10:07:14	deploy update	org.freedesktop.Platform.GL.nvidia-535-129-03	1.4	system	flathub
Nov 22 10:07:55	deploy update	org.freedesktop.Platform.GL.nvidia-535-154-05	1.4	system	flathub
Nov 22 10:08:37	deploy update	org.freedesktop.Platform.GL.nvidia-535-54-03	1.4	system	flathub
Nov 22 10:09:24	deploy update	org.freedesktop.Platform.GL.nvidia-535-86-10	1.4	system	flathub
Nov 22 10:10:01	deploy update	org.freedesktop.Platform.GL.nvidia-550-127-05	1.4	system	flathub
Nov 22 10:10:38	deploy update	org.freedesktop.Platform.GL.nvidia-550-54-14	1.4	system	flathub
Nov 22 10:11:15	deploy update	org.freedesktop.Platform.GL.nvidia-550-90-12	1.4	system	flathub
Nov 22 10:26:49	deploy update	org.freedesktop.Platform.GL32.nvidia-550-127-05	1.4	system	flathub
Nov 22 10:27:29	deploy update	org.freedesktop.Platform.GL32.nvidia-550-90-12	1.4	system	flathub
Nov 25 18:43:04	deploy update	org.freedesktop.Platform.GL.nvidia-535-104-05	1.4	system	flathub
Nov 25 18:43:48	deploy update	org.freedesktop.Platform.GL.nvidia-535-104-12	1.4	system	flathub
Nov 25 18:44:31	deploy update	org.freedesktop.Platform.GL.nvidia-535-129-03	1.4	system	flathub
Nov 25 18:45:14	deploy update	org.freedesktop.Platform.GL.nvidia-535-154-05	1.4	system	flathub
Nov 25 18:45:57	deploy update	org.freedesktop.Platform.GL.nvidia-535-54-03	1.4	system	flathub
Nov 25 18:46:40	deploy update	org.freedesktop.Platform.GL.nvidia-535-86-10	1.4	system	flathub
Nov 25 18:47:19	deploy update	org.freedesktop.Platform.GL.nvidia-550-127-05	1.4	system	flathub
Nov 25 18:47:57	deploy update	org.freedesktop.Platform.GL.nvidia-550-54-14	1.4	system	flathub
Nov 25 18:48:36	deploy update	org.freedesktop.Platform.GL.nvidia-550-90-12	1.4	system	flathub
Nov 25 19:18:37	deploy update	org.freedesktop.Platform.GL32.nvidia-550-127-05	1.4	system	flathub
Nov 25 19:19:18	deploy update	org.freedesktop.Platform.GL32.nvidia-550-90-12	1.4	system	flathub
Dez  3 18:31:42	deploy update	org.freedesktop.Platform.GL.nvidia-535-104-05	1.4	system	flathub
Dez  3 18:32:24	deploy update	org.freedesktop.Platform.GL.nvidia-535-104-12	1.4	system	flathub
Dez  3 18:33:10	deploy update	org.freedesktop.Platform.GL.nvidia-535-129-03	1.4	system	flathub
Dez  3 18:33:50	deploy update	org.freedesktop.Platform.GL.nvidia-535-154-05	1.4	system	flathub
Dez  3 18:34:33	deploy update	org.freedesktop.Platform.GL.nvidia-535-54-03	1.4	system	flathub
Dez  3 18:35:14	deploy update	org.freedesktop.Platform.GL.nvidia-535-86-10	1.4	system	flathub
Dez  3 18:35:50	deploy update	org.freedesktop.Platform.GL.nvidia-550-127-05	1.4	system	flathub
Dez  3 18:36:27	deploy update	org.freedesktop.Platform.GL.nvidia-550-54-14	1.4	system	flathub
Dez  3 18:37:09	deploy update	org.freedesktop.Platform.GL.nvidia-550-90-12	1.4	system	flathub
Dez  3 18:37:47	deploy update	org.freedesktop.Platform.GL32.nvidia-550-127-05	1.4	system	flathub
Dez  3 18:38:27	deploy update	org.freedesktop.Platform.GL32.nvidia-550-90-12	1.4	system	flathub
```

All might have to do with the NVIDIA drive, but I have nothing done except updated from the MINT repos.

Please let me know if you need more information to bring this issue to a solution.
_I will definitely NOT upgrade to Linux Mint 22.x until this is solved, as I have seen messages here that there are also issues with Flatpak on Wilma._

Any help or solution appreciated.

**Comment by chrisawi** [comment]
You're using version 550.127.08 of the NVIDIA driver, which appears to be designed for data center applications. That version isn't available as a Flathub nvidia extension. You can open an issue to request it be added here: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia

However, you may want to consider using the normal desktop driver (e.g. 550.135.x). It lists your GPU as a supported model.

P.S. You appear to have a bunch of old nvidia driver extension installed. You can safely remove all them that don't match the nvidia driver in use.

**Comment by kludikovsky** [comment]
For whomever (beginner) it may help:
in Linux MINT to update the NVIDIA driver simply go into the Driver Manager (Start menu) select one of the proposed drivers and execute. 
Then restart.

That's it!
