### ISSUE TITLE
[Bug]: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: Key file contains line...

### ISSUE THREAD

**Issue by SiamSami** [flatpak/flatpak#6030]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.10

### What Linux distribution are you using?

Clear Linux

### Linux distribution version

42760

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
2. Get error

### Expected Behavior

The repository should be added without any issue

### Actual Behavior

After running the command I get the following error,
![image](https://github.com/user-attachments/assets/8261b392-8e10-4a4c-9e4d-57f83910a280)

### Additional Information

This error started to appear after upgrading my system. The error doesn't appear on other distros with the same version of flatpak.

**Comment by SiamSami** [comment]
I think this issue is specific to clearlinux's few versions only. Closing it.

**Comment by XDream8** [comment]
Updating curl to 8.12.1 fixed it for me but i am not using clear linux
