### ISSUE TITLE
[Bug]: Some flatpak apps seem broken in certain multi-monitor configurations 

### ISSUE THREAD

**Issue by paulimer** [flatpak/flatpak#6037]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.12

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

41

### What architecture are you using?

x86_64

### How to reproduce

1. Have two monitors with two different integral scaling (100% 1080p and 200% 4K in my case)
2. Open some flatpak apps (VLC, Spotify, Slack) (but some do work : Telegram, Zotero)
3. On the 100% monitor it is impossible to click on the bottom half of the screen
4. On the 200% monitor everything works 

### Expected Behavior

All the interface of the apps should be accessible on both screen.

### Actual Behavior

The entire screen is not clickable on the 100% monitor. Actually when I have 2 100% monitor and 1 200%, the same broken behavior is present on both 100% monitors. 

### Additional Information

See a screen cast for a example of the behavior with spotify, if the description is not precise enough.

https://github.com/user-attachments/assets/df226e29-dd72-4e3c-b9d8-f9ab9e264f61

I have looked at other issues with mixed dpi settings, but most are about font/appearance issues (eg https://github.com/flatpak/flatpak/issues/5033)

**Comment by chrisawi** [comment]
It seems likely that this is a bug in the compositor (mutter), somewhat similar to https://gitlab.gnome.org/GNOME/mutter/-/issues/3451. Do you have fractional scaling enabled? (`scale-monitor-framebuffer`)

Have you tried one of these apps outside of Flatpak? VLC is available in Fedora's repos.

**Comment by paulimer** [comment]
Indeed this looks likely. First it is an issue that I can also reproduce with the dnf version of VLC (should have tried before posting here !). And yes it seems fractional scaling is enabled by default in Fedora 41. I'll post the issue in mutter.
