### ISSUE TITLE
[Feature request]: Add distribution package manager into the common flatpak environments

### ISSUE THREAD

**Issue by ell1e** [flatpak/flatpak#6040]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I assume that most of the basic GNOME and KDE flatpak environments are either constructed from some debian-based or some Red Hat or Fedora-based system. However, I haven't found `apt` or `dnf` or `yum` in any of them. This seems occasionally unfortunate as an end user, when e.g. I want to install some sort of plugin for a program that needs some additional library that I could in theory easily get via `flatpak --command=bash com.github.whateverprogram` and then using `apt install missinglibrary` inside the flatpak sandbox. I suggest that therefore, distribution package managers of whatever the base is for the common images should therefore be added into the image as well.

If the reason they are missing is that such changes would revert with every flatpak update, I think it would be still useful since e.g. plugins could be expanded to just offer to run `apt` for the missing library via some user prompt, and rerun that whenever it is detected missing. Since flatpaks usually don't take plugins into account (e.g. for some text editor flatpak), fetching dependencies later like this could be very useful.

**Affects version:** flatpak 1.14.10 and latest image environments, I don't know how to look up the image versions

**Comment by rusty-snake** [comment]
There's a number of reasons why `foo install` inside the sandbox does not work and will never work. And the runtimes are not controlled by flatpak I.e. this is not a flatpak issue.

**Comment by ell1e** [comment]
Where would runtime issues best be filed? And is there some documentation somewhere that goes into more detail why package managers inside a flatpak runtime wouldn't work? I realize docker containers and chroot is different, but since all the major folders inside flatpak exist, it intuitively feels like for software that isn't system services (which also commonly have issues in docker) an `apt install` might perhaps be doable.

**Comment by rusty-snake** [comment]
> where would runtime issues best be filed?

https://gitlab.com/freedesktop-sdk/freedesktop-sdk for example.

> And is there some documentation somewhere that goes into more detail why package managers inside a flatpak runtime wouldn't work?

- Permission problems, `/usr` and others are read-only
- I know that at least apt (the only one I tested with such an scenario) has problems in an user namespace with only one uid mapped.
- The runtime is a shared resources between multiple flatpaks.

.

- Making install work, would also make uninstall work.
- While you could implement an overlayfs based approach (bwrap now supports it in nosuid mode) I doubt that the flatpak developers have the time and the will to implemented it.

**Comment by bbhtt** [comment]
Unlike popular theory, the runtimes aren't built from any pre-existing distribution. They are built completely from the ground up independently and there will be no package manager inside them. 

The runtimes are image-based and inside the Flatpak sandbox, everything is read-only. These serve immutable systems and read-only `/` like Flatpak.

**Comment by smcv** [comment]
As others have said, this is not a design goal for Flatpak. (Indeed, in some ways it's an anti-goal: Flatpak runtimes are meant to be predictable, shareable and read-only.)

> when e.g. I want to install some sort of plugin for a program

The Flatpak way to do this is for the packaging of that program to set up extension points for [the "extensions" mechanism](https://docs.flatpak.org/en/latest/extension.html).

**Comment by rusty-snake** [comment]
> extension

Which, correct me if I'm wrong, requires an existing extension point in the app/runtime. i.e. you can not create arbitrary custom-user/third-party extensions. And flatpak/runtime authors refused generic extension points in the past AFAIK. e.g. there is no `LD_PRELOAD`-hook extension point w/o abusing some other (VA-API, ...) point.

**Comment by smcv** [comment]
> Which, correct me if I'm wrong, requires an existing extension point in the app/runtime. i.e. you can not create arbitrary custom-user/third-party extensions

Correct. The list of extension points in the runtime is under the control of the runtime author (and indirectly the app author, by their choice of runtime), and the list of extension points in the app is under the control of the app author.

(Technically it is possible for a user to create arbitrary extensions by forking the runtime or app and making your own version with all the extension points you could want, but if you do that, you're taking responsibility for it - the runtime/app author cannot be expected to provide support for the result.)

> And flatpak/runtime authors refused generic extension points in the past AFAIK. e.g. there is no `LD_PRELOAD`-hook extension point

I do not know specifics of whether the addition of a `LD_PRELOAD` hook extension point was refused, but that seems like a rational thing to have done, because a generic mechanism to inject arbitrary code into non-cooperating processes seems like the opposite of the predictable environment that Flatpak tries to provide to app authors.
