### ISSUE TITLE
Automatic retry on connection close ("Need more input")

### ISSUE THREAD

**Issue by treba123** [flatpak/flatpak#605]
Hello,

when installing or updating packages with a very poor network connection, I quite often get errors like the following:
`error: While pulling app/org.mozilla.FirefoxNightlyWayland/x86_64/master from remote org.mozilla.FirefoxNightlyWayland-2-origin: Need more input`

Less often there are random other errors like:
`error: While pulling app/org.mozilla.FirefoxNightlyWayland/x86_64/master from remote org.mozilla.FirefoxNightlyWayland-3-origin: Peer failed to perform TLS handshake
`

After retrying a couple of times it usually works. I suspect there's some problem how flatpak handles reconnections/retries.

There is another report about the same problem here: https://github.com/xhorak/firefox-devedition-flatpak/issues/1

Best regards and thanks for flatpak!

**Edit:** if this is a problem with the server in question (and not how flatpak handles reconnects), it would still be nice if flatpak would not always create a new remote location and download everything again, but allow to continue unfinished installations (just as most package managers would do on a broken connection).

**Comment by marsjaninzmarsa** [comment]
>Edit: if this is a problem with the server in question (and not how flatpak handles reconnects), it would still be nice if flatpak would not always create a new remote location and download everything again, but allow to continue unfinished installations (just as most package managers would do on a broken connection).

Umm, isn't it working like this right now (Flatpak 0.8.5)?

**Comment by glaubersm** [comment]
I use flatpak 0.9.6 on Arch. When an update process fails, all data is downloaded again.

**Comment by alexlarsson** [comment]
This is the error:
```
 →       /* Z_FINISH not set, so this means no progress could be made */•
 →       /* We do have output space, so this should only happen if we•
 →          have no input but need some */•
 •
 →       g_set_error_literal (error, G_IO_ERROR, G_IO_ERROR_PARTIAL_INPUT,•
 →       →       →            _("Need more input"));•
 ( g_zlib_decompressor_convert )
```
Which means we got a partial download of some zlib compressed file.

**Comment by gri1n** [comment]
I just encountered this problem when trying to install a Firefox package with Flatpak. Is there likely to be a fix soon?

**Comment by alex285** [comment]
same here 
```
flatpak install --user --from https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxNightlyCSD.flatpakref

Installing: org.mozilla.FirefoxNightlyCSD/x86_64/master
Installing: org.mozilla.FirefoxNightlyCSD/x86_64/master from org.mozilla.FirefoxNightlyCSD-3-origin
[###########         ] Downloading files: 1/2 21.3 MB (418.2 kB/s)                 
error: While pulling app/org.mozilla.FirefoxNightlyCSD/x86_64/master from remote org.mozilla.FirefoxNightlyCSD-3-origin: Need more input
```
and after 4-5 tries the same

**Comment by arthurtiteica** [comment]
How does one download locally?

**Comment by alex285** [comment]
@arthurtiteica on [their page](https://firefox-flatpak.mojefedora.cz/) give bundle links

btw i noticed that even download bundles from there, are always closing the connection on 25MB, so you need to resume download. so maybe this particular repo isn't a Flatpak issue

**Comment by mwleeds** [comment]
Recent versions of ostree automatically retry network requests on failure, and no one has reported this in a while, so I think it's safe to close.

**Comment by Ruedii** [comment]
I'm still having this issue.

**Comment by mwleeds** [comment]
@Ruedii could you post the output of `ostree --version`? Or if that command is not installed, get the version from your package manager? 2018.6 is the version that introduced the retry feature.

**Comment by Ruedii** [comment]
The data is:
`libostree:
 Version: 2018.8
 Features:
  - libsoup
  - gpgme
  - libarchive
  - selinux
  - libmount
  - release
  - p2p`

Retry seemed to be set to 5 by default in my checks.  It seems this particular error does not result in a retry, though.   Do you think this is an upstream issue?
