### ISSUE TITLE
flatpak.sh fails to set XDG_DATA_DIRS if snapd is installed

### ISSUE THREAD

**Issue by elvisangelaccio** [flatpak/flatpak#606]
Hi, when I login on my archlinux box I get the following value for `XDG_DATA_DIRS`:
```
$ printenv XDG_DATA_DIRS
/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```

which means I can't run flatpak apps via GUI. Could it be possible that `snapd` and `flatpak` are conflicting with each other when setting `XDG_DATA_DIRS`?

This is the file installed by snapd in `/etc/profile.d`:

```
$ cat /etc/profile.d/apps-bin-path.sh 
# Expand the $PATH to include /snaps/bin which is what snappy applications
# use
PATH=$PATH:/snap/bin

if [ -z "$XDG_DATA_DIRS" ]; then
    XDG_DATA_DIRS=/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
else
    XDG_DATA_DIRS="$XDG_DATA_DIRS":/var/lib/snapd/desktop
fi
export XDG_DATA_DIRS
```

**Comment by elvisangelaccio** [comment]
I can also reproduce with the following script:

```bash
unset XDG_DATA_DIRS
. /etc/profile.d/apps-bin-path.sh
printenv XDG_DATA_DIRS
. /etc/profile.d/flatpak.sh
printenv XDG_DATA_DIRS
```

which outputs:

```
$ ./test.sh 
/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```

**Comment by elvisangelaccio** [comment]
Ok I understand the bash syntax correctly:

```
XDG_DATA_DIRS="${XDG_DATA_DIRS:-$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/}"
```

means: "if XDG_DATA_DIRS is already set, use it; otherwise define it", which explains my issue.

What was the rational here? Why not just always append the flatpak paths, regardless of the previous `XDG_DATA_DIRS` value?

**Comment by mattiasb** [comment]
FWIW, "if XDG_DATA_DIRS is already set, use it; otherwise define it" is what the spec says. :)

**Comment by mattiasb** [comment]
Hm, actually nevermind what I said. I was thinking about XDG_{CONFIG, DATA_HOME}.

**Comment by smcv** [comment]
Is there a reason why the flatpak directories are being put *after* the pre-existing contents?

I would have expected the flatpak directories to be prepended - if everything that manipulates a search path prepends to it, then you get "last edit has highest precedence" semantics.

The current setup can have some rather weird results. Suppose you have GNOME Maps installed as a Flatpak, and also as a system package for some reason (perhaps you want a newer version than the system package used by other users of your computer), and you do not explicitly set your XDG_DATA_DIRS. The Flatpak has highest precedence (its .desktop file will be the visible one). Now suppose you install Snap. Without changing anything in Flatpak, the system copy of GNOME Maps suddenly becomes highest precedence! This seems undesired.

I'll send a PR soon with some improvements to this profile snippet, which will include the proposed re-ordering if there's no reason not to.

**Comment by smcv** [comment]
(See PR #616)
