### ISSUE TITLE
flatpak build command interacts poorly with ninja

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#607]
If we have a `flatpak build ...` that executes `ninja`, we will always perform full builds. This is because headers such as those in `/usr/include/gtk-3.0/gtk/deprecated/gtknumerableicon.h` have an mtime of `0`.

This breaks incremental builds in Builder for meson-based projects, causing them to always perform full builds.

**Comment by chergert** [comment]
Relevant

https://github.com/ninja-build/ninja/issues/1120

**Comment by TingPing** [comment]
Here is a patch to `ninja` to workaround this. We can try to upstream it at some point but it is trivial and largely flatpak/ostree specific.

Note that I didn't actually test this in the context of Flatpak but just on a local file it seemed to behave as expected:

```diff
From 9fb1922583f98200d6fc141a575bde459c9b8927 Mon Sep 17 00:00:00 2001
From: Patrick Griffis <tingping@tingping.se>
Date: Mon, 20 Mar 2017 21:46:42 -0400
Subject: [PATCH] Work around mtime being set to 0 sometimes

---
 src/disk_interface.cc | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/src/disk_interface.cc b/src/disk_interface.cc
index 1b4135f..46625b1 100644
--- a/src/disk_interface.cc
+++ b/src/disk_interface.cc
@@ -185,6 +185,11 @@ TimeStamp RealDiskInterface::Stat(const string& path, string* err) const {
     *err = "stat(" + path + "): " + strerror(errno);
     return -1;
   }
+  // Some users (Flatpak) set mtime to 0, this should be harmless
+  // and avoids conflicting with our return value of 0 meaning
+  // that it doesn't exist.
+  if (st.st_mtime == 0)
+    return 1;
   return st.st_mtime;
 #endif
 }
-- 
2.9.3
```

**Comment by chergert** [comment]
I think it is perfectly reasonable to to host an OSTree/Flatpak based patch in flatpak until upstream ninja figures out what they're willing to maintain.

**Comment by matthiasclasen** [comment]
it makes sense to me to put this patch in the sdk for the time being.

**Comment by alexlarsson** [comment]
Lemme put this in the sdk then.

**Comment by alexlarsson** [comment]
This is now in the 1.6 fd.o sdk
