### ISSUE TITLE
Can't Connect to  209.132.179.2

### ISSUE THREAD

**Issue by johjeff** [flatpak/flatpak#614]
Hello,

There was a previous issue opened for this in January I think. I am not able to add the nightly-graphics repo for flatpak. The error is '_Could not connect: No route to host_'.

**Is there anywhere that this repo is mirrored?**

Thanks.

Jeff

**Comment by alexlarsson** [comment]
Oh, the machine had been shut down. I'll restart it.
However, this is living on a cloud instance that is scheduled to go away soon. I think we need to move it somewhere else at some point.

**Comment by feeef** [comment]
Thank you @alexlarsson ! I had commented on a closed issue related to the same problem, I just noticed this one now.

Thanks!
