### ISSUE TITLE
It is possible to preserve the summary.sig file after flatpak build-import-bundle?

### ISSUE THREAD

**Issue by jgarciao** [flatpak/flatpak#615]
I'm trying to create a web application to process flatpak bundles in order to easilly create/update remote flatpak repos. 

The problem I'm having is that the summary.sig file is lost after some commands and the resulting repo can't serve apps for the end users without using --no-gpg-verify. 

I would like that the webapp doesn't require to upload the private key.

This is how I create the bundle:

### Developer's computer: create local repo, check contents, run and create bundle
```bash
# Create repo
flatpak build-export --update-appstream --gpg-sign=MYKEYID --gpg-homedir=/home/jorge/gpg org.gnome.Dictionary.Test01 dictionary3.20 stable

# Check that the repo contains summary, summary.sig, and commitmeta files
ls -lR  org.gnome.Dictionary.Test01 | grep "summary\|commit"
	-rw-r--r--   1 jorge jorge  509 mar  3 23:42 summary
	-rw-r--r--   1 jorge jorge  336 mar  3 23:42 summary.sig
	-rw-r--r-- 1 jorge jorge  166 mar  3 23:42 88f93103c0f9f2dd5d7b1808e58d3cfef5377a0e84134b1c17b2b6532bf3d9.commit
	-rw-r--r-- 1 jorge jorge  336 mar  3 23:42 88f93103c0f9f2dd5d7b1808e58d3cfef5377a0e84134b1c17b2b6532bf3d9.commitmeta
	-rw-r--r-- 1 jorge jorge   86 mar  3 23:42 da983322c96c065522c3cffa290ec68bcf0696e02476f875ef65c3752a1bcb.commit
	-rw-r--r-- 1 jorge jorge  336 mar  3 23:42 da983322c96c065522c3cffa290ec68bcf0696e02476f875ef65c3752a1bcb.commitmeta

# Install and run the app from the local repo. 
flatpak remote-add --gpg-import=jorge.gpg org.gnome.Dictionary-origin org.gnome.Dictionary.Test01
flatpak remote-ls org.gnome.Dictionary-origin
flatpak install org.gnome.Dictionary-origin org.gnome.Dictionary
flatpak run org.gnome.Dictionary

# Create a bundle
flatpak build-bundle --arch=x86_64 --gpg-keys=jorge.gpg org.gnome.Dictionary.Test01 GnomeDictionary-3.20.0.flatpak org.gnome.Dictionary stable
```

### Webapp: create empty repo and import the bundle
```bash
# If we import the bundle in an empty repo the summary.sig file is lost
ostree init --repo=org.gnome.Dictionary.Test01 --mode=archive-z2
flatpak build-import-bundle org.gnome.Dictionary.Test01 GnomeDictionary-3.20.0.flatpak
ls -lR  org.gnome.Dictionary.Test01 | grep "summary\|meta"

	-rw-r--r--   1 jorge jorge  389 mar  4 01:06 summary
	-rw-r--r-- 1 jorge jorge  648 mar  4 01:06 88f93103c0f9f2dd5d7b1808e58d3cfef5377a0e84134b1c17b2b6532bf3d9.commitmeta
	-rw-r--r-- 1 jorge jorge  12 mar  4 01:06 6a0ef11b7cc167f3b603e585c7eeeeb675faa412d5ec73f62988eb0b6c5488.dirmeta

# If we import the bundle using ostree the result is even worse, because the summary file is lost too
ostree init --repo=org.gnome.Dictionary.Test01 --mode=archive-z2
ostree static-delta apply-offline --repo=org.gnome.Dictionary.Test01 GnomeDictionary-3.20.0.flatpak
ls -lR  org.gnome.Dictionary.Test01-B | grep "summary\|meta"
	-rw-r--r-- 1 jorge jorge  12 mar  1 00:17 6a0ef11b7cc167f3b603e585c7eeeeb675faa412d5ec73f62988eb0b6c5488.dirmeta
	-rw-r--r-- 1 jorge jorge  336 mar  1 00:17 15f616eb8174318cc399105c526398d3e06905567ef7ccd9de1af3b68cc661.commitmeta

# It seems that we need to provide the private key to build-import-bundle to have everything
ostree init --repo=org.gnome.Dictionary.Test01 --mode=archive-z2
flatpak build-import-bundle --gpg-sign=MYKEYID --gpg-homedir=/home/jorge/gpg org.gnome.Dictionary.Test01 GnomeDictionary-3.20.0.flatpak

ls -lR  org.gnome.Dictionary.Test01 | grep "summary\|meta"
	-rw-r--r--   1 jorge jorge  389 mar  4 18:10 summary
	-rw-r--r--   1 jorge jorge  336 mar  4 18:11 summary.sig
	-rw-r--r-- 1 jorge jorge  960 mar  4 18:10 88f93103c0f9f2dd5d7b1808e58d3cfef5377a0e84134b1c17b2b6532bf3d9.commitmeta
	-rw-r--r-- 1 jorge jorge  12 mar  4 18:10 6a0ef11b7cc167f3b603e585c7eeeeb675faa412d5ec73f62988eb0b6c5488.dirmeta
```

Another thing I've tried is to upload a second bundle (for example for GnomeDictionary 3.22) using the same process and after running `flatpak build-update-repo --generate-static-deltas ...` 
the summary.sig file is also lost so it seems the previous command also require to have the private key in the server.

As I said I would like to be able to process the flatpak bundle in the server without having the private key. Is not possible or I'm doing something wrong?

**Comment by alexlarsson** [comment]
Its not really *lost* in that sense. The summary file contains a list of all the branches in the repo, and the current commit they are on.  Whenever you import something into a repo this file changes, and you need to recreate the summary, and thus rebuild the signature.

You can't in general reuse the old signature because it may not match the end result of the repo where you imported the bundle. For instance, that repo could have a pre-existing branch for another application.

That said, in your case you have a completely new repo with a completely copy of a source repo, so you *could*  just copy the old summary and summary.sig. However, at that point you may as well just tar up the source repo and ship to the web-app, so this solution won't really fix the full problem.

**Comment by jgarciao** [comment]
Thanks for the answer. I was suspecting some reason like that.

I think I will reconsider the webapp design in order that the user uploads the signature (or the webapp creates one for him) so repos can be updated and signed by the service
