### ISSUE TITLE
flatpak-builder: allow specifying location for sources 

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#620]
For Builder, it would be really nice if we could share git checkouts for different projects. Things like gnome-todo and gnome-calendar both having 300 mb dependencies (e-d-s) makes things tough for people that work on both of those.

It would be interesting if git work-trees could help here and somehow share repositories with jhbuild.

**Comment by alexlarsson** [comment]
This is part of https://github.com/flatpak/flatpak/pull/678

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#20
