### ISSUE TITLE
claims to work with GLib 2.40 but actually needs 2.44

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#622]
configure.ac says flatpak 0.8.x only needs GLib 2.40, but it actually uses `G_DECLARE_FINAL_TYPE`, which was introduced in 2.44.

I have patched the jessie-backports version to cope, but the patches are fairly nasty, particularly the second one (I had to copy in half of gtype.h):

* https://anonscm.debian.org/cgit/collab-maint/flatpak.git/tree/debian/patches/flatpak-dir-Adapt-to-old-GLib-APIs.patch?h=debian/jessie-backports
* https://anonscm.debian.org/cgit/collab-maint/flatpak.git/tree/debian/patches/flatpak-json-Backport-G_DECLARE_FINAL_TYPE-G_DECLARE_DERI.patch?h=debian/jessie-backports

Assuming you don't like those patches (in your place I wouldn't!), I suspect the best solution upstream might be to just bump `GLIB_REQS` to 2.44, and then I can patch that back to 2.40 for the jessie backport.

**Comment by alexlarsson** [comment]
Yeah, i think going with 2.44 is ok at this point.
