### ISSUE TITLE
flatpak-builder: Add ability to lint manifests

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak#623]
It would be useful for Gnome Builder if it could parse the manifest for warnings or errors without building the project.

**Comment by alexlarsson** [comment]
At least it now prints warnings for unknown propeties

**Comment by ace13** [comment]
You can skip all the build steps, and only parse the manifest, by doing something like;
```
flatpak-builder --download-only --disable-download directory_name com.application.manifest.json
```

Currently using that method myself for validation.
Worth noting is that `directory_name` doesn't need to exist, and won't be created by the command.

**Comment by TingPing** [comment]
I actually believe this will be the best method to lint them going forward: https://github.com/TingPing/flatpak-manifest-schema

External tools and editors will do a better job than `flatpak-builder` probably.

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#21
