### ISSUE TITLE
library sanboxing support

### ISSUE THREAD

**Issue by esodan** [flatpak/flatpak#624]
An application is a set of widgets and business logic. Widgets and business logic, is recommended to be placed in independent libraries, in order to create unit tests for them, while applications just contains that widgets and adds some stuff.

Develop a stack of libraries, requires to develop each in isolated environments in order to make sure you have controlled tests. Once finished, you can create a tarball and add it to dependency for a next level library in the stack, to continue development until you have reached your application. This is a very common case.

So flatpak should add special json format to setup build and test environments for libraries. This means Builder should be able to read it, download dependencies, or use tarballs, not included in standard SDK, build them and make ready your sanbox to start your library development environment without affect your host OS.

**Comment by matthiasclasen** [comment]
I think this is a bit outside the mission of flatpak.
