### ISSUE TITLE
Third party SDK

### ISSUE THREAD

**Issue by esodan** [flatpak/flatpak#625]
flatpak should allow to create custom SDK from vendors, so anyone can use GNOME SDK and "append" others SDK to build their applications, so when update your app you can leave your users getting updates (may be security ones) from third party repositories along with the already automatically updated GNOME Platform and SDK. This will reduce burden on application developers on update dependencies by them self.

For strict control, as a vendor, you should be able to "enable" updates from third party repositories, in order to verify if current update works well with your app. So users will get an update from their app vendor with a manifest to update dependencies from third party repositories "already tested and approved".

May flatpak repositories should allow ref (may it have already) specific versions in third party respositories, to update dependencies from, allowing channels lilke nightly, beta and stable. May vendor updates a third party dependency, but mark initially to nightly, then after initial test mark it to beta and finally to stable, so users will take them as they wish. This is already in place, just (may be) not for third party repositories. Remember, that this means an application may have no changes but its dependencies, but requires to cross each channel before to declare a new "official" update.

**Comment by mwleeds** [comment]
I'm not sure I understand what you're asking for but I think it's covered by base apps, which is a way for apps to share a set of dependencies that sit on top of their runtime. For example base apps are used to package Electron apps: 
- https://docs.flatpak.org/en/latest/electron.html
- https://github.com/flathub/electron-sample-app
