### ISSUE TITLE
Permissions not fully forwarded when running inside a flatpak environment

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak#627]
I'm following this https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#debugging-a-failing-build together with https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#runningtesting-an-uninstalled-application that mentions to use the --run command to have all the permissions set up for building most of GNOME apps.
In this case I'm trying with gnome-photos (uses GOA and Tracker), gnome-calendar (uses GOA), gnome-todo (uses GOA).
What I do is:
flatpak-builder ../photosBuild org.gnome.Photos.json
flatpak-builder --run ../photosBuild org.gnome.Photos.json sh
cd bin
./gnome-photos

And it doesn't have permission to access neither GOA or Tracker even if it has in the json file and in the resulting manifest:
Error calling StartServiceByName for org.gnome.OnlineAccounts: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.gnome.OnlineAccounts: No such file or directory

and same for tracker.

This happen with all the applications mentioned.

However, if I get those apps and export them to a repo and install them locally, they run succesfully. So I guess this is an issue with flatpak-builder --run somehow not forwarding properly the permissions.

This issue also prevents any development in GNOME Builder since they use similar commands (without exporting to a repo or installing), so the same issues arise.

**Comment by chergert** [comment]
In Builder we should be propagating `--share=...` and such from the finish-args of the manifest.

**Comment by csoriano89** [comment]
Another issue I realized, the app menu is not exported or usable. So it adds points to the dbus not being available at all for the uninstalled app.

**Comment by alexlarsson** [comment]
Ah, yeah, `flatpak build` (which is what gets run here) doesn't start the dbus proxy, because you generally don't want to leak the build environment into the build sandbox. However, in this case we probably should do that. So, we need to trigger this of a flag or something.

**Comment by alexlarsson** [comment]
This should be fixed in master. Can you try it?

**Comment by csoriano89** [comment]
Yes it works with https://github.com/flatpak/flatpak/commit/248a603e6a5a6adbed9f8e60ae270dbef87f4d42 and https://github.com/flatpak/flatpak/commit/248a603e6a5a6adbed9f8e60ae270dbef87f4d42, closing, thanks a lot!!!
