### ISSUE TITLE
tests require `ostree trivial-httpd` which is going away

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#632]
In recent (2017.x) versions of `libostree`, `ostree trivial-httpd` is backed by a separate executable that is not always installed (in Debian it's packaged in `ostree-tests`), and in 2017.4 it will not be compiled by default unless https://github.com/ostreedev/ostree/pull/723 is reverted. This is part of potentially moving `libostree` from `libsoup` to `curl` as its HTTP implementation.

I'll continue to build the `trivial-httpd` in Debian for the moment, and rely on installing `ostree-tests` to run Flatpak's tests.

Ideally, the Flatpak tests would either not use it at all, or use it if it can be launched sucessfully but fall back to `file:///` or something if not; or possibly use an alternative like `python3 -m http.server 8000 --bind 127.0.0.1`, but that doesn't have the same nice automatic port assignment and automatic cleanup behaviour that `ostree trivial-httpd` does.

cc @cgwalters

**Comment by alexlarsson** [comment]
The auto-cleanup behaviour in particular is very nice.

**Comment by smcv** [comment]
https://github.com/projectatomic/rpm-ostree/pull/684/commits/1c222ba68a0b1a3700c682873f98308a3c07ad02 is relevant, although not particularly pleasant...

**Comment by smcv** [comment]
I've wondered about the possibility of moving some of the Flatpak and libostree tests to a more wrapper/adverb-based approach, where a parent process (maybe in Python for its fewer traps than shell scripts) runs a gpg-agent, web server, etc., then runs the actual test as a subprocess, then cleans up the infrastructure bits before exiting with a status that mirrors what the actual test returned.

**Comment by cgwalters** [comment]
Yeah, looks like this broke the PR testing.  Sorry ☹️.

**Comment by cgwalters** [comment]
PR in https://github.com/flatpak/flatpak/pull/658

**Comment by alexlarsson** [comment]
Fixed in https://github.com/flatpak/flatpak/commit/32eb260d24d9bb94fad4dd4e8765ffad9bb7331b
