### ISSUE TITLE
Can't span rosefiles-fuse failed to execute child process (not such file or directory)

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak#640]
Trying to build GNOME apps in Ubuntu 16.04.2 leads to this error, preventing any build.
The steps were:
git clone https://git.gnome.org/browse/nautilus
cd nautilus
flatpak-builder ../build org.gnome.Nautilus.org

**Comment by csoriano89** [comment]
flatpak 0.9.1

**Comment by alexlarsson** [comment]
This was a ppa dependencies issue, now fixed
