### ISSUE TITLE
Flatpak requires CONFIG_MAGIC_SYSRQ?

### ISSUE THREAD

**Issue by colemickens** [flatpak/flatpak#643]
I don't have `/proc/sysrq-trigger`. I'm wondering if that's why I'm receiving:

```
$ sudo flatpak run org.mozilla.FirefoxNightly
Can't bind mount /newroot/proc/sysrq-trigger on /newroot/proc/sysrq-trigger: No such file or directory
```

**Comment by smcv** [comment]
I think your guess is right. This appears to be fixed in bubblewrap git master, but not in a release yet:

https://github.com/projectatomic/bubblewrap/commit/3b51f382626c645f1d929213393251f85dfe4d1f

**Comment by alexlarsson** [comment]
We have latest bwrap imported now, or you need to use a system-installed 0.1.8 version
