### ISSUE TITLE
Expose the installation manifest or path through Flatpak CLI

### ISSUE THREAD

**Issue by csoriano1618** [flatpak/flatpak#644]
Today I wanted to know what commit ID one app was used to build from. I got the answer to go to
/var/lib/flatpak/app/<appid>/current/active/files/manifest.json and read it.
It's useful all the info is there, so would be useful to expose this path or some bits (the manifest, dir, etc) through flatpak CLI.

**Comment by alexlarsson** [comment]
Well, that is something flatpak-builder creates, but that not necessarily any flapak would have (for instance if it was built some other way)
