### ISSUE TITLE
Add --clean-failed-build-dir

### ISSUE THREAD

**Issue by jurf** [flatpak/flatpak#646]
@alexlarsson I hope you remember the conversation on IRC, but for non-participants:

Flatpak at the moment automatically (and silently) keeps unsuccessful build directories in `.flatpak-builder/build`. When testing they can easily pile up without the user noticing (it’s a hidden directory after all), and since they aren’t used again they can be safely deleted before another try.

With this argument people wouldn’t need to have a separate command to clean it before running `flatpak-builder`.

**Comment by jurf** [comment]
Maybe `--force-clean-build-dir`? To complement `--force-clean`? It would probably make more sense, since there’s already `--keep-build-dirs`.

**Comment by alexlarsson** [comment]
Yeah, that seems useful for e.g. autobuilders like flathub.
