### ISSUE TITLE
Cannot build anymore

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#647]
Since recently, I cannot build my applications anymore, maybe since 0.9.1?

```
rm -rf app
flatpak-builder --ccache --repo=repo --subject="Build of org.kde.ark.json, `date`"  app org.kde.ark.json
Downloading sources
Fetching git repo git://anongit.kde.org/ark.git
Starting build of org.kde.ark
Cache miss, checking out last cache hit
fuse: device not found, try 'modprobe fuse' first
========================================================================
Building module libarchive in /home/flatpakdev/flatpak-kde-applications/.flatpak-builder/build/libarchive-7
========================================================================
error: Build directory /home/flatpakdev/flatpak-kde-applications/.flatpak-builder/rofiles/rofiles-4ZB0XY not initialized, use flatpak build-init
Error: module libarchive: Child process exited with code 1
Makefile:8: recipe for target 'org.kde.ark.app' failed
make: *** [org.kde.ark.app] Error 1
```

**Comment by alexlarsson** [comment]
The latest flatpak-builder uses the rofiles-fuse fuse-filesystem (see announce message for 0.9.1 for details). This needs to have fuse working on your machine. I think you can use --disable-rofiles-fuse, but that will make building much slower. A better approach is to figure out why fuse is not working on your distro.

**Comment by aleixpol** [comment]
Had to install `fuse`. The actual error message would be welcome, other than that this issue can be closed.

**Comment by monperrus** [comment]
`fuse` is installed on my machine but I still hit `error: Build directory org.gnome.Evolution-master not initialized, use flatpak build-init`

Any idea?
