### ISSUE TITLE
add module providing runtime versions of xdg-open and xdg-email

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#651]
These should be very minimal gio binaries calling out to the right portal.
We don't want to ship the shell script versions in side the sandbox, but we have to support 3rd party apps using these commandline tools

**Comment by fmuellner** [comment]
Something like https://github.com/fmuellner/flatpak-xdg-utils?

**Comment by matthiasclasen** [comment]
that is pretty prompt delivery. Thanks!

**Comment by matthiasclasen** [comment]
an initial implementation is in https://github.com/flatpak/flatpak-xdg-utils now
All that remains to be done is to wrap it in a tarball and add it to the xdg runtime.

**Comment by alexlarsson** [comment]
Its in the latest 1.6 builds
