### ISSUE TITLE
libtool error

### ISSUE THREAD

**Issue by daa84** [flatpak/flatpak#653]
I try to build library [unibilium](https://github.com/mauke/unibilium) and get next error:
```
libtool --mode=link --tag=CC cc -L/app/lib  -rpath '/app/usr/local/lib' -version-info 3:0:3 -o libunibilium.la unibilium.lo uninames.lo uniutil.lo
libtool:   error: cannot find the library '' or unhandled argument '/usr/lib'
Makefile:66: recipe for target 'libunibilium.la' failed
```
the same build works ok on ubuntu 16.10.

**Comment by alexlarsson** [comment]
These two look unmatched: `-L/app/lib  -rpath '/app/usr/local/lib'`
Something must be going wrong with the prefix in the build.

**Comment by daa84** [comment]
/app/lib - place to search for libraries and /app/usr/local/lib - target folder, so i don't see any problem here. Also i try to set LDFLAGS to empty and get same error:

```
libtool --mode=link --tag=CC cc  -rpath '/app/usr/local/lib' -version-info 3:0:3 -o libunibilium.la unibilium.lo uninames.lo uniutil.lo
libtool:   error: cannot find the library '' or unhandled argument '/usr/lib'
Makefile:66: recipe for target 'libunibilium.la' failed
```

Maybe i'am wrong, but looks like something wrong with libtool, when no dependency passed with -lsome_lib to it

**Comment by alexlarsson** [comment]
Its not necessarily wrong, but it seems weird. Do you not want the library to end up in /app/lib in the end?

How does the `libunibilium.la` file look?

**Comment by daa84** [comment]
ah ok, i set wrong path with usr/local/lib, it is really just /app/lib, but this changes nothing

```
libtool --mode=link --tag=CC cc -L/app/lib  -rpath '/app/lib' -version-info 3:0:3 -o libunibilium.la unibilium.lo uninames.lo uniutil.lo
libtool:   error: cannot find the library '' or unhandled argument '/usr/lib'
Makefile:66: recipe for target 'libunibilium.la' failed

```

**Comment by daa84** [comment]
This is libunibilium.la on my ubuntu machine, i renamed it to txt
[libunibilium.txt](https://github.com/flatpak/flatpak/files/872273/libunibilium.txt)

**Comment by alexlarsson** [comment]
That seems very strange. Why is it trying to find a library called `''`'? Maybe it is from `dependency_libs=''` in the .la file, but that makes *no* sense.

**Comment by daa84** [comment]
Looks like empty dependency produce this problem. I compare libtool script from ubuntu and from flatpak and find that it differ a lot, even --version display same version number, this is because it generated from some file i think. Maybe some settings are wrong in this script? Can't say exactly as i don't understand to much in this script.

**Comment by daa84** [comment]
Later i want to try to install libtool directly with flatpak-builder, maybe this change something.

**Comment by daa84** [comment]
Hello! ok, good news,  i install libtool with flatpak-builder - and it begin to work
i take libtool here: http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz

so looks like problem in libtool that ships with flatpak build environment?

**Comment by alexlarsson** [comment]
What runtime are you using? Maybe the libtool in the new freedesktop.org 1.6 runtime works better for you.

**Comment by daa84** [comment]
I use org.gnome.Platform 3.22

> freedesktop.org 1.6

How can i check this? Does set platform version to 3.24 change something?

**Comment by matthiasclasen** [comment]
Closing this, since it was reported against old versions. Please reopen if the problem still exists with flatpak 1.0.x and current runtimes.
