### ISSUE TITLE
Unmaintained system extensions are ignored unless the user extension dir exists

### ISSUE THREAD

**Issue by gcampax** [flatpak/flatpak#654]
flatpak_dir_collect_unmaintained_refs returns TRUE if the extension directory does not exist, and therefore flatpak_list_unmaintained_refs does not look into the system directory, assuming that the search in the user directory succeeded.

Instead flatpak_dir_collect_unmaintained_refs() should return FALSE and set the error to "no such file or directory" or similar.

**Comment by gcampax** [comment]
(This affect the .host workaround suggested in #138)

**Comment by alexlarsson** [comment]
No, that's not right either. It should look in both, because there may be multiple matching extensions, some in the user and some in the system. They should not override an earlier one though.
