### ISSUE TITLE
reconsider exporting mime types

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#656]
As we discussed at the hackfest, there are some issues with just allowing sandboxed applications to install new mimetypes or claim support for existing ones.

We need to carefully evaluate what we allow here, without exposing the user to risks.

One principle that was suggested is: Installing a new application should never change the default handler for an existing mime type.

**Comment by TingPing** [comment]
> One principle that was suggested is: Installing a new application should never change the default handler for an existing mime type.

I'm not sure that would really be possible across desktops as the desktop files are just thrown into the path and the machinery for looking up associations will just always find it? Some desktops still don't expose a UI for setting handlers either like Gnome..

**Comment by alexlarsson** [comment]
We now rewrite and limit mimetypes as per: 3e9bc8ba7a2ef6333b2ee381db4f32248f764a44
