### ISSUE TITLE
Add way to disable transfer.fsckObjects in git clone

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#661]
Error:
```
Cloning git repo git://anongit.freedesktop.org/poppler/poppler.git
Cloning into bare repository 'git_anongit.freedesktop.org_poppler_poppler.git.clone_tmp'...
error: object bcd37bee2b48b33fc75f2962e5b3fc59fbc159aa: missingSpaceBeforeDate: invalid author/committer line - missing space before date
```

Input from org.kde.okular.json:
```
    {
            "name": "poppler",
            "config-opts": ["-DENABLE_TESTING=OFF", "-DCMAKE_INSTALL_LIBDIR=lib"],
            "cmake": true,
            "builddir": true,
            "sources": [ { "type": "git", "url": "git://anongit.freedesktop.org/poppler/poppler.git", "branch": "master" } ]
        },
```

Project clones properly here. I'm guessing there's something else going on on the flatpak side, but I don't know what that is.

**Comment by alexlarsson** [comment]
flatpak clones with `git clone -c transfer.fsckObjects=1`. Maybe that is the problem?

**Comment by alexlarsson** [comment]
Yeah, that seems to be it.
I really only want it to verify the sha1 hashes though, not date formats...
Maybe we need to add a way to disable this...

**Comment by alexlarsson** [comment]
Given all the recent hoopla about sha1 being broken i really do want to at least verify the sha1 for the git objects...

**Comment by tsdgeos** [comment]
I think "i've fixed" the poppler repository, but you probably need to be less strict, not sure everyone will want/know how to fix the repos.

**Comment by alexlarsson** [comment]
@tsdgeos I agree, but cool that you fixed it. Did you need to rewrite the history?

**Comment by tsdgeos** [comment]
depends on what you mean by "history", the only broken things were tags so i had to overwrite the broken ones with the proper dates.
