### ISSUE TITLE
Allow FTP sources

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak#666]
I'm trying to build TeX Live, but the official archive is only available via FTP: ftp://tug.org/texlive/historic/2016/texlive-20160523b-source.tar.xz

Adding the url as a source results in the following error message: "Failed to download sources: module texlive: Not supported address schema"

**Comment by alexlarsson** [comment]
Yeah, libsoup (which we use for downloads) has no ftp support. We would need some nice ftp library to add this.

**Comment by alexlarsson** [comment]
In previous examples of this I have always been able to find a http mirror though.

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#23

**Comment by Alexander-Wilms** [comment]
I tried using the binary distribution instead. I encountered [this](https://github.com/flatpak/flatpak/issues/1452) A workaround is omitting the doc directory, but it still didn't work.

There's more info [here](https://github.com/texstudio-org/texstudio/issues/10)  a manifest [here](https://github.com/Alexander-Wilms/flathub/tree/texstudio).

**Comment by wolfv** [comment]
Cool, thanks for the update. 
In the meantime I came up with this: https://gist.github.com/wolfv/2f42bbe5cd80cf235dc0a0514ca149a6

I guess we'll encounter the same issue as you with the number of files -- but we might not need all of the texlive distribution for our use case (it's supposed to be part of UberWriter, to create PDFs from Markdown via Pandoc and Latex).

I'm pinging @somas95 and @njam who've been active in the respective issue https://github.com/UberWriter/uberwriter/issues/46
