### ISSUE TITLE
Ctrl-C should stop flatpak-builder and not leave anything running

### ISSUE THREAD

**Issue by futuretim** [flatpak/flatpak#676]
While trying to build rust for an extension I did Ctrl-C to stop the build. However, it dumped me to the terminal appearing to stop but then everything that was running just kept logging to the terminal with the actual build eventually completing.

**Comment by alexlarsson** [comment]
I think we can use the new bubblewrap --die-with-parent option for this.

**Comment by alexlarsson** [comment]
master has this now
