### ISSUE TITLE
Flatpak and flatpak-builder should make it easy to use trusted certificates globally

### ISSUE THREAD

**Issue by futuretim** [flatpak/flatpak#677]
I have created derivative sdks to include certificates I need in my CA chain to continue working but I believe this mechanism should be easily provided for by flatpak/builder. I believe I've seen a similar issue with the flatpak Hexchat and SSL that would possibly be alleviated by a similar mechanism.

**Comment by futuretim** [comment]
By globally I mean for a given build or perhaps for a given application instance when it is invoked properly.

**Comment by alexlarsson** [comment]
I'm no expert at openssl, but surely this must be possible. Some app must be able to have a custom certificate that it needs to do something that is not globally installed as root.

**Comment by alexlarsson** [comment]
I've been looking over this, and I think the proper way is to expose the host CA configuration to the sandbox (read-only), and the best way to do this seems to be using the PKCS#11 protocol and modules in combination with p11-kit. I filed an issue about this here: 
https://github.com/p11-glue/p11-kit/issues/68

**Comment by baztian** [comment]
I'm affected by this issue as well. We have a corporate root ceritficate that forces me to add that certificate to etc/ssl/certs. Unfortunately flatpak doesn't work in our company.

**Comment by alexlarsson** [comment]
We now (as per #85) support using the host ca certs via p11-kit proxying. Not all apps support it (for example it doesn't currently work with opensll), but the basic flatpak side is there.

**Comment by alexlarsson** [comment]
Eh, i meant as per #1757
