### ISSUE TITLE
Restarts downloads from scratch every time

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#679]
On a super flaky Wi-Fi connection, downloads are restarted every time, instead of resuming from where it stopped. An example session:

```
$ flatpak install https://git.gnome.org/browse/gnome-games/plain/flatpak/gnome-games-nightly.flatpakref
Installing: org.gnome.Games/x86_64/master
Required runtime for org.gnome.Games/x86_64/master (org.gnome.Platform/x86_64/master) is not installed, searching...
Found in remote gnome-nightly, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/master from gnome-nightly

Receiving delta parts: 10/10 436.7 kB/s 100.9 MB/197.4 MB 3 minutes 41 seconds remaining                 
error: While pulling runtime/org.gnome.Platform/x86_64/master from remote gnome-nightly: Connection terminated unexpectedly

$ flatpak install https://git.gnome.org/browse/gnome-games/plain/flatpak/gnome-games-nightly.flatpakref
Installing: org.gnome.Games/x86_64/master
Required runtime for org.gnome.Games/x86_64/master (org.gnome.Platform/x86_64/master) is not installed, searching...
Found in remote gnome-nightly, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/master from gnome-nightly

Receiving delta parts: 1/10 279.0 kB/s 22.9 MB/197.4 MB 10 minutes 25 seconds remaining                  
error: While pulling runtime/org.gnome.Platform/x86_64/master from remote gnome-nightly: Could not connect: Socket I/O timed out
```

**Comment by alexlarsson** [comment]
Its supposed to remember the parts that are fully downloaded at least. But this seems to completely start over.

**Comment by rik-shaw** [comment]
I am in a country with unstable network and am continually facing this problem.

Here is the most recent output:
```
flatpak --user install --from https://kube.kde.org/files/org.kde.kube.flatpakref
Installing: org.kde.kube/x86_64/master
Required runtime for org.kde.kube/x86_64/master (org.kde.Platform/x86_64/5.9) is not installed, searching...
Found in remote kderuntime, do you want to install it? [y/n]: y
Installing: org.kde.Platform/x86_64/5.9 from kderuntime
[##############      ] Downloading files: 14106/20639 149.7 MB (94.8 kB/s)      
error: While pulling runtime/org.kde.Platform/x86_64/5.9 from remote kderuntime: Socket I/O timed out
```

Previous attempts had downloaded 4MB, 32MB, and 62MB of the kderuntime, but it seems to start *at the beginning* each time I retry.  Esp. the above after 150MB download is a shame to not be able to resume!  Flatpak simply isn't going to be an option for many locations until the resumability is more consistently working.

Thanks for the good work.

**Comment by rik-shaw** [comment]
I am in a country with unstable network and am continually facing this problem.

Here is the most recent output:
flatpak --user install --from https://kube.kde.org/files/org.kde.kube.flatpakref
Installing: org.kde.kube/x86_64/master
Required runtime for org.kde.kube/x86_64/master (org.kde.Platform/x86_64/5.9) is not installed, searching...
Found in remote kderuntime, do you want to install it? [y/n]: y
Installing: org.kde.Platform/x86_64/5.9 from kderuntime
[##############      ] Downloading files: 14106/20639 149.7 MB (94.8 kB/s)      
error: While pulling runtime/org.kde.Platform/x86_64/5.9 from remote kderuntime: Socket I/O timed out

Previous attempts had downloaded 4MB, 32MB,

**Comment by amtlib-dot-dll** [comment]
The download actually resumes from where it breaks, but the output is a little bit confusing as the progress bar starts from the left most position every time though the total size is decreasing

**Comment by hadess** [comment]
> The download actually resumes from where it breaks, but the output is a little bit confusing as the progress bar starts from the left most position every time though the total size is decreasing

The total size isn't decreasing in the top comment shown here, and in my recent dupe https://github.com/flatpak/flatpak/issues/3484 (3 years, I didn't remember I filed this one)

**Comment by nanonyme** [comment]
Note that this has regressed *a lot* in later flatpak versions that now corrupt the repo on download failures.

**Comment by mwleeds** [comment]
> > Note that this has regressed _a lot_ in later flatpak versions that now corrupt the repo on download failures.
> 
> I think that's what I'm seeing here:
> 
> ```
> 1 ✗ mwleeds@fedora ~ (1 key)
> ↳ flatpak update org.freedesktop.Platform.GL.default//19.08
> Looking for updates…
> Info: (pinned) org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
>    The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
> 
> 
>         ID                                             Branch            Op           Remote            Download
>  1. [✗] org.freedesktop.Platform.GL.default            19.08             u            flathub           1.0 kB / 89.1 MB
> 
> Error: While trying to checkout 54eadc8792dbc1ab739e47cd22f7e97458ee6f419ea8d4564dafd71c54199ac7 into /var/home/mwleeds/.local/share/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/19.08/.54eadc8792dbc1ab739e47cd22f7e97458ee6f419ea8d4564dafd71c54199ac7-JWUXB1: Opening content object fa9d39464ac4c561b7215ecfb5e04454b05d9712b79aeb0d915be7e0378c1c81: Couldn't find file object 'fa9d39464ac4c561b7215ecfb5e04454b05d9712b79aeb0d915be7e0378c1c81'
> Updates complete.
> error: There were one or more errors
> 1 ✗ mwleeds@fedora ~ (1 key)
> ↳ flatpak update org.freedesktop.Platform.GL.default//19.08
> Looking for updates…
> Info: (pinned) org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
>    The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
> 
> 
>         ID                                             Branch            Op           Remote            Download
>  1. [✗] org.freedesktop.Platform.GL.default            19.08             u            flathub           1.0 kB / 89.1 MB
> 
> Error: While trying to checkout 54eadc8792dbc1ab739e47cd22f7e97458ee6f419ea8d4564dafd71c54199ac7 into /var/home/mwleeds/.local/share/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/19.08/.54eadc8792dbc1ab739e47cd22f7e97458ee6f419ea8d4564dafd71c54199ac7-T6BXB1: Opening content object fa9d39464ac4c561b7215ecfb5e04454b05d9712b79aeb0d915be7e0378c1c81: Couldn't find file object 'fa9d39464ac4c561b7215ecfb5e04454b05d9712b79aeb0d915be7e0378c1c81'
> Updates complete.
> error: There were one or more errors
> 1 ✗ mwleeds@fedora ~ (1 key)
> ```

This is #3479 and has been fixed now.

**Comment by mwleeds** [comment]
I can say definitively from looking into #3479 that Flatpak (at least Flatpak 1.13.x and 1.12.x) do not restart downloads from scratch every time they are interrupted or canceled. Subsequent downloads do re-use already downloaded objects, with a couple caveats:

- This is only true if there wasn't another successful operation in between the interrupted download and the resume, since the staging directory would be cleared if there was an intervening operation that succeeded.
- This is only necessarily true for normal libostree downloads (whether via static deltas or object pulls). I don't know about extra-data downloads or OCI downloads.
