### ISSUE TITLE
Cannot use .desktop as an application id

### ISSUE THREAD

**Issue by grulja** [flatpak/flatpak#682]
Using name such as **org.telegram.desktop** as an application id results into warning that **org.telegram** is invalid id. Apparently the .desktop part is omitted somewhere and flatpak probably think it's not part of the id.

Error:
(flatpak build-update-repo:27718): flatpak-WARNING **: Invalid id org.telegram

**Comment by grulja** [comment]
This might not actually be a bug in flatpak, but in appstream-glib, because problem is using **org.telegram.desktop** as appstream id and not as application id in flatpak manifest or in name of that manifest.

**Comment by ximion** [comment]
Just as additional info: With the upcoming AppStream 0.11 release, the component-id won't necessarily be equal to the desktop-id anymore. See https://lists.freedesktop.org/archives/appstream/2017-March/000148.html for reference.
One way to mitigate this issue would be to look for a metainfo file having a `<launch type="desktop-id>%a-desktop-id.desktop%</launch>` tag, which is in the upcoming spec. In that case, the component-id should not be touched at all.
This should preserve backwards-compatibility.

Unfortunately it will also mean waiting for AppStream 0.11 to be released and possibly for changes in appstream-glib to resolve this issue.

**Comment by alexlarsson** [comment]
Fixed in https://github.com/flatpak/flatpak/commit/b426306884b59340c75dc8d03a5517f6c9925711

**Comment by grulja** [comment]
There is still one probably related problem. When I have app using .desktop in its name, then I'm unable to properly export icons and also icons are not put into exported appstream metadata file.

**Comment by grulja** [comment]
Also using .desktop in name in flatpakref file makes flatpak fail as well.

**Comment by alexlarsson** [comment]
@grulja do you have your manifest somewhere so I can test this?

**Comment by grulja** [comment]
Yes, I have it in your repository https://github.com/alexlarsson/nightly-build-apps.

**Comment by alexlarsson** [comment]
It does seem to export the icon for me:
```
...
Exporting share/icons/hicolor/256x256/apps/org.telegram.desktop.png
...
```

**Comment by grulja** [comment]
It does, but it doesn't put it to appstream metadata, I can see that e.g. one KDE application has:
    <icon type="cached" height="128" width="128">128x128/org.kde.kanagram.png</icon>
    <icon type="cached" height="64" width="64">64x64/org.kde.kanagram.png</icon>

While telegram appstream metadata doesn't have this. This was working with telegram before I renamed it if I remember correctly. At least I could see icon when opening flatpak bundle in Discover, because the icon was taken from appstream metadata file.

**Comment by alexlarsson** [comment]
So, the reason the appstream breaks is because we require the id in the appstream file to end with .desktop, but the telegram doesn't (i mean, other than the .desktop that is in the for the real name).

I fixed this here:   https://github.com/alexlarsson/nightly-build-apps/commit/9a66e8608a33e61c9ac5b792b92215f4d23286c6

**Comment by grulja** [comment]
But then with this change the app id will be different from upstream so when someone in example writes a review for telegram running in flatpak and someone else will write review for telegram coming from upstream then they will be each submitted to a different application.

Appstream metadata specification doesn't mention that .desktop is mandatory for desktop applications and that's why upstream decided to use .desktop as an application name.

**Comment by alexlarsson** [comment]
@grulja I pushed some other cleanups to the telegram json too. Hope that was ok.

**Comment by alexlarsson** [comment]
@grulja Appstream upstream recently changed the spec so that .desktop is not needed, see https://github.com/flatpak/flatpak/issues/682#issuecomment-292138991

**Comment by ximion** [comment]
@alexlarsson Jup :) Not having the component-id convey any special meaning besides "unique ID for this software" is a great thing, this allows us to avoid all the special treatment IDs for desktop-apps get everywhere.

The comment from above is already outdated though, for API-beauty reasons we decided to call the tag`launchable` again, it's described here: https://github.com/ximion/appstream/blob/master/docs/sources/metainfo/component.xml#L252
(and will be in the next release like this, the release will likely happen next Monday)

**Comment by alexlarsson** [comment]
Anyway, the current flatpak code requires $appid.desktop as the id in the appdata.

**Comment by grulja** [comment]
Ok then and thanks for your improvements in the manifest.

**Comment by ximion** [comment]
@alexlarsson Does it really require the .desktop suffix? Because if that's the case, then this is a bug on its own, as the .desktop suffix has been optional for a while.

**Comment by mwleeds** [comment]
> @alexlarsson Does it really require the .desktop suffix? Because if that's the case, then this is a bug on its own, as the .desktop suffix has been optional for a while.

Looks like, at least these days, Flatpak does not require the `.desktop` suffix in the appstream component id:
- https://github.com/flatpak/flatpak/blob/bf37034663f611c47257412eb198f8efb3c8fe73/common/flatpak-utils.c#L5399
- https://github.com/flatpak/flatpak/blob/bf37034663f611c47257412eb198f8efb3c8fe73/common/flatpak-utils.c#L5150
- https://github.com/flatpak/flatpak/blob/bf37034663f611c47257412eb198f8efb3c8fe73/common/flatpak-appdata.c#L371
