### ISSUE TITLE
flatpak-builder does not grant write access to sdk filesystem when  using shell

### ISSUE THREAD

**Issue by futuretim** [flatpak/flatpak#684]
When trying to build and install an extension from a build shell, write access is not granted to the sdk filesystem area. for instance with the rust extension after a proper build-init, using:

flatpak build --share=network ../rust-build

I can easily clone rust's git, have it do its build but upon install it fails with this error:

mkdir: cannot create directory ‘/usr/lib/sdk/rust’: Read-only file system
install: error: can't write to destination. consider `sudo`.

**Comment by alexlarsson** [comment]
Well, the sdk should not be writable, but it seems the extension point is not mounted there.

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#24
