### ISSUE TITLE
flatpak-builder: zip extraction

### ISSUE THREAD

**Issue by orbisvicis** [flatpak/flatpak#687]
The zip format [allows extraneous data between chunks](https://en.wikipedia.org/wiki/Zip_(file_format)#Structure), which is how self-extracting archives are built. Unfortunately this is a warning for the `unzip` tool, which process the archive successfully but returns with an exit code of `1`, which breaks the build process. However that exit code is also reserved for similar but legitimate warnings. If `flatpak-builder` ignores that code, important errors might be missed. Furthermore self-extracting archives have non-standard file extensions and can't be identified by magic numbers. So...

1. Provide and default to an extraction tool that doesn't have this problem - `bsdtar` works fine and is more flexible.
2. Allow specifying the archive's format explicitly.

**Comment by orbisvicis** [comment]
For now you can use the `file` type and extract manually in `build-commands` if using the `simple` build system, or add a `shell` sources type otherwise. Just note the exit status of each command string is checked, though thankfully the commands are run in a shell and not `execvp`'d directly. So just add a null-up to the extraction command to wipe the status code: `false; :`

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#25
