### ISSUE TITLE
flatpak install something already installed

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#688]
At the moment it errors, which is weird and makes us add weird workarounds on scripts. We have them in KDE and we have them in flatpak-build-scripts.

I propose that if it's already installed then it `exit(0)`'s and possibly tries to update, which is what flatpak-build-scripts does at the moment.

**Comment by alexlarsson** [comment]
Fixed in 2b5af6a036607ac410991df2e5c03de2ccac5ee0

**Comment by alexlarsson** [comment]
Note: It does not update if its already installed.
