### ISSUE TITLE
Virtual joystick - access to /dev/uinput ?

### ISSUE THREAD

**Issue by mwoz123** [flatpak/flatpak#696]
I'm trying to create flatpak package for application that is "driver" for my joystick (remaps buttons, creates virtual joystick):
https://github.com/uglyDwarf/evdevshift

So here's question : can flatpak package have access to /dev/uinput?
Because I didn't find such information.

If yes where to find information about it?

Thanks
Marcin

**Comment by alexlarsson** [comment]
There is no finegrained access for it, you have to use the hammer `--device=all`

**Comment by alexlarsson** [comment]
Closing this as dup of https://github.com/flatpak/flatpak/issues/7

**Comment by mwoz123** [comment]
Does `--device=all` have be used from commandline or it can be added to e.g. metadata?
e.g.:
`[Context]`
`devices=all;`
?

**Comment by sezanzeb** [comment]
> Does `--device=all` must be used from commandline only or it can be added to e.g. metadata?
> e.g.:
> `[Context]`
> `devices=all;`
> ?

I think that needs to be below `finish-args:` in the yml file
