### ISSUE TITLE
build-import-bundle doesn't update OSTree summary

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#70]
I'm trying out a bundle.
The command flatpak build-import-bundle ~/repos/local howl.pak succeeds, but
flatpak --user remote-ls local does not show the imported app, and installing it doesn't work.
After running ostree summary --repo=$HOME/repos/local -u everything works.

**Comment by alexlarsson** [comment]
You can also run `flatpak build-update-repo`, but yeah, this should be fixed.

**Comment by matthiasclasen** [comment]
Looks like this was fixed in 6386ea3222231ea475afef734fe74cab0cdac829
