### ISSUE TITLE
flatpak-builder: Allow removing individual module(s) from build cache manually

### ISSUE THREAD

**Issue by casept** [flatpak/flatpak#704]
`flatpak-builder` currently doesn't invalidate the cache of a module build when that module's .json is changed. This leads to situations where you're forced to clear caches for all parts, only to rebuild a part of which only a configure option was changed. This doesn't pose much of a problem with smaller flatpaks, but becomes a serious issue once the bundle takes hours to compile. I think the best approach to solving this would be to give users the option to clear the build cache of that module and all subsequent modules manually (possibly without clearing `ccache`).

**Comment by alexlarsson** [comment]
That sounds weird. When is not a module change causing a rebuild? It should always happen.

**Comment by casept** [comment]
I added `configure-args` to a module, which didn't trigger a rebuild. Interestingly, me adding some `build-options` just now did trigger a rebuild. Maybe it's an issue localized to `configure-args`?

**Comment by alexlarsson** [comment]
Its `config-opts`, not `configure-args`. And it doesn't really depend on the json itself, but on the things that it actually uses.

**Comment by alexlarsson** [comment]
However, we should probably warn better about unrecognized properties...

**Comment by ranguli** [comment]
I seem to be running into this issue as well. I've updated the Flatpak manifest (changing the branch name and build system of a dependency) but it's still using the cache and not triggering rebuilds.
