### ISSUE TITLE
Not found symbols in configure

### ISSUE THREAD

**Issue by phxvyper** [flatpak/flatpak#706]
I `git clone`d from master. `autoconf`'d in origin. Ran `./configure` immediately after. The following errors were produced:

```
./configure: 4178: ./configure: AM_PROG_CC_C_O: not found
./configure: 4179: ./configure: AC_DISABLE_STATIC: not found
./configure: 4181: ./configure: Syntax error: word unexpected (expecting ")")
```

I triple-checked that autoconf is up to date, and I also deleted my local clone and re-cloned after, same issue. What might be causing this issue and is there a way to fix it?

**Comment by matthiasclasen** [comment]
you are missing autoconf macros, so autoconf fails t expand some macros.

**Comment by phxvyper** [comment]
Is there a way to add those macros?

**Comment by phxvyper** [comment]
adding 

```ac
m4_pattern_allow([AC_DISABLE_STATIC])
m4_pattern_allow([AM_GNU_GETTEXT])
m4_pattern_allow([AM_GNU_GETTEXT_VERSION])
```

seemed to amend that problem. But now arises another issue:
```
automate: error: cannot open < libglnx/Makefile-libglnx.am.inc: No such file or directory
```
Cloning the [libglnx repo](https://github.com/GNOME/libglnx) doesn't help - repo doesnt contain that file.

**Comment by TingPing** [comment]
This was discussed on the irc channel: Missing deps for libtool, gettext, and gobject-introspection. Also running `autoreconf` instead of `./autogen.sh`.

We can make more useful errors when missing macros at least.
