### ISSUE TITLE
Different cursor theme in flatpak apps

### ISSUE THREAD

**Issue by Corsseir** [flatpak/flatpak#709]
I have installed Spotify (flatpak) and I noticed that the cursor theme is different from which I use (Adwaita). It looks like flatpak app doesnt inherit cursor theme from dconf settings.

**Comment by matthiasclasen** [comment]
Spotify is using the freedesktop runtime, which does not include any icon or cursor theme. And the spotify flatpak itself doesn't include any cursors either.

This may be fixed if we define and populate extensions for themes.

**Comment by Corsseir** [comment]
I use default Adwaita theme with gnome 3.22 and fedora 25.

Pt., 14 kwi 2017, 17:54 użytkownik Matthias Clasen <notifications@github.com>
napisał:

**Comment by alex285** [comment]
@matthiasclasen is this the same bug with Skype? it uses X cursor and some different theme too

**Comment by Corsseir** [comment]
I have this bug in every flatpak app in Fedora 25, gnome 3.22.

Sob., 15 kwi 2017, 23:52 użytkownik alex285 <notifications@github.com>
napisał:

**Comment by matthiasclasen** [comment]
See #114 for suggestions for how to fix this for both themes and icon themes.

**Comment by Corsseir** [comment]
Sry, but I cant find the solution of my problem in #114. Can you be more
specific please?

**Comment by matthiasclasen** [comment]
We have gtk and icon themes that can be installed as flatpak extensions now.

**Comment by Corsseir** [comment]
Ok, but how to install these extensions?

**Comment by Corsseir** [comment]
It should be like: flatpak install gnome org.freedesktop.Platform.Icontheme
?

**Comment by alexlarsson** [comment]
This is a work in progress, so not a lot of themes are packaged yet, but yeah, something like that will install it.

**Comment by Sparsa** [comment]
> I have installed Spotify (flatpak) and I noticed that the cursor theme is different from which I use (Adwaita). It looks like flatpak app doesnt inherit cursor theme from dconf settings.

Its been 2 years now, any progress in this measure? I am facing the same issue, do you have any workaround?

**Comment by lae** [comment]
for folks coming from search engines:

`flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`

might be all that you need, provided that's where your cursor theme is located. (it was enough for me, but I'm not quite sure how the icon theme is determined (if it even is) within the app since I can't find a relevant .gtkrc in the directories it can access.)

**Comment by TingPing** [comment]
> but I'm not quite sure how the icon theme is determined (if it even is) within the app since I can't find a relevant .gtkrc in the directories it can access.)

Its provided over XSettings that some service (like `gsd-xsettings` on gnome) provides.

Anyway this problem is actually fixed as of https://github.com/flatpak/flatpak/pull/3247

**Comment by ryanrms** [comment]
Came in from a search engine, @lae's solution was PERFECT.  Just made the whole .icons directory readable by the flatpak application in question (Spotify), and viola, it now shows my mouse cursor instead of the default Adwaita theme it was showing before.  Makes me want to use more flatpak apps, and it's already way better than snap packages.  Thanks again friend!

**Comment by basedtho** [comment]
> `flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`

I would like to add that if that doesn't work for you do
`cp /usr/share/icons ~/.icons -r`

**Comment by lolrepeatlol** [comment]
> > `flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`
> 
> I would like to add that if that doesn't work for you do
> `cp /usr/share/icons ~/.icons -r`

does that automatically do it for every flatpak? i'm looking for a way to have this work every time i install a flatpak instead of having to worry about doing it for each app every time

**Comment by nozomimiyamori** [comment]
For Gentoo uers.

To use Adwaita cursor theme, You need to mount cursor directory on `/usr/share/icons/Adwaita/cursors`  because Gentoo installs cursor themes into non-standard directory (they install cursors into `/usr/share/cursors`, but flatpak expects cursors are in `/usr/share/icons`).

```
mkdir /usr/share/icons/Adwaita/cursors
mount -o ro,bind /usr/share/cursors/xorg-x11/Adwaita/cursors /usr/share/icons/Adwaita/cursors
```

That's it! If you want to mount the cursor directory automatically, add `fstab` entry like below.

```
/usr/share/cursors/xorg-x11/Adwaita/cursors	/usr/share/icons/Adwaita/cursors	none	ro,bind
```

**Comment by jcdickinson** [comment]
> > `flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`
> 
> I would like to add that if that doesn't work for you do [...]
> `cp /usr/share/icons ~/.icons -r`

Alternatively, you should be able to fix this for all flatpaks forever (at least on Ubuntu 20.10) with:

```sh
flatpak --user override --filesystem=/home/$USER/.icons/:ro
flatpak --user override --filesystem=/usr/share/icons/:ro
```

**Comment by FireLizard** [comment]
Hmm no. That didn't solved the problem on CentOS Stream 8 with KDE Plasma 5.18.4.
Maybe you can help me, please.
```bash
$ flatpak --version
Flatpak 1.8.5

$ flatpak override --user --filesystem=/home/$USER/.local/share/icons/:ro org.kde.skrooge

$ flatpak info --user --show-permissions org.kde.skrooge                                 
[Context]
shared=ipc;
sockets=x11;wayland;pulseaudio;
devices=dri;
filesystems=xdg-config/kdeglobals:ro;host;/home/me/.local/share/icons/:ro;

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk

$ flatpak run --user org.kde.skrooge
##WARNING: Qt: Session management error: Could not open network socket
##WARNING: Icon [view-statistics] not found
...
```
Its the same behaviour with _org.kde.kontact_ .
The only thing I can do is copying the icons into /usr/share/icons. But that's ugly for my grandmother.

**Comment by nozomimiyamori** [comment]
> Hmm no. That didn't solved the problem on CentOS Stream 8 with KDE Plasma 5.18.4.
> Maybe you can help me, please.
> 
> ```shell
> $ flatpak --version
> Flatpak 1.8.5
> 
> $ flatpak override --user --filesystem=/home/$USER/.local/share/icons/:ro org.kde.skrooge
> 
> $ flatpak info --user --show-permissions org.kde.skrooge                                 
> [Context]
> shared=ipc;
> sockets=x11;wayland;pulseaudio;
> devices=dri;
> filesystems=xdg-config/kdeglobals:ro;host;/home/me/.local/share/icons/:ro;
> 
> [Session Bus Policy]
> com.canonical.AppMenu.Registrar=talk
> 
> $ flatpak run --user org.kde.skrooge
> ##WARNING: Qt: Session management error: Could not open network socket
> ##WARNING: Icon [view-statistics] not found
> ...
> ```
> 
> Its the same behaviour with _org.kde.kontact_ .
> The only thing I can do is copying the icons into /usr/share/icons. But that's ugly for my grandmother.

`--filesystem=$HOME/.icons:ro` might work, not `--filesystem=$HOME/.local/share/icons:ro`

**Comment by FireLizard** [comment]
> > Hmm no. That didn't solved the problem on CentOS Stream 8 with KDE Plasma 5.18.4.
> > Maybe you can help me, please.
> > ```shell
> > $ flatpak --version
> > Flatpak 1.8.5
> > 
> > $ flatpak override --user --filesystem=/home/$USER/.local/share/icons/:ro org.kde.skrooge
> > 
> > $ flatpak info --user --show-permissions org.kde.skrooge                                 
> > [Context]
> > shared=ipc;
> > sockets=x11;wayland;pulseaudio;
> > devices=dri;
> > filesystems=xdg-config/kdeglobals:ro;host;/home/me/.local/share/icons/:ro;
> > 
> > [Session Bus Policy]
> > com.canonical.AppMenu.Registrar=talk
> > 
> > $ flatpak run --user org.kde.skrooge
> > ##WARNING: Qt: Session management error: Could not open network socket
> > ##WARNING: Icon [view-statistics] not found
> > ...
> > ```
> > 
> > 
> > Its the same behaviour with _org.kde.kontact_ .
> > The only thing I can do is copying the icons into /usr/share/icons. But that's ugly for my grandmother.
> 
> `--filesystem=$HOME/.icons:ro` might work, not `--filesystem=$HOME/.local/share/icons:ro`

Thank you for quick replying.
But unfortunately this doesn't work, too. KDE is downloading new icon sets (installed with SystemSettings) to `$HOME/.local/share/icons` (see https://develop.kde.org/docs/plasma/).

**Comment by raffaem** [comment]
> for folks coming from search engines:
> 
> `flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`
> 
> might be all that you need, provided that's where your cursor theme is located. (it was enough for me, but I'm not quite sure how the icon theme is determined (if it even is) within the app since I can't find a relevant .gtkrc in the directories it can access.)

You are great. Works on Ubuntu 20.10

Notice that for this to work you first need to _close the application_ that is using the default cursor.

Some applications (like Element) stays open in the task bar. You need to close them from the task bar too. Run the fix then re-open them.

**Comment by d4f5409d** [comment]
> > > `flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`
> > 
> > 
> > I would like to add that if that doesn't work for you do [...]
> > `cp /usr/share/icons ~/.icons -r`
> 
> Alternatively, you should be able to fix this for all flatpaks forever (at least on Ubuntu 20.10) with:
> 
> ```shell
> flatpak --user override --filesystem=/home/$USER/.icons/:ro
> flatpak --user override --filesystem=/usr/share/icons/:ro
> ```

Thank you so much! Do any of you have this solution to snaps as well?

**Comment by Nightfirecat** [comment]
> Alternatively, you should be able to fix this for all flatpaks forever (at least on Ubuntu 20.10) with:
> 
> ```shell
> flatpak --user override --filesystem=/home/$USER/.icons/:ro
> flatpak --user override --filesystem=/usr/share/icons/:ro
> ```

This works great for the default icon, but any non-default cursor (pointer, text, move, resize, etc. [All the cursors besides auto, default, and wait in the keyword table](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#keyword)) appears as it did before applying this fix. Is there some workaround for that?

**Comment by hholst80** [comment]
> Didn't work for Telegram on Ubuntu 22.04 for me.

What did you do to make it work in Xorg? I am using just environment variables to enable HiDPI settings. But all flatpak apps - including Telegram (which is a QT app if I am not mistaken) fails set HiDPI settings.

```
export GDK_SCALE=2
export QT_SCALE_FACTOR=2
export WINIT_X11_SCALE_FACTOR=2
export XCURSOR_SIZE=48
```

```
 ~  flatpak override --user --show
[Context]
filesystems=/home/om/.icons:ro;/usr/share/icons:ro;

[Environment]
GDK_SCALE=2
XCURSOR_SIZE=48
QT_SCALE_FACTOR=2
```

**Comment by miromarszal** [comment]
> Didn't work for Telegram on Ubuntu 22.04 for me.
> 
> **Edit**: Seems to work on Xorg but not Wayland.

Same for me — does not work on Ubuntu on Wayland.

**Comment by hholst80** [comment]
I think you need to use XCURSOR_THEME=Adwaita

**Comment by miromarszal** [comment]
Ok my bad, this was actually necessary: 
```
cp /usr/share/icons ~/.icons -r
```
followed by 
```
flatpak --user override --filesystem=/home/$USER/.icons/:ro 
```
I was expecting that this is sufficient: 
```
flatpak --user override --filesystem=/usr/share/icons/:ro 
```
but it doesn't seem to affect anything. So I had to copy the icons to my home dir. 

By the way, this workaround should be necessary only temporarily. Normally, the correct theme should be picked up, provided that you installed the right flatpak. On Ubuntu, however, names of colored Yaru themes don't match those of flatpaks (https://github.com/ubuntu/yaru/issues/3618), so everything falls back to Adwaita, but folks are working on this.

**Comment by joshbode** [comment]
this was sufficient to fix the cursor issue for me, which just copies the theme `cursor` directories:
```bash
$ find /usr/share/icons -type d -name cursors -prune -printf "%P\n" | while read X; do NAME=$(dirname "${X}"); mkdir -p "${HOME}/.local/share/icons/${NAME}"; cp -r "/usr/share/icons/${X}" "${HOME}/.local/share/icons/${X}"; done
$ flatpak override --user --filesystem=xdg-data/icons:ro
```
note: `xdg-data` is automatically interpreted as your `${XDG_DATA_HOME}` (which by default is `${HOME}/.local/share`)

**Comment by hholst80** [comment]
The problem I see with many application is that they do not honor xdg-data and $XDG_DATA_HOME. XCURSOR_PATH will however work. If it is not set ~/.icons is part of the default so that will indeed work because flatpaks mount there. Flatpaks will however not mount host icons under /usr as one could assume. Instead the app needs to use $XDG_DATA_HOME to find it.

**Comment by JohnOberhauser** [comment]
I needed to override the `XCURSOR_PATH` environment variable as well as grant permissions to the icons directory.

```
flatpak override --user --env=XCURSOR_PATH=~/.icons
flatpak override --user --filesystem=/home/$USER/.icons/:ro
```

**Comment by Gustash** [comment]
For me, on Arch, the filesystem override to `/home/$USER/.icons:ro` alone stopped working recently.

The solution was to also allow filesystem read access to `xdg-config/gtk-3.0`.

```
flatpak override --user --filesystem=/home/$USER/.icons:ro
flatpak override --user --filesystem=/usr/share/icons:ro
flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
```

**Comment by TheDylanArts** [comment]
As of Jan 12th, 2023, I ran the following commands (in this order) on Fedora 37 (Gnome 43) and all my Flatpak apps now see the correct cursor icons:

```
cp /usr/share/icons ~/.icons -r
flatpak --user override --filesystem=/home/$USER/.icons/:ro 
flatpak --user override --filesystem=/usr/share/icons/:ro
flatpak override --user --env=XCURSOR_PATH=~/.icons
flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
```

**Comment by firefoxlover** [comment]
Solution for KDE:

`flatpak install -y kvantum`

**Comment by hexchain** [comment]
Most of these workarounds involve copying system icons to the user directory, which IMO isn't ideal as it creates duplicates, and these directories have to be synchronized manually when new icons are installed or updated system-wide. Here is my attempt at a cleaner solution that doesn't involve duplication:

```
flatpak override --user --filesystem=/usr/share/icons/:ro
flatpak override --user --filesystem=xdg-data/icons:ro
flatpak override --user --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
```

Note that `~/.local/share/icons` is preferred according to xdg basedir-spec. In my system `~/.icons` is a link to it.

**Comment by TheDylanArts** [comment]
> Most of these workarounds involve copying system icons to the user directory, which IMO isn't ideal as it creates duplicates, and these directories have to be synchronized manually when new icons are installed or updated system-wide. Here is my attempt at a cleaner solution that doesn't involve duplication:
> 
> ```
> flatpak override --user --filesystem=/usr/share/icons/:ro
> flatpak override --user --filesystem=xdg-data/icons:ro
> flatpak override --user --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
> ```
> 
> Note that `~/.local/share/icons` is preferred according to xdg basedir-spec. In my system `~/.icons` is a link to it.

I undid the changes I made and applied these and it works. Thank you! I will edit my post to point to yours.

**Comment by smcv** [comment]
@hexchain:

> `flatpak override --user --filesystem=/usr/share/icons/:ro`

This doesn't do anything useful. `--filesystem=/usr/anything` is ignored and has no effect, because `/usr` is reserved for the Flatpak runtime. The next development release of Flatpak will show a warning about this.

> `flatpak override --user --filesystem=xdg-data/icons:ro`

This is likely to be unnecessary for the workaround you suggest. `--filesystem=xdg-data/icons` would expose `~/.local/share/icons` as something like `~/.var/app/org.gnome.Recipes/data/icons` in the container, and that is not the path you're using in your `XCURSOR_PATH`.

> `--env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`

If your cursors are in `~/.local/share/icons` or `/usr/share/icons`, then this should work even without the other overrides, because Flatpak makes these paths available by default:

* host `/usr/share/icons` -> sandbox `/run/host/share/icons`
* host `$XDG_DATA_HOME/icons` (usually `~/.local/share/icons`) -> sandbox `/run/host/user-share/icons`

**Comment by hexchain** [comment]
@smcv: Thanks for pointing this out! I've edited my comment to simplify the solution even more.

But upon further digging, the fix to this cursor issue (https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1484) seems to be already available in runtime 22.08, so I'm not quite sure what's going on for the apps here. Maybe it's because Electron and Chromium-based browsers use their vendored copy of libwayland?

**Comment by smcv** [comment]
> Maybe it's because Electron and Chromium-based browsers use their vendored copy of libwayland?

If they do that, then any changes to a runtime's libwayland are not going to get applied to them until/unless they update their vendored copy; likewise if they have a vendored copy of libXcursor and a runtime makes changes to that. If this is a general Electron/Chromium problem, then the Flatpak apps that wrap those browsers could set the `XCURSOR_PATH` as a workaround.

(This makes a nice example of how a relatively broad/vague issue report often isn't actionable, because everyone who replies to it has a different system setup or is working with different apps, so there is no shared understanding of the scope of the issue or whether it has been resolved.)

**Comment by firefoxlover** [comment]
Cursors fit after applying all these commands @TheDylanArts dont know what worked but all apps automatically adapt the correct cursor.

**Comment by d4f5409d** [comment]
> Cursors fit after applying all these commands @TheDylanArts dont know what worked but all apps automatically adapt the correct cursor.

Thanks for fixing this issue. I remember I had a hard time back then where there was no fix for this.

**Comment by Ultra980** [comment]
Thanks to @lae 's comment, I figured out how to do it. I also made a little script to set it for all flatpaks:

```bash
for i in $(flatpak list --columns=application)
do
flatpak --user override $i --filesystem=$HOME/.icons:ro
flatpak --user override $i --filesystem=$HOME/.local/share/icons:ro
flatpak --user override $i --filesystem=/usr/share/icons:ro
done
```

**Comment by Silveere** [comment]
@hexchain's solution is what worked for me, and it seems to be the simplest and most elegant solution. I'd like to emphasize the importance of the icon config being located in `~/.local/share/icons`. The solution wasn't working for me at first, but after moving all my icon config to `~/.local/share/icons` and making `~/.icons` a symlink to it, everything started working properly.

**Comment by Apple-QAQ** [comment]
> Most of these workarounds involve copying system icons to the user directory, which IMO isn't ideal as it creates duplicates, and these directories have to be synchronized manually when new icons are installed or updated system-wide. Also, icon directories are [available by default](https://github.com/flatpak/flatpak/issues/709#issuecomment-1418926977) inside flatpak containers without the need for any overrides (thanks @smcv for pointing this out!). Here is an attempt at a cleaner and simpler solution:
> 
> ```
> flatpak override --user --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
> ```
> 
> Note that `~/.local/share/icons` is preferred according to xdg basedir-spec. In my system `~/.icons` is a link to it.

Thank you! It's useful on my Archlinux KDE Plasma 5.27.5!

**Comment by firefoxlover** [comment]
@dipankardas011 

### DONT DO THIS
Its not working across every Desktop, and for me it currently irreversibly broke cursors completely. Luckily there is some fallback cursor, but before it actually worked normally without any overrides, now it doesnt, at all.

I removed all overrides from every app using a script

```
#!/bin/bash

app_list=$(flatpak list --columns=application)
echo $app_list

# Iterate through each application and reset the overrides
for app in $app_list; do
  flatpak override --reset "$app" &&\
  echo "'$app' bereinigt" ||\
  echo "'$app' bereinigen fehlgeschlagen."
done
```

But its still the same

**Comment by Flashwalker** [comment]
## Solution

#### Set global Overrides (in userspace)
```bash
flatpak --user override --filesystem=xdg-data/themes:ro
flatpak --user override --filesystem=$HOME/.themes:ro
flatpak --user override --filesystem=xdg-data/icons:ro
flatpak --user override --filesystem=$HOME/.icons:ro
flatpak --user override --filesystem=/usr/share/icons/:ro
```

#### Additional: link userspace gtk settings files to flatpak apps dirs
```bash
user_confdir="${XDG_CONFIG_HOME:-$HOME/.config}"
flat_theme_name="$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")"
xfconf-query -V >& /dev/null
hasxfce=$?
if ! ((hasxfce == 127)); then
    xfce=true
fi
for dir in ${HOME}/.var/app/*; do
    # Link files
    flat_confdir3="${dir}/config/gtk-3.0"
    flat_confdir4="${dir}/config/gtk-4.0"
    mkdir -p "$flat_confdir3"
    mkdir -p "$flat_confdir4"
    ln -s "${user_confdir}/gtk-3.0/settings.ini" "${flat_confdir3}"/
    ln -s "${user_confdir}/gtk-3.0/gtk.css" "${flat_confdir3}"/
    ln -s "${user_confdir}/gtk-4.0/settings.ini" "${flat_confdir4}"/
    ln -s "${user_confdir}/gtk-4.0/gtk.css" "${flat_confdir4}"/

    # Set theme via dconf
    flatpak info "${dir##*/}" >& /dev/null && \
        flatpak run --command=bash<<<"gsettings set org.gnome.desktop.interface gtk-theme $flat_theme_name" "${dir##*/}"

    # If XFCE copy xsettings file
    if $xfce; then
        flat_xfconfdir="${dir}/config/xfce4/xfconf/xfce-perchannel-xml"
        mkdir -p "$flat_xfconfdir"
        cp "${user_confdir}/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml" "$flat_xfconfdir"/
    fi
done
```

**Comment by DSDV** [comment]
> > Most of these workarounds involve copying system icons to the user directory, which IMO isn't ideal as it creates duplicates, and these directories have to be synchronized manually when new icons are installed or updated system-wide. Here is my attempt at a cleaner solution that doesn't involve duplication:
> > ```
> > flatpak override --user --filesystem=/usr/share/icons/:ro
> > flatpak override --user --filesystem=xdg-data/icons:ro
> > flatpak override --user --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that `~/.local/share/icons` is preferred according to xdg basedir-spec. In my system `~/.icons` is a link to it.
> 
> I undid the changes I made and applied these and it works. Thank you! I will edit my post to point to yours.

Sadly for me it did not work :/ 
i tried setting it via FlatSeal and copying your command into my Terminal. 

Any suggestions what might be wrong? (i am on latest Fedora 38 with gnome/wayland)

**Comment by Flashwalker** [comment]
> i also made sure that the Cursor Icons are in ./icons and ./share/icons

in userspace it should be `~/.local/share/icons` and `~/.local/share/themes`

**Comment by DSDV** [comment]
> in userspace your icons and themes should be in `~/.local/share/icons` and `~/.local/share/themes`

Thanks now i have a coherent look & feel <3

**Comment by McBruno712** [comment]
Just for the record, if you moved your icons to userspace and it's sitll not working, you have to change your cursor theme to another and then set it back to the one you want. 

I'm using LMDE 6 and was trying to fix Stremio flatpak.

**Comment by Flopster101** [comment]
Currently using Plasma 6 (Wayland) on EndeavourOS and none of the fixes above helped me, but the reply at https://github.com/flatpak/flatpak/issues/2861#issuecomment-1922213727 pointed me in the right direction.

I already had the file with the contents mentioned in the reply, but I think that xdg-desktop-portal isn't recognizing my desktop as KDE, and therefore isn't loading the correct file. I copied the file to the local config like this:

`cp /usr/share/xdg-desktop-portal/kde-portals.conf .config/xdg-desktop-portal/portals.conf`

And after restarting `xdg-desktop-portal` and `xdg-desktop-portal-gtk`, my cursor theme finally loaded correctly!

Although this seems like a problem unrelated to flatpak, it was only affecting flatpak GTK apps for me.

**Comment by DenebTM** [comment]
Using Plasma 6 (Wayland) on Arch Linux; adding an override for `xdg-config/kcminputrc:ro` fixed the cursor theme in Audacious for me.

**Comment by FunctionDJ** [comment]
```
flatpak --user override --filesystem=/home/$USER/.icons/:ro 
flatpak --user override --env=XCURSOR_PATH=~/.icons
```
these are the only two lines i needed to fix the cursor in all of my flatpaks. the first one fixed it in most apps, the second one also fixed discord.

**Comment by GuilhermeIsNotUnix** [comment]
> > > `flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`
> > 
> > 
> > I would like to add that if that doesn't work for you do [...]
> > `cp /usr/share/icons ~/.icons -r`
> 
> Alternatively, you should be able to fix this for all flatpaks forever (at least on Ubuntu 20.10) with:
> 
> ```shell
> flatpak --user override --filesystem=/home/$USER/.icons/:ro
> flatpak --user override --filesystem=/usr/share/icons/:ro
> ```

I had this problem with the cursor having different sizes on all my Flatpak on my Fedora 40. This solved it perfectly. Thank you!

**Comment by claymorwan** [comment]
Did what qwyop said but doesn't seem to work for me, I'm also on Arch Linux with KDE Plasma 6 (Wayland) so that's weird

**Comment by Mohabdo21** [comment]
I had this issue on GNOME (Wayland), and I used this one-liner to apply my UI configuration to all installed Flatpaks:
```
for app in $(flatpak list --app --columns=application); do
  flatpak --user override "$app" \
    --filesystem=~/.icons/:ro \
    --filesystem=/usr/share/icons/:ro \
    --filesystem=~/.themes/:ro \
    --filesystem=/usr/share/themes/:ro \
    --filesystem=~/.fonts/:ro \
    --filesystem=/usr/share/fonts/:ro \
    --env=GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | tr -d \')
done
```

**Comment by violog** [comment]
Nothing from this thread helped me on Linux Mint, despite Telegram Desktop app worked good in Fedora Kinoite.

Found fix here: https://forums.linuxmint.com/viewtopic.php?t=443925

> 1. create a directory named default inside $HOME/.local/share/icons/; you can do this with the file manager or you can run > mkdir -p $HOME/.local/share/icons/default in the terminal
> 2. create a text file named index.theme inside the $HOME/.local/share/icons/default directory 
> 3. write inside the file the following lines: 
> 4. [icon theme]
> Inherits=Bibata-Modern-Classic

**Comment by Flashwalker** [comment]
> Nothing from this thread helped me on Linux Mint, despite Telegram Desktop app worked good in Fedora Kinoite.
> 
> Found fix here: https://forums.linuxmint.com/viewtopic.php?t=443925
> 
> > 1. create a directory named default inside $HOME/.local/share/icons/; you can do this with the file manager or you can run > mkdir -p $HOME/.local/share/icons/default in the terminal
> > 2. create a text file named index.theme inside the $HOME/.local/share/icons/default directory
> > 3. write inside the file the following lines:
> > 4. [icon theme]
> >    Inherits=Bibata-Modern-Classic

also `~/.icons/default/index.theme`

**Comment by Stradios** [comment]
I just encountered this problem in a game. It usually worked for me, but this time it didn’t, so I started thinking and searching online for a solution, and I came up with this.
https://github.com/Stradios/Make-Flatpak-Apps-Use-Your-Cursor-Theme-Veloren-Example-/tree/main
