### ISSUE TITLE
flatpak install creates textfiles instead of symlinks 

### ISSUE THREAD

**Issue by Duncaen** [flatpak/flatpak#710]
Hello,

I'm trying to get flatpak packaged for Void Linux, my problem is that I can't run any dynamically linked binaries in flatpak.
I first copied a static busybox build into the `app/bin` directory to inspect the environment which worked fine, I noticed that files in `/usr/lib` which should be symlinks were text files with the target name inside.

This happens already outside of the namespace:
```
~$ ls -lsa /var/lib/flatpak/app/org.gnome.sudoku/current/active/files/lib/
total 888K
4.0K drwxr-xr-x 4 root root 4.0K Jan  1  1970 ./
4.0K drwxr-xr-x 6 root root 4.0K Apr 13 23:34 ../
4.0K drwxr-xr-x 2 root root 4.0K Jan  1  1970 debug/
4.0K -rwxr-xr-x 2 root root  965 Jan  1  1970 libgee-0.8.la*
4.0K -rw-r--r-- 3 root root   20 Jan  1  1970 libgee-0.8.so
4.0K -rw-r--r-- 3 root root   20 Jan  1  1970 libgee-0.8.so.2
808K -rwxr-xr-x 2 root root 806K Jan  1  1970 libgee-0.8.so.2.6.0*
4.0K -rwxr-xr-x 2 root root  950 Jan  1  1970 libqqwing.la*
4.0K -rw-r--r-- 3 root root   19 Jan  1  1970 libqqwing.so
4.0K -rw-r--r-- 3 root root   19 Jan  1  1970 libqqwing.so.2
 40K -rwxr-xr-x 2 root root  39K Jan  1  1970 libqqwing.so.2.1.0*
4.0K drwxr-xr-x 2 root root 4.0K Jan  1  1970 pkgconfig/
~$ file /var/lib/flatpak/app/org.gnome.sudoku/current/active/files/lib/libqqwing.so.2
/var/lib/flatpak/app/org.gnome.sudoku/current/active/files/lib/libqqwing.so.2: ASCII text, with no line terminators
~$ cat /var/lib/flatpak/app/org.gnome.sudoku/current/active/files/lib/libqqwing.so.2
~$ hd /var/lib/flatpak/app/org.gnome.sudoku/current/active/files/lib/libqqwing.so.2
00000000  6C 69 62 71 71 77 69 6E - 67 2E 73 6F 2E 32 2E 31  |libqqwing.so.2.1|
00000010  2E 30 00                -                          |.0.|
```

Here is a strace log running `flatpak install -v --from https://git.gnome.org/browse/gnome-apps-nightly/plain/gnome-sudoku.flatpakref`:
https://gist.github.com/d56642dd0f75e8e777820692152a09c2

Versions of the libraries my flatpak build uses:
 ```
bubblewrap-0.1.8_1
libarchive-3.3.1_1
libostree-2017.4_1
libsoup-2.56.0_1
json-glib-1.2.8_1
glib-2.52.0_1
libXau-1.0.8_1
libseccomp-2.3.2_1
gpgme-1.7.1_2
glibc-2.25_3
polkit-0.113_2
fuse-2.9.7_1
libelf-0.168_1
```

Do you need more informations, or did I mess up something with the build?

Thanks,
Duncan

**Comment by Duncaen** [comment]
I got it working by downgrading `libostree` to `2017.3`.

**Comment by matthiasclasen** [comment]
i'm seeing this in fedora rawhide too

**Comment by alexlarsson** [comment]
I see this with latest ostree too. Bisecting.

**Comment by alexlarsson** [comment]
Seems like this broke it:
https://github.com/ostreedev/ostree/commit/d3385a3014e173299094133d644763e34e5ecd52

**Comment by alexlarsson** [comment]
Fix in: https://github.com/ostreedev/ostree/pull/799

**Comment by cgwalters** [comment]
https://github.com/ostreedev/ostree/releases/tag/v2017.5

**Comment by cgwalters** [comment]
It looks like to recover from this, you'll need to uninstall/reinstall the affected runtimes/apps after upgrading libostree.

**Comment by smcv** [comment]
To make things like this easier to recover from, it would be nice if there was a `flatpak update --verify` or something, which checked file content/metadata and redeployed where necessary; or perhaps `flatpak update --redeploy`.

**Comment by alexlarsson** [comment]
Doing an ostree fsck + redeploy seems like a useful "rescue" operation.
