### ISSUE TITLE
eu-strip used outside of the runtime

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#711]
When using flatpak-builder, builder_post_process_debuginfo() calls eu_strip() which boils down to a call of eu-strip on the host system. This is needed by all systems that use flatpak-builder.

So we need to do one of:

 * Take a dependency on elfutils form flatpak-builder (missing in various distro packages today such as debian)
 * Try to use eu-strip from within the runtime

**Comment by alexlarsson** [comment]
I think this has been fixed in the debian package, no?
We can't really rely on it being in the runtime. For instance, we may be building the runtime, or using a minimal one.

**Comment by csoriano89** [comment]
Seeing this issue in Arch. If Flatpak uses it internally, shouldn't it hard depend on it?
