### ISSUE TITLE
"uname -m" reports host arch inside runtimes and flatpaks

### ISSUE THREAD

**Issue by kujeger** [flatpak/flatpak#712]
For various reasons I'm having to build i386 flatpak images, and some of the things I put inside use "uname -m" in start-scripts or configure scripts.

This sometimes results in e.g. a library trying to build the x86_64 version with an i386 runtime, which does not work.
Some proprietary software also do this when starting up, trying to decide on which actual binaries to use.

Would it be possible to have flatpak return the arch of the runtime/image?
If that's not feasible or advisable, could setarch become part of the freedesktop.org runtime? It would make workarounds a lot easier.

**Comment by matthiasclasen** [comment]
uname is just a wrapper around the uname syscall, so it directly returns kernel information, flatpak is not involved.

**Comment by kujeger** [comment]
Could flatpak automatically wrap stuff inside setarch ?

**Comment by alexander255** [comment]
Wouldn't this simply be a call to `personality(PER_LINUX32)` when running 32-bit container inside of a 64-bit OS-kernel?

I suppose that call could be added somewhere in `flatpak_run_app` or `flatpak_run_setup_base_argv` (file [`common/flatpak-run.c`](https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c))? It already has some code for dealing with multiarch in the seccomp filters, after all.
Is my observation correct here that `(flags & FLATPAK_RUN_FLAG_MULTIARCH) != 0` is only true when the app to be run is from a different architecture? Is it correct that the only way to run an app of a different architecture currently is to run a 32-bit app on a 64-bit platform?
If both of these assumptions hold then a patch should be pretty easy…

**Comment by alexlarsson** [comment]
For now you can wrap this in a setarch call, but yeah, it might makes sense to do this in flatpak build.

**Comment by alexlarsson** [comment]
I'm somewhat wary about always setting PER_LINUX32 when running an app. It seems that this could cause some weird issues like about dialogs showing i386 on x86-64 machines, which may be confusing to users. If some app really needs this i think that can be hacked around in the app itself.

However, this is definitely a problem when building, so i think that flatpak build should automatically set it.

**Comment by alexander255** [comment]
@alexlarsson: Just what I had in mind but with a much better implementation :-)
