### ISSUE TITLE
[BASH] Autocompletion cannot recoginize multiple installed versions

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#719]
example app: `org.gnome.Builder`

there are two installations
```
org.gnome.Builder/x86_64/master
org.gnome.Builder/x86_64/stable
```
on 
```
flatpak run org.gnome.B[tab]
```
it autocompletes
```
org.gnome.Builder
```
expected
```
org.gnome.Builder/x86_64/master
org.gnome.Builder/x86_64/stable
```

that is what `flatpak-zsh-completion` does
https://github.com/bil-elmoussaoui/flatpak-zsh-completion/issues/1

**Comment by matthiasclasen** [comment]
I briefly looked into this, and it is not easy to get the behavior to feel right, with bash completion.
