### ISSUE TITLE
flatpak_installation_get_id is sometimes empty

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#720]
We were looking into how to identify a `FlatpakInstallation` but in my system both _get_id and _get_display_name return empty. Shouldn't `flatpak_installation_get_id` return a unique id?

`qDebug() << "ggggg" << flatpakInstallation << g_file_get_path(file) << "." << flatpak_installation_get_id(flatpakInstallation) << "." << flatpak_installation_get_display_name(flatpakInstallation);`

```
$ plasma-discover --backends flatpak-backend |& grep ggg | sort -u
discover(3265)/(default) FlatpakResource::installationPath: ggggg 0x7f5170009160 /var/lib/flatpak . default . Default system directory
discover(3265)/(default) FlatpakResource::installationPath: ggggg 0x7f51700092b0 /home/apol/.local/share/flatpak .  . 
```

**Comment by matthiasclasen** [comment]
I agree that it would be nice to have an ID and display name for the standard locations as well, but the way the code is written, those functions return NULL for the standard locations.

**Comment by aleixpol** [comment]
Maybe it should return the path otherwise?
I don't see what's the point of having an id if it can be null...

**Comment by matthiasclasen** [comment]
Interestingly, we actually have a function that is a bit more elaborate:
char *
flatpak_dir_get_name (FlatpakDir *self)
{
  const char *id = NULL;

  if (self->user)
    return g_strdup ("user");
  
  id = flatpak_dir_get_id (self);
  if (id != NULL && g_strcmp0 (id, "default") != 0)
    return g_strdup_printf ("system (%s)", id);
  
  return g_strdup ("system");
}

**Comment by matthiasclasen** [comment]
I think "user" and "system" are perfectly fine ids for the default locations.

**Comment by matthiasclasen** [comment]
of course, there are some interesting quesitons about what happens when I add a custom installation with a name like "user" or "system". We should probably prevent that
