### ISSUE TITLE
flatpak-builder: allow rename of archive or pass extract options

### ISSUE THREAD

**Issue by matze** [flatpak/flatpak#721]
I have a specific problem with my flatpak recipe for Inkscape. For whatever reason, I can only download archives with a [wrong file extension](https://github.com/matze/inkscape-flatpak/blob/a7287671e1b1f6d30dd180fd8150140698ca7ede/org.inkscape.Inkscape.json#L152), which `tar` is unable to extract. Besides asking the Inkscape devs to change their distribution methods, I think it would be easier for me to either be able to rename the file (e.g. in a `pre-build` step) or passing the `-j` flag to the `tar` process.

**Comment by alexlarsson** [comment]
You could specify it as a file instead of an archive, and then have a shell source with commands=[rename, untar]

**Comment by alexlarsson** [comment]
That said, this is similar to issue https://github.com/flatpak/flatpak/issues/687

**Comment by matze** [comment]
Well, I tried that as well. But `wget` is not available and `curl` complains about not being able to resolve inkscape.org.

**Comment by matze** [comment]
Alright, not so straightforward but it's working. Thanks for the pointer!
