### ISSUE TITLE
clarify extension terminology

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#727]
We are currently calling both [Extension org.freedesktop.Platform.GL] and org.freedesktop.Platform.GL.nvidia-381-99 an "extension".

It think it would be clearer if we used separate terms for the two things, e.g. "extension point" and "extension".

This mainly affects the documentation.

**Comment by alexlarsson** [comment]
I agree

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/flatpak/pull/769
