### ISSUE TITLE
[CLI] Show update-able apps/runtimes but dont download or install

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#729]
when we do `flatpak update` that will download and install all the updates
is it possible to list only all the runtimes and all apps that have available updates?

**Comment by matthiasclasen** [comment]
flatpak remote-ls --updates REMOTE does this, although only for a single remote.

**Comment by alexlarsson** [comment]
Yeah, supporting that with no specified rename would be nice. Anyone want to try for a first patch?

**Comment by handsome-feng** [comment]
Should the command be "flatpak update --list" , "flatpak remote-ls --updates" (without REMOTE), "flatpak list --updates" or anything else ?

**Comment by alexlarsson** [comment]
I think "flatpak remote-ls --updates" (without REMOTE) makes most sense. It would need to add a remote column though.
