### ISSUE TITLE
Packages in some distributions doesn't pull portals

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak#730]
This is a tracker bug for the major distributions (Fedora, OpenSUSE, Ubuntu, Debian, Arch) that are missing in the package to pull at least one of the portal implementations, rendering impossible for the apps to communicate to the external services.

Debian http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861068
OpenSUSE: contact Adrien Plazas, he is taking a look.
Arch: works
Ubuntu PPA: missing, but I guess @alexlarsson will take care of that 
Fedora: works

**Comment by csoriano89** [comment]
Update, Debian is fixed now.

**Comment by csoriano89** [comment]
OpenSUSE seems to be fixed now.

@alexlarsson is the Ubuntu PPA in your radar for this?

**Comment by matthiasclasen** [comment]
Is this all fixed now ?

**Comment by matthiasclasen** [comment]
lets assume it is all fixed
