### ISSUE TITLE
Using flatpak to run code coverage

### ISSUE THREAD

**Issue by albfan** [flatpak/flatpak#732]
If #699 is merged, compiling with `--enable-gcov` can collect code coverage data when running installed test. After that don't know how to report code coverage.

gcov generated info can be consumed from multiple third-parties but to see results offline an option can be add lcov to flatpak Sdk like this:

https://github.com/albfan/gnome-todo/commit/4d6f87c88c9bae1c5f0707d7b811f14203884642#diff-d4276d2c4955bea40b4ddb5a8c053ed1R125

The patch is to add buid-api required files and to install in /app

From that running lcov and genhtml can generate reports.

**Comment by albfan** [comment]
gcovr is another option http://gcovr.com/guide.html

**Comment by albfan** [comment]
I miss a lot of details, due to my lack of knowlegde but in my understanding, org.gnome.Sdk is based on org.freedesktop.Sdk which is based on https://github.com/flatpak/freedesktop-sdk-base which is based on yocto:

Seems yocto has gcov included since March 2017

http://git.yoctoproject.org/cgit/cgit.cgi/poky/log/?qt=grep&q=gcov

so the question is only: what prevents flatpak to use lastest version of yocto? or better: has sense to backport gcov inclusion into actual yocto version used on flatpak?

**Comment by albfan** [comment]
@ebassi found the problem:

https://github.com/flatpak/freedesktop-sdk-base/pull/4

**Comment by alexlarsson** [comment]
Better fix: https://github.com/flatpak/freedesktop-sdk-base/commit/473c40e5b6bba40b48a8b9dfe1b5bcc927a78131 https://github.com/flatpak/freedesktop-sdk-base/commit/c693f54e6b0e663475cb34f23ca8164e1aed7a0d

Building right now.
