### ISSUE TITLE
What is the package that adds gcc

### ISSUE THREAD

**Issue by albfan** [flatpak/flatpak#735]
I can't find gcov in a flatpak sandbox based on org.gnome.Sdk//master

but seems it is provided by gcc

https://github.com/gcc-mirror/gcc/blob/master/gcc/gcov.c

I want to tweak it to provide gcov and allow to run test suite with code coverage. (related with #699 and #732)

My idea is to build with `--keep-build-dirs` and `--disable-cache` but don't know if there is a better way to access gcda nad gcno files

**Comment by matthiasclasen** [comment]
gcc comes from the yocto base of the runtime

**Comment by albfan** [comment]
Thanks
