### ISSUE TITLE
Telegram won't run on Fedora Atomic

### ISSUE THREAD

**Issue by andreasn** [flatpak/flatpak#741]
This sounds super-specific, but after speaking to @alexlarsson about it a bit, it seems it's a more general issue.
The Telegram flatpak by @grulja needs to do some stuff with /tmp on the host. On Fedora Atomic, /tmp is a symlink (it links to sysroot/tmp). So when I try to run org.telegram.desktop, I get the error:
`Can't make symlink at /tmp: File exists`

**Comment by grulja** [comment]
It does, it creates a file in /tmp to check whether it is running to avoid
running multiple instances.

2017-04-27 10:36 GMT+02:00 andreasn <notifications@github.com>:

**Comment by matthiasclasen** [comment]
Can you make it take a bus name instead ?

**Comment by grulja** [comment]
I can try if I find some time, but given how that app is written it might not be easy.

**Comment by andreasn** [comment]
Alex said that flatpak probably needs support for following symlinks like that.

**Comment by matthiasclasen** [comment]
ok. But using a bus name for uniqueness would still be a good idea.

**Comment by grulja** [comment]
It is, but given telegram is available also on other platforms, including windows, then I don't blame the devs that they took universal approach.

**Comment by matthiasclasen** [comment]
sure, no blame. But giving the app filesystem access just for uniqueness is sad.

**Comment by grulja** [comment]
Lots of stuff about tdesktop is sad, from I can see it uses that file with QLocalSocket for IPC, I also see that it tries to write there some commands like SEND, OPEN so it's not just for uniqueness I guess, but I cannot really tell how it works. On the other hand I allow access only to "/tmp" which shouldn't be a problem from security point of view.

**Comment by matthiasclasen** [comment]
alright, then. lets make it work

**Comment by alexlarsson** [comment]
I believe f28d318cc9029f28901b47e03e9ef2e144660c74 should fix this
