### ISSUE TITLE
can't list apps in gnome

### ISSUE THREAD

**Issue by maniat1k** [flatpak/flatpak#746]
This is the error:

```
 ~  flatpak remote-add --if-not-exists gnome https://sdk.gnome.org/gnome.flatpakrepo
 ~  flatpak remote-add gnome-apps https://sdk.gnome.org/gnome-apps.flatpakrepo
 ~  flatpak remote-ls gnome-apps
error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
```
where do I need to add this "gpg-verify-summary=false"?

**Comment by maniat1k** [comment]
ok found where to put it but it does not work.
```

~  cat ~/.local/share/flatpak/repo/config
[core]
repo_version=1
mode=bare-user
gpg-verify-summary=false
 ~  

```

```
 ~  flatpak remote-ls gnome-apps          
error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
 ✘  ~  

```

**Comment by alexlarsson** [comment]
That is not right. You should not need to set that, and I don't. Do you still get that error? Maybe some temporary issue?

**Comment by maniat1k** [comment]
that's still happening...
¿What else can I check?

**Comment by alexlarsson** [comment]
So, you did a system wide install (not per user), so the config is in `/var/lib/flatpak/repo/config`.
Next to that file, do you have a gnome-apps.trustedkeys.gpg ?
Does it match:

```
$ gpg2 --show-keyring /var/lib/flatpak/repo/gnome-apps.trustedkeys.gpg 
pub   rsa2048 2015-03-26 [SC]
      C6B64651C1C06216A58207E50AE4CFA555D15281
uid           Gnome SDK 3.16 <gnome-os-list@gnome.org>
```

**Comment by maniat1k** [comment]
OK I did this, I coment all the `config` file and added the `gnome-apps.trustedkeys.gpg`. Still no luck so uncoment the config and set to false the verifications (apeared one new after I added the gnome-apps.truetedkeys.gpg)

```
✘  ~  cat  /var/lib/flatpak/repo/config
[core]
repo_version=1
mode=bare-user

[remote "gnome"]
gpg-verify=true
gpg-verify-summary=false
url=https://sdk.gnome.org/gnome.flatpakrepo


[remote "gnome-apps"]
gpg-verify=true
gpg-verify-summary=false
url=https://sdk.gnome.org/gnome-apps.flatpakrepo

```

Now got this error... 

```
 ~  flatpak remote-ls gnome-apps         
error: Remote listing not available; server has no summary file
Check the URL passed to remote-add was valid

```

and that another totally different thing.... thanks! 
Regards,
Marcelo.-

**Comment by elya5** [comment]
I don't know if it's the same issue but I already get that error when I add the remote

    > flatpak remote-add --user gnome-apps https://sdk.gnome.org/gnome-apps-nightly.flatpakrepo
    Fehler: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)

(flatpak version 0.9.4)

**Comment by matthiasclasen** [comment]
I'm seeing the same with git master

**Comment by mwleeds** [comment]
In https://github.com/flatpak/flatpak/issues/746#issuecomment-298658027 the issue is that the URL shouldn't end in `.flatpakrepo`. You have to pass the `.flatpakrepo` to `flatpak remote-add` and let it determine the correct URL.

Beyond that, since no one has reported this issue in a year I think it's safe to close.
