### ISSUE TITLE
Cant run command with two words

### ISSUE THREAD

**Issue by biji** [flatpak/flatpak#75]
For example, I am creating package for bzr explorer, the command is "bzr explorer"

But get this error when run:
```
execvp "bzr explorer": No such file or directory
```

**Comment by alexlarsson** [comment]
Yeah, its just the binary. You'll have to make a small wrapper script and run that instead.
I wonder if we should support default arguments, but it becomes complicated how those would mix with the arguments give on the command line. Maybe its best to have the app author combine them with a shell wrapper.

**Comment by matthiasclasen** [comment]
I've added some documentation and improved error messages around this now.

**Comment by darkoverlordofdata** [comment]
still get the same error message:
execvp autovala: No such file or directory

I'm working off the documentation at http://flatpak.org/developer.html. If this were in the documentation, I wouldn't be here looking for it.

**Comment by TingPing** [comment]
@darkoverlordofdata This issue was about the command used at runtime not building. It sounds like autovala is a build dependency that just isnt included in the Sdk in which case you need to build it.
