### ISSUE TITLE
Polkit integration doesn't work if no remote installed

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak#756]
I was trying to install Builder in a fresh install (simulated removing all config & data in var/lib/flatpak, /usr/local/flatpak and the home directory) with flatpak 0.9.3,  and couldn't install is. However using root worked, so I bet there is some polkit integration failing in here. The strace is:
https://gist.github.com/csoriano89/2a4abc5e74db595979056a029181a21e

**Comment by alexlarsson** [comment]
Known issue. Closing this as dup of: https://github.com/flatpak/flatpak/issues/113 which is somewhat the same.

Basically, ostree as user with system repo as parent repo fails if there is no repo at all, so you have to run *some* command as root first. The packages does thise in %post.

**Comment by csoriano89** [comment]
I'm seeing this also for adding remotes. Basically I have to use always sudo for installing/adding repos.

In the case of adding a repo, no error is reported:
[csoriano@localhost Downloads]$ flatpak remote-add --if-not-exists gnome-nightly https://sdk.gnome.org/gnome-nightly.flatpakrepo -v
XA: Calling system helper: ConfigureRemote
[csoriano@localhost Downloads]$ flatpak install gnome-nightly org.gnome.Platform
error: Remote "gnome-nightly" not found
[csoriano@localhost Downloads]$
