### ISSUE TITLE
Need portal for opening a (http) URI

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#76]
Many apps use this for showing help pages or just linking to the project website.

**Comment by matthiasclasen** [comment]
Initial api proposal is here: https://github.com/matthiasclasen/flatpak/tree/app-chooser

**Comment by matthiasclasen** [comment]
This is being done in xdg-desktop-portal now

**Comment by hbons** [comment]
@matthiasclasen where's that? I'd like to follow that work.

**Comment by aleb** [comment]
@hbons https://github.com/flatpak/xdg-desktop-portal

**Comment by aleb** [comment]
IIUC this is done in GTK 3.22 and the portal is accessible for example using http://lazka.github.io/pgi-docs/#Gio-2.0/interfaces/AppInfo.html#Gio.AppInfo.launch_default_for_uri
