### ISSUE TITLE
Move portals to xdg-desktop-portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#765]
It would make sense to have the document portal and the permission store colocated with the other portals, rather than with flatpak itself, in particular if we want to make the portals usable outside the flatpak context.

This will need some cleanups, since they currently both link against libflatpak-common.

**Comment by alexlarsson** [comment]
With the new AddFull document portal method this relies on even more flatpak code, so its a bit tricky to extract.

**Comment by matthiasclasen** [comment]
yeah, lets just forget about it now. I think it is fine to consider the document portal and permission store as 'portal plumbing', and thus a bit special
