### ISSUE TITLE
Add a AddMany method to the document portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#766]
The document portal should offer to rewrite an list of file paths or uris by exporting them for the given application, and returning document portal paths / uris in place of the original ones. Non-file uris and files which the application can see on the host filesystem should be left untouched.

If the call is coming out of a sandbox, only files that are accessible to the caller should be exported.

A call like this will be needed to implement file copy/paste and dnd into sandboxes and dbus activation of sandboxed apps with files.

**Comment by matthiasclasen** [comment]
Here is some initial work:

https://github.com/matthiasclasen/flatpak/tree/add-many

Still missing: check if the files are accessible to the application

**Comment by matthiasclasen** [comment]
A glib patch for using this can be found here: https://git.gnome.org/browse/glib/commit/?h=sandboxed-dbus-activation

**Comment by matthiasclasen** [comment]
Sadly, tools like glib's gapplication still call Open directly

**Comment by alexlarsson** [comment]
Hmm, figuring out what files are visible to the app is kinda tricky. I mean, it depends on which branch of the app you run, whether you run the system or per-user install, the per-user overrides and even the per-instance commandline arguments. I guess we can find the "default" setting for the current user though, but this is going to involve quite some flatpak specific code, which may be problematic if we want to move the document portal to xdg-desktop-portal.

**Comment by matthiasclasen** [comment]
Yeah, thats the reason I didn't touch this yet. It looked like it almost needs a running sandbox to say for sure, and not just an app id. I wouldn't worry too much about moving the document portal - if it needs to be tied closely to flatpak, so be it. An alternative would be to move common/ to a submodule and share it that way.

**Comment by matthiasclasen** [comment]
Further thoughts:

It would be good if we could add an easy key to the desktop file to see if it is a flatpak one. Then we can avoid the AddMany call for unsandboxed apps. Say,

X-RunsInFlatpakSandbox=true

Having to call GetMountPoint separately sucks, we should either return the mountpoint with the list, or just return full document paths instead of just doc ids.

Another direction for this would be an org.freedesktop.Flatpak.SessionHelper.Open(app-id, uris) that would first rewrite the uris by calling AddMany, and then call org.freedesktop.Application.Open to activate the app. The advantage of AddMany is that it can also be used for copy-paste, dnd, etc.

**Comment by alexlarsson** [comment]
Adding a "is-flatpak" boolean when we export seems like an easy win to me.

**Comment by matthiasclasen** [comment]
Pushed a new version of this:

https://github.com/matthiasclasen/flatpak/commits/add-many-2
https://git.gnome.org/browse/glib/commit/?h=sandboxed-dbus-activation

Changes:
- Rely on X-Flatpak in desktop files
- Avoid extra roundtrip by adding the mountpoint to the AddMany results
- Make the gio code async

**Comment by matthiasclasen** [comment]
Should we allow passing a pid instead of or in addition to the app-id ?

For some uses (copy-paste, dnd), that could be easier than obtaining the app-id client-side, and it would let us find our way back to the running sandbox for determining effective visibility.

**Comment by matthiasclasen** [comment]
One issue pointed out by alex: this gets used by the OpenURI portal where a sandboxed app can currently send e.g. file:///etc/passwd, and possible arrange for itself to be selected as the url handler and bypass the sandbox restrictions that way.

I tend to think that the source of this problem is the OpenURI portal accepting uris  instead of fds for local files. One solution could be to only accept document portal uris for local files. or to perform an access check for the calling app before accepting local file uris.

**Comment by alexlarsson** [comment]
@matthiasclasen I agree. I will look into a way to handle local files in the openuri portal.

**Comment by matthiasclasen** [comment]
Another alternative: remove support for file: uris entirely, and add a OpenFile call that takes an fd

**Comment by alexlarsson** [comment]
I looked into this a bit and had a nice idea of how to detect when a file is reachable by looking in `/proc/$pid/root`. However it turns out in the portal case that `$pid` is that of the dbus proxy, which doesn't have the same file access as the actual sandbox, so this didn't quite work...

I will think some more about this.

**Comment by alexlarsson** [comment]
So, i agree with you, we should make sure we don't handle file: uris (or invalid uris) and then add OpenFile.

**Comment by alexlarsson** [comment]
I landed AddFull, which is similar to AddMany. It has a flag that i want to add too for handing the rewrite-for-app case.

**Comment by matthiasclasen** [comment]
I've updated the sandboxed-dbus-activation branch of glib to work with AddFull

**Comment by alexlarsson** [comment]
I wonder if maybe we could put the entire app file permissions in the desktop file, then the document portal wouldn't need to know about apps.

Of course, then it would not respect per-user app overrides, so that might not be a great idea.

**Comment by alexlarsson** [comment]
The glib code needs to use g_filename_from_uri() for unscaping, etc.

**Comment by alexlarsson** [comment]
Also, i tried "gio open test.gnome-recipes-export", but the portal stuff in the open-uri codepath is async, and the tool does not spin the mainloop, so it dies before handling the rewrite_uris_done callback.

**Comment by alexlarsson** [comment]
Landed the as-needed flag: 
https://github.com/flatpak/flatpak/commit/dfaf925dd0db8336d037e58919c30af9eca6a337

**Comment by matthiasclasen** [comment]
I've pushed another iteration of sandboxed-dbus-activation to glib, entirely untested.
Changes:
- use g_filename_from_uri
- use the as-needed flag
- make the AddFull cal sync

**Comment by matthiasclasen** [comment]
this is done, as far as I'm concerned
