### ISSUE TITLE
hints when you are on flatpak shell

### ISSUE THREAD

**Issue by albfan** [flatpak/flatpak#771]
When enter on flatpak shell could be useful to add a hint on prompt. 

This is is a modified PS1 from default .bashrc

```bash
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ -d "/app" ]
then
    if [ "$color_prompt" = yes ]; then
        SUFFIX_PROMPT=" $red(flatpak)$color_off"
    else
        SUFFIX_PROMPT="${SUFFIX_PROMPT} (flatpak)"
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]${SUFFIX_PROMPT}\n\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w${SUFFIX_PROMPT}\n\$ '
fi

```

that shows:

```
alberto@laptop:~/ (flatpak)
$
```

inside flatpak sandbox

**Comment by mwleeds** [comment]
Flatbox does something similar: https://github.com/alexlarsson/flatbox/blob/41886441c63f0b63f377047de27618d6a12a2c87/flatbox#L59

**Comment by matthiasclasen** [comment]
One way to achieve this for --command=sh is to use ENV:

`flatpak run --command=sh --env=ENV=/etc/flatpak-profile org.gnome.Platform`

will make sh read /etc/flatpak-profile, which could do things like

`PS1="[📦$NAME \W] "`

**Comment by matthiasclasen** [comment]
Even simpler would be to just set PS1 in the environment, and possibly some useful flatpak information. That would let users override things globally with override --env:

`flatpak run --command=sh --env=FLATPAK_APP_ID=eu.scarpetta.PDFMixTool --env=PS1="[📦 \$FLATPAK_APP_ID \W]\$ " eu.scarpetta.PDFMixTool `
