### ISSUE TITLE
flatpak-builder doesn't seem to build from the requested commit

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#777]
The GNOME Games Flatpak from master [has this](https://git.gnome.org/browse/gnome-games/tree/flatpak/libretro-cores/libretro-pcsx_rearmed.json): (stripped to the relevant parts)

```json
        {
            "name": "libretro-pcsx_rearmed",
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/libretro/pcsx_rearmed",
                    "commit": "511848c9da1829102e9107ca06e2a06a2f7982eb"
                }
            ]
        }
```

Yet, [the build logs](http://sdkbuilder.gnome.org/logs/build-2017-05-09-082043/build-gnome-apps-nightly-master-org.gnome.Games-x86_64.txt) say:

```
Cloning into '/srv/sdkbuilder/work/build/x86_64/gnome-apps-nightly-master/.flatpak-builder/build/libretro-pcsx_rearmed-1'...
done.
Already on 'master'
```

And after installing the app, the manifest indicates it was built from the tip of the master branch of pcsx_rearmed: (stripped to the relevant parts)

```json
    {
      "name" : "libretro-pcsx_rearmed",
      "sources" : [
        {
          "url" : "https://github.com/libretro/pcsx_rearmed",
          "branch" : "358a8764ccdab8d5228c0c8c958fa7c0ff45f4a0",
          "type" : "git"
        }
      ]
    },
    {
      "name" : "gnome-games",
      "sources" : [
        {
          "url" : "https://git.gnome.org/browse/gnome-games",
          "branch" : "f694588cf63786674fba583c72913ade8cb5ed42",
          "type" : "git"
        }
      ]
    }
```

Why did flatpak-builder not build from the requested commit hash?

**Comment by bochecha** [comment]
Fun, I get this when locally building GNOME Games with flatpak 0.9.3:

```
...
Cloning into '/home/mathieu/Projects/gnome/gnome-games/.flatpak-builder/build/libretro-pcsx_rearmed-1'...
done.
Note: checking out '511848c9da1829102e9107ca06e2a06a2f7982eb'.
...
```

So what's different on the nightly build server? 😕

**Comment by alexlarsson** [comment]
"commit" support requires a newer flatpak-builder than what is installed on the gnome build machines atm. If you don't specify both a commit and a tag i recommend to just use "branch", because that works for both commit ids and branch names.
