### ISSUE TITLE
Need better solution for dconf/GSettings

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#78]
Currently we support the traditional dconf gsettings backend by openinng a lot of access to the host. There are plans for a new GSettings backend for use in a sandbox, we should look into supporting that.

**Comment by jangernert** [comment]
Would that also mean multiple versions of the same application all with their own sand-boxed gsettings?

**Comment by hadess** [comment]
I'm guessing not, unless your applications have separate .desktop files, and D-Bus names, à-la Epiphany's web apps.

**Comment by matthiasclasen** [comment]
work in progress here: https://git.gnome.org/browse/dconf/log/?h=wip/proxy

**Comment by alexlarsson** [comment]
Current work/discussion is in https://github.com/flatpak/flatpak/pull/1689

**Comment by alexlarsson** [comment]
With #1689 landed we have the base stuff landed to eventually have a real dconf story, but for now i'm removing this from the 1.0 blocker list as it depends on further dbus-daemon and dconf upstream work.

**Comment by sonnyp** [comment]
https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

**Comment by sonnyp** [comment]
I removed dconf hole and I get the following in a gjs app:

```
GLib.getenv("GSETTINGS_BACKEND")) == null
Gio.SettingsBackend.get_default()) == DConfSettingsBackend
```

* Flatpak 1.4.2
* flatpak-builder 1.0.8
* org.gnome.Platform//3.32

Am I missing something?

**Comment by TingPing** [comment]
@sonnyp 	The GLib changes are not in org.gnome.Platform//3.32. They will likely not happen until 3.34.

**Comment by sonnyp** [comment]
Okay nevermind, I'm getting `GKeyfileSettingsBackend` now. Some cache must have gotten in the way.
