### ISSUE TITLE
Flatpak-builder doesn't play well when a git clone was stopped

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak#786]
Basically, for some people with whaky internet, sometimes the clone phase is cut. Then flatpak-builder is unable to retry the build/clone.

Here's an example output:
Creating directory “/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master”
Emptying app dir '/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master'
fatal: destination path 'git_git.gnome.org_babl.clone_tmp' already exists and is not an empty directory.
Downloading sources
Failed to download sources: module babl: Child process exited with code 128
Cloning git repo git://git.gnome.org/babl
fatal: destination path 'git_git.gnome.org_babl.clone_tmp' already exists and is not an empty directory.
Emptying app dir '/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master'
Failed to download sources: module babl: Child process exited with code 128
Downloading sources
Cloning git repo git://git.gnome.org/babl
Creating directory “/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master”
Emptying app dir '/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master'
Creating directory “/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master”
fatal: destination path 'git_git.gnome.org_babl.clone_tmp' already exists and is not an empty directory.
Downloading sources
Failed to download sources: module babl: Child process exited with code 128
Cloning git repo git://git.gnome.org/babl
Creating directory “/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master”
Emptying app dir '/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master'
Downloading sources
Cloning git repo git://git.gnome.org/babl
fatal: destination path 'git_git.gnome.org_babl.clone_tmp' already exists and is not an empty directory.
Failed to download sources: module babl: Child process exited with code 128
Creating directory “/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master”
Emptying app dir '/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master'
Downloading sources
Cloning git repo git://git.gnome.org/babl
fatal: destination path 'git_git.gnome.org_babl.clone_tmp' already exists and is not an empty directory.
Failed to download sources: module babl: Child process exited with code 128
Creating directory “/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master”
Emptying app dir '/home/ankritisachan/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/Photos/flatpak:org.gnome.Platform-x86_64-master'
Downloading sources
Cloning git repo git://git.gnome.org/babl
fatal: destination path 'git_git.gnome.org_babl.clone_tmp' already exists and is not an empty directory.
Failed to download sources: module babl: Child process exited with code 128

**Comment by alexlarsson** [comment]
I guess we should do the initial clone in a tmp directory with a "random" name instead of just '_tmp'.

**Comment by csoriano89** [comment]
Thanks Alex! Another newcomer without problems :)
