### ISSUE TITLE
Inkscape not listed

### ISSUE THREAD

**Issue by Svetomech** [flatpak/flatpak#788]
Why is [official](https://inkscape.org/download/linux/) [Flatpak version](https://github.com/matze/inkscape-flatpak) of Inkscape not listed on the site? [It was](https://www.maketecheasier.com/assets/uploads/2016/07/unversal-packages-flatpak-repo-page.jpg), though.

**Comment by andreasn** [comment]
This issue tracker for the website is on the web repo.
https://github.com/flatpak/flatpak.github.io/issues

Can you file this there instead?
Thanks!

**Comment by Svetomech** [comment]
Sure. Sorry for any inconvenience.
