### ISSUE TITLE
Spotify file picker (zenity) shows flatpak file tree instead of system file tree

### ISSUE THREAD

**Issue by LinAGKar** [flatpak/flatpak#798]
When trying to add local files in Spotify, the file picker shows the flatpak file tree instead of system file tree.

**Comment by matthiasclasen** [comment]
That is to be expected when you run an application in a sandbox without making changes to the code. In some cases, we can hide this inside the toolkit and transparently use a portal, but it evidently does not work here.

**Comment by LinAGKar** [comment]
It apparently uses the zenity file picker, from the GNOME runtime. I also get the same result when running zenity from the command line inside flatpak.

**Comment by TingPing** [comment]
Looks like Zenity exposes the ability to add extra widgets to the filechooser dialog so it can't fully be ported to GtkFileChooserNative though for the needs of Spotify alone it could be done.

**Comment by LinAGKar** [comment]
Specifically, it lets you pick directories, so I guess it uses something like `zenity --file-selection --directory`.

**Comment by TingPing** [comment]
Here is a Zenity patch if somebody wants to try it out:

```diff
From eba25dffebb264a82cdcaabc03ffff82a1c7e418 Mon Sep 17 00:00:00 2001
From: Patrick Griffis <tingping@tingping.se>
Date: Mon, 22 May 2017 09:30:49 -0400
Subject: [PATCH] Use GtkFileChooserNative

---
 src/fileselection.c | 55 +++++++++++++++++++++++++++++++++++++----------------
 1 file changed, 39 insertions(+), 16 deletions(-)

diff --git a/src/fileselection.c b/src/fileselection.c
index 521464b..b320270 100644
--- a/src/fileselection.c
+++ b/src/fileselection.c
@@ -34,10 +34,14 @@ static void zenity_fileselection_dialog_response (
 
 void
 zenity_fileselection (ZenityData *data, ZenityFileData *file_data) {
-	GtkWidget *dialog;
 	gchar *dir;
 	gchar *basename;
 	GtkFileChooserAction action = GTK_FILE_CHOOSER_ACTION_OPEN;
+#if GTK_CHECK_VERSION(3, 20, 0)
+	GtkFileChooserNative *dialog;
+#else
+	GtkWidget *dialog;
+#endif
 
 	zen_data = data;
 
@@ -51,22 +55,37 @@ zenity_fileselection (ZenityData *data, ZenityFileData *file_data) {
 			action = GTK_FILE_CHOOSER_ACTION_SAVE;
 	}
 
+#if GTK_CHECK_VERSION(3, 20, 0)
+	dialog = gtk_file_chooser_native_new (data->dialog_title,
+		NULL, /* TODO: Get parent from xid */
+		action,
+		_ ("_OK"),
+		_ ("_Cancel")
+	);
+
+	if (data->modal)
+		gtk_native_dialog_set_modal (GTK_NATIVE_DIALOG(dialog), TRUE);
+
+	if (data->extra_label)
+		g_warning ("Cannot add extra labels to GtkFileChooserNative");
+#else
 	dialog = gtk_file_chooser_dialog_new (NULL,
 		NULL,
 		action,
 		_ ("_Cancel"),
 		GTK_RESPONSE_CANCEL,
 		_ ("_OK"),
-		GTK_RESPONSE_OK,
+		GTK_RESPONSE_ACCEPT,
 		NULL);
 
-	gtk_file_chooser_set_do_overwrite_confirmation (
-		GTK_FILE_CHOOSER (dialog), file_data->confirm_overwrite);
+	if (data->dialog_title)
+		gtk_window_set_title (GTK_WINDOW (dialog), data->dialog_title);
 
-	g_signal_connect (G_OBJECT (dialog),
-		"response",
-		G_CALLBACK (zenity_fileselection_dialog_response),
-		file_data);
+	if (data->modal)
+		gtk_window_set_modal (GTK_WINDOW (dialog), TRUE);
+
+	zenity_util_set_window_icon (
+		dialog, data->window_icon, ZENITY_IMAGE_FULLPATH ("zenity-file.png"));
 
 	if (data->extra_label) {
 		gint i = 0;
@@ -76,15 +95,15 @@ zenity_fileselection (ZenityData *data, ZenityFileData *file_data) {
 			i++;
 		}
 	}
+#endif
 
-	if (data->dialog_title)
-		gtk_window_set_title (GTK_WINDOW (dialog), data->dialog_title);
-
-	zenity_util_set_window_icon (
-		dialog, data->window_icon, ZENITY_IMAGE_FULLPATH ("zenity-file.png"));
+	gtk_file_chooser_set_do_overwrite_confirmation (
+		GTK_FILE_CHOOSER (dialog), file_data->confirm_overwrite);
 
-	if (data->modal)
-		gtk_window_set_modal (GTK_WINDOW (dialog), TRUE);
+	g_signal_connect (G_OBJECT (dialog),
+		"response",
+		G_CALLBACK (zenity_fileselection_dialog_response),
+		file_data);
 
 	if (file_data->uri) {
 		dir = g_path_get_dirname (file_data->uri);
@@ -156,7 +175,11 @@ zenity_fileselection (ZenityData *data, ZenityFileData *file_data) {
 		}
 	}
 
+#if GTK_CHECK_VERSION(3, 20, 0)
+  gtk_native_dialog_show (GTK_NATIVE_DIALOG(dialog));
+#else
 	zenity_util_show_dialog (dialog, data->attach);
+#endif
 
 	if (data->timeout_delay > 0) {
 		g_timeout_add_seconds (data->timeout_delay,
@@ -189,7 +212,7 @@ zenity_fileselection_dialog_response (
 	ZenityFileData *file_data = data;
 
 	switch (response) {
-		case GTK_RESPONSE_OK:
+		case GTK_RESPONSE_ACCEPT:
 			zenity_fileselection_dialog_output (widget, file_data);
 			zenity_util_exit_code_with_data (ZENITY_OK, zen_data);
 			break;
-- 
2.13.0
```

**Comment by LinAGKar** [comment]
I just get `(zenity:43): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed` when running with `zenity --file-selection`, and `zenity --file-selection --directory` remains unchanged.

**Comment by phw** [comment]
> Looks like Zenity exposes the ability to add extra widgets to the filechooser dialog so it can't fully be ported to GtkFileChooserNative 

GtkFileChooserNative also supports calling gtk_file_chooser_set_extra_widget(), but ignores it silently in case the portal is used.

**Comment by TingPing** [comment]
> GtkFileChooserNative also supports calling gtk_file_chooser_set_extra_widget(), but ignores it silently in case the portal is used.

That behaves differently than `gtk_dialog_add_button()` so isn't what we want.

> I just get (zenity:43): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed when running with zenity --file-selection, and zenity --file-selection --directory remains unchanged.

I'm only running it outside of Flatpak but that command works fine here.

This patch was submitted upstream: https://bugzilla.gnome.org/show_bug.cgi?id=782993

**Comment by LinAGKar** [comment]
>I'm only running it outside of Flatpak but that command works fine here.

It works for me too when running it outside of Flatpak with the above patch (on openSUSE Tumbleweed), but when compiling and running it with the patch inside Flatpak I get the aforementioned error.

**Comment by TingPing** [comment]
> It works for me too when running it outside of Flatpak with the above patch (on openSUSE Tumbleweed), but when compiling and running it with the patch inside Flatpak I get the aforementioned error.

Alright, glancing at the `OpenFile()` interface it could be that we don't set one of `app_id`, `parent_window`, or `title`.

**Comment by matthiasclasen** [comment]
If zenity is running i side a flatpak sandbox, it can in principle find out the app id

**Comment by TingPing** [comment]
> If zenity is running i side a flatpak sandbox, it can in principle find out the app id

Perhaps the Gtk side could handle that? If app-id is NULL figure it out for you?

**Comment by matthiasclasen** [comment]
It was the title that is NULL here, not the app-id. I've pushed fixes to gtk to avoid that.

**Comment by LinAGKar** [comment]
This is still not working.

Currently `zenity --file-selection` gives:
```(zenity:51): Gtk-WARNING **: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files```
and `zenity --file-selection --directory` remains unchanged.

Is it possible to pick a directory from the command line some other way as a workaround?

**Comment by matthiasclasen** [comment]
you need to install xdg-desktop-portal and xdg-desktop-portal-gtk

**Comment by LinAGKar** [comment]
Now nothing happens when I run it, and after a while I get:

```(zenity:3): Gtk-WARNING **: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.portal.Desktop': timed out```

**Comment by LinAGKar** [comment]
Now the file selection is finally working correctly. However, when it is used with `--directory` it still uses the local file picker instead of the portal, and that seems to be what Spotify uses, so the behavior in Spotify remains unchanged.

**Comment by TingPing** [comment]
The portal itself isn't usable with Spotify anyway because it expects persistant access between runs so you have to do `flatpak override com.spotify.Client --filesystem=/foo/bar` anyway.
