### ISSUE TITLE
Doesn't download file types

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#8]
_From @hadess on April 27, 2016 9:50_

For example, the stand-alone waf file here I would expect to be downloaded as the filename mentioned for building.

```
                {   
                    "type": "file",
                    "url": "https://waf.io/waf-1.8.12",
                    "sha256": "01bf2beab2106d1558800c8709bc2c8e496d3da4a2ca343fe091f22fca60c98b",
                    "dest-filename": "waf"
                },  
```

_Copied from original issue: alexlarsson/xdg-app#146_

**Comment by alexlarsson** [comment]
_From @hadess on April 27, 2016 9:51_

Note that I just realised that we'd be missing a way to set the executable bit on the downloaded file.

**Comment by hadess** [comment]
Bizarrely, the above worked and I've used the "script" source to chmod the file before launching it.
