### ISSUE TITLE
support 'dir' for module source in flatpak-builder

### ISSUE THREAD

**Issue by tygerlord** [flatpak/flatpak#800]
Don't know if I correctly use flatpak but for developping but for now to build my package requiring a lot of dependancies I do like this:

1) I use flapack-builder with json contents dependancies list and --build-only
2) I do flatpak build ./configure etc etc
3) flapak-builder --finish-only
4) flatpak build-export
5) flatpak run

This will be more simple if I can use directly flatpak-builder for sources that I'm currently developping,
for that a 	"type": "dir", or something like this can help. What do you think about?

**Comment by alexlarsson** [comment]
flatpak-builder is primarily designed for building releases from scratch, in a stable reproducible way. It is not designed to work with unclean build directories. 

If you want to build your day-to-day builds in flatpak, then @csoriano89 is working on script for this.

**Comment by csoriano89** [comment]
Hey,

Still in its infancy, and I hope some time in the future can be upstreamed, but here it is: https://gitlab.com/csoriano/flatpak-dev-cli

**Comment by tygerlord** [comment]
Yes Iv'e seen this, but if I correctly understand how it's working this try first to build like flatpack-builder will do and enter in the sandbox to let you play with it, but what about if building fail because missing dependancies not installed? Moreover you need to tar application before to let the cli untar it ...
This tool is convenient for debugging I think, not for developping or perhaps I dont understand correctly?

**Comment by csoriano89** [comment]
@tygerlord What dependencies? The ones you set up in the manifest?

**Comment by tygerlord** [comment]
@csoriano89 yes

**Comment by csoriano89** [comment]
@tygerlord it runs flatpak-builder, so they will get build.
Dependencies on the system has nothing to do here, because flatpak cannot access those.

**Comment by tygerlord** [comment]
@csoriano89 yes i'm ok, it's the goal but I use externals applications like gnuplot, sqlite3 I don't use libs, directly, I call subprocess. Until you run your application you don't have problems. 
I see two problems for developping, if a tool is missing you need to update you're json restart the process. If you discover a bug you need to correct it in your sources under flatpak sandbox, verify if it's ok and report correction in your source, remake a tar file and restart the process. It's not very easy. You can avoid this if you get exactly same environment that the one in your sdk, but the goal is just to be independant from the os environment....

**Comment by csoriano89** [comment]
@tygerlord I think there is some missunderstandings in your comment. Let me try to clarify if I understood correctly:

"use externals applications like gnuplot, sqlite3 I don't use libs, directly, I call subprocess" if something isnot in the SDK and you don't build it in your manifest, you are out of luck. This is the pourpose of flatpak, to not require anything from the host system. You can handle this smoothly by not providing the duncionality attached to those tools if they are not available, or just build them in your manifest.

"if a tool is missing you need to update you're json restart the process"
I'm not sure what you mean by this. You mean if your manifest has some error, you have to fix it and run it again? Well, yes of course.

"If you discover a bug you need to correct it in your sources under flatpak sandbox"
Aha! Not really :) The sources are in your host system, and then you can enter the flatpak environment, with your sources in there too. I know it's a little confusing to understand, but inside this environment you have the permission to see the folder where the sources are.

"remake a tar file and restart the process"
No no. This tool I present to you, you build your application as you use to, with make or meson whatever, but inside the Flatpak environment. The dependencies are handled by flatpak-builder, incorporated in this tool too.

"You can avoid this if you get exactly same environment that the one in your sdk"
Exactly, this is what the tool does.

"but the goal is just to be independant from the os environment"
Yes, that's what the flatpak environment is, and independent environment.

**Comment by tygerlord** [comment]
@csoriano89 
Ok, so It seems that i don't understand correctly , I will test it, sorry to have wasted your time.

**Comment by csoriano89** [comment]
@tygerlord no problem at all! I think it's a little confusing to understand the first time. But you will get use to these concepts. These concepts are kinda similar to Android sdk's, if you know them already.

**Comment by tygerlord** [comment]
@csoriano89,
OK thank you. I will close the issue so.

**Comment by csoriano89** [comment]
@tygerlord sure. Feel free to approach me on IRC at irc.freenode.org on #flatpak as csoriano if you have any problem with that tool.
