### ISSUE TITLE
flatpak-builder does not recover from failed/cancelled clone

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#808]
If flatpak-builder is stopped while performing a clone, it can fail to recover when run a second time. This causes problems for us in Builder when a user cancels the build during the "download dependencies" phase.

```
fatal: destination path 'https_github.com_mendsley_bsdiff.clone_tmp' already exists and is not an empty directory.
```

See https://bugzilla.gnome.org/show_bug.cgi?id=782995 for more information.

**Comment by alexlarsson** [comment]
This is fixed in 0.9.4
