### ISSUE TITLE
flatpak-builder: allow miscellaneous data in .json file

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#809]
It would be convenient for us in Builder if we could add some extra application-specific information to the JSON manifest. Otherwise, we have to drop yet another file in the project repository (which we prefer to avoid doing).

In particular, it would be great if the .json manifest could ignore any field starting with `x-`.

That would allow us to do something like this in Builder.

```json
{
  "x-gnome-builder-run-command": "run-development-script.sh"
}
```

**Comment by alexlarsson** [comment]
We generally *do* allow this, although we recently added a warning about it.
