### ISSUE TITLE
Need notification portal

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#81]
We want apps to (optionally) be allowed to send desktop-global notifications. Need a portal for this.

**Comment by matthiasclasen** [comment]
Isn't this just org.gtk.Notifications=talk ?

**Comment by alexlarsson** [comment]
No, that would be a way to give an app broad access to notifications in a static fashion. What we would like is a more dynamic portal that lets you give/take access to notification at runtime in a similar fashion to how it looks on e.g. iOS or android, or in fact how the GPS access stuff looks in gnome today (i.e. you'll see a list of apps in the control center and you can give individual apps access to it or not. Maybe we can even give multiple levels of access.).

**Comment by matthiasclasen** [comment]
How it works currently, is that everybody who is on the session bus can talk to org.gtk.Notifications, and the shell decides (based on those control center settings) which ones to toss and which ones to show.

**Comment by alexlarsson** [comment]
How does it know what app is doing the request?

**Comment by matthiasclasen** [comment]
By guessing, as always. A portal could do this without guessing, of course

**Comment by matthiasclasen** [comment]
this is being done in the xdg-desktop-portal module now.
