### ISSUE TITLE
Need sharing portal

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#82]
An app should be able to share some selected content (text, images, etc) with one of several registred sharing targets (facebook, twitter, email, etc)

**Comment by fabianthoma** [comment]
Might I suggest you'll look at elementary's contractor before starting work on this? It does a big part of this over dbus and might be a starting point. 
https://elementary.io/docs/human-interface-guidelines#contractor
http://www.valadate.org:8000/#!api=granite/Granite.Services.Contractor

**Comment by matthiasclasen** [comment]
This will be done in the xdg-desktop-portal module
