### ISSUE TITLE
debug and locale extensions are not extracted as separate packages

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#824]
I noticed that my GIMP package is huge:

> $ flatpak install --user gimp org.gimp.GIMP
> Installing: org.gimp.GIMP/x86_64/master from gimp
>
> 812 metadata, 10933 content objects fetched; 157363 KiB transferred in 35 seconds

After investigating on #flatpak, we realized that is because the debug info are extracted correctly but they are not extracted into a separate package.

> $ flatpak remote-ls --user --show-details gimp
> app/org.gimp.GIMP/x86_64/master 82e189bc52b8

gimp-flatpak-build-x86-64/ being where flatpak built GIMP and its dependencies:
> $ du -sh gimp-flatpak-build-x86-64/
> 578M    gimp-flatpak-build-x86-64/
> $ du -sh gimp-flatpak-build-x86-64/files/lib/debug
> 383M    gimp-flatpak-build-x86-64/files/lib/debug

Obviously it makes sense that the download size ends up so big.
This is my manifest: https://git.gnome.org/browse/gimp/tree/build/flatpak/org.gimp.GIMP.json
And this is my process: https://git.gnome.org/browse/gimp/tree/build/flatpak/flatpak-howto.txt

On the build server:
> $ flatpak --version
> Flatpak 0.9.4
(from the PPA on an Ubuntu 16.04.2 LTS up-to-date)

As far as people said on IRC, nothing seems wrong with the process or the manifest. I was asked if eu-strip was installed on this build server. It is.
What else could be the problem?

**Comment by Jehan** [comment]
Additional note, I built with:

> flatpak-builder --arch=x86_64 gimp-flatpak-build-x86-64 org.gimp.GIMP.json > gimp-flatpak-build-x86-64.log 2>&1

The result:
[gimp-flatpak-build-x86-64.log.txt](https://github.com/flatpak/flatpak/files/1040010/gimp-flatpak-build-x86-64.log.txt)

Then exported with:

> flatpak build-export --gpg-sign=MYKEY /some/path/gimp-dev-repo/ gimp-flatpak-build-x86-64

**Comment by alexlarsson** [comment]
Ah, I see the problem.
flatpak-builder builds all the results into a single directory, and then exports from it multiple times, specifying some subset each time.

You just have to pass --repo=/path/to/repo to flatpak-builder to make it do the exports, which will properly split it up.

**Comment by alexlarsson** [comment]
Also, I would recommend bumping the runtime requirement to 3.24, as its based on the new freedesktop 1.6 base which has some newer stuff, and a longer support cycle.

**Comment by alexlarsson** [comment]
And for your docs: You can test the build without installing by doing:
`flatpak-builder --run gimp-flatpak-build-x86-64 org.gimp.GIMP.json gimp`


>   Note: if you ever want to check the `config.log` of any of the module,
  this is available in a hidden directory of your working path.
  For instance GIMP build dir will be `.flatpak-builder/build/gimp-1/`.
  The number will be incrementing at each build (`flatpak-builder`
  apparently caches every build).

This is weird. Unless you specify --keep-build-dirs it should only keep failed builds.

**Comment by alexlarsson** [comment]
You can also refer to this for some tips:
https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks

**Comment by Jehan** [comment]
> You just have to pass --repo=/path/to/repo to flatpak-builder to make it do the exports, which will properly split it up.

I see. So there is a bug in `flatpak build-export`?
The reason why I was doing in 2 steps (I used to export from the build) is that flatpak-builder will fail anyway at export time if I do it in 1 step because of issue #573. I discovered that if I detach the screen, the signing will always fail. But that's the whole point of running it through a ssh+screen since it takes hours. So I can't really do a `flatpak-builder --repo`.
Will the `flatpak build-export` be fixed?

> Also, I would recommend bumping the runtime requirement to 3.24, as its based on the new freedesktop 1.6 base which has some newer stuff, and a longer support cycle.

Ok.

> This is weird. Unless you specify --keep-build-dirs it should only keep failed builds.

I have not checked the build contents for some time, and when I added this tip, it was when I was creating the manifest. Hence builds were often failing. This may just be an error on my side. Probably new builds are not kept, I don't know. I'll open a bug report if they are.

**Comment by alexlarsson** [comment]
Its not really a bug per-se. `flatpak build-export` is a low-level tool, and flatpak-builder is a higher level tool that uses the lower level tool. You can manually do the same commands that flatpak builder does, which is something like (untested):
```
flatpak build-export --exclude="/lib/debug/*" --include=/lib/debug/app --exclude="/share/runtime/locale/*/*" repo appdir
flatpak build-export --runtime --metadata=metadata.locale  --files=files/share/runtime/locale/ 
flatpak build-export --runtime --metadata=metadata.debuginfo  --files=files/lib/debug/ 
```

**Comment by alexlarsson** [comment]
It might be interesting to have a flatpak-builder --export feature that did this though.

**Comment by alexlarsson** [comment]
I added support for flatpak-builder --export-only

**Comment by alexlarsson** [comment]
If you're using the old flatpak without this feature I recommend running flatpak-builder -v once with --repo. That will print out what exact commands are used during the export. Then you can re-use them. (In case the example i typed above was not quite right).

**Comment by Jehan** [comment]
P.S.: the output from:

> flatpak-builder -v --arch=x86_64 --repo=gimp-repo gimp-flatpak-build-x86-64_3.24 org.gimp.GIMP.json > gimp-flatpak-build-x86-64-verbose.log 2>&1
[gimp-flatpak-build-x86-64-verbose.log.txt](https://github.com/flatpak/flatpak/files/1045919/gimp-flatpak-build-x86-64-verbose.log.txt)
