### ISSUE TITLE
a way to warn packagers of missing libaries

### ISSUE THREAD

**Issue by muayyad-alsadi** [flatpak/flatpak#827]
Check this out

https://github.com/lirios/files/issues/6

**Comment by alexlarsson** [comment]
This is not really possible in a generic way. But any such issues should be found in testing anyway, as the users will be running the same bits as the testers.

**Comment by muayyad-alsadi** [comment]
Won't just `find /bin/ -type f -executable | while read a; do ldd "$a" | grep not found; done`

Just report that
