### ISSUE TITLE
flatpak 0.8.6 release tracker

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#829]
@alexlarsson asked me to review the contents of the flatpak-0.8.x branch for a 0.8.6 release. I'm opening a bug to have somewhere to discuss the contents of that release.

**Comment by smcv** [comment]
The current 0.8.x branch up to 0.8.5-12-gbeaa1fc3 (commit beaa1fc3) looks good to me, other than needing #828 fixed.

I've asked the Debian release team for feedback on a 0.8.5-3 Debian revision that applies `0.8.5..flatpak-0.8.x` as patches, plus #828. I'll see what they say. Debian 9 is in hard freeze at the moment (the release is planned for 2 weeks' time) so it's possible that this update will miss the deadline for Debian 9.0; if it does, I'm hoping to be able to get it into the Debian 9.1 point release.

If there are any changes on flatpak-0.8.x that you consider to be critical, please let me know and I can try to expedite them.

**Comment by alexlarsson** [comment]
0.8.6 is out now
