### ISSUE TITLE
flatpak-builder outputs invalid utf-8

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#830]
I'm seeing some tofu blocks in Builder when running flatpak-builder on our nightly branch.

```
|Cloning git repo https://git.gnome.org/browse/libgsystem.git
```

http://www.fileformat.info/info/unicode/char/fffd/index.htm

I don't see this anywhere else in our subprocess logging in Builder, so I'm pretty sure it's something in the subprocess encoding negotiation with flatpak-builder (maybe improper environment variables on our part) or something expecting a PTY that isn't.

I'm using flatpak-builder 0.9.4 on rawhide.

**Comment by alexlarsson** [comment]
Whats the line before that in the log?

**Comment by chergert** [comment]
It appears to be more git cloning operations

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#4
