### ISSUE TITLE
does flatpak for centos 7/rhel 7 require a newer kernel?

### ISSUE THREAD

**Issue by dragonballz2k** [flatpak/flatpak#846]
would I need to use elrepo kernel for flatpak to work or will the stock kernel work? I am using this repo https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/

**Comment by alexlarsson** [comment]
It should work with the regular kernel, does it not?

**Comment by scx** [comment]
See also:
https://github.com/flatpak/flatpak/issues/2551
https://github.com/flathub/flathub/issues/805
