### ISSUE TITLE
Flatpak lacks virtual keyboard support

### ISSUE THREAD

**Issue by M4gma** [flatpak/flatpak#851]
Just tried Gedit with virtual keyboard enabled on Gnome. As gtk3 automatically calls for the virtual keyboard popup it's very unlikely a problem with flatpaked Gedit itself

**Comment by alexlarsson** [comment]
I don't really know how this works. Maybe its somehow being sandboxed.

**Comment by matthiasclasen** [comment]
works here in my testing with wayland. We use the text protocol now, so all the interaction is over the wayland protocol
