### ISSUE TITLE
Install dependencies automatically

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak#853]
After installing the `com.valvesoftware.Steam` flatpak, one needs to manually install `org.freedesktop.Platform.Compat32` by running `flatpak update`, otherwise Steam complains about missing libraries. If possible, this should be done automatically.

**Comment by alexlarsson** [comment]
It installs automatically if org.freedesktop.Platform.Compat32 is in the same remote, which is the case for flathub. Did this not work for you?

**Comment by Alexander-Wilms** [comment]
No, it didn't. It didn't either for this user: https://github.com/flathub/com.valvesoftware.Steam/issues/1

**Comment by alexlarsson** [comment]
Ah, i see, you installed via gnome-software too?

**Comment by Alexander-Wilms** [comment]
Yes

**Comment by matthiasclasen** [comment]
This was fixed in gnome-software
