### ISSUE TITLE
flatpak enter cannot chroot or enter namespace

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#855]
I've tried `flatpak enter PID /bin/sh` for all of the PIDs associated with my application process and cannot get any of them to drop me inside the app mount namespace.

```
[christian@starthink ~]$ flatpak enter 15607 /bin/sh 
error: Can't chroot
[christian@starthink ~]$ flatpak enter 15608 /bin/sh 
error: Can't enter mnt namespace: Operation not permitted
[christian@starthink ~]$ flatpak enter 15611 /bin/sh 
error: Can't chroot
[christian@starthink ~]$ flatpak enter 15612 /bin/sh 
error: Can't enter mnt namespace: Operation not permitted
```

**Comment by alexlarsson** [comment]
Yeah, for stupid reasons you need to sudo flatpak enter

**Comment by chergert** [comment]
Rather than try to catch all the failures and plumb a nice error message, how about just a simple warning when the command starts if the effective user id is not 0?

**Comment by matthiasclasen** [comment]
have a patch ?

**Comment by intagger** [comment]
hm, for me it does not work with sudo and without sudo.

```
$ flatpak ps                 
Instance   PID   Application                     Runtime
3502034575 30011 com.jetbrains.PyCharm-Community org.freedesktop.Sdk
```
```
$ flatpak enter 30011 sh
Not running as root, may be unable to enter namespace
error: No such pid 30011
```

```
$ sudo flatpak enter 30011 sh
[sudo] password for lessneek: 
error: 30011 is neither a pid nor an application or instance ID
```

**Comment by matthiasclasen** [comment]
Grr. This is rather stupid. Try with sudo -E. It turns out we rely on XDG_RUNTIME_DIR to find the list of instances we iterate over

**Comment by BrainBlasted** [comment]
sudo -E doesn't seem to help either:

```
sudo -E flatpak enter $(pidof gnome-builder) bash

[sudo] password for chris: 
error: 22140 is neither a pid nor an application or instance ID
```

**Comment by rugk** [comment]
It still does not work in my case… strangely…

Note that `flatpak ps`works with sudo, so it does not seem to be the problem of sudo…

(Fedora 29)

```sh
$ sudo -E flatpak ps                   
Instance   PID   Application  Runtime
2725877937 31125 io.atom.Atom org.freedesktop.Sdk
$ sudo -E flatpak enter 31125 /bin/bash
error: No such pid 31125
```

**Comment by rugk** [comment]
Okay created a new issue for that: https://github.com/flatpak/flatpak/issues/2767
