### ISSUE TITLE
Cannot do make due to compile errors

### ISSUE THREAD

**Issue by AETolouee** [flatpak/flatpak#862]
First time trying to compile something, I've installed all dependencies, cloned `bubblewrap` and `libglnx` into the project root directory, and executed these commands.
```
./autogen.sh
./configure --with-priv-mode=setuid --enable-sudo
```
Though when I run `make` I get these errors:
https://pastebin.com/8Zxkgst3

what am I doing wrong?

OS: ubuntu 17.04

**Comment by alexlarsson** [comment]
It looks like the version of libglnx does not match what its supposed to be? Are you building from tarballs, then the libglnx should be included and with the right version. If you're building from git its included via git submodules, and a git submodule update should fix it. (Same with bubblewrap, you never need to manually add it to the tree)

**Comment by matthiasclasen** [comment]
Lets assume that was the reason.
