### ISSUE TITLE
GPG verification enabled, but no summary signatures found

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#866]
I can't install anymore as the system (i.e. without --user). I tested with a third-party flatpakref in case the error may have been from my GIMP flatpakref:

> $ flatpak install http://flatpak.pitivi.org/pitivi.flatpakref
> Installing: org.pitivi.Pitivi/x86_64/stable
> Required runtime for org.pitivi.Pitivi/x86_64/stable (org.gnome.Platform/x86_64/3.22) is not installed, searching...
> Found in remote gnome, do you want to install it? [y/n]: y
> Installing: org.gnome.Platform/x86_64/3.22 from gnome
> [####################] 9 delta parts, 73 loose fetched; 178829 KiB transferred in 70 seconds
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: GPG verification enabled, but no summary signatures found

It still works fine with --user:
> $ flatpak install --user http://flatpak.pitivi.org/pitivi.flatpakref
> Installing: org.pitivi.Pitivi/x86_64/stable
> Required runtime for org.pitivi.Pitivi/x86_64/stable (org.gnome.Platform/x86_64/3.22) is not installed, searching...
> Found in remote gnome, do you want to install it? [y/n]: y
> Installing: org.gnome.Platform/x86_64/3.22 from gnome
> [####################] 9 delta parts, 73 loose fetched; 178829 KiB transferred in 141 seconds
> Installing: org.gnome.Platform.Locale/x86_64/3.22 from gnome
> [####################] 3 metadata, 1 content objects fetched; 13 KiB transferred in 4 seconds
> Installing: org.pitivi.Pitivi/x86_64/stable from org.pitivi.Pitivi-origin
> [####################] 6 delta parts, 34 loose fetched; 117805 KiB transferred in 44 seconds

**Comment by Jehan** [comment]
Note: this issue seems to happen with any flatpakref I test (well I have tested just 3 or 4).

**Comment by Jehan** [comment]
Oh I just noticed issue 860. Mine is probably a duplicate then?

**Comment by alexlarsson** [comment]
Yeah, duplicate. Update to flatpak 0.9.6 should fix this though.
