### ISSUE TITLE
--filesystem=xdg-config/GIMP not working anymore

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#867]
After installing a flatpak on a fresh user, I realized that --filesystem=xdg-config/GIMP does not work anymore.
Exiting flatpaked GIMP, I notice that .var/app/org.gimp.GIMP/config/ is full of the config file whereas .config/GIMP/ did not exist.

Is the feature broken, or did the syntax evolve and we should update the manifest?

Flatpak 0.9.5 from a Fedora 25.
GIMP manifest: https://git.gnome.org/browse/gimp/tree/build/flatpak/org.gimp.GIMP.json

**Comment by TingPing** [comment]
That is working as expected. The `--filesystem` arg just grants read/write access it doesn't change env vars and the `XDG_CONFIG_HOME` env var points to `~/.var/app/org.gimp.GIMP/config/`. It is not generally recommended to forcefully change this to another location.

**Comment by Jehan** [comment]
xdg-config was created especially because we wanted that flatpaked GIMP respects the XDG_CONFIG_HOME. Cf. https://github.com/flatpak/flatpak/issues/328#issuecomment-260565160

So I am pretty sure that going back to being ~/.var/app/org.gimp.GIMP/config/ (which was the case by default) is not "working as expected". :P

**Comment by TingPing** [comment]
> The variable xdg-config used in --filesystem was created especially because we wanted that flatpaked GIMP respects the XDG_CONFIG_HOME.

That is just poor behavior though, the entire point of Flatpak is to be self contained and not conflict with other packages or your system.

> So I am pretty sure that going back to being ~/.var/app/org.gimp.GIMP/config/ (which was the case by default) is not "working as expected". :P

Oh it may have changed behavior in the past I'm not sure but the current behavior is expected at least

**Comment by Jehan** [comment]
> That is just poor behavior though, the entire point of Flatpak is to be self contained and not conflict with other packages or your system.

Well we have millions of creators who collected years of plugins, brushes, dynamics, patterns, and whatnot. We don't want to tell them: why not use flatpak? By the way, all your data will be lost.
Of course, we could ask them to move manually the files, but that's not people-friendly. We version our files, have automatic migration procedures, and so on. We don't do this to ask people to manually move the files in the end.
Moreover moving files from one version to another (for instance from a GIMP 2.8 to GIMP 2.10) might even not work well and would break things (since no migration update happens when one does so, hence files which should have been updated won't be).

Also I am pretty sure that all the XDG base directory variables were meant to be over-written (if at all) by the people only, not by applications. IMO the "poor behavior" is that flatpak over-writes these variables and creates yet another hidden directory under $HOME rather than following a standard which finally ends up getting used by most applications nowadays (after years of frustrations when it was not). Just saying. :P
Now I totally understand the sandbox issue, but I believe a better alternative has to be found (which one? I don't have the perfect solution either to conciliate both the sandbox and keeping-existing-data/config issues, mind you…). IMO the current situation is not right. :-/
In any case, the proposed alternative in #328 was ok for me at least until better is found if you think of a better solution.

> Oh it may have changed behavior in the past I'm not sure but the current behavior is expected at least

@alexlarsson Is it expected? Have you deleted the feature which you implemented in https://github.com/flatpak/flatpak/issues/328#issuecomment-260565160?

**Comment by alexlarsson** [comment]
I did not expect this to regress. Looking at it.

**Comment by alexlarsson** [comment]
It seems to work here. I don't have the gimp flatpak installed, but e.g. net.supertuxkart.SuperTuxKart is and has no filesystem access. I also don't have a .config/GIMP, but i have a .config/eog.
```
$ flatpak run --command=ls --filesystem=xdg-config/eog  net.supertuxkart.SuperTuxKart/x86_64/stable ~/.var/app/net.supertuxkart.SuperTuxKart/config
eog  supertuxkart
```
Since i have no .config/GIMP already it will not do the magic, instead it will store the gimp config in the flatpak per-app area:
```
$ flatpak run --command=ls --filesystem=xdg-config/GIMP  net.supertuxkart.SuperTuxKart/x86_64/stable ~/.var/app/net.supertuxkart.SuperTuxKart/config
eog  supertuxkart
```
I thought this was what you wanted. Inherit existing config if it exists, otherwise work like other flatpaks.
If you want to always use the host side config, then you need to add `:create`, like so:
```
$ flatpak run --command=ls --filesystem=xdg-config/GIMP:create  net.supertuxkart.SuperTuxKart/x86_64/stable ~/.var/app/net.supertuxkart.SuperTuxKart/config
eog  GIMP  supertuxkart
```

**Comment by Jehan** [comment]
> I thought this was what you wanted. Inherit existing config if it exists, otherwise work like other flatpaks.

Oh ok. This is acceptable like this. I was indeed testing on a fresh new user. I will do tests today to make sure that's what it does right now and will close if so.

>  If you want to always use the host side config, then you need to add :create, like so:

Nice feature. Did not know about it. The previously explained behavior can be acceptable though if I confirm it works.
Thanks.

**Comment by matthiasclasen** [comment]
I guess this can be closed then
