### ISSUE TITLE
[REGRESSION] Debug symbols CRC mistmatch when running in "build environment"

### ISSUE THREAD

**Issue by thiblahute** [flatpak/flatpak#872]
I just packed the [Hello World](http://flatpak.org/hello-world.html) example from flatpak.org  to reproduce this issue (with org.gnome.Sdk//3.24)

```
wget https://usercontent.irccloud-cdn.com/file/O5P2lPCq/hello.flatpak.gdbbug.tar.xz
tar -xvf hello.flatpak.gdbbug.tar.xz
flatpak build hello gdb sh
```

Then inside the sandbox:

```
gdb sh
(gdb) run
```

Here we get the following warning:

```
warning: the debug information found in "/usr/lib/debug//usr/lib/libc-2.24.so" does not match "/lib/libc.so.6" (CRC mismatch).
```

Meaning that we are not able to debug inside that env, which is quite limitating.

Changing the used Sdk to 3.22 in `hello/metadata` 'fixes' the issue, meaning it is a recent regression in the 3.24 Sdk.

**Comment by alexlarsson** [comment]
It means your sdk and sdk.debug installations don't match. A simple "flatpak update" should fix this.

**Comment by thiblahute** [comment]
> It means your sdk and sdk.debug installations don't match. A simple "flatpak update" should fix this.

Stupid me :-)
