### ISSUE TITLE
No sound from Flatpak apps, likely cannot find/access PulseAudio

### ISSUE THREAD

**Issue by ChrootDoot** [flatpak/flatpak#878]
Linux from Scratch, 64bit

None of my Flatpak apps have sound, where as their normal counterparts do. I've been troubleshooting for the last few days, but haven't found anything which seems out of place, other than these standard error messages.

For an unofficial Firefox build: (Doesn't mention PA, just appears when I start an audio source)
> fork(): Operation not permitted

And for every other application: (With some slight variation)
> ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

It's difficult to list anything out of the ordinary since I don't know the specifics of how Flatpaks work. Inside the namespace, if I run pacmd, it will tell me there is no running PA server, but this could be standard behavior.

When mounted, Flatpak does not seem to carry over any user groups, which the audio group is needed to play sound for standard applications. Again, I don't believe this is an issue, since the namespace does not contain /dev/snd/, so I assume it goes through Flatpak, in which case there would be no need to receive permissions from an audio group.

D-bus does not return any PulseAudio specific errors, but it did mention this:
> the name org.gnome.SessionManager was not provided by any .service files

I do not have Systemd installed, and I believe I have satisfied all (essential) runtime dependencies. I have ensured PulseAudio is running (not as root or system-daemon) (also it should be started automatically even if it wasn't running), and every audio-required application has the PulseAudio socket enabled.

I don't know what else the check. My biggest thought would be that since I compiled Flatpak from source I would be missing a compilation option, which would explain why nobody else seems to have this issue/an issue similar.

**Comment by ChrootDoot** [comment]
Apparently I am missing xdg portals which I didn't realized was separate software, plus this [https://github.com/flatpak/xdg-desktop-portal/issues/27](issue) suggests PulseAudio support is not implemented, so I'm closing this for now.

**Comment by TingPing** [comment]
@ChrootDoot You don't need the portals for sound, that issue is over future plans to more securely implement it.

**Comment by ChrootDoot** [comment]
Thank you for clarification.

**Comment by ChrootDoot** [comment]
Fixed by exporting XDG_RUNTIME_DIR as /run/user/$(id -u) in /etc/profile, but since Flatpak assumes the uid is 0 I had to enter the uid manually in .profile.

Originally Pulse was exporting its socket to /tmp, which wasn't being mounted by Flatpak.

**Comment by CrashyBang** [comment]
@ChrootDoot could you go a little more into detail as to how you fixed this, I have the same issue, but am having a little trouble understanding your solution.

**Comment by m0nt3sh0t** [comment]
I can confirm same issue on OpenSuSe Tumbleweed 20190301 flatpak version 1.2.3

ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_empty_open
ALSA lib ../../src/dlmisc.c:296:(snd1_dlobj_cache_get) symbol _snd_pcm_empty_open is not defined inside [builtin]

Other tested games work.
