### ISSUE TITLE
libflatpak allows installations of apps incompatible with the current Flatpak version

### ISSUE THREAD

**Issue by joaquimrocha** [flatpak/flatpak#881]
I have noticed that even though the Flatpak CLI does check the required-version before installing/updating an app, using libflatpak will just ignore that setting.
This is a setting that can be verified from the remote-metadata but I believe that it should be rather used inside libflatpak and not by the user.

**Comment by matthiasclasen** [comment]
Have a patch ?

**Comment by joaquimrocha** [comment]
Nope, otherwise I'd gladly have attached it here :)

**Comment by matthiasclasen** [comment]
Looking at where that check lives, maybe FlatpakTransaction should be moved to libflatpak ? Could gnome-software just use that ?

**Comment by joaquimrocha** [comment]
That'd make the API very complex IMO. Defaulting to not installing an app if it's incompatible, or using a flag to control that would be of course much easier to use.

**Comment by matthiasclasen** [comment]
But FlatpakTransaction seems to be doing exactly what g-s needs ? Collect a bunch of things to install, and then install them all in one go...
