### ISSUE TITLE
Allow other forms of checksum for sources in flatpak-manifest such as md5 and sha512.

### ISSUE THREAD

**Issue by adityashah1212** [flatpak/flatpak#892]
It would be great if flatpak-builder/flatpak-manifest could support other forms of checksum provided by the source location. Also if it was possible provide functionality to pull checksum value from a remote location.

**Comment by Limero** [comment]
Manually entering the checksum in the manifest will make sure that the source can't mess with the content without anyone noticing. If it was possible to pull the checksum, both the content and checksum could be maliciously altered and go unnoticed.

**Comment by adityashah1212** [comment]
Hmm... I get it. I guess that makes automatically pulling checksums a big no-no.

**Comment by Barthalion** [comment]
Automatic checksum pulling sounds like a huge hole to perform man-in-the-middle. What's the rationale for other checksums? sha256 seems okay for verifying integrity.

**Comment by adityashah1212** [comment]
Well the reason being most websites don't provide sha256 by default, it is easier if it is available from them directly, as we don't have to download the archive and then calculate the checksum and then add it to manifest. I don't know if work required for adding support for other checksums is worth that small time though.

**Comment by TingPing** [comment]
If we wanted to care about security it would support verifying gpg signed downloads.

**Comment by Barthalion** [comment]
It might be handy, but unless you have automated pipeline, you should always verify more than just a checksum. Having just one hashing algorithm supported at least save us from disputes about which of md5/sha1/sha2/etc is more secure.

**Comment by matthiasclasen** [comment]
I don't think this is needed.
