### ISSUE TITLE
Can't open or save via samba share

### ISSUE THREAD

**Issue by cmurf** [flatpak/flatpak#893]
First I'm running into this bug with both conventional and flatpak applications
https://bugzilla.gnome.org/show_bug.cgi?id=784490

But in that bug I use a work around for conventional applications, which does not work with flatpak applications.

Connected to a samba share in Terminal using Files.

Determine path by drag and drop onto Terminal:
[chris@f26h ~]$ '/run/user/1000/gvfs/smb-share:server=192.168.1.115,share=scratch/wl_apsta.o'

```
[chris@f26h 1000]$ ls -l /run/user/1000
total 0
drwx------. 3 chris chris  60 Jul  3 15:11 app
srw-rw-rw-. 1 chris chris   0 Jul  2 20:44 bus
drwx------. 3 chris chris  60 Jul  2 20:44 dbus-1
drwx------. 2 chris chris  60 Jul  3 15:47 dconf
dr-x------. 2 chris chris   0 Dec 31  1969 doc
drwxr-xr-x. 2 chris chris 120 Jul  3 15:11 flatpak-monitor
drwx------. 3 chris chris  60 Jul  2 20:44 gnome-shell
drwx------. 2 chris chris  40 Jul  3 07:46 gnupg
dr-x------. 3 chris chris   0 Jul  2 20:44 gvfs
drwx------. 2 chris chris 100 Jul  2 20:44 keyring
drwx------. 2 chris chris  80 Jul  2 20:44 pulse
drwxr-xr-x. 3 chris chris 100 Jul  2 20:44 systemd
srwxrwxr-x. 1 chris chris   0 Jul  2 20:44 wayland-0
-rw-rw----. 1 chris chris   0 Jul  2 20:44 wayland-0.lock
[chris@f26h 1000]$
```
However from a flatpak program, I can't navigate beyond this path. The gvfs directory doesn't exist. 

![screenshot from 2017-07-03 15-57-47-2](https://user-images.githubusercontent.com/10091077/27808917-88ba1d1c-6008-11e7-9866-07411b682f26.png)

**Comment by matthiasclasen** [comment]
that is what the filechooser portal is for. The application just needs to use GtkFileChooserNative, and it will get a host-side filechooser with all the mounts you desire.

**Comment by WizardOfWor1969** [comment]
GtkFileChooserNative, you mean they need to change the programs to fix the bug?

**Comment by WizardOfWor1969** [comment]
Also, using a program like Retroarch, this stuff does not work.

**Comment by yllekz** [comment]
Is there a better explanation as to why flatpak apps fail to see smb shares? I see this as an issue with flatpak and not individual applications.

**Comment by ergoithz** [comment]
Well, if somebody's wondering, GtkFileChooserNative won't actually solve this issue even with every gvfs permission (see https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access ) see https://gitlab.gnome.org/GNOME/gtk/-/issues/5078

**Comment by ergoithz** [comment]
@yllekz to answers:
- If not using desktop portals to access files, apps will need wide-open filesystem access (which can be granted via manifest or enabled after install via Flatseal).
- If an app is using the appropriate xdg-desktop-portal mechanism (like GtkFileChooserNative), it will still fail because is still pretty buggy: https://github.com/flatpak/xdg-desktop-portal/issues/820

So, for now, there is no simple solution.

**Comment by sergio-costas** [comment]
There is a fix for portal ones: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/67

**Comment by dreua** [comment]
Note that `--filesystem=host` is not sufficient for this, you weill need `xdg-run/gvfs` or `xdg-run/gvfsd`. Documentation: https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access
