### ISSUE TITLE
Flatpak Applications Do Not Follow Icon Theme

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#897]
Using GNOME 3.24 on fedora 26 with Flatpak 0.9.7
My icon theme is Paper and I have installed the equivalent flatpak package from Flathub for Paper as well. The icons seem fine within the applications but GNOME's app picker shows the .desktop entries using the default icons and not Paper's icons. I noticed that this issue started happening somewhere after upgrading flatpak to 0.9.4

**Comment by TingPing** [comment]
It sounds like you are talking about the icon theme on the host? Maybe you are missing the package there?

**Comment by Saroufim** [comment]
The rest of the applications are fine. Only flatpak applications don't use the icon theme on the app picker.

**Comment by TingPing** [comment]
Ah, the problem might be that flatpak often renames the application if it doesn't already follow the layout it requires, so very often your theme has an icon for lets say `hexchat` but the flatpak is named `io.github.Hexchat`.

Ideally upstream renames their application *and/or* the icon theme adds a symlink for these names too.

**Comment by matthiasclasen** [comment]
Ideally, application icons are not themed. They are part of the personality of the app, not some exchangeable part of the decoration.

**Comment by matthiasclasen** [comment]
I don't think there is anything to do here. As TingPing says, this is up to upstream apps.
