### ISSUE TITLE
flatpak_installation_list_remote_related_refs_sync() suggests things with the wrong arch

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#898]
Basic problem is that `flatpak_installation_list_remote_related_refs_sync("runtime/org.gnome.Platform/x86_64/3.24")` returns results that do not match the architecture of the platform. Test case attached, which can be compiled with `gcc -o test test.c `pkg-config --cflags --libs flatpak` && ./test` which gives the following output:

    getting related refs for: runtime/org.gnome.Platform/x86_64/3.24
    related: runtime/org.gtk.Gtk3theme.Arc/aarch64/3.22    <------------- "aarch64!?"
    related: runtime/org.gnome.Platform.Locale/x86_64/3.24

**Comment by hughsie** [comment]
[test.zip](https://github.com/flatpak/flatpak/files/1122625/test.zip)

**Comment by matthiasclasen** [comment]
Not happening here:

$ ./test
getting related refs for: runtime/org.gnome.Platform/x86_64/3.24
related: runtime/org.freedesktop.Platform.GL.nvidia-378-13/x86_64/1.4
related: runtime/org.freedesktop.Platform.Icontheme.Paper/x86_64/1.0
related: runtime/org.gnome.Platform.Locale/x86_64/3.24

Maybe it got fixed ?

**Comment by matthiasclasen** [comment]
but actually, why isn't it listing any of the gtk themes ?

**Comment by matthiasclasen** [comment]
it turns out that the should_download check filters out all the Gtk theme extensions (but why not the icontheme ones ?)

**Comment by matthiasclasen** [comment]
I tracked this down to a copy-paste error in flatpak_summary_match_subrefs:

https://github.com/flatpak/flatpak/pull/913
