### ISSUE TITLE
Wayland-intel session, but games are rendered by nVidia on optimus

### ISSUE THREAD

**Issue by adityashah1212** [flatpak/flatpak#902]
I have an optimus laptop installed with fedora 26 beta, nvidia proprietary drivers. It seems even though the session is a gnome wayland session over intel driver, games from [steam](https://github.com/flathub/com.valvesoftware.Steam) are rendered by nvidia card. Weird enough steam itself shows Intel Haswell card when looked at the system information, also `org.freedesktop.GlxInfo` shows mesa as renderer. But I am certain that games are rendered by nvidia, because no way a Haswell chip can render a AAA game such as "The Talos Principle" on good graphics settings. I don't have any problems with this as I can play games without having to logout, but I am curious why it is happening.

As a side note, Fedora has libglvnd enabled and my nvidia driver is configured with nvidia-modeset=0, if that helps.

**Comment by nanonyme** [comment]
Sorry for noise, linked wrong way around flathub/com.valvesoftware.Steam#16

**Comment by Mikenux** [comment]
@GeorgesStavracas: It seems that this issue can be closed.
