### ISSUE TITLE
flatpak asking for ostree-1

### ISSUE THREAD

**Issue by zhushazang** [flatpak/flatpak#906]
After installed ostree flatpak "configure" process asking for ostree-1 program instead for just ostree (i guess).

https://paste.pound-python.org/show/0gHMimFN99FIEhopzsKm/

Best regards.

**Comment by pwithnall** [comment]
That’s a pkg-config check for the OSTree library, libostree, whose pkg-config name is `ostree-1`. Make sure you have `ostree-devel` (or whatever your distribution calls the library’s development package) installed.

**Comment by zhushazang** [comment]
There is no ostree in portage system (Gentoo). Then I installed manually using git clonning. Ostree its already installed for sure.

**Comment by pwithnall** [comment]
You need to make sure its `ostree-1.pc` pkg-config file is installed in the prefix where flatpak is looking for pkg-config files.

**Comment by zhushazang** [comment]
There is one in a default location:

/usr/local/lib64/pkgconfig/ostree-1.pc

Do the configure script of flatpak search into default places?

**Comment by matthiasclasen** [comment]
see man pkg-config

to make sure add the location to PKG_CONFIG_PATH
