### ISSUE TITLE
Build finish

### ISSUE THREAD

**Issue by biji** [flatpak/flatpak#91]
Why build finish can only run once? sometimes I forget to add filesystems, etc

**Comment by matthiasclasen** [comment]
We want our builds to be reproducible, ideally. Layering build attempts on top of each other is not a great way to get reproducible results.

**Comment by alexlarsson** [comment]
If you want to just do it while debugging, just remove the exports dir and run again.
But, as @matthiasclasen said, its generally a poor idea to do this so I don't think we should support it in a cleaner way.
