### ISSUE TITLE
Install Pithos as Flatpak fails

### ISSUE THREAD

**Issue by jtlpa** [flatpak/flatpak#914]
command
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
executed OK

command
`flatpak install flathub io.github.Pithos`
FAILS with no GPG key

OS Debina 9.0, MATE DeskTop

Originally filed issue at --> https://github.com/pithos/pithos/issues/483
There response: Hmm, this is probably a better question for flatpak but it might have to do with the rather old flatpak version.

**Comment by jtlpa** [comment]
Resolved by installing Pithos from the file pithos.flatpakref from http://flatpak.org/apps.html

It appears the instructions at https://github.com/pithos/pithos/wiki/Flatpak are wrong

**Comment by TingPing** [comment]
Nothing about the instructions are wrong.
