### ISSUE TITLE
Handling non-free codecs etc as runtime extensions?

### ISSUE THREAD

**Issue by marsjaninzmarsa** [flatpak/flatpak#923]
As suggested here: https://github.com/xhorak/firefox-devedition-flatpak/issues/22#issuecomment-304822640, Flatpak need to have defined policy for handling such cases.

**Comment by TingPing** [comment]
They can either:

- Define an extension point in their app to load ffmpeg that some other party packages
- Just bundle ffmpeg themselves if they legally can

**Comment by gjsieben** [comment]
It isn't just ffmpeg. There are other codecs. libdvdcss2?

There needs to be an extension platform.

**Comment by TingPing** [comment]
Applications can define any extension points they want.

**Comment by marsjaninzmarsa** [comment]
How (without violating US patent rights)?

**Comment by marsjaninzmarsa** [comment]
There is large need for common, generic solution, even as just FAQ answer.

**Comment by alexlarsson** [comment]
The freedesktop sdk (and thus also the gnome and kde one) has an extension point for gstreamer plugins as extensions already.

**Comment by TingPing** [comment]
Firefox doesn't use GStreamer anymore, so it would have to make its own just for ffmpeg.

**Comment by mcatanzaro** [comment]
> The freedesktop sdk (and thus also the gnome and kde one) has an extension point for gstreamer plugins as extensions already.

How does this work?

I see I have installed:

org.freedesktop.Platform.ffmpeg/x86_64/1.6

which I guess is useful for Firefox, but it does not contain gstreamer-libav, so it's not useful for GStreamer-based applications (e.g. anything produced by GNOME, or WebKit).

**Comment by TingPing** [comment]
> which I guess is useful for Firefox, but it does not contain gstreamer-libav, so it's not useful for GStreamer-based applications (e.g. anything produced by GNOME, or WebKit).

I think we agreed to just add `gst-libav` to the runtime, just didn't happen yet.

**Comment by mcatanzaro** [comment]
I don't know: what bad things might happen if gst-libav is installed without ffmpeg? No clue.

**Comment by TingPing** [comment]
> I don't know: what bad things might happen if gst-libav is installed without ffmpeg? No clue.

`ffmpeg` is always there.

**Comment by mcatanzaro** [comment]
What is org.freedesktop.Platform.ffmpeg/x86_64/1.6 for, then?

**Comment by TingPing** [comment]
> What is org.freedesktop.Platform.ffmpeg/x86_64/1.6 for, then?

A build with patent-encumbered bits.

**Comment by hfiguiere** [comment]
This is done at the runtime level. not a fatpak issue.
