### ISSUE TITLE
Permissions as a request

### ISSUE THREAD

**Issue by ranomier** [flatpak/flatpak#928]
I think a flatpaked application should never get permissions before asking the user.

Reasons why i think this is important:
- If for some reason a flatpak gets started (e.G.: the user makes a mistake), a malicious flatpak could do its bad things
- If the user doesn't know what permissions are granted, the flatpaked app could do things the user don't want to.

So my proposal:
\<EDIT>
After talking a little bit on irc i wan't to add things.
- There is this project: https://github.com/flatpak/xdg-desktop-portal . It implements something called portals.
  - If u understand correctly (please correct me) it's like permission groups under well known names.
  - I think that's a good idea! But the fine granulated permission should be accessible at all times.

\<\EDIT>
- Every gui application should list the permissions before installing
  - maybe there could be a possibility to switch permissions on/off
- As soon as a application tries to access a permission there should be a pop up asking for it. (Android style)
- The cli should have a distinguish command for listing granting and revoking permissions:
`flatpak permissions [grant|revoke|list]`

What do you guys think about that?

PS: There should be a network permission lan[yes|no], internet[yes|no]

**Comment by matthiasclasen** [comment]
See flatpak info --show-metadata and flatpak override for commandline control of permissions.

**Comment by gjsieben** [comment]
Also, here is another issue (and bit of polish): Installing Flatpaks doesn't say which permissions the app uses. You install blind to what permissions the app uses. Unless there is a command I'm not getting?

**Comment by matthiasclasen** [comment]
The command flatpak info --show-metadata shows you what permissions the app uses.

**Comment by alexlarsson** [comment]
This is: https://github.com/flatpak/flatpak/issues/275

**Comment by Esokrates** [comment]
@alexlarsson Since the referred issue is closed and only handles a subset of this request here: Is there still something planned in the future in that regard? Similar to Android, where every app has no permissions by default and the users is prompted on first launch if the app is allowed to access $HOME, Microphone etc.?
