### ISSUE TITLE
Accept "Flatpak" or "Flatpack" from Terminal

### ISSUE THREAD

**Issue by gjsieben** [flatpak/flatpak#929]
A small but important tweak.

Flatpak uses a unique name, which is good. However, it is very easy to instead type _flatpa**c**k_ instead of _flatpak_. Because of this, perhaps all commands to a _flatpa**c**k_ should be redirected to _flatpak_.

This way, either command could work:

- flatpak install gnome-apps org.gnome.gedit
- flatpack install gnome-apps org.gnome.gedit

Very subtle, but could help prevent unnecessary frustration.

**Comment by gjsieben** [comment]
Also, to help spread the correct name, perhaps a small "Warning" could appear every time "flatpack" is used.

For example:
Warning: The correct command is "flatpak", not "flatpack." Running _flatpak install gnome-apps org...__

**Comment by ernestask** [comment]
There are tools specifically for this purpose with the alternative of simply using an alias, if you mistype it so often.

And how does acknowledging the incorrect name help spread awareness?

**Comment by matthiasclasen** [comment]
Providing suggestions for misspelt commands is a function of your shell. We are not going to install a 'flatpack' script just to redirect you.

In general, if you misspell like this often, you should use tab completion. flatpak has good completion support.

**Comment by bochecha** [comment]
Especially, introducing a `flatpack` executable means that those typing `flat<tab>` won't get the whole command completed, it will stop at `flatpa`, which would be pretty annoying.

**Comment by gjsieben** [comment]
It isn't for just me. It is just to help prevent some unexpected annoyance from new users. Just a bit of polish. After all, most new users are probably going to type it as "Flatpack" for a long time.

**Comment by TingPing** [comment]
Modern shells are pretty friendly, they might even suggest *"Did you mean flatpak?"* for you, combined with tab completion it is pretty discoverable.
