### ISSUE TITLE
Cannot pull runtime/org.gnome.Platform/x86_64/3.20

### ISSUE THREAD

**Issue by archlinuxrussian** [flatpak/flatpak#93]
Edit: I should have said before, but I'm running Antergos with all the latest updates.
Attached is a log for 
> strace -o log -f flatpak install gnome org.gnome.Platform 3.20

I was getting the error 

> error: While pulling runtime/org.gnome.Platform/x86_64/3.20 from remote gnome: Error resolving 'sdk.gnome.org': Name or service not known

However, I could access https://sdk.gnome.org with my browser. After some help I found this bug and it may be relevant [https://bugzilla.gnome.org/show_bug.cgi?id=763878](url), the main difference for me is the delta stays at "0/9" thusly:

> luke@Neptune ~> flatpak install gnome org.gnome.Platform 3.20
 Receiving delta parts: 0/9 1,7 MB/s 18,3 MB/171,4 MB 
 error: While pulling runtime/org.gnome.Platform/x86_64/3.20 from remote gnome: Error resolving ' sdk.gnome.org': Name or service not known

[log.txt](https://github.com/flatpak/flatpak/files/299027/log.txt)

Hopefully this is of help!

**Comment by Alexander-Wilms** [comment]
For me it didn't get stuck at 0/9 but segfaulted after a while
[log.txt](https://github.com/flatpak/flatpak/files/299157/log.txt)

**Comment by palasso** [comment]
A fedora 24 [user](https://whatofhow.wordpress.com/2016/06/01/libreoffice-5-2-beta-flatpak/#comment-288) had same output as @archlinuxrussian per this comment in the announcement of the LibreOffice flatpak.

**Comment by alexlarsson** [comment]
There was a broken server in the gnome dns setup, which is now fixed.

**Comment by abelncm** [comment]
Hi, I am having the same issue with runtime/org.freedesktop.Platform/x86_64/1.4

I'm on Ubuntu 16.04LTS

**Comment by alexandre1985** [comment]
I'm on Manjaro x86_64. When trying to install spotify I get this flatpak error:

> error: While pulling runtime/org.gnome.Platform/x86_64/3.24 from remote gnome: Error resolving “sdk.gnome.org”: Name or service not known

**Comment by shirriff** [comment]
I repeatedly got the error "While pulling runtime/org.freedesktop.Platform/x86_64/1.4 from remote gnome: Error resolving 'sdk.gnome.org': Temporary failure in name resolution"

Adding "nameserver 8.8.8.8" to /etc/resolv.conf made the problem go away.  I could resolve sdk.gnome.org without this change, so it's puzzling why it was a fix, but it solved my problem. Maybe the previous nameserver was flaky?

**Comment by alexandre1985** [comment]
I have already put "nameserver 8.8.8.8" and still I get the same error.
The last time I tried it went far in the download but I still got the same error.
I'm giving up and use the web player instead.
I someone has a fix for this I would still like to hear it

**Comment by mmFooD** [comment]
Had this error message which was fixed by adding 'nameserver 8.8.8.8' in /etcresolv.conf as mentioned by @shirriff 

> error: While pulling runtime/org.freedesktop.Sdk/x86_64/1.4 from remote gnome: Error resolving 'sdk.gnome.org': Name or service not known
