### ISSUE TITLE
FFmpeg expects libcuda.so.1 but that does not exist

### ISSUE THREAD

**Issue by AsavarTzeth** [flatpak/flatpak#930]
A lot of my Flatpak builds include FFmpeg and my most [recent one](https://github.com/AsavarTzeth/flathub/tree/com.github.djfun.audio-visualizer-python) does make use of Nvidia nvenc hardware acceleration.

I currently disable this in the ffmpeg build because when it is enabled (default), ffmpeg expects the library file to be named differently:

```
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_nvenc))
  Stream #1:0 -> #0:1 (flac (native) -> mp3 (libmp3lame))
Cannot load libcuda.so.1
```

My system currently uses the `org.freedesktop.Platform.GL.nvidia-381-22/x86_64/1.4` extension, which provides `/usr/lib/GL/nvidia-381-22/extra/libcuda.so.381.22`. Perhaps a symlink is in order? or am I missing some more complicated issue?

**Comment by alexlarsson** [comment]
There were some fixes to the nvidia integration recently. Does it work now?

**Comment by TingPing** [comment]
I didn't change cuda since i've never used it but its an easy fix so I'll submit a PR.
