### ISSUE TITLE
Allow "flatpak install" without remote name

### ISSUE THREAD

**Issue by gjsman** [flatpak/flatpak#931]
Just a suggestion, but perhaps we should allow "flatpak install" without specifying remotes names. When entered, it would check all remotes installed for the package. If it is found in only one remote, it goes and installs that version. If it finds it in two different remotes, it lists both, the versions of each, and asks which one to install.

Example:
$ flatpak install org.gnome.gedit
Installing org.gnome.gedit from remote flathub

Another Example:
$ flatpak install org.gnome.gedit
Which remote do you want?
1) flathub, org.gnome.gedit version 0.2
2) other-repository, org.gnome.gedit version 0.1.1

**Comment by Alexander-Wilms** [comment]
I think there should be an additional user prompt, even if the package has only been found in a single repository.

**Comment by gjsieben** [comment]
@Alexander-Wilms That wouldn't be too bad, however, when I run flatpak install right now, it looks like this:

$ flatpak install flathub org.inkscape.Inkscape
[...]
Found in remote flathub, do you want to install it? [y/n]:

See, it already says which remote it is using. If it is in one repository, it will just say that repository name instead. So this isn't really necessary.

**Comment by gjsieben** [comment]
Actually, weirdly, I don't always get the prompt above. ?

**Comment by TingPing** [comment]
@gjsieben That prompt is for installing runtimes.

**Comment by matthiasclasen** [comment]
I'm not convinced that we want to turn the flatpak commandline into a 'do what I mean' style of interface. There could be a command like 'flatpak search' that offers this kind of search through repositories.

**Comment by gjsieben** [comment]
It isn't for a specific style. This is just a convenience tweak. Flatpak search is a whole nother deal.

**Comment by gjsieben** [comment]
Besides, it makes installing packages faster if you can't remember which repository it is from (directly, not just searching for them.) It also helps keep things that change (like books and online media) possibly more up-to-date.

**Comment by gjsieben** [comment]
I just found that this already exists for repositories in a form similar to what I am suggesting:
`flatpak install flathub org.geogebra.GeoGebra
Required runtime for org.geogebra.GeoGebra/x86_64/stable (org.freedesktop.Platform/x86_64/1.6) is not installed, searching...
Found in several remotes:
1) flathub
2) gnome
Which do you want to install (0 to abort)? [0-2]: ^C
`

**Comment by alexlarsson** [comment]
The security model for flatpak is tied to installs happening from a well-known remote, so we don't want to automagically do this. However, in the latest version we have things like flatpak search which makes finding things easier.
