### ISSUE TITLE
Create a Runtime for nvidia-375-82

### ISSUE THREAD

**Issue by vanyasem** [flatpak/flatpak#933]
I recently upgraded my NVidia drivers to 375.82. I can't install any other version because it will break CUDA support. Flatpak doesn't seem to have a Runtime for this particular version thus breaking [apps](https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers) that depend on it.

```
$ cat /sys/module/nvidia/version
375.82
```

```
$ flatpak remote-ls gnome | grep nvidia-375
org.freedesktop.Platform.GL.nvidia-375-26
org.freedesktop.Platform.GL.nvidia-375-39
org.freedesktop.Platform.GL.nvidia-375-66
org.freedesktop.Platform.GL32.nvidia-375-26
org.freedesktop.Platform.GL32.nvidia-375-39
org.freedesktop.Platform.GL32.nvidia-375-66
```

I am running elementary OS 0.4.1 Loki x86_64 based on Ubuntu 16.04.

**Comment by alexlarsson** [comment]
built
