### ISSUE TITLE
Add ability to persist individual files

### ISSUE THREAD

**Issue by Limero** [flatpak/flatpak#934]
Using --persist=abc.txt in a manifest creates a directory called abc.txt. There should be an option to persist individual files instead of just directories. The best current solution I can find is to persist the whole parent directory which seems unnecessary.

Why?
I've encounter applications that creates files directly in the home directory and I do want to keep those, without giving full access to my home directory.

**Comment by alexlarsson** [comment]
Persisting works by creating bind mounts, and bind mounts of files are possible, but they don't work as expected. For instance, you cannot remove or replace the files with a new version. So, i understand the need, but there is no good technical solution to this.
