### ISSUE TITLE
Source installation question - Documentation: is it correct or missing?

### ISSUE THREAD

**Issue by shevegen** [flatpak/flatpak#940]
The main readme says that configure, make and make install are used.

However, after grabbing the .zip from the website, and extracting it, trying to run ./configure gives:

  bash: ./configure: No such file or directory

If I run autoconf, then I can run ./configure.

Is the "autoconf" step missing? If so then it would be nice if that step could be added into the main readme, just to give people the confidence that they are doing something right. It's a minor thing but still - right now I am compiling flatpak from source and wondering if I did everything correct so far (I assume so, but assumptions are not always correct).

Feel free to close this here at any moment in time, in any way that you feel warranted and it.

**Comment by mdeguzis** [comment]
See `man flatpak-builder` and `man flatpak-manifest`. Other build systems are supported.

**Comment by pwithnall** [comment]
> after grabbing the .zip from the website

Which .zip from which website?

**Comment by matthiasclasen** [comment]
It is general tribal knowledge that you have to run autoconf to create a configure file if it is missing. But a proper distribution archive _should_ contain configure. Can you answer Philips question ?

**Comment by TingPing** [comment]
Surely the source code zips github generates.

**Comment by pwithnall** [comment]
> Surely the source code zips github generates.

Probably, but let’s not guess.

**Comment by alexlarsson** [comment]
If you want to build this, please use the .tar.xz releases from https://github.com/flatpak/flatpak/releases. These have the files needed
