### ISSUE TITLE
Alternative to JSON manifest for flatpak-build?

### ISSUE THREAD

**Issue by mdeguzis** [flatpak/flatpak#941]
I don't like so much that you can't really avoid having to manually compile dependencies as part of your build. For something like Kodi, that is a huge amount of "modules" you'd have to write in and get all correct vs. just adding a line to debian/control for an existing ffmpeg package.

JSON gets messy, and keeping which bracket/brace goes to which gets out of hand with long files. Contrast this to A Makefile or debian/rules, where things are structure with labels, and allow scenarios where "this depends on that", just as you have modules here. I see the JSON manifest as a barrier for acceptance, I know it is for me, even if I write JSON payloads frequently for my day job as a devop for Hadoop.

Having packaged for Debian/Fedora/Arch Linux for several years, it just seems there is a better way. Any plans for an alternative? JSON generator?

**Comment by TingPing** [comment]
Just throwing my personal thoughts out there:

> and allow scenarios where "this depends on that"

A module can have modules, so they are effectively marked as dependencies. Sure the builder json doesn't express complex dependencies but I don't think that is necessary. A Makefile is over-complex for the task and has downsides to a purely declarative JSON file.

> JSON gets messy, and keeping which bracket/brace goes to which gets out of hand with long files. 

Cleaner formats like say YAML or TOML introduce unwanted dependencies, extra complexity, and have less common parsers.

> just adding a line to debian/control for an existing ffmpeg package.

Automatically reusing deb/rpm definitions could be useful and Fedora will probably be doing that soon. 

There is nothing stopping generating from any format you want as `flatpak-builder` is little more than a convenient wrapper above `flatpak` already.

**Comment by matthiasclasen** [comment]
You may like the idea that some have of generating flatpaks from buildstream

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#2
