### ISSUE TITLE
flatpak update gives "error: GPG signatures found, but none are in trusted keyring" after adding flathub

### ISSUE THREAD

**Issue by skierpage** [flatpak/flatpak#944]
I followed https://flathub.org/#using and added flathub to my old-ish flatpak setup:
``` bash
% flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```
but then `flatpak update` displays _error: GPG signatures found, but none are in trusted keyring"_

The error message is the same as in issue #421

**Comment by skierpage** [comment]
I then tried `flatpak remote-ls --app flathub` and got the same _error: GPG signatures found, but none are in trusted keyring_.

I then tried to clean up with `flatpak remote-delete flathub` but that resulted in _error: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Flatpak system operation ConfigureRemote not allowed for user_
So I retried with sudo, `sudo flatpak remote-delete flathub` , which worked, but now when I try to reproduce, the same initial `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` command results in _error: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Flatpak system operation ConfigureRemote not allowed for user_

This is all with Flatpak 0.9.7

**Comment by pothos** [comment]
Maybe my issue is the same. Do I really have to delete everything and add it anew to get it working again? Thanks for the help :)

```
flatpak update --user
Looking for updates...
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
[…]
error: GPG signatures found, but none are in trusted keyring

```

**Comment by pothos** [comment]
I might have used an 0.8 version while flathub changed its key and so it was not migrated as it would be with a recent flatpak version.

It could be resolved by importing the new key manually.

The flathub entry in ~/.local/share/flatpak/repo/config is:
```
[remote "flathub"]
gpg-verify=true
gpg-verify-summary=true
url=https://flathub.org/repo/
xa.title=Flathub

```
The manual key import was done via:
```
wget https://flathub.org/repo/flathub.gpg
flatpak --user remote-modify --gpg-import=flathub.gpg flathub
```

**Comment by viktormadarasz** [comment]
I have the same issue on flatpak 0.9.7  even after importing the key as @pothos specified

**My Flatpak config entry looks like below in ~/.local/share/flatpak/repo/config** 

[core]
repo_version=1
mode=bare-user

[remote "flathub"]
gpg-verify=true
gpg-verify-summary=true
url=https://flathub.org/repo/
xa.title=Flathub

**--- Error:   ----------**

[viktormadarasz@littlepocoklenovo Downloads]$ flatpak --user remote-modify --gpg-import=flathub.gpg flathub
[viktormadarasz@littlepocoklenovo Downloads]$ sudo flatpak install --from https://git.gnome.org/browse/recipes/plain/flatpak/gnome-recipes.flatpakref
[sudo] password for viktormadarasz: 
Installing: org.gnome.Recipes/x86_64/stable
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
error: GPG signatures found, but none are in trusted keyring

Thanks

Viktor

**Comment by alexlarsson** [comment]
@viktormadarasz Ah, but that example is pulling gnome-recipes from the old gnome repo, not from flathub. After having adder the flathub remote (with --user) you should just do:
`flatpak --user install flathub org.gnome.Recipes`

**Comment by alexlarsson** [comment]
Oh, sorry, that was wrong of me. The gnome-recipes flatpakref actually *does* point to flathub, but has the wrong (old) GPG key for it. lemme update it.

**Comment by viktormadarasz** [comment]
Hi

thanks

works like a charm now

Regards

Viktor Madarasz

Sent from my iPad

On 04 Sep 2017, at 13:51, Alexander Larsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, sorry, that was wrong of me. The gnome-recipes flatpakref actually does point to flathub, but has the wrong (old) GPG key for it. lemme update it.

**Comment by Adhi1296** [comment]
Failed to install com.belledonnecommunications.linphone: Commit bae79f29ce390b6b28254cba0ae63f1bbb8d9a30f50acce422ce5ef1f1839441: GPG signatures found, but none are in trusted keyring getting this error again.

**Comment by Adhi1296** [comment]
Failed to install com.belledonnecommunications.linphone: Commit bae79f29ce390b6b28254cba0ae63f1bbb8d9a30f50acce422ce5ef1f1839441: GPG signatures found, but none are in trusted keyring

**Comment by barthalion** [comment]
Please report it to the team managing repository that application comes from.

**Comment by lagweasel** [comment]
@Adhi1296 I had the same problem and found I needed to use `https://linphone.org/flatpak/bc.flatpakrepo` for the remote URL instead of `https://linphone.org/flatpak/linphone.flatpakref`
