### ISSUE TITLE
Vulkan icd directory is broken symbolic link

### ISSUE THREAD

**Issue by LinAGKar** [flatpak/flatpak#949]
I was unable to use Vulkan withing Flatpak. Upon further inspection, /etc/vulkan, which is supposed to contain the icd.d directory with the Vulkan icd files in it, is a broken symbolic link to /usr/lib/GL/vulkan. If, however, I delete /etc/vulkan, and then create the file /etc/vulkan/icd.d/nvidia_icd.json with the content:
```
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.0.46"
    }
}
```
I do get working Vulkan. Of course, this is not persistent, and requires me to go in through `Flatpak run --command=sh` and launch the program from in there. I am, as you might have guessed, using the proprietary Nvidia driver. I'm also on OpenSUSE Leap 42.3. The program I tested this with was RetroArch, from Flathub.

**Comment by alexlarsson** [comment]
Yeah. This seems to be an issue with the nvidia driver builds. It doesn't contain a vulkan/ directory, which makes this not work right now. Otherwise it will automatically merge it, like it currently does with /usr/lib/GL/glvnd/egl_vendor.d/

**Comment by alexlarsson** [comment]
I think this is fixed in the latest nvidia extension
