### ISSUE TITLE
Add sandboxed equivalent to HostCommand

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#953]
From https://github.com/flatpak/flatpak/wiki/BOF-GUADEC-2017:
> Needed for stuff like thumbnailers/pixbuf loaders and browser sandboxes if they are to be run inside Flatpak. At present newly added support for sandboxing gnome-desktop thumbnailers is disabled when the app is inside Flatpak, arguably lowering security.
> 
> Starting new user namespaces is a privileged operation which is impossible inside a Flatpak sandbox, and other things like Chrome's sandbox setuid helper also fail.
> 
> Prototype something based on the Host command but have it start the command in a sandbox with the same r/o /usr and /app as the flatpak

If a test application is required, the easiest would be to use one of the finding/reminding applications, or nautilus, inside a Flatpak, and modify the builtin `gnome-desktop` library locally to take advantage of the new API.

**Comment by alexlarsson** [comment]
This is now in with the flatpak portal.
