### ISSUE TITLE
install on a Live CD?

### ISSUE THREAD

**Issue by ctaggart** [flatpak/flatpak#957]
How do I install and run a flatpak on a live CD such as [Fedora 26 Cinnamon](https://spins.fedoraproject.org/cinnamon/download/)?

Steps to reproduce:
```
sudo dnf install flatpak
sudo flatpak install https://s3.amazonaws.com/ctaggart/flatpak/gtk-rs-examples.flatpakref
```

![image](https://user-images.githubusercontent.com/80104/29250353-c1a3536c-8049-11e7-8260-b760f7e9a905.png)

**Comment by TingPing** [comment]
Passing `--user` may work?

**Comment by ctaggart** [comment]
> Passing `--user` may work?

I remember also trying that, but it didn't work. It required gnome 3.22, which required sudo.

**Comment by TingPing** [comment]
You can add a repo and install both runtimes and applications as user with `--user`, no root access required at all.

**Comment by alexlarsson** [comment]
Yes, --user install should work fine here. There might be issues with $HOME on tmpfs, but those should be fixed in the latest versions (not sure if those are in f26 yet though)
