### ISSUE TITLE
runtime/org.gnome.Sdk/x86_64/3.20 fails to install

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak#96]
Sometimes flatpak gets stuck at 

```
[awilms@localhost ~]$ flatpak install gnome org.gnome.Platform 3.20

Receiving delta parts: 9/9 622,1 kB/s 31,7 MB/94,9 MBSegmentation fault (Speicherabzug geschrieben)
```

But even if it doen't segfault I can't use the runtime:

```
[awilms@localhost ~]$ flatpak install gnome org.gnome.Platform 3.20

9 delta parts, 71 loose fetched; 167335 KiB transferred in 174 seconds
[awilms@localhost ~]$ flatpak run org.gnome.Builder
error: runtime/org.gnome.Sdk/x86_64/3.20 not installed
```

**Comment by alexlarsson** [comment]
What build of flatpak are you using?

**Comment by alexlarsson** [comment]
Oh, gnome-builder is special. It uses the sdk as the runtime (since it needs a compiler, etc). So you need to:
flatpak install gnome org.gnome.Sdk 3.20

**Comment by alexlarsson** [comment]
Still, it should not segfault

**Comment by Alexander-Wilms** [comment]
This time there was some more info before it segfaulted:

```
flatpak install gnome org.gnome.Sdk 3.20

(flatpak install:2448): flatpak-WARNING **: Can't find org.freedesktop.Flatpak.SystemHelper: Fehler beim Aufruf von StartServiceByName für org.freedesktop.Flatpak.SystemHelper: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.Flatpak.SystemHelper': timed out

Segmentation fault (Speicherabzug geschrieben)
```

**Comment by alexlarsson** [comment]
Means the dbus helper for system-wide installation using policy kit was not found. But it worked after that?

**Comment by Alexander-Wilms** [comment]
No. I tried it a few more times. First the download appeared to be stuck then the helper wasn't found.

```
[awilms@localhost ~]$ flatpak install gnome org.gnome.Sdk 3.20

Receiving delta parts: 1/17 1,1 MB/s 77,3 MB/315,7 MB^C
[awilms@localhost ~]$ flatpak install gnome org.gnome.Sdk 3.20

Receiving delta parts: 1/17 703,6 kB/s 17,6 MB/311,0 MB^C
[awilms@localhost ~]$ flatpak install gnome org.gnome.Sdk 3.20

(flatpak install:2862): flatpak-WARNING **: Can't find org.freedesktop.Flatpak.SystemHelper: Fehler beim Aufruf von StartServiceByName für org.freedesktop.Flatpak.SystemHelper: Zeitüberschreitung wurde erreicht

Segmentation fault (Speicherabzug geschrieben)
[awilms@localhost ~]$ flatpak install gnome org.gnome.Sdk 3.20

(flatpak install:2905): flatpak-WARNING **: Can't find org.freedesktop.Flatpak.SystemHelper: Fehler beim Aufruf von StartServiceByName für org.freedesktop.Flatpak.SystemHelper: Zeitüberschreitung wurde erreicht

Segmentation fault (Speicherabzug geschrieben)
[awilms@localhost ~]$ flatpak run org.gnome.Builder
error: runtime/org.gnome.Sdk/x86_64/3.20 not installed

```

**Comment by alexlarsson** [comment]
And what packages are you using of flatpak itself?

**Comment by Alexander-Wilms** [comment]
I dnf installed flatpak and flatpak installed org.gnome.Builder, if that's what you mean.

**Comment by alexlarsson** [comment]
So, fedora? what version?

**Comment by Alexander-Wilms** [comment]
Yes, Fedora 24 with all packages up to date.

**Comment by alexlarsson** [comment]
@amigadave Did you ever see this?

**Comment by amigadave** [comment]
I have not seen this, but given that Fedora 24 does not have 0.6.4 yet (it is still in updates-pending), I guess that this is 0.6.2-1. I would guess that the D-Bus daemon has not been restarted, and is not aware of the new service file (does it monitor the system-services directory for new files?). I would try restarting the system dbus-daemon, probably by rebooting (as most system services are not tolerant of the bus disappearing).

**Comment by Alexander-Wilms** [comment]
I rebooted and something appears to have changed:

```
[awilms@localhost ~]$ flatpak install gnome org.gnome.Sdk 3.20

17 delta parts, 39 loose fetched; 32879 KiB transferred in 49 seconds
[awilms@localhost ~]$ flatpak run org.gnome.Builder
error: Unable to start app
```

But it looks like the runtime is still not installed:

```
[awilms@localhost ~]$ flatpak list
org.gnome.Builder
```

**Comment by amigadave** [comment]
You need to install flatpak-libs, or wait for 0.6.4-1 to go stable.

**Comment by Alexander-Wilms** [comment]
Thanks, now it runs.

**Comment by alexlarsson** [comment]
Various issues, but i think all fixed now.

**Comment by mohamed591195** [comment]
now after 1 year i think i have the same problem on ubuntu

from terminal 

flatpak install --user http://flatpak.pitivi.org/pitivi.flatpakref                                                                                         
Installing: org.pitivi.Pitivi/x86_64/stable                                                                                                                                                      
Required runtime for org.pitivi.Pitivi/x86_64/stable (org.gnome.Platform/x86_64/3.22) is not installed, searching...                                                                             
Found in remote gnome, do you want to install it? [y/n]: y                                                                                                                                       
Installing: org.gnome.Platform/x86_64/3.22 from gnome                                                                                                                                            
[###########         ] Downloading: 95.3 MB/182.3 MB (108.8 kB/s)                                                                                                                                
error: While pulling runtime/org.gnome.Platform/x86_64/3.22 from remote gnome: Could not connect: Socket I/O timed out 

i did my best to solve it , can any one help please

**Comment by qazip** [comment]
So, @mohamed591195 , did you solve it?

**Comment by mabdullah4** [comment]
@mohamed591195 I think it's your internet issue.. I got same error will installing but worked on reconnecting.. :-)

**Comment by hub229ox** [comment]
flatpak install gnome org.gnome.Sdk 3.20
is not working


> You need to install flatpak-libs, or wait for 0.6.4-1 to go stable.

how do I install it ?

**Comment by hub229ox** [comment]
> flatpak install --user http://flatpak.pitivi.org/pitivi.flatpakref
 
> Found in remote gnome, do you want to install it? [y/n]: y
> Installing: org.gnome.Platform/x86_64/3.22 from gnome
 

here, gnome is not found and the install breaks as I expected.

same with "AbiWord" flatpak app. it all just breaks.

**Comment by hub229ox** [comment]
flatpak install  flathub   org.gnome.Sdk       3.28 

works though
