### ISSUE TITLE
Allow apps to support multiple runtimes

### ISSUE THREAD

**Issue by gjsieben** [flatpak/flatpak#964]
Instead of an app only supporting one runtime, allow developers to let their apps run on multiple runtimes.

This is so if a runtime that is compatible already is on the computer, then use that instead of downloading a different one.

When it comes to multiple runtime versions, download the new version (if possible). E.g., prefer Gnome.Platform//3.26 over Gnome.Platform//3.24, unless there isn't enough disk space to download the new one.

**Comment by alexlarsson** [comment]
Its possible to force-use a different runtime than the app specified, e.g. for testing. However, doing so is completely unsupported. 

Making this a supported thing is completely contrary to the major goals of flatpak which is that the code that runs on the users machine is exactly what the developer built and tested against, and will never be supported by flatpak.

**Comment by gjsieben** [comment]
@alexlarsson This is not what I meant. What I meant was that the developer could choose to support multiple runtimes if preferred. An example is that the Freedesktop runtime is similar to the GNOME runtime, just less features. Therefore, as a developer, perhaps I might say I want to support both.

**Comment by cgwalters** [comment]
One thing I'd say though is at least with multiarch in the picture, things are going to be built which aren't tested locally.

**Comment by zakaria-chahboun** [comment]
Yeah if that possible will be better!

**Comment by ell1e** [comment]
I think this would be really cool if 1. a developer is interested in actually testing the multiple runtimes, and 2. the app is portable to start with so supporting a whole row of runtimes can be easy in that case. The latter may for example be the case when an AppImage release already exists, and the flatpak is just based on integrating the AppImage version. In that case, supporting multiple runtimes could be easier. This would help bring down disk storage use for users.

**Comment by Mikenux** [comment]
If you are interested in this issue, the author can reopen it if possible, or you can either open another issue or mention an active member or collaborator and ask them to reopen it.
