### ISSUE TITLE
[gnome] Show both distro and flatpak apps in applications list

### ISSUE THREAD

**Issue by abdulkareemnalband** [flatpak/flatpak#967]
This maybe an issue with gnome shell, but if I install same app(`gnome builder`) from distro (`Fedora 26`) 
Only one is shown in Applications List (Flatpak version)

### Issue
Only one App is shown in Shell Applications List even when two different versions of apps are installed

### Excepted Behaviour 
More than one Entries should be shown in Shell Application if there are multiple versions of app

### Steps to reproduce 
 1. Install `Gnome Builder` from distro repository
 2. Install `Gnome Builder` from `gnome` flatpak  repository
 3. Open Shell Application LIst
 4. Only one entry visible

### System details
**Distro** : Fedora 26
**Flatpak** : flatpak-0.9.7-2.fc26.x86_64
**bubblewrap** : bubblewrap-0.1.8-1.fc26.x86_64

**Comment by matthiasclasen** [comment]
This is not a flatpak issue

**Comment by abdulkareemnalband** [comment]
filed bug against gnome shell https://bugzilla.gnome.org/show_bug.cgi?id=786378
