### ISSUE TITLE
Icon themes doesn't work when built locally

### ISSUE THREAD

**Issue by bilelmoussaoui** [flatpak/flatpak#968]
Hello,
I have been trying to build Numix icon themes as flatpak packages. But sadly, something seems to be not working.
The manifest file
```json
{
  "id": "org.freedesktop.Platform.Icontheme.Numix",
  "branch": "1.0",
  "runtime": "org.freedesktop.Sdk",
  "build-extension": true,
  "sdk": "org.freedesktop.Sdk",
  "runtime-version": "1.6",
  "sdk-extensions": [],
  "separate-locales": false,
  "appstream-compose": false,
  "modules": [
    {
      "name": "NumixBase",
      "buildsystem": "simple",
      "build-commands": [
        "install -dm755 /usr/share/runtime/share/icons/Numix",
        "cp -aL Numix/* /usr/share/runtime/share/icons/Numix/"
      ],
      "sources": [
        {
          "type": "git",
          "url": "https://github.com/numixproject/numix-icon-theme.git",
          "branch": "master"
        }
      ]
    },
    {
      "name": "appdata",
      "buildsystem": "simple",
      "build-commands": [
        "mkdir -p ${FLATPAK_DEST}/share/appdata",
        "cp org.freedesktop.Platform.Icontheme.Numix.appdata.xml ${FLATPAK_DEST}/share/appdata",
        "appstream-compose --basename=org.freedesktop.Platform.Icontheme.Numix --prefix=${FLATPAK_DEST} --origin=flatpak org.freedesktop.Platform.Icontheme.Numix"
      ],
      "sources": [
        {
          "type": "file",
          "path": "org.freedesktop.Platform.Icontheme.Numix.appdata.xml"
        }
      ]
    }
  ]
}
```
the appdata file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="runtime">
  <id>org.freedesktop.Platform.Icontheme.Numix</id>
  <metadata_license>CC0-1.0</metadata_license>
  <name>Numix Icon Theme</name>
  <summary>Numix Base icon theme</summary>
  <description>
    <p>A nice and modern icon theme</p>
  </description>
  <url type="homepage">https://numixproject.org/</url>
  <url type="bugtracker">https://github.com/numixproject/numix-gtk-theme/issues/</url>
</component>
```
The build is done correctly without any issues. And the icon theme extension is installed correctly. But when I open Nautilus or Gedit (flatpak apps ofc) the icon theme is not used at all. I have compared the files under /build/files with the files from the Paper icon theme from Flathub and the file layout is the same. Building and installing Paper icon theme by myself results on not working icon theme too :( the bizarre part about this issue is installing Paper icon theme from flathub seems to work as expected.

Also, this might be a side issue, but Gtk inspector doesn't detect the installed extensions (Themes/Icons) on flatpak apps. So this must be an upstream issue i guess
![screenshot from 2017-08-17 20-09-39](https://user-images.githubusercontent.com/7660997/29427387-efa011a4-8389-11e7-8765-70c8cf521e5d.png)

The issue was discussed with @TingPing on #flatpak iirc

**Comment by TingPing** [comment]
Just some more data, the paths are in `$XDG_DATA_DIRS` but themes are technically missing the `gnome` theme they inherit from. So just a guess that maybe Gtk checks for those missing now and hides them.

**Comment by matthiasclasen** [comment]
the inspector doesn't actually look at all data dirs, it seems. Patches welcome
