### ISSUE TITLE
Provide scribus dev

### ISSUE THREAD

**Issue by JLuc** [flatpak/flatpak#97]
Could flatpack also provide a scribus pak of the HEAD dev version 
along with gimp and other tools on the app page of flatpak.org ?
http://flatpak.org/apps.html

**Comment by alexlarsson** [comment]
Scribus is actually in the nightly graphics apps repo, but it doesn't work, so its not listed.
However. this is a project to create an application system, not to package applications. So unless someone else shows up to do the work we have other things that we need to focus on.
