### ISSUE TITLE
[Question] The Size Of Flatpak Apps?

### ISSUE THREAD

**Issue by Syntist** [flatpak/flatpak#977]
The size of the installed app is equal to the installed app?

like downloading Discord, 63mb of download but on disk take upto 250mb. 

So 250mb is the actual size or it just show's that way?

**Comment by TingPing** [comment]
Discord is a proprietary application so the flatpak doesn't actually contain anything it just downloads Discords installer at runtime. To make matters even worse is their installer isn't the actual application it downloads an ever-changing release each startup and we can't possibly know the size of that download ahead of time.

**Comment by Syntist** [comment]
Ok, but i am still not clear,
Like runtimes, gnome runtime is of 250 mb download,
but after the installation the size of that file is +750 mb. 

My Question was the Size of file when being download and the size of file after being install is different?

**Comment by alexlarsson** [comment]
The download size is the download size. It is compressed, so no, it is not the same as the installed size.

**Comment by alexlarsson** [comment]
750 mb seems large though, the current gnome platform is 605 MB for me.
