### ISSUE TITLE
Add some way of enabling the personality system call for builds (for Emacs and possibly other things)

### ISSUE THREAD

**Issue by muep** [flatpak/flatpak#978]
Currently the `personality` system call is forbidden in the sandbox setup in [common/flatpak-run.c:4021](https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L4021). I am not familiar at all with this system call but it indeed looks like something that's good to keep unavailable by default.

The application where I ran into wishing to have this system call available is GNU Emacs. It would be really nice to be able to have an identical, up-to-date Emacs installation on computers I use, but currently this seems difficult to achieve because at least the Emacs build process expects to be able to use this system call to disable ASLR. In latest stable Emacs (25.2) this call is in [emacs.c:684](http://git.savannah.gnu.org/cgit/emacs.git/tree/src/emacs.c?h=emacs-25.2#n684). In case this system call is not available, a special process dump/re-exec mechanism will fail to get memory addresses right and this gets you a Segmentation Fault during the build.

Emacs can be built without this mechanism at the cost of making the editor startup take several extra seconds. This would be workable in my use, but this mode of operation runs a bit different code paths on editor startup and seems to be rarely tested because I get many extra bugs in Emacs if I use that. And of course ideally Emacs would be just fixed to work better with ASLR enabled, but that would require quite a lot of low-level work at their end. Especially since some users would consider those extra seconds unacceptable and on hardware more modest than a recent Intel i7 it may be more like minutes than seconds. I'm not saying that it is absolutely no work to address in Flatpak, but to me it looks like most of the work would be parameter delivery rather than doing much refactoring and upheaval.

Would it be possible to have some way of loosening the sandbox either for just this system call, or alternatively any developer-configurable system call?

**Comment by nanonyme** [comment]
Rather than allowing arbitrary usage of personality, would it alternatively be possible to use overrides to pre-set this kind of things like disabling ASLR per Flatpak? Of course if the Flatpak segfaults without overrides, this means really bad usability....

**Comment by alexlarsson** [comment]
The --allow=devel feature already unlocks some things ofthe seccomp limits (ptrace and perf), I guess it could also apply to the personality syscall, at least the some of the flags.

**Comment by muep** [comment]
@nanonyme I think Emacs might actually make do with having this syscall enabled only at build time. At least in my quick testing, I was able to build it with locally modified flatpak installation that allows the `personality` system call. Results from this build seemed to be OK in flatpak as shipped in Fedora 26 repos.

For cases where this is actually needed at runtime (I have no idea if such cases exist and someone wants flatpaks of those), I think it would definitely be best to have that marked in the metadata so that users would not need to figure by themselves why it does not work.

@alexlarsson  Are the devel options intended for being able to build an application at all, or more for debugging? As far as I currently know I might just run the build with the `--allow=devel` if that system call was forbidden only in the non-devel blacklist. This at least would seem fairly straightforward to implement.

My impression is that most applications, like those you'd get from flathub, however are built without devel so I'm a bit worried about if there are some other effects that'd make the results from these builds unsuitable for "production" use. But can someone confirm if it'd be reasonable to aim for being able to run builds with `--allow=devel` and the application with a more usual sandbox?

**Comment by nanonyme** [comment]
@muep My bad then, my understanding from the thread was Emacs needs ASLR disabled to start at all (since it loads some image from disk) so it wouldn't be limited to packaging

**Comment by muep** [comment]
My bad too because I did not describe this precisely enough. But hopefully this is now clear enough. And I guess I should still warn that I am not very familiar with either Emacs or Flatpak source code so my impression might be inaccurate.

**Comment by alexlarsson** [comment]
--allow=devel is a permissions like other permissions. It gives the app access to things that "normal" apps really don't (shouldn't) need, and that could be a security risk (attack surface mitigation). That doesn't mean no apps will need it. For instance, an IDE with a debugger clearly needs strace access, so they have to request it (and e.g. gnome-builder does so).

**Comment by alexlarsson** [comment]
I looked into this, but given the current APIs in libseccomp it is really hard to implement the correct filter for allowing the flag.

**Comment by nedrichards** [comment]
I think this is closed by https://github.com/flatpak/flatpak/pull/1414
