### ISSUE TITLE
Export MIME types

### ISSUE THREAD

**Issue by L0L022** [flatpak/flatpak#98]
Flatpak could export these files:
- /app/share/mime/packages/valid_appname.xml
- /app/share/icons/hicolor/iconsize/mimetypes/nonvalid_name.png

Like it does with icons and desktop files ?

**Comment by alexlarsson** [comment]
Hmm, the mimetype icons are tricky. We require the app id as prefix because otherwise things could conflict between different apps, and between the app and the host. For instance, an app could easily replace the icon for a dangerous file type with an innocent-looking one...

**Comment by ximion** [comment]
In theory, Flatpak could check for collisions and ignore the icon there already is an icon provided. Maybe the Flatpak-installed icon could also have a lower priority than trusted stuff from the theme or hicolor iconset.
But, that being said, I think the thread of making "dangerous" filetypes look harmless is already there by allowing users to install icon themes in their home directory...

In any case, the issue of registering mimetypes is real, e.g. apps like Scribus will need that.

**Comment by L0L022** [comment]
Virtualbox uses its own icon, virtualbox.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
   <mime-type type="application/x-virtualbox-vbox">
      <comment>VirtualBox Machine Definition</comment>
      <comment xml:lang="en">VirtualBox Machine Definition</comment>
      <glob pattern="*.vbox"/>
      <icon name="virtualbox-vbox"/>
   </mime-type>
```
`<icon>` description from [freedesktop](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-0.18.html): icon elements specify the icon to be used for this particular mime-type, given by the name attribute. Generally the icon used for a mimetype is created based on the mime-type by mapping "/" characters to "-", but users can override this by using the icon element to customize the icon for a particular mimetype. This element is not used in the system database, but only used in the user overridden database. Only one icon element is allowed.

**Comment by alexlarsson** [comment]
@ximion as a non-sandboxed user you can obviously replace an icon by installing an icon theme. But that would be an explicit action. The problem is when you install a seemingly safe, sandboxed "org.small.Game" and it maliciously replaces some completely unrelated icon (or other kind of file if we more generally allow non-prefixed files).

@L0L022 Yeah, if you use a named icon like that it could work.

**Comment by L0L022** [comment]
If a bad app want to hide a bad file with ODT icon:
```
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
	<mime-type type="application/x-bad-app">
		<comment>BAD APP</comment>
	<glob pattern="*.badapp"/>
        <icon name="vnd.oasis.opendocument.text"/>
	</mime-type>
</mime-info>
```

**Comment by matthiasclasen** [comment]
I think we can consider letting apps export mime types under some constraints:

1) only allow to add new types, never override existing ones
2) only allow to use the app icon

anything else ?

**Comment by alexlarsson** [comment]
@matthiasclasen How do you check 1) though? I mean, we can check the current list of mimetypes, but what if the host adds another one later, or if another flatpak later adds one and they conflict, which wins?

**Comment by matthiasclasen** [comment]
I guess the only realistic way to do that is to arrange for exported mime types to have a lower priority than system-provided ones.

**Comment by L0L022** [comment]
Or flatpak shows what the app installs (desktop file, icons, mimetypes) to the user and he should see if an icon looks like, for example: a pdf or a odt one.

**Comment by ximion** [comment]
@L0L022 I made very bad experience with that. If users install an app, they want to have it *now* and really don't care to ready any dialogs they throw at you. An "app requests these permissions" dialog is probably the maximum we can bother them with, asking them to compare icons or even requesting them to make a choice whether installing this mimetype is a good idea is too much.

**Comment by L0L022** [comment]
@ximion I think it's important to watch what the app does before the install with a "permissions dialog". If the user doesn't want, he can disable it.

**Comment by ZanderBrown** [comment]
Has there been any further discussion around this?

We seem to be able to register mime based on glob but not to provide an icon for it.

Whilst I see the concerns around applications spoofing things as more applications like LibreOffice are available it becomes increasingly relevant for mime type icons

**Comment by TingPing** [comment]
@ZanderBrown just modify the mime file to use an icon name with your app-id prefix. Simple as that.

**Comment by ZanderBrown** [comment]
Hmm, this doesn't seem to be documented anywhere.

Did lead me to notice I wasn't installing an icon to `mimetypes`, only `apps` which won't have been helping.

Interestingly `gio info` shows the file's icon as being that of my application but nautilus is falling back to a generic

**Comment by TingPing** [comment]
> Did lead me to notice I wasn't installing an icon to mimetypes, only apps which won't have been helping.

I don't think it actually matters, icons are referred to by name only it is just a logical organization on disk.

> Interestingly gio info shows the file's icon as being that of my application but nautilus is falling back to a generic

If the icon isn't exported, which again only happens if it matches your appid, then that would be logical.

**Comment by ZanderBrown** [comment]
It's definitely being exported, under `apps` & `minetypes`, and is found by the desktop file in the `apps` case, however, GIO/Gtk seems to skip to the fallback

**Comment by ZanderBrown** [comment]
Okay so it seems the value of `<generic-icon>` is used despite all indications that `<icon>` has higher priority, problem solved

**Comment by matthiasclasen** [comment]
seems this issue has been solved
