### ISSUE TITLE
Translations don't work for certain applications

### ISSUE THREAD

**Issue by AsavarTzeth** [flatpak/flatpak#981]
Some apps seem to experience issues with translations when they are packaged as a Flatpak. I have ruled out some of the common causes.

1. Verified that the required Locale extensions are indeed installed.
2. Verified that distribution packages, of the latest version, does not have this issue.

Apps that experience this issue:
- [Feedreader](https://github.com/flathub/org.gnome.FeedReader)
- [PulseEffects](https://github.com/flathub/com.github.wwmm.pulseeffects)

Things like GtkFileChooseDialog and On/Off buttons are translated as expected. But the application specific strings remain untranslated.

Not sure how to fix this and I cannot find any documentation on it. Since it only affects a few apps (only found 2 so far), I cannot rule out a packaging or application specific mistake. Anyhow, I have no clue on how to fix it. Any ideas on the cause?

**Comment by alexlarsson** [comment]
This is because those apps do not correctly initialize gettext for being installed in a prefix other than /usr.
They need to call bindtextdomain() with the right path, as described in:
https://developer.gnome.org/glib/stable/glib-I18N.html

Can you report these bugs upstream?

**Comment by AsavarTzeth** [comment]
Of course, now that I know what the issue is I would be happy to help.
