### ISSUE TITLE
Better handling of python *.pyo and *.pyc files

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#99]
These files seem to have a timestamp in them that make each rebuild different. This is pretty lame wrt reproducible builds, which is important for ostree deduplication. It also probably causes them to not work, because ostree doesn't store timestamps, so all checked out files will have mtime == 0.

**Comment by magcius** [comment]
Actually, the forcing mtime to 0 code was specifically added by us at Endless to handle the .pyc case.

https://bugzilla.gnome.org/show_bug.cgi?id=720363

**Comment by alexlarsson** [comment]
Fixed by https://github.com/flatpak/flatpak/commit/bd66da0dad92c0c0432cf35fcf137d4e5e35cf32
