### ISSUE TITLE
Is the flatpak hello-world tutorial outdated ?

### ISSUE THREAD

**Issue by kyrios123** [flatpak/flatpak#995]
Hello,

I just make a new package for `flatpack-builder` and I wanted to test it using the [hello wolrd tutorial](http://flatpak.org/hello-world.html), but I'm stuck at point 4. Looks like the init step is missing ?
```
flatpak build-export repo hello
error: Build directory hello not initialized, use flatpak build-init
```

**Comment by gjsman** [comment]
I need help with this too.

**Comment by mwleeds** [comment]
```
$ flatpak build-export repo hello
Commit: 738474f042f9e6eb53178e7d39fd9ca0b302599b16eed2e090936be6d92a0714
Metadata Total: 9
Metadata Written: 6
Content Total: 2
Content Written: 2
Content Bytes Written: 182 (182 bytes)
```

It works for me. @kyrios123 @gjsman perhaps you could post what version of flatpak you're using and the contents of `hello`.

**Comment by mwleeds** [comment]
If you're using `flatpak-builder` you shouldn't follow the Hello World tutorial. You can pass `--repo=DIR` to `flatpak-builder` and it will run `build-export` for you. See the [docs](http://docs.flatpak.org/en/latest/flatpak-builder.html#example).

**Comment by kyrios123** [comment]
thanks @mwleeds 😃 
I leave this issue open because  I guess the tutorial should be adapted to reflect this change.

**Comment by gjsman** [comment]
I am not using `flatpak-builder`, I am using the Hello World tutorial as it is.

**Comment by kyrios123** [comment]
@gjsman I guess that's because you're still using an old version of flatpack (prior to release 0.9.9)

**Comment by hfiguiere** [comment]
out of date.
