### ISSUE TITLE
CMake buildsystem: curl: Couldn't resolve host

### ISSUE THREAD

**Issue by a-andre** [flatpak/flatpak#996]
In my project I use CMake's external project which fetches repositories add build-time. This works without problems if flatpak is not involved. But with flatpak I get a `Couldn't resolve host` error.

```
* getaddrinfo(3) failed for github.com:443
* Couldn't resolve host 'github.com'
* Closing connection 0
curl: (6) Couldn't resolve host 'github.com'
```

To reproduce the issue create a local repository containing [CMakeLists.txt](https://github.com/flatpak/flatpak/files/1280712/CMakeLists.txt) and use [org.example.app.json](https://github.com/flatpak/flatpak/files/1280713/org.example.app.json.txt) to build it with `flatpak-builder --repo=repo directory org.example.app.json`.

I'm using flatpak 0.9.8.
I had the same problem with other flatpak runtimes and other CMake versions.

**Comment by TingPing** [comment]
Builds are sandboxed so you have to explicitly allow network access:

```json
      "build-options": {
        "build-args": [
          "--share=network"
        ]
      },
```

To say the obvious this is not recommended and build systems should never require network access.

**Comment by a-andre** [comment]
Thanks.

Is there way to detect network access and provide some helpful message about the situation?

**Comment by TingPing** [comment]
Not really? Any application trying to access the network will just fail.
