### ISSUE TITLE
Failed to install a flatpakref from flathub

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#998]
$ flatpak install --system --from https://flathub.org/repo/appstream/net.blockout.BlockOutII.flatpakref
This application depends on runtimes from:
  https://flathub.org/repo/
Configure this as new remote 'flathub' [y/n]: y

(flatpak install:19523): GLib-CRITICAL **: g_key_file_set_string: assertion 'string != NULL' failed
Installing: net.blockout.BlockOutII/x86_64/stable
Warning: Can't find dependencies: Remote "net.blockout.BlockOutII-origin" not found
Warning: Problem looking for related refs: Remote "net.blockout.BlockOutII-origin" not found
Installing: net.blockout.BlockOutII/x86_64/stable from net.blockout.BlockOutII-origin
error: Remote "net.blockout.BlockOutII-origin" not found

**Comment by alexlarsson** [comment]
What version is this, with master i get:
```
$ flatpak install --system --from https://flathub.org/repo/appstream/net.blockout.BlockOutII.flatpakref
The remote 'flathub', at location https://flathub.org/repo/ contains additional applications.
Do you want to install other applications from here? [y/n]: y
Installing: net.blockout.BlockOutII/x86_64/stable
Required runtime for net.blockout.BlockOutII/x86_64/stable (org.freedesktop.Platform/x86_64/1.6) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.freedesktop.Platform/x86_64/1.6 from flathub
[####################] 11 delta parts, 81 loose fetched; 140948 KiB transferred in 13 seconds
Installing: org.freedesktop.Platform.GL.nvidia-384-69/x86_64/1.4 from flathub
[####################] Downloading: 46,1 MB/46,1 MB (2,7 MB/s)   
Installing: org.freedesktop.Platform.Locale/x86_64/1.6 from flathub
[####################] 3 delta parts, 61 loose fetched; 26745 KiB transferred in 2 seconds
Installing: net.blockout.BlockOutII/x86_64/stable from flathub
[####################] 1 delta parts, 2 loose fetched; 4673 KiB transferred in 1 seconds

```

**Comment by matthiasclasen** [comment]
my mistake. I was in a jhbuild shell which had flatpak 0.9.8
